### ISSUE TITLE
[Node.js] Add changelog to the project

### ISSUE THREAD

**Issue by harshithkashyap** [Microsoft/AdaptiveCards#1006]
I'm looking at a couple of undocumented breaking changes and we need a changelog/release notes to follow them.

1. Looking at my package.json, the adaptive cards typescript SDK is pointing to ` "microsoft-adaptivecards": "0.6.1"` but it looks the npm package has been **renamed** to `"adaptivecards": "v1.0.0-beta9"` and I couldn't find any release notes/changelog regarding this.

2. HTML/JavaScript SDK also seems to have been changed in rendering the card. 
This is what I currently have:
```javascript
import * as AdaptiveCards from 'microsoft-adaptivecards';

AdaptiveCards.setHostConfig(hostConfig);
const adaptiveCard = new AdaptiveCards.AdaptiveCard();
adaptiveCard.parse(this.card);
const cardHtml = adaptiveCard.render();
// Append the cardHtml to DOM.
AdaptiveCards.AdaptiveCard.onExecuteAction = this.onExecuteAction.bind(this);
```

Looking at the [docs](https://docs.microsoft.com/en-us/adaptive-cards/display/libraries/htmlclient), `render` method has changed to `renderCard`. 
```javascript
const renderOptions = {
    hostConfig: hostConfig,
    onExecuteAction: this.onExecuteAction.bind(this)
};
const cardHtml = AdaptiveCards.renderCard(this.card, renderOptions);
```

3. `base.scss` also seems to be missing from `adaptivecards` npm package. It is available from  `microsoft-adaptivecards` npm package.

**Comment by matthidinger** [comment]
Hi @harshithkashyap, I'm really sorry about the lack of changelog. We will do better at this documentation as we get closer to 1.0.

1. Indeed the microsoft-adaptivecards has been deprecated and we're using this new name going forward.
2. The only change you should need to make in your above code is `setHostConfig()` is no longer a static function and is now a property on each `AdaptiveCard` - so you could do `adaptiveCard.hostConfig = hostConfig;` - do note however that HostConfig itself has also been going through some changes so you may have to tweak your property names. See our [sample host config](https://github.com/Microsoft/AdaptiveCards/blob/master/samples/v1.0/HostConfig/sample.json) for details.
3. The `renderCard` method is a helper for simple card rendering. If you were using `adaptiveCard.render()` as seen above that will continue to work.

4. I wasn't sure how/if folks were using `base.scss` in the wild so it's not currently in the npm package. Can you describe you usage and if it makes sense to keep it in the package I will make that addition.

Thanks again for reporting this, and you patience while we iron out the kinks!
(FYI I'm adding a breaking change notice to this top of [the docs page](https://docs.microsoft.com/en-us/adaptive-cards/display/libraries/htmlclient) which will be available later today)

**Comment by matthidinger** [comment]
As of our 1.0 release we've started including release notes and will continue in the future. Thanks again for your patience along the way!
