### ISSUE TITLE
[WPF] All Renderers Image background is colored

### ISSUE THREAD

**Issue by mrbrennonwilliams** [microsoft/AdaptiveCards#1007]
I was sure this was already any issue marked as fixed - couldnt find the issue # though. Please close if duplicate.

When rendering all cards with an image in WPF, we see that a blue background is rendered as part of the image container

![image](https://user-images.githubusercontent.com/32671341/33434020-d18adba6-d5d5-11e7-88db-020cadb69899.png)

**Comment by matthidinger** [comment]
Is this latest release, or from master? I notice a few other bugs in that screenshot that should he fixed too

**Comment by mrbrennonwilliams** [comment]
Its from master.

Which release are you referring to as latest and where is that located? I see a branch tag for beta09 but the build status for main says that WPF has a beta10.. When I go to that source, it says that beta10 is on master.

**Comment by matthidinger** [comment]
Hmm, those really seem out of date (for example, buttons are no longer blue by default).

Are you syncing to your forks master or **this** repos master? If you're working from your fork you need to `get fetch upstream` to keep your master fork in sync

https://help.github.com/articles/syncing-a-fork/

**Comment by mrbrennonwilliams** [comment]
Firstly, I think it is safe to say that I am GitHub challenged ;-)

I really don't understand the desktop or visual studio plugin process as they both say I am working on microsoft/AdaptiveCards master branch

After completely removing and recloning, I see the gray buttons but the renders are still accurate:

![image](https://user-images.githubusercontent.com/32671341/33448422-ebbb489e-d5fd-11e7-9de2-20e2843e3d4a.png)

I see this from time to time with image renders - this is the default rendering of the card

![image](https://user-images.githubusercontent.com/32671341/33448545-385de224-d5fe-11e7-9beb-f9ff31e7a056.png)


I think it actually has something to do with with Focus style applied by default to the image element that is generated by the WPF renderer. Shall take a look and report back

**Comment by mrbrennonwilliams** [comment]
I think this is going to be a proper pain.

From what I can see, the Listbox which the ImageSet element is, has a default ItemsContainer style applied from WPF.

This style contains a default MultiTrigger in the Template Setter, which has the conditions IsSelectionActive = false and IsSelected = true

You can see the same effect here, when an Image is selected and then a button is pressed to take the focus of the selected ImageSet item

![image](https://user-images.githubusercontent.com/32671341/33453106-54da64aa-d60c-11e7-8ca2-1f481a36bb6c.png)


To be honest, I think there are bigger issues to sort out and this should be pushed to vnext, where perhaps the render can have a default style added to the ImageSet Listbox in AdaptiveImageSetRenderer.cs, after the Factory has been newed up.

Thoughts?

**Comment by matthidinger** [comment]
Hmm yea. We could probably replace that ListView with something simpler, without selection, maybe an ItemsControl? I'm not in WPF land right now but if you've got the source cloned and want to give that a quick shot and report back I'd be happy to merge a PR if it works well

**Comment by mrbrennonwilliams** [comment]
I think this needs some more thought - itemscontrol is the way to go, but I believe it wont solve this issue.

I am most likely wrong, but I dont see a clean way of doing it at present. Rather than pollute what is there (and possibly introduce worse defects), it's an edge case that can be lived with at v1.

As far as I can see, It's WPF specific as opposed to all renderers,

Do you want to track it as debt?

**Comment by jonmill** [comment]
I don't believe this issue repros in the newest builds; please re-open if you find that is not the case. Thanks!
