### ISSUE TITLE
Card Background Image Size

### ISSUE THREAD

**Issue by mrbrennonwilliams** [Microsoft/AdaptiveCards#1008]
I was just thinking about specific card designs, and when I see this example

![image](https://user-images.githubusercontent.com/32671341/33434426-302cddac-d5d7-11e7-8d0c-a82bd311506e.png)

I am wondering how this is going to be created in the current specification.

If I specify a background image, the amount of the image (or the entire card size and height) is only shown based on the elements that are inside the card.

So if I only have a single textblock at the top, the rest of the image and the background is not shown like so

![image](https://user-images.githubusercontent.com/32671341/33444578-9544d328-d5f2-11e7-839c-a5ff5baf7292.png)

Is the idea being that the host will default the card size/height?

**Comment by dclaux** [comment]
The background image will always cover the entirety of the card. However, the card's height depends on the target host; in many cases (Teams and Outlook for instance) the card's height is determined by the card's content. For Timeline, the card's height is pre-defined and fixed.

I do not know how you produced the screenshot above, but I'm going to assume that the height of the rendered card isn't ever set to 100% of its parent container, which is why you would see the output you see.

**Comment by mrbrennonwilliams** [comment]
@dclaux - each one of those squares is the WPF renderer - so if there is an issue, it should be logged.

The very top image is just an example of what content providers will **want** to be able to do, so that is the issue in terms of meeting those requirements.

Another issue (not a bug) is that with the approach of scaling a background image to the entire body of a card, it doesnt take much to ruin a visual design. For example, a showcard extends the entire card, and all that scaling really turns things ugly - quickly.

**Comment by dclaux** [comment]
@mrbrennonwilliams what you want to be able to do you can do, but it depends whether or not the target hosts imposes fixed-height cards or not.

This payload
```
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"backgroundImage": "http://2.bp.blogspot.com/-kGPfxUo_mQU/UgDOW336h9I/AAAAAAAAADg/Btb3z_LBDMY/s1600/Beautiful+Sunrise+Wallpapers+%25283%2529.jpg",
	"version": "1.0",
	"body": [
		{
		    "type": "TextBlock",
		    "text": "**Hello world**"
		}
	]
}
```

will look like this in Timeline which does use fixed height cards:
![image](https://user-images.githubusercontent.com/1334689/33798219-8ebc756e-dcc9-11e7-93c0-ab40cb0fe03b.png)

but will look like this in Teams which uses cards that compute their height based on their content:
![image](https://user-images.githubusercontent.com/1334689/33798223-9db3b6e0-dcc9-11e7-9735-34e232ba8d69.png)

As for your comment on background images over the entire card, you are absolutely right that it doesn't take much to ruin things. But we also know that it's not really an option not to support it as so many scenarios need it.

**Comment by matthidinger** [comment]
Going to close this as it's currently working as designed. But we do have a feature proposal #1201 to specify the dimensions of a card, which would improve this scenario for fluid-height Hosts.
