### ISSUE TITLE
[WPF] Textblock alignment not applied

### ISSUE THREAD

**Issue by mrbrennonwilliams** [Microsoft/AdaptiveCards#1009]
In all cards here, you can see that the text is not right aligned

![image](https://user-images.githubusercontent.com/32671341/33444837-36a0af62-d5f3-11e7-8d9b-d63fcb4ff3a9.png)

`{
    "type": "AdaptiveCard",
    "version": "1.0",
    "id": "48a2077f-f1a3-4324-9c1a-9dc84a93c5b6",
    "minVersion": "1.0",
    "fallbackText": "",
    "speak": "",
    "backgroundImage": "http://www.jamies.london/wp-content/uploads/2016/12/our-wine-bars-wide-2300x994.jpg",
    "body": [
        {
            "type": "Container",
            "id": "936346ce-a227-4c25-a6ff-6eb03915a343",
            "items": [
                {
                    "type": "TextBlock",
                    "id": "8c16a1d1-b35f-477b-ac25-a7fd2fc5ba5e",
                    "size": "large",
                    "weight": "bolder",
                    "color": "light",
                    "text": "Come and experience the best wine bar that London has to offer",
                    "horizontalAlignment": "right",
                    "wrap": true,
                    "maxLines": 3
                }
            ]
        }
    ]
}`

**Comment by mrbrennonwilliams** [comment]
Actually, after inspecting this, I don't think my statement is accurate.

The Textblock is right aligned, but the text content is not right aligned.

Is this property meant to imply that the content should also be right aligned, or should there be a separate property for content alignment?

I do think it will be a common requirement to have text alignment which may also tie in with issue #999

**Comment by dclaux** [comment]
HorizontalAlignment for TextBlock controls the text justification as well as the position of the overall bounding box. See example below.

```
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "TextBlock",
			"text": "**Left aligned:** Now that we have defined the main rules and features of the format, we need to produce a schema and publish it to GitHub. The schema will be the starting point of our reference documentation.",
			"horizontalAlignment": "right",
			"wrap": true
		},
		{
			"type": "TextBlock",
			"text": "**Centered:** Now that we have defined the main rules and features of the format, we need to produce a schema and publish it to GitHub. The schema will be the starting point of our reference documentation.",
			"horizontalAlignment": "center",
			"wrap": true
		},
		{
			"type": "TextBlock",
			"text": "**Right aligned:** Now that we have defined the main rules and features of the format, we need to produce a schema and publish it to GitHub. The schema will be the starting point of our reference documentation.",
			"horizontalAlignment": "right",
			"wrap": true
		}
	]
}
```

As rendered:
![image](https://user-images.githubusercontent.com/1334689/33785698-15a5a0f0-dc1b-11e7-9fdb-722955498779.png)

**Comment by mrbrennonwilliams** [comment]
@dclaux - the images I provide you are always derived from the WPF renderer. They are not modified by me. So the images shown above very clearly show that the textblock content is not right aligned.

My initial issue title was incorrect, which I added another comment to clarify.

Sorry if I am not making it clear enough, that right aligned text is what I am expecting.

This image is taken from the WPF visualiser - showing that the text is not right aligned. 
![image](https://user-images.githubusercontent.com/32671341/33787251-5b30568a-dc64-11e7-92b0-b8b70182f8fa.png)


This is the web visualiser, and in my view, correctly renders it. So one of them is wrong.
![image](https://user-images.githubusercontent.com/32671341/33787374-d83b45f4-dc64-11e7-9391-81c0698defff.png)

**Comment by dclaux** [comment]
@mrbrennonwilliams I had actually understood you (I think) :) What I was saying is thata there seems to be a bug in the WPF renderer.
