### ISSUE TITLE
[WEB] Textblock color not applied

### ISSUE THREAD

**Issue by mrbrennonwilliams** [Microsoft/AdaptiveCards#1010]
In the following snippet we get this visualisation which shows the text barely visible when it is specified as light

![image](https://user-images.githubusercontent.com/32671341/33445004-a85b7858-d5f3-11e7-8e59-0b4de9787844.png)

`{
    "type": "AdaptiveCard",
    "version": "1.0",
    "id": "48a2077f-f1a3-4324-9c1a-9dc84a93c5b6",
    "minVersion": "1.0",
    "fallbackText": "",
    "speak": "",
    "backgroundImage": "http://www.jamies.london/wp-content/uploads/2016/12/our-wine-bars-wide-2300x994.jpg",
    "body": [
        {
            "type": "Container",
            "id": "936346ce-a227-4c25-a6ff-6eb03915a343",
            "items": [
                {
                    "type": "TextBlock",
                    "id": "8c16a1d1-b35f-477b-ac25-a7fd2fc5ba5e",
                    "size": "large",
                    "weight": "bolder",
                    "color": "light",
                    "text": "Come and experience the best wine bar that London has to offer",
                    "horizontalAlignment": "right",
                    "wrap": true,
                    "maxLines": 3
                }
            ]
        }
    ]
}`

**Comment by matthidinger** [comment]
@dclaux seems `color: "light"` isn't working properly

**Comment by dclaux** [comment]
That's because there is no light (or dark) color anymore. It's not really compatible with container styles.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by matthidinger** [comment]
I thought after we talked about that need for them in backgroundImage we agreed to keep them? light/dark is necessary for proper rendering on a background image (as seen above)

**Comment by dclaux** [comment]
(I had responded to this from email earlier but apparently it didn't go through.)

You are correct @matthidinger  - I had just forgotten.

[I have a PR](https://github.com/Microsoft/AdaptiveCards/pull/998/) ready which reintroduces the dark and light colors.

Because the PR also updates the schema, I will wait until you and @danmarshall have a chance to review it.

**Comment by dclaux** [comment]
The change has been reviewed and approved. It's now merged in master.

**Comment by mrbrennonwilliams** [comment]
@dclaux  nice one

**Comment by dclaux** [comment]
You are correct, I forgot. I will add them back today.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
