### ISSUE TITLE
Provide change log for official and beta releases

### ISSUE THREAD

**Issue by robinsedlaczek** [microsoft/AdaptiveCards#1011]
I know that there is no final official version released yet, so I assume that there will be a change log or the release notes for official versions (e.g. for the upcoming 1.0). For now, there are no notes or logs. But as an adaptor of beta releases, it is important for me to know the changes that were released, also in beta versions.

As a beta adaptor I want to have change logs, at least when NuGet packages are updated, in order to detect and identify problems in own code early as well as to avoid being misleaded by changed behavior. And last but not least, to provide feedback to this project as soon as possible. Please provide a change log per tag and/or release.

[Tag for v1.0.0-beta1](https://github.com/Microsoft/AdaptiveCards/releases/tag/v1.0.0-beta1) points to [release announcements](https://github.com/Microsoft/AdaptiveCards/wiki/Announcing-v1.0-Beta), but both sections are not really maintained or up-to-date.

**Comment by ederbond** [comment]
I miss that too.
