### ISSUE TITLE
[WPF] Image element in Container renders with white background

### ISSUE THREAD

**Issue by mrbrennonwilliams** [microsoft/AdaptiveCards#1017]
In this image, the card has a background - the white box is actually an image element with the same image shown below the white box. I should just be seeing two images here

![image](https://user-images.githubusercontent.com/32671341/33486536-62ef0096-d6a2-11e7-9e20-a20cdbc54168.png)

`{
    "type": "AdaptiveCard",
    "version": "1.0",
    "id": "4a0721fb-6143-4941-94e5-ae50ce9e4e87",
    "minVersion": "1.0",
    "fallbackText": "",
    "speak": "",
    "backgroundImage": "https://goo.gl/eYUNCW",
    "body": [
        {
            "type": "Container",
            "id": "61f335d3-6b64-4c68-8a7b-b71d262d040b",
            "items": [
                {
                    "type": "Image",
                    "id": "e875cd7a-ef50-425c-b52d-81e8f91fe67f",
                    "size": "medium",
                    "url": "https://goo.gl/FynjUB",
                    "altText": ""
                }
            ]
        },
        {
            "type": "ColumnSet",
            "id": "93967c2b-fd15-495e-808e-e7ab98511c00",
            "columns": [
                {
                    "type": "Column",
                    "id": "05df09a6-c6d9-43b9-9dbf-307b672f4099",
                    "width": "auto",
                    "items": [
                        {
                            "type": "Image",
                            "id": "10d08b1a-88f8-430a-9ba1-c8c1d327bbfd",
                            "url": "https://goo.gl/FynjUB",
                            "altText": ""
                        }
                    ]
                }
            ]
        }
    ]
}`

**Comment by jonmill** [comment]
This issue should be fixed in the latest builds; please re-open if you find that is not the case. Thanks!
