### ISSUE TITLE
[WPF] Column Stretch - child elements 

### ISSUE THREAD

**Issue by mrbrennonwilliams** [microsoft/AdaptiveCards#1018]
I was looking at an image element set to stretch, inside a column that is set to stretch.

![image](https://user-images.githubusercontent.com/32671341/33486834-3f5dfaf0-d6a3-11e7-9d49-5e60cc817193.png)

The image should fill the column as is the case with the web visualizer

`{
    "type": "AdaptiveCard",
    "version": "1.0",
    "id": "4a0721fb-6143-4941-94e5-ae50ce9e4e87",
    "minVersion": "1.0",
    "fallbackText": "",
    "speak": "",
    "backgroundImage": "https://goo.gl/eYUNCW",
    "body": [
        {
            "type": "ColumnSet",
            "id": "93967c2b-fd15-495e-808e-e7ab98511c00",
            "columns": [
                {
                    "type": "Column",
                    "id": "05df09a6-c6d9-43b9-9dbf-307b672f4099",
                    "width": "stretch",
                    "items": [
                        {
                            "type": "Image",
                            "id": "10d08b1a-88f8-430a-9ba1-c8c1d327bbfd",
                            "size": "stretch",
                            "url": "https://goo.gl/FynjUB",
                            "altText": ""
                        }
                    ]
                }
            ]
        }
    ]
}`

**Comment by shalinijoshi19** [comment]
@almedina-ms is this something that is still repro'ing on WPF with 1.2 payload? Does the minHeight change address this on WPF at all? @matthidinger / @dclaux / @andrewleader thoughts?

**Comment by jonmill** [comment]
This should be fixed in the latest builds; please re-open if you find that is not the case. Thanks!
