### ISSUE TITLE
[WPF] Container non-default spacing adds "separation" back as a property

### ISSUE THREAD

**Issue by mrbrennonwilliams** [Microsoft/AdaptiveCards#1021]
If you set spacing on a container to anything other than "default", adaptive cards adds a "separation" property back which is obsolete

**Comment by almedina-ms** [comment]
I think this was solved in this PR: https://github.com/Microsoft/AdaptiveCards/pull/2200

**Comment by almedina-ms** [comment]
Also in this one: https://github.com/Microsoft/AdaptiveCards/pull/2202
