### ISSUE TITLE
[WEB] Vast differences in card rendered size

### ISSUE THREAD

**Issue by mrbrennonwilliams** [Microsoft/AdaptiveCards#1024]
The included JSON creates several different size cards when using the web visualiser. 

I would expect the card to look the same on all platforms, merely transformed to a smaller space if the card boundaries in terms of overall size are fixed

(The font color issue is already noted, but the fonts should be white.)

**TEAMS - MASSIVE CARD**
![image](https://user-images.githubusercontent.com/32671341/33566007-a3c8bb72-d916-11e7-9baa-ff2d53d09f03.png)

**TIMELINE - CUT OFF CARD**
![image](https://user-images.githubusercontent.com/32671341/33566045-c26d46d8-d916-11e7-9a97-e48efe61f569.png)

**SKYPE - RIGHT SIDE OF CARD TRUNCATED**
![image](https://user-images.githubusercontent.com/32671341/33566071-d852b6f4-d916-11e7-9344-bb61ea0ec41a.png)

`{
    "type": "AdaptiveCard",
    "version": "1.0",
    "id": "4a0721fb-6143-4941-94e5-ae50ce9e4e87",
    "minVersion": "1.0",
    "fallbackText": "",
    "speak": "",
    "backgroundImage": "https://goo.gl/eYUNCW",
    "body": [
        {
            "type": "ColumnSet",
            "id": "93967c2b-fd15-495e-808e-e7ab98511c00",
            "columns": [
                {
                    "type": "Column",
                    "id": "2e817002-808e-4b9d-a299-d198cde16e03",
                    "width": "1",
                    "items": [
                        
                    ]
                },
                {
                    "type": "Column",
                    "id": "05df09a6-c6d9-43b9-9dbf-307b672f4099",
                    "width": "5",
                    "items": [
                        {
                            "type": "Image",
                            "id": "10d08b1a-88f8-430a-9ba1-c8c1d327bbfd",
                            "size": "stretch",
                            "url": "https://goo.gl/FynjUB",
                            "horizontalAlignment": "center",
                            "altText": ""
                        }
                    ]
                },
                {
                    "type": "Column",
                    "id": "704d773e-1ff9-47bb-9fd8-e580fd63fc67",
                    "width": "1",
                    "items": [
                        {
                            "type": "TextBlock",
                            "id": "62492e35-81e8-4639-a2b0-c7ca4212ebc4",
                            "weight": "bolder",
                            "color": "light",
                            "text": "Sunday",
                            "maxLines": 1
                        },
                        {
                            "type": "TextBlock",
                            "id": "201f7c09-811a-4ad9-a7b6-81b96d388acc",
                            "size": "extraLarge",
                            "color": "light",
                            "text": "19 °C",
                            "maxLines": 1
                        },
                        {
                            "type": "TextBlock",
                            "id": "b4f975d1-2c37-4da4-b1ee-3ef54d582c98",
                            "color": "light",
                            "isSubtle": true,
                            "text": "London",
                            "maxLines": 1
                        }
                    ]
                }
            ],
            "selectAction": {
                "type": "Action.OpenUrl",
                "url": "http://www.google.com",
                "title": "Open more weather"
            }
        },
        {
            "type": "TextBlock",
            "id": "d30a1a28-ff21-426b-b175-2afc79f89941",
            "size": "large",
            "weight": "bolder",
            "color": "light",
            "text": "PARTLY CLOUDY",
            "horizontalAlignment": "center",
            "maxLines": 1
        },
        {
            "type": "ColumnSet",
            "id": "d05583aa-3290-4a04-9e1a-3de0cde8401c",
            "columns": [
                {
                    "type": "Column",
                    "id": "96f3a864-18a0-4acd-8df5-181763305445",
                    "width": "1",
                    "items": [
                        
                    ]
                },
                {
                    "type": "Column",
                    "id": "6bfe91c2-8740-41cd-9ac3-724865fc08aa",
                    "width": "2",
                    "items": [
                        {
                            "type": "Image",
                            "id": "cb3c430f-bb36-4467-ad5d-b9368e97d7b1",
                            "size": "small",
                            "url": "https://goo.gl/g5Surp",
                            "horizontalAlignment": "center",
                            "selectAction": {
                                "type": "Action.OpenUrl",
                                "url": "http://localhost/",
                                "title": ""
                            },
                            "altText": ""
                        },
                        {
                            "type": "TextBlock",
                            "id": "8b8ef2f9-c4c0-4add-8dd9-dde49717a0fd",
                            "size": "small",
                            "weight": "bolder",
                            "color": "light",
                            "text": "CLEAR",
                            "horizontalAlignment": "center",
                            "maxLines": 1
                        }
                    ]
                },
                {
                    "type": "Column",
                    "id": "b82af09c-c9e2-4878-9df7-d996de418cc1",
                    "width": "2",
                    "items": [
                        {
                            "type": "Image",
                            "id": "b88e158c-228e-49be-a9c6-5d9d5816d329",
                            "size": "small",
                            "url": "https://goo.gl/AWRgLC",
                            "horizontalAlignment": "center",
                            "altText": ""
                        },
                        {
                            "type": "TextBlock",
                            "id": "5048a27e-aa7e-43a7-8d36-bb697cafcbf8",
                            "size": "small",
                            "weight": "bolder",
                            "color": "light",
                            "text": "CLOUDY",
                            "horizontalAlignment": "center",
                            "maxLines": 1
                        }
                    ]
                },
                {
                    "type": "Column",
                    "id": "e1850e8e-b90f-4fdc-a60f-f41a66846510",
                    "width": "2",
                    "items": [
                        {
                            "type": "Image",
                            "id": "304761fc-a9dd-495d-ab4e-1d6f340660ae",
                            "size": "small",
                            "url": "https://goo.gl/ttUfbx",
                            "horizontalAlignment": "center",
                            "altText": ""
                        },
                        {
                            "type": "TextBlock",
                            "id": "29a8521b-0a2b-4023-9919-2b15fc62bd4e",
                            "size": "small",
                            "weight": "bolder",
                            "color": "light",
                            "text": "STORM",
                            "horizontalAlignment": "center",
                            "maxLines": 1
                        }
                    ]
                },
                {
                    "type": "Column",
                    "id": "81d65875-02e5-4e33-8bc9-b713760f77c3",
                    "width": "2",
                    "items": [
                        {
                            "type": "Image",
                            "id": "db19181e-9882-4ff1-a5b5-6577b80c1655",
                            "size": "small",
                            "url": "https://goo.gl/vWVmuL",
                            "horizontalAlignment": "center",
                            "altText": ""
                        },
                        {
                            "type": "TextBlock",
                            "id": "920298d3-2799-4bb0-b95f-92ae020643fa",
                            "size": "small",
                            "weight": "bolder",
                            "color": "light",
                            "text": "SNOW",
                            "horizontalAlignment": "center",
                            "maxLines": 1
                        }
                    ]
                },
                {
                    "type": "Column",
                    "id": "667fe0fb-44bc-4a45-84bc-2528f629886e",
                    "width": "2",
                    "items": [
                        {
                            "type": "Image",
                            "id": "3d7bcfd9-4b74-49e9-bb2c-203bcaad0225",
                            "size": "small",
                            "url": "https://goo.gl/LC6GHg",
                            "horizontalAlignment": "center",
                            "altText": ""
                        },
                        {
                            "type": "TextBlock",
                            "id": "6e421614-0e63-4148-a87b-45881610d09c",
                            "size": "small",
                            "weight": "bolder",
                            "color": "light",
                            "text": "RAIN",
                            "horizontalAlignment": "center",
                            "maxLines": 1
                        }
                    ]
                },
                {
                    "type": "Column",
                    "id": "83bf3dda-2df0-4792-8b86-0b2f04957b4e",
                    "width": "1",
                    "items": [
                        
                    ]
                }
            ],
            "spacing": "extraLarge"
        }
    ]
}`

**Comment by dclaux** [comment]
@mrbrennonwilliams there are two things to consider here (3 if you include the font color problem, but the fix for that is in already):
- I don't think the card is necessarily designed the right way. The main issue is that the big image is stealing the space the text at the top right needs. Redesigning the card slightly differently can solve that problem. Below is a slightly modified version of your payload - not a recommendation for what you should do but more an illustration on how to set the columns' with and use horizontalAlignment on the ColumnSet rather than using an empty first column
- Teams and Skype use variable-height cards, e.g. the height of the card is controlled by its content. Timeline, however, uses a fixes-height card. The only solution for a single card to look great on all these hosts would be to design it for the most constraining one, namely Timeline. But then, the card would not be as big and nice as you might want it to be on other hosts that do not use fixed-height cards. Adaptive does not provide automatic adjustment of a card when it height is constrained.

```
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "id": "4a0721fb-6143-4941-94e5-ae50ce9e4e87",
    "minVersion": "1.0",
    "fallbackText": "",
    "speak": "",
    "backgroundImage": "https://goo.gl/eYUNCW",
    "body": [
        {
            "type": "ColumnSet",
            "id": "93967c2b-fd15-495e-808e-e7ab98511c00",
            "horizontalAlignment": "center",
            "columns": [
                {
                    "type": "Column",
                    "id": "05df09a6-c6d9-43b9-9dbf-307b672f4099",
                    "width": "auto",
                    "items": [
                        {
                            "type": "Image",
                            "id": "10d08b1a-88f8-430a-9ba1-c8c1d327bbfd",
                            "size": "stretch",
                            "url": "https://goo.gl/FynjUB",
                            "horizontalAlignment": "center",
                            "altText": ""
                        }
                    ]
                },
                {
                    "type": "Column",
                    "id": "704d773e-1ff9-47bb-9fd8-e580fd63fc67",
                    "width": "auto",
                    "verticalContentAlignment": "center",
                    "spacing": "large",
                    "items": [
                        {
                            "type": "TextBlock",
                            "id": "62492e35-81e8-4639-a2b0-c7ca4212ebc4",
                            "weight": "bolder",
                            "color": "light",
                            "text": "Sunday",
                            "maxLines": 1
                        },
                        {
                            "type": "TextBlock",
                            "id": "201f7c09-811a-4ad9-a7b6-81b96d388acc",
                            "size": "extraLarge",
                            "color": "light",
                            "text": "19 °C",
                            "maxLines": 1,
                            "spacing": "none"
                        },
                        {
                            "type": "TextBlock",
                            "id": "b4f975d1-2c37-4da4-b1ee-3ef54d582c98",
                            "color": "light",
                            "text": "London",
                            "maxLines": 1,
                            "spacing": "none"
                        }
                    ]
                }
            ],
            "selectAction": {
                "type": "Action.OpenUrl",
                "url": "http://www.google.com",
                "title": "Open more weather"
            }
        },
        {
            "type": "TextBlock",
            "id": "d30a1a28-ff21-426b-b175-2afc79f89941",
            "size": "large",
            "weight": "bolder",
            "color": "light",
            "text": "PARTLY CLOUDY",
            "horizontalAlignment": "center",
            "maxLines": 1
        },
        {
            "type": "ColumnSet",
            "id": "d05583aa-3290-4a04-9e1a-3de0cde8401c",
            "columns": [
                {
                    "type": "Column",
                    "id": "96f3a864-18a0-4acd-8df5-181763305445",
                    "width": "1",
                    "items": [
                        
                    ]
                },
                {
                    "type": "Column",
                    "id": "6bfe91c2-8740-41cd-9ac3-724865fc08aa",
                    "width": "2",
                    "items": [
                        {
                            "type": "Image",
                            "id": "cb3c430f-bb36-4467-ad5d-b9368e97d7b1",
                            "size": "small",
                            "url": "https://goo.gl/g5Surp",
                            "horizontalAlignment": "center",
                            "selectAction": {
                                "type": "Action.OpenUrl",
                                "url": "http://localhost/",
                                "title": ""
                            },
                            "altText": ""
                        },
                        {
                            "type": "TextBlock",
                            "id": "8b8ef2f9-c4c0-4add-8dd9-dde49717a0fd",
                            "size": "small",
                            "weight": "bolder",
                            "color": "light",
                            "text": "CLEAR",
                            "horizontalAlignment": "center",
                            "maxLines": 1
                        }
                    ]
                },
                {
                    "type": "Column",
                    "id": "b82af09c-c9e2-4878-9df7-d996de418cc1",
                    "width": "2",
                    "items": [
                        {
                            "type": "Image",
                            "id": "b88e158c-228e-49be-a9c6-5d9d5816d329",
                            "size": "small",
                            "url": "https://goo.gl/AWRgLC",
                            "horizontalAlignment": "center",
                            "altText": ""
                        },
                        {
                            "type": "TextBlock",
                            "id": "5048a27e-aa7e-43a7-8d36-bb697cafcbf8",
                            "size": "small",
                            "weight": "bolder",
                            "color": "light",
                            "text": "CLOUDY",
                            "horizontalAlignment": "center",
                            "maxLines": 1
                        }
                    ]
                },
                {
                    "type": "Column",
                    "id": "e1850e8e-b90f-4fdc-a60f-f41a66846510",
                    "width": "2",
                    "items": [
                        {
                            "type": "Image",
                            "id": "304761fc-a9dd-495d-ab4e-1d6f340660ae",
                            "size": "small",
                            "url": "https://goo.gl/ttUfbx",
                            "horizontalAlignment": "center",
                            "altText": ""
                        },
                        {
                            "type": "TextBlock",
                            "id": "29a8521b-0a2b-4023-9919-2b15fc62bd4e",
                            "size": "small",
                            "weight": "bolder",
                            "color": "light",
                            "text": "STORM",
                            "horizontalAlignment": "center",
                            "maxLines": 1
                        }
                    ]
                },
                {
                    "type": "Column",
                    "id": "81d65875-02e5-4e33-8bc9-b713760f77c3",
                    "width": "2",
                    "items": [
                        {
                            "type": "Image",
                            "id": "db19181e-9882-4ff1-a5b5-6577b80c1655",
                            "size": "small",
                            "url": "https://goo.gl/vWVmuL",
                            "horizontalAlignment": "center",
                            "altText": ""
                        },
                        {
                            "type": "TextBlock",
                            "id": "920298d3-2799-4bb0-b95f-92ae020643fa",
                            "size": "small",
                            "weight": "bolder",
                            "color": "light",
                            "text": "SNOW",
                            "horizontalAlignment": "center",
                            "maxLines": 1
                        }
                    ]
                },
                {
                    "type": "Column",
                    "id": "667fe0fb-44bc-4a45-84bc-2528f629886e",
                    "width": "2",
                    "items": [
                        {
                            "type": "Image",
                            "id": "3d7bcfd9-4b74-49e9-bb2c-203bcaad0225",
                            "size": "small",
                            "url": "https://goo.gl/LC6GHg",
                            "horizontalAlignment": "center",
                            "altText": ""
                        },
                        {
                            "type": "TextBlock",
                            "id": "6e421614-0e63-4148-a87b-45881610d09c",
                            "size": "small",
                            "weight": "bolder",
                            "color": "light",
                            "text": "RAIN",
                            "horizontalAlignment": "center",
                            "maxLines": 1
                        }
                    ]
                },
                {
                    "type": "Column",
                    "id": "83bf3dda-2df0-4792-8b86-0b2f04957b4e",
                    "width": "1",
                    "items": [
                        
                    ]
                }
            ],
            "spacing": "extraLarge"
        }
    ]
}
```

**Comment by mrbrennonwilliams** [comment]
Thanks for your response @dclaux 

> I don't think the card is necessarily designed the right way

Your result is not inline with the original design of the card. The images and text are positioned specifically for information flow.

That is going to be an issue, because in particular, UX designers can and do become quite anal about layout and positioning of text elements with respect to information architecture.

If we are going to say that that there is a "right" and "wrong" way to design cards - then a comprehensive design guideline needs to be created.

With respect to the card heights - while I can understand that, it goes against the USP of adaptive cards where content is provided and the host will adapt to handle the layout.

Yes it's V1 - but moving forward, this type of scenario should be debated to understand what use cases the constraints will have.

It's all a bit of a rabbit hole...

**Comment by dclaux** [comment]
@mrbrennonwilliams unfortunately I don't know what the card is supposed to look like, so I just came up with an illustration of how to use various properties to achieve a specific result (I focused on centering the image and the text on its right as well as making sure the text wasn't truncated.)

If you give me a screenshot of what the card is supposed to look like, I can look into it further.

I really didn't mean to say that there is a "right" way and a "wrong" way, sorry for using the wrong words. Adaptive is designed so that designers can actually achieve what they want - there are still compromises, but overall they should be minimal.

Again, if you don't mind sharing a screenshot of the desired card, I can try and figure out the best way to achieve it with Adaptive, and maybe identify what might be missing from Adaptive that we might want to consider for v1.1 or later.

**Comment by dclaux** [comment]
Here is another version that is probably much closer to what you want to achieve and scales properly (horizontally). Again it's all about picking the right column and image sizing strategy. Note however that the main image is scaled up in both cases, which I don't imagine would be acceptable (and also why in the first version I sent I had it auto-size):
```
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "id": "4a0721fb-6143-4941-94e5-ae50ce9e4e87",
    "minVersion": "1.0",
    "fallbackText": "",
    "speak": "",
    "backgroundImage": "https://goo.gl/eYUNCW",
    "body": [
        {
            "type": "ColumnSet",
            "id": "93967c2b-fd15-495e-808e-e7ab98511c00",
            "horizontalAlignment": "center",
            "columns": [
                {
                    "type": "Column",
                    "id": "05df09a6-c6d9-43b9-9dbf-307b672f4099",
                    "width": "stretch",
                    "items": [
                        {
                            "type": "Image",
                            "size": "stretch",
                            "id": "10d08b1a-88f8-430a-9ba1-c8c1d327bbfd",
                            "url": "https://goo.gl/FynjUB",
                            "altText": ""
                        }
                    ]
                },
                {
                    "type": "Column",
                    "id": "704d773e-1ff9-47bb-9fd8-e580fd63fc67",
                    "width": "auto",
                    "spacing": "small",
                    "items": [
                        {
                            "type": "TextBlock",
                            "id": "62492e35-81e8-4639-a2b0-c7ca4212ebc4",
                            "horizontalAlignment": "right",
                            "weight": "bolder",
                            "color": "light",
                            "text": "Sunday",
                            "maxLines": 1
                        },
                        {
                            "type": "TextBlock",
                            "id": "201f7c09-811a-4ad9-a7b6-81b96d388acc",
                            "horizontalAlignment": "right",
                            "size": "extraLarge",
                            "color": "light",
                            "text": "19 °C",
                            "maxLines": 1,
                            "spacing": "none"
                        },
                        {
                            "type": "TextBlock",
                            "id": "b4f975d1-2c37-4da4-b1ee-3ef54d582c98",
                            "horizontalAlignment": "right",
                            "color": "light",
                            "text": "London",
                            "maxLines": 1,
                            "spacing": "none"
                        }
                    ]
                }
            ],
            "selectAction": {
                "type": "Action.OpenUrl",
                "url": "http://www.google.com",
                "title": "Open more weather"
            }
        },
        {
            "type": "TextBlock",
            "id": "d30a1a28-ff21-426b-b175-2afc79f89941",
            "size": "large",
            "weight": "bolder",
            "color": "light",
            "text": "PARTLY CLOUDY",
            "horizontalAlignment": "center",
            "maxLines": 1
        },
        {
            "type": "ColumnSet",
            "id": "d05583aa-3290-4a04-9e1a-3de0cde8401c",
            "columns": [
                {
                    "type": "Column",
                    "id": "96f3a864-18a0-4acd-8df5-181763305445",
                    "width": "1",
                    "items": [
                        
                    ]
                },
                {
                    "type": "Column",
                    "id": "6bfe91c2-8740-41cd-9ac3-724865fc08aa",
                    "width": "2",
                    "items": [
                        {
                            "type": "Image",
                            "id": "cb3c430f-bb36-4467-ad5d-b9368e97d7b1",
                            "size": "small",
                            "url": "https://goo.gl/g5Surp",
                            "horizontalAlignment": "center",
                            "selectAction": {
                                "type": "Action.OpenUrl",
                                "url": "http://localhost/",
                                "title": ""
                            },
                            "altText": ""
                        },
                        {
                            "type": "TextBlock",
                            "id": "8b8ef2f9-c4c0-4add-8dd9-dde49717a0fd",
                            "size": "small",
                            "weight": "bolder",
                            "color": "light",
                            "text": "CLEAR",
                            "horizontalAlignment": "center",
                            "maxLines": 1
                        }
                    ]
                },
                {
                    "type": "Column",
                    "id": "b82af09c-c9e2-4878-9df7-d996de418cc1",
                    "width": "2",
                    "items": [
                        {
                            "type": "Image",
                            "id": "b88e158c-228e-49be-a9c6-5d9d5816d329",
                            "size": "small",
                            "url": "https://goo.gl/AWRgLC",
                            "horizontalAlignment": "center",
                            "altText": ""
                        },
                        {
                            "type": "TextBlock",
                            "id": "5048a27e-aa7e-43a7-8d36-bb697cafcbf8",
                            "size": "small",
                            "weight": "bolder",
                            "color": "light",
                            "text": "CLOUDY",
                            "horizontalAlignment": "center",
                            "maxLines": 1
                        }
                    ]
                },
                {
                    "type": "Column",
                    "id": "e1850e8e-b90f-4fdc-a60f-f41a66846510",
                    "width": "2",
                    "items": [
                        {
                            "type": "Image",
                            "id": "304761fc-a9dd-495d-ab4e-1d6f340660ae",
                            "size": "small",
                            "url": "https://goo.gl/ttUfbx",
                            "horizontalAlignment": "center",
                            "altText": ""
                        },
                        {
                            "type": "TextBlock",
                            "id": "29a8521b-0a2b-4023-9919-2b15fc62bd4e",
                            "size": "small",
                            "weight": "bolder",
                            "color": "light",
                            "text": "STORM",
                            "horizontalAlignment": "center",
                            "maxLines": 1
                        }
                    ]
                },
                {
                    "type": "Column",
                    "id": "81d65875-02e5-4e33-8bc9-b713760f77c3",
                    "width": "2",
                    "items": [
                        {
                            "type": "Image",
                            "id": "db19181e-9882-4ff1-a5b5-6577b80c1655",
                            "size": "small",
                            "url": "https://goo.gl/vWVmuL",
                            "horizontalAlignment": "center",
                            "altText": ""
                        },
                        {
                            "type": "TextBlock",
                            "id": "920298d3-2799-4bb0-b95f-92ae020643fa",
                            "size": "small",
                            "weight": "bolder",
                            "color": "light",
                            "text": "SNOW",
                            "horizontalAlignment": "center",
                            "maxLines": 1
                        }
                    ]
                },
                {
                    "type": "Column",
                    "id": "667fe0fb-44bc-4a45-84bc-2528f629886e",
                    "width": "2",
                    "items": [
                        {
                            "type": "Image",
                            "id": "3d7bcfd9-4b74-49e9-bb2c-203bcaad0225",
                            "size": "small",
                            "url": "https://goo.gl/LC6GHg",
                            "horizontalAlignment": "center",
                            "altText": ""
                        },
                        {
                            "type": "TextBlock",
                            "id": "6e421614-0e63-4148-a87b-45881610d09c",
                            "size": "small",
                            "weight": "bolder",
                            "color": "light",
                            "text": "RAIN",
                            "horizontalAlignment": "center",
                            "maxLines": 1
                        }
                    ]
                },
                {
                    "type": "Column",
                    "id": "83bf3dda-2df0-4792-8b86-0b2f04957b4e",
                    "width": "1",
                    "items": [
                        
                    ]
                }
            ],
            "spacing": "extraLarge"
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/1334689/33569804-baa6b484-d8df-11e7-8a0b-d2a758a10a5b.png)

![image](https://user-images.githubusercontent.com/1334689/33569826-c4b656be-d8df-11e7-9d10-5be0f079146b.png)

**Comment by dclaux** [comment]
By the way, what should the card look like in the fixed-height Timeline container?

**Comment by mrbrennonwilliams** [comment]
Hey @dclaux all good ;-)

So here is the render achieved in WPF
![image](https://user-images.githubusercontent.com/32671341/33570072-96805bca-d923-11e7-828e-2bf642cb6fde.png)

A number of the web renderers get it correct.

I also had another thought, that this could be related (in the WPF scenario) to the issue #1018 around WPF image element render sizes on the card. I remember building this card and initially added the image element to a container, but it wouldnt scale correctly.

The text on the right hand side was an after thought - in which case I needed the columnset to balance everything.

**Comment by dclaux** [comment]
I'm a bit confused :) Is the image supposed to be displayed as above (e.g. at its native size smaller and centered) or stretched out like in the first screenshot you provided?

Note that I am not sure the WPF renderer is up to date. The reference in terms of layout at this point is the Web renderer.

**Comment by dclaux** [comment]
Sorry, I should have read the issue you pointed to - it appears the image is supposed to be stretched, which is what the payload I sent you does.

**Comment by mrbrennonwilliams** [comment]
@dclaux - The [web] bot framework renderers do what I would expect
![image](https://user-images.githubusercontent.com/32671341/33570619-4bfebca2-d925-11e7-8d02-fdbce0d65989.png)

I think the fixed height is a real challenge. I guess ultimately I wanted the effect of a WPF ViewBox to scale the child elements - but that really isn't realistic for the other platforms - and I'm quite sure you and everyone else would throw stones at me if I suggest it!

Perhaps a thought:
Related to #967 

With my designer, could we get a list of fixed card sizes for those hosts that have them, and then I can constrain those cards sizes in the preview - or provide a bounding box - so an author can see what will happen?

**Comment by dclaux** [comment]
What is not going to work with the card you have as displayed above is that you size all columns using a weight (by the way weights are supposed to be expressed as numbers, not a strings, e.g. ```"width": 5``` and not ```"width": "5"```) When you use weights, the horizontal space a column gets does not depend on its content, so its content will get truncated when the column gets resized to a width that simply isn't enough for the column's content.

To avoid that, you want to use "auto" and "stretch" as much as possible. In your case that means you can't define that empty column on the left with a weight. Your solution is probably to remove that column (that's what I did in the payload I sent you) or to add an invisible image in it to reserve a fixed amount of space.

**Comment by mrbrennonwilliams** [comment]
The width as string is a bug on my side - not applying an int (although the renderers appear to still handle it correctly, which is a bug also ;-) )

The empty column is there to balance out the 3 columns.

1* col  5* col  1* col

The large image is supposed to be centred, not to the left.

This approach of column widths is pretty standard when we don't have the option of absolute widths (which I am not saying we ought to have).

Having to use an empty image has a smell about it don't you think?

The same approach is used on all the smaller columns below - so the content is not on the very edge of the cards.

I guess my point is that a column weight of 5 should correctly render in proportion to the other two columns that are also weighted. And in this event, the Image element should be scaling appropriately to fit the parent container - as the image is sized semantically as opposed to a fix size.

**Comment by dclaux** [comment]
My point is with the column sizing you currently use the text at the top right _will_ get truncated if the card isn't wide enough, and in my opinion that is worse than making the design compromise of having the image at the top left of the card. Explicit column width is the right solution for you, but given it is not supported your only option right now (again aside from removing the leftmost column) is to put an explicitly sized invisible image in it.

[I have just opened an issue](https://github.com/Microsoft/AdaptiveCards/issues/1026) to propose support for explicit column sizing in a later version.

**Comment by mrbrennonwilliams** [comment]
No worries.

Thanks for taking a look at it and working through it with me.

I'll close this out.
