### ISSUE TITLE
[WPF] Column Width property is type String

### ISSUE THREAD

**Issue by mrbrennonwilliams** [Microsoft/AdaptiveCards#1027]
Looking at previous comments from @dclaux  in issue #1024 , he indicated that Column Width property should be a number as is also indicated in the schema.

A TODO is listed in the code for a ColumnWidth property type, but I was unable to find an existing issue tracking this.

**Comment by tuanh118** [comment]
Since we're now supporting both number (e.g., 1, 2, 3) and string (e.g., 50px, 100px) and it's also correctly specified in the documentation, should we close this issue?
