### ISSUE TITLE
[WPF] SelectAction on Image element sets Image Left aligned

### ISSUE THREAD

**Issue by mrbrennonwilliams** [microsoft/AdaptiveCards#1031]
Throw this JSON in the WPF visualiser and you will note that the last image is positioned on the left. Remove the SelectAction and the correct position resolves.

`{"type":"AdaptiveCard","version":"1.0","id":"5dcc6c6e-c068-4aab-bc09-07e0c6046109","minVersion":"1.0","fallbackText":"","speak":"","body":[{"type":"TextBlock","id":"02b09e80-484e-429b-9a0f-1f7a8b2b8702","size":"extraLarge","weight":"bolder","text":"Nutrition Facts","maxLines":1},{"type":"TextBlock","id":"da05f1e6-8d26-4fab-9521-2e8ef236adc1","weight":"bolder","text":"Serving: 1 Order","maxLines":1},{"type":"TextBlock","id":"1009703f-0504-4797-b373-3e8f27b6968d","text":"Amount Per Serving","maxLines":1,"spacing":"small","separator":true},{"type":"ColumnSet","id":"a2ca74e2-37b9-46dd-bfb5-d48f23b497e3","columns":[{"type":"Column","id":"ff619204-f5a0-42b2-b013-c0b635398ac5","width":"stretch","items":[{"type":"TextBlock","id":"f4491440-544b-4178-88b5-3b371dd74eda","text":"Calories 0","maxLines":1}]},{"type":"Column","id":"3ed52ac3-4662-4270-80aa-84efbe7d45da","width":"auto","items":[{"type":"TextBlock","id":"4de27f80-c720-494c-802a-66dded3c0343","text":"Calories from Fat 0","maxLines":1}]}],"separator":true},{"type":"TextBlock","id":"1793d093-cff2-449e-8e04-366c1c96bbdb","text":"% Daily Value*","horizontalAlignment":"right","maxLines":1,"separator":true},{"type":"ColumnSet","id":"b22dc2a2-9ee8-4809-b65c-f74313119e84","columns":[{"type":"Column","id":"5e4e0ab2-cab6-4f7e-9180-eb0a9227625e","width":"stretch","items":[{"type":"TextBlock","id":"e767de31-9ae1-457d-95d1-a632c1041421","weight":"bolder","text":"Total Fat 0g","maxLines":1}]},{"type":"Column","id":"77296042-0a32-4f41-95b7-4787523858a9","width":"auto","items":[{"type":"TextBlock","id":"fea15b61-0616-4ebc-81cd-2d0205edebfb","weight":"bolder","text":"0%","maxLines":1}]}],"separator":true},{"type":"ColumnSet","id":"fc85e321-e6d6-4e11-90c9-4ae014b241fb","columns":[{"type":"Column","id":"b8bec443-fbd7-4c3e-a36a-b3c25c550801","width":"stretch","items":[{"type":"TextBlock","id":"c3c806a9-6920-4c3d-ba5b-52fbaa2aa403","text":"Saturated Fat 0g","maxLines":1}]},{"type":"Column","id":"6d1019a9-fa34-471d-baf9-280b398c9864","width":"auto","items":[{"type":"TextBlock","id":"3f112e0b-1700-4da0-8151-ecefb5b046c5","weight":"bolder","text":"0%","maxLines":1}]}],"separator":true},{"type":"TextBlock","id":"4d9a9add-037c-4f5e-80c8-b34e348c3daf","text":"Trans Fat 0g","maxLines":1,"separator":true},{"type":"ColumnSet","id":"da566640-bab0-4024-aeaa-b54545543f83","columns":[{"type":"Column","id":"b0540886-d2c3-4593-99dc-2b1fd56c867a","width":"stretch","items":[{"type":"TextBlock","id":"3623cb84-1363-4d6a-8d35-fa582b13f3b3","weight":"bolder","text":"Cholesterol 0mg","maxLines":1}]},{"type":"Column","id":"a4e3170d-b50b-46fd-9e0c-3eed368be292","width":"auto","items":[{"type":"TextBlock","id":"8ff43559-94db-40d5-a6e1-007625bf2d74","weight":"bolder","text":"0%","maxLines":1}]}],"separator":true},{"type":"ColumnSet","id":"d551cac4-6913-4972-a8f5-c8952f711098","columns":[{"type":"Column","id":"2a6dd83b-10a0-4668-ad2c-584017a065aa","width":"stretch","items":[{"type":"TextBlock","id":"7d949c22-3e8c-497b-8f7a-cd24fcbc5a0e","weight":"bolder","text":"Sodium 0mg","maxLines":1}]},{"type":"Column","id":"01c42701-c5b1-4177-820a-dd0997448ce6","width":"auto","items":[{"type":"TextBlock","id":"3065b651-a3a8-4a06-9ebf-baf0f62053db","weight":"bolder","text":"0%","maxLines":1}]}],"separator":true},{"type":"ColumnSet","id":"896f4f84-e7a9-4fef-831b-32e0a9719ef8","columns":[{"type":"Column","id":"4a0b73db-a5ca-4013-8de9-64161d9356ca","width":"stretch","items":[{"type":"TextBlock","id":"a2e3da51-1bb7-4561-9e96-9ec5acadec61","weight":"bolder","text":"Total Carbohydrates 0g","maxLines":1}]},{"type":"Column","id":"71d04168-7d40-4e33-b338-6ddb7eda8bc2","width":"auto","items":[{"type":"TextBlock","id":"70e9e2a9-e295-4c05-ab19-66e5bca7a2bc","weight":"bolder","text":"0%","maxLines":1}]}],"separator":true},{"type":"ColumnSet","id":"ba58adfa-305b-4c62-9ce7-6502e9c09ae5","columns":[{"type":"Column","id":"7ce9cb7a-8f49-4fa2-8341-574346efbca3","width":"stretch","items":[{"type":"TextBlock","id":"aa83b749-e080-493e-a200-23b50357ce23","text":"Dietary Fiber 0g","maxLines":1}]},{"type":"Column","id":"5255c792-7170-453c-aab3-30f717049144","width":"auto","items":[{"type":"TextBlock","id":"feb25ee6-f8b5-4e01-aff3-86e9e9cfb784","weight":"bolder","text":"0%","maxLines":1}]}],"separator":true},{"type":"TextBlock","id":"c7599b65-4abb-49e8-9736-d979b0535db2","text":"Sugars 0g","maxLines":1,"separator":true},{"type":"TextBlock","id":"7691e840-c03e-40a2-bcf7-be4abaa1ba50","weight":"bolder","text":"Protein 0g","maxLines":1,"separator":true},{"type":"TextBlock","id":"363fb53c-4974-425a-ab1d-d4ead4297b8e","size":"medium","text":"*Percent Daily Values are based on a 2000 calorie diet.","maxLines":1,"spacing":"extraLarge","separator":true},{"type":"Image","id":"f7628a34-4baa-4130-abf0-7baea1447a12","url":"https://goo.gl/exYocx","horizontalAlignment":"center","selectAction":{"type":"Action.OpenUrl","url":"https://www.nutritionix.com/","title":"Open"},"altText":"","separator":true}]}`

**Comment by jonmill** [comment]
This issue should not repro in the latest builds; please re-open the issue if that is not the case. Thanks!
