### ISSUE TITLE
Bug on adaptivecards.io website

### ISSUE THREAD

**Issue by sahngah** [microsoft/AdaptiveCards#1037]
Hi Adaptive Cards team!

I found a bug on every page under adaptivecards.io/explorer. If you scroll all the way to the bottom, the nav bar on the left goes crazy making the menu items almost unclickable. I tested it on two computers and the website does that on both computers. 

![SidebarIssues](https://user-images.githubusercontent.com/13246069/59786932-363c4e80-927d-11e9-8de5-946e2f82a4b3.gif)

Thanks.

**Comment by matthidinger** [comment]
Thanks for reporting, I will take a look and get this fixed with our next site rollout!

**Comment by sahngah** [comment]
No problem! I visited the website again and noticed a few more things:

- It doesn't happen on Edge, but only on Chrome.
- It only goes crazy on my laptop. If I place the browser window on a bigger monitor, it doesn't do it. (tested on two laptops)

Hopefully this helps a little!

**Comment by andrewleader** [comment]
Closing as no longer seems to repro

**Comment by andrewleader** [comment]
Nevermind, still repro's, see GIF (it's wonky crazy!!)

![SidebarIssues](https://user-images.githubusercontent.com/13246069/59786932-363c4e80-927d-11e9-8de5-946e2f82a4b3.gif)

Matt and I are looking into fixing

**Comment by andrewleader** [comment]
This has been fixed and the fixed site is now live! Thanks for reporting this!
