### ISSUE TITLE
GroupMe Windows Client not showing Card immediately

### ISSUE THREAD

**Issue by kwiggen** [microsoft/AdaptiveCards#1042]
Using the following code with the C# gnuget, I send a reply back to GroupMe.  It doesn't render on Windows or Android unless i reload the discussion.  It works on iOS.  After working with the GroupMe people it seems the GroupMe client is barfing on the "lat" and "lng" being sent as null.  They are fixing their clients, but older ones will barf.

`AdaptiveCard card = new AdaptiveCard();
botMessage.Attachments = new List<Attachment>();

            card.BackgroundImage = "https://messagecardplayground.azurewebsites.net/assets/Mostly%20Cloudy-Background-Dark.jpg";

            AdaptiveCard card = new AdaptiveCard();
                      

            ColumnSet cs = new ColumnSet
            {
                Columns = new List<Column>()
            };
            Image img = new Image
            {
                Url = "http://messagecardplayground.azurewebsites.net/assets/Mostly Cloudy-Square.png",
                Size = ImageSize.Stretch
            };
            
            cs.Columns.Add(new Column
            {
                Size = "35",
                Items = { img }
            });

            TextBlock tb1 = new TextBlock
            {
                Text = "Monday April 1",
                Weight = TextWeight.Bolder,
                Size = TextSize.Large,
                Color = TextColor.Light
            };
            TextBlock tb2 = new TextBlock
            {
                Text = "63 / 42",
                Size = TextSize.Medium,
                Separation = SeparationStyle.None
            };
            TextBlock tb3 = new TextBlock
            {
                Text = "20% chance of rain",
                IsSubtle = true,
                Separation = SeparationStyle.None
            };
            TextBlock tb4 = new TextBlock
            {
                Text = "Winds 5 mph NE",
                IsSubtle = true,
                Separation = SeparationStyle.None
           };
            cs.Columns.Add(new Column
            {
                Size = "65",
                Items = { tb1, tb2, tb3, tb4 }
            });

            card.Body.Add(cs);
            

            Attachment attachment = new Attachment()
            {
                ContentType = AdaptiveCard.ContentType,
                Content = card
            };

            botMessage.Attachments.Add(attachment);
                        
            await context.PostAsync(botMessage);
`

**Comment by kwiggen** [comment]
Possibly EmitDefaultValue=false???

**Comment by mwdavis84** [comment]
Hi, Mark from the GroupMe team here. Like he said, what happens here is GroupMe is receiving a malformed payload that some clients are handling better than others. When an attachment is sent to GroupMe, it should only have attachments specified that are there, not the full payload of possible attachment types with nulls.

This is an example of a correct attachment payload for an image:

`"attachments\":[{"type":"image","url":\"MY_IMAGE_URL"}]`

This is what is being sent in the case noted above:

`"attachments":[{"lat":null,"lng":null,"name":null,"type":"image","url":"MY_IMAGE_URL"}]`

If the service writing these messages is C# and uses a standard attachment type for every attachment, and serializing it to JSON, the proper thing to do, as stated above, is to use EmitDefaultValue=false like this:

       ```
 /// <summary>
        /// Gets or sets the Latitude of the attached location
        /// </summary>
        [DataMember(Name = "lat", EmitDefaultValue = false)]
        public double Latitude { get; set; }

        /// <summary>
        /// Gets or sets the Longitude of the attached location
        /// </summary>
        [DataMember(Name = "lng", EmitDefaultValue = false)]
        public double Longitude { get; set; }

```

**Comment by shalinijoshi19** [comment]
@matthidinger / @andrewleader what is GroupMe?
