### ISSUE TITLE
How UWP response to Action.OpenUri? Nothing happened when I click the button in my app.

### ISSUE THREAD

**Issue by freshomer** [Microsoft/AdaptiveCards#1043]
How UWP response to Action.OpenUri? Nothing happened when I click the button in my app.

**Comment by riarenas** [comment]
The SDK does not provide a default handler for any of the actions. It's up to each host that is rendering cards to hook up an action event handler to the RenderedAdaptiveCard that results from a call:

```C#
RenderedAdaptiveCard renderResult = renderer.RenderAdaptiveCard(card)
renderResult.Action += async (sender, e) =>
{
    var m_actionDialog = new ContentDialog();
    if (e.Action.ActionType == ActionType.OpenUrl)
    {
       // Do something
    }
}
```

We are exploring some options to provide default implementations for some of the action types in future versions.

**Comment by matthidinger** [comment]
Hi @freshomer, hopefully the above comment resolved your issue. Please re-open if you're still having issues
