### ISSUE TITLE
Adaptive Cards not really adaptive on Skype client

### ISSUE THREAD

**Issue by vreddi** [Microsoft/AdaptiveCards#1052]
With the new Sykpe update I started seeing my adaptive cards show up on the client for my bot.

But it seems like they are not really adaptive. They did not adapt well on the skype client (Both mobile/Desktop).

Here is how it looks on the web client:
![image](https://user-images.githubusercontent.com/6148930/34184395-56a196ba-e4d4-11e7-8dc5-3ed33f33b3d7.png)

But on the skype client, on a mobile device it looks like this (similar on desktop):
![img_6986](https://user-images.githubusercontent.com/6148930/34184472-cb04cec8-e4d4-11e7-9878-c2496679c8b5.PNG)
![img_6987](https://user-images.githubusercontent.com/6148930/34184473-cb1d6e92-e4d4-11e7-93df-e9cad1ba8d3a.PNG)

**Comment by matthidinger** [comment]
Hi @vreddi, sorry about the delay over the holidays! Adaptive Cards in Skype are under active development and not quite ready for prime time yet. 

That said, Skype cards (as they are currently designed), will not be as wide as what you see in WebChat. You may have to alter the payload slightly for Skype clients. 

In the future we plan to add more "responsive" attributes to Adaptive to make them adjust to various widths more naturally.

**Comment by dclaux** [comment]
@vreddi the general guidance when designing cards is to design them for the minimum expected width. Cards designed this way should adapt nicely to a wider container. That said, as @matthidinger wrote above, we will be considering explicit ways to help designers craft cards for multiple target widths in a future version.

**Comment by vreddi** [comment]
@matthidinger No worries, hope you had a great time during the holidays. I was actually surprised when my bot started working with the Skype client i.e when it showed all the Adaptive cards. I knew that you guys were still working on integrating with other clients but all of a sudden seeing the cards pop up on the Skype client made me think that you guys were at-least in beta on Skype.

I think adaptive cards are great. They surely need more custom properties. If they could be as free as HTML/CSS are today along with the "responsive" attributes you talk about so that they can naturally adapt to any client and any form factor, it would be awesome!

@dclaux Totally understandable. Makes sense. 

I will go ahead and close the issue.
