### ISSUE TITLE
Carousel of columns

### ISSUE THREAD

**Issue by yogiderek** [microsoft/AdaptiveCards#1059]
This article titled Future Work https://docs.microsoft.com/en-us/adaptive-cards/resources/future
says "Add a threshold that, when exceeded, changes columnSet to carousel of columns."

I think this may be better suited to my design than a carosuel of cards. Can you say if this is still future work and if so when it might be available for release. Also, is there a nightly build etc of the nuget package that can be used to get the most recent updates and enhancments etc.

**Comment by matthidinger** [comment]
Hi @yogiderek, it is indeed something we are looking to explore but no concrete plans yet. At this time our nightly builds are not publicly available outside Microsoft but we're looking for ways of making this happen.

**Comment by yogiderek** [comment]
Thanks, looking forward to seeing and trying both in the future

**Comment by andrewleader** [comment]
Closing for now. @yogiderek, if you have some specific requirements about what you're trying to achieve, please share them and we can capture them! Some visual comps are particularly useful!
