### ISSUE TITLE
Few errors while migrating from "microsoft-adaptivecards"(previous version) to "adaptivecards"(new version)

### ISSUE THREAD

**Issue by Yash-7** [Microsoft/AdaptiveCards#1060]
Hey guys, I've been trying to migrate from previous version of adaptive cards to newer version. I came across a few errors while using the new version for the WebChat channel of the chat bot I'm working on.
## ERROR 1
` receiptCardBuilder.addTextBlock(item.price, { horizontalAlignment: 'right' }, columns2[2]);`
This is a piece of code from webchat channel in which the error is  " **Type "right" is not assignable to type 'HorizontalAlignment'** ".

**New version**
The error is being generated from this code located in _node_modules/adaptivecards/lib/enum.d.ts_
![capture](https://user-images.githubusercontent.com/26803022/34513147-a8c44ff0-f08c-11e7-91c7-3047b6c136d2.PNG)

**Old version**
In the previous version, it was like this `export declare type HorizontalAlignment = "left" | "center" | "right";`
also the path is _node_modules/microsoft-adaptivecards/built/schema.d.ts_

I already tried changing right to Right in my webchat but it's not working. I think that error is originating from the type enum although I don't understand why.
## ERROR 2
Also there is one more error that I got. This is a piece of code from my webchat channel. 
![capture1](https://user-images.githubusercontent.com/26803022/34513333-cccf5d6c-f08d-11e7-8534-9394736ef4e0.PNG)
The error is **" Property 'setHostConfig' does not exist on type 'typeof "d:/custom_webchat_channel/node_modules/adaptivecards/lib/adaptivecards"'."** 

The error is being generated from this code located in _node_modules/adaptivecards/lib/card-elements.d.ts_. This piece of code is missing in the new version of adaptivecards.
![capture2](https://user-images.githubusercontent.com/26803022/34513414-2edebc28-f08e-11e7-840a-cb9687cd5637.PNG)

Is there any fix to this? Any help would be appreciated.

**Comment by dclaux** [comment]
Hi @Yash-7 sorry for the headaches these changes are causing. You need to do the following:

## Error 1
The correct syntax is now ```yourTextBlock.horizontalAlignment = HorizontalAlignment.Right```

Depending on how you are referencing the Adaptive rendering library, you might have to prefix with the namespaces you used, e.g. something like **AdaptiveCards**.HorizontalAlignment.Right

## Error 2
HostConfig is now set on a per-card basis. So you will have to write something like:
```
let myCard = new AdaptiveCard();
myCard.hostConfig = adaptiveCardsHostConfig;
```

**Comment by Yash-7** [comment]
Thanks for your quick reply. That is exactly what I wanted. I wanted to know if there any major changes in the new version of the adaptive cards? There were many other changes which I was able to resolve. Is it worth the time to migrate? Or is the older version good enough for now because I can't see any major changes in the card.

**Comment by dclaux** [comment]
Definitely worth the time to migrate :) This new version is close to complete and you can expect very few (actually probably none) breaking changes in updates leading to v1 of Adaptive Cards. This new version is more solid and feature complete, and definitely a better bet for you.
