### ISSUE TITLE
Facebook messenger does not display the adaptive card

### ISSUE THREAD

**Issue by CalvinFengDatacom** [microsoft/AdaptiveCards#1065]
I assembled the adaptive card with C# AdaptiveCard SDK, which can display the Adaptive Card in WebChat. But, Facebook Messenger does not display the adaptive card. 

Here is the key part of adaptive card code, please let me know why I can't see adaptive card in Facebook channel? Thanks

`AdaptiveCard adaptiveCard = new AdaptiveCard()`
`  {`
`     Body = new List<AdaptiveElement>`
`         {`
`		new AdaptiveColumnSet`
`		{`
`			Columns = new List<AdaptiveColumn>`
`			{                      `     
`				new AdaptiveColumn`
`				{`
`					Items = new List<AdaptiveElement>`
	`				{`
		`				new AdaptiveTextBlock`
			`			{`
						`	Size = AdaptiveTextSize.Large,`
						`	Text = "&#42;",`
						`	Color = AdaptiveTextColor.Warning`
					`	}`
					`}`
			`	},`
				`new AdaptiveColumn`
				`{`
					`Size = "1px",`
					`Items = new List<AdaptiveElement>`
				`	{`
				`		new AdaptiveTextBlock`
					`	{`
						`	Text = "indicates mandatory fields",`
						`	Size = AdaptiveTextSize.Medium,`
						`	Wrap = true`
						`}`
				`	}`
				`}`
			`}`
		`},`
		`new AdaptiveTextBlock()`
		`{`
		`	Text = " ",`
		`	Spacing = AdaptiveSpacing.Medium,`
		`}`
`	},`
`	Actions = new List<AdaptiveAction>()`
`	{`
	`	new AdaptiveSubmitAction()`
		`{`
	`		Title = "Confirm",`
	`		DataJson = "{\"Type\": \"RequestBody\"}"`
	`	}`
	`}`
`};`
`RenderedAdaptiveCard renderedAdaptiveCard = renderer.RenderCard(adaptiveCard);`
`Attachment plAttachment = new Attachment()`
`{`
`ContentType = AdaptiveCard.ContentType,`
`Content = renderedAdaptiveCard.OriginatingCard`
`};`

**Comment by brunoadamalves** [comment]
Hi,
Any news about this?

Kind regards

**Comment by matthidinger** [comment]
Hi folks, really sorry about the delay. Can you provide the JSON that is generated from this? Does Messenger show any card response at all, or just nothing? 

@EricDahlvang any ideas?

**Comment by EricDahlvang** [comment]
Removing the line that renders the adaptive card, the following code:

```cs
AdaptiveCard adaptiveCard = new AdaptiveCard()
{
    Body = new List<AdaptiveElement>
    {
        new AdaptiveColumnSet
        {
            Columns = new List<AdaptiveColumn>
            {
                new AdaptiveColumn
                {
                    Items = new List<AdaptiveElement>
                    {
                        new AdaptiveTextBlock
                        {
                            Size = AdaptiveTextSize.Large,
                            Text = "&#42;",
                            Color = AdaptiveTextColor.Warning
                        }
                    }
                },
                new AdaptiveColumn
                {
                    Size = "1px",
                    Items = new List<AdaptiveElement>
                    {
                        new AdaptiveTextBlock
                        {
                            Text = "indicates mandatory fields",
                            Size = AdaptiveTextSize.Medium,
                            Wrap = true
                        }
                    }
                }
            }
    },
        new AdaptiveTextBlock()
        {
            Text = " ",
            Spacing = AdaptiveSpacing.Medium,
        }
    },
    Actions = new List<AdaptiveAction>()
    {
        new AdaptiveSubmitAction()
        {
            Title = "Confirm",
            DataJson = "{\"Type\": \"RequestBody\"}"
        }
    }
};

Attachment plAttachment = new Attachment()
{
    ContentType = AdaptiveCard.ContentType,
    Content = adaptiveCard
};
```

Produces the following .json:

```
{
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "items": [
            {
              "type": "TextBlock",
              "size": "large",
              "color": "warning",
              "text": "&#42;"
            }
          ]
        },
        {
          "type": "Column",
          "size": "1px",
          "items": [
            {
              "type": "TextBlock",
              "size": "medium",
              "text": "indicates mandatory fields",
              "wrap": true
            }
          ]
        }
      ]
    },
    {
      "type": "TextBlock",
      "text": " ",
      "spacing": "medium"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "data": {
        "Type": "RequestBody"
      },
      "title": "Confirm"
    }
  ]
}
```

This is rendered on https://www.messenger.com like:

![image](https://user-images.githubusercontent.com/11055362/38759697-0fb5c304-3f2c-11e8-9559-505e88e8ca14.png)

**Comment by artus** [comment]
Adaptive Cards are not supported by the facebook messenger channel yet. They will be [rendered as an image with limited button mapping suport](https://stackoverflow.com/questions/48313198/adaptive-cards-are-converted-to-image-in-facebook-messenger).
