### ISSUE TITLE
Proposal: Create telemetry interface

### ISSUE THREAD

**Issue by manoskow** [microsoft/AdaptiveCards#1077]
# Solves requests

* Telemetry interface (#2026)

# Proposal

API to ask for how many elements are in a card... This returns a dictionary of how many elements are used, which can then be reported via telemetry...

| Element | Count |
|--|--|
| TextBlock | 3 |
| Image | 1 |
| Input.Text | 1 |
| Action.Submit | 2 |

```csharp
Dictionary<string, int> elements = card.GetElementsAndCounts();
```

Make sure we allow intercepting the Action.OpenUrl event and Action.ShowCard event so hosts can report telemetry on it

Make sure we report useful parse/render errors/warnings

**Comment by andrewleader** [comment]
Proposal needs more details. Break them into sub-scenarios? Lots of information missing from proposal.

**Comment by paulcam206** [comment]
Not currently under consideration, but will reactivate should we decide to pursue.
