### ISSUE TITLE
Input.ChoiceSet needs a better UX for multiselect + expanded with large lists

### ISSUE THREAD

**Issue by Subabrota** [microsoft/AdaptiveCards#1080]
We have requirement for multi select from a list of fields. The field list is having more than 200 values. So when we use checkbox view as shown below the card length is exceeding the frame of bot. Please suggest how can we give a better view to the bot with multi select options available within a restricted height.
![multiselect](https://user-images.githubusercontent.com/35215114/35044169-5da3ea10-fbb5-11e7-9acf-cd10660bd5c8.png)

Note: 1. We are currently using the drop down control in adaptive card with single select).
2.The image is sample. Consider the same view with 100+ list items.

**Comment by matthidinger** [comment]
Hi @Subabrota, unfortunately we don't have a standard UX for multi-select expanded view at this time. We're open to explore options but haven't been able to prioritize designing this yet

**Comment by Subabrota** [comment]
Hi Matt,


Can you provide any suggestion how to manage this requirement through an alternative way.


Subabrota Pal
-Kolkata
________________________________

**Comment by matthidinger** [comment]
What app/technology are you using to host your card. Is it a bot? Are you using the WebChat control?

**Comment by Subabrota** [comment]
Yes we are using adaptive card within WebChat using Directline. We have used Bot Framework sdk to develop the bot.
