### ISSUE TITLE
[UWP Renderer] Data property on Submit action doesn't handle a string instead of a json object

### ISSUE THREAD

**Issue by anbare** [Microsoft/AdaptiveCards#1083]
When a card author uses a string instead of a JSON object for the `data` property on `Action.Submit`, the UWP renderer is unable to retrieve the data property. In the web libraries this works fine.

## Object works fine...

```json
{
  "type": "Action.Submit",
  "title": "Dismiss",
  "data": {
      "action": "dismiss",
      "alarmId": 3
  }
}
```

## But string doesn't...

```json
{
  "type": "Action.Submit",
  "title": "Dismiss",
  "data": "action=dismiss&alarmId=3"
}
```

When we receive the callback and inspect the `Data` property on `AdaptiveSubmitAction`, it's null.

We SHOULD be able to do the following as to support both strings and objects being specified there...

```csharp
if (submitAction.DataJson.ValueType == JsonValueType.String)
{
    arguments = submitAction.DataJson.GetString();
}
else
{
    arguments = submitAction.DataJson.Stringify();
}
```

## Full repro payload

```json
{
  "type": "AdaptiveCard",
  "version": "1.0",

  "body": [

    {
        "type": "TextBlock",
        "text": "Time to wake up!"
    }

  ],

  "actions": [

    {
      "type": "Action.Submit",
      "title": "Snooze",
      "data": "action=snooze&alarmId=3"
    },
    {
      "type": "Action.Submit",
      "title": "Dismiss",
      "data": "action=dismiss&alarmId=3"
    }

  ]
}
```

**Comment by riarenas** [comment]
The likely changes that need to be made to make this work should be something like:

1. Change AdaptiveSubmitAction.DataJson's type from an IJsonObject to an IJsonValue.
2. When creating the DataJson field, check if the value is a string or an object, and use IJsonValue.Parse().

**Comment by anbare** [comment]
Closing as dupe of #773
