### ISSUE TITLE
Rendering images using Adaptive Cards in prompts.choice() method

### ISSUE THREAD

**Issue by Yash-7** [microsoft/AdaptiveCards#1098]
Hey,
I am working on webchat to build a chatbot and Webchat uses adaptive cards to render cards. 

`builder.Prompts.choice(session, "Which color?", "red|green|blue", { listStyle: builder.ListStyle.button });`
This piece of code gives me a list of buttons to select with classname ac-pushButton. Is there a way in which we can render images instead of buttons.

This might not be an issue but can anyone please take your time and answer this? Thanks in advance.

**Comment by matthidinger** [comment]
Hi @Yash-7, I'm really sorry about the delay getting back to you. The primary way to change how the card is rendered would be to fork WebChat and modify the source. I'm not actually sure if there's another way. 

If you post an issue on their GitHub they might be able to give a better answer: https://github.com/Microsoft/BotFramework-WebChat

**Comment by andrewleader** [comment]
Closing as inactive
