### ISSUE TITLE
Enable Carthage for iOS SDK

### ISSUE THREAD

**Issue by pandres95** [microsoft/AdaptiveCards#1103]
It'd be awesome to have proper support for importing the library via [Carthage](https://github.com/Carthage/Carthage).

**Comment by matthidinger** [comment]
Hi @pandres95, thanks for the suggestion. I can't say when specifically we'll be able to work on this, but PR's are most welcome :)

**Comment by andrewleader** [comment]
Closing as stale

**Comment by jwoo-msft** [comment]
closing this as the efforts will be focused on supporting Swift Manager.
