### ISSUE TITLE
spacing and separation needs to be applied to all components in card - Android

### ISSUE THREAD

**Issue by eschavez** [Microsoft/AdaptiveCards#1106]

**Comment by Assaya** [comment]
Working?

GLOBALCHERRY

**Comment by eschavez** [comment]
Yes. Working and committed to master.

**Comment by Assaya** [comment]
Fiverr
    
    
            
      {
          "@context": "http://schema.org",
          "@type": "EmailMessage",
          "action": {
            "@type": "ViewAction",
            "url": "https://www.fiverr.com/s2/40af5bc329",
            "name": "Browse Services on Fiverr"
          },
          "description": "Browse Services on Fiverr"
      }
    

        
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    

                                        
    

    
        Globalcherry is tired of keeping Fiverr a secret.
    

    
        Fiverr is the world’s largest marketplace for services,where you can get everything you need at an unbeatable value.
    

    
        Sounds too good to be true? See for yourself!
    



                                        
                                            
                                                
                                                    
                                                        
                                                            Browse Services On Fiverr
                                                        
                                                    
                                                
                                                
                                                    
                                                        

		
			
			
			The Fiverr Team
		
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
                
                    
                        
                            
                                

                                    © Fiverr International Limited 2010-2016, Fiverr Inc. | 401 Broadway, Suite 1600 New York NY, 10013 USA.
                                    Your personal information will not be stored or used for any marketing purposes.
                                
                            
                         
                    
                
            
        
            

    

If you would like to unsubscribe and stop receiving these emails click here.

**Comment by Assaya** [comment]
As many of you will know, I suffer from schizophrenia and can be quite ill at times.
With the help of cloud computing I have come to some revealing conclusions.
Like 'yin and yang' there is good and bad. But one thing I have learnt is 'life is priceless'.
I intend doing a recorded message about my experiences, all positive I might add.
I might have a brain like the map of London but my heart is in my home, where I can write and communicate with the people I love.


angela@thehelm

[cid:936c08cc-6c91-4172-a13c-1a32b971a761]
