### ISSUE TITLE
Source of version 0.6.1

### ISSUE THREAD

**Issue by pavei** [microsoft/AdaptiveCards#1114]
Hi,

I want the source code of version 0.6.1, but i cant find a tag with this version.

**Comment by matthidinger** [comment]
Hi @pavei, I'm sorry we didn't get tagging for releases setup during our pre-release phase. Moving forward this will be possible. Is there anything specific we can help you debug?

**Comment by telkomops** [comment]
Hi @matthidinger, Looking at source code for tag v1.0 , points to node.js version of v1.0.0-beta7, is this the right source code and tagging?

**Comment by matthidinger** [comment]
Hi @telkomops, yeah it's correct. Unfortunately our versioning/taging script for npm failed so package.json wasn't updated. I've manually updated it in master and will be looking at the script
