### ISSUE TITLE
Text size is missing a 6th size for parity with existing tile/toast notifications

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#112]
Tiles/toasts have six sizes... right now the schema has only 5. It's missing a largest "Huge" size

Small = caption
Normal = base
Medium = subtitle
Large = title
ExtraLarge = subheader
?????????? = header

**Comment by peterblazejewicz** [comment]
Call it `display` - the Bootstrap does this:
The version of headers dedicated to stand out from display:
https://v4-alpha.getbootstrap.com/content/typography/
