### ISSUE TITLE
Changing string to wstring in MarkDownParser

### ISSUE THREAD

**Issue by nesalang** [Microsoft/AdaptiveCards#1120]
Adaptive Cards need to support characters that are outside of 0x00-0xFF value range.
i.e. isspace() will assert if it receives argument out of that range in debug flavor.

**Comment by khouzam** [comment]
This doesn't need to be done. The markdown parser takes in utf8 input and reading from the stream will always give one byte at a time. The comparisons made are always on single byte chars.
