### ISSUE TITLE
Date picker hide dropdown button, which actually misunderstanding person they can change the date

### ISSUE THREAD

**Issue by CalvinFengDatacom** [microsoft/AdaptiveCards#1139]
I just wondering why the dropdown button of date-picker is hidden in default. We are developing a bot with the adaptive card, many user testing reports are mentioned that users don't know they can change the date. Because the button is hidden in default, unless they hover the date.input. Do you have any option of how to resolve this issue?
I got this screenshot from http://adaptivecards.io/explorer/Input.Date.html, you can see the button is hidden.
![image](https://user-images.githubusercontent.com/26469662/36359955-c5b34900-1584-11e8-94d9-06c39a7e267e.png)

Unless you hover the date.input, then you can see the button.

![image](https://user-images.githubusercontent.com/26469662/36359974-f467e738-1584-11e8-991f-91f9d1329be1.png)

**Comment by mollyd26** [comment]
Hi @CalvinFengDatacom, we actually use the browser's native date control. If you test it out in various browsers, you'll notice a different experience on hover

**Comment by shalinijoshi19** [comment]
Closing this out as stale and potentially resolved.
