### ISSUE TITLE
Bot is not giving Voice output in Webchat

### ISSUE THREAD

**Issue by suresh1271** [microsoft/AdaptiveCards#1140]
I want my bot to give voice output for a specific message. I am using adaptive cards. When I see the code in http://adaptivecards.io it is working but when i use in my code it is not giving voice output.

Here is the code Iam using.

`
var msg = new builder.Message(session)
    .addAttachment({
        'contentType': 'application/vnd.microsoft.card.adaptive',
        'content': {
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  **"speak": "<s>Your  meeting about \"Adaptive Card design session\"<break strength='weak'/> is starting at 12:30pm</s><s>Do you want to snooze <break strength='weak'/> or do you want to send a late notification to the attendees?</s>",**
  "body": [
    {
      "type": "TextBlock",
      "text": "Adaptive Card design session",
      "size": "large",
      "weight": "bolder"
    },
    {
      "type": "TextBlock",
      "text": "Conf Room 112/3377 (10)",
      "isSubtle":true
    },
    {
      "type": "TextBlock",
      "text": "12:30 PM - 1:30 PM",
      "isSubtle":true,
      "spacing":"none"
    },
    {
      "type": "TextBlock",
      "text": "Snooze for"
    },
    {
      "type": "Input.ChoiceSet",
      "id": "snooze",
      "style":"compact",
      "value": "5",
      "choices": [
        {
          "title": "5 minutes",
          "value": "5",
          "isSelected": true
        },
        {
          "title": "15 minutes",
          "value": "15"
        },
        {
          "title": "30 minutes",
          "value": "30"
        }
      ]
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Snooze",
      "data": { "x": "snooze" }
    },
    {
      "type": "Action.Submit",
      "title": "I'll be late",
      "data": { "x": "late" }
    }
  ]
}
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "speak": "<s>Your  meeting about \"Adaptive Card design session\"<break strength='weak'/> is starting at 12:30pm</s><s>Do you want to snooze <break strength='weak'/> or do you want to send a late notification to the attendees?</s>",
  "body": [
    {
      "type": "TextBlock",
      "text": "Adaptive Card design session",
      "size": "large",
      "weight": "bolder"
    },
    {
      "type": "TextBlock",
      "text": "Conf Room 112/3377 (10)",
      "isSubtle":true
    },
    {
      "type": "TextBlock",
      "text": "12:30 PM - 1:30 PM",
      "isSubtle":true,
      "spacing":"none"
    },
    {
      "type": "TextBlock",
      "text": "Snooze for"
    },
    {
      "type": "Input.ChoiceSet",
      "id": "snooze",
      "style":"compact",
      "value": "5",
      "choices": [
        {
          "title": "5 minutes",
          "value": "5",
          "isSelected": true
        },
        {
          "title": "15 minutes",
          "value": "15"
        },
        {
          "title": "30 minutes",
          "value": "30"
        }
      ]
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Snooze",
      "data": { "x": "snooze" }
    },
    {
      "type": "Action.Submit",
      "title": "I'll be late",
      "data": { "x": "late" }
    }
  ]
}
});
session.endDialog(msg);`

Can anyone please help me

**Comment by BlockLabor** [comment]
The webchat control will only output voice if you input voice.  (from my experience)

https://blog.botframework.com/2017/06/26/Speech-To-Text/

**Comment by solidcloudio** [comment]
The webchat control will only output voice if you input voice. (from my experience)

https://blog.botframework.com/2017/06/26/Speech-To-Text/

**Comment by Assaya** [comment]
Unblock

GLOBALCHERRY

**Comment by mollyd26** [comment]
Hi @suresh1271, 

 If you aren't able to solve your problem from the link above, please file a bug with WebChat - https://github.com/Microsoft/BotFramework-WebChat

**Comment by shalinijoshi19** [comment]
@suresh1271 are you still observing this issue at this point? @matthidinger is this anything to do wtih AdaptiveCards?

**Comment by shalinijoshi19** [comment]
This is likely external to AdaptiveCards. marking for internal discussion and follow up.

**Comment by Assaya** [comment]
<blockquote class="embedly-card" data-card-theme="dark"><h4><a href="http://loadmypixel.club/index.html">BLANK TITLE</a></h4><p>WHAT IS VUE CONFERENCE?</p></blockquote>
<script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
https://loadmypixel.club


angela@thehelm

[cid:e37e5345-10f4-4d69-b966-5f9e1b3bd23b]
