### ISSUE TITLE
Android and UWP font family needs to be applied to Card

### ISSUE THREAD

**Issue by eschavez** [Microsoft/AdaptiveCards#1144]
Host Config specifies FontFamily but android does not respect that option.

**Comment by matthidinger** [comment]
@eschavez any ETA on when this will get checked in?

**Comment by RebeccaAnne** [comment]
UWP doesn't support this either

**Comment by almedina-ms** [comment]
iOS does support it

**Comment by eschavez** [comment]
Fixed.
