### ISSUE TITLE
FactSet allows an AdaptiveElement for the value, allows succinct creation of forms with a label/input control

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#116]

**Comment by RebeccaAnne** [comment]
With Input Validation, we probably wouldn't use this approach for this scenario anymore. Leaving open in case there are other scenarios that benefit from more robust FactSets.

**Comment by RebeccaAnne** [comment]
Request for TextBlocks in FactSets in #3880
