### ISSUE TITLE
Ability to change defaultHostConfig applied to new card elements

### ISSUE THREAD

**Issue by rcasto** [Microsoft/AdaptiveCards#1160]
It seems today it is possible to apply a custom hostconfig to individual instances of Adaptive Cards, but it would be convenient to not have to do this for all cards, although the flexibility is great.  

If we could also override the defaultHostConfig that is applied to new instances of cards, I believe that would be useful.  If there is a way to do this please let me know, I didn't see a way to do this as it seems the ability to adjust the defaultHostConfig is not exposed

By the way, I'm speaking about the HTML/JS renderer, but this could be exposed in all renderers

**Comment by dclaux** [comment]
Seems like a very reasonable ask. I think we can get it done.

**Comment by Assaya** [comment]
SUPER

<3
GLOBALCHERRY

**Comment by dclaux** [comment]
Already possible. The defaultHostConfig constant cannot be fully replaced with a new instance, but individual properties can be changed.
