### ISSUE TITLE
Action.ShowCard Does not Validate Against The Schema

### ISSUE THREAD

**Issue by justinwilaby** [Microsoft/AdaptiveCards#1165]
When performing schema validation on the samples in this repository, all samples that use the `Action.ShowCard` element fail validation.

## Repro Steps
```bash
npm i -s ajv
```
```js
// Assumes a fork exists locally instead of npm installing it.
const assert = require('assert');
const Ajv = require('ajv');
const schema = require('./schemas/adaptive-card.json');
const card = require('./samples/v1.0/Elements/Action.ShowCard.json');

const ajv = new Ajv();
ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json')); // Draft 6
const validate = ajv.compile(schema);
const valid = validate(card);
assert(valid); // false - Error - actions[0] should match some schema in anyOf
```
Although this seems to be limited to just `Action.ShowCard` elements, it prevents proper testing and validation when dynamically generating cards.

**Comment by dclaux** [comment]
I'm going to bet that it is because of the ```version``` property, although seeing the output would be helpful.

Although the ```version``` property is required on the root AdaptiveCard, it isn't required on the ```card``` of an ```Action.ShowCard```, which instead inherits the version of the root card.

**Comment by justinwilaby** [comment]
Good point. The output in this example shows 4 errors but only the one of particular concern was raised here. Adding a version to the nested card does not resolve this error but brings the count from 4 to 3. 

I believe this could be because of a circular reference that is dropped by the validator. `Action.ShowCard` refs `AdaptiveCard` which refs `Action.ShowCard` and so on. If that's the case, the question is then: "How is validation performed using JSON Schema Draft 6 validators?"

Furthermore, if the version is inherited for nested cards and thus is not required to exist, the Schema does not seem to correctly enumerate this which could lead to similar validation issues.

**Comment by dclaux** [comment]
I think the version property should be marked as optional in the schema and renderers should enforce its presence in the root card, e.g. it should be runtime validation rather than schema driven. That's one thing.

Now you raise good questions around how the schema validator works; I personally don't know much about it though.

**Comment by justinwilaby** [comment]
I assume the schema exists for this purpose and based on the number of daily downloads for the [Ajv NPM Package](https://www.npmjs.com/package/ajv), it seems reasonable that others will as well. I'm happy to take a crack at this if you think it would add value. 

From my testing, it looks like the `Action.ShowCard` is the only one to be affected. e.g. anywhere in the JSON that `"type": "Action.ShowCard"` exists, validation fails.

**Comment by justinwilaby** [comment]
As it turns out, the `version` was missing on other cards in the sample I was using (the sample contained 4 cards, 3 of which eluded me somehow) and adding the version caused them to pass validation. So this is great news!

> I think the version property should be marked as optional in the schema and renderers should enforce its presence in the root card, e.g. it should be runtime validation rather than schema driven.

Seems like this would fix validation issues.

**Comment by paulcam206** [comment]
This appears fixed with the latest version of the schema.
