### ISSUE TITLE
UWP doesn't render card if Container items is empty

### ISSUE THREAD

**Issue by matthidinger** [Microsoft/AdaptiveCards#1168]
UWP renderer is failing to render a card if the `Container` `items` property is empty. If this is in the shared model then it's possible the other mobile renderers are also affected

```json
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "TextBlock",
			"text": "Line 1"
		},
	    {
	        "type": "Container",
	        "spacing": "large",
			"items": []
	    },
	    {
			"type": "TextBlock",
			"text": "Line 2"
		}
	]
}
```

**Comment by eschavez** [comment]
This is not specific to UWP. Empty items results in a parse exception thrown by the shared model.
