### ISSUE TITLE
Add property for specifying card dimensions

### ISSUE THREAD

**Issue by tongyliu** [microsoft/AdaptiveCards#1201]
The Problem
=========

Currently, there is no way for a card author to specify that they would like their markup to be rendered at a fixed 1) height, 2) width, or 3) aspect ratio. This is a limitation for Bing API cards, which are designed to have a fixed aspect ratio, and it may be an issue for others as well.

Potential Design
============

Add a top-level field such as `dimensions` to the `AdaptiveCard` schema. It's still an open question as to what the structure of this field should be -- do we want to allow authors control over exact height and width, or perhaps only aspect ratio? We'll also need to figure out what format we want these values specified as.

```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.x",
    "dimensions": {
        "height": "150px",  // Should we allow this?
        "width": "285px" 
    }
    "body": [
       ...
    ]
}

{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.x",
    "dimensions": {
        "aspectRatio": 1.9 // Or we could do something like "16:9"
    }
    "body": [
        ...
    ]
}
```

**Comment by nuevocampo** [comment]
Suggestion for aspectRatio: number instead of string to keep the implementation straightforward.

**Comment by RebeccaAnne** [comment]
This is a good suggestion, but not something that's on our roadmap at this time. We may reconsider it in the future, or if you would like to make a contribution please see our contribution guidelines [here](https://github.com/microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md).
