### ISSUE TITLE
Support relative URLs for images in renderers

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#1244]
## Implementation status
- [x]   JavaScript (N/A)
- [x]   UWP (#1322)
- [x]   .NET (#1661)
- [x]   iOS (#1659)
- [x]   Android (#1658)
- [x]   Documentation

Today, using a relative URL in an Adaptive Card throws an exception while rendering.

In toasts, it makes sense for us to allow relative URLs to default to `ms-appx:///`, which is what other XAML surfaces allow, and what existing XML toasts allow. For example, `"url": "Assets/Images/dog.jpg"` rather than having to write `"url": "ms-appx:///Assets/Images/dog.jpg"`

```json
{
  "type": "AdaptiveCard",
  "version": "1.0",

  "title": {
    "text": "Dogs are the best!"
  },

  "body": [

    {
      "type": "Image",
      "url": "Assets/Images/dog.jpg",
      "size": "stretch"
    }

  ]
}
```

This requires a few pieces of work...

1. Host config where host can optionally specify a base url
2. Object model code updated to support relative URLs
3. Renderer code updated to support relative URLs and if relative, prefix the base url

## 1. Updated host config

```json
{
  "supportsInteractivity": true,
  "imageBaseUrl": "ms-appx:///"
  ...
```

## 2. Object model code updated

[This line of code](https://github.com/Microsoft/AdaptiveCards/blob/0d9065bec622bded16bdad881b2f4715e57e5df9/source/uwp/Renderer/lib/AdaptiveImage.cpp#L41) needs to be updated to allow relative urls

BEFORE

```cpp
RETURN_IF_FAILED(uriActivationFactory->CreateUri(imageUri, m_url.GetAddressOf()));
```

AFTER (idk what the equivalent in C++ is, but this needs to parse a URL that's either relative or absolute, allowing a relative url to be assigned)

```csharp
imageUri = new Uri(imageUri, UriKind.RelativeOrAbsolute);
```

## 3. Renderer code updated

And then while rendering, [this line of code](https://github.com/Microsoft/AdaptiveCards/blob/0d9065bec622bded16bdad881b2f4715e57e5df9/source/uwp/Renderer/lib/XamlBuilder.cpp#L453) needs to be updated to prefix the base url if the url is a relative url.

BEFORE

```cpp
THROW_IF_FAILED(imageUri->get_SchemeName(&schemeName));
```

This will throw on relative urls, since relative urls don't have a scheme. Therefore, this should be updated to...

AFTER (written in C#)

```csharp
// If not an absolute uri
if (!imageUri.IsAbsoluteUri)
{
    // Prefix the host config specified base url
    // Note that hostConfig.BaseUrl is a Uri object too
    imageUri = new Uri(hostConfig.BaseUrl, imageUri);
}

// Then continue with original code of getting scheme name
schemeName = imageUri.SchemeName;
```

**Comment by CalvinFengDatacom** [comment]
@anbare  Try using HostingEnvironment.MapPath.
`System.Web.Hosting.HostingEnvironment.MapPath("~/Assets/Images/dog.jpg");`

I can get the file with using HostingEnvironment.MapPath, but my file is in the App_Data folder (one of the default folder of Web.Api). Not too sure you can get it from other path.

**Comment by matthidinger** [comment]
Closing as not applicable to platform

**Comment by matthidinger** [comment]
Whoops, docs :)

**Comment by paulcam206** [comment]
Documentation is done and in the mahiding/site1.1 branch.
