### ISSUE TITLE
[Bug] Different result when using Size and Width

### ISSUE THREAD

**Issue by Kartik1607** [Microsoft/AdaptiveCards#1255]
I am creating a user form using adaptive card. Earlier I was using v0.5 and have recently updated to v1.0
In v1, the size property of column is deprecated and instead it is advised to use Width property.

But, both of them render different results.

| Size (Expected) | Width (Bug?) |
| ------------- | ------------- |
| ![Size](https://imgur.com/OGhdtAN.png)  | ![Width](https://imgur.com/IyE6ICr.png)  |

Code used for creating a single form field.

```C#
private static AdaptiveColumnSet GetFormField(String text, String defaultValue , String placeholder, AdaptiveTextInputStyle style = AdaptiveTextInputStyle.Text)
        {
            return new AdaptiveColumnSet()
            {
                Columns = new List<AdaptiveColumn>()
                {
                    new AdaptiveColumn()
                    {
                        Size = "35",
                        Spacing = AdaptiveSpacing.Medium,
                        Items = new List<AdaptiveElement>()
                        {
                            GetTextBlock(text + " - "),
                        }
                    },
                    new AdaptiveColumn()
                    {
                        Size = "65",
                        Spacing = AdaptiveSpacing.Medium,
                        Items = new List<AdaptiveElement>()
                        {
                            GetTextInput(text.Replace(" ",""), defaultValue, placeholder, style)
                        }
                    }
                }
            };
        }
```

### Details
<b>BotBuilder Version : </b> v3.14.0.7
<b>AdaptiveCard Version : </b> v1.0.0
<b>Platform : </b> .Net

**Comment by matthidinger** [comment]
Hi @Kartik1607, are those screenshots from WebChat or the BF Emulator? It's possible that WebChat is expecting a v0.5 payload but your .NET service is generating a v1.0 payload. If you include both Size and Width properties does it help?

@compulim do you have any ideas here?

**Comment by compulim** [comment]
For Bot Emulator and Web Chat, if you are not building by yourself, it's expecting 0.5 payload. And Web Chat `master` branch is now on `adaptivecards@1.0.0`, it will be on Web Chat `0.12.0` and should roll out very soon.

**Comment by Kartik1607** [comment]
@matthidinger The screenshots were from Bot Emulator.
Using both Size and Width provide even poorer results.

Testing on latest build of bot emulator from did not help. 

Let me know how can I debug what version the .Net service is generating and what version is the emlator expecting.

As of WebChat, we are using a React based modified implementation of  Webchat repo.

**Comment by Kartik1607** [comment]
Bumping up. Really need to get this fixed. 
Current emulator version : v3.5.35.

I am getting the correct payload from the bot. Using the JSON in Visualizer at adaptivecards.io produces the desired result.

**Comment by compulim** [comment]
@Kartik1607 we just released Web Chat [`@0.12.0`](https://github.com/Microsoft/BotFramework-WebChat/releases/tag/v0.12.0) few hours ago, with Adaptive Cards `@1.0.0`. Can you try it out?

Bot Emulator is pending update so you won't see it there yet.

**Comment by Kartik1607** [comment]
@compulim The issue was fixed in the new webchat.
However, there are still some issues in the adaptive card.

1. There is still no background change during hover in the webchat, while we do get the change in the MS Visualizer. Notice the background on the excellent (there is no mouse in screenshot)

| Visualizer | Webchat |
| ------------- | ------------- |
| ![MS Visualizer](https://imgur.com/H8ac4h8.png)  | ![Webchat](https://imgur.com/gP1NNOd.png)  |

Current workaround is to add custom css to .ac-selectable

2. Earlier webchat did not had a way to add new **blank** lines. 
To add a new line, we used ```  \n\n```, while to add a completely blank line ```  \n\n&nbsp;  \n\n```. (First \n to get to next and then a non-breaking space to go to next line).

This problem seems to have been fixed in new webchat and now we are getting 3 blank lines instead of 1. Now, even if we update our strings would it have same effect across all channels (for instance, in the emulator, we get desired results using the non-breaking space approach). Do we now need to generate different strings for each channel now?

**Comment by MichaelBartlettGitHub** [comment]
Are those just 5 images (text part of the images)?  Is the hover automatic for this or does it need to be set by a property?

**Comment by dclaux** [comment]
The hover behavior is controlled via CSS. Any rendered element that has its selectAction set has the ac-selectable style added to its class list. It looks like WebChat doesn't define the ac-selectable style.

**Comment by MichaelBartlettGitHub** [comment]
Thank you.  If I want to add custom CSS to webchat is there any way to do this out of the box by injecting it into the iframe or does this have to be done by hosting my own webchat?

**Comment by Kartik1607** [comment]
@dclaux There seems to be another bug in selectAction. I'll make a separate issue for that.

**Comment by Kartik1607** [comment]
@dclaux This issue can be closed as well. Thanks :)
