### ISSUE TITLE
Teams Incoming Webhooks

### ISSUE THREAD

**Issue by ramspoluri** [Microsoft/AdaptiveCards#1256]
Are AdapativeCards supported for Teams Incoming Webhooks?

**Comment by matthidinger** [comment]
Hi @ramspoluri, I'm not entirely following. Can you elaborate on what you mean?

**Comment by ramspoluri** [comment]
Hi @matthidinger,

I was trying to send AdaptiveCard (below sample) to incoming webhook using [Card Playground](https://messagecardplayground.azurewebsites.net). It errors out mentioning **Error: Summary or Text is required** (400 Bad Request)

```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "Image",
      "url": "http://adaptivecards.io/content/cats/1.png"
    }
  ]
}
```

And if I include "text" and some message, only that text message sent to Teams client.

**Comment by matthidinger** [comment]
Ah I understand. Right now Teams Connectors/Actionable Messages do not support adaptive cards yet, but we are actively working on it and hope to share more information in the coming months.

**Comment by ramspoluri** [comment]
Thanks and Appreciate all the work your work you guys are doing.

I do want to ask one more question - Are heroImage cards supported with Teams Incoming Webhooks?

**Comment by larryjin** [comment]
HeroImage is not currently supported. It's in the O365 connector card schema but we don't support rendering that property in Teams client. It's currently on the backlog.

**Comment by matthidinger** [comment]
I'll close this issue for now but please re-open if you run into anything else!
