### ISSUE TITLE
Smart image cropping to improve card portability

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#1266]
We should investigate a standard image cropping algorithm so the same image (esp background images) can be shared across hosts with different aspect ratios

**Comment by andrewleader** [comment]
Closing as no customer requests

**Comment by VMey** [comment]
This would be great for profile pictures.  We are trying to pull in images of folks from their profile pic and most of them have been pre-cropped, but not all.  Throwing off the card balance this way.
