### ISSUE TITLE
[Feature Request] Carousel Layout for Adaptive Cards on FB Messenger

### ISSUE THREAD

**Issue by Claessens14** [Microsoft/AdaptiveCards#1299]
# Feature Request
Is it possible to have adaptive cards (rendered to an image and maybe a button mapped) sent in Carousel layout?

**Comment by Kartik1607** [comment]
As far as I know, Carousel are supported in FB Messenger. And adaptive cards are just an attachment with limited support. You can attach adaptive cards to message and set attachment layout as carousal. 

In messenger, the cards would be shown as rendered image.

**Comment by Claessens14** [comment]
@Kartik1607  When I put the adaptive cards in Carousel layout, it sent each card as an individual photo to the user, not using the Carousel layout.

**Comment by AlbinShaji** [comment]
can anyone please provide an example where this is implemented if possible?

**Comment by andrewleader** [comment]
Great question, however closing because this is a Bot Framework question as they own the integration with Facebook. Please ask this question on the Bot Framework GitHub: https://github.com/Microsoft/BotBuilder/issues
