### ISSUE TITLE
Input.ChoiceSet to allow horizontal orientation

### ISSUE THREAD

**Issue by patokike** [microsoft/AdaptiveCards#1304]
Currently "Input.ChoiceSet" input type when style is expanded only allow for the options to be shown vertically.  It would be great to have to option of showing it horizontally.

Thanks

**Comment by mollyd26** [comment]
Thanks for the feedback @patokike! We'll look into it!

**Comment by andrewleader** [comment]
Thanks @patokike, we've captured this request in our feedback system. Just to confirm, do you still need this ability to display choices horizontally? If so, can you explain a bit more about your scenario and what you're trying to achieve (and if you have any visual comps, those would be incredible!)?

(Closing as your feedback is tracked in our feedback system)
