### ISSUE TITLE
iOS ACRRenderer uses a CGRect instead of CGSize

### ISSUE THREAD

**Issue by Clancey** [Microsoft/AdaptiveCards#1307]
The Constraint for the ACARenderer Render method takes a CGRect. Since this is used to constrain the size, the X,Y values have no bearing and are not used. This should take a CGSize instead.

**Comment by nesalang** [comment]
Updated API takes width as argument.
if width is set to zero, then AdaptiveCards width will be bound by its contents, otherwise, it will be constraint to the width specified. 
Fixed with [PR1313](https://github.com/Microsoft/AdaptiveCards/pull/1313)
