### ISSUE TITLE
NodeJs visualizer install fails.

### ISSUE THREAD

**Issue by Kartik1607** [Microsoft/AdaptiveCards#1318]
When following the instructions given at [nodejs folder](https://github.com/Microsoft/AdaptiveCards/tree/master/source/nodejs) the ```npm install``` command fails inside **adaptivecards-visualizer** directory.

Error : 
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for adaptivecards@1.0.0-ci.20180112.5
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'adaptivecards-visualizer'
npm ERR! notarget
```

Workaround : 
Inside **package.json** set adaptive card version to **1.0.0**, then run **npm install** and follow the commands in readme.md

**Comment by tuanh118** [comment]
I got the same issue. There are 2 options for you:
- Use the **published** npm package (https://www.npmjs.com/package/adaptivecards): This is exactly what you did. Specifying the package version in `package.json` and then run `npm install`
- Use the **local** npm package from `./source/nodejs/adaptivecards` folder: Remove the `adaptivecards` dependency from `package.json` and execute these commands in order:
  1. `npm install`
  2. `npm link adaptivecards` (make sure `npm link` was executed from the local `adaptivecards` project)
  3. `npm run build`
  4. `npm start`

**Comment by Kartik1607** [comment]
@tuanh118 It seems that the [README.md](https://github.com/Microsoft/AdaptiveCards/blob/master/source/nodejs/README.md) should be updated to better reflect the steps.

**Comment by tuanh118** [comment]
@Kartik1607 I fixed the npm package-lock.json files to avoid the error and also updated the README files to better explain the different installation options
