### ISSUE TITLE
[.NET Microsoft Bot] Title of Adaptive card Action.Submit is coming in capital letters only 

### ISSUE THREAD

**Issue by GauravKatariya** [Microsoft/AdaptiveCards#1319]
I am using AdaptiveCards  v1.0.0.
I want the title of Action in capital and small letters but somehow it is appearing in capital letters only.Is it the expected behavior? How can i change it .

**Comment by shalinijoshi19** [comment]
@GauravKatariya does this still repro for you? IF so, per ask from last year, could you share the JSON format you are using?

**Comment by GauravKatariya** [comment]
Hi Shalini,
I am out of the project now so, not sure what is current status.

Regards,
Gaurav
