### ISSUE TITLE
.NET HTML server renderer does not wrap text in facts correctly

### ISSUE THREAD

**Issue by andrewmagee** [Microsoft/AdaptiveCards#1328]
For facts with long text and/or values, the server renderer does not wrap text correctly. An example:

![image](https://user-images.githubusercontent.com/21367930/38322262-c804247c-37ee-11e8-9372-e5992d833863.png)

As can be seen above, the fact values expand out past the edges of the adaptive card.

The javascript renderer gets this right, so I imagine whatever logic it uses just needs to be copied:
![image](https://user-images.githubusercontent.com/21367930/38322086-43cb4366-37ee-11e8-8b05-b9921980d5ea.png)

**Comment by dclaux** [comment]
Mistakenly closed, re-opened.

**Comment by khouzam** [comment]
It looks like MaxWidth is not being respected for the FactSet in the .NET renderer.

**Comment by khouzam** [comment]
Ok, it seems that the different renderers as each interpreting `maxWidth` in the factset title slightly differently and I think that they should all behave as similar as possible.

I've based myself on the typescript renderer for most of the work, but I'm still a little confused as to the actual behavior that we'd like. @dclaux can you help clarify if you know how this should work?

Here are a couple of samples and their outputs:

##Long Title and Value


```json
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "FactSet",
            "facts": [
                {
                    "title": "This is a long factset title that will need to wrap around on the second line if it becomes too long.",
                    "value": "This is a long factset value that will need to wrap around on the second line if it becomes too long."
                },
                {
                    "title": "Fact 2",
                    "value": "Value 2"
                },
                {
                    "title": "Fact 3",
                    "value": "Value 3"
                },
                {
                    "title": "Fact 4",
                    "value": "Value 5"
                }
            ]
        }
    ]
}

```json
and the `factSet` section of the host config:
```
	"factSet": {
		"title": {
			"size": "Default",
			"color": "Default",
			"isSubtle": false,
			"weight": "Bolder",
			"warp": true,
                        "maxWidth": 300
		},
		"value": {
			"size": "Default",
			"color": "Default",
			"isSubtle": false,
			"weight": "Default",
			"warp": true
		},
```

This gives me what I expects, the `title` taking at most 150 pixels and wrapping the excess. The `value` taking the rest of the space for the card and wrapping appropriately.


![image](https://user-images.githubusercontent.com/6656040/38586698-ab09d378-3cd3-11e8-8f1b-bc2ad73cf04e.png)


Now, in the TS renderer, if I keep the same hostconfig, but make the fact title smaller, as in with this payload:

##Small Title

```json
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "FactSet",
            "facts": [
                {
                    "title": "Fact 1",
                    "value": "This is a long factset value that will need to wrap around on the second line if it becomes too long."
                },
                {
                    "title": "Fact 2",
                    "value": "Value 2"
                },
                {
                    "title": "Fact 3",
                    "value": "Value 3"
                },
                {
                    "title": "Fact 4",
                    "value": "Value 5"
                }
            ]
        }
    ]
}
```
I get the title column wrapping around well before it hits the `maxWidth` limit on the hostconfig. Is this the intended behavior?

![image](https://user-images.githubusercontent.com/6656040/38586882-6d95fae8-3cd4-11e8-90df-34338e9ad5b0.png)


Or should it look like this?

![image](https://user-images.githubusercontent.com/6656040/38586911-803cd0e0-3cd4-11e8-9c5d-82fdb912f4aa.png)

where the title tries to fit as much as it can until it reaches the `maxWidth` property and then would start wrapping.

I've made most of the code changes to try to get this consistency but I wanted to make sure that we all agreed on the right behavior before finishing.

**Comment by khouzam** [comment]
This has been fixed.
