### ISSUE TITLE
[MS Teams] Status for MS Teams integration? How to activate the preview?

### ISSUE THREAD

**Issue by serialoverflow** [Microsoft/AdaptiveCards#1345]
Hey,

i am looking forward to working with AdaptiveCards, particularly in the combination MS Bot Framework + MS Teams.
It says the feature is currently in preview:
https://docs.microsoft.com/en-us/adaptive-cards/resources/partners

How do i activate said preview? Can you share a current estimate on when MS Teams support will be officially available?

Thanks!

**Comment by kerams** [comment]
@khouzam, if you have a moment to comment on this, it would me much appreciated!

**Comment by alex030293** [comment]
I've activated developer preview in Teams, but cards won't render. Do I need to active anything else?

Thanks.

**Comment by molly26dalton** [comment]
@serialoverflow - sorry for the delay. Dev preview should be available in the next few weeks. Please check-in here for more information 

https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference

@alex030293 - Once it's available for dev preview, you'll be able to use them.

**Comment by matthidinger** [comment]
Closing as this is now available in production :) Thanks for your interest, please keep the feedback coming!
