### ISSUE TITLE
[UWP] Add support for card-level selectActions

### ISSUE THREAD

**Issue by khouzam** [Microsoft/AdaptiveCards#1346]

**Comment by tuanh118** [comment]
@khouzam the outermost `selectAction` should not overwrite any inner `selectAction`, i.e., it is activated only when a non-action area is clicked right?

**Comment by tuanh118** [comment]
@khouzam @RebeccaAnne I have been investigating the behavior of `selectAction` and looks like `Inline`  `ShowCard` actions is intentionally ignored (https://github.com/Microsoft/AdaptiveCards/blob/master/source/uwp/Renderer/lib/XamlBuilder.cpp#L2567). Also, if selectAction mode is set to `Popup`, cards in the popup dialog don't have interactive actions.

These are current behaviors of any `selectAction` at the moment (for containers, images, column sets, and columns). I looked into potential fix, but it seems to entail substantial code change and will require more investigation.

Should I wrap up this story's code or continue to fix the issues?

**Comment by RebeccaAnne** [comment]
If card level select action is working the same as other select actions I think that's sufficient for this issue. Let's log a separate issue to track the fact that we don't handle show card select actions (in general).
