### ISSUE TITLE
TextBlock missing a "numerical" style

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#136]
When you start using larger font sizes, those also implicitly add more space to the top before the actual pixels for the characters start.

Therefore, without an option to trim that initial padding from the numbers, using large fonts for things like displaying a count becomes impossible.

For example, the following tile notification would not look correct, since the large "5" would actually be displayed several pixels lower, due to the larger line height of the larger font size.

![image](https://cloud.githubusercontent.com/assets/13246069/23590397/fd905882-0193-11e7-8d81-bac328ee5f04.png)

**Comment by matthidinger** [comment]
@anbare we're having a hard time visualizing this one, can you possibly provide a screenshot with the current and expected outcome?

**Comment by anbare** [comment]
Here's the two examples. First one is what we would have today without a style that removes the descender space from the text area as Chris said, and the second image is what we would have if we introduced the style (which would be parity with Adaptive XML)

![image](https://user-images.githubusercontent.com/13246069/27997205-03e45298-64a8-11e7-8094-241234eda8ae.png) 
![image](https://user-images.githubusercontent.com/13246069/27997204-fec0dfac-64a7-11e7-8a5e-90d92c932cda.png)

**Comment by dclaux** [comment]
seems to me that the below can be accomplished with the proposed new spacing model, which allows for more control. I thought this was more about aligning say the top bar of the 5 with the top edge of an image for instance; that indeed can't be done, but the above I think we will be fine.

**Comment by andrewleader** [comment]
Closing as no active requests
