### ISSUE TITLE
[Android] crash in AdaptiveCard.DeserializeFromString()

### ISSUE THREAD

**Issue by KayMKM** [Microsoft/AdaptiveCards#1367]
Hi,

I am trying integrate Adaptive card SDK in a Android project. But I have a problem when I use AdaptiveCard.DeserializeFromString():

java.lang.UnsatisfiedLinkError: No implementation found for long com.microsoft.adaptivecards.objectmodel.AdaptiveCardObjectModelJNI.AdaptiveCard_DeserializeFromString(java.lang.String) (tried Java_com_microsoft_adaptivecards_objectmodel_AdaptiveCardObjectModelJNI_AdaptiveCard_1DeserializeFromString and Java_com_microsoft_adaptivecards_objectmodel_AdaptiveCardObjectModelJNI_AdaptiveCard_1DeserializeFromString__Ljava_lang_String_2)
                                                                            at com.microsoft.adaptivecards.objectmodel.AdaptiveCardObjectModelJNI.AdaptiveCard_DeserializeFromString(Native Method)
                                                                            at com.microsoft.adaptivecards.objectmodel.AdaptiveCard.DeserializeFromString(AdaptiveCard.java:105)

Could anyone take a look on this issue?

Thanks,
Yue

**Comment by eschavez** [comment]
Can you make sure you are on the latest? We are no longer in the com.microsoft.adaptivecards namespace. We moved to io.adaptivecards prior to the v1.0 release.

**Comment by eschavez** [comment]
Also, this issue is likely because you are not doing a call to `System.loadLibrary("adaptivecards-native-lib')`. This load call is no longer required so please update to latest.

**Comment by KayMKM** [comment]
Thank you for reply. I added io.adaptivecards:adaptivecards-android-arm:1.0.0 in the gradle. Isn't this the latest lib? And how can I get the latest lib?

**Comment by eschavez** [comment]
We removed arm from the package name. Latest should be io.adaptivecards-android:1.0.1. Sorry for the confusion.

**Comment by KayMKM** [comment]
@eschavez Got it. I get the package name from readme.md. I think you should update it.
