### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by KayMKM** [Microsoft/AdaptiveCards#1369]
Hi,

I used v1.0.1 in project now. But the build is failed with this log:
Error:Execution failed for task ':transformNativeLibsWithMergeJniLibsForLocalDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/armeabi-v7a/libc++_shared.so
  	File1: C:\Users\yuesu\.android\build-cache\865ea54445ecac9832b751ddaeb8fd05938fe7e5\output\jni
  	File2: C:\Users\yuesu\.android\build-cache\281e71cedee43876919d0950d3dd9035c83af4df\output\jni

Please help to take a look.

Thanks,
Yue

**Comment by eschavez** [comment]
The reason for this is that you have another module that has libc++_shared.so included and out project includes it as well. You can fix this simply by adding the following to your apps build.gradle file: 
`android {
  packagingOptions {
    pickFirst 'lib/armeabi-v7a/libassmidi.so'
  }
}`

**Comment by eschavez** [comment]
Please let us know if this doesn't solve it.

**Comment by KayMKM** [comment]
It works. Thank you!
