### ISSUE TITLE
[Android] App crashes when rendering card in SDK 19 

### ISSUE THREAD

**Issue by rednivrug15** [Microsoft/AdaptiveCards#1371]
The android app crashes when the following JSON payload is used with SDK 19 ( Using the Sample App ). 

`{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [{
		"type": "Container",
		"items": [{
			"type": "TextBlock",
			"text": "Publish Adaptive Card schema",
			"weight": "bolder",
			"size": "medium"
		}, {
			"type": "ColumnSet",
			"columns": [{
				"type": "Column",
				"width": "auto",
				"items": [{
					"type": "Image",
					"url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg",
					"size": "small",
					"style": "person"
				}]
			}, {
				"type": "Column",
				"width": "stretch",
				"items": [{
					"type": "TextBlock",
					"text": "Matt Hidinger",
					"weight": "bolder",
					"wrap": true
				}, {
					"type": "TextBlock",
					"spacing": "none",
					"text": "Created {{DATE(2017-02-14T06:08:39Z, SHORT)}}",
					"isSubtle": true,
					"wrap": true
				}]
			}]
		}]
	}, {
		"type": "Container",
		"items": [{
			"type": "TextBlock",
			"text": "Now that we have defined the main rules and features of the format, we need to produce a schema and publish it to GitHub. The schema will be the starting point of our reference documentation.",
			"wrap": true
		}, {
			"type": "FactSet",
			"facts": [{
				"title": "Board:",
				"value": "Adaptive Card"
			}, {
				"title": "List:",
				"value": "Backlog"
			}, {
				"title": "Assigned to:",
				"value": "Matt Hidinger"
			}, {
				"title": "Due date:",
				"value": "Not set"
			}]
		}]
	}],
	"actions": [{
		"type": "Action.ShowCard",
		"title": "Set due date",
		"card": {
			"type": "AdaptiveCard",
			"body": [{
				"type": "Input.Date",
				"id": "dueDate"
			}],
			"actions": [{
				"type": "Action.Submit",
				"title": "OK"
			}]
		}
	}, {
		"type": "Action.ShowCard",
		"title": "Comment",
		"card": {
			"type": "AdaptiveCard",
			"body": [{
				"type": "Input.Text",
				"id": "comment",
				"isMultiline": true,
				"placeholder": "Enter your comment"
			}],
			"actions": [{
				"type": "Action.Submit",
				"title": "OK"
			}]
		}
	}, {
		"type": "Action.OpenUrl",
		"title": "View",
		"url": "http://adaptivecards.io"
	}]
}`

**Comment by eschavez** [comment]
I see the issue from logcat:

04-12 18:32:15.315 4468-4468/io.adaptivecards.adaptivecardssample I/dalvikvm: Could not find method android.text.Html.fromHtml, referenced from method io.adaptivecards.renderer.readonly.TextBlockRenderer.render
04-12 18:32:15.325 4468-4468/io.adaptivecards.adaptivecardssample W/dalvikvm: VFY: unable to resolve static method 20383: Landroid/text/Html;.fromHtml (Ljava/lang/String;ILandroid/text/Html$ImageGetter;Landroid/text/Html$TagHandler;)Landroid/text/Spanned;

Still investigating why this failed.

**Comment by almedina-ms** [comment]
quick update: looks like the real issue is the return value from the method wcsftime
