### ISSUE TITLE
Support custom image URIs, enabling symbols and URI schemes like ms-appx

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#138]
# Implementation status
- [ ] TypeScript
- [x] UWP (PR #638)
- [x] WPF
- [x] iOS
- [x] Android
- [x] Documentation

# Scenarios  
Enables Card authors to use custom URL schemes for Images, e.g., a set of icons that are packaged within a particular app, or specialized form of URL resolution.

## Scenario: Custom Icons
The Skype app could include a custom set of icons that are packaged within their app, e.g., a set of Media player icons. A developer could reference those icons by using a custom `icon:` scheme that Skype controls and documents.

```json
{
"type":"image",
"url":"skype-icon:play",
}
```

## Scenario: ms-appx resolution
Host apps like Timeline and Action Center can resolve ms-appx URLs to the correct package that contains the assets.

```json
{
"type":"image",
"url":"ms-appx://foo.png",
}
```

# Design

Renderers provide an API to register a custom `ResourceResolver` for a specific scheme. Hosts can override http/https images too.

## Host App
```csharp
renderer = new AdaptiveCardRenderer();

// Provide custom resource resolver
renderer.ResourceResolvers.Set("ms-appx", new MsAppxResourceResolver());

// Host implements the resolver like seen below
private class MsAppxResourceResolver : IAdaptiveCardResourceResolver
{
    public IAsyncOperation<IRandomAccessStream> GetResourceStreamAsync(XamlCardGetImageStreamArgs args)
    {
        return GetResourceStreamHelperAsync(args).AsAsyncOperation();
    }

    private async Task<IRandomAccessStream> GetResourceStreamHelperAsync(XamlCardGetImageStreamArgs args)
    {
        StorageFile file = await StorageFile.GetFileFromApplicationUriAsync(args.Url);
        return await file.OpenAsync(FileAccessMode.Read);
    }
}
```

## Interface of IAdaptiveCardResourceResolver
Note that each platform will have their own style of Resolver. For WinRT, it returns an IRandomAccessStream, since that's what WinRT uses. Other platforms might use a byte[] or something else.

```csharp
// Resource resolvers have the following interface
public interface IAdaptiveCardResourceResolver
{
    IAsyncOperation<IRandomAccessStream> GetResourceStreamAsync(XamlCardGetImageStreamArgs args);
}
```

# Fallback URL
Introduce fallbackBack url in case the primary URL doesn't load an image

```json
{
"type":"image",
"url":"skype-icon:play",
"fallbackUrl":"http://mysite.com/play.png"
}
```

**Comment by anbare** [comment]
Toasts need this so we can use our own platform image cache for http images, and so we can resolve ms-appx/appdata images

**Comment by paulcam206** [comment]
Documentation is done and in the mahiding/site1.1 branch.

**Comment by RebeccaAnne** [comment]
Closing this issue as resource resolvers for JS are now tracked by #3643.
