### ISSUE TITLE
Add readme to image renderer

### ISSUE THREAD

**Issue by Claessens14** [microsoft/AdaptiveCards#1397]
I would like to use the image renderer for the adaptive cards that is found here..
https://github.com/Microsoft/AdaptiveCards/tree/master/source/dotnet/Samples/ImageRendererServer
However, I don't use c# and would like to just deploy it to Azure. Would it be possible if that folder had a readme with a 'deploy to Azure' button so people could implement this solution with a click of a button?

**Comment by ignacionr** [comment]
@Claessens14 to be honest, I started using that rendered and the results were not good. Had much more reliable and customizable images by using headless chrome (puppet) with jsdom and the more robust HTML renderer.

In the process I did have to extend an old dependency of jsdom to support flex, so if you use this path make sure you get this commit https://github.com/jsakas/CSSStyleDeclaration/pull/56/commits/a8fc29c1a49829e89efe8dea6d1acd61aa78499f .

Hope this helps and remember to take it as just another users personal opinion.
