### ISSUE TITLE
Consider adding Input.File

### ISSUE THREAD

**Issue by ignacionr** [microsoft/AdaptiveCards#1416]
> As a user of a hardware store, I want to provide their bot with a picture of the little-thing-that-fits-on-the-other-little-thing, so the bot can suggest a description, pricing, or other options.

```json
{
    "type": "Input.File",
    "id": "user-provided-picture"
}
```

**Comment by andrewleader** [comment]
Thanks! We've captured this feedback in our feedback system and will let you know if/when we implement this.
