### ISSUE TITLE
Crash when image size is zero

### ISSUE THREAD

**Issue by an888ha** [Microsoft/AdaptiveCards#1419]
App Crashing when scrolling fast in a view which has multiple adaptive cards iOS
App is crashing when we have multiple adaptive cards in a view having sanitized image urls. The reason being image.width = 0.
Multiplier is not finite!  That's illegal.  multiplier:nan
(
	0   CoreFoundation                      0x000000011bf091e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000011b5a6031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000011bf0e472 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00000001168ae652 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   Foundation                          0x0000000116832840 -[NSLayoutConstraint _setMultiplier:] + 336
	5   Foundation                          0x0000000116832567 +[NSLayoutConstraint constraintWithItem:attribute:relatedBy:toItem:attribute:multiplier:constant:] + 248
	6   AdaptiveCards                       0x000000010ed16087 __36-[ACRView processImageConcurrently:]_block_invoke_2 + 421
	7   libdispatch.dylib                   0x000000011796c807 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x000000011796d848 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x000000011797892b _dispatch_main_queue_callback_4CF + 628
	10  CoreFoundation                      0x000000011becbc99 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	11  CoreFoundation                      0x000000011be8fea6 __CFRunLoopRun + 2342
	12  CoreFoundation                      0x000000011be8f30b CFRunLoopRunSpecific + 635
	13  GraphicsServices                    0x000000011e68ca73 GSEventRunModal + 62
	14  UIKit                               0x0000000117ad30b7 UIApplicationMain + 159
	15  TeamsAppCore                        0x000000010f75d4aa AXPApplicationMain + 58
	16  TeamSpaceApp                        0x000000010e2c0ec9 main + 393
	17  libdyld.dylib                       0x000000011c402955 start + 1
)

**Comment by msmoosa** [comment]
The reason being image.width = 0.
