### ISSUE TITLE
Adaptive Card Markdown not working.

### ISSUE THREAD

**Issue by Kartik1607** [Microsoft/AdaptiveCards#1421]
Hi,
I am creating an adaptive card with this code 
```C#
var ac = new AdaptiveCards.AdaptiveCard()
            {
                Body = new List<AdaptiveCards.AdaptiveElement>()
                {
                    new AdaptiveCards.AdaptiveTextBlock()
                    {
                        Text = "**Hello ** world to [adaptivecards](https://wwww.adaptivecards.io)"
                    }
                }
            };

            var message = context.MakeMessage();
            message.Attachments.Add(new Attachment() { ContentType = AdaptiveCard.ContentType, Content = ac });
            await context.PostAsync(message);
```

The output produced (in Webchat) is ![output](https://imgur.com/xjtNaEc.png)

According to [Adaptive card website](https://docs.microsoft.com/en-us/adaptive-cards/create/textfeatures) markdown is supported.

More Info : 
Adaptive card version : 1.0
WebChat version : 0.12.1-pre

**Comment by matthidinger** [comment]
Hi @Kartik1607, to make the `adaptivecards.js` bundle smaller, and allow customers to use their own markdown library we no longer bundle a default markdown implementation in the JavaScript renderer.

The easiest way to get it going would be to include a <script> tag with `markdown-it` before the webchat library, outlined here:

https://www.npmjs.com/package/adaptivecards#render-a-card

```javascript
// For markdown support you need a third-party library
// E.g., to use markdown-it, include in your HTML page:
//     <script type="text/javascript" src="https://unpkg.com/markdown-it/dist/markdown-it.js"></script>
// And add this code to replace the default markdown handler:
//     AdaptiveCards.processMarkdown = function(text) { return markdownit().render(text); }
```

**Comment by Kartik1607** [comment]
I am currently using custom implementation of webchat forked from [here] (https://github.com/Microsoft/BotFramework-WebChat) 

It already includes the markdown-it, so I would have to update the webchat itself for it to work. Also, this mean that the [documentation on Microsoft website](https://docs.microsoft.com/en-us/adaptive-cards/create/textfeatures) is invalid as of now.

This is actually a breaking change, for which I found no post. This should be known to end user.

**Comment by Kartik1607** [comment]
@matthidinger This is solvable for webchat. Is it guaranteed that markdown will/will not work in other channels like skype?

**Comment by matthidinger** [comment]
Markdown is working in the Teams preview and is planned to be supported in Skype as well.

**Comment by Kartik1607** [comment]
Hey, allow me put a point for suggestion regarding to include / not to include markdown by default.
As you said, the markdown library was removed to reduce the bundle size.
This causes a few side effects.
1. Customer can not directly use webchat and now needs to use custom build of directline adding additional development effort.
2. There is inconsistent behavior between different channels which use adaptive cards. I would expect skype to render adaptive card similarly to cortona, webchat etc. (minus the themes)
3. The markdown library size is not that big and would be cached any how if customer returns to webchat.
4. Developer can easily change the markdown library anyhow when he wish to go use a custom one.

My point is that essential features like markdown should be supported by default. Please do not add additional burden of including them. A customer should be simply able to grab iFrame of webchat, paste it into html and have his bot running. Customer should only go down the path of custom build if some additional features are needed.

I expect adaptive cards to be important for Microsoft as they were shown at the build event. They must be easy to implement out of the box.

**Comment by compulim** [comment]
@Kartik1607 Since Markdown-It was bundled in Web Chat for things other than Adaptive Cards, Web Chat will expose it via `window.markdownit`, so Adaptive Cards 1.0 can pick it up without the need for the user to bundle it themselves.

**Comment by Kartik1607** [comment]
@compulim Totally agree that markdown should not pollute the global namespace. Looks like adaptive card checks for markdownit specifically at  [this line](https://github.com/Microsoft/AdaptiveCards/blob/master/source/nodejs/adaptivecards/src/card-elements.ts#L4827) and even if we wanted to use a different markdown library, it would only look for markdownit, which would defeat the purpose of

>  allow customers to use their own markdown library

Also for Adaptive Cards team, why the heck is all the code in one massive 5000 line of file. Why no componentization?

**Comment by dclaux** [comment]
@Kartik1607 you can override Markdown processing by setting AdaptiveCard.processMarkdown to your own handler instead of using the default one. You are not tied to markdown-it.

Was "why the heck" really necessary?

**Comment by compulim** [comment]
Updated PR #1034 to use `AdaptiveCard.processMarkdown` instead of `window.markdownit`.

**Comment by Kartik1607** [comment]
@dclaux Sometimes emotions overpower a person.  Looking at those many lines in a single file was one of that moment. Sorry for being toxic.

**Comment by ignacionr** [comment]
@Kartik1607 one way to build a constructive conversation is look on the existing issues like https://github.com/Microsoft/AdaptiveCards/issues/1652 and taking it from what's already in discussion. Just saying.
