### ISSUE TITLE
[ios]App Crashes on valid json

### ISSUE THREAD

**Issue by kratijain-microsoft** [Microsoft/AdaptiveCards#1429]
This json renders fine in adaptive cards Visualizer tool and android sdk. But for ios sdk, it crashes throwing EXC_BAD_ACCESS. Also there is a ACRParseErrorDomain with code 3.

 {"version":"1.0","body":[{"type":"TextBlock","size":"large","text":"Issue opened: \"Push notifications not working\""},{"type":"Container","items":[{"type":"ColumnSet","columns":[{"type":"Column","width":"auto","items":[{"size":"small","style":"person","type":"Image","url":"http:\/\/connectorsdemo.azurewebsites.net\/images\/MSC12_Oscar_002.jpg"}]},{"type":"Column","width":"stretch","items":[{"wrap":"true","weight":"bolder","type":"TextBlock","text":"Miguel Garcie"},{"text":"9\/13\/2016, 11:46am","wrap":"true","isSubtle":"true","type":"TextBlock","spacing":"none"}]}]},{"type":"FactSet","facts":[{"title":"Repository:","value":"mgarcia\\test"},{"title":"Issue #:","value":"176715375"}]}]}],"type":"AdaptiveCard","$schema":"http:\/\/adaptivecards.io\/schemas\/adaptive-card.json"}

**Comment by nesalang** [comment]
dup of #1418 
json payload provided does't work with web visualizer.

**Comment by kratijain-microsoft** [comment]
@nesalang The json payload is working fine in the Visualizer (http://adaptivecards.io/visualizer/index.html?hostApp=Bot%20Framework%20WebChat) Can you please check again.

**Comment by kratijain-microsoft** [comment]
Please try this json.
{
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "size": "large",
      "text": "Issue opened: \"Push notifications not working\""
    },
    {
      "type": "Container",
      "items": [
        {
          "type": "ColumnSet",
          "columns": [
            {
              "type": "Column",
              "width": "auto",
              "items": [
                {
                  "size": "small",
                  "style": "person",
                  "type": "Image",
                  "url": "http://connectorsdemo.azurewebsites.net/images/MSC12_Oscar_002.jpg"
                }
              ]
            },
            {
              "type": "Column",
              "width": "stretch",
              "items": [
                {
                  "wrap": "true",
                  "weight": "bolder",
                  "type": "TextBlock",
                  "text": "Miguel Garcie"
                },
                {
                  "text": "9/13/2016, 11:46am",
                  "wrap": "true",
                  "isSubtle": "true",
                  "type": "TextBlock",
                  "spacing": "none"
                }
              ]
            }
          ]
        },
        {
          "type": "FactSet",
          "facts": [
            {
              "title": "Repository:",
              "value": "mgarcia\\test"
            },
            {
              "title": "Issue #:",
              "value": "176715375"
            }
          ]
        }
      ]
    }
  ],
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}

**Comment by kratijain-microsoft** [comment]
Found the issue. The json works fine for web and android but for ios, it expects true instead of "true". I fixed the json and it started rendering the card.
