### ISSUE TITLE
Adaptive Cards Renderer for React-Native

### ISSUE THREAD

**Issue by ryanzjohnson** [microsoft/AdaptiveCards#1438]
I noticed you don't have a renderer for react-native, any plan to support react and react-native in the future?

**Comment by ignacionr** [comment]
There’s a status column here for a React renderer https://docs.microsoft.com/en-us/adaptive-cards/display/rendererstatus but it seems no-one has tackled it yet.
In my experience, this team is very receptive so if you plan to start it make your fork and PR away. They review actively.
My team is also very interested on a react renderer, esp react-native.

**Comment by IbrahimSulai** [comment]
Adaptive cards - whether support is enabled for react-native?

Thanks in advance for reply.

**Comment by Kevin-Chung** [comment]
Seems to be an official Microsoft repo for this https://github.com/Microsoft/react-native-adaptivecards

**Comment by IbrahimSulai** [comment]
@Kevin-Chung - When I am trying to integrate the above repo, facing many issues in UI.

**Comment by IbrahimSulai** [comment]
I have used the new Microsoft repo for adaptive cards - https://github.com/Imaginea/AdaptiveCards/tree/master/source/reactnative
which rendering adaptive cards properly and working as expected.

**Comment by Kevin-Chung** [comment]
Thanks for this, definitely worth looking into

**Comment by andrewleader** [comment]
React Native renderer is community-official now thanks to the Imaginea folks!

### Community SDKs

The following SDKs are lovingly maintained by the Adaptive Cards community. Their contributions are sincerely appreciated! 🎉

|Platform|Install|Build|Docs|Status|Maintainer|
|---|---|---|---|---|---|
| ReactNative | [![npm install](https://img.shields.io/npm/v/adaptivecards-reactnative.svg)](https://www.npmjs.com/package/adaptivecards-reactnative) | [Source](https://github.com/Microsoft/AdaptiveCards/tree/master/source/community/reactnative)| [Docs](https://github.com/Microsoft/AdaptiveCards/blob/master/source/community/reactnative/README.md) | [![Build status](https://dev.azure.com/microsoft/AdaptiveCards/_apis/build/status/PR%20Validation/AdaptiveCards-ReactNative-Android-CI)](https://dev.azure.com/microsoft/AdaptiveCards/_build/latest?definitionId=38416) | [Imaginea](https://github.com/Microsoft/AdaptiveCards/blob/master/source/community/reactnative/Contributors.md)
