### ISSUE TITLE
Unify the Object Model Across Languages

### ISSUE THREAD

**Issue by ignacionr** [microsoft/AdaptiveCards#1450]
Currently, different language implementations may offer slightly different object models. One example could be that on C# there is a constructor for TextBlock that conveniently takes the text to be presented, whereas an equivalent feature for C++ (and correspondingly JNI) does not exist.

On JavaScript, the object model is basically not prepared to be used for producing cards (create an empty AdaptiveCard, try to parse it, you get a number of issues). I am guessing this is out of the assumption that directly creating the JSON is more convenient from JavaScript that resorting to the model. I would agree, yet a standardized API would be of value anyhow.

A possible solution would be to find/create a DSL that allows for a generic definition of tests that can run within different languages. In my mind it would look something like this.

```
TEST_GROUP_PROLOGUE(ParseUtilTest)
TEST_PROLOGUE(SelectActionEmptyJsonTest)
TEST_VERSION("C++")
        {
            auto elementParserRegistration = std::make_shared<ElementParserRegistration>();

            auto actionParserRegistration = std::make_shared<ActionParserRegistration>();

            Json::Value json;

            std::shared_ptr<BaseActionElement> selectAction = ParseUtil::GetSelectAction(
                elementParserRegistration,
                actionParserRegistration,
                json,
                AdaptiveCardSchemaKey::SelectAction,
                false);

            Assert::IsTrue(selectAction == nullptr);
        }
TEST_VERSION("C#")
        {
            var elementParserRegistration  = new ElementParserRegistration();
            var actionParserRegistration = new ActionParserRegistration();

            var selectAction = ParseUtil.GetSelectAction(
                elementParserRegistration,
                actionParserRegistration,
                json,
                AdaptiveCardSchemaKey::SelectAction,
                false);

            Assert.IsTrue(selectAction == null);
        }
TEST_EPILOGUE()
TEST_GROUP_EPILOGUE()
```

**Comment by andrewleader** [comment]
Closing as stale
