### ISSUE TITLE
hostConfig with Bot Framework

### ISSUE THREAD

**Issue by isteven** [microsoft/AdaptiveCards#1451]
Hi all,

I'm trying to integrate the adaptive card into my bot (using NodeJs + Ms Bot Framework). The target channel is Facebook Messenger - at least for now.

My design requires me to modify some parameters in the hostConfig file. The question is, how do I include/require this hostConfig file (or values) into the bot?

Thanks.

**Comment by andrewleader** [comment]
You cannot edit the hostConfig used when cards appear on Facebook Messenger, that is controlled by the Bot Framework. You can submit a feature request to the Bot Framework team!
