### ISSUE TITLE
[ios][Teams]Need to override Layout Renderer so that more than 5 buttons can wrap to next line instead of truncating.

### ISSUE THREAD

**Issue by kratijain-microsoft** [Microsoft/AdaptiveCards#1459]
We want to override the view for rendering actions so that we can either wrap them to next line or enable horizontal scrolling when we have more actions as compared to screen width.

**Comment by kratijain-microsoft** [comment]
The screenshot shows a blue line on the left which is the 5th button 
<img width="572" alt="screen shot 2018-04-26 at 1 56 19 pm" src="https://user-images.githubusercontent.com/38986011/40114668-6f6b297e-592b-11e8-9b14-16e2e3a92f7f.png">

**Comment by nesalang** [comment]
PR 1445 will fix the issue.
