### ISSUE TITLE
[ios][Teams]Text is truncated in full rendered card

### ISSUE THREAD

**Issue by kratijain-microsoft** [Microsoft/AdaptiveCards#1462]
We implemented the callback for didLoadElements to ensure card is shown only after full content is loaded and height is calculated. But still we are getting text truncated as shown below:

![simulator screen shot - iphone 8 - 2018-05-16 at 17 04 56](https://user-images.githubusercontent.com/38986011/40114779-c0340f7e-592b-11e8-8847-da03076f956e.png)

**Comment by nesalang** [comment]
Can you share your json payload and hostconfig used? let me try it on my end.

**Comment by nesalang** [comment]
I was able to reproduce the issue.
In addition to didLoadElements delegates, setting appropriate compression resistance priority was also required to completely resolve it on my end. I will create PR hopefully by tomorrow. 
Thanks

**Comment by kratijain-microsoft** [comment]
The issue persists in case of expanded show card. Attaching the screenshot for same. Button and multiline is truncated.
![simulator screen shot - iphone 8 - 2018-05-30 at 15 50 18](https://user-images.githubusercontent.com/38986011/40714821-4e89695e-6421-11e8-8303-784b5e171e33.png)
