### ISSUE TITLE
inlineAction on text boxes

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#147]
<table>
<tr>
<th>Release</th>
<th>Renderer status</th>
<th>Tasks status</th>
</tr>
<tr>
<td>1.2
<td>✔️ .NET (#1359)<br/>🔄 Android (#2671)<br/>🔄 iOS (#2672)<br/>🔄 TS (#1360)<br/>✔️ UWP (#1283)</td>
<td>✔️ Shared (#1282)<br/>🔄 Designer (#2674)</td>
</tr>
</table>

# Solves requests

* Ability to display image button to right of input for quick-reply toast (#1992)

## Example Comps

![image](https://cloud.githubusercontent.com/assets/13246069/23772874/80ea60e8-04d1-11e7-960c-ab01ff951c76.png)

Notice how Android notifications choose to display the button as part of the text input. The payload should allow this flexibility for the host to display the button however makes sense.

![image](https://user-images.githubusercontent.com/13246069/45708997-b6d7ee00-bb37-11e8-9efd-0d61ff3b263f.png)

# Spec

## Schema Changes

On only **Input.Text** (since that seems to be the only place a quick action would be desired on an input), the following property would be added...

| Property | Type | Required | Description |
|---|---|---|---|
| **type**| Input.Text | true | |
| **inlineAction** | Action | false | The inline action for the input. Typically displayed to the right of the input. Strongly recommended you provide an icon on the action (which will be displayed instead of the title of the action). |

## Schema example

```json
{
  "type": "Input.Text",
  "id": "comment",
  "placeholder": "enter comment",
  "inlineAction": {
    "type": "Action.Submit",
    "iconUrl": "ms-appx:///Assets/reply.png",
    "title": "Reply"
  }
}
```

## Renderer Requirements

* A renderer **must** display the inlineAction however the native platform typically displays actions related to a text input. For example, on UWP, should be displayed like the following

![image](https://cloud.githubusercontent.com/assets/13246069/23772874/80ea60e8-04d1-11e7-960c-ab01ff951c76.png)

Android might display like the following...

![image](https://user-images.githubusercontent.com/13246069/45708997-b6d7ee00-bb37-11e8-9efd-0d61ff3b263f.png)

  * If there is an icon on the action, simply use the icon (don't display the text). The title text should be used as a tooltip on the action.
    * The icon should use the same fitting behavior as normal icon actions (if the icon is 100px tall and only 50px wide, it should behave the same here as it does when it's a normal icon action)
  * If there's no icon, display the title instead.

![image](https://user-images.githubusercontent.com/13246069/45234276-13125680-b28a-11e8-9121-b318105c9591.png)

  * Inline expansion of Action.ShowCard is NOT supported (since we don't support inline showcards within the body right now). If a show card is present and the host is configured for inline show cards the action will be dropped and a warning will be returned.

* A renderer **must** invoke the inlineAction when the user performs the native platform action for submitting a text field...
  * For example...
    * On UWP...
      * For a single line text input, enter will trigger the action (shift-enter and ctrl-enter will be ignored).
      * For a multiline text input, enter will add a newline.
    * On iOS
      * If isMultiline is NOT enabled
        * The virtual keyboard should display the "submit" button and pressing that should submit the button.
      * If isMultiline IS enabled
        * The virtual keyboard should be left as-is (leaving the normal enter button that adds a newline, since otherwise there's no way to add newlines).
* Renderers **must** assign a style of `InlineAction` (or whatever the renderer standard for style names is) to the button so that hosts can natively style the button as they wish

## Downlevel Impact

**High**

This will not be able to render properly, and the card will be unfunctional.

Host impact: **Medium**. Hosts need to update their native styling to include this new InlineAction button.

## Related features

* Associating a text box enter press with an action: #333 

# Auto-generated task status

- [x] Shared
- [ ] Designer
- [x] .NET
- [ ] Android
- [ ] iOS
- [ ] TS
- [x] UWP

**Comment by anbare** [comment]
(nvm, will open new issue on ability to associate input with text box for Ctrl+Enter)

**Comment by anbare** [comment]
Actually we do have to re-open this. Using two columns with a size = auto on the image column doesn't work, as seen below

![image](https://cloud.githubusercontent.com/assets/13246069/26082368/54d317ce-3984-11e7-81ba-e11f328869c0.png)

There's no way to force the image to match the height of the text box. The airplane seen there displays taller than the text box itself.

Maybe we need a size property on the image itself that is "button" or something? Or even better, "squareButton".

**Comment by dclaux** [comment]
Would the ability to vertically center content in both columns solve the problem?

**Comment by anbare** [comment]
Vertically center wouldn't force the image to match the height of the text box. If the image is 200 px tall and the text box is only 80 px tall, you're still going to have 60 px of blank space above and below the text box

**Comment by dclaux** [comment]
Why not use an image that's as tall as the input then? You control the input's height. Plus you probably don't want a stretched or downsized image anyway?

**Comment by anbare** [comment]
How does the card author control the input height? Each card host might have different input heights. We don't want devs needing to provide different images for each host.

Plus, what happens in a future release when a card host decides "My input text boxes are now going to be 90px tall instead of 80px", all existing cards being sent will look incorrect.

Guidance would definitely be "Provide the correct resolution image", but the reality is, that can't be the only solution due to its drawbacks (future app-compat issues being the key drawback).

**Comment by dclaux** [comment]
The host controls the height of the inputs and the available image sizes. It could be a convention that the "small" image size is the same height as an input, but there is no guarantee.
Also the vertical alignment solution I think could be a decent compromise. Yes, there is no guarantee the image would be the same height as the input, but at least things would be properly aligned.
I'm just trying to find a solution in the confines of the format before jumping to the conclusion we need something new. You have great points; I think we'll have to sit together and discuss.

**Comment by anbare** [comment]
I think a new image size, `"size": "squareImageButton"` might be the most elegant solution. I prototyped it in the UWP renderer, and this is what it looks like

![image](https://user-images.githubusercontent.com/13246069/26942638-a504083c-4c37-11e7-912d-3e1d0082dd01.png)

```json
      {
        "type": "ColumnSet",
        "columns": [
          {
            "type": "Column",
            "size": "stretch",
            "items": [
              {
                "type": "Input.Text",
                "id": "textInput",
                "placeholder": "reply"
              }
            ]
          },
          {
            "type": "Column",
            "size": "auto",
            "items": [
              {
                "type": "Image",
                "url": "Assets/Icons/send.png",
                "size":  "squareImageButton",
                "selectAction": {
                  "type": "Action.Submit",
                  "title": "Send"
                }
              }
            ]
          }
        ]
      }
```

Adding the new size allows hosts to still keep `small` for a different purpose rather than requiring `small` to match the height of inputs.

**Comment by matthidinger** [comment]
@anbare would you consider this necessary for v1 to ship notifications?

**Comment by anbare** [comment]
Without this that would mean the story is: "If you want to make a quick reply message toast, you have to use legacy XML"

Maybe that's an ok story, the scenarios that require new Card features like ShowCard and hit targets are all using normal buttons rather than quick reply buttons. But it's definitely not a perfect story.

**Comment by matthidinger** [comment]
What if we add something semantic like `quickReplyAction` on `Input.Text` (since that seems to be the only real-world scenario where a quick-reply would be used)

```json
 {
      "type": "Input.Text",
      "id": "comment",
      "placeholder": "enter comment",
      "maxLength": 500,
      "isMultiline": false,
      "speak": "What comments do you have?",
      "value": "This is a pre-filled value",
      "quickReplyAction": {
          { "type": "Action.Submit" }
   }
    }
```

**Comment by andrewleader** [comment]
Proposal needs more review time. Concerns around...

* Naming, maybe shouldn't be "quickReply"
* There should also be a way to define the "press enter" action without having an action to the right
* Ideally re-using existing elements instead of creating something new

**Comment by andrewleader** [comment]
Proposal is ready for another round of review

**Comment by andrewleader** [comment]
Open question around vertical alignment as the input grows. Align to the bottom?

**Comment by andrewleader** [comment]
Schema addition: When displaying as icon, the `title` should be displayed as a tooltip when hovering over button
