### ISSUE TITLE
[bug][Android][Teams] FactSet clips content and exceeds the width of the parent grid layout . Reproducible on sample app .

### ISSUE THREAD

**Issue by rednivrug15** [Microsoft/AdaptiveCards#1472]
Sample JSON payload 
`{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "FactSet",
            "facts": [
                {
                    "title": "This is a long FactSet that should wrap the title",
                    "value": "This is a long FactSet that can introduce wrapping for the value"
                },
                {
                    "title": "Fact 2",
                    "value": "Value 2"
                },
                {
                    "title": "Fact 3",
                    "value": "Value 3"
                },
                {
                    "title": "Fact 4",
                    "value": "Value 5"
                }
            ]
        }
    ]
}`

Sample screenshot :
![factset](https://user-images.githubusercontent.com/7874856/40177424-37eaa7be-59fc-11e8-8ff8-bdd8d8efe597.png)

**Comment by almedina-ms** [comment]
This one is already fixed

This is the PR that fixed this https://github.com/Microsoft/AdaptiveCards/pull/1563
