### ISSUE TITLE
Move cards from Tests folder to 1.1/vNext/<pending name> folder

### ISSUE THREAD

**Issue by almedina-ms** [Microsoft/AdaptiveCards#1480]
Move the files with properties not in 1.0 to the 1.1 folder instead of keeping them in the Tests folder

The files to be moved are:
v1.0/Scenarios/NotificationCard.json
Tests/ColumnSet.Input.Text.VerticalStretch.json
Tests/ColumnSet.VerticalStretch.json
Tests/ColumnSet_Container.VerticalStretch.json
Tests/VerticalStretch.json

**Comment by almedina-ms** [comment]
@RebeccaAnne @nesalang 
Can you add the jsons for properties that weren't present in v 1.0, I think it's going to be easier for the person that has to move the files later

**Comment by RebeccaAnne** [comment]
These got moved in #1957
