### ISSUE TITLE
Do not include .map files in npm publish output

### ISSUE THREAD

**Issue by wictorwilen** [microsoft/AdaptiveCards#1492]
Currently when bundling adaptive cards through the `botframework-webchat` npm package you get a set of webpack warnings. Referenced here https://github.com/Microsoft/BotFramework-WebChat/issues/974

The way to work around this warning is to delete the `.map` files in the build output or better remove them when publishing to the npm repository (through the `.npmignore` file)

**Comment by pschaeflein** [comment]
Problem also exists when bundling adaptive cards in a SharePoint Framework web part. The fix submitted by Wictor resolves the issue.

**Comment by jonmill** [comment]
This issue should be fixed in the recent versions of the package; if that is not the case, please re-open the issue and we'll engage. Thanks!
