### ISSUE TITLE
Not working in swift 

### ISSUE THREAD

**Issue by Bharath2r** [Microsoft/AdaptiveCards#1514]
This my code not working me please tell me how to resolve
let filePath = Bundle.main.path(forResource: "FlightItinerary", ofType: "json")
            print(filePath)
      let useselected =  try? String(contentsOfFile: filePath!, encoding: String.Encoding.utf8)
        let host =  try? String(contentsOfFile: Bundle.main.path(forResource: "FlightItinerary", ofType: "json")!, encoding: String.Encoding.utf8)
        self.hostconfigParseResult = ACOHostConfig.fromJson(host)
        var cardParseResult: ACOAdaptiveCardParseResult? = ACOAdaptiveCard.fromJson(useselected!)
        if (cardParseResult?.isValid)! {
            self.renderResult = ACRRenderer.render(cardParseResult?.card, config: self.hostconfigParseResult?.config, frame: CGRect(x: 0, y: 0, width: 200, height: 0))
        }
        if (self.renderResult?.succeeded)! {
            self.adcVc = (self.renderResult?.viewcontroller)!
            self.view2 = self.adcVc.view
            print("dsfsfs:>>> \(self.view2)")
    }
**This is error message below**
error: Execution was interrupted, reason: internal c++ exception breakpoint(-4)..
The process has been returned to the state before expression evaluation.

**Comment by nesalang** [comment]
closing it due to inactivity

**Comment by Bharath2r** [comment]
Adaptive card render successfully but action Submit delegate function not working 

this is my code
    func didFetchUserResponses(_ userResponses: [AnyHashable : Any]!) {
        print("usersss:>>> \(userResponses)")
    }

**Comment by nesalang** [comment]
@pandres95 Please add bridge header to your swift project.

Adding bridge header is straight forward. Add a new empty objective-c .m file, and click Yes when XCode ask for the permission for configuring the .m file for bridge header, then XC will add a new bridge header, there add the following line #import <AdaptiveCards/ACFramewor.h>
For more Info, please refer to https://stackoverflow.com/questions/24002369/how-to-call-objective-c-code-from-swift
