### ISSUE TITLE
[ios]Expanded show card truncates the card elements

### ISSUE THREAD

**Issue by kratijain-microsoft** [Microsoft/AdaptiveCards#1523]
Elements like buttons, multiline inputs are truncated when show card is tapped.
![simulator screen shot - iphone 8 - 2018-05-30 at 15 50 18](https://user-images.githubusercontent.com/38986011/40714938-9ca1a9ee-6421-11e8-8b5e-d6f56ce2292b.png)

**Comment by nesalang** [comment]
i believe this is addressed. please re-open it if not.
