### ISSUE TITLE
[ios]Clear all input fields when user press submit

### ISSUE THREAD

**Issue by kratijain-microsoft** [Microsoft/AdaptiveCards#1534]
![simulator screen shot - iphone 8 - 2018-05-31 at 14 13 49](https://user-images.githubusercontent.com/38986011/40772160-d95313f8-64dc-11e8-9399-bf1508753560.png)

**Comment by khouzam** [comment]
This is the behavior that we have in every renderer. Maybe that might be a new host configurable behavior, but for the time being it should remain consistent across the platforms. I don't think that it should be an iOS only issue.

**Comment by matthidinger** [comment]
You can have your bot update the card with a read only view after submit though. Bot Framework offers the ability to update a card with a new payload
