### ISSUE TITLE
[ios] Make choice doesnt open new view on tap

### ISSUE THREAD

**Issue by kratijain-microsoft** [Microsoft/AdaptiveCards#1535]
For Card 2, tapping on Make Choice doesnt open a new view on tapping.
![simulator screen shot - iphone 8 - 2018-05-31 at 14 15 19](https://user-images.githubusercontent.com/38986011/40772275-2841ec14-64dd-11e8-972a-ce37e9e3b5f1.png)

**Comment by nesalang** [comment]
not a sdk issue.
