### ISSUE TITLE
[Android]Constructors should be protected instead of private to allow extending of renderers instead of overwriting everything.

### ISSUE THREAD

**Issue by rednivrug15** [Microsoft/AdaptiveCards#1539]
All the constructor in the renderers currently have private constructors. Making it protected would help us to extend those renderers instead of having to override everything

**Comment by matthidinger** [comment]
Thanks for reporting this. I believe we were tracking this change previously and it may already be in master. 

@khouzam @tuanh118 could you confirm, and whether or not this will be in the next maven push?
