### ISSUE TITLE
Licensing Terms for Corporate Grade Applications

### ISSUE THREAD

**Issue by ignacionr** [Microsoft/AdaptiveCards#1542]
We're in Indonesia following this project and committing our own product to follow suit. This is a tough internal sell, especially considering our target audience are big banks (as such, institutions that require long term technology support).

- Today, AdaptiveCards is MIT license and we're fine to use it commercially. What does the future look like? Can our customers be sure those terms are not going to change in at least 5 years?

- Our most important host will shift towards react-native by the end of 2018; what chances to have support for a react-native renderer by then?

**Comment by dclaux** [comment]
I don't imagine our license terms will change, but if they do we wouldn't make them more restrictive. That said there can always be unforeseen circumstances.

We can't promise anything wrt an ETA for the React Native renderer, but I would say that end of 2018 doesn't seem like an unrealistic target.

**Comment by ignacionr** [comment]
Thanks for this answer @dclaux , within expected terms. As a company we will keep tracking both items. Do bear in mind that you have decided to give the industry an interesting and valuable tool; the more solid the licensing and support foundation, the better reach we all will have.

Keep up this great job.
