### ISSUE TITLE
Scrolling results in very poor performance. Repro on sample App. [iOS]

### ISSUE THREAD

**Issue by an888ha** [Microsoft/AdaptiveCards#1545]
We are facing performance issue while scrolling , Since Adaptive Card renders the views async , we are loading our table view cells after getting the callback from delegate(Did Load Elements).  Our Normal Chat cells are being rendered first and than Adaptive Cards cells comes , this results in jumping in some cells. 
Note :- We are caching the ACRViews , so this behavior is for the first time scroll only, once we scroll on cached views the performance is good.

**Comment by nesalang** [comment]
please try PR #1547

**Comment by nesalang** [comment]
will close it once PR 1547 and 1554 merged.
