### ISSUE TITLE
Availability of CppCoreChecks should depend on build system, not platform

### ISSUE THREAD

**Issue by ignacionr** [Microsoft/AdaptiveCards#1550]
E.g. I'm not building on Android, Apple, or Windows, and yet I don't have access to the Visual Studio-specific CppCoreCheck headers.

For now I will build defining ```__APPLE__``` but if you get into a third round of this, @paulcam206 I know you will come up with a proper way to isolate CppCoreChecks. For fellow C++ users?

https://github.com/Microsoft/AdaptiveCards/blob/17eeb8adb25b71482f00ca080b9ca3cc253b26a1/source/shared/cpp/ObjectModel/pch.h#L26

**Comment by paulcam206** [comment]
I think I should be able to add compiler detection to this :)

**Comment by paulcam206** [comment]
See #1552

**Comment by paulcam206** [comment]
Should be fixed with #1552. Please confirm and close :)

**Comment by ignacionr** [comment]
That's some show of love. Thank you all!
