### ISSUE TITLE
Adpative Forms - Submit Action not working

### ISSUE THREAD

**Issue by naveenprasaths** [Microsoft/AdaptiveCards#1565]
Hi,

I am trying to create an Adaptive forms using c#. I have installed Microsoft.AdaptiveCards Nuget package with Version 0.5.1 and Bot Builder version is 3.14.1.1. My card has rendered correctly in Skype channel. But on click of Submit button, Forms input data Json is not passing to the Bot framework Post Activity. Submit Type is "Action.Submit". But this is working in Web chat.

I am using the below code.

`var Makedmessage = context.MakeMessage();
                        AdaptiveCards.AdaptiveCard card = new AdaptiveCards.AdaptiveCard();
                        Attachment attach = new Attachment();
                        attach.ContentType = AdaptiveCards.AdaptiveCard.ContentType;
                        card.Body = new List<CardElement>() { new TextBlock() { Text = "Present a form and submit it back to the originator" }, new TextInput() { Id = 			"firstName", Placeholder = "What is your first name?" }, new TextInput() { Id = "lastName", Placeholder = "What is your last name?" } };
                        card.Actions = new List<ActionBase>() { new SubmitAction() { Title = "Action.Submit" } };
                        attach.Content = card;
                        Makedmessage.AttachmentLayout = AttachmentLayoutTypes.Carousel;
                        Makedmessage.Attachments.Add(attach);
                        await context.PostAsync(Makedmessage, CancellationToken.None);`

Also attached the screenshot.
![adaptivecardformsubmitbutton](https://user-images.githubusercontent.com/24312385/41025741-5f3f7ddc-6990-11e8-94cc-d51adf95aad8.png)

Can someone assist me on this?

**Comment by Kartik1607** [comment]
Skype does not support adaptivecards as of now. Full support is expected soon. Until then you would have to find a different approach

**Comment by anbare** [comment]
Closing as Skype doesn't yet support Adaptive Cards as Kartik said. Thanks Kartik!

**Comment by mukeshdewangan89** [comment]
Try changing the Title of **Action.Submit** button to **Submit**.
