### ISSUE TITLE
verify AdaptiveCards works with Swift

### ISSUE THREAD

**Issue by nesalang** [Microsoft/AdaptiveCards#1574]

**Comment by alessioarsuffi** [comment]
Hi, I've successfully integrated AdaptiveCards inside an iOS Sample Swift App.

This is my code:

    override func viewDidLoad() {
		super.viewDidLoad()
		// Do any additional setup after loading the view, typically from a nib.
		
		let cardParseResult: ACOAdaptiveCardParseResult = ACOAdaptiveCard.fromJson("{\"$schema\": \"http://adaptivecards.io/schemas/adaptive-card.json\",\"type\": \"AdaptiveCard\",\"version\": \"1.0\",\"body\": [{\"type\": \"TextBlock\",\"text\": \"Here are some cool photos\",\"size\": \"large\"},{\"type\": \"TextBlock\",\"text\": \"Sorry some of them are repeats\",\"size\": \"medium\",\"weight\": \"lighter\"},{\"type\": \"ImageSet\",\"imageSize\": \"medium\",\"images\": [{\"type\": \"Image\",\"url\": \"https://picsum.photos/200/200?image=100\"},{\"type\": \"Image\",\"url\": \"https://picsum.photos/300/200?image=200\"},{\"type\": \"Image\",\"url\": \"https://picsum.photos/300/200?image=301\"},{\"type\": \"Image\",\"url\": \"https://picsum.photos/200/200?image=400\"},{\"type\": \"Image\",\"url\": \"https://picsum.photos/300/200?image=900\"}]}]}")
		
		/// render result
		var renderResult = ACRRenderResult()
		
		if cardParseResult.isValid {
			renderResult = ACRRenderer.render(cardParseResult.card, config: nil, widthConstraint: 262)
		}
		
		if renderResult.succeeded {
			// access returned UIView object
			let containerView = UIView(frame: CGRect(x: 8, y: 60, width: 262, height: 500))
			let adaptiveView = renderResult.view
			containerView.addSubview(adaptiveView!)
			self.view.addSubview(containerView)
		}
	}

However, when i open UI debugger, I see that ACRView is misplaced. Autolayout says: "Position is ambiguous for ACRView" any suggestion?

**Comment by nesalang** [comment]
Try setting layout constraints between containerView and adaptiveView (leading, top and bottom), and have containerView to own the constraints.

**Comment by nesalang** [comment]
verified that adpativecards works with swift. but to close this issue, I want to verify cocoapod can integrate the framework for swift project without an issue.

**Comment by nesalang** [comment]
Verified that AdaptiveCards works with cocoapods for Swift project; however, it requires a bridge header. 
Adding bridge header is straight forward. Add a new empty objective-c .m file, and click Yes when XCode ask for the permission for configuring the .m file for bridge header, then XC will add a new bridge header, there add the following line `#import <AdaptiveCards/ACFramewor.h>` 
For more Info, please refer to https://stackoverflow.com/questions/24002369/how-to-call-objective-c-code-from-swift

**Comment by alessioarsuffi** [comment]
Hi guys, i'm back 😅

Can someone help me using AdaptiveCards inside a cocoa touch framework? I'm not able to accompish this task :/ 

thanks
