### ISSUE TITLE
Proposal: Container-level fallback mechanism

### ISSUE THREAD

**Issue by dclaux** [Microsoft/AdaptiveCards#1587]
# Implementation status

- [ ] .NET
- [ ] Android
- [ ] iOS
- [ ] JavaScript
- [ ] UWP
- [ ] Documentation

# Solves requests

* Ability to provide fallback elements when elements aren't supported #2018

# Problem
Currently, there are two fallback strategies employed when rendering a card:
- Version: if a host receives a card that has its version set to a value higher than what the host understands, the host can fall back to displaying the card's fallbackText property (if present)
- If an element in the body of the card is of a type the host doesn't understand, the host will drop that element entirely (e.g. not render it)

The existing fallback mechanisms were designed to address the problem of hosts not evolving at the same pace, e.g. Host A may have been updated to understand a new "graph" element type, while Host B hasn't yet been updated and doesn't understand "graph". If a card that makes use of the "graph" element reaches Host B, the "graph" element will simply not be rendered.

While that doesn't sound too bad, the "graph" element might be surrounded by other elements that make little or no sense on their own.

# Asks

* Outlook
  * A number of partners have asked for this. They want to use these new elements, but their clients are using old clients and would have to wait a while to use new features.

# Solution
In the previous example, the right solution would be for Host B to not render the "graph" element nor any other elements that are inherently associated with it.

The concept of "associated elements" exists in Adaptive in the form of Container, ColumnSet and Column (and the entire card itself, but that isn't very interesting in the context of this document.) A card author should be able to define the fallback strategy for these containers in such a way that if any of their child elements can't be rendered, then the entire container isn't rendered.

# Design
We will add a **fallbackStrategy** property to **Container**, **ColumnSet** and **Column**. Valid values for fallbackStrategy will be:
- **ignoreInvalidChildren (default)**: the container's behavior remains as it currently is, that is any child element that isn't understood simply isn't rendered
- **noInvalidChild**: if any of the container's children (including children of the containers it may contain, and including actions) isn't understood, the entire container is hidden.

Example (assuming the host displaying this card does NOT understand the "Graph" element type):
```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "This text block is always displayed."
        },
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "This text block makes no sense without the graph below it."
                },
                {
                    "type": "Graph"
                    … other graph properties
                }
            ]
        }
    ]
}
```

The above card would render as follows:
![image](https://user-images.githubusercontent.com/1334689/41309942-ea2216be-6e34-11e8-9e20-7ca797340adb.png)

If the **fallbackStrategy** of the container is set to **noInvalidChild**:

```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "This text block is always displayed."
        },
        {
            "type": "Container",
            "fallbackStrategy": "noInvalidChild",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "This text block makes no sense without the graph below it."
                },
                {
                    "type": "Graph"
                    ... other graph properties
                }
            ]
        }
    ]
}
```

The card now renders like this:
![image](https://user-images.githubusercontent.com/1334689/41309877-b86913ca-6e34-11e8-90e9-e32918e6af2c.png)

**OPEN QUESTION**: How does an author provide alternate content when the container gets dropped since there was an invalid child? Without that, this is only a partial solution to fallback, but they need to be able to provide alternate fallback content.

## Host Config
No changes.

## Down-level impact
**Low**. Card would operate as it does today, with no fallback strategy.

## Host burden
**None**. All logic built in to the renderer.

## Renderer Requirements

Needed

**Comment by ignacionr** [comment]
Somebody had mentioned the possible addition of an "important" mark so to identify elements that preferably kept under space shortage.

How would this play in relation to this? If as a host I can't render an "important" element shouldn't I give up regardless of the fallback strategy?

**Comment by dclaux** [comment]
I think those two things are unrelated. What I am proposing is a fallback mechanism so a renderer can better handle cards that contain elements or actions it doesn't understand. What you are describing is one possible aspect of adding "responsiveness" to Adaptive Cards, e.g. a mechanism by which a card can adjust to various screen space.

**Comment by andrewleader** [comment]
Proposal agreed except use only `fallbackElement` (should it be an array?) @dclaux please update!

**Comment by andrewleader** [comment]
Closing in favor of updated #2019
