### ISSUE TITLE
[ios]Sometimes activityImage is truncated due to activity label

### ISSUE THREAD

**Issue by kratijain-microsoft** [Microsoft/AdaptiveCards#1588]
![simulator screen shot - iphone 8 - 2018-06-13 at 00 49 42](https://user-images.githubusercontent.com/38986011/41312154-04d0335a-6ea4-11e8-85fc-cfdf2e364355.png)
<img width="389" alt="screen shot 2018-06-13 at 12 49 48 am" src="https://user-images.githubusercontent.com/38986011/41312160-0ad3c6cc-6ea4-11e8-80f7-253f76bd2dbd.png">

**Comment by nesalang** [comment]
could you share the json payload?

**Comment by kratijain-microsoft** [comment]
Here is the json:

{"version":"1.0","body":[{"type":"Container","items":[{"type":"TextBlock","text":"<p>My interests<\/p>","weight":"bolder"},{"type":"ColumnSet","columns":[{"type":"Column","width":"auto","items":[{"size":"small","style":"person","type":"Image","url":"https:\/\/urlp.asm.skype.com\/v1\/url\/content?url=https%3a%2f%2fwww.bing.com%2fth%3fid%3dON.E494C2CE0D742AE613571B211B0CC159%26pid%3dNews%26c%3d7%26w%3d200%26h%3d150"}]},{"type":"Column","width":"stretch","items":[{"text":"<p>Cats<br>\r\n\n\n<a href=\"https:\/\/newspro.microsoft.com\/promotion?url=https%3a%2f%2fwww.bizjournals.com%2fsanjose%2fnews%2f2018%2f05%2f29%2fgoogle-doesn-t-hate-owls-it-just-loves-cats.html&amp;id=395178&amp;scope=3&amp;guid=878cd5ed47506f19c634c6379189fbd5&amp;signature=83aa5471c779c9af9e492a7216101234&amp;t2=20180529\" title=\"Google doesn’t hate owls. It just loves cats.\">Google doesn’t hate owls. It just loves cats.<\/a><\/p>","wrap":true,"isSubtle":true,"type":"TextBlock","spacing":"none"},{"text":"<p>Editor's note: This story is available as a result of a content partnership with The New York Times. Subscribers will see stories like this every day on ...<br>\r\n\n\nThe Business Journals<\/p>","wrap":true,"isSubtle":true,"type":"TextBlock","spacing":"none"}]}]}]},{"type":"Container","items":[{"type":"ColumnSet","columns":[{"type":"Column","width":"auto","items":[{"size":"small","style":"person","type":"Image","url":"https:\/\/urlp.asm.skype.com\/v1\/url\/content?url=https%3a%2f%2fwww.bing.com%2fth%3fid%3dON.994C6A21B0DB99A343991729A64C009D%26pid%3dNews%26c%3d7%26w%3d200%26h%3d150"}]},{"type":"Column","width":"stretch","items":[{"text":"<p>Cats<br>\r\n\n\n<a href=\"https:\/\/newspro.microsoft.com\/promotion?url=http%3a%2f%2fsacramento.cbslocal.com%2f2018%2f05%2f28%2fpanik-starts-river-cats-rehab-pence-gets-closer-to-finishing%2f&amp;id=395178&amp;scope=3&amp;guid=4aec6806b7e725a8eae53a0033846321&amp;signature=3d093d1e99bbaa892b7e3463335c7cb0&amp;t2=20180529\" title=\"Panik Starts River Cats Rehab, Pence Gets Closer To Finishing\">Panik Starts River Cats Rehab, Pence Gets Closer To Finishing<\/a><\/p>","wrap":true,"isSubtle":true,"type":"TextBlock","spacing":"none"},{"text":"<p>WEST SACRAMENTO (CBS13) – Monday’s Sacramento River Cats game had a big league feel as All-Star second baseman Joe Panik started his rehab ...<br>\r\n\n\nCBS Sacramento<\/p>","wrap":true,"isSubtle":true,"type":"TextBlock","spacing":"none"}]}]}]},{"type":"Container","items":[{"type":"ColumnSet","columns":[{"type":"Column","width":"auto","items":[{"size":"small","style":"person","type":"Image","url":"https:\/\/urlp.asm.skype.com\/v1\/url\/content?url=https%3a%2f%2fwww.bing.com%2fth%3fid%3dON.66256D3F741DF0220D0B7D6B1C987DF5%26pid%3dNews%26c%3d7%26w%3d200%26h%3d150"}]},{"type":"Column","width":"stretch","items":[{"text":"<p>Cats<br>\r\n\n\n<a href=\"https:\/\/newspro.microsoft.com\/promotion?url=http%3a%2f%2fwww.catster.com%2fcat-food%2fwhat-foods-are-toxic-to-cats&amp;id=395178&amp;scope=3&amp;guid=a47c85b4cac6f32b5fbcad7ddbebc157&amp;signature=91cac8450504a1f9e7b35b414732336c&amp;t2=20180529\" title=\"What Foods Are Toxic to Cats?\">What Foods Are Toxic to Cats?<\/a><\/p>","wrap":true,"isSubtle":true,"type":"TextBlock","spacing":"none"},{"text":"<p>As with us humans, there are some things kitty should just avoid. Not every animal reacts the same way to every food item, but we always advise you to do the safest thing ...<br>\r\n\n\nCatster<\/p>","wrap":true,"isSubtle":true,"type":"TextBlock","spacing":"none"}]}]}]},{"type":"Container","items":[{"type":"ColumnSet","columns":[{"type":"Column","width":"auto","items":[{"size":"small","style":"person","type":"Image","url":"https:\/\/urlp.asm.skype.com\/v1\/url\/content?url=https%3a%2f%2fwww.bing.com%2fth%3fid%3dON.A9C295BBB54362A52A3C9BEF129A6E21%26pid%3dNews%26c%3d7%26w%3d200%26h%3d150"}]},{"type":"Column","width":"stretch","items":[{"text":"<p>Cats<br>\r\n\n\n<a href=\"https:\/\/newspro.microsoft.com\/promotion?url=https%3a%2f%2fkentucky.rivals.com%2fnews%2fq-a-cats-illustrated-s-clint-jackson-goes-1-on-1-with-tyrese-maxey&amp;id=395178&amp;scope=3&amp;guid=01e97faaac089af7764a7054ed5bd3ff&amp;signature=48ecd585b58a17b9feec3741259904e8&amp;t2=20180529\" title=\"Q&amp;A: Cats Illustrated's Clint Jackson goes 1-on-1 with Tyrese Maxey\">Q&amp;A: Cats Illustrated's Clint Jackson goes 1-on-1 with Tyrese Maxey<\/a><\/p>","wrap":true,"isSubtle":true,"type":"TextBlock","spacing":"none"},{"text":"<p>The entire Kentucky basketball fan base, or so it seems, is familiar with Tyrese Maxey, the high scoring guard who has committed to ...<br>\r\n\n\nKentucky Rivals<\/p>","wrap":true,"isSubtle":true,"type":"TextBlock","spacing":"none"}]}]}]},{"type":"Container","items":[{"type":"ColumnSet","columns":[{"type":"Column","width":"auto","items":[{"size":"small","style":"person","type":"Image","url":"https:\/\/urlp.asm.skype.com\/v1\/url\/content?url=https%3a%2f%2fwww.bing.com%2fth%3fid%3dON.B9952E0C30913EDDB1B77DCCF14BD15F%26pid%3dNews%26c%3d7%26w%3d200%26h%3d150"}]},{"type":"Column","width":"stretch","items":[{"text":"<p>Cats<br>\r\n\n\n<a href=\"https:\/\/newspro.microsoft.com\/promotion?url=http%3a%2f%2fwww.johnsoncitypress.com%2fColumn%2f2018%2f05%2f27%2fWhy-it-s-important-to-play-with-your-cats&amp;id=395178&amp;scope=3&amp;guid=5ba6e946525005a5b4d649cf2ef6956f&amp;signature=52c52ef355cdc6c2b474c2d34a606550&amp;t2=20180529\" title=\"Why it's important to play with your cats\">Why it's important to play with your cats<\/a><\/p>","wrap":true,"isSubtle":true,"type":"TextBlock","spacing":"none"},{"text":"<p>It is commonly believed that the Egyptians first domesticated cats 4,000 years ago, but many now believe that cats could’ve been domesticated thousands of ...<br>\r\n\n\nJohnson City Press<\/p>","wrap":true,"isSubtle":true,"type":"TextBlock","spacing":"none"}]}]}]},{"type":"Container","items":[{"type":"ColumnSet","columns":[{"type":"Column","width":"auto","items":[{"size":"small","style":"person","type":"Image","url":"https:\/\/urlp.asm.skype.com\/v1\/url\/content?url=https%3a%2f%2fwww.bing.com%2fth%3fid%3dON.C4DCBFA20B9B1A967EC7F03CEA8EC15A%26pid%3dNews%26c%3d7%26w%3d200%26h%3d150"}]},{"type":"Column","width":"stretch","items":[{"text":"<p>Cats<br>\r\n\n\n<a href=\"https:\/\/newspro.microsoft.com\/promotion?url=http%3a%2f%2fwww.unionleader.com%2fapps%2fpbcs.dll%2farticle%3fAID%3d%2f20180528%2fSPORTS0102%2f180529304&amp;id=395178&amp;scope=3&amp;guid=f7af67b5d6486b4dd26a6c2af59d2f65&amp;signature=10e287acc22dfedbe3a841fa8cac5e52&amp;t2=20180529\" title=\"Kelly helps Fisher Cats over Yard Goats\">Kelly helps Fisher Cats over Yard Goats<\/a><\/p>","wrap":true,"isSubtle":true,"type":"TextBlock","spacing":"none"},{"text":"<p>Juan Kelly delivered the biggest hits of the afternoon, a two-run double in the third inning and a solo homer in the eighth, helping the New Hampshire Fisher ...<br>\r\n\n\nNew Hampshire Union Leader<\/p>","wrap":true,"isSubtle":true,"type":"TextBlock","spacing":"none"}]}]}]},{"type":"Container","items":[{"type":"ColumnSet","columns":[{"type":"Column","width":"auto","items":[{"size":"small","style":"person","type":"Image","url":"https:\/\/urlp.asm.skype.com\/v1\/url\/content?url=https%3a%2f%2fwww.bing.com%2fth%3fid%3dON.ABE30E9C3DD41797A08ABB28EE96520B%26pid%3dNews%26c%3d7%26w%3d200%26h%3d150"}]},{"type":"Column","width":"stretch","items":[{"text":"<p>Cats<br>\r\n\n\n<a href=\"https:\/\/newspro.microsoft.com\/promotion?url=https%3a%2f%2fkentucky.rivals.com%2fnews%2ftourney-snub-for-cats-draws-strong-reaction&amp;id=395178&amp;scope=3&amp;guid=c439ed0b385bbd0cd321d3f2a31a41a9&amp;signature=debec660e7e2ad5c8f839f89d615361e&amp;t2=20180529\" title=\"Tourney snub for Cats draws strong reaction\">Tourney snub for Cats draws strong reaction<\/a><\/p>","wrap":true,"isSubtle":true,"type":"TextBlock","spacing":"none"},{"text":"<p>Joined the Cats Illustrated staff in the summer of 2017. Veteran reporter and photographer who has covered UK sports dating back to 1987. The most ...<br>\r\n\n\nKentucky Rivals<\/p>","wrap":true,"isSubtle":true,"type":"TextBlock","spacing":"none"}]}]}]}],"type":"AdaptiveCard","actions":[{"type":"Action.OpenUrl","title":"Read more from Bing News ","url":"https:\/\/www.bing.com\/news\/search?q=Top%20Stories&FORM=CONVER"}],"$schema":"http:\/\/adaptivecards.io\/schemas\/adaptive-card.json"}

**Comment by nesalang** [comment]
closed as discussed; custom labeling issue

**Comment by kratijain-microsoft** [comment]
Reopening this as its not due to custom label rendering. Its due to extra stretching of the title column as compared to image.
