### ISSUE TITLE
Think alternatives to COM Macros

### ISSUE THREAD

**Issue by ignacionr** [Microsoft/AdaptiveCards#1597]
@RebeccaAnne and @paulcam206 can we think of nicer alternatives to THROW_IF_FAILED and RETURN_IF_FAILED?
There's room for improving readability if we can come up with a template or function solution. Definitely not saying go all 1990s with verbose ```if (SUCCEEDED(hr))``` or ATL stubs (no preprocessing is best), but there must be some better way (also consider ES.31 as an argument).

**Comment by paulcam206** [comment]
Hey @ignacionr -- the reason we have these idioms is that they match internal best practices. Specifically, these macros are normally defined as part of an internal helper library. This library may yet be made available in some public form, but it currently has dependencies on the Microsoft compiler toolchain as well as the Windows SDK (there's active discussion around handling these issues). I think for now we should take a "wait and see" approach. :)

**Comment by ignacionr** [comment]
Wait and see works for me. Thanks for reading, for understanding the concern, and taking the time to explain.
