### ISSUE TITLE
HTML renderer and visualizer incorrectly allow selectAction without a "title" property

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#1604]
The `title` property on `selectAction` is required as per the schema, but the web visualizer and HTML renderer still allow rendering cards that don't have a title set on their selectActions.

These should be updated to fail rendering, to be consistent with all other platforms. Otherwise, people get confused (as seen in #1572) when something works fine on the web, but then the same payload doesn't work on UWP.

Example payload that SHOULD fail but doesn't today on the web visualizer/HTML renderer...

```json
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "ColumnSet",
			"columns": [
				{
					"type": "Column",
					"width": "20",
					"items": [
						{
							"type": "TextBlock",
							"horizontalAlignment": "center",
							"wrap": false,
							"text": "Fri"
						},
						{
							"type": "Image",
							"size": "auto",
							"url": "http://messagecardplayground.azurewebsites.net/assets/Mostly%20Cloudy-Square.png"
						},
						{
							"type": "TextBlock",
							"horizontalAlignment": "center",
							"wrap": false,
							"text": "62"
						},
						{
							"type": "TextBlock",
							"horizontalAlignment": "center",
							"isSubtle": true,
							"wrap": false,
							"text": "52",
							"spacing": "none"
						}
					],
					"selectAction": {
						"type": "Action.OpenUrl",
						"url": "http://www.microsoft.com"
					}
				},
				{
					"type": "Column",
					"width": "20",
					"items": [
						{
							"type": "TextBlock",
							"horizontalAlignment": "center",
							"wrap": false,
							"text": "Sat"
						},
						{
							"type": "Image",
							"size": "auto",
							"url": "http://messagecardplayground.azurewebsites.net/assets/Drizzle-Square.png"
						},
						{
							"type": "TextBlock",
							"horizontalAlignment": "center",
							"wrap": false,
							"text": "60"
						},
						{
							"type": "TextBlock",
							"horizontalAlignment": "center",
							"isSubtle": true,
							"wrap": false,
							"text": "48",
							"spacing": "none"
						}
					],
					"selectAction": {
						"type": "Action.OpenUrl",
						"url": "http://www.microsoft.com"
					}
				}
			]
		}
	]
}
```

**Comment by tuanh118** [comment]
The HTML does not require `title` for any kind of action, including card actions. Should I make `title` required everywhere?

**Comment by andrewleader** [comment]
@matthidinger thoughts?

**Comment by dclaux** [comment]
I do think there is a case for a button with an icon and no title. For icon-less buttons, a title is definitely necessary, but I don't think that's a reason for failing parsing or even rendering.

**Comment by andrewleader** [comment]
@dclaux For hosts that require titles on their button (they have no UI paradigm of a button with just an icon), what would you expect them to do?

I think that's yet again a convergence question... some hosts might want buttons with only icons, some hosts might want buttons with both icons and titles, and some hosts might want buttons with only titles. How do you have a single payload that works for all of these hosts, while making it clear and obvious to the content author which properties they should assign so that their content works everywhere?

**Comment by tuanh118** [comment]
@dclaux yeah I think that makes sense. We can discuss and possibly create an epic for that. As of this issue, it's just a bug according to our [current documentation](https://adaptivecards.io/explorer/Action.OpenUrl.html) that requires `title` for all kinds of actions
