### ISSUE TITLE
Support custom rendering override for background image

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#1605]
<table>
<tr>
<th>Release</th>
<th>Renderer status</th>
<th>Tasks status</th>
</tr>
<tr>
<td>Not scheduled
<td>🔄 .NET (#2539)<br/>🔄 Android (#2540)<br/>✔️ iOS (#1609)<br/>🔄 TS (#2541)<br/>🔄 UWP (#2542)</td>
<td>🔄 Shared (#2537)<br/>✔️ Designer (#2538)</td>
</tr>
</table>

## The problem

While hosts can override rendering of text blocks, images, etc, they can't override background image

# Auto-generated task status

- [ ] Shared
- [x] Designer
- [ ] .NET
- [ ] Android
- [x] iOS
- [ ] TS
- [ ] UWP

**Comment by dclaux** [comment]
Not quite sure what this is about or why it's needed, maybe an example would help.

**Comment by andrewleader** [comment]
If a host wants to override how the background image is drawn, they can't exactly do that today in many of the renderers. @nesalang you added this for iOS correct? Can you elaborate on the scenario that (Teams?) needed this ability for?

**Comment by dclaux** [comment]
I understand the concept of custom rendering the background image, my question is why is that necessary? What's an example of a custom rendering that can't be accomplished with what we support out of the box, especially given we are introducing enhanced background image support?

**Comment by paulcam206** [comment]
Not currently under consideration, but will reactivate should we decide to pursue.
