### ISSUE TITLE
button not readable in Cortana

### ISSUE THREAD

**Issue by IntranetFactory** [microsoft/AdaptiveCards#1608]
Button labels are very small and and black and blue makes them hard to read.

I didn't find any information how to select a larger font and a different color for the button labels.

Did I miss any option to make the button readable?

![image](https://user-images.githubusercontent.com/7462342/41422919-fa5c1f0e-6fc7-11e8-89c9-ac98f0b9fac6.png)

**Comment by matthidinger** [comment]
Thanks for reporting @IntranetFactory - I'll loop in the Cortana folks!

**Comment by shalinijoshi19** [comment]
@matthidinger was this ever resolved/Cortana looped in? Thanks!
