### ISSUE TITLE
Add size and alignment for buttons in Adaptive cards

### ISSUE THREAD

**Issue by Tyagit3** [Microsoft/AdaptiveCards#1610]
Is there a way to resize a button in an Adaptive card?

**Comment by Kartik1607** [comment]
Yes. Have a look at documentation for [host config](https://docs.microsoft.com/en-us/adaptive-cards/display/hostconfig#actionsconfig)

**Comment by Kartik1607** [comment]
@Tyagit3 It would depend on platform where your bot is running. For instance, if your bot is running on a webchat, there is adaptivecards-hostconfig.json in root of project which you can edit.

**Comment by Tyagit3** [comment]
@Kartik1607 I don't see any hostconfig.json in my project folder. I'm building it in C# using AdaptiveCards package. I can access hostconfig class under AdaptiveCards.Rendering.Config namespace. But I'm not sure how to actually render cards using that.

**Comment by Tyagit3** [comment]
Hi @anbare I'm displaying it in my own website. But I'm not sure how to use hostconfig using C#. I don't see any hostconfig.json in my project. I can access hostconfig class under AdaptiveCards.Rendering.Config namespace. But I didn't find any documentation how to actually use that. Please provide a sample if you have any. (C# example)

**Comment by anbare** [comment]
@Tyagit3  What exactly are you using to render the cards on your own website? Bot Framework SDK? Or are you using the AdaptiveCards.Rendering.Html NuGet library?

**Comment by Tyagit3** [comment]
@anbare  I'm using Bot Framework SDK.

**Comment by anbare** [comment]
@Tyagit3 Try reaching out to the Bot Builder SDK team: https://github.com/Microsoft/botbuilder-dotnet/issues

You'll have to assign a Host Config in their SDK somewhere, since their SDK is the one rendering the cards. This Host Config would apply to all cards that get rendered within your web page's bot.

**Comment by Kevin-Chung** [comment]
If anyone else gets to this point, here's a sample from the repo https://github.com/Microsoft/AdaptiveCards/blob/master/samples/HostConfig/sample.json

**Comment by Shivang007-del** [comment]
@Tyagit3 found any solution ?
