### ISSUE TITLE
how to check valid url or not delegate function not trigger

### ISSUE THREAD

**Issue by Bharath2r** [Microsoft/AdaptiveCards#1617]
Valid url is working fine but  delegate function not  trigger
not valid url crashing

This function not triggering both case valid and not valid
  func didFetchHttpRequest(_ urlRequest: URLRequest) {
        print("fsfsf:>>> \(urlRequest)")
    }

this is error msg
error:'NSInvalidArgumentException', reason: 'The specified URL has an unsupported scheme. Only HTTP and HTTPS URLs are supported.'

**Comment by anbare** [comment]
Hi @Bharath2r, can you please clarify your question? It's unclear how this is related to Adaptive Cards. I will close this issue, feel free to open it if you can provide more actionable details. Thanks!
