### ISSUE TITLE
[UWP] Action event not raised with native compiled app and EventTriggerBehavior

### ISSUE THREAD

**Issue by oliverluethi** [microsoft/AdaptiveCards#1634]
We're facing a problem with native compiled UWP apps. We bind the Action event of the AdaptiveCard to a Command in XAML with a behavior. 
`<interactivity:Interaction.Behaviors>`
`<core:EventTriggerBehavior EventName="Action" SourceObject="{Binding Path=DataContext, ElementName=adptGrid}">`
`<core:InvokeCommandAction Command="{Binding ElementName=ConversationAreaControl,
                                                                                Path=DataContext.AdaptiveCardActionCommand}"/>`
`</core:EventTriggerBehavior>`
`</interactivity:Interaction.Behaviors>`

With ".NET Native Tool Chain" disabled everything runs great. With ".NET Native Tool Chain" enabled the  InvokeCommandAction is never called through our binding. A workaround we found is to add an EventHandler to the AdaptiveCard in code. After the event got raised in code, the InvokeCommandAction will be raised as expected.

`var renderResult = renderer.RenderAdaptiveCard(card.AdaptiveCard);`
`renderResult.Action += RenderResult_Action;`
`private void RenderResult_Action(RenderedAdaptiveCard sender, AdaptiveActionEventArgs args){;}`

**Comment by anbare** [comment]
Hey Oliver, thanks for reporting this bug! We're not sure when we will be able to investigate this, so if this isn't a blocking issue, I'd suggest assigning the event handler in code to workaround the issue as you described.

If this is a blocking issue and higher priority, let us know!

**Comment by jonmill** [comment]
Closing per above comment
