### ISSUE TITLE
[UWP] Vertical Stretch changed the behaviour for image placement

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#1640]
When the vertical stretch for UWP was introduced some elements were being drawn in the middle of the available space; when the vertical stretch for Android was merged, I tried to fix those placements making all the elements being drawn at the top which ended up changing the behavior of the ImageSets

@khouzam proposed that we should be able to define the vertical alignment of the images inside an image set (independently of the alignment of the image set) but that would mean a behavior change so we would like to know what should we do? @matthidinger @dclaux @anbare

**Comment by anbare** [comment]
@almedina-ms can we get some visuals or more description? I'm not understanding what the behaviors are.

**Comment by anbare** [comment]
Thanks almedina!

@matthidinger @dclaux what do you think the behavior should be? I kind of like the original behavior, where the images are vertically aligned in the center of their rows.

**Comment by anbare** [comment]
I agree, margin and top-aligned looks good

![image](https://user-images.githubusercontent.com/13246069/41791854-d7992972-760b-11e8-9a58-64ae3ab5ee89.png)

We probably should have margin between rows too though? The same margins all around?

![image](https://user-images.githubusercontent.com/13246069/41791909-0ede520e-760c-11e8-9e07-5d4d457b5859.png)

**Comment by dclaux** [comment]
Problem with the top margin, in html at least, is that it will leave white space below the very last row screwing up with spacing. That is unless ImageSet layout is computed manually, in which case we can do a lot better than what I currently have. But it's also a lot more expensive.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
