### ISSUE TITLE
Inline emotes/ gifs in adaptive card

### ISSUE THREAD

**Issue by Tyagit3** [Microsoft/AdaptiveCards#1645]
Is there a way to use a gif/emotes in an adaptive card?

**Comment by Kartik1607** [comment]
Adaptive cards support gif. Add the url of gif inside the image element something like 
```JSNO
{
    "type":"Image",
    "url": "https://gifurl/"
}
```

**Comment by ignacionr** [comment]
I believe @Tyagit3 means to mix 🗣 emoji inside 🙌 text. I can confirm that at least Unicode emoji works perfectly well if properly encoded into the JSON. See the image.

<img width="432" alt="screen shot 2018-06-25 at 9 15 55 am" src="https://user-images.githubusercontent.com/1210985/41827236-907b8f0e-7858-11e8-8c3f-79c9f4377198.png">

**Comment by ignacionr** [comment]
@Tyagit3 FYI I created a test that renders a card with a text block that includes Emoji. The test checks that the length of the text rendered is the same as the original string (making sure it didn't chop the chars or misinterpreted the sequence).

You can check it out at https://github.com/Microsoft/AdaptiveCards/pull/1647/commits/6f5404489efa6d2e355eb4a5b1d40c1340711d89 ; if you feel this fulfills your doubt, go ahead and close this issue.

Thank you!

**Comment by Tyagit3** [comment]
@ignacionr This is a simple emoji. I was asking about something similar but to show animated emojis/ animojis.

**Comment by Kartik1607** [comment]
> Or you want to replace text in grammatically significant points of the phrasing, with animations
Can't wait for it.

@Tyagit3 The closest you can get is to use markdown and add gif's in place of emojis. You would have to take care of image sizing though.

**Comment by andrewleader** [comment]
Tracking this feature request for inline animated emojis/GIFs here: #2525

Closing this question thread. Markdown with GIFs is a great workaround for now Kartik (but definitely has image sizing issues as you point out), thanks for that though!
