### ISSUE TITLE
Issue style customization AdaptiveCards for Webchat channel

### ISSUE THREAD

**Issue by Avartarus-Testicus** [Microsoft/AdaptiveCards#1667]
Hello, I'm using the botbuilder-sdk with nodeJS. Including those adaptive cards to my messages already succeeded, like the following way:

```
var msg = new builder.Message(session)
    .addAttachment(card);
session.send(msg);
```
But I realy don't get it how to customize the styling of AdaptiveCards over  **hostConfig**.

The documentation (https://docs.microsoft.com/de-de/adaptive-cards/sdk/rendering-cards/javascript/getting-started) is describing that you need a new instance of AdaptiveCard and then you can set the hostConfig like the following:

```
var adaptiveCard = new AdaptiveCards.AdaptiveCard();

adaptiveCard.hostConfig = new AdaptiveCards.HostConfig({
    fontFamily: "Segoe UI, Helvetica Neue, sans-serif"
    // More host config options
});
```
But after that they describing you need to render it and in the end you can attach it to the DOM (document.body.appendChild(renderedCard);) BUT I have no page where I want to attach my AdpativeCard to the DOM. I'm in the backend-site and want to attach my AdaptiveCard in my Bot-Message with a overwritten hostConfig.

If I try to attach my **AdpativeCard-Obj** to the botbuilder **addAttachement**-Funktion, I have no success. Currently I'm only able to attach a simple AdaptiveCard-JSON-scheme to it.

Please, could anyone help me to find it out ? Thanks in adavance.

**Comment by Kartik1607** [comment]
hostConfig stays at the front end. Each channel like Cortona, Skype etc have their own host config which can not be edited.

However, you are free to edit host config if you have control over your frontend part of channel. In webchat, you can use  [Webchat](https://github.com/Microsoft/BotFramework-WebChat) and modify the [hostConfig](https://github.com/Microsoft/BotFramework-WebChat/blob/master/adaptivecards-hostconfig.json) to chage UI of cards.

**Comment by anbare** [comment]
Closing for now, re-activate if further questions.

**Comment by buoyantair** [comment]
Does that mean that we can't really style our Adaptive cards in Microsoft Teams etc?
