### ISSUE TITLE
ActiveCard Speak & Lang

### ISSUE THREAD

**Issue by grahamehorner** [microsoft/AdaptiveCards#1668]
The ActiveCard Speak & Lang property have the same order value of -6; it would be better to have unique order values; and have the JsonProperty attribute Order property reference a const int to avoid duplication of the ordering value in the property attribute decorator

**Comment by jonmill** [comment]
Closing as this should no longer repro - if you're still seeing this issue then please re-open and we'll engage. Thanks!
