### ISSUE TITLE
[.NET] AdaptiveElementRenderers TryGet/TrySet

### ISSUE THREAD

**Issue by grahamehorner** [microsoft/AdaptiveCards#1669]
Please consider adding the TryGet/TrySet methods to the AdaptiveElementRenderers <TUIElement,TContext> at present if a TElement renderer is not registered an expection is thrown, it would be good to have the option to override this and/or check is a renderer has been registered, with a possible fallback renderer if the a specified TElement renderer is not present.

**Comment by anbare** [comment]
Good suggestion @grahamehorner! Would you be interested in making a pull request to add those methods?

**Comment by grahamehorner** [comment]
@anbare I have a working TryGet/TrySet and will be adding unit tests for completeness over this weekend, I’m more than happy to then submit this as a pull request.

**Comment by grahamehorner** [comment]
@anbare first pass TryGet in pull request https://github.com/Microsoft/AdaptiveCards/pull/1686
