### ISSUE TITLE
[.NET] HtmlTag Id/Name property

### ISSUE THREAD

**Issue by grahamehorner** [microsoft/AdaptiveCards#1680]
The HtmlTag class should have a strongly typed first class property for Id and/or Name this should be populated via with the value from the AdativeCard when rendered; this would allow the developer to perform queries based on the Id/name of a element for things like late data-binding.

**Comment by anbare** [comment]
Hey Grahame,

For things like inputs, which have Id properties in the Card schema, I believe we do transfer those ids over to the name property of the HTML input.

For everything else, in the Adaptive Card schema there's currently no purpose for an Id on elements, hence we didn't add one.

For data-binding, that's something we're thinking of adding support for natively into Adaptive Cards in a future release.

What other scenarios do you have in mind that would require ids being specified? And what is your scenario where you're rendering cards?

**Comment by grahamehorner** [comment]
@anbare I currently have a requirement where I need to render a card for multiple host configurations and replace some of the textual content based on the recipient eg. applying branding/contact information (rending cards with data-binding to a model etc.) injecting sections etc.

**Comment by anbare** [comment]
Would it make sense to replace those **before** rendering? You can parse the Card they sent, and you can inspect additional properties they specified (you could have them specify ids, or any other property you'd like), and then you can replace info ahead of rendering.
