### ISSUE TITLE
Cards missing parts when rendered as image when Channel is FB

### ISSUE THREAD

**Issue by oyen** [microsoft/AdaptiveCards#1684]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML

# Author or host

Host

# Version of SDK

AdaptiveCards 1.0.3

# Issue

When sending adaptive cards in carousel layout, and the channel is FB, the texts above the image do not appear. If there are 2 cards in the carousel, less text after the image appear.

[Here is what it looks like](https://siritsit.blob.core.windows.net/siritsitcontent/20180703%20emulator%20vs%20fb.png)

**Comment by rafadorado** [comment]
Same issue here. At least,  we can work-around the "look & feel" of the carousel images by creating specific adaptative Cards for facebook. 

But what can we do with the **Title** attribute? Any ideas? 

![adaptative-card-bug](https://user-images.githubusercontent.com/3205516/42322422-c2459de8-805c-11e8-83db-b2b3523fafc9.jpg)

Thanks!

**Comment by rafadorado** [comment]
Hi @andrewleader , are there any plans to look into this? 

The carousel component with adaptative cards in Facebook doesn't render the images properly. In the image attached you can see how the same card it renders perfectly by itself but when adding it to the carousel breaks. The same code en webchat works perfectly.

If you are not planning to work on this, could you point me where could we try to fix it ourselves?

Thanks.

![image](https://user-images.githubusercontent.com/3205516/43513974-63f356b2-957f-11e8-98a8-75d184fac402.png)

**Comment by ignacionr** [comment]
Hola @rafadorado ! This can help if you're looking into creating better renders of cards into images.

A long time ago I started something similar. My thoughts are that rendering through WPF on a server is a bad idea. It's true I have zero love for WPF in general, but the results were low in quality and utterly difficult to manage.

My take was just use Puppeteer and NodeJS; the code is so simple that it's not even worth sharing. The result is really good, and consistent (e.g. resolution and drivers that may or not be installed on the server will affect big time the WPF results).

Hope this helps. Sincerely, Ignacio.//

**Comment by jonmill** [comment]
The HTML renderer is deprecated; if we can provide any further help, please respond and let us know. Thanks!
