### ISSUE TITLE
[ios]Reduce final binary size.

### ISSUE THREAD

**Issue by kratijain-microsoft** [Microsoft/AdaptiveCards#1685]
# Platform
ios

# Author or host
host

# Version of SDK
1.1

# Issue
Current size of adaptive cards sdk is 19 MB in the final archive of our Teams app. Can you please slice down the sdk files using Apple's app size reduction guidelines : 
App Thinning : https://developer.apple.com/videos/play/wwdc2015/404/
On-Deman Resources: https://developer.apple.com/videos/play/wwdc2015/214/

**Comment by nesalang** [comment]
closing this.
binary size got increased after enabling bitcode.
bitcode allows Apple to optimize the binary size; what's important is the final binary size of the hosting app.
