### ISSUE TITLE
Extensibility to override rendering of entire action set

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#1690]
<table>
<tr>
<th>Release</th>
<th>Renderer status</th>
<th>Tasks status</th>
</tr>
<tr>
<td>Not scheduled
<td>🔄 .NET (#1691)<br/>✔️ Android (#2458)<br/>✔️ iOS (#1692)<br/>🔄 TS (#1694)<br/>🔄 UWP (#1693)</td>
<td>✔️ Shared (#2457)</td>
</tr>
</table>

# Summary

Microsoft Teams wants to add a custom shadow on the right of the actions list, to indicate that you can scroll right. This requires being able to override the rendering of the entire set of actions, not just an individual action.

We need to decide on the right API structure for all of the renderers to use for this.

# API

Add a new **ActionsRenderer** property on the renderer, to allow overriding the rendering.

```csharp
// Existing method
renderer.ElementRenderers.Set("TextBlock", myTextBlockRenderer);

// Existing method
renderer.ActionRenderers.Set("Action.ShowCard", myShowCardRenderer);

// New property
renderer.ActionsRenderer = myActionsRenderer;
```

```csharp
public interface IActionsRenderer
{
    UIElement Render(IList<IAdaptiveActionElement> actions, AdaptiveRenderContext context);
}
```

# Auto-generated task status

- [x] Shared
- [ ] .NET
- [x] Android
- [x] iOS
- [ ] TS
- [ ] UWP

**Comment by paulcam206** [comment]
Not currently under consideration, but will reactivate should we decide to pursue.
