### ISSUE TITLE
ImageSet inside Container does not render initially

### ISSUE THREAD

**Issue by anirudhrbMSFT** [Microsoft/AdaptiveCards#1703]
# Platform
iOS

# Author or host
Host: MS Teams - iOS.

# Version of SDK

1.1

# Issue
When there is an ImageSet inside a Container, the ImageSet doesn't get rendered initially. It gets rendered later when the view is refreshed. For e.g. in Teams chat view, the image set won't render initially but, if you scroll up so that the view is not on the screen anymore and then scroll back down, the images are rendered.

This is **reproducible on the Adaptive Cards sample app** too (_ImageGallery_ example). This is the card JSON we are using:

```
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "ImageSet",
                    "images": [
                        {
                            "type": "Image",
                            "url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg"
                        },
                        {
                            "type": "Image",
                            "url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg"
                        },
                        {
                            "type": "Image",
                            "url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg"
                        }
                    ],
                    "imageSize": "medium"
                }
            ]
        }
    ]
}

```

# Screenshots
Initially
<img src="https://user-images.githubusercontent.com/41040316/42490700-4cd70750-842f-11e8-8099-736107cb99ef.png" width=300/>

After scrolling up and then back down
<img src="https://user-images.githubusercontent.com/41040316/42490723-67cd8c46-842f-11e8-947c-7327ecc1cb83.png" width=300/>

**Comment by nesalang** [comment]
This is not reproducible on sample pp. on Sample app, it appears near instantly
 on iPhone 6s.

**Comment by anirudhrbMSFT** [comment]
@nesalang Did you put the ImageSet inside a Container?

**Comment by nesalang** [comment]
container didn't get the frame from its superview, so its intrinsic content size was returning zero, and collapsed whole view.
