### ISSUE TITLE
[ios] Drastic Collapse Animation of ShowCard

### ISSUE THREAD

**Issue by kratijain-microsoft** [Microsoft/AdaptiveCards#1704]
# Platform
* iOS

# Author or host
Host

If you're an author, who are you sending cards to?

# Version of SDK
1.1

# Issue

When show card button expands the card, it opens upwards. But when it collapses the card, the animation/transition is so drastic that the user loses context of the screen position as shown in the video attached. 
#Expected Behaviour:
The card should collapse in such a way that it maintains the user screen content offset or scroll position.  
[CollapseAnimation.zip](https://github.com/Microsoft/AdaptiveCards/files/2180209/CollapseAnimation.zip)

**Comment by nesalang** [comment]
This is not something apdativecard can provide
