### ISSUE TITLE
[ios]Placeholder for Choice Set is not supported ; Empty label if none of the values are selected

### ISSUE THREAD

**Issue by kratijain-microsoft** [Microsoft/AdaptiveCards#1705]
# Platform

* iOS

# Author or host
Host : MS Teams ios

# Version of SDK
1.1

# Issue
When a choice set doesnt have a default selected value, it shows empty label with an arrow as seen in screenshot. The web client for adaptive cards supports placeholder text but ios sdk doesnt. Please show the placeholder text for choice set in case none of the values are selected.
Try to repro it with this json for Input.ChoiceSet.json:
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "What color do you want? *(isMultiSelect:false, style:compact)*"
        },
        {
            "type": "Input.ChoiceSet",
            "id": "myColor",
            "style": "compact",
            "isMultiSelect": false,
            "placeholder": "SELECT A VALUE",
            "choices": [
                {
                    "title": "Red",
                    "value": "1"
                },
                {
                    "title": "Green",
                    "value": "2"
                },
                {
                    "title": "Blue",
                    "value": "3"
                }
            ]
        },
        {
            "type": "TextBlock",
            "text": "What color do you want? *(isMultiSelect:false, style:expanded)*"
        },
        {
            "type": "Input.ChoiceSet",
            "id": "myColor2",
            "style": "expanded",
            "isMultiSelect": false,
            "value": "1",
            "choices": [
                {
                    "title": "Red",
                    "value": "1"
                },
                {
                    "title": "Green",
                    "value": "2"
                },
                {
                    "title": "Blue",
                    "value": "3"
                }
            ]
        },
        {
            "type": "TextBlock",
            "text": "What colors do you want? *(isMultiSelect:true, style:compact)*"
        },
        {
            "type": "Input.ChoiceSet",
            "id": "myColor3",
            "isMultiSelect": true,
            "value": "1,3",
            "style": "compact",
            "choices": [
                {
                    "title": "Red",
                    "value": "1"
                },
                {
                    "title": "Green",
                    "value": "2"
                },
                {
                    "title": "Blue",
                    "value": "3"
                }
            ]
        },
        {
            "type": "TextBlock",
            "text": "What colors do you want? *(isMultiSelect:true, style:expanded)*"
        },
        {
            "type": "Input.ChoiceSet",
            "id": "myColor4",
            "isMultiSelect": true,
            "value": "1",
            "style": "expanded",
            "choices": [
                {
                    "title": "Red",
                    "value": "1"
                },
                {
                    "title": "Green",
                    "value": "2"
                },
                {
                    "title": "Blue",
                    "value": "3"
                }
            ]
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "OK"
        }
    ]
}
![simulator screen shot - iphone 8 plus - 2018-07-10 at 17 31 41](https://user-images.githubusercontent.com/38986011/42508715-20b5b3a0-8467-11e8-8da2-04d1e54bc107.png)

**Comment by nesalang** [comment]
AdaptiveCard Scheme does not support placeholder text for Input.ChoiceSet. To mitigate that AC will display first choice by default if value is not given.

**Comment by nesalang** [comment]
fixed via https://github.com/Microsoft/AdaptiveCards/pull/1709
