### ISSUE TITLE
[ios]Extra spaces in the card on multiple show card button taps when succession

### ISSUE THREAD

**Issue by kratijain-microsoft** [Microsoft/AdaptiveCards#1706]
# Platform

* iOS

# Author or host
Host : MS Teams ios

# Version of SDK
1.1
# Issue
In case of multiple ShowCard buttons, when height of card after expansion is different, the extra space is appended around the text of the card. Example : Tap mulipleChoice button > Tap Send button > Tap text input button and see how card text label gets extra spaces.

Please refer to screenshot attached
![simulator screen shot - iphone 8 - 2018-05-31 at 13 57 32](https://user-images.githubusercontent.com/38986011/40771296-9b6146ca-64da-11e8-958f-424a4dc359ac.png)

**Comment by nesalang** [comment]
this is not reproducible on SDK.
