### ISSUE TITLE
[ios]Restaurant card: Large 4th star

### ISSUE THREAD

**Issue by kratijain-microsoft** [Microsoft/AdaptiveCards#1707]
![simulator screen shot - iphone 8 - 2018-07-11 at 11 35 26](https://user-images.githubusercontent.com/38986011/42553444-8a4dbcee-84fe-11e8-9e51-7824b44360e3.png)
# Platform
* iOS

# Author or host
Host : MS Teams ios

# Version of SDK
1.1

# Issue
Adaptive card :[Restaurant]:-  In feedback star list 4th star icon size is larger than other stars.

**Comment by nesalang** [comment]
closing it This is not reproducible on sample app
