### ISSUE TITLE
Card Speak attribute in carroussel

### ISSUE THREAD

**Issue by BloodSeaker** [Microsoft/AdaptiveCards#1708]
WEB CHAT MODULE

Hi
I am using adaptivecards, which seem to be working quite okay.
Recently, I started to add speech to them, as my website chat module now connects with microsoft Speech to Text service.
However, I noticed that when the result displays a carrousel of items to choose from (for example, 5 upcoming events), only the Speak attribute of 1 of the cards is being handled.

The work around is to build a string of all the cards and attach it to the speak property of the last card, but this is just weird as a developer.

Not sure if this is an adaptivecards issue ,or the control. As I cannot think of other test scenario's currently.

**Comment by andrewleader** [comment]
Hey @BloodSeaker, please reach out to the Bot Framework support about this issue, since the carousel is a unique Bot Framework issue, and they're choosing which speak tag to pull out.
