### ISSUE TITLE
The published Adaptive JSON schema is incorrect, needs to be reworked

### ISSUE THREAD

**Issue by dclaux** [microsoft/AdaptiveCards#1711]
# Platform

The published schema at http://adaptivecards.io/schemas/adaptive-card.json isn't defined correctly. Validating payloads against it generates many incorrect errors. You can see for yourself on https://www.jsonschemavalidator.net/ - just paste the schema and any of our published samples.

# Solution

Rewrite the schema.

**Comment by billbliss** [comment]
Also, it really should be an https:// link. ;-)

**Comment by andrewleader** [comment]
The new schema is now valid, https://adaptivecards.io/schemas/1.2.0/adaptive-card.json
