### ISSUE TITLE
Show Card has a leading margin of 10pixel even if nothing is given in host config, android and desktop does not have it. Please make is consistent [iOS]. Give No padding if nothing is given in config

### ISSUE THREAD

**Issue by an888ha** [Microsoft/AdaptiveCards#1721]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards?

If you're an author, who are you sending cards to?

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

# Issue

Explain your issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards).

**Comment by nesalang** [comment]
fixed via 1717
