### ISSUE TITLE
Request: Progress bar element

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#1725]
# Problem

Some hosts want to allow card authors to able to display a progress bar in their card. Also should have a progress ring?

# Asks

* Cortana (indeterminate progress ring/bar, and determinate progress bar, want updating)
* Action Center (progress bar, [see existing](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-progress-bar) for requirements, also need to be able to update it)
* Skype (progress ring, indeterminate)

## Action Center requirements

In addition to the link provided above to the existing XML progress bar (which they need parity with), Action Center also wants the progress bars to be able to be shown while the notification is collapsed. They do this today by having the progress bars NOT be part of the free-form body, so that they can be displayed in compact mode.

## Cortana requirements

Cortana Calendar team wanted a progress bar. Here's visuals...

![image](https://user-images.githubusercontent.com/13246069/45391928-e340b700-b5d9-11e8-9e49-8fc4c96a4fcc.png) 
![image](https://user-images.githubusercontent.com/13246069/45391941-efc50f80-b5d9-11e8-8fbd-784254c7a729.png)

They need...

* Indeterminate progress ring
* Indeterminate progress bar
* Determinate progress bar
* Good to have an option for the author to dynamically hide/show the progress bar once the operation "completes"
* Would be good if Skill owners can update the determinate progress bar rather than forcing the user to ask for the updated content
* Good with letting the author embed the progress bar anywhere inside the Card surface

## Skype requirements

Need requirements (Andrew reached out to Skype on 9/7/2018)

**Comment by RebeccaAnne** [comment]
This is a good suggestion, but not something that's on our roadmap at this time. We may reconsider it in the future, or if you would like to make a contribution please see our contribution guidelines [here](https://github.com/microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md).
