### ISSUE TITLE
padding property on Container and ColumnSet

### ISSUE THREAD

**Issue by dclaux** [microsoft/AdaptiveCards#1727]
# Solves requests

* Bleeding background images/colors for containers #2013

# Proposed solution

Allow explicit paddings on Container and ColumnSet. New property would be added to these...

Property|Type|Required|Default|Description
---|---|---|---|---
padding | Padding | false | null | Specifies the padding for the container

The Padding property will be defined as follows (in pseudo code):
```typescript
interface Padding {
	top?: Spacing;
	right?: Spacing;
	bottom?: Spacing;
	left?: Spacing;
}
```

Each property is nullable, since null represents `"auto"`, which is a distinct value for padding, since padding is typically automatically determined based on whether the container is emphasis and the parent is not emphasis (so sometimes, the "initial" padding is none, and other times the initial padding is "padding")

The Spacing enum uses the existing Spacing enum.

**Spacing**

Controls the amount of spacing between this element and the previous element.

* Type: `string`
* Allowed values:
  * `"none"`
  * `"small"`
  * `"default"`
  * `"medium"`
  * `"large"`
  * `"extraLarge"`
  * `"padding"`

In an Adaptive JSON payload, the padding property can be specified in two different ways:
- As a string:
  - `"padding": "none"`
  - This is equivalent to all Top, Right, Bottom and Left being set to "none"
	
- As an object:
```json
		"padding": {
			"top": "none",
			"right": "large",
			"bottom": "none",
			"left": "extraLarge"
		}
```

When padding is specified as an object, any of the top, right, bottom and left properties are optional and default to "none"

**Open Question**: Shouldn't they actually default to "default", as that's the default enum value for spacing?
	
When the padding property is NOT specified, the behavior remains the default, e.g.:
	- Containers (AdaptiveCard, Container, Column) that do not have a background get no padding
	- Containers that do have a background get the default amount of padding

When the padding property is explicitly specified, it is applied as specified.

## Host Config
No changes, since spacing is already defined.

## Down-level impact (authors)
**Low**. Card still renders, padding is simply ignored.

## Down-level impact (hosts)
**None**. No changes, works for free.

### Example ([try it here](https://messagecardplayground.azurewebsites.net/)):
```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "padding": "none",
    "body": [
        {
            "type": "Container",
            "style": "emphasis",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "This container has a gray background that extends to th edges of th card",
                    "wrap": true
                }
            ]
        },
        {
            "type": "Container",
            "spacing": "none",
            "padding": "default",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "This other container does not have a background.",
                    "wrap": true
                }
            ]
        }
    ]
}
```

### As rendered:
![image](https://user-images.githubusercontent.com/1334689/42978461-ca894b6e-8b81-11e8-9f6f-988a582a954f.png)

### How it works:
In this example, the top container has a background color, and the desired result is that its background color extends to the edges of the card. But the card gets paddings by default, so we remove them by setting the card's "padding" property to "none".

The second container does not have a background, so per the basic rules (see above) its does not get any padding by default. Because of that, its content would normally touch the left and right edges of the card, which is not desirable. To compensate, its "padding" property is set to "default."

## Renderer Requirements

1. A renderer **should** render padding as specified, supporting top/left/bottom/right and supporting the behaviors described in this spec (correct default behaviors when padding not specified, etc)

**Comment by andrewleader** [comment]
Proposal has concerns: Need to run by partners to get feedback of whether Timeline and Notifications would be okay with this. Teams gut feeling is they wouldn't allow it.

**Comment by andrewleader** [comment]
We're not doing this for 1.2, instead we're going with the bleed proposal.

**Comment by paulcam206** [comment]
Not currently under consideration, but will reactivate should we decide to pursue.
