### ISSUE TITLE
Popup menu support

### ISSUE THREAD

**Issue by dclaux** [microsoft/AdaptiveCards#1728]
# Problem
Many scenarios call for a single UI affordance (be it a button or anything else) to popup a menu. This is useful to save space within a card, for example.

# Who's asking
- Outlook
- Cortana
- Windows Notifications (context menu)

**Comment by ignacionr** [comment]
Not too clear how this would differ from a Show Card action?

**Comment by andrewleader** [comment]
To be clear David, the Cortana/Notifications requirements here are where the *host* decides to draw a "..." popup button, *not* the card author. The card author doesn't get to decide where or how the "..." gets displayed.
