### ISSUE TITLE
Author ability to refresh card contents after action performed

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#1737]
# Problem

When the user takes an action on a card, like approving an expense report, the card often has to be updated, since the approve/deny buttons are no longer relevant.

# Prior designs

Outlook has this for Action.Http, called "refresh cards": https://docs.microsoft.com/en-us/outlook/actionable-messages/adaptive-card#refresh-cards

XML notifications has this via pending update: https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-pending-update

# Notes

* For toast notifications, the card itself disappears when acted on... so for scenarios like that, there's likely no need for the refresh. It's only for scenarios where the card continues to be displayed... a.k.a. bots, Outlook, etc, where updating the contents of the card is relevant. Maybe we could have an additional property, like *keepOnScreen*, that if set to true forces the notification to stay up? Allowing multi-step interactions?

**Comment by praveenpudi329** [comment]
Hi All, any updates on refreshing cards

**Comment by shalinijoshi19** [comment]
@praveenpudi329 can you please describe your scenario real quick? This is likely not going to come in any time this year since it's a huge chunk of work but @dclaux / @matthidinger are investigating a [broader issue around Universal Actions ](https://portal.productboard.com/adaptivecards/1-adaptive-cards-features/c/22-universal-action-model)that should help somebut that's still in very early investigation stages. It would help to understand your scenario to see how it would/could feed into requirements at this point. Thanks

**Comment by praveenpudi329** [comment]
> @praveenpudi329 can you please describe your scenario real quick? This is likely not going to come in any time this year since it's a huge chunk of work but @dclaux / @matthidinger are investigating a [broader issue around Universal Actions ](https://portal.productboard.com/adaptivecards/1-adaptive-cards-features/c/22-universal-action-model)that should help somebut that's still in very early investigation stages. It would help to understand your scenario to see how it would/could feed into requirements at this point. Thanks


Requirement : We want to send adaptive cards with approve/reject action to group/channel. once some one approves/reject the card, we want refresh the card with some message and hide the actions

**Comment by vigneshp826** [comment]
@shalinijoshi19 any update on this feature?

**Comment by paulcam206** [comment]
as noted above, this should be addressed by Universal Actions / Action.Execute
