### ISSUE TITLE
Support newline/linefeed in textblocks

### ISSUE THREAD

**Issue by billbliss** [microsoft/AdaptiveCards#1738]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android
* iOS
* JavaScript

# Author or host

Microsoft Teams

# Version of SDK

Latest master

# Issue

Please support \r in textblocks. There is no way to get a newline or a blank line currently.

**Comment by Kartik1607** [comment]
Adding `\r\r` or `\n\n` (notice `\r`  and `\n` are **2** times ) seems to do the trick.

**Comment by v-kydela** [comment]
@Kartik1607 - That works for newlines but there doesn't seem to be a way to include blank lines other than by using separate text blocks.

![image](https://user-images.githubusercontent.com/41968495/85331065-4b4c4e80-b48a-11ea-869b-a781c003ab18.png)

**Comment by trallnag** [comment]
@v-kydela @billbliss there is a way: Use a hidden unicode character between two newlines. Try it out with the following string

```
\n\n\n\n‌‌ \n\n\n\n
```

The whitespace is not a whitespace

**Comment by yashh007** [comment]
> @v-kydela @billbliss there is a way: Use a hidden unicode character between two newlines. Try it out with the following string
> 
> ```
> \n\n\n\n‌‌ \n\n\n\n
> ```
> 
> The whitespace is not a whitespace



> @v-kydela @billbliss there is a way: Use a hidden unicode character between two newlines. Try it out with the following string
> 
> ```
> \n\n\n\n‌‌ \n\n\n\n
> ```
> 
> The whitespace is not a whitespace

Thanks Its working.

**Comment by jonmill** [comment]
Tracked by #1984
