### ISSUE TITLE
Compact multiselect ChoiceSet 

### ISSUE THREAD

**Issue by FilipFilipov** [microsoft/AdaptiveCards#1744]
At the moment a ChoiceSet with `isMultiSelect: true` is rendered as a group of checkboxes regardless of the style property. For `style:compact` in html contexts shouldn't that be a `<select multiple>` instead?

**Comment by dclaux** [comment]
We think the checkbox UI is a lot more approachable for end users. `<select multiple>` forces the user to use CTRL or SHIFT to select multiple items; it isn't as straightforward as checkboxes.

**Comment by dclaux** [comment]
Oh I see. I guess what you're saying isn't that the CTRL+click multi-selection model is better, but that for long lists it would be great to have a way to not list all of the options one after the other (and end up with a massive card) Maybe we could honor the `"style": "compact"` property by grouping the checkboxes into an embedded scrolling area, maybe with its own border?

**Comment by FilipFilipov** [comment]
Yeah, that would probably work better from a usability standpoint.

**Comment by dclaux** [comment]
Will definitely keep that in mind, seems like it could indeed be an improvement. The only question mark is, how many scenarios are there that already set "style": "compact" even though it has no effect, and would it be ok for these scenarios to see their UI change suddenly. In any case we'd have a threshold, e.g. the ChoiceSet would have to have at least 4 entries or something before we apply the compact mode.

Thanks for the suggestion and for pointing out this issue!

**Comment by johnameyer** [comment]
Why was this closed? Was the proposed solution of "grouping the checkboxes into an embedded scrolling area" undesirable for some reason?
