### ISSUE TITLE
Nested ColumnSets do not render the HTML

### ISSUE THREAD

**Issue by smontsaroff-luxoft** [Microsoft/AdaptiveCards#1747]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML

# Author or host

Author: Stephen Montsaroff (stephm@pobox.com)

Rending cards using AdaptiveCards.Sample.Html

# Version of SDK

Lastest git master as of 7/31/2018 ( master 6311adfd)

# Issue

Nested Columnsets do not render properly.  Some columnsets do not display

Attached is a sample used (there are others) and its html output
[nestCols.html.txt](https://github.com/Microsoft/AdaptiveCards/files/2247439/nestCols.html.txt)
[nestCols.json.txt](https://github.com/Microsoft/AdaptiveCards/files/2247440/nestCols.json.txt)

**Comment by tuanh118** [comment]
@smontsaroff-luxoft should be fixed https://github.com/Microsoft/AdaptiveCards/pull/1772
