### ISSUE TITLE
Slow rendering of adaptive cards causes frame drops

### ISSUE THREAD

**Issue by rednivrug15** [microsoft/AdaptiveCards#1763]
# Platform
* Android

# Host
Microsoft Teams

# Version of SDK
1.0 / 1.1

# Issue
The slow rendering of cards ( due to extreme nested view hierarches created more than 15 levels of depth in some cases ) causes extreme slow rendering of cards 

```json
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"height": "stretch",
	"verticalContentAlignment": "center",
	"body": [
		{
			"type": "TextBlock",
			"text": "Hi,"
		},
		{
			"type": "TextBlock",
			"text": "MasterHip",
			"isSubtle": true
		},
		{
			"type": "ColumnSet",
			"height": "stretch",
			"columns": [
				{
					"type": "Column",
					"width": 1,
					"items": [
						{
							"type": "TextBlock",
							"text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet...",
							"wrap": true
						}
					]
				},
				{
					"type": "Column",
					"width": 1,
					"verticalContentAlignment": "top",
					"items": [
						{
							"type": "TextBlock",
							"text": "This text should be at the top",
							"wrap": true
						}
					]
				},
				{
					"type": "Column",
					"width": 1,
					"verticalContentAlignment": "center",
					"items": [
						{
							"type": "TextBlock",
							"text": "This text should be at the vertical center",
							"wrap": true
						}
					]
				},
				{
					"type": "Column",
					"width": 1,
					"verticalContentAlignment": "bottom",
					"items": [
						{
							"type": "TextBlock",
							"text": "This text should be at the bottom",
							"wrap": true
						}
					]
				}
			]
		}
	]
}
```

This card itself takes 20ms to render + 35ms to parse ( Each card should be rendered in < 15 ms to ensure no frame drops in android ) . More complex cards take 50+ms to render essentially making scrolling not possible .

**Comment by almedina-ms** [comment]
Have you tried to do the parsing in a background thread (making the call to function AdaptiveCard.DeserializeFromString(jsonText, AdaptiveCardRenderer.VERSION, elementParserRegistration); ) and after parsing rendering the result in the UI thread (calling this other function AdaptiveCardRenderer.getInstance().render(this, getSupportFragmentManager(), parseResult.GetAdaptiveCard(), this, hostConfig); ) ??

**Comment by rednivrug15** [comment]
We parse the json in main thread and cache it . But rendering needs to happen on main thread . I think the view hierarchy could be flattened a bit to allow fast rendering .

**Comment by rednivrug15** [comment]
Also the parser is really slow . Parsing should not ideally take more than a couple of milliseconds . Not sure but i feel it is a problem with the JSON library that is being used

**Comment by paulcam206** [comment]
Does this still repro on a more recent version of the renderer? If so, please feel free to reactivate.
