### ISSUE TITLE
Width of Adaptive Card is fixed for json

### ISSUE THREAD

**Issue by vijaysaimutyala** [microsoft/AdaptiveCards#1786]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Bot Framework Web Chat - json

# Author
We're sending cards to Bot Framework Web Chat Control

# Version of SDK - JSON - 1.0

# Issue
I need to display a table in the web chat control. Markdown table rendering is not really helpful and I switced to Adaptive Cards ColumnSet to display the table. The json is shown good in the [visualizer](http://adaptivecards.io/visualizer/index.html?hostApp=Bot%20Framework%20WebChat). Though some part of the text is wrapped, still its pretty decent.

But when the same is rendered on the web chat, all the dates are lost and it does not the required info. I tried modifying the width of the "wc-card", "wc-adaptive-card" properties on a custom build but with no results.

# Visualizer Output

![image](https://user-images.githubusercontent.com/7084628/43967244-9755a71c-9ce1-11e8-9c7a-da0073c88358.png)

# Web Chat Output
![image](https://user-images.githubusercontent.com/7084628/43967262-a27fc064-9ce1-11e8-88bf-e3deae9ea4a7.png)

# Source for the visualizer 
`{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type":"TextBlock",
            "text": "This is  a sample test that is being tested for the feasibility of testing the test and there on....."
        },
        {
            "type": "ColumnSet",            
            "columns": [
                {
                    "type": "Column",     
                    "items": [
                        {
                            "type": "TextBlock",
                            "weight": "bolder",
                            "text": "FPC"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "80322923"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "80322923"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "80322923"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "80322923"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "80322923"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "80322923"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "80322923"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "80322923"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "80322923"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "80322923"
                        }
                    ]
                },
                {
                    "type": "Column", 
                    "items": [
                        {
                            "type": "TextBlock",
                            "weight": "bolder",
                            "text": "LIFECYCLE"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "ARGENTINA"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "CHILE"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "COLOMBIA"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "COSTA RICA"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "ECUADOR"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "GUATEMALA"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "LADMAR CENTRAL AND C"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "LADMAR SOUTH AMERICA"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "MEXICO"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "PERU"
                        }
                    ]
                },
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "TextBlock",
                            "weight": "bolder",
                            "text": "NOT FOR SALES FLAG"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "N"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "N"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "N"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "N"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "N"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "N"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "N"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "N"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "N"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "N"
                        }
                    ]
                },
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "TextBlock",
                            "weight": "bolder",
                            "text": "CUSTOMER LIST PRICE DATE"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "7/25/2018"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "7/25/2018"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "7/25/2018"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "7/25/2018"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "7/25/2018"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "7/25/2018"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "7/25/2018"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "7/25/2018"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "7/25/2018"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "7/25/2018"
                        }
                    ]
                },
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "TextBlock",
                            "weight": "bolder",
                            "text": "SOS"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "12/1/2018"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "11/1/2018"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "11/1/2018"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "11/1/2018"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "11/1/2018"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "11/1/2018"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "11/1/2018"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "11/1/2018"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "10/1/2018"
                        },
                        {
                            "type": "TextBlock",
                            "separator": true,
                            "text": "11/1/2018"
                        }
                    ]
                }
            ]
        }
    ]
}`
Also tried the width and size properties as specified [here](https://github.com/Microsoft/BotFramework-WebChat/issues/923) without any luck. I'm not 100% sure if this belongs here or in the Web Chat repo. Am happy to move it there if its the case.

There is a [Similar issue on stackoverflow ](https://stackoverflow.com/questions/45206060/how-to-change-size-of-adaptive-card-within-message) which does not help.

**Comment by dclaux** [comment]
@vijaysaimutyala you unfortunately won't be able to do much better because you are really pushing the limits of how a 5 column table can look like when constrained to a limited space... That said, you have not set any size constraint on your columns, so they are all using 1/5th of the total width of the card. I suggest you experiment with setting the weight of your columns explicitly. For instance, you could give the two date columns a slightly higher weight to make sure they get more space than the other three columns. But again, such a dense table in such a small space isn't going to look great. Removing at least one column would help a lot I believe.

**Comment by vijaysaimutyala** [comment]
@dclaux I agree with you. That's a lot of data for the space we have. I was hoping that I could atleast achieve the width that was shown in the visualiser until I figure out a better way to do this.

**Comment by vijaysaimutyala** [comment]
An update.

HTML on Web Chat is turned off by default. If anyone were to render their HTML on Web Chat, they can turn it on by forking the repo and carrying out their build. Instruction for this are mentioned [here](https://blog.botframework.com/2017/09/07/html-not-supported-web-chat/).

Though the issue with table is resolved, I would still like to know if there is any way we can increase the width of an adaptive card.

**Comment by shalinijoshi19** [comment]
Dup of #4773 which is now being tracked for this work.
