### ISSUE TITLE
Infinite scroll when element.height is set to stretch

### ISSUE THREAD

**Issue by dptejas** [microsoft/AdaptiveCards#1794]
# Platform

* JavaScript

#  host

Outlook Actionable Messages in iOS and android

# Version of SDK

latest master

# Issue

When element.height is set to stretch there is infinite scroll issue in mobile devices. This is happening as flex property is set to "1 1 100%"

![issue-android](https://user-images.githubusercontent.com/35917092/44069184-3c26547e-9f9b-11e8-8364-a7cb20fbb01c.png)
![issue-ios](https://user-images.githubusercontent.com/35917092/44069185-3c53bac2-9f9b-11e8-8c9c-af194d991526.jpg)

# Fix

Set the flex property of the element to "1 1 auto".

**Comment by dptejas** [comment]
Merged with PR #1795

**Comment by compulim** [comment]
I bumped to AC 1.1 in Web Chat and we are still seeing this behavior.

Repro:
![image](https://user-images.githubusercontent.com/1622400/47451303-3e8acb00-d77c-11e8-8d7d-aa62d323c34a.png)

Links:
- [Web Chat PR that bump AC 1.1](https://github.com/Microsoft/BotFramework-WebChat/pull/1231)
- [Web Chat issue on this "too tall button"](https://github.com/Microsoft/BotFramework-WebChat/issues/1228)

**Comment by compulim** [comment]
We investigated and the layout weirdo is probably cause by missing HTML5 declaration `<!DOCTYPE html>` on the web page.

Although HTML5 is highly-recommended for everyone, on Web Chat, we also make sure developers can add Web Chat to their existing page which could be outdated but still works in IE11.

**Comment by jonmill** [comment]
IE11 is not a supported browser, so this issue is fixed
