### ISSUE TITLE
[HTML] Title for choiceset is not trimmed

### ISSUE THREAD

**Issue by kmkaliraj** [Microsoft/AdaptiveCards#1797]
*(Edited by andrewleader: Using this to track the bug that the text extends past the boundaries of the Adaptive Card, and we've [opened a separate feature to track allowing text wrapping](https://github.com/Microsoft/AdaptiveCards/issues/1821))*

# Platform
Bot Framework 
![bug](https://user-images.githubusercontent.com/23566351/44111340-006070b6-9fb7-11e8-9658-ec2437b2adb5.PNG)
Web chat
What platform is your issue or question related to? (Delete other platforms).

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards?

If you're an author, who are you sending cards to?

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

# Issue

Explain your issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards).

**Comment by matthidinger** [comment]
@dclaux are you able to look into this? If we make changes here should we also consider using `<label for="X" />` to improve the user experience and allow the user to tap on the text itself as opposed to just the radio and checkbox?

**Comment by dclaux** [comment]
I can look into this, and agreed about the label.

**Comment by dclaux** [comment]
@matthidinger Not sure we've ever addressed this, but should those long strings wrap in Input.Toggle and Input.ChoiceSet, or just be truncated?

**Comment by matthidinger** [comment]
Hmm yeah I don't recall explicitly addressing that. My gut feeling is we should reserve the right to interpret this on each renderer as the experience dictates, so maybe just truncate in most of them, but update our docs with guidance that the choice title should be <30 characters for optimal presentation?

**Comment by kmkaliraj** [comment]
My requirement is to make it wrapped. Could you please fix for wrapping?

**Comment by dclaux** [comment]
If I do it here it needs to be done in all other renderers, so it needs to a concerted decision. We will discuss and come up with a plan.

**Comment by dclaux** [comment]
Fix for properly truncating is here: https://github.com/Microsoft/AdaptiveCards/pull/1801

**Comment by andrewleader** [comment]
Thanks kmkaliraj and David! We can use this thread to track the HTML issue where the text doesn't get clipped correctly.

I've opened a new issue #1821 on the topic of whether we should wrap (which would have to be applied to all renderers)

**Comment by khouzam** [comment]
Closing since the issue has been merged.
