### ISSUE TITLE
[UWP] AdaptiveShowCardAction doesn't fire

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/AdaptiveCards#1805]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* UWP

# Author or host

Host rendering cards using the UWP Nuget API.

# Version of SDK

NuGet 1.0.1

# Issue

After calling `RenderAdaptiveCard` and adding to the visual tree as well as registering to the `Action` event, I never see a `AdaptiveShowCardAction` type in my event callback.  I see OpenUrl and Submit for other button types, but never this event when clicking on an action button.

The new card just automatically renders inline without this event firing as indicated by the [docs](https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/uwp/actions).

It also doesn't appear there's a way on this event to prevent the default inline render behavior?

```
            var renderedAdaptiveCard = _renderer.RenderAdaptiveCard(card);
            if (_border != null && renderedAdaptiveCard.FrameworkElement != null)
            {
                _border.Child = renderedAdaptiveCard.FrameworkElement;

                renderedAdaptiveCard.Action += RenderedAdaptiveCard_Action;
            }
```

```
        private async void RenderedAdaptiveCard_Action(RenderedAdaptiveCard sender, AdaptiveActionEventArgs args)
        {
            if (args.Action is AdaptiveOpenUrlAction openUrlAction)
            {
                // See this
            }
            else if (args.Action is AdaptiveShowCardAction showCardAction)
            {
                // Not this!!!
            }
            else if (args.Action is AdaptiveSubmitAction submitAction)
            {
                // See this
            }
```

I've used both the [ShowCard](https://adaptivecards.io/explorer/Action.ShowCard.html) sample and the [ActivityUpdate](https://adaptivecards.io/samples/ActivityUpdate.html) sample as input.

**Comment by michael-hawker** [comment]
Looks like this may be a documentation problem?

I think whether this event fires is dictated by the [ShowActionMode](https://docs.microsoft.com/en-us/adaptive-cards/rendering-cards/host-config#showactionmode) in the HostConfig?  If it's set to popup then I get this event.

**Comment by andrewleader** [comment]
Correct, this event only fires if ShowActionMode in HostConfig is set to "popup". By default, it's set to "inline", which means the renderer will automatically handle the ShowCard action click and won't trigger any event.

Thanks for [opening that docs bug](https://github.com/MicrosoftDocs/AdaptiveCards/issues/92)! We'll get that updated. Closing this issue.
