### ISSUE TITLE
name attribute of Input tag is not populated 

### ISSUE THREAD

**Issue by neel-hektor** [Microsoft/AdaptiveCards#1810]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML

# Author 

Sending Cards to Cortana as a 1st party skill

# Version of SDK
Version: 1.0.0 
https://www.nuget.org/packages/AdaptiveCards/1.0.0

# Issue
During Form submit the value of the `name` attribute is paired with the value of the `input` element. 
In its absence the input element value is not passed. 

e.g. 
`<label for="firstname">First name:</label>`
`<input type="text" name="firstname" id="firstname"></input>`

Query param will be added to URL during Form Submit as  ```&firstname=[InputValue]```

**Comment by andrewleader** [comment]
Hey @neel-hektor, can you provide a sample card payload that reproduces your issue?

And is this an accurate summary of your problem?

1. You're a card author sending a card to Cortana
2. You're using text inputs in your card
3. When the user types in the input and then clicks your button (**what's the action type of the button??** Action.Submit? Action.OpenUrl?), you don't receive their input

**Comment by neel-hektor** [comment]
Closing this issue since this was a problem with a missing aria label that was triaged wrongly
