### ISSUE TITLE
Request: Ability for ChoiceSet and Toggle text to wrap so that the text is all displayed

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#1821]
# Summary
Sometimes authors have choice sets that have lots of content, and they need that content to all be displayed. Truncating isn't an option, since information would be lost.

Same would be desired for Input.Toggle.

![bug](https://user-images.githubusercontent.com/23566351/44111340-006070b6-9fb7-11e8-9658-ec2437b2adb5.PNG)

# Asks

* Outlook
* [kmkaliraj](https://github.com/Microsoft/AdaptiveCards/issues/1797) (Bot author)
* [dkonyayev](https://github.com/Microsoft/AdaptiveCards/issues/1887#issuecomment-424833549) (Author?)
* [Shon-Elias](https://github.com/Microsoft/AdaptiveCards/issues/1887#issuecomment-448573317)

**Comment by kmkaliraj** [comment]
Thank you for creating an issue on this. Our team is waiting on the fix.

**Comment by andrewleader** [comment]
Shipped in 1.2!
