### ISSUE TITLE
Placeholder doesn't work for choice set drop down list

### ISSUE THREAD

**Issue by kmkaliraj** [Microsoft/AdaptiveCards#1831]
![issue](https://user-images.githubusercontent.com/23566351/44612984-51a40d80-a7c2-11e8-841b-321cb7f7a6d3.PNG)
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards?

If you're an author, who are you sending cards to?

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

# Issue

Explain your issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards).

**Comment by paulcam206** [comment]
I believe the problem is with `"value": "1",`. Since there's a pre-chosen value, the placeholder text isn't shown. If you clear the value, do you see the placeholder text? This seems to behave how I'd expect:

```json
    {
      "type": "Input.ChoiceSet",
      "style": "compact",
      "placeholder": "Please choose a color",
      "choices": [
        {
          "title": "Red",
          "value": "1"
        },
        {
          "title": "Green",
          "value": "2"
        },
        {
          "title": "Blue",
          "value": "3"
        }
      ]
    }
```

**Comment by khouzam** [comment]
This is by design. The placeholder should only be shown when there isn't a selection made to have some context on the choiceset.
