### ISSUE TITLE
JSON content not properly rendered on iOS devices.

### ISSUE THREAD

**Issue by shriyamgupta** [Microsoft/AdaptiveCards#1845]
For the following card content the JSON strings are rendered in HTML encoding rather than JSON strings on iOS devices for MS Teams App

Card Content file is attached below.
[CardContent.txt](https://github.com/Microsoft/AdaptiveCards/files/2344351/CardContent.txt)

<img width="497" alt="screen shot 2018-09-03 at 11 10 59 am" src="https://user-images.githubusercontent.com/42666174/44969502-1f856f00-af6b-11e8-8268-c1a986670cfa.png">
.

<img width="505" alt="screen shot 2018-09-03 at 11 11 18 am" src="https://user-images.githubusercontent.com/42666174/44969485-0ed4f900-af6b-11e8-910d-e3e8cb19f7bd.png">

**Comment by nesalang** [comment]
@shriyamgupta, is the screenshot at the bottom what the renderer should render?
Sample app's textBlock renderer will ignore all html tags as shown in the first screenshot.
Team's app use custom textBlock renderer that renders html tags.

**Comment by rednivrug15** [comment]
@nesalang the below text block just contains JSON 
`				"text": "{\"task\":{\"type\":\"continue\",\"value\":{\"title\":\"Custom Form\",\"height\":430,\"width\":510,\"fallbackUrl\":\"https:\/\/taskmoduletest.azurewebsites.net\/customform\",\"url\":\"https:\/\/taskmoduletest.azurewebsites.net\/customform\"}}}",
`

It should render as plain text .It renders correctly on Android and Desktop .

**Comment by shriyamgupta** [comment]
> @shriyamgupta, is the screenshot at the bottom what the renderer should render?
> Sample app's textBlock renderer will ignore all html tags as shown in the first screenshot.
> Team's app use custom textBlock renderer that renders html tags.
Sorry for the late reply but we were not using the custom label renderers in Teams iOS app for adaptive cards.
