### ISSUE TITLE
Input.ChoiceSet sends back ; separated values in Mobile renderers ( iOS and Android )

### ISSUE THREAD

**Issue by rednivrug15** [Microsoft/AdaptiveCards#1851]
# Platform

* Android
* iOS

# Host

Teams

# Version of SDK

1.0.0

# Issue

When an Action.Submit button is pressed Mobile SDK's ( Android and iOS ) return back ; separated values while the HTML renderer return back , separated values . This happens when multiple choice selection is allowed in Input.ChoiceSet . There should be a common experience for all the platforms .

**Comment by matthidinger** [comment]
@khouzam looks like we missed this for the 1.0 release. Per #652 they are indeed supposed to be comma separated. This fix to align all the renderers will be a breaking change so let's make sure we include that in the release notes for 1.1.
