### ISSUE TITLE
Choice Picker Configurability 

### ISSUE THREAD

**Issue by DuntyVinayRaj** [Microsoft/AdaptiveCards#1866]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

host

# Version of SDK

latest master

# Issue

The current Choice Picker expands in-line and doesnt have the option to configure it from the bottom of keyboard like Date Picker does. Say Im an host app where I would like the behavior of Pickers across the app to be uniform and should open on the window under beneath the Keyboard like Date Picker does, there isnt a configurability option.

**Comment by andrewleader** [comment]
Hey @DuntyVinayRaj, as a host, to configure behaviors of the ChoiceSet picker, you can override the rendering of the ChoiceSet element and choose to draw your own control (which shows a picker how you want).

See our docs on extensibility of the rendering: https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/ios/extensibility

Closing this issue, let us know if you have any further questions.
