### ISSUE TITLE
NuGet Package adaptivecards.rendering.xamarin

### ISSUE THREAD

**Issue by andrechi1** [microsoft/AdaptiveCards#1880]
I've searched the adaptivecards.rendering.xamarin package for IOS and Android on Xamarin. And they're not available. Are you expected to be sent to Nuget? Is there a date estimate?

I want to use it for a project I have in progress and I have to make a decision if I use the AdaptiveCards.

**Comment by andrewleader** [comment]
Thanks for requesting Xamarin support! This is a popular request which we're tracking here: https://adaptivecards.productboard.com/portal/1-adaptive-cards-portal/tabs/c88173a2-a3a1-4bc5-ad15-11051b3c7942/features/1961753/portal/expanded
