### ISSUE TITLE
FallbackCard Takes Language But Text Only in English

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#1881]
# Platform
* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

# Issue
Currently, the fallback card takes in two parameters to be created: `language` and `fallback text`. However, when the `fallback text` is passed in as empty (or isn't passed in at all), the default `fallback text` is a constant written in English. However, this is completely independent of the `language` parameter passed in, so the language could be non-English.

**Comment by RebeccaAnne** [comment]
@paulcam206 FYI
