### ISSUE TITLE
Inline text highlighting

### ISSUE THREAD

**Issue by dclaux** [Microsoft/AdaptiveCards#1885]
# Problem
Outlook partners are asking for a way to highlight a portion of a TextBlock. There is currently no way to do so.

# Proposed solution
Markdown officially allows html tags. We should allow the use of the standard <mark> tag in TextBlock. For instance:

```
{
    "type": "TextBlock",
    "text": "This is <mark>highlighted</mark>"
}
```

would result in the word "highlighted" being, well, highlighted.

The highlight color would have to be configurable in HostConfig as part of container styles. The associated font color for highlighted text would also have to be configurable (given that the highlight essentially changes the text's background color.) It would look like this:

```
{
        ...
        containerStyles: {
            default: {
                backgroundColor: "#FFFFFF",
                foregroundColors: {
                        ...
                },
                highlightBackgroundColor: "#0000FF",
                highlightForegroundColor: "#FFFFFF"
            },
            ...
        }
}
```

# Open questions

* How easy is it to programmatically construct markdown? There doesn't seem to be any libraries for it. Maybe we should use an array of runs instead?

# Alt solution

[Andrew Leader] Mimick what XAML does with RichTextBlock...

```json
{
  "type": "RichTextBlock",
  "wrap": 2,
  "paragraphs": [
    {
      "inlines": [
        {
          "type": "TextRun",
          "text": "This is "
        },
        {
          "type": "TextRun",
          "text": "highlighted",
          "highlight": true
        }
      ]
    }
  ]
}
```

This could also be our solution for inline colors, #1079, and inline advanced emojis #1645, and inline actions #865

**Comment by andrewleader** [comment]
Closing in favor of the consolidated inline text runs issue: #1933
