### ISSUE TITLE
Introduce wrap property on ChoiceSet/Toggle

### ISSUE THREAD

**Issue by dclaux** [Microsoft/AdaptiveCards#1887]
<table>
<tr>
<th>Release</th>
<th>Renderer status</th>
<th>Tasks status</th>
</tr>
<tr>
<td>1.2
<td>✔️ .NET (#2219)<br/>✔️ Android (#2218)<br/>✔️ iOS (#2216)<br/>🔄 TS (#2423)<br/>✔️ UWP (#2217)</td>
<td>✔️ Shared (#2215)</td>
</tr>
</table>

# Solves requests

* Ability for ChoiceSet and Toggle text to wrap so that the text is all displayed (#1821)

# Summary
Allow the authors to specify if they want their title to wrap. We could either:
1. Change the current behavior and always wrap. The risk here is to degrade the experience for some existing scenarios
2. Provide a setting in HostConfig to control title wrapping. This would allow hosts to opt into title wrapping
3. Allow card authors to decide

I recommend option 3, with the default being "no wrap" to maintain compatibility with the current behavior.

# Example
Add a **wrap** property to Input.Toggle:

```json
{
    "type": "Input.Toggle",
    "title": "This is a very long title",
    "wrap": true
}
```

Add a **wrap** property to Input.ChoiceSet:

```json
{
    "type": "Input.ChoiceSet",
    "choices": [
        { "title": "This choice has a very long title", "value": "1" },
        { "title": "This is another choice", "value": "2" }
    ],
    "wrap": true
}
```

# Host Config
No changes.

# Down-level impact
**Low**. Content simply won't wrap, but it never did anyways.

# Host burden
**None**. All handled by the renderer.

# Renderer Requirements

1. A renderer **should** respect the `wrap` property and display accordingly.

# Auto-generated task status

- [x] Shared
- [x] .NET
- [x] Android
- [x] iOS
- [ ] TS
- [x] UWP

**Comment by dkonyayev** [comment]
I also need this feature. Any ETA?

**Comment by khouzam** [comment]
This will most likely be part of our 1.2 release. No firm date on it though.

**Comment by andrewleader** [comment]
Proposal approved. Note that we also liked the proposal for adding a content property to ChoiceSet/Toggle, but for simplicity purposes, being able to easily control the text wrapping is desirable, so we also want this proposal.

**Comment by Shon-Elias** [comment]
Got an ETA for that?

**Comment by andrewleader** [comment]
@Shon-Elias this will most likely be part of our 1.2 release. We don't have a release date to share yet, 1.1 was just released two months ago.

**Comment by Shon-Elias** [comment]
Version 1.2 was released but it does not support most of the channels. 

I would like to use this feature for MS Teams but at the moment you are supporting only version 1.0.

Why is it take that long to support that feature? when will it be available for MS Teams users?

**Comment by andrewleader** [comment]
Microsoft Teams is working on updating to 1.2. You can send your feedback to them using their UserVoice: https://microsoftteams.uservoice.com/forums/555103-public
