### ISSUE TITLE
Proposal: border property on Containers

### ISSUE THREAD

**Issue by dclaux** [microsoft/AdaptiveCards#1890]
# Solves requests

* Allow borders on containers (#2033)

# Proposed solution
Add a border property to Container, ColumnSet and Column. The border property makes it possible to add a border on any side of the container.

The color of the border is controlled via HostConfig in container styles:
```
{
	...
	containerStyles: {
		default: {
			backgroundColor: "#FFFFFF",
			foregroundColors: {
				...
			},
			borderColor: "#EEEEEE"
		},
		...
	},
	...
}
```

## Example 1: Add a border all around
```
{
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "Container",
			"border": true,
			"items": [
				{
					"type": "TextBlock",
					"text": "This is <mark>highlighted</mark>"
				}
			]
		}
	]
}
```

## Example 2: Add a border only left and right
```
{
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "Container",
			"border": {
				"left": true,
				"right": true
			},
			"items": [
				{
					"type": "TextBlock",
					"text": "This is <mark>highlighted</mark>"
				}
			]
		}
	]
}
```

# Open question
Should we also support several border thicknesses?

**Comment by dclaux** [comment]
If we're going to have paddings (as it's shaping up to be), I think this should really not be a problem. That said, we could use the terms "outline" or "frame" instead of "border" if that makes a difference.

**Comment by GearTheWorld** [comment]
Thickness of the borders would be handy.  Right now I barely see them.

**Comment by dclaux** [comment]
@GearTheWorld what borders are you referring to? The entire card's border? If so that's something controlled solely by each host. If you are referring to borders around containers, there are none, which would explain why you don't see them ;)
