### ISSUE TITLE
Request: Support style on ColumnSet

### ISSUE THREAD

**Issue by dclaux** [microsoft/AdaptiveCards#1891]
# Problem
Though specialized, ColumnSet is a container. But unlike Container and Column, it doesn't support the style property. This forces card authors to either:
- Place their ColumnSet in a Container and set that Container's style
- Or set the style of each and every column in the set

While the second option above isn't too bad for as long as what the card author is interested in is the background color, it becomes more cumbersome if the card author wants to put a border around the entire ColumnSet ([proposal for border support](https://github.com/Microsoft/AdaptiveCards/issues/1890)) as it would mean setting borders on specific sides of each column.

# Asks

* Outlook

# Solution
Add support for **style** on ColumnSet.

**Comment by GearTheWorld** [comment]
Does that mean we will be able to set the thickness of the border of column set including column as well ?

**Comment by dclaux** [comment]
@GearTheWorld the border support proposal is here: https://github.com/Microsoft/AdaptiveCards/issues/1890

**Comment by andrewleader** [comment]
Shipped in 1.2!
