### ISSUE TITLE
Actions without title gets dropped in JavaScript

### ISSUE THREAD

**Issue by khouzam** [Microsoft/AdaptiveCards#1893]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

Related to #1883.

**Comment by dclaux** [comment]
@khouzam this should be fixed - did you establish that it wasn't?

**Comment by khouzam** [comment]
You're right. I jhad misclosed it when I saw the merge, but the merge didn't seem to mention this.

Anyway, you are right, the visualizer works as expected.

Thanks.
