### ISSUE TITLE
[Parser] Property values as "true" or "1" are sometimes parsed correctly

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#1901]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

# Author or host

Developer

# Version of SDK

master

# Issue

This card parses different in different shared models

```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "text": "This card has an action with an icon. Icon placement and size depend on host.",
      "wrap": "true"
    }
  ],
  "actions": [
    {
      "type": "Action.OpenUrl",
      "iconUrl": "http://adaptivecards.io/content/cats/1.png",
      "url": "http://adaptivecards.io",
      "title": "With Icon",
      "text": "This is text"
    }
  ]
}
```
UWP - fails parsing
![image](https://user-images.githubusercontent.com/35784165/45459737-a397cf00-b6ae-11e8-803f-88f943c4f1cf.png)

.NET - Parses and actually uses value
![image](https://user-images.githubusercontent.com/35784165/45459757-bc07e980-b6ae-11e8-9115-b20e0ba397b0.png)

JS - Parses but ignores value
![image](https://user-images.githubusercontent.com/35784165/45459790-d9d54e80-b6ae-11e8-911a-ae8d6f832634.png)

**Comment by jonmill** [comment]
This will be fixed with the convergence effort
