### ISSUE TITLE
[Parser] Visualizer accepts null values for strings

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#1905]
# Platform

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

# Author or host

Developer

# Version of SDK

master

# Issue

JS parser actually accepts null values in strings while .NET and UWP fail

Card example: 
```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "FactSet",
            "facts": [
                {
                    "title": "Fact 1",
					"value": null
                },
                {
                    "title": "Fact 2",
                    "value": "Value 2"
                },
                {
                    "title": "Fact 3",
                    "value": "Value 3"
                },
                {
                    "title": "Fact 4",
                    "value": "Value 5"
                }
            ]
        }
    ]
}
```

JS 
![image](https://user-images.githubusercontent.com/35784165/45507166-2a4bbb00-b746-11e8-946e-05c7dba18e0b.png)

.NET and UWP

![image](https://user-images.githubusercontent.com/35784165/45507271-6ed75680-b746-11e8-9f1e-7df7c0dee905.png)

![image](https://user-images.githubusercontent.com/35784165/45507250-62eb9480-b746-11e8-9024-5c9b0713d408.png)

**Comment by jonmill** [comment]
As we have shipped with this, we can't break this functionality. Closing
