### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#1907]
*By pritambaldota*

It would have been great if we have validation attributes for input field. For e.g. Required Field, Email type. These are very common scenario when we ask user to fill the information. User may type any invalid information and send that to API for further processing. This is very common scenario and other chat engines have this. For instance intercom chat does this. 

![image](https://user-images.githubusercontent.com/6270238/31873796-58f61b20-b77a-11e7-9e60-ae5f1f1396d1.png)

Whereas the the adaptive cards doesn't validate input on client side (http://adaptivecards.io/samples/InputForm.html). See the screenshot -
![image](https://user-images.githubusercontent.com/6270238/31873826-8f125674-b77a-11e7-9929-31bc2abfca99.png)

**Comment by shalinijoshi19** [comment]
@andrewleader, heads up - this seems to be tracked by issue #1978 yes? OK if i go ahead and close this out referencing that issue?

**Comment by andrewleader** [comment]
Yep go ahead and close!
