### ISSUE TITLE
Skype of Business Support

### ISSUE THREAD

**Issue by dkonyayev** [Microsoft/AdaptiveCards#1909]
I noticed that SFB is not in the timeline at all. Skype and Skype for Business do not render the same way. Is SFB supported by AdaptiveCards?

**Comment by matthidinger** [comment]
Hi @dkonyayev, we do not have plans for Skype for Business at this time. Most of the corporate collaboration work is focused on Microsoft Teams, which officially released Adaptive Card support last week.
