### ISSUE TITLE
[Parser] .NET and UWP accept negative column width ratios

### ISSUE THREAD

**Issue by almedina-ms** [Microsoft/AdaptiveCards#1914]
# Platform

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

# Author or host

Developer

# Version of SDK

master

# Issue

The JS Visualizer doesn't accept negative values for width ratio in columns

Card example: 

```
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "ColumnSet",
			"columns": [
				{
					"type": "Column",
					"width": -1,
					"items": [
						{
							"type": "TextBlock",
							"text": "Column 1 (10)"
						},
						{
							"type": "Image",
							"url": "http://adaptivecards.io/content/cats/1.png"
						}
					]
				},
				{
					"type": "Column",
					"width": 30,
					"items": [
						{
							"type": "TextBlock",
							"text": "Column 2 (30)"
						},
						{
							"type": "Image",
							"url": "http://adaptivecards.io/content/cats/1.png"
						}
					]
				},
				{
					"type": "Column",
					"width": 60,
					"items": [
						{
							"type": "TextBlock",
							"text": "Column 3 (60)"
						},
						{
							"type": "Image",
							"url": "http://adaptivecards.io/content/cats/1.png"
						}
					]
				}
			]
		}
	]
}
```

# Visualizer

![image](https://user-images.githubusercontent.com/35784165/45579637-0d92ae80-b83e-11e8-951e-b1f408c6a129.png)

# UWP and .NET

![image](https://user-images.githubusercontent.com/35784165/45579643-2307d880-b83e-11e8-8e54-2282d5bc09eb.png)

![image](https://user-images.githubusercontent.com/35784165/45579649-36b33f00-b83e-11e8-9095-6f61b3f9f4f2.png)

**Comment by dclaux** [comment]
The problem is that the other renderers/parsers do accept negative values, not the other way around. Any column weight <= 0 is invalid/meaningless. The JS renderer reverts to defaults (e.g. **auto**) when the width property of a column is invalid, and the other renderers should do the same.

**Comment by almedina-ms** [comment]
@khouzam UWP actually allows negative values but it gives them a size 1 so the column looks super small, for consistency, which should be the right behaviour??
