### ISSUE TITLE
Javascript displays "undefined" when "Action.Submit"'s "title" is missing

### ISSUE THREAD

**Issue by carlos-zamora** [Microsoft/AdaptiveCards#1921]
# Platform
* JavaScript

# Issue
`Action.Submit` buttons look different when missing `title`. In Javascript, "undefined" is shown. In .NET & UWP, the button is blank.

Example card:
```json
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "Action.Title is highly recommended, but for the time being not enforced",
            "wrap": true
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Good"
        },
        {
            "type": "Action.Submit"
        },
        {
            "type": "Action.Submit",
            "title": ""
        },
        {
            "type": "Action.Submit",
            "title": " "
        }
    ]
}
```

# Javascript
![image](https://user-images.githubusercontent.com/11050425/45715431-20142d00-bb49-11e8-865e-1af7eae45809.png)

# .NET & UWP
![image](https://user-images.githubusercontent.com/11050425/45715482-39b57480-bb49-11e8-82bf-2d58b4005c7a.png)

![image](https://user-images.githubusercontent.com/11050425/45715455-2a362b80-bb49-11e8-9cfe-6a9daaddf6a6.png)

**Comment by khouzam** [comment]
This has been fixed.
