### ISSUE TITLE
Markdown support in Fact Sets

### ISSUE THREAD

**Issue by rednivrug15** [Microsoft/AdaptiveCards#1930]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* Android

# Author or host

Host ( MS Teams )

# Version of SDK

Latest master

# Issue

Fact Sets allow markdown formatting in HTML and iOs renderer . The platform behaviour should be consistent ( Preferably allow markdown formatting )  .

**Comment by khouzam** [comment]
This does work in WPF and HTML. Doesn't work in UWP and Android.

**Comment by carlos-zamora** [comment]
Also works on iOS.
