### ISSUE TITLE
Request: Inline text highlighting

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#1934]
Outlook partners are asking for a way to highlight a portion of a TextBlock. There is currently no way to do so.

![image](https://user-images.githubusercontent.com/13246069/45834659-9e451080-bcbc-11e8-9539-cb5986dc024e.png)

# Asks

* Outlook partners

**Comment by andrewleader** [comment]
Shipped in 1.2!

**Comment by knt36** [comment]
Does the highlighting color change when the user is in high contrast mode? or even dark mode? and how do I control which color it changes to?
