### ISSUE TITLE
Proposal: Expand markdown functionality

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#1935]
# Solves requests

* Inline text colors (#1932)
* Inline highlighting (#1934)
* Monospace blocks of text (#1982)

# Summary
Expand markdown support to support scenarios like highlighting, text colors, etc.

# Schema
**New** additions to markdown support...

* HTML `<mark>` tag support
* Inline text color support
* \`\`\` block support

# Example

Inline highlighting...

```json
{
    "type": "TextBlock",
    "text": "This is <mark>highlighted</mark>"
}
```

Inline text colors...

```json
{
    "type": "TextBlock",
    "text": "[color=good](The Huffington Post) · 5/23/2016",
    "wrap": true,
    "maxLines": 2
}
```

Monospace blocks of text...

```json
{
  "type": "TextBlock",
  "text": "```
Error: Missing , on line number 5
```",
  "wrap": true
}
```

# Host Config
Hosts would need to be able to pick the highlight colors. And they would need to pick monospace fonts and maybe the styling of the monospace block background/border.

```json
{
        ...
        "containerStyles": {
            "default": {
                "backgroundColor": "#FFFFFF",
                "foregroundColors": {
                        ...
                },
                "highlightBackgroundColor": "#0000FF",
                "highlightForegroundColor": "#FFFFFF"
            },
            ...
        },
        "monospaceFont": "consolas",
        "monospaceBackground": "#CCCCCC"
}
```

# Down-level impact
**Medium**. Content appears, but has confusing tags around it.

# Host burden
**Low**. Hosts can customize if they wish.

# Renderer Requirements

* A renderer **MUST** at least understand the ``` markdown syntax and not display the ticks to the user (it'd be acceptable to display the content without monospace font, but that's not ideal)
* A renderer **SHOULD** display the ``` content within a styled block, using the monospace font
  * If *monospaceFontFamily* is specified in host config, renderer should use that font family
  * Otherwise, renderer should default to a reasonable font family (like Consolas)

**Comment by andrewleader** [comment]
Proposal has concerns: Concerns around the cost of expanding markdown support

**Comment by dclaux** [comment]
Do we really have to bundle all three features into one? I think it would be better to keep them separate, as that would allow us to prioritize each independently and spread the cost of a full implementation across several releases if necessary.

**Comment by andrewleader** [comment]
Agreed, the grouping of it doesn't imply that we'd have to do all of them in a single release, it simply allows us to envision the overall future better. We certainly could choose to do just one, or just two, for the upcoming release.

Also, I'm working on re-designing how we do requests and proposals (all the new issues you've possibly noticed), once I have a few "samples", I'll share out with you and the team to get feedback and see if this is how we want to operate for all requests/proposals/specs.

**Comment by andrewleader** [comment]
We've decided on inline text runs for 1.2, not adding to markdown support at this time. Potentially the ``` code block support might be desirable in the future though.
