### ISSUE TITLE
Request: IsRequired validation on inputs

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#1936]
Right now, users can submit a response with text boxes and other inputs that are completely empty. It'd be helpful if we at least added a property that makes an input required.

Below is an example of what the user would theoretically see after clicking Confirm when they haven't typed in the required text.

![image](https://user-images.githubusercontent.com/13246069/45521568-5fbacd80-b773-11e8-9d6f-3b577fffa431.png)

Maybe we should also visually indicate required fields before users type/submit? There's debate about the right pattern around that (using asterisks, or instead marking optional fields). Here's three articles in support of marking optional fields ([one](https://uxdesign.cc/form-field-required-vs-optional-9b4d7cdbf400), [two](http://uxmovement.com/forms/always-mark-optional-form-fields-not-required-ones/), [three](https://www.fusionbox.com/blog/detail/rethinking-the-red-required-asterisk-for-better-form-ux/599/)).

There are three sets of requirements that have been identified...

* Ability for an author to use instant validation to prevent the user from submitting without providing required values
  * This occurs when the user clicks the button
* Ability for the author to choose whether their inputs have a host-controlled "required" display treatment
  * Sometimes on simple cards, there's no benefit of a visual indication that a field is required, but authors still want to use the instant validation to prevent empty submission
* Ability for the author to also provide button(s) that do NOT require inputs
  * For example, an "I'll be late" button doesn't require inputs, but the "Snooze" button would require inputs. Users need to be able to click "I'll be late" without providing any inputs though!
 

# Asks

* Outlook
* Author - pritambaldota
* Author - thirteenflt

## Outlook requirements

Outlook also wants to be able to visually indicate that fields are required before the user types or submits anything. They want to be able to control this for visual consistency (rather than the author themselves adding "(Optional)" text to their placeholders or anything else).

They do this today using extension properties, and they draw a black asterisk on the right side of the required input, similar to below (except in black, and no explanation of what the asterisk signifies)

![image](https://user-images.githubusercontent.com/13246069/45846839-d3ae2600-bcdd-11e8-8536-a43ccadc0c1b.png)

## Notification requirements

We didn't explicitly ask for this, but it seems nice! There's some scenarios to consider, where one button requires inputs while another button doesn't.

![image](https://user-images.githubusercontent.com/13246069/45849932-d82c0c00-bce8-11e8-938f-ddc42e1176bb.png)

**Comment by RebeccaAnne** [comment]
Implemented with Input Validation feature work.

**Comment by shalinijoshi19** [comment]
dup #3081
