### ISSUE TITLE
Proposal: Add requiredInputs to actions

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#1937]
# Implementation status

- [ ] .NET
- [ ] Android
- [ ] iOS
- [ ] JavaScript
- [ ] UWP
- [ ] Documentation

# Solves requests

* Basic IsRequired validation on inputs #1936

# Summary
Add a `requiredInputs` property on `Action` elements.

# Schema
**New** property on `Action` 

Property|Type|Required|Description
---|---|---|---
requiredInputs|string[]|false|Specifies which inputs are required. If values are missing from those inputs when clicking this action, validation errors will be displayed and the action won't be performed.

**OPEN QUESTION**: Should we also allow authors to provide custom text for the validation error? Maybe that's a vNext feature? Or maybe we do it now? It probably shouldn't be required for authors to provide that text though, there's something nice about not needing to provide that text.

# Example
```json
{
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "text": "Please confirm your username"
    },
    {
      "type": "Input.Text",
      "id": "username",
      "placeholder": "Username"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Confirm",
      "data": "action=confirm",
      "requiredInputs": [
        "username"
      ]
    },
    {
      "type": "Action.Submit",
      "title": "Cancel",
      "data": "action=cancel"
    }
  ]
}
```

**Initial state**
![image](https://user-images.githubusercontent.com/13246069/45521370-7dd3fe00-b772-11e8-9dc9-ad2df5cb6659.png)

**User clicks Confirm**, we show validation errors (and trigger event to host telling host where it needs to scroll to, in case some of the invalid fields were off-screen)
![image](https://user-images.githubusercontent.com/13246069/45521568-5fbacd80-b773-11e8-9d6f-3b577fffa431.png)

**User changes the input value**, we remove the validation error. We'll re-validate upon button press again. So even if they type "a" and then delete it, the validation error should remain removed.

![image](https://user-images.githubusercontent.com/13246069/45521705-0acb8700-b774-11e8-9410-261fa43794e6.png)

Note that **we do NOT place the validation above the input**, since it breaks the flow of the header text related to the input. And we can't place the validation above the header text, since inputs don't have a header property.

![image](https://user-images.githubusercontent.com/13246069/45521586-782ae800-b773-11e8-83fd-cb71b4e0a680.png)

**Other inputs**

![image](https://user-images.githubusercontent.com/13246069/45521920-166b7d80-b775-11e8-956c-d4fe267247c4.png) ![image](https://user-images.githubusercontent.com/13246069/45522135-086a2c80-b776-11e8-886f-9f966e6d15cb.png)

# Host Config
**New** validation object that allows hosts to **optionally** specify what required text they want. This is so that hosts can localize to the language they're running in. Plus, their app might have a different wording for validation errors, like "Value required".

```json
{
  "fontFamily": "Segoe UI",
  "validation": {
    "requiredText": "Required"
  }
}
```

# Down-level impact
Medium. Authors need to expect that users running down-level can still submit the card with empty inputs (most concerning for new authors who might assume that required property works, existing authors should already have that logic).

# Host burden
**Low**. Hosts can optionally customize if they wish, but they don't have to.

## Renderer Requirements

1. A renderer **must** respect the `requiredInputs` property and not allow action execution until the required inputs are fulfilled.
1. A renderer **should** display the validation errors as described in this spec.
1. If displaying validation errors, a renderer **must** use the text provided in the host config. If none is specified, use `"Required"`

**OPEN QUESTION**: If host didn't provide "Required" text, should we use localized versions based on the locale of the card and client?

**Comment by dclaux** [comment]
This proposal is somewhat problematic for Outlook and its `Action.Http` action type. Action.Http uses [input value substitution](https://docs.microsoft.com/en-us/outlook/actionable-messages/adaptive-card#input-value-substitution) which makes it explicit which input values are to be sent to the host when the action is executed. Coupled with an `isRequired` property specified on the input itself, Outlook's Action.Http model is functionally equivalent to this requiredInputs proposal but is in my opinion more elegant/practical as it keeps validation coupled with inputs.

***But*** Outlook's Action.Http is custom and can't really be used as an argument for how we should design this feature.

However, a model where the "required" aspect of an input is specified at the input level has the big advantage of **making it possible for the card to visually identify which inputs are required before any action is executed**, as is done in basically all online forms. I think this capability is very important for Adaptive Cards to support as it will make for a much better end user experience.
