### ISSUE TITLE
ChoiceSet IsSelected=True not working on BotEmulator

### ISSUE THREAD

**Issue by dkonyayev** [Microsoft/AdaptiveCards#1950]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML

# Author or host

Author using BotEmulator

# Version of SDK

AdaptiveCards v 0.5.1

# Issue

On BotEmulator, items marked as IsSelected=true in ChoiceSet are not selected/checked.

**Comment by khouzam** [comment]
Hi @dkonyayev,

Can you please try on a more recent version? 0.5.1 was a preview that did not have all features implemented.

Thank you.

**Comment by dkonyayev** [comment]
When I do a search for Microsoft.AdaptiveCards using Nuget Package Manager in Visual Studio it only finds version "Latest Stable 0.5.1". Should I clone the project and make it part of my solution?

**Comment by dkonyayev** [comment]
I could swear I read somewhere for another issue to go from AdaptiveCards to Microsoft.AdaptiveCards, and I have. I will go back, hopefully whatever the old issue was it will not reappear.

**Comment by dkonyayev** [comment]
I upgraded to AdaptiveCards 1.0.3 and the issue still exists in BotEmulator. I will be moving this to environment where I can use webchat and I will test it there as well.

**Comment by khouzam** [comment]
Sorry, I had misread the issue. 

This is actually expected. `isSelected` has been deprecated from the `Choice` in favor is `ChoiceSet.Value` as described in our [documentation](adaptivecards.io/explorer/Input.ChoiceSet.html)

**Comment by dkonyayev** [comment]
Thank you, that fixed the issue.
