### ISSUE TITLE
UWP: Debugger throws break in PayloadValidator

### ISSUE THREAD

**Issue by carlos-zamora** [Microsoft/AdaptiveCards#1973]
# Platform
* UWP

# Issue

Debugging a card using the AdaptiveCardVisualizer always throws `Debugger.Break()` from `PayloadValidator.cs` (Line 68). I'm pretty sure it works with any card but, for repro purposes, I've used `TextBlock.Markdown.json`

**Comment by paulcam206** [comment]
So it looks like we *do* have some schema validation going on... in the UWP visualizer. I'll see if I can fix up the schema in a way that generates decent documentation and doesn't cause the visualizer to get crabby.

**Comment by khouzam** [comment]
merged
