### ISSUE TITLE
Timeline cuts off FactSet improperly

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#1975]
# Platform
* UWP

# Issue
When a card has a `FactSet` at the end and it is too big to fit in the timeline card, the card should remove the `FactSet` as follows: 
![image](https://user-images.githubusercontent.com/11050425/46176792-6eba7900-c265-11e8-9197-b6951cd93232.png)

However, using the UWPTestApp, the text from the `FactSet` is cut off and displays as such:
![image](https://user-images.githubusercontent.com/11050425/46176831-8a258400-c265-11e8-8a1d-c6dc4b0d6e9a.png)

To reproduce, you can use the card `LongFactSet.json`. Copied here for convenience:
```
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "TextBlock",
			"text": "Nutrition facts",
			"size": "large",
			"weight": "bolder"
		},
		{
			"type": "TextBlock",
			"text": "Per 3 cookies (36 g)"
		},
		{
			"type": "TextBlock",
			"text": "Calories 180",
			"weight": "bolder"
		},
		{
			"type": "FactSet",
			"facts": [
				{
					"title": "Fat",
					"value": "10 g"
				},
				{
					"title": "Saturated",
					"value": "4 g"
				},
				{
					"title": "+ Trans",
					"value": "0 g"
				},
				{
					"title": "Cholesterol",
					"value": "5 mg"
				},
				{
					"title": "Sodium",
					"value": "100 mg"
				},
				{
					"title": "Carbohydrate",
					"value": "24 g"
				},
				{
					"title": "Fibre",
					"value": "0 g"
				},
				{
					"title": "Sugars",
					"value": "12 g"
				},
				{
					"title": "Protein",
					"value": "2 g"
				},
				{
					"title": "Vitamin A",
					"value": "0 %"
				},
				{
					"title": "Vitamin C",
					"value": "0 %"
				},
				{
					"title": "Calcium",
					"value": "0 %"
				},
				{
					"title": "Iron",
					"value": "6 %"
				}
			]
		}
	]
}
```

**Comment by jonmill** [comment]
The Card does not know what will fit or not fit in the client rendering area and will make the best-effort attempt to display the card payload...so this is currently by-design.
