### ISSUE TITLE
BadRequest error with MS Teams

### ISSUE THREAD

**Issue by dkonyayev** [Microsoft/AdaptiveCards#1986]
# Platform

What platform is your issue or question related to? (Delete other platforms).

BotFramework, AdoptiveCards on MS Teams

# Version of SDK

1.0.2

# Issue

When returning a AdoptiveCard attachment to MS Teams client I get an  odd error. I am not in Developer Preview, but the error seems to occur on server side. I have traced it all the way to context.PostAsync function, and the error occurs somewhere in there. I am able to have regular text chat with MS Teams.

Microsoft.Bot.Connector.ErrorResponseException: Operation returned an invalid status code 'BadRequest'

**Comment by dkonyayev** [comment]
This morning I activated "Developer Preview" on my MS Teams and still got the same message. I am able to display a very simple card (just textbox and few action buttons). The card that it fails on is more complicated and has ChoiseSet, Date, Time, and Number Input controls.

**Comment by dkonyayev** [comment]
@rednivrug15  see attached file
[1986_sample_json.txt](https://github.com/Microsoft/AdaptiveCards/files/2439326/1986_sample_json.txt)

**Comment by rednivrug15** [comment]
@dkonyayev I think the issue is with the min value of Input.Number ( currently it is Nan which is causing the server to reject the payload ) . Can you please try changing it to a number ?.

**Comment by dkonyayev** [comment]
That was it. Thanks!
