### ISSUE TITLE
Android DateInputRenderer OnClick Crash

### ISSUE THREAD

**Issue by gnamse** [Microsoft/AdaptiveCards#1987]
# Platform
* Android (Xamarin Froms)

# Version of SDK
Adaptive card 1.0.4

# Issue
When i click on an input date in android, i get the following error:

`io.adaptivecards.renderer.input.DateInputRenderer$1.onClick
DateInputRenderer.java - line 112
java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentTransaction android.support.v4.app.FragmentManager.beginTransaction()' on a null object reference`

**Comment by gnamse** [comment]
I'm using API 26

**Comment by gnamse** [comment]
The bug is in DateInputRender.java
I replaced like 112 from
`
FragmentManager fm = dateInputHandler.getFragmentManager();
datePickerFragment.show(fm, TITLE);
`
to 
`
datePickerFragment.show(fragmentManager, TITLE);
`

**Comment by almedina-ms** [comment]
Hey
I'm trying to repro the issue in SDK 1.0.4 android API 26 in an emulator using the mobile app but I haven't made it crash. I'm using the Input.Date.json for testing, can you repro the same issue with the same card?

**Comment by gnamse** [comment]
I'm using adaptive card 1.0.4 with Xamarin Forms Android. 

Still got the same error when i tested it with  Input.Date.json. 

`dateInputHandler.getFragmentManager()` returns null

Seems to work fine in android studio.

**Comment by gnamse** [comment]
Check out the latest master branch and the issue has been sorted.

**Comment by khouzam** [comment]
Thanks for confirming @gnamse.

Closing the issue then.
