### ISSUE TITLE
Request: Inline actions within text

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#1990]
# Summary

There are quite a few scenarios where it makes sense to have an action displayed as a link on a part of the text in a TextBlock. As an example, GitHub is showing this as I write this issue:

![image](https://user-images.githubusercontent.com/1334689/32185944-f07d4df4-bd5d-11e7-806f-fb36aa874c06.png)

In that screenshot, **contributing** is just a link, but in the context of Adaptive, card authors may want to hook it to a Submit or ShowCard action (or even Http action in Outlook.)

# Asks

* Microsoft Teams
* Outlook

**Comment by andrewleader** [comment]
Shipped in 1.2!

**Comment by msftjayongg** [comment]
Is there a sample of this?  I saw the release notes but couldn't figure out how to do this.
