### ISSUE TITLE
Request: Allow embedding image data locally within card

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#1991]
Some cards needs images that aren't available on the public internet. This also alleviates making many HTTP requests for cards with multiple sprite-like images.

# Asks

* Timeline partners
* GearTheWorld (see below)

**Comment by GearTheWorld** [comment]
I back this request.  Excellent idea !

**Comment by andrewleader** [comment]
Shipped in 1.2! dataUris can be used in image urls!
