### ISSUE TITLE
Request: Bleeding background images/colors for containers

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2013]
There is currently no way to make an image (or background color) bleed to the edges of the card aside from using the backgroundImage property of the card.

There are plenty of scenarios that call for an image as the header or footer of a card, bleeding to the edges of the card, while the rest of the card has padding and no background.

![img](https://user-images.githubusercontent.com/1334689/42978461-ca894b6e-8b81-11e8-9f6f-988a582a954f.png)

# Asks

* Outlook

**Comment by ritwikrd** [comment]
what is the eta of this request? it would be great to have this

**Comment by andrewleader** [comment]
Hey @ritwikrd thanks for the interest! We're primarily considering the #2019 proposal (bleed property) to solve this request. Could you take a look at that proposal and see if it'll work for your scenario?

**Comment by andrewleader** [comment]
Shipped in 1.2!
