### ISSUE TITLE
Request: Be able to use actions (buttons) anywhere within card body

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2027]
Currently you can only use actions at the bottom of the card. Some authors want the ability to use actions elsewhere within the body.

# Asks

* Outlook
* Notifications
  * Quick Pair
* Cortana
* vishwa306 (see comment below)
* pschaeflein (see comment below)

# Example comps

Quick Pair team would like to have buttons inside the body of their adaptive card

![image](https://user-images.githubusercontent.com/13246069/31154685-a45f52ec-a85d-11e7-92b5-c4af6f5da1df.png)

![image](https://user-images.githubusercontent.com/13246069/47676305-7c6f6100-db79-11e8-8203-169de1d08b54.png)

![image](https://user-images.githubusercontent.com/13246069/47676697-880f5780-db7a-11e8-946e-553e3857d36a.png)

![image](https://user-images.githubusercontent.com/13246069/47679257-15ee4100-db81-11e8-89fb-46b2399cd2b1.png)

## Outlook examples

![image](https://user-images.githubusercontent.com/13246069/47677254-dec96100-db7b-11e8-8422-74c0f686a403.png)

### Inline quick button for exporting as PDF

![image](https://user-images.githubusercontent.com/13246069/47677336-0c160f00-db7c-11e8-91bd-193de7fab103.png)

### Buttons to right of image

![image](https://user-images.githubusercontent.com/13246069/47677452-58f9e580-db7c-11e8-878e-9c2019f41fb1.png)

### Buttons and content inside a really fancy container

![image](https://user-images.githubusercontent.com/13246069/47677483-7333c380-db7c-11e8-8c79-0d8af6141e13.png)

**Comment by vishwa306** [comment]
Second @andrewleader on this request. This is needed for buttons within multi-attachment messages inside Teams.

**Comment by pschaeflein** [comment]
FYI - you can do this in Outlook by using the [ActionSet element](url
https://docs.microsoft.com/en-us/outlook/actionable-messages/adaptive-card#outlook-specific-adaptive-card-properties-and-features).

Agree that this functionality in the core spec would be great.

**Comment by andrewleader** [comment]
Shipped in 1.2!
