### ISSUE TITLE
Bug: When using .NET SDK and setting Spacing=Large, it also sets deprecated Separation property

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#2037]
# Platform

* .NET

# Author or host

Author creating cards with .NET SDK

# Version of SDK

AdaptiveCards 1.1.0

# Issue

When adding a text block with Spacing=Large and then serializing to JSON, it also adds the deprecated Separation property, generating a warning in the Visualizer (and incorrectly adding a separator when I didn't want one).

![image](https://user-images.githubusercontent.com/13246069/46897863-1a54f300-ce3a-11e8-9104-1c90085742c1.png)

![image](https://user-images.githubusercontent.com/13246069/46897856-12954e80-ce3a-11e8-867d-bf9aaf090628.png)

**Comment by khouzam** [comment]
This has been merged through PR #2275
