### ISSUE TITLE
Issue Opening huge images in Android

### ISSUE THREAD

**Issue by desaibijon** [microsoft/AdaptiveCards#2038]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android

# Author or host
Host

# Version of SDK
android v 1.0

# Issue

I am having trouble rendering huge/big size images on the adaptive cards. It throws an OutOfMemoryError while decoding thee byte array for the bitmap. The image in question is https://res.cloudinary.com/zerocater/image/upload/v1439520196/zhdam4pyoauurj6uomzn.jpg

I agree that the image in question is a very big image, but I am looking for a solution where I can override SDK methods to downsize the image, so that it fits. 

I have tried using [Loading Large Bitmaps](https://developer.android.com/topic/performance/graphics/load-bitmap) but in vain.

I hope this is an issue, you guys can help me fix.

**Comment by andrewleader** [comment]
@khouzam can we harden our Android renderer to handle large image sizes? Seems like a risk that an author could send a huge image and eat up all of the host app's memory.

**Comment by khouzam** [comment]
As a potential solution, you can use our resource resolver model for you to intercept the bitmap call and provide back a reduced image avoiding the OutOfMemory exception.

@andrewleader, that's an interesting idea, I'm not sure though what limits should be enforced. Perhaps simply catching the out of memory exception and failing the card, so that the app doesn't get terminated.

**Comment by desaibijon** [comment]
@khouzam Thank You for your tip, but I was not able to locate any resource resolver model in the adaptive cards sdk. I have tried overriding OnlineImageLoader and registered my own ImageLoader, if that is what you mean by a resource resolver, but that has not helped me yet.

**Comment by khouzam** [comment]
Yes, the OnlineImageLoader is the way to handle this case. When you get invoked with the call to `loadImageOnline`, you should do the resize and return the scaled down bitmap. Is this not working?

**Comment by khouzam** [comment]
Sorry @desaibijon, 'm not sure that I understand the comment: `the scaled down image is too small for the max scale factor I can pass through`.

How are you scaling the image and to what resolution? You should have control over those parameters and find an adequate size for the card.

**Comment by desaibijon** [comment]
I am sorry if I was not clear with my comment. Thank You for your tip, I will look into my methods of resizing the image. For now, I am using BitmapFactory.options and [Loading Large Images using Bitmap](https://developer.android.com/topic/performance/graphics/load-bitmap) as my guide.

**Comment by khouzam** [comment]
We'll need to think about perhaps being smarter in the platform about this situation.
