### ISSUE TITLE
Select Action With Hyperlink

### ISSUE THREAD

**Issue by nesalang** [microsoft/AdaptiveCards#2107]
# Platform

* Android
* UWP

# Version of SDK

1.1

# Issue
Precondition: TextBlock with the wrap attribute set true, with hyperlink, and with horizontal alignment set "Right" is contained in a Container which has a selectAction. The empty space on the left of the text is clicked or touched.
Expected: the selectAction in container is triggered.
Actual: hyperlink is opened.
```
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
           {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "[Select](http://adaptivecards.io) Choice",
                    "horizontalAlignment":"Right",
                    "wrap":true
                }
            ],
            "selectAction": {
                "type": "Action.Submit",
                "title": "Submit action",
                "data": {
                    "info": "Data of choice 2"
                }
            }
        }
    ]
}
```
![Capture](https://user-images.githubusercontent.com/4112696/62391655-4ac96300-b51a-11e9-915f-f76c30343266.PNG)

White space on the left is active hyperlink.

**Comment by shalinijoshi19** [comment]
@nesalang please go ahead file 2 separate bugs for the 2 different platforms this bug still applies to.

**Comment by nesalang** [comment]
There is also a xml bug tracking this issue: https://github.com/microsoft/microsoft-ui-xaml/issues/1125
