### ISSUE TITLE
Discrepancies between different renderers

### ISSUE THREAD

**Issue by rednivrug15** [microsoft/AdaptiveCards#2111]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML
* Android
* iOS

# Author or host

Host ( Teams )
Any version

Inconsistencies between renderers : 

1.   Consider any card element which has a required field . Example TextBlock has text as required property . In case the developer does not specify test , this card is dropped on Android and iOs ( Probably WPF renderer as well as it uses the same shared code ) . While the HTML renderer will continue rendering the rest of the card and just drop the element . 

**Sample**

```JSON
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "Container",
			"items": [
				{
					"type": "TextBlock"
				
				},
				{
					"type": "ColumnSet",
					"columns": [
						{
							"type": "Column",
							"width": "auto",
							"items": [
								{
									"type": "Image",
									"url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg",
									"size": "small",
									"style": "person"
								}
							]
						},
						{
							"type": "Column",
							"width": "stretch",
							"items": [
								{
									"type": "TextBlock",
									"text": "Matt Hidinger",
									"weight": "bolder",
									"wrap": true
								},
								{
									"type": "TextBlock",
									"spacing": "none",
									"text": "Created {{DATE(2017-02-14T06:08:39Z,SHORT)}}",
									"isSubtle": true,
									"wrap": true
								}
							]
						}
					]
				}
			]
		},
		{
			"type": "Container",
			"items": [
				{
					"type": "TextBlock",
					"text": "Now that we have defined the main rules and features of the format, we need to produce a schema and publish it to GitHub. The schema will be the starting point of our reference documentation.",
					"wrap": true
				},
				{
					"type": "FactSet",
					"facts": [
						{
							"title": "Board:",
							"value": "Adaptive Card"
						},
						{
							"title": "List:",
							"value": "Backlog"
						},
						{
							"title": "Assigned to:",
							"value": "Matt Hidinger"
						},
						{
							"title": "Due date:",
							"value": "Not set"
						}
					]
				}
			]
		}
	],
	"actions": [
		{
			"type": "Action.ShowCard",
			"title": "Set due date",
			"card": {
				"type": "AdaptiveCard",
				"body": [
					{
						"type": "Input.Date",
						"id": "dueDate",
						"title": "Select due date"
					},
					{
						"type": "Input.Text",
						"id": "comment",
						"isMultiline": true,
						"placeholder": "Add a comment"
					}
				],
				"actions": [
				    {
				        "type": "Action.OpenUrl",
						"title": "OK",
						"url": "http://adaptivecards.io"
			        }
				]
			}
		},
		{
			"type": "Action.OpenUrl",
			"title": "View",
			"url": "http://adaptivecards.io"
		}
	]
}

```

2. In case of empty textBlocks ( "text" : "" )  , Android and iOS renderers will add the text View plus the spacing while the HTML renderer will add only spacing . There should be a parity in this . 

Sample : [Card](https://adaptivecards.io/samples/FlightUpdate.html)

**Comment by khouzam** [comment]
I absolutely agree that we need to have consistent behavior between the renderers.

But I'm not sure which is the right one, this needs to be discussed.

**Comment by shalinijoshi19** [comment]
Thanks @rednivrug15 ; 
This (inconsistency across renderer implementations)  is a problem we are trying to slowly address ; Part of it is ambiguous Spec design when they are first drawn up, part of it is the complexity of implementing one feature in a specific platform vs another -- in which case we should at least document and have a plan to converge eventually (assuming the feature itself makes sense). We will keep this open and use this to track the consistency problem in general. Thanks

**Comment by andrewleader** [comment]
Thanks @rednivrug15, the first issue is being tracked with #3154, and the second issue is being tracked with #641
