### ISSUE TITLE
Background Image is not rendered when custom rendering is Enabled [iOS]

### ISSUE THREAD

**Issue by an888ha** [Microsoft/AdaptiveCards#2138]
# Platform
iOS
# Version
1.1 and 1.0

# Description :
Background image is not being rendered in iOS if there is a custom image renderer. Happening on sample App too.

I guess its because of this code.
```objc
UIView *imgView = nil;
    UIImage *img = nil;
if(![[ACRRegistration getInstance] isElementRendererOverriden:[ACRImageRenderer elemType]]){
        img = _imageViewMap[key];

        imgView = [[ACRUIImageView alloc] initWithImage:img];

    }
```

**Comment by an888ha** [comment]
Platform
iOS

Version
1.1 and 1.0

Description :
Background image is not being rendered in iOS if there is a custom image renderer. Happening on sample App too.
I guess its because of this code.
UIView *imgView = nil;

        UIImage *img = nil;

if(![[ACRRegistration getInstance] isElementRendererOverriden:[ACRImageRenderer elemType]]){

            img = _imageViewMap[key];

            imgView = [[ACRUIImageView alloc] initWithImage:img];

        }

**Comment by an888ha** [comment]
Can use weather large cards in sample App for repro.

**Comment by khouzam** [comment]
Reopening for cherry-picking into 1.1

**Comment by khouzam** [comment]
Closing as this has been merged.
