### ISSUE TITLE
Adaptive Card Designer : Invalid column width

### ISSUE THREAD

**Issue by Kartik1607** [microsoft/AdaptiveCards#2143]
The designer changes the column width from a number to an object 
```
                    "width": {
                        "physicalSize": 30,
                        "unit": 0
                    }
```

This causes rendering issues in the designer.

Expected : 
```
"width":30
```

**Comment by dclaux** [comment]
Thanks for reporting, we will fix ASAP.

**Comment by dclaux** [comment]
Actually I can't repro in the latest build.

**Comment by Kartik1607** [comment]
Steps to repro in [Adaptive card designer website](https://adaptivecards.io/designer/)

1.  Click on new card.
2. Drag a column set in body.
3. Click on add column twice in the  *Element Properties* tab.
4. For each column set width to weighted and leave weight to 50.
5. Copy columnset part of JSON and paste it to make another column set. 
```{
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "width": 50
                },
                {
                    "type": "Column",
                    "width": 50
                }
            ]
        }
```
6. Now click on second column set in *Visual Tree* and delete it.
7. Width property of first column set is not changed from number to an object, which causes render issues.

Let me know, if this helps.  If not, here is a video I recorded : [Video here](https://www.youtube.com/watch?v=HaVfkjMDRR4)

**Comment by dclaux** [comment]
Wow that's a good one :) Will fix ASAP, thanks for the detailed repro steps!

**Comment by solidcloudio** [comment]
I've also produced this simply by adding an Id value..  The online editor outputs the JSON incorrectly..

I forked master and added few unit tests the show this..  (Although you can simply reproduce it in the online editor)

https://github.com/solidcloudio/AdaptiveCards

![image](https://user-images.githubusercontent.com/11837859/48318282-4f7c6e80-e5bb-11e8-951a-57dd1a713efd.png)

All I did to repro this was to take the original Large Weather Card from here : https://adaptivecards.io/samples/WeatherLarge.html  Load it into the designer..
All I have to do is select the first column and add "Col1" as the Id.  At this point the designer changes the width object as outlined by @Kartik1607 .
![image](https://user-images.githubusercontent.com/11837859/48318290-7a66c280-e5bb-11e8-94db-2ce2ddd79989.png)

If you copy and paste the JSON into the editor now, its reparsed:
![image](https://user-images.githubusercontent.com/11837859/48318297-b8fc7d00-e5bb-11e8-81af-afa95cf493b1.png)

The Unit test uses the JSON from the Online Editor and JSON from just added a Column ID manually.

**Comment by dclaux** [comment]
This is known, i have checked in a fix for it last week or so.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by solidcloudio** [comment]
The online editor at https://adaptivecards.io/designer/ still exhibits this behavior..   Has it gotten your fix ?

**Comment by dclaux** [comment]
No, I don't believe so. We are working on it though. The change is part of a bigger update - we are making the designer a reusable component: https://www.npmjs.com/package/adaptivecards-designer/v/0.1.0-alpha1
