### ISSUE TITLE
Teams Channel 'RequestEntityTooLarge'

### ISSUE THREAD

**Issue by igusDroth** [Microsoft/AdaptiveCards#2147]
At the Moment i'm creating a Bot with adaptive Card response.

With Bot Emulator and Text Chat the Card is working fine. But when testing on MS Teams, the following error occurs:
Exception: Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'RequestEntityTooLarge' at Microsoft.Bot.Connector.Conversations.d__9.MoveNext() --- End of stack

**Comment by rednivrug15** [comment]
@igusDroth can you provide JSON payload that you are using ?

**Comment by igusDroth** [comment]
> @igusDroth can you provide JSON payload that you are using ?

Hello Mr. Singh,

here is our DEV json File.

[Orderbot.zip](https://github.com/Microsoft/AdaptiveCards/files/2547263/Orderbot.zip)

**Comment by rednivrug15** [comment]
@igusDroth The JSON size exceeds the maximum limit on the message size . You can use a smaller card to solve this problem

**Comment by igusDroth** [comment]
> @igusDroth The JSON size exceeds the maximum limit on the message size . You can use a smaller card to solve this problem

@rednivrug15 How large is the maximum message limit? Is it possible to increase the limits?
