### ISSUE TITLE
How to use Adaptive Cards for Bot Botbuilder v3 and v4

### ISSUE THREAD

**Issue by rjgmail88** [microsoft/AdaptiveCards#2155]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Version of SDK

botbuilder v3 and v4

# Issue
I read through 2 document on adaptive case usages for bot developers. 

_This usages nodejs library adaptivecards_
[Adaptive Cards for Bot Developers](https://docs.microsoft.com/en-us/adaptive-cards/getting-started/bots)

_This usages addAttachment() method on bot builder_
[Add rich card attachments to messages](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-send-rich-cards?view=azure-bot-service-3.0)

What is the best way and right way to use adaptivecards?

1) Do I need to use npm library for bot builder nodejs v3 or/and v4 ?
2) Can we rely on addAttachment() and never use npm ?

**Comment by khouzam** [comment]
@compulim can you help with this?

**Comment by RebeccaAnne** [comment]
This question is external to Adaptive Cars and hasn't had any recent activity. If you still need assistance feel free to reopen and we can try to get you connected to the right people.
