### ISSUE TITLE
[JavaScript] Demo PWA with Microsoft/AdaptiveCards and wojtekmaj/uwp-web-framework 

### ISSUE THREAD

**Issue by englishextra** [microsoft/AdaptiveCards#2158]
# Platform

* JavaScript

# Author or host

Host

# Version of SDK

```json
"adaptivecards": "^1.1.0",
```

# Issue

A Web App Demo Repo - a snapshot of a certain stage. The goal is to mimic UWP App on the Web/Electron/NWJS

Work in progress and is not polished. Just for front-enders to dig into.

The repo: https://github.com/englishextra/uwp-ac-demo
The online demo: https://uwp-ac-demo.surge.sh/

**Comment by matthidinger** [comment]
This looks pretty cool :) is there anything you'd like from us or any issue you're facing?
