### ISSUE TITLE
Adaptive Cards JSON Schema Development

### ISSUE THREAD

**Issue by michaeldera** [Microsoft/AdaptiveCards#2162]
# Platform

* JSON Schema 

Will the schema for Adaptive cards be adopting schema from [Schema.org](https://schema.org/)? At the moment it is the greatest collaborative effort for schema used for structured data and is community driven.

So say, if an adaptive card had information about a person for example, it would be great if the Adaptive Card schema matched schema from [here on Schema.org](https://schema.org/Person).

Schema.org also happens to have schema for actions.

Beside the advantage of piggyback of the efforts of the community, adopting the schema will also allow for existing content on the web with such structured data to be turned into adaptive cards

**Comment by matthidinger** [comment]
Hi Michael, we are actually looking at these very concepts in adaptive cards "2.0" 

Take a look at the end of this video where we explore some of the concepts, please let us know if you have any thoughts or feedback:

https://youtu.be/GJkep8wToVA?t=3287

**Comment by michaeldera** [comment]
Thank you Matt. Had missed that session from Build but it definitely answers my question. Look forward to more of the concepts being rolled out and I will definitely share any feedback or thoughts if I have any.
