### ISSUE TITLE
[UWP]: Date Input initial value not displayed

### ISSUE THREAD

**Issue by Wenish** [Microsoft/AdaptiveCards#2172]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* UWP

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards?

* Host

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...
* UWP 1.1.0

# Issue

If I create a adaptive card like in the [docs ](https://adaptivecards.io/explorer/Input.Date.html)described:
```csharp
var datePicker = new AdaptiveDateInput();
datePicker.Id = "DateInput";
datePicker.Value = "2017-10-12";
```

The set init value will not get displayed by the UWP renderer.

**Comment by RebeccaAnne** [comment]
You're correct that this functionality is missing from the UWP renderer, and we're working on getting it added. While doing so, we've noticed some inconsistencies in the date/time handling across our renderers, and we're looking at our support all up to get those inconsistencies resolved. As a result, it's taking us a bit of time to get this sorted, but we are working towards a fix.
