### ISSUE TITLE
Visualizer/NodeJS doesn't enforce required "text" property on TextBlock

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2175]
# Reported by

* Teams is finding these issues to be a big problem, cards work fine in App Studio but not on Mobile due to these differences

# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript
* Visualizer

# Author or host

Author

# Version of SDK

1.1

# Issue

On TextBlock, the `text` property is required. Thus, parsing should fail if it's not included.

However, the Visualizer displays the payload without any errors or warnings. When I use this payload in Timeline (which uses UWP renderer), the payload fails since the `text` property is missing.

Here's the repro payload. Notice the first text block doesn't have a text property.

```json
{
  "type": "AdaptiveCard",
  "backgroundImage": "https://picsum.photos/600/250?image=1076",
  "body": [
    {
      "type": "TextBlock",
      "height": "stretch"
    },
    {
      "type": "TextBlock",
      "size": "Large",
      "text": "Angela Chin"
    },
    {
      "type": "TextBlock",
      "spacing": "Small",
      "text": "Video call ᛫ 1 m 40 s"
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0"
}
```

**Comment by dclaux** [comment]
JS renderer is behaving as Adaptive was originally designed - a TextBlock with an empty text property (e.g. "text": "") is valid and causes the TextBlock to simply be dropped. Omitting the text property has the same result. I don't think this is a bug nor that it should be "fixed".

**Comment by shalinijoshi19** [comment]
We  need to talk about what "required in the schema" means really.. And that should be documented and then enforced

**Comment by andrewleader** [comment]
Closing as part of the bigger required property consistent issue #3154
