### ISSUE TITLE
How to include the reason in the URL

### ISSUE THREAD

**Issue by GearTheWorld** [Microsoft/AdaptiveCards#2179]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* .NET HTML

# Author or host
Author

Are you an author (like sending something to Outlook), or a host that is rendering your own cards?
Author sending a card to Outlook

If you're an author, who are you sending cards to?
Approvers

# Version of SDK
?  No SDK

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...
? None

# Issue
I'm sending a payload (Adaptive Card) using C# SMTP client.  This payload has a Reject button for which you can enter a reason.  I'm trying to figure out how to do the payload in order for the URL to include the data entered in the reason.  Here's the action.  the id is comment and I have to send it via the URL set in the OpenURL action.

{
    "type": "Action.ShowCard",
    "title": "@REJECT_TITLE",
    "card": {
        "type": "AdaptiveCard",
        "style": "emphasis",
        "body": [
            {
                "type": "Input.Text",
                "id": "comment",
                "placeholder": "@COMMENT_PLACE_HOLDER",
                "isMultiline": true
            }
        ],
        "actions": [
            {
                "type": "Action.OpenUrl",
                "title": "@SEND_REASON_TITLE",
                "url": "@SEND_REASON_URL"
            }
        ],
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
    }
}

**Comment by pschaeflein** [comment]
If Outlook is the application in which the card is seen by users, you can take advantage of the [Outlook-specific Adaptive Card properties and features](https://docs.microsoft.com/en-us/outlook/actionable-messages/adaptive-card#outlook-specific-adaptive-card-properties-and-features) including Input Value Substitution. This is an example from the linked page:


```json
"actions": [
    {
      "type": "Action.Http",
      "title": "Say hello",
      "method": "GET",
      "url": "https://contoso.com/sayhello?name={{nameInput.value}}"
    }
  ]
```

There is a more information available in the [Training Content repo](https://github.com/OfficeDev/TrainingContent/tree/master/ConnectorActionableMsgs/03%20Adaptive%20Cards).

**Comment by GearTheWorld** [comment]
Wow excellent.  Thank you
