### ISSUE TITLE
Rendering a card on a background thread triggers the Main Thread Checker

### ISSUE THREAD

**Issue by tnev** [Microsoft/AdaptiveCards#2181]
Platform

* iOS

# Author or host

host

# Version of SDK

1.1.0

# Issue

I'm trying to render cards in UITableViewCells. It seems that the suggested way to do this, based on #1420 , is to render the card on a background thread and then use the delegate methods to notify the table view to update. However, the call to ACRRenderer +render:card:config:width initializes an ACRView, a subclass of UIView, which causes the Main Thread Checker to report:

<img width="1358" alt="screen shot 2018-11-19 at 1 48 42 pm" src="https://user-images.githubusercontent.com/13140302/48740410-61968680-ec25-11e8-8d55-443841c2f7b9.png">

I believe this causes a tricky situation where you can't call -render on the main thread because it will eventually make a call to -waitForAsyncTasksToFinish and block the main thread, and you can't call it on a background thread because it will initialize a UIView and trigger the Main Thread Checker.

**Comment by nesalang** [comment]
Hello,
To render adaptive card to UITableViewCell, you don't need to do anything special. Once a view is returned after calling render:card:config:width to the SDK, and you can just add it to the cell as subview. 
Please make sure to set the autolayout constraints properly, and [ follow this guide](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/AutolayoutPG/WorkingwithSelf-SizingTableViewCells.html). 
Thank you

**Comment by tnev** [comment]
Thanks for the reply @nesalang . The rendering of the card actually works very well, I’m more concerned with the Main Thread Checker warning. I was looking for a way that I could initialize an ACRView on the main thread and then render it on a background thread to avoid the warning, but the default ACRView initializer calls render and there’s no other way to initialize it and give it a host config and card. I was curious if there’s a way to avoid this warning.

**Comment by nesalang** [comment]
Hello,
Rendering AdaptiveCards on background threads would not work because the sdk builds UIView trees using UIKit.

**Comment by tnev** [comment]
@nesalang If I render the cards on the main thread the warning goes away, but the main thread will get hung up since ACRRenderer's +renderWithAdaptiveCards method calls ACRView's -waitForAsyncTasksToFinish which seems to make the main thread wait. I've been time profiling this and it seems like this will hang up the main thread for things like loading images.

**Comment by nesalang** [comment]
please, try using branch jwoo/ios-resource-resolver-callback
and search ADCResolver in the visualizer project for the usage.
it uses KVO for image loading.

**Comment by tnev** [comment]
Will do, thanks for your responses 👍

**Comment by nesalang** [comment]
sure

**Comment by tnev** [comment]
Resolved by #2197 , thanks @nesalang !
