### ISSUE TITLE
Full Text Not Display On Window Skype

### ISSUE THREAD

**Issue by gpujar** [Microsoft/AdaptiveCards#2184]
#[Skype on Window] 

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Giriyappa Pujar

Are you an author (like sending something to Outlook), or a host that is rendering your own cards?
Host

# Version of SDK
[Skype version 8.34.0.78]

What version are you using?
Latest master

# Issue
Adaptive card is not rendering all text on window skype messaging channel but renders properly on web chat.
![web chat](https://user-images.githubusercontent.com/18320765/48946905-41ccce80-ef55-11e8-8be6-9a5ab3830072.png)
![Uploading window_response.png…]()

JSON File

{
    "contentType": "application/vnd.microsoft.card.adaptive",
    "content": {
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "version": "1.0",
        "type": "AdaptiveCard",
        "body": [
        {
            "type": "TextBlock",
            "text": "DCTAP Source Code Setup",
            "weight": "bolder",
            "size": "large"
        },
        {
            "type": "TextBlock",
            "text": "Open Git Bash \n\n Use below link to install if not installed",
            "separator": true,
            "wrap": true,
            "size": "medium"
        },
        {
            "type": "TextBlock",
            "text": "Clone Repository: \n\n git clone git@github3.cisco.com:<cec_id>/ctap.git \n\n Ex: git clone git@github3.cisco.com:<cec_id>/ctap.git",
            "separator": true,
            "wrap": true,
            "size": "medium"
        },
        {
            "type": "TextBlock",
            "text": "Install node modules: \n\n cd ctap \n\n ./utils/appserver setup \n\n ./utils/appserver start \n\n cd /tests \n\n npm install",
            "separator": true,
            "wrap": true,
            "size": "medium"
        },
        {
            "type": "TextBlock",
            "text": "Install sqlite3 module in tests,cue and cma folders \n\n npm sqlite3 \n\n cd ../cma \n\n npm sqlite3 \n\n cd ../cue \n\n npm sqlite3",
            "separator": true,
            "wrap": true,
            "size": "medium"
        },
        {
            "type": "TextBlock",
            "text": "Run Robohydra: \n\n cd ../tests \n\n node node_modules/robohydra/bin/robohydra -I ./robohydra-plugin/ -n -P ib_vws_mock -p 4730 \n\n Open robohydra using Activate Robohydra option \n\n Activate ib_vws_mock plugin",
            "separator": true,
            "wrap": true,
            "size": "medium"
        },
        {
            "type": "TextBlock",
            "text": "Local Changes In kIB.json: \n\n Set consoleOnly flag to true to enable log \n\n Change DB path of dbBasePath, plannerDBPath, serviceDbBasePath",
            "separator": true,
            "wrap": true,
            "size": "medium"
        },
        {
            "type": "TextBlock",
            "text": "Local Changes In default.json: \n\n Change server port other then 8000 in window machine.",
            "separator": true,
            "wrap": true,
            "size": "medium"
        },
        {
            "type": "TextBlock",
            "text": "Start DCTAP server: \n\n cd ../cue \n\n NODE_ENV=kIB NODE_CONFIG_DIR=./etc node --inspect server.js",
            "separator": true,
            "wrap": true,
            "size": "medium"
        }
        ],
        "actions": [
            {
              "type": "Action.OpenUrl",
              "title": "Activate Robohydra",
              "url": "http://localhost:4730/robohydra-admin/scenarios"
            },
            {
              "type": "Action.OpenUrl",
              "title": "Git Bash Installer",
              "url": "https://git-scm.com/downloads"
            },
            {
              "type": "Action.OpenUrl",
              "title": "More Info",
              "url": "https://wiki.cisco.com/display/SPVSSPE/Setting+Up%2C+Starting%2C+and+Stopping+the+Aggregation+%28Application%29+Servers+in+Detail"
            }
        ]
  }
}

**Comment by matthidinger** [comment]
Hi @gpuja, unfortunately Skype does not support Adaptive Cards at this time, and we don't have any updated news to share on their timelines. Will be sure to update if this changes.
