### ISSUE TITLE
Card with same input id not failing as exception

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#2187]
Fix needed for Javascript.

See #1852 for details. This has been fixed on other platforms.

See test files [Action.DuplicateIds.json](https://github.com/Microsoft/AdaptiveCards/blob/master/samples/Tests/Action.DuplicateIds.json) and [Action.NestedDuplicateIds.json](https://github.com/Microsoft/AdaptiveCards/blob/master/samples/Tests/Action.NestedDuplicateIds.json)

**Comment by shalinijoshi19** [comment]
@dclaux FYI moved this to backlog

**Comment by paulcam206** [comment]
@shalinijoshi19 -- are we sure we want to punt this? without a fix, you can author a card in the designer that won't render on any other platform...

**Comment by dclaux** [comment]
Fix here: https://github.com/microsoft/AdaptiveCards/pull/2905
