### ISSUE TITLE
Action title: required or not?

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#2189]
# Platform

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

# Issue

Similar to #2111. I haven't been able to validate behavior between renderers (VS is updating), but at least in the visualizer, if you leave out an action's title, you get a warning:

```json
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
	],
	"actions": [
		{
			"type": "Action.OpenUrl",
			"url": "http://adaptivecards.io"
		}
	]
}
```
Warning given: `Actions should always have a title.`

However, according to our schema, title isn't required. Buttons render weird (at least in HTML) if a title isn't given, though. Should `title` be required? Should we have better default behavior in the absence of a `title`?

**Comment by khouzam** [comment]
This is related to #1882

**Comment by jonmill** [comment]
Dupe of #1882
