### ISSUE TITLE
[docs.microsoft.com] Dead link to sample.json

### ISSUE THREAD

**Issue by englishextra** [Microsoft/AdaptiveCards#2190]
On this page https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/javascript/getting-started

sample.json link to https://github.com/Microsoft/AdaptiveCards/blob/master/samples/v1.0/HostConfig/sample.json  is dead

Thanks
![51 -h2u7mrl _ss500](https://user-images.githubusercontent.com/537127/49080064-77becb00-f253-11e8-9d70-c2c1c29e586c.jpg)

**Comment by khouzam** [comment]
Thanks for spotting the broken link @englishextra 

I've updated the doc to point to the right place.
