### ISSUE TITLE
Using media element for Youtube videos or signed urls

### ISSUE THREAD

**Issue by sravanthialuri** [microsoft/AdaptiveCards#2223]
Thank you for the "media" support on v1.1 it works great when I tried with "Mp4" Video Urls.

I would like to play YouTube videos is there any way to get to it? Also, for our native videos we generate signed urls (these Urls expire after a while) for our videos. So, I would like to assign the signed Url for video on playbutton click? Is there any particular way to do it?(Any events to listen for?)

Looking forward for your response.

**Comment by matthidinger** [comment]
Hi @sravanthialuri, I'm glad it's working for mp4 links. Unfortunately the only way I've heard to play YouTube videos has been to setup a proxy server that re-encodes them as standard mp4. I am not a lawyer so can't speak to the legality of that approach if you do look into it. If you find another way please do let us know! 

As for the other queestion, @RebeccaAnne did we end up adding MediaStarted/Stopped events into all the SDKs? I know we talked about this for a while.

**Comment by dclaux** [comment]
@matthidinger another way is to host the embeddable YouTube player, but that would mean build explicit support for YouTube videos and also that non-web platforms would have to use a web view control to host the player.

**Comment by sravanthialuri** [comment]
Any update on the events?
