### ISSUE TITLE
[Shared] The shared model requires media elements to have a sources array

### ISSUE THREAD

**Issue by RebeccaAnne** [Microsoft/AdaptiveCards#2229]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android
* iOS
* UWP

The documentation for Media (https://adaptivecards.io/explorer/Media.html) says that the sources property is not required, but the shared model will fail to parse media elements that don't have it.

**Comment by paulcam206** [comment]
Issue has been fixed in the schema. @matthidinger - we'll need to update our online content to pick up these changes.
