### ISSUE TITLE
Focus is landing on non-interactive elements after activating the 'Show a simple' Adaptive cards button.

### ISSUE THREAD

**Issue by JasonAment** [microsoft/AdaptiveCards#2236]
Please reference the following bug for repro steps and videos:
https://github.com/Microsoft/BotFramework-WebChat/issues/1340

**Comment by compulim** [comment]
Fixing this one should partially/fully fix the following issues:
- https://github.com/microsoft/BotFramework-WebChat/issues/3084
- https://github.com/microsoft/BotFramework-WebChat/issues/3086

**Comment by shalinijoshi19** [comment]
This is also been identified as part of our Accessibility test pass ADO #23950535

**Comment by shalinijoshi19** [comment]
@shalinijoshi19 to sync with @dclaux on getting this fixed.

**Comment by rp-dev** [comment]
@shalinijoshi19 is there an ETA on the fix and when that'd be available in the release.

Thanks
Rohini

**Comment by shalinijoshi19** [comment]
@dclaux for updates here. Thanks

**Comment by dclaux** [comment]
I have been looking at this today and here are my findings:
- The apparently desired behavior calls for removing the tab stop on the root card container
- That would indeed be a better for anyone that has no disability and is able read and see the card
- But removing that tab stop makes narrator not stop on the card, and thus not read it. That seems really bad to me when it comes to actual accessibility

So my conclusion:
- "Fixing" this issue would favor power users over people with disabilities who use narration
- I do not believe there is a fix; we need to keep the root card as a tab stop

I think we'll need to look into other ways to solve this if it is critical (is it?)

Thoughts and comments welcome.

**Comment by shalinijoshi19** [comment]
@compulim FYI; please take a look at @dclaux's response above..

**Comment by shalinijoshi19** [comment]
@dclaux fixing this is indeed high priority. @compulim could you take a look at @dclaux's comments above?

**Comment by paulcam206** [comment]
This bug will be fixed in the next release, but will require callers to to set `GlobalSettings.setTabIndexAtCardRoot` to `false` if the desired behavior is for us not to emit a tabstop.
