### ISSUE TITLE
Name property does not defined for “Date" and "Time" editable text boxes from all card inputs data

### ISSUE THREAD

**Issue by JasonAment** [microsoft/AdaptiveCards#2237]
Repro steps and video for this bug can be found at:
https://github.com/Microsoft/BotFramework-WebChat/issues/1347

**Comment by shalinijoshi19** [comment]
@shalinijoshi19 to follow up on potential dup that @dclaux triaged in ADO last week.

**Comment by paulcam206** [comment]
Looks like #2256 is a duplicate of this bug, which is the bug I've been tracking/working against.
