### ISSUE TITLE
Label is not properly associated with controls defined under 'What color do you want'.

### ISSUE THREAD

**Issue by JasonAment** [microsoft/AdaptiveCards#2238]
Repro steps and video can be found at:
https://github.com/Microsoft/BotFramework-WebChat/issues/1348

**Comment by shalinijoshi19** [comment]
This is tracked by vNext as part of the inputEvolution/Labels work we are doing. @almedina-ms, @dclaux FYI.

**Comment by matthidinger** [comment]
This has been addressed with the v1.3 release with the new `label` property on all inputs, including [Input.ChoiceSet](https://adaptivecards.io/explorer/Input.ChoiceSet.html)
