### ISSUE TITLE
Meaningful sequence is not correct at 'Depart and Arrive' text content while navigating in scan mode.

### ISSUE THREAD

**Issue by JasonAment** [microsoft/AdaptiveCards#2241]
Please review bug repro steps and video at this link:
https://github.com/Microsoft/BotFramework-WebChat/issues/1351

**Comment by shalinijoshi19** [comment]
@shalinijoshi19 to pick up @dclaux's comments from the corresponding ADO item

**Comment by RebeccaAnne** [comment]
This is now tracked by microsoft/AdaptiveCards#4815
