### ISSUE TITLE
[HtmlRenderer][Columnset] Column set is overflowing when using time input, text box and time input for width 344px

### ISSUE THREAD

**Issue by umeshkanoja007** [microsoft/AdaptiveCards#2248]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards?

If you're an author, who are you sending cards to?

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...
v 1.0

# Issue
I am using [time input][textbox][time input] in column set. When you reduce the width of the browser to 344px, it is overflowing. Attaching JSON for this. Issue is in HTML renderer
[ColumnSetOverflow.txt](https://github.com/Microsoft/AdaptiveCards/files/2689630/ColumnSetOverflow.txt)

![image](https://user-images.githubusercontent.com/13246069/50611829-ad775500-0e8c-11e9-9067-6541ed925dbc.png)

**Comment by jonmill** [comment]
The .NET HTML renderer is deprecated and no longer under active development
