### ISSUE TITLE
Input.Date should not have placeholder

### ISSUE THREAD

**Issue by corinagum** [microsoft/AdaptiveCards#2255]
# Platform

* JavaScript

# Author or host

Host, https://github.com/Microsoft/BotFramework-WebChat

If you're an author, who are you sending cards to?
Bots

# Version of SDK

1.0.0

# Issue
(original issue: https://github.com/Microsoft/BotFramework-WebChat/issues/1362)
Although Input.Date has the property `placeholder`, adding a value to the property does not have an affect on the input because HTML5 inputs with the type of date to not allow placeholders. This means that the property gets dropped without explanation, and is ultimately unnecessary.

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.
