### ISSUE TITLE
Request: Adding aria-label (speak property) to Input.Date?

### ISSUE THREAD

**Issue by corinagum** [microsoft/AdaptiveCards#2256]
# Platform

* JavaScript

# Author or host

Host, https://github.com/Microsoft/BotFramework-WebChat

If you're an author, who are you sending cards to?
Bots

# Version of SDK

1.0.0

# Issue
(original issue: https://github.com/Microsoft/BotFramework-WebChat/issues/1362)
Web Chat is currently doing an accessibility pass. The above issue shows that an adaptive card with Input.Date will be read as 'mm/dd/yyyy' by narrator. Since `placeholder` is not an option for input.Date, would it be possible to add an aria-label that can be passed through the speak property?

**Comment by shalinijoshi19** [comment]
Input.Date does have a [placeholder property] (https://adaptivecards.io/explorer/Input.Date.html) though there was a bug in the JS renderer that didn't surface it; What's remaining is to port the change over from @dclaux's branch into release/1.2 code base.

**Comment by paulcam206** [comment]
Verified that this is fixed in `master`. Looking to see what our release plan looks like :)

**Comment by paulcam206** [comment]
Note that the fix for this issue needs to apply to `Input.Time` as well. :)
