### ISSUE TITLE
Request: Universal actions that work across all hosts (Outlook, Teams, etc)

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2268]
# Summary
Today, Outlook has `Action.Http` while not supporting `Action.Submit`, whereas Teams and Cortana use `Action.Submit`, but they use it differently... therefore, cards aren't universal since their actions and activation model is not universally shared, so you have to author different cards for each host.

Ideally, you should be able to create a single actionable card that works everywhere, while still supporting some host-specific actions.

# Asks

* Outlook
  * Needs HTTP actions that include Microsoft auth info so user is already authenticated
  * Needs actions that can invoke Outlook extensions/add-ins

# Requirements

* HTTP actions that send a GET/POST to a server, and then server can optionally respond with updated content for the card (Outlook needs this)
  * Needs to include MSA/AAD user info so that the third party author doesn't have to re-authenticate the user (Outlook)
* Submit actions that send data through the implicit channel the host has (Bot Framework, Windows Notifications)
  * Some hosts have two channels which authors can choose from, like a foreground and background activation channel. The same data is sent, but one launches the app in the foreground while the other just activates a background task.
* Open URL actions that simply launch/open a url (Outlook, Bot Framework, Windows Notifications)

**Comment by crf200** [comment]
I have a project at a stand still until and Action.HTTP can be released. Any progress?

I'm trying to use it to post a HTTP trigger for a flow with data provided in the Adaptive Card.
