### ISSUE TITLE
JavaScript: Adaptive Card should not assume css-loader/webpack is available on the build pipeline of the host project

### ISSUE THREAD

**Issue by compulim** [Microsoft/AdaptiveCards#2279]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Author or host

Host

# Version of SDK

`1.1.2`

# Issue

In `lib/adaptivecards.js`, it read

```js
"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
__export(require("./card-elements"));
__export(require("./enums"));
__export(require("./host-config"));
var utils_1 = require("./utils");
exports.SizeAndUnit = utils_1.SizeAndUnit;
exports.getEnumValueOrDefault = utils_1.getEnumValueOrDefault;
require("./adaptivecards-default.css");
//# sourceMappingURL=adaptivecards.js.map
```

On the very last line, `require("./adaptivecards-default.css");`, it assume the build pipeline of the project that include Adaptive Cards is on Webpack and have `css-loader` and `style-loader` installed.

This will prohibit the use of Adaptive Cards on projects that use [rollup.js](https://rollupjs.org/) or other bundling engines that does not support loading CSS in JavaScript.

**Comment by matthidinger** [comment]
Thanks for reporting @compulim, I will hopefully have this resolved this week
