### ISSUE TITLE
Request: Borderless header/footer images

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2290]
# Summary
Some authors want to have a header or footer image that's borderless. For illustration purposes, a notification is shown below which illustrates the desire of having an image that bleeds to the edge of the card.

![image](https://user-images.githubusercontent.com/13246069/51006514-5f9bc600-14f8-11e9-8877-bc06626e320b.png)

This image needs to have a controllable fixed height, and cropped using `UniformToFill` (XAML) or `cover` (CSS), since the image might be different aspect ratios, but the author always wants a consistent height.

# Asks

* Outlook (partners asking for this)

**Comment by mdtauk** [comment]
Is there not a proposal to enable a "bleed" on all containers.  This would be a more flexible option than calling out images only, and only for headers and footers.

**Comment by andrewleader** [comment]
Hey Martin, this is tagged a "Request", which is meant to capture the customer scenario - what the authors/developers want to achieve.

A "Proposal" on the other hand is a way to solve the scenario. We're thinking this indeed will be solved by the same bleed proposal, but we also need to track the customer scenario, **why** we're doing something, not just **what** we're doing.

**Comment by mdtauk** [comment]
Ok that makes sense.  Thank you for the thoughtful reply!

**Comment by andrewleader** [comment]
Shipped in 1.2!
