### ISSUE TITLE
minHeight property on containers

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#2293]
<table>
<tr>
<th>Release</th>
<th>Renderer status</th>
<th>Tasks status</th>
</tr>
<tr>
<td>1.2
<td>🔄 .NET (#2618)<br/>✔️ Android (#2619)<br/>🔄 iOS (#2620)<br/>✔️ TS (#2621)<br/>✔️ UWP (#2622)</td>
<td>✔️ Shared (#2616)<br/>✔️ Designer (#2617)</td>
</tr>
</table>

# Solves requests

* Borderless header/footer images #2290
* Full-width images with fixed height and correct fill/crop behavior #2291

# Summary
This proposal is an alternative way of solving the above two requests, written up so we can consider both options. Containers can already almost achieve the two above requests except for one thing... you can't set a height on them.

# Schema
**New** property on the following elements...

* `Container`
* `ColumnSet`
* `Column`
* `ActionSet`

Property|Type|Required|Description
---|---|---|---
minHeight | `null` (default) or `px` | false | Specifies the minimum height of the container.

# Example

To achieve the following, where the image is full width but has a fixed height...

![image](https://user-images.githubusercontent.com/13246069/51007006-9a9ef900-14fa-11e9-977c-f20586a47184.png)

I would add a container with a background image, and set the minimum height of the container to 100px (so it's my exact height).

```json
        {
            "type": "Container",
            "backgroundImage": {
              "url": "https://picsum.photos/300/400?image=882"
            },
            "minHeight": "100px"
        }
```

Now, what if I want the image to go to the edge of the card? I don't want that padding around the edges?

![image](https://user-images.githubusercontent.com/13246069/51008026-cc19c380-14fe-11e9-9ec4-52579db4c34d.png)

I would simply set bleed=true, and that'll remove the padding.
```json
        {
            "type": "Container",
            "backgroundImage": {
              "url": "https://picsum.photos/300/400?image=882"
            },
            "minHeight": "100px",
            "bleed": true
        }
```

# Host Config
None.

# Down-level impact
**High**. Image won't appear at all (since height on container is ignored down-level, and therefore the container won't have any height).

# Host burden
None.

# Auto-generated task status

- [x] Shared
- [x] Designer
- [ ] .NET
- [x] Android
- [ ] iOS
- [x] TS
- [x] UWP

**Comment by andrewleader** [comment]
Proposal approved!

**Comment by mdtauk** [comment]
> consensus: build minimum height logic and call it `minHeight`

If you have a Minimum height, why not Maximum with scrolling for bits that overflow or extended out of a container?

**Comment by dclaux** [comment]
@mdtauk I'll return the question: why do what you suggest? What scenario does it support? Not saying I'm opposed, but it doesn't seem necessary.

**Comment by mdtauk** [comment]
> @mdtauk I'll return the question: why do what you suggest? What scenario does it support? Not saying I'm opposed, but it doesn't seem necessary.

The very fact you would have a Minimum Width property, would make people expect to be a Maximum.  Why only constrain in one direction?

**Comment by dclaux** [comment]
Because there is a reason to have a minimum height (namely what this spec describes) while we have not identified a reason why having a maximum height would be desirable. It's always easier to add new features as necessary rather than introduce it without concrete evidence it's useful and have to live with it forever.

Do you have a concrete scenario in mind that would need a maximum height?

**Comment by andrewleader** [comment]
We updated the spec so that it's only on containers

**Comment by andrewleader** [comment]
Updating spec to reflect that we also added it to `AdaptiveCard`
