### ISSUE TITLE
Designer should specify the version that properties/elements were introduced in

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#2294]
Similar to how the schema explorer shows the version for each property, the Designer should do as well. 

As a bonus, it would be awesome if the Host App list was initialized with the current supported version of each host, so the tooling could pop a warning if attempting to use a 1.1 element/property but the Selected Host App currently ships on 1.0.

![image](https://user-images.githubusercontent.com/1432195/51048501-f9f31c80-157f-11e9-8095-68349994eb27.png)

**Comment by dclaux** [comment]
Closing this as those are addressed in this PR: https://github.com/microsoft/AdaptiveCards/pull/3508
