### ISSUE TITLE
Allow configure date formatting in Input.Date

### ISSUE THREAD

**Issue by elena20ruiz** [microsoft/AdaptiveCards#2305]
# Platform

What platform is your issue or question related to?
* JavaScript

# Author or host
An author sending by WebChat.

# Version of SDK
Latest

# Issue
Hello, I ask a question in stackoverflow about if it possible determine the date formatting of **Input.Date** to European format. ( Now it shows mm/dd/yyyy, we want to show dd/mm/yyyy). And we realize that is not possible to renderize with WebChat change this fact.

We relalize that when you have configured your computer language (on Windows) in other european language as Spanish or Italian. The Input.Date shows the 'compact' date in dd/mm/yyyy, but with English language always shows first the month. 

We want to request if in possible to have the option of a new property when you create the JSON to select the order that you want, with the independence of your computer language.

Thanks you so much.

**Comment by khouzam** [comment]
Hi @elena20ruiz 

Thanks for the suggestion. Can you explain a little more of your scenario so that we can understand it and take it under advisory. Both aspects can be confusing to the user if they don't know that the date coming in is a different format than the rest of the system.
