### ISSUE TITLE
Why not list validation on #/definitions/CardElements?

### ISSUE THREAD

**Issue by juanevp** [microsoft/AdaptiveCards#2313]
#/definitions/CardElements is currently specified as:
```json
"CardElements": {
	"type": "array",
	"additionalItems": true,
	"items": [
		{
			"anyOf": [
				...
			]
		}
	]
},
```
That is, it is an array that is validated as a tuple with only the first element specified and it can have additional items. With this spec the validator only checks the first element in the list and accepts the rest without checking. Why not specify this definition with list validation and check all the items?
I mean this:
```json
"CardElements": {
	"type": "array",
	"items": {
		"anyOf": [
			...
		]
	}
},
```

**Comment by jonmill** [comment]
This should be fixed in the newer versions of the schema
