### ISSUE TITLE
Autocomplete attribute for TextInput

### ISSUE THREAD

**Issue by EdwinOtten** [microsoft/AdaptiveCards#2329]
# Platform

What platform is your issue or question related to?

* JavaScript

# Author or host

Both, I am sending cards from a MBF bot and receiving them in a WebChat client, which uses the AdaptiveCards NodeJS package to render cards.

# Version of SDK

Version 1.0.0 via NPM

# Suggestion

I am using the TextInput element inside my adaptive card. I want to be able to set the [HTML `autocomplete` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete). Is this something that can be added to the AdaptiveCards schema?

I have created a fork and already made a start on the implementation inside the NodeJS SDK: [diff view](https://github.com/Microsoft/AdaptiveCards/compare/master...EdwinOtten:patch-1)

**Comment by EdwinOtten** [comment]
Related: #1068

**Comment by matthidinger** [comment]
Hi @EdwinOtten, thanks for filing this and the associated PR. Can you help us understand the scenario you use it for, maybe providing an example payload and the expected autocomplete behavior. It seems browsers have robust support for this attribute but I'm not entirely sure about the other platforms we support, like iOS and Android.

As another option that may work for you today...

Adaptive cards allow you to pass "additional properties" to the renderer as long as you are doing the rendering. See these [JavaScript docs on custom rendering elements](https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/javascript/extensibility). This same API can be used to override the rendering for `Input.Text`, where you can extract the non-standard property from the JSON and assign it to the HTML element.

The main gotcha is that you're using WebChat, which itself uses the renderer. I know they are working on a new version that allows easier access to the adaptive card renderer, but I'm not fully up to speed on that. If you run into issues let us know and I'll loop in the right people.

As for naming the additional properties we typically recommend prefixing them to prevent conflict with future releases, such as:

```json
{
  "type": "Input.Text",
   "-myorg-autocomplete": "x"
}
```

Hopefully this helps!

**Comment by EdwinOtten** [comment]
Thanks! I didn't know about the AdditionalProperties so this helped me a lot. 
I found that is also [available](https://github.com/Microsoft/AdaptiveCards/blob/f915e02a017cf2dba85e4219adbcd1e851a102bc/source/dotnet/Library/AdaptiveCards/AdaptiveTypedElement.cs#L43) in the [AdaptiveCards NuGet package](https://www.nuget.org/packages/AdaptiveCards/), so easy to implement in C#.

I am still struggling to implement the part in the front-end because, like matthidinger mentioned, it's hard to extend the adaptivecard renderer in the WebChat application.
