### ISSUE TITLE
Auto sized images with background colors don't render on UWP

### ISSUE THREAD

**Issue by RebeccaAnne** [Microsoft/AdaptiveCards#2345]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Issue

The card at \samples\v1.1\Elements\Image.BackgroundColor.json renders as a blank card on UWP. Comparing to the card at \samples\Tests\Image.BackgroundColor.json (which does render), and playing around with it a bit, the issue seems to be that non-person auto-sized images with background colors don't render. Adding a different size ("size":"medium") or removing background color causes the images to render successfully.

**Comment by almedina-ms** [comment]
Went back to commit c31c6a33 and the images dont show up
