### ISSUE TITLE
Adaptive Cards in ChatBot Azure

### ISSUE THREAD

**Issue by stuckerbsas** [Microsoft/AdaptiveCards#2352]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards?
Author

If you're an author, who are you sending cards to?

# Version of SDK
Nuget 1.1.2

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

# Issue

When i make a adptive cards with columns, in the emulator it work fine but in the webchat not render with the width i define in it.

Pd: Sorry for my poor Enlgish

Explain your issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards).

**Comment by matthidinger** [comment]
Hi there, could you include the JSON payload you're using and potentially a screenshot of what you're seeing? Are you use pixel-width column sizes? If so, that is a 1.1 feature so you would need to roll out the WebChat update that includes Adaptive Cards v1.1 which should be released shortly

**Comment by stuckerbsas** [comment]
Mathdinger, 
   Removing the AdaptiveCards.dll and repolacing with the AdaptiveCards.Rendering.Html 1.1.2, it working.

**Comment by matthidinger** [comment]
Glad to hear it, please let us know if we can help further! :)
