### ISSUE TITLE
Designer doens't preview fixed height Timeline card correctly

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#2366]
In the Designer, select the Timeline host preview and paste in the following payload...

```json
{
"type": "AdaptiveCard",
"verticalContentAlignment": "bottom",
"body": [
    {
        "type": "TextBlock",
        "text": "Cool"
    }
],
"version": "1.0"
}
```

**Expected:** (classic Visualizer renders correctly)
![image](https://user-images.githubusercontent.com/13246069/52495848-b1cb1800-2b86-11e9-9f00-3715c4567b0b.png)

**Actual**: (Designer doesn't seem to handle the fixed height, and therefore verticalContentAlignment has no effect)
![image](https://user-images.githubusercontent.com/13246069/52495874-c3acbb00-2b86-11e9-9977-2057e97caea7.png)

**Comment by dclaux** [comment]
Fixed: https://github.com/Microsoft/AdaptiveCards/commit/2cb96cd07553279ac0b2648c4b65188399b0af3c

**Comment by dclaux** [comment]
Fixed in master: https://github.com/Microsoft/AdaptiveCards/pull/2369
