### ISSUE TITLE
Designer is missing verticalContentAlignment property on top-level AdaptiveCard

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#2367]
The "verticalContentAlignment" property is supported on the top-level AdaptiveCard element, yet in the Designer, the Designer doesn't expose that property.

![image](https://user-images.githubusercontent.com/13246069/52495990-0bcbdd80-2b87-11e9-8d80-e452e8f5f3df.png)

This is somewhat related to #2366... until #2366 is fixed, applying the verticalContentAlignment property in the designer won't result in any visual difference. But it's part of the schema, so the property should be assignable.

**Comment by dclaux** [comment]
Fixed: https://github.com/Microsoft/AdaptiveCards/commit/2cb96cd07553279ac0b2648c4b65188399b0af3c

**Comment by dclaux** [comment]
Fixed in master: https://github.com/Microsoft/AdaptiveCards/pull/2369
