### ISSUE TITLE
Add setDataJson method in Action.Submit

### ISSUE THREAD

**Issue by rednivrug15** [microsoft/AdaptiveCards#2381]
# Platform

* Android
* Shared Model

# Author or host

Host ( Teams )

# Version of SDK

1.1

# Issue

Teams is using the setDataJson(String dataJson) method . This method was removed in 1.1 android .

**Comment by almedina-ms** [comment]
The method was removed 9 months ago but was re added less than a month ago (https://github.com/Microsoft/AdaptiveCards/pull/2318), we should add this to a v 1.1.1 release

**Comment by shalinijoshi19** [comment]
@almedina-ms / @paulcam206 - FYI this needs to be patched down to 1.1
