### ISSUE TITLE
[Request] Action to upload a file or activate the camera

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#2384]
A few bot authors have asked for the ability to upload a file or activate the camera. This sounds like something we could reasonably spec out as a new action type, with properties to toggle what type of file/media picker should be invoked on a given platform

**Comment by RajaniJillaGit** [comment]
Hi Team,

Any update on the above feature request to be able to support file upload inside adaptive cards. Kindly please share the details.

**Comment by RebeccaAnne** [comment]
Duping to #3707

**Comment by kamarajPasupathi** [comment]
Hi Rebecca,

I want to attach or upload the file to my adaptive card. Can you suggest to me the possibilities?

Regards,
Kamaraj.P
