### ISSUE TITLE
Input.Number UWP not rendering

### ISSUE THREAD

**Issue by Wenish** [Microsoft/AdaptiveCards#2386]
# Platform
* UWP

# Author or host
host

# Version of SDK
NuGet v1.1.2

# Issue
If in the AdaptiveCard JSON is a Type Input.Number the AdaptiveCard does not get rendered.

**Comment by RebeccaAnne** [comment]
I'm not able to reproduce this issue, Input.Number elements are showing up fine for me on v1.1.2. @Wenish could you provide a sample payload that you're having issues with? Thanks!

**Comment by paulcam206** [comment]
@Wenish -- if you're still seeing this issue, please reactivate this issue and supply us with the card you're trying to render.

Thanks!
