### ISSUE TITLE
ACRUILabel's intrinsicContentSize calculation seems a bit off

### ISSUE THREAD

**Issue by Aditya0603** [Microsoft/AdaptiveCards#2394]
# Platform
* iOS

# Author or host
Host

If you're an author, who are you sending cards to?

# Version of SDK
1.1, latest master

# Issue

ACRUILabel's intrinsicContentSize calculation seems a bit off
This only happens when ACRUILabel is inside an ACRColumnView

In the below screen shots "next" it is one line and looks fine, but when i say "nexts" it goes to next line but the 
contentsize is not changed and it overlaps with date text below, then for word "nextss" it works fine in 2 lines

![simulator screen shot - iphone xr - 2019-02-14 at 03 49 11](https://user-images.githubusercontent.com/33312128/52749932-b5d8b900-3010-11e9-9f75-020aea3d5dbf.png)
![simulator screen shot - iphone xr - 2019-02-14 at 03 48 53](https://user-images.githubusercontent.com/33312128/52749933-b5d8b900-3010-11e9-8a71-c73d12798277.png)
![simulator screen shot - iphone xr - 2019-02-14 at 03 50 11](https://user-images.githubusercontent.com/33312128/52749935-b6714f80-3010-11e9-9bbf-f9ee44a8cb9b.png)

**Comment by nesalang** [comment]
problem is understood & fix is available locally.
