### ISSUE TITLE
Investigate holding on to async operations in XamlBuilder

### ISSUE THREAD

**Issue by khouzam** [microsoft/AdaptiveCards#2396]
# Platform

* UWP

In `xamlbuilder.cpp` we use vectors to keep a reference to async operations. We need to validate if these are necessary and whether they leak the async operations for the lifetime of the XamlBuilder and when adding the XamlBuilder itself if that creates a permanent leak.

**Comment by shalinijoshi19** [comment]
Being tracked by issue #3026
