### ISSUE TITLE
iOS add ACRTextField to bridging header

### ISSUE THREAD

**Issue by aleckretch** [Microsoft/AdaptiveCards#2398]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Host

If you're an author, who are you sending cards to?

# Version of SDK

Latest master

# Issue

ACRTextField is not in the ACFramework.h file, making it inaccessible to Swift developers. We added this in our own bridging header, but wanted to bring up this issue with the team.

**Comment by nesalang** [comment]
Thank you, I will check it out. this must have been oversight! Sorry for the trouble.

**Comment by shalinijoshi19** [comment]
@nesalang to confirm if this is fixed or not. Thanks

**Comment by nesalang** [comment]
closes it as the header is included.
