### ISSUE TITLE
[.NET] No HTML/WPF Test App

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#2399]
# Platform

* .NET HTML
* .NET WPF

# Issue

We should probably make some kind of test app similar to UWP's to be able to track if they render properly. This would also help prevent interactivity from breaking.

# HTML

Lucky for us, the HTML's output is just HTML tags. So, we could probably just have the output treated like "round trip JSON" for the UWP Test App. Just save the output and compare it to the one generated on a new run by the test app.

It'd be nice if we could make the output saved to multiple lines so that the diff would be like what is shown in #2391.

# WPF

WPF's would probably be a bit more annoying but the idea would be exactly the same as the UWP Test App. Snap a picture of the rendered card. Save it. Compare it to the one generated on a new run by the test app.

**Comment by matthidinger** [comment]
There is indeed an "automated" way to test/verify the WPF and .NET HTML renderers - via 2 console apps.

For WPF we can render them to bitmap images:
https://github.com/Microsoft/AdaptiveCards/tree/master/source/dotnet/Samples/AdaptiveCards.Sample.ImageRender

For HTML, we output all the samples to a single HTML file.
https://github.com/Microsoft/AdaptiveCards/tree/master/source/dotnet/Samples/AdaptiveCards.Sample.Html

**Comment by carlos-zamora** [comment]
Yeah but we have such a large number of tests (and growing) so comparing the output manually can make it easy to miss something. The benefit of a test app would be that we can directly compare the output + round trip json automatically and make sure we don't break anything.
