### ISSUE TITLE
[UWP] Images ignore constraints of parent container

### ISSUE THREAD

**Issue by barryptak** [Microsoft/AdaptiveCards#2400]
# Platform
* UWP

# Author or host
We're a host rendering cards received from Bing, etc..

# Version of SDK
1.1.2 though this applies to all UWP implementations.

# Issue
Images placed within size-constrained parents (e.g. weighted columns) ignore the parent dimensions when they have their "size" property set and will render at the requested size regardless. This is inconsistent with other renderers.

## Example Json
```json
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "TextBlock",
                            "text": "Weight 1"
                        },
                        {
                            "type": "Image",
                            "url": "https://cdn-01.independent.ie/migration_catalog/Non-Staff/article25331906.ece/fea85/AUTOCROP/w620/No%20name",
                            "size": "Large"
                        }
                    ],
                    "width": 1
                },
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "TextBlock",
                            "text": "Weight 3"
                        }
                    ],
                    "width": 3
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

## Html Renderer Output
![image](https://user-images.githubusercontent.com/43549850/52850766-36301480-310c-11e9-9e17-74741e2fa5ac.png)

## UWP Renderer Output
![image](https://user-images.githubusercontent.com/43549850/52850777-434d0380-310c-11e9-8fa4-6a019b62393f.png)

## Fix
I have a fix for this (need this bug approved first before creating PR) that produces the following from the UWP renderer:
![image](https://user-images.githubusercontent.com/43549850/52850889-98891500-310c-11e9-84b7-3365642d87cf.png)

**Comment by barryptak** [comment]
My fix is to modify XamlBuilder::BuildImage to replace calls to put_Width and put_Height to use put_MaxWidth and put_MaxHeight instead:

```cpp
THROW_IF_FAILED(frameworkElement->put_MaxWidth(imageSize));
THROW_IF_FAILED(frameworkElement->put_MaxHeight(imageSize));
```

If everyone is happy then I can make up a PR for this.

**Comment by matthidinger** [comment]
Thanks Barry. @RebeccaAnne could you please weigh in on this one?

**Comment by barryptak** [comment]
@RebeccaAnne, I've created a PR to address this here: #2520.

**Comment by paulcam206** [comment]
Should be fixed in master
