### ISSUE TITLE
Blog does not have RSS/Atom feed

### ISSUE THREAD

**Issue by lafe** [microsoft/AdaptiveCards#2404]
The blog located at https://adaptivecards.io/blog/ has an "alternate" link that points to a "/atom.xml" so that feed readers can retrieve information. Unfortunately, that file is missing and therefore, the blog currently does not have a feed which makes it difficult to stay up to date.

**Comment by matthidinger** [comment]
Thanks for reporting! I'll hopefully get this resolved within a few weeks and make it easier to stay up to date with things, as well as get a blog post published that includes the video from our last monthly community call
