### ISSUE TITLE
Document 1.2 features

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2407]
New 1.2 features that need to be documented...

* [x] #628 
* [x] #147 
* [x] #861
* [x] #477
* [x] #877
* [x] #1078
* [x] #1729
* [x] #1887
* [x] #1886
* [x] #2019
* [x] #2109
* [x] #2031
* [x] #1933

**Comment by shalinijoshi19** [comment]
Tracking by #3030
