### ISSUE TITLE
[TS] Action.ToggleVisibility

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#2415]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

TS implementation of #1729

**Comment by andrewleader** [comment]
Similar to the fallback task, looks like this is already implemented in the TS renderer, but the Designer doesn't have full support for creating an Action.ToggleVisibility from within the designer UI itself (developer has to break into the JSON).

![image](https://user-images.githubusercontent.com/13246069/53194496-535f5a00-35c8-11e9-8993-301b17c70642.png)

Based on David's answer to how he wants to track designer vs renderer tasks, I'll apply the same answer to this.

**Comment by dclaux** [comment]
I'd rather track renderer and designer tasks separately.

**Comment by andrewleader** [comment]
Awesome, I'll work on updating the GitHub sync tool to create separate designer tasks!

**Comment by andrewleader** [comment]
Closing since TS implementation is complete, we'll have a separate task to track Designer work.
