### ISSUE TITLE
[TS] Introduce wrap property on ChoiceSet/Toggle

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#2423]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

TS implementation of #1887

**Comment by andrewleader** [comment]
It appears this is mostly implemented, however when `"style": "expanded"` (drop down), the wrapping doesn't apply.

![image](https://user-images.githubusercontent.com/13246069/53191796-a4b81b00-35c1-11e9-8cd8-5f17609740f6.png)

Starting an internal email thread to see how other platforms handled the wrapping of this.

**Comment by dclaux** [comment]
@andrewleader that's an HTML limitation, can't wrap the value of an `<option>` tag. Best workaround is to truncated the text explicitly, which I do not believe is necessary here.

**Comment by andrewleader** [comment]
Conclusion was that wrapping here is a "SHOULD", and that renderers don't have to implement that support if it's unfeasible. Therefore, TS implementation is complete, closing.
