### ISSUE TITLE
Adaptive Cards Designer breaks when adding an action to ActionSet

### ISSUE THREAD

**Issue by manuelschlegel** [Microsoft/AdaptiveCards#2443]
Hi,

So I am using the [Adaptive Cards Designer](https://acdesignerstaging.azurewebsites.net/) in Outlook Actionable Messages mode.

When I add an an empty ActionSet to it and use the button `Add action` in the `Element properties` on the right, the whole site stops responding and I have to refresh the whole page. Reading the console in the browser shows the following error: https://i.imgur.com/eRcf3Qi.png

Interestingly,  adding an action using the "lightning bolt" icon in the card itself works fine.

This bug happens across different browsers (Firefox - Chrome - Edge) on Windows.

**How to replicate**

1. Go to https://acdesignerstaging.azurewebsites.net/ and select 'Outlook Actionable Messages' mode.
2. Add an empty ActionSet.
3. Select the newly created ActionSet.
4. Click on the `Add action` button.

**Comment by dclaux** [comment]
@manuelschlegel thanks for reporting this. Will fix ASAP. In the meantime, please use the lightning bold button.

**Comment by dclaux** [comment]
This is now fixed: https://github.com/Microsoft/AdaptiveCards/commit/bb4e658e0dfdb439e83234056375c285dcbbb9e8

By the way, going forward, it's best to use http://adaptivecards.io/designer
