### ISSUE TITLE
🎁 1.2 Feature List (Shipping end of May)

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#2444]
This is the tentative list of 1.2 features.  These items are not guaranteed to ship, but we will do our best to keep this date and status as up to date as possible. 1.2 is planning to ship end of May 2019.

1. [Element-level fallback support](https://github.com/Microsoft/AdaptiveCards/issues/2019)
2. [Full bleed background images/containers](https://github.com/Microsoft/AdaptiveCards/issues/2013)
3. [Action.ToggleVisibility](https://github.com/microsoft/adaptivecards/issues/1729)
4.  [More Container styles to match Textblock styles](https://github.com/Microsoft/AdaptiveCards/issues/1886) 
5. [Better inline text formatting](https://github.com/microsoft/adaptivecards/issues/1933)
6. [TextBlock inline Actions](https://github.com/microsoft/adaptivecards/issues/1990) 
7.  [Base64 encode image into URI (Data URIs)](https://github.com/microsoft/adaptivecards/issues/628)
8.  [Input.Text with associated action (Quick-Reply)](https://github.com/microsoft/adaptivecards/issues/1992)
9. [TextBlock font styles](https://github.com/microsoft/adaptivecards/issues/1078)
10. [Action sentiment (primary / destructive)](https://github.com/microsoft/adaptivecards/issues/2025) 
11. [Place actions anywhere in the card (ActionSet)](https://github.com/Microsoft/AdaptiveCards/issues/2027) 
12. [Stretch and Repeat for Background Images](https://github.com/microsoft/adaptivecards/issues/2032)
13. [MinHeight Property on Containers](https://github.com/microsoft/adaptivecards/issues/2293)
14. [Wrap property on ChoiceSet/Toggle](https://github.com/Microsoft/AdaptiveCards/issues/1887)

## Breaking Changes

https://github.com/microsoft/AdaptiveCards/releases/tag/v1.2.0

## Bug fixes

https://github.com/microsoft/AdaptiveCards/releases/tag/v1.2.0

**Comment by jefflhp** [comment]
Do you have an update on this 1.2 release?

**Comment by matthidinger** [comment]
@jefflhp it's still underway and coming along nicely! Still targetting end of the month release (+/- a few days). Are you looking for any particular information?

**Comment by shalinijoshi19** [comment]
https://github.com/microsoft/AdaptiveCards/releases/tag/v1.2.0
