### ISSUE TITLE
Inconsistency around placeholder support for Input.ChoiceSet

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2445]
The Designer and TS renderer DOES support `placeholder` property on `Input.ChoiceSet`, but all the other renderers (and the schema itself) does NOT have `placeholder` on ChoiceSet...

We need to resolve this inconsistency.

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.
