### ISSUE TITLE
WPF Input.ChoiceSet incorrectly defaults to "expanded"

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#2446]
# Platform

* .NET WPF

# Version of SDK

Latest master as of 2/21/2019 (so 1.2 feature set).

Also 1.1 behaved this way too (just cloned 1.1 branch and tried WPF Visualizer), so this is NOT a new regression

Also 1.0 behaved this way too... so since the very beginning it's been like this.

# Issue

`Input.ChoiceSet` is supposed to default to `"style": "compact"`. However, in the WPF visualizer, when style isn't specified, it's displayed as expanded...

### Expected

![image](https://user-images.githubusercontent.com/13246069/53193240-645a9c00-35c5-11e9-8563-badffc61b915.png)

### Actual

![image](https://user-images.githubusercontent.com/13246069/53193186-3ecd9280-35c5-11e9-984d-473d1569d36f.png)

```json
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "\"style\": undefined"
        },
        {
            "type": "Input.ChoiceSet",
            "id": "myChoiceSet",
            "value": "Choice 1",
            "choices": [
                {
                    "title": "Choice 1",
                    "value": "Choice 1"
                },
                {
                    "title": "Choice 2",
                    "value": "Choice 2"
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

**Comment by shalinijoshi19** [comment]
Ideally this should be fixed; @paulcam206 FYI; if we run through existing 1.2 bugs we tackle this next. Should include documentation as well as part of the fix.
