### ISSUE TITLE
Android SDK renders isSubtle property incorrectly

### ISSUE THREAD

**Issue by ryanlengel** [Microsoft/AdaptiveCards#2482]
# Platform
Android
# Author or host
Host

# Version of SDK
1.1 (latest available on Maven)

# Issue
The `isSubtle` property is parsed incorrectly in the SDK.  The card is received from a bot with values "true" or "false", but when the object is sent to the Adaptive Card parser it is returned as "yes".

Microsoft/AI#853

**Comment by andrewleader** [comment]
@ryanlengel based on the comments in Microsoft/AI#853 it looks like the bot is sending an invalid card...

The bot is sending the following, correct?

```json
                  {
                    "type": "TextBlock",
                    "size": "default",
                    "isSubtle": "yes",
                    "text": "Now that you have successfully run your bot, follow the links in this Adaptive Card to expand your knowledge of Bot Framework.",
                    "wrap": true,
                    "maxLines": 0
                  }
```

`"isSubtle": "yes"` is an invalid value. isSubtle must be a boolean.

The fact that the WebChat renderer DOES render this card is a bug, the WebChat renderer is being too loose and allowing "yes" to be interpreted as a boolean.

The author needs to update their card payload to simply be a boolean: `"isSubtle": true`.

If you confirm that this interpretation is correct, I'll update this issue to reflect the inconsistency with the web renderer being too accepting and not as strict as the others.

**Comment by ryanlengel** [comment]
Sorry, the conversation in the issue cleared it up. The bot is sending the correct payload:

```
"type": "TextBlock",
"size": "default",
"isSubtle": true,
"text": "Now that you have successfully run your Virtual Assistant, follow the links in this Adaptive Card to explore further.",
"speak": "Now that your up and running let's get started.",
"wrap": true,
```

From our tester:

> The above json was directly received from the bot so no Android Adaptive Card renderer involved at that point. When the call to parse happened is when the error is thrown

**Comment by andrewleader** [comment]
Ah sorry, I missed that line.

So I'm confused... the bot author is sending...

`"isSubtle": true`

That's successfully received from the Bot Framework...?

At what point does it become `"isSubtle": "yes"`? Is the chat bot client on Android parsing the card and then re-serializing the card to produce that? Can you identify the steps of flow in this process with the associated payloads at those points in time?

**Comment by ryanlengel** [comment]
@dwhiteddsoft can you provide an answer for the above?

**Comment by dwhiteddsoft** [comment]
The json as it is received from DirectLine is "isSubtle": "yes". This is why I thought it was a bot problem....

**Comment by ryanlengel** [comment]
Thanks, closing this as I misunderstood :) I've opened up the original issue.

**Comment by andrewleader** [comment]
Thanks, FYI we've created an issue on our Adaptive Cards side tracking the fact that the JavaScript renderer is incorrectly allowing values like `"isSubtle": "yes"`: #2483
