### ISSUE TITLE
TS parser allows incorrect values for boolean values

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#2483]
For Boolean properties (like wrap, isSubtle, etc), the TS parser seems to allow any string or any value and considers those as true... For example, this works...

![image](https://user-images.githubusercontent.com/13246069/53442154-7b323180-39bd-11e9-9830-6cc4dcc900aa.png)

Integers also work...

![image](https://user-images.githubusercontent.com/13246069/53442189-92711f00-39bd-11e9-9942-07489ad68661.png)

**EXPECTED:** Only strictly Booleans `true` and `false` (no quotes) should be allowed

**Comment by dclaux** [comment]
I believe this (and other similar cases) is already fixed in the js\template-engine branch.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dclaux** [comment]
This is fixed. Sorry I can't put my hand on the PR.
