### ISSUE TITLE
Input Adaptive Card is displayed again after click of Submit button in Bot Framework

### ISSUE THREAD

**Issue by ashay-maheshwari** [Microsoft/AdaptiveCards#2490]
# Platform

* Microsoft Bot Framework - Node JS SDK 3.0

# Author or host

Bot in Webchat as well as emulator is displayed with the Adaptive card

# Issue
I am using Input Adaptive Card in bot framework Node JS SDK 3.0
The card on submit action is displayed again in the webchat or bot emulator.

# Code

> / Add dialog to return list of shirts available
> bot.dialog('show_shirts', function(session) {
>   var card_json = {
>     "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
>     "type": "AdaptiveCard",
>     "version": "1.0",
>     "body": [
>       {
>         "type": "TextBlock",
>         "text": "Ticket Incident Details"
>       },
>       {
>         "type": "Input.Text",
>         "id": "incidentTitle",
>         "placeholder": "Title of incident"
>       },
>       {
>         "type": "Input.Text",
>         "id": "incidentDescription",
>         "placeholder": "Description of your incident"
>       }
>     ],
>     "actions": [
>       {
>         "type": "Action.Submit",
>         "title": "Submit",
>         "data": {
>           "x": 13
>         }
>       }
>     ]
>   }
>     var adaptiveCardMessage = new builder.Message(session)
>     .addAttachment({
>         contentType: "application/vnd.microsoft.card.adaptive",
>         content: card_json
>     });
>     session.send(adaptiveCardMessage);
>     session.replaceDialog('values')
>     
>     if (session.message && session.message.value) {
>       // A Card's Submit Action obj was received
>       processSubmitAction(session, session.message.value);
>       session.send("Something")
>       return;
>   }
>  
> 
>     //console.log(card_json.actions.data.first);
> }).triggerAction({ matches: /^(show|list)/i });
> 

* Images 
![image](https://user-images.githubusercontent.com/16608791/53567735-24c41f00-3b86-11e9-8538-c1920d548122.png)

**Comment by paulcam206** [comment]
This would appear to be an issue with Bot Framework...

**Comment by paulcam206** [comment]
Issue moved to [Microsoft/BotBuilder #5322](https://github.com/Microsoft/BotBuilder/issues/5322) via [**ZenHub**](https://www.zenhub.com/)

**Comment by v-kydela** [comment]
@ashay-maheshwari - Have you looked at the relocated issue?

**Comment by v-kydela** [comment]
@paulcam206 - For future reference, the BotBuilder repo is a landing page and the issues in it are supposed to be design change requests. Issues pertaining to BotBuilder V3 go here: https://github.com/Microsoft/BotBuilder-V3/issues

**Comment by paulcam206** [comment]
Will make sure these go to the right place in the future. Thanks @v-kydela!
