### ISSUE TITLE
 [Android] Input.Date and Input.Time value/min/max consistency

### ISSUE THREAD

**Issue by RebeccaAnne** [Microsoft/AdaptiveCards#2496]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android

# Issue

The Input.Date value/min/max properties should only be recognized if they are of the form YYYY-MM-DD. The Input.Time value property should only be recognized if it's of the form HH:MM. The Android code should use the shared model's DateTimePreparser::TryParseSimpleDate and DateTimePreparser::TryParseSimpleTime methods added in #2450 to ensure consistency.

**Comment by shalinijoshi19** [comment]
@almedina-ms assigning to you to take a look

**Comment by RebeccaAnne** [comment]
Fixed by #2732
