### ISSUE TITLE
[TS] Typescript renderer should not accept seconds for initial value for Input.Time

### ISSUE THREAD

**Issue by RebeccaAnne** [Microsoft/AdaptiveCards#2497]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Issue

The designer currently accepts times of the form HH:MM:SS as the initial value for an Input.Time. For consistency with the other renderers, it should only accept HH:MM.

**Comment by shalinijoshi19** [comment]
@dclaux i can take a stab at this?

**Comment by dclaux** [comment]
Sure, no problem.

**Comment by shalinijoshi19** [comment]
This could be lower priority vis-a-vis others that are currenty open.
