### ISSUE TITLE
[Designer] Fallback and requires properties on elements

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2502]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

Designer implementation of #2019

**Comment by shalinijoshi19** [comment]
@dclaux / @andrewleader why is this one still open? Was this not tackled by #2421 ?

**Comment by shalinijoshi19** [comment]
No tooling support for 1.2 for fallback + requires at this point in time. Not blocking the release for 1.2

**Comment by shalinijoshi19** [comment]
"This looks to be more of an aspirational task at this point." - @dclaux
