### ISSUE TITLE
Carousel Support for javascript 

### ISSUE THREAD

**Issue by dattatrayw** [Microsoft/AdaptiveCards#2507]
Hello Team,

I am using adaptive cards in our  Angular 7 based chat application. Currently we need functionality like render multiple adaptive cards in carousel. I found code at your official site  "https://docs.microsoft.com/en-us/adaptive-cards/getting-started/bots"  but its not working at all.
 When I did some research on internet I found carousel is not supporting in adaptive cards currently.

Please let me know is it supporting for JS/ Angular framework or not.

Thanks 
Datta

**Comment by paulcam206** [comment]
@matthidinger or @andrewleader -- care to jump in here?

**Comment by andrewleader** [comment]
Hey @dattatrayw, the carousel is a feature that's part of the Bot Framework, and currently not part of Adaptive Cards.

Bot Framework provides a way for you to provide a set of cards, which they display inside a carousel, they built this themselves.

A workaround is to build this yourself (just like Bot Framework). You can define a data structure for a carousel that takes an array of Adaptive Cards, and then you can render them within a carousel. For example, you could define the following JSON...

```json
{
  "type": "Carousel",
  "cards": [
    { "type": "AdaptiveCard", ... },
    { "type": "AdaptiveCard", ... }
  ]
}
```

And then when your app renders it, you render a carousel, and then use the Adaptive Card renderer to render each of the cards and place them inside your carousel.

However, if you want a carousel natively supported within Adaptive Cards, please let us know and we can track a feature request!

**Comment by dattatrayw** [comment]
Hi @andrewleader 
Here is my test JSON and TS code to render adaptive cards in carousel. But still getting error response.
JSON : 

 var card =

    {
      "type": "Carousel",
      "cards": [
        {
          "contentType": "application/vnd.microsoft.card.adaptive",
          "content": {
              "type": "AdaptiveCard",
              "body": [
                  {
                      "type": "ColumnSet",
                      "columns": [
                          {
                              "type": "Column",
                              "size": "auto",
                              "items": [
                                  {
                                      "type": "Image",
                                      "size": "medium",
                                      "url": "http://adaptivecards.io/content/FabrikamLogo.png"
                                  }
                              ]
                          },
                          {
                              "type": "Column",
                              "items": [
                                  {
                                      "type": "TextBlock",
                                      "text": "Fabrikam",
                                      "size": "large",
                                      "weight": "bolder"
                                  },
                                  {
                                      "type": "TextBlock",
                                      "text": "4.1 stars",
                                      "separation": "none"
                                  }
                              ]
                          }
                      ]
                  },
                  {
                      "type": "TextBlock",
                      "text": "13 miles away",
                      "weight": "bolder"
                  },
                  {
                      "type": "TextBlock",
                      "text": "217 W Pine St.",
                      "separation": "none"
                  },
                  {
                      "type": "TextBlock",
                      "text": "Seattle, WA 98126",
                      "separation": "none"
                  }
              ]
          }
      },
      {
          "contentType": "application/vnd.microsoft.card.adaptive",
          "content": {
              "type": "AdaptiveCard",
              "body": [
                  {
                      "type": "ColumnSet",
                      "columns": [
                          {
                              "type": "Column",
                              "size": "auto",
                              "items": [
                                  {
                                      "type": "Image",
                                      "size": "medium",
                                      "url": "http://adaptivecards.io/content/MargiesTravel.png"
                                  }
                              ]
                          },
                          {
                              "type": "Column",
                              "items": [
                                  {
                                      "type": "TextBlock",
                                      "text": "Margie's Travel",
                                      "size": "large",
                                      "weight": "bolder"
                                  },
                                  {
                                      "type": "TextBlock",
                                      "text": "4.4 stars",
                                      "separation": "none"
                                  }
                              ]
                          }
                      ]
                  },
                  {
                      "type": "TextBlock",
                      "text": "42 miles away",
                      "weight": "bolder"
                  },
                  {
                      "type": "TextBlock",
                      "text": "1602 E Avenue Rd.",
                      "separation": "none"
                  },
                  {
                      "type": "TextBlock",
                      "text": "Gig Harbor, WA 98335",
                      "separation": "none"
                  }
              ]
          }
      },
      {
          "contentType": "application/vnd.microsoft.card.adaptive",
          "content": {
              "type": "AdaptiveCard",
              "body": [
                  {
                      "type": "ColumnSet",
                      "columns": [
                          {
                              "type": "Column",
                              "size": "auto",
                              "items": [
                                  {
                                      "type": "Image",
                                      "size": "medium",
                                      "url": "http://adaptivecards.io/content/Relecloud.png"
                                  }
                              ]
                          },
                          {
                              "type": "Column",
                              "items": [
                                  {
                                      "type": "TextBlock",
                                      "text": "Relecloud Diving",
                                      "size": "large",
                                      "weight": "bolder"
                                  },
                                  {
                                      "type": "TextBlock",
                                      "text": "4.7 stars",
                                      "separation": "none"
                                  }
                              ]
                          }
                      ]
                  },
                  {
                      "type": "TextBlock",
                      "text": "15 miles away",
                      "weight": "bolder"
                  },
                  {
                      "type": "TextBlock",
                      "text": "1210 W Hanford St.",
                      "separation": "none"
                  },
                  {
                      "type": "TextBlock",
                      "text": "Seattle, WA 98105",
                      "separation": "none"
                  }
              ]
          }
      },
      {
          "contentType": "application/vnd.microsoft.card.adaptive",
          "content": {
              "type": "AdaptiveCard",
              "body": [
                  {
                      "type": "ColumnSet",
                      "columns": [
                          {
                              "type": "Column",
                              "size": "auto",
                              "items": [
                                  {
                                      "type": "Image",
                                      "size": "medium",
                                      "url": "http://adaptivecards.io/content/AdventureWorksLogo.png"
                                  }
                              ]
                          },
                          {
                              "type": "Column",
                              "items": [
                                  {
                                      "type": "TextBlock",
                                      "text": "Adventure Works",
                                      "size": "large",
                                      "weight": "bolder"
                                  },
                                  {
                                      "type": "TextBlock",
                                      "text": "3.2 stars",
                                      "separation": "none"
                                  }
                              ]
                          }
                      ]
                  },
                  {
                      "type": "TextBlock",
                      "text": "7 miles away",
                      "weight": "bolder"
                  },
                  {
                      "type": "TextBlock",
                      "text": "510 N Yale Ave.",
                      "separation": "none"
                  },
                  {
                      "type": "TextBlock",
                      "text": "Seattle, WA 98127",
                      "separation": "none"
                  }
              ]
          }
      }
      ]
    }

TS : 

    var adaptiveCard = new AdaptiveCards.AdaptiveCard();
    adaptiveCard6.parse(card);
    var renderedCard = adaptiveCard.render();
    var d1 = this.elRef.nativeElement.querySelector("#adaptiveCard");
    d1.appendChild(this.renderedCard)

Error on UI : 
The card could not be rendered. It is either malformed or uses features not supported by this host.

**Comment by dclaux** [comment]
@dattatrayw in the above example you're feeding a Carousel object to the Adaptive Card TS renderer. That can't work; carousel is a Bot concept, not an AdaptiveCard concept. While you can send a carousel in a Bot message, and the receiving Bot client will handle it just fine, Adaptive Card renderers do not handle carousel, only single AdaptiveCard objects. If you want to render multiple Adaptive Cards in your application, you will have to render them one by one and assemble them whichever way you want.

**Comment by andrewleader** [comment]
Yeah @dattatrayw as I said, either your app can do choose to render/assemble multiple cards in a carousel however you want (like David described and I described earlier), or you can request a new feature from Adaptive Cards to support a carousel control. Let us know what you want, we're happy to help further with either!

**Comment by dattatrayw** [comment]
Hi @dclaux , @andrewleader 
So if I am not wrong you guys suggesting to install bot framework npm package and with the help of bot framework I can render my adaptive cards in carousel.
I suggest it will good if adaptive cards could support carousel. 
Please correct me if I am wrong.

**Comment by dattatrayw** [comment]
Hi @dclaux , @andrewleader 
So for carousel I have generated html from render function and created multiple adaptive cards html list variable, Passed this list to angular carousel for render it on html.
So fast this solve my issue, But it could be great if adaptive cards support this must need feature in it.
Thanks for help.

**Comment by andrewleader** [comment]
Thanks @dattatrayw, glad to hear you implemented a workaround!

We'll track a new feature request for a carousel control here: #2521
