### ISSUE TITLE
Adaptive Card does not render in Teams Android  

### ISSUE THREAD

**Issue by schnill** [Microsoft/AdaptiveCards#2508]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android

# Author or host

I am an host trying to render a card in Teams android client.

# Version of SDK

We are using sdk version 1.0.4

# Issue
**Renderer thrown an error with message "Adaptive Card does not contain body"**

We have a card json and we get instance of AdaptiveCard as instructed using below code snippet 
 
```
ParseResult parseResult = AdaptiveCard.DeserializeFromString(..)
AdaptiveCard adaptiveCard = parseResult.GetAdaptiveCard();

```
`AdaptiveCardRenderer.getInstance().render` throws an exception "Adaptive Card does not contain body" 
# #

**Comment by paulcam206** [comment]
Can you please provide a sample of the card you're trying to render?

**Comment by shalinijoshi19** [comment]
@schnill ping? Can you provide us with a quick repro sample please to rule out any user-error?  Please reactivate with the sample once you do have it. Thanks!
