### ISSUE TITLE
Video-control override (or adaptive sizing)

### ISSUE THREAD

**Issue by achipa** [microsoft/AdaptiveCards#2528]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF
* UWP

# Author or host

Host

# Version of SDK

Nuget uwp-v1.1.2

# Issue

By default, the Windows 10 (UWP/WPF) renderer uses the two-row Media Transport Control on Video elements:

![image](https://user-images.githubusercontent.com/822934/54121919-43fe5000-43c1-11e9-8f6a-d9491d5d7bc8.png)

However, Adaptive cards are often rendered non-fullscreen, in preset and/or limited space, so the two-line transport control can get intrusive, especially on 16:9 or wider video content, for example:

![image](https://user-images.githubusercontent.com/822934/54122408-8ecc9780-43c2-11e9-820d-f194970e92c7.png)
 
Windows *does* allow for a better presentation for use-cases like Adaptive Cards through the [isCompact](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.mediatransportcontrols.iscompact#Windows_UI_Xaml_Controls_MediaTransportControls_IsCompact) property of MediaTransportControls:

![image](https://user-images.githubusercontent.com/822934/58972842-b93caf80-877b-11e9-8d4b-d469d0cc02e3.png)

….but currently there is no way to enable this from the host side. 

Request: 
a) Expose isCompact through the hostconfig schema, and/or 
b) Enable isCompact adaptively in the renderer if the two-row control takes up more than 20% (?) of the video element.

**Comment by andrewleader** [comment]
Excellent feedback! I'd say we should always use the compact style by default, since cards by nature are usually small, and then we could always add the option to enable the full size controls (which maybe we tell hosts to accomplish by extending the media renderer or something, rather than host config, since each platform might have different media control options).

**Comment by achipa** [comment]
@andrewleader Certainly. While we are at the defaults - we might have another niggle that would be worth setting differently by default in the context of Adaptive Cards:

@Windows.UI.Xaml.Controls.MediaTransportControls.IsZoomButtonVisible?text=IsZoomButtonVisible (**true**)

As the media will always be rendered *within* the (normally small) card, this should be off unless there is a specific width/height setting is specified (as normally you'll not want to letterbox a video that is already of small dimensions), or just be off altogether when displayed as part of a card. As is, it's a (from a user perspective) a dead button only cluttering the card (gets extra-painful on portrait mode videos).

@andrewleader Should I file that as a separate improvement request or should we track that as part of this transport control story?

**Comment by andrewleader** [comment]
@achipa I'll discuss both of these things with the Adaptive Cards team by next week and then we'll let you know! I think you're totally right that we should eliminate that zoom button :P I'll just quickly sync with the rest of the team and make sure they're on the same page.

For now let's keep this all tracked in this one issue. Thanks for the great feedback!

**Comment by achipa** [comment]
@andrewleader Just checking in if there have been any news around this? If it's a prioritization issue, I'm happy to do a PR as long as there is an agreement on the change. (I'd always rather upstream than having to maintain forks for things like these)

**Comment by andrewleader** [comment]
With achipa's pull request (thanks!!), we made isCompact the default behavior :) If further customization is needed please open a new issue!
