### ISSUE TITLE
[.NET] [HTML] Add SelectAction to InlineTextRuns

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#2530]
Part of #2378 
Spec: #1933 

Addendum to work from #2519

**Comment by RebeccaAnne** [comment]
This is implemented for WPF but not yet for HTML

**Comment by almedina-ms** [comment]
@RebeccaAnne @paulcam206 @shalinijoshi19 @andrewleader do we have any plans or ideas on how are we going to render the select actions for HTML?? are they going to be links or how are we planning on callling the behavior for select actions here? I don't think we have actual behaviors for any actions that are not ShowCard and ToggleVisibility actions (added for v1.2)

**Comment by andrewleader** [comment]
I believe the inline text SelectActions should just be links `<a>Click me to submit</a>`, that's what you did in JS, right @dclaux?

**Comment by shalinijoshi19** [comment]
thanks! @almedina-ms / @RebeccaAnne  FYI moving this out of 1.2 at this point for post-RTM fixing.

**Comment by jonmill** [comment]
.NET HTML is deprecated
