### ISSUE TITLE
Reconcile XamlHelpers::IterateOverVector implementations

### ISSUE THREAD

**Issue by paulcam206** [Microsoft/AdaptiveCards#2533]
We currently have two versions of `XamlHelpers::IterateOverVector()` -- one that iterates through all items ignoring any failures coming from the supplied callback, and one that gives the option of ending the iteration on failure. We should consolidate it down to one implementation and fix consumers. While we're at it, we should probably demote `XamlHelpers` from a class to a namespace.

**Comment by shalinijoshi19** [comment]
@paulcam206 is this coming in for 1.2?
