### ISSUE TITLE
[UWP] Regression: Image with explicit size and person style clipped rather than stretched

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#2548]
In UWP (current master), an image with explicit size and style:person ends up clipped rather than stretched (see `Tests\Image.Explicit.Size.json`):

![image](https://user-images.githubusercontent.com/16614499/54381728-b4200680-464b-11e9-83f5-1b1467316387.png)

**Comment by shalinijoshi19** [comment]
@paulcam206 / @RebeccaAnne does this need to get fixed for 1.2? Would this be addressed with some of the other issues around image clipping we are tracking already?

**Comment by shalinijoshi19** [comment]
Load balancing out to you @paulCam206

**Comment by paulcam206** [comment]
regressed by 6ffc99b

**Comment by shalinijoshi19** [comment]
@paulcam206, how are we looking on this one?
