### ISSUE TITLE
Updates of Adaptive Card for Skype

### ISSUE THREAD

**Issue by CalvinFengDatacom** [microsoft/AdaptiveCards#2558]
# Updates of Adaptive Card for Skype? (Skype for business)

Hi guys, is there any updates of the Adaptive Card development for Skype?

I can see from MS Adaptive Card document, the status of channel of Skype is in development, any updates or ETA to share?

Thanks

**Comment by andrewleader** [comment]
Thanks for asking Calvin, we don't have any updates to share around Skype support.
