### ISSUE TITLE
Create a anchor link between text block

### ISSUE THREAD

**Issue by atishayv** [Microsoft/AdaptiveCards#2564]
# Platform

* JavaScript

# Author or host

Host

# Version of SDK

1.0.

# Issue

I want to create a card with a link between TextBlock. Can you please explain whether is it possible using adaptiveCard ?

Something like this should be rendered : 

> Hello world
> [Link to Hello world](https://www.google.com/)
> End

**Comment by dclaux** [comment]
You can totally do that, just use Markdown syntax:
```
{
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "TextBlock",
			"text": "Hello world"
		},
		{
			"type": "TextBlock",
			"text": "[Link to Hello world](http://www.helloworld.com)"
		},
		{
			"type": "TextBlock",
			"text": "End"
		}
	]
}
```

**Comment by atishayv** [comment]
Sorry, I will rephrase my question. Basically I want to insert an action of openUrl between text block. 
Something like this should be rendered :

Hello world
[Link to Hello world](https://www.google.com/)
End

But also I want to console log, that this link was clicked.

Can you tell me how is it possible using adaptiveCards ?

**Comment by dclaux** [comment]
Just handle either the global `AdaptiveCard.onAnchorClicked` event, or the per-card-instance `card.onAnchorClicked` event. Have your handler return `true` if it handled the click, or `false` to let the default execution happen.

**Comment by atishayv** [comment]
Cool... Thanks
