### ISSUE TITLE
Ability to specify High contrast mode for a card in Host Options

### ISSUE THREAD

**Issue by riarenas** [Microsoft/AdaptiveCards#257]

**Comment by matthidinger** [comment]
@riarenas can you elaborate on this one? Not sure I follow the ask, or what change would be necessary in host config. Also I assume this is necessary for v1? If so, please feel free to add the v1 milestone

**Comment by riarenas** [comment]
This was an issue that came out for Timeline. They wanted some way to be able to specify a whole arrange of settings for High contrast mode in HostConfig.

**Comment by riarenas** [comment]
I wonder if just swapping host configs would be the way to go. Having a whole set of options for high contrast mode could bloat the HostConfig JSON payload.

**Comment by dclaux** [comment]
@riarenas Yes swapping HostConfig is the solution :) It'll cover 95% of your needs. Areas that are not covered by HostConfig are buttons (although that's controlled by the host, so I don't think it's a problem) and images - how would a card author provide high-contrast versions of the images they use?

**Comment by riarenas** [comment]
Decided that swapping host configs when the host detects the contrast mode change is the way to go.
