### ISSUE TITLE
Update adaptive card on invoking an action

### ISSUE THREAD

**Issue by atishayv** [microsoft/AdaptiveCards#2577]
# Platform
* JavaScript

# Author or host
 Host

# Version of SDK
1.0 

# Issue
Is there a way to update an adaptive card on invocation of an action?
For ex : On click of custom action which makes request to server and get the response, I want to set status text in card as success without re rendering the entire card. Can you provide an example on how to do that?

**Comment by dclaux** [comment]
That isn't currently supported. You will have to re-render.

**Comment by atishayv** [comment]
Is there a plan to support it like in 2.0 version ?

**Comment by andrewleader** [comment]
Hey @atishayv, can you explain some about where you're using Adaptive Cards? Are you sending them to Teams/Outlook/Bot Framework? Or rendering cards yourself?

**Comment by atishayv** [comment]
I am rendering the card in my own host app.
