### ISSUE TITLE
No postback in adaptive cards with inputs

### ISSUE THREAD

**Issue by jakmex** [microsoft/AdaptiveCards#2578]
# Platform
* .NET HTML
# Author or host
host
# Version of SDK
V 1.0

# Issue

Hi good day,

I have been struggling with the postback option in web when a card has input elements.

if I remove the input element the postback is working but as soon I add any type of input element the action is not working.

If you could help me understand what I am doing wrong, I will really appreciate it.

```json
{
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "size": "Medium",
      "weight": "Bolder",
      "text": "New SNC Ticket",
      "horizontalAlignment": "Center"
    },
    {
      "type": "Input.Text",
      "title": "New Input.Toggle",
      "placeholder": "Placeholder text",
      "id" : "test"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Send Ticket",
      "data": "Sending Ticket"
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```
![image](https://user-images.githubusercontent.com/13124469/55176786-6aedad80-5147-11e9-93c1-bb04b8e8ff20.png)

**Comment by andrewleader** [comment]
Hey jakmex, sorry for never responding. Did you manage to fix your problem with receiving the postback?

Thanks!
Andrew

(Closing for now, feel free to re-open)
