### ISSUE TITLE
Action.ShowCard crashes parse method when card is not provided

### ISSUE THREAD

**Issue by MattSFT** [microsoft/AdaptiveCards#2579]
# Platform
* JavaScript

# Author or host
Host, App Studio application in Microsoft Teams. The AdaptiveCards.io designer also crashes with the same issue

# Version of SDK

"adaptivecards": "^1.1.3",

# Issue

The card below causes the parse function to crash because the action is Action.ShowCard but the user accidentally put a url there instead of a card object. The schema says this is correct.

Here is a sample card:
```json
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "text": "Hello World!"
    }
  ],
  "actions": [
    {
      "type": "Action.ShowCard",
      "title": "Suggest edit",
      "url": "http://adaptivecards.io"
    }
  ]
}
```

**Comment by paulcam206** [comment]
The schema has been updated to reflect that `url` is not a valid property
