### ISSUE TITLE
[UWP][1.2] isVisible on column doesn't work

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2586]
# Platform

* UWP

# Version of SDK

1.2.0-beta

# Issue

`isVisible` doesn't seem to work on columns in UWP. Similarly, trying to toggle the visibility of a Column doesn't work.

For example, see below... the column renders despite isVisible being set to false.

```json
                {
                    "type": "Column",
                    "spacing": "small",
                    "verticalContentAlignment": "center",
                    "id": "chevronUp2",
                    "isVisible": false,
```

Test payload is on https://messagecardplayground.azurewebsites.net/ (select the Zoho sample)

**Expected**
 
![image](https://user-images.githubusercontent.com/13246069/55258841-436b1380-5221-11e9-9115-f7f6ba5603ba.png)

**Actual**: Both buttons appear since column visibility isn't respected
 
![image](https://user-images.githubusercontent.com/13246069/55258853-4f56d580-5221-11e9-854f-6ecec6da9979.png)

**Comment by shalinijoshi19** [comment]
@RebeccaAnne please investigate if this behavior needs to be fixed on other renderers and let's make sure those are tracked by bugs as well. iff we decide to fix this.

**Comment by shalinijoshi19** [comment]
@paulcam206 reassigning to you to load balance.

**Comment by RebeccaAnne** [comment]
Taking this back as I am actively working on it.
