### ISSUE TITLE
[WPF][1.2] Toggling visibility of columns doesn't work

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#2587]
# Platform

* .NET WPF

# Version of SDK

1.2.0-beta

# Issue

Using Action.ToggleVisibility to show a previously-non-visible column doesn't work. See the animation below. Clicking the drop down should (1) hide the current column (which works) and (2) show a different column (which doesn't work).

![WpfColumnVisibility](https://user-images.githubusercontent.com/13246069/55259579-4a932100-5223-11e9-8a04-59f86fec788d.gif)

Repro payload on https://messagecardplayground.azurewebsites.net/ (select the Zoho sample)

**Comment by shalinijoshi19** [comment]
@almedina-ms could you please investigate. Thanks!

**Comment by almedina-ms** [comment]
Just ran the application with the card provided and I think it works

@andrewleader  is this the expected behaviour?

![negativeMarginDisappear](https://user-images.githubusercontent.com/35784165/56541366-5f13c200-6520-11e9-834f-d06a76f31765.gif)
