### ISSUE TITLE
[WPF] Inline ShowCard is not supported

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2599]
WPF doesn't support inline ShowCard (all the other renderers do). This is a feature parity gap that we need to address.

**Comment by shalinijoshi19** [comment]
In addition to this, we should remove support for ShowCard and selectaction in the .NET renderers.
(1) Per discussion today, at the team meeting, we will move this to match what was originally decided upon ie showCard and selectAction is *NOT* supported in Adaptive Card renderers. 
(2) In addition we will include a warning that the host would get knowing it's pop-up is being dropped though. (@almedina-ms FYI)
