### ISSUE TITLE
Ensure ToggleVisibility interacts with separators correctly

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2600]
<table>
<tr>
<th>Release</th>
<th>Renderer status</th>
<th>Tasks status</th>
</tr>
<tr>
<td>1.2
<td>✔️ .NET (#2604)<br/>✔️ Android (#2605)<br/>✔️ iOS (#2606)<br/>✔️ TS (#2607)<br/>✔️ UWP (#2608)</td>
<td>✔️ Shared (#2602)<br/>✔️ Designer (#2603)</td>
</tr>
</table>

Reducing the scope of this issue to track separator issue only. Bleed issue now tracked by #2812.

Many of our renderers likely don't handle scenarios around ToggleVisibility and separators. We should ensure this works correctly on all our renderers. 

So it looks like ToggleVisibility's effect is solely to change the Visibility property of the framework element associated with the specified Adaptive element Id. Does the framework element include the target element's potentially visible separator? If not, then ToggleVisibility may result in an orphaned separator.

# Auto-generated task status

- [x] Shared
- [x] Designer
- [x] .NET
- [x] Android
- [x] iOS
- [x] TS
- [x] UWP

**Comment by shalinijoshi19** [comment]
Approving. Please investigate + fix. thanks

**Comment by shalinijoshi19** [comment]
@almedina-ms please close once all related bugs are addressed in this area. Assigning to you for tracking. Tx
