### ISSUE TITLE
[UWP] Ensure ToggleVisibility interacts with separators correctly

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2608]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

UWP fix of #2600

**Comment by shalinijoshi19** [comment]
This looks like this should be done. Marking Approved.

**Comment by shalinijoshi19** [comment]
@paulcam206   assigning to you for loadbalancing. Thanks!
