### ISSUE TITLE
[Skype] AdaptiveSubmitAction not generating any activity

### ISSUE THREAD

**Issue by AndreMantas** [microsoft/AdaptiveCards#2611]
# Version of SDK

Nuget 1.1.2

# Issue

As per [schema](https://adaptivecards.io/explorer/Action.Submit.html), `data` can be `string,object`, but currently Skype does not generate any activity either way when a button is clicked.

Is there any way to trigger at least an imBack when data is a plain string (as webchat does)?

Without this, the simple case where a bot needs to show some cards with structured data in a carousel/list with one single "choose this option" button per card is not possible.

With an imBack at least there would be some workarounds for this.

I talked about this a bit [here](https://github.com/Microsoft/botbuilder-dotnet/issues/1202#issuecomment-479102756) but was redirected to this repo.

**Comment by matthidinger** [comment]
Hi @AndreMantas, Skype never officially released adaptive card support so it's hard to say what behavior you will get. Are you seeing the expected behavior when you use your payload in WebChat?

**Comment by AndreMantas** [comment]
Yes.

Upon button click, the string that I set in Data instantly appears in chat and bot receives activity with Text filled and Value null (as expected since its an imBack and not a postBack).

If this is not possible, is there any workaround?

**Comment by AndreMantas** [comment]
@matthidinger any update? can this be fixed at the connector, maybe?

**Comment by matthidinger** [comment]
Unfortunately I'm not aware of any workaround given Skype never officially supported Adaptive Cards, so I'm not surprised there are inconsitencies or incomplete behaviors. As soon as I hear anything about Skype continuing rollout of adaptive cards I will be sure to post here, but I don't expect anything soon. Really sorry about the troubles. Bot Framework WebChat is under active development and staying current with adaptive cards releases (including v1.2 soon) so maybe you could use that tool possibly?

**Comment by matthidinger** [comment]
Skype adaptive cards are not currently in development. If anything changes in this regard we'll make sure actions are working properly.
