### ISSUE TITLE
iOS Text Processor

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#2615]
There are numbers of text related tasks such as date parsing / markdown / rich text block / text block, and new features will be added for text in the future. Having one unit that handles text related task will increase code maintainability and re-usability.

Completion of this task will create one text processor that will handle all of these features, and old usages will become client calls to this text processor.

**Comment by shalinijoshi19** [comment]
This was already merged/closed. wiht the referenced PR
