### ISSUE TITLE
Support RGB or hex code text color formatting instead of fixed value

### ISSUE THREAD

**Issue by vishrutshukla** [Microsoft/AdaptiveCards#2630]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Microsoft Teams
* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

# Author or host
Author and host both

If you're an author, who are you sending cards to?

# Version of SDK

1.1

# Issue

Support RGB or hex code text color formatting instead of fixed value

Explain your issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards).

**Comment by dclaux** [comment]
@vishrutshukla this goes against one of the guiding principles of Adaptive Cards, namely that it is up to the host application to impose its own actual colors. There is very little chance that we'd move to an explicit color model.
