### ISSUE TITLE
Backport fix for Issue #2478 to 1.0.*

### ISSUE THREAD

**Issue by shalinijoshi19** [Microsoft/AdaptiveCards#2635]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards?

If you're an author, who are you sending cards to?

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

# Issue
Backporting fix for Issue #2478

**Comment by paulcam206** [comment]
This was fixed by PR #2633
