### ISSUE TITLE
Android renderer throws uncatcheable exception with Teams dark Host Config

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2636]
# Platform

* Android

# Version of SDK

1.2 (latest master)

# Issue

When using the [Teams dark host config](https://github.com/Microsoft/AdaptiveCards/blob/master/samples/HostConfig/microsoft-teams-dark.json) (or Teams light) in the Android renderer, it throws an exception that cannot be caught.

> terminating with uncaught exception of type AdaptiveCards::AdaptiveCardParseException: Enum type was invalid. Expected type string.

**Comment by shalinijoshi19** [comment]
@almedina-ms could you take a stab at this ? Thanks!

**Comment by shalinijoshi19** [comment]
@andrewleader is this a regression wtih 1.2?

**Comment by andrewleader** [comment]
@shalinijoshi19 no clue, I don't have Android 1.1 to test against, and only discovered this when playing with 1.2 in our new app.

**Comment by almedina-ms** [comment]
I have no repro on this bug using the latest master

**Comment by shalinijoshi19** [comment]
Thanks for confirming @almedina-ms ; @andrewleader  closing this one out then
