### ISSUE TITLE
[Android] Update minHeight implementation to only apply to Container types (Columns/ColumnSets/Cards)

### ISSUE THREAD

**Issue by shalinijoshi19** [Microsoft/AdaptiveCards#2646]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android

# Author or host

Neither. Feature dev.

If you're an author, who are you sending cards to?

# Version of SDK

master

# Issue

Per discussion, minHeight should only apply to container types and not all elements.

Containers
Columns
ColumnSets
AdaptiveCards

**Comment by almedina-ms** [comment]
Solved in this PR https://github.com/Microsoft/AdaptiveCards/pull/2660
