### ISSUE TITLE
Markdown doesn't handle nested [] inside link display text

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#2650]
<table>
<tr>
<th>Release</th>
<th>Renderer status</th>
<th>Tasks status</th>
</tr>
<tr>
<td>1.2
<td>✔️ .NET (#2653)<br/>✔️ Android (#2654)<br/>✔️ iOS (#2655)<br/>✔️ TS (#2656)<br/>✔️ UWP (#2657)</td>
<td>🔄 Shared (#2651)<br/>✔️ Designer (#2652)</td>
</tr>
</table>

**Reported by**
 * Teamwork on 4/9/2019

With markdown links, you're supposed to be able to have a nested [] inside the display text of the link, like seen below

**Markdown**
```
[Bug [021356]](https://msn.com): Markdown link parsing
```

**Correct rendering** (commonmark renders like this too)
![image](https://user-images.githubusercontent.com/13246069/55826038-f22e1000-5abb-11e9-9b2a-301a2797d631.png)

However, on some of our platforms, this doesn't work correctly and is just displayed as raw text...

**Incorrect rendering**
![image](https://user-images.githubusercontent.com/13246069/55826128-273a6280-5abc-11e9-8681-2df4df8558d8.png)

**Card repro payload**
```json
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "text": "Markdown link with [] in display text"
        },
        {
            "type": "TextBlock",
            "text": "[Bug [021356]](https://msn.com): Markdown link parsing"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

(I'll create the sub-issues once ZenHub service is back up... this bug definitely exists in Android, but not TS, but maybe other renderers?)

# Auto-generated task status

- [ ] Shared
- [x] Designer
- [x] .NET
- [x] Android
- [x] iOS
- [x] TS
- [x] UWP

**Comment by shalinijoshi19** [comment]
@RebeccaAnne assigning to you since you are already looking into this..

**Comment by shalinijoshi19** [comment]
N/m checked the status of #2651 and noticed @nesalang you have it.. This broader one goes to you as well for tracking.
