### ISSUE TITLE
[Android] Markdown doesn't handle nested [] inside link dispaly text

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#2654]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

Android fix of #2650

**Comment by andrewleader** [comment]
Android has this bug

![image](https://user-images.githubusercontent.com/13246069/55827849-01af5800-5ac0-11e9-8b6f-e784a5809901.png)

**Comment by RebeccaAnne** [comment]
This is handled by the shared model, so the shared model fix should address this for Android.
