### ISSUE TITLE
[UWP] Markdown doesn't handle nested [] inside link dispaly text

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#2657]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

UWP fix of #2650

**Comment by andrewleader** [comment]
Confirmed UWP has this bug:

![image](https://user-images.githubusercontent.com/13246069/55827804-e80e1080-5abf-11e9-9039-acb5425949de.png)

**Comment by RebeccaAnne** [comment]
This is handled by the shared model, so the shared model fix should address this for UWP.
