### ISSUE TITLE
[Designer] Setting Image width settings incorrect behavior

### ISSUE THREAD

**Issue by matthidinger** [Microsoft/AdaptiveCards#2658]
See gif. I set the image Width/Height to "50px" then click something else, then re-select the Image, the property sheet shows "50" instead of "50px" 

![designer](https://user-images.githubusercontent.com/1432195/55833476-7b4d4300-5acc-11e9-8db4-08286455ba80.gif)

**Comment by andrewleader** [comment]
Nice ScreenToGif 😎
