### ISSUE TITLE
Elements with bleed should bleed top and bottom in addition to left and right

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#2702]
<table>
<tr>
<th>Release</th>
<th>Renderer status</th>
<th>Tasks status</th>
</tr>
<tr>
<td>1.2
<td>✔️ .NET (#2705)<br/>✔️ Android (#2706)<br/>✔️ iOS (#2707)<br/>✔️ TS (#2708)<br/>✔️ UWP (#2709)</td>
<td>✔️ Shared (#2703)<br/>✔️ Designer (#2704)</td>
</tr>
</table>

# Issue

On all non-javascript platforms, the bleed property currently only causes bleeding behavior to the left and right, not the top and bottom.

# Auto-generated task status

- [x] Shared
- [x] Designer
- [x] .NET
- [x] Android
- [x] iOS
- [x] TS
- [x] UWP

**Comment by andrewleader** [comment]
Closing as done
