### ISSUE TITLE
[Designer] Elements with bleed should bleed top and bottom in addition to left and right

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#2704]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

Designer fix of #2702

**Comment by RebeccaAnne** [comment]
@dclaux Assiging this auto-generated bug to you to track any changes you may want to make to the designer to make the top/bottom bleed more obvious. If this issue isn't useful to you or is tracked elsewhere feel free to close.

**Comment by dclaux** [comment]
At this point the behavior is by design in designer. Closing this.
