### ISSUE TITLE
[.NET] Elements with bleed should bleed top and bottom in addition to left and right

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2705]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

.NET fix of #2702

**Comment by shalinijoshi19** [comment]
@RebeccaAnne is this already in PR or covered by your shared model PR?

**Comment by almedina-ms** [comment]
@shalinijoshi19 There are two shared models. 
* The C++ shared model is consumed by the UWP, Android and iOS renderer. 
* The C# shared model is more of an object model and is consumed by the WPF and HTML renderers
When we talk about shared model, we usually refer to the C++ one
