### ISSUE TITLE
[Android] Elements with bleed should bleed top and bottom in addition to left and right

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2706]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

Android fix of #2702

**Comment by shalinijoshi19** [comment]
@almedina-ms  / @RebeccaAnne is this required to be fixed explicitly for Android or is sharedmodel changes going to address things here?

**Comment by RebeccaAnne** [comment]
There will be renderer specific work for Android once the shared model changes are in place.
