### ISSUE TITLE
[iOS] Elements with bleed should bleed top and bottom in addition to left and right

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2707]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

iOS fix of #2702

**Comment by shalinijoshi19** [comment]
@nesalang / @RebeccaAnne is there anything left on the iOS side explicitly for this bug? Or would the sharedmodel changes suffice?

**Comment by RebeccaAnne** [comment]
There will be renderer specific work for Android once the shared model changes are in place.

**Comment by shalinijoshi19** [comment]
Closing out. This is now pending merge with master from @RebeccaAnne 's branch
