### ISSUE TITLE
[.NET] Case sensitive string comparisons

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#2710]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML
* .NET WPF

# Issue

.NET seems to be making case sensitive string comparisons. The button in the following card does not render due to the type being "Action.OpenURL" rather than "Action.OpenUrl"
```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "text": "This card's action will open a URL"
    }
  ],
  "actions": [
    {
      "type": "Action.OpenURL",
      "title": "Action.OpenUrl",
      "url": "http://adaptivecards.io"
    }
  ]
}
```

**Comment by shalinijoshi19** [comment]
Moving this out of 1.2 for now

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.
