### ISSUE TITLE
[UWP] Don't re-use custom AdaptiveImage renderer for background images

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2712]
Using the AdaptiveImage renderer to render background images causes strange things. As a host, if I override rendering of AdaptiveImage, I also override rendering of background images, which probably wasn't my intention.

![image](https://user-images.githubusercontent.com/13246069/56326426-ce597280-612a-11e9-8e88-d67d9d61d797.png)

At the working group meeting today (with Matt, David, Andrew, Bill, Alberto, Shalini, Becky, and Paul), consensus was that we shouldn't be doing this.

When a need arises for overriding background image rendering, we'll solve that with a separate API

**Comment by shalinijoshi19** [comment]
@almedina-ms assigning to you for load balancing; Also @RebeccaAnne / @andrewleader moving this out of 1.2 to make space for some of the other breaking/pressing bugs

**Comment by shalinijoshi19** [comment]
The work that this bug needs in XamlBuilder is being tracked by issue #3026

**Comment by shalinijoshi19** [comment]
@paulcam206 assigning to you; Do you just want to use this as a test for the rework you are doing as part of #2534 now?

**Comment by RebeccaAnne** [comment]
See also #1605
