### ISSUE TITLE
Semantic hints on actions to mark destructive/undestructive

### ISSUE THREAD

**Issue by matthidinger** [Microsoft/AdaptiveCards#272]
Dupe of #861

### Problem Space

If Hosts/platforms have UX guidelines on how to order actions like OK/Cancel or Accept/Decline, we should allow authors to markup their actions accordingly. Hosts should also be able to style these if they wish.

**Comment by matthidinger** [comment]
Also useful in scenarios where there is a primary action 
![image](https://cloud.githubusercontent.com/assets/1432195/26745013/78a096be-479d-11e7-9840-b1b83e0de5b5.png)

**Comment by matthidinger** [comment]
# Proposal
We are optimizing this proposal based on **visual experience** to draw attention to the intent of the action versus relying on the order of the buttons. The web is an example of a great cross-plat experience that users have shown adept to.

## Schema

**New** property on `Action` 

Property|Type|Required|Description
---|---|---|---
Style|enum [emphasized, normal, destructive] |false|Applies a style to an Action to indicate to intent

## Host Config
TBD: pending another discussion on Action styling


## Renderer Requirements

1. TBD

**Comment by andrewleader** [comment]
Closing as dupe of #861
