### ISSUE TITLE
Add nullability annotations to Objective C headers

### ISSUE THREAD

**Issue by johnflanagan-spok** [microsoft/AdaptiveCards#2738]
# Platform
* iOS

# Author or host
host

# Version of SDK
1.2.0-beta1

# Issue
When working with AdaptiveCards from Swift the lack of nullability annotations in the Objective C headers make the library very error prone. 

Adding nullability annotations as described in this document would make the library much safer and easier to use. 

https://developer.apple.com/documentation/swift/objective-c_and_c_code_customization/designating_nullability_in_objective-c_apis

**Comment by shalinijoshi19** [comment]
@johnflanagan-spok if you have a PR out to help out wiht this work item we'd be happy to absorb this. We have been swamped with a few higher priority items/bugs but would love to see this happen esp if it helps you out.
