### ISSUE TITLE
[Android] Select Action With Hyperlink

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#2739]
# Platform
* Android

# Issue
Json Used:
```
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
           {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "[Select](http://adaptivecards.io) Choice",
                    "horizontalAlignment":"Right",
                    "wrap":true
                }
             ],
             "selectAction": {
                "type": "Action.Submit",
                "title": "Submit action",
                "data": {
                    "info": "Data of choice 2"
                }
            }
        }
    ]
}
```

# Description
Container has a selection action, and a TextBlock. The TextBlock has a hyperlink.
As shown in the image, clicking on the white space on the row from where hyper link in text is to the left will trigger hyper link instead of the selection action of the container. 
![Screenshot (7)](https://user-images.githubusercontent.com/4112696/56536156-384e8f00-6512-11e9-84eb-feb7b592f8e0.png)

**Comment by jonmill** [comment]
Closing as by-design
