### ISSUE TITLE
Should whitespace be allowed for use as an ID?

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#2748]
I haven't had the chance to check across platforms yet, but I bet that the `id` property is allowed to be whitespace across most (all?) platforms. Should it?

**Comment by shalinijoshi19** [comment]
Whitespaces for Id's dont make much sense; We should fix our parsers/renderers - wherever it is that this is enforced to not allow these.

**Comment by andrewleader** [comment]
Agreed. We ought to define what a valid ID is, for example a-z, A-Z, 0-9 and maybe nothing more? Or just follow what C# does for variable names?

**Comment by paulcam206** [comment]
should we trim leading/trailing whitespace or reject them altogether?

**Comment by andrewleader** [comment]
I'd say reject all together, and enforce a strict Regex for ids.

**Comment by jonmill** [comment]
Whatever is shipped today is the supported scenario - we can't break existing customers at this point
