### ISSUE TITLE
[TS] Changes to column style padding to improve visual layout of content

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2761]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

TS implementation of #2755

**Comment by dclaux** [comment]
Implemented here: https://github.com/Microsoft/AdaptiveCards/pull/2750

**Comment by RebeccaAnne** [comment]
Reopening as we have decided not to make this change. This bug now tracks reverting to the original behavior.

**Comment by dclaux** [comment]
Already fixed here: https://github.com/microsoft/AdaptiveCards/pull/2771
