### ISSUE TITLE
[.NET] Action Fallback card doesn't render properly

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#2772]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF
* .NET HTML

# Issue

The [samples\v1.2\Elements\ActionFallback.json](https://github.com/Microsoft/AdaptiveCards/blob/master/samples/v1.2/Elements/ActionFallback.json) card does not render correctly on .NET WPF visualizer. The fallback actions are not being rendered. 

UWP results [correct]:
![image](https://user-images.githubusercontent.com/9091833/56838040-87a5ff80-6831-11e9-8c16-44c525fe0334.png)

.NET WPF results [missing fallback actions]:
![image](https://user-images.githubusercontent.com/9091833/56838075-a0aeb080-6831-11e9-9fb6-06fe8eb69780.png)

**Comment by shalinijoshi19** [comment]
@almedina-ms is this something you can take a stab at ?

**Comment by almedina-ms** [comment]
@shalinijoshi19 yes, I can take a stab at this
