### ISSUE TITLE
[JS] Action Fallback card doesn't render

### ISSUE THREAD

**Issue by RebeccaAnne** [Microsoft/AdaptiveCards#2773]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Issue

The [samples\v1.2\Elements\ActionFallback.json](https://github.com/Microsoft/AdaptiveCards/blob/master/samples/v1.2/Elements/ActionFallback.json) card does not render on the JS visualizer. (Change the card version to 1.0 as the renderer rejects cards labeled 1.2) The card returns the message "The card could not be rendered. It is either malformed or uses features not supported by this host." This card renders properly on UWP.

![image](https://user-images.githubusercontent.com/9091833/56838361-8cb77e80-6832-11e9-8c18-58506361762f.png)

**Comment by dclaux** [comment]
Ah, known bug that I had lost track of. Will address.
