### ISSUE TITLE
[iOS] Inline Action not rendering image button on iOS 10.0

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#2774]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Version of SDK

master

# Issue

Using the Input.Text.InlineAction.json payload gives this result where the image buttons are not displayed

![Screen Shot 2019-04-26 at 2 56 41 PM](https://user-images.githubusercontent.com/35784165/56838634-88d82c00-6833-11e9-82a9-9fc9d34a4633.png)

**Comment by nesalang** [comment]
it doesn't work on iOS 10.0.

**Comment by jonmill** [comment]
iOS10 is not supported anymore
