### ISSUE TITLE
[JS] Fallback issues on DeepFallback test card

### ISSUE THREAD

**Issue by RebeccaAnne** [Microsoft/AdaptiveCards#2775]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* JavaScript

# Issue

The card [DeepFallback.json](https://github.com/Microsoft/AdaptiveCards/blob/master/samples/Tests/DeepFallback.json) doesn't render correctly. A "Graph" element in a deeply nested Container->Container->ColumnSet->Column doesn't cause the top level parent container to execute its fallback. 

Expected result [UWP]:
![image](https://user-images.githubusercontent.com/9091833/56838704-de143d80-6833-11e9-9345-6a936107a6e0.png)

Actual result [JS]:
![image](https://user-images.githubusercontent.com/9091833/56838713-e9ffff80-6833-11e9-9f98-012039470531.png)

**Comment by shalinijoshi19** [comment]
@dclaux is this still coming in for 1.2?

**Comment by paulcam206** [comment]
@shalinijoshi19 -- looks like the bug wasn't referenced correctly in the PR, so this bug didn't get autoclosed...
