### ISSUE TITLE
[.NET] ActionSet ShowCard

### ISSUE THREAD

**Issue by nesalang** [microsoft/AdaptiveCards#2777]
# Platform

* .NET WPF

# Version of SDK
1.2

# Issue
Json used: ActionSet.json.
When ShowCard buttons are pressed (there are two), the rendered ShowCard appears at the same position making them overlapping each other.
![Capture](https://user-images.githubusercontent.com/4112696/56841995-2e949680-6846-11e9-8461-5c17bdd51d4b.PNG)

UWP
![Capture](https://user-images.githubusercontent.com/4112696/56841991-1755a900-6846-11e9-92b8-a081dc13d001.PNG)

**Comment by shalinijoshi19** [comment]
@nesalang please do include screenshots if you can to clearly indicate expected and observe behavior. Also  does this behave OK on other platforms?

**Comment by shalinijoshi19** [comment]
@almedina-ms can you please pick this up for load balancing if @nesalang hasnt started work on it. thanks!
