### ISSUE TITLE
[UWP] RichTextBlock is not a valid type

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#2778]
# Platform

* UWP

# Version of SDK

master

# Issue

I get this warning when running the visualizer with the RichTextBlock.json payload

![image](https://user-images.githubusercontent.com/35784165/56839117-f2593a00-6835-11e9-9f2f-8ddf46a5d7d2.png)

**Comment by RebeccaAnne** [comment]
This is because the visualizer validates cards against the schema which has not been updated.

**Comment by shalinijoshi19** [comment]
Looks like this *could* be fixed once #2407 is fixed

**Comment by shalinijoshi19** [comment]
Resolving as dup of # #2407
