### ISSUE TITLE
[iOS] Media not hiding properly and imageSet not showing or hiding properly

### ISSUE THREAD

**Issue by almedina-ms** [Microsoft/AdaptiveCards#2781]
# Platform

* iOS

# Version of SDK

master

# Issue

When running the ToggleVisibility.AllElements.json the media element should be not visible at the start and when clicking the Toggle button, the element below the fastest should be an ImageSet but it's not appearing (when clicking the button again, there's extra space at the bottom, below the not properly hidden media)

![Screen Shot 2019-04-29 at 1 44 04 PM](https://user-images.githubusercontent.com/35784165/56925695-e616ec00-6a84-11e9-8d8b-d705a5b2a51f.png)

![Screen Shot 2019-04-29 at 1 44 39 PM](https://user-images.githubusercontent.com/35784165/56925726-f6c76200-6a84-11e9-8669-e14b7cfdb0f2.png)

**Comment by shalinijoshi19** [comment]
@almedina-ms can we actually include images/snapshots that makes it easier to visualize what is not rendering correctly ?

**Comment by shalinijoshi19** [comment]
@nesalang assigning to you for fixing
