### ISSUE TITLE
[iOS] ColumnSet.AllElements.Stretch.ToggleVisibility.json card is not rendering

### ISSUE THREAD

**Issue by almedina-ms** [Microsoft/AdaptiveCards#2783]
# Platform

* iOS

# Version of SDK

master

# Issue

The card is not rendering at all, all the other cards render but this one

**Comment by nesalang** [comment]
i'm closing this since it was due to parsing failure.

**Comment by almedina-ms** [comment]
The problem is with the json file, the json contains an extra ',' that makes all renderers not being able to parse the json file

**Comment by shalinijoshi19** [comment]
Have we fixed the actual card with the bad json?

**Comment by shalinijoshi19** [comment]
Also do the renderers provide an actionable message upon this parsing failure to help troubleshoot things a bit?

**Comment by RebeccaAnne** [comment]
Reopening to track fixing the broken sample file.
