### ISSUE TITLE
[Android] ActionSet ShowCard

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#2784]
# Platform

* Android

# Issue

Json Used: ActionSet.json

ShowCards rendered at the bottom of the card and in the middle of the card have different margins and alignment
![Screen Shot 2019-04-26 at 5 03 29 PM](https://user-images.githubusercontent.com/4112696/56841891-4586b900-6845-11e9-8350-5b779bdaa6dc.png)

UWP:
![Capture](https://user-images.githubusercontent.com/4112696/56841985-fb520780-6845-11e9-80c5-5d98d56e3230.PNG)

**Comment by shalinijoshi19** [comment]
@nesalang can you be more precise about where the issue is at in your opinion? (highlights in the images in teh bug description around what is expected and what you observe as inaccurate for eg would be helpful getting everybody on the same page) Marking investigate for now thanks!

**Comment by jonmill** [comment]
Not something we'll be getting to fixing anytime soon
