### ISSUE TITLE
[Designer] Attempting to use a json with version 1.2 results in an error

### ISSUE THREAD

**Issue by shalinijoshi19** [Microsoft/AdaptiveCards#2786]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* JavaScript

# Version of SDK
master (https://adaptivecards-ci.azurewebsites.net/designer/) 

# Issue

Pasting in this JSON is causing the designer to complain about the max version it supports:

![image](https://user-images.githubusercontent.com/20822397/56841988-10c73180-6846-11e9-98dd-d0a4097a1bb3.png)

**Comment by dclaux** [comment]
Renderer current version hasn't yet been updated to 1.2. This PR fixes that: https://github.com/Microsoft/AdaptiveCards/pull/2771
