### ISSUE TITLE
Version handling inconsistency

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#2788]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

# Issue

What format is accepted for versions is not consistent across platforms. On shared model platforms (UWP, iOS, Android) we accept versions of the forms 1, 1.2, 1.2.3, or 1.2.3.4 using the following regex: ^([\d]+)(?:\.([\d]+))?(?:\.([\d]+))?(?:\.([\d]+))?$

Javascript does not support the version "1".

Both Javascript and .NET **do** accept versions with anything past the initial two decimals, such as 1.2.3.4.5.6.7.8.9 or 1.1.elephant.

**Comment by shalinijoshi19** [comment]
@andrewleader assigning to you

**Comment by andrewleader** [comment]
Good catch. Probably an existing inconsistency, added the label and we can look at all inconsistencies at some point
