### ISSUE TITLE
Warnings should be logged when fallback is performed

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#2790]
When element fallback is performed, a warning should be logged for the renderer to consume.

**Comment by paulcam206** [comment]
Fixes still needed for iOS and Android

**Comment by shalinijoshi19** [comment]
@paulcam206 assuming you are tacklng this for iOS + Android as well?

**Comment by paulcam206** [comment]
@shalinijoshi19 -- yes. I hope to have something in PR today :)

**Comment by paulcam206** [comment]
iOS doesn't currently have warnings, so no work to be done there.
