### ISSUE TITLE
[Designer] Background image spec changes in 1.2

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#2796]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

Designer fix of #2794

**Comment by dclaux** [comment]
Already fixed. Can't put my finger on the commit/PR though.

**Comment by andrewleader** [comment]
Oh @dclaux this is for the spec changes we just decided on (rename `stretch` to `cover`, rename `mode` to `fillMode`). I assume those aren't implemented yet? :P

**Comment by dclaux** [comment]
I know. It's already done.
