### ISSUE TITLE
[iOS] Background image spec changes in 1.2

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2799]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

iOS fix of #2794

**Comment by shalinijoshi19** [comment]
@nesalang assigning the iOS implementation to you for this one for load balancing

**Comment by shalinijoshi19** [comment]
@nesalang FYI :) . Have you had a chance to start on this at all?  tx
