### ISSUE TITLE
[TS] Background image spec changes in 1.2

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#2800]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

TS fix of #2794

**Comment by dclaux** [comment]
Already fixed. Can't put my finger on the commit/PR though.

**Comment by andrewleader** [comment]
Oh @dclaux this is for the spec changes we just decided on (rename stretch to cover, rename mode to fillMode, etc). I assume those aren't implemented yet? :P
