### ISSUE TITLE
[UWP] Background image spec changes in 1.2

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2801]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

UWP fix of #2794

**Comment by shalinijoshi19** [comment]
@paulcam206, assigning this one to you.

**Comment by shalinijoshi19** [comment]
@almedina might be easier if you just picked this up as well (assuming @paulcam206 hasnt already started wrking on this)

**Comment by shalinijoshi19** [comment]
@paulcam206 load balancing on to you! thanks

**Comment by shalinijoshi19** [comment]
@Paulcam206 i think this one is going to be a big one that we should look into if @RebeccaAnne hasnt already started looking into it; Can you pick it up please?
