### ISSUE TITLE
[JS] input date max and in min absent in generated input tag

### ISSUE THREAD

**Issue by adalfa** [microsoft/AdaptiveCards#2807]
What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Author or host

author to webchat

# Version of SDK
adaptivecards npm 1.1.3
.

# Issue
we are developing a bot that is using a webchat, the adaptivecards with type input.Date and min and max attributes are  rendered without min and max. 

```js
const AdaptiveCards = require("adaptivecards");

const jsdomInstance = new (require('jsdom')).JSDOM();
global.document = jsdomInstance.window.document;
global.window = jsdomInstance.window;
global.HTMLElement = jsdomInstance.window.HTMLElement;

var card = {
  "type": "AdaptiveCard",
  "body": [
      {
          "type": "Input.Date",
          "id": "date",
          "value": "2019-04-30",
          "min": "2019-04-23",
          "max": "2019-05-07"
      }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.1"
};

// Create an AdaptiveCard instance
var adaptiveCard = new AdaptiveCards.AdaptiveCard();

// Parse the card payload
adaptiveCard.parse(card);
const renderedCard = adaptiveCard.render();

console.log(renderedCard.outerHTML);
```

**Output**

```html
<div class="ac-container" style="display: flex; flex-direction: column; justify-content: flex-start; background-color: rgb(255, 255, 255); box-sizing: border-box; flex: 0 0 auto; padding: 20px 20px 20px 20px;" tabindex="0">
    <input type="date" class="ac-input ac-dateInput" style="width: 100%; box-sizing: border-box; flex: 0 0 auto;">
</div>
```

I would recommend opening a new issue in the [AdaptiveCards Repo](https://github.com/microsoft/AdaptiveCards).

_Originally posted by @tdurnford in https://github.com/Microsoft/BotFramework-WebChat/issues/1942#issuecomment-488049755_

**Comment by matthidinger** [comment]
Thank you for reporting! @dclaux can you take a look?

**Comment by dclaux** [comment]
The JS renderer doesn't even support min and max on Input.Date, nor on Input.Time. I have no recollection of when these were introduced for that matter.

I'll add support.

**Comment by MouadhDos** [comment]
have same issue , the min and max Date properties not rendered in Teams

**Comment by jonmill** [comment]
This should be fixed in the latest builds; if not, please re-open and we'll engage. Thanks!
