### ISSUE TITLE
[UWP] Image.BackgroundColor.json cuts off image when rendered at fixed height.

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#2808]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Issue

The Image.BackgroundColor.json test file cuts off the image when rendered at fixed height. I believe the WholeItemsPanel should be ensuring that only whole items are displayed:

![image](https://user-images.githubusercontent.com/9091833/57025978-7bcd8b00-6bed-11e9-9d49-d232ef0dc74e.png)

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
