### ISSUE TITLE
[UWP] Background images frame differently with custom image renderer

### ISSUE THREAD

**Issue by nimercer** [microsoft/AdaptiveCards#2809]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* UWP

# Author or host
Host

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...
1.2 Beta

# Issue
When using the adaptive card image renderer with a background image (mode: stretch), the background image is framed incorrectly. (Not fitting to the size of its boundary).
When a custom renderer is added which does not do any manipulation of the image, just calls the underlying renderer, the issue is fixed despite no extra code added.

eg.
        public UIElement Render(IAdaptiveCardElement element, AdaptiveRenderContext context, AdaptiveRenderArgs renderArgs)
        {
            var baseRenderer = new AdaptiveImageRenderer();
            return baseRenderer.Render(element, context, renderArgs);
        }

Background Image before custom renderer:
![image](https://user-images.githubusercontent.com/48482128/57026801-8eb67e80-6c32-11e9-991a-21fe771c3a5e.png)

After custom renderer added:
![image](https://user-images.githubusercontent.com/48482128/57027054-421f7300-6c33-11e9-8c1f-efc17d61d9f1.png)

**Comment by barryptak** [comment]
The original issue that Nicola is referring to, but which goes away when using a custom renderer is this one: #2697

**Comment by shalinijoshi19** [comment]
At this point moving it out of 1.2 for fixing post RTM. @RebeccaAnne FYI

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
