### ISSUE TITLE
Ensure ToggleVisibility interacts with bleed correctly

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#2812]
<table>
<tr>
<th>Release</th>
<th>Renderer status</th>
<th>Tasks status</th>
</tr>
<tr>
<td>Backlog
<td>🔄 .NET (#2816)<br/>🔄 Android (#2817)<br/>🔄 iOS (#2818)<br/>✔️ TS (#2819)<br/>🔄 UWP (#2820)</td>
<td>🔄 Shared (#2814)<br/>✔️ Designer (#2815)</td>
</tr>
</table>

Splitting the bleed issue out from #2600 (which now tracks issues of separators only)

Does setting the framework element's visibility trigger a re-layout of the card to make sure that bleeding elements bleed correctly? For instance, take the following payload:
```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "id": "title",
            "text": "This is a TextBlock at the top of the card",
            "wrap": true
        },
        {
            "type": "Container",
            "style": "emphasis",
            "bleed": true,
            "items": [
                {
                    "type": "TextBlock",
                    "text": "This is a bleeding container",
                    "size": "extraLarge"
                },
                {
                    "type": "ActionSet",
                    "actions": [
                        {
                            "type": "Action.ToggleVisibility",
                            "title": "Click me",
                            "targetElements": [
                                "title"
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
```

Initially it renders like this:
![image](https://user-images.githubusercontent.com/1334689/54856676-e15a5d80-4cb8-11e9-9e60-a5bf1d8e9484.png)

Once the button is clicked, it should look like this:
![image](https://user-images.githubusercontent.com/1334689/54856692-efa87980-4cb8-11e9-9a56-63623d3d0c2b.png)

# Auto-generated task status

- [ ] Shared
- [x] Designer
- [ ] .NET
- [ ] Android
- [ ] iOS
- [x] TS
- [ ] UWP

**Comment by RebeccaAnne** [comment]
Due to a constraint in the current design (#2678), this isn't going to make it into 1.2. Moving to the backlog.

**Comment by paulcam206** [comment]
Not currently under consideration, but will reactivate should we decide to pursue.
