### ISSUE TITLE
[Shared] Ensure ToggleVisibility interacts with bleed correctly

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2814]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

Shared fix of #2812

**Comment by shalinijoshi19** [comment]
@RebeccaAnne do we want to tackle this as a bug still ? Also 1.3?

**Comment by RebeccaAnne** [comment]
This doesn't apply to the shared model.
