### ISSUE TITLE
[UWP] Container background image doesn't stretch as expected

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#2841]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Issue

The below card doesn't render correctly. The background image should be stretched across the container.

Correct Behavior [TS]:
![image](https://user-images.githubusercontent.com/9091833/57166110-fcd38080-6dad-11e9-83b2-907e44548b35.png)

Actual Behavior [UWP]:
![image](https://user-images.githubusercontent.com/9091833/57166080-df061b80-6dad-11e9-9124-6143bfe6c54c.png)

Json:
```
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.2",
	"body": [
		{
			"type": "Container",
			"backgroundImage": "https://picsum.photos/60/60?image=101",
			"items": [
				{
					"type": "TextBlock",
					"text": "Container 1 - Text 1 - Stretch"
				},
				{
					"type": "TextBlock",
					"text": "Container 1 - Text 2 - Stretch"
				},
				{
					"type": "TextBlock",
					"text": "Container 1 - Text 3 - Stretch"
				}
			]
		}
	]
}
```

**Comment by shalinijoshi19** [comment]
@RebeccaAnne FYI - I've moved this out to our backlog for tackling post-1.2 RTM. Let me know if this is already fixed as a result of recent fixes in stretch + background images (_if so go ahead close it out_) or if you think this should be a release blocker

**Comment by jonmill** [comment]
This should be fixed in the latest builds; please re-open if this is not the case and we'll engage. Thanks!
