### ISSUE TITLE
[UWP][iOS] \r Creates new lines

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#2842]
# Platform

* iOS
* UWP

# Issue

\r characters are adding new lines in UWP while in iOS the new lines are not generated

Json payload:
* samples\v1.2\Elements\Column.BackgroundImage.json

![image](https://user-images.githubusercontent.com/35784165/57166120-0957d900-6dae-11e9-8be7-e45435de30a9.png)

![Screen Shot 2019-05-03 at 2 18 47 PM](https://user-images.githubusercontent.com/35784165/57166240-65226200-6dae-11e9-82c4-78a7da4f5017.png)

**Comment by RebeccaAnne** [comment]
Javascript and .Net also don't respect \r or \n or \r\n.

**Comment by shalinijoshi19** [comment]
@almedina-ms FYI i've moved this out to our backlog outside of 1.2.  tx

**Comment by shalinijoshi19** [comment]
@paulcam206 out of curiosity, where did we land with this discussion again and \r \n handling?
