### ISSUE TITLE
Inconsistency In Size When Rendering DataURI Image

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#2843]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android
* iOS

# Issue
DataURI images renders differently on the different renderers.
Between Android & iOS, image is rendered much smaller in Android.

**Android**
![Screenshot_1556918239](https://user-images.githubusercontent.com/4112696/57166369-d104ca80-6dae-11e9-99be-9b50684bdd57.png)

**iOS**
![Simulator Screen Shot - iPhone 6s - 2019-05-03 at 14 05 04](https://user-images.githubusercontent.com/4112696/57166377-dd892300-6dae-11e9-9258-82fec3fe9e7e.png)

**Comment by andrewleader** [comment]
It looks like iOS is definitely wrong (it shouldn't be increasing its size (upscaling) unless its size was actually set to something bigger. It should be displaying at its original image pixel size.
