### ISSUE TITLE
DataURI Image As Background Image has Inconsistent Rendering 

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#2845]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS
* Android
* UWP
* .NET WPF

# Issue
Data URI Image is rendered differently across the platforms.

**iOS**
![Simulator Screen Shot - iPhone 6s - 2019-05-03 at 14 04 21](https://user-images.githubusercontent.com/4112696/57166530-5f794c00-6daf-11e9-9c1e-2592d2585850.png)

**Android**
![Screenshot_1556918814](https://user-images.githubusercontent.com/4112696/57166656-b97a1180-6daf-11e9-91e5-413481600bc7.png)

**UWP**
![AdaptiveCard BackgroundImage](https://user-images.githubusercontent.com/4112696/57166770-107fe680-6db0-11e9-9f1b-7528afd94eab.PNG)

**.NET WPF**
![bacground](https://user-images.githubusercontent.com/4112696/57167631-4c687b00-6db3-11e9-8380-ff3445906ca8.PNG)

**Comment by RebeccaAnne** [comment]
I believe the .NET WPF image is the correct behavior.

**Comment by andrewleader** [comment]
Correct, .NET WPF is the correct rendering (that's also what JavaScript does). [The spec](https://github.com/microsoft/AdaptiveCards/issues/477) says that for the default background image fill mode (cover), `The background image covers the entire width of the container. Its aspect ratio is preserved. Content may be clipped if the aspect ratio of the image doesn't match the aspect ratio of the container.`
