### ISSUE TITLE
Data URI Portrait Mode

### ISSUE THREAD

**Issue by nesalang** [microsoft/AdaptiveCards#2846]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Issue

The size of same DataURI image changes depending on which image style is used.

**InPerson**
![image data uri inPerson](https://user-images.githubusercontent.com/4112696/57166893-71a7ba00-6db0-11e9-84da-4d220604b738.PNG)

![image data uri](https://user-images.githubusercontent.com/4112696/57166902-81270300-6db0-11e9-85bb-99ad0c9c498a.PNG)

**Comment by shalinijoshi19** [comment]
@nesalang, can you update the bug description + title to actually indicate what you observe and what is expected behavior? RIght now it's unclear what the issue is.. thanks!
