### ISSUE TITLE
Images in an ImageSet require the "type" property

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#2848]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

# Issue

If the images in an imageset do not have "type":"Image" set on them, they do not render in shared model platforms or .NET. Javascript does render these payloads. The analogous case for columns in a columns set does render properly without requiring the type property to be set on the payload.

Sample payload:
``` 
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "ImageSet",
			"images": [
				{
					"url": "http://adaptivecards.io/content/cats/1.png"
				},
				{
					"url": "http://adaptivecards.io/content/cats/1.png"
				},
				{
					"url": "http://adaptivecards.io/content/cats/1.png"
				},
				{
					"url": "http://adaptivecards.io/content/cats/1.png"
				},
				{
					"url": "http://adaptivecards.io/content/cats/1.png"
				},
				{
					"url": "http://adaptivecards.io/content/cats/1.png"
				}
			]
		}
	]
}
```

**Comment by shalinijoshi19** [comment]
@RebeccaAnne FYI moving this out to backlog for post 1.2 fixing.
