### ISSUE TITLE
[TS] RichTextBlock missing date rendering

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#2850]
See rich text block [sample card](https://github.com/Microsoft/AdaptiveCards/blob/master/samples/v1.2/Elements/RichTextBlock.json). Typescript renderer lacks date parsing:

![image](https://user-images.githubusercontent.com/16614499/57167700-833e9100-6db3-11e9-8851-bafe45914aaf.png)

Looks correct in UWP and WPF.

**Comment by dclaux** [comment]
Fixed here: https://github.com/microsoft/AdaptiveCards/pull/2905
