### ISSUE TITLE
[iOS][UWP] Showcard behavior inconsistency

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#2851]
# Platform

* iOS
* UWP

# Issue

When clicking on show card actions, UWP and iOS have different behaviours (other platforms may also differ). In the case of UWP, multiple show cards can be visible at the same time, while in iOS only the last shown card is kept visible

Json payload:
* samples\v1.2\Elements\ActionSet.json

UWP
![image](https://user-images.githubusercontent.com/35784165/57167702-85085480-6db3-11e9-8734-56b1371ff808.png)

iOS

![Screen Shot 2019-05-03 at 3 00 45 PM](https://user-images.githubusercontent.com/35784165/57167905-56d74480-6db4-11e9-9d22-9861040df2cf.png)

![Screen Shot 2019-05-03 at 3 00 54 PM](https://user-images.githubusercontent.com/35784165/57167908-59d23500-6db4-11e9-8630-9a472efc983d.png)

**Comment by RebeccaAnne** [comment]
UWP only shows a single show card per action set, but will allow multiple show cards in different action sets.

**Comment by shalinijoshi19** [comment]
@andrewleader / @matthidinger thoughts on this one? This looks to be a spec issue where it's not clear what the right showcard behavior should be

**Comment by andrewleader** [comment]
Agreed, spec is ambiguous about this.

I think Becky's implementation is correct - each ActionSet should function independently. So using a ShowCard on one ActionSet shouldn't affect the ShowCards on a different action set.

@matthidinger @dclaux what's your opinion?

**Comment by dclaux** [comment]
In JS it's always been like Becky describes, e.g. there can be one expanded card per ActionSet (including the actions on the card itself) all expanded at the same time. The is the desired model.

**Comment by shalinijoshi19** [comment]
@andrewleader can we update the spec at this point given we've come to a conclusion around desired behavior? @RebeccaAnne what platform needs fixing here still? iOS? If so go ahead reassign though this will not make the ship blocker bar at this point.

**Comment by andrewleader** [comment]
👍 updated [the spec](https://github.com/microsoft/AdaptiveCards/issues/877)! Thanks!

**Comment by VikrantSingh01** [comment]
How is it on Android and J.S version of SDK ?  CC- @shalinijoshi19

**Comment by jonmill** [comment]
This should be fixed in the latest builds; please re-open if this is not the case and we'll engage. Thanks!
