### ISSUE TITLE
[TS] RichTextBlock missing monospace rendering

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#2852]
See rich text block [sample card](https://github.com/Microsoft/AdaptiveCards/blob/master/samples/v1.2/Elements/RichTextBlock.json). Typescript renderer lacks monospace rendering:

![image](https://user-images.githubusercontent.com/16614499/57167805-f2b48080-6db3-11e9-867f-5615db1d6330.png)

Looks like it's not a CSS issue:
![image](https://user-images.githubusercontent.com/16614499/57167823-03fd8d00-6db4-11e9-8124-606d152b7e37.png)

Looks correct on WPF and UWP.

**Comment by dclaux** [comment]
It's the test payload that is incorrect. Decision was made to rename `fontStyle` into `fontFamily` which the JS renderer has already implemented.
