### ISSUE TITLE
[UWP minHeight] Height of the AdaptiveCard doesnt seem to go below a certain minimum(100px?)  despite configuring it to be smaller

### ISSUE THREAD

**Issue by shalinijoshi19** [microsoft/AdaptiveCards#2853]
# Platform

* UWP

# Version of SDK
UWP visualizer app off of the store (which i believe is compiled off of master nightly) 

# Issue

1. Tried this sample AdaptiveCard-minHeight.json which seems to reduce to accomodate the minHeight say in JS or WPF but not in UWP it seems; I can go for eg down to 10px in WPF but UWP seems to stay at 100px or so.. 
```
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.2",
	"minHeight": "100px",
	"body": [
		{
			"type": "TextBlock",
			"wrap": true,
			"text": "This card has a minHeight of 100px"
		}
	]
}
```

UWP:

![minHeightQuirks](https://user-images.githubusercontent.com/20822397/57167469-bfbdbd00-6db2-11e9-9c9e-efc3b2a7f812.gif)

WPF:

![minHeightQuirks-WPF](https://user-images.githubusercontent.com/20822397/57167768-c993f000-6db3-11e9-967b-e9e1ab766640.gif)

JS:
![minHeightQuirks-JS](https://user-images.githubusercontent.com/20822397/57167881-3dce9380-6db4-11e9-89af-435ea597fe38.gif)

**Comment by almedina-ms** [comment]
This fails for parsing 
"minHeight": "200
px"
That's why you are not seeing the change of height

![image](https://user-images.githubusercontent.com/35784165/57168346-488a2800-6db6-11e9-8a86-cd59e06a9cc3.png)

**Comment by shalinijoshi19** [comment]
@almedina-ms can you investigate with the json (now added to the bug) ? thanks

**Comment by almedina-ms** [comment]
This works in master

![MinHeightUWP](https://user-images.githubusercontent.com/35784165/57474150-5290a880-7246-11e9-9d21-8c0cf893e118.gif)

**Comment by almedina-ms** [comment]
minHeight won't go below the height of the content that is rendered in the card, as for the behaviour of minimum height any height that is greater than the minimum is valid

**Comment by shalinijoshi19** [comment]
Got it! Thanks for looking into this @almedina-ms
