### ISSUE TITLE
[UWP] Inconsistent warning about inlines type

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#2855]
In UWP, this card is an error:

```json
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.2",
	"body": [
		{
			"type": "RichTextBlock",
			"inlines": ""
		}
	]
}
```

however, this card is considered fine (note value of `inlines`):

```json
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.2",
	"body": [
		{
			"type": "RichTextBlock",
			"inlines": {}
		}
	]
}
```

Both cards are incorrect, as `inlines` has to be an array type.

Note that JS incorrectly allows both of these payloads (and even doesn't require `"inlines"`, although note that JS also doesn't require `"text"` on TextBlock, so that's related to a whole separate issue)

**Comment by shalinijoshi19** [comment]
Good to have; Looks like an easy fix if we can absorb it; @RebeccaAnne do we have clarity around addressing this?

**Comment by shalinijoshi19** [comment]
Moving it out of 1.2 given there are still pending
