### ISSUE TITLE
JSON schema for adaptive cards is slightly wrong

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/AdaptiveCards#2857]
# Issue

The schema for adaptive cards provides wrong intellisense.

![Screenshot](https://user-images.githubusercontent.com/23744935/57198262-0eb15100-6f71-11e9-87bb-a820591d2251.png)

**Current behaviour**: 
It shows `Must be "Action.Submit"`

**Expected behaviour**:
It shows `Must be "Action.OpenUrl"`

**Comment by andrewleader** [comment]
Hey @SimonSiefke, thanks for reporting this! We've fixed this in our latest version of the Adaptive Card schema for 1.2: https://adaptivecards.io/schemas/1.2.0/adaptive-card.json
