### ISSUE TITLE
Gif are not animating on android sdk.

### ISSUE THREAD

**Issue by desaibijon** [microsoft/AdaptiveCards#2863]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards?

Host rendering cards on Android devices/
# Version of SDK

Android v1.1

# Issue

Gif images are not animating on android and the same images animate on web.

**Comment by andrewleader** [comment]
Hey @desaibijon, thanks for reporting this issue! We'll track GIF support with issue #2871 since it's also missing on WPF and we'll have to track this as a cohesive feature. Please subscribe and follow along there.
