### ISSUE TITLE
iOS SDK docs for rendering cards are outdated

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2882]
The iOS docs for rendering cards and using the SDK are outdated.

https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/ios/render-a-card

Class names have changed, it doesn't compile, etc.

**Comment by shalinijoshi19** [comment]
@andrewleader do we typically track these documentation issues as release todo's? In other words, I should be tracking these bugs as part of the overall 1.2 triage board yes?

**Comment by andrewleader** [comment]
I guess it depends, if it's just general doc improvements, then probably not part of the release? But if it's documentation changes as a result of 1.2, then probably should be tracked. I think this one makes sense as part of 1.2 since our renderer doc is out-of-date for 1.2!
