### ISSUE TITLE
[.NET][HTML] Font style not respected as multiple are set

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#2889]
# Platform

* .NET HTML

# Issue

AdaptiveCard is not respecting the font because the font is being filled with more than one value

In the image we can see that the <p> tag has multiple fonts assigned to it but the actual font doesn't change, if only one font is used, then the change is visible

![image](https://user-images.githubusercontent.com/35784165/57557839-6284b700-7330-11e9-859f-fa7e082001d7.png)

![image](https://user-images.githubusercontent.com/35784165/57557913-a1b30800-7330-11e9-8eb6-2690e223f9ef.png)

**Comment by shalinijoshi19** [comment]
FYI @almedina-ms / @RebeccaAnne moving this out of 1.2 at this point.
