### ISSUE TITLE
[WPF] Visualizer doesn't have a scrollbar for cards

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#2890]
The WPF visualizer should have scrollbars so that we can look at cards that are too tall to display within the window:

![image](https://user-images.githubusercontent.com/16614499/57558186-9b715b80-7331-11e9-873f-c995916e4030.png)

**Comment by RebeccaAnne** [comment]
This is fixed in the PR for .NET Toggle visibility #2767
