### ISSUE TITLE
[.NET] Per action type styling for action sentiments

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#2891]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF

# Issue

In .NET sentiment styles are specific to the type of action. You can (and must if you want all buttons to behave the same) set the "Adaptive.Action.Submit.Positive" style and the "Adaptive.Action.OpenUrl.Positive" style separately. In UWP, for example, you set a single "Adaptive.Action.Positive" style that applies to all action types. Per the spec, the latter appears to be the correct behavior:

From #861:
"A renderer must output the appropriate styling name on the action, so that hosts can natively style the buttons. For example, a default button might get a style name of Action, but an emphasized button might get a style name of Action.Positive (or however the native platform styling naming convention works)"

**Comment by shalinijoshi19** [comment]
@RebeccaAnne, good catch. FYI I've approved for fix but moved it out of 1.2 for post release fixing
