### ISSUE TITLE
[.NET][HTML] DeepFallback card failed to render

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#2893]
# Platform

* .NET HTML

# Issue

[DeepFallback.json](https://github.com/microsoft/AdaptiveCards/blob/master/samples/Tests/DeepFallback.json) card fails to render

![image](https://user-images.githubusercontent.com/35784165/57558501-c0b29980-7332-11e9-8a76-da30a03aea81.png)

**Comment by RebeccaAnne** [comment]
[ActionFallback.json](https://github.com/microsoft/AdaptiveCards/blob/master/samples/v1.2/Elements/ActionFallback.json) also fails.

**Comment by shalinijoshi19** [comment]
This doesnt look like a shipblocker to me; We can always fix it as a patch release - @paulcam206 / @RebeccaAnne / @almedina-ms let me know if you guys think it should be a release blocker.

**Comment by jonmill** [comment]
.NET HTML is deprecated
