### ISSUE TITLE
.NET WPF Choice Set Wrap

### ISSUE THREAD

**Issue by nesalang** [microsoft/AdaptiveCards#2894]
# Platform

* .NET WPF

# Issue
Wrap doesn't work for ChoiceSet with compact style and single select as seen in the capture
<img width="282" alt="capture1" src="https://user-images.githubusercontent.com/4112696/57558634-4df5ee00-7333-11e9-9dcb-310097ab9096.PNG">

https://github.com/microsoft/AdaptiveCards/blob/master/samples/Tests/SearchResults.json

**Comment by shalinijoshi19** [comment]
@nesalang is this a 1.2 feature and is this a release blocker at this point?

**Comment by RebeccaAnne** [comment]
Wrapping on choice sets is a 1.2 feature.

**Comment by shalinijoshi19** [comment]
thanks! @RebeccaAnne / @nesalang FYI I've approved this for fixing but moved it out of 1.2 at this point.
