### ISSUE TITLE
ToggleVisibility on a non-existent ID

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#2896]
If a card author includes a non-existent element `id` in their `Action.ToggleVisibility` action, should we throw a warning?

**Comment by shalinijoshi19** [comment]
Good to resolve the spec issue part of this in 1.2; @andrewleader FYI. Seems reasonable to me to throw

**Comment by paulcam206** [comment]
We need to make sure we consider the fallback case as well. It's possible that an author might have one nonexistent `id` and one existent `id` specified. I don't think we should fail the parse, but a warning is probably the right call...

**Comment by shalinijoshi19** [comment]
FYI @paulcam206 and @andrewleader I've moved this out of 1.2 at this point.
