### ISSUE TITLE
[Shared] Support long data URIs

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2898]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

Shared implementation of #2881

**Comment by almedina-ms** [comment]
do we have a test case for a card where this fails or to test against?

**Comment by andrewleader** [comment]
I believe the Shared model already supports long data URIs (it just parses as a string, it doesn't validate it's a URI or anything as far as I remember?) I think it's the native platforms that then convert it into the native platform URI objects (like UWP converts it into a Uri object) that then fails.
