### ISSUE TITLE
HTML - input field values not passed to onExecuteAction

### ISSUE THREAD

**Issue by danmarshall** [microsoft/AdaptiveCards#290]
Try this in the visualizer, fill out the fields and click submit
```
{
    "$schema": "https://microsoft.github.io/AdaptiveCards/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "Input.Text",
            "id":"firstName",
            "placeholder": "What is your first name?"
        },
        {
            "type": "Input.Text",
            "id":"lastName",
            "placeholder": "What is your last name?"
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Action.Submit",
            "data": {
                "x" : 13
            }            
        }
    ]
}
```

**Comment by RamyaViswanthan** [comment]
OnExecuteAction handler on the Javascript is not firing. Here is the code snippet.


// Set the adaptive card's event handlers. onExecuteAction is invoked
// whenever an action is clicked in the card
adaptiveCard.onExecuteAction = function(action) { alert("Ow!"); };

**Comment by dclaux** [comment]
@RamyaViswanthan I am not able to reproduce this. What browser are you using?

**Comment by RamyaViswanthan** [comment]
Hello Mr. David,

 

First and foremost, thank you for your prompt response. I am Raja, a developer in Mrs. Ramya’s engineering team. Please allow me to present the artifact. The attached HTML technology demonstrator file will allow you to reproduce the issue. We use Google Chrome as our enterprise browser.

 

By the way, the code snippet on this MSDN article (https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/javascript/render-a-card) is not working as advertised. Case in point, we had to tweak it as follows to make it work. Just sharing to make you aware of the issue. Having a comprehensive sample code on the website would help newbies like us embrace this technology with fewer struggles. If your team can expand the literature in MSDN – for instance; Javascript objects, methods, functions, Javascript files to include, etc – then I believe more teams will adopt this awesome technology. Just a suggestion as a well-wisher.

 

We look forward to crossing this small hurdle and get on with your BETA for Data Binding.

 



 

Regards
Raja
Outsourcing Projects Management Team
Profiniti Systems

Visit us online  <http://www.profinitisystems.com/> www.profinitisystems.com
Catalyze your business with our IT services

**Comment by RamyaViswanthan** [comment]
[Sample File.zip](https://github.com/Microsoft/AdaptiveCards/files/2981146/Sample.File.zip)

**Comment by RamyaViswanthan** [comment]
![MSND Code Snippet - Needing correction](https://user-images.githubusercontent.com/48655826/54574692-50853880-49bf-11e9-874a-8f6333ea7767.jpg)

**Comment by RamyaViswanthan** [comment]
![MSND Code Snippet - Needing correction](https://user-images.githubusercontent.com/48655826/54575368-da360580-49c1-11e9-841f-19045430db74.jpg)

**Comment by RamyaViswanthan** [comment]
![Google Chrome Version](https://user-images.githubusercontent.com/48655826/54575374-e0c47d00-49c1-11e9-9102-c7ba5618aa30.PNG)

**Comment by dclaux** [comment]
@RamyaViswanthan your code cannot work, and the "tweak" you are using is the culprit. You are grabbing the `innerHTML` of the rendered card and using it to set the `innerHTML` of your div. By doing that, you lose any event that was set in the `renderedCard` element because events are not serialized.

You need to do follow the sample code and simply pass the `renderedCard` instance to the call to `appendChild` on your **cardHolder** div. I updated your code that way and now it works just fine:

```js
// Create an AdaptiveCard instance
var adaptiveCard = new AdaptiveCards.AdaptiveCard();

// Set its hostConfig property unless you want to use the default Host Config
// Host Config defines the style and behavior of a card
adaptiveCard.hostConfig = new AdaptiveCards.HostConfig({
    fontFamily: "Segoe UI, Helvetica Neue, sans-serif"
    // More host config options
});

// Parse the card payload
if (typeof adaptiveCard != "undefined") {
    adaptiveCard.parse(card);
}
else {
    alert("Object is undefined");
}

// Render the card to an HTML element:
var renderedCard = adaptiveCard.render();

// Set the adaptive card's event handlers. onExecuteAction is invoked
// whenever an action is clicked in the card
adaptiveCard.onExecuteAction = function (action, e) { alert("Ow!"); };

// And finally insert it somewhere in your page:
document.getElementById("cardHolder").appendChild(renderedCard);
```

**Comment by RamyaViswanthan** [comment]
Awesome, Thanks! Much appreciate your timely response.

**Comment by remimichael** [comment]
I am rendering Adaptive Cards  following instructions as in **https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/javascript/render-a-card)**. However web chat UI is not displaying the images as per the  card structure upon rendering first time.. Only upon refresh of the web chat in browser, the images are loaded and clickable. Appreciate any pointers to resolve the issue.

![image](https://user-images.githubusercontent.com/24701260/97005283-db46f580-155b-11eb-9465-6a61cb5d740f.png)
 
![image](https://user-images.githubusercontent.com/24701260/97005600-4b557b80-155c-11eb-83cd-bcdfaebcff02.png)

Card JSON:
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "Image",
            "url": "http://adaptivecards.io/content/adaptive-card-50.png"
        },
        {
            "type": "TextBlock",
            "text": "Hello **Adaptive Cards!**"
        }
    ],
    "actions": [
        {
            "type": "Action.OpenUrl",
            "title": "Learn more",
            "url": "http://adaptivecards.io"
        },
        {
            "type": "Action.OpenUrl",
            "title": "GitHub",
            "url": "http://github.com/Microsoft/AdaptiveCards"
        }
    ]
}
