### ISSUE TITLE
[1.2 API review] Rename TextBlock's fontStyle to fontType

### ISSUE THREAD

**Issue by shalinijoshi19** [microsoft/AdaptiveCards#2906]
<table>
<tr>
<th>Release</th>
<th>Renderer status</th>
<th>Tasks status</th>
</tr>
<tr>
<td>1.2
<td>🔄 .NET (#2909)<br/>🔄 Android (#2910)<br/>🔄 iOS (#2911)<br/>🔄 TS (#2912)<br/>🔄 UWP (#2913)</td>
<td>🔄 Shared (#2907)<br/>🔄 Designer (#2908)</td>
</tr>
</table>

# Platform

* .NET HTML
* .NET WPF
* Android
* iOS
* UWP

If you're an author, who are you sending cards to?

# Version of SDK

Latest master

# Issue

Rename Textblock.fontStyle property to TextBlock.fontType across our renderers

Rename fontStyles property in HostConfig to fontTypes

# Auto-generated task status

- [ ] Shared
- [ ] Designer
- [ ] .NET
- [ ] Android
- [ ] iOS
- [ ] TS
- [ ] UWP

**Comment by shalinijoshi19** [comment]
@RebeccaAnne / @andrewleader FYI this is the root bug tracking the renames.

**Comment by RebeccaAnne** [comment]
All sub-issues have been resolved
