### ISSUE TITLE
[.NET] [1.2 API review] Rename TextBlock's fontStyle to fontType

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2909]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

.NET fix of #2906

**Comment by shalinijoshi19** [comment]
Blocked on merging PR microsoft/AdaptiveCards#2933 due to iOS breaks. All the rest of the changes would need to come in together -- @RebeccaAnne can you drive getting these merged in to master? tx
