### ISSUE TITLE
[UWP] Renderer solution no longer compiles in VS

### ISSUE THREAD

**Issue by shalinijoshi19** [microsoft/AdaptiveCards#2922]
# Platform

* UWP

# Version of SDK

master

# Issue

Compiling the .sln gives errors in teh mdmerge custom build step in teh UWP renderer:

<snip>
>XamlBuilder.cpp
2>   Creating library C:\AdaptiveCards\source\uwp\x64\Debug\AdaptiveCardRenderer\AdaptiveCards.Rendering.Uwp.lib and object C:\AdaptiveCards\source\uwp\x64\Debug\AdaptiveCardRenderer\AdaptiveCards.Rendering.Uwp.exp
2>AdaptiveCardRenderer.vcxproj -> C:\AdaptiveCards\source\uwp\x64\Debug\AdaptiveCardRenderer\AdaptiveCards.Rendering.Uwp.dll
2>Performing Custom Build Step
2>MDMERGE : error MDM2018: The type "AdaptiveCards.Rendering.Uwp.TileControl" defined in file C:\AdaptiveCards\source\uwp\x64\Debug\AdaptiveCardRenderer\AdaptiveCards.Rendering.Uwp.winmd was referenced but could not be found.
2>MDMERGE : error MDM2018: The type "AdaptiveCards.Rendering.Uwp.WholeItemsPanel" defined in file C:\AdaptiveCards\source\uwp\x64\Debug\AdaptiveCardRenderer\AdaptiveCards.Rendering.Uwp.winmd was referenced but could not be found.
2>Microsoft(R) Metadata Merge Utility Version 10.0.47.
2>

</snip>

**Comment by shalinijoshi19** [comment]
@paulcam206, could you help get to the bottom of this since it's blocking alberto's PR's as well? Thanks!

**Comment by paulcam206** [comment]
> @paulcam206, could you help get to the bottom of this since it's blocking alberto's PR's as well? Thanks!

Sure thing! :)
