### ISSUE TITLE
Lacking full RFC3339 support for dates

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2925]
Someone pointed out that we aren’t fully supporting RFC3339. Specifically, we don’t support fractional seconds and leap seconds (and possibly more, those were the examples they pointed out)

Fractional seconds
1985-04-12T23:20:50.52Z

Leap seconds
1990-12-31T23:59:60Z

   This represents the leap second inserted at the end of 1990.

**Comment by paulcam206** [comment]
Not currently under consideration, but will reactivate should we decide to pursue.
