### ISSUE TITLE
[TS] Provide card render context on custom CardElement

### ISSUE THREAD

**Issue by PhoenixHe-TSP** [microsoft/AdaptiveCards#2929]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Author or host

Author

# Version of SDK

1.2.0-beta1

# Issue

I want to extend adaptive card with custom control, and I want to collect render context on rendering card element. However currently the AdaptiveCard.elementTypeRegistry is a singleton and not suitable for holding rendering context. What I want to do here is to inject a card related object which could be referenced by custom card element.

Maybe the elementTypeRegistry could be card independent? Or maybe expose some API for passing through context?

**Comment by dclaux** [comment]
@NullMDR if I understand you correctly, you want:
1. A non-global registry, so you can parse different cards with different registered elements/actions
2. A way to pass custom data to element instances at parse time

Is that correct?
1. I plan to address this, you are not the only one who's been asking for it and I need it personally for the designer. It will likely be a property on HostConfig though
2. This will also likely happen, however it will most likely be a breaking change, so I've refrained from doing it so far

**Comment by NullMDR** [comment]
@dclaux 

> A non-global registry, so you can parse different cards with different registered elements/actions

This one is just enough for me, like this:

js`
let context = 42;
card.elementTypeRegistry.registerType("SomeType", () => new CustomElement(context));
`

> A way to pass custom data to element instances at parse time

IMO it's not necessary, but if it would enable more scenarios it would be great to keep it in backlog.

**Comment by dclaux** [comment]
Not quite sure how the above can be useful. As the custom element is instantiated via the registry when a payload is being parsed, the same context will be used for each and every CustomElement instance. At that point a global context variable would achieve the same result.

Maybe I'm missing your point, but a concrete use case with pseudo code sample would be helpful.
