### ISSUE TITLE
[iOS][BugBash] Vertical Stretch Doesn't Work with Toggle Visibility

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#2939]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Issue
When toggle visibility is toggled, vertical stretch still active.

https://github.com/microsoft/AdaptiveCards/blob/master/samples/Tests/ColumnSet.AllElements.Stretch.ToggleVisibility.json
**JSON 1**

![Screen Shot 2019-05-17 at 1 53 11 PM](https://user-images.githubusercontent.com/4112696/57955598-2959c300-78ab-11e9-9475-00a1c78abd68.png)
**Screen Shot 1**

**Comment by shalinijoshi19** [comment]
@nesalang FYI that i've moved this out from the 1.2 release into backlog for post 1.2 fixing. Thanks!
