### ISSUE TITLE
[JS] Compact choice sets don't respect wrap

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#2940]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Issue

Compact choice sets with wrap set aren't respected by the javascript renderer:

Card json:
```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Input.ChoiceSet",
            "id": "ChoiceSet",
            "value": "Choice 1",
            "placeholder": "Placeholder text",
            "choices": [
                {
                    "title": "Choice 1 is a very long choice with lots of details that definitely will need to wrap. ",
                    "value": "Choice 1"
                },
                {
                    "title": "Choice 2",
                    "value": "Choice 2"
                }
            ],
            "wrap": true
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

Result (Designer):
![image](https://user-images.githubusercontent.com/9091833/57955728-78075d00-78ab-11e9-991c-16562e24ee7f.png)

Expected result (UWP):
![image](https://user-images.githubusercontent.com/9091833/57955743-85bce280-78ab-11e9-9ea2-71c37ca41957.png)

**Comment by shalinijoshi19** [comment]
@dclaux / @RebeccaAnne  FYI - not something I'd block 1.2 RTM for so moving this to Backlog though approving it for fixing.

**Comment by dclaux** [comment]
Won't fix. The wrap behavior isn't supported by the standard HTML select input, and I would have to include a custom combo box implementation which would increase the size of the library for very little value add.
