### ISSUE TITLE
[iOS][BugBash] Vertical Stretch Doesn't Work Properly

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#2942]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* iOS

# Issue

https://github.com/microsoft/AdaptiveCards/blob/master/samples/Tests/ColumnSet.AllElements.Stretch.ToggleVisibility.json
**JSON**

![Screenshot_1558127825](https://user-images.githubusercontent.com/4112696/57956745-ec8fcb00-78ae-11e9-9b98-417280c8aed0.png)
**Figure 1**

![Simulator Screen Shot - iPhone 6s - 2019-05-17 at 14 17 38](https://user-images.githubusercontent.com/4112696/57956753-f3b6d900-78ae-11e9-92c3-a5fa814c60a4.png)
**Figure 2**

There is vertical stretch in Figure 2 where it shouldn't be as in Figure 1. 

Although not shown in the screen capture, input items in 2nd ColumnSet do not respect the alignment. i.e. it has spaces but not aligned properly or aligned differently compared to Android.

**Comment by shalinijoshi19** [comment]
@RebeccaAnne / @nesalang  FYI - moving this out of 1.2 RTM for post-release fixing.
