### ISSUE TITLE
[Android][BugBash] Bleed Issue

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#2944]
# Platform

* Android

# Issue
https://github.com/microsoft/AdaptiveCards/blob/master/samples/Tests/Bleed.Comprehensive.json
**JSON 1**

![Screenshot_1558129688](https://user-images.githubusercontent.com/4112696/57958093-75106a80-78b3-11e9-888a-0c002c84db43.png)
** Figure 1**

![cortana-skills Tests Bleed Comprehensive](https://user-images.githubusercontent.com/4112696/57958118-88233a80-78b3-11e9-9bd5-f478fc640369.png)
** Figure 2**

![Screenshot_1558129682](https://user-images.githubusercontent.com/4112696/57958112-7fcaff80-78b3-11e9-99fc-906e1bc7d9fc.png)
** Figure 3**

Issue 1:
First Y and N in Figure 1 don't stretch top and bottom.

Issue 2:

There are no padding in the text in the center of Figure 3 compared to Figure 2

**Comment by shalinijoshi19** [comment]
@nesalang thanks for finding! Moving this out of 1.2 for post-release fixing.

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.
