### ISSUE TITLE
Data URI behavior for invalid images

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#2946]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML
* .NET WPF
* JavaScript
* UWP

# Issue

Behavior is inconsistent across platforms when encountering an invalid data URI. When opening the [Image.DataUri.InvalidChars.json](https://github.com/microsoft/AdaptiveCards/blob/master/samples/Tests/Image.DataUri.InvalidChars.json) card, some renderers show error images and some just drop it:

UWP:
![image](https://user-images.githubusercontent.com/9091833/57958614-3a0f3680-78b5-11e9-8705-d1a5b014ae97.png)

.NET WPF:
![image](https://user-images.githubusercontent.com/9091833/57958634-45faf880-78b5-11e9-8a29-d115f97ed60c.png)

.NET HTML:
![image](https://user-images.githubusercontent.com/9091833/57958650-57dc9b80-78b5-11e9-9af4-b336f611ec39.png)

Designer:
![image](https://user-images.githubusercontent.com/9091833/57958672-6dea5c00-78b5-11e9-8f34-5cdf1b398551.png)

**Comment by shalinijoshi19** [comment]
@RebeccaAnne good catch. I've approved for fixing. Looks like this would need to be addressed on all platforms? Feel free to use this as a parent/Epic and file separate bugs for tracking per-platform fixes. At this point though moved out of 1.2

**Comment by jonmill** [comment]
Closing as by-design - the designer should have the frowny faces for visual purposes
