### ISSUE TITLE
[Android][BugBash] Background Image FillMode Issue

### ISSUE THREAD

**Issue by nesalang** [microsoft/AdaptiveCards#2947]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android
# Issue

https://github.com/microsoft/AdaptiveCards/blob/master/samples/v1.2/Elements/AdaptiveCard.BackgroundImage.FillMode.json
**JSON 1**

https://github.com/microsoft/AdaptiveCards/blob/master/samples/v1.2/Elements/AdaptiveCard.BackgroundImage.FillMode.Repeat.json
**JSON 2**

![Screenshot_1558131374](https://user-images.githubusercontent.com/4112696/57959023-b7877680-78b6-11e9-9e89-aeb6de211874.png)
**Figure 1**

JSON1 & 2 doesn't show background images as in Figure 2.

**Comment by shalinijoshi19** [comment]
@nesalang good find! Moving this out of 1.2 at this point though for fixing post-RTM
