### ISSUE TITLE
"Input value substitution" does not work anymore on Action.OpenUrl in Teams

### ISSUE THREAD

**Issue by simonrivas** [microsoft/AdaptiveCards#2948]
# Platform

I am using :
* Microsoft Teams v1.2.00.8864 (64 bits) on Windows 10
* Microsoft Teams v1.0.73 on iOS 12.2

# Author or host

I use the Logic Apps connector for Teams to send a custom adaptive card to a channel as the Flow bot connector.

# Issue

The input value substitution does not work with an Action.OpenUrl action :
* on Windows, clicking the action button has simply no effect
* on iOS, the input value placeholders are not replaced by the actual values of the inputs; instead, the brackets are replaced with %7B and %7D

**This did work very well until the 9th of may** (maybe the 10th, not 100% sure), and then it didn't.

Please find below a sample adaptive card that I am using :

`{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "ColumnSet",
                    "columns": [
                        {
                            "type": "Column",
                            "items": [
                                {
                                    "type": "Image",
                                    "style": "Person",
                                    "url": "http://i0.wp.com/media.steampowered.com/steamcommunity/public/images/avatars/a6/a6dd35235d6c439b956baf59c291883e3330239f_full.jpg",
                                    "size": "Medium"
                                }
                            ],
                            "width": "auto"
                        },
                        {
                            "type": "Column",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "weight": "Bolder",
                                    "text": "Feeling stressed?",
                                    "wrap": true
                                },
                                {
                                    "type": "TextBlock",
                                    "id": "txtDate",
                                    "spacing": "None",
                                    "text": "Created {{DATE(2017-02-14T06:08:39Z,SHORT)}}",
                                    "isSubtle": true,
                                    "wrap": true
                                }
                            ],
                            "width": "stretch"
                        }
                    ]
                }
            ]
        },
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "separator": true,
                    "weight": "Bolder",
                    "text": "Your mood:"
                },
                {
                    "type": "Input.Text",
                    "id": "txtMot",
                    "title": "A word",
                    "value": "RAS",
                    "placeholder": "A little word?"
                }
            ]
        }
    ],
    "actions": [
        {
			"type": "Action.OpenUrl",
			"title": "Submit",
			"url":"https://www.google.com?mood={{txtMot.value}}"
		}
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}`

**Comment by dclaux** [comment]
@simonrivas input value substitution is a concept that only works with Action.Http which is only available for Actionable Messages in Outlook. I don't think it's ever worked in an Action.OpenUrl, regardless of the client. I am very surprised you say it has worked before.

**Comment by simonrivas** [comment]
Well, that is indeed consistent with what I had read in the documentation, but out of pure curiosity I tried it maybe 2 months ago with Action.OpenUrl and it worked fine. I have a history of hundreds of cards so I am a 100% sure of that.

So, where can I go from here? Is there some plan of supporting this feature (again 😄) in the near future?
If not, how can I tacle my need to allow users to input some pieces of information and then process them? Do I have to build a fully fledged bot in Teams to do that?

**Comment by simonrivas** [comment]
UPDATE : I have re-read the documentation and discovered I could use Actionnable Message in Teams as well (thanks for the hint) (more information here for those interested : [Post an actionable message card to an Office 365 group](https://docs.microsoft.com/fr-fr/outlook/actionable-messages/send-via-connectors) ). 
I was under the impression it was deprecated but actually it isn't for Teams, as stated in teh first paragraph here : [Legacy actionable message card reference](https://docs.microsoft.com/fr-fr/outlook/actionable-messages/message-card-reference)

It doesn't look as nice as an Adaptive Card (in my opinion) but at least it does the job.
Again, thanks for the help!

**Comment by shishir-sumant** [comment]
> @simonrivas input value substitution is a concept that only works with Action.Http which is only available for Actionable Messages in Outlook. I don't think it's ever worked in an Action.OpenUrl, regardless of the client. I am very surprised you say it has worked before.

@dclaux I am trying to send some user data in Http Post action of a message card in teams. It works fine on desktop but is not substituting the value when sent from my android device. Do you have any suggestions? Would be of great help!

action:
  {
          "@@type": "ActionCard",
          "actions": [
            {
              "@@type": "HttpPOST",
              "body": "{\"ID\":\"@{body('Parse_JSON_2')?['Id']}\",\"FirstName\":\"@{body('Parse_JSON_2')?['FirstName']}\",\"LastName\":\"@{body('Parse_JSON_2')?['LastName']}\",\"DOB\":\"@{body('Parse_JSON_2')?['DOB']}\",\"Comment\":\"{{Comment.value}}\",\"Options\" : \"{{OptionsSelected.value}}\",\"CO\" : \"{{CO.value}}\",\"AE\" : \"{{AE.value}}\"}",

              "name": "Submit Edit",
              "target": "https://......."
            }
          ],
          "inputs": [
            {
              "@@type": "TextInput",
              "id": "Comment",
              "isMultiline": true,
              "isRequired": true,
              "title": "Comment"
            },
            {
              "@@type": "TextInput",
              "id": "CO",
              "title": "CO"
            },
            {
              "@type": "TextInput",
              "id": "AE",
              "title": "AE"
            }
          ]
