### ISSUE TITLE
Incorrect method name serText in TextBlock (should be setText)

### ISSUE THREAD

**Issue by moreJs** [microsoft/AdaptiveCards#2949]
# Platform
* JavaScript

# host

# Version of SDK

1.2.0-beta1

# Issue

https://github.com/microsoft/AdaptiveCards/blob/master/source/nodejs/adaptivecards/src/card-elements.ts#L1147

``` js
    protected serText(value: string) {
        super.setText(value);

        this._processedText = null;
    }
```

the function name 'serText' is right ? it seems that  'setText'.

**Comment by dclaux** [comment]
Thanks for reporting, fix is here: https://github.com/microsoft/AdaptiveCards/pull/2966
