### ISSUE TITLE
[TS] Fallback id collision detection doesn't align with shared model implementation

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#2951]
The TypeScript renderer performs `id` collision detection *after* fallback has been performed, meaning that some possible collisions may not be detected at time of authoring. To implement would require a breaking change:

> Nice! At this point, I will not be implementing this algorithm in the JS renderer because it would require slightly changing the overall way payloads are parsed, and would most likely introduce a breaking change.

_Originally posted by @dclaux in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMTczNDYzMTkwOnYy/pull_request_review_threads/discussion_

**Comment by paulcam206** [comment]
@dclaux - can you characterize the breaking change that would be required here?

(@shalinijoshi19 for visibility)

**Comment by dclaux** [comment]
I would likely have to change the signature of the `parse()` method on CardElement and Action, which would break existing code. There might be a way to do it without the breaking change, but I need to think more about it.
