### ISSUE TITLE
Schema says that Version property isn't required

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2958]
The schema says that version isn't required, yet as far as I'm aware it's certainly required

![image](https://user-images.githubusercontent.com/13246069/58123109-f3c11c80-7bbf-11e9-8a84-8e2e7c1244fd.png)

Paul, maybe you can fix this as part of the 1.2 updates?

**Comment by andrewleader** [comment]
Ah maybe it's an artifact of version not being required within Action.ShowCard? And that's not able to be represented in the schema file? The description could at least be updated to say at the beginning, `Required for top-level cards` or something, to make it more clear.

**Comment by paulcam206** [comment]
this will be covered as part of my documentation changes

**Comment by andrewleader** [comment]
Fixed in master with our 1.2 updates
