### ISSUE TITLE
Sentiment should be renamed to style

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#2968]
Per email thread, the action `sentiment` property should be renamed to `style`.

**Comment by shalinijoshi19** [comment]
@paulcam206 / @andrewleader why is this a specbug? I understand this needs to be changed in code yes?  Also do we want to create platform-specific workitems? @RebeccaAnne + @nesalang FYI this rename might be coming to you guys respectively

**Comment by andrewleader** [comment]
Maybe Paul assigned the SpecBug label thinking that's how we track bugs that are a result of spec bugs? Idk 😵 We have lots of labels 😛

Yes, this needs to be changed in code.

Platform-specific work items sound good to me if that's what you'd like! Up to the dev team :)

**Comment by paulcam206** [comment]
I added `SpecBug` because at the time I filed, there was still the outstanding question of whether we allow arbitrary styles. That seems resolved now on the email thread, but it needs to be documented in the spec (#861).

As it stands, the spec still calls for `style` to be an enum value rather than a string.

**Comment by shalinijoshi19** [comment]
Awesome! Great find @paulcam206 and thanks a ton @RebeccaAnne for being on top of this including getting the children spun up and assigned! Looks like this should land in 1.2 just fine.

**Comment by andrewleader** [comment]
The spec seems to be correct, it **should** be an enum. There's simply the option for hosts to extend support and add different values (which UWP added). That's a host-specific feature. From the authoring side, it still should be an enum for ease of authoring (if they're sending to a host that has a custom value, they'll need to do something different... same as if they're sending to a host that has a custom container style)

**Comment by paulcam206** [comment]
fair enough! 👍

**Comment by dclaux** [comment]
As part of https://github.com/microsoft/AdaptiveCards/pull/2981 I made the JS implementation extensible.
