### ISSUE TITLE
RTL support doesn't work in UWP

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#2969]
HP claimed that in the UWP renderer, when running on a full RTL machine (no other languages installed) and displaying a card with RTL content, it doesn't correctly invert the content, they had to do some special work to fix that.

We should test our renderer in RTL languages and check if we can repro this issue.

**Comment by achipa** [comment]
Linked to https://github.com/microsoft/AdaptiveCards/issues/2144

It's also unclear if the language field has any effect on RTL rendering (which only mentions date/time - but that makes no sense as it's a 2-char language field, and the date/time formats are defined by locale).

Note that properties like horizontalAlignment operate with values like "left" and "right", which are inherently ambiguous in a RTL context. I would recommend (also) supporting more directional terms to avoid confusion (like flexbox uses "start" and "end")..

**Comment by jonmill** [comment]
This should be fixed in the newest builds; if not, please re-open and we'll engage. Thanks!
