### ISSUE TITLE
[iOS] Default Font Has Changed

### ISSUE THREAD

**Issue by nesalang** [microsoft/AdaptiveCards#2982]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Issue

PR #2960 changed fallback font type.

**Comment by shalinijoshi19** [comment]
Thanks for catching @nesalang. Is this a breaking change? @andrewleader  fyi/thoughts?

**Comment by andrewleader** [comment]
Not a breaking change (our host config defaults are subject to change, hosts should provide their own host config).

As long as the new font looks good and is an improvement (or at least on par) and consistent with most iOS apps, I have no concerns!
