### ISSUE TITLE
Emit warnings when unknown container styles are encountered

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#2984]
Container styles are defined as strings. there are well-known styles (i.e. default, accent, emphasis, etc.), but arbitrary styles can be specified. When an unknown style is encountered (one that doesn't have an entry in the host config), a warning should be emitted.

**Comment by dclaux** [comment]
This is addressed in JS with this PR: https://github.com/microsoft/AdaptiveCards/pull/3508

**Comment by RebeccaAnne** [comment]
Dup of #2780
