### ISSUE TITLE
[BOT Web Chat v4] The Button Control renders as full width in BOT Chat Control?

### ISSUE THREAD

**Issue by vikramdadwal** [microsoft/AdaptiveCards#2985]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML
* JavaScript

# Author or host

I am Author

If you're an author, who are you sending cards to?: To Web Chat

# Version of SDK

Latest Nuget

# Issue

Issue is already logged in Stackoverflow:

https://stackoverflow.com/questions/56298444/action-button-renders-as-full-width-of-the-card

**Comment by jonmill** [comment]
Closed via resolution in StackOverflow
