### ISSUE TITLE
non-latin characters breaks markdown on UWP renderer

### ISSUE THREAD

**Issue by achipa** [microsoft/AdaptiveCards#2992]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Author or host

Author

# Version of SDK

Latest master (~1.2.0-beta1)

# Issue

Whitespace can break (valid) markdown styling when there are non-latin characters in the string.

For example, the following elements
```
{
	"type": "TextBlock",
	"text": "以前の製品のリンクで検索",
	"size": "large"
},
{
	"type": "TextBlock",
	"text": "**以前の製品のリンクで検索**",
	"size": "large"
},
{
	"type": "TextBlock",
	"text": "How about **以前の製品のリンクで検索**",
	"size": "large"
},
{
	"type": "TextBlock",
	"text": "How about **Search**",
	"size": "large"
},
{
	"type": "TextBlock",
	"text": "How about**以前の製品のリンクで検索**",
	"size": "large"
},
{
	"type": "TextBlock",
	"text": "It's OK!\rClick [以前の製品のリンクで検索](https://www.microsoft.com)\rClick [以前の製品のリンクで検索](https://www.microsoft.com)",
	"size": "large"
},
{
	"type": "TextBlock",
	"text": "1. Click [以前の製品のリンクで検索](https://www.microsoft.com)\r2. Click [以前の製品のリンクで検索](https://www.microsoft.com)",
	"size": "large"
},
{
	"type": "TextBlock",
	"text": "It's not OK!\r1. Click [以前の製品のリンクで検索](https://www.microsoft.com)\r2. Click [以前の製品のリンクで検索](https://www.microsoft.com)",
	"size": "large"
},

```
…when rendered in the UWP visualizer, becomes...

![image](https://user-images.githubusercontent.com/822934/58594344-9154c580-822a-11e9-81de-7c0cd888e6ff.png)

The only obvious difference I could notice is markdown failing if there was whitespace in front of it (for some reason, it does not manifest with latin/ASCII characters). The issue is not limited to bold (styling), hyperlinks and lists are susceptible, too. 

I did a quick check and the JS visualizer at adaptivecards.io DOES render these more to expectation:

![image](https://user-images.githubusercontent.com/822934/58581506-f26da080-820c-11e9-8b3e-ad20daa7324a.png)

**Comment by shalinijoshi19** [comment]
@paulcam206 can you please take a look at this? Thanks

**Comment by paulcam206** [comment]
@achipa -- thanks for this great bug! I ended up finding a few bugs in the vicinity of this :)
