### ISSUE TITLE
[.NET WPF] Separators appears at the bottom of spacing rather than centered

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#3005]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF

# Issue

.NET separators appear at the bottom of the spacing rather than centered in the spacing. In a card with "ExtraLarge" spacing between the text blocks it should look like this (UWP):

![image](https://user-images.githubusercontent.com/9091833/58735337-f507fb80-83ae-11e9-9b54-6b277323c027.png)

But instead looks like this (.NET WPF):
![image](https://user-images.githubusercontent.com/9091833/58735367-0e10ac80-83af-11e9-8d27-9904fce629f9.png)

```json
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "text": "New TextBlock"
        },
        {
            "type": "TextBlock",
            "spacing": "ExtraLarge",
            "separator": true,
            "text": "New TextBlock"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

**Comment by shalinijoshi19** [comment]
Looks like a candidate for fixing and addressing the inconsistency. @almedina-ms can you pick this up? Thanks!
