### ISSUE TITLE
[JS] Error on card with columnset, no columns, and a select action

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#3007]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Issue

A columnSet without columns but with a selectAction causes an error on JavaScript (using the [visualizer ](https://adaptivecards-ci.azurewebsites.net/visualizer/index.html?hostApp=Bot%20Framework%20WebChat) to verify). Removing the select action or adding columns causes the card to render successfully as a blank card.

```json
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "ColumnSet",
            "selectAction": {
                "type": "Action.OpenUrl",
                "url": "https://adaptivecards.io/schemas/adaptive-card.json"
            }
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

Result:
![image](https://user-images.githubusercontent.com/9091833/58736284-19190c00-83b2-11e9-9ba6-e9e1a599f0f9.png)

**Comment by dclaux** [comment]
Fix pending here: https://github.com/microsoft/AdaptiveCards/pull/3008
