### ISSUE TITLE
Open URL behavior when url not set

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#3011]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF
* JavaScript
* UWP

# Issue
The behavior of OpenURL is not consistent across renderers when the url is not set. 

- Javascript: Renders the card with a warning. Clicking the button works and has url undefined. 
- UWP: Fails to render the card with the error "Property is required but was found empty:  url"
- .NET: Renders the card, but then dereferences a null if you try to click on the button.

```json
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.OpenUrl",
                    "title": "Action.OpenUrl"
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

**Comment by shalinijoshi19** [comment]
@andrewleader / @RebeccaAnne what does that spec say about OpenURL behavior again? For sure .NET needs fixing (@almedina-ms FYI) but it almost feels like all 3 behaviors today are a bit too late? Is it not possible to detect this as part of input validation even before we get to the rendering stage? Thoughts?

**Comment by RebeccaAnne** [comment]
The schema says that url is required: https://adaptivecards.io/explorer/Action.OpenUrl.html

UWP (via the shared model) is failing at parse time.

**Comment by andrewleader** [comment]
Will be captured as part of #3154, which converges on a consistent behavior around missing required properties
