### ISSUE TITLE
[.NET HTML] Stretch height items are not hiding

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#3012]
# Platform

* .NET HTML

# Version of SDK

master

# Issue

Items with stretch height are not hiding making this card fail

https://github.com/microsoft/AdaptiveCards/blob/master/samples/Tests/ColumnSet.AllElements.Stretch.ToggleVisibility.json

**Comment by jonmill** [comment]
.NET HTML is deprecated
