### ISSUE TITLE
Height Feature 

### ISSUE THREAD

**Issue by utsavlathia** [microsoft/AdaptiveCards#3013]
The height option that is available in the visualizer does not exist in the documentation. Also it does not look like it is functioning.

**Comment by dclaux** [comment]
Can you post a card sample that illustrates height not functioning?

**Comment by andrewleader** [comment]
Hey @utsavlathia do you have more details to share on this issue? Specifically about what doesn't seem to be functioning?

We've updated the schema docs to include the `height` property, maybe that resolves it? Closing for now, re-open if there's still issues around docs not being clear or anything :)
