### ISSUE TITLE
[UWP] Long words don't wrap

### ISSUE THREAD

**Issue by choupete** [microsoft/AdaptiveCards#3014]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript
* UWP

# Issue

Really long words do not wrap on UWP, even when the "wrap" field is set to true. This problem is not present on JS.

```json
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "text": "WhenIWriteAReallyLongWordLikeThisOnUWPTextWrappingDoesntWork",
            "wrap": true
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```
Result:
![Annotation 2019-05-31 160712](https://user-images.githubusercontent.com/42462906/58739273-41a70300-83be-11e9-9c8e-cb4b2cd1db8c.png)
![Annotation 2019-05-31 160734](https://user-images.githubusercontent.com/42462906/58739274-41a70300-83be-11e9-95a5-94cdef75d320.png)

**Comment by shalinijoshi19** [comment]
@almedina-ms can you take a stab at this? Also please remember to check on iOS/android and the .NET platforms as well please? Thanks!

**Comment by almedina-ms** [comment]
@shalinijoshi19 all platforms do the same as UWP, should this be marked as a JS bug?

**Comment by dclaux** [comment]
The fact that all other renderers behave the same doesn't make them right :) The JS renderer was the first ever available and has always wrapped single words like this. What would card authors expect? The JS behavior IMO, which is why it was done like that in the first place.

**Comment by almedina-ms** [comment]
JS does the same, what's the inconsistency here?

![image](https://user-images.githubusercontent.com/35784165/61085502-44493f00-a3e5-11e9-96cf-c0f8a51685f7.png)

**Comment by almedina-ms** [comment]
Nevermind, got the issue now, UWP is the one that isn't wrapping

![image](https://user-images.githubusercontent.com/35784165/61085643-9ab67d80-a3e5-11e9-9509-2b943bf983de.png)
