### ISSUE TITLE
[JS][Android] Newlines not working in JS, Android in textblock

### ISSUE THREAD

**Issue by btam** [microsoft/AdaptiveCards#3016]
# Platform

* Android
* JavaScript

# Author or host

Author

# Version of SDK

Latest master

# Issue

Having newlines in a string results in expected behavior for the UWP renderer, but the JavaScript (Designer) renderer doesn't display the first newline.

So in **JavaScript** "First Line\nSecond Line" looks like

![image](https://user-images.githubusercontent.com/605509/58740359-e3315300-83c4-11e9-88d3-73dedac837d9.png)

And (still in **JavaScript**) "First Line\n\nSecond Line" looks like

![image](https://user-images.githubusercontent.com/605509/58740373-f7755000-83c4-11e9-942c-0a15c231581c.png)

In **Android** the newlines don't seem to work at all, so "First Line\n\nSecond Line" looks like

![image](https://user-images.githubusercontent.com/605509/58740320-8d5cab00-83c4-11e9-829e-296d73bba990.png)

**Comment by RebeccaAnne** [comment]
#3531

**Comment by jonmill** [comment]
Tracked by #1984
