### ISSUE TITLE
[Android] Target items can't be added to ToggleVisibility programatically

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#3027]
# Platform

* Android

# Version of SDK

master

# Issue

ToggleVisibility actions can't be added items through code, there are no addItem or other similar methods

**Comment by RebeccaAnne** [comment]
In UWP you can add targets by adding them to the AdaptiveToggleVisibility.TargetElements vector.

**Comment by almedina-ms** [comment]
Android has the same way to access to the target element list as UWP
