### ISSUE TITLE
Add underline support to RichTextBlock

### ISSUE THREAD

**Issue by dclaux** [microsoft/AdaptiveCards#3028]
# Problem
RichTextBlock is quite powerful, but lack the basic ability to underline text.

# Solution
Add an underline property to TextRun.

**Comment by matthidinger** [comment]
@andrewleader can you re-create through productboard

**Comment by andrewleader** [comment]
Closing as dupe of #3051 (productboard unfortunately doesn't let us link an existing issue, we have to create a new one :/ we've sent a feature request to them to allow linking to existing)
