### ISSUE TITLE
Column.width default value is inconsistent (auto on JS vs stretch on the rest)

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#3031]
# Version of SDK

1.2

# Issue

If a `Column` doesn't have `width` specified, it defaults to different things on each platform... See the rendering of the following card...

```json
{
  "type": "AdaptiveCard",
  "$schema": "https://raw.githubusercontent.com/microsoft/AdaptiveCards/8b0c89c286d4721f9c8a9d48587a49f126702131/schemas/adaptive-card-new.json",
  "version": "1.0",
  "body": [
      {
          "type": "Container",
          "style": "emphasis",
          "items": [
              {
                  "type": "ColumnSet",
                  "columns": [
                      {
                          "type": "Column",
                          "width": "stretch",
                          "items": [
                              {
                                  "type": "TextBlock",
                                  "text": "**EXPENSE APPROVAL**",
                                  "size": "large",
                                  "weight": "bolder"
                              }
                          ]
                      },
                      {
                          "type": "Column",
                          "items": [
                              {
                                  "type": "Image",
                                  "url": "https://filedepot.blob.core.windows.net/build/pending.png",
                                  "height": "30px",
                                  "altText": "Pending"
                              }
                          ]
                      }
                  ]
              }
          ]
      }
  ]
}
```

| JS | UWP, WPF, Android |
|---|---|
| ![image](https://user-images.githubusercontent.com/13246069/59070084-38121500-886e-11e9-90d5-ea9eea0af72f.png) | ![image](https://user-images.githubusercontent.com/13246069/59070026-08630d00-886e-11e9-9eaf-1cd544251114.png) |

WPF and UWP works correctly if you set `"width": "auto"` to the second column, so it's a problem with the default value

**Untested**

* iOS

**Comment by shalinijoshi19** [comment]
@almedina-ms assigning to you for follow up.

**Comment by andrewleader** [comment]
@shalinijoshi19 I don't think we know what the default value should be yet. We first need to pick a default (which there's no great answer to, but probably go with JS' default since most people probably test in the web designer)

We can discuss it with everyone at the beginning of the 1.3 planning meeting?

**Comment by shalinijoshi19** [comment]
@andrewleader / @almedina-ms can you guys drive arriving at a good default here? Thanks!

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.
