### ISSUE TITLE
Emphasis container inside emphasis container provides inconsistent results

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#3042]
Issue existed since 1.0

# UWP

The text is butted up to the edge without any padding, that's definitely wrong

![image](https://user-images.githubusercontent.com/13246069/59133377-aa492f00-892c-11e9-8390-dd3129e6963a.png)

# JS

JS correctly has padding, should this be the behavior? Or should emphasis be ignored since it's already inside an emphasis container? Note that you have to change the host config so that emphasis is semi-transparent to see any difference

![image](https://user-images.githubusercontent.com/13246069/59133456-ec727080-892c-11e9-99ae-624f165b112c.png)

# WPF

Text is also butted up to the edge just like UWP

![image](https://user-images.githubusercontent.com/13246069/59133471-014f0400-892d-11e9-82d0-8d33bdd75345.png)

```json
{
	"type": "AdaptiveCard",
	"body": [
		{
			"type": "Container",
			"items": [
				{
					"type": "Container",
					"style": "emphasis",
					"items": [
						{
							"type": "ColumnSet",
							"columns": [
								{
									"type": "Column",
									"style": "emphasis",
									"items": [
										{
											"type": "TextBlock",
											"horizontalAlignment": "Left",
											"size": "Small",
											"text": "Confirmation Number"
										},
										{
											"type": "TextBlock",
											"id": "confirmationNumber",
											"horizontalAlignment": "Left",
											"spacing": "Small",
											"size": "Small",
											"text": "0987654321"
										}
									],
									"width": "stretch"
								},
								{
									"type": "Column",
									"style": "emphasis",
									"items": [
										{
											"type": "TextBlock",
											"horizontalAlignment": "Right",
											"size": "Small",
											"text": "PIN"
										},
										{
											"type": "TextBlock",
											"id": "pinNumber",
											"horizontalAlignment": "Right",
											"spacing": "Small",
											"size": "Small",
											"text": "1234"
										}
									],
									"width": "stretch"
								}
							]
						}
					]
				}
			]
		}
	],
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"version": "1.0"
}
```

**Comment by shalinijoshi19** [comment]
I do like the padding approach visually. @matthidinger / @RebeccaAnne / @almedina-ms / @nesalang / @paulcam206 thoughts? Is taking the JS approach forward do-able on the other platforms?

**Comment by shalinijoshi19** [comment]
@andrewleader assigning to you until we can address the spec ambiguity if that's alright.
