### ISSUE TITLE
How to change fontFamily of Action Button ?

### ISSUE THREAD

**Issue by nileshprajapati007444** [microsoft/AdaptiveCards#3049]
I want to change font family of Action Button. Is it possible ?

I have tried to change css in theme-config.js file at below lines:
const defaultThemeConfig = {
    android: {
            borderRadius: 10,
            backgroundColor: "#c35353",
            color: "#FFFFFF",
            textTransform: undefined, 
            
            fontFamily: 'Courier New',
        },
}

I can change backgroundColor. But can't change fontFamily.

Please help.

**Comment by andrewleader** [comment]
Hi @nileshprajapati007444, can you explain a bit about where you're using Adaptive Cards? Are you using WebChat?

**Comment by nileshprajapati007444** [comment]
@andrewleader I am using adaptive card in React native mobile app. I have displayed Action Button. I want to change font family which i am using in my app. But i can not change. I have added css of fontFamily, but not affected.

**Comment by andrewleader** [comment]
Ah, so you're using the React Native community renderer? @BalajiR or @vivekvijayakrishnan can you help with this issue?

**Comment by nileshprajapati007444** [comment]
@andrewleader yes i am using React Native community renderer.

@BalajiR @vivekvijayakrishnan 

Please help me.

**Comment by BalajiR** [comment]
@nileshprajapati007444, Sorry for the late reply. Somehow missed this from notifications.
As of current version of RN renderer, we have added only [limited properties](https://github.com/Imaginea/AdaptiveCards/wiki/Extensibility---Theme-Config) via THEME CONFIG as an experiment.

Upcoming updates to the RN renderer will cover more properties for sure.

**Comment by nileshprajapati007444** [comment]
@BalajiR 

It is ok. No problem.
