### ISSUE TITLE
Underline support in text runs

### ISSUE THREAD

**Issue by productboard-ac** [microsoft/AdaptiveCards#3051]
<table>
<tr>
<th>Release</th>
<th>Renderer status</th>
<th>Tasks status</th>
</tr>
<tr>
<td>1.3
<td>✔️ .NET (#3215)<br/>✔️ Android (#3216)<br/>✔️ iOS (#3217)<br/>🔄 TS (#3218)<br/>✔️ UWP (#3219)</td>
<td>✔️ Shared (#3220)<br/>🔄 Designer (#3221)</td>
</tr>
</table>

# Summary

Add an underline property to TextRun

# Requirements

- Be able to underline a text run within a RichTextBlock

# Schema/spec

<https://github.com/microsoft/AdaptiveCards/pull/3086/files>

# Proposed changes

Add an `underline` boolean property to `TextRun`. Note that depending on #3071 this property might also be added to `TextBlock`.

# Example

![image](https://user-images.githubusercontent.com/13246069/59635384-fa32ad80-9105-11e9-88d5-107203cd912f.png)

```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "This is the first inline. "
                },
                {
                    "type": "TextRun",
                    "text": "We support underlining",
                    "underline": true
                },
                ", ",
                {
                    "type": "TextRun",
                    "color": "Good",
                    "text": "colors, "
                },
                {
                    "type": "TextRun",
                    "text": "both regular and subtle...",
                    "isSubtle": true
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2"
}
```

# Host Config

N/A

# Down-level impact

**Minimal**. The underline won't appear, but text still will appear.

# Host burden

N/A

# Auto-generated task status

- [x] Shared
- [ ] Designer
- [x] .NET
- [x] Android
- [x] iOS
- [ ] TS
- [x] UWP

**Comment by productboard-ac** [comment]
Link to feature: https://adaptivecards-test.productboard.com/feature-board/planning/features/2323172

**Comment by andrewleader** [comment]
# 7/12/2019 review

* Will there ever be double underline?
  * Consensus is we can support that in future if need be, by upgrading the property to also be an enum so you could specify double

Proposal and spec approved, although the TextBlock aspect is dependent on the other convergence proposal
