### ISSUE TITLE
Thumbs up/down input control

### ISSUE THREAD

**Issue by productboard-ac** [microsoft/AdaptiveCards#3055]
Maybe something like this? Need to gather more requirements

<p></p>

![](https://productboard-files.s3.amazonaws.com/production/attachments/3bee2e1de6bf3212f47d81119e6953d51fefb083924473f4d5341d3906091dfa/image.png)

<p></p>

**Comment by productboard-ac** [comment]
Link to feature: https://adaptivecards.productboard.com/feature-board/planning/features/1711066

**Comment by shalinijoshi19** [comment]
> Link to feature: https://adaptivecards.productboard.com/feature-board/planning/features/1711066

This isnt accessbile to anybody but our team. What's the point of embedding this link here? @andrewleader ?

**Comment by andrewleader** [comment]
I don't put those links, the productboard tool does. Ideally it would say "Internal link" or something (similar to how the codeflow tool puts a link completely internal to Microsoft but it at least clarifies that it's meant for internal).

But it makes it easier for our team to trace back to productboard (same concept as the codeflow tool). I have no control over this anyways though.
