### ISSUE TITLE
`ac-image` in Internet Explorer 11 stretches from max-width 100% but does not adjust height

### ISSUE THREAD

**Issue by corinagum** [microsoft/AdaptiveCards#3056]
# Platform
* JavaScript

# Author or host
Web Chat, related to https://github.com/microsoft/BotFramework-WebChat/issues/1944

# Version of SDK
1.2

# Issue
(card json is provided at the bottom)

On Chrome, an Adaptive Card renders as expected (with Web Chat host config):
![image](https://user-images.githubusercontent.com/14900841/59457078-8f633880-8dcc-11e9-9eca-8d99ebeca879.png)

However, when shown in Internet Explorer 11, the image is stretched and also has an invisible overflow that causes the card to display as much larger than expected:

![image](https://user-images.githubusercontent.com/14900841/59457150-ba4d8c80-8dcc-11e9-9a22-93808b0c0f01.png)

Note that the image is stretched and the card no longer appears immediately above the input. 

When inspecting the image, unchecking max-width: 100% shows the image in full size, showing that height is unadjusted when max-width is applied, making the image larger than the card's original borders.

![image](https://user-images.githubusercontent.com/14900841/59457277-fbde3780-8dcc-11e9-9b73-ec7e8c200e23.png)

This is reproduced on the Adaptive Card visualizer:

![image](https://user-images.githubusercontent.com/14900841/59457501-5f686500-8dcd-11e9-9156-b7ac1604eeac.png)

Below is the json for the card in this example:
```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "TextBlock",
                            "text": "Airports"
                        },
                        {
                            "type": "TextBlock",
                            "spacing": "None",
                            "size": "ExtraLarge",
                            "weight": "Bolder",
                            "text": "Sea-Tac"
                        },
                        {
                            "type": "TextBlock",
                            "spacing": "None",
                            "text": "3 ★★★☆☆ (856) · $$$$",
                            "isSubtle": true
                        },
                        {
                            "type": "TextBlock",
                            "size": "Small",
                            "text": "**Steve G. said** \"Another day, another airport.\"",
                            "wrap": true
                        }
                    ],
                    "width": 2
                },
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "Image",
                            "url": "https://upload.wikimedia.org/wikipedia/commons/2/23/Deltalax_%28cropped%29.jpg"
                        }
                    ],
                    "width": 1
                }
            ]
        }
    ],
    "actions": [
        {
            "type": "Action.OpenUrl",
            "title": "More Info",
            "url": "https://www.portseattle.org/sea-tac"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0",
    "speak": "three of five stars, 856 reviews, Extremely Expensive. Steve G said, \"Another day, another airport\""
}
```

**Comment by andrewleader** [comment]
Great bug find and report @corinagum! What's the priority of this issue?

**Comment by corinagum** [comment]
For Web Chat this is low priority. :)  I went ahead and edited our broken card with a different (smaller) image to avoid causing this issue.

**Comment by shalinijoshi19** [comment]
@dclaux could you help take a first stab ? What i am unclear about is why the browser would come into the picture if the JS library is the same ? Also do we want to support IE11 at this point? @andrewleader / @matthidinger thoughts?

**Comment by jonmill** [comment]
IE11 is not a supported browser
