### ISSUE TITLE
Feedback Controls Telemetry

### ISSUE THREAD

**Issue by productboard-ac** [microsoft/AdaptiveCards#3058]
# Proposal: Adaptive Cards Feedback Controls Telemetry

## Summary

We'll gather data on the feedback controls’ usage, performance, error messages, and reliability in general and across different platforms.
This will serve as a model for preexisting controls and components, guiding our telemetry implementation in the rest of Adaptive Cards.

## Rationale

* We'd be able to measure the usage of the new feedback controls to get a sense of their adoption on each platform
* We'd be able to identify the most common errors and possible bugs, enabling a more data-driven bug fixing process.
* Overall, the Adaptive Cards team would be able to move to a more data-driven development process.

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow the Adaptive Cards (AC) team to capture and send back the predefined metrics for the new feedback controls for offline analysis | Must |
| The telemetry implementation will capture and send trace logging and/or errors back to Microsoft with platform and [other relevant card information] | Must |
| This proposal will allow developers to opt-out of telemetry | Must |
| This proposal will allow the AC team to gather data on the time taken to render their controls | Should |
| This proposal will allow external developers to request to send the telemetry data to themselves  | Won't |

## Important Notes

We considered allowing external developers to send the telemetry data to themselves, but that would require further consultation with CELA. We'll need to be conscious of how we communicate our reasons for this. We may give external developers a dashboard for some of the telemetry data in the future, but not now.
We should start with the JS and UWP 1DS telemetry libraries; the mobile SDKs are less supported in this timeframe.

## Open Questions

* How will we differentiate between developers testing out a feature/control and genuine use in practice?
* Will the 1DS team be able to provide consistent support for our timeframe?

**Comment by productboard-ac** [comment]
Link to feature: https://adaptivecards.productboard.com/feature-board/planning/features/1713641

**Comment by andrewleader** [comment]
Meeting notes from 6/14/2019 proposal review meeting

Matt: One random data point, people like Cortana wanted to know if they clicked play on a video. Should equally explore exposing telemetry for authors

David: Actionable Messages does a lot of logging, is there a way we can make sure whatever we produce works for the majority of AC customers and not the minority. Provide way for third party hosts to collect the telemetry themselves.

David: Outlook needs to expose controls to be able to turn off specific telemetry, might be turn off all actionable messages or maybe turn off some things like button clicks. Could be opportunity to converge.

David: Need to work with Actionable Messages team on making sure we're in sync about our telemetry. David to set up that meeting.

David: Develop more on the specific goal of this, is it to understand which elements are used for our team, or for partners to understand how their scenarios are used.

Shalini: First iteration is designed for us, future iteration is building something that also works for partners

David: It'd be good to have an idea of how cards are constructed, using ColumnSets, etc. Maybe we could server-side analyze cards on our endpoints that receive cards (like Bot Framework), that'd be more for first party partners.

Lilian: We have that for Bot Framework already, BF team collects that data today

Shalini: We should reach out to all our other AC partners and discuss the telemtry plans and see if there's any redundancy concerns
