### ISSUE TITLE
Difference in rendering in MS Teams Chat and Preview

### ISSUE THREAD

**Issue by siderisltd** [microsoft/AdaptiveCards#3062]
# Version of SDK
AdaptiveCards 1.1.2 from NuGet  

"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"version": "1.0"

# Issue
This is the adaptive card's JSON https://pastebin.com/F1nkSdRS that is generated from .NET core 
app. When this JSON is pasted on https://adaptivecards.io/designer/ it renders very well 
![14-06-2019-05-55-29](https://user-images.githubusercontent.com/10515463/59518089-99b92b80-8ecd-11e9-8690-bf32e6a677d9.png)

The text  "Some text that should be centered in MS Teams" is placed within a column in columnSet with VerticalAlignment.Center and it renders perfectly fine in App Studio or the web designer. When the same JSON is send in a chat in MS Teams the text is rather with VerticalAlignment.Top as shown on this image

![14-06-2019-06-02-32](https://user-images.githubusercontent.com/10515463/59518586-95414280-8ece-11e9-8c8e-5ed5af5582b2.png)

**Comment by matthidinger** [comment]
Hi @siderisltd, thanks for taking the time to file this. [`verticalContentAlignment`](https://adaptivecards.io/explorer/Container.html) was added in v1.1 of the schema, and as of right now [Microsoft Teams is running on v1.0](https://docs.microsoft.com/en-us/adaptive-cards/resources/partners), so the property is not understood on Teams yet.

We are working on an improvement to the Designer to include a **Target version** selector (potentially automatically selected based on the Host app dropdown), which will let you know if you're using newer properties/features than are currently supported by your desired Host app.

@dclaux FYI

**Comment by siderisltd** [comment]
@matthidinger do you know when migration to the new schema is planned for MS Teams?

**Comment by RebeccaAnne** [comment]
Teams is now updated to 1.2, and this property should be working there now.
