### ISSUE TITLE
Necessity property slipped into public designer

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#3066]
Looks like the necessity property wasn't properly pulled from the JS designer, it's showing up on the official adaptivecards.io!

![image](https://user-images.githubusercontent.com/13246069/59540948-32db4880-8eb4-11e9-9872-fab5500936a4.png)

**Comment by shalinijoshi19** [comment]
@dclaux was this not disabled by default as we'd discussed for 1.2?

**Comment by shalinijoshi19** [comment]
@dclaux FYI (he's already looking into this). Thanks!
