### ISSUE TITLE
TextBlock <-> TextRun parity

### ISSUE THREAD

**Issue by productboard-ac** [microsoft/AdaptiveCards#3071]
# Summary

All the relevant properties on TextRun should also be on TextBlock and vice versa

# Requirements

- See summary

# Spec/schema

After the proposal process, update this with a link to the spec PR.

# Proposed changes

Added to TextBlock

- `highlight`

- `italic`

- `selectAction`

- `strikethrough`

- `underline`

Added to TextRun

- N/A

# Example

```
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "Strike me out",
            "strikethrough": true
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```

# Host Config

N/A

# Down-level impact

**Minimal**. The new properties won't be respected down-level.

# Host burden

N/A

**Comment by productboard-ac** [comment]
Link to feature: https://adaptivecards.productboard.com/feature-board/planning/features/2372634

**Comment by dclaux** [comment]
I personally vote against this. These properties will conflict with Markdown support, which is precisely why we decided that RichTextBlock would not support Markdown.

**Comment by andrewleader** [comment]
# 7/12/2019 review meeting

* David absent and Matt not sure, so postponing any decisions
