### ISSUE TITLE
[Shared model] BaseInputElement is serializing isRequired property

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#3072]
# Platform

Impacts: 
* Android
* iOS
* UWP

# Version of SDK

1.2

# Issue

isRequired was not shipped as part of v1.2 so serializing it is a bug in it's own

**Comment by shalinijoshi19** [comment]
@almedina-ms was this fixed as part of your PR here https://github.com/microsoft/AdaptiveCards/pull/3100 or does this need to be fixed still?

**Comment by RebeccaAnne** [comment]
This has existed since 1.0, when we thought we might have an IsRequired property and it never got pulled.

**Comment by almedina-ms** [comment]
There are UWP methods for setting the isRequired property but we never use the property, we just serialize it, I was thinking of removing just the serialization for the method just so there are no breaking changes, is that good??
