### ISSUE TITLE
"px" option missing from Column.width

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#3073]

**Comment by andrewleader** [comment]
Reopening, this won't be resolved till site is manually published (which Matt is working on)

**Comment by shalinijoshi19** [comment]
@andrewleader / @matthidinger  this looks like this should be fixed now yes?

**Comment by shalinijoshi19** [comment]
I see this now in the latest version on adaptivecards.io: 

![image](https://user-images.githubusercontent.com/20822397/60748850-b550a880-9f46-11e9-9fbe-f588d66fc912.png)

**Comment by shalinijoshi19** [comment]
And this is the schema: 

![image](https://user-images.githubusercontent.com/20822397/60748874-0c567d80-9f47-11e9-913e-0ced6ffd6ee8.png)

**Comment by shalinijoshi19** [comment]
Looks like this is fixed at this point - @andrewleader can you please confirm and close out? thanks!
