### ISSUE TITLE
Right-to-left markdown links are rendered on the wrong side of the card (UWP).

### ISSUE THREAD

**Issue by jefflhp** [microsoft/AdaptiveCards#3077]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* UWP

# Author or host
Author and Host
If you're an author, who are you sending cards to?
HP Applications

# Version of SDK
AdaptiveCards.Rendering.UWP 1.2

# Issue
Right-to-left languages with markdown links are not rendered properly. The link is active on the 'right' side of the card, even thought the text for the link is rendered on the 'left' side of the card.

Here is a card that will replicate the problem using the UWP AdaptiveCardVisualizer

![RTLAdaptiveCardLink](https://user-images.githubusercontent.com/20073177/59643012-6de3b300-9124-11e9-98f8-7b2a9ae84e6d.png)

```json
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "TextBlock",
			"text": "Publish Adaptive Card schema",
			"weight": "bolder",
			"size": "medium"
		},
		{
			"type": "TextBlock",			
			"text": "\n\n1.פתח [ערכת לימוד זו](https://support.office.com/he-il/article/set-up-email-in-the-mail-app-for-windows-10-7ff79e8b-439b-4b47-8ff9-3f9a33166c60).\n2.פתח את [דואר אלקטרוני וחשבונות בלוח הבקרה](ms-settings:emailandaccounts)",
"horizontalAlignment" : "right",

			"wrap": true
		}
	]
}
```

**Comment by shalinijoshi19** [comment]
@RebeccaAnne can you take a look to see where and what the fix would need to be here? Thanks!

**Comment by jonmill** [comment]
Tracked by #1984
