### ISSUE TITLE
monacoEditorLoaded is not a function

### ISSUE THREAD

**Issue by ericrrichards** [microsoft/AdaptiveCards#3088]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Author or host

I am trying to use the adaptivecards-designer library to render the designer inside my web application

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

I am using the sample CDN code in the readme at https://github.com/microsoft/AdaptiveCards/tree/master/source/nodejs/adaptivecards-designer
I have lifted the code exactly from the readme and placed it in a stand-alone HTML page in my application, like so:

    <!DOCTYPE html>
    <html lang="en">
    <head></head>
    <body>
    <div id="designerRootHost"></div>
    <script src="https://unpkg.com/markdown-it@8.4.0/dist/markdown-it.min.js"></script>
    <script src="https://unpkg.com/adaptivecards-designer@0.1.1/dist/monaco-editor/min/vs/loader.js"></script>

    <script src="https://unpkg.com/adaptivecards-designer@0.1.1/dist/adaptivecards-designer.min.js"></script>
    <script>
        window.onload = function () {

            let hostContainers = [];

            // Optional: add the default Microsoft Host Apps (see docs below)
            hostContainers.push(new ACDesigner.WebChatContainer("Bot Framework WebChat", "containers/webchat-container.css"));
            hostContainers.push(new ACDesigner.DarkTeamsContainer("Microsoft Teams - Dark", "containers/teams-container-dark.css"));
            hostContainers.push(new ACDesigner.LightTeamsContainer("Microsoft Teams - Light", "containers/teams-container-light.css"));

            let designer = new ACDesigner.CardDesigner(hostContainers);

            // The designer requires various CSS and image assets to work properly,
            // If you've loaded the script from a CDN it needs to know where these assets are located
            designer.assetPath = "https://unpkg.com/adaptivecards-designer@0.1.1/dist";

            // Initialize monaco-editor for the JSON-editor pane. The simplest way to do this is use the code below, since we currently bundle monaco into our CDN distribution.
            require.config({ paths: { 'vs': 'https://unpkg.com/adaptivecards-designer@0.1.0/dist/monaco-editor/min/vs' } });
            require(['vs/editor/editor.main'], function () {
                designer.monacoEditorLoaded();
            });

            designer.attachTo(document.getElementById("designerRootHost"));
        };
    </script>
    </body>
    </html>

# Issue

The Monaco JSON editor is not loading, and in my Chrome DevTools console I am seeing the error: 

    Uncaught TypeError: designer.monacoEditorLoaded is not a function
        at CardDesigner:51
        at Function.t._invokeFactory (loader.js:22)
        at t.complete (loader.js:22)
        at s._onModuleComplete (loader.js:33)
        at s._onModuleComplete (loader.js:33)
        at s._onModuleComplete (loader.js:33)
        at s._onModuleComplete (loader.js:33)
        at s._onModuleComplete (loader.js:33)
        at s._onModuleComplete (loader.js:33)
        at s._onModuleComplete (loader.js:33)

(CardDesigner.html is my html page with the script and CDN links embedded)

I notice that most of the paths use 'adaptivecards-designer@0.1.1', except for the require.config path definition.  If I change everything to use 'adaptivecards-designer@0.1.0' the editor will load, however if I change the require.config path to 'adaptivecards-designer@0.1.1' it does not.  There appear to be newer versions of this package available - adaptivecards-designer@0.6.0 as of this writing - but I can't get any of this to work unless I use adaptivecards-designer@0.1.0

**Comment by dclaux** [comment]
Good catch - the documentation is out of date. The method has been renamed into `monacoModuleLoaded()`

Let me know if that works.

**Comment by andrewleader** [comment]
Thanks David! Assigning this issue to you if you could update the readme with the new method name?

**Comment by ericrrichards** [comment]
@dclaux  Thanks, yes, changing to use the new function works just fine

**Comment by dclaux** [comment]
Fixed: https://github.com/microsoft/AdaptiveCards/pull/3093#event-2425732088
