### ISSUE TITLE
Update SignConfig.xml to use stronger cert

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#3089]
Per email thread, we should be using a stronger cert in https://github.com/microsoft/AdaptiveCards/blob/master/source/uwp/Build/SignConfig.xml

(more context [here](https://github.com/dotnet/roslyn/issues/8459))

**Comment by shalinijoshi19** [comment]
@paulcam206 / @matthidinger marking approved since this one seems obvious to be picked up and worked on. thanks!

**Comment by shalinijoshi19** [comment]
@paulcam206 this can just come in now right ? Not blocked on anything ?

**Comment by shalinijoshi19** [comment]
@paulcam206 if we are doing this for 1.2.1 let's try to get started on this next week. Thanks!
