### ISSUE TITLE
Adaptive Card Viewer - Doesn't show AdaptiveCard JSON

### ISSUE THREAD

**Issue by DJF3** [microsoft/AdaptiveCards#3096]
# Info
**Platform**: MacOS
**VS Code**: 1.35.1
**Extension**: Adaptive Card Viewer v1.1.3

# Issue
VS Code: Copy/paste Adaptive Card example JSON in new document
VS Code: Save as card.json
**Language: JSON (auto-detected)**
Press CTRL-V then A:  Nothing happens

**Change language to: JSON with comments (jsonc)**
Press CTRL-V then A:  Error: 

> Active editor doesn't show a AdaptiveCard JSON document.

Is there, besides installing the "Adaptive Cards Viewer" plugin anything else I have to do to make it work/recognize adaptive card json?

**Comment by andrewleader** [comment]
@matthidinger do you have ownership of the VS Code extension?

**Comment by shalinijoshi19** [comment]
@matthidinger another one around the AC Viewer VS extension/plugin!

**Comment by matthidinger** [comment]
The extension actually lives in our repo, `~/source/vscode` 
I just realized it uses the old microsoft-adaptivecards rendering library, and the publisher is tomlm, so we'd have to do some research on how to update that with the store.

**Comment by matthidinger** [comment]
This should be fixed with the v2.0.0 Extension, please let us know if it's still happening!
