### ISSUE TITLE
Action OpenUrl not supported on Android?

### ISSUE THREAD

**Issue by patgoley** [microsoft/AdaptiveCards#3097]
# Platform

* Android

# Author or host

Host

# Version of SDK

`'io.adaptivecards:adaptivecards-android:1.2.0'`

The `BaseActionElement` does not seem to support getting the URL value for an Action.OpenUrl type Action in an adaptive card.

It contains the following getters:

```
GetTitle()
GetStyle()
GetIconURL()
GetAdditionalProperties() // returns a JSON element of "{}" for Action.OpenUrl actions
//... a few other getters from BaseElement
```

`ACOBaseActionElement` in the iOS SDK has a `url` method which returns the action url. It doesn't seem to have a counterpart in the Android SDK.

Is there some other way to get the URL for an OpenUrl action? If not, please add support to BaseActionElement.

Thank you!

**Comment by shalinijoshi19** [comment]
@patgoley thanks fore reporting. @almedina-ms could you take a look at this please real quick? Thanks!

**Comment by almedina-ms** [comment]
@shalinijoshi19 I just made the unit tests for properties and GetUrl does exist, it's under the OpenUrlAction as it's only a property for OpenUrl actions https://github.com/microsoft/AdaptiveCards/pull/3067/files#diff-41a904f1db6efb60c53107fc8ef0037a

**Comment by patgoley** [comment]
Thanks, I see that now. I was thrown off by the difference between the SDK's.

**Comment by patgoley** [comment]
I'd just like to mention a bug in the docs around this issue:

```
private void onOpenUrl(BaseActionElement actionElement)
    {
        OpenUrlAction openUrlAction = null;
        if (actionElement instanceof ShowCardAction)
        {
            openUrlAction = (OpenUrlAction) actionElement;
        }
```

The logic checks `instanceof ShowCardAction` but then casts to OpenUrlAction. I think that requiring so much dynamic casting between action types is counter intuitive and may cause breakage down the line if the types change. Perhaps in a future API `ICardActionHandler` could be updated to provide different methods for different action types where the action has already been cast to the appropriate type. Just my feedback, thanks!

**Comment by patgoley** [comment]
Sorry, one more issue with OpenUrl here. In my `ICardActionHandler`, the BaseActionElement does not successfully cast to OpenUrlAction and therefore I can't access the `getUrl` getter on the OpenUrlAction object. 

```
public void onAction(BaseActionElement baseActionElement, RenderedAdaptiveCard renderedAdaptiveCard) {
                        OpenUrlAction openUrlAction;
                        if (baseActionElement instanceof OpenUrlAction) {
                            openUrlAction = (OpenUrlAction) baseActionElement;
                           // never gets here
                        } else {
                            // always goes here, regardless of action type
                        }
                    }
```
The cast failed even though `baseActionElement..GetElementTypeString()` is `Action.OpenUrl`, which seems like a bug.

**Comment by almedina-ms** [comment]
that's something I found too while developing the tests, the work around I found for doing casting was declaring methods like the one below. This is due to the casting of objects from the c++ shared model having to be done through SWIG, in the future we'll try to look for a better solution to this problem

```
    public static OpenUrlAction castToOpenUrlAction(BaseActionElement baseActionElement)
    {
        OpenUrlAction openUrlAction = null;

        if (baseActionElement instanceof OpenUrlAction)
        {
            openUrlAction = (OpenUrlAction) baseActionElement;
        }
        else if ((openUrlAction = OpenUrlAction.dynamic_cast(baseActionElement)) == null)
        {
            throw new InternalError("Unable to convert BaseActionElement to OpenUrlAction object model.");
        }

        return openUrlAction;
    }
```

**Comment by patgoley** [comment]
Thanks, that worked for me. 

By the way, I spotted a typo in the docs for the open URL code:

```
private void onOpenUrl(BaseActionElement actionElement)
    {
        OpenUrlAction openUrlAction = null;
        if (actionElement instanceof ShowCardAction)
        {
            openUrlAction = (OpenUrlAction) actionElement;
```
`ShowCardAction` should be `OpenUrlAction` here.

Thanks for your help!
