### ISSUE TITLE
[Designer] Unable to load designer via Node package

### ISSUE THREAD

**Issue by lalli-flores** [microsoft/AdaptiveCards#3110]
# Platform

What platform is your issue or question related to?
**JavaScript**

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards?
**Host**

If you're an author, who are you sending cards to?
N/A

# Version of SDK
What version are you using? Ex: NuGet 1.0.2, or latest master, etc...
**Latest [NPM version of adaptive card designer](https://www.npmjs.com/package/adaptivecards-designer) (v0.6.0)**

# Issue

I am unable to load the adaptive card designer via [Node + Webpack](https://www.npmjs.com/package/adaptivecards-designer#option-2-node--webpack). I've created a [simple repository to replicate the issue](https://github.com/lalli-flores/adaptive-card-designer-test).
Seems like the adaptive card designer is looking for samples that are not installed when using NPM. This prevents the designer from loading at all.
Similar issue is found when using [RunKit](https://npm.runkit.com/adaptivecards-designer)
![image](https://user-images.githubusercontent.com/6610308/60228112-75067180-9846-11e9-91b9-b3486a0a1527.png)

**Comment by shalinijoshi19** [comment]
@matthidinger so this should be fixed now yes?

**Comment by lalli-flores** [comment]
Do we have an ETA for when this fix will be published?

**Comment by shalinijoshi19** [comment]
This likely will be part of our 1.2.1 release if not sooner - _@matthidinger  can you correct me here if we plan to release with this fix sooner than 1.2.1? Thanks!_

**Comment by matthidinger** [comment]
This should be fixed with the 0.7.0 release that just went out. Please reopen and let us know if you're seeing issues! 

https://www.npmjs.com/package/adaptivecards-designer/v/0.7.0
