### ISSUE TITLE
Width of card in Outlook

### ISSUE THREAD

**Issue by SWarnberg** [microsoft/AdaptiveCards#3111]
Can anyone elaborate on the width limitations when viewing a card in Outlook mail?
I'm pretty sure that when I first tested Adaptive Cards, sent to mail, it was using the whole width of the mail window. However, now it's only showing as a narrow card, using maybe 40% of the window width.
In desktop it's really ugly. In OWA, it's better, but still too narrow.
This is how it looks in desktop:

![image](https://user-images.githubusercontent.com/26246346/60249741-b427d780-98c5-11e9-9040-46054d257d22.png)

When using the designer in https://adaptivecards.io/designer, and selecting "Outlook Actionable Messages", the card looks really good. However, when using https://amdesigner.azurewebsites.net/, it's not possible to show or design for Outlook. Seems like there is a fixed max width of the cards now?

**Comment by paulcam206** [comment]
@dclaux - care to chime in here?

**Comment by paulcam206** [comment]
Per @dclaux:
> Hi @SWarnberg, we are aware of the issue and are working on a fix. Thanks for your patience!

**Comment by abhauau** [comment]
Is there any update on this issue. ServiceNow solution is not working due to this defect

**Comment by paulcam206** [comment]
@dclaux -- any word on this one?

**Comment by dclaux** [comment]
I have pinged the AM team again. They'll take it from here.

**Comment by TravisJefferds** [comment]
Hello, I see this was closed, but was there a fix? 
I have the same issue and it would really help fit all the info I need if I could just widen the effective area of the card.
Thank You,
Nute
![image](https://user-images.githubusercontent.com/89096109/136102159-c082b9d2-5f97-4429-9dc9-ab5a84b31445.png)

**Comment by laizk** [comment]
I have the same issue. Is there a solution or workaround for this?
