### ISSUE TITLE
iOS UnitTest Improvement: Networking

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#3127]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Issue

It came to our attention that during iOS unit testing, if a url to image or resources in general is used to get the resources, and if the resources is not available, the quality of unit testing can be degraded.

For example, if a resource is hosted by a third party, it's reasonable to assume that they may have a "rate limit" which is once hit, it can degrade unit testing experiences. 

Currently there are two suggestions:
1. replace url via networking with url via local resources. eg. via resource resolvers.
2. replace third party url with ms owned url.

**Comment by shalinijoshi19** [comment]
This is completed per the referenced PR. No networking calls in unit tests anymore.
