### ISSUE TITLE
Documentation of Authoring SDKs

### ISSUE THREAD

**Issue by btam** [microsoft/AdaptiveCards#3128]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android
* iOS
* UWP

# Author or host

Author

# Issue

We only have Authoring SDK documentation pages for .NET and JavaScript, although there are authoring SDKs for all platforms.

**Comment by shalinijoshi19** [comment]
I agree this should be fixed - at least a quick one-liner in our existing documentation here https://docs.microsoft.com/en-us/adaptive-cards/sdk/authoring-cards/net about how the library is optimized for the net/js platforms but not others, even though they are available as the complete renderer SDK offering for the remaining platforms.

**Comment by jonmill** [comment]
We don't have any supported scenarios for authoring in other languages; it can be done and we *should* add support for them, but we don't currently do that today
