### ISSUE TITLE
[JavaScript] : Video should play on Tap of a Thumbnail on Desktop as well as Mobile

### ISSUE THREAD

**Issue by cmevawala** [microsoft/AdaptiveCards#3140]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* JavaScript

# Author or host
Host

# Version of SDK
AdaptiveCards Release/1.1

# Issue
In the adaptive cards release version 1.1, the videos are played onClick of PlayButton. User should be allowed to play the video on Tap of Thumbail/Poster on Large Screen as well as in Mobile Devices

**Comment by dclaux** [comment]
@matthidinger what do the other renderers do? Do they allow clicking anywhere on the poster to start playback? If not, why would we make this change only in the JS renderer?

**Comment by shalinijoshi19** [comment]
@cmevawala is there a reason you are working with AdaptiveCards v1.1? Are you able to port this change over to master first?

**Comment by cmevawala** [comment]
@shalinijoshi19  : We have upgraded our webchat repo with latest 4.6 release which is referring 1.2.3. We will validate and let you know if this issue still exists.

**Comment by cmevawala** [comment]
Any plan of adding this feature in next release?

**Comment by shalinijoshi19** [comment]
@cmevawala I believe there are open comments on your PR

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. However, would welcome a contribution to fix it.
