### ISSUE TITLE
[UWP] Helper implementations should be provided to parse and implement base element properties

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#3145]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Issue

Today to implement a custom element, parsing of all properties is required. We should provide a base implementation to handle parsing properties that are common to all elements.

**Comment by shalinijoshi19** [comment]
@RebeccaAnne is this something that can be community-sourced?
