### ISSUE TITLE
Consistent behavior around required properties and schema errors

### ISSUE THREAD

**Issue by productboard-ac** [microsoft/AdaptiveCards#3154]
# Summary
There are a lot of inconsistencies between JS and UWP/iOS/Droid when it comes to how required properties on elements are handled. JS is less strict and often continues rendering even when required properties are missing, while the other platforms fail rendering the entire card. We must converge on a consistent behavior to reduce developer frustration. This has been a big pain point for Teams authors, since their card works fine on Desktop (JS) but not on Mobile.

Similarly, properties that are invalid/incorrect should also be handled consistently (like an incorrect enum, or a pixel height missing the "px").

# Requirements

* Consistent and intuitive behavior around missing required properties
* Consistent and intuitive behavior around invalid property values

# Spec/schema

#3248

# Proposed changes

## Missing required properties

If an element is missing a required property (or the required property is an empty string `""`), the **element** will be **dropped** and a **warning** will be triggered. Fallback will NOT be invoked.

```json
{
    "type": "TextBlock",
    "text": "First TextBlock"
},
{
    "type": "TextBlock"
},
{
    "type": "TextBlock",
    "text": "Third TextBlock"
}
```

**Rendering**

![image](https://user-images.githubusercontent.com/13246069/60830415-01306700-a16c-11e9-9c71-7799d2e5466c.png)

**Warnings**

```
Dropping TextBlock since required `text` property is missing.
```

## Invalid values

If a property value on an element is invalid (for example, specifying a string when it should be a boolean, specifying an unknown enum, specifying a pixel height in the wrong format, etc), the **property** will be **ignored** (use default value) and a **warning** will be triggered.

```json
{
  "type": "TextBlock",
  "text": "Wrap should have been boolean, not integer",
  "wrap": 5
}
```

**Rendering**

![image](https://user-images.githubusercontent.com/13246069/60830224-8ff0b400-a16b-11e9-8a81-1353ae2ca9a9.png)

**Warnings**

```
Ignoring invalid value 5 on TextBlock.wrap
```

# Host Config
N/A

# Down-level impact
Cards that used to fail rendering on UWP/Android/iOS/WPF will now start to render with some elements dropped

# Host burden
N/A

# Things to fix

* TextBlock text property
* Action.OpenUrl missing `url` (especially .NET, it fails upon clicking): #3011
* Everything else

**Comment by productboard-ac** [comment]
Link to feature: https://adaptivecards.productboard.com/feature-board/planning/features/2509613

**Comment by andrewleader** [comment]
# 7/12/2019

Proposal approved

* Required properties that have an empty value, like `"text": ""`... should that render?
  * Empty string should NOT render... empty string is same as null.
* Need follow-up on schema and whether we should have a strict/loose schema, but we need more data on how people are actually using the schema

**Comment by VikrantSingh01** [comment]
We may need #MsftTeams-Integration tag here as well @shalinijoshi19

**Comment by RebeccaAnne** [comment]
This issue came up again in discussion of #3702.
