### ISSUE TITLE
iOS "auto" and "stretch" in column width properties

### ISSUE THREAD

**Issue by nesalang** [microsoft/AdaptiveCards#3159]
# Platform

* iOS

# Issue

This is child issue of #3125.

iOS "auto" and "stretch" in column width properties have different behaviors compared to other renderers.  Please refer to #3125 for payload and screen shots.

When two UI elements can not be fitted in a row without resizing, column with "stretch" value tends to get shrunken more than with "auto" in other renders. 

This behavior is opposite in iOS.

**Comment by shalinijoshi19** [comment]
Fixed in AdaptiveCards v1.2.1
