### ISSUE TITLE
Fallback not respected in UWP ImageSet

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#3163]
# Platform

* .NET HTML
* .NET WPF
* UWP
* Android
* iOS

# Version of SDK

latest master

# Issue

The .NET platform and the UWP renderer render this card in two different ways; there are two big differences:

1.  Fallback is not being respected in UWP

![image](https://user-images.githubusercontent.com/35784165/60998331-91f27880-a30d-11e9-87e2-8e9a5405fc9b.png)

![image](https://user-images.githubusercontent.com/35784165/60998409-bcdccc80-a30d-11e9-82c9-6d3449e3a4f0.png)

```
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "ImageSet",
			"imageSize": "auto",
			"images": [
				{
					"type": "Image",
					"url": "http://adaptivecards.io/content/cats/1.png",
					"size": "small"
				},
				{
					"type": "Image",
					"url": "http://adaptivecards.io/content/cats/2.png",
					"size": "medium"
				},
				{
					"type": "Image",
					"url": "http://adaptivecards.io/content/cats/3.png",
					"size": "large",
					"requires": 
					{
						"adaptiveCard": "1.4"
					},
					"fallback": 
					{
						"type": "TextBlock",
						"text": "Some text"
					}
				},
				{
					"type": "Image",
					"url": "http://adaptivecards.io/content/cats/1.png",
					"backgroundColor": "#228B22"
				},
				{
					"type": "Image",
					"url": "http://adaptivecards.io/content/cats/2.png",
					"size": "stretch"
				},
				{
					"type": "Image",
					"url": "http://adaptivecards.io/content/cats/3.png",
					"style": "person"
				}
			]
		}
	]
}
```

**Comment by RebeccaAnne** [comment]
@almedina-ms lets split this into two separate bugs.

**Comment by shalinijoshi19** [comment]
@almedina-ms did you ever get to splitting this bug? If not can you create a separate one for tracking issue #2 (Image sizes are not being respected in UWP when ImageSet imageSize is set to auto)

**Comment by matthidinger** [comment]
@almedina-ms friendly ping about splitting this bug and we can triage them independently

**Comment by shalinijoshi19** [comment]
@RebeccaAnne this looks like a clear case of fallback needing to be respected in UWP yes? Assigning to you to see if we can come up with a proposal for this bug to discuss in the design notes meet.

**Comment by almedina-ms** [comment]
@shalinijoshi19 this has to do more with the rules for fallback and most likely ImageSets shouldn't allow an image to have a texblock as fallback, we should set the rules for this cases just as in columnset we only allow columns to be replaced by other columns
