### ISSUE TITLE
[Designer] Maximum value listed twice

### ISSUE THREAD

**Issue by choupete** [microsoft/AdaptiveCards#3167]
# Platform

What platform is your issue or question related to? (Delete other platforms).

N/A

# Issue

In the designer, for `Input.Text`, `Input.Time`, and `Input.Date`, "Maximum Value" is erroneously listed twice (the former field should be minimum).

Result:
![image](https://user-images.githubusercontent.com/42462906/61006248-bacf3980-a31e-11e9-9f2e-5637df424963.png)

**Comment by dclaux** [comment]
Nice catch. Copy/paste error; first input is minimum value, second is maximum. Easy fix.

**Comment by dclaux** [comment]
PR: https://github.com/microsoft/AdaptiveCards/pull/3169

**Comment by matthidinger** [comment]
Fixed in #3169
