### ISSUE TITLE
[UWP][JS] Inconsistency with types in Input.Number

### ISSUE THREAD

**Issue by choupete** [microsoft/AdaptiveCards#3171]
# Platform

* JavaScript
* UWP

# Issue

When creating a card in the designer that has a `Input.Number` element, the designer returns values for the "min" and "max" fields as string types in the resulting JSON. This renders fine in JS, but UWP returns rendering errors because it expects a number. JS will render with both a number and a string in this field.

```
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "Input.Number",
            "title": "New Input.Toggle",
            "placeholder": "Placeholder text",
            "min": "12",
            "max": "16",
            "id": "d"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```

Result:

In UWP:
![image](https://user-images.githubusercontent.com/42462906/61007488-ce2fd400-a321-11e9-9ff3-14767063abbc.png)

**Comment by RebeccaAnne** [comment]
Schema says that these should be numbers: https://adaptivecards.io/explorer/Input.Number.html

**Comment by RebeccaAnne** [comment]
Choice set in javascript also accepts numbers where it should only accept strings:
![image](https://user-images.githubusercontent.com/9091833/61010252-5914cc80-a32a-11e9-83c4-4bc0ec6537d9.png)


```{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "Input.ChoiceSet",
            "placeholder": "Placeholder text",
            "choices": [
                {
                    "title": 5,
                    "value": 2
                },
                {
                    "title": "Choice 2",
                    "value": "Choice 2"
                }
            ],
            "style": "expanded"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}

**Comment by matthidinger** [comment]
@dclaux can you confirm this is fixed and close if so, thanks!

**Comment by dclaux** [comment]
Yes, these are fixed.

**Comment by jpjpjp** [comment]
Which version of the designer is this fixed in?   I'm still seeing the default value being defined as a string in the generated JSON.     

When designing Input.Number here:
[![Screen-Shot-2020-02-03-at-12-59-23-PM.png](https://i.postimg.cc/3JbWLsQW/Screen-Shot-2020-02-03-at-12-59-23-PM.png)](https://postimg.cc/KRBZjszy)

the generated JSON is:

```json
                {
                    "type": "Input.Number",
                    "placeholder": "Placeholder text",
                    "min": 1,
                    "max": 5,
                    "value": "3",
                    "id": "TestDefaultValue"
                },
```

Note that the "min" and "max" values are numbers but the "value" value is a string.

**Comment by dclaux** [comment]
It is fixed in https://vnext.adaptivecards.io/designer/ which is powered by the [2.0 alpha release](https://www.npmjs.com/package/adaptivecards/v/2.0.0-alpha.1). There is no intent to backfix into previous releases at this point because it is a breaking change.
