### ISSUE TITLE
[Schema Explorer] The page's "try it yourself" button text continues to be busted 

### ISSUE THREAD

**Issue by shalinijoshi19** [microsoft/AdaptiveCards#3172]
# Platform

https://adaptivecards.io/explorer/Container.html

# Author or host
latest prod deployment

# Issue
The text on the "Try it Yourself" button appears busted still with a trailing character; This should have been addressed with the 7/9 deployment per Matt ; The right version appears on http://adaptivecards-ci.azurewebsites.net/explorer/
![image](https://user-images.githubusercontent.com/20822397/61007579-03d4bd00-a322-11e9-8800-d3a510e8af35.png)

**Comment by shalinijoshi19** [comment]
@matthidinger assigned to you for tracking. Thanks

**Comment by matthidinger** [comment]
This is fixed now, thanks! :)
