### ISSUE TITLE
[Designer] json created by designer sets value of Input.Number to wrong type

### ISSUE THREAD

**Issue by utsavlathia** [microsoft/AdaptiveCards#3173]
# Platform

* Designer

# Issue
This is the json created by the designer when you put a default value in a Input.Number
```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Input.Number",
            "title": "New Input.Toggle",
            "placeholder": "Placeholder text",
            "id": "Inputer4",
            "value": "5"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```
According to [the schema](https://adaptivecards.io/explorer/Input.Number.html) value is supposed to be a number not a string, so this seems to be a designer bug for setting value as a string in the produced json. 

This is most likely the root cause of [this issue](https://github.com/microsoft/AdaptiveCards/issues/3171)

**Comment by RebeccaAnne** [comment]
We'll track this as part of #3171
