### ISSUE TITLE
[UWP] Visualizer crashes with erroneous values on Input.Date

### ISSUE THREAD

**Issue by choupete** [microsoft/AdaptiveCards#3174]
# Platform

* UWP

# Issue

The UWP visualizer crashes when the JSON has faulty min and max values on `Input.Date` (when max comes before min). The visualizer initially renders the card, but when clicking the button to expand the date picker, the application crashes.

```
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "Input.Date",
            "title": "New Input.Toggle",
            "id": "asdf",
            "min": "2017-08-01",
            "max": "2017-07-08"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```

# Result:

![image](https://user-images.githubusercontent.com/42462906/61008153-a6417000-a323-11e9-9abd-243d9d3b6a3f.png)
Clicking the calendar icon will cause a crash.

**Comment by shalinijoshi19** [comment]
@nesalang load balancing some of the UWP issues to you. Please work with @RebeccaAnne / @paulcam206 to follow up. We should fix the crash for sure, but also a separate validation if needed for validating the dates that fell outside of the acceptable values.

**Comment by nesalang** [comment]
@shalinijoshi19 sure
