### ISSUE TITLE
[UWP] Visulizer throwing an futile error expecting number on strings

### ISSUE THREAD

**Issue by utsavlathia** [microsoft/AdaptiveCards#3178]
# Platform

* UWP

# Issue

This error is being thrown on the UWP visualizer although the Input.Text.Value should be a string not a number
![image](https://user-images.githubusercontent.com/43022566/61008496-7cd51400-a324-11e9-88dd-6d8d8876b291.png)

This is an example of the json that would throw this error
```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Input.Text",
            "title": "New Input.Toggle",
            "placeholder": "Placeholder text",
            "id": "66",
            "isMultiline": true,
            "value": "hi"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

**Comment by RebeccaAnne** [comment]
The card renders properly in spite of this error.

**Comment by shalinijoshi19** [comment]
@almedina-ms could you take a look at what the issue is here? Thanks
