### ISSUE TITLE
[WPF .NET Renderer] Fails to render a card with Id set on elements

### ISSUE THREAD

**Issue by shalinijoshi19** [microsoft/AdaptiveCards#3181]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF

# Version of SDK
Latest master 

# Issue

It looks like as soon as I add an Id to the card, it fails to render in WPF (renders fine in JS) with the following exception that's thrown under the covers:

RENDER Failed. '3' is not a valid value for property 'Name'.
Exception thrown: 'System.NullReferenceException' in WpfVisualizer.exe

`{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "This is some of my bug bash text",
                    "id": "3"
                },
                {
                    "type": "Image",
                    "url": "http://adaptivecards.io/content/cats/1.png",
                    "id": "4",
                    "altText": "This is a cat"
                }
            ]
        }
    ],
    "id": "1"
}`

**Comment by RebeccaAnne** [comment]
This is due to the issue where .NET doesn't accept numeric ids.

**Comment by RebeccaAnne** [comment]
Closing as dup of #2569
