### ISSUE TITLE
[JS] Interaction between show card and toggle

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#3182]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* JavaScript

# Issue

Repro steps:
Render the card below:
![image](https://user-images.githubusercontent.com/9091833/61009101-67f98000-a326-11e9-86d1-f57cbf545f93.png)

Click the show card action:
![image](https://user-images.githubusercontent.com/9091833/61009117-76e03280-a326-11e9-9438-5fbcff28b495.png)

Click the toggle visibility action:
![image](https://user-images.githubusercontent.com/9091833/61009132-895a6c00-a326-11e9-9d08-5334137608af.png)

Click the toggle visibility action again.
Expected: "Hidey" comes back
Actual: "Hidey" stays hidden
(Works properly on UWP)

```
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "New TextBlock"
        },
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.ShowCard",
                    "title": "Action.ShowCard",
                    "card": {
                        "type": "AdaptiveCard",
                        "version": "1.0",
                        "body": [
                            {
                                "type": "TextBlock",
                                "text": "Hidey",
                                "id": "hidey"
                            }
                        ],
                        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
                    }
                },
                {
                    "type": "Action.ToggleVisibility",
                    "title": "Action.ToggleVisibility",
                    "targetElements": [
                        "hidey"
                    ]
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}

**Comment by dclaux** [comment]
The ToggleVisibility button merely shows or hides the "Hidey" TextBlock, it doesn't nor should reveal the ShowCard's card, so the observed behavior is correct and UWP seems to be a bit overzealous.

That said, clicking the ToggleVisibility button once, then the ShowCard should show an empty ShowCard because the ToggleVisibility button is supposed to have hidden the TextBlock. That isn't the case, so there is a bug. But I think it is a minor corner case.

**Comment by RebeccaAnne** [comment]
The behavior i was seeing was that once the show card was open, the toggle button could hide the hidey text block, but not bring it back.

**Comment by dclaux** [comment]
What I am saying is that the ToggleVisibility button doesn't hide the TextBlock, it causes the ShowCard to collapse. Clicking the ToggleVisibility button again is not going to re-expand the ShowCard.

**Comment by RebeccaAnne** [comment]
Ah, got it, so the bug is that the ToggleVisibility button is collapsing the show card instead of hiding just the text block, makes sense. Thanks.

**Comment by dclaux** [comment]
Nope. The ToggleVisibility button is supposed to collapse the ShowCard. The currently expanded ShowCard should collapse as a result of any other button within the same collection being clicked.

BUT, the ToggleVisibility button should also hide the TextBlock, but it doesn't. That's the bug.

**Comment by RebeccaAnne** [comment]
Oh. Hmm... That's not how that works in UWP or .NET.  On those platforms we only collapse the show card if another **ShowCard** button is clicked. @nesalang @almedina-ms what happens in ios and android? @andrewleader @matthidinger thoughts on how this is supposed to work?

Summary: Should clicking another non-ShowCard button in the same action set as a show card cause the show card to collapse? Today UWP and .NET collapse only if another ShowCard is clicked, Javascript collapses if any other button (any action type) is clicked.

**Comment by andrewleader** [comment]
Hmm, interesting. I'm not sure what's the right behavior around whether clicking a non-ShowCard action within the same set should collapse the currently-shown card.

Let's open a new issue specific to that, and let this issue remain specific to the JS bug around the ToggleVisibility hide action not working.

**Comment by RebeccaAnne** [comment]
Opened https://github.com/microsoft/AdaptiveCards/issues/3200

**Comment by shalinijoshi19** [comment]
@dclaux assigning to you to address on the JS side. Thanks
