### ISSUE TITLE
[iOS] Nested ShowCards Don't Work Properly in ActionSet

### ISSUE THREAD

**Issue by nesalang** [microsoft/AdaptiveCards#3183]
# Platform

* iOS

# Issue

Nested ShowCards in ActionSet don't render properly, however the same nested ShowCard render properly in actions.
Please refer to #3177 for json

**Comment by shalinijoshi19** [comment]
@nesalang, can you pls pick this up! thanks

**Comment by nesalang** [comment]
@shalinijoshi19  sure
