### ISSUE TITLE
[UWP,X64, VS2019] solution fails to compile with a certificate mismatch error for the 2 store apps

### ISSUE THREAD

**Issue by shalinijoshi19** [microsoft/AdaptiveCards#3194]
# Platform

* UWP

# Version of SDK

latest master with VS2019

# Issue

Trying to compile the VS solution fails with the following errors in VS2019; Confirmed that this isnt an issue with VS2017

Severity	Code	Description	Project	File	Line	Suppression State
Error		Certificate does not match supplied signing thumbprint: 7DF59BF73D990455B63DFF7735D301D0BB319CD2	AdaptiveCardTestApp			
Error		Certificate does not match supplied signing thumbprint: BD1E51E915EF811D813E0C6C4143C44144367328	AdaptiveCardVisualizer

**Comment by shalinijoshi19** [comment]
@almedina-ms assigning to you per standup; Could you follow up with the 2019 upgrade thread/see if regenerating the appx signing cert helps unblocks this! Thanks

**Comment by shudson302** [comment]
Any resolution on this?  I am getting this error as well

Severity	Code	Description	Project	File	Line	Suppression State
Error		Certificate does not match supplied signing thumbprint: 6460AE0F77456B08910E509B06E28B4D921D2AA0	NID.Client.UWP

**Comment by almedina-ms** [comment]
@shudson302 Currently I was able to fix the issue locally by 
1. Right click the project -> Properties -> Package Manifest
2. On the Package.appxmanifest go to Packaging tab -> Choose Certificate
3. In the new window click "Select a Certificate..." if you have one, or create a certificate if you havent created one (https://docs.microsoft.com/en-us/windows/uwp/packaging/create-certificate-package-signing)

**Comment by shudson302** [comment]
Ok, that fixed it.  Thanks

**Comment by shalinijoshi19** [comment]
Load-balancing this out to myself see if this was a regression here at all or we just need a new self-signed certificate checked in for the app.
