### ISSUE TITLE
Column Set does not truncate characters from end

### ISSUE THREAD

**Issue by Aditya0603** [microsoft/AdaptiveCards#3196]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

host 

If you're an author, who are you sending cards to?

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

1.2

# Issue

if the card to tab width is less an adaptive Card with his number of column sets does not truncate the text properly.
![65303bfb-6576-4aae-9514-bc6d75386950](https://user-images.githubusercontent.com/33312128/61116450-1847bf80-a4b2-11e9-91df-3ebbfe9c4186.jpeg)

**Comment by nesalang** [comment]
@Aditya0603 
can you share your json? I want to see if recent fix fixes this issue.
thanks

**Comment by VikrantSingh01** [comment]
This bug need #MsftTeams-Integration label @shalinijoshi19

**Comment by shalinijoshi19** [comment]
@Aditya0603 / @nesalang is this still an issue that is repro'ing with the latest AC 1.2.5 ?

**Comment by VikrantSingh01** [comment]
> @Aditya0603 / @nesalang is this still an issue that is repro'ing with the latest AC 1.2.5 ?

@Aditya0603 / @Shbhadra Do we still need a fix here on top of A.C 1.2.5 ?

**Comment by nesalang** [comment]
@nesalang , check for the update on the issue.

**Comment by paulcam206** [comment]
Is this issue still reproducing? If so, please reactivate this bug.
