### ISSUE TITLE
Add placeholder to Input.ChoiceSet

### ISSUE THREAD

**Issue by productboard-ac** [microsoft/AdaptiveCards#3198]
<table>
<tr>
<th>Release</th>
<th>Renderer status</th>
<th>Tasks status</th>
</tr>
<tr>
<td>1.3
<td>🔄 .NET (#3201)<br/>🔄 Android (#3202)<br/>🔄 iOS (#3203)<br/>✔️ TS (#3204)<br/>🔄 UWP (#3205)</td>
<td>🔄 Shared (#3206)<br/>✔️ Designer (#3207)</td>
</tr>
</table>

# Summary

`placeholder` currently isn't supported on ChoiceSet (although JS does actually unofficially support it). We should add official support for `placeholder` on ChoiceSet.

# Requirements

- Can specify placeholder text for Input.ChoiceSet.

# Spec/schema

<https://github.com/microsoft/AdaptiveCards/pull/3199/files>

# Proposed changes

**New** `placeholder` property on `Input.ChoiceSet`. Works the same as `placeholder` on `Input.Text`.

# Example

```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Input.ChoiceSet",
            "id": "ChoiceSet",
            "placeholder": "Select a choice",
            "choices": [
                {
                    "title": "Choice 1",
                    "value": "Choice 1"
                },
                {
                    "title": "Choice 2",
                    "value": "Choice 2"
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

![image](https://user-images.githubusercontent.com/13246069/61146873-e32a7580-a48f-11e9-8aba-7583bfd61c9f.png)

# Host Config

N/A

# Down-level impact

**Minimal**. Placeholder text will be dropped down-level, which may be slightly confusing to users but card should at least still be functional.

# Host burden

N/A

# Auto-generated task status

- [ ] Shared
- [x] Designer
- [ ] .NET
- [ ] Android
- [ ] iOS
- [x] TS
- [ ] UWP

**Comment by productboard-ac** [comment]
Link to feature: https://adaptivecards.productboard.com/feature-board/planning/features/2541871

**Comment by andrewleader** [comment]
# 7/12/2019 review

Proposal and spec approved

* Update spec to say that placeholder should respect wrap
