### ISSUE TITLE
Inconsistency in show card collapse behavior

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#3200]
There is an inconsistency between renderers as to what should happen when another non-showcard button in a action set is pressed when a show card is showing. In javascript, pressing any other button will collapse the shown show card. In UWP and .NET, only pressing another **ShowCard** button will collapse the shown show card.

JS | UWP/.NET
--|--
![TSShowCard](https://user-images.githubusercontent.com/13246069/61160763-9e193a00-a4b5-11e9-8b80-ed60a4248f28.gif) | ![UWPShowCard](https://user-images.githubusercontent.com/13246069/61160818-e0db1200-a4b5-11e9-9f54-c22bd4150416.gif)

**Repro card**

```json
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "My card"
        },
        {
            "type": "TextBlock",
            "text": "Content to toggle",
            "id": "toggle1",
            "isVisible": false
        },
        {
            "type": "TextBlock",
            "text": "Toggled content",
            "id": "toggle2"
        },
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.ShowCard",
                    "title": "Action.ShowCard",
                    "card": {
                        "type": "AdaptiveCard",
                        "version": "1.0",
                        "body": [
                            {
                                "type": "TextBlock",
                                "text": "ShowCard contents",
                                "id": "hidey"
                            }
                        ],
                        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
                    }
                },
                {
                    "type": "Action.ToggleVisibility",
                    "title": "Action.ToggleVisibility",
                    "targetElements": [
                        "toggle1",
                        "toggle2"
                    ]
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```

**Comment by andrewleader** [comment]
_(from Becky's comment on the other thread)_

@nesalang @almedina-ms what happens in ios and android? @matthidinger thoughts on how this is supposed to work?

Summary: Should clicking another non-ShowCard button in the same action set as a show card cause the show card to collapse? Today UWP and .NET collapse only if another ShowCard is clicked, Javascript collapses if any other button (any action type) is clicked.

Andrew's opinion is mixed - I could go either way. How UWP behaves seems like it might be the most reasonable/expected way, but I'm also probably okay with how JS behaves (any button closes the ShowCard).

@dclaux do you have any opinions on what the ideal behavior should be? I don't think we ever spec'd out this behavior clearly, any reasons/explanations why one approach is better than the other?

**Comment by andrewleader** [comment]
Also @MikeHillberg any perspectives from the XAML side? See the GIF in the main description for a quick visual of the two options.

**Comment by dclaux** [comment]
@andrewleader I do, it is the behavior of the JS renderer.

**Comment by matthidinger** [comment]
This experience in Teams + GitHub feels right to me. Action.Submit and Action.OpenUrl keep the ShowCard open, and at least in this scenario does feel like the expected user experience. 

@dclaux do you feel super strongly about the other behavior?

![showcard](https://user-images.githubusercontent.com/1432195/61239324-79aaa100-a6f3-11e9-933b-9b2e5d6d42d7.gif)

**Comment by dclaux** [comment]
Teams has explicitly overriden the renderer's behavior (I don't know how for that matter, there's no hook for this.) I do not believe it is the right experience, but I can't speak for everybody and that's obviously just my opinion. Outlook implements the behavior I described and is just as valid an example as the GIF you posted above.

**Comment by shalinijoshi19** [comment]
@jjustinjacob (Teams), could you confirm that you are overriding the default AdaptiveCards JS behavior here? @paulcam206 FYI.
