### ISSUE TITLE
[Shared] Add placeholder to Input.ChoiceSet

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#3206]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

Shared implementation of #3198

**Comment by shalinijoshi19** [comment]
@RebeccaAnne is there a more recent Input.Evolution related issue that is tracking this work that we can dup this to ?

**Comment by RebeccaAnne** [comment]
@shalinijoshi19 It's a little orthogonal, but we could pull this one into the input stuff. I'll leave open for now until i update the doc to add this feature.
