### ISSUE TITLE
[Designer] There are two "value for on " textblocks

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#3223]
# Platform

* Designer

# Version of SDK

latest master

# Issue

Input.Toggle in the designer has two values "Value when on"; also the value for off is "true" just as the value for on

![image](https://user-images.githubusercontent.com/35784165/61161605-70ce8b00-a4b9-11e9-9428-3cf8246c26ba.png)

**Comment by dclaux** [comment]
Fixed here: https://github.com/microsoft/AdaptiveCards/pull/3169

**Comment by dclaux** [comment]
Oops. Reopening as the PR has not been merged.

**Comment by shalinijoshi19** [comment]
@dclaux can this issue be closed now?

**Comment by RebeccaAnne** [comment]
This is fixed in the current version of the designer.
