### ISSUE TITLE
[Shared model] There is no consistency for on and off values in Input.Toggle

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#3224]
# Platform

* Shared

# Version of SDK

latest master

# Issue

In a Input.Toggle input object the default value, when creating the element, for valueOn is  "true" and for valueOff is "false" but when serializing we check for empty strings for default values which is not the same; the Deserialize method in the other hand considers empty string to be the default values for both properties, which should be the default value?

**Comment by almedina-ms** [comment]
@andrewleader @paulcam206 @RebeccaAnne , any ideas here?

**Comment by andrewleader** [comment]
In the schema we say default values are `"true"` and `"false"` if the author didn't specify those properties, I'd say we should converge around that?
