### ISSUE TITLE
Input.Text and other Input types in Adaptive Cards doesn't have layout property "horizontalAlignment"

### ISSUE THREAD

**Issue by mamhh** [microsoft/AdaptiveCards#3230]
`Input.Text` and other Input types in `Adaptive Cards` doesn't have layout property `"horizontalAlignment"` .. which is very weird ... how can I overcome this limitation and make   (`Input.Text`) aligned to `Right `instead of Left ???

**Comment by dclaux** [comment]
@mamhh all inputs always use the full width available in their parent container, thus they don't support horizontal alignment because it would be meaningless (that's especially true for Input.Text.)

**Comment by mamhh** [comment]
> @mamhh all inputs always use the full width available in their parent container, thus they don't support horizontal alignment because it would be meaningless (that's especially true for Input.Text.)

So, if I want the text inside `INPUT. TEXT` to be aligned to right (right to left writing) ... what should I do ??

**Comment by dclaux** [comment]
There is nothing to align... an Input.Text always uses the full width of its parent container. Maybe you could post an image of what you're trying to accomplish?

**Comment by dclaux** [comment]
Let me put it differently: if you were able to right align an Input.Text, what would the width of that Input.Text be?

**Comment by mamhh** [comment]
Your point is valid for English writing .. but for OTHER LANGUAGES , Arabic in my case , Arabic is written from Right to Left .. 
So, if we are writing Arabic inside a TEXTBOX and the text is aligned to left, it will have bad looking ...

Below example may clarifies the point..

[عربي         ] aligned to left --> current look.
[         عربي] aligned to right --> target look

**Comment by dclaux** [comment]
Ah... so you are asking about RTL support, which is a completely different thing. You don't want to explicitly set alignments to achieve RTL, you want the host to do the right thing automatically. For instance, a host would interpret `"horizontalAlignment": "left"` as meaning `"horizontalAlignment": "right"` (and the other way around) if it was set to a RTL language such as Arabic. But it goes beyond that - the content of an `Input.Text` (or any input for that matter) would itself have to be correctly aligned within the input. The `horizontalAlignment` property solely aligns the full control within its parent.

RTL is something that a host must explicitly support. What is your scenario? Are you implementing a Bot? Are you displaying Adaptive Cards in your own application? If so, which SDK (renderer) are you using?

**Comment by matthidinger** [comment]
Re #2139, which I've added to the 1.3 milestone for review

**Comment by mamhh** [comment]
@dclaux @matthidinger  I'm implementing a bot that returns a form to be filled by user .. current rendering within the EMULATOR.. target channel (WEBCHAT) ..so do both *currently* support  RTL ?? Should I follow the post referenced by @matthidinger ??

**Comment by dclaux** [comment]
I unfortunately do not know whether Teams/WebChat support RTL. I have asked internally and will get back to you here if I get an answer.

What Matt referenced is an issue that I opened to add explicit support for RTL in Adaptive Cards. That feature hasn't been implemented though, and Matt is saying we will consider it for the next AC release, namely 1.3.

**Comment by mamhh** [comment]
@dclaux .. target date of 1.3  plz ??? and if adaptive cards will support RTL, that means having them rendered within webchat will reflect that behavior?? Anyways .. I'm waiting more details about webchat once you got it ,,,

**Comment by mamhh** [comment]
@dclaux ... waiting for your response plz ....
