### ISSUE TITLE
Adaptive Card Viewer - File Does Not Show Adaptive Card JSON 

### ISSUE THREAD

**Issue by dominicdustin** [microsoft/AdaptiveCards#3234]
Issue Type: <b>Bug</b>

when I invoke the Adaptive Card Viewer Extension command I get the following error message "File does not show adaptive Card JSON". I have tried almost 30 of the microsoft and github sample card JSON files with the correct schema and it does it no matter what.

Extension version: 1.1.3
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.76GB (48.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jonmill** [comment]
The AC Viewer extension is deprecated,  please use this one instead: https://marketplace.visualstudio.com/items?itemName=madewithcardsio.adaptivecardsstudiobeta
