### ISSUE TITLE
Number Input default value undefined when value is set to zero

### ISSUE THREAD

**Issue by tdurnford** [microsoft/AdaptiveCards#3237]
# Platform

* JavaScript

# Author or host
Host Rendering Cards

# Version of SDK

npm Adaptive Cards v1.2.0

# Issue

Per issue https://github.com/microsoft/BotFramework-WebChat/issues/2192

Adaptive inputs of type `Input.Number` don't display the value `0`.

![image](https://user-images.githubusercontent.com/7884997/61311209-cd011a00-a7ed-11e9-8c61-a8e13124c920.png)

## To Reproduce

Steps to reproduce:

1. Go to [Adaptive Cards Designer](https://adaptivecards.io/designer/)
2. Select `Bot Framework WebChat` as the host app
3. Paste the following json in the `Card Payload Editor`:
~~~
{
    "type": "AdaptiveCard",
    "actions": [
      {
        "title": "Submit",
        "type": "Action.Submit"
      }
    ],
    "body": [
      {
        "text": "Input 1",
        "type": "TextBlock"
      },
      {
        "id": "InputOne",
        "placeholder": "Input 1 Placeholder",
        "type": "Input.Number",
        "value": 10
      },
      {
        "text": "Input 2",
        "type": "TextBlock"
      },
      {
        "id": "InputTwo",
        "placeholder": "Input 2 Placeholder",
        "type": "Input.Number",
        "value": -10
      },
      {
        "text": "Input 3",
        "type": "TextBlock"
      },
      {
        "id": "InputThree",
        "placeholder": "Input 3 Placeholder",
        "type": "Input.Number",
        "value": 0
      }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
~~~
4. See that the third input is not displaying the expected value 

# Likely cause
It looks like Adaptive Card's `Input` class's `parse` method uses the `getStringValue` utility to set the input's default value. The function uses a ternary to either return the value set in the Adaptive Card JSON as a string or the default value which would be `undefined`. In the case of the value being `0`, the `getStringValue` function would return `undefined`.

**[Input Parse Method](https://github.com/microsoft/AdaptiveCards/blob/5c1114871186618bb3a2195a85e01b04c55788f0/source/nodejs/adaptivecards/src/card-elements.ts#L2902)**
```javascript
parse(json: any, errors?: Array<HostConfig.IValidationError>) {
    super.parse(json, errors);

    this.id = Utils.getStringValue(json["id"]);
    this.defaultValue = Utils.getStringValue(json["value"]);

    if (AdaptiveCard.useBuiltInInputValidation) {
        let jsonValidation = json["validation"];

        if (jsonValidation) {
            this.validation.parse(jsonValidation);
        }
    }
}
```

**[Get String Value Method](https://github.com/microsoft/AdaptiveCards/blob/5c1114871186618bb3a2195a85e01b04c55788f0/source/nodejs/adaptivecards/src/utils.ts#L11)**
```javascript
export function getStringValue(obj: any, defaultValue: string = undefined): string {
    return obj ? obj.toString() : defaultValue;
}
```

# Possible Fix
The `getStringValue` method would likely have to be changed to check if the value is not undefined or equal to zero.

```javascript
export function getStringValue(obj: any, defaultValue: string = undefined): string {
    return (typeof obj !== 'undefined') ? obj.toString() : defaultValue;
}
```

**Comment by matthidinger** [comment]
Thanks for the detailed report!

**Comment by paulcam206** [comment]
What a great bug! Thanks for filing!

**Comment by shalinijoshi19** [comment]
@RebeccaAnne could you take a look while David is OOF.. Thanks!

**Comment by tdurnford** [comment]
Thanks for the fix!
