### ISSUE TITLE
Issue with text color of adaptive cards changing by teams theme

### ISSUE THREAD

**Issue by bgert** [microsoft/AdaptiveCards#3244]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* JavaScript

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards?
Author
If you're an author, who are you sending cards to?
Either DMs or group chats on MS teams
# Version of SDK
1.0
What version are you using? Ex: NuGet 1.0.2, or latest master, etc...
Issue happens both the current version of the botbuilder framework with ```CardFactory.adaptiveCard()``` and with the direct importing of the adaptivecards package and declaring the adaptive card as:
```
var companyCard = new AdaptiveCards.AdaptiveCard();
companyCard.parse(card);
```
# Issue
When I set the text of an adaptive card to light (white) it will appear white on the default teams theme and the high contrast but will invert to black on the teams dark theme and therefore not be readable.
The screen shots I posted are of the same card with and without a background image that I'm using as a background color for the cards (#001F3D)
<img width="492" alt="Screen Shot 2019-07-18 at 10 54 38 AM" src="https://user-images.githubusercontent.com/45300745/61473209-950fe900-a94b-11e9-9ad4-dc91ff3d29ac.png">
<img width="488" alt="Screen Shot 2019-07-18 at 10 55 46 AM" src="https://user-images.githubusercontent.com/45300745/61473211-950fe900-a94b-11e9-8936-fad317a9c482.png">
<img width="489" alt="Screen Shot 2019-07-18 at 10 56 00 AM" src="https://user-images.githubusercontent.com/45300745/61473212-950fe900-a94b-11e9-962f-d4aef38f6cd8.png">
<img width="484" alt="Screen Shot 2019-07-18 at 10 56 05 AM" src="https://user-images.githubusercontent.com/45300745/61473213-950fe900-a94b-11e9-9aa3-b1f6563bfac3.png">
<img width="497" alt="Screen Shot 2019-07-18 at 10 56 29 AM" src="https://user-images.githubusercontent.com/45300745/61473214-950fe900-a94b-11e9-9fe0-b63ce3eec9b4.png">
<img width="490" alt="Screen Shot 2019-07-18 at 10 56 34 AM" src="https://user-images.githubusercontent.com/45300745/61473215-950fe900-a94b-11e9-835c-0b8feb12c273.png">

As you can see the default and high contrast themes work as intended, but the dark theme inverts the white to black which is detrimental in this instance. 

 . The JSON is:
```
let card = CardFactory.adaptiveCard(
            {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "Container",
                        "items": [
                            {
                                "type": "TextBlock",
                                "size": "Medium",
                                "weight": "Bolder",
                                "text": "Feature not active",
                                "color": "Light"
                            }
                        ]
                    },
                    {
                        "type": "Container",
                        "items": [
                            {
                                "type": "TextBlock",
                                "text": "This version does not support imperatives.",
                                "wrap": true,
                                "color": "Light"
                            }
                        ]
                    },
                    {
                        "type": "Image",
                        "url": "https://raw.githubusercontent.com/link-works-but-has-repo-names-I-cant-share",
                        "size": "Small",
                        "horizontalAlignment": "Right",
                        "spacing": "None"
                    }
                ],
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "version": "1.0",
                "backgroundImage": "https://raw.githubusercontent.com/link-works-but-has-repo-names-I-cant-share"
            }
        );
```

**Comment by bgert** [comment]
I forgot to add. This issue happens wether or not you are on dark theme when the card is sent or you switch into dark theme after it is sent.

**Comment by oettingerj** [comment]
> detrimental in this instance

do not mess with this guy's adaptive cards

**Comment by matthidinger** [comment]
Thanks for the report on this. It seems to be an issue on within the Teams app so I'm working with them to see what we can do

**Comment by shalinijoshi19** [comment]
@jjustinms FYI.

**Comment by shalinijoshi19** [comment]
@siduppal can your team help follow up from the Teams side? Thanks

**Comment by shalinijoshi19** [comment]
@siduppal / @susanshen96 could you help take a look at this real quick please?

**Comment by wehnicde** [comment]
is there any progress?

**Comment by vman** [comment]
Adaptive cards rendering in Teams Dark theme on Android devices is still an issue. They are being rendered in the default theme.

**Comment by susanshen96** [comment]
@wehnicde - The fix for desktop has been checked in - it should take around two weeks for the change to manifest. 
@vman - Just logged a bug with our mobile team, will update when the fix is made.

**Comment by slinehan** [comment]
@susanshen96 I am still seeing this behavior in teams.  Was there anything that needed to be done on the Adaptive Card side to address this or should Teams be properly handling it with no changes?

**Comment by susanshen96** [comment]
@slinehan Teams should be handling this - I checked on desktop and it seems that the 'light' color is being handled properly on dark theme. Are you still seeing this on desktop?

**Comment by cameron0208** [comment]
Still experiencing this issue. Is there any update?

**Comment by slinehan** [comment]
I still see this as well and here is an example in the latest Teams.  Maybe my expectations are wrong but here it is in normal color scheme, dark and then high contrast

Normal
![image](https://user-images.githubusercontent.com/30914792/101093771-f2c4c580-3580-11eb-81d4-b2b77170f651.png)

Dark
![image](https://user-images.githubusercontent.com/30914792/101093846-14be4800-3581-11eb-8fe0-0c56cc04379e.png)

High Contrast
![image](https://user-images.githubusercontent.com/30914792/101093937-34557080-3581-11eb-85eb-09339967dd56.png)

I had expected that in Dark mode the black text would be white or at least a readable color.  You will notice in Dark that the gray and black text does not transform and is almost unreadable.

Thanks,

-Steve

**Comment by susanshen96** [comment]
@slinehan - are you using a test client by any chance? In my desktop client, after I send an adaptive card with a Textblock containing text in "light" color, the text is white in dark mode. If you are not, would you be able to paste the JSON for that Textblock so that I can test it out on my client? Thanks! 

![image](https://user-images.githubusercontent.com/10697383/101097162-9019fc80-3575-11eb-8b35-3cb23f84b26f.png)

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4590
