### ISSUE TITLE
Adaptive card is coming as icon in skype

### ISSUE THREAD

**Issue by roshnig** [microsoft/AdaptiveCards#3253]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards?

If you're an author, who are you sending cards to?

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

# Issue

Explain your issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards).

**Comment by roshnig** [comment]
Hi,

 In skype bot, we have created an adaptive card for response. In mac, it is coming properly but in windows laptop it is coming as an icon. I am not able to see card here. How can I fix this issue for window laptops
![Capture](https://user-images.githubusercontent.com/19589981/61786175-0bf22980-ae05-11e9-8071-c9857b5d1867.PNG)

**Comment by andrewleader** [comment]
Hi roshnig, for Skype issues, please reach out to the Bot Framework: https://github.com/Microsoft/botframework-sdk/issues
