### ISSUE TITLE
[UWP] Spacing/separator are ignored on Image

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#3254]
# Platform

* UWP

# Version of SDK

Visualizer version 1907.11

# Issue

Spacing and separator properties get ignored on an image

```json
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "Publish Adaptive Card schema"
        },
        {
            "type": "Image",
            "url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg",
"separator": true,
"spacing": "medium"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

Expected (.NET) | Actual (UWP)
--|--
![image](https://user-images.githubusercontent.com/13246069/61816238-cfbcca00-ae00-11e9-9198-e48003790457.png) | ![image](https://user-images.githubusercontent.com/13246069/61816219-c895bc00-ae00-11e9-943c-db684c9cc153.png)

**Comment by shalinijoshi19** [comment]
@almedina-ms can you take a stab at this please? thanks!

**Comment by almedina-ms** [comment]
Adding more information, only with size "auto" this behaviour occurs, stretch and all other image sizes don't behave like this
