### ISSUE TITLE
.NET MAUI Renderer SDK

### ISSUE THREAD

**Issue by productboard-ac** [microsoft/AdaptiveCards#3255]
# Summary
Support Xamarin Forms! Xamarin Forms apps currently have no way to render Adaptive Cards. Just like we support UWP/Android/ReactNative/etc, we should support Xamarin Forms!

# Requirements

* P0: Can render Adaptive Card
* P0: Can handle actions
* P1: Can extend render and add custom elements
* P1: Can custom style elements

# Spec/schema

After the proposal process, update this with a link to the spec PR.

# Proposed changes
We add a new renderer library for Xamarin Forms

# Example
Provide an example of rendering cards from Xamarin

**Comment by productboard-ac** [comment]
Link to feature: https://adaptivecards.productboard.com/feature-board/planning/features/1961753

**Comment by shalinijoshi19** [comment]
@almedina-ms assigning to you for driving. thanks

**Comment by davidwoolbright** [comment]
How's this feature coming? If there's anything I can do to help, I'd be glad to.

The company I work for just built a tablet app, using Xamarin Forms, for their internal users and a web site with the same functionality for their external users. 

I ran across Adaptive Cards and this issue in particular, and thought it might be interesting if we could design the front end using the design tool and have it rendered appropriately by the hosting application.

I'm not sure if that would be possible but I'm willing to help if like.

**Comment by almedina-ms** [comment]
Hello @davidwoolbright 

Thank you for your interest in the Xamarin Forms renderer library

We're currently working on the bindings of our current ios and android renderers for native xamarin, once we have a solid base then we'll continue on the development of this feature. I started prototyping this feature so if you'd like to check it out just ask me and I can share it with you

**Comment by davidwoolbright** [comment]
I'd like to see it.

Is it the XamarinFormsRenderer branch?

Do you have a list of what's been done and what needs to be done to complete this feature?

David 
⁣

**Comment by almedina-ms** [comment]
> 
> I'd like to see it. Is it the XamarinFormsRenderer branch? Do you have a list of what's been done and what needs to be done to complete this feature? David ⁣
> […](#)
> On Nov 25, 2019, 5:14 PM, at 5:14 PM, almedina-ms ***@***.***> wrote: Hello @davidwoolbright Thank you for your interest in the Xamarin Forms renderer library We're currently working on the bindings of our current ios and android renderers for native xamarin, once we have a solid base then we'll continue on the development of this feature. I started prototyping this feature so if you'd like to check it out just ask me and I can share it with you -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#3255 (comment)](https://github.com/microsoft/AdaptiveCards/issues/3255#issuecomment-558383681)

The branch which is more up-to-date is user/almedina-ms/XamarinPrototyping but this was still a very rough prototype which found a blocking issue because we have 3 different projections of the same code and the same information but that are not interchangeable unless we wrap them

**Comment by davidwoolbright** [comment]
What can I do to help?

**Comment by almedina-ms** [comment]
I'm not 100% sure how experienced are you around working with native Xamarin and Xamarin.Forms or if you have made a Xamarin.Forms control before. If you could share some of that information with me it would be great

For the inmediate list of tasks that come in my mind and that are really abstract are:
* Check that card rendering for Android and UWP is working as expected
* Fixing the iOS control (something broke when I was trying to implement actions)
* Coming up with a fix for the object model wrappers
* Add more functionality to the test app (As far as I remember cards in android and uwp were being able to be rendered, we just hit the wall when the information returned by the events was not the same between the three platforms)

Finally, as we're making a control I think you would be a great partner and we would love to hear your proposals and feedback for the contents of the control, what would you like to include when you define it, how and why as we would get first hand information on how users would consume our library/control

> 
> What can I do to help?
> […](#)
> On Nov 26, 2019, 10:43 AM, at 10:43 AM, almedina-ms ***@***.***> wrote: > > I'd like to see it. Is it the XamarinFormsRenderer branch? Do you have a list of what's been done and what needs to be done to complete this feature? David ⁣ > […](#) > On Nov 25, 2019, 5:14 PM, at 5:14 PM, almedina-ms ***@***.***> wrote: Hello @davidwoolbright Thank you for your interest in the Xamarin Forms renderer library We're currently working on the bindings of our current ios and android renderers for native xamarin, once we have a solid base then we'll continue on the development of this feature. I started prototyping this feature so if you'd like to check it out just ask me and I can share it with you -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#3255 (comment)]([#3255 (comment)](https://github.com/microsoft/AdaptiveCards/issues/3255#issuecomment-558383681)) The branch which is more up-to-date is user/almedina-ms/XamarinPrototyping but this was still a very rough prototype which found a blocking issue because we have 3 different projections of the same code and the same information but that are not interchangeable unless we wrap them -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#3255 (comment)](https://github.com/microsoft/AdaptiveCards/issues/3255#issuecomment-558716483)

**Comment by Edwardfelix08** [comment]
Hi @almedina-ms,

Is this feature available in Xamarin. 
If "Yes", then is there a document to refer to.
If "No", then when can we expect it to be released.

Thanks 
Edward

**Comment by almedina-ms** [comment]
> Hi @almedina-ms,
> 
> Is this feature available in Xamarin.
> If "Yes", then is there a document to refer to.
> If "No", then when can we expect it to be released.
> 
> Thanks
> Edward

Good morning, Edward:

We are currently investigating on the best approach to take for the creation of this renderer. We prototyped a renderer version using our existing android and iOS renderers projected into a native Xamarin libraries but we got stuck on iOS as it didn't deliver on the experience we want to give our developers. We're currently prototyping on some work was that made some years ago but it is still an incomplete version of a rendering library for 1.0 so I can't give an exact date for the library to be released. 

If you are interested in this feature please vote for it in [our product board portal] so we can prioritize this work (https://portal.productboard.com/adaptivecards/1-adaptive-cards-features/c/28-xamarin-and-xamarin-forms-sdks )

**Comment by nielscup** [comment]
@almedina-ms Are you still working on Adaptive Cards for Xamarin.Forms? I would like to do a prototype for AC in our app. Can you tell me which branch I can use best to start with Adaptive Cards in Xamarin.Forms?

**Comment by Pepsi1x1** [comment]
Where does this work sit in terms of priorities? I can see the last commit was to the perf test branch back in February. It would be great to see some progress on this and have confidence this may end up in main.

This is an important component for our app and we're blocked on providing a mobile implementation of our chatbot on Xamarin.

**Comment by Pepsi1x1** [comment]
WIth the changes in the linked PR there are only a few outstanding changes to bring this up to the 1.0 feature set.

TextInputs - Multiline editor
ChoiceSet - combobox (This should be rendered as an XF picker)
ToggleInputs - should move over to the CheckBox control added as part of this PR
RadialImages (Person type) - I don't see this as a blocker, we could write a Xamarin custom renderer or wait for XF 4.8

Xamarin Forms 4.8 will include Brush support which should significantly reduce the amount of pre-processors.

@shalinijoshi19 @almedina-ms is this enough to get it back out of the backlog and onto the roadmap?

**Comment by Pepsi1x1** [comment]
Why was this issue closed?

**Comment by nielscup** [comment]
So we decided to create bindings for Adaptive cards ourselves and we got it up and running within a week or two, Android an iOS. I don't understand why @almedina-ms got stuck on this... I don't work for that particular project/customer anymore but I can ask if they are willing to put the bindings on github.
