### ISSUE TITLE
[Designer] Version Restriction

### ISSUE THREAD

**Issue by jeffhoang** [microsoft/AdaptiveCards#3260]
# Platform
* JavaScript

# Version of SDK
1.1

# Version of Adaptive Cards Designer
0.7.1

# Issue / Feature Request

Is there a way to restrict the adaptive cards designer to only support a certain adapative cards version?  We're still on version 1.1 and don't want our developers to use features beyond this.

**Comment by matthidinger** [comment]
Thanks for the feedback. This is something that is being worked on, hopefully we'll have it finished it shortly. In the mean time, can you try this code to at least restrict items from the toolbar?

```js
let designer = new ACDesigner.CardDesigner(hostContainers);
Adaptive.AdaptiveCard.elementTypeRegistry.unregisterType("RichTextBlock");
ACDesigner.CardDesignerSurface.cardElementPeerRegistry.unregisterPeer(Adaptive.RichTextBlock);
 
Adaptive.AdaptiveCard.elementTypeRegistry.unregisterType("ActionSet");
ACDesigner.CardDesignerSurface.cardElementPeerRegistry.unregisterPeer(Adaptive.ActionSet);
 
designer.attachTo(document.getElementById("designerRootHost"));
 
Adaptive.AdaptiveCard.actionTypeRegistry.unregisterType("Action.ToggleVisibility");
    ACDesigner.CardDesignerSurface.actionPeerRegistry.unregisterPeer(Adaptive.ToggleVisibilityAction);
```

**Comment by shalinijoshi19** [comment]
@dclaux, can this be closed now?

**Comment by dclaux** [comment]
@shalinijoshi19  no, there is still a lot to do to actually make the designer version aware. What Matt suggests above is a way to de-register elements, but that doesn't fully solve the problem.

**Comment by shalinijoshi19** [comment]
Thanks; Do we have a quick one-pager/spec consolidating the versioning requirements we are targeting  for the designer?

**Comment by dclaux** [comment]
We don't. By the time I have a PR for the feature, I will open an issue with a description of what it entails. But it's fairly simple:
- Designer has a version selector
- Cards are parsed per the selected version (e.g. don't parse the "minHeight" property if selected version isn't 1.2 or greater)
- Cards are serialized to JSON per the selected version  (e.g. don't serialize the "minHeight" property if selected version isn't 1.2 or greater)
- Property sheet only shows properties that existed in the selected version
- Toolbox only shows elements that were available in selected version

**Comment by shalinijoshi19** [comment]
Thanks. I've also captured this to the internal OneNote I'd created for tracking.
