### ISSUE TITLE
Designer puts title in Input.Text

### ISSUE THREAD

**Issue by v-kydela** [microsoft/AdaptiveCards#3267]
# Issue

![image](https://user-images.githubusercontent.com/41968495/62086875-a17e2680-b214-11e9-991d-7cfd3af333c0.png)

To reproduce:

1. Drag an Input.Text from the left toolbox onto the card
2. Observe the erroneous title field in the card's JSON

Expected:

Input.Text should not have a title field

**Comment by matthidinger** [comment]
@dclaux I've also seen this, can you take a look when you're back?
