### ISSUE TITLE
Javascript angular 7 Actions are not getting rendered  

### ISSUE THREAD

**Issue by nibinki** [microsoft/AdaptiveCards#3270]
# Platform  JavaScript

# Author or host both

# Version of SDK 1.2

# Issue

I am using Angular 7 and trying to render card as mentioned in documents . Strangely , the generated HTML doesn't contain any Action related items. I am trying to use 'Show Card' which contains Factset . Below is my json . i am using default hostConfig and installed latest 1.2 version from npm

import * as AdaptiveCards from 'adaptivecards';
var   adaptiveCard: any;
this.adaptiveCard = new AdaptiveCards.AdaptiveCard();

 let json="{" +
						"    \"$schema\": \"http://adaptivecards.io/schemas/adaptive-card.json\"," +
						"    \"type\": \"AdaptiveCard\"," +
						"    \"version\": \"1.2\"," +
						"    \"body\": [" +
						"        {" +
						"            \"type\": \"TextBlock\"," +
						"            \"text\": \"Message Type\"," +
						"            \"weight\": \"Bolder\"," +
						"            \"size\": \"Medium\"," +
						"            \"color\": \"Dark\"," +
						"            \"horizontalAlignment\": \"Left\"" +
						"        }," +
						"        {" +
						"            \"type\": \"TextBlock\"," +
						"            \"text\": \"Identifies each message version number, message class, message function and  the transaction originator.\"," +
						"            \"wrap\": true" +
						"        }" +
						"            ]," +
						"            \"actions\": [" +
						"                {" +
						"                    \"type\": \"Action.ShowCard\"," +
						"                    \"title\": \"Show Details\"," +
						"                    \"card\": {" +
						"                        \"type\": \"AdaptiveCard\"," +
						"                        \"$schema\": \"http://adaptivecards.io/schemas/adaptive-card.json\"," +
						"                        \"body\": [" +
						"                            {" +
						"                                \"type\": \"FactSet\"," +
						"                                \"facts\": [" +
						"                                    {" +
						"                                        \"title\": \"Business Alias\"," +
						"                                        \"value\": \"Message Code, Message Type Indicator\"" +
						"                                    }," +
						"                                    {" +
						"                                        \"title\": \"Canonical Name\"," +
						"                                        \"value\": \"MTI\"" +
						"                                    }," +
						"                                    {" +
						"                                        \"title\": \"Field Type\"," +
						"                                        \"value\": \"string\"" +
						"                                    }," +
						"                                    {" +
						"                                        \"title\": \"Field Length\"," +
						"                                        \"value\": \"4\"" +
						"                                    }," +
						"                                    {" +
						"                                        \"title\": \"Pattern\"," +
						"                                        \"value\": \"N/A\"" +
						"                                    }," +
						"                                    {" +
						"                                        \"title\": \"Value Transalation\"," +
						"                                        \"value\": \"Y\"" +
						"                                    }," +
						"                                    {" +
						"                                        \"title\": \"Data Policy\"," +
						"                                        \"value\": \"N/A\"" +
						"                                    }," +
						"                                    {" +
						"                                        \"title\": \"Data Retention\"," +
						"                                        \"value\": \"2 Years\"" +
						"                                    }," +
						"                                    {" +
						"                                        \"title\": \"Classification\"," +
						"                                        \"value\": \"N/A\"" +
						"                                    }" +
						"                                ]" +
						"                            }" +
						"                        ]" +
						"                    }" +
						"                }" +
						"                " +
						"    ]" +
						"}";

this.adaptiveCard.parse(JSON.parse(json));
this.renderedCard1 = this.adaptiveCard.render();
console.log(this.renderedCard1.innerHTML);

After running this i am getting this as innertHTML which doesn't contain any action item . it shows show detail button but not showing any Factset , button is clickable but nothing happens . Both textblocks are visible though
Attaching html generated . Please let me know if this is a bug or something to with angular or my code.
[issue.zip](https://github.com/microsoft/AdaptiveCards/files/3445991/issue.zip)

**Comment by matthidinger** [comment]
Just to make sure the string concat is working can you JSON.parse(json), and then JSON.stringify it again and paste it into the Adaptive Cards Designer and make sure it renders as you expected?

**Comment by nibinki** [comment]
i tried that  it is showing properly and verified with card designer. I also printed this.adaptiveCard after parsing json and i can see _actionCollection object . PFA the screenshot

![image](https://user-images.githubusercontent.com/36858559/62186632-95b17200-b384-11e9-86d9-90bc84ebcc3d.png)

![image](https://user-images.githubusercontent.com/36858559/62186693-c09bc600-b384-11e9-999c-ccbc7f81556e.png)

but the rendered item list only shows 2 textblocks

![image](https://user-images.githubusercontent.com/36858559/62186868-39028700-b385-11e9-8966-60d9caff837d.png)

infact i tried with multiple json available in samples and every where there is no actions only textblocks are visible in rendered html

Please help

**Comment by matthidinger** [comment]
Hi @nibinki, I'm not familiar enough with Angular 7 to help with this without a repro. Can you include a small repro project or include any other information? If the DOM is inspected has the elements then it seems the Adaptive Card Renderer is working is correctly, and something is getting dropped in Angular?

**Comment by BalajiR** [comment]
@nibinki, `ShowCard` ActionItems' contents are added in the DOM only when such action actually happens (say, button click). Not sure how you are adding the card to DOM in your Angular app, but when i tried, the JSON you shared works -> able to see the fact set card on click of `show details` button.

**Example**: https://stackblitz.com/edit/angular-7-master-euwiqu

**Comment by nibinki** [comment]
@BalajiR thanks for the help ..i am using angular 7.2.0. my problem is because of ( i think) zone.js . i debugged ur code and i can see entire execution of rendering is happening in card.element.js of adaptivecards , however in my case during rendering of action items it reaches this point

ActionButton.prototype.render = function (alignment) {
        var _this = this;
        this.action.render();
        this.action.renderedElement.style.flex = alignment === Enums.ActionAlignment.Stretch ? "0 1 100%" : "0 1 auto";
        this.action.renderedElement.onclick = function (e) {
            e.preventDefault();
            e.cancelBubble = true;
            _this.click();
        };
        this.updateCssStyle();
    };

and while enabling onclick it is going to zone.js
desc.set = function (newValue) {
        // in some of windows's onproperty callback, this is undefined
        // so we need to check it
        var target = this;
        if (!target && obj === _global) {
            target = _global;
        }
        if (!target) {
         

After reaching this point only button is rendered while the whole factset is removed. Zone.js is by default added to angular projects , i am also using other dependencies but still not able to figure it out why factset is not rendered

**Comment by dclaux** [comment]
Hi @nibinki, as @BalajiR explained, the initial `render()` of your card will not actually render the **FactSet** because the **FactSet** belongs to the card of a **ShowCard** action. The card of a **ShowCard** action is rendered "just in time" as the end user clicks the associated button. In your case, that hasn't happened, therefore you will not see the DOM for the FactSet in the innerHtml.

**Comment by shalinijoshi19** [comment]
Hello @nibinki, closing this out for now. Please reopen if you continue to have questions for us.. Thanks!
