### ISSUE TITLE
[iOS] Input.Number value is not validated against min or max

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#3293]
# Platform

* iOS

# Version of SDK

master

# Issue

When using Input.Number, the value is not validated against the given min and max values

**Comment by RebeccaAnne** [comment]
Min/Max are marked as "may be ignored by some clients". iOS has some code that doesn't execute and does the wrong thing anyway that should probably be removed. We should consider whether min and max should be validated as part of the 1.3 input validation feature.

**Comment by shalinijoshi19** [comment]
This is being tracked by the Input Validation feature, #3081. Closing this out
