### ISSUE TITLE
[iOS] TextInput InlineAction with show card crashes

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#3295]
# Platform

* iOS

# Version of SDK

master

# Issue

If you add an inline action to a text input of type show card and click on it, the process crashes. ShowCard actions should not be allowed as inline actions and they shouldn't be tried to be rendered at all

**Comment by RebeccaAnne** [comment]
Probably should be fixed in the shared model.

**Comment by matthidinger** [comment]
@nesalang we should fix the crash, but we need a separate issue on whether or not this should be supported. I just looked in the Designer and it filters out Action.ShowCard, but it does include ToggleVisibility, which might be weird?
