### ISSUE TITLE
Fallback doesn't happen when url is missing for OpenUrl Action

### ISSUE THREAD

**Issue by nesalang** [microsoft/AdaptiveCards#3297]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

If you're an author, who are you sending cards to?

# Version of SDK

1.2.1

# Issue

url is required property for openURLAction, if url is not given, dropping the card is correct for previous version, but fallback should handle this case if SDK version is >= 1.2
```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "This card's action will open a URL"
        }
    ],
    "actions": [
        {
            "type": "Action.OpenUrl",
            "title": "Action.OpenUrl",
            "style": "default",
            "id": "firstGraphVTwo",
            "fallback": {
                    "type": "TextBlock",
                    "text": "Multiply-nested fallback works!",
                    "weight": "bolder",
                    "color": "good"
            }
        }
    ]
}

**Comment by RebeccaAnne** [comment]
https://github.com/microsoft/AdaptiveCards/issues/3154 tracks consistent behavior for required properties. As part of that work we should confirm whether missing required properties should trigger fallback.
