### ISSUE TITLE
UWP parser requires "type": "Column" when it's not necessary

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#330]
Accepted, task list: 

- [x] TypeScript
- [x] UWP (PR #555)
- [x] Android (PR #555)
- [x] iOS (PR #555)
- [x] .NET

The following payload will break the UWP parser

```json
{
   "type":"AdaptiveCard",
   "version":"1.0",
   "body":[
      {
         "type":"ColumnSet",
         "columns":[
            {
               "size":33,
               "items":[
                  {
                     "type":"Image",
                     "url":"https://unsplash.it/64?image=1027",
                     "size":"small",
                     "style":"person"
                  }
               ]
            },
            {
               "size":67,
               "contentVerticalAlignment":"center",
               "items":[
                  {
                     "type":"TextBlock",
                     "text":"Hi,",
                     "size":"large"
                  },
                  {
                     "type":"TextBlock",
                     "text":"MasterHip",
                     "size":"medium",
                     "isSubtle":true
                  }
               ]
            }
         ]
      }
   ]
}
```

It breaks simply because each column item doesn't have `"type": "Column"` specified which is redundant and unnecessary, since ColumnSet's column property is explicitly an array of Column type... the Web visualizer doesn't break on this.

**Comment by riarenas** [comment]
According to http://adaptivecards.io/documentation/#column. The type property is required.

**Comment by riarenas** [comment]
Didn't mean to close.

**Comment by riarenas** [comment]
Adding Schema label for further review. Simpliifying this seems like a good idea.

**Comment by matthidinger** [comment]
My vote is that we keep the Type property required for the time being. It makes readability of a large payload slightly easier

**Comment by anbare** [comment]
Why not just use the Type property for the samples, but make the property itself optional? Who cares what devs are sending when they programmatically create their payloads. Might as well allow them to save space by not providing properties that are meaningless except when visually viewing the payload itself.

**Comment by dclaux** [comment]
If we think we could have a different type of column in the future, then I vote for "type" being required. Otherwise, omitting "type" when the type is implicit is a good simplification. We don't have "type": "Fact" for a fact in a FactSet for instance.

**Comment by dclaux** [comment]
@anbare I notice the contentVerticalAlignment property in the payload above. Is it a proposed new feature?

**Comment by anbare** [comment]
@dclaux  The new height spacing model that we recently added solves requests for being able to center content vertically inside a column. It could be a nice addition to have a contentVerticalAlignment property so you don't have to add two empty elements to achieve the vertical centering of some content inside a column, but it's not technically required.

**Comment by dclaux** [comment]
@anbare got it, thanks.

**Comment by matthidinger** [comment]
DECISION: Any *Set that takes on a single item type, the type will be implicit if left out. 

ImageSet, FactSet, ColumnSet, should all **not require** children type properties.

- [ ] TypeScript
- [ ] UWP
- [ ] Android
- [ ] iOS
- [ ] .NET

**Comment by matthidinger** [comment]
@anbare can you confirm this is fixed in .NET now? There's a test payload for it

~samples\Tests\ColumnSet.ImplicitColumnType.json

**Comment by anbare** [comment]
It's very possible that my changes actually broke that scenario, since as part of adding support for parsing the Adaptive Card I had to ensure it requires the "type": "AdaptiveCard" to be present, and I simply made the "type" property required in the shared Element class.

I'll check it out

**Comment by khouzam** [comment]
All works properly.
