### ISSUE TITLE
[Designer] In ChoiceSet, "Add a new choice" deletes titles of existing choices

### ISSUE THREAD

**Issue by choupete** [microsoft/AdaptiveCards#3306]
# Platform

N/A

# Issue

If I have one or more existing choices listed using the designer, each with their own respective "title" fields, then clicking "Add a new choice," and then typing in something for the "Title" or "Value" field of this new choice (in the Element Properties tab) will cause the titles of existing choices to automatically disappear in the JSON.

```
{
            "type": "Input.ChoiceSet",
            "placeholder": "Placeholder text",
            "style": "expanded",
            "id": "asdf",
            "choices": [
                {
                    "title": "One",
                    "value": "choice1"
                },
                {
                    "title": "Two",
                    "value": "choice2"
                }
            ]
        }
```

Result:

```
{
            "type": "Input.ChoiceSet",
            "placeholder": "Placeholder text",
            "style": "expanded",
            "id": "asdf",
            "choices": [
                {
                    "value": "choice1"
                },
                {
                    "value": "choice2"
                },
                {
                    "title": "Three",
                    "value": "choice3"
                }
            ]
        }
```
(Typing in the Title or Value field automatically deletes the "title" of the previous choices)

**Comment by matthidinger** [comment]
@dclaux this seems to be a designer glitch. I was able to repo it pressing the "Add a new Choice" button

@choupete  thanks for reporting!

**Comment by dclaux** [comment]
Yes, bug... will look into it.
