### ISSUE TITLE
Adaptive Cards is not wrapping Text Block

### ISSUE THREAD

**Issue by tdurnford** [microsoft/AdaptiveCards#3311]
# Platform

* JavaScript

# Author or host
Host
Web Chat

# Version of SDK
Adaptive Cards v1.2

# Issue

Adaptive Cards is setting the Text Block `white-space` css style option to `nowrap` even though  Text Blocks should wrap text by default according to the host config [documentation](https://docs.microsoft.com/en-us/adaptive-cards/rendering-cards/host-config#textblockconfig). This is causing text in the card to overflow outside the Adaptive Card container. I've tried setting the Text Block wrap property in the host config to `true`; however, that didn't seem to have any effect.

![image](https://user-images.githubusercontent.com/17039790/62493384-cf6be980-b785-11e9-8a6b-ff777cf4e2f7.png)

#### Web Chat
![image](https://user-images.githubusercontent.com/17039790/62493284-903d9880-b785-11e9-89bb-654835ed3204.png)

#### Web Chat
![image](https://user-images.githubusercontent.com/17039790/62493281-8e73d500-b785-11e9-821d-1c68b21cb936.png)

#### Adaptive Cards Designer
![image](https://user-images.githubusercontent.com/17039790/62495112-ddbc0480-b789-11e9-84dc-dd8feb717499.png)

### Adaptive Card JSON
```json
{
    "$schema": "https://microsoft.github.io/AdaptiveCards/schemas/adaptive-card.json",
    "version": "1.0",
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "text": "## Basic formatting\r\nParagraphs must be separated by a blank line. Basic formatting of *italics* and **bold** is supported."
        }
    ]
}
```

**Comment by shalinijoshi19** [comment]
@matthidinger, do you know if webchat is using our JS library?

**Comment by shalinijoshi19** [comment]
@dclaux / @matthidinger FYI.

**Comment by dclaux** [comment]
TextBlocks do not wrap by default. The `wrap` property has to be explicitly set to `true`. This is by design and has been true since the inception of AC (whether that was the right call is another story.)
