### ISSUE TITLE
Adaptive Cards Carousel not displaying in Teams

### ISSUE THREAD

**Issue by dcmesh** [microsoft/AdaptiveCards#3315]
# Platform

.NET Bot Framework

# Author or host

Bot is hosted in Azure, displayed to Teams users.

# Version of SDK

AdaptiveCards v1.2.1 (also an issue on 1.2.0 and 1.0.0)

# Issue

In my bot, I dynamically generate a list of Adaptive Cards and return them in a Carousel format. In both the Bot Framework Emulator and Azure Web Chat, the Carousel is displayed normally. However, when I test the bot in the Teams Web App, instead of showing the cards, I get the following error: "Sorry, it looks like something went wrong." When I went to debug the code, I discovered that it could not get past the ` await turnContext.SendActivityAsync(reply, cancellationToken);` line.

This is how I create the list of Adaptive Cards: 

            var attachments = new List<Attachment>();
            var reply = MessageFactory.Carousel(attachments);
            for (int i = 0; i < limit; i++)
            {
                AdaptiveCard card = new AdaptiveCard();
                card.Body.Add(new AdaptiveTextBlock()
                {
                    Text = $"{element0}, {element1}\n",
                    Size = AdaptiveTextSize.Large,
                    Wrap = true
                });
                card.Body.Add(new AdaptiveTextBlock()
                {
                    Text = $"{element2}\n" +
                    $"El3 : {element3}\n",
                    Size = AdaptiveTextSize.Medium,
                    Wrap = true
                });
                var adaptiveCardAttachment = new Attachment()
                {
                    ContentType = "application/vnd.microsoft.card.adaptive",
                    Content = card
                };
                reply.Attachments.Add(adaptiveCardAttachment);
              }
              await turnContext.SendActivityAsync(reply, cancellationToken);

**Comment by shalinijoshi19** [comment]
@jjustinms are you able to take a first stab at this at all to determine if this is a Teams issue or an Adaptive Cards bug?

**Comment by dcmesh** [comment]
Just for clarification, each elementX in the code above (i.e. `element0`) is a string variable that has already been assigned.

**Comment by jjustinms** [comment]
@billbliss @siduppal - looks like its for Teams web (atleast for now) - can you pls have a look.

**Comment by dcmesh** [comment]
After a bit more testing, I figured out what the issue was. It seems that Microsoft Teams does not allow more than 10 Adaptive Card Attachments in a Carousel at a time, and throws an error if there are more. The only documentation I could find that pertained to any such limitations referred only to email attachments, and didn't mention Adaptive Cards. 

It would be great if the documentation of either Adaptive Cards or Teams was updated to reflect this restriction. Also, would there be a way of manually disabling this restriction (a question for the Teams side)? Such a feature would be great.

**Comment by droidriz** [comment]
@dcmesh Yes we can't have more than 10 adaptive cards inside carousel.
at first we also had this requirement due to this limitation we are limiting the cards to 10 for carousel.
Source:- https://stackoverflow.com/questions/52428158/maximum-number-of-adaptive-cards-on-carousel-microsoft-teams

Also @dcmesh  recently i am not able to see the cards when i limit it to 3 its being displayed or else an error possibly due to payload size. but it was working earlier something has changed in connector side.  have a look at this issue
https://github.com/microsoft/BotFramework-Services/issues/103

**Comment by shalinijoshi19** [comment]
@nesalang can you please help follow up on this investigation? Thanks!

**Comment by nesalang** [comment]
@dcmesh and @droidriz 
thanks for the feedback. we value it. I brought this up to the teams.

There is hard limit on overall message size, so depending on the size of a card, the number of cards that can be sent per message is variable.
[this](https://microsoftteams.uservoice.com/forums/908686-bug-reports/suggestions/38572720-adaptive-cards-carousel-not-displaying-in-teams) is where the issue being tracked in Teams.
As this is Teams related issue, I will close it for now.

thank you.
