### ISSUE TITLE
Colors in HostConfig are rendered incorrectly when using 8 digit hex codes

### ISSUE THREAD

**Issue by DeeJayTC** [microsoft/AdaptiveCards#3320]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Author or host
Host

# Version of SDK
1.2.1
# Issue
When using 8 digit hex codes for RGBA in the host config the rendered color is different to the expected color. 

One example :

#53f950ad is a light greenish color in RGBA or a pink color in ARGB interpretation. 

The correct RGBA code for that would be: rgba(83,249,80,0.678) when inspecting the card background color its actually: background-color: rgba(197, 197, 173, 0.773). 

Either host config shouldn't accept 8 digit codes or render them correctly.

**Comment by paulcam206** [comment]
@DeeJayTC - is this still an issue in recent versions of the JS renderer? If so please feel free to reactivate...
