### ISSUE TITLE
Inconsistent AdaptiveImage expandability behavior in Teams across Windows and iOS

### ISSUE THREAD

**Issue by stpeteparadox** [microsoft/AdaptiveCards#3324]
**Platform**
.NET Bot Framework

**Author or host**
Bot is hosted in Azure, displayed to Teams users.

**Version of SDK**
AdaptiveCards v1.0  (higher versions unsupported in Teams)

**Issue**
Hi Microsoft AdaptiveCards Team,

We have previously posted this issue here ([https://github.com/MicrosoftDocs/msteams-docs/issues/388]), but it appears that your colleagues there may be too busy as no one has yet attempted to reproduce the issue.

Here is the problem: Teams "renders" an AdaptiveImage embedded in an AdaptiveCard in a different manner when accessed via Windows Desktop vs. iOS (we have not tested with other platforms). **An AdaptiveImage sent from a proactive bot to a channel and viewed with Teams on Windows is not expandable, whereas that same AdaptiveImage when viewed on iOS is expandable.**

_AdaptiveImage is not expandable:_
![image](https://user-images.githubusercontent.com/3724281/62775740-1b4ac580-badb-11e9-9c5e-fe8e66f2c641.png)

If the image is instead simply sent as a Teams message attachment, then the image is expandable on both Teams Windows and Teams iOS. However, for our purposes, we need to use an AdaptiveCard as we need all the rich formatting/structuring capabilities, so the attachment approach is not suitable.

_Image as msg attachment is expandable_
![image](https://user-images.githubusercontent.com/3724281/62775789-40d7cf00-badb-11e9-99e4-48f45b2f5463.png)

Pasted below are the sample code we use to test sending as an AdaptiveCard image, as well as as a basic image attachment.

The image used in both scenarios is simply a 1000x1000 placeholder. The important thing is that this image must be expandable within Teams on Windows in order for our users to be able to see/read/analyze the content--**it is otherwise too small**. The requirement for image expandability is effectively no different than the expandability functionality we already see for images sent by users themselves in Teams, or by a bot via the mentioned basic message attachment approach.

_**AdaptiveCard approach**_
```
card.Body.Add(new AdaptiveTextBlock()
{
  Text = "A title here",
  Size = AdaptiveTextSize.Large,
  Weight = AdaptiveTextWeight.Bolder,
  Wrap = true
});
card.Body.Add(new AdaptiveImage()
{
  Type = "Image",
  Size = AdaptiveImageSize.Auto,
  Style = AdaptiveImageStyle.Default,
  HorizontalAlignment = AdaptiveHorizontalAlignment.Center,
  Separator = true,
  Url = "https://via.placeholder.com/1000"
});
card.Body.Add(new AdaptiveTextBlock()
{
  Text = "A message here",
  Wrap = true
});
```

_**Basic message attachment approach**_
Attachment attachment = new Attachment()
```
{
  ContentType = "image/png",
  ContentUrl = "https://via.placeholder.com/1000"
};
```

If there is anything more we can provide that can help you to reproduce this issue/bug, please just let us know. Thank you for your help.

**Comment by stpeteparadox** [comment]
Here is the json for the adaptive card, in case of convenience:

`{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Large",
            "weight": "Bolder",
            "text": "A title here",
            "wrap": true
        },
        {
            "type": "Image",
            "horizontalAlignment": "Center",
            "separator": true,
            "url": "https://via.placeholder.com/1000"
        },
        {
            "type": "TextBlock",
            "text": "A message here: \n 1)  Sub-point 1 \n 2)  Sub-point  2 \n 3)  Sub-point 3 \n 4)  Sub-point 4 \n 5)  Sub-point 5",
            "wrap": true
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}`

**Comment by matthidinger** [comment]
@stpeteparadox I've reached out to the Teams folk to look into this inconsistency. Currently this isn't a feature in Adaptive Cards, but it sounds like a reasonable feature for a future release. We'll update you as soon as I hear

**Comment by paulcam206** [comment]
for reference, the original bug is MicrosoftDocs/msteams-docs#388

**Comment by shalinijoshi19** [comment]
@jjustinms, can you take a look please? thanks

**Comment by shalinijoshi19** [comment]
@siduppal / @VikrantSingh01 this looks to be something that we dont support in AdaptiveCards at the moment but something that needs tracking over on the Teams side looks like; Per @paulcam206's comment above the teams bug is  MicrosoftDocs/msteams-docs#388

**Comment by shalinijoshi19** [comment]
Closing this out since it's already being tracked by MicrosoftDocs/msteams-docs#388 on the teams side.
