### ISSUE TITLE
Associate a button with a text box for Ctrl+Enter behavior

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#333]
There should be a generic way to link a button to an input, so that when you press "Enter" or "Ctrl+Enter", the button is pressed. Given inputs already have id's, here's what I would propose (notice that **inputId** on the **action** is the new item):

![image](https://user-images.githubusercontent.com/13246069/45718333-8309c200-bb51-11e8-8e5e-010f26536960.png)

```json
      {
        "type": "TextBlock",
        "text": "Tell us more",
        "size": "medium"
      },
      {
        "type": "Input.Text",
        "id": "tellUsMore",
        "placeholder": "Explain in your own words",
        "isMultiline": true,
        "submitActionId": "SubmitFeedback"
      }

    ],

    "actions": [

      {
        "type": "Action.Submit",
        "id": "SubmitFeedback",
        "title": "Submit"
      }

    ]
```

Basically, if an input has a `submitActionId` assigned to it, then when the input receives the default "submit" action (like pressing enter), it invokes that action.

**Comment by anbare** [comment]
It would also work well for buttons like the following, where the button is below (part of the action bar).

![image](https://cloud.githubusercontent.com/assets/13246069/26746519/d31c2bec-47a4-11e7-9deb-afa5369633a1.png)

Therefore, the solution should be a generic way to link a button to an input. Given inputs already have id's, here's what I would propose (notice that **inputId** on the **action** is the new item):

```json
      {
        "type": "TextBlock",
        "text": "Tell us more",
        "size": "medium"
      },
      {
        "type": "Input.Text",
        "id": "tellUsMore",
        "placeholder": "Explain in your own words",
        "isMultiline": true
      }

    ],

    "actions": [

      {
        "type": "Action.Submit",
        "title": "Submit",
        "inputId": "tellUsMore"
      }

    ]
```

**Comment by matthidinger** [comment]
Toasts present an interesting problem given that inputs are currently limited to within the "action bar", which means linking them to actions would work perfectly fine. But I'm not sure how this would work given the current schema allows Inputs to be placed anywhere within the card, but actions are only permitted in the action bar. 

What do we do about an input in the body and associated to an action? The question applies to toasts as well as chat apps. 

Perhaps this is really a new type of action, or an action with an associated input? This would keep everything grouped in the action bar, and prevent linking an action to an input in the body of the card.

**Comment by anbare** [comment]
Why does that make any difference? The developer is simply saying "Wire this action up to the Enter press of a text box"

I don't think we need to restrict or enforce that the text box has to be visually next to the button. Devs already can do *anything* in their app, like having a text button on the top right invoke a button on the bottom left... but they probably don't, since that wouldn't make sense :)

**Comment by matthidinger** [comment]
Sorry I misinterpreted the ask, is this just about ctrl+enter or **also** the visual layout of putting a small button next to the input?

**Comment by anbare** [comment]
This one's just about ctrl+enter (since I believe this scenario is def desired where ctrl+enter would invoke a button that is NOT a small adjacent button).

For putting a small button next to the input I believe the best solution would be adding a "ImageButton" size option to the existing image sizes
