### ISSUE TITLE
[Cortana Accessibility] Allow borders on containers

### ISSUE THREAD

**Issue by shalinijoshi19** [microsoft/AdaptiveCards#3330]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Author or host
Host

# Version of SDK
1.2.0-beta1-201905.29017

# Issue

For high contrast requirements, we have to be able to draw a colored border around clickable items.  We originally had this around the entire card as this was the only thing we could draw a border around (as this is all one “card” element), but have been told this is not correct and we should only be highlighting the border around the actual clickable content.  While we’ve tried to see if there is a way to break down the visual tree to allow this, it doesn’t appear there is any clean way for us to hack this to make it work as required.
Here’s the json for reference:
```json
{
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "size": "small",
      "weight": "lighter",
      "isSubtle": true,
      "text": "Alarm",
      "spacing": "padding"
    },
    {
      "type": "Container",
      "items": [
        {
          "type": "TextBlock",
          "size": "extraLarge",
          "text": "3:52 PM"
        },
        {
          "type": "TextBlock",
          "size": "small",
          "weight": "lighter",
          "isSubtle": true,
          "text": "Only once",
          "spacing": "none",
          "separation": "none"
        }
      ],
      "selectAction": {
        "type": "Action.OpenUrl",
        "url": "ms-clock://alarms"
      }
    }
  ]
}
```
Ask:

We believe we could make this work if we were able to draw borders around containers – which is something it seems has been asked before (#2033 and #1890), but does not appear to ever been prioritized.

For now we will have to leave this accessibility issue open as we have no way to fix.  Hoping you can help prioritize this item for the next release (is there an ETA on this, btw?) so we can provide more information to that team on when we’ll be able to get  fix in place.

**Comment by shalinijoshi19** [comment]
Assigning to you @paulcam206 to investigate. Thanks

**Comment by shalinijoshi19** [comment]
Have not heard back from the Cortana team on this one. Removing from 1.2.3 investigations.

**Comment by shalinijoshi19** [comment]
@matthidinger / @paulcam206 - this is now not much of a priority for Cortana at this point. More interested in #3535

**Comment by paulcam206** [comment]
This is not currently on our roadmap.

**Comment by robross0606** [comment]
I'm super confused how "This is not currently on our roadmap" equates to "Closed as **completed**."
