### ISSUE TITLE
AdaptiveCard throws "Unable to reach app. Please try again" using Logic Apps and MS Teams

### ISSUE THREAD

**Issue by johno-a** [microsoft/AdaptiveCards#3334]
# Platform

- MS Teams,
- Flow
- Logic Apps

# Author or host

- Author sending cards from Logic App to MS Teams

If you're an author, who are you sending cards to?

- To MS Teams

# Version of SDK

Latest availabe in Logic Apps

# Issue

Explain your issue. If you just have a question, please post [on StackOverflow instead]

The problem we are facing is that the flow(using Logic Apps) does not wait for input from the user (to completing the adaptive card) when use the MS teams connector with the "Post your own adaptive card as the Flow bot to a user" action, so the flow completes almost immediate and then when the user clicks a button on the custom adaptive card the "Unable to reach app. Please try again" is shown on the card.

When we use the "Post a choice of options as the Flow bot: action" the Logic App waits until a user has performed an action on the card, only after this the Logic App will continue with the next actions. We want this same behavior.

**Comment by johno-a** [comment]
This isses was resolved but we are still having experiecing the error:

**Comment by johno-a** [comment]
Ping?

**Comment by matthidinger** [comment]
Hi @johno-a, 

The capability to wait for a card response, and to use that response in your flows is pending release, which explains why you are seeing an error message when consumers interact with the card. The only button types that you can leverage in flow today are show/hide and open URL. OpenUrl can sometimes be used to trigger events but not for data collection via the card itself. Stay tuned to the very early part of next year and we should have this feature rolled out and generally available!

Incidentally I plan to talk about some new Power Automate developments on the [Adaptive Cards community call](https://aka.ms/adaptivecardscommunitycall) this morning at 9 AM PST. If you're able to join it would be great to hear your feedback.

Thanks for your patience!

**Comment by cconrado** [comment]
@matthidinger how early this year? :)

**Comment by matthidinger** [comment]
It's getting close! Check out [this video](https://www.youtube.com/watch?v=74qHXhI6xZc&feature=youtu.be) and [blog post](https://poszytek.eu/en/microsoft-en/office-365-en/powerautomate-en/register-response-from-custom-adaptive-cards-sent-from-power-automate-to-teams/). They are currently available to some folks in preview and we're really close to release!

**Comment by hartski** [comment]
Is this out now? I have the option to add 'Post to a user and wait for a response' but still get the unable to connect to app message.

**Comment by helloanurag** [comment]
I am also getting the same error when using Power Automate - For a selected message (MS Teams connector). When I run the talk by clicking on three dots of a message in Teams - More actions - Select my Flow - 50% of the time it works and 50% of the time I get the same error - "Unable to reach app, please try again". I have tried it from a different environment too and got the same result. This seems to be a bug from MS end. If there was something wrong, it wouldn't have worked on the same message after trying several times. Something is wrong with this version of Adaptive Card compatibility with Power Automate. Please fix ASAP!

**Comment by RebeccaAnne** [comment]
This is not an adaptive cards issue. Please follow up at https://powerusers.microsoft.com/t5/Get-Help-with-Power-Automate/ct-p/FL_GeneralDiscussions if you are still having issues here. Thanks!
