### ISSUE TITLE
[UWP] Mixing lists and links in markdown breaks rendering

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#3337]
A combination of leading text, lists, and links renders incorrectly in UWP (fine in .NET WPF and JS).

```json
{
  "version": "1.0",
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "body": [
    {
      "type": "TextBlock",
      "text": "Leading text\r1. Click [link1](https://adaptivecards.io/)\r2. Click [link2](https://adaptivecards.io/)"
    }
  ]
}
```

Renders in UWP like this:
![image](https://user-images.githubusercontent.com/16614499/63114464-bdd6ce80-bf49-11e9-8b56-1ba643036fbe.png)
(note that if you omit the leading text, it renders correctly)

For reference, here's how it looks in .NET WPF:
![image](https://user-images.githubusercontent.com/16614499/63114493-d3e48f00-bf49-11e9-8c07-aa36229d8f0d.png)

**Comment by paulcam206** [comment]
I should note that this is because it's failing to parse the markdown HTML output from the shared model and falling back to rendering it as plain text. This is because the shared model output has two root nodes and the XML parser is rejecting it.

**Comment by nesalang** [comment]
> I should note that this is because it's failing to parse the markdown HTML output from the shared model and falling back to rendering it as plain text. This is because the shared model output has two root nodes and the XML parser is rejecting it.

it worked on iOS
