### ISSUE TITLE
[UWP] Links are no longer underlined

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#3341]
Not sure if this is an intentional AdaptiveCards change, an OS change, or something else, but the test app is no longer rendering links with an underline in current master:

![image](https://user-images.githubusercontent.com/16614499/63129962-d3f68600-bf6d-11e9-9a99-fc5ca36d9869.png)

**Comment by RebeccaAnne** [comment]
Looks like this is a regression from #3308

**Comment by paulcam206** [comment]
> Looks like this is a regression from #3308

tricksy. guessing it's [here](https://github.com/microsoft/AdaptiveCards/blob/1642b5992fcd9a42a20f1493c8ffa584e4d5d945/source/uwp/Renderer/lib/TextHelpers.cpp#L66-L69) and [here](https://github.com/microsoft/AdaptiveCards/blob/1642b5992fcd9a42a20f1493c8ffa584e4d5d945/source/uwp/Renderer/lib/TextHelpers.cpp#L87-L90)?
