### ISSUE TITLE
[Shared] Markdown doesn't respect Unicode space

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#3348]
see discussion in #3342.

**Comment by nesalang** [comment]
Could we broaden the scope of the issue a bit to include building a tokenizer?
Our MarkDwon parser would benefit from having a separate tokenizer. we could roll up all of the tokenizing task including UTF-8 support in one place.  
Having this task as one of the requirements for building tokenizer would be great. Any thought @paulcam206, @RebeccaAnne , and @shalinijoshi19 ?

**Comment by paulcam206** [comment]
yeah, that's basically what this is going to require -- we need to tokenize to be able to handle multibyte chars :)

**Comment by shalinijoshi19** [comment]
Let's track this via #1984
