### ISSUE TITLE
MS Teams is throwing "BadRequest" error for adaptive cards

### ISSUE THREAD

**Issue by ayanatwork** [microsoft/AdaptiveCards#3357]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- Bot Framework (C#)
- SDK v4
- Adaptive Cards (1.0)

# Version of SDK
v4

# Issue

When returning a AdoptiveCard attachment to MS Teams client I am getting an error - "Operation returned an invalid status code 'BadRequest' ".  The same adaptive card is getting successfully rendered in emulator but failing in Teams. I was not able to check developer preview in teams(due to accessibility issue) ,but I am guessing it is occurring in the server end.

# Issue - Scenario 1

Card is not getting displayed and throwing the error

# Issue - Scenario 2

Card is getting displayed but throwing the error as well.

**_Note - I have attached one zip file containing two card responses , which is working as expected in emulator as well as adaptive card visualizer section, but throwing error in Teams_**

[Issue_Scenari_1&2.zip](https://github.com/microsoft/AdaptiveCards/files/3520764/Issue_Scenari_1.2.zip)

**Comment by gaurav1621** [comment]
Facing the same issue, in Action.Submit, adaptive card working fine in bot emulator but giving "400: Bad Request" error in MSTeams.

**Comment by siduppal** [comment]
@shalinijoshi19 please assign this to @Wajeed-msft

**Comment by shalinijoshi19** [comment]
Thanks @siduppal ; Done (@Wajeed-msft  FYI) ; Btw do we want to keep this in the AC repo or transfer over to your end? If so, could you let us know the right repo to use and I'll get that taken care of as well ? Thanks!

**Comment by iBoonz** [comment]
Hi, Any updates on this? :)

**Comment by d1rrected** [comment]
Have the same problem with all adaptive cards

**Comment by WizX20** [comment]
Same issue with the latest version of adaptive cards here; is there any progress on this?

**Comment by Wajeed-msft** [comment]
Sorry, I missed this thread. 
Could you please try the same JSON directly using [App Studio](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/app-studio-overview#card-editor)'s Card Editor section? 
![image](https://user-images.githubusercontent.com/31851992/76506252-db80fd80-6470-11ea-86bd-1c1759a3f158.png)

Let me know if you see any error.  If you don't see any error, then please share the code snippet which you are using to send the Adaptive Card.

**Comment by WizX20** [comment]
Hi @Wajeed-msft, I tried it in the App Studio and also on https://adaptivecards.io/designer/
Both work. But it does not work in Teams directly. I'm also having a hard time finding any information about it in application insights; is there any way to debug this in teams?

**Comment by Wajeed-msft** [comment]
Hi @WizX20 - I tried the JSON which you shared and was able to send card successfully from code.
![image](https://user-images.githubusercontent.com/31851992/76936752-736f6300-6919-11ea-9522-b820bb2a626b.png)

Could you please try this code locally using [ngrok](https://docs.microsoft.com/en-us/microsoftteams/platform/tutorials/get-started-dotnet-app-studio#tunnel-using-ngrok)? 
```
var cardJson = System.IO.File.ReadAllText("AdaptiveCard.json");

            AdaptiveCardParseResult resultCard = AdaptiveCard.FromJson(cardJson);

            // Get card from result
            AdaptiveCard card = resultCard.Card;

            var reply = activity.CreateReply();
            reply.Attachments.Add(
                 new Microsoft.Bot.Connector.Attachment() 
                 { ContentType = AdaptiveCard.ContentType, Content = card });

            try
            {
                await context.PostAsync(reply);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                // throw;
            }
```

**Comment by pramodkn** [comment]
Please use channel specific data payload for channel
 `  "data": {
    "msteams": {
        "type": "messageBack",
        "displayText": "I clicked this button",
        "text": "text to bots",
        "value": "{\"bfKey\": \"bfVal\", \"conflictKey\": \"from value\"}"
    },
    "extraData": {}
  }`

reference [link](https://blog.botframework.com/2019/07/02/using-adaptive-cards-with-the-microsoft-bot-framework/) 

That works for me over teams.

**Comment by Wajeed-msft** [comment]
@WizX20 - Did you get chance to try out the code? Can we consider this issue closed?

**Comment by WizX20** [comment]
@Wajeed-msft Hi, my issue was resolved by ditching the background images and reverting to a simpler version of the schema for cards. So, you can close this issue if you like.

Is it fixed? I'm not sure, I still think there are some issues with Adaptive Cards in MS Teams, but I guess those will get resolved over time.
