### ISSUE TITLE
Deal with versionless cards

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#3376]
In the past we allowed cards with no explicit set version to parse (I believe we implied a version of `0.5`). That was removed as is was thought to no longer be needed. We need to revisit that decision

**Comment by matthidinger** [comment]
I think the last time Gilles and I talked about this we were considering a `MissingVersion` callback API or similar. I can't recall if we just ran out of time to implement it or found flaws in the design. 

Essentially it was something like

```cs
// AdaptiveCard.cs

public static Func<AdaptiveVersion> OnDeserializingMissingVersion { get; set; }

// then later where we deserialize and check for version

if(version == null) 
{
   if(OnDeserializingMissingVersion == null)
       throw new AdaptiveException("Missing required property 'version'");
   else
       card.Version = OnDeserializingMissingVersion();
}
```

The caller (BF) would use like:

```cs
AdaptiveCard.OnDeserializeMissingVersion = () => new AdaptiveVersion(0, 5);
AdaptiveCard.FromJson("....");
```

**Comment by shalinijoshi19** [comment]
For reference it's just the Bot framework that's affected by this. If that's the case I'd much rather go for a less flexible approach than delegates and a simpler targeted (boolean config for eg) approach.  Paul, let's write something up and float it around for discussion/review? We can revisit extensibility if there is a need for it in the future - right now a delegate for what appears to be a simple boolean condition seems overkill.

**Comment by shalinijoshi19** [comment]
@paulcam206 update on this? Would this be ready by 9/18's bugbash event?
