### ISSUE TITLE
Link Broken at Wiki Data-Binding-in-Adaptive-Cards-(Preview)

### ISSUE THREAD

**Issue by fuchsdaniel** [microsoft/AdaptiveCards#3382]
In the Wiki file 
https://github.com/Microsoft/AdaptiveCards/wiki/Data-Binding-in-Adaptive-Cards-(Preview)
when mentioned **AdaptiveCards repo**, the URL is missing an "S", causing 404:

It should be https://github.com/Microsoft/AdaptiveCards instead of https://github.com/Microsoft/AdaptiveCard

Thanks,

Daniel

**Comment by shalinijoshi19** [comment]
@matthidinger FYI; maybe addressed with the new set of website changes you are putting up?

**Comment by shalinijoshi19** [comment]
Hey @matthidinger, is this something you are able to address with the current website changes you have out? Thanks

**Comment by matthidinger** [comment]
Thanks for reporting! We've actually published official documentation on Templating, so I've updated the wiki to link there: https://docs.microsoft.com/en-us/adaptive-cards/templating/
