### ISSUE TITLE
Russian not rendered correctly in UWP

### ISSUE THREAD

**Issue by MichaelBuczek** [microsoft/AdaptiveCards#3383]
# Platform
* UWP

# Author or host
Bot sending the same adaptive card to teh emulator, webchat and the DLspeech sample app

If you're an author, who are you sending cards to?
Bot sending the same adaptive cards to several channels, rendering failing in UWP.

# Version of SDK
latest master

# Details
Presenting a card that does translation. The translated sentence is spoken as well as written. 
In uwp the translated content in russian and arabic is garbled. It looks like it is not rendered in UTF8, but with something else, probably Windows-1251. 

Further, the SSML is heard if applied on the Action Button Speak property, but not on the card itself.

Emulator/Webchat:
![image](https://user-images.githubusercontent.com/27769195/63606688-ed807900-c5d0-11e9-98ae-60de235a796a.png)

UWP:
![image](https://user-images.githubusercontent.com/27769195/63607038-cb3b2b00-c5d1-11e9-9a37-1ce05b611466.png)

**Comment by paulcam206** [comment]
Interesting! @MichaelBuczek, could you post the contents of this card?

**Comment by MichaelBuczek** [comment]
It's generated in code: 
`       public TranslationCard(string originaltext, TranslationItem translation, string language, Lng locale, string soundFileName, string channelID)
        {

            // top column set with items
            AdaptiveColumn originaltextCol = new AdaptiveColumn()
            {
                Width = AdaptiveColumnWidth.Stretch,
            };

            AdaptiveTextBlock originaltxt = new AdaptiveTextBlock()
            {
                Type = AdaptiveTextBlock.TypeName,
                Color = AdaptiveTextColor.Accent,
                Weight = AdaptiveTextWeight.Bolder,
                HorizontalAlignment = AdaptiveHorizontalAlignment.Center,
                Wrap = true,
                Text = originaltext,
            };
            originaltextCol.Items.Add(originaltxt);

            AdaptiveColumn feedbackheaderCol = new AdaptiveColumn()
            {
                Width = AdaptiveColumnWidth.Auto,

            };

            AdaptiveTextBlock txt = new AdaptiveTextBlock()
            {
                Type = AdaptiveTextBlock.TypeName,
                Size = AdaptiveTextSize.Small,
                Weight = AdaptiveTextWeight.Lighter,
                IsSubtle = true,
                Text = "Feedback:",
            };
            feedbackheaderCol.Items.Add(txt);

            AdaptiveColumnSet headerColumnSet = new AdaptiveColumnSet();
            headerColumnSet.Columns.Add(originaltextCol);
            headerColumnSet.Columns.Add(feedbackheaderCol);

            // middle column set
            AdaptiveColumn emptyCol = new AdaptiveColumn()
            {
                Width = AdaptiveColumnWidth.Stretch,
            };

            AdaptiveImage postivefeedbackImage = new AdaptiveImage()
            {
                Type = AdaptiveImage.TypeName,
                Size = AdaptiveImageSize.Auto,
                Style = AdaptiveImageStyle.Person,
                PixelWidth = 20,
                Url = new System.Uri($"{Fixed.ImageURL}glad_s.png"),
                SelectAction = null, // to be set later
            };
            //TODO AdaptiveAction positiveFeedback = new AdaptiveAction();

            AdaptiveColumn positivefaceCol = new AdaptiveColumn()
            {
                Width = AdaptiveColumnWidth.Auto, //"25",
            };
            positivefaceCol.Items.Add(postivefeedbackImage);

            AdaptiveImage negativefeedbackImage = new AdaptiveImage()
            {
                Type = AdaptiveImage.TypeName,
                Size = AdaptiveImageSize.Auto,
                Style = AdaptiveImageStyle.Person,
                PixelWidth = 20,
                Url = new System.Uri($"{Fixed.ImageURL}sad_s.png"),
                SelectAction = null, // to be set later
            };
            AdaptiveColumn negativefaceCol = new AdaptiveColumn()
            {
                Width = AdaptiveColumnWidth.Auto, //"25",

            };
            negativefaceCol.Items.Add(negativefeedbackImage);

            AdaptiveColumnSet feedbackbuttonColumnSet = new AdaptiveColumnSet();
            feedbackbuttonColumnSet.Columns.Add(emptyCol);
            feedbackbuttonColumnSet.Columns.Add(positivefaceCol);
            feedbackbuttonColumnSet.Columns.Add(negativefaceCol);

            // core Columnset
            // TODO: Implement worried face if score falls below 1 once we have data
            // use translation.Score
            string avatar = Avatar.GetAvatar(Expression.Happy, language);
            AdaptiveImage avatarImage = new AdaptiveImage()
            {
                Type = AdaptiveImage.TypeName,
                Size = AdaptiveImageSize.Medium,
                Style = AdaptiveImageStyle.Default,
                PixelHeight = 80,
                Url = new System.Uri(Fixed.ImageURL + avatar),
            };

            AdaptiveColumn avatarCol = new AdaptiveColumn()
            {
                Width = AdaptiveColumnWidth.Auto,
            };
            avatarCol.Items.Add(avatarImage);

            bool isArabic = locale == Language.GetCode("ar");
            AdaptiveTextBlock lbl = new AdaptiveTextBlock()
            {
                Type = AdaptiveTextBlock.TypeName,
                HorizontalAlignment = (isArabic) ? AdaptiveHorizontalAlignment.Right : AdaptiveHorizontalAlignment.Left,
                Text = (isArabic) ? $":{language}" : $"{language}:",
            };

            isArabic = GetLocale(language) == "ar";
            byte[] textbytes = Encoding.UTF8.GetBytes(translation.Text);
            string teststring = Encoding.UTF8.GetString(textbytes);
            AdaptiveTextBlock translationtxt = new AdaptiveTextBlock()
            {
                Type = AdaptiveTextBlock.TypeName,
                Weight = AdaptiveTextWeight.Bolder,
                Wrap = true,
                Text = channelID == ChannelID.Emulator ? translation.Text : teststring,
                HorizontalAlignment = (isArabic) ? AdaptiveHorizontalAlignment.Right : AdaptiveHorizontalAlignment.Left,
            };

            AdaptiveColumn translationCol = new AdaptiveColumn()
            {
                Width = AdaptiveColumnWidth.Stretch,
            };
            translationCol.Items.Add(lbl);
            translationCol.Items.Add(translationtxt);

            AdaptiveColumnSet coreColumnSet = new AdaptiveColumnSet();
            coreColumnSet.Columns.Add(avatarCol);
            coreColumnSet.Columns.Add(translationCol);

            string lang = GetVoiceIsoCode(language);
            string voiceName = GetFileVoiceName(language);

            AdaptiveSubmitAction actionPlay = new AdaptiveSubmitAction()
            {
                Type = "Action.Submit",
                Id = "play",
                Title = Rsp.Repeat(locale),
                IconUrl = $"{Fixed.ImageURL}repeat.png",
            };
            switch (channelID)
            {
                case ChannelID.DirectLineSpeech:
                    actionPlay.Data = $"{Fixed.MediaURL}{soundFileName}";
                    break;
                case ChannelID.DirectLine:
                case ChannelID.Emulator:
                default:
                    actionPlay.Speak = $"<speak version=\"1.0\" xmlns=\"http://www.w3.org/2001/10/synthesis\" xml:lang=\"{lang}\"><voice name=\"{voiceName}\" xml:lang=\"{lang}\">{translation}</voice></speak>";
                    break;
            }

            AdaptiveSubmitAction actionStop = new AdaptiveSubmitAction()
            {
                Type = "Action.Submit",
                Id = "stop",
                Title = Rsp.StopTranslating(locale),
                IconUrl = $"{Fixed.ImageURL}_stop_icon_1209711.png",
                Data = "Stop translating",
            };

            AdaptiveSubmitAction actionHelp = new AdaptiveSubmitAction()
            {
                Type = "Action.Submit",
                Id = "help",
                Title = (GetCode(language) == Lng.EN) ? Rsp.HelpLarsIsWrong(locale) : Rsp.HelpLieseIsWrong(locale),
                IconUrl = $"{Fixed.ImageURL}help.png",
                Data = "Handover to a human please",
            };

            AdaptiveBackgroundImage background = new AdaptiveBackgroundImage
            {
                Url = new Uri($"{Fixed.ImageURL}translationbackground2.jpg"),
            };

            // put it all together

            Body.Add(headerColumnSet);
            Body.Add(feedbackbuttonColumnSet);
            Body.Add(coreColumnSet);

            // commented out as not all renderers dislpay the media player
            //Body.Add(playContainer);
            if (GetFileVoiceName(language) != null)
            {
                Actions.Add(actionPlay);
                //Body.Add(playColumnSet);
            }
            Actions.Add(actionStop);
            Actions.Add(actionHelp);

            BackgroundImage = background;

            Speak = Say.SaySSML(translation.Text, GetCode(language));
        }

`

**Comment by MichaelBuczek** [comment]
Actually it seems to be a general issue, it's just that I send all text through an adaptive card to make the conversation less dull. But plain text has the same issue:
![image](https://user-images.githubusercontent.com/27769195/63654573-7ab40100-c77c-11e9-8c56-1fdc5c8d5c59.png)

**Comment by MichaelBuczek** [comment]
Paul,

Thanks for getting in touch. This seems to be a general UWP problem, not a specific Adaptive Card issue.

While I’m at it, there does not seem to be any way to play sound using directlinespeech from adaptive cards.
Of the four options below this is what works:

  1.  Only plays a file. That always works. It is often too slow to work in a in a dialog
  2.  Option 2 is adding speech to the activity containing text only. It stays silent
  3.  This adds speech as suggested to an activity containing a card. Also stays silen
  4.  This does not do what is documented but simply uses the speak property you can set. It works, but not with SSML.

Not sure if you are interested, but I thought I’d share.

        //diffetent ways to try to play sound
        await NAudioPlayer.VoiceReply(say, locale);
        await context.SendActivityAsync(sayit, cancellationToken);
        await context.SendActivityAsync(SaySSML(MyCard, message, lng), cancellationToken);
        await context.SendActivityAsync(".", say);

        //not working
        private static IActivity Speak(string ssmlmessage, Lng lng)
        {
            var activity = MessageFactory.Text(ssmlmessage);

            activity.Speak = SaySSML(ssmlmessage, lng);
            return activity;
        }

        private static IActivity Speak(Activity cardReply, string ssmlmessage, Lng lng)
        {
            var activity = cardReply;

            activity.Speak = SaySSML(ssmlmessage, lng);
            return activity;
        }

        public static string SaySSML(string rawtext, Lng lng)
        {
            string langCode = GetVoiceIsoCode(lng);
            string voiceName = GetBotVoiceName(lng);
            return $"<speak version=\"1.0\" xmlns=\"http://www.w3.org/2001/10/synthesis\" xml:lang=\"{langCode}\"><voice name=\"{voiceName}\" xml:lang=\"{langCode}\">{rawtext}</voice></speak>";
        }


Kind Regards,
Michael

[hel logo flerfärg]
Skype: michael.buczek@brainless.se<mailto:michael.buczek@brainless.se>
+46 790 763 261

**Comment by shalinijoshi19** [comment]
load balancing to @almedina-ms ; @paulcam206 FYI ; Can you try to repro this see and loop in the Target team if needed to aid?

**Comment by shalinijoshi19** [comment]
This maybe related to known issue #2969

**Comment by jonmill** [comment]
Closing as this is a UWP-general problem and not an AC specific problem
