### ISSUE TITLE
[.Net] [Internal ID]

### ISSUE THREAD

**Issue by nesalang** [microsoft/AdaptiveCards#3386]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF

Explain your issue. If you just have a question, please post [on StackOverflow instead]

As working on inner show cards, i came across this issue where internal id are null for all elements.

fix is added via inner show card PR, but we need to re-visit and ensure that this works correctly.

**Comment by shalinijoshi19** [comment]
@almedina-ms can you make sure that the element id design note includes this aspect of "internal" id's as well?
