### ISSUE TITLE
[UWP][Custom Rendering] Inconsistency in handling of parse errors for custom parsers

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#3387]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Details
 The parse result we return as a result of AdaptiveCard parsing is defined as follows:

```
    runtimeclass AdaptiveCardParseResult 
    {
        AdaptiveCardParseResult();

        AdaptiveCard AdaptiveCard { get; };
        Windows.Foundation.Collections.IVector<AdaptiveError> Errors { get; };
        Windows.Foundation.Collections.IVector<AdaptiveWarning> Warnings { get; };
    };
```

For our known types, warnings are things that don't cause rendering of the card to fail, and errors are things that do cause rendering of the card to fail. At the shared model layer, we throw for things that become AdaptiveErrors, but the UWP layer catches those exceptions and converts them into AdaptiveErrors. The reason for this is that we were given API guidance that we should NOT throw out of WinRT APIs on bad data (malformed cards).

In the case of custom elements, callers implement the following API:
```
    interface IAdaptiveElementParser 
    {
        IAdaptiveCardElement FromJson(
            Windows.Data.Json.JsonObject inputJson,
            AdaptiveElementParserRegistration elementParsers,
            AdaptiveActionParserRegistration actionParsers,
            Windows.Foundation.Collections.IVector<AdaptiveWarning> warnings);
    };
```  
This API, however, does not provide a way for callers to return an AdaptiveError. If they throw out of their parser (which they are of course free to do), that exception will bubble up unhindered to the caller of AdaptiveCard.FromJson, and will not be placed in the AdaptiveErrors Vector. This leads to an inconsistency between the handling of errors in known elements and the handling of errors in custom elements.

There are a few possible solutions:
1. Do nothing. This inconsistency is somewhat subtle and perhaps not a big deal.

2. Update the  IAdaptiveElementParser.FromJson method to include a place to put an error. This is probably how we should have designed it from the beginning, but would now be a breaking change to anyone already implementing this method.

3. The same as 2, but implement a new interface IAdaptiveElementParser2 (or something) that people could move to to get the new version. This may have trickle down effects requiring new updated APIs in AdaptiveElementParserRegistration, AdaptiveActionParserRegistration and QIs to determine which version to call back to.

4. Implement logic to catch any exceptions out of a caller's parser and convert them to AdaptiveErrors.

**Comment by RebeccaAnne** [comment]
Depending on our decisions from #3154, perhaps we don't want to allow custom parsers to do things that would fail the render. In that case, we should probably consider: .

5. Implement logic to catch any exceptions out of a caller's parser and convert them to **AdaptiveWarnings**.

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.
