### ISSUE TITLE
[Teams] [No image icon displayed on buttons]

### ISSUE THREAD

**Issue by HindoliyaYogesh** [microsoft/AdaptiveCards#3394]
# Platform
Microsoft Teams Integration

# Author or host
Microsoft Teams Client

# Version of SDK
SDK Version 1.2

# Details
## Version
Bot framework : v3
Adaptive Cards : 1.0

## Describe the bug
I am sending an adaptive card to a teams chat via bot. The card has two Open Url Action buttons. Both the action buttons have their iconUrl property set to valid Uri.

The card is rendered perfectly in web-chat, where both the action buttons contain icon before the text. But in Teams chat, the buttons only contain text and no icon.

## To Reproduce
1. Open App Studio > Card Editor in Teams client
2. Use the following JSON in card editor
`{
    "type": "AdaptiveCard",
    "body": [],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0",
    "actions": [
        {
            "type": "Action.OpenUrl",
            "title": "Email",
            "url": "mailto:yogeshhindoliya@hotmail.com",
            "iconUrl": "https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/243_Outlook_logo-128.png"
        },
        {
            "type": "Action.OpenUrl",
            "title": "Chat",
            "url": "mailto:yogeshhindoliya@hotmail.com",
            "iconUrl": "https://cdn.iconscout.com/icon/free/png-256/teams-1411850-1194339.png"
        }
    ]
}`
3. Click on "Send me this Card"

The Json above is sanitised, I am actually using Uri from my blob storage with public access.

## Expected behavior
I would expect a card to be sent to me with two buttons. First button ith outlook icon and the second one with teams icon in it as shown in the live-preview on card-editor

##Additional Info
The card designer on adaptivecards.io also renders the action buttons with icon in preview mode, so I would expect the same behaviour in chat window.

## Screenshots
1. Live-Preview in card editor
![bug_live_preview](https://user-images.githubusercontent.com/40543539/63761581-09d92a00-c8df-11e9-94a2-d6769561c589.png)

2. Card received in Teams Chat window (shows no icon)
![bug_chat_window](https://user-images.githubusercontent.com/40543539/63761584-0c3b8400-c8df-11e9-80f8-94af901ee93d.png)

**Comment by HindoliyaYogesh** [comment]
Hi,
Any updates on this or any suggestions on workaround on this will also be much appreciated.
I have a go-live pending because of this bug.

Regards,
Yogesh

**Comment by matthidinger** [comment]
Hi @HindoliyaYogesh, thanks for reporting this. `iconUrl` was added in v1.1 of Adaptive Cards and [Microsoft Teams is currently on v1.0](https://docs.microsoft.com/en-us/adaptive-cards/resources/partners). They are actively working on updating to v1.2 so stay tuned for announcements shortly!

**Comment by matthidinger** [comment]
Hi @HindoliyaYogesh, we've filed a separated issue to track updating Teams to v1.2 #3480 

Please go ahead and subscribe to that issue to be notified when Teams has updated

If you're seeing other issues please reopen and let us know

**Comment by HindoliyaYogesh** [comment]
@matthidinger :Thanks, i'll subscribe.

**Comment by RajaniJillaGit** [comment]
Hi Team,

Any update on this ? Could you please confirm by when release can happen in teams ?

Thanks
