### ISSUE TITLE
[UWP] ColumnSet.SelectAction sample card is a bit flaky in the test app

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#3399]
I think maybe we just need to choose a better source for images... More than once I've had the card (`v1.0/elements/ColumnSet.SelectAction.json`) render incorrectly (missing images) in the test app. Works fine on rerun.

**Comment by RebeccaAnne** [comment]
@paulcam206 can you confirm that this repros with the latest test app (including automatic re-runs) and the latest test files updates (PR #3450)? Thanks!
