### ISSUE TITLE
Carousel card is rendering one below one in teams channel.

### ISSUE THREAD

**Issue by Basavarajsk** [microsoft/AdaptiveCards#3405]
I am using carousel cards in node js bot to display results. But in teams carousel card is rendering one below one instead of side by side with navigator as 'next and prev'.
Version: SDK V3 Bot Framework
Deployment : Azure
Language : Node js
Adpative card Verison : 1.0
Platform Tested: Teams Desktop

**Comment by matthidinger** [comment]
Hi @Basavarajsk, Bot Framework has a maximum limit of 10 cards for carousel view, are you sending less than 10 cards? If so, can you provide additional information and potentially screenshots?

**Comment by matthidinger** [comment]
Hi @Basavarajsk I will close this for now, but if you are still having issues or can provide more information please reopen
