### ISSUE TITLE
[JavaScript][Mac] Chrome on Mac magically apply gradient white background on button when we say solid white

### ISSUE THREAD

**Issue by compulim** [microsoft/AdaptiveCards#3411]
# Platform

* JavaScript

# Author or host

Host. We are Web Chat 🌐💬.

# Version of SDK

Web Chat 4.5.2 uses Adaptive Cards 1.2.0.

# Details

> Related to https://github.com/microsoft/BotFramework-WebChat/issues/2365.

In Chrome on Mac (yap, very specific). We observed that all buttons on the Adaptive Card have gradient background color.

We checked it was styled properly with `background-color` set to `White`. I think this is a very specific problem to Chrome.

![image](https://user-images.githubusercontent.com/1622400/63982249-af72d180-ca76-11e9-8c7a-c48bb1647c36.png)

If you set the `background-color` to `#FEFEFE`, it become solid off-white. But if you set it to `#FFF`, it become gradient. And if you set `border-style` to `dashed`, it is solid white again. But if you set `border-style` to `solid`, it become gradient again. 🙄

So, I believe Adaptive Cards need to set `appearance: none` to prevent Chrome on Mac to style it.

![image](https://user-images.githubusercontent.com/1622400/63982037-3a9f9780-ca76-11e9-8ebc-e2d7f5e4261b.png)

To try this out real quick, please do the following:

1. On a Mac with Chrome 76 (it repro on 72 before we upgraded to 76)
1. Navigate to https://compulim.github.io/webchat-loader
1. On the "Secret" field, click on "MockBot" below
1. Click "Open Web Chat in a new window"
1. After Web Chat is loaded, type `card breakfast`, `help`, or `herocard`

Then, play with the <kbd>F12</kbd> and try fiddling `background-color` and `border-style`. 😉

**Comment by dclaux** [comment]
Problem is that to ensure `appearance` is set to `none` I would have to hard code it as an explicit style, and that will break apps that have not defined an explicit `ac-pushButton` style...

**Comment by corinagum** [comment]
Web Chat will go ahead and add `appearance:none` to `ac-pushButton` then. 

Can we get documentation regarding needing a native stylesheet on top of the host config? I think this is a common scenario that customers of Adaptive Cards would hit.

**Comment by dclaux** [comment]
Eventually we'll get the AC CSS stylesheet properly documented, but I can't promise when.

**Comment by shalinijoshi19** [comment]
Based on the conversation above looks to be a documetnation issue. @nesalang can you try to work with @dclaux on getting the documentation gap addressed? thanks!

**Comment by corinagum** [comment]
ping

**Comment by jonmill** [comment]
Closing this issue as a workaround has been identified and our css styles have been documented
