### ISSUE TITLE
Better visual feedback on button click.

### ISSUE THREAD

**Issue by vijaysaimutyala** [microsoft/AdaptiveCards#3412]
This is for the card using the WebChat renderer. The earlier version of the Adaptive cards used give a nice visual feedback to the user whether the button was clicked or not. But with the latest updates, the feedback is no longer present. It just shows a outline around the button in accent color which is not very helpful.

Old Adaptive Cards

![Old-Adaptive-Button-Feedback](https://user-images.githubusercontent.com/7084628/63999923-3f218a00-cb22-11e9-82bf-562900a16dbb.gif)

New Adaptive Cards
![New Adaptive Card](https://user-images.githubusercontent.com/7084628/64000299-0e8e2000-cb23-11e9-8903-300c351ad9a7.gif)

Users are not able to understand whether they've clicked the button or not. Sometimes when the  response from the bot needs some time to process and respond, the user without the help of feedback is clicking the button again before the response from bot appears. Any suggestions on this would be helpful.

**Comment by matthidinger** [comment]
@compulim @corinagum can you folks take a look at this?

**Comment by matthidinger** [comment]
Issue moved to [microsoft/BotFramework-WebChat #2401](https://github.com/microsoft/BotFramework-WebChat/issues/2401) via [**ZenHub**](https://www.zenhub.com/)
