### ISSUE TITLE
Relax the minimum version number of Newtonsoft

### ISSUE THREAD

**Issue by ckkashyap** [microsoft/AdaptiveCards#3413]
Adaptive card library nuget package requires atleast 12.0.2 version of Newtonsoft. This forces users of the library (such as Azure Bot Framework) to also upgrade the library.
Since Adaptive card does not really have a strong requirement for any feature/bug fix from 12.0.2 it would be better if it requires the minimum version of Newtonsoft that it really needs - this way, a larger group of applications can use the library.

**Comment by shalinijoshi19** [comment]
@paulcam206 assigned to you for picking up here. Thanks.

**Comment by shalinijoshi19** [comment]
@paulcam206 is this something that @nesalang or @almedina-ms can help out with to load balance?
