### ISSUE TITLE
[iOS]Sample/Visualizer app should be published to the store like the other platforms

### ISSUE THREAD

**Issue by shalinijoshi19** [microsoft/AdaptiveCards#3414]
# Platform
iOS

# Details

We should be consistent about publishing our samples in the resp stores on all platforms to test/show-case the published packages; Today we do that for other platforms but iOS is missing. This bug tracks fixing this gap on iOS.

**Comment by nesalang** [comment]
@shalinijoshi19 @RebeccaAnne 
when we do bug bash, we create our test cards. if we could keep those test cards in our repo for the next bug bash, we can re-use them to test on other platforms. For example, if we had so and so cards to test & find bugs on JS library. At next bug bas session, we could include ship them with our test apps, iOS and Android. This will make bashing bug much efficient.
