### ISSUE TITLE
adaptive card button not wrapping the text

### ISSUE THREAD

**Issue by mamhh** [microsoft/AdaptiveCards#3416]
dears,
 I face an issue of having adaptive card with button not wrapping the text content .. how can I make the text of the button wrapping ??  snapshot below for reference .. 

![Capture](https://user-images.githubusercontent.com/52238413/64261864-e2fda200-cf35-11e9-897b-a2b7746413bf.PNG)

**Comment by BalajiR** [comment]
You can wrap the title of the actions by setting the `allowTitleToWrap` boolean property in HostConfig as below.

```
actions: {
 actionTitleToWrap: true
}
```

**Comment by mamhh** [comment]
Plz share an example of using *HostConfig*

**Comment by BalajiR** [comment]
Find a sample usage in https://www.npmjs.com/package/adaptivecards#usage
Add the previously referred `actionTitleToWrap` property to the HostConfig to wrap the titles of Action elements.

**Comment by dclaux** [comment]
Hi @mamhh 

Are you rendering cards yourself inside your own app, or are you sending cards to a host (for example, Teams via a Bot)?

If you are rendering cards yourself and you are using the JS renderer, then you can indeed set the `allowTitleToWrap` property in HostConfig to true.

If you are sending a card to a host, then you are constrained to the behavior that host has chosen (the host owns its own HostConfig, and you can't change that). If the host doesn't allow the title to wrap, then that's what you have to work with.

**Comment by matthidinger** [comment]
This sounds like a useful feature and indeed helps for folks using JS/RN. Other platforms should consider having this as well

**Comment by matthidinger** [comment]
@mamhh please see Balaji's comment for sample usage of Host Config. Let us know if you run into further issues

**Comment by RebeccaAnne** [comment]
Logged #3482 to track possibly adding ```allowTitleToWrap``` to other platforms.
