### ISSUE TITLE
[UWP][Fallback Requirements] A element that fails its requirements reports "No Renderer found"

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#3418]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Details

For the following card which requires a future version of adaptive cards:
```
{
  "version": "1.2",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "text": "This textblock requires adaptiveCards 5.0",
      "color": "Attention",
      "wrap": true,
      "requires": {
        "adaptiveCards": "5.0"
      }
    }
  ]
}
```

The UWP renderer reports:
![image](https://user-images.githubusercontent.com/9091833/64288768-bd61a000-cf17-11e9-8420-4f305c31c6a7.png)

This is an inaccurate and confusing warning message as there **is** a renderer for TextBlock.

**Comment by jonmill** [comment]
Closing as fallback is not used
