### ISSUE TITLE
[UWP][Fallback Requires] Requirement comparison is case sensitive

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#3420]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Details

The following card will drop it's text block because the casing on the requirement is "AdaptiveCards" rather than the expected "adaptiveCards" camel casing. This text block is not dropped on .NET
```
{
  "version": "1.2",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "text": "This textblock requires adaptiveCards 1.0",
      "color": "Good",
      "wrap": true,
      "requires": {
        "AdaptiveCards": "1.0"
      }
    }
  ]
}
```

**Comment by shalinijoshi19** [comment]
@almedina-ms FYI assigning to you for fixing.
