### ISSUE TITLE
[Question] What is the estimated release date of v1.2.2 in npm?

### ISSUE THREAD

**Issue by jodufra** [microsoft/AdaptiveCards#3422]
What is the estimated release date of v1.2.2 in npm?

**Comment by shalinijoshi19** [comment]
@dclaux / @matthidinger ?

**Comment by jodufra** [comment]
As I looked into the release tag [v1.2.2](https://github.com/microsoft/AdaptiveCards/releases/tag/v1.2.2) I noticed only a few pull requests that, I think, affects the JS payload, they are the follow:
#3169 
#3407 
#3350 

Even though they are in short number, these PRs provide bug fixes that improve dialog flow and UX.
So I believe that users and developers would benefit from this release.

**Comment by shalinijoshi19** [comment]
@jodufra, we'll be getting the npm packages updated as part of our upcoming Sept patch targeted for end of this month. Thanks.

**Comment by shalinijoshi19** [comment]
Also the changelists you mention are actually still in master and have not been pushed out in previous releases at all at this time.

**Comment by jodufra** [comment]
> 
> 
> @jodufra, we'll be getting the npm packages updated as part of our upcoming Sept patch targeted for end of this month. Thanks.

Thank you
