### ISSUE TITLE
ColumnSet should have a selectAction property just like Container

### ISSUE THREAD

**Issue by anbare** [Microsoft/AdaptiveCards#344]
Anyone else think ColumnSet should have a selectAction property just like Container?

For scenarios like the following, you already have to use a ColumnSet to achieve that specific layout (three column sets, one for each item)... today, to make them clickable, you have to wrap them in a Container which causes your JSON to be two-additional levels deep.

![image](https://cloud.githubusercontent.com/assets/13246069/26167399/7f370cec-3aeb-11e7-8f73-8063e69af6a0.png)

If ColumnSet simply had a selectAction, this scenario would be much more straightforward.

**Comment by dclaux** [comment]
# Implementation status
- [ ] TypeScript (In code review: https://github.com/Microsoft/AdaptiveCards/pull/494)
- [ ] UWP
- [ ] WPF
- [ ] iOS
- [ ] Android
- [ ] Documentation

# Problem
In many cases, a ColumnSet is used to represent a single visual "block" of data. To make that block of data actionable, a card author currently has no other option than putting the ColumnSet inside a Container so they can set the Container's selectAction.

# Design

Add a selectAction property to the ColumnSet element:

| Property | Type | Description |
|---|---|---|
| selectAction | Action | The action that is executed when the ColumnSet is clicked/tapped. |

**Comment by almedina-ms** [comment]
Already fixed
