### ISSUE TITLE
[Designer] Remove useless full screen button from toolbar

### ISSUE THREAD

**Issue by dclaux** [microsoft/AdaptiveCards#3447]
**What platform is your feature request related to? (Delete other platforms).**
Designer

**Is your feature request related to a problem? Please describe.**
As the title says, the "go full screen" button in the designer's toolbar is pretty much useless.
A quick informal survey during the community call on 9/12/2019 had multiple people saying they never used the button and that it was redundant with the browser's F11 feature.

**Describe the solution you'd like**
Given that and the fact that the button consumes valuable space in the toolbar, the button should be permanently removed.

**Comment by RebeccaAnne** [comment]
Looks like this was taken care of at some point.
