### ISSUE TITLE
Request: Background color support for Card and Containers

### ISSUE THREAD

**Issue by sowsan** [microsoft/AdaptiveCards#345]
Some authors need to be able to specify specific background colors on containers and the card itself. For example, when displaying tags, the tag colors need to exactly match the colors of the original service.

![image](https://user-images.githubusercontent.com/13246069/49968274-3593bb80-feda-11e8-8b99-3fb8c1c29473.png)

## Requests

* soswan
* Teamwork Projects (Teams bot) (12/13/2018)

**===ORIGINAL COMMENT===**

Looking for a way to change the color of container control , its always showing as grey color. Thanks !

**Comment by matthidinger** [comment]
Currently this isn't possible but we plan to tackle background images and colors in both Cards and Containers soon

**Comment by sowsan** [comment]
Thanks Mat, is there a blog / announcement channel to keep track on the updates on adaptive cards?

**Comment by soumyajit-ghosh** [comment]
is there any possibility of adding hover color?

**Comment by andrewleader** [comment]
Hey @soumyajit-ghosh, sorry no one responded to your question a while back. Hover color sounds like a new scenario separate from this. Can you create a new issue describing the **scenario** you're trying to accomplish? If you have any visuals to share, that'd be excellent. We need to understand exactly what you need to do (what colors do you need to use, how exactly is it being used, etc). Thanks!
