### ISSUE TITLE
Need a way to find any element by id

### ISSUE THREAD

**Issue by EasyRhinoMSFT** [microsoft/AdaptiveCards#3453]
# Platform
* .NET WPF

# Author or host
* Author -- Teams

# Version of SDK
* NuGet v1.2.2

# Issue
I need a way to find any element in my card by id. I was going to write my own helper method but I found that, for some reason, the AdaptiveCollectionElement doesn't include the Items[] property.

**Comment by matthidinger** [comment]
Hi @EasyRhinoMSFT are you just trying to get the item from the object model? Or are you trying to get the underlying WPF Framework Element that was rendered? Can you explain more about what you're trying to achieve?

**Comment by EasyRhinoMSFT** [comment]
Hi Matt, I just want to get the object from the OM, e.g. var myElement = myAdaptiveCard.FindById("textBlock_Footer");
So what's needed is a method on the AdaptiveCard class that does a recursive search of the entire object hierarchy. It would also be possible to write my own utility method if AdaptiveCollectionElement provided an Items<AdaptiveElement> property.

**Comment by bil-ash** [comment]
https://github.com/microsoft/AdaptiveCards/issues/1326#issuecomment-581918310

**Comment by RebeccaAnne** [comment]
This is a good suggestion, but not something that's on our roadmap at this time. We may reconsider it in the future, or if you would like to make a contribution please see our contribution guidelines [here](https://github.com/microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md).
