### ISSUE TITLE
Remove isSelected from schema

### ISSUE THREAD

**Issue by dsanvita** [Microsoft/AdaptiveCards#346]
The Choice schema has an isSelected property, but this is not implemented in the HTML renderer.

https://github.com/Microsoft/AdaptiveCards/pull/347

**Comment by dclaux** [comment]
There shouldn't be an isSelected property. This has already been discussed; just like any other input, the only way to pre-select a value (or several in the case of ChoiceSet) is to include the "value" property in the payload in the same format a client application would expect it at runtime, e.g. a comma-separated list of values. For instance, "1,2,3" where 1, 2 and 3 are three valid choice values in the ChoiceSet.

This issue should be changed into "Remove isSelected from schema."

**Comment by matthidinger** [comment]
Thanks David, I'll take this on myself to update

**Comment by matthidinger** [comment]
This is done
