### ISSUE TITLE
[Shared] Missing highlightColors initialization

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#3460]
`ColorsConfig` has a bunch of members of type `ColorConfig`, which are initialized for default and subtle colors, but not highlight colors:

https://github.com/microsoft/AdaptiveCards/blob/302b0d8a397ef46fce1f80c73ff73253ba05397e/source/shared/cpp/ObjectModel/HostConfig.h#L77-L98

**Comment by RebeccaAnne** [comment]
We'll need to spec what we want the default host config to be for highlighter colors.
