### ISSUE TITLE
[.NET C#][Input Choicelist] [Selection disappears when action button is clicked in adaptive cards]

### ISSUE THREAD

**Issue by banubhooti** [microsoft/AdaptiveCards#3463]
# Platform
* .NET c#
# Author or host
Trying to render card to Microsoft Teams
# Version of SDK
 Adaptive Card version 1.0
# Details

I am using Input Choice List but when I click on submit button,the selected value disappears in the card

**Comment by nesalang** [comment]
@banubhooti , can you share the payload you used?

**Comment by RebeccaAnne** [comment]
@banubhooti could you please let us know if you're still seeing this, and if so share a sample json payload? Thanks!

**Comment by rutujlangalia** [comment]
Hi @RebeccaAnne ,

I am facing similar issue in teams where selection disappears for adaptive cards Input.Text and Input.Choice.

Please find attachment for example json.
Suggest a way to overcome this issue.

[ExampleJson.txt](https://github.com/microsoft/AdaptiveCards/files/3803702/ExampleJson.txt)

**Comment by rutujlangalia** [comment]
Hi @RebeccaAnne ,
Any updates on the issue?

**Comment by RebeccaAnne** [comment]
@rutujlangalia What platform is teams running on in your scenario?

**Comment by rutujlangalia** [comment]
@RebeccaAnne ,
I am using Windows as Teams platform.
Microsoft Teams Version : 1.2.00.27559 (64-bit)

**Comment by nikheelneelay** [comment]
@RebeccaAnne 
Hi Rebecca, just for info, this particular feature works fine on Bot Emulator 4.6.0. However, it didn't used to work on prior version i.e 4.5.2. I hope, this fix in 4.6 will be of some help.
![image](https://user-images.githubusercontent.com/16623762/69147322-b1898100-0af7-11ea-9d3f-cdb3544c869a.png)

**Comment by rutujlangalia** [comment]
@RebeccaAnne ,
Any updates?

**Comment by jonmill** [comment]
This should be fixed in the latest build; please re-open if this is not the case and we'll re-engage. Thanks!
