### ISSUE TITLE
Is there anyway to render a code block in v1.0 (in MS Teams)?

### ISSUE THREAD

**Issue by eamodio** [microsoft/AdaptiveCards#3466]
I've tried using \`\`\` to start a markdown code fence, which works in the visualizer, but not in MS Teams. I've tried setting the `fontType` property (but that seems to be 1.2 only).

I'm trying to format a card with a section that is a code block -- where I want whitespace preserved, ideally a monospace font, and horizontal scrolling if the lines are long enough.

Is there anyway to accomplish this?

**Comment by matthidinger** [comment]
Hi @eamodio, there's currently no way to do this I'm afraid. You're correct that `fontType` is the ideal approach as soon as Teams completes the v1.2 rollout, which hopefully won't be too much longer. If you'd like something more advanced than that please do let us know at https://aka.ms/ACfeatures and we can evaluate future improvements. Please reopen if this doesn't solve your issue.

**Comment by quinndumala** [comment]
Any updates on adding support for this? I'm trying to achieve the same thing and while changing the `fontType` helps, leading whitespaces aren't really preserved well leading to messy-looking code snippets.

**Comment by qris** [comment]
You can now use [CodeBlock](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html#codeblock-in-adaptive-cards) instead of TextBlock for preformatted text with syntax highlighting in AdaptiveCards.
