### ISSUE TITLE
[iOS][Investigate Feasibility of Supporting Swift UI] 

### ISSUE THREAD

**Issue by nesalang** [microsoft/AdaptiveCards#3470]
**What platform is your feature request related to? (Delete other platforms).**

* iOS

**Describe the solution you'd like**
Swift UI is coming as part iOS 13 (currently 12 is widely used).
Investigate the language, gauge the interest, and find possible path to adoption if possible.

**Comment by shalinijoshi19** [comment]
Resolving as #dup of #3468 . Let's track supporting SwiftUI and corresponding investigations using that via that.
