### ISSUE TITLE
[.NET][WPF] GetResourceInformation API doesn't retrieve audio or video

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#3476]
# Platform
* .NET WPF

# Version of SDK
master

# Details
When using the GetResourceInformation the API in .NET doesn't retrieve video or audio information compared to its counterpart in the C++ shared model where this elements are actually retrieved

**Comment by RebeccaAnne** [comment]
Let's confirm that the desired behavior is to return information for audio/video as well. Does this work in javascript?

If it already works everywhere except .NET we should just fix it.

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.
