### ISSUE TITLE
[ACWebsiteRefresh] Website Navbar not Loading Properly

### ISSUE THREAD

**Issue by fuchsdaniel** [microsoft/AdaptiveCards#3477]
When entering in the website provided via URL https://aka.ms/ACWebsiteRefresh, redirected to https://adaptivecardsci.z5.web.core.windows.net/pr/3261, Navbar not building horizontally, giving the impression that the rest of the webpage is not loaded. You only find it if you scroll down after Navbar Items.

Image below to ilustrate it:
![image](https://user-images.githubusercontent.com/16815722/65379427-1f533100-dc9e-11e9-9b65-41d1b710fae5.png)

I hope this helps,

Daniel

**Comment by matthidinger** [comment]
Thank you for taking the time to report this Daniel. It should be fixed now. Please do keep any other feedback coming!
