### ISSUE TITLE
[Actionable Message Designer] Copy JSON Button copy the JSON Card as a serialized object

### ISSUE THREAD

**Issue by fuchsdaniel** [microsoft/AdaptiveCards#3478]
Adaptive Card Team,

Wonderful work with the technology. Thanks a lot.

When using the new "Designer for Actionable Messages" at the new https://amdesigner.azurewebsites.net/, everything seems fine until you click on the COPY JSON button.
The text copies came as serialized string, requiring the output to be modified before it can be pasted in postman or in the other Adaptive Card related websites.

Thanks,

Daniel

**Comment by shalinijoshi19** [comment]
Thanks for trying us out @fuchsdaniel ! @dclaux would you know if this question is better suited for the Actionable Messages forum rather than AC first?

**Comment by shalinijoshi19** [comment]
Looks like this was an issue wiht the Actionable Messages Designer that should be fixed now. @fuchsdaniel please let us know/reactivate should you cntinue to the see issues in your workflow
