### ISSUE TITLE
[Teams] Update Microsoft Teams to v1.2

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#3480]
Tracking issue for updating Microsoft Teams to v1.2

**Comment by HindoliyaYogesh** [comment]
I need to get back to my customer regarding this update. Is there an ETA on this?

**Comment by shalinijoshi19** [comment]
@siduppal

**Comment by sayertherebel** [comment]
So the ActionSet buttons in my Teams bot just lit up on the Desktop app.. which is awesome.. Does this mean changes are afoot?

**Comment by shalinijoshi19** [comment]
@siduppal / @clearab any updates on the Teams desktop 1.2 upgrade? Thanks!

**Comment by gturbahn1** [comment]
Hi folks, is there any update on this. Is support for 1.2 adaptive cards part of the MICROSOFT reignite release?

**Comment by shalinijoshi19** [comment]
Hi, @gturbahn1 unsure if this is being targeted for Ignite and what platform you are looking for updates on,  (@siduppal for comment here for timeline) but we are working through a few more remaining integration issues this month with Teams Desktop + Mobile to enable them to be able to fully get on v1.2* on time for their next refresh. Stay tuned and know that we are actively engaged here on making this happen.

**Comment by daniel0x00** [comment]
+1. I’ve been waiting a lot for Teams to be at least v1.2 ready to be able to use Action.ToggleVisibility. My use case affects 1000+ people. I work in a large organisation of 100.000+ employees, for sure we have more colleagues waiting for this feature to be able to show lengthy adaptive cards. 
Thanks.

**Comment by HindoliyaYogesh** [comment]
I received the following response in the Partner Community from one of Microsoft Guys.

> Hi Yogesh, apologies for the delayed answer. We have now the release locked. We are looking at early CY20Q1 for GA, and dev preview by EOM (if things go well).

Hope this helps.

**Comment by daniel0x00** [comment]
> I received the following response in the Partner Community from one of Microsoft Guys.
> 
> > Hi Yogesh, apologies for the delayed answer. We have now the release locked. We are looking at early CY20Q1 for GA, and dev preview by EOM (if things go well).
> 
> Hope this helps.

Thanks a lot Yogesh, looking forward!

**Comment by viperfx** [comment]
Looking forward to this update.

Will this update include Templating feature?

**Comment by shalinijoshi19** [comment]
@viperfx Templating is a separate package still in pre-release/Alpha stage at this point. For details on  the AdaptiveCards features and [changes in 1.2.0](https://github.com/microsoft/AdaptiveCards/releases/v1.2.0) and other patch releases, please refer to our [release notes](https://github.com/microsoft/AdaptiveCards/releases)

**Comment by viperfx** [comment]
@shalinijoshi19 do you mean in Microsoft Teams, v1.2 of Adaptive Cards is still in alpha stage?

**Comment by gturbahn1** [comment]
Hey guys. Any update on this? Adaptive cards 1.2 on teams is critical to our customers. Thanks!

**Comment by gturbahn1** [comment]
> Hey guys. Any update on this? Adaptive cards 1.2 on teams is critical to our customers. Thanks!

Bumping this up - I would love an update on this. thanks!

**Comment by gturbahn1** [comment]
Hi guys,
We have a customer dependency on this update. Could someone please take a look?

Thanks

**Comment by shalinijoshi19** [comment]
Hi @gturbahn1  apologies for the delay in getting to this. This is absolutely the issue to use to track the Teams upgrade. What platform are you specifically interested in - Teams Web/Desktop or Teams Mobile? There is a preview version of Teams with 1.2 support available in preview mode as of Nov 2019; PLease refer to https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features#adaptive-12-support ; Also adding the Teams partners we are working with actively: @siduppal for Desktop and @VikrantSingh01 for Mobile.

**Comment by srishtisatwah** [comment]
> Hi @gturbahn1 apologies for the delay in getting to this. This is absolutely the issue to use to track the Teams upgrade. What platform are you specifically interested in - Teams Web/Desktop or Teams Mobile? There is a preview version of Teams with 1.2 support available in preview mode as of Nov 2019; PLease refer to https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features#adaptive-12-support ; Also adding the Teams partners we are working with actively: @siduppal for Desktop and @VikrantSingh01 for Mobile.

Hi guys,
As mentioned by @gturbahn1, we are using Teams Desktop and are trying adaptive cards 1.2. Currently, I am not seeing any cards display. Screenshot attached.

<img width="1213" alt="test_adaptivecards@1 2" src="https://user-images.githubusercontent.com/10636538/72121850-1b145780-3311-11ea-9e0d-0abf4bf61dde.png">

**Comment by cconrado** [comment]
@shalinijoshi19 i turned on the developer preview and it didn't expand the adaptive card as referenced in #3388

**Comment by srishtisatwah** [comment]
> > Hi @gturbahn1 apologies for the delay in getting to this. This is absolutely the issue to use to track the Teams upgrade. What platform are you specifically interested in - Teams Web/Desktop or Teams Mobile? There is a preview version of Teams with 1.2 support available in preview mode as of Nov 2019; PLease refer to https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features#adaptive-12-support ; Also adding the Teams partners we are working with actively: @siduppal for Desktop and @VikrantSingh01 for Mobile.
> 
> Hi guys,
> As mentioned by @gturbahn1, we are using Teams Desktop and are trying adaptive cards 1.2. Currently, I am not seeing any cards display. Screenshot attached.
> 
> <img alt="test_adaptivecards@1 2" width="1213" src="https://user-images.githubusercontent.com/10636538/72121850-1b145780-3311-11ea-9e0d-0abf4bf61dde.png">

Hi guys, Any update on this yet?

**Comment by shalinijoshi19** [comment]
@srishtisatwah , @gturbahn1 , apologies for hte delay here. If you are already using the Developer Preview for teams Desktop and continue to see the original issue, can you please file a separate bug/issue for it so we can engage on it along with the Teams Desktop partners?  Thanks!

**Comment by srishtisatwah** [comment]
> @srishtisatwah , @gturbahn1 , apologies for hte delay here. If you are already using the Developer Preview for teams Desktop and continue to see the original issue, can you please file a separate bug/issue for it so we can engage on it along with the Teams Desktop partners? Thanks!

Opened #3759
