### ISSUE TITLE
[UWP] Renderer ignores image size in ImageSet

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#3481]
# Platform

* .NET HTML
* .NET WPF
* Android
* iOS
* UWP

# Version of SDK

latest master

# Details

The UWP renderer doesn't respect the size of images when the image set has imageSize: "auto"

UWP Renderer
![image](https://user-images.githubusercontent.com/35784165/65453513-34dc6e00-ddf8-11e9-961d-0f3b32a2b94a.png)

WPF Renderer
![image](https://user-images.githubusercontent.com/35784165/65453522-386ff500-ddf8-11e9-8c0c-40d29715d365.png)

```json
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "ImageSet",
			"imageSize": "auto",
			"images": [
				{
					"type": "Image",
					"url": "http://adaptivecards.io/content/cats/1.png",
					"size": "small"
				},
				{
					"type": "Image",
					"url": "http://adaptivecards.io/content/cats/2.png",
					"size": "medium"
				},
				{
					"type": "Image",
					"url": "http://adaptivecards.io/content/cats/3.png",
					"size": "large",
					"requires": 
					{
						"adaptiveCard": "1.4"
					},
					"fallback": 
					{
						"type": "TextBlock",
						"text": "Some text"
					}
				},
				{
					"type": "Image",
					"url": "http://adaptivecards.io/content/cats/1.png",
					"backgroundColor": "#228B22"
				},
				{
					"type": "Image",
					"url": "http://adaptivecards.io/content/cats/2.png",
					"size": "stretch"
				},
				{
					"type": "Image",
					"url": "http://adaptivecards.io/content/cats/3.png",
					"style": "person"
				}
			]
		}
	]
}
``` 

Bug separated from: https://github.com/microsoft/AdaptiveCards/issues/3163

**Comment by RebeccaAnne** [comment]
See also #4043

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.
