### ISSUE TITLE
[JavaScript] Unregistering all actions in host app of designer doesn't removes “Selected action” in Element properties

### ISSUE THREAD

**Issue by atishayv** [microsoft/AdaptiveCards#3500]
# Platform
* JavaScript

# Author or host
Host Name : Microsoft Search

# Version of SDK
adaptivecards-designer@0.7.1

# Details
If I unregister all actions in my host app(Ex : `Adaptive.AdaptiveCard.actionTypeRegistry.unregisterType("Action.ShowCard"`)), I still see “Selected action” in Element properties with no values in dropdown for Image elements.

![image](https://user-images.githubusercontent.com/13940020/65986812-441b8580-e4a2-11e9-95cd-4f59ea20d2f0.png)

**Comment by shalinijoshi19** [comment]
@dclaux initial thoughts?

**Comment by jonmill** [comment]
This is currently by-design to ensure UI consistency
