### ISSUE TITLE
[JavaScript] Unable to properly see side panel options in high resolution mode.

### ISSUE THREAD

**Issue by atishayv** [microsoft/AdaptiveCards#3501]
# Platform
* JavaScript

# Author or host
Host Name : Microsoft Search

# Version of SDK

adaptivecards-designer@0.7.1

# Details

1) Make your screen at very high resolution or zoom the browser to 175%.
2) The scroll bar overlaps with "Card structure", "Element properties" and "Data Structure options"
![Untitled](https://user-images.githubusercontent.com/13940020/65988771-16d0d680-e4a6-11e9-9a87-de1989ec1140.png)

**Comment by dclaux** [comment]
Minor fix. I have been working with Atishay and am aware of this.

**Comment by jonmill** [comment]
This should be fixed in the latest version; if not, please re-open and we'll re-engage. Thanks!
