### ISSUE TITLE
[Templating] Support AND OR operation in "$when" condition

### ISSUE THREAD

**Issue by atishayv** [microsoft/AdaptiveCards#3502]
Platform
* Template engine, all platforms

**Is your feature request related to a problem? Please describe.**
3)	Is it possible to do a AND OR operation in $when condition? Something like : `"$when": "{price > 20 && qty < 5}" ?` or `"$when": "{price > 20 || qty < 5}"

**Additional context**
If an element is binded with 2 properties, the user should be able to put $when condition with both properrties

**Comment by matthidinger** [comment]
Hi @atishayv 

I've been researching how other similar JSON-based expression languages work, and all of them seem to rely on the Excel-like pattern of explicit functions as opposed to operators.

IMO it's a little more difficult to read, but definitely makes writing the template engines simpler and more extensible. I'm reaching out to the respective teams here at Microsoft to understand the backstory and why some decisions were made.

As another data point I've noticed a similar syntax in Azure DevOps builds:
![image](https://user-images.githubusercontent.com/1432195/66854183-b033ca00-ef35-11e9-9a67-fcfa67f63de4.png)

 
How do you feel about this syntax? Interestingly it has a mix of functions + operators to comparison, where-as devops has no operators of any kind.

```json
{
   "type": "TextBlock",
   "$when": "{and(price > 20, qty < 5)}",
   "color": "{if(and(price > 10, qty = 0), 'attention', 'good')}"
}
```

The `if` function seen below is designed to make the TextBlock appear "red" if the price is greater than 10 and the qty is 0.

**Comment by atishayv** [comment]
@matthidinger The syntax looks good, but it would be better if we can utilize already existing expression-based language instead of writing the new one if it fits our requirements.

Also, is it not possible to use js in expression instead of a JSON-based expression language. Something like : 
`
{
   "type": "TextBlock",
   "$when": "{(price > 20 && qty < 5)",
   "color": "{if(price > 10 && qty = 0){ return 'attention'}else{return 'good'}}"
}
`

**Comment by dclaux** [comment]
No, it is not possible to use JS in expressions, and that isn't a goal. What you suggest above can be written the way Matt suggested (aside from the fact we currently don't support and/or operators), and doesn't require complex code parsing.
