### ISSUE TITLE
[.NET] Deprecation warnings not updated for fontStyles->fontTypes rename

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#3506]
# Platform

* .NET HTML
* .NET WPF

# Description

`FontStyle` was renamed to `FontType`, but an older deprecation warning wasn't updated to reflect this:

https://github.com/microsoft/AdaptiveCards/blob/16172639b4aa70c7461e7b2b52824ae6d5c68d25/source/dotnet/Library/AdaptiveCards/Rendering/AdaptiveHostConfig.cs#L29-L39

**Comment by shalinijoshi19** [comment]
@nesalang can you pick this up? This should be part of our October patch. Thanks

**Comment by nesalang** [comment]
> @nesalang can you pick this up? This should be part of our October patch. Thanks

sure
