### ISSUE TITLE
[.NET][Unit Testing] FromJson throws exceptions when running unit tests in parallel

### ISSUE THREAD

**Issue by Rufus1123** [microsoft/AdaptiveCards#3509]
# Platform
.NET
botframework

# Version of SDK
NuGet version 1.2.3

# Details
I have multiple dialogs and multiple tests for each dialog in my chatbot project. I use cards in these dialogs, which are obtained from json files. When running all my tests, I get the following exception for most of the tests:

>   Message: 
>     System.InvalidOperationException : Stack empty.
>   Stack Trace: 
>     at Stack`1.ThrowForEmptyStack()
>     at Stack`1.Peek()
>     at ParseContext.PopElement()
>     at AdaptiveTypedElementConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
>     at JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
>     at JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>     at JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
>     at WhereSelectEnumerableIterator`2.MoveNext()
>     at WhereSelectEnumerableIterator`2.ToList()
>     at Enumerable.ToList[TSource](IEnumerable`1 source)
>     at JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
>     at JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>     at JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>     at JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
>     at JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
>     at AdaptiveTypedElementConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
>     at AdaptiveCardConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
>     at JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
>     at JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>     at JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>     at JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>     at JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>     at AdaptiveCard.FromJson(String json)

and one test returns the following error:

>   Message: 
>     System.NullReferenceException : Object reference not set to an instance of an object.
>   Stack Trace: 
>     at ParseContext.PopElement()
>   at AdaptiveTypedElementConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
>     at JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
>     at JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>     at JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
>     ...

When running the unit tests one by one, all of the pass.
It looks like AdaptiveCards.FromJson cannot handle multiple simultaneous calls.

**Comment by shalinijoshi19** [comment]
Hey @nesalang could you help pick this up? Thanks

**Comment by nesalang** [comment]
> Hey @nesalang could you help pick this up? Thanks

sure

**Comment by nesalang** [comment]
@shalinijoshi19 
from the log, the error happened in ParseContext. ParseContext is a static class, and PopElement and PushElement probably ran into synchronization issue. 

in discussion with @paulcam206, we have two options:
one is adding mutex
second is making ParseContext an instance variable, and set the lifetime to be same as its root card.

second option seems better choice in terms of the performance from user perspective since we don't have to use computationally expensive mutex lock and create a bottleneck, but making non static will involve more work as we need to plumb down the parse context.

**Comment by shaktikumar-singh** [comment]
Issue is not fixed yet, I got this same issue.
