### ISSUE TITLE
[Designer] Open Sample modal should be wired up to ESC button to close

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#3512]
# Platform
Designer

The "Open Sample" dialog should support the Escape key to close, for both usability and accessibility support. 

![image](https://user-images.githubusercontent.com/1432195/66243160-60910b00-e6b8-11e9-8800-7977501bebbe.png)

Here's the code I used to close the Homepage modal video. Tweak to remove jQuery references
```js
	$(document).keyup(function (e) {
		if (e.keyCode === 27) $('#closeVideo').click();
	});
```

**Comment by RebeccaAnne** [comment]
This button has been replaced in the current version of the designer with the "New Card" button. The dialog that pops up from that button does close on esc.
