### ISSUE TITLE
[iOS][Sample App] Adding Support For ToggleVisibility to CustomImageRenderer

### ISSUE THREAD

**Issue by nesalang** [microsoft/AdaptiveCards#3513]
**What platform is your feature request related to? (Delete other platforms).**

* iOS

**Is your feature request related to a problem? Please describe.**
Teams reported that iOS sample app's custom image renderer doesn't support toggle visibility.

**Comment by shalinijoshi19** [comment]
@nesalang took a look at this today and let me know that this is just a documentation issue at this point. @Visinghr FYI this shouldn't be a blocker

**Comment by Visinghr** [comment]
@shalinijoshi19  I am not sure, I have raise any issue against AdaptiveCard or not. If you meant to mention someone else. then you please check.
