### ISSUE TITLE
[Designer] Open Sample modal missing close button if you select the "Outlook Actionable Messages" host app.

### ISSUE THREAD

**Issue by larry-lau** [microsoft/AdaptiveCards#3515]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* JavaScript

# Author or host
Authoring

# Version of SDK
NPM Package "adaptivecards-designer": "^0.7.2"

# Details
1. Navigate to https://adaptivecards.io/designer/
2. Select "Outlook Actionable Messages" host app
3. Click the "Open Sample"
4. Note the modal is missing the Cancel button that you get in other host app type.
5. Also note that you can't select any sample listed. so now the designer is stuck.

**Comment by shalinijoshi19** [comment]
@dclaux thoughts? Feel free to send it my way for load balancing! tx

**Comment by dclaux** [comment]
Fix for this is coming in this PR: https://github.com/microsoft/AdaptiveCards/pull/3508
