### ISSUE TITLE
[Consistency] [Horizontal Scroll Bar in ActionSet]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#3516]
# Version of SDK

Latest master

# Details

iOS & Android have a horizontal scrollbar in ActionSet that appears when there are more actions than given frame's width. It was feature requested by the mobile clients such as Teams. We may have to revisit this issue for consistency across the platforms.

**Comment by shalinijoshi19** [comment]
@nesalang is this something you are looking at as part of #3592 ?
