### ISSUE TITLE
[Webchat][UI] Wrap text on action button 

### ISSUE THREAD

**Issue by tolotrasamuel** [microsoft/AdaptiveCards#3521]
# Platform

What platform is your issue or question related to? (Delete other platforms).
Webchat
* JavaScript

By default, the text on the action button of an HeroCard is trimmed with an overflow (Three dots) when it is longer than the width.

[![enter image description here][1]][1]

Is it possible to force all the text to be shown by going to the next line?

    private getAdaptiveHeroCard(title: string, description: string, choices?: SimpleChoice[]) {
        const card = new AdaptiveCards.AdaptiveCard();
        if (title) {
            const cardTitle = new AdaptiveCards.TextBlock()
            cardTitle.spacing = AdaptiveCards.Spacing.Medium
            cardTitle.weight = AdaptiveCards.TextWeight.Bolder
            cardTitle.maxLines = 0
            cardTitle.wrap = true
            cardTitle.text = title
            card.addItem(cardTitle)

        }
        const cardDescription = new AdaptiveCards.TextBlock()
        // cardDescription.parse(cardTitle.toJSON())
        cardDescription.isSubtle = true
        cardDescription.wrap = true
        cardDescription.text = description
        card.addItem(cardDescription)
        if(choices){
            for (const choice of choices) {
                const action = new AdaptiveCards.SubmitAction()
                action.data = choice.data
                action.title = choice.title
                card.addAction(action)
            }
        }

        return card;
    }

  [1]: https://i.stack.imgur.com/Wahyb.png

**Comment by matthidinger** [comment]
Hi @tolotrasamuel, thanks for filing this. Buttons are typically relatively terse pieces of UX, as a workaround is there any chance of trimming the length of that button text? 

In the meantime, I'm not aware of any options for configuration in the JS SDK. You could potentially achieve something using CSS customizations: https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/javascript/native-styling

@corinagum maybe you're aware of any other options in WebChat?

**Comment by corinagum** [comment]
Potentially you could fiddle with the defaultStyleOptions' `bubbleMaxWidth`, `bubbleMinWidth` in Web Chat and the word-wrap configurations in native styling of the card button. However my strong recommendation would be to consolidate button text as much as possible. :)

**Comment by shalinijoshi19** [comment]
@tolotrasamuel  do the suggestions above from @matthidinger and @corinagum help you here? At this point am closing out the issue but please feel free to re-open if you have more questions/follow up's here. Thanks!
