### ISSUE TITLE
[Designer] TextBlock "Subtle" checkbox is not working

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#3522]
The current build of the Adaptive Card designer at https://adaptivecards.io/designer is not properly applying the `isSubtle` property on `TextBlock`s

![image](https://user-images.githubusercontent.com/1432195/66767775-00dbf200-ee66-11e9-98b1-47b698e88638.png)

Expected:

* When clicking the above Subtle checkbox it should set the `isSubtle` property in the JSON.

Actual:

* No JSON modifications

**Comment by RebeccaAnne** [comment]
This seems to be working now.
