### ISSUE TITLE
[JavaScript] TextRun with empty text generates an uncaught exception that prevents the card from rendering

### ISSUE THREAD

**Issue by atishayv** [microsoft/AdaptiveCards#3523]
# Platform
* JavaScript

# Author or host
Host Name : Microsoft Search

# Version of SDK
adaptivecards-designer@0.7.1

# Details
In the below example, the $when condition ends up generating a TextRun with an empty text, which causes the card to fail rendering:

```
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "{a}",
                    "$when": "{a==true}"
                }
            ],
            "$when": "{!!a==true}"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "$data": {
        "a": ""
    }
}
```

**Comment by dclaux** [comment]
`{!!a==true}` isn't a valid expression. Use `{a==false}` or `{a!=true}` instead.

**Comment by atishayv** [comment]
What I wanted to achieve with the condition is :
If the value is not defined or null, it should evaluate to false otherwise it should evaluate to true. The type of data-bound variable `a` is not necessarily Boolean.

Can you please tell me how can it be achieved?

**Comment by atishayv** [comment]
@dclaux  I have also tried `“when”: “{a}”`, still it doesn't works. Can you please tell how can it be achieved ?

**Comment by dclaux** [comment]
Well, it should work with the syntax I gave you. The property name is `"$when"` though, not just `"when"`.

The below sample shows it in action:

Template:
```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "{title}",
            "$when": "{showTitle}"
        },
        {
            "type": "TextBlock",
            "wrap": true,
            "text": "{subTitle}"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2"
}
```

Data:
```
{
    "title": "Publish Adaptive Card Schema",
    "showTitle": true,
    "subTitle": "Now that we have defined the main rules and features of the format, we need to produce a schema and publish it to GitHub. The schema will be the starting point of our reference documentation."
}
```

**Comment by atishayv** [comment]
@dclaux I did used `$when` before. Here is ths adaptive card json I tried : 

Template:

```
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "New TextBlock"
        },
        {
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "{a}"
                }
            ],
            "$when": "{a}"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```

Data : 
```
{
    "a": ""
}
```

Not sure if this is a problem with RichTextBlock ?

**Comment by dclaux** [comment]
The expression in your `"$when"` clause needs to evaluate to a boolean. In your example, `{a}` evaluates to an empty string, and there is no implicit conversion between string and boolean. So you need to use `{a == ''}`

**Comment by atishayv** [comment]
@dclaux In the template that you provided : 
```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "{title}",
            "$when": "{showTitle}"
        },
        {
            "type": "TextBlock",
            "wrap": true,
            "text": "{subTitle}"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2"
}
```

If I give `subtitle` as an empty string like : 
```
{
    "title": "Publish Adaptive Card Schema",
    "showTitle": true,
    "subTitle": ""
}
```
Or if I remove the `subtitle` field from data : 
```
{
    "title": "Publish Adaptive Card Schema",
    "showTitle": true
}
```
 it s**till renders** the adaptive card by removing the `subTitle` TextElement from card.

But in RichTextBlock if I do the same thing, as in give `a` as empty string, the card **fails to render.**

**Comment by dclaux** [comment]
Sorry @atishayv that was really not clear from your previous comment.

I see indeed there is a bug in RichTextBlock, but it is independent of templating. $when works as expected. In this situation, it generates a TextRun with an empty text, which when rendered produces an undefined HTMLElement which the library attempts to add as a child, which generates an unhandled exception which causes the card to not render.

It's an easy fix, I will try to get to it ASAP.

**Comment by dclaux** [comment]
BTW, TextBlock (and TextRun) with an empty text simply do not render, by design - there is no need to use a `$when` clause for that.

**Comment by dclaux** [comment]
@atishayv please review the fix.

**Comment by atishayv** [comment]
@dclaux  Its all working... Thanks for the clarification
