### ISSUE TITLE
Include guidance that images cannot behind authentication

### ISSUE THREAD

**Issue by buildbod** [microsoft/AdaptiveCards#3525]
My suggestion is to add extra detail to the documentation to clarify where images should be stored for them to render. 

You are likely to encounter rendering issues esp. in applications like Outlook if your image is stored in a service like SharePoint that requires authentication.

Typically images in SharePoint will be rendered in the Designer especially if you cut the extraneous baggage and definitely remove the query element of the URL. Links like:

https://tenant.sharepoint.com/site/library/image.png

will work fine in the Designer. The results are patchy in Outlook Desktop - sometimes you will get all of the images used in the card other times several will be broken. Results are usually better in Outlook Web. Images stored in SharePoint are not displayed in Outlook Mobile.

The approach is to use images that are in the public domain e.g. https://buildboddotcom.files.wordpress.com/2017/10/cropped-header.jpg 

The ability to host images in this way might be beyond a citizen developer. 

---
* URL: https://adaptivecards.io/explorer/BackgroundImage.html

**Comment by paulcam206** [comment]
This is a good idea. We're using #6316 to track documentation work, so this should be addressed with that.
