### ISSUE TITLE
[Android] Newline Character ("\n") inside TextBlock not rendered

### ISSUE THREAD

**Issue by shbhadra** [microsoft/AdaptiveCards#3531]
# Platform
* Android

# Author or host

Host

# Version of SDK

1.2.0

# Details
Newline escape character ("\n") used inside a textBlock does not get rendered. With reference to the attached screenshot, "2 things", "1) ... " and "2) ..." should have appeared on a new line. The same however works fine on iOS and web.

<img width="283" alt="newline_card" src="https://user-images.githubusercontent.com/51158485/67365697-b22e0680-f58f-11e9-8d97-47be4031bcf3.png">

The card json for the screenshot is included in the attached zip
[newline_card.zip](https://github.com/microsoft/AdaptiveCards/files/3760646/newline_card.zip)

**Comment by VikrantSingh01** [comment]
Needed for Teams Mobile Platform

**Comment by VikrantSingh01** [comment]
This bug need #MsftTeams-Integration label @shalinijoshi19

**Comment by shalinijoshi19** [comment]
@RebeccaAnne / @matthidinger / @paulcam206 I could have sworn there was a newline support in textblock discussion somewhere in an issue a while back? Could one of you add a link to it here at all? Thanks

**Comment by RebeccaAnne** [comment]
#3016
