### ISSUE TITLE
[iOS][URL Support] Telephony urls not recognized as such on iOS

### ISSUE THREAD

**Issue by JoshuaSullivan** [microsoft/AdaptiveCards#3534]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Host rendering in-house authored cards.

# Version of SDK

iOS SDK v1.2.3

# Details

When a telephony link is embedded in text using markdown syntax, it is not being treated as a link on iOS. Instead, the entire markdown construct is printed out as plain text.

Example:
```
[(555) 555-5555](tel:5555555555)
```

On the web and Android, this is converted to a link with the text "(555) 555-5555" that launches call functionality when tapped. On iOS, the entire construct is simply displayed as text:

![ios-telephone-url](https://user-images.githubusercontent.com/698249/67318827-9cf2a280-f4d1-11e9-85d9-7eb2a90899cb.png)

**Comment by shalinijoshi19** [comment]
@nesalang thoughts on this so far? Can you also update the bug with your findings? thanks!
