### ISSUE TITLE
[Cortana UWP Ask] We need a way to expose a list of elements

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#3535]
We currently allow lists to be expressed via markdown. However, on some platforms (probably all of the non-HTML ones), these are exposed to accessibility as a single block of text, which might not be easy to consume. Similarly, we don't currently have a way to describe elements in a container as a list of things. I haven't done a bunch of thinking on this, but I think we should consider adding a `listType` property to all container elements with values `ordered`, `unordered`, and `semantic`. This would have the behavior of numbering, prepending a bullet, or simply exposing items to accessibility as a list, respectively.

**Comment by dclaux** [comment]
I think this might only be the tip of the iceberg. I feel we need to look at accessibility holistically and pervasively update the schema with accessibility-specific properties.

**Comment by paulcam206** [comment]
I agree, but I filed this to track a specific ask from a partner team :)

**Comment by shalinijoshi19** [comment]
@matthidinger to track this on product board. While this is not a blocker since Cortana have been able to workaround it, it still would be really great to have to have a consistent story in AC for all hosts.

**Comment by shalinijoshi19** [comment]
Tracking on product board as [Carousel Control](https://adaptivecards.productboard.com/insights/shared-inbox/notes/10899904)
