### ISSUE TITLE
Rounded Corners and Dark mode on Cards

### ISSUE THREAD

**Issue by vyomanaut** [microsoft/AdaptiveCards#3536]
webchat /bot framework
Rounded corners would add a charm to the already beautifull cards . 

And a dark mode implementation of cards for bot framework, similar to the windows notifications . i am not sure if this already exists .

**Comment by RebeccaAnne** [comment]
You may be able to achieve rounded corners in the host using CSS or other native styling. Supporting this natively in the SDK is not on our roadmap at this time. We may reconsider it in the future, or if you would like to make a contribution please see our contribution guidelines [here](https://github.com/microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md).
