### ISSUE TITLE
[Javascript][Rendering/Templating] Invalid Action.OpenUrl url parameter can break card render on desktop Teams

### ISSUE THREAD

**Issue by Zenulous** [microsoft/AdaptiveCards#3538]
# Platform

* JavaScript

# Author or host

Teams

# Version of SDK

1.2.3

# Details

Previously when an invalid URL was passed to the `Action.OpenUrl` action (e.g. because invalid input was passed by a user from previous interaction with the bot) the corresponding action button would render alongside the card. In this case, this button would not do anything upon clicking it.

Since not too long ago some strings completely break the rendering for the entire card. I consistently get this bug when the `url` parameter contains a string that could be interpreted as an integer, like `1`. 

This bug happens on the Microsoft Teams desktop client only (the mobile client still has the correct 'fallback'). The following Angular console error can be spotted:

![image](https://user-images.githubusercontent.com/45333650/67595830-ca587e00-f767-11e9-8e05-4dc52657a2f3.png)

The following snippet can be used to recreate the problem:

```JSON
{
        "type": "Action.OpenUrl",
        "title": "Link",
        "url": "1",
 },
```

**Comment by matthidinger** [comment]
I have a feeling this is happening in the Agular code that "wraps" the Adaptive Card renderer. Are you able to reach out to the owner of that code and see what has changed?

**Comment by shalinijoshi19** [comment]
@Zenulous FYI on @matthidinger 's question above for you.

**Comment by dclaux** [comment]
Evidence points to this being a regression in the host code, not the JS library. You can check using [the visualizer](https://adaptivecards.io/visualizer/index.html?hostApp=Bot%20Framework%20WebChat) that the url parameter is correctly passed to the host, even if it includes a line break character.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4655
