### ISSUE TITLE
Xamarin Forms - Nuget Package for AdaptiveCards

### ISSUE THREAD

**Issue by sowsan** [microsoft/AdaptiveCards#354]
Which one need to use for testing the Xamarin Forms and AdaptiveCards as like the sample provided in the repo?

Seeing two nuget packages so not sure which one to pick

 
Microsoft.AdaptiveCards.Xaml.Wpf.RichInput By: thermous 

Microsoft.AdaptiveCards.Xaml.Wpf By: thermous

**Comment by matthidinger** [comment]
Hi there, we currently don't have the Xamarin Forms packages published on Nuget, but you can build it from source in the `dotnet` folder/solution.

**Comment by sowsan** [comment]
Thanks Mat. Any tentative timeline on getting the xamarin forms nuget via the official push ?

**Comment by HernanCote** [comment]
Hello @matthidinger any thougths on an official or tentative timeline for getting the package from nuget?

**Comment by andrewleader** [comment]
Closing as tracked with #3255
