### ISSUE TITLE
[iOS][Dark theme: Text Color] [Text color for toggle switch in dark mode is not being set properly]

### ISSUE THREAD

**Issue by adumrewal** [microsoft/AdaptiveCards#3542]
# Platform

* iOS

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.

Host: Teams App

# Version of SDK

1.2

# Details
The text color in dark theme for toggle switch is not being set correctly.

**Comment by nesalang** [comment]
@adumrewal 
can you give us an screenshot, json payload, and etc to better understand the issue?

**Comment by adumrewal** [comment]
class ACRToggleInputDataSource
cellForRow, cell uses textlabel.textColor to be default black, so does not work on dark mode

PFA the screenshot.
![IMG_0015](https://user-images.githubusercontent.com/8917620/67847863-9a272b80-fb29-11e9-9d6c-3afc72320e24.PNG)

**Comment by nesalang** [comment]
**BB Payload**
samples/v1.0/Elements/
Input.Toggle.json

host configs
must be from dark theme configs
