### ISSUE TITLE
[Android][Button Icon Rendering] [Button icons placed on the left of the title are pushed out of the button, icon size not honored]

### ISSUE THREAD

**Issue by shbhadra** [microsoft/AdaptiveCards#3543]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android

# Author or host

Host

# Version of SDK

1.2.0

# Details

- Upon configuring the HostConfig to place the button icons to the left of the button title, the icons are pushed out of the bounds of the button.

- Icon size for the button icon as mentioned in the HostConfig is not honoured.

<img width="391" alt="button_icon" src="https://user-images.githubusercontent.com/51158485/67763007-ae592300-fa6c-11e9-9bbd-d5931a7ba49d.png">

Note the following observations : 
 

- For the case that there is only a single button the icon is infact rendered within the bounds of the button.

- For the case of multiple buttons, only the icon in the last button is rendered within the bounds of the button.

- The size of the icon is always rendered at the very small size as shown in the screenshot above irrespective of the value defined in the host config json.

Expecting the result to be similar to what is rendered on web, as shown in the image below
<img width="520" alt="desktop_btns" src="https://user-images.githubusercontent.com/51158485/67763787-81a60b00-fa6e-11e9-81aa-5443bb6bc06e.png">

Please find the following in the attached zip
1. Json for the card shown in the screenshot
2. HostConfig used for the card in the screenshot.
3. The screenshot itself.

[button_icon_render_issue.zip](https://github.com/microsoft/AdaptiveCards/files/3783314/button_icon_render_issue.zip)

**Comment by shalinijoshi19** [comment]
@almedina-ms can you please take a look at this with high priority? It's blocking Teams mobile upgrade to 1.2* ; @matthidinger  FYI

**Comment by almedina-ms** [comment]
For the image size that's by design, only if the icon is on top of the action test then we honour the iconSize property, otherwise it must match the size of the text next to it. Looking at the icons being pushed out of the button

**Comment by VikrantSingh01** [comment]
Needed for Teams Mobile Platform

**Comment by shbhadra** [comment]
@almedina-ms For the screenshot in the above description, the icon size is smaller than the text size too, and the icon size in the hostConfig is set to be very large and is thus not smaller than text size because of a host configuration.

**Comment by shalinijoshi19** [comment]
@almedina-ms please take a look at @shbhadra 's comment above around iconsize ? thanks
