### ISSUE TITLE
[iOS][RichTextBlock] Rich text Block does not work on 1.2

### ISSUE THREAD

**Issue by Aditya0603** [microsoft/AdaptiveCards#3544]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host
Host

If you're an author, who are you sending cards to?

1.2

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

None

Explain your issue. Rich text Block rendering does not work on iOS

Attached JSON

{
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"type": "AdaptiveCard",
"version": "1.2",
"body": [
{
"type": "RichTextBlock",
"inlines": [
{
"type": "TextRun",
"text": "This is the first inline. "
},
{
"type": "TextRun",
"text": "We support colors, ",
"color": "Good"
},
{
"type": "TextRun",
"text": "both regular and subtle. ",
"isSubtle": true
},
{
"type": "TextRun",
"text": "Text ",
"size": "Small"
},
{
"type": "TextRun",
"text": "of ",
"size": "Medium"
},
{
"type": "TextRun",
"text": "all ",
"size": "Large"
},
{
"type": "TextRun",
"text": "sizes! ",
"size": "ExtraLarge"
},
{
"type": "TextRun",
"text": "Light weight text. ",
"weight": "Lighter"
},
{
"type": "TextRun",
"text": "Bold weight text. ",
"weight": "Bolder"
},
{
"type": "TextRun",
"text": "Highlights. ",
"highlight": true
},
{
"type": "TextRun",
"text": "Italics. ",
"italic": true
},
{
"type": "TextRun",
"text": "Strikethrough. ",
"strikethrough": true
},
{
"type": "TextRun",
"text": "Monospace too!",
"fontType": "Monospace"
}
]
},
{
"type": "RichTextBlock",
"inlines": [
{
"type": "TextRun",
"text": "Date-Time parsing: {{DATE(2017-02-14T06:08:39Z,LONG)}} {{TIME(2017-02-14T06:08:39Z)}}"
}
]
},
{
"type": "RichTextBlock",
"horizontalAlignment": "Center",
"inlines": [
{
"type": "TextRun",
"text": "Rich text blocks also support center alignment. Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor "
}
]
},
{
"type": "RichTextBlock",
"horizontalAlignment": "Right",
"inlines": [
{
"type": "TextRun",
"text": "Rich text blocks also support right alignment. Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor "
}
]
},
{
"type": "RichTextBlock",
"inlines": []
}
]
}

**Comment by nesalang** [comment]
this works for sample app.
![Simulator Screen Shot - iPhone 8 - 2019-10-29 at 12 24 24](https://user-images.githubusercontent.com/4112696/67801779-23b1fd00-fa47-11e9-9ba2-dbe7a72a8983.png)

Is it possible that rich text block renderer does not exist, or it's not registered with the registration?

please see our default implementation of ACRRichTextBlockRenderer.mm

**Comment by VikrantSingh01** [comment]
This bug need #MsftTeams-Integration label @shalinijoshi19

**Comment by shalinijoshi19** [comment]
@nesalang , @Aditya0603  / @VikrantSingh01 was the reason for closing this bug understood?
