### ISSUE TITLE
[iOS][Action.ToggleVisibility] Toggle Visibility action does not call the delegate didChangeViewLayout/didFetchUserResponses method

### ISSUE THREAD

**Issue by Aditya0603** [microsoft/AdaptiveCards#3545]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Host

If you're an author, who are you sending cards to?

# 1.2

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

None

Clicking on Action.ToggleVisibility type buttons does not call the delegate method to refresh the UI

**Comment by nesalang** [comment]
fixed via #3513

**Comment by VikrantSingh01** [comment]
Pls share the SDK release details @nesalang

**Comment by VikrantSingh01** [comment]
This bug need #MsftTeams-Integration label @shalinijoshi19

**Comment by VikrantSingh01** [comment]
As per the above comment. It's fixed in AdaptiveCards@v1.2.4.
