### ISSUE TITLE
[Android][verticalContentAlignment for a container not being honoured]

### ISSUE THREAD

**Issue by shbhadra** [microsoft/AdaptiveCards#3549]
# Platform
* Android
# Author or host
Host
# Version of SDK
1.2.0
# Details
The "verticalContentAlignment" always renders to "top" even if specified otherwise ("center", "bottom"). With reference to the following screenshot, the second line should have been placed centrally to the card, and the third line should have been placed at the bottom of the card.
<img width="389" alt="vert_content" src="https://user-images.githubusercontent.com/51158485/67830094-7ea72b00-faff-11e9-8f51-b8aee465df16.png">

The same card as rendered on desktop
<img width="406" alt="desktop_vert" src="https://user-images.githubusercontent.com/51158485/67830114-8e267400-faff-11e9-8b3d-fb4edfb14042.png">

The same card as rendered on iOS
<img width="377" alt="ios_vert" src="https://user-images.githubusercontent.com/51158485/67830141-9e3e5380-faff-11e9-805a-6ffa677feb68.png">

Please find the json in the attached zip
[vert_alignment_issue.zip](https://github.com/microsoft/AdaptiveCards/files/3787023/vert_alignment_issue.zip)

**Comment by shalinijoshi19** [comment]
@almedina-ms  FYI; Could you please prioritize this for the November release for Teams? Thanks

**Comment by almedina-ms** [comment]
@shalinijoshi19 , the verticalContentAlignment needs extra space for being able to render the contents of a container in different positions, for the Android renderer doesn't have APIs for defining the size of a card (not sure about the story for this) so the base card is always rendered with as much vertical space as needed (not as asked), so Containers in the root of a card won't render the contents with different vertical positions, the behaviour for verticalContentAlignment can be seen when the container is in a column (next to a larger one) as it is able to have more vertical space

**Comment by shalinijoshi19** [comment]
@nesalang could you help with next steps here? Based on what @almedina-ms mentions this has been an inconsistency right from the start in Android.. 
@shbhadra / @VikrantSingh01  this doesn't appear to be a regression in Android but something that has always existed on the Android side looks like. We could tackle this as part of the inconsistency investigation between iOS and Android that @nesalang is driving but this is not likely to be addressed withthe November patch as it may need more feature-level work on the Android side.

**Comment by shalinijoshi19** [comment]
@VikrantSingh01 FYI that this isn't a regression in 1.2 so shouldn't block Teams upgrade at this point. @nesalang is investigating this for the next patch (January). Thanks

**Comment by VikrantSingh01** [comment]
@nesalang / @shalinijoshi19 : Any update on this one ?

**Comment by VikrantSingh01** [comment]
@nesalang : Estimate of around 4 days for the fix.

**Comment by shalinijoshi19** [comment]
@almedina-ms can you please look at this wiht high priority for this month's January patch release? Thanks
