### ISSUE TITLE
[Website] Filter Documentation by Schema Version

### ISSUE THREAD

**Issue by ericrrichards** [microsoft/AdaptiveCards#3550]
It's probably a lot of work to do, but it would be very helpful to be able to filter the schema documentation by a maximum AdaptiveCards version.

For instance, I do a lot of work with Microsoft Teams, which still only supports 1.0 properties and elements, so I really only want to see the docs on the bits and pieces that will work with that version of the spec.

---
* URL: https://adaptivecards.io/explorer/

**Comment by matthidinger** [comment]
Thank you for the feedback on this! That's a great suggestion worth adding to the Schema Explorer.

We are actually working on adding a Version Selector to the Designer in PR #3508. This drop-down will update the Toolbox and Properties based on the version selected.

![image](https://user-images.githubusercontent.com/1432195/67891628-2fb5c180-fb10-11e9-99b1-ec727d280501.png)

Hopefully we'll have this rolled out within the next month or two.
