### ISSUE TITLE
[.Net][Input.Choiceset's Text's foreground Doesn't Adapt to Parent's Container Background color]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#3551]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF
* UWP
# Details

![image](https://user-images.githubusercontent.com/4112696/67906206-1ffaa500-fb31-11e9-8f16-f219c20dbe27.png)

As the screenshot shows, text's foreground color doesn't adapts to parent view's background color
However, this scenario works with Input.Toggle as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/4112696/67906337-710a9900-fb31-11e9-9ccf-42dcec4df33b.png)

Explain your issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards).

**Comment by shalinijoshi19** [comment]
@nesalang, is this a WPF renderer only bug? What is the behavior on the other platforms here? This looks like something we should fix - @RebeccaAnne , @paulcam206 , @matthidinger , @dclaux  for thoughts/comments here also.

**Comment by nesalang** [comment]
> @nesalang, is this a WPF renderer only bug? What is the behavior on the other platforms here? This looks like something we should fix - @RebeccaAnne , @paulcam206 , @matthidinger , @dclaux for thoughts/comments here also.

@shalinijoshi19 
UWP has same issues.
we haven't defined behavior for text foreground color for inputs.
