### ISSUE TITLE
[Android][Element Rendering] [Spacing within Choice sets not rendered]

### ISSUE THREAD

**Issue by shbhadra** [microsoft/AdaptiveCards#3554]
**this needs to be fixed for radio button as well**

# Platform
* Android
# Author or host
Host
# Version of SDK
1.2.0
# Details
There is no spacing between the elements in a choice set, for an "expanded" style of the choice set, for both checkboxes and radio buttons. The issue is illustrated in the image below
<img width="292" alt="choice_without_wrap" src="https://user-images.githubusercontent.com/51158485/67929539-922bc200-fbe3-11e9-9f0c-8edb5eda74f1.png">
However upon setting "wrap" : true, the spacing shows up
<img width="288" alt="choice_with_wrap" src="https://user-images.githubusercontent.com/51158485/67929602-b1c2ea80-fbe3-11e9-84bb-2d63df42adbe.png">
The attached zip contains the card jsons and screenshots
[choice_set_spacing.zip](https://github.com/microsoft/AdaptiveCards/files/3792740/choice_set_spacing.zip)

**Comment by shalinijoshi19** [comment]
@almedina-ms can you help pick this up for the November release as part of the Teams blocker bugs? Thanks

**Comment by nesalang** [comment]
@shalinijoshi19 

Teams confirmed that the issue is fixed from the last meeting; however, they said single select ChoiceSet that uses radio button still has the issue; and reason for the re-opening the issue.

**Comment by VikrantSingh01** [comment]
@shbhadra : Let's log a new bug for this.
