### ISSUE TITLE
[TS] Empty fact title shows up as 'Title' instead of a blank

### ISSUE THREAD

**Issue by susanshen96** [microsoft/AdaptiveCards#3563]
# Platform

* Typescript

# Version of SDK

1.2.3

# Details
When a title is not provided for Fact, the default value is now 'Title' instead of a blank. 

I'm using Microsoft Teams, and this is how the card used to render, with the 1.0 SDK. 
![image](https://user-images.githubusercontent.com/10697383/68055377-c23f9780-fcad-11e9-9b1a-733f9f7a199b.png)

With the update to 1.2, this is what the card looks like.
![image](https://user-images.githubusercontent.com/10697383/68055481-ef8c4580-fcad-11e9-887c-7ab7bc6e2f6d.png)

**Comment by shalinijoshi19** [comment]
@dclaux / @matthidinger FYI moved to triage-investigate as David has picked this up for investigating (we update the label and it will automatically move to the right projectboard column)

**Comment by dclaux** [comment]
No investigation is needed, this is a regression and it needs to be fixed.

**Comment by shalinijoshi19** [comment]
> No investigation is needed, this is a regression and it needs to be fixed.

Great. Thanks for confirming; In that case I just simply add the Triage-Approved for Fix label and the automation takes care of the rest of the workflow..
