### ISSUE TITLE
[TS] Column default width is now 'auto' instead of 'stretch'

### ISSUE THREAD

**Issue by susanshen96** [microsoft/AdaptiveCards#3564]
# Platform

* Typescript

# Version of SDK

1.2.3

# Details

We've been seeing a regression in how some columns are being rendered on cards. It seems that the default width, when no value is provided by the developer, is now 'auto' instead of 'stretch', which is causing some 1.0 cards to break in terms of previous styling. I've included a screenshot of a sample card that exhibits this behavior. 

In Microsoft Teams, the card in question rendered as such, with the 1.0 version. 
![image](https://user-images.githubusercontent.com/10697383/68055697-80632100-fcae-11e9-9911-2e163d3e307f.png)

Now, with the 1.2 version, the card renders like so. 
![image](https://user-images.githubusercontent.com/10697383/68055684-750ff580-fcae-11e9-9a95-6dd75efdbabd.png)

**Comment by shalinijoshi19** [comment]
@dclaux / @matthidinger  FYI moved to triage-investigate as David has picked this up for investigating (_we update the label and it will automatically move to the right projectboard column_)
