### ISSUE TITLE
[UWP][Markdown] Markdown not working on UWP

### ISSUE THREAD

**Issue by nimercer** [microsoft/AdaptiveCards#3568]
# Platform

UWP

# Author or host

Host

If you're an author, who are you sending cards to?

n/a

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

1.2

Markdown does not appear to be working with UWP.

![image](https://user-images.githubusercontent.com/48482128/68201051-f3bfa800-ffb8-11e9-89d3-143d0ec64b2c.png)

Same json in adaptivecards.io designer:

![image](https://user-images.githubusercontent.com/48482128/68201100-05a14b00-ffb9-11e9-9f9b-6386c8fa48ec.png)

json for reference:

{  
   "type":"AdaptiveCard",
   "version":"1.0",
   "body":[  
      {  
         "type":"TextBlock",
         "size":"large",
         "weight":"bolder",
         "text":" Good morning"
      },
      {  
         "type":"TextBlock",
         "text":"\r\n\n‌   \n### Hi there. \r\n\n‌   \n### Hello \r\n\n‌   \n***\"What is your favorite baseball team?\"***   \n   \n***\"Show my shopping list\"***",
         "wrap":true,
         "maxLines":10
      }
   ]
}

**Comment by nesalang** [comment]
this isn't bug on UWP. We only support subset of markdown. It's actually inconsistency bug on TS render (one used for designer).

**Comment by nimercer** [comment]
Ahh thanks for the replying here - no this is from an old bug on our side and not a regression, my confusion came from the fact that the markdown works in the adaptive cards online designer.
In this case the json coming is invalid and we can close this on your side 😀
