### ISSUE TITLE
UWP larger font sizes have extra padding on left side

### ISSUE THREAD

**Issue by anbare** [Microsoft/AdaptiveCards#357]
**Expected:** Regardless of font size, the left edge of text should be consistent. If there's a small text followed by a large text, you should be able to draw a line down from the left edge of the small text and it should be flush with the left edge of the large text.

**Actual:** Larger fonts start to creep to the right, rather than staying flush with the imaginary line on the left.

Visualization of the issue today...

![image](https://cloud.githubusercontent.com/assets/13246069/26225426/fbba15b6-3bdb-11e7-8fc7-6e4eef8b8fc1.png)

Fix is to use a specific property on the XAML TextBlock... I'll look up what it is, we used it for tiles previously

**Comment by mdtauk** [comment]
Have you tried this property, it is supposed to fix those issues.
`<TextBlock OpticalMarginAlignment="TrimSideBearings"/>`

**Comment by anbare** [comment]
Yep that's the one, found it from my previous project a while ago, currently adding it to the code. Thanks mdtauk!

**Comment by anbare** [comment]
Fixed!
