### ISSUE TITLE
[Web][Avatars] Person avatars are not always circular

### ISSUE THREAD

**Issue by ankuraren4u** [microsoft/AdaptiveCards#3572]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* JavaScript

# Author or host

Host: Microsoft Teams

# Version of SDK
1.4.0

# Details
For adaptive card having style as "Person", the person image which are not square are shown as "Oval" and not circular. On Android the image is always shown as Circular and also adaptive card specification says that user avatars are circular.

```json
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "items": [
            {
              "type": "Image",
              "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTQUkjZhQUcC0gI2wpt6LRviTxv7yKrTlfyGX6E2H-7eNuZzRpH",
              "style": "Person",
              "size": "Large"
            }
          ],
          "width": "auto"
        }
      ]
    }
  ]
}

```

**Comment by shalinijoshi19** [comment]
@dclaux thoughts?

**Comment by dclaux** [comment]
Like the WPF renderer, the JS renderer favors maintaining the aspect ratio of images over enforcing that the "Person" style always be a square. It is always possible to obtain the desired result by forcing the dimensions of the image using the `width` and `height` properties specified in pixels.

**Comment by shalinijoshi19** [comment]
Thanks @dclaux.  @ankuraren4u are you able to use explicit image sizes in place of the 'size' property here? Also what is the spec you are referring to again where you saw the mention around avatars being circular please ? @paulcam206 heads up here though still trying to figure out the extent of the inconsistency here and whether we are actually ambiguous wrt documentation or that we have this laid out in our docs someplace and it's a matter of making sure the JS/WPF renderers comply.

**Comment by dclaux** [comment]
Note that currently the only "right" solution (e.g. the solution that will produce the actually desired result) for person images is to have the physical image itself be a square. Any non-square image forced into a perfect circle will lead to its original aspect ratio being lost, producing ugly results.

**Comment by ankuraren4u** [comment]
We are passing the size property, but with size property the avatar images looks oval for rectangular images. Also, by passing explicit height and width the aspect ratio will be broken and image will get stretched from one side. 

For teams, we need to show all person avatars as circular even in the case when the image is rectangular. 
Adaptive Card Android SDK automatically takes care of it by taking the circle from centre and fixing the lower dimension (height/width) to the container.

**Comment by ankuraren4u** [comment]
@dclaux For our current situation it is not possible to force all images to be in the square size. The images come from a source we don't control and that service also cannot resize all the profile pictures of all users in the database.
Android and iOS clients have written their own "custom renders" to fix this.

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.
