### ISSUE TITLE
[.NET C#][Input.ChoiceSet] [adaptive card dropdown title with double quotes rendering issue]

### ISSUE THREAD

**Issue by rutujlangalia** [microsoft/AdaptiveCards#3573]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET C#

# Dropdown rendering title value containing double quotes is getting replaced with "&quot"

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name. : **Microsoft Teams**

# 1.2.0

# Details

We are having dropdown in adaptive card which is having double quotes in title. double quotes on teams channel are getting replaced with "&quot"

Please find example JSON below:
[DropdownExampleJson.txt](https://github.com/microsoft/AdaptiveCards/files/3814266/DropdownExampleJson.txt)

Please suggest a solution.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/32361772/68296260-3321ed80-00ba-11ea-8415-472aa0dc5c25.png)

**Comment by shalinijoshi19** [comment]
@paulcam206 can you take a first stab at this please? thanks

**Comment by paulcam206** [comment]
Looks like we should be able to use something like [this](https://docs.microsoft.com/en-us/dotnet/api/system.net.webutility.htmldecode?view=netframework-4.8) for our .NET platforms, but we should take a look make sure our other platforms can handle this as well.

**Comment by nikheelneelay** [comment]
Any updates on this?

**Comment by LLautt** [comment]
Has there been any updates on this from anyone?  I have the same problem with single quotations, being replaced with "&#39;"

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4591
