### ISSUE TITLE
Anchor tag is not coming when using adaptivecard lib in angular 4 application

### ISSUE THREAD

**Issue by sanjay2880** [microsoft/AdaptiveCards#3579]
# Details

Explain your issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards).

I am using adaptivecard lib with directline to display the cards. However I am not getting the anchor tag. It is working on other channels. e.g. "text": "ER-13052"

**Comment by shalinijoshi19** [comment]
@sanjay2880 a couple of requests:
1. Could you update the bug title to be something other than the placeholder text from the bug-filing template :) 
2. Also do you have the sample JSON here that you are working with? 

@ckkashyap heads up on this one in case you have some context at all for us..

**Comment by sanjay2880** [comment]
@shalinijoshi19 @ckkashyap 
Got the fix for the issue. I am using adaptive cards in our angular4 application. We need to also add "**markdown-it**" as dependency which was not there.
"**npm i markdown-it --save**"
Upon adding the dependency it was working as expected. Please add in the readme or documentation which would help others

**Comment by matthidinger** [comment]
Thanks for letting us know! `markdown-it` should be an optional dependency, could you provide any more details on what exactly went wrong before it was added?

**Comment by sanjay2880** [comment]
`<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<title>Adaptive Cards Example</title>

	

	<style type="text/css">
		#exampleDiv {
			width: 250px;
			border: solid 1px black;
		}
	</style>

	<script type="text/javascript">
		function renderCard() {

			// author a card
			// in practice you'll probably get this from a service
			// see http://adaptivecards.io/samples/ for inspiration
			var card = {
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "ColumnSet",
                    "columns": [
                        {
                            "type": "Column",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "spacing": "Small",
                                    "size": "Small",
                                    "weight": "Bolder",
                                    "color": "Accent",
                                    "text": "[ER-13052](https://adaptivecards.io)"
                                }
                            ],
                            "width": "stretch"
                        }
                    ]
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "fallbackText": "This card requires Adaptive Cards v1.2 support to be rendered properly."
};

			// Create an AdaptiveCard instance
			var adaptiveCard = new AdaptiveCards.AdaptiveCard();

			// Set its hostConfig property unless you want to use the default Host Config
			// Host Config defines the style and behavior of a card
			adaptiveCard.hostConfig = new AdaptiveCards.HostConfig({
				fontFamily: "Segoe UI, Helvetica Neue, sans-serif"
				// More host config options
				// You can find example configs here: https://github.com/microsoft/AdaptiveCards/tree/master/samples/HostConfig
			});

			// Set the adaptive card's event handlers. onExecuteAction is invoked
			// whenever an action is clicked in the card
			adaptiveCard.onExecuteAction = function (action) {
				alert("Ow!");
			}
			debugger;

			// Parse the card payload
			adaptiveCard.parse(card);

			// Render the card to an HTML element:
			var renderedCard = adaptiveCard.render();

			// And finally insert it in the page:
			document.getElementById('exampleDiv').appendChild(renderedCard);
		}
	</script>

</head>

<body onload="renderCard()">
	<h3>A card will render below</h3>

	<div id="exampleDiv"></div>

<script type="text/javascript" src="https://unpkg.com/adaptivecards/dist/adaptivecards.min.js"></script></body>

</html>`

If you run the above html you could see that the link is not working as expected. This is as import of 'markdown-it' has been commented. If you uncomment the import the the link will work as expected.

**Comment by matthidinger** [comment]
Thanks for the info. That is indeed working as expected, the markdown will not render properly without the necessary markdown library loaded. We also log an error in the browser developer console to help highlight this. Sorry for the troubles but glad you got it working!
