### ISSUE TITLE
[IOS][Layout] verticalContentAlignment with "center" doesn't take effect in container

### ISSUE THREAD

**Issue by FelixZhang001** [microsoft/AdaptiveCards#3581]
# Platform

* iOS

# Author or host

Host - Teams IOS 

# Version of SDK

latest master.

# Details

Tried to use adaptive card lastest master branch sample app to test below payload.
Seems that "verticalContentAlignment": "center" doesn't take effect and the avatar image position is not correct.

{
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "Container",
      "items": [
        {
          "type": "ColumnSet",
          "columns": [
            {
              "type": "Column",
              "width": "Auto",
              "items": [
                {
                  "type": "TextBlock",
                  "weight": "bolder",
                  "text": "To",
                  "wrap": true
                }
              ],
              "verticalContentAlignment": "center"
            },
            {
              "type": "Column",
              "width": "Auto",
              "items": [
                {
                  "type": "Image",
                  "size": "small",
                  "style": "person",
                  "url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg"
                }
              ],
              "spacing": "small",
              "verticalContentAlignment": "center"
            },
            {
              "type": "Column",
              "width": "Auto",
              "items": [
                {
                  "type": "TextBlock",
                  "text": "Mu Yang",
                  "wrap": true
                }
              ],
              "verticalContentAlignment": "center"
            }
          ]
        },
        {
          "type": "Input.Text",
          "id": "message",
          "placeholder": "Enter Message",
          "isMultiline": true
        }
      ]
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "data": {
        "ux_send": "true",
        "intent:confirm": "true"
      },
      "title": "Send"
    },
    {
      "type": "Action.Submit",
      "data": {
        "intent:cancel": "true"
      },
      "title": "Cancel"
    }
  ]
}

<img width="379" alt="Screen Shot 2019-11-08 at 4 25 22 PM" src="https://user-images.githubusercontent.com/52741892/68462432-7cec0e80-0247-11ea-9aa5-73e2e5c02a15.png">

**Comment by shalinijoshi19** [comment]
@nesalang could you take a first stab pls? Thanks

**Comment by shalinijoshi19** [comment]
@nesalang is looking into this. Thanks

**Comment by shalinijoshi19** [comment]
@nesalang does this need to be ported into master?

**Comment by shalinijoshi19** [comment]
Please go ahead and close once it' checked into master.. thanks! (_unsure why despite using the fixes keyword the issue wasnt closed out automatically_)

**Comment by nesalang** [comment]
**BB Payload**
[samples/v1.1/Test](https://github.com/microsoft/AdaptiveCards/tree/master/samples/v1.1/Tests)
Column.VerticalAlignment.json
