### ISSUE TITLE
Inconsistencies spec

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#3583]
Need to pull together a spec covering what inconsistencies currently exist for our renderers, along with a plan for addressing them and preventing them in the future.

**Comment by shalinijoshi19** [comment]
@paulcam206 can we check this in at this point?

**Comment by paulcam206** [comment]
> @paulcam206 can we check this in at this point?

just need signoff: https://github.com/microsoft/AdaptiveCards/pull/3633

**Comment by jwoo-msft** [comment]
@paulcam206 & @shalinijoshi19 I'm closing this since its associated PR is merged.
