### ISSUE TITLE
AdaptiveShowCardAction default clicked setting

### ISSUE THREAD

**Issue by anprabhu** [microsoft/AdaptiveCards#3584]
Hi,
I am using the Action.ShowCard element in my adaptive card to display multiple sub cards. At this point, these are not set to show up by default. Can we get a field in this element where we can specify whether the sub-card should be displayed by default in the Action.ShowCard element? It will give better control over how the UI displays by default.

I also tried using the ToggleVisibility action, but that does not allow me to toggle the visibility of a sub-card

---
* URL: https://adaptivecards.io/explorer/Action.ShowCard.html

**Comment by RebeccaAnne** [comment]
@anprabhu thanks for reaching out and for the suggestion. In terms of how to solve your problem using the existing (1.2) schema, I think you can make it work using toggle visibility and a container with isVisible set to false. Would something like this work for your scenario:

```
{
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "text": "Here is the main card"
        },
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.ToggleVisibility",
                    "title": "Action.ToggleVisibility",
                    "targetElements": [
                        "subCard"
                    ]
                }
            ]
        },
        {
            "type": "Container",
            "isVisible": false,
            "id": "subCard",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "This is a \"sub-card\" (container)"
                },
                {
                    "type": "TextBlock",
                    "text": "(Put more sub-card elements here)"
                }
            ]
        }
    ]
}
```
