### ISSUE TITLE
[Platform][Broad Issue Category if applicable (eg Accessibility)] [Bug Title]

### ISSUE THREAD

**Issue by SPDoctor** [microsoft/AdaptiveCards#3588]
# Platform

* JavaScript

# Author or host

Samples page - http://adaptivecards.io/samples

# Version of SDK

latest?

# Details

The page http://adaptivecards.io/samples does not render the card. This is because the link to pull in fontawesome doesn't work, presumably because of a typo in which @fontawesome is spelled @fortawesome. There is also a script error with a missing parenthesis in https://adaptivecards.io/js/script.46a93d.js line 427.

**Comment by matthidinger** [comment]
Thanks for filing this! It'll be resolved in the deploy that goes out in ~30 mins
