### ISSUE TITLE
[iOS/Android][Frictionless SDK consumption]

### ISSUE THREAD

**Issue by nesalang** [microsoft/AdaptiveCards#3592]
**What platform is your feature request related to? (Delete other platforms).**

* Android
* iOS

**Is your feature request related to a problem? Please describe.**
try find out issues developers may facing using our mobile SDKs, and understand the frictions devs are facing, and remove the frictions.

**Comment by VikrantSingh01** [comment]
P.R out with change : https://github.com/microsoft/AdaptiveCards/pull/3633/
@Aditya0603 to check.

**Comment by nesalang** [comment]
closed via #3687
