### ISSUE TITLE
[UWP] Symbols incorrectly published for UWP.

### ISSUE THREAD

**Issue by nimercer** [microsoft/AdaptiveCards#3595]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Author or host

Host: Cortana UWP.

# Version of SDK

Currently upgrading to 1.2.4

# Details
The symbols for the UWP renderer are uploaded automatically to the nuget symbol server using the -Symbol flag on nuget pack. However, this server only supports managed code so the symbols can never be found.

Instead we should pack them inside the regular package.

**Comment by shalinijoshi19** [comment]
This is fixed already.
