### ISSUE TITLE
[Android][Rendering Discrepancy between Android and web] [For Choice sets with compact style, when no option is explicitly pre-selected, first option gets pre-selected]

### ISSUE THREAD

**Issue by shbhadra** [microsoft/AdaptiveCards#3605]
# Platform
* Android
# Author or host
Host
# Version of SDK
1.2
# Details
For choice sets of the type shown below in the screenshot, even if no value is specified to be pre selected, the first option shows up pre selected.
<img width="359" alt="Screenshot 2019-11-13 at 3 49 27 PM" src="https://user-images.githubusercontent.com/51158485/68754707-36265c00-062d-11ea-9163-0822c5fe64a0.png">
On the other hand web shows nothing
<img width="686" alt="Screenshot 2019-11-13 at 3 50 25 PM" src="https://user-images.githubusercontent.com/51158485/68754782-5f46ec80-062d-11ea-9e17-5fb7e1239a8d.png">

Please find the json for the card in the attached zip
[choice_set_pre_selected.zip](https://github.com/microsoft/AdaptiveCards/files/3840574/choice_set_pre_selected.zip)

**Comment by shalinijoshi19** [comment]
@shbhadra thanks for reporting this.. I am trying to understand if this is something that is new with 1.2 (and hence a blocker for December for you) or something that you are running into as you upgrade but has persisted pre-1.2 ? Thanks

**Comment by shbhadra** [comment]
@shalinijoshi19 I tried the same by checking out the 1.1 release branch in the SDK repo, and I could repro the issue there aswell, suggesting that the issue has been there from before and has only now been brought to attention by one of our partners. As to whether it is a blocker, @VikrantSingh01 would be in a better position to reply to that.
