### ISSUE TITLE
[SharedModel] DateAndTime tests failing in CI

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#3609]
Presumably this is due to a change in the test execution environment, as neither the test code nor the implementation have changed. See discussion here: https://github.com/microsoft/AdaptiveCards/pull/3607#issuecomment-553551998

**Comment by shalinijoshi19** [comment]
@paulcam206 is this still an issue?  i dont see the sharedmodel builds failing with this error at this point ?

**Comment by paulcam206** [comment]
We should probably still take this change

**Comment by shalinijoshi19** [comment]
i see that it's been merged already in release/1.2 ? At this point we should just merge it into master as well
