### ISSUE TITLE
HTML renderer doesn't implement isRequired for inputs

### ISSUE THREAD

**Issue by dsanvita** [Microsoft/AdaptiveCards#361]
The Input.* card elements all have an isRequired property, but this is not implemented in the HTML renderer.

**Comment by matthidinger** [comment]
We removed isRequired for the v1.0 schema and are not doing client validation at this point, but we will likely revisit in a future release

**Comment by hobpet** [comment]
@matthidinger, I know this one is closed, but the end of your sentence suggests that you will likely revisit in a future release.
Any update on this?
Thanks!

**Comment by matthidinger** [comment]
Hi @hobpet, indeed we are looking at this for the 1.2 release. It's not commited yet but we are doing initial investigations. Once we get closer we will get a 1.2 announcement post published.

https://github.com/Microsoft/AdaptiveCards/issues/808
