### ISSUE TITLE
Ability to access SharePoint URLs from Microsoft host apps

### ISSUE THREAD

**Issue by buildbod** [microsoft/AdaptiveCards#3612]
**What platform is your feature request related to?**

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

**Is your feature request related to a problem? Please describe.**
Images used in Adaptive Cards that are stored in SharePoint Online are not rendered in Adaptive Cards. This forces designers to use publicly hosted images and icons.

**Describe the solution you'd like**
Include support for anonymous SharePoint links to images. Using anonymous links removes the need to authenticate the user to access the image.

**Comment by matthidinger** [comment]
Hi @buildbod, thanks for filing this. There are things you can do to make this work today on all platforms **except** JavaScript. 

Here are the docs on Android, but the APIs are similar, we call them "Resource Resolvers" and they are hooks in the Rendering API to modify outbound image requests.

https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/android/extensibility#iresourceresolver-deprecates-ionlineimageloader

I have renamed this title to reflect the missing support in JavaScript. This is something we will need to add at some point, so I will talk with the team and try to get some traction for our next major release.

**Comment by matthidinger** [comment]
@dclaux  FYI

**Comment by dclaux** [comment]
@matthidinger I might be mistaken, but the request doesn't seem to be about how to make that happen as a host, but rather make authenticated SharePoint images just work in existing hosts ( probably Teams for that matter.) To that extent, the ResourceResolver APIs won't help.

Besides, it **is** possible for a host to hook into images in JavaScript, by manipulating the generated DOM. A host would typically do something like:
- Look for all `<img>` tags in the rendered card sub-tree
- Hide those that point to SharePoint images (for instance), grab their `src`
- Download these images using custom code
- Update the original `<img>` tags by replacing their `src` with, say, a Base64 encoded version of the downloaded image (or an actual URL for that matter, really anything is possible)
- Un-hide the `<img>` tags

Sure, the above isn't necessarily as easy as using the ResourceResolver API, but saying that it is not possible to make this work in JavaScript is inaccurate.

@buildbod, could you clarify whether you are authoring cards, as I suspect, or rendering cards in your own app?

**Comment by buildbod** [comment]
I am authoring cards for them to be rendered in Microsoft products: Outlook, Teams etc.

I want to store the images in SharePoint and have them rendered in Outlook etc.

Does that clarify?






Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by dclaux** [comment]
Yes, and that is what I had understood.

The request is therefore for Microsoft products to allow loading images from SharePoint URLs, using the current user's authentication context.

**Comment by dclaux** [comment]
Could you update the description of the issue to include these details?

**Comment by buildbod** [comment]
Yes that is a good description of my request.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by matthidinger** [comment]
Thanks for the clarification folks. I've updated the title, and filed a related issue #3643 to track the ability for JS Hosts to easily handle authenticated image downloads

**Comment by RebeccaAnne** [comment]
You may be able to solve your scenario by encoding your image as a data URI.

If that doesn't work for you, work would need to be done in the Microsoft hosts to address this scenario.
