### ISSUE TITLE
[BotFramework] Different date format for Date Input

### ISSUE THREAD

**Issue by wal88** [microsoft/AdaptiveCards#3613]
**What platform is your feature request related to? (Delete other platforms).**

* .NET HTML
* Android
* iOS

**Is your feature request related to a problem? Please describe.**
MM/dd/yyyy is not the typical format for many countries. I would like to change it to dd/MM (at least when displaying to users)

**Describe the solution you'd like**
An attribute to allow format change of displayed date. Otherwise a boolean attribute to toggle to "dd/MM/yyyy" format

**Describe alternatives you've considered**
 a boolean attribute to toggle to "dd/MM/yyyy" format will suffice as well

**Additional context**
Could not find it in the Designer or Schema

**Comment by matthidinger** [comment]
@paulcam206 we should consider this for all up inconsistency. It seems like the date picker should be rendered with the **users** locale, as opposed to the card author specifying it. We also have the `lang` attribute on the `AdaptiveCard` but I'm not sure if that applies here or if it's even used for `Input.Date`

**Comment by walsaadysixco** [comment]
As a side note, the AdaptiveTimeInput renders to 12hour or 24hour format based on user's system settings

**Comment by Chekrii** [comment]
Hello all,

We are also facing the same issue, Is there any workaround for this?

After selecting the value from the date picker, we would like to show a different format than ` Apr 28, 2019 `  in Teams desktop.

Please find the screenshot.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/49824279/83166870-271c7c80-a12d-11ea-9b2c-8b386bbdb6da.png)

Thanks.

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.
