### ISSUE TITLE
Adaptive card Submit button issue

### ISSUE THREAD

**Issue by vikramdadwal** [microsoft/AdaptiveCards#3616]
# Platform

I have raised an issue with BOT webchat team, but it seems it could be an adaptive card issue. Please take a look:

https://github.com/microsoft/BotFramework-WebChat/issues/2605

* JavaScript

# Author or host

# Version of SDK

1.2.4

# Details

Explain your issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards).

**Comment by shalinijoshi19** [comment]
@siduppal / @dclaux  FYI; @vikramdadwal what makes you think this is an AdaptiveCards issue please? I couldnt find a reference to this in the issue you reference above. @dclaux heads up.

**Comment by dclaux** [comment]
I'm not sure how that could possibly be an AC issue. Definitely seems to be a Teams problem.

**Comment by shalinijoshi19** [comment]
@siduppal / @clearab could you please take a look at this and the referenced Teams issue to help us understand why this is suspected to be an AC issue? Thanks again!

**Comment by RebeccaAnne** [comment]
The linked issue was investigated on the webchat side, and this doesn't seem to be a cards issue.
