### ISSUE TITLE
VS Code : Unable to load schema when behind a proxy

### ISSUE THREAD

**Issue by TechWatching** [Microsoft/AdaptiveCards#363]
I can't have intellisense when using the Adaptive Card Viewer extension behind a proxy.
I get the error "Unable to load schema from ....".

VS Code : 1.13.0-insiders
Adaptive Card Viewer : 1.0.7

**Comment by matthidinger** [comment]
Hmm that's kind of a bummer. I'm not sure there's anything particular we can do to enable this then. Perhaps you can file an issue with VS Code?

**Comment by matthidinger** [comment]
Closing stale issue, please re-open if more information is found
