### ISSUE TITLE
Support for different "categories" of templates in template service

### ISSUE THREAD

**Issue by palktonderAtpowelno** [microsoft/AdaptiveCards#3632]
**Describe the solution you'd like**
We are trying to use adaptive cards both for input and presentation of data. A template for data editing will/should look really different from one used for read-only presentation. There is some support for turning off interactivity for an adaptive card with input fields, but then those fields just disappear, which doesn't make sense for presentation.

Being able to categorize a template to be used for editing and another for presentation, and then use that category to retrieve a suitable template from the template service, would widen the scope of the service, and make it more usable. If no category was given, the default/fallback template (presentation?) would be returned. The response should include the category of the template, if any.

**Describe alternatives you've considered**
The difference between editing and presentation could potentially be handled through conditionals(?), but that would make the template very involved and hard to maintain

**Comment by RebeccaAnne** [comment]
This is a good suggestion, but not something that's on our roadmap at this time. We may reconsider it in the future, or if you would like to make a contribution please see our contribution guidelines [here](https://github.com/microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md).
