### ISSUE TITLE
[iOS]Samples\1.2\Scenarios\FlightDetails.json isn't rendering correctly

### ISSUE THREAD

**Issue by shalinijoshi19** [microsoft/AdaptiveCards#3637]
# Platform
* iOS (13+)

# Version of SDK

release/1.2

# Details

This is what i am seeing; Notice the clipped Action.Submit in the ActionSet to the bottom right : 
![image](https://user-images.githubusercontent.com/20822397/69387898-1f5eb580-0c7c-11ea-8c3e-e016c38f3569.png)

**Comment by nesalang** [comment]
@shalinijoshi19 
Thank you for testing iOS!
This definitely is needed to be fixed. But it's less likely a stopper fro teams. The preconditions of this bug is pretty rare; One of superviews of ActionSet has to be a column, and buttons wouldn't fit in the width provided for the ActionSet.

**Comment by shalinijoshi19** [comment]
Closing. This was fixed in 1.2.7
