### ISSUE TITLE
[iOS] Both 1.2\tests\newlinecard with \r  and \n fail to render in the Custom Renderer mode in the test app

### ISSUE THREAD

**Issue by shalinijoshi19** [microsoft/AdaptiveCards#3638]
# Platform
* iOS

# Version of SDK
release/1.2

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

# Details

The newline card renders correctly in our default iOS renderer in the Visualizer app, but when switched to the "Enable Custom Renderer" mode the newlines aren't getting rendered correctly.

![image](https://user-images.githubusercontent.com/20822397/69389451-eaa12d00-0c80-11ea-9c90-7f391a1cd58c.png)

**Comment by shalinijoshi19** [comment]
Am seeing the same behavior for the other '\n' card: 
![image](https://user-images.githubusercontent.com/20822397/69389689-a19da880-0c81-11ea-9828-71ca4b7a3da5.png)

**Comment by nesalang** [comment]
@shalinijoshi19 
Thank you for testing iOS!

This shouldn't be blocker for Teams. The custom renderer here is added to provide a sample code of how to add custom renderer. I can update the custom renderer to also support /r and /n, but this implementations of custom renderers are not part of the adaptive cards package we release.
