### ISSUE TITLE
Resource Resolver support in JS

### ISSUE THREAD

**Issue by productboard-ac** [microsoft/AdaptiveCards#3643]
This feature tracks adding the `ResourceResolver` API to JavaScript to make it easy for a Host to download authenticated image URLs from card payloads.

* [Android docs]( https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/android/extensibility#iresourceresolver-deprecates-ionlineimageloader)
* Related issue (although rather outdated): #138

**Comment by productboard-ac** [comment]
Link to feature: https://adaptivecards.productboard.com/feature-board/planning/features/3377322

**Comment by dclaux** [comment]
Just as an FYI, it is already possible in JS to do exactly what the resource resolver APIs allows on other platforms. It involves slightly modifying the generated DOM, something fairly simple to do. The resource resolver API would merely be sugar on top.

**Comment by RebeccaAnne** [comment]
This is now tracked by #6366
