### ISSUE TITLE
[JavaScript][Support ellipsis for multi line text wrap in adaptive card] 

### ISSUE THREAD

**Issue by atishayv** [microsoft/AdaptiveCards#3644]
# Platform

All platforms

# Author or host

Host : Microsoft Search

# Version of SDK

adaptivecards-designer@0.7.1

# Details

For multi line wrap in TextBlock element, ellipsis doesn't comes. 

For single line wrap, it looks like : 
![image](https://user-images.githubusercontent.com/13940020/69626553-dee1ac00-106e-11ea-8896-4400e6b92f71.png)
But for 2 line wrap, ellipsis doesn't comes : 
![image](https://user-images.githubusercontent.com/13940020/69626627-03d61f00-106f-11ea-9949-d34d36a9f39c.png)
Want it to be something like : 
![image](https://user-images.githubusercontent.com/13940020/69626677-1a7c7600-106f-11ea-91ed-bd8d3f4c8223.png)

**Comment by shalinijoshi19** [comment]
@dclaux / @matthidinger thoughts on this?

**Comment by dclaux** [comment]
The right solution for this is to use [-webkit-line-clamp](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp) which seems to besupported on all modern browsers. I will investigate as time permits.

**Comment by paulcam206** [comment]
looks like [`line-clamp`](https://caniuse.com/?search=line-clamp) is generally available, so it could be used to implement this.
