### ISSUE TITLE
.NET Accessibility  Alt text support for images and buttons in Bot Framework PromptOptions

### ISSUE THREAD

**Issue by murcinar** [microsoft/AdaptiveCards#3647]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.

If you're an author, who are you sending cards to?
We are hosting our own adaptive cards for our Bot.

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...
Microsoft.Bot.Builder 4.6.2

# Details

Explain your issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards).

Through Accessibility Scan, we have received the following issues where we could not found a solution to implement using Adaptive Cards:
**Issue description: Ensures <img> elements have alternate text or a role of none or presentation**
**Issue description: Ensures buttons have discernible text**
These issues occurred where we have created suggested action items (like thumbs up/down, create a ticket, etc) using the PromptOptions class in Microsoft.Bot.Builder.Dialogs. Using the PromptActions, we see that there is no way to add alt text to an image or a button.

Can you please advise on how to achieve accessibility on the PromptOptions in Adaptive Cards?

Thank you!
Murat

**Comment by shalinijoshi19** [comment]
@Murat thanks for reporting; May i request you to kindly update the title of the issue from the placeholder template text, to be more reflective of what it is you are bringing up here please? Meanwhile @dclaux / @dandriscoll any thoughts here for the bot customer? I know we have a bunch of newer JS platform accessibility bugs filed last month that i'll try to consolidate in a single rollup github issue for visibility outside of the internal database

**Comment by murat** [comment]
Hi @shalinijoshi19 I think you are mentioning the wrong @murat

**Comment by murcinar** [comment]
> @murcinar / Murat: Thanks for reporting; May i request you to kindly update the title of the issue from the placeholder template text, to be more reflective of what it is you are bringing up here please? Meanwhile @dclaux / @dandriscoll any thoughts here for the bot customer? I know we have a bunch of newer JS platform accessibility bugs filed last month that i'll try to consolidate in a single rollup github issue for visibility outside of the internal database

Hi Shalini, thanks for your reply. I have updated the title of the issue and please let me know any questions or clarifications you need.
Thank you.

**Comment by murcinar** [comment]
@dclaux and @dandriscoll please let me know if you have any insights/ answer to the issue I described above and please let me know if you need any clarification on the problem. Thank you!

**Comment by murcinar** [comment]
I've had a conversation with @dclaux, Thank you for the explanation! It seems like the issue is not related to Adaptive Cards hence closing the bug.

**Comment by shalinijoshi19** [comment]
@murcinar that's great that you were unblocked. Can you also go ahead and update the bug comments with a summary of your discussion/what you learned for the benefit of others who might run into the same problem? thanks again!
