### ISSUE TITLE
[ALL]Font Awesome Icons Support

### ISSUE THREAD

**Issue by vivek-dhayalan** [microsoft/AdaptiveCards#3649]
**What platform is your feature request related to? (Delete other platforms).**

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

**Is your feature request related to a problem? Please describe.**
While designing some cards I have need to include icons as part of my card. Most of the time in web app I'll use FontAwesome for standard look and feel also, it makes my life easier. If I want too use icons in adaptive cards then I need to go through image where I give the URL of icon that I need to add in the card.

**Describe the solution you'd like**
With out of box support of FontAwesome in Adaptive cards I'll not have the pain of hosting the icons and using it would be out of the box.

**Additional context**
https://fontawesome.com/
<i class="far fa-user-astronaut fa-sm fa-flip-horizontal" style="color: #ff922b;"></i>

We should also have the provision to configure license for the same.

**Comment by KamilPacanek** [comment]
Are we having any update on that? Is that possible to implement? Maybe I can help with anything that needs to be done to make it possible to use some icons OotB? Font Awesome or Fabric UI Icons would be great.

**Comment by darrenparkinson** [comment]
I stumbled across this searching for some kind of icon support on Adaptive Cards -- this would be really useful.

**Comment by RebeccaAnne** [comment]
This is a good suggestion, but not something that's on our roadmap at this time. We may reconsider it in the future, or if you would like to make a contribution please see our contribution guidelines [here](https://github.com/microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md).

**Comment by rvdwegen** [comment]
I'd like to bring this up once again. Some sort of support for font based icons would be ideal. Unicode would already help a lot.
