### ISSUE TITLE
[iOS/Android] Intra-mobile inconsistencies spec

### ISSUE THREAD

**Issue by shalinijoshi19** [microsoft/AdaptiveCards#3653]
# Related Issues
## Open Issues
#3734 [Resolution By Design] Customizing ACRButton 
#3733 [New Issue] Input Text not displaying place holder text
#3712 [Priority Urgent] Random Order in Voice-Over
#3705 [Priority Urgent] Action Orientation
#3702 [Priority Normal] Input Retention
#3702 [Priority Normal] Excess spacing in empty text blocks
## In Code Review
#3672 Time rendering format on android is different as that of web
#3700 Container background image does not cover card
#3718 Custom Renderer fallback handling
## Closed Issues
#3680 Telephony Service; iOS does not recognize telephone link by default. Each 
#3671 Date input component does not honor the default value
#3693 Input.Text element with multi line isn't vertically scrollable
#3695 Number of Actions Setting Is Not Supported

# Details
* Android
* iOS

Child of #3583 and #3592 and will feed into our overall consistency story.  This should focus on the inconsistencies we have observed esp around:
1. Android renderer vs iOS renderer
2. Android/iOS renderer vs other renderers
But for this iteration, the scope will be limited to Teams. We're not working on hacks that only work for Teams, rather we're addressing a subset of the whole problem set at a time. 

- #3705 identified one major source of inconsistency between mobile and desktop, the width.
 We can add card width property at Designer and make it prominent. 
 Address the differences in actions rendering when actions are squeezed in the width.
- #3680 example of inconsistency in default behaviors provided by different platforms.

**Comment by VikrantSingh01** [comment]
@nesalang : Can you kindly update intra mobile discrepancy spec with the specific issue you are tracking internally for the team's eas of access. CC- @shalinijoshi19

**Comment by shalinijoshi19** [comment]
@jwoo-msft are we on track for reviewing + checking this in for 20.09?
