### ISSUE TITLE
JS Data Binding for json properties containing a number does not work

### ISSUE THREAD

**Issue by mberry73** [microsoft/AdaptiveCards#3658]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* JavaScript (The only one I tried)

# Author or host
Host: A Prototype app

# Version of SDK
nuget 1.2.5

# Issue
Data binding for jsson objects which contain a number in the property does not work.
The easiest way to repro this is to use the desinger here: https://adaptivecards.io/designer/

With the card payload:
```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "text": "{title}"
        },
        {
            "type": "TextBlock",
            "text": "{title1}"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

and the sample json data:
```
{
    "title": "Publish Adaptive Card Schema",
    "title1": "Publish Adaptive Card Schema",

}
```

**Comment by matthidinger** [comment]
Hi @mberry73 thanks for filing this. I don't see a number in the sample data you provided, but I think I know what you're referring to. We are currently working on a plan to support this, but in the meantime, can you try this:

Data
```json
{
  "myNum": 3
}
```

Template
```json
{
   "type": "TextBlock",
   "text": "{myNum} "
}
```

Notice the **space** after the binding expression. This forces a cast to a string. Let us know if this helps

**Comment by mberry73** [comment]
Sorry to be unclear. But the problem in the example above is the property «title1».
It’s not about the value of properties, but the property itself. It does not bind if it contains a numerical character.

You can easily see that if you use the data and template I provided above.

**Comment by dclaux** [comment]
@mberry73 thanks for reporting. This is indeed a limitation (a bug) that needs to be fixed. I'll try to get to it ASAP.

**Comment by NxP4Code** [comment]
I think I am still facing this issue. I just wanted to confirm. I have integer coming in my JSON data, but final output is completely omitting the text property. I am using JS API. Can you please confirm if this is fixed or it's me doing something wrong.

**Comment by NxP4Code** [comment]
I just tried with double quotes as mentioned by @matthidinger . I get result like this.

![image](https://user-images.githubusercontent.com/56322272/80022158-40cd0300-84a1-11ea-8775-127019756a34.png)

**Comment by dclaux** [comment]
@NxP4Code please update to the latest templating package if you haven't yet and use the toString function:
`"text": "{toString(myNum)}"`

**Comment by NxP4Code** [comment]
It worked with {toString(num)}

**Comment by matthidinger** [comment]
The workaround above is the currently accepted solution so closing for now
