### ISSUE TITLE
[MSTeams]IamBack functionality on Input.Number

### ISSUE THREAD

**Issue by Chekrii** [microsoft/AdaptiveCards#3664]
**Platforms**
*MsTeams

Can we get the IamBack functionality on Clicking on Action.submit in Adaptive card and the Iamback message should be of the Value of  Input.Number 
![TeamsInput.Number](https://user-images.githubusercontent.com/49824279/70298303-30302f00-1817-11ea-9bc4-7bde3c24c11e.PNG)
In the above Image On clicking on "OK"(Action.Submit) the value enter by the User in Input.Number should be echo back in the bot chat (Value of Input.Number should be Iamback on clicking Action.Submit) in Teams

Adaptive Card Json:-

{
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "text": "How many Days would you like to book?",
      "size": "Medium"
    },
    {
      "type": "Input.Number",
      "placeholder": "Placeholder text",
      "id": "TimeOffNumber",
      "min": 1,
      "value": "1",
      "max": 15
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Ok"
    }
  ]
}

**Comment by Chekrii** [comment]
![IamBack](https://user-images.githubusercontent.com/49824279/70598028-e4fb8f00-1c0f-11ea-9e82-e20f52ddbc26.PNG)

Hello,

Can we have this.. where the user will enter the date in Adaptive card and Click on Action.submit can we IamBack the number entered in the input.Number 

Thanks.

**Comment by Chekrii** [comment]
Can someone please reply on this

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4281
