### ISSUE TITLE
Adaptive Card - Render PDF, Office Docs, Iframe (web page) 

### ISSUE THREAD

**Issue by sowsan** [microsoft/AdaptiveCards#3670]
* .NET HTML
* JavaScript

**Is your feature request related to a problem? Please describe.**
Not finding a way to render office docs, pdf and webpage within a card

**Describe the solution you'd like**
Render a PDF, Office docs - excel, word, powerpoint and also a webpage as iFrame 

**Describe alternatives you've considered**
nil

**Additional context**
nil

**Comment by dclaux** [comment]
Hi @sowsan, I don't think that's going to happen. Being able to render pretty much random HTML content within an Adaptive Card would defeat the purpose of Adaptive Cards in the first place.

**Comment by yogi-bhargav** [comment]
Hi, I am also Using teams Webview to render PDF URL using HTML code, embed tag but it is not displaying in teams Webview.

Is there any way we can render the PDF in Microsoft Teams?
