### ISSUE TITLE
[Android][Inconsistency between android and web] [Time rendering format on android is different as that of web]

### ISSUE THREAD

**Issue by shbhadra** [microsoft/AdaptiveCards#3672]
# Platform
* Android
* iOS
# Author or host
HOST

# Version of SDK
1.2.5

# Details
The time rendered in the Input.Time component, on android also shows the seconds whereas it doesn't on web. With reference to the card json attached
View of the card in web
<img width="391" alt="Screenshot 2019-12-10 at 5 59 09 PM" src="https://user-images.githubusercontent.com/51158485/70529540-ca290c00-1b76-11ea-9036-9e4b12a9979a.png">
View of the card on android
<img width="304" alt="Screenshot 2019-12-10 at 6 00 16 PM" src="https://user-images.githubusercontent.com/51158485/70529607-f3499c80-1b76-11ea-84eb-0b961ded0d79.png">
[time_render.json.zip](https://github.com/microsoft/AdaptiveCards/files/3944830/time_render.json.zip)
```json
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "text": "What time do you want to meet?"
    },
    {
      "type": "Input.Time",
      "id": "time",
      "min": "09:00",
      "max": "17:00",
      "value": "15:30"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "OK"
    }
  ]
}
```

iOS would not show "PM" in this use case.

**Comment by shalinijoshi19** [comment]
Hey Almedina-ms, can you please pick this up wiht high priority for this month's January patch release? Thanks!
