### ISSUE TITLE
[iOS][UI] [Image size or height setting doesn't reflect correctly as desktop view]

### ISSUE THREAD

**Issue by shenred176** [microsoft/AdaptiveCards#3677]
# Platform
mobile - iOS

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.
host, using bot on Teams

If you're an author, who are you sending cards to?

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...
AdaptiveCard version 1.0
NETCore 2.1
Microsoft.Bot.Builder.Dialogs 4.6.3
Microsoft.Bot.Builder.Integration.AspNet.Core 4.6.3

# Details

Desktop view correctly respond to image size or height setting. However, mobile view does not.
First card has one image height set as "100px", second card has three images size set as "medium", "large", and "small" 

desktop view: 
![desk](https://user-images.githubusercontent.com/5407251/70676780-2442d380-1c42-11ea-9b13-53403bd78940.JPG)

mobile view:
![mob](https://user-images.githubusercontent.com/5407251/70676781-2442d380-1c42-11ea-8632-0665b535f14c.jpg)

adaptiveCard.json
https://microsoft.sharepoint.com/:u:/t/skypespacesteamnew/EcoFXku_eRVDmDHQ1I7hM20BcWvO_grlgfbmaikUgjGEmg?e=JSYe5H

**Comment by shalinijoshi19** [comment]
@nesalang could you take a first pass at this? Also do we need to track this with the MsftTeams* label(s)? @VikrantSingh01 FYI
