### ISSUE TITLE
Format Buttons with IconURL Images

### ISSUE THREAD

**Issue by dkonyayev** [microsoft/AdaptiveCards#3682]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML

# Author or host

Author
If you're an author, who are you sending cards to?

BotFramework WebChat

# Version of SDK

Latest

# Details

I want to create a simple Yes/No action card, and I assigned iconURLs to my buttons. My goal is to make buttons smaller and basically have just the icons displayed. However, what I get back is not what I expected. Can you check my attached images and let me know how to adjust it?
<img width="304" alt="adaptive-button-with-image" src="https://user-images.githubusercontent.com/15344498/70916996-915fbb80-1fea-11ea-8a14-bdbbc1a6b9b5.PNG">

**Comment by shalinijoshi19** [comment]
@dkonyayev can you share your sample adaptiveCards json payload? @ckkashyap / @dandriscoll is this something that your team could help take a first pass at?

**Comment by paulcam206** [comment]
Closing due to lack of response
