### ISSUE TITLE
[Teams][Rating System] Request to create a http method for Ajax call

### ISSUE THREAD

**Issue by Raj-kishore** [microsoft/AdaptiveCards#3683]
**What platform is your feature request related to?**

* JavaScript

**Is your feature request related to a problem? Please describe.**
The methods such as Action.submit can be used to rate a document, but apart from this an additional approach such as Action.http can be helpful. 

**Describe the solution you'd like**
This feature can be helpful in the Teams channel for rating carousel items with Ajax call instead of dwelling upon the Action.submit call since this event is a part of the dialog flow. A button event like Action.http should make an Ajax call independent of the flow and should run in the background when called. Adding Animation such on hover star rating image change and after making the star rating it should update the rating images on the go.  

**Describe alternatives you've considered**
Any alternative approach is to add extra methods to the Action.submit to deal with Ajax call and on success, provide API to update response in the Adaptive card. 

**Additional context**
Solutions in the comment sections are welcome. I will be grateful if I would get relevant responses from the community.

**Comment by paulcam206** [comment]
Please use [Universal Actions in Teams](https://docs.microsoft.com/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview)
