### ISSUE TITLE
[Bot Framework Emulator][Adaptive card not rendering because of incorrect value type] [Better error message needed or card should render in emulator]

### ISSUE THREAD

**Issue by geo-msft** [microsoft/AdaptiveCards#3684]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Bot Framework emulator, version 4.7.0
* JavaScript
* Node.js 

# Author or host

Using Bot Framework emulator to test bots with adaptive cards. 

# Version of SDK

"botbuilder": "~4.6.1",
 "dotenv": "^8.2.0",
 "restify": "~8.4.0"

# Details

ISSUE
===================

Using the following code in Node.js bot (please reach out privately for the code) we get this error when rendering the card in the emulator: 

![image](https://user-images.githubusercontent.com/57954688/70978287-2e3c5a80-20b8-11ea-9cc9-b4495596fa2a.png)

{
    "error": 8,
    "message": "All choices in an Input.ChoiceSet must have their title and value properties set."
 }

EXPECTED RESULT
=====================

The card should render properly or a more intuitive error message should be displayed to the user. 
Example of error message: "Value type is invalid: expecting string and received {type}", where {type} in this case is a number. 

OTHER DETAILS
===========================
In Azure portal, when testing using Test in webchat, the card is rendered.

We expect a better error message which should point us to what the issue is. 
OR the card should render in the emulator as well, as the same code works properly in Azure webchat.

**Comment by geo-msft** [comment]
`// in bot.js file: 

const { ActivityHandler } = require('botbuilder');
const { MessageFactory, CardFactory } = require('botbuilder');

class EchoBot extends ActivityHandler {
    constructor() {
        super();
        // See https://aka.ms/about-bot-activity-message to learn more about the message and other activity types.    
        
        function selectDurationContactForEBCPIntake(duration) {
const card = {
'type': 'AdaptiveCard',
'version': '1.0',
'body': [
{
'type': 'TextBlock',
'text': "Ok, now let's set the duration:",
'wrap': true
},
{
'type': 'TextBlock',
'text': 'What was the contact duration?',
'wrap': true
},
{
'type': 'ColumnSet',
'columns': [
{
'type': 'Column',
'width': 'auto',
'id': 'ColumnIntakeSelectedContactDuration',
'items': [
{
'type': 'Input.ChoiceSet',
'id': 'CompactIntakeSelectedContactDuration',
'value': duration[0],
'choices': duration.map(d => {
return {
'title': d,
'value': d
};
})
}
]
},
{
'type': 'Column',
'width': 'auto',
'items': [{
'type': 'TextBlock',
'text': 'Minutes',
'wrap': true
}
]
}
]
},
{
'type': 'TextBlock',
'text': 'What was the documentation duration?',
'wrap': true
},
{
'type': 'ColumnSet',
'columns': [
{
'type': 'Column',
'width': 'auto',
'id': 'ColumnIntakeSelectedDocumentationDuration',
'items': [
{
'type': 'Input.ChoiceSet',
'id': 'CompactIntakeSelectedDocumentationDuration',
'value': duration[0],
'choices': duration.map(d => {
return {
'title': d,
'value': d
};
})
}
]
},
{
'type': 'Column',
'width': 'auto',
'items': [
{
'type': 'TextBlock',
'text': 'Minutes',
'wrap': true
}
]
}
]
}
],
'actions': [
{
'type': 'Action.Submit',
'title': 'Submit'
}
],
'$schema': 'http://adaptivecards.io/schemas/adaptive-card.json'
};


return card;
}
       // additional comments 

        this.onMessage(async (context, next) => {
            
            var duration = [];
for (let index = 1; index < 121; index++) {
duration.push(index);
}
          //  await context.sendActivity(`You said '${ context.activity.text }'`);
await context.sendActivity({
attachments: [CardFactory.adaptiveCard(selectDurationContactForEBCPIntake(duration))]
});

            // By calling next() you ensure that the next BotHandler is run.
            await next();
        });

        this.onMembersAdded(async (context, next) => {
            const membersAdded = context.activity.membersAdded;
            for (let cnt = 0; cnt < membersAdded.length; ++cnt) {
                if (membersAdded[cnt].id !== context.activity.recipient.id) {
                    await context.sendActivity('Hello and welcome!');
                }
            }
            // By calling next() you ensure that the next BotHandler is run.
            await next();
        });
    }
    
     
}

module.exports.EchoBot = EchoBot;`

**Comment by shalinijoshi19** [comment]
Thanks for reporting @geo-msft. Is there sample json that you can include in teh report.  @ckkashyap , @dandriscoll it doesnt appear that this is an AdaptiveCards issue does it?

**Comment by geo-msft** [comment]
Hi,


Thanks a lot for reaching out.

As I stated on the GitHub issue, it appears only in the bot framework emulator.
In Azure webchat control, the card is rendered properly.

I would like to include the code, but it is a customer code.
Is there any private way to share with you the code? If yes, how can I share it, so that is viewable only inside Microsoft?

What are your Microsoft aliases?
Do not hesitate to reach me, if you need other info.

Thank you again.

Best regards, --
Georgiana Nitu
Developer Support Engineer | Microsoft Romania | +40 (31) 1330601  |  genitu@microsoft.com<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgenitu%40microsoft.com&data=02%7C01%7Cgenitu%40microsoft.com%7C8dd5d747749a41813f3c08d74e2e3076%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063832607038092&sdata=0DxUo1UMUNbWhyTgEgERaS50kl7yenQE30oDW5tzT%2FQ%3D&reserved=0>
Customer Services and Support
Manager contact: Alex Vulcan <alvulcan@microsoft.com<mailto:alvulcan@microsoft.com>>
[Microsoft]

**Comment by geo-msft** [comment]
Hi, 

Thank you for looking into it. 

Here is the bot sample code:

`// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

const { ActivityHandler } = require('botbuilder');
const { MessageFactory, CardFactory } = require('botbuilder');

class EchoBot extends ActivityHandler {
    constructor() {
        super();
        // See https://aka.ms/about-bot-activity-message to learn more about the message and other activity types.    
        
        function selectVal(myvalues) {
const card = {
'type': 'AdaptiveCard',
'version': '1.0',
'body': [
{
'type': 'TextBlock',
'text': "Select the value:",
'wrap': true
},
{
'type': 'TextBlock',
'text': 'What was value 1?',
'wrap': true
},
{
'type': 'ColumnSet',
'columns': [
{
'type': 'Column',
'width': 'auto',
'id': 'ColumnIntakeSelectedContactDuration',
'items': [
{
'type': 'Input.ChoiceSet',
'id': 'CompactIntakeSelectedContactDuration',
'value': myvalues[0],
'choices': myvalues.map(d => {
return {
'title': d,
'value': d
};
})
}
]
},
{
'type': 'Column',
'width': 'auto',
'items': [{
'type': 'TextBlock',
'text': 'Category 1',
'wrap': true
}
]
}
]
},
{
'type': 'TextBlock',
'text': 'What were the reference values?',
'wrap': true
},
{
'type': 'ColumnSet',
'columns': [
{
'type': 'Column',
'width': 'auto',
'id': 'myvaluescolumn',
'items': [
{
'type': 'Input.ChoiceSet',
'id': 'myvaluescolumnselect',
'value': myvalues[0],
'choices': myvalues.map(d => {
return {
'title': d,
'value': d
};
})
}
]
},
{
'type': 'Column',
'width': 'auto',
'items': [
{
'type': 'TextBlock',
'text': 'Minutes',
'wrap': true
}
]
}
]
}
],
'actions': [
{
'type': 'Action.Submit',
'title': 'Submit'
}
],
'$schema': 'http://adaptivecards.io/schemas/adaptive-card.json'
};


return card;
}
       // additional comments 

        this.onMessage(async (context, next) => {
            
            var myvalues = [];
for (let index = 1; index < 4; index++) {
myvalues.push(index);
}
          //  await context.sendActivity(`You said '${ context.activity.text }'`);
await context.sendActivity({
attachments: [CardFactory.adaptiveCard(selectVal(myvalues))]
});

            // By calling next() you ensure that the next BotHandler is run.
            await next();
        });

        this.onMembersAdded(async (context, next) => {
            const membersAdded = context.activity.membersAdded;
            for (let cnt = 0; cnt < membersAdded.length; ++cnt) {
                if (membersAdded[cnt].id !== context.activity.recipient.id) {
                    await context.sendActivity('Hello and welcome!');
                }
            }
            // By calling next() you ensure that the next BotHandler is run.
            await next();
        });
    }
    
     
}

module.exports.EchoBot = EchoBot;
`

In the emulator, I have the error. 

In the Azure portal, the card is rendered. 

![image](https://user-images.githubusercontent.com/57954688/72081481-39755580-3307-11ea-96b6-7bbd6f19f8ad.png)



Here is the JSON in the emulator:
`{
  "attachments": [
    {
      "content": {
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "actions": [
          {
            "title": "Submit",
            "type": "Action.Submit"
          }
        ],
        "body": [
          {
            "text": "Select the value:",
            "type": "TextBlock",
            "wrap": true
          },
          {
            "text": "What was value 1?",
            "type": "TextBlock",
            "wrap": true
          },
          {
            "columns": [
              {
                "id": "ColumnIntakeSelectedContactDuration",
                "items": [
                  {
                    "choices": [
                      {
                        "title": 1,
                        "value": 1
                      },
                      {
                        "title": 2,
                        "value": 2
                      },
                      {
                        "title": 3,
                        "value": 3
                      }
                    ],
                    "id": "CompactIntakeSelectedContactDuration",
                    "type": "Input.ChoiceSet",
                    "value": 1
                  }
                ],
                "type": "Column",
                "width": "auto"
              },
              {
                "items": [
                  {
                    "text": "Category 1",
                    "type": "TextBlock",
                    "wrap": true
                  }
                ],
                "type": "Column",
                "width": "auto"
              }
            ],
            "type": "ColumnSet"
          },
          {
            "text": "What were the reference values?",
            "type": "TextBlock",
            "wrap": true
          },
          {
            "columns": [
              {
                "id": "myvaluescolumn",
                "items": [
                  {
                    "choices": [
                      {
                        "title": 1,
                        "value": 1
                      },
                      {
                        "title": 2,
                        "value": 2
                      },
                      {
                        "title": 3,
                        "value": 3
                      }
                    ],
                    "id": "myvaluescolumnselect",
                    "type": "Input.ChoiceSet",
                    "value": 1
                  }
                ],
                "type": "Column",
                "width": "auto"
              },
              {
                "items": [
                  {
                    "text": "Minutes",
                    "type": "TextBlock",
                    "wrap": true
                  }
                ],
                "type": "Column",
                "width": "auto"
              }
            ],
            "type": "ColumnSet"
          }
        ],
        "type": "AdaptiveCard",
        "version": "1.0"
      },
      "contentType": "application/vnd.microsoft.card.adaptive"
    }
  ],
  "channelId": "emulator",
  "conversation": {
    "id": "b2431ae0-32f5-11ea-aee9-29a1af511730|livechat"
  },
  "from": {
    "id": "f5af5920-32f4-11ea-aee9-29a1af511730",
    "name": "Bot",
    "role": "bot"
  },
  "id": "b3e99ef0-32f5-11ea-bf3f-9f4a8a2fc32b",
  "localTimestamp": "2020-01-09T17:35:45+02:00",
  "locale": "en-US",
  "recipient": {
    "id": "1b685103-8f84-44d0-82f4-2f510c8dcdbd",
    "role": "user"
  },
  "replyToId": "b3e7f140-32f5-11ea-bf3f-9f4a8a2fc32b",
  "serviceUrl": "http://localhost:50620",
  "timestamp": "2020-01-09T15:35:45.503Z",
  "type": "message"
}`


I would expect a proper error message in the emulator or consistency across the channels. 

Let me know if you need other details. Thank you!

**Comment by geo-msft** [comment]
The JSON from the adaptive card which I see in the emulator: 

`{ "content": { "$schema": "http://adaptivecards.io/schemas/adaptive-card.json", "actions": [ { "title": "Submit", "type": "Action.Submit" } ], "body": [ { "text": "Select the value:", "type": "TextBlock", "wrap": true }, { "text": "What was value 1?", "type": "TextBlock", "wrap": true }, { "columns": [ { "id": "ColumnIntakeSelectedContactDuration", "items": [ { "choices": [ { "title": 1, "value": 1 }, { "title": 2, "value": 2 }, { "title": 3, "value": 3 } ], "id": "CompactIntakeSelectedContactDuration", "type": "Input.ChoiceSet", "value": 1 } ], "type": "Column", "width": "auto" }, { "items": [ { "text": "Category 1", "type": "TextBlock", "wrap": true } ], "type": "Column", "width": "auto" } ], "type": "ColumnSet" }, { "text": "What were the reference values?", "type": "TextBlock", "wrap": true }, { "columns": [ { "id": "myvaluescolumn", "items": [ { "choices": [ { "title": 1, "value": 1 }, { "title": 2, "value": 2 }, { "title": 3, "value": 3 } ], "id": "myvaluescolumnselect", "type": "Input.ChoiceSet", "value": 1 } ], "type": "Column", "width": "auto" }, { "items": [ { "text": "Minutes", "type": "TextBlock", "wrap": true } ], "type": "Column", "width": "auto" } ], "type": "ColumnSet" } ], "type": "AdaptiveCard", "version": "1.0" }, "contentType": "application/vnd.microsoft.card.adaptive" } `

**Comment by geo-msft** [comment]
One more detail:
![image](https://user-images.githubusercontent.com/57954688/72417020-9f873000-3780-11ea-9e4b-b12b62a21e76.png)

**Comment by geo-msft** [comment]
One detail:

In this line, if we convert the value to string, the card is rendered properly:  
Instead of 
myvalues.push(index);

Do this: 
myvalues.push(index.toString());

We expect a better error message which should point us to what the issue is.

**Comment by shalinijoshi19** [comment]
@siduppal  / @dandriscoll / @ckkashyap FYI on this since I am not able to effect issue transfers to your repo yet.
