### ISSUE TITLE
[Website] The Explorer UI has problems with the content navigation panel

### ISSUE THREAD

**Issue by v-kydela** [microsoft/AdaptiveCards#3686]
1. The sections will not collapse, even though the chevron icons look like they should be clickable
2. The full contents do no scroll all the way to the bottom if the browser window is too small, and thus the contents cannot be viewed or navigated to

![image](https://user-images.githubusercontent.com/41968495/71124476-c0685f80-2199-11ea-9806-88f605cb040e.png)

---
* URL: https://adaptivecards.io/explorer

**Comment by paulcam206** [comment]
the scrollability problem should be fixed now, but I'll take a look at collapsing :)

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.
