### ISSUE TITLE
[Teams for Android][botframework] Adaptive card not displaying

### ISSUE THREAD

**Issue by matte-a** [microsoft/AdaptiveCards#3689]
# Platform

* typescript/javascript
* Android

# Author

Microsoft Teams for Android

# Version of SDK

I'm sending the card from the botbuilder 4.7.0

# Details
I'm sending the card from the botbuilder and on Teams desktop the card works perfectly fine.
On the other hand, on Android the card is empy.

These are the results.

MS Teams desktop:
![image](https://user-images.githubusercontent.com/48250758/71185095-1234e680-227b-11ea-89a0-9fe3d90f5876.png)

MS Teams for Android:
![image](https://user-images.githubusercontent.com/48250758/71185967-af444f00-227c-11ea-96ec-edde324f87ee.png)

This is the code:
`CardFactory.adaptiveCard({
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "New TextBlock"
        },
        {
            "type": "Input.ChoiceSet",
            "placeholder": "Placeholder text",
            "choices": [
                {
                    "title": "Choice 1",
                    "value": "Choice 1"
                },
                {
                    "title": "Choice 2",
                    "value": "Choice 2"
                }
            ],
            "style": "expanded",
            "id": "1"
        },
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.Submit",
                    "title": "Action.Submit"
                }
            ]
        }
    ]
})`

**Comment by matthidinger** [comment]
You may be hitting an issue with the `id` property not having any non-numeric characters in it. Can you try changing the `id` from "1" to "a1" or something else and see if that helps?

**Comment by matte-a** [comment]
> You may be hitting an issue with the `id` property not having any non-numeric characters in it. Can you try changing the `id` from "1" to "a1" or something else and see if that helps?

Hi, sorry for the delay.

I've just tried what you suggested by changing the id with a non-numeric characters but the result is exactly the same

**Comment by neittien0110** [comment]
I had the same issue. I fixed this bug. 

In my case, I created an **empty action**. I paste the card json in this URL to check
`[https://adaptivecards.io/visualizer/index.html?hostApp=Microsoft%20Teams]
This tool verified the json an announce an issue as below
![image](https://user-images.githubusercontent.com/8079397/78579468-2a953500-785b-11ea-9250-423ea0b3b6b5.png)
Deleted the empty action 
![image](https://user-images.githubusercontent.com/8079397/78579594-5f08f100-785b-11ea-99d3-f8f4e33ef14d.png)

Finally, it's okay.

**Comment by JbIPS** [comment]
If it can help someone, I also had this problem and by removing part of my JSON I found out an image without `url` (a missing value when templating).

So, card not appearing on mobile (it was iOS and Android) seems to be related to an incomplete JSON (not error found in Visualizer or Designer).

Hope that help!

**Comment by RalfAlpert** [comment]
JvIPS, thanks for the solution. Just adding a value to the URL fixed the problem for me, too.

**Comment by paulcam206** [comment]
Closing as this issue appears to have been figured out.
