### ISSUE TITLE
Interactive card for customers UI

### ISSUE THREAD

**Issue by shunyh** [microsoft/AdaptiveCards#3691]
**Bot-framework WebChat AdaptiveCard interactive UI**

* .NET HTML
* JavaScript

The feature request just like [this](https://github.com/microsoft/BotFramework-WebChat/issues/2770).

**Describe the solution you'd like**
I hope the AdaptiveCard could change UI when the mouse hovers on the stars, and keep the style always if the customer takes action on the star.

Currently, the star is a static image, nothing can't be changed after customer clicking the stars in the UI.

I noted that your team plans to develop this new feature on your [website](https://portal.productboard.com/adaptivecards/1-adaptive-cards-features/tabs/5-roadmap)

![image](https://user-images.githubusercontent.com/7311188/71390940-31e25b00-263d-11ea-9a10-df71fc6d8d99.png)

When will this feature be released? And is there any solutions for my scenario?

**Comment by mutanttech** [comment]
I would also want a configurable text box in this star rating setup. So that when user give 3 or less stars we can ask for a small feedback on it. This could make this a super star solution. Please consider this suggestion.

**Comment by paulcam206** [comment]
This is not currently on roadmap.
