### ISSUE TITLE
Input.Text element with multi line isn't vertically scrollable

### ISSUE THREAD

**Issue by Gunashree-R-V** [microsoft/AdaptiveCards#3693]
# Platform

* Android

# Author or host

Host

# Version of SDK

1.2.5

# Issue
 
An Input.Text element with `"isMultiline": true` isn't vertically scrollable. If the input has multiple lines, then there is no way to scroll up and view the previously typed text.
However, the same element is scrollable on Desktop/Web and iOS.

Below is the sample Input.Text element JSON.

> {
>             "id": "MultiLineVal",
>             "placeholder": "Comments",
>             "type": "Input.Text",
>             "isMultiline": true
>  }

Also, attaching the relevant JSON.
[multi-line-input-text.json.zip](https://github.com/microsoft/AdaptiveCards/files/4004709/multi-line-input-text.json.zip)

cc: @VikrantSingh01 .

**Comment by VikrantSingh01** [comment]
This seems to discrepancy of mobile vs web where the multiline text is scrollable on web vs not on mobile.

**Comment by shalinijoshi19** [comment]
@almedina-ms / @nesalang can you guys take a look at this one? @VikrantSingh01 i think we missed this in our sync today. Assigning this to @almedina-ms for load balancing.
