### ISSUE TITLE
[iOS][UI] Container background image does not cover card 

### ISSUE THREAD

**Issue by Aditya0603** [microsoft/AdaptiveCards#3700]
# Platform
* iOS

# Author or host

*Host - Teams

# Version of SDK

*1.2.5

# Details

Container background image does not cover card 

Sample JSON

{"$schema":"http://adaptivecards.io/schemas/adaptive-card.json","type":"AdaptiveCard","version":"1.0","body":[{"type":"Container","items":[{"type":"TextBlock","text":"This is some text"},{"type":"Container","backgroundImage":{"url":"http://104.211.228.145:3000/images/assets/icons/Background.png"},"items":[{"type":"TextBlock","text":"New TextBlock"},{"type":"TextBlock","text":"New TextBlock"},{"type":"TextBlock","text":"New TextBlock"},{"type":"TextBlock","text":"New TextBlock"},{"type":"TextBlock","text":"New TextBlock"},{"type":"TextBlock","text":"New TextBlock"},{"type":"TextBlock","text":"New TextBlock"},{"type":"TextBlock","text":"New TextBlock"},{"type":"TextBlock","text":"New TextBlock"},{"type":"TextBlock","text":"New TextBlock"},{"type":"TextBlock","text":"New TextBlock"},{"type":"TextBlock","text":"New TextBlock"},{"type":"TextBlock","text":"New TextBlock"},{"type":"TextBlock","text":"New TextBlock"},{"type":"TextBlock","text":"New TextBlock"},{"type":"TextBlock","text":"New TextBlock"},{"type":"FactSet","facts":[{"title":"Fact 1","value":"Value 1"},{"title":"Fact 2","value":"Value 2"}]}]}],"height":"stretch"}]}

<img width="284" alt="image" src="https://user-images.githubusercontent.com/33312128/71716393-9b7f1800-2e3a-11ea-808b-bb393e4063d6.png">

**Comment by paulcam206** [comment]
is there anything special about the background image? also, is it accessible to where the card is being rendered?

**Comment by Aditya0603** [comment]
@paulcam206 nothing about the image, just that the image is smaller than the. card being generated but in case of Cover/Default it should scaleToFill the whole card or update constraints accordingly

**Comment by adumrewal** [comment]
Reopening this issue. It is working in most cases but failing for some cases like for the following JSON.
**fillMode : Cover/Default**
<img src="https://user-images.githubusercontent.com/8917620/84007084-76fd0e00-a98d-11ea-87c0-31fde1635ceb.png" alt="drawing" width="300"/>
**fillMode : Repeat**
<img src="https://user-images.githubusercontent.com/8917620/84011881-5dab9000-a994-11ea-9360-2bc48bc57796.png" alt="drawing" width="300"/>
**Card JSON:**
[BGImageACIssue.txt](https://github.com/microsoft/AdaptiveCards/files/4744899/BGImageACIssue.txt)

**Comment by adumrewal** [comment]
@jwoo-msft @shalinijoshi19 for reopening the issue.

**Comment by adumrewal** [comment]
@Subhasish-msft please reopen this issue.
