### ISSUE TITLE
[iOS][Android][Input] [Input Retention]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#3703]
# Platform

* Android
* iOS

# Version of SDK
latest

# Details

It's reported by Teams that when adaptive card with user input is scrolled out, and scrolled back in, the user input value is lost.

- Implement sample app ability to scroll an adaptive card out of view
- p0 requirement; value retained after submit action

**Comment by shalinijoshi19** [comment]
@nesalang, what are the specific issues that this bug is tracking?

**Comment by nesalang** [comment]
> @nesalang, what are the specific issues that this bug is tracking?

it tracks the following issue: "user input is scrolled out, and scrolled back in, the user input value is lost"
to mark it complete, it has to prove it met "p0 requirement; value retained after submit action"
optional goal is "implement sample app ability to scroll an adaptive cards out of view"

**Comment by VikrantSingh01** [comment]
This is w.r.t. state management for adaptive card.

**Comment by shalinijoshi19** [comment]
@VikrantSingh01 at this point we likely wont get to include this in this month's patch (we're tracking code complete this week for a bug bash early next and release 1/31) ; Do we have the instrumented app for us to use at all?

**Comment by shalinijoshi19** [comment]
Meanwhile at lower priority tracking the work at our end to update our sample app to support scrolling using this issue. @nesalang

**Comment by VikrantSingh01** [comment]
If the instrumented Teams App is required, would be great to generate it with the instrumented Adaptive Card library.

**Comment by nesalang** [comment]
@nesalang link the sample app update with scrolling function to this issue, confirm that this is still an issue for them.

**Comment by nesalang** [comment]
> @nesalang link the sample app update with scrolling function to this issue, confirm that this is still an issue for them.

#3704

**Comment by VikrantSingh01** [comment]
@nesalang / @shalinijoshi19 : Any update in this issue ?

**Comment by shalinijoshi19** [comment]
@jwoo-msft I've moved this to 20.12 but not backlogging to allow us to deliver the sample app to them.

**Comment by RebeccaAnne** [comment]
@jwoo-msft Does the original issue still repro, and what work is outstanding here? Thanks!

**Comment by jwoo-msft** [comment]
@RebeccaAnne,
The team has mitigated the issue, and it's their p2 items.

**Comment by RebeccaAnne** [comment]
This has been mitigated and doesn't meet our current bug bar since there is a workaround.
