### ISSUE TITLE
[iOS][Sample App Update] Append AdaptiveCards

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#3704]
## Platform

* iOS

## Problem
AdaptiveCards are used frequently in chatting apps.
Salient feature of chatting app is scrolling.
Current sample app only show single AdaptiveCards.
Issues or features related to scrolling can't be tested.

## Proposed Solution
Add option to append AdaptiveCards, so scrolling functions can be tested.

## Additional context
This is possibly precursor to #3703

**Comment by VikrantSingh01** [comment]
https://github.com/microsoft/AdaptiveCards/issues/3703
