### ISSUE TITLE
[Mobile/JS][Consistency]Actions Rendering Orientation

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#3705]
# Platform

* Android
* iOS
* JS

# Version of SDK
latest

# Details
Ideally both images should look same.
There are two issues here.
1. differences in actions rendering when actions are squeezed in space, 
mobile uses horizontal scroll in this case. In JS, it is shown that actions grew vertically.
we need to find out if JS's hostconfig used vertical alignment for action alignment.
- mobile's horizontal scroll have been introduced per Team's Mobile's ask, AC team needs to decide if this feature should be adopted to all platofrms
- need to check if desktop and mobile use same HostConfig for action sets. @VikrantSingh01 could you please check if there are differences in [actionAlignment property](https://docs.microsoft.com/en-us/adaptive-cards/rendering-cards/host-config#schema-actionsconfig) in ActionConfing of HostConfig between Desktop and Mobile?

2. differences in the way textblock is rendered.
text is cut off in the mobile, there are two reasons.
- textblock's default value for wrap is false, so the shorter width for the mobile version caused the issue; but this isn't really a issue; it's the result of the current design.
- the reason for the shorter width is obvious; mobile has narrower width compared to desktop
;however, current designer does not allow to set width property, and this should be addressed. it's hard to detect the differences if users cannot set the width property; this issue is tracked here (place holder)

3. these will be documented in [mobile spec](https://github.com/microsoft/AdaptiveCards/issues/3653)

![image](https://user-images.githubusercontent.com/4112696/72091954-34dc7d00-32c6-11ea-9c99-06071ca6e3e4.png)
![image](https://user-images.githubusercontent.com/4112696/72091963-3dcd4e80-32c6-11ea-8d3f-d800063ed88d.png)

**Comment by shalinijoshi19** [comment]
Hey @vikrantsingh01, looks like we need more information about this issue. @nesalang FYI.

**Comment by VikrantSingh01** [comment]
@Aditya0603  : Please attach the screenshot for this issue.

**Comment by VikrantSingh01** [comment]
@nesalang / @shalinijoshi19 : Here is the internal link : https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/732783

Attaching Image : 
![image](https://user-images.githubusercontent.com/53896717/72054109-5ea99a00-32ee-11ea-821d-b41640fff60d.png)

There are times where the teams platform wants to have consistent O.O.B experience for the UI components (via using Host Config Options). @Aditya0603 to log bug for getting this for the current critical components, long term plan is to have the components  behave same across the board

**Comment by shalinijoshi19** [comment]
@nesalang FYI we have the screenshot here from Teams. @VikrantSingh01 is this the bug thats tracking the longer term goals? Could one of you @nesalang  or @Aditya0603 update the description and title of the bug to reflect precisely what is being tracked here with this issue?

**Comment by shalinijoshi19** [comment]
@VikrantSingh01 to get back with some clarification here - @nesalang can you clarify what the ask is here? Thanks

**Comment by nesalang** [comment]
@shalinijoshi19 The original ask was why buttons are rendered differently. The current understanding is that actions orientation is controlled by host config setting, so this is expected behavior.

**Comment by VikrantSingh01** [comment]
@shbhadra @Aditya0603 : I understand we can handle this using host config. Any other concerns with this bug ?

**Comment by shalinijoshi19** [comment]
Removing the v1.2.6 tracking label from this one

**Comment by nesalang** [comment]
@VikrantSingh01 , do you still need any assistance from our side?

**Comment by shalinijoshi19** [comment]
@VikrantSingh01 pls do reactivate if there's still pending asks on this one. Thanks!
