### ISSUE TITLE
[MsTeams]Adding files support in Adaptive card

### ISSUE THREAD

**Issue by Chekrii** [microsoft/AdaptiveCards#3707]
**What platform is your feature request related to? **

* .NET Core
* Bot Framework V4

Hi All,

Can we have a new Input in adaptive card where user can attach files(pdf) and send to Bot.

As of now we are taking user Input.text, input.Date and along with that we want to take attachment from user as an input.

Is it possible with Adaptive cards?

Thanks .

**Comment by shalinijoshi19** [comment]
@matthidinger, @RebeccaAnne  is this something that we want to or have ever considered as part of Input evolution?  @siduppal / @dandriscoll thoughts on this one?

**Comment by Chekrii** [comment]
Please any update on this.

**Comment by shaikShehanaaz** [comment]
Any update or workaround for this ?
Our requirement is to attach file in adaptive card in MS Teams.

**Comment by sukanyaam** [comment]
Any update on file support for Bot Framework V4 ??
Please let us know the ETA.

**Comment by shivajivarma** [comment]
Any update on this??? We have many use cases lineup for this feature.

**Comment by RebeccaAnne** [comment]
No immediate plans to build this, but it is being tracked as under consideration on our product board here: https://portal.productboard.com/adaptivecards/1-adaptive-cards-features/c/56-file-attachment-upload-control

**Comment by paulcam206** [comment]
This is not currently on roadmap.

**Comment by alokahr** [comment]
hi ms team
do we have it now? can we send and receive attachments in adaptive cards?
thank you 
alok

**Comment by joadoumie** [comment]
+1. This would be a really great feature. I'm looking for a way to essentially launch a file picker for a widget.

**Comment by nikosalexakis** [comment]
+1, This is long awaited.
