### ISSUE TITLE
[MSTeams][Attachments] Support on mobile

### ISSUE THREAD

**Issue by RajaniJillaGit** [microsoft/AdaptiveCards#3708]
Hi Team,

We are having requirement to attach files in Bot on MS teams channel. Looks like it is not supported on mobile version of MS teams Bot as per the below article.
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-and-receive-files?tabs=dotnet

Can you please help sharing the road map and work arounds to achieve this as of now on mobile ?

**Comment by matthidinger** [comment]
Hi there, we have an similar issue relating to File Upload support (#2384) but it's not currently on the roadmap. @siduppal might be able to share more on workarounds in Teams or other options

**Comment by shalinijoshi19** [comment]
@VikrantSingh01 thoughts on workarounds here for @RajaniJillaGit ?

**Comment by shalinijoshi19** [comment]
@VikrantSingh01 quick ping on this! thanks

**Comment by nesalang** [comment]
@shalinijoshi19 , @VikrantSingh01 any updates?

**Comment by Trinetra-MSFT** [comment]
@jwoo-msft , @shalinijoshi19 , We are aware of this, We have plan to roll out sending and receiving files support for mobile, but we don't have ETA to share with you.

**Comment by anbah34** [comment]
This is part of the Q2 roadmap on Mobile

cc- @VikrantSingh01

**Comment by shalinijoshi19** [comment]
@anbah / @vikrantsingh01 is this still on for Q2?

**Comment by anbah34** [comment]
@shalinijoshi19 The capability of bots to send and receive files is now shipped on mobile clients This only exists as a capability in a 1:1 chat with the bot (Not in group chat/ channel context). This is now in parity with desktop.

You can mark this ticket as clised

**Comment by jwoo-msft** [comment]
> @shalinijoshi19 The capability of bots to send and receive files is now shipped on mobile clients This only exists as a capability in a 1:1 chat with the bot (Not in group chat/ channel context). This is now in parity with desktop.
> 
> You can mark this ticket as clised

Closing it per anbah34 comment.
