### ISSUE TITLE
Javascript bot MSTeams mobile apps not rendering action iconUrl

### ISSUE THREAD

**Issue by mattcobb** [microsoft/AdaptiveCards#3711]
# JavaScript

# node-js bot sending adaptive card

# botframework v4

# Details

I have an adaptive card with Action.ShowCard and Action.ToggleVisibility actions with iconUrl for the button.  The images render just fine on MSTeams mac app and MSTeams website, but on both iOS and Android MSTeams apps, the images do not show.

Here you can see it working on the desktop app:
<img width="812" alt="msteams_desktop_iconurl" src="https://user-images.githubusercontent.com/893006/72030875-5b0b0a00-323f-11ea-9eb8-9c602f3c55f3.png">

Here you can see a mobile screen shot where the buttons do not render:

![msteams_mobile_icon_missing](https://user-images.githubusercontent.com/893006/72030807-28611180-323f-11ea-9277-82f22f8be1c8.png)

Attached is also the card json: 

`{"type":"AdaptiveCard","version":"1.2","body":[{"type":"TextBlock","text":"Here is some relevant information...","wrap":true},{"type":"Container","separator":false,"items":[{"type":"TextBlock","text":"Pryon requires employees to book air travel in coach or economy classes.  **You must have manager approval**  to book first or business class travel.","wrap":true,"maxLines":16},{"type":"FactSet","facts":[{"title":"Source","value":"[All Files/dev/Travel Policy, Benefits, and Employee Handbook/Pryon_Employee_Travel__8.19.docx](https://app.box.com/file/589339734969)"}],"isVisible":true,"id":"mainFactSet_0"},{"type":"FactSet","facts":[{"title":"Confidence","value":"51%"},{"title":"Name","value":"All Files/dev/Travel Policy, Benefits, and Employee Handbook/Pryon_Employee_Travel__8.19.docx"},{"title":"Level","value":"weak_accept"}],"isVisible":false,"id":"details_id_0"}],"style":"default","isVisible":true,"actions":[]},{"type":"Container","separator":true,"items":[{"type":"TextBlock","text":"All business travel must be booked 14 days prior to your departure date.  **If that is not possible, obtain approval from your manager. As always, use common sense when booking your travel to balance costs with convenience.**   ","wrap":true,"maxLines":16},{"type":"FactSet","facts":[{"title":"Source","value":"[All Files/dev/Travel Policy, Benefits, and Employee Handbook/Pryon_Employee_Travel__8.19.docx](https://app.box.com/file/589339734969)"}],"isVisible":true,"id":"mainFactSet_1"},{"type":"FactSet","facts":[{"title":"Confidence","value":"44%"},{"title":"Name","value":"All Files/dev/Travel Policy, Benefits, and Employee Handbook/Pryon_Employee_Travel__8.19.docx"},{"title":"Level","value":"reject"}],"isVisible":false,"id":"details_id_1"}],"style":"emphasis","isVisible":false,"actions":[],"id":"answer_containter_1"},{"type":"Container","separator":true,"items":[{"type":"TextBlock","text":"•Travel not booked in  **economy class** ","wrap":true,"maxLines":16},{"type":"FactSet","facts":[{"title":"Source","value":"[All Files/dev/Travel Policy, Benefits, and Employee Handbook/Pryon_Employee_Travel__8.19.docx](https://app.box.com/file/589339734969)"}],"isVisible":true,"id":"mainFactSet_2"},{"type":"FactSet","facts":[{"title":"Confidence","value":"44%"},{"title":"Name","value":"All Files/dev/Travel Policy, Benefits, and Employee Handbook/Pryon_Employee_Travel__8.19.docx"},{"title":"Level","value":"reject"}],"isVisible":false,"id":"details_id_2"}],"style":"default","isVisible":false,"actions":[],"id":"answer_containter_2"}],"$schema":"http://adaptivecards.io/schemas/adaptive-card.json","actions":[{"type":"Action.ToggleVisibility","title":" ","iconUrl":"https://cdn2.iconfinder.com/data/icons/social-icons-33/128/Trello-128.png","isVisible":true,"targetElements":["answer_containter_1","answer_containter_2","details_id_0","details_id_1","details_id_2"]},{"type":"Action.ShowCard","style":"default","title":"Related","card":{"type":"AdaptiveCard","version":"1.2","body":[{"type":"Input.ChoiceSet","id":"related_choice","isMultiSelect":false,"style":"expanded","spacing":"none","height":"stretch","choices":[{"title":"Do i need to fly commercial?","value":"Do i need to fly commercial?"},{"title":"Can I fly on whatever airline I want?","value":"Can I fly on whatever airline I want?"}],"value":"Do i need to fly commercial?"}],"actions":[{"type":"Action.Submit","title":"Ask"}]}},{"type":"Action.ShowCard","version":"1.2","title":" ","iconUrl":"https://storage.googleapis.com/pryon-bot-assets/fa-comments-blue.png","card":{"type":"AdaptiveCard","body":[{"type":"TextBlock","text":"Please give us your feedback on the answer."},{"type":"Input.ChoiceSet","id":"feedback_rating","isMultiSelect":false,"style":"expanded","choices":[{"title":"Answer was on topic and helpful","value":"5"},{"title":"Answer was on topic, but not helpful","value":"4"},{"title":"Answer was not on topic","value":"3"},{"title":"Did not receive an answer","value":"2"}]}],"actions":[{"type":"Action.Submit","title":"Submit Feedback","data":{"feedback_exchange_id":"97f261fc-408d-4406-8ada-5bfd8bb3b70b"}}]}}]}`

**Comment by shalinijoshi19** [comment]
@vikrantsingh01 is this something you can help get us a first pass on to see if this is really an AdaptiveCards issue? Thanks a ton!

**Comment by VikrantSingh01** [comment]
This can be verified in the latest Teams Alpha. 
![photo6104958019268880762](https://user-images.githubusercontent.com/53896717/72053449-0f169e80-32ed-11ea-9d07-a79cca7687e3.jpg)

**Comment by mattcobb** [comment]
That means verified the repro or the fix?

**Comment by nesalang** [comment]
> That means verified the repro or the fix?

@mattcobb 
this most likely means that once teams' mobile app finishes updating their app with later version of adaptive cards sdk, this issue will be addressed.
the screenshot from @VikrantSingh01 shows images from action icon url, and as they mentioned, this image was taken from their alpha build.

**Comment by shalinijoshi19** [comment]
@vikrantsingh01 thanks for helping.. Could you confirm if you see the repro still with Teams Mobile alpha drop or if you've verified it fixed?  Thanks!
