### ISSUE TITLE
[UWP] Person image with background color not rendering

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#3720]
# Platform

* UWP

# Details
 [Image.BackgroundColor.json](https://github.com/microsoft/AdaptiveCards/blob/master/samples/v1.1/Tests/Image.BackgroundColor.json) test doesn't render the person image with a background color. Only a circle with the background color is shown. Removing either the background color or the person style causes the image to render properly. Adding a size also causes it to render properly.

![image](https://user-images.githubusercontent.com/9091833/72194390-515ddf80-33c2-11ea-8595-2eacc512e73d.png)

**Comment by shalinijoshi19** [comment]
@RebeccaAnne is this only repro'ing iwth UWP or is this a consistent problem across iOS/Android/JS ?

**Comment by RebeccaAnne** [comment]
@shalinijoshi19  Works fine in Javascript and .NET. Haven't tried the others, but i don't have any reason to believe it would be broken anywhere else.

**Comment by shalinijoshi19** [comment]
@nesalang, / @almedina-ms can one you test this on iOS/Android resp to rule out this as an issue on these platforms? @paulcam206 do you want to take a stab at costing this out and fixing this if it's an easy one to absorb? Thanks!

**Comment by shalinijoshi19** [comment]
@paulcam206 do unassign & update the issue once we know impact + cost details and if the cost >2 days! Thanks.

**Comment by nesalang** [comment]
it works on ios.

**Comment by paulcam206** [comment]
Looks like this came in with commit f1dcf01c2f0d0a67b12de42ba0198d041efa14ad - guessing it's XamlBuilder changes, but still narrowing down

**Comment by paulcam206** [comment]
I further narrowed it down specifically to 8058022ea7d9dc440e4aa693149538d14192f92d (@RebeccaAnne FYI) :)
