### ISSUE TITLE
[MsTeams] Deep link to an app in teams

### ISSUE THREAD

**Issue by RajaniJillaGit** [microsoft/AdaptiveCards#3721]
Hi Team,

Wanted to build a deep link for an existing app in teams. Read the article about deep link but there is no mention about apps. Can you please help if this is possible? We wanted to build a link to who bot app inbuilt app of teams.

**Comment by shalinijoshi19** [comment]
@siduppal could you help take a first pass at this issue? @RajaniJillaGit what article are you referring to here again? Please provide a bit more context and why you think it's an AdaptiveCards issue again? Thanks!

**Comment by shalinijoshi19** [comment]
@siduppal , @RajaniJillaGit ping! thanks.

**Comment by Subhasish-msft** [comment]
@RajaniJillaGit , Do you mean deeplink to an app in app studio Or deeplink to an app's chat or tab.

**Comment by Subhasish-msft** [comment]
@RajaniJillaGit , Currently deeplink to an app is not supported. Please have a look at the [deeplink doc](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#deep-linking-to-a-chat)
