### ISSUE TITLE
[Designer] Does the templating system support simple string arrays? e.g. ["Red","Blue","Yellow"]

### ISSUE THREAD

**Issue by ClairelyClaire** [microsoft/AdaptiveCards#3722]
My JSON data model looks like:

```json
{
    "image" : "hazelnut.jpg",
    "clade" : [
        "Tracheophytes",
        "Angiosperms",
        "Eudicots",
        "Rosids"
    ],
    "name" : "American Hazelnut",
    "order" : "Fagales",
    "family" : "Betulaceae",
    "genus" : "Corylus",
    "species" : "Corylus Americana"
}
```

How do I map the array value of `clade` to the `text` property on an adaptive card's `items` array?

This is what I'm trying to do:
https://docs.microsoft.com/en-us/adaptive-cards/templating/language#repeating-items-in-an-array

**Comment by shalinijoshi19** [comment]
@dclaux / @matthidinger could you help with the question here?

**Comment by matthidinger** [comment]
Indeed this should work! The syntax is a bit strange when binding to an array of strings directly, you have to use `{$data}` to access the raw value. 

With the data you provided above, I pasted it into the Designer **Sample Data** field and built the card. Setting `$data` on a key causes the element to repeat, then you use `{$data}` as a **value** in order to access individual items within the array.


![image](https://user-images.githubusercontent.com/1432195/72284058-f19b4a80-35f4-11ea-9f09-f5b88de16faa.png)


```json
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "{name}",
            "size": "Large"
        },
        {
            "type": "TextBlock",
            "text": "Clade",
            "size": "Medium",
            "spacing": "Medium"
        },
        {
            "type": "TextBlock",
            "$data": "{clade}",
            "text": "{$data}"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```

Let me know if that helps, or if I misunderstood the question!

**Comment by dclaux** [comment]
I was looking at this last night (tool ate to respond, sorry) and I must have broken something in https://vnext.adaptivecards.io/designer as **this doesn't work anymore**. I will have to look at it and fix.

**Comment by ClairelyClaire** [comment]
@matthidinger that did indeed work for me. Can the documentation I linked also be updated to include this information? Thanks!

**Comment by matthidinger** [comment]
@ClairelyClaire tried to add some clarification, does this help? https://github.com/MicrosoftDocs/AdaptiveCards/commit/cec9a10a02e26e0ea8c49b976082a765238f4d60

**Comment by ClairelyClaire** [comment]
That's perfect, thanks!

**Comment by shalinijoshi19** [comment]
Thanks @dclaux, is this still a bug we need to track then? I"ve gone ahead repurposed it for the time being from a question to an actual bug.

**Comment by dclaux** [comment]
On my machine the bug doesn't repro. I think it's just a matter of updating vnext to the current code base in js/renderer-refactor

**Comment by paulcam206** [comment]
This appears to be fixed! Please reactivate if that's not the case.
