### ISSUE TITLE
[Javascript][Safari/Media] [Media Attachments not loading in Safari]

### ISSUE THREAD

**Issue by tdurnford** [microsoft/AdaptiveCards#3723]
# Platform
* JavaScript

# Author or host
Host [Web Chat](https://github.com/microsoft/BotFramework-WebChat/)

If you're an author, who are you sending cards to?

# Version of SDK
Javascript v1.2.5

# Details
Videos embedded in an Adaptive Card do not load on iOS devices when the user presses the play button that is overlaid on the video unless the user presses pause and restarts the video or navigates away from Safari and then returns to the page.

## Adaptive Card
```json
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.1",
  "fallbackText": "This card requires Media to be viewed. Ask your platform to update to Adaptive Cards v1.1 for this and more!",
    "body": [
        {
            "type": "Media",
            "poster": "https://adaptivecards.io/content/poster-video.png",
            "sources": [
                {
                    "mimeType": "video/mp4",
                    "url": "https://adaptivecardsblob.blob.core.windows.net/assets/AdaptiveCardsOverviewVideo.mp4"
                }
            ]
        }
    ],
    "actions": [
        {
            "type": "Action.OpenUrl",
            "title": "Learn more",
            "url": "https://adaptivecards.io"
        }
    ]
}
```

## Screen Recording
![RPReplay_Final1578941642](https://user-images.githubusercontent.com/17039790/72284205-3f17b780-35f5-11ea-9968-d370b2cd3b3c.gif)

## Additional Context
https://github.com/microsoft/BotFramework-WebChat/issues/2697

**Comment by shalinijoshi19** [comment]
Hi @tdurnford thanks for reporting this issue as well as the additional context. Could you help us understand specific repro steps/debugging details that lead you to believe this to be an AdaptiveCards issue? @nesalang FYI.

**Comment by nesalang** [comment]
@tdurnford 
does your bot-framework use ios adaptive cards or java script adaptive cards sdk?
if iOS, can you make sure this delegate is implemented?
- (void)didFetchMediaViewController:(AVPlayerViewController *)controller
                               card:(ACOAdaptiveCard *)card
you can check the sample app's implementation from ViewController.m

**Comment by arman-g** [comment]
Is this going to be included in the next release? And when is the next release? Thanks!

**Comment by arman-g** [comment]
Any updates on this one?
