### ISSUE TITLE
Adaptive card is not rendering in Webchat

### ISSUE THREAD

**Issue by gouseshake0786** [microsoft/AdaptiveCards#3731]
I am Using BDK v4 template build a bot. Also I am using AdaptiveCard 1.2.1 version

Attachment skillRecommendationAttachment = new Attachment();
                Activity replyToActivity = innerDc.Context.Activity.CreateReply();
skillRecommendationAttachment = GetSkillsCardAttachment();
                Attachment GetSkillsCardAttachment()
                {
                    AdaptiveCard card = new AdaptiveCard("1.0");
                    card.Version = "1.0";
                    card.Type = "AdaptiveCard";

                    card.Body.Add(new AdaptiveTextBlock()
                    {
                        Text = "NEAR SKILLS",
                        Size = AdaptiveTextSize.Large,
                        Weight = AdaptiveTextWeight.Bolder,
                    });

                    Attachment attachment = new Attachment()
                    {
                        ContentType = AdaptiveCard.ContentType,
                        Content = card
                    };

                    return attachment;
                }

                replyToActivity.Attachments.Add(skillRecommendationAttachment);
                await innerDc.Context.SendActivityAsync(replyToActivity);

When I tried above code It's coming Bot Emulator and when i deploy this changes adaptive card is not rendering

![image](https://user-images.githubusercontent.com/25403427/72620926-4678f100-3966-11ea-98ef-dfeb13d503b0.png)

Any Solution ?

**Comment by shalinijoshi19** [comment]
@gouseshake0786 do you have access to the card json when you try this in the bot emulator?@ckkashyap / @dandriscoll any other debugging tips here? How would one go about debugging this class of problems where it's a no repro in the emulator but repros in prod webchat ?

**Comment by gouseshake0786** [comment]
Can I have any update on this?.

**Comment by paulcam206** [comment]
This isn't an Adaptive Cards issue -- please file a bug over in the [BotFramework GitHub](https://github.com/microsoft/botframework-sdk)
