### ISSUE TITLE
ios teams mobile app, Adaptive card, pre filled text (Input Text) is not showing after recent teams update last month

### ISSUE THREAD

**Issue by prasanthrpadharthi** [microsoft/AdaptiveCards#3733]
# Platform

* iOS

# Author or host

Testing the capabilities of the adaptive card to pre fill text while rendering Text input fields. It was working fine last month, but the latest Teams IOS App update got some issues which dont show the pre filled text in the Text box

# Version of SDK

Tried both Adaptive card 1.0 & 1.2

# Details

ios teams mobile app, Adaptive card, pre filled text (Input Text) is not showing after recent teams update last month
![Team_Adaptive_card_issue_IOS_APP](https://user-images.githubusercontent.com/36985649/72696255-7f87b000-3b76-11ea-8666-856347a72e53.png)

**Comment by shalinijoshi19** [comment]
@prasanthrpadharthi can you please share specifically what the card json looks like as well as the specific Teams version you are on ? @VikrantSingh01 would you have ideas here on the repro? I have the latest Teams Alpha app installed, and am working with Adapto-Bot for testing some AC scenarios out but dont quite know how to simulate teh repro above. Thansk! @nesalang  FYI

**Comment by shalinijoshi19** [comment]
Also @nesalang, is this v1.2.6 ?

**Comment by prasanthrpadharthi** [comment]
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.x",
  "body": [
    {
      "type": "TextBlock",
      "text": "Default text input"
    },
    {
      "type": "Input.Text",
      "id": "input1",
      "placeholder": "enter comment",
      "value": "Text Field",
      "maxLength": 500
    }
  ]
}


Tried with 1.0, 1.1 and 1.2 version with the above json.

Desktop version of Teams is working fine. I can see the value in Text Box, In Microsft Team IOS mobile phones the text is empty in Text box.

**IOS MICROSOFT TEAMS Version info is as below.
Version: 2.0.1
Build: 1.077.2020011301 (general)
Calling Version: 2019.46.01.6**

** Identified older version of Teams (1.86) is working fine, but now the latest verion of IOS Teams is 2.0.1

**Comment by mplwork** [comment]
I have the same problem with the result that I can't submit form input for verification.

**Comment by Ramesh-MRO** [comment]
Hello Team,

Any update on this, need anything more for simulation?

Thank you :)

**Comment by shalinijoshi19** [comment]
@nesalang was not able to repro this with the AC visualizer app. @VikrantSingh01 + team to help see if this repro's with the latset Teams alpha + adaptobot.

**Comment by VikrantSingh01** [comment]
@Aditya0603 : Can you / amol take a quick look at this ?

**Comment by adumrewal** [comment]
@VikrantSingh01 this was an issue on our CustomRenderer. It has been fixed and will be available in the Feb store build.

**Comment by prasanthrpadharthi** [comment]
Still the issue is open and not fixed

**Comment by cheeseypi** [comment]
Confirmed still not fixed
