### ISSUE TITLE
[iOS][UI] ACRButton highlighted states show default system color

### ISSUE THREAD

**Issue by Aditya0603** [microsoft/AdaptiveCards#3734]
# Platform
* iOS
# Author or host
Host (Teams)
# Version of SDK
1.2.5

# Details
ACRButton uses default system button which on highlighted states show default blue color as Background.

Can we change them to UIButtonTypeCustom

**Comment by shalinijoshi19** [comment]
@nesalang, can you take a quick first pass at this ask ? Thanks!

**Comment by nesalang** [comment]
Hey @Aditya0603 ,

Yes, this can be easily accomplished through XIB.
Please follow the instruction [here](https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/ios/native-styling).
If the documentation is empty, please do let me know. I have to update it.

Thanks

**Comment by VikrantSingh01** [comment]
@Aditya0603 : Do  we have all the support we need here from A.C Team. Pls. sync up with Gaurav/Amol as well.

**Comment by shalinijoshi19** [comment]
@Aditya0603 / @VikrantSingh01 closing this out at this point unless you have specific documentation asks of us? If so could you file a separate issue with teh specifics of where the documentation or support/samples is lacking and can be improved? Thanks!
