### ISSUE TITLE
[Android/IOS][UI] The ability to make some card background color "transparent" through card payload

### ISSUE THREAD

**Issue by FelixZhang001** [microsoft/AdaptiveCards#3735]
**What platform is your feature request related to? (Delete other platforms).**

* Android
* iOS

**Is your feature request related to a problem? Please describe.**
Recently, we receive a design request to make some specific card background color to be transparent. For other cards, the background color keeps as before.
As we can't distinguish cards during client render, so we can't apply a separate host config for this demand.

**Describe the solution you'd like**
I notice that the "card" background color would be the same as the background color in the host config file's "default" container style. But I don't want to change that to be transparent as it is used throughout the card.
I wonder if we can specify the color through card payload and not use the "default" one.

**Describe alternatives you've considered**
I have considered changing the "default" container style background color to be transparent. But that means we need to modify all the current adaptive card payload to align with original UI.

**Additional context**
N/A

**Comment by paulcam206** [comment]
This is not currently on roadmap.

@JeanRoca 👀
