### ISSUE TITLE
Adaptive Cards Support for MS Teams Incoming Webhooks

### ISSUE THREAD

**Issue by varundmishra** [microsoft/AdaptiveCards#3740]
I see that there was an issue which was closed on this (back in 2018) but I wanted to know if/when the Adaptive Cards will be supported by Incoming Webhooks in MS Teams?

**Comment by shalinijoshi19** [comment]
@siduppal / @VikrantSingh01/ @matthidinger / @dclaux  ideas on what the ask here is ?

**Comment by matthidinger** [comment]
This is something that Teams is aware of and has been working on, but we don't have a timeline for when it can be released yet. There are some complicated dependencies that make it difficult to estimate

**Comment by dclaux** [comment]
This is related to Teams' Connectors support, which are currently limited to the MessageCard format. The Connectors platform is owned by Outlook, and it is not straightforward to add support for Adaptive Cards.

**Comment by shalinijoshi19** [comment]
Thanks @matthidinger / @dclaux . @siduppal can you share the tracking issue etc at your end for reference here for details/timelines? Thanks!

**Comment by shalinijoshi19** [comment]
@dclaux / @siduppal  do we have tracking bugs or issues or forums that we can route the customer to for updates here? @varundmishra FYI please see notes above.

**Comment by Trinetra-MSFT** [comment]
@varundmishra , Adaptive cards is not supported in webhooks, However you can [send message card ](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using)to work with [webhooks](https://messagecardplayground.azurewebsites.net/)

**Comment by Trinetra-MSFT** [comment]
Feel free to reopen this issue

**Comment by sgiulianiamius** [comment]
Hi guys,
how's the situation here? When will this functionality be released?
Is there at least a way to simulate a NxN table with Message Card?
Thanks

**Comment by cryptic-ai** [comment]
Just going to +1 this. It would be nice to have Adaptive Cards in webhooks.

**Comment by chandan-g-bhagat** [comment]
Eagerly waiting for the adaptive cards to be supported in webhooks.

**Comment by Jon889** [comment]
+1 on this too

**Comment by kdll** [comment]
+1 on this
If anyone knows how to send them via other methods, let me know!

**Comment by cscheffauer** [comment]
+1 on this as well!

**Comment by timdonovanuk** [comment]
+1 here too.

**Comment by matthidinger** [comment]
Hi folks, we've got some updates to share here from the Teams developer community call. This video walks through how to use an Adaptive Card in an incoming webhook, but please note there is a limitation today with regards to Action.Submit. Take a look at the video for details:

https://www.youtube.com/watch?v=y5pbJI43Zvg

**Comment by dylan-asos** [comment]
Quick schema reference as used in the video linked from @matthidinger  if it helps anyone, it's wrapping the adaptive content in the outermost envelope that got this working for me, then it's basically as described at https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference
```
{
   "type":"message",
   "attachments":[
      {
         "contentType":"application/vnd.microsoft.card.adaptive",
         "contentUrl":null,
         "content":{
            "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
            "type":"AdaptiveCard",
            "version":"1.2",
            "body":[
               {
                  "type":"ColumnSet",
                  "id":"1ede2aba-61b9-faa0-9895-9ed0c26b2e6f",
                  "columns":[
                     {
                        "type":"Column",
                        "id":"e5756242-0963-37a2-7cb4-4397886d60bb",
                        "padding":"None",
                        "width":"stretch",
                        "items":[
                           {
                              "type":"TextBlock",
                              "id":"20f3833e-0435-5c87-fad1-b528e0046fb6",
                              "text":"Company Name",
                              "wrap":true
                           }
                        ],
                        "verticalContentAlignment":"Center"
                     },
                     {
                        "type":"Column",
                        "id":"74215a26-fa8b-e549-cced-7f99fd34a661",
                        "padding":"None",
                        "width":"auto",
                        "items":[
                           {
                              "type":"Image",
                              "id":"795047e2-e63e-6e14-07ba-5a3e13323dff",
                              "url":"https://amdesigner.azurewebsites.net/samples/assets/PlaceHolder_Person.png",
                              "size":"Small"
                           }
                        ],
                        "horizontalAlignment":"Right"
                     }
                  ],
                  "padding":{
                     "top":"Small",
                     "bottom":"Small",
                     "left":"Default",
                     "right":"Small"
                  },
                  "style":"emphasis"
               }
            ],
            "padding":"None"
         }
      }
   ]
}
```

**Comment by rkapoor028** [comment]
**Official Update:-**
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/35793883-adaptive-cards-webhooks

**Comment by chandan-g-bhagat** [comment]
> Quick schema reference as used in the video linked from @matthidinger if it helps anyone, it's wrapping the adaptive content in the outermost envelope that got this working for me, then it's basically as described at https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference
> 
> ```
> {
>    "type":"message",
>    "attachments":[
>       {
>          "contentType":"application/vnd.microsoft.card.adaptive",
>          "contentUrl":null,
>          "content":{
>             "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
>             "type":"AdaptiveCard",
>             "version":"1.2",
>             "body":[
>                {
>                   "type":"ColumnSet",
>                   "id":"1ede2aba-61b9-faa0-9895-9ed0c26b2e6f",
>                   "columns":[
>                      {
>                         "type":"Column",
>                         "id":"e5756242-0963-37a2-7cb4-4397886d60bb",
>                         "padding":"None",
>                         "width":"stretch",
>                         "items":[
>                            {
>                               "type":"TextBlock",
>                               "id":"20f3833e-0435-5c87-fad1-b528e0046fb6",
>                               "text":"Company Name",
>                               "wrap":true
>                            }
>                         ],
>                         "verticalContentAlignment":"Center"
>                      },
>                      {
>                         "type":"Column",
>                         "id":"74215a26-fa8b-e549-cced-7f99fd34a661",
>                         "padding":"None",
>                         "width":"auto",
>                         "items":[
>                            {
>                               "type":"Image",
>                               "id":"795047e2-e63e-6e14-07ba-5a3e13323dff",
>                               "url":"https://amdesigner.azurewebsites.net/samples/assets/PlaceHolder_Person.png",
>                               "size":"Small"
>                            }
>                         ],
>                         "horizontalAlignment":"Right"
>                      }
>                   ],
>                   "padding":{
>                      "top":"Small",
>                      "bottom":"Small",
>                      "left":"Default",
>                      "right":"Small"
>                   },
>                   "style":"emphasis"
>                }
>             ],
>             "padding":"None"
>          }
>       }
>    ]
> }
> ```

This one worked like a charm. Wrapping it in the type Message and attaching it in the attachments. However, I tried passing array of adaptive cards in it, but it displayed only one.

**Comment by Wajeed-msft** [comment]
Here is the documentation on [Send adaptive cards using an incoming webhook](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using#send-adaptive-cards-using-an-incoming-webhook).

**Comment by jishwin13** [comment]
I wanted to know whether the incoming webhook for teams and adaptive cards support the @mention feature in Teams? I have gone through some articles regarding this. How can one find the 8:orgid:{org-ID-of-the-user}  and more importantly what is this? Can someone help?

**Comment by Nikitha-MSFT** [comment]
Currently incoming webhook does not support @mention feature. Also why you need 8:orgid? could you please share more info?

**Comment by jishwin13** [comment]
> Currently incoming webhook does not support @mention feature. Also why you need 8:orgid? could you please share more info?

Because I had read in some other articles you might need the 8:orgid for the @mentions. Thanks anyway for your help. If incoming webhooks doesn't support it I am chucking this. Also I would like to know what and how we can get the 8:orgid. It would be of help in future.

**Comment by Nikitha-MSFT** [comment]
Could you please check this [docs](https://docs.microsoft.com/en-us/power-platform/admin/determine-org-id-name) for organization id. and for @mention you require the user id not the organization id

**Comment by yisonPylkita** [comment]
I also stumbled upon this `@mention` issue. I'm writing a webhook that needs mentions and I can't do that right now.  Do you guys have a plan to add this feature?

**Comment by Nikitha-MSFT** [comment]
Currently teams does not support @mention incoming webhook. Could you please raise a [user voice](https://microsoftteams.uservoice.com/forums/555103-public-preview/category/182881-developer-platform)?

**Comment by sky-sharma** [comment]
Is there a way to update / refresh an AdaptiveCard or ActionCard sent using an incoming MS Teams webhook? I recall this might not have been possible in the past, but it appears new features have been added to webhooks fairly recently.

**Comment by Prasad-MSFT** [comment]
@sky-sharma - There is no such way to update/refresh an AdaptiveCard or ActionCard sent using an incoming MS Teams webhook. It is not supported.
