### ISSUE TITLE
[iOS][Code][Sample code is not working] ACRActionDelegate is not called

### ISSUE THREAD

**Issue by Jageen** [microsoft/AdaptiveCards#3741]
# Platform
iOS

# Author or host
HOST : I am just running sample code from GIT.

# Version of SDK
(1.2.4)

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...
latest from master branch

# Details
ACRActionDelegate is not called when user click on button.
I am using sample code
Here I am attaching my source-code (Which is basically sample code from git itself) and video for batter understanding.
[AdaptiveCardDemo.zip](https://github.com/microsoft/AdaptiveCards/files/4108771/AdaptiveCardDemo.zip)

[AdaptiveCardDemoNotWorking.mp4.zip](https://github.com/microsoft/AdaptiveCards/files/4108793/AdaptiveCardDemoNotWorking.mp4.zip)

**Comment by Jageen** [comment]
I try to debug issue and find out that its happening because we are passing nil as ACOHostConfig.
due to that _actionsTargetBuilderDirector object is not created
(https://github.com/microsoft/AdaptiveCards/blob/fe5fcefb4275b6bfd0fbf395e0fc80f71a01277d/source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm#L95)

I believe there should be a way to access default config object if it's not passed.

**Comment by shalinijoshi19** [comment]
@nesalang, thoughts?

**Comment by nesalang** [comment]
@Jageen 
Thanks for reporting this issue. Yes, the action build directors shouldn't be depended on the presence of user host config. i
thanks

**Comment by Jageen** [comment]
If this is going to take longer time to fix this issue, I am suggesting to change sample code (as patch) in README.mg file to avoid same problem for future users.
https://github.com/microsoft/AdaptiveCards/pull/3744

**Comment by shalinijoshi19** [comment]
@jageen @nesalang has a PR out that fixes this issue above
