### ISSUE TITLE
[JS][Bug Bash] [ImageSet Auto Size doesn't work properly]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#3748]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Version of SDK

1.2.6

# Details

# repro steps:
1. add the below json, and paste it to designer.
2. no images will show up.
3. ctrl-a then paste it again
```json
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "TextBlock",
			"text": "Here are some cool photos",
			"size": "large"
		},
		{
			"type": "TextBlock",
			"text": "Sorry some of them are repeats",
			"size": "medium",
			"weight": "lighter"
		},
		{
			"type": "ImageSet",
			"imageSize": "auto",
			"images": [
				{
					"type": "Image",
					"url": "https://picsum.photos/200/200?image=100"
				},
				{
					"type": "Image",
					"url": "https://picsum.photos/300/200?image=200"
				},
				{
					"type": "Image",
					"url": "https://picsum.photos/300/200?image=301"
				},
				{
					"type": "Image",
					"url": "https://picsum.photos/200/200?image=400"
				},
				{
					"type": "Image",
					"url": "https://picsum.photos/300/200?image=500"
				},
				{
					"type": "Image",
					"url": "https://picsum.photos/200/200?image=600"
				},
				{
					"type": "Image",
					"url": "https://picsum.photos/300/200?image=700"
				},
				{
					"type": "Image",
					"url": "https://picsum.photos/300/200?image=800"
				},
				{
					"type": "Image",
					"url": "https://picsum.photos/300/200?image=900"
				}
			]
		}
	]
}
```
some pictures are overlapped each other, and some pictures have wrong aspect ratio
JS
![image](https://user-images.githubusercontent.com/4112696/73316283-535bd700-41e7-11ea-9859-c296113c248c.png)

UWP
![image](https://user-images.githubusercontent.com/4112696/73316320-666ea700-41e7-11ea-84ad-cca7c61c3fce.png)

**Comment by dclaux** [comment]
I am not able to repro this.

**Comment by nesalang** [comment]
> I am not able to repro this.

you're really active! i edited the description with repro step

**Comment by shalinijoshi19** [comment]
@dclaux could you take a first pass with teh repro steps that @nesalang provides? Thanks!

**Comment by dclaux** [comment]
`auto` and `stretch` are not supported sizes in ImageSet. But the JS renderer fails to fall back to `medium` in those cases, so what you're seeing is HTML doing its best to auto-size while being constrained to a maximum height for each image.

The fix will be to fall back to `medium` when either `auto` or `stretch` are specified as `imageSIze`, and to remove the option to select `auto` or `stretch` from the designer.

Note [the documentation](https://adaptivecards.io/explorer/ImageSet.html) doesn't say that "auto" and "stretch" are not supported, and I can foresee my assertion they are not supported will be debated. If we're going to debate, please do include a description of how "auto" and "stretch" should work in an ImageSet.

**Comment by RebeccaAnne** [comment]
Duping to #4043
