### ISSUE TITLE
[iOS][BugBash] [Vertical Content Alignment for Adaptive Card Not Working]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#3749]
# Platform
* iOS

# Version of SDK
1.2.6

# Details
Expected Behavior 
on JS
![image](https://user-images.githubusercontent.com/4112696/73317510-29a4af00-41eb-11ea-8fd9-20a73caaa6d2.png)

Actual Behavior
on iOS 
![image](https://user-images.githubusercontent.com/4112696/73318065-1e528300-41ed-11ea-87bb-e08833da9f90.png)

**Comment by shalinijoshi19** [comment]
@dclaux thoughts on this ? Marking investigate and assigning to you for a frst pass; Please add back "Triage Needed" and unassign  yourself once you are done investigating/update with comments? thanks!
