### ISSUE TITLE
[Android] Error in the Submit action flow in Input.Text.Multiline sample in the test visualizer app

### ISSUE THREAD

**Issue by shalinijoshi19** [microsoft/AdaptiveCards#3751]
# Platform
Android

# Version of SDK
Bits off of release/1.2
# Details
Repro Steps:
1. Open the test visualizer app on Android
2. Try to open the v1.2\tests\Input.Text.Multiline.json sample to test for regression tests for issue #3714 
3. Scroll to the bottom; Click the ShowCard button; Add some text in the Comment Input.Text for the shown card and then click OK to submit action; Notice the error that pops up: 

![image](https://user-images.githubusercontent.com/20822397/73319742-25c85b00-41f2-11ea-8c2b-458807ae07a6.png)

**Comment by almedina-ms** [comment]
Can you check that this is the application installed from Joseph's email? I was going to install one but it was from April 2019

**Comment by shalinijoshi19** [comment]
I followed the link in the OneNote which is version 2020.01.28.1 which seems accurate..@nesalang?

**Comment by almedina-ms** [comment]
Yes, the application is fine, I just tested this

**Comment by almedina-ms** [comment]
I just checked, the fix was not ported to the release/1.2 branch but it is in master 

https://github.com/microsoft/AdaptiveCards/blob/a55815e3b4be12f9b09ba9570310179a3691813d/source/android/mobile/src/main/java/io/adaptivecards/adaptivecardssample/MainActivityAdaptiveCardsSample.java#L484

**Comment by shalinijoshi19** [comment]
Are you sure? I see it here - https://github.com/microsoft/AdaptiveCards/commits/release/1.2/

**Comment by almedina-ms** [comment]
This is the original issue: #3184

**Comment by shalinijoshi19** [comment]
Ok so this is just a sample issue that is not avaiable in release/1.2 Closing as a dup of #3184
