### ISSUE TITLE
[Windows][Rendering][Teams] [Adaptive Card 1.2 not fully stretching]

### ISSUE THREAD

**Issue by cconrado** [microsoft/AdaptiveCards#3752]
# Windows

* Teams

# Author
Azure Logic App to Teams

# Details

So in Teams adaptive cards don't stretch across the screen like messagecards do. I was told that v1.2 would fix this.

EX. Current Behavior
![image](https://user-images.githubusercontent.com/9168464/73382984-28788e00-428e-11ea-9235-0c09309a9ce4.png)

Ex. Expected Behavior
![image](https://user-images.githubusercontent.com/9168464/73383087-51991e80-428e-11ea-9d9a-dec8490f7850.png)

I am using the Teams developer preview mode and the json of the card is 1.2. So not sure what else can be done

**Comment by shalinijoshi19** [comment]
@dclaux ideas on this one? Thanks!

**Comment by dclaux** [comment]
@cconrado this is a Teams issue, not an Adaptive Card issue. 1.2 can't fix this, and it was never broken to start with. Teams is the entity responsible for imposing a maximum width to the card, and their logic differs between MessageCard and Adaptive Card.

**Comment by cconrado** [comment]
@dclaux thanks for that.

So where I can I post this issue so the right team resolves it?

**Comment by dclaux** [comment]
Let's mention @billbliss and @siduppal here - they should see it and take it from there. That being said, I believe this behavior is by design, so chances are it will not change.

**Comment by cconrado** [comment]
@dclaux no update 😔

**Comment by susanshen96** [comment]
Hi @cconrado - the width for adaptive cards for Teams is currently at a fixed size, and there are currently no plans to change that.

**Comment by cconrado** [comment]
@susanshen96 where do I need to post to change it? The reason is it cuts off text because of it. It needs to be like messagecards

**Comment by stpeteparadox** [comment]
@susanshen96 @billbliss @siduppal @dclaux 
Providing insight into the logic/reasoning behind this supposed design choice would be far more helpful to your clients than simply saying 'it is because it is'. We have planning considerations as well.

**Comment by RebeccaAnne** [comment]
Take a look at this [teams feature](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#full-width-adaptive-card) to see if it addresses your concern.
