### ISSUE TITLE
[Browser][Javascript bundle size] [adaptivecards-fabric import whole fabric so that the bundle size is huge]

### ISSUE THREAD

**Issue by zhaotai** [microsoft/AdaptiveCards#3756]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Author or host

I'm a host. My app is MyAnalytics.

# Version of SDK
adaptivecards-fabric 1.0.4

# Details
![image](https://user-images.githubusercontent.com/8597746/73488709-46152880-435e-11ea-8a3a-d92108fec79a.png)
This will import all into the final bundle. I only circled one. There are a few same others. 

![image](https://user-images.githubusercontent.com/8597746/73489009-bde35300-435e-11ea-8fcb-1704f1eab2ec.png)
Typo

**Comment by matthidinger** [comment]
Thanks for filing this. As I understand it our webpack config has marked all those dependencies as "externals" and in package.json we've marked them as "peerDependencies" meaning they need to be loaded in the consuming app. It's possible something is incorrect in our setup but can you confirm that it is actually loading more than you expect in this configuration?

**Comment by shalinijoshi19** [comment]
@matthidinger since we've responded to this issue marking as "Investigate" and since we're waiting to hear back from @zhaotai added "Needs author feedback" label for telemetry

**Comment by zhaotai** [comment]
I'm not saying the import of "react".
I'm saying "office-ui-fabric-react". You import the whole package in and that's non business of peer dependency or dependency.
The correct way is `import { XX } from "office-ui-fabric-react/lib/XX"`.

**Comment by shalinijoshi19** [comment]
@matthidinger, who from the office fabric team would be the best folks to help farm this out to?

**Comment by shalinijoshi19** [comment]
Hey @BalajiR, @pragadeeshk @Vasanth-S would you be able to take look at this issue please? Thanks

**Comment by paulcam206** [comment]
`adaptivecards-fabric` has been deprecated in favor of `adaptivecards-fluentui`. If this issue still repros in `adaptivecards-fluentui`, please feel free to reactivate. Thanks!
