### ISSUE TITLE
[Platform][Broad Issue Category if applicable (eg Accessibility)] [Bug Title]

### ISSUE THREAD

**Issue by murcinar** [microsoft/AdaptiveCards#3757]
# Platform
* .NET HTML

# Author or host
host, Finance Digital Assistant

If you're an author, who are you sending cards to?

Bot Framework SDK version 4.6.2

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

# Details

images inserted into adaptive cards don't have a property to assign aria-label and by default come as "undefined" as their aria-label. This is a bug preventing us to be accessibility compliant and we need this to be fixed on priority. Please see the screenshot below:

![image](https://user-images.githubusercontent.com/58231579/73494841-297eed80-436a-11ea-91b6-2b0473367529.png)

**Comment by murcinar** [comment]
Attaching a screenshot of the Adaptive card with the image (trash can image):

![image](https://user-images.githubusercontent.com/58231579/73496314-26d1c780-436d-11ea-802a-432cf8ebebac.png)

**Comment by dclaux** [comment]
You need to set the `title` property of your Image's `selectAction`. It will be used as the `aria-label` attribute.

**Comment by murcinar** [comment]
setting the title property of the selectAction fixed the issue. Thank you for your help!
