### ISSUE TITLE
[Android] Add support to provide styling to dialogs

### ISSUE THREAD

**Issue by desaibijon** [microsoft/AdaptiveCards#3758]
* Android

**Is your feature request related to a problem? Please describe.**
Action buttons on dialogs created by Adaptive Cards are not visible

**Describe the solution you'd like**
Is it possible to render the dialogs in adaptive cards with custom styling? The solution to show the buttons seems to work when creating an alert dialog with a custom styling which specifies the text color explicitly.

**Describe alternatives you've considered**
Tried creating a custom element parser and renderer, but I am unable to provide just the styling while keeping every other functionality same.

**Additional context**

**Comment by paulcam206** [comment]
Tracking work in #3830
