### ISSUE TITLE
[Teams Desktop] [Support for v1.2 adaptive cards in Preview Mode fails]

### ISSUE THREAD

**Issue by srishtisatwah** [microsoft/AdaptiveCards#3759]
# Details
I am using Teams Desktop and am trying adaptive cards 1.2 in Developer Preview mode. 
Currently, I am not seeing any cards display. Screenshot attached.

We have a customer dependency on this.
As recommended by @shalinijoshi19 in #3480 , [here](https://github.com/microsoft/AdaptiveCards/issues/3480#issuecomment-579217963) , I am creating this new issue.
Could someone please take a look?

<img width="1086" alt="Screen Shot 2020-01-30 at 2 36 35 PM" src="https://user-images.githubusercontent.com/10636538/73496680-ffc7c580-436d-11ea-814e-c20adfb0208d.png">

**Comment by shalinijoshi19** [comment]
@siduppal / @susanshen96 / @dclaux thoughts on this ? @srishtisatwah coul dyou provide the sample json payload for your adaptive cards? Thanks

**Comment by ManjulaMalaiarasan** [comment]
Hello @shalinijoshi19 Thank you for your patience. Here is a JSON payload we are sending to the bot. 
`{
	"msg": "  \n ",
	"type": null,
	"textFormat": "markdown",
	"speakText": " ",
	"inputHint": "ignoringInput",
	"content": [{
		"type": "receiptCard",
		"contentType": "application/vnd.microsoft.card.adaptive",
		"content": {
			"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
			"type": "AdaptiveCard",
			"version": "1.2",
			"body": [{
					"type": "ColumnSet",
					"columns": [{
							"type": "Column",
							"width": "auto",
							"items": [{
								"type": "Image",
								"url": "https:/****/NewQuoteIcon.png",
								"horizontalAlignment": "left",
								"size": "small",
								"style": "person"
							}]
						},
						{
							"type": "Column",
							"width": "stretch",
							"items": [{
									"type": "TextBlock",
									"text": "Quote Name",
									"isSubtle": true,
									"size": "small",
									"wrap": false,
									"style": {
										"color": "dark"
									},
									"color": "dark"
								},
								{
									"type": "TextBlock",
									"spacing": "none",
									"text": "**[RM MAX 101](https:&#x2F;&#x2F;*****S)**",
									"horizontalAlignment": "left",
									"size": "large",
									"color": "",
									"style": {
										"color": ""
									},
									"wrap": true
								}
							]
						}
					]
				},
				{
					"type": "ColumnSet",
					"separator": "true",
					"columns": [{
							"type": "Column",
							"width": "auto",
							"items": [{
								"type": "Image",
								"url": "https://*****DefaultAccountIcon.png",
								"horizontalAlignment": "left",
								"size": "small",
								"style": "person"
							}]
						},
						{
							"type": "Column",
							"width": "stretch",
							"items": [{
									"type": "TextBlock",
									"spacing": "none",
									"size": "small",
									"color": "dark",
									"text": "Account",
									"isSubtle": true,
									"wrap": true,
									"weight": ""
								},
								{
									"type": "TextBlock",
									"spacing": "none",
									"text": "[Acme Enterprises](https:*****AM)",
									"weight": "bolder",
									"wrap": false,
									"color": "dark"
								}
							]
						},
						{
							"type": "Column",
							"width": "auto",
							"items": [{
								"type": "Image",
								"url": "https:******/ContactIcon.png",
								"horizontalAlignment": "left",
								"size": "small",
								"style": "person"
							}]
						},
						{
							"type": "Column",
							"width": "stretch",
							"items": [{
									"type": "TextBlock",
									"spacing": "none",
									"size": "small",
									"color": "dark",
									"text": "Primary Contact",
									"isSubtle": true,
									"wrap": true,
									"weight": ""
								},
								{
									"type": "TextBlock",
									"spacing": "none",
									"text": "[Edward Stamos](https:/********Q)",
									"weight": "bolder",
									"wrap": false,
									"color": "dark"
								}
							]
						}
					]
				},
				{
					"type": "ColumnSet",
					"separator": "true",
					"columns": [{
						"type": "Column",
						"width": "stretch",
						"items": [{
								"type": "TextBlock",
								"text": "Proposal ID",
								"style": {
									"color": "dark"
								},
								"separator": false,
								"isSubtle": true,
								"size": "small",
								"weight": "bolder",
								"wrap": false
							},
							{
								"type": "TextBlock",
								"text": "[Q-00000346](https*******S)",
								"spacing": "none",
								"size": "medium",
								"isSubtle": false,
								"wrap": false
							},
							{
								"type": "TextBlock",
								"text": "Opportunity Name",
								"style": {
									"color": "dark"
								},
								"separator": false,
								"isSubtle": true,
								"size": "small",
								"weight": "bolder",
								"wrap": false
							},
							{
								"type": "TextBlock",
								"text": "[Acme Opportunity](https:******U)",
								"spacing": "none",
								"size": "medium",
								"isSubtle": false,
								"wrap": false
							},
							{
								"type": "TextBlock",
								"text": "Quote Status",
								"style": {
									"color": "dark"
								},
								"separator": false,
								"isSubtle": true,
								"size": "small",
								"weight": "bolder",
								"wrap": false
							},
							{
								"type": "TextBlock",
								"text": "Generated",
								"spacing": "none",
								"size": "medium",
								"isSubtle": false,
								"wrap": false
							},
							{
								"type": "TextBlock",
								"text": "Net Price",
								"style": {
									"color": "dark"
								},
								"separator": false,
								"isSubtle": true,
								"size": "small",
								"weight": "bolder",
								"wrap": false
							},
							{
								"type": "TextBlock",
								"text": "$  45,125.00",
								"spacing": "none",
								"size": "medium",
								"isSubtle": false,
								"wrap": false
							},
							{
								"type": "TextBlock",
								"text": "Payment Term",
								"style": {
									"color": "dark"
								},
								"separator": false,
								"isSubtle": true,
								"size": "small",
								"weight": "bolder",
								"wrap": false
							},
							{
								"type": "TextBlock",
								"text": "Net 30 Days",
								"spacing": "none",
								"size": "medium",
								"isSubtle": false,
								"wrap": false
							},
							{
								"type": "TextBlock",
								"text": "Created Date",
								"style": {
									"color": "dark"
								},
								"separator": false,
								"isSubtle": true,
								"size": "small",
								"weight": "bolder",
								"wrap": false
							},
							{
								"type": "TextBlock",
								"text": "Mon Nov 18 2019",
								"spacing": "none",
								"size": "medium",
								"isSubtle": false,
								"wrap": false
							},
							{
								"type": "TextBlock",
								"text": "_Created By_",
								"style": {
									"color": "accent"
								},
								"separator": false,
								"isSubtle": true,
								"size": "small",
								"weight": "bolder",
								"wrap": false
							},
							{
								"type": "TextBlock",
								"text": "_[Ajay DeBoss](https:********A)_",
								"spacing": "none",
								"size": "medium",
								"isSubtle": false,
								"wrap": false
							},
							{
								"type": "TextBlock",
								"text": "_Owner_",
								"style": {
									"color": "accent"
								},
								"separator": false,
								"isSubtle": true,
								"size": "small",
								"weight": "bolder",
								"wrap": false
							},
							{
								"type": "TextBlock",
								"text": "_[Ajay DeBoss](https:*******A)_",
								"spacing": "none",
								"size": "medium",
								"isSubtle": false,
								"wrap": false
							},
							{
								"type": "TextBlock",
								"text": "_Last Modified On_",
								"style": {
									"color": "accent"
								},
								"separator": false,
								"isSubtle": true,
								"size": "small",
								"weight": "bolder",
								"wrap": false
							},
							{
								"type": "TextBlock",
								"text": "_Thu Feb 13 2020_",
								"spacing": "none",
								"size": "medium",
								"isSubtle": false,
								"wrap": false
							}
						]
					}]
				}
			],
			"actions": [{
					"type": "Action.Submit",
					"title": "View more details",
					"data": {
						"msteams": {
							"type": "messageBack",
							"displayText": "View more details",
							"text": "View more details"
						}
					}
				},
				{
					"type": "Action.Submit",
					"title": "Send proposal",
					"data": {
						"msteams": {
							"type": "messageBack",
							"displayText": "Send proposal",
							"text": "Send proposal"
						}
					}
				},
				{
					"type": "Action.Submit",
					"title": "Submit for approval",
					"data": {
						"msteams": {
							"type": "messageBack",
							"displayText": "Submit for approval",
							"text": "Submit for approval"
						}
					}
				},
				{
					"type": "Action.Submit",
					"title": "Search for fields",
					"data": {
						"msteams": {
							"type": "messageBack",
							"displayText": "Search for fields",
							"text": "Search for fields"
						}
					}
				},
				{
					"type": "Action.Submit",
					"title": "Send it to me",
					"data": {
						"msteams": {
							"type": "messageBack",
							"displayText": "Send it to me",
							"text": "Send it to me"
						}
					}
				},
				{
					"type": "Action.Submit",
					"title": "Update quote",
					"data": {
						"msteams": {
							"type": "messageBack",
							"displayText": "Update quote",
							"text": "Update quote"
						}
					}
				}
			]
		}
	}]
}`

**Comment by susanshen96** [comment]
@ManjulaMalaiarasan - I checked the payload and I see some inconsistencies that could be contributing to the reason why the card isn't sent on the Teams client. 

- Anything in the format `"style": { "color": value } }` will not be supported - it is an invalid property for TextBlock, as the style property does not exist for TextBlock. Instead, remove these, and just use `"color": value`. (correct me if I'm wrong - @shalinijoshi19)
-Please remove any empty string values - such as `"color": ""` or `"weight": ""`. 

If removing these still doesn't cause the card to be rendered, it may be an issue of the Image URL. I noticed that the URLs provided for the image elements contain asterisks and are not valid URLs - I assume the asterisks are there for privacy/security concerns. But to confirm the Image URLs are another issue, please first correct the inconsistencies listed above, and respond back if the card is still not being rendered.

**Comment by ManjulaMalaiarasan** [comment]
@susanshen96 yes, the asterisks in the URLs are all there for privacy concerns. They are otherwise valid URLs. I will modify the json with given suggestions and get back to you

**Comment by ManjulaMalaiarasan** [comment]
@susanshen96 The cards are rendered after removing the empty string values and the property style. Thank you.

**Comment by shalinijoshi19** [comment]
Closing this issue out at this point. @mmalaiarasan-apttus do let us know if you run into any other issues here. Thanks!
