### ISSUE TITLE
[Teams iOS][ColumnSet-Rendering] [Text gets clipped in columnset if both columns are stretch type]

### ISSUE THREAD

**Issue by adumrewal** [microsoft/AdaptiveCards#3761]
# Teams - iOS

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Host - Teams

# Version of SDK

1.2.5

# Details

If columns in ColumnSet are of type stretch, text gets clipped based on comparative size of texts in columns. PFA the screenshot and JSON.
![Simulator Screen Shot - iPhone X (12 4) - 2020-02-03 at 12 16 47](https://user-images.githubusercontent.com/8917620/73632038-a8cd3380-4680-11ea-822d-ff70d31dae4a.png )
[ColumnSetJson.txt](https://github.com/microsoft/AdaptiveCards/files/4146632/ColumnSetJson.txt)

**Comment by nesalang** [comment]
this is fixed in the master. I will make sure the fix is part of 1.2.6 release

![image](https://user-images.githubusercontent.com/4112696/73717656-48b1ae00-46cf-11ea-9bbc-e2a207f68617.png)

**Comment by nesalang** [comment]
> this is fixed in the master. I will make sure the fix is part of 1.2.6 release
> 
> 

I verified that the fix is part 1.2.6 release, and it's not reproducible. I will leave it open for a few days, but will close it if there are no activities.

**Comment by nesalang** [comment]
Closed as the fix is in 1.2.6 & master, and there have been no activities for last 2 days.

**Comment by nesalang** [comment]
@adumrewal can you confirmed that this is no longer an issue on 1.2.6

**Comment by shalinijoshi19** [comment]
@nesalang , once this is confirmed, we should remove the 1.2.7 tag from this issue. Thanks

**Comment by adumrewal** [comment]
@nesalang @shalinijoshi19 confirming that this issue got fixed with 1.2.6 update.
