### ISSUE TITLE
[TS][Adaptive Card Designer][Image in column with size "auto" disappears]

### ISSUE THREAD

**Issue by susanshen96** [microsoft/AdaptiveCards#3765]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Typescript
* Adaptive Card Designer

# Version of SDK

1.2.5

# Details

The payload in question - (`{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "Image",
                            "altText": "Awesome",
                            "url": "https://adaptivecards.io/content/cats/1.png",
                            "horizontalAlignment": "Center"
                        }
                    ],
                    "width": "auto"
                },
                {
                    "type": "Column",
                    "width": "auto",
                    "items": [
                        {
                            "type": "TextBlock",
                            "text": "Mock praise testing text"
                        },
                        {
                            "type": "TextBlock",
                            "text": "New TextBlock"
                        },
                        {
                            "type": "TextBlock",
                            "text": "New TextBlock"
                        }
                    ]
                }
            ]
        }
    ]
}`). Repro steps are as follows: 

1. Go to the Adaptive Card designer in a Chrome browser. 
2. Open the Chrome debugger. 
3. Close any sub-menus until the card appears unblocked and is visible. 
4. Select "Preview Mode". 

The picture disappears from view once "Preview mode" is selected. This does not repro on any other browser besides Chrome. 
![image](https://user-images.githubusercontent.com/10697383/73796252-9ecf3180-4761-11ea-904a-904ecd8e76d6.png)

A similar experience is happening in Teams in Chrome as well - the picture in the card does not appear. It appears occasionally but there is no consistency. Sometimes a hard refresh of the browser works - sometimes it does not. 
![image](https://user-images.githubusercontent.com/10697383/73796566-62e89c00-4762-11ea-81a3-944ecb9841e4.png) 

In contrast - in Edge, this is the current experience. 
![image](https://user-images.githubusercontent.com/10697383/73796369-dccc5580-4761-11ea-9c82-f9d280ab132a.png)

**Comment by dclaux** [comment]
@susanshen96 unfortunately, as discussed this morning, the generated DOM is correct, so there isn't much I can do. I am not able to repro on my side. I believe it is a browser/cache/something like that issue.

**Comment by shalinijoshi19** [comment]
@susanshen96 can you actually attach a screen recording/screentogif of what you are seeing and calling out as a bug? Also what version of Edge are you referring to?  The json itself renders with the image as expected on both Edge Anaheim (dev) as well as Chrome directly and dont see any errors or issues viewing the image that is getting rendered either? Thanks!

**Comment by shalinijoshi19** [comment]
@susanshen96 ping. Please reopen if you do have some more details for us here. Thanks!
