### ISSUE TITLE
[Android][Extensibility] [TimePickerDialog used in Input.Time card type does not show action buttons]

### ISSUE THREAD

**Issue by desaibijon** [microsoft/AdaptiveCards#3767]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* Android

# Author or host

Host -> Android

What version are you using? Android v1.2.6

# Details

There are issues when the Input.Time CardElementType is rendered by Android. The picker dialog does display the time and has the ability to change the time value, but it is missing the action buttons at the bottom. This is a known issue with Dialogs, here is a stackoverflow link indicating the solution:
[TimePickerDialog is missing buttons](https://stackoverflow.com/questions/48000426/timepickerdialog-cancel-and-ok-button-not-showing)

For now, there is a way for Android to parse the CardElementType.TimeInput specially but we cannot render the custom element to provide a styling to the dialog and leave other functionality as is.

Is there a way to either achieve:

- Add styling to the TimePickerDialog created in the TimePickerFragment
- Add ability to provide a styling via custom renderer while keeping the original content as is.
- Provide me with guidance on how something our app is doing is not allowing the buttons to renderer.

![Screenshot_20200205-125533_Dynamic Signal](https://user-images.githubusercontent.com/17939063/73882351-bb797100-4816-11ea-8e2d-92711acd6440.jpg)

**Comment by shalinijoshi19** [comment]
@almedina-ms , @nesalang  thoughts?

**Comment by desaibijon** [comment]
Do we have any update on this bug?

**Comment by almedina-ms** [comment]
Good morning @desaibijon 

I think one of our most needed features is the ability of defining native styling for elements. I'll file a bug for it and start working on it

**Comment by paulcam206** [comment]
Tracking work in #3830
