### ISSUE TITLE
[Azure Bot - Adaptive Card][Accessibility - Alttext for ICON used in Action button] [MAS 1.1.1: Images must have alternate text (img)]

### ISSUE THREAD

**Issue by Har1pr1ya** [microsoft/AdaptiveCards#3768]
Issue: Images must have alternate text (image-alt - https://dequeuniversity.com/rules/axe/3.3/image-alt?application=msftAI)​

Environment: Chrome version 78.0.3904.108​
​Adaptive card version-  **adaptivecards-1.1.3**

This accessibility issue was found using Accessibility Insights for Web 2.10.3 (axe-core 3.3.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.

**Comment by shalinijoshi19** [comment]
@Har1pr1ya / @siduppal  is this actually on AdaptiveCards? Who/how is the icon for the action button being specified? @RebeccaAnne thoughts ? I thought this was something that the card author would need to specify when they described the image json and use the [alt-text](https://adaptivecards.io/explorer/Image.html) property on it?

**Comment by dandriscoll** [comment]
We are preparing a spec for alt text on Bot Framework CardActions, which can be used within Adaptive Cards. At a high level, the plan is to use the `title` field for alt text in most cases and allow it to be overridden with a new `imageAltText` field when required.

For Adaptive Cards,

- You will need to work out what to do with your own action types
- You may need to introduce something similar for images outside of actions

**Comment by shalinijoshi19** [comment]
Thanks @dandriscoll.  Would you then @RebeccaAnne can you weigh in here on Dan's comments above?

**Comment by Har1pr1ya** [comment]
Thanks a lot for immediate action.  @shalinijoshi19 To set some we are using adaptive card in our agent assist scenario where Bot will send adaptive card to Agent as a suggestion.
https://docs.microsoft.com/en-us/dynamics365/omnichannel/agent/agent-oc/oc-smart-assist#overview-of-smart-assist

We found out this bug in our accessibility review. Let me know if you need more details.

**Comment by Har1pr1ya** [comment]
@RebeccaAnne  @shalinijoshi19 When this bug will be fixed ?

**Comment by JeanRoca** [comment]
Closing this as we now have support for alt text.
