### ISSUE TITLE
C# Adaptive Card namespace is "AdaptiveCards" and not "Microsoft.AdaptiveCards"

### ISSUE THREAD

**Issue by BenjaBobs** [Microsoft/AdaptiveCards#377]
Nuget package is called "Microsoft.AdaptiveCards" but the namespace used is just "AdaptiveCards". This is confusing when adding using-statements.

**Comment by matthidinger** [comment]
This is fixed in the latest AdaptiveCards package. (NOTE: we renamed the package from Microsoft.AdaptiveCards) and it has a few breaking changes in the names. 

Full details here:
https://docs.microsoft.com/en-us/adaptive-cards/create/libraries/net

**Comment by arashberlin** [comment]
**The samples on the official BotBuilder Sample Github page are outdated:** 
[https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/cards-AdaptiveCards](https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/cards-AdaptiveCards)
