### ISSUE TITLE
Action Button Alignment - Horizontal or Vertical

### ISSUE THREAD

**Issue by premaarya** [microsoft/AdaptiveCards#3770]
**What platform is your feature request related to? (Delete other platforms).**

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

**Is your feature request related to a problem? Please describe.**
Action Buttons are aligned either horizontal or vertical depending on the HostConfig setting. If  I want to align them Horizontal for a yes/no, submit/cancel card and  vertical for adaptive card with multiple options, I cannot do that.

**Describe the solution you'd like**
Action button alignment property at card level or Actions level.

**Describe alternatives you've considered**
On a web page for WebChat control write java-script on action fulfillment. if 2 buttons make them horizontally aligned. it was not a good solution :).

**Comment by adamcoulombe** [comment]
As an alternative though, you can just create columns and add seperate actionsets with individual actions. This ended up working for my situation

![alt text](https://i.ibb.co/7CL02Wf/Screenshot-1.png "adaptive card action alignments")

**Comment by RebeccaAnne** [comment]
Duping to #492
