### ISSUE TITLE
[Android][Button Icon rendering] [Button icons size, too big and not controllable]

### ISSUE THREAD

**Issue by shbhadra** [microsoft/AdaptiveCards#3775]
# Platform
What platform is your issue or question related to? (Delete other platforms).

* Android

# Author or host
HOST

# Version of SDK
1.2.6

# Details
For icons placed on the left of the title in a button, the image appears too large and further the size is not controllable using the host config. The icons rendered on web are a lot smaller.

Following screenshots illustrate the issue. They are for the below mentioned Json
`{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "TextBlock",
			"text": "This card's action will open a URL"
		}
	],
	"actions": [
		{
			"type": "Action.OpenUrl",
			"title": "Action.OpenUrl",
			"url": "https://adaptivecards.io",
			"iconUrl": "https://adaptivecards.io/content/cats/1.png"
		}
	]
}`

As rendered on web
![image](https://user-images.githubusercontent.com/51158485/74310994-73b59500-4d94-11ea-87d3-6c59779cb9bc.png)

As rendered on android
![image](https://user-images.githubusercontent.com/51158485/74311193-e292ee00-4d94-11ea-9194-06653b980f84.png)

**Comment by shalinijoshi19** [comment]
@almedina-ms can you please take a look to investigate? Thanks! @nesalang FYI.

**Comment by VikrantSingh01** [comment]
Can it be in v1.2.6 @shalinijoshi19  pls. ?

**Comment by shalinijoshi19** [comment]
Yes. @almedina-ms any update on this one?
