### ISSUE TITLE
[All][Docs] Typo in ActionSet docs ("Array of Image")

### ISSUE THREAD

**Issue by scovetta** [microsoft/AdaptiveCards#3781]
# Details

The [docs](https://adaptivecards.io/explorer/ActionSet.html) for ActionSet reference an "array of Image elements to show". I think this should be an array of Action elements to show.

![image](https://user-images.githubusercontent.com/732166/74399877-1d1a7c00-4dd1-11ea-8e66-ee6f57373317.png)

**Comment by paulcam206** [comment]
Fixed!
