### ISSUE TITLE
[iOS][Card-Height-Rendering] [Card heights changes based on number of actions in ActionsSet]

### ISSUE THREAD

**Issue by adumrewal** [microsoft/AdaptiveCards#3784]
# Platform

* iOS

# Author or host

TeamSpace iOS app

# Version of SDK

latest-master

# Details

The card height gets changed based on the number of actions in ActionSet although the actions are supposed to be a scrollable view. The change in height is the same as ('number of buttons added' x 'height of a button').
PFA the screenshot and JSON.
![Simulator Screen Shot - iPhone X - 2020-02-07 at 10 40 05](https://user-images.githubusercontent.com/8917620/74508655-8dd2ad00-4f25-11ea-8592-4316d51f9b75.png)
[8ActionsJson.txt](https://github.com/microsoft/AdaptiveCards/files/4203172/8ActionsJson.txt)

**Comment by VikrantSingh01** [comment]
This looks to be surfacing only in 1.2.6 drop. Would be good to have this addressed in the final 1.2.6 drop.

**Comment by nesalang** [comment]
This doesn't seem to be SDK's issue
Sample App
![Screen Shot 2020-02-19 at 11 35 22 AM](https://user-images.githubusercontent.com/4112696/74869065-22fde900-530c-11ea-87d9-134de2a1b985.png)

Teams
![image](https://user-images.githubusercontent.com/4112696/74869018-09f53800-530c-11ea-8bc6-5619537f2427.png)

There appear to be an extra view above actions and separator. Can you check what this view is?
It's possible that the expanded view is actually a super view for the action set. Can you also share the dimension of this expanded view and the expanded view's subview if it has any?

**Comment by adumrewal** [comment]
PFA screenshot with heights of the extra view based on the number of buttons.

Hierarchy for the UIView:
- ACRView - ACR Root View
  - UIStackView
    - ACRUILabel
    - **UIView** [_Our view of interest_]
    - ACRSeparator
    - TSCGradientCustomScrollView
<img width="338" alt="Screenshot 2020-02-20 at 5 45 13 PM (1) (1)" src="https://user-images.githubusercontent.com/8917620/74937073-5a09f280-5411-11ea-8fd6-51c71ac8d1e5.png">

The view might be getting added by the function addPaddingSpace in ACRColumnView.
**Note**: The height does not change on adding a ShowCard button.

**Comment by shalinijoshi19** [comment]
@nesalang this will need to be merged in master for the issue to be auto-closed. Could you also do that so the status of the bug can auto-update? Thanks!

**Comment by nesalang** [comment]
with 1.2.7, action set is not cut any more.
in addition to it, teams wants to have way to set intrinsic content size.
