### ISSUE TITLE
[Android][Action Button Rendering] [Not able to style the action buttons for android]

### ISSUE THREAD

**Issue by prathibhap-google** [microsoft/AdaptiveCards#3786]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* Android

# Author or host

adaptive cards -  in webex android application

# Version of SDK

Version: 1.2.6[io.adaptivecards:adaptivecards-android:1.2.6]

# Details
I was looking at styling the adaptive cards based on the theme selected for my android application. My android application supports dark and light themes. I am able to style the adaptive-card by passing a config[JSON file with colors configured] to Host Config like below.

val hostConfig = HostConfig.DeserializeFromString(adaptiveCardConfig)

I have three action buttons [Action.ShowCard, Action.Submit, Action.OpenUrl ] in my card. I would like to change the background color, font, shape of the action buttons based on the theme  selected. I tried reading the docs and looked at the samples in github, but did not find a way to do it. 

The documentation has a section Native-Styling under android docs which tells me to specify style in my themes.xml file.
<item name="adaptiveInlineAction">@style/adaptiveInlineAction</item>
Specifying a style with this attribute doesn't apply the specified style. 

Attached screenshot gives you the preview of the buttons that I am looking at styling. 
<img width="334" alt="Screen Shot 2020-02-14 at 2 02 36 PM" src="https://user-images.githubusercontent.com/25312561/74571484-bd3be680-4f32-11ea-82b3-a85ba5378e19.png">

Can you please let me know if there is an option to style the action buttons?

**Comment by shalinijoshi19** [comment]
@almedina-ms can you take a look at this real quick ? Thanks!

**Comment by almedina-ms** [comment]
The inline action element refers to an action defined in a textblock, if you want to try styling for other actions you can try setting a sentiment and overriding that style. On the other hand, I'm also prototyping more native styling for other elements so expect an update soon

**Comment by almedina-ms** [comment]
Closing this as it's going to be fixed along with this issue

https://github.com/microsoft/AdaptiveCards/issues/3830
