### ISSUE TITLE
[Android][] [Adaptive card is not rendered on android phone]

### ISSUE THREAD

**Issue by jobinesh** [microsoft/AdaptiveCards#3787]
# Platform
* Android

# Author or host

External bot app sending message to MS Teams channel

# Version of SDK

NA

# Details

I have an external bot configured to use MS Teams channel via the message end point web hook. The following is the message posted to the  Ms Teams channel by the external bot. This message gets rendered as expected when MS Teams is accessed via web browser or MS Teams application on desktop computer. However,  the card is not rendered (seeing an empty line/block without any content)  when used with  Teams application on android mobile phone. 
`{ 
   "channelData":{ 
      "tenant":{ 
         "id":"xxxxxxxxxxxxxx"
      }
   },
   "attachments":[ 
      { 
         "contentType":"application/vnd.microsoft.card.adaptive",
         "content":{ 
            "fallbackText":"Adaptive card version not supported",
            "type":"AdaptiveCards",
            "body":[ 
               { 
                  "text":"Here is an adaptive card with a link to a task module",
                  "type":"TextBlock"
               },
               { 
                  "type":"Image",
                  "url":"http://adaptivecards.io/content/cats/1.png"
               }
            ],
            "version":"1.0",
            "actions":[ 
               { 
                  "type":"Action.OpenUrl",
                  "title":"Open Link",
                  "url":"https://teams.microsoft.com/l/task/xxxxx?url=https%3A%2F%2Fwww.wikipedia.com%0A&height=large&width=large&title=Wikipedia-Embed"
               }
            ]
         }
      }
   ],
   "replyToId":"xxxxxx",
   "serviceUrl":"https://smba.trafficmanager.net/amer/",
   "recipient":{ 
      "name":"xxxx xxxx",
      "aadObjectId":"xxxxx",
      "id":"xx:xxxxxxxx"
   },
   "localTimestamp":"2020-02-14T15:21:41.1360000-08:00",
   "channelType":"msteams",
   "from":{ 
      "name":"xxxxxx",
      "id":"xx:xxxxx"
   },
   "type":"message",
   "conversation":{ 
      "conversationType":"personal",
      "tenantId":"xxxxxx",
      "id":"x:xxxxxx"
   }
}`

**Comment by shaikShehanaaz** [comment]
Any update/workaround on this ?
We have a bot configured to MS Teams on iOS. Adaptive card buttons are not responsive.

**Comment by jobinesh** [comment]
The above issue was due to the typo. The type  needs to be as follows, with this change it works on mobile as well.
 "type":"AdaptiveCards"

**Comment by shaikShehanaaz** [comment]
After changing the property to - "type":"AdaptiveCards" - it is not working in MS Teams. It says "Sorry, it looks like something went wrong."

**Comment by jobinesh** [comment]
Sorry, I mean to say "type":"AdaptiveCard" (it was AdaptiveCards in my case). May be you can log a new issue with a test case(steps to reproduce the issue) as this issue is already marked as closed

**Comment by shaikShehanaaz** [comment]
Sure. Thanks for your input @jobinesh

**Comment by rajjagani021** [comment]
@jobinesh 

how did you solve it? I am still having the same issue after using `type:"AdaptiveCard"`. Below is my JSON and it's working fine on MS Team Web and desktop app but not working in the Android/IOS mobile app.
```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "Container",
      "items": [
        {
          "type": "Container",
          "items": [
            {
              "type": "Image",
              "url": "https://user-photos.imgix.net/avatar/user/original/300a55d8-c50b-44e2-bbf7-9f619a523d38_1603367494.jpeg",
              "size": "medium",
              "horizontalAlignment": "left"
            },
            {
              "type": "Image",
              "size": "large",
              "horizontalAlignment": "center"
            },
            {
              "type": "Container",
              "horizontalAlignment": "left",
              "items": [
                {
                  "type": "TextBlock",
                  "weight": "bolder",
                  "size": "large"
                },
                {
                  "type": "TextBlock",
                  "text": "Raj Jagani is here to meet you."
                },
                {
                  "type": "FactSet",
                  "facts": [
                    {
                      "title": "Location",
                      "value": "HID Location"
                    }
                  ]
                },
                {
                  "type": "RichTextBlock",
                  "inlines": [
                    {
                      "type": "TextRun",
                      "isSubtle": true,
                      "text": "{{DATE(2020-10-22T17:49:50+05:30, LONG)}} {{TIME(2020-10-22T17:49:50+05:30)}}"
                    }
                  ]
                },
                {
                  "type": "TextBlock",
                  "text": ""
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "actions": []
}
```
**Output**
![image](https://user-images.githubusercontent.com/4434991/96991623-5e5d5100-1546-11eb-9483-2851f7969f5b.png)
