### ISSUE TITLE
[TEAMS][ERROR  Adaptive Card with video] 

### ISSUE THREAD

**Issue by LizMoreno** [microsoft/AdaptiveCards#3790]
**I can´t show an adaptiveCard in###  teams with video. 
This is json I use, help please. Thanks!**
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.1",
    "fallbackText": "This card requires Media to be viewed. Ask your platform to update to Adaptive Cards v1.1 for this and more!",
    "body": [
        {
            "type": "Media",
            "poster": "{ThumbnailUrl}",
            "sources": [
                {
                    "mimeType": "video/mp4",
                    "url": ""
                }
            ]
        }
    ]
}

**Comment by susanshen96** [comment]
Hi @LizMoreno, Teams doesn't currently support adaptive cards with Media content. We're looking to support that in the future, but currently do not have a timeline for that.
