### ISSUE TITLE
.Net Adaptive card not rendering with large data in Teams

### ISSUE THREAD

**Issue by nagavamsi777** [microsoft/AdaptiveCards#3797]
Hi,

I am using Adaptive cards version v.1.2.4.

When I am trying to post Weather report Today , 24 Hour and 5 Day  in single message using Adaptive card in **Teams** channel using json. But it giving below error

Operation returned an invalid status code '**RequestEntityTooLarge**'   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)

Is there any limitation of  size of the data that can be posted in teams using Adaptive card.
Please help me.

**Comment by shalinijoshi19** [comment]
@ckkashyap / @dandriscoll / @jameslew ideas on this one? @nagavamsi777 this error isn't coming from AdaptiveCards so have added the Bot framework partners to help!

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4668
