### ISSUE TITLE
Input Elements should have non-editable property

### ISSUE THREAD

**Issue by sandeepnmenon** [microsoft/AdaptiveCards#380]
Suggestion: Input Elements should have non-editable property

**Comment by matthidinger** [comment]
Hi @sandeepnmenon can you elaborate on this suggestion?

**Comment by sandeepnmenon** [comment]
Input text fields, for example
`{
              "type": "Input.Text",
              "id": "myName",
              "placeholder": "Last, First"
            }`
These text fields do not have a non-editable property.
A scenario where you do not want users to edit the text field after some action.
Just a suggestion

**Comment by andrewleader** [comment]
Thanks for the feedback! We've captured this feature request and will monitor additional requests for read-only inputs.
