### ISSUE TITLE
iOS - adaptive card Buttons are not responsive in Teams on iOS device/mobile

### ISSUE THREAD

**Issue by shaikShehanaaz** [microsoft/AdaptiveCards#3800]
# Platform: iOS

What platform is your issue or question related to? (Delete other platforms).
* iOS

# Author or host
External bot app sending message to MS Teams channel

# Version of SDK: SDK 4
framework: netcoreapp3.0

# Details
We are working on a cross platform bot. Adaptive card with buttons doesn't seems to respond in MS Teams when used in iOS mobile. There is no response from bot at all. 
The issue doesn't appear in Android devices.

**Comment by shalinijoshi19** [comment]
Thanks @shaikShehanaaz for reaching out. Are you able to share the card json that you are sending up  to the bot?  @VikrantSingh01 / @siduppal could you help take a first stab at this please to help me understand how this could be an AdaptiveCards issue?

**Comment by shaikShehanaaz** [comment]
@shalinijoshi19 
Here is the Json paylod, some of the text is modified run-time:
`{
   "type": "AdaptiveCard",
   "version": "1.0",
   "body": [
      {
         "type": "Container",
         "items": [
            {
               "type": "TextBlock",
               "text": "<heading>",
               "wrap": true
            }
         ]
      },
      {
         "type": "Container",
         "items": [
            {
               "type": "ColumnSet",
               "columns": [
                  {
                     "type": "Column",
                     "width": "stretch",
                     "items": [
                        {
                           "type": "TextBlock",
                           "text": "<Option1>",
                           "horizontalAlignment": "Center",
                           "weight": "Light",
                           "separator": true,
                           "color": "Accent"
                        }
                     ],
                     "id": "1",
                     "selectAction": {
                        "type": "Action.Submit",
                        "title": "actionButton",
                        "data": {
                           "msteams": {
                              "type": "imBack",
                              "value": "{3}"
                           }
                        }
                     },
                     "horizontalAlignment": "Center",
                     "style": "emphasis"
                  },
                  {
                     "type": "Column",
                     "width": "stretch",
                     "separator": true,
                     "items": [
                        {
                           "type": "TextBlock",
                           "text": "<Option2>",
                           "horizontalAlignment": "Center",
                           "weight": "Light",
                           "separator": true,
                           "color": "Accent"
                        }
                     ],
                     "id": "2",
                     "selectAction": {
                        "type": "Action.Submit",
                        "title": "actionButton",
                        "data": {
                           "msteams": {
                              "type": "imBack",
                              "value": "{4}"
                           }
                        }
                     },
                     "horizontalAlignment": "Center",
                     "style": "emphasis"
                  }
               ]
            }
         ]
      }
   ],
   "$schema": "http:adaptivecards.ioschemasadaptive-card.json"
}`

**Comment by adumrewal** [comment]
This looks like something to do with the keyword "msteams" in the "data" object on the Teams iOS app side.
cc- @Aditya0603 @nesalang

**Comment by siduppal** [comment]
@VikrantSingh01 can you take a look from mobile perspective?

**Comment by adumrewal** [comment]
This looks like a bug on Teams iOS app and not on the SDK. We are working on the fix, it should be available in the next release.
cc- @VikrantSingh01  @Aditya0603

**Comment by nesalang** [comment]
@nesalang check if we can close it.

**Comment by jwoo-msft** [comment]
@shaikShehanaaz can you let us know if this is still an issue for you?

**Comment by shalinijoshi19** [comment]
Going ahead closing this. Please reactivate if this is still repro'ing for you with the latest Teams iOS app.

**Comment by birla** [comment]
@shalinijoshi19  I'm facing this on Android app, buttons working fine on Teams desktop and web. Curiously, other buttons are working on Android using the "msteams" in the "data" object. This has got us stumped!
