### ISSUE TITLE
[Teams][TextBlock] Dates in TextBlock are not localized when Teams is in a different language

### ISSUE THREAD

**Issue by susanshen96** [microsoft/AdaptiveCards#3801]
**What platform is your feature request related to? (Delete other platforms).**

* JavaScript

**Is your feature request related to a problem? Please describe.**
The provided date format for TextBlock does not localize to the language of Teams Client - it simply localizes to the local region of the user - i.e. specifically for me, it would only display dates in US format. For instance, consider this section of a sample JSON card payload:

`{
                                            "type": "TextBlock",
                                            "size": "small",
                                            "height": "auto",
                                            "weight": "lighter",
                                            "horizontalAlignment": "right",
                                            "text": "**{{DATE(2019-12-17T15:12:00Z)}}**"
}`

The date renders correctly when the language of the Teams Client is in English, but doesn't render in the localized format when the language is switched to another one - for instance, in many European languages, the month and the day are flipped.  

**Describe the solution you'd like**
It would be great for the SDK to support functionality for Teams to be able to inject its own logic to localize dates to the language of that the Teams client of a specific user.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4772
