### ISSUE TITLE
Narrator Support for TextBlock Elements on Microsoft Edge Browser

### ISSUE THREAD

**Issue by murcinar** [microsoft/AdaptiveCards#3802]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Author or host

Host, Finance Digital Assistant (Chat Bot)

# Version of SDK

4.6.2

# Details

Using Microsoft Narrator, TextBlock properties are announced on Chrome browser but on MS Edge, none of the TextBlock is announced to the user. only links and input fields are announced with Edge. This is blocking accessibility compliance and needs to be fixed immediately.

**Comment by shalinijoshi19** [comment]
Hi @murcinar thanks for reporting this. Could you help me understand if this is the older Microsoft Edge or the newer/Chrome-based Edge browser that you are referring to? Also can you please help me understand your timelines here please?  @dclaux could you help me understand the scope of the changes needed here? Thanks

**Comment by murcinar** [comment]
Hi @shalinijoshi19 I believe I still have the older (legacy) Microsoft Edge which came installed with Windows 10. 
I am currently working on these accessibility bugs to enable my team to achieve level B accessibility compliance as soon as possible. 
So if you could help us resolve these issues on the highest priority, I would really appreciate. If any help or additional info needed from our end, please let me know.
Thank you!

**Comment by murcinar** [comment]
![image](https://user-images.githubusercontent.com/58231579/75578763-4d8d2780-5a19-11ea-9734-0b692b42759d.png)

**Comment by dclaux** [comment]
I can repro this in legacy Edge. I could swear this is a regression on Edge's part, but I am not 100%.

The fix is most likely simple, namely set the correct aria-label attributes on rendered TextBlock elements.

**Comment by murcinar** [comment]
Hi @shalinijoshi19  Is there any progress/update on this issue? We are still blocked by this and any help is appreciated. Thank you!

**Comment by shalinijoshi19** [comment]
@paulcam206 is this something you can address with the fix for [ #3914](https://github.com/microsoft/AdaptiveCards/pull/3914)

**Comment by paulcam206** [comment]
This no longer repros with a newer build of (old) Edge (version `44.19XXX` with EdgeHTML version `18.19XXX`). I looked at the HTML emitted for TextBlocks and they look correct from an aria standpoint. I don't think there's any further action required on our part here.
