### ISSUE TITLE
[MS-Teams][Card Area] Max height for a card with scroller enabled

### ISSUE THREAD

**Issue by wasim8906** [microsoft/AdaptiveCards#3803]
**What platform is your feature request related to? (Delete other platforms).**

* MS Teams

**Is your feature request related to a problem? Please describe.**
Currently there is no way to set max height of a card or a container, due to which if there is a long list of data then this stretches for pages. Instead a scroller is preferable

**Describe the solution you'd like**
A property like minHeight , maybe maxHeight where we can declare the max height of the card, which comes with scroller when the height of the card exceeds the maxHeight.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4771
