### ISSUE TITLE
[iOS][ChoiceSet] ["wrap":true doesn't work and text still gets clipped]

### ISSUE THREAD

**Issue by adumrewal** [microsoft/AdaptiveCards#3804]
# Platform

* iOS

# Author or host

Teams iOS app

# Version of SDK

latest-master

# Details

Even on setting the wrap as true for ChoiceSet, text is still getting clipped.
PFA screenshot of the SDK visualiser and the json.
<img src="https://user-images.githubusercontent.com/8917620/75332230-0d5b6700-58aa-11ea-80f0-6d4e4e832f33.png" width="300">

[choiceSetLongWrap.txt](https://github.com/microsoft/AdaptiveCards/files/4254693/choiceSetLongWrap.txt)

**Comment by VikrantSingh01** [comment]
@shalinijoshi19 @nesalang : Can you pls. check.

**Comment by shalinijoshi19** [comment]
Thanks for reporting @VikrantSingh01 / @adumrewal .  @almedina-ms can you please help take a look at this ? @nesalang for FYI.

**Comment by shalinijoshi19** [comment]
@VikrantSingh01 / @adumrewal  how much of a blocker is this bug towards your GA? Do we need to block release of AC 1.2.7 (slated for Friday 2/28) for this?

**Comment by shalinijoshi19** [comment]
@almedina-ms  this issue will get auto closed once you commit the change to master.. is that done?
