### ISSUE TITLE
[Templating] Adaptive Card is not rendering, when binded data is not provided

### ISSUE THREAD

**Issue by ramya-ramanathan-28** [microsoft/AdaptiveCards#3806]
**Platform**
Template engine, all platforms

**Is your feature request related to a problem? Please describe.**
1. If the data is not binded to RichTextBlocks, the entire Adaptive card does not render. 
2, For textblocks with hyperlinks, when data is not binded to the display property, 
       - The value shows up as **undefined** if $when condition is not present 
       - the card doesn't render if the $when is present

**Additional context**
If an element is binded to a display property, but the data associated is not provided, 
 - The card should render. 
 - No undefined value should be seen.

**Comment by RamyaRamanathan28** [comment]
@dclaux, Could you please take a look at this issue? Thank you.

**Comment by dclaux** [comment]
@RamyaRamanathan28 can you please provider a repro payload?
