### ISSUE TITLE
Adaptive Cards getCard and setCard method return Object

### ISSUE THREAD

**Issue by ramya-ramanathan-28** [microsoft/AdaptiveCards#3807]
In Adaptive card-designer, the `getCard()` and `setCard(card)` methods return type `Object` instead of an `IAdaptiveCard` interface.

**Comment by shalinijoshi19** [comment]
@dclaux can you help take a look at this one please? Thanks!

**Comment by dclaux** [comment]
This is by design. If they were to accept/return something other than object, it would be an `AdaptiveCard` instance, not `IAdaptiveCard` anyway. `IAdaptiveCard` really shouldn't be part of the library to start with; there is a broader conversation that needs to be had on that front.

**Comment by shalinijoshi19** [comment]
Thanks David! @RamyaRamanathan28 please see @dclaux's response above. Reopening to make sure we can track the "broader design conversation" issue that David refers to on the team backlog.

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.
