### ISSUE TITLE
Conditional Layout documentation

### ISSUE THREAD

**Issue by wilheimpage** [microsoft/AdaptiveCards#3814]
The [documentation on Conditional Layout](https://docs.microsoft.com/en-us/adaptive-cards/templating/language#conditional-layout) using the $when property is fairly limited. 

Would it be possible to expand this a bit with the syntax? If it's possible to do more than just evaluate numbers? For example if a text input is not null or a choice set is not a certain value etc.

**Comment by paulcam206** [comment]
tracking doc updates in #6316
