### ISSUE TITLE
[MSTeams][AdaptiveCard] Adaptive Cards Carousel not displaying in Teams

### ISSUE THREAD

**Issue by Chekrii** [microsoft/AdaptiveCards#3821]
# Platform

* .Net Core
* Bot Framework

# Author or host

* MsTeams

Hi,

I am using Bot framework V4 and I am sending the Adaptive card as a Carousel to Teams but sometimes teams is failing to load the adaptive carousel.

Note:- After waiting some time, the carousel is loading. properly.

Can you please help with the issue.

Please find the screenshot.

 
<img width="663" alt="MainCarousel" src="https://user-images.githubusercontent.com/49824279/75963486-98141580-5eeb-11ea-8470-3aceb67e0893.PNG">

**Comment by DeeJayTC** [comment]
Hey @Chekrii ,
do you mind adding your card json for completion?

Pretty sure its easier for the guys to find out whats going on with some example.

**Comment by nesalang** [comment]
@Chekrii 
Your issue seems similar to #3315. Can you try to reduce the number of cards in the carousel, and see if it helps?

**Comment by Chekrii** [comment]
Hello @nesalang,

I am sending 4 cards in Carousel and still facing the same issue. when I logging to Teams and open the bot, the whole conversation with the bot is loading but not Carousel.

Please find the Adaptive card  I am using.

{"type":"AdaptiveCard","version":"1.0","body":[{"type":"TextBlock","text":"<Title>","wrap":true},{"type":"TextBlock","text":"<Content of article>","wrap":true,"maxLines":4}],"$schema":"http://adaptivecards.io/schemas/adaptive-card.json","actions":[{"type":"Action.OpenUrl","title":"Read more","id":"","iconUrl":"","url":"<Url>"}]}

I am replacing Title, Content, and Url at run time.

Thanks.

**Comment by shalinijoshi19** [comment]
@nesalang assigning to you for follow up here. Please see @Chekrii 's response above. Thanks!

**Comment by Chekrii** [comment]
Hi All, Any update on this Issue or any workaround?
Thanks.

**Comment by Chekrii** [comment]
Hi all,

this is happening a lot these days for the carousel a lot.
After scrolling up and come to the carousel it is blank and takes a lot of time to load.
my carousel is having 4  adaptive cards with 4 buttons each.

**Comment by susanshen96** [comment]
Hi @Chekrii,
There was a fix for a similar bug for adaptive card carousel that was deployed in May, and it should have reached the public version of Teams. Can you confirm that this is still happening, or if the issue has been fixed? Thanks!

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4667
