### ISSUE TITLE
[Javascript][Accessibility] [ChoiceSet is rendering empty option when placeholder is not set or empty]

### ISSUE THREAD

**Issue by ashkvarenko** [microsoft/AdaptiveCards#3822]
# Platform

* JavaScript

# Version of SDK

latest master

# Details

ChoiceSet is rendering empty option when placeholder is not set or empty.
This affects screen reader. It reads options as "value 1 (2 of 3)" and "value 2 (3 of 3)"

```javascript
"type": "Input.ChoiceSet",
"id": "2eebbe39-4842-437c-9560-1b0a23f7bc3c",
"choices": [
    {
        "title": "value 1",
        "value": "value 1"
    },
    {
        "title": "value 2",
        "value": "value 2"
    }
]
```

I suggest to render additional option when placeholder is not empty.
Rendering code is in internalRender method of ChoiceSetInput class in this file
https://github.com/microsoft/AdaptiveCards/blob/master/source/nodejs/adaptivecards/src/card-elements.ts#L3275

Current logic:
```javascript
let option = document.createElement("option");
option.selected = true;
option.disabled = true;
option.hidden = true;
option.value = "";

if (this.placeholder) {
    option.text = this.placeholder;
}

Utils.appendChild(this._selectElement, option);
```

Suggestion:
```javascript
if (this.placeholder) {
    let option = document.createElement("option");
    option.selected = true;
    option.disabled = true;
    option.hidden = true;
    option.value = "";

    option.text = this.placeholder;

    Utils.appendChild(this._selectElement, option);
}
```

**Comment by shalinijoshi19** [comment]
@ashkvarenko thanks for reporting it and the proposed solution as well.. @dclaux thoughts on this?

**Comment by dclaux** [comment]
I am not sure I am following.
- ChoiceSetInput always renders a "hidden" option, that is how the placeholder gets displayed
- If the placeholder property is not specified though, that hidden option is empty. But it still provides a way to have a "nothing selected" option
- If the hidden option's placeholder was always set to the value of the plaholder property even when it is undefined, then the text "undefined" would appear and narrator would read "undefined" which I doubt is what we want
