### ISSUE TITLE
[MsTeams][IOS][AdaptiveCard] Action.submit of Column in ColumnSet is not working in IOS Mobile

### ISSUE THREAD

**Issue by Chekrii** [microsoft/AdaptiveCards#3824]
# Platform
* IOS
# Host
* Ms Teams

Hi all,

I am using Action.Submit Property On Column in Column set.
In Android and Windows, Text is echoing back on click on Column but In IOS Clicking on Column is not working as expected.

Please find the Screenshot in Windows:-
![Apdaptive Tap](https://user-images.githubusercontent.com/49824279/76076366-bd288700-5fc4-11ea-84cb-44c7ee42dacc.PNG)

please find the screenshot in IOS where Clicking on Column is not working:-

![Adaptive IOS](https://user-images.githubusercontent.com/49824279/76076422-d7fafb80-5fc4-11ea-9440-5770b1b6a52c.PNG)

Adative Card Json:-

{"type":"AdaptiveCard","version":"1.0","body":[{"type":"ColumnSet","columns":[{"type":"Column","width":"stretch","items":[{"type":"Image","altText":"","url":"https://picsum.photos/200/200?image=100","size":"Medium","horizontalAlignment":"Center"},{"type":"TextBlock","text":"Adaptive things","wrap":true,"spacing":"Small","horizontalAlignment":"Center","size":"Small","maxLines":3}],"selectAction":{"type":"Action.Submit","title":"Main Title","data":{"msteams":{"type":"imBack","value":"Can you help me"}}}},{"type":"Column","width":"stretch","items":[{"type":"Image","altText":"","url":"https://picsum.photos/200/200?image=100","size":"Medium","horizontalAlignment":"Center"},{"type":"TextBlock","text":"Adaptive things","wrap":true,"spacing":"Small","horizontalAlignment":"Center","size":"Small","maxLines":3}],"selectAction":{"type":"Action.Submit","title":"Main Title","data":{"msteams":{"type":"imBack","value":"Can you help me"}}}},{"type":"Column","width":"stretch","items":[{"type":"Image","altText":"","url":"https://picsum.photos/200/200?image=100","size":"Medium","horizontalAlignment":"Center"},{"type":"TextBlock","text":"Adaptive things","wrap":true,"spacing":"Small","horizontalAlignment":"Center","size":"Small","maxLines":3}],"selectAction":{"type":"Action.Submit","title":"Main Title","data":{"msteams":{"type":"imBack","value":"Adaptive things"}}}},{"type":"Column","width":"stretch","items":[{"type":"Image","altText":"","url":"https://picsum.photos/200/200?image=100","horizontalAlignment":"Center","size":"Medium"},{"type":"TextBlock","text":"Adaptive things","wrap":true,"spacing":"Small","size":"Small","horizontalAlignment":"Center","maxLines":3}],"selectAction":{"type":"Action.Submit","title":"Main Title","data":{"msteams":{"type":"imBack","value":"Can you help me"}}}}]}],"$schema":"http://adaptivecards.io/schemas/adaptive-card.json"}

Please help,
Thanks.

**Comment by nesalang** [comment]
@shalinijoshi19 I just verified that this works on our sample app.  I thinks it's Team's issue.

**Comment by Chekrii** [comment]
Is there any fix for this? One of our features depends on this.

**Comment by nesalang** [comment]
> Is there any fix for this? One of our features depends on this.
@adumrewal Can you respond to @Chekrii 's question?

**Comment by shalinijoshi19** [comment]
Hey @Vikrantsingh01 FYI. This seems to be an example of an issue where an AC customer is blocked on a Teams host app update; Cc - @adumrewal / @Aditya0603

**Comment by Chekrii** [comment]
Hi,
One more Issue in IOS is that In the above JSON, we are using four column set and each column set is having one image.
Even when we click on the first image or second image, the image from the last column set is popping up in IOS.
Thanks.

**Comment by adumrewal** [comment]
@Chekrii this issue has been fixed on the Teams iOS client and should be available in the April Store build.
cc- @VikrantSingh01 / @Aditya0603

**Comment by Chekrii** [comment]
@adumrewal  Thanks for the help

**Comment by nesalang** [comment]
@nesalang check see if we can close.

**Comment by Sujit-Gaikwad** [comment]
@Subhasish-msft  is April store update given for this issue??

**Comment by Subhasish-msft** [comment]
@Sujit-Gaikwad , We have active bug for this and currently there is no ETA.

**Comment by Sujit-Gaikwad** [comment]
@Subhasish-msft , with V2.0.9 teams update this is working for iPhone 10 but with same update it is not working for iPhone 6
can you tell me for which all version it will support???

**Comment by Sujit-Gaikwad** [comment]
@Subhasish-msft any update on above comment

**Comment by Subhasish-msft** [comment]
I am discussing with engineering team on this. Will post once i receive an update.

**Comment by adumrewal** [comment]
@Sujit-Gaikwad can you provide the iOS versions on iPhone 10 and iPhone 6

**Comment by Sujit-Gaikwad** [comment]
@adumrewal here are the details
iPhone 6
   iOS version 12.4.5
​   Teams version 2.0.10

iPhone X
   iOS version 13.4.1
​   Teams version 2.0.10

**Comment by adumrewal** [comment]
@Sujit-Gaikwad iPhone 6 (iOS: 12.4, Teams version: 2.0.10) and iPhone X (iOS: 13.4, Teams version: 2.0.10) have the same behaviour for the above card. Can you please elaborate on the issue that you are facing? If a screen recording is possible please attach that.

**Comment by Sujit-Gaikwad** [comment]
@adumrewal 
I'm having issue with column set **select action** which is not working on iphone 6.
>>@Sujit-Gaikwad iPhone 6 (iOS: 12.4, Teams version: 2.0.10) and iPhone X (iOS: 13.4, Teams >>version: 2.0.10) have the same behaviour for the above card.

is it means that Adaptive column set action will work on every  iphone ?
if it is working fine which all iPhone and iOS version it will aupport

**Comment by adumrewal** [comment]
You should expect the same behaviour if both the devices are running the same Teams version and iOS version.
Can you please share a screen recording of the issue you are facing with the complete Teams version number.

**Comment by Subhasish-msft** [comment]
@Sujit-Gaikwad , Could you please share the recording of the issue that you are facing with complete Teams version number.

**Comment by Sujit-Gaikwad** [comment]
>>@Sujit-Gaikwad , Could you please share the recording of the issue that you are facing with >>complete Teams version number.

@Subhasish-msft Sorry, i'm not able to share the recording as my leads not allowing me to do so.
but as per my obsevation this is now working fine with new teams update V2.0.11.

Thanks for your help

Regards,
Sujit sanjay gaikwad.

**Comment by Subhasish-msft** [comment]
Thanks for your confirmation. I am closing this issue.
