### ISSUE TITLE
System.InvalidOperationException: Current error context error is different to requested error.

### ISSUE THREAD

**Issue by 3GDXC** [microsoft/AdaptiveCards#3835]
#Issue 
I'm seeing the System.InvalidOperationException: Current error context error is different to requested error. when using AdaptiveCards

# Platform
* .NET HTML

# Author or host
outlook-desktop as per this report samples
agenda.template as per this report samples

# Version of SDK
v1.2.4 of AdaptiveCard 
v3.1 ASP.NET Core 

# Details
> System.InvalidOperationException: Current error context error is different to requested error.
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalBase.GetErrorContext(Object currentObject, Object member, String path, Exception error)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalBase.IsErrorHandled(Object currentObject, JsonContract contract, Object keyValue, IJsonLineInfo lineInfo, String path, Exception ex)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    at AdaptiveCards.AdaptiveCard.FromJson(String json)

**Comment by nesalang** [comment]
@3GDXC ,

Can you share your json payload that caused this error?

**Comment by 3GDXC** [comment]
```
{
	"$schema": "https://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "ColumnSet",
			"columns": [
				{
					"width": "32px",
					"items": [
						{
							"type": "Image",
							"width": "16px",
							"horizontalAlignment": "center"
						}
					]
				},
				{
					"width": "stretch",
					"items": [
						{
							"type": "TextBlock",
							"text": "logo"
						}
					]
				},
				{
					"width": "auto",
					"verticalContentAlignment": "center",
					"items": [
						{
							"type": "Image",
							"width": "12px",
							"url": "https://messagecardplayground.azurewebsites.net/assets/Close.png",
							"altText": "Close"
						}
					]
				}
			]
		},
		{
			"type": "ColumnSet",
			"spacing": "large",
			"separator": true,
			"columns": [
				{
					"width": "32px",
					"items": [
						{
							"type": "Image",
							"width": "32px",
							"style": "person",
							"horizontalAlignment": "center"
						}
					]
				},
				{
					"width": "stretch",
					"items": [
						{
							"type": "TextBlock",
							"text": "**Leo Adams added a card**"
						},
						{
							"type": "TextBlock",
							"spacing": "none",
							"isSubtle": true,
							"text": "\"Visual design for Project A\" to \"Fabrikam\" list"
						},
						{
							"type": "TextBlock",
							"spacing": "small",
							"isSubtle": true,
							"text": "Sent on: 12/12/2017"
						},
						{
							"type": "TextBlock",
							"spacing": "none",
							"isSubtle": true,
							"wrap": true,
							"text": "Comment: \"We need to make sure we have updated designs for our meeting on Monday.\""
						}
					]
				}
			]
		},
		{
			"type": "Container",
			"items": [
				{
					"type": "ColumnSet",
					"columns": [
						{
							"width": "32px"
						},
						{
							"width": "stretch",
							"items": [
								{
								}
							]
						}
					]
				}
			]
		}
	]
}
```

**Comment by shalinijoshi19** [comment]
Thanks @3GDXC we'll investigate and get back.

**Comment by mahathota** [comment]
I am also getting the same error. Any fix for this. Below is the Card Json.

{
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "text": "Edit Swap Out",
      "weight": "bolder"
    },
    {
      "type": "Container",
      "items": [
        {
          "type": "Container",
          "style": "emphasis",
          "items": [
            {
              "type": "ColumnSet",
              "columns": [
                {
                  "type": "Column",
                  "items": [
                    {
                      "type": "TextBlock",
                      "text": "**Package :** 163505004 - Package for Additionals",
                      "wrap": true
                    },
                    {
                      "type": "Container",
                      "items": [
                        {
                          "type": "ColumnSet",
                          "columns": [
                            {
                              "type": "Column",
                              "items": [
                                {
                                  "type": "Input.Toggle",
                                  "valueOn": "true",
                                  "valueOff": "false",
                                  "id": "Add163519006"
                                }
                              ],
                              "width": "auto"
                            },
                            {
                              "type": "Column",
                              "spacing": "Medium",
                              "items": [
                                {
                                  "type": "TextBlock",
                                  "text": "163519006 - WSKU AD Backup Disaster Recovery",
                                  "wrap": true
                                },
                                {
                                  "type": "Input.Number",
                                  "placeholder": "Quantity",
                                  "id": "163519006",
                                  "min": 1,
                                  "errorMessage": "Max Value should be 2"
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "type": "Container",
          "style": "emphasis",
          "items": [
            {
              "type": "ColumnSet",
              "columns": [
                {
                  "type": "Column",
                  "items": [
                    {
                      "type": "TextBlock",
                      "text": "**Package :** 163505005 - Microsoft Package",
                      "wrap": true
                    },
                    {
                      "type": "Container",
                      "items": [
                        {
                          "type": "ColumnSet",
                          "columns": [
                            {
                              "type": "Column",
                              "items": [
                                {
                                  "type": "Input.Toggle",
                                  "valueOn": "true",
                                  "valueOff": "false",
                                  "id": "Add163505006"
                                }
                              ],
                              "width": "auto"
                            },
                            {
                              "type": "Column",
                              "spacing": "Medium",
                              "items": [
                                {
                                  "type": "TextBlock",
                                  "text": "163505006 - WSKU AD Backup Disaster Recovery",
                                  "wrap": true
                                },
                                {
                                  "type": "Input.Number",
                                  "placeholder": "Quantity",
                                  "id": "163505006",
                                  "min": 1,
                                  "errorMessage": "Max Value should be 1"
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Update & Return to Summary",
      "style": "positive",
      "data": {
        "type": "messageBack",
        "action": "update"
      }
    },
    {
      "type": "Action.Submit",
      "title": "Cancel & Return to Summary",
      "style": "destructive",
      "data": {
        "action": "cancel"
      },
      "ignoreInputValidation": true
    }
  ]
}

**Comment by JeanRoca** [comment]
Closing this issue for now, please re-open if the problem persists.
