### ISSUE TITLE
[Designer] [C# output - alternative output]

### ISSUE THREAD

**Issue by LionelMaes** [microsoft/AdaptiveCards#3840]
It would be great if u could choose the output of your choice. Now there is only JSON but you can create adaptive card in C# and others so if you could design it in the designer and select the output. It would be a great feature

**Comment by dclaux** [comment]
Not an easy feature to implement (and especially maintain) but definitely interesting.

**Comment by paulcam206** [comment]
This is not currently on roadmap.
