### ISSUE TITLE
[Android][inconsistency android vs web] [Columns in a column set get pushed out of the card when width set to auto]

### ISSUE THREAD

**Issue by shbhadra** [microsoft/AdaptiveCards#3855]
# Platform
* Android

# Author or host
Host

# Version of SDK
1.2.6

# Details
For the attached card json.
The button in the column set is cutoff on android
![image](https://user-images.githubusercontent.com/51158485/76822755-046e0d80-6838-11ea-97fd-cffe5a09875e.png)

The same card on web
![image](https://user-images.githubusercontent.com/51158485/76822819-25366300-6838-11ea-9e0c-be7bebb0aeeb.png)

Note : On web, no matter how large the string in the first column becomes, the second column is never pushed out of the card completely (there is a sliver of the button in the second column as seen below). Whereas on android, it looks like the column did not even render.

Card with a lot of text in the first column as rendered on web
![image](https://user-images.githubusercontent.com/51158485/76823003-c1f90080-6838-11ea-93a3-a88abc726b9b.png)

P.S. : What is the expectation for the value "auto" for the column width (refer to the attached card). Is there in any documentation around the functioning of the value.

[widthAuto.json.zip](https://github.com/microsoft/AdaptiveCards/files/4341527/widthAuto.json.zip)

**Comment by VikrantSingh01** [comment]
@shalinijoshi19 , @almedina-ms : Pls. check.

**Comment by shalinijoshi19** [comment]
@nesalang can you update here please with follow up onhte internal thread and next steps? thanks

**Comment by VikrantSingh01** [comment]
@nesalang : Any update in this issue pls. CC - @shbhadra

**Comment by nesalang** [comment]
> P.S. : What is the expectation for the value "auto" for the column width (refer to the attached card). Is there in any documentation around the functioning of the value.
> 
> [widthAuto.json.zip](https://github.com/microsoft/AdaptiveCards/files/4341527/widthAuto.json.zip)

When there are at least two columns with "auto" width, each columns's width are calculated, and columns will get the proportional  amount when both of them cannot be satisfied.

**Comment by almedina-ms** [comment]
in the case of android,  an auto column gives liberty to the contents to use as much space as needed, if there is a long piece of text then it uses the whole parent space while the next columns get none. As can be seen below, this is the result from the different combinations

Column 1: Auto | Column 2: Auto
![image](https://user-images.githubusercontent.com/35784165/77370837-fb40dd00-6d1e-11ea-8582-e2cebcf31b1c.png)

Column 1: Auto | Column 2: Stretch
![image](https://user-images.githubusercontent.com/35784165/77370877-190e4200-6d1f-11ea-84e3-3c046adf8161.png)

Column 1: Stretch | Column 2: Auto
![image](https://user-images.githubusercontent.com/35784165/77370935-44912c80-6d1f-11ea-9a1e-754f4be16b24.png)

Column 1: Stretch | Column 2: Stretch
![image](https://user-images.githubusercontent.com/35784165/77370968-5a065680-6d1f-11ea-8b68-3cda67bfdf77.png)

**Comment by almedina-ms** [comment]
Also, at some point a more specific calculation as the one performed in Javascript was planned to be performed in UWP but I think we never actually developed it

**Comment by nesalang** [comment]
@shbhadra, we recommend using "stretch" on the column with "TextBlock", and "auto" on the column with the button in this case. "stretch" will make the TextBlock to adjust its width, and button to have its required width. In general, we don't recommend using more than one column with "auto" width since it will make all of the columns look bad if all of the columns cannot be fit in their superview without being compromised in their width.

**Comment by nesalang** [comment]
@shalinijoshi19 @almedina-ms  @nesalang  to close this issue, we need to update our scheme to better explain what "auto" and "stretch" do with sample json card.

**Comment by VikrantSingh01** [comment]
@shalinijoshi19 , @nesalang : It would be great if we have the same experience across the board for consistency where the same card payload work with all form factor.

**Comment by VikrantSingh01** [comment]
@shalinijoshi19 : Can we update the next steps here pls.  CC -  @anujb

**Comment by jwoo-msft** [comment]
1. it's not clear what's "auto" do in column.
2. swallowing up entire column is not desirable.
