### ISSUE TITLE
[Visual Studio][Schema] Schema Not Supported in Visual Studio

### ISSUE THREAD

**Issue by JoeMayo** [microsoft/AdaptiveCards#3856]
**What platform is your feature request related to? (Delete other platforms).**

* .NET HTML

**Is your feature request related to a problem? Please describe.**
When adding Adaptive Card JSON, as a *.json file, then editor shows the following Warning:

> The type of schema applied to the document is not supported

The VS JSON editor has a schema drop-down (at the top of the editor), but that doesn't include Adaptive Cards. More investigation indicates that those schemas can be configured via Tools | Options | Text Editor | JSON | Schema. That points to http://schemastore.org. Visiting schemastore.org, there isn't an entry for Adaptive Cards schemas.

Visual Studio also appears to have the ability to add another schema catalog via manual configuration.

**Describe the solution you'd like**
I'm not sure what the optimal solution is here, but it seems like adding the Adaptive Cards schema to the schemastore.org catalog might resolve the problem. This is a supported option and sounds like it might enable schema support for Adaptive Cards in Visual Studio out-of-the-box.

**Describe alternatives you've considered**
Alternatively, provide the URL to another catalog that does have the schema - though this doesn't sound optimal as a user would need to research and discover the need to do this in order to clear their warning. 

I've also seen where it's possible to add a schema to project files. However, this doesn't seem optimal as it would require developers to always add that file to every project they worked with for adaptive cards - also they would need to discover how this could be done, rather than just working with a normal VS installation.

**Additional context**
I'm building a chatbot with Microsoft Bot Framework in Visual Studio 2019. The adaptive cards I'm using were built with the Adaptive Cards Designer and I pasted the JSON into a *.json file in my Visual Studio project.

**Comment by paulcam206** [comment]
This is not currently on roadmap.
