### ISSUE TITLE
[Adaptive Schema] Ability to specify state of action buttons in Adaptive schema

### ISSUE THREAD

**Issue by pankajpalOlk** [microsoft/AdaptiveCards#3857]
The action buttons such as Action.OpenUrl, Action.Submit have a 'style' field in their schema and the supported values are:

- default
- positive
- destructive

[OpenUrl schema](https://adaptivecards.io/explorer/Action.OpenUrl.html)

Can we have a 'disabled' value appended to this existing list? The idea is to show the action button in disabled state to support some of the scenarios.
The requirement is from an actionable messages scenario (built using Adaptive Cards in outlook) and here is snapshot of the desired behaviour:

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/35917079/76953995-9c9dec80-6935-11ea-9dc5-5991c88c9464.png)

**Comment by dclaux** [comment]
I think it would probably be best to introduce another property, e.g. `isEnabled` that defaults to true, as a button can both have a specific style and be disabled.

**Comment by jpjpjp** [comment]
I will add a vote for this (and possibly extend it).   Has there ever been consideration of adding some type of `disableAfterFirstClick` type attribute to the Actions?   This would be extremely useful for polls where you only want one entry per user.

To further complicate things I can imagine a couple of flavors of this:
* `disableAfterFirstClickPerUser` - the button would become disabled only in the client only for the user who clicked it.  In environments where multiple users are viewing the same card it would still be active for the other users.
* `disableAfterFirstClick` - the button would become disabled for all users regardless of who clicked it.

It seems to me that application developers could do the latter themselves by updating the card after the first click (provided the `isEnabled` attribute is included in a future version of the schema`), but the per-user disablement would require some smarts in the client renderer to work.

**Comment by pankajpalOlk** [comment]
@dclaux can you confirm that the finalized key name here will be "isEnabled" : true|false ?

**Comment by dclaux** [comment]
@pankajpalOlk yes, there will be an `isEnabled` boolean property on all Action types. Please refer to this issue which we will use to track the feature and will include the spec: https://github.com/microsoft/AdaptiveCards/issues/4257

**Comment by shalinijoshi19** [comment]
Dup #4670
