### ISSUE TITLE
[MSTeams]Placeholder is not working in Input.Number

### ISSUE THREAD

**Issue by Chekrii** [microsoft/AdaptiveCards#3862]
# Platform
* .Net Core
* Botframework v4

# Host

* MsTeams

Hi All,

Placeholder property is not as expected in Input.Number.

Earlier is was showing the placeholder text but from past few days it is displaying "0" as default.

Please find the Json pf my adaptive card and Screenshot.

<img width="380" alt="Input Number" src="https://user-images.githubusercontent.com/49824279/77228415-518e0e80-6bad-11ea-919b-f292dab646a7.PNG">

Json:-
-------
{"type":"AdaptiveCard","version":"1.0","body":[{"type":"TextBlock","text":"Please enter the days","spacing":"Medium","height":"stretch","horizontalAlignment":"Left","size":"Medium","weight":"Bolder","color":"Accent"},{"type":"Input.Number","placeholder":"Number of days","id":"id"}],"minHeight":"69px","$schema":"http://adaptivecards.io/schemas/adaptive-card.json"}

Thanks for the Help.

**Comment by shalinijoshi19** [comment]
Thanks @Chekrii for reporting this. I will look into it. @dclaux any ideas on this- based on the description looks like this is Teams Desktop and JS renderer yes?

**Comment by Chekrii** [comment]
Hi All,
Any update on this.
Thanks.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4739
