### ISSUE TITLE
[MSTeams][iOS][Accessibility]No decimal point selector for Input.Number

### ISSUE THREAD

**Issue by chathudev** [microsoft/AdaptiveCards#3863]
# Platform

*  iOS
* MSTeams
* .Net Core
* Botframework v4

# Details

Decimal point selector for Input.Number is not available on MSTeams iOS App. This is available on Android.

![IMG_2139](https://user-images.githubusercontent.com/8149625/77242374-b2582e00-6c23-11ea-8936-e73404418a26.PNG)

**Comment by shalinijoshi19** [comment]
@nesalang could you help investigate this one please? Thanks!

**Comment by nesalang** [comment]
fixed via #3879
