### ISSUE TITLE
[Android][Inconsistency with web and iOS] [Invalid value for column width not defaulting to auto in Android]

### ISSUE THREAD

**Issue by shbhadra** [microsoft/AdaptiveCards#3864]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* Android
# Author or host
HOST
# Version of SDK
1.2.6
# Details
Consider the following json
`{
               "type":"AdaptiveCard",
               "version":"1.2",
               "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
               "body":[
                  {
                     "type":"ColumnSet",
                     "spacing":"none",
                     "columns":[
                        {
                           "type":"Column",
                           "items":[
                              {
                                 "type":"Image",
                                 "url":"https://www.sewausa.org/resources/Sewa%20USA%20Images/DIY%20Campaigns/profile-clipart-generic-user-12.png",
                                 "horizontalAlignment":"left",
                                 "size":"small",
                                 "style":"person"
                              }
                           ],
                           "horizontalAlignment":"left",
                           "width":"automatic",
                           "verticalContentAlignment":"center",
                           "separator":false
                        },
                        {
                           "type":"Column",
                           "verticalContentAlignment":"center",
                           "items":[
                              {
                                 "type":"TextBlock",
                                 "text":"Some text here",
                                 "weight":"Bolder"
                              },
                              {
                                 "type":"TextBlock",
                                 "text":" "
                              }
                           ]
                        },
                        {
                           "type":"Column",
                           "verticalContentAlignment":"center",
                           "items":[
                              {
                                 "type":"ActionSet",
                                 "actions":[
                                    {
                                       "type":"Action.Submit",
                                       "title":"Button description",
                                       "data":{
                                          "nwCommand":"ANYTIME_FEEDBACK_RECIPIENT_SELECTION",
                                          "wid":"2a37f8012406102d1ad61154601e02a1",
                                          "descriptor":"Logan Johnson"
                                       }
                                    }
                                 ]
                              }
                           ]
                        }
                     ]
                  }
               ]
            }`

Which defines the column width for one of the columns as "automatic". While this is not a valid value for the width parameter, the card renders fine on iOS and Web, however it doesn't render on android.

As rendered on iOS
![image](https://user-images.githubusercontent.com/51158485/77316388-5aa6e900-6d2f-11ea-8c3d-f904108007f9.png)

As rendered on Web
![image](https://user-images.githubusercontent.com/51158485/77316493-8a55f100-6d2f-11ea-80fe-faad1ea99e61.png)

The web visualizer shows the message - Invalid column width:automatic - defaulting to "auto"

However android doesn't render the card at all.

**Comment by shalinijoshi19** [comment]
@jwoo-msft / @almedina-ms This wasnt shipped as part of AdaptiveCards 1.2.8 - what's the current status on this?

**Comment by VikrantSingh01** [comment]
@jwoo-msft / @Shalini-MSFT : Pls. get this prioritised.
