### ISSUE TITLE
[Android][Adaptive card UI] [Action buttons jumps on top of adaptive card]

### ISSUE THREAD

**Issue by ranjanraviraj** [microsoft/AdaptiveCards#3869]
# Platform
* Android

# Ravi Ranjan

# io.adaptivecards:adaptivecards-android:1.2.7

# Details
a.	Adaptive cards have two buttons to the bottom of a card.
b.	The button appears at the bottom when it renders.
c.	Cards also have an image as an image URL. 
d.     Button suppose to be displayed at the bottom, but it jumps on top. 

Please see the attachment for adaptive card data and respective screenshot.
[action_botton_issue.txt](https://github.com/microsoft/AdaptiveCards/files/4373487/action_botton_issue.txt)
![adaptive_card](https://user-images.githubusercontent.com/55788218/77394442-680eb280-6dc5-11ea-85eb-980894d6397d.png)

**Comment by shalinijoshi19** [comment]
@almedina-ms would you be able to prioritize looking into this one please? Heads up that I'll be looping you in on a thread ongoing with the customer (JCI) as well.. Thanks

**Comment by shalinijoshi19** [comment]
This was fixed with #3363. Porting it over to 1.2 to include with the 1.2.8 patch.

**Comment by shalinijoshi19** [comment]
@ranjanraviraj , FYI that thisis now released. Closing this issue out. Thanks.
