### ISSUE TITLE
UWP "data" property on Action.Submit isn't accessible (data values not returned on action click)

### ISSUE THREAD

**Issue by anbare** [Microsoft/AdaptiveCards#387]
![image](https://cloud.githubusercontent.com/assets/13246069/26737453/0f652516-477f-11e7-9784-66f3ca1f3fd4.png)

There's no Data property on the AdaptiveSubmitAction. The event you get back for a button being clicked is called "Inputs", which would imply that it would NOT contain the Data key/value pairs (and today it does NOT).

Hence exposing the Data property on AdaptiveSubmitAction would allow the host to merge Inputs and Data into a single ValueSet. Plus having the property accessible could be useful for other reasons.

**Comment by anbare** [comment]
I might play around with adding the Data property to the object model if no one is currently working on this. Wanted to get toast activation in the Visualizer 100% wired up given that inputs are now returned :)

**Comment by matthidinger** [comment]
Go for it!
