### ISSUE TITLE
[Android][Adaptive card input data] [Adaptive cards form data doesn't persist once action has been taken]

### ISSUE THREAD

**Issue by ranjanraviraj** [microsoft/AdaptiveCards#3870]
# Platform
* Android

# Ravi Ranjan

# io.adaptivecards:adaptivecards-android:1.2.7

Issue
a.	When a user provides inputs to cards all data are seen whatever user has provided as input.
b.	As soon as a user submits an action button on that, a request is submitted to bot with all user input data.
c.	An issue is all user input data are wiped out.

**Comment by almedina-ms** [comment]
Hi @ranjanraviraj , is the card hosted in teams or in your own app? Do you have an application I can use to test this behaviour?

**Comment by shalinijoshi19** [comment]
@almedina-ms I'll be looping you in on a thread with the customer (JCI)  we have ongoing to get more details from them. Thanks !

**Comment by almedina-ms** [comment]
This issue has already been fixed, the card was being redrawn so the inputs were being rendered again

**Comment by jayarau** [comment]
Hi @almedina-ms , We also facing same issue. Data is getting wiped out once submit action taken on adaptive card. We are using below adaptive card related packages:
    "adaptivecards": "^1.2.6",
    "adaptivecards-fabric": "^1.1.1",
    "adaptivecards-templating": "^1.1.0",
We have used react adaptive cards. 
Reference link: https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-adaptivecards

Can you please look into it and let us know if issue is also fixed for react adaptive card packges.

**Comment by paulcam206** [comment]
@vivekvijayakrishnan / @IbrahimSulai - care to take a look here?

**Comment by IbrahimSulai** [comment]
Hi @almedina-ms,

Please use the package - [adaptivecards-reactnative](https://www.npmjs.com/package/adaptivecards-reactnative) instaead of adaptivecards.

Please let us know if any issues in the same.

@paulcam206
