### ISSUE TITLE
[Adaptive Card] Does Action.OpenUrl support a custom URL scheme?

### ISSUE THREAD

**Issue by JemmyWong** [microsoft/AdaptiveCards#3873]
[Your detailed feedback here]
Hi MSFT experts,

We want to use adaptive card **Action.OpenUrl** to open our custom URL(not http/https) to cross launch our app, does it possible? Since we found it doesn't work now.  

Thanks.

---
* URL: https://adaptivecards.io/explorer/Action.OpenUrl.html

**Comment by matthidinger** [comment]
Hi Jeremy, 

- which Host app are you using to render the cards? (Outlook, Teams, your own apps?) 
- Which platforms is it failing to run on? All or some? (Web, Android, iOS)

**Comment by JemmyWong** [comment]
Hi Matt,
I'm using MSFT Teams, it fails on macOS native app and Web, not test on iOS and Android.

Here is my code snippet:
```JSON
"actions": [
    {
        "type":"Action.OpenUrl",
        "title":"Make a Call",
        "url": "webextel://xxx@xxx.com"
    }
]
```
This scheme **webextel://** has registered in OS, it works in browsers (Chrome, Safari, FireFox).

**Comment by bence-nagy** [comment]
I see this is closed, but was this issue ever resolved?
I have the same problem on Win 10 using either the Teams web app or the Teams desktop app.
URLs with custom schemes simply do nothing. The same URLs when opened in any browser do work and open the appropriate applications.
