### ISSUE TITLE
Action.Openurl is not working 

### ISSUE THREAD

**Issue by olu1987** [microsoft/AdaptiveCards#3874]
Can't get the button to open up a url. Not in the designer, not in my app. Don't understand what is going wrong.

https://adaptivecards.io/explorer/Action.OpenUrl.html

**Comment by almedina-ms** [comment]
Hi @olu1987 ,  could you provide us with a little more detail on what platform are you working on?

I can't talk for all renderers but UWP, Android, iOS and .NET need you to implement the behaviour for actions, depending on the platform that implementation may differ a little bit.

**Comment by olu1987** [comment]
@almedina-ms - when I use the below json in your designer I get a but button that when clicked nothing happens. I would expect when I click it a tab opens on the browser to url specified (https://adaptivecards.io). Why is this not the case?

{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "text": "This card's action will open a URL"
    }
  ],
  "actions": [
    {
      "type": "Action.OpenUrl",
      "title": "Action.OpenUrl",
      "url": "https://adaptivecards.io"
    }
  ]
}

**Comment by nesalang** [comment]
@olu1987,  that is the expected behavior. once Adaptive Cards SDK is integrated to a host app. the host app has to provide handling of events such open url.
