### ISSUE TITLE
Can TextBlock elements be used within Factset?

### ISSUE THREAD

**Issue by olu1987** [microsoft/AdaptiveCards#3880]
I want to use TextBlock within Factset so that I can make the value attribute of a fact a Hyperlink i.e

{
      "type": "FactSet",
      "facts": [
        {
          "title": "Fact 1:",
          "value": {
            "type": "TextBlock",
            "text": "Check out [Adaptive Cards](http://adaptivecards.io)"
        }....

Is this possible or could it be added as a feature?

**Comment by nesalang** [comment]
@olu1987

This isn't a supported feature.

However, you can use markdown in `fact` to add hyperlink.

```json
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "FactSet",
            "facts": [
                {
                    "title": "Fact 1",
                    "value": "Check [Adaptive Cards](www.adaptivecards.io)"
                }                
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```

![image](https://user-images.githubusercontent.com/4112696/78063925-cdbee980-7345-11ea-9963-fc7fe0dded07.png)

**Comment by paulcam206** [comment]
This is not currently on our roadmap.
