### ISSUE TITLE
[MSTeams][Android/Ios] [Adaptive card input.choice set placeholder not getting displayed]

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [microsoft/AdaptiveCards#3885]
# Platform

What platform is your issue or question related to? (Delete other platforms).
- [x] Documentation
- [x] Android
- [x] iOS
- [x] UWP

# Author or host

MsTeams

# Details
I used the placeholder property of adaptive cards in the input.Choiceset schema of adaptive cards. I added the placeholder text for the input.Choiceset drop down. The placeholder text was displayed in the desktop teams but when i checked it for mobile teams(android/ios) the placeholder text was not displayed.

I then tried adding the value field to the placeholder and then tried to render it for both the platforms. The teams desktop i am getting **default placeholder** text displayed in card but this time in mobile(android/ios) teams the card displayed the first value from the drop down list. In both the cases i was not able to display the placeholder text in mobile(android/ios) teams. 

As well in desktop teams also i am getting the default text value **(Select an option)** even if give other placeholder values.

please find attachment for more details
[PlaceHolderIssueJson.txt](https://github.com/microsoft/AdaptiveCards/files/4395849/PlaceHolderIssueJson.txt)
![PlaceHolder_Desktop](https://user-images.githubusercontent.com/60354515/77798800-93c9bb00-7099-11ea-92ea-29c37ef3800e.PNG)
![PlaceHolderMobile](https://user-images.githubusercontent.com/60354515/77798810-99270580-7099-11ea-8539-b192a10a7d48.png)

I need a fix for this issue as it is creating a roadblock in my project. Please help.

**Comment by nesalang** [comment]
@Sujit-Gaikwad 
This is not an officially supported feature across the all the renders; we do have a road map for it, but at this point only JS renderer (desktop) supports it.

**Comment by shalinijoshi19** [comment]
@siduppal / @dclaux could you help with the Desktop aspect of this question (see description above): 

>>> As well in desktop teams also i am getting the default text value (Select an option) even if give other placeholder values.

**Comment by Sujit-Gaikwad** [comment]
any updates on this issue??

**Comment by Sujit-Gaikwad** [comment]
Any update on this

**Comment by shalinijoshi19** [comment]
@almedina-ms would the work around Input evolution address this behavior at all or were we saying PlaceHolders are not something the Accessibility team has been advocating for features and we should deprecate support for it? @dclaux for FYI also

**Comment by Sujit-Gaikwad** [comment]
Any progress / update on this issue??

**Comment by anbah34** [comment]
@shalinijoshi19 , @jwoo-msft Are there any timelines for this? This bug was part of the P0 bugs that I had earlier shared with the team

**Comment by Sujit-Gaikwad** [comment]
any updates on this??

**Comment by Gunashree-R-V** [comment]
@jwoo-msft, @shalinijoshi19, 
This issue applies to the **placeholder in input.choice set** component as per the title.
We have a similar issue([4484](https://github.com/microsoft/AdaptiveCards/issues/4484)) created for other input components as well.

Hope this bug([4484](https://github.com/microsoft/AdaptiveCards/issues/4484)) will also be addressed as part of the current fix.

cc: @VikrantSingh01, @anbah34, @shbhadra

**Comment by shalinijoshi19** [comment]
@Gunashree-R-V we have been re-evaluating guidance and support for placeholder elements and usage in card design over various discussion, esp due to bad Accessibility implications on the card design they may have- Are you able to leverage [labels](https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/input-validation#labels) that shipped with adaptivecards 1.3 earlier last month for these scenarios? Do you actually have a use case for placeholders in the card design here?
