### ISSUE TITLE
[MsTeams][Ios] [Adaptive card Gifs not working]

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [microsoft/AdaptiveCards#3886]
# Platform

* iOS

# Author or host

MsTeams

# Details

I want to use gifs(animated images) in adaptive cards in Msteams for ios device. It is working fine for windows desktop MsTeams and android mobile MsTeams but it is displaying as a still image on Ios mobile teams.The gif is not working and it is showing as a still image on ios device. PFA json file for my adaptive card.
[GifAdaptiveCardJson.txt](https://github.com/microsoft/AdaptiveCards/files/4396000/GifAdaptiveCardJson.txt)

I need a fix for this bug as it is creating a roadblock in my project. Please help.

**Comment by nesalang** [comment]
@Sujit-Gaikwad 
Unfortunately, gif is not officially supported feature.

**Comment by Sujit-Gaikwad** [comment]
Do we have any roadmap to support it on iOS device

**Comment by shalinijoshi19** [comment]
@Sujit-Gaikwad, we are working on fleshing out our roadmap in the backdrop of the pandemic situation and any new requests that we'll need to accomodate but for now please keep an eye out on 
 aka.ms/acroadmap for updates! @matthidinger / @dclaux : Here's a request for gif support in AC.

**Comment by anbah34** [comment]
@shalinijoshi19 , @jwoo-msft Can we please reopen this issue as a feature request. This is a parity issue as well as Gifs work on desktop and android

cc- @VikrantSingh01
