### ISSUE TITLE
[MsTeams][IOS] [Adaptive card image select action not working]

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [microsoft/AdaptiveCards#3888]
# Platform

* iOS

#  host

MsTeams

# Details

I wanted to display images which are clickable using adaptive cards select action property  in microsoft teams. I tried for desktop MsTeams and android mobile MsTeams and it worked fine the image clicks were working  and i was getting the expected result.
But on MsTeams for ios mobile the image clicks are not working. I used the select action property on images in adaptive card. I need a fix for this bug as it is creating a roadblock in my project.Please help.
PFA for json of my adaptive card.
[SampleJsonImageClick.txt](https://github.com/microsoft/AdaptiveCards/files/4396073/SampleJsonImageClick.txt)

**Comment by nesalang** [comment]
@Sujit-Gaikwad 
There is sometimes gap between what SDK (AdaptiveCards) offers, and what's actually being offered in host app (Teams).

Your use case is definitely supported in the SDK. 
<img width="348" alt="Screen Shot 2020-03-30 at 3 59 57 PM" src="https://user-images.githubusercontent.com/4112696/77969992-fbe9ee00-729f-11ea-9cf5-9c8cede63127.png">

This is what would look if visibility is set to true in the SDK.
<img width="335" alt="Screen Shot 2020-03-30 at 4 01 09 PM" src="https://user-images.githubusercontent.com/4112696/77970027-12904500-72a0-11ea-90aa-33ccc8baeea1.png">

We will communicate what you've found to the Teams.

Thank you.

**Comment by nesalang** [comment]
@Sujit-Gaikwad 
This is related to #3824 
Teams said that it will be fixed in April store release.

**Comment by Sujit-Gaikwad** [comment]
>>Teams said that it will be fixed in April store release.


is this release has given from your site
I'm still facing the same issue @shalinijoshi19  can you reopen this issue.

**Comment by Sujit-Gaikwad** [comment]
@shalinijoshi19, with V2.0.9 teams update this is working for iPhone 10 but with same update it is not working for iPhone 6
can you tell me for which all iPhone version it will support???
