### ISSUE TITLE
[Microsoft][MsTeams] [MS teams users conversation cache]

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [microsoft/AdaptiveCards#3889]
# Platform

* iOS

# Author or host
MsTeams

# Details

We have good amount of features talking to Graph API where in access token of users will be used to query them. Can you help for how much time MS teams users conversation cache will be retained and refreshed ?

**Comment by nesalang** [comment]
@nesalang 
forward the question to Teams.

**Comment by shalinijoshi19** [comment]
@siduppal / @Wajeed-msft This is for Teams please.

**Comment by Subhasish-msft** [comment]
> Can you help for how much time MS teams users conversation cache will be retained and refreshed ?

@Sujit-Gaikwad , Are you talking about the validity of access token and refresh token for calling graph API?

**Comment by Sujit-Gaikwad** [comment]
@Subhasish-msft It will helpful is if you give clarity  on below points :
1. validity of access token
2. will it automatically refreshed?
     a. if **yes** what will be validity after refresh
3. is there any way to know the token expiry before it get expired ?

**Comment by Subhasish-msft** [comment]
Here are the answers :
1. Access token expires in 60 mins
2. No, User must refresh them by providing the `refresh_token`.
   a. After refresh, a new access token will be granted with 60 mins validity. Azure allows an access-token to be refreshed using the `refresh_token` for a maximum period of time of 90 days
3. Not exactly any direct mechanism, but you can cache the last refreshed/granted time of access token to validate.

Please refer [Authentication with Azure AD](https://docs.microsoft.com/en-us/graph/auth-v2-user#authentication-and-authorization-steps).
