### ISSUE TITLE
[MsTeams][AdapiveCard] [Adaptive card Support for teams mobile]

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [microsoft/AdaptiveCards#3890]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android
* iOS

# Author or host

MsTeams

# Details

Hi all,

While developing bot on teams channel. We are facing some roadblocks with respect to teams support to adaptive card  for mobile (android + iOS ) which can be show stopper for us 
please check following list of bugs:

1.	For a better experience,we are using adaptive cards for the conversation dialogs. Looks like adaptive cards are not stable in all the platforms especially in IOS. **Can you help do we have any plan or road map for the adaptive cards to be working in all the platforms.** We have raised with engineering team to progress on it. 

https://github.com/microsoft/AdaptiveCards/issues/3799

Ex: button isVisible property works well in desktop, browser but not in android and IOS. Due to these limitations, bot app has to customize the feature device specific.

2. Some of the frequently used actions by a user is to be able to tag a person, upload files during the conversations. Can we have this core features as a part of adaptive cards ? Pain point or impact from the user experience point of view to be able to book meetings(with attendees), attaching references for raising issues.

3. **MS Teams App on mobile does not have support for attachments**. Can you help by when can we expect this feature ?
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-and-receive-files?tabs=dotnet

4. **Updating and Deleting activity in direct line channel**. As of now, this is supported in teams channel but not in a web chat. Due to this, bot app has to render new messages in the activity and channel will not be having clean history.
https://github.com/microsoft/BotFramework-WebChat/issues/2426

5. **Carousel taking time to load** on the conversation window of MS Teams 
https://github.com/microsoft/AdaptiveCards/issues/3824

6. **Scroll bars not visible on the task module and list card**. Users are able to scroll only using mouse scroll bar.

7. We have good amount of features talking to Graph API where in access token of users will be used to query them.  **Can you help for how much time MS teams users conversation cache will be retained and refreshed ?** 

8. **Show Card is not rendering properly** (Action.showcard not rendering on iOS devices)

9. **Adaptive card visibility false** is not supporting on mobile device 
we have raised  same concern in issue : https://github.com/microsoft/AdaptiveCards/issues/3884

10. **Image click is not support on mobile (iOS)** device. [ Image selection not working for iOS as well as  column set action.submit is also not working)

11. **Scroll options not working properly** (in case we have list of buttons)

12.	**Place holder value is not getting displayed in drop down**
same concern we have raised with team under bug id: (https://github.com/microsoft/AdaptiveCards/issues/3885)

13. **Animate images not getting rendered on mobile**
same concern we have raised with team under bug id: (https://github.com/microsoft/AdaptiveCards/issues/3886)

14.	slash(/) before  phone number is  not showing bullet in Desktop where as it is showing Slash(/) as it is in Mobile teams.

15.	**Teams app is getting crashed** while rendering adaptive card

Please help as soon as possible.
thanks.

@Sujit-Gaikwad, please see the inline updates.

**Comment by nesalang** [comment]
> # Platform
> What platform is your issue or question related to? (Delete other platforms).
> 
> * Android
> * iOS
> 
> # Author or host
> MsTeams
> 
> # Details
> Hi all,
> 
> While developing bot on teams channel. We are facing some roadblocks with respect to teams support to adaptive card for mobile (android + iOS ) which can be show stopper for us
> please check following list of bugs:
> 
> 1. For a better experience,we are using adaptive cards for the conversation dialogs. Looks like adaptive cards are not stable in all the platforms especially in IOS. **Can you help do we have any plan or road map for the adaptive cards to be working in all the platforms.** We have raised with engineering team to progress on it.
> 
> #3799
> 
> Ex: button isVisible property works well in desktop, browser but not in android and IOS. Due to these limitations, bot app has to customize the feature device specific.
> 
> 1. Some of the frequently used actions by a user is to be able to tag a person, upload files during the conversations. Can we have this core features as a part of adaptive cards ? Pain point or impact from the user experience point of view to be able to book meetings(with attendees), attaching references for raising issues.
> 2. **MS Teams App on mobile does not have support for attachments**. Can you help by when can we expect this feature ?
>    https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-and-receive-files?tabs=dotnet
> 3. **Updating and Deleting activity in direct line channel**. As of now, this is supported in teams channel but not in a web chat. Due to this, bot app has to render new messages in the activity and channel will not be having clean history.
>    [microsoft/BotFramework-WebChat#2426](https://github.com/microsoft/BotFramework-WebChat/issues/2426)
> 4. **Carousel taking time to load** on the conversation window of MS Teams
>    #3824
> 5. **Scroll bars not visible on the task module and list card**. Users are able to scroll only using mouse scroll bar.
> 6. We have good amount of features talking to Graph API where in access token of users will be used to query them.  **Can you help for how much time MS teams users conversation cache will be retained and refreshed ?**
> 7. **Show Card is not rendering properly** (Action.showcard not rendering on iOS devices)
> 8. **Adaptive card visibility false** is not supporting on mobile device
>    we have raised  same concern in issue : #3884
> 9. **Image click is not support on mobile (iOS)** device. [ Image selection not working for iOS as well as  column set action.submit is also not working)
> 10. **Scroll options not working properly** (in case we have list of buttons)
> 11. **Place holder value is not getting displayed in drop down**
>     same concern we have raised with team under bug id: (#3885)
> 12. **Animate images not getting rendered on mobile**
>     same concern we have raised with team under bug id: (#3886)
> 13. slash(/) before  phone number is  not showing bullet in Desktop where as it is showing Slash(/) as it is in Mobile teams.
> 14. **Teams app is getting crashed** while rendering adaptive card
> 
> Please help as soon as possible.
> thanks.

**Comment by nesalang** [comment]
@Sujit-Gaikwad, please see the inline updates.

1.	For a better experience,we are using adaptive cards for the conversation dialogs. Looks like adaptive cards are not stable in all the platforms especially in IOS. **Can you help do we have any plan or road map for the adaptive cards to be working in all the platforms.** We have raised with engineering team to progress on it. 

https://github.com/microsoft/AdaptiveCards/issues/3799
> This issue has been resolved in our end, it will be released by Teams
> work around is using ***** (5 *s) intead of *. It will make bold *

Ex: button isVisible property works well in desktop, browser but not in android and IOS. Due to these limitations, bot app has to customize the feature device specific.

2. Some of the frequently used actions by a user is to be able to tag a person, upload files during the conversations. Can we have this core features as a part of adaptive cards ? Pain point or impact from the user experience point of view to be able to book meetings(with attendees), attaching references for raising issues.

3. **MS Teams App on mobile does not have support for attachments**. Can you help by when can we expect this feature ?
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-and-receive-files?tabs=dotnet

4. **Updating and Deleting activity in direct line channel**. As of now, this is supported in teams channel but not in a web chat. Due to this, bot app has to render new messages in the activity and channel will not be having clean history.
https://github.com/microsoft/BotFramework-WebChat/issues/2426


5. **Carousel taking time to load** on the conversation window of MS Teams 
https://github.com/microsoft/AdaptiveCards/issues/3824
> please see the update on your github ssue

6. **Scroll bars not visible on the task module and list card**. Users are able to scroll only using mouse scroll bar.

7. We have good amount of features talking to Graph API where in access token of users will be used to query them.  **Can you help for how much time MS teams users conversation cache will be retained and refreshed ?** 
> please see the update on your github issue 

8. **Show Card is not rendering properly** (Action.showcard not rendering on iOS devices)
> can you create a separate issue for this with inlined cards payload?

9. **Adaptive card visibility false** is not supporting on mobile device 
we have raised  same concern in issue : https://github.com/microsoft/AdaptiveCards/issues/3884
> please see the update on your github issue 

10. **Image click is not support on mobile (iOS)** device. [ Image selection not working for iOS as well as  column set action.submit is also not working)
> please see the update on yoru github issue.
11. **Scroll options not working properly** (in case we have list of buttons)
> is this for desktop or mobile?

12.	**Place holder value is not getting displayed in drop down**
same concern we have raised with team under bug id: (https://github.com/microsoft/AdaptiveCards/issues/3885)
> please see the update on your github issue 

13. **Animate images not getting rendered on mobile**
same concern we have raised with team under bug id: (https://github.com/microsoft/AdaptiveCards/issues/3886)
> please see the update on your github issue 

14.	slash(/) before  phone number is  not showing bullet in Desktop where as it is showing Slash(/) as it is in Mobile teams.

15.	**Teams app is getting crashed** while rendering adaptive card
> it seems to be related to first issue. does the payload contains "*"  in "text"?

Please help as soon as possible.
thanks.

**Comment by shalinijoshi19** [comment]
@Sujit-Gaikwad thanks for filing this. Could you take a look at @nesalang's detailed response above and create separate issues for separate bugs you notice to make it easier to triage + Track? thanks again. For now, going ahead and closing this out.

**Comment by Sujit-Gaikwad** [comment]
> Scroll options not working properly (in case we have list of buttons)
> 
> 
> is this for desktop or mobile?


this issue is related to mobile teams
can you guide me on this ??

**Comment by prasannawatson** [comment]
Hi Support Team,

I am facing the problem while integration the adaptive card in the Webex Teams Integration.

Word is not wrapped when the word doesn’t come with a space character in the sentence. It wraps only when the sentence contains space. I have attached the example screen-shot here.
[desktop View](https://cxnext.blob.core.windows.net/prasanna/n.jpg)
 

In the Mobile View:
[Mobile View Screen-shot here](https://cxnext.blob.core.windows.net/prasanna/Screenshot_2020-09-25-17-43-07-105_com%20(1).png)
Same adaptive card looking fine in the mobile why I don’t know?

 


**Note:** I have used the “FactSet”  to create the UI look. In Microsoft adaptive card the FactSet itself comes with wrap: true in default.
Please refer the link to you will understand it. Even though I have using the correct code but it's not wrapping.

Please give me the correct solution to solve this problem ASAP.

**JSON:** I am using the below JSON.

            {
                "content": {
                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                    "body": [
                        {
                            "size": "Small",
                            "text": "Cisco Webex Experience Management",
                            "type": "TextBlock",
                            "weight": "Bolder",
                            "wrap": true
                        },
                        {
                            "type": "ColumnSet",
                            "columns": [
                                {
                                    "items": [
                                        {
                                            "size": "Small",
                                            "style": "Person",
                                            "type": "Image",
                                            "url": "https://cxnext.blob.core.windows.net/prasanna/WXM-PushNotification-Logo/teamswxm.jpg"
                                        }
                                    ],
                                    "type": "Column",
                                    "width": "auto"
                                },
                                {
                                    "items": [
                                        {
                                            "type": "TextBlock",
                                            "text": "New Notification: Webex Teams Bot Requests",
                                            "weight": "Bolder",
                                            "wrap": true
                                        },
                                        {
                                            "size": "Small",
                                            "type": "TextBlock",
                                            "text": "Created 9/25/2020 8:44:03 AM (UTC +0)",
                                            "weight": "Lighter",
                                            "wrap": true,
                                            "isSubtle": true,
                                            "spacing": "None"
                                        }
                                    ],
                                    "type": "Column",
                                    "width": "stretch"
                                }
                            ]
                        },
                        {
                            "type": "FactSet",
                            "facts": [
                                {
                                    "title": "Dummy Question for Notification Condition",
                                    "value": "5"
                                },
                                {
                                    "title": "Room Id",
                                    "value": "Y2lzY29zcGFyazovL3VzL1JPT00vNTMyMTNlNTAtZTQyMi0xMWVhLWJkZjAtODM4MjRkZGI1MzZh"
                                },
                                {
                                    "title": "Email",
                                    "value": "narskuma@cisco.com"
                                },
                                {
                                    "title": "Screen Size",
                                    "value": "Width: 1440px / Height: 728px"
                                },
                                {
                                    "title": "Token Id",
                                    "value": "WX-107588"
                                },
                                {
                                    "title": "Survey client version",
                                    "value": "Web Survey v18.4"
                                },
                                {
                                    "title": "Partial Response ID",
                                    "value": "10cb87d68d784190bc88a55adbe12516-WX-107588",
                                    "wrap": true
                                },
                                {
                                    "title": "Language",
                                    "value": "English"
                                },
                                {
                                    "title": "UserAgent",
                                    "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:80.0) Gecko/20100101 Firefox/80.0",
                                },
                                {
                                    "title": "Browser",
                                    "value": "Firefox"
                                },
                                {
                                    "title": "Browser Version",
                                    "value": "80"
                                },
                                {
                                    "title": "OS",
                                    "value": "Mac OS X"
                                },
                                {
                                    "title": "Device",
                                    "value": "Other"
                                }
                            ]
                        }
                    ],
                    "type": "AdaptiveCard",
                    "version": "1.0"
                },
                "contentType": "application/vnd.microsoft.card.adaptive"
            }
