### ISSUE TITLE
Python Templating Support

### ISSUE THREAD

**Issue by mohamedmansour** [microsoft/AdaptiveCards#3896]
Would be great to see templating come to a Python SDK so we can make use of the powerful features of templates like $data and functions

**Comment by wonboyn** [comment]
Has there been any movement on this?

**Comment by dkdndes** [comment]
Check out:
* https://github.com/CiscoSE/pyadaptivecards  (last updated 2 years ago)
* https://github.com/utsurius/django-actionable-messages (last update 17month ago, supports multiple card formats)
* https://github.com/huuhoa/adaptivecards (4 month old, and installable via pip3)

**Comment by paulcam206** [comment]
This is not currently on our roadmap.

**Comment by dionoid** [comment]
Check out:
- https://pypi.org/project/adaptive-cards-templating-py/
