### ISSUE TITLE
[MSTeams][Desktop]Input.Date today date is not visiblr

### ISSUE THREAD

**Issue by dchathu** [microsoft/AdaptiveCards#3899]
# Platform

* MSTeams
* Desktop

# Details

Today date is not visible in Input.Date on MSTeams Desktop app.

![input date](https://user-images.githubusercontent.com/8149625/78210509-0c7cad00-74c8-11ea-8df8-b1d9317878ea.png)

**Comment by shalinijoshi19** [comment]
@dclaux / @susanshen96 ideas on this one?

**Comment by Gousia-MSFT** [comment]
@chathudev Thanks for reaching out. This is a known issue. We have a bug on this.
