### ISSUE TITLE
[MsTeams][Mobile][iOS][Action.showcard button not getting displayed]

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [microsoft/AdaptiveCards#3903]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

MsTeams

#Details

HI Team,

I have trying to show two different form in adaptive card by using **action.Showcard** property

this worked fine on desktop and android device but when same thing I'm trying to get on iOS device it not get rendered.

in case of **android device** I'm getting card like  

![Showcard](https://user-images.githubusercontent.com/60354515/78473241-b2e0e080-775c-11ea-93b9-c6cf2cb1af28.png)

but In case of iOS device buttons are not getting displayed

please help me on this 

PFA sample adaptive card json  
[ActionShowcard.txt](https://github.com/microsoft/AdaptiveCards/files/4433478/ActionShowcard.txt)

same concern i have raised in issue https://github.com/microsoft/AdaptiveCards/issues/3890. 
As per @nesalang comment on issue raising this issue separately.

**Comment by shalinijoshi19** [comment]
Thanks for reporting this @Sujit-Gaikwad ... @nesalang can you help take a look please? Thanks!

**Comment by nesalang** [comment]
@Sujit-Gaikwad 

Hello,

Thanks for sharing the issue with us.
Can you share what version of iOS Teams app you are using?

@Aditya0603 
Hi Aditya,
Can you take a look at this issue?
On SDK side, this card works as below.
<img width="354" alt="Screen Shot 2020-04-06 at 10 11 56 AM" src="https://user-images.githubusercontent.com/4112696/78588550-b4111c80-77f3-11ea-9e2c-5f1eab49e3da.png">
<img width="347" alt="Screen Shot 2020-04-06 at 10 12 07 AM" src="https://user-images.githubusercontent.com/4112696/78588570-ba06fd80-77f3-11ea-8975-8066fd64c29b.png">
<img width="362" alt="Screen Shot 2020-04-06 at 10 12 16 AM" src="https://user-images.githubusercontent.com/4112696/78588592-c25f3880-77f3-11ea-8c2e-eb12b43ca21d.png">

**Comment by Sujit-Gaikwad** [comment]
@nesalang : this version of iOS and teams app we are using

**iphone 6**
version - 12.4.5
ms teams app version - 2.0.2

**ipad mini**
version - 12.4.5
ms teams app version -2.0.2

**Comment by jwoo-msft** [comment]
> @Sujit-Gaikwad
> 
> Hello,
> 
> Thanks for sharing the issue with us.
> Can you share what version of iOS Teams app you are using?
> 
> @Aditya0603
> Hi Aditya,
> Can you take a look at this issue?
> On SDK side, this card works as below.
> <img alt="Screen Shot 2020-04-06 at 10 11 56 AM" width="354" src="https://user-images.githubusercontent.com/4112696/78588550-b4111c80-77f3-11ea-9e2c-5f1eab49e3da.png">
> <img alt="Screen Shot 2020-04-06 at 10 12 07 AM" width="347" src="https://user-images.githubusercontent.com/4112696/78588570-ba06fd80-77f3-11ea-8975-8066fd64c29b.png">
> <img alt="Screen Shot 2020-04-06 at 10 12 16 AM" width="362" src="https://user-images.githubusercontent.com/4112696/78588592-c25f3880-77f3-11ea-8c2e-eb12b43ca21d.png">

@shalinijoshi19 can you help me forward this issue to Teams?

**Comment by jwoo-msft** [comment]
@shalinijoshi19 can you help me forward this issue to Teams?

**Comment by Sujit-Gaikwad** [comment]
any updated  on this??

**Comment by shalinijoshi19** [comment]
@vikrantsingh01 I think @jwoo-msft has a question here for your team?

**Comment by adumrewal** [comment]
This is working fine on the latest Teams iOS store build. @Sujit-Gaikwad please check it out.
<img src="https://user-images.githubusercontent.com/8917620/84761698-6c72f200-afe7-11ea-8942-d793469e8260.png" alt="drawing" width="250"/>

**Comment by Sujit-Gaikwad** [comment]
@adumrewal  Thanks for an update

**Comment by shalinijoshi19** [comment]
@adumrewal closing this out per @adumrewal's update above. Do reach out if you run into any other issues.
