### ISSUE TITLE
Adaptive Card and webhook connector (When?)

### ISSUE THREAD

**Issue by sgiulianiamius** [microsoft/AdaptiveCards#3907]
**What platform is your feature request related to? (Delete other platforms).**
Provide Adaptive card support to webhook connectors

**Is your feature request related to a problem? Please describe.**
We need webhook to support ActionCard(s). There are so many businesses that need them so badly.
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/35793883-adaptive-cards-webhooks?page=1&per_page=20

**Describe the solution you'd like**
I would like to be able to write Adaptive Cards and POST them to the right channel(s)

**Describe alternatives you've considered**
Changing chat system

**Additional context**
If you see the answer of Bill Bliss it says that it was planned already in 2018. 
https://stackoverflow.com/questions/50753072/microsoft-teams-webhook-generating-400-for-adaptive-card/50753413#50753413

Many companies have a chatbot infrastructure that is easily integrable with webhook-like solutions.  These companies would rather change chat systems than migrate everything towards bot-framework like solution, that is very peculiar

**Comment by menbren** [comment]
I can only say: YES YES YES, please fix this :)

**Comment by s3638844** [comment]
so why announce that it is compatible with Teams when it in truth isn't.... the ability to POST a JSON to the connector should have come BEFORE the bot framework.... especially since the messaging says to use adaptive cards for future projects..... Not everything needs a bot

**Comment by c3-florianbasier** [comment]
Hi, Do we have any ETA on this?
The list of capabilities compatible with Connectors (in particular, the lack of "mention" support) without AdaptiveCard is so low, my customer is not willing to move forward with Teams integration but is moving back to Slack instead.
Microsoft, you are losing customers for what should be an easy fix...

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4774
