### ISSUE TITLE
[iOS] Rendering of Flow adaptive card in Teams breaks if @mentions are used

### ISSUE THREAD

**Issue by vbvbvbv** [microsoft/AdaptiveCards#3915]
# Platform
* iOS

# Author or host
Teams for iOS (v 2.0.5 ring3_9) 

# Details
Using Flow "Post your own adaptive card as the Flow bot to a channel" with mentions breaks down formatting on Teams for iOS while absolutely fine in desktop version of Teams. Using sample JSON from this example of formatting: https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#sample-adaptive-card-with-a-mention

$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
Tried version 1.0 to 1.2.8

Without mentions, good sample rendering as expected:
![good](https://user-images.githubusercontent.com/63403252/79012677-c0cca200-7b5e-11ea-9620-6956f6fe6492.png)

With mentions, these issues:
![bad](https://user-images.githubusercontent.com/63403252/79012754-f4a7c780-7b5e-11ea-9499-e53a92a6dc5b.png)

Sorry in advance in this should go to Teams instead.

**Comment by shalinijoshi19** [comment]
Hey @VikrantSingh01 FYI this looks to be for Teams mobile.. Would you be able to take a quick look? Thanks.

**Comment by vbvbvbv** [comment]
@VikrantSingh01 i am msft internal, if it's easier to show issue directly, let me know if I can ping you in Teams.

**Comment by Nikitha-MSFT** [comment]
we could able to reproduce the issue. Raised a bug

**Comment by shalinijoshi19** [comment]
@Nikitha-MSFT / @vbvbvbv could you clarify if you've raised a separate issue for Teams Mobile ? If so, can we close this out?

**Comment by shalinijoshi19** [comment]
Moving out to @VikrantSingh01 as a Teams issue.
