### ISSUE TITLE
[MSTeams][Desktop/Mobile] [Scroll bar is not visible in list card]

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [microsoft/AdaptiveCards#3918]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML
* .NET WPF
* Android
* iOS

# Author or host

MsTeams

# Details

Hi All,

We are using list card (same as we are getting in Microsoft who bot). the card is getting rendered in teams  but **Scroll bars not visible in the list card.** Users are able to scroll only using mouse or even using button.

please guide me on same 

we have already raised this issue with Microsoft https://github.com/microsoft/AdaptiveCards/issues/3890  but as per @nesalang  comment raising issue separately for tracking purpose

**Comment by shalinijoshi19** [comment]
@jwoo-msft thoughts on this one? @Sujit-Gaikwad thanks for filing the issue separately.

**Comment by jwoo-msft** [comment]
@Sujit-Gaikwad 
As AdaptiveCards doesn't have list card, I presume this is a Teams' feature. Can you share your actual paylaod? if you can copy & paste directly to the comment section and wrap them with triple `, that will be great, and can you share an image that shows what is a expected behavior.
Thank you

**Comment by Sujit-Gaikwad** [comment]
Hi @jwoo-msft,

please find the card json and let me know if any issue 
[ListCard.txt](https://github.com/microsoft/AdaptiveCards/files/4503775/ListCard.txt)

**Comment by jwoo-msft** [comment]
> Hi @jwoo-msft,
> 
> please find the card json and let me know if any issue
> [ListCard.txt](https://github.com/microsoft/AdaptiveCards/files/4503775/ListCard.txt)

@Sujit-Gaikwad 
ListCard.txt is not a valid AdaptiveCards we support
```json
{
  "contentType": "application/vnd.microsoft.teams.card.list",
  "content": {
    "title": "These are the top 6 results I found for PersonName. Please pick one.",
    "items": [
      {
        "type": "person",
        "id": "PersonName.First@ABV.com",
        "title": "PersonName, First",
        "subtitle": "Head of Operations",
        "icon": "",
        "tap": {
          "type": "imBack",
          "value": "who is PersonName.First@ABV.com"
        }
      },
      {
        "type": "person",
        "id": "PersonName.Second@ABV.com",
        "title": "PersonName, Second",
        "subtitle": "Production Manager",
        "icon": "",
        "tap": {
          "type": "imBack",
          "value": "who is PersonName.Second@ABV.com"
        }
      },
      {
        "type": "person",
        "id": "PersonName.Third@ABV.com",
        "title": "PersonName, Third",
        "subtitle": "She Leader",
        "icon": "",
        "tap": {
          "type": "imBack",
          "value": "who is PersonName.Third@ABV.com"
        }
      },
      {
        "type": "person",
        "id": "PersonName.Fourth@ABV.com",
        "title": "PersonName, Fourth",
        "subtitle": "Marketing Assistant manager",
        "icon": "",
        "tap": {
          "type": "imBack",
          "value": "who is PersonName.Fourth@ABV.com"
        }
      },
      {
        "type": "person",
        "id": "PersonName.Fifth@ABV.com",
        "title": "PersonName, Fifth",
        "subtitle": "Marketing Services & Consumer Call Center Mgr",
        "icon": "",
        "tap": {
          "type": "imBack",
          "value": "who is PersonName.Fifth@ABV.com"
      },
      {
        "type": "person",
        "id": "PersonName.Sixth@ABV.com",
        "title": "PersonName, Sixth",
        "subtitle": "Services Mgr",
        "icon": "",
        "tap": {
          "type": "imBack",
          "value": "who is PersonName.Sixth@ABV.com"
      }

      }
]
}
}
```

**Comment by Sujit-Gaikwad** [comment]
@shalinijoshi19 any updated from teams on this

**Comment by anbah34** [comment]
Advised by mobile designers not to have a vertical scroll in Mobile for adaptive cards, so the user will have to scroll on the screen to view list embedded in the adaptive card rather than scrolling inside the card itself

**Comment by Sujit-Gaikwad** [comment]
>>@shalinijoshi19 Can you help me forward this issue to Teams?

@shalinijoshi19
is this issue forwarded to teams ???
if yes can you update on this

**Comment by Wajeed-msft** [comment]
@Sujit-Gaikwad - @anbah34  and @VikrantSingh01  are from MS Teams mobile team. This is by design.
Comment from Mobile Team:
> Advised by mobile designers not to have a vertical scroll in Mobile for adaptive cards, so the user will have to scroll on the screen to view list embedded in the adaptive card rather than scrolling inside the card itself

**Comment by Sujit-Gaikwad** [comment]
@Wajeed-msft  for desktop I'm getting list without scroll bar and I'm unable to scroll that without a mouse. there is a vertical scroll bar at all for desktop.


![WhoBottList_card1](https://user-images.githubusercontent.com/60354515/83096067-6661b380-a0c2-11ea-855b-3ff2f7b53e1a.PNG)

![WhoBottList_card2](https://user-images.githubusercontent.com/60354515/83096064-65308680-a0c2-11ea-8d68-c2e13b1954c9.PNG)

As you can see I got a list of user but no scroll bar available.

**Comment by Sujit-Gaikwad** [comment]
any updated on this?

**Comment by RebeccaAnne** [comment]
Please reactivate if this is still an issue for you.

**Comment by Niraj2021** [comment]
Can we fixed the scroll bar from header to footer only using adaptivecard?

**Comment by ChetanSharma-msft** [comment]
Hello @Niraj2021 - Sorry for delay in response.
We will check on it from our end and let you know the updates.

**Comment by Prasad-MSFT** [comment]
Hello @Niraj2021 - The Scroll bar is visible in the list card now.
Tested in `Microsoft Teams Version 1.5.00.35276`
![image](https://user-images.githubusercontent.com/62237649/208882352-dce363c5-5815-4933-8aa3-47203950aa2d.png)
