### ISSUE TITLE
'Cannot read property 'style' of null' when trying to navigate detail within explorer page

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/AdaptiveCards#392]
Say one navigates to Image card information:
http://adaptivecards.io/explorer/#Image
The page opens fine, so the link works. Now she tries to see details about `ImageStyle`:
http://adaptivecards.io/explorer/#imagestyle
The blank page renders. The reason:

```text
Uncaught TypeError: Cannot read property 'style' of null
    at showElement (explorer.js:225)
    at explorer.js:243
```
Thanks!
(Chrome/macOS)

**Comment by matthidinger** [comment]
Hi Peter, is this still occurring? Sorry I don't have a mac handy to test

**Comment by peterblazejewicz** [comment]
Yup:
```
explorer.js:225 Uncaught TypeError: Cannot read property 'style' of null
    at showElement (explorer.js:225)
    at explorer.js:243
```
The ui change is based on id tokens and query selector returns no match:
```
var element = document.getElementById(id + 'Content');
element.style.display = 'block';
```
(the id has `imagestyle` value here)

**Comment by matthidinger** [comment]
This should be all fixed up now :)
