### ISSUE TITLE
UWP Style and Layout default SubmitAction style is white on white.

### ISSUE THREAD

**Issue by DavidStrickland0** [microsoft/AdaptiveCards#3920]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Author or host

If host, please specify the corresponding host (app) name.
UWP

If you're an author, who are you sending cards to?
UWP 

# Version of SDK
AdaptiveCards.Rendering.Uwp 1.2.8

# Details
Have a Basic 1 page UWP App Im using the AdaptiveCardRenderer as follows:

```
public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
        }
        protected override void OnNavigatedTo(NavigationEventArgs e)
        {
            var renderer = new AdaptiveCardRenderer();
            renderer.OverrideStyles = Application.Current.Resources;
            var cardJson = "{\"type\": \"AdaptiveCard\", \"version\": \"1.0\", \"body\": [{\"type\": \"Image\",\"url\": \"http://adaptivecards.io/content/adaptive-card-50.png\"},{\"type\": \"TextBlock\",\"text\": \"Hello **Adaptive Cards!**\"}],\"actions\": [{\"type\": \"Action.OpenUrl\",\"title\": \"Learn more\",\"url\": \"http://adaptivecards.io\"},{\"type\": \"Action.OpenUrl\",\"title\": \"GitHub\",\"url\": \"http://github.com/Microsoft/AdaptiveCards\"}]}";
            var card = AdaptiveCard.FromJsonString(cardJson);
            var renderedAdaptiveCard = renderer.RenderAdaptiveCard(card.AdaptiveCard);
            if (renderedAdaptiveCard.FrameworkElement != null)
            {
                this.Content = renderedAdaptiveCard.FrameworkElement;
            }
        }
    }
```

If I run this no Action Button Displays
![image](https://user-images.githubusercontent.com/12382552/79136178-7c344700-7da8-11ea-991e-c88f3c9ad621.png)

If I change the cardJson so the Action Style is "positive" it displays. 
![image](https://user-images.githubusercontent.com/12382552/79136247-966e2500-7da8-11ea-8670-c92f0b2eaee9.png)

It appears the "default" style is white text on a white background.

**Comment by DavidStrickland0** [comment]
Repo Code
[AdaptiveCardDemo.zip](https://github.com/microsoft/AdaptiveCards/files/4470414/AdaptiveCardDemo.zip)

**Comment by DavidStrickland0** [comment]
As an addendum
`        <SolidColorBrush x:Key="Adaptive.Action.Positive.Button.Foreground" Color="#FFCB4040" />`
appears to alter the appearance of the Positive but
`        <SolidColorBrush x:Key="Adaptive.Action.Default.Button.Foreground" Color="#FFCB4040" />`
and
`        <SolidColorBrush x:Key="Adaptive.Action.Button.Foreground" Color="#FFCB4040" />`
seem to have no effect. Might just be doing it wrong but can't seem to get ahold of the button to set the color.

**Comment by shalinijoshi19** [comment]
Thanks a ton for reporting @DavidStrickland0 . @paulcam206 could you take alook at this please? Thanks!

**Comment by paulcam206** [comment]
I was looking at another issue in the vicinity of this one, but it looks like this one doesn't repro any more (or at least doesn't for me locally). 

@DavidStrickland0 -- are you still seeing problems here?

**Comment by DavidStrickland0** [comment]
The Code in the zip file I uploaded produces thew same result ... no button appears by default.
Comment out line 36 uncomment line 39 of MainPage.xaml.cs and button appears.

Even tried updating AdaptiveCards.Rendering.Uwp to 2.0 and updating UWP to 6.2.10
See attached
[AdaptiveCards.pdf](https://github.com/microsoft/AdaptiveCards/files/5053296/AdaptiveCards.pdf)

**Comment by RebeccaAnne** [comment]
Moving this into the current milestone as we're getting current reports of this being an issue.

**Comment by paulcam206** [comment]
@DavidStrickland0 - are you still seeing this?
