### ISSUE TITLE
Cannot use website card code (schema) editor on macOS

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/AdaptiveCards#393]
I cannot edit card schema using web page editor (macOS, any browser). In the sample below I'm trying to just change 'size' property value:
![online editor](https://cloud.githubusercontent.com/assets/14539/26802934/b2d91020-4a42-11e7-839a-b8a8699075af.gif)

Have read somehow related: https://github.com/Microsoft/AdaptiveCards/pull/366

macOS/any browser

**Comment by matthidinger** [comment]
Ah yep, this is because Consolas doesn't exist on macOS and the ace editor requires a monospace font. 

@dclaux I think this would be fixed by changing the editor style to

`font-family: Consolas, Monaco, monospace;`

**Comment by peterblazejewicz** [comment]
Edited tile to be specific :)

**Comment by matthidinger** [comment]
Hi @peterblazejewicz is this fixed now? Sorry I don't have a mac available to test

**Comment by peterblazejewicz** [comment]
@matthidinger No, unfortunately not (Chrome/Safari)

**Comment by matthidinger** [comment]
Hi @peterblazejewicz, really sorry about the delay here. This should be fixed now

**Comment by matthidinger** [comment]
Closing stale issue, please let us know if you encounter anything else!
