### ISSUE TITLE
[iOS][Incorrect height]

### ISSUE THREAD

**Issue by emelyanovkirill** [microsoft/AdaptiveCards#3935]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* iOS

# Author or host

Microsoft

# Version of SDK

CocoaPods, 1.2.7

# Details

When I add AdaptiveCard view in UITableView cell, cell height more than adaptive card height, an empty area in the middle of the cell.
Height is correct in 1.2.4 version, what I had before.

**Comment by jwoo-msft** [comment]
@emelyanovkirill 
If you follow [the self-sizing table view cell](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/AutolayoutPG/WorkingwithSelf-SizingTableViewCells.html), it should work for you.

**Comment by emelyanovkirill** [comment]
Yes, but v1.2.4 works correctly, but v1.2.7 is not :(
