### ISSUE TITLE
MicrosoftTeams ,Smileys created in MS Teams chatbot is not aligned per the users device

### ISSUE THREAD

**Issue by sonu-create** [microsoft/AdaptiveCards#3937]
Microsoft Teams Cards ,

I have created a chat bot in teams and have a adaptive card with three smiley icon and buttons to it. It displays well in a normal desktop teams app , but since we have given fixed width it does not work well when viewed from ios or android device.

so need your help here to know what changes to be done in below payloa d, so that the smiley and button is auto aligned per device size.

**Comment by shalinijoshi19** [comment]
@VikrantSingh01 / @jwoo-msft / @matthidinger thoughts on this one? This seems to be something we should also document btw..

**Comment by Trinetra-MSFT** [comment]
@shalinijoshi19 @sonu-create , Could you please more information on this issue payload or screenshot would be fine?

**Comment by Wajeed-msft** [comment]
@sonu-create - Please re-open with required information.
