### ISSUE TITLE
[MsTeams][Mobile/Desktop] [New feature support for adaptive card]

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [microsoft/AdaptiveCards#3938]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Desktop
* Android
* iOS

# Author or host
MsTeams

# Details

Some of the frequently used actions by a user is to be able to tag a person, upload files during the conversations. Can we have this core features as a part of adaptive cards ? Pain point or impact from the user experience point of view to be able to book meetings (with attendees), attaching references for raising IT or HR cases.

**Comment by shalinijoshi19** [comment]
Thanks @Sujit-Gaikwad ; We've now onboarded this request onto productboard. @matthidinger / @dclaux FYI.
