### ISSUE TITLE
[iOS][MSTeams][PowerAutomate] Adaptive card with subcard only returns data from subcard

### ISSUE THREAD

**Issue by bottekott** [microsoft/AdaptiveCards#3939]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* iOS

# Author or host
MSTeams

# Details
I'm building a flow in Power Automate with the action "Post an Adaptive Card to a Teams user and wait for a response" action.
The card has a main card, and a sub card. Both cards have input fields and submit actions. It works great everywhere except on iOS devices.

If i fill out the main card, and submit. iOS only returns data from the subcard.
Snippet of output from working platforms:
`  "submitActionId": "submitFood",
  "data": {
    "txtFood": "Salmon",
    "txtDrink": ""
  }`

Snippet of output from iOS devices:
`  "submitActionId": "submitFood",
  "data": {
    "txtDrink": ""
  }`

I've attached the adaptive card JSON
[FoodOrder.JSON.txt](https://github.com/microsoft/AdaptiveCards/files/4489502/FoodOrder.JSON.txt)

(this is obviously not the real adaptive card I'm working with, but the concept and structure is the same)

**Comment by shalinijoshi19** [comment]
@jwoo-msft could you help take a look at this one? Thanks

**Comment by jwoo-msft** [comment]
@bottekott Thanks for reporting this issue. I can reproduce the issue on my end. Meanwhile, try using actions instead of ActionSet for your use case.

**Comment by bottekott** [comment]
@jwoo-msft Thanks for the quick reply. My main source for learning adaptive cards have been playing around in the designer. Adding an ActionSet is the only graphical way to add actions there AFAIK.
It seems to work like expected when using actions. Thanks!

**Comment by shalinijoshi19** [comment]
@jwoo-msft can you ensure this lands in the release/1.2 branch as well as master.. thanks

**Comment by bottekott** [comment]
As a side note, with the original adaptive card i did not get any "dynamic content" in flow. This was also fixed when using actions instead of ActionSet.

**Comment by shalinijoshi19** [comment]
@jwoo-msft does this still need to be addressed for 1.2.9?

**Comment by shalinijoshi19** [comment]
@jwoo-msft bringing it to the top of your inbox. Thanks!
