### ISSUE TITLE
Web rendered card actions UI states differences

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/AdaptiveCards#394]
Could be issue with online editor only, but I've noticed different rendering of web version for action buttons. See sample record below:

![buttons](https://cloud.githubusercontent.com/assets/14539/26803200/9982fdb0-4a43-11e7-8ebc-a96ae10a35c0.gif)

edited:
this could be cards explorer web editor issue only. The visualizer renders UI states

Thanks!

**Comment by matthidinger** [comment]
This should be fixed now, please let me know if not
