### ISSUE TITLE
[Android][Inconsistency between desktop and android] [Cards containing facts with empty title do not render]

### ISSUE THREAD

**Issue by shbhadra** [microsoft/AdaptiveCards#3949]
# Platform

- [x] Android
- [x] iOS
- [x] JS
- [x] WPF
- [x] UWP
# Author or host
Host
# Version of SDK
1.2.6
# Details
Consider the following card json, which contains certain facts with empty and null titles.
`{
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "version": "1.0",
        "body": [
            {
                "type": "FactSet",
                "facts": [
                    {
                        "title": "",
                        "value": "Value 1"
                    },
                    {
                        "value": "Value 2"
                    },
                    {
                        "title": "Fact 3",
                        "value": "Value 3"
                    },
                    {
                        "title": "Fact 4",
                        "value": "Value 5"
                    }
                ]
            }
        ]
    }`

The same card as rendered on the web visualizer
![image](https://user-images.githubusercontent.com/51158485/79864396-07d85400-83f7-11ea-9747-06ad1c1c4673.png)

On the android visualizer however it doesn't render and the following error message is shown
"Property is required but was found empty: title"

**Comment by shalinijoshi19** [comment]
Thanks for reporting this @shbhadra. @almedina-ms can you take a look please? @paulcam206 / @jwoo-msft FYI (Inconsistencies)

**Comment by shalinijoshi19** [comment]
@jwoo-msft what's the plan for this one? ARe we able to land this in 20.09 still? I havent seen this move forward here?
