### ISSUE TITLE
Issue with action buttons with customer FireFox on macOS

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/AdaptiveCards#395]
The content (text) of action buttons when viewed with FireFox (customer edition) on macOS is just blank. I've noticed that when checking the fonts (the FireFox lists all fonts on the dev tools). The inner html of buttons are just empty:
For example on that page:
http://adaptivecards.io/samples/
![image](https://cloud.githubusercontent.com/assets/14539/26804630/ee071f60-4a48-11e7-9f8b-599f91d7c654.png)
The content in developer FF edition is fine (just like on any other browser)

**Comment by matthidinger** [comment]
Hm, @dclaux any idea here? I'll have to find a mac to repro

**Comment by peterblazejewicz** [comment]
This seems to be fixed. This could be a domain problem with font served (here you are using web fonts), or maybe specific font file was not available at that time. Thanks!
