### ISSUE TITLE
[iOS][TextRun] [Last character of TextRun does not honour defined style]

### ISSUE THREAD

**Issue by adumrewal** [microsoft/AdaptiveCards#3953]
# Platform

* iOS

# Author or host

Host- Teams iOS App

# Version of SDK

1.2.7

# Details

Defined style in TextRun field does not get applied on the last character.
PFA screenshot of the visualizer app and the card JSON.
<img src="https://user-images.githubusercontent.com/8917620/79973373-16854080-84b5-11ea-8720-95a338de22cc.png " alt="drawing" width="400"/>
Card JSON: [textRun.txt](https://github.com/microsoft/AdaptiveCards/files/4515605/textRun.txt)

**Comment by shalinijoshi19** [comment]
@jwoo-msft can you please take a look at what's going on with this one? Thanks!
