### ISSUE TITLE
[MsTeams][Mobile] [slash(\) before  phone number is  not getting ignored in card.]

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [microsoft/AdaptiveCards#3954]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android
* iOS

# Author or host

MsTeams

# Details

In the adaptive card that we are sending to the bot there is slash (\\) before  phone number that is getting ignored while we are rendering card in bot (Desktop channel) but in case of mobile device slash is not getting ignored while rendering.
 
Please check screenshot for clarity

please find adaptive card json attached

[AdaptivecardJson.txt](https://github.com/microsoft/AdaptiveCards/files/4522907/AdaptivecardJson.txt)

**Desktop card  view :**
![Desktop_Channel](https://user-images.githubusercontent.com/60354515/80107171-61c44f80-8598-11ea-99f0-fcf03c9b564e.png)

**Mobile card view :**
![Mobile_Channel](https://user-images.githubusercontent.com/60354515/80107210-6d177b00-8598-11ea-9e5c-1b9be0b7d844.jpg)

**Comment by shalinijoshi19** [comment]
@jwoo-msft / @almedina-ms could you guys check this out for iOS/ Android respectively please? Thanks!

**Comment by shalinijoshi19** [comment]
@jwoo-msft please take a first pass when you get a chance? Thanks!

**Comment by shalinijoshi19** [comment]
@dclaux thoughts please? Is "\" a special character here wrt phone numbers and how is JS special-casing it?

**Comment by shalinijoshi19** [comment]
@paulcam206 can you take a look real quick here and consider adding to your inconsistencies workstream? @jwoo-msft also for comment/fyi

**Comment by paulcam206** [comment]
looks like the desktop behavior here is correct:

```json
            {
              "type": "TextBlock",
              "text": "\\+91 (911) 1234567",
              "size": "Small",
              "wrap": true
            }
```

the `\\` bit means that a single backslash should be displayed

**Comment by Sujit-Gaikwad** [comment]
We are not getting single slash on desktop card.
It is getting displayed on android device.

**Comment by RebeccaAnne** [comment]
Please reactivate if this is still an issue for you.
