### ISSUE TITLE
[MSTeams][Duplicate records] [Azure Bot Service - Duplicate records from Adaptive card forms using Graph api]

### ISSUE THREAD

**Issue by vivekagrawal1110** [microsoft/AdaptiveCards#3956]
# Platform
* .NET Core Bot v4
* Microsoft Teams

# Version of SDK
.NET Core Bot v4

# Details
We are Using adaptive card to create ListItem in SharePoint site using MS Graph API. We are doing messageBack on Action.submit to send details filled by users to Bot. Sometimes Graph API take some extra few seconds to complete the request then we are getting the error on the card saying "Unable to reach app. Please try again." and two items created in SharePoint.

we don't want to show that error on the card. and want no duplication of item.

**Comment by shalinijoshi19** [comment]
@matthidinger, thoughts? Is this actually an AC issue?

**Comment by udaya-reddy** [comment]
Hi, 
Any update on this issue since April 2020 ? Was this addressed ?

**Comment by Mamatha-MSFT** [comment]
@vivekagrawal1110 - Could you please share the adaptive card code snippet. So the we can repro at our end.

**Comment by Mamatha-MSFT** [comment]
Hi @vivekagrawal1110 If your still facing the issue please share the adaptive card code snippet here.

**Comment by Mamatha-MSFT** [comment]
@vivekagrawal1110 - Before sending request query send a proactive message to the bot. Send another proactive message after request query got sent.  

https://github.com/microsoft/BotBuilder-Samples/blob/824b63a4e85d1ee615b3f793ea5c4c892aea60ae/samples/csharp_dotnetcore/16.proactive-messages/Controllers/NotifyController.cs#L36
