### ISSUE TITLE
[iOS][Theming] In iOS 13, native components reflect background color of OS-level theme

### ISSUE THREAD

**Issue by JohnnyKehr** [microsoft/AdaptiveCards#3961]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* iOS

# Author or host
Host on Webex Teams

# Version of SDK
AdaptiveCards@v1.2.6

# Details
On iOS 13, the `backgroundColor` of native components reflects the OS-level theme (light or dark) regardless of what's passed into the HostConfig. For most of these components, it can be overridden in a custom renderer, but the default color should align with the rest of the card (i.e. white or similar).  There are some components where this isn't changeable because they cannot be overridden with custom renderers (ACRPickerView and ACRCellForCompactMode are two examples where this can't be changed).  Since not all of these components are able to be overridden with custom renderers, this causes conflicts with our current app's theme.  

Example of what it looks like out of the box when the OS theme is set to **Dark** using [this](https://adaptivecards.io/samples/Inputs.html) template card: 
![file_D8932A6C-5C9D-440C-96E1-7AFD5DC624A4](https://user-images.githubusercontent.com/1463512/80402574-ef42c080-8872-11ea-91d7-22cf1b5d742d.jpg)

# Root Cause
I believe the reason for this is the use of `default` for the background colors.  There isn't much documentation around what `default` maps to, but I believe in iOS 13 it takes on the `systemBackground` value.  In `ACRChoiceSetViewDataSourceCompactStyle`, the backgrounds for each cell are also set to `groupTableViewBackgroundColor` which maps to `systemGroupedBackgroundColor ` in iOS 13. There may be other colors as well that I missed.

**Comment by shalinijoshi19** [comment]
Thanks for filing the detailed issue report @JohnnyKehr ! @jwoo-msft can you comment when you get a chance please? Thanks!

**Comment by jwoo-msft** [comment]
@JohnnyKehr 
I wished I could've responded sooner. I was super occupied with [Templating work](https://docs.microsoft.com/en-us/adaptive-cards/templating/) until now.

While I'm working on providing customization option through custom rendering, have you thought about using .xibs? You can customize ACRCellForCompactMode and ACRPickerView through ACRCellForCompactMode.xib and ACRPickerView.xib. More detail [here](https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/ios/native-styling)

**Comment by jwoo-msft** [comment]
You can access ACRPickerView, by casting the UIView that's returned from the render method of ACRInputDateRenderer, then the ACRPickerView is accessible through inputView accessor, e.g. ((ACRDateTextField *) view).inputView.

If you want to override choice set input's style, you have to override its delegate, and have the delegate to return a customized cell.

For example, 
```
UIView *view = [choiceSetRenderer render:viewGroup ...
UITableView *tableView = (UITableView *)view;
tableView.dataSource = customDataSource;
```
As for customData source, you can subclass ACRChoiceSetViewDataSourceCompactStyle class, and override - (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath method, and add your custom styling code to there.

**Comment by shalinijoshi19** [comment]
@jwoo-msft what is the work here on the SDK side and is that landing for 1.2.9? I'd rather include it in the next patch for now since I'd like to lock down the release/1.2 branch for this week soon.

**Comment by jwoo-msft** [comment]
closed as this is configurable from client's application.
