### ISSUE TITLE
AdaptiveCard rendering issue in Virtual Assistant : Error reading JArray from JsonReader. Current JsonReader item is not an array

### ISSUE THREAD

**Issue by Jashmi-1402** [microsoft/AdaptiveCards#3963]
# Platform

* .NET
* C#

# Author or host

NA

# Version of SDK
Microsoft.Bot.Solutions  :  Version=0.8.0-preview1
AdaptiveCards : Version 1.2.4
Microsoft.AspNetCore.Mvc.NewtonsoftJson : Version 3.1.0

# Details

We have migrated the VA to 0.8. Json rendering is fine but while clicking the adaptive card button I am getting the above error.

For rendering the card I have used the below code
var card = JsonConvert.DeserializeObject(ItemFinal.ToString());
card = AdaptiveCard.FromJson(ItemFinal.ToString()).Card;
var attachment = new Attachment(AdaptiveCard.ContentType, content: card);
return attachment;

In above code ItemFinal is an Json object.

**Comment by shalinijoshi19** [comment]
@Jashmi-1402 can you please include your card json please? Also what is the virtual assistant that you are referring to here? (@ckkashyap ideas what they are referring to here?) Thanks!

**Comment by Jashmi-1402** [comment]
Hi Shalini,

I have used the below json.

{\"type\":\"AdaptiveCard\",\"version\":\"1.0\",\"body\":[{\"type\":\"Container\",\"items\":[{\"type\":\"TextBlock\",\"text\":\"<heading>\",\"wrap\":true}]},{\"type\":\"Container\",\"items\":[{\"type\":\"ColumnSet\",\"columns\":[{\"type\":\"Column\",\"width\":\"stretch\",\"items\":[{\"type\":\"TextBlock\",\"text\":\"<Option1>\",\"horizontalAlignment\":\"Center\",\"weight\":\"Light\",\"separator\":true,\"color\":\"Accent\"}],\"id\":\"1\",\"selectAction\":{\"type\":\"Action.Submit\",\"title\":\"actionButton\",\"data\":\"{3}\"},\"horizontalAlignment\":\"Center\",\"style\":\"emphasis\"},{\"type\":\"Column\",\"width\":\"stretch\",\"separator\":true,\"items\":[{\"type\":\"TextBlock\",\"text\":\"<Option2>\",\"horizontalAlignment\":\"Center\",\"weight\":\"Light\",\"separator\":true,\"color\":\"Accent\"}],\"id\":\"2\",\"selectAction\":{\"type\":\"Action.Submit\",\"title\":\"actionButton\",\"data\":\"{4}\"},\"horizontalAlignment\":\"Center\",\"style\":\"emphasis\"}]}]}],\"$schema\":\"http://adaptivecards.io/schemas/adaptive-card.json\"}

for migrating the Virtual Assistant I have followed the below link.

https://microsoft.github.io/botframework-solutions/overview/whats-new/0.8-beta/migrate-existing-va-to-0.8/

**Comment by paulcam206** [comment]
Closing as this appears to be a BotFramework issue. If you're still seeing a problem, please file an issue in their [GitHub repo](https://github.com/Microsoft/botframework-sdk).
