### ISSUE TITLE
[JS][Template] [Repeating Elements With $When Doesn't Work]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#3970]
# Platform
* JavaScript

# Version of SDK
latest from ts/renderer-refactor

# Details
Trying [Template.ConditionalLayout.json](https://github.com/microsoft/AdaptiveCards/blob/jwoo/Template-visualizer-dotnet/samples/Templates/Elements/Template.ConditionalLayout.json)  should result in repeating elements with different TextBlock based on ```price``` in [Template.data.json](https://github.com/microsoft/AdaptiveCards/blob/jwoo/Template-visualizer-dotnet/samples/Templates/Elements/Template.data.json). Instead, same TextBlocks were appeared.
![image](https://user-images.githubusercontent.com/4112696/80744754-0502f080-8ad4-11ea-82e0-432756606b89.png)

**Comment by dclaux** [comment]
Cannot repro:
![image](https://user-images.githubusercontent.com/1334689/80745505-434cdf80-8ad5-11ea-869e-0f8279cd3f90.png)

**Comment by jwoo-msft** [comment]
wrong designer used.
