### ISSUE TITLE
[JS][Template] [Array Access Doesn't Work]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#3971]
# Platform

* JavaScript

# Version of SDK
latest from ts/renderer-refactor

# Details
Template used:  [Template.DataBinding.Inline.json](https://github.com/microsoft/AdaptiveCards/blob/jwoo/Template-visualizer-dotnet/samples/Templates/Elements/Template.DataBinding.Inline.json)
Template Data used: [Template.data.json](https://github.com/microsoft/AdaptiveCards/blob/jwoo/Template-visualizer-dotnet/samples/Templates/Elements/Template.data.json)
Expected: Andrew, Lei, Marry Anne
Actual:
![image](https://user-images.githubusercontent.com/4112696/80745382-15679b00-8ad5-11ea-9a23-cce9496a66e8.png)

**Comment by dclaux** [comment]
Cannot repro:
![image](https://user-images.githubusercontent.com/1334689/80745680-8444f400-8ad5-11ea-83ec-03afb61bfb10.png)

**Comment by jwoo-msft** [comment]
wrong designer used.
