### ISSUE TITLE
[JS][Template] [json instance created using AEL can't be used for setting data context]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#3972]
# Platform

* JavaScript

# Version of SDK
latest from ts/renderer-refactor

# Details
Template used:  [Template.Functions.DataManipulation.json](https://github.com/microsoft/AdaptiveCards/blob/jwoo/Template-visualizer-dotnet/samples/Templates/Elements/Template.Functions.DataManipulation.json)
Template Data used: [Template.data.json](https://github.com/microsoft/AdaptiveCards/blob/jwoo/Template-visualizer-dotnet/samples/Templates/Elements/Template.data.json)
Expected: data should be bound to the template.
Actual:
![image](https://user-images.githubusercontent.com/4112696/80747753-c1f74c00-8ad8-11ea-8c9d-ee58a3b1605d.png)

**Comment by dclaux** [comment]
Fixed here: https://github.com/microsoft/AdaptiveCards/pull/3508/commits/cd68f45cf2a8fdbe56b18da9b5c24b53c2543d7b
