### ISSUE TITLE
[JS][Template] [Data Binding Issue]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#3974]
# Platform

* JavaScript

# Version of SDK
latest from ts/renderer-refactor

# Details
Template used:  [Template.Keywords.json](https://github.com/microsoft/AdaptiveCards/blob/jwoo/Template-visualizer-dotnet/samples/Templates/Elements/Template.Keywords.json)
Template Data used: [Template.data.json](https://github.com/microsoft/AdaptiveCards/blob/jwoo/Template-visualizer-dotnet/samples/Templates/Elements/Template.data.json)
Expected: Thomas
Actual: \<name is undefined\>
![image](https://user-images.githubusercontent.com/4112696/80749927-10f2b080-8adc-11ea-8eb6-c084e873b096.png)

**Comment by shalinijoshi19** [comment]
@dclaux FYI. this was the 3rd bug bash bug from yestrday.
