### ISSUE TITLE
[WPF][AEL]Price is not rendered in Template.ConditionalLayout.json

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#3975]
# Platform
* .NET WPF

# Version of SDK
AEL preview

# Details

When running the card [Template.ConditionalLayout.json](https://github.com/microsoft/AdaptiveCards/blob/jwoo/Template-visualizer-dotnet/samples/Templates/Elements/Template.ConditionalLayout.json) the prices are not visible

The data used is in [here](https://github.com/microsoft/AdaptiveCards/blob/jwoo/Template-visualizer-dotnet/samples/Templates/Elements/Template.data.json)

![image](https://user-images.githubusercontent.com/35784165/80752827-11da1100-8ae1-11ea-80d6-9c5c95e18a39.png)

**Comment by jwoo-msft** [comment]
I don't think you are on the latest of the branch.

**Comment by almedina-ms** [comment]
you're right, I hadn't made the pull
