### ISSUE TITLE
[Ios] [Adaptive Cards Input Toggle(CheckBox) display issue in Iphone]

### ISSUE THREAD

**Issue by MonoGO** [microsoft/AdaptiveCards#3978]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Ms Teams

# Details

We have created bot using Microsoft bot-framework which is integrated to Microsoft teams. We have created few adaptive cards for interactive conversation with bot. One of the Adaptive card is causing design issue in IPhone X Microsoft Teams Application.

We used Adaptive card template for building this card which displays the list of Tasks along with status of the task. Each task has Input.Toggle (Checkbox) and at the end a button will be displayed. When Checkbox's are selected and button is clicked. Sample design as shown [Adaptive Card Design Preview](https://i.stack.imgur.com/CQ1tp.png)

We are sending new card with task details where they can edit the status and so on. Please find the JSON data below.

Card Payload Editor Json Data:
[Card Payload.txt](https://github.com/microsoft/AdaptiveCards/files/4572961/Card.Payload.txt)

Sample Data Editor:
[Sample Data.txt](https://github.com/microsoft/AdaptiveCards/files/4572965/Sample.Data.txt)

The InputToggle is inside the column set with **width** as **auto** and it is perfectly rendering in [Microsoft Teams Desktop](https://i.stack.imgur.com/3ahYn.png) and  [ Android App ](https://i.stack.imgur.com/Opo9i.jpg) but whereas in [IOS app](https://i.stack.imgur.com/S9MLP.png) it is not showing.

When we set the **width** property to **stretch**, InputToggle is getting displayed in [IOS App](https://i.stack.imgur.com/hHGaH.png) in big size but in [Desktop App](https://i.stack.imgur.com/ojihc.png) and [Android App](https://i.stack.imgur.com/VvSxF.png) the column is pushing and occupying much space. 

Please help me so that we can display the Input.Toggle in IOS Microsoft Teams without breaking the design in Desktop and Android Teams App.

Adding final JSON sent to the bot. The columns in the column set will be changed dynamically based on the ask list in database.

[Final Json.txt](https://github.com/microsoft/AdaptiveCards/files/4572957/Final.Json.txt)

Thank you.

**Comment by Gousia-MSFT** [comment]
@MonoGO Thanks for reporting this! We could repro the issue and we have raised a bug for it.

**Comment by shalinijoshi19** [comment]
@MonoGO what templating library are you using here and how are you rendering on iOS? FYI that we are in the middle of reworking our templating packages for JS + .NET and releasing an update within the next few weeks so do watch the [releases page](https://github.com/microsoft/AdaptiveCards/releases) for that. Meanwhile @jwoo-msft yet another test card for us to test out with the templating packages albeit .NET.

**Comment by MonoGO** [comment]
@shalinijoshi19 thanks for the reply. We are building JSON using Adaptive templating service and sending/receiving messages via REST api .
The adaptive card is getting rendered in the IOS Teams mobile app.

**Comment by shalinijoshi19** [comment]
@VikrantSingh01 are you aware of this issue with Input.Toggle on iOS? @jwoo-msft thoughts here?
