### ISSUE TITLE
[.Net][HTML] [Doesn't display AdaptiveNumberInput Initial value]

### ISSUE THREAD

**Issue by arman-g** [microsoft/AdaptiveCards#3991]
# Platform

* .NET HTML

# Version of SDK

NuGet 1.2.4

# Details

I am not able to set the initial value of an `AdaptiveNumberInput` field. When I set its Value field to a number it will not be shown in the input box for Bot Framework Emulator and WebChat (see the image below). The JSON does have the value but it is not rendered. `AdaptiveTextInput` does not have this problem.
I do remember this issue existed in the Adaptive designer too prior to the latest release 1.2.9. The issue does not exist in the designer anymore but it still exist at least in emulator and WebChat in .Net.

![83581451-b0e49500-a4f3-11ea-9fbc-343c3af3e06f](https://user-images.githubusercontent.com/22778273/86210318-3fffbf80-bb29-11ea-8004-3767a481e323.png)

**Comment by shalinijoshi19** [comment]
Hello @arman-g FYI that we are in the process of rolling out our new templating package offering for .NET in a few weeks. Please watch out our [releases page](https://github.com/microsoft/AdaptiveCards/releases) for updates. Meanwhile @jwoo-msft yet another sample card/scenario here for you to validate works with the new package please. Thanks.

**Comment by jwoo-msft** [comment]
same as #3977 
This issue doesn't seem to apply to [.Net Template SDK](https://www.nuget.org/packages/AdaptiveCards.Templating/0.1.0-alpha1).
cc @shalinijoshi19

**Comment by arman-g** [comment]
> same as #3977
> This issue doesn't seem to apply to [.Net Template SDK](https://www.nuget.org/packages/AdaptiveCards.Templating/0.1.0-alpha1).
> cc @shalinijoshi19

I am using NuGet 1.2.4 in C# .Net Core 3.1 project. I am not sure if I completely understand your input. Are you saying you can't preproduce these two issues with the current template?

**Comment by shalinijoshi19** [comment]
@arman-g can you share your sample json content please?

**Comment by arman-g** [comment]
@jwoo-msft sure
```
{{
  "type": "AdaptiveCard",
  "version": "1.2",
  "speak": "I can look up your juror ID if you give me a little more information. It may take me a few moments to search our files. I appreciate your patience.",
  "body": [
    {
      "type": "Container",
      "items": [
        {
          "type": "ColumnSet",
          "columns": [
            {
              "type": "Column",
              "width": "auto",
              "items": [
                {
                  "type": "Image",
                  "url": "http://localhost:3978/jurybot/_bot.png",
                  "width": "40px",
                  "height": "40px"
                }
              ]
            },
            {
              "type": "Column",
              "width": "stretch",
              "items": [
                {
                  "type": "TextBlock",
                  "text": "I can look up your juror ID if you give me a little more information. It may take me a few moments to search our files. I appreciate your patience.",
                  "wrap": true
                }
              ],
              "verticalContentAlignment": "center"
            }
          ]
        }
      ],
      "style": "good",
      "bleed": true
    },
    {
      "type": "Container",
      "items": [
        {
          "type": "Container",
          "items": [
            {
              "type": "TextBlock",
              "text": "What is your Last Name?",
              "wrap": true
            },
            {
              "type": "Input.Text",
              "id": "LastName",
              "spacing": "small"
            }
          ]
        },
        {
          "type": "Container",
          "items": [
            {
              "type": "TextBlock",
              "text": "What is your home zip code?",
              "wrap": true
            },
            {
              "type": "Input.Number",
              "id": "ZipCode",
              "placeholder": "XXXXX",
              "value": 99999.0,
              "spacing": "small"
            }
          ]
        },
        {
          "type": "Container",
          "items": [
            {
              "type": "TextBlock",
              "text": "What is your birth month (MM)?",
              "wrap": true
            },
            {
              "type": "Input.Number",
              "id": "BirthMonth",
              "placeholder": "MM",
              "value": 3.0,
              "spacing": "small"
            }
          ]
        },
        {
          "type": "Container",
          "items": [
            {
              "type": "TextBlock",
              "text": "What is your birth year (YYYY)?",
              "wrap": true
            },
            {
              "type": "Input.Number",
              "id": "BirthYear",
              "placeholder": "YYYY",
              "value": 2000.0,
              "spacing": "small"
            }
          ]
        }
      ]
    },
    {
      "type": "Container",
      "items": []
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "data": {
        "actionText": "Submit",
        "actionId": "Submit",
        "cardType": "lasc.services.jurybot.AdaptiveCards.RecoverLoginCard, lasc.services.jurybot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
        "modelType": "lasc.services.jurybot.AdaptiveCards.Models.RecoverCardModel, lasc.services.jurybot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
      },
      "title": "Submit"
    }
  ]
}}
```

**Comment by jwoo-msft** [comment]
@arman-g 
You mentioned that this is .Net Templating issue. What we are sayin is that this is not templating issue.
Please see about [Templating](https://docs.microsoft.com/en-us/adaptive-cards/templating/).

**Comment by arman-g** [comment]
@jwoo-msft Hi, you are right it is not a templating issue. I am not sure under what category this bug should go. Can you please change the category where it belongs to and set it as an open issue since this is still an issue.

**Comment by arman-g** [comment]
Was this fixed? I don't see the issue in the [Adaptive Cards Designer](https://adaptivecards.io/designer/) now. What version is Adaptive Cards Designer running?

**Comment by jwoo-msft** [comment]
@arman-g sorry for the late response. we're working on the fix. I will get back to you.

**Comment by shalinijoshi19** [comment]
@arman-g the designer doesn't work against the .NET HTML library but the JS renderer NPM package directly. @jwoo-msft then this is not a dup of #3977 correct?

**Comment by arman-g** [comment]
> @arman-g the designer doesn't work against the .NET HTML library but the JS renderer NPM package directly. @jwoo-msft then this is not a dup of #3977 correct?

No it's not.

**Comment by jwoo-msft** [comment]
> @arman-g the designer doesn't work against the .NET HTML library but the JS renderer NPM package directly. @jwoo-msft then this is not a dup of #3977 correct?

Yes, you're correct. the title is changed to [HTML] from [Templating], I mentioned #3977 because as in #3977, this issue had Templating as sub category which is wrong.

**Comment by arman-g** [comment]
@shalinijoshi19 #4091 is the dup of this.

**Comment by arman-g** [comment]
Is this bug ever going to be fixed? Any updates?

**Comment by paulcam206** [comment]
Hello @arman-g, I'm unable to reproduce this issue using the current .NET HTML renderer:

steps to repro:
* write test card to `some\location\repro.json`
* `cd source\dotnet\Samples\AdaptiveCards.Sample.Html`
* `dotnet run some\location\repro.json -- -i -o tmp.html`
* `tmp.html` contains .NET HTML rendered result

![image](https://user-images.githubusercontent.com/16614499/107254416-25a99080-69ec-11eb-9f0c-b9f224881e48.png)

If you're still seeing this behavior in WebChat, it's possible that this is an issue specific to WebChat.

For reference, here's where we set initial values for `Input.Number` elements in the .NET HTML renderer:
https://github.com/microsoft/AdaptiveCards/blob/b35e9961fb0bf3b7d29c9182470ec3684af7ea0a/source/dotnet/Library/AdaptiveCards.Rendering.Html/AdaptiveCardRenderer.cs#L1685-L1688

**Comment by arman-g** [comment]
Hi @paulcam2065, yes did fork the AdaptiveCards project and set a unit test for zip code and it passes. The AdaptiveCardRenderer works as expected. This issue I have is shown in Emulator and WebChat. Are you saying it is on their side?

![IMG2](https://user-images.githubusercontent.com/22778273/107256688-a79ab900-69ee-11eb-9ec1-86a5608c0b60.png)

**Comment by paulcam206** [comment]
It does indeed look like this was an integration issue between us and Bot Framework: https://github.com/microsoft/BotFramework-WebChat/issues/3111. However, they've since picked up the newer version of our package and this should theoretically no longer repro as of August. Perhaps @corinagum might have more context?

**Comment by corinagum** [comment]
Web Chat has bumped Adaptive Cards to 2.x, and is available in our daily builds. Support for 1.3 schema on the DirectLine service is still in progress. Testing out our dailies may fix some previously buggy behaviors like this one, but schema 1.3 cards still won't be passed along by DL. Our next release date is scheduled for March 8.

**Comment by arman-g** [comment]
@paulcam206 and @corinagum thanks guys. So with WebChat R12 this issue should be resolved, great!

**Comment by paulcam206** [comment]
@arman-g - sorry for the delay in having this issue resolved. Please feel free to reactivate this issue (or file a new one) if you encounter problems after WebChat R12 is available.
