### ISSUE TITLE
[MsTeams][Desktop/Mobile] [Input box and drop down box style not similar across all platform]

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [microsoft/AdaptiveCards#3993]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android
* iOS
* JavaScript

# Author or host

MsTeams

# Details

HI ,

As we notice that we are getting different style of input box across different platform

**For Desktop:**
Input box style is rounded corner and with gray color 
Drop down style is similar to input box style

![Screenshot (8)](https://user-images.githubusercontent.com/60354515/81319512-66ffbf00-90ad-11ea-8a6b-388942043570.png)

**For Android:**
Input box style is rectangular with border and no gray color 
![Android](https://user-images.githubusercontent.com/60354515/81320807-649e6480-90af-11ea-838b-ca5ec4921071.png)

**For Iphone:**
Input box style is underline with no border and no gray color 

![Iphone](https://user-images.githubusercontent.com/60354515/81320910-85ff5080-90af-11ea-9237-736f2798d640.png)

Can it be similar across all platform like desktop???

**Comment by shalinijoshi19** [comment]
@paulcam206 / @jwoo-msft an inconsistency issue here to tackle in our Inconsistencies work stream. Comments here?

**Comment by shalinijoshi19** [comment]
@almedina-ms also for thoughts on Android here..

**Comment by Sujit-Gaikwad** [comment]
Any update on this??

**Comment by Sujit-Gaikwad** [comment]
hey there any updates on  this??

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4665
