### ISSUE TITLE
[MsTeams][Mobile/Desktop][AdaptiveCard] UI Elements styles are different across the render

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [microsoft/AdaptiveCards#3994]
**What platform is your feature request related to? (Delete other platforms).**

* Android
* iOS
* JavaScript

**Is your feature request related to a problem? Please describe.**
https://github.com/microsoft/AdaptiveCards/issues/3993

**Describe the solution you'd like**
As i have described in bug we have different style for input box across all renders so my suggestion for this issue can we have styling property for such element like user can make it rounded corner or rectangular box with border 

It will be up to user which style he want to user while design there card and UI look similar across all renders

**Comment by paulcam206** [comment]
This is not currently on our roadmap.
