### ISSUE TITLE
.NET ASP.net "Only Show When" functionality in designer does not match Teams App

### ISSUE THREAD

**Issue by raheemdaya** [microsoft/AdaptiveCards#3995]
.NET ASP.net

What platform is your issue or question related to? (Delete other platforms).

#Platform
.NET Core ASP.net

# Author or host
MS Teams

# Version of SDK
0.1.0-alpha1

# Details

I have a card that works perfectly in the designer but fails to render correctly within Teams.  There are two components, RV_{RuleId} and a RichTextBlock before it that have a conditional set for visibility, {HasVars == 1}.  These two components fail to render in Teams but work fine in the Designer. I have attached Rules.txt with the card and data.txt with the data.
[Rules.txt](https://github.com/microsoft/AdaptiveCards/files/4596024/Rules.txt)
[data.txt](https://github.com/microsoft/AdaptiveCards/files/4596026/data.txt)

**Comment by shalinijoshi19** [comment]
Hello @raheemdaya are you using our templating SDK for .NET? If so, please know that we are in the process of finalizing a new version of our templating package for JS + .NET so please watch our [releases page](https://github.com/microsoft/releases) for updates. Meanwhile @jwoo-msft FYI - another sample card for testing the outbound package. Thanks
