### ISSUE TITLE
[MsTeams][IOS] [adapticard compactibility on iOS devices]

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [microsoft/AdaptiveCards#3996]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

MSTeams

# Details

Hi ,

https://github.com/microsoft/AdaptiveCards/issues/3799
https://github.com/microsoft/AdaptiveCards/issues/3824
https://github.com/microsoft/AdaptiveCards/issues/3888
 
these are few issue we have raised on git and now with teams store update v2.0.9 it is not occurring on iPhone 10 device **but still we are facing same issue on iPhone6** .

**can you please provide me data that which all iPhone and iOS version it will supported??**

 **is Adaptive card V1.2 is available for all iOS device ??**

**Comment by shalinijoshi19** [comment]
@jwoo-msft can you prioritize this next week once you are back in the office? Thanks!

**Comment by shalinijoshi19** [comment]
@jwoo-msft could you confirm if this is still an issue?

**Comment by jwoo-msft** [comment]
@Sujit-Gaikwad as per comments on #3824, it seems that Teams has fixed the issues. Could you confirm that the listed issues are fixed, and we can close this?

Thank you

**Comment by Sujit-Gaikwad** [comment]
@jwoo-msft , as per my obsevation it is working fine but some time the selection is not working randomaly for some iphone version below 8. we got some customer feedback on this can.
i can't tell you exact scinario but randomly some time it is creatig issue other than that it is working fine
>some time the selection is not working randomaly for some iphone version below 8. we got some customer feedback on this can.

if are able to provide a reason for this issue it will be better for me 

thanks  for support
regards,
sujit

**Comment by jwoo-msft** [comment]
> @jwoo-msft , as per my obsevation it is working fine but some time the selection is not working randomaly for some iphone version below 8. we got some customer feedback on this can.
> i can't tell you exact scinario but randomly some time it is creatig issue other than that it is working fine
> 
> > some time the selection is not working randomaly for some iphone version below 8. we got some customer feedback on this can.
> 
> if are able to provide a reason for this issue it will be better for me
> 
> thanks for support
> regards,
> sujit

@Sujit-Gaikwad 
thanks for your input. So do your and your customers' observations apply to all three issues, #3799, #3824, #3888?

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4664
