### ISSUE TITLE
[MS Teams Windows Desktop and Android Mobile Clients][Adaptive Cards/Channel URL Redirects] [Adaptive card inconsistent behavior across platforms on channel URL redirect]

### ISSUE THREAD

**Issue by ChristopherP1221** [microsoft/AdaptiveCards#3997]
# Platform
MS Teams

What platform is your issue or question related to? (Delete other platforms).
* Android
* maybe iOS?
* UWP

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? Author sending cards to a channel

# Version of SDK
Graph API v1.0 & beta

# Details
Links to channels where a user is not a member of the team behave differently on the Windows Desktop client than they do on the Android mobile client.  Further, the same links do not invoke the "join team" workflow when posted within an Adaptive card using the Action.OpenUrl action in a button.  When posting the URL directly, users are redirected to their default web browser  outside of the Windows Desktop client.  The expected behavior when a user clicks these links from any platform when the channel lives within a public team should be redirecting the users to the "join team" workflow OR simply add them automatically instead of making them click the button.  I'm looking for a workaround here.  Our use case is business critical and needs to be consistent.  If a user clicks the link, they should go directly to the channel.  This bug report is actually a re-post of what I reported here https://github.com/microsoft/AdaptiveCards/issues/3338.  Since issue 3338 is somewhat old, I wasn't sure it would get the level of visibility I am looking for.  Hoping you all can help out.  Oh, I also posted on StackOverflow to see if anyone else in the community can help out. 
 I'm also reporting this as a bug because the mobile app seemed to have been redirecting me to the "join team" workflow just two nights ago when we were doing some testing.  I'm not sure what changed but it's strange that it now tells me "you are no longer a member of this team."  Please let me know if I can provide any additional information!

**Comment by shalinijoshi19** [comment]
@ChristopherP1221 many thanks for reporting this afresh and apologies for the lack of follow up on #3338. @VikrantSingh01 / @siduppal would you be able to help a bit with firstpass on this one? I am not sure I understand how/why this is an AdaptiveCards issue or the end-end flow.. In the past I believe @matthidinger  has believed this to be an issue in Flow?

**Comment by dblyth-msft** [comment]
@shalinijoshi19 I expect this is a Teams client issue, not a Flow issue. The customer confirmed on the previous thread that the same behavior occurs when using Graph APIs directly to post a cards.

**Comment by Gousia-MSFT** [comment]
@ChristopherP1221 Could you please provide some screenshots capturing the difference in Desktop vs Mobile behaviour?
