### ISSUE TITLE
[Adaptive Card Templating][Adaptive card rendering issue if link has a space character]

### ISSUE THREAD

**Issue by ramya-ramanathan-28** [microsoft/AdaptiveCards#4002]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* JavaScript

# Author or host
Host - Microsoft Search

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...
Latest master

Explanation: 
- If a textblock is linked to a URL value that has space, the URL isn't formed correctly.
- For example, if the text of textblock is as follows: `[{Title}](http://{Projectname}.com)`
- If ProjectName is bound to a value with space (test url), 
![image](https://user-images.githubusercontent.com/37632003/81661594-f87a8280-9459-11ea-8858-cd16afb06d6c.png)
The link is not rendered properly and the adaptive card renders as above

**Comment by RamyaRamanathan28** [comment]
@dclaux Could you please take a look at this issue?

**Comment by shalinijoshi19** [comment]
Great find here @RamyaRamanathan28 ! @paulcam206 can you see if you can investigate to see if this is one of the known inconsistency issues you've been tracking at all? 
Btw, @RamyaRamanathan28 curious about your consumption model of our renderer on Search. Is there a reason you take a dependency on our source in master vs npm released packages?

**Comment by paulcam206** [comment]
#5853 is tracking markdown issues -- will track progress there.
