### ISSUE TITLE
[Adaptive Card Designer] [setting isSubtle to true is not adding the property to the Adaptive Card JSON ]

### ISSUE THREAD

**Issue by RamyaRamanathan28** [microsoft/AdaptiveCards#4003]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* JavaScript

# Author or host
Host - Microsoft Search

# Version of SDK
Latest master

# Details
Selecting the isSubtle checkbox in Element Properties makes no difference to the Adaptive Card JSON Payload as seen below. 

![image](https://user-images.githubusercontent.com/37632003/81662390-1e545700-945b-11ea-8f40-e1f6fda0ed05.png)

**Comment by RamyaRamanathan28** [comment]
@dclaux Please take a look at this bug

**Comment by shalinijoshi19** [comment]
@dclaux is this something that is now addressed as part of teh designer/renderer refactor ?

**Comment by RebeccaAnne** [comment]
This is fixed in the current version of the designer.
