### ISSUE TITLE
Designer no longer works for cards being rendered in Teams

### ISSUE THREAD

**Issue by raheemdaya** [microsoft/AdaptiveCards#4012]
# Platform

.Net Core Teams Bot

# Author or host

Teams

# Version of SDK

latest

# Details

The changes to the Designer have broken the ability to use it for Teams.  The additional $ signs have made the cards completely unusable when templating is used.  I have tried using the version selector at the top, I have tried taking the corresponding card and using it Teams.  I will be happy to try pretty much anything at this point.  That tool is critical for me and my team.

**Comment by shalinijoshi19** [comment]
@Matthidinger / @dclaux was this related inadvertently to the //build related website updates over the last couple of days?

**Comment by shalinijoshi19** [comment]
@raheemdaya apologies for this! We were working on a //BUILD conference recording internally, and inadvertently pushed changes up to the website without the corresponding templating package SDK updates. I believe this should now be addressed for you. Please do go ahead and reactivate if not. Thanks!

**Comment by raheemdaya** [comment]
@shalinijoshi19  I know this is already closed, but I really want to thank you and the team for the work you have done on this.  I know I probably came across as a little grumpy, but this tool has been vital to some of the things we are trying to accomplish.  Thank you again!
