### ISSUE TITLE
[Android][TextBlock] Font Weights are not consumed.

### ISSUE THREAD

**Issue by Gunashree-R-V** [microsoft/AdaptiveCards#4015]
# Platform

* Android

# Author or host

Host - Teams Android app

# Version of SDK

1.2.6

# Issue
 

- Host config has an option to control font weight by providing metrics to it(As mentioned in the public documentation: https://docs.microsoft.com/en-us/adaptive-cards/rendering-cards/host-config#fontweightsconfig).Updating these metrics remain unaffected on client. 

- Also, the TextBlock with fontWeight=“lighter” has Italic typeface. 
The issue is illustrated in the image below:

![image](https://user-images.githubusercontent.com/28745768/82041692-34b21b00-96c6-11ea-9739-9679274b25c7.png)

However, desktop has normal typeface with lesser fontWeight.

![image](https://user-images.githubusercontent.com/28745768/82041834-7216a880-96c6-11ea-824f-67d2ef04a93b.png)

Moreover it is found that each fontWeight property is mapped to Typeface as below on Android:
Lighter -> Italic
Default -> Normal
Bolder -> Bold.

On the other hand, iOS and Desktop consumes the values from hostConfig for each fontWeight and use that:

Also, attaching the relevant JSON.
[fontWeight.zip](https://github.com/microsoft/AdaptiveCards/files/4633852/fontWeight.zip)

cc: @VikrantSingh01.

**Comment by VikrantSingh01** [comment]
FYI - @anujb , @shalinijoshi19

**Comment by jwoo-msft** [comment]
@almedina-ms could you please give justification of why this feature can not be supported in Android?
