### ISSUE TITLE
[Android][Input.Choice] Spacing within Input.Choice sets not rendered.

### ISSUE THREAD

**Issue by Gunashree-R-V** [microsoft/AdaptiveCards#4016]
# Platform

* Android

# Author or host

Host - Teams Android app

# Version of SDK

1.2.6

# Issue
 
There is no spacing between the elements in a choice set for radio buttons. However upon setting “wrap”:true, the spacing shows up.
The issue is illustrated in the image below:

![image](https://user-images.githubusercontent.com/28745768/82042779-19480f80-96c8-11ea-94f4-8ca9ecdb825e.png)

Also, attaching the relevant JSON.
[InputChoice-RadioButton.zip](https://github.com/microsoft/AdaptiveCards/files/4633890/InputChoice-RadioButton.zip)

cc: @VikrantSingh01 .

**Comment by shalinijoshi19** [comment]
@almedina-ms would you be able to take a stab at looking at what's going on here real quick please? Thanks! @jwoo-msft FYI.
