### ISSUE TITLE
Teams update v2.0.10 in Mobile , does not allow users to click on any buttons

### ISSUE THREAD

**Issue by sonu-create** [microsoft/AdaptiveCards#4030]
I am using ios 13..4.1 version and teams app has updated recently in mobile . The chatbot which I had been intercating earlier, now If i try to click on any buttons, there is no action , it just selects the button as if we are doing copy paste cation and does not return the relevant output action on clicking buttons.

This has been faced with recent teams patch update.

**Comment by shalinijoshi19** [comment]
@VikrantSingh01 / @ojasvichoudhary ideas on this scenario? @jwoo-msft FYI.
