### ISSUE TITLE
[HTML][rendering] [video player icon clipped, not rendered correctly]

### ISSUE THREAD

**Issue by mindmodel** [microsoft/AdaptiveCards#4031]
# Platform
Back end: C#, .Net Core 2.1.  Microsoft Bot Framework 4.9.1 (NuGet packages).

Microsoft travel bot sample (back end). Microsoft web chat client sample (front end).

# Author or host
Sending adaptive cards to web host.
Bot code is Microsoft travel bot sample.
Card markup is product details sample from adaptive card designer.
Demo page is here:
https://dnctestbot.z13.web.core.windows.net

Type any message (eg hi) to wake up the bot.
The play icon in the video item in the card is clipped.  Right side of arrow is truncated.

I posted this question on StackOverflow and Kyle Delaney identified that the cause is a reliance on a box-sizing: border box; CSS rule in the host page.  This rule is not present in the web chat sample.

# Version of SDK
Microsoft Bot Framework 4.9.1

**Comment by mindmodel** [comment]
Here's a link to the question I posted on StackOverflow for this issue and one other.

https://stackoverflow.com/questions/61829070/microsoft-bot-framework-adaptive-card-1-1-media-play-button-doesnt-display-co/61878406

**Comment by mindmodel** [comment]
![videoplayer](https://user-images.githubusercontent.com/6022922/82359767-58cb7000-99d6-11ea-8ced-a3f5da0d80a3.png)

Screen shot of the video player with clipped icon.

**Comment by shalinijoshi19** [comment]
Hey @mindmodel I tried to repro this on our [designer](https://adaptivecards.io/designer) tool with your sample json below from the stackoverflow linked above but don't observe the clipping appear? 

![image](https://user-images.githubusercontent.com/20822397/83659231-1e3a0980-a578-11ea-8c56-a0a37808f6dc.png)


@dclaux / @ckkashyap  thoughts on this one? 


`{
      "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
      "type": "AdaptiveCard",
      "version": "1.1",
      "fallbackText": "This card requires Media to be viewed. Ask your platform to update to Adaptive Cards v1.1 for this and more!",
      "body": [
        {
          "type": "Media",
          "sources": [
            {
              "mimeType": "video/mp4",
              "url": "https://adaptivecardsblob.blob.core.windows.net/assets/AdaptiveCardsOverviewVideo.mp4"
            }
          ]
        }
      ],
      "actions": [
        {
          "type": "Action.OpenUrl",
          "title": "Learn more",
          "url": "https://adaptivecards.io"
        }
      ]
    }`

**Comment by mindmodel** [comment]
Regarding the failure to replicate in the adaptive card designer web site, I agree.  I have seen the same behavior.  I don't know whether the code behind the card designer is identical to the Visual Studio bot framework travel bot sample, but I suspect it's not.  For example, the card designer might use React.  All my code does is read the JSON markup for the card from an embedded resource, call MessageFactory.Attachment, then call SendActivityAsync to send the card.  All in C# on the server.  Card markup is from the product sample.

**Comment by shalinijoshi19** [comment]
@mindmodel the AdaptiveCards designer doesn't use react. 
@ckkashyap / @dandriscoll would you know why the code above, hosted at https://dnctestbot.z13.web.core.windows.net, and that spits out the JSON card above, would show a clipped image in WebChat but not in the standalone AC designer? 
@matthidinger / @dclaux in case they have some insights around the webchat discrepancy also.

**Comment by mindmodel** [comment]
A comment by Kyle Delaney in the StackOverflow item referenced above

https://stackoverflow.com/questions/61829070/microsoft-bot-framework-adaptive-card-1-1-media-play-button-doesnt-display-co/61878406

describes the proximate cause of the display error.

**Comment by paulcam206** [comment]
Closing as this appears to be a BotFramework issue -- please open a new issue in their [GitHub repo](https://github.com/Microsoft/botframework-sdk) if this is still a problem. Thanks!
