### ISSUE TITLE
[Designer] Binding UI could use "short-form" when creating binding expressions

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#4036]
I prefer to shorter binding syntax when hand-typing bindings, if the implicit syntax is sufficient.

E.g., `"text": "${myProperty}` as opposed to `"text": "${$root.myProperty}"`

In the Designer, when I use the Binding Flyout to select a root property, it includes `$root` in the expression.

```json
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "text": "${$root.title}",
            "type": "TextBlock"
        }
    ]
}
```

Expected:

```json
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "text": "${title}",
            "type": "TextBlock"
        }
    ]
}
```

**Comment by DeeJayTC** [comment]
Just saw this here, my 2 cents on this it could actually reduce maintainability of cards. 
As long as you only have one hierarchy level in your data its totally fine, if you have multiple levels, nested arrays etc this could get messy quite fast. 

Thats why personally I'd always use $root , $data etc anyway. Really helps with visibility where stuff is coming from.

**Comment by dclaux** [comment]
@matthidinger, what @DeeJayTC describes is the very reason for the current design. Using `$root` consistently throughout makes things more predictable.
