### ISSUE TITLE
[All][HostConfig | Styling] [Button styles can't be modified in HostConfig]

### ISSUE THREAD

**Issue by DeeJayTC** [microsoft/AdaptiveCards#4038]
# Platform

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

# Author or host
Host

# Version of SDK
1.2 Web, IOS, Android
# Details
Question was raised in TAP asking how to modify destructive/positive styles of actions. Turned out its not possible using host configs, changing container styles doesn't have an effect on actions. 

Its only working in designer for WebChat where its done with css styles

**Comment by dclaux** [comment]
@DeeJayTC buttons and inputs are styled using native styling in each platform (CSS for the JS SDK, XAML styles for UWP, etc.) The reason for this design decision is that there are simply too many different visual combinations app developers want to be able to achieve (background, frame, rounded corners, drop shadow to cite a few.)

The JS SDK uses well defined CSS classes for buttons, including `ac-pushButton` and `ac-pushButton.style-positive`.

Is native styling presenting any challenge, and if so could you describe which ones?

**Comment by DeeJayTC** [comment]
I pretty much just forwarded that from a TAP conversation, i ping you on it. 

If its not a bug but design desicision there might be some documentation needs on that, heard before that people where missing this in the config. And didn't know how to change it.

**Comment by dclaux** [comment]
There is a definite lack of documentation in that area, for sure.

**Comment by DeeJayTC** [comment]
Regarding the original issue:

For iOS  you can change the styles of buttons through XIB. https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/ios/native-styling
    
If not, UI element such buttons can be updated through overriding corresponding renderer. https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/ios/extensibility

Closing this one, not an issue.
