### ISSUE TITLE
ImageSet need an imageHeight property in HostConfig

### ISSUE THREAD

**Issue by dclaux** [microsoft/AdaptiveCards#404]
Currently, the height of each image in the set is hard-coded to 100px (at least in the HTML renderer). We need to make that configurable.

**Comment by qpongo** [comment]
I agree -- this would be nice.

Not sure if this helps but...

For now I hacked around this by setting exact column widths I want and have a 1st column with a 1px wide transparent image in a column of size = 1.  Adding an image of 1x100 will make the entire row exactly 100 pixels high unless some other column overflows and makes it bigger.

**Comment by RebeccaAnne** [comment]
Image sizes in an ImageSet are now controlled by an imageSize property on the ImageSet. The pixel sizes are configurable via host config.
