### ISSUE TITLE
[Designer][Template] [Toggle Visibility Issue]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#4042]
# Platform

* JavaScript

# Version of SDK
https://adaptivecards.io/designer/

# Details
[Expense Report Card](https://github.com/microsoft/AdaptiveCards/blob/jwoo/Template-ExpenseReport-Update/samples/Templates/Scenarios/ExpenseReport.template.json)
[Expense Report Card Data](https://github.com/microsoft/AdaptiveCards/blob/jwoo/Template-ExpenseReport-Update/samples/Templates/Scenarios/ExpenseReport.data.json)
Running the payload above yields nicely rendered card. There are three chevrons, and each one supposed to toggle the visibility of their corresponding containers, but all of the chevron toggle visibility for only one container when clicked.

**Comment by shalinijoshi19** [comment]
@dclaux could you take a quick stab at this to see what is going on? Thanks!

**Comment by dclaux** [comment]
Fixed, please review PR
