### ISSUE TITLE
[iOS-Android-Web][ImageSet Rendering] [No parity in rendering of images in imageSet for various imageSizes]

### ISSUE THREAD

**Issue by adumrewal** [microsoft/AdaptiveCards#4043]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [x] Android
- [x] iOS
- [ ] UWP
- [x] JS
- [ ] .NET
- [ ] Documentation

# Author or host

Host - Teams

What version are you using? Ex: NuGet 1.0.2, or latest master, etc...

1.2.7 on iOS

# Details

When using imageSize for imageSet, there is no parity between the rendering experience on the three clients ( iOS, Android and Web). Sample JSON and screenshots are attached.

|Card Number|iOS|Android|Web|
|:-:|:-:|:-:|:-:|
|1: Large Images|<img src="https://user-images.githubusercontent.com/8917620/82421801-381b1d00-9a9f-11ea-89e4-ecd890750b0b.png" alt="drawing" width="150"/>|<img src="https://user-images.githubusercontent.com/8917620/82421925-68fb5200-9a9f-11ea-9951-080b3c8d54f7.png" alt="drawing" width="150"/>|<img width="150" alt="Screenshot 2020-05-20 at 1 33 24 PM" src="https://user-images.githubusercontent.com/8917620/82421851-4ff2a100-9a9f-11ea-9b9c-42c2cb0f9e28.png">|
|1: Small Images|<img src="https://user-images.githubusercontent.com/8917620/82421829-45d0a280-9a9f-11ea-9ecc-56ae9c0b67b0.png" alt="drawing" width="150"/>|<img src="https://user-images.githubusercontent.com/8917620/82421906-639e0780-9a9f-11ea-91a1-58a6049e03b8.png" alt="drawing" width="150"/>|<img width="150" alt="Screenshot 2020-05-20 at 1 35 28 PM" src="https://user-images.githubusercontent.com/8917620/82421862-53862800-9a9f-11ea-8970-444e1bcdfba8.png">|

Card JSON:
Json for card with Large images: 
[imageSetLarge.txt](https://github.com/microsoft/AdaptiveCards/files/4655476/imageSetLarge.txt)

Json for card with Small images: 
[imageSetSmall.txt](https://github.com/microsoft/AdaptiveCards/files/4655478/imageSetSmall.txt)

**Comment by shalinijoshi19** [comment]
@paulcam206 this seems related to the investigation you did for #4035 no? @jwoo-msft FYI.

**Comment by paulcam206** [comment]
> @paulcam206 this seems related to the investigation you did for #4035 no? @jwoo-msft FYI.

no -- #4035 is UWP-specific

**Comment by jwoo-msft** [comment]
@almedina-ms & @golddove can you check if Android does the right thing as specified in [here](https://github.com/microsoft/AdaptiveCards/projects/21#card-40205424).

@dclaux could you please update JS renderer as was discussed [here](https://github.com/microsoft/AdaptiveCards/projects/21#card-40205424)

**Comment by shalinijoshi19** [comment]
> @almedina-ms & @golddove can you check if Android does the right thing as specified in [here](https://github.com/microsoft/AdaptiveCards/projects/21#card-40205424).
> 
> @dclaux could you please update JS renderer as was discussed [here](https://github.com/microsoft/AdaptiveCards/projects/21#card-40205424)

@jwoo-msft are we actually targeting this for this month's release? This one will include a behavior change that will need to be documented as well and the behavior needing to be vetted for UWP/.NET to ensure it's consistent.

**Comment by shalinijoshi19** [comment]
@RebeccaAnne this is the issue around only allowing a subset of enum values for ImageSets (disallowing auto and stretch sizes) and needing to update our [schema docs](https://adaptivecards.io/explorer/ImageSet.html) to reflect this

**Comment by shalinijoshi19** [comment]
Reopening to track Android/iOS changes.
