### ISSUE TITLE
Microsoft Teams only shows the first carousel card and not a littel of the next

### ISSUE THREAD

**Issue by domacKA** [microsoft/AdaptiveCards#4051]
# Platform
Microsoft Bot Framework SDK 4.72
.NET Core 3.0

What platform is your issue or question related to? (Delete other platforms).
Microsoft TEAMS

# Author or host

I render my own Cards. (lg-files)

# Details
In BotFramework Emulator (V4) carousel cards show the current card and a little bit of the next one. Microsoft Teams only shows the first card.
How would it be possible to have the same effect in Microsoft Teams?

(https://stackoverflow.com/questions/tagged/adaptive-cards).

**Comment by domacKA** [comment]
BotFramework Emulator (V4):
![Emulator](https://user-images.githubusercontent.com/65910471/82868758-7a27e100-9f2d-11ea-9b2e-d217786a4e9a.jpg)

Teams:
![teams_card](https://user-images.githubusercontent.com/65910471/82868808-9035a180-9f2d-11ea-9d68-8333f2a38063.jpg)

**Comment by shalinijoshi19** [comment]
@siduppal / @matthidinger thoughts on this one?
