### ISSUE TITLE
[Designer] [Microsoft Teams Task Module Add-on]

### ISSUE THREAD

**Issue by TylerOdenthal** [microsoft/AdaptiveCards#4053]
Hey Adaptive Card Team!

Love what you do, and I use a lot of your card on Microsoft Teams in Bot Applications.

I have been trouble integrating Task Modules into the Adaptive Cards on Teams. 

Can we just make that a feature? I feel like people would have their buttons open native inside of Teams more often if it was easier. 

Example: Action.OpenURL() <- Have a drop down to open in Microsoft Teams, thus enabling Task Module code.

Here is the tutorial on using Task Modules, I have spent hours trying to get the right syntax: https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots

**Comment by shalinijoshi19** [comment]
@siduppal / @matthidinger / @dclaux  thoughts?

**Comment by Trinetra-MSFT** [comment]
@TylerOdenthal : Could you please help us to know what you are trying to achieve? I see, you are willing to call a Task Module onclick of Adaptive Card button is it or dropdown? If that is the scenario, Please take a look at [Teams Task Module Bot](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/54.teams-task-module/Bots/TeamsTaskModuleBot.cs). Let me know if this is not what you are looking for.
