### ISSUE TITLE
[ios][size] [imageView size is wrong]

### ISSUE THREAD

**Issue by zjw7sky** [microsoft/AdaptiveCards#4060]
# Platform
* iOS

# Version of SDK
1.2.7

# Details
![image](https://user-images.githubusercontent.com/8446716/83094196-b85f0500-a0d3-11ea-8db9-e95b02262344.png)

1.2.1 is OK
The size of the picture set in json is invalid, the size of the actual picture displayed

**Comment by jwoo-msft** [comment]
@zjw7sky 
Hi,

Can you share your json and screenshots of what you've expected and what you've actually got?

Thanks

**Comment by zjw7sky** [comment]
json size 50 * 50
image size 300 * 300
imageView size 300 * 300 
What i want is 50 * 50

**Comment by jwoo-msft** [comment]
@zjw7sky,

please check [here](https://adaptivecards.io/explorer/Image.html)
Image size is a configurable property.

**Comment by zjw7sky** [comment]
👌 
 Thank you
