### ISSUE TITLE
[IOS][Layout] [Extra UIView in the container with only 1 ColumnSet element, and sometimes this cause extra space for the card]

### ISSUE THREAD

**Issue by FelixZhang001** [microsoft/AdaptiveCards#4063]
# Platform

IOS

# Author or host

Host - Teams IOS

# Version of SDK

Both SDK 1.2.7 and the latest master

# Details

We want to show several items on one card. For the first item, it is one Container with only one ColumnSet element. The payload is shown below.

```
{
  "type": "Container",
  "items": [
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "stretch",
          "items": [
            {
              "type": "TextBlock",
              "size": "large",
              "text": "Backup2 on-call schedule for the [Cortana Experience\\Cortana on Android/iOS CoA/CoI Cortana Exp China DRI] team",
              "wrap": true,
              "maxLines": 2,
              "spacing": "medium"
            },
            {
              "type": "TextBlock",
              "isSubtle": true,
              "text": "Today, 9:00 AM - Tomorrow, 12:00 AM",
              "spacing": "none"
            }
          ]
        }
      ]
    }
  ]
}
```
But sometimes, for the same payload, the first item would have an extra space UIView like this.
![Screenshot (1)](https://user-images.githubusercontent.com/52741892/83124324-a51a5c80-a108-11ea-9346-8bce7a47868b.png)

After investigation, I find that every container would have an extra UIView. Attached the payload.
[new_payload.txt](https://github.com/microsoft/AdaptiveCards/files/4694605/new_payload.txt)

In most cases, the extra UI view's height would be zero and won't affect UI, but not sure why sometimes, it would extend height to 20.5px.

<img width="404" alt="Screen Shot 2020-05-28 at 5 10 39 PM" src="https://user-images.githubusercontent.com/52741892/83125236-d7788980-a109-11ea-803d-923aaa3f4b6c.png">
<img width="284" alt="Screen Shot 2020-05-28 at 4 49 32 PM" src="https://user-images.githubusercontent.com/52741892/83124604-fc203180-a108-11ea-924d-6cae58f656fe.png">
<img width="208" alt="Screen Shot 2020-05-28 at 4 49 45 PM" src="https://user-images.githubusercontent.com/52741892/83124666-10fcc500-a109-11ea-8469-03517d40a36a.png">
<img width="225" alt="Screen Shot 2020-05-28 at 4 50 19 PM" src="https://user-images.githubusercontent.com/52741892/83124730-28d44900-a109-11ea-8c68-882d393c68d1.png">

The UI view could also be found with the Adaptive card latest master branch.

**Comment by shalinijoshi19** [comment]
@jwoo-msft thoughts on this one real quick?

**Comment by shalinijoshi19** [comment]
@VikrantSingh01 is this something that you are aware of/tracking?

**Comment by FelixZhang001** [comment]
Any update on this issue, I suspect it is related to the below code to add extra UIView, but not sure why the height > 0 sometimes.
https://github.com/microsoft/AdaptiveCards/blob/main/source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRColumnRenderer.mm

```
if (columnElem->GetVerticalContentAlignment() == VerticalContentAlignment::Center || (columnElem->GetVerticalContentAlignment() == VerticalContentAlignment::Top && _fillAlignment)) {
      trailingBlankSpace = [column addPaddingSpace];
}
```
