### ISSUE TITLE
Stretch on FactSet

### ISSUE THREAD

**Issue by danmarshall** [microsoft/AdaptiveCards#408]
I have a scenario that I would like to use a FactSet but the layout is limited, I would like it to go edge to edge. So I am using a ColumnSet instead. But my data is essectially a FactSet.

**Comment by dclaux** [comment]
Dan, I am not sure I understand. Could you clarify? Maybe a screenshot of what you'd like to accomplish?

**Comment by danmarshall** [comment]
Surely :)

Here is a FactSet from samples:
![image](https://user-images.githubusercontent.com/11507384/27111395-aff4fd2e-5064-11e7-8f62-fd1be36bb2c7.png)

I'd like the second column to appear right-aligned to the edge of the container, like the Flight status:
![image](https://user-images.githubusercontent.com/11507384/27111425-d5d32282-5064-11e7-8c5d-9b9245d537eb.png)

**Comment by dclaux** [comment]
Oh, you want horizontal alignment for fact values. Seems reasonable to me.

**Comment by danmarshall** [comment]
Yes, and also that they align to the container. So I suppose there might be 3 modes:

Default: (current functionality)
![image](https://user-images.githubusercontent.com/11507384/27116935-c56c6510-5088-11e7-8121-50b79c189686.png)

Horizontal align fact values to the right:
![image](https://user-images.githubusercontent.com/11507384/27116959-e2d937b8-5088-11e7-9ea0-44fbb7b4cb18.png)

Stretch:
![image](https://user-images.githubusercontent.com/11507384/27116975-073263f0-5089-11e7-8608-cc684cffce52.png)

Stretch will make the fact set fill the container. Used in combination with horizontal alignment to the right. 

Stretch + horizontal alignment to the left would appear as the current default.

**Comment by dclaux** [comment]
FactSet already renders across the entire available width, so adding horizontal alignment support will get us the "Stretch" behavior you have above. I am not sure there is a need for the your second screenshot though.

**Comment by matthidinger** [comment]
Trying to prioritize what we Must-Have for v1, do you guys feel this is important enough to include?

**Comment by danmarshall** [comment]
Hi Matt, I think it's a nice enhancement but is not a showstopper. Feel free to lower the priority.

**Comment by dalekunce** [comment]
I'm working on something that uses facts with numbers. I would like to be able to right align all numbers similar to a receipt.

**Comment by dclaux** [comment]
@dalekunce for now, the layout you desire can be accomplished with ColumnSet, one per row. You also have more control over font sizes/color in a ColumnSet. I do agree though that in this simple case FactSet could make it easier.

**Comment by matthidinger** [comment]
Thanks for the feedback! I've added it to the list of things being considered for 1.1

**Comment by xjose97x** [comment]
@matthidinger any update on this?

**Comment by chaim770** [comment]
We would also appreciate an update on this one.
Thanks

**Comment by RebeccaAnne** [comment]
This is not currently on our roadmap. If this is still of interest to you either open a request in [product board](https://portal.productboard.com/adaptivecards/1-adaptive-cards-features/tabs/5-roadmap) or if you would like to make a contribution please check out our contribution guidelines  [here](https://github.com/microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md.).
