### ISSUE TITLE
[Schema Explorer] can't scroll left hand nave bar on chrome

### ISSUE THREAD

**Issue by Stevenic** [microsoft/AdaptiveCards#4086]
# Platform

Chrome

# Details

You can't access all of the links in the left hand nav bar on chrome because there's no scroll bar.

**Comment by paulcam206** [comment]
Interesting -- can you post a screenshot and more details (device, chrome version, etc.)?

I'm not able to repro this locally.

**Comment by matthidinger** [comment]
HI Steve, I'm also unable to repro this. What's your viewport dimensions and screen resolution?

![image](https://user-images.githubusercontent.com/1432195/83299550-3fcb7780-a1ab-11ea-96bc-f07754e8c4db.png)

**Comment by eyadon** [comment]
I have this issue too - Chrome 83.0.4103.61 on Win10, the scroll bar will magically show up when you get far enough down in the right pane. 
![noscrollbar](https://user-images.githubusercontent.com/17410657/83912057-d3182600-a732-11ea-8dbf-119ae60d804b.png)
![yesscrollbar](https://user-images.githubusercontent.com/17410657/83912051-ce537200-a732-11ea-8e38-5cc99f855fbb.png)

**Comment by paulcam206** [comment]
I have a repro on this and am looking at addressing it :)

**Comment by paulcam206** [comment]
sneaksy little bug:

https://github.com/microsoft/AdaptiveCards/blob/98b9c5d1e3bc0224ca4918faf2889c62ca2f5660/source/nodejs/adaptivecards-site/themes/adaptivecards/source/js/script.js#L563

doesn't account for the case where `hiddenAfter > footerHeight`

**Comment by paulcam206** [comment]
@stevenic / @eyadon - you can try out the fix [here](https://adaptivecardsci.z5.web.core.windows.net/pr/4173/explorer).

thanks for your patience/input! 👍
