### ISSUE TITLE
Choiceset cannot be closed after Card-Update in MS-Teams

### ISSUE THREAD

**Issue by janandreschweiger** [microsoft/AdaptiveCards#4096]
Hello, we have developed an MS-Teams chat bot.
This issue seems at first insignificant, but is extremely annoying to our clients.

**The problem:**
1. The user opens up a Choiceset.
2. We update his card.
3. The old Choiceset is still open and cannot be closed.

**Example**
![Screenshot from 2020-06-03 09-13-06](https://user-images.githubusercontent.com/44372046/83606888-96a1ca00-a57a-11ea-8d84-e88fff98e5bd.png)
The client can select his Tags and apply changes with the Check. Now we have to update his card, since all values (all checked tags) disappear after a submit. After updating the card the Choiceset cannot be closed and hides the content beneath. We experience this issue with 3 other cards.

**Why updating the card?**
When the user clicks submit all inputs are cleared. We have another card where the user can create a question. When his inputs are invalid (e.g. too few words) we need to update his card with the sent values. Otherwise the user has to rewrite everything again.

We desperately need a solution for this issue, since we serve two big organizations.

**Comment by geckgecko** [comment]
I have experienced this issue a month ago. I could not find a workaround.
A bug-fix would be nice...

**Comment by shalinijoshi19** [comment]
@siduppal could you help take look to identify if this is a teams issue at all? @dclaux / @matthidinger / @paulcam206 FYI

**Comment by Trinetra-MSFT** [comment]
@shalinijoshi19 , Thanks for bringing up this issue, We can reproduce this as Bug. We are looking into this.
We will let you know once this got resolved.

**Comment by janandreschweiger** [comment]
@Trinetra-MSFT, thank you. If you need any support just let me know.

**Comment by Trinetra-MSFT** [comment]
@shalinijoshi19 @janandreschweiger , The Bug is Resolved now with Pull Request 265446. Please check and let us know.

**Comment by Trinetra-MSFT** [comment]
@shalinijoshi19 , Can you help to close this, This is resolved now

**Comment by janandreschweiger** [comment]
Thank you 😍! I recognized the change yesterday. Really awesome work of you guys!

In addition, I experienced another major change. When users submit their cards, the value (e.g. TextField input) persists. This is great, because we no longer need to update the cards (e.g. Otherwise the inputs are lost, if the action fails).

Do you know if these two changes are permanent? Is there any way to learn about a major change in advance?
