### ISSUE TITLE
[JS] Multiline Input.Text elements should stretch when height is set to stretch

### ISSUE THREAD

**Issue by mokandre** [microsoft/AdaptiveCards#4097]
# Platform
Javascript

See also #5346 (UWP), #5347 (.NET), #5348 (iOS), and #5349 (Android)

# Author or host

Rendering in Webex teams

# Version of SDK

1.2.0

# Details

According to the [Adaptive Card Schema explorer](https://adaptivecards.io/explorer/Input.Text.html) when Input.Text has the inherited "height" attribute set to "stretch" the behavior should be "The container will stretch its height to the available remaining height of the parent container." Card designer is not showing the height property in `ELEMENT PROPERTIES`

**JSON:**
```json
{
      "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
      "type": "AdaptiveCard",
      "version": "1.0",
      "body": [
        {
          "type": "TextBlock",
          "size": "Medium",
          "weight": "Bolder",
          "text": "Custom JSON Design Input",
          "horizontalAlignment": "Center"
        },
        {
          "type": "TextBlock",
          "text": "In addition to showing your our pre-built samples, I can submit your custom design for you.  This helps to see how it will render or to see what type of payload your app will need to process if a user hits an Action.Submit button.",
          "wrap": true
        },
        {
          "type": "TextBlock",
          "text": "One way to get design JSON to paste here is to use the \"Copy Card JSON\" button from the [Buttons and Cards Designer](https://developer.webex.com/buttons-and-cards-designer) "
        },
        {
          "type": "Container",
          "items": [
            {
              "type": "Input.Text",
              "placeholder": "Paste card JSON here",
              "id": "cardJson",
              "isMultiline": true,
              "height": "stretch",
              "maxLength": 8000
            }
          ],
          "minHeight": "266px"
        }
      ],
      "actions": [
        {
          "type": "Action.Submit",
          "title": "Display My Card",
          "data": {
            "cardType": "customJsonInput",
            "nextAction": "submitJson"
          }
        },
        {
          "type": "Action.Submit",
          "title": "Go Back To The Built In Samples",
          "data": {
            "cardType": "customJsonInput",
            "nextAction": "samplePicker"
          }
        }
      ]
    }
```

**Expected Output:**

<img width="534" alt="expectedOutput" src="https://user-images.githubusercontent.com/55378170/83617680-0cbc2600-a5a7-11ea-966e-f23d112e8ce2.png">

**Actual Output:**

<img width="554" alt="actualOutput" src="https://user-images.githubusercontent.com/55378170/83617738-2493aa00-a5a7-11ea-97c4-cf62e0bb79aa.png">

**Card Designer:**

<img width="1679" alt="cardDesigner" src="https://user-images.githubusercontent.com/55378170/83617990-7b997f00-a5a7-11ea-9293-ba33df308e6c.png">

**Comment by shalinijoshi19** [comment]
@dclaux thoughts for this one real quick? Also @paulcam206 since he's been toying with the designer as well as FYI.

**Comment by shalinijoshi19** [comment]
@dclaux this is one of the Cisco integration bugs they reported.. thoughts?

**Comment by dclaux** [comment]
As discussed last week, this kind of is a feature request. All inputs cannot honor the height property when set to "stretch". Basically, only Input.Text with isMultiline = true can - but it currently doesn't, by design. So we just need to make a collective decision whether or not we want to change that across all renderers (assuming non-JS renderers have the same behavior as the JS renderer). Aside from that the change (in JS at least) is trivial.

**Comment by RebeccaAnne** [comment]
We agree that multiline Input.Text should stretch in this case.
