### ISSUE TITLE
[iOS][Action Rendering] Allow for text wrapping in Action buttons

### ISSUE THREAD

**Issue by JohnnyKehr** [microsoft/AdaptiveCards#4107]
**What platform is your feature request related to? (Delete other platforms).**
iOS

**Is your feature request related to a problem? Please describe.**
An action with a really long title can extend beyond the bounds of the button without any wrapping. The title then gets cut off with no way to see the rest of it. 

**Describe the solution you'd like**
Allowing for text wrapping would be a simple solution to resolve this.

**Describe alternatives you've considered**
n/a

**Additional context**
Wasn't sure if this is considered a "bug" or not (feel free to make it a bug if it's more fitting there). 

Here is an example card that does not allow for text wrapping (note the host config has `"actionsOrientation": "vertical"`):

```javascript
{
   "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
   "type":"AdaptiveCard",
   "version":"1.2",
   "body":[
      {
         "type":"TextBlock",
         "wrap":true,
         "text":"There are also still actions at the bottom of the card"
      }
   ],
   "actions":[
      {
         "type":"Action.ShowCard",
         "title":"Really Long Title That's Too Long For the Card",
         "style":"positive",
         "card":{
            "type":"AdaptiveCard",
            "body":[
               {
                  "type":"TextBlock",
                  "text":"This is a show card"
               }
            ]
         }
      },
      {
         "type":"Action.OpenUrl",
         "title":"Desctructive",
         "url":"https://adaptivecards.io",
         "style":"destructive"
      },
      {
         "type":"Action.Submit",
         "title":"Default",
         "data":{
            "x":13
         }
      }
   ]
}
```

this produces the card: 

![Screen Shot 2020-06-03 at 3 14 45 PM](https://user-images.githubusercontent.com/1463512/83694687-70495200-a5ad-11ea-8c4a-f5e2ff9fe7bb.png)

**Comment by jpjpjp** [comment]
Its worth noting that this seems to be the default behavior on Android.
![AndroidMarkdown](https://user-images.githubusercontent.com/4774656/83798099-b536bc80-a671-11ea-83f8-a4b7b3935866.png)

The same JSON on iOS results in this:

![iOSMarkdown](https://user-images.githubusercontent.com/4774656/83798129-c384d880-a671-11ea-9402-51f5f4bdfa20.png)

JSON for these images is here:  https://developer.webex.com/buttons-and-cards-designer/lesson-9

**Comment by shalinijoshi19** [comment]
Updating this with the priority per offline sync for now.

**Comment by DeeJayTC** [comment]
Based on this stackoverflow discussion: https://stackoverflow.com/questions/62470617/how-would-it-be-possible-that-adaptive-cards-in-microsoft-teams-for-android-neve 

It seems to be an issue for Android aswell.

**Comment by JohnnyKehr** [comment]
> Based on this stackoverflow discussion: https://stackoverflow.com/questions/62470617/how-would-it-be-possible-that-adaptive-cards-in-microsoft-teams-for-android-neve
> 
> It seems to be an issue for Android aswell, at least for MS Teams tho
> 
> Seems to be similar to this aswell: #3919

There's an important distinction between the two issues you linked and the one above (although I believe that the issues above are valid issues to figure out as well). In both of the ones you linked, the actions have a property set: `"actionsOrientation": "horizontal"`. With the horizontal orientation, the behavior is for the actions to be scrollable if they go outside of the view (which I don't love, but it's still usable to a degree).  

The bug I mentioned above is with `"actionsOrientation": "vertical"`. When the action title is too long in that scenario, it just goes off these screen and is no longer scrollable.

**Comment by jwoo-msft** [comment]
Hello @JohnnyKehr,
The cut off issue has been fixed via [PR4108](https://github.com/microsoft/AdaptiveCards/pull/4108)
Even in vertical orientation, with this fix, button will scroll horizontally.
Thank you.
