### ISSUE TITLE
[JavaScript]Adaptive cards framework does not work in IE11

### ISSUE THREAD

**Issue by atishayv** [microsoft/AdaptiveCards#4109]
# Platform

* JavaScript

# Author or host

Host Name : Microsoft Search

# Version of SDK

"adaptivecards": "^1.3.0-alpha.2",

# Details

Loading card using adaptive card library throws an error in IE. 
The error coming is because adaptive cards uses array findIndex which is not supported in IE.

**Comment by atishayv** [comment]
CC : @dclaux

**Comment by dclaux** [comment]
Can you please include more precise details of the error? I just searched through the (latest) codebase and it doesn't use findIndex.

**Comment by atishayv** [comment]
@dclaux 
This is the compiled code from adaptive cards templating library : 
```
 var FunctionCollection = function() {
                        function FunctionCollection() {
                            this._functions = [];
                        }
                        FunctionCollection.prototype.indexOf = function(name) {
                            return this._functions.findIndex(function(f) {
                                return f.name === name;
                            });
                        };
                        FunctionCollection.prototype.register = function(name, callback) {
                            var index = this.indexOf(name);
                            if (index >= 0) {
                                this._functions[index].callback = callback;
                            } else {
                                this._functions.push({
                                    name: name,
                                    callback: callback
                                });
                            }
                        };
                        FunctionCollection.prototype.unregister = function(name) {
                            var index = this.indexOf(name);
                            if (index >= 0) {
                                this._functions.splice(index, 1);
                            }
                        };
                        FunctionCollection.prototype.find = function(name) {
                            var index = this.indexOf(name);
                            return index >= 0 ? this._functions[index] : undefined;
                        };
                        return FunctionCollection;
                    }();
                    var EvaluationContext = function() {
                        function EvaluationContext() {
                            this._functions = new FunctionCollection();
                            this._stateStack = [];
                        }
```

and the error is : 
![image](https://user-images.githubusercontent.com/13940020/83875206-5138f480-a754-11ea-9bd2-4a3e0bc0e18f.png)

**Comment by atishayv** [comment]
@dclaux, @matthidinger  We are using 0.1.1-alpha.1 version of adaptivecards-templating where findIndex is used. 

Checking here : https://www.npmjs.com/package/adaptivecards-templating/v/1.0.0-rc.0, it seems the next version available for this library is 1.0.0-rc.0. 
Is this version a breaking change, as it uses `$when: ${title}` syntax?
If not, what is the corresponding adaptivecards package dependency for it ?

**Comment by dclaux** [comment]
@atishayv yes, 1.0.0-rc.0 introduces breaking changes, which I have mentioned to your team over email. Please refer to the release notes at https://docs.microsoft.com/en-us/adaptive-cards/templating/

**Comment by RebeccaAnne** [comment]
IE11 is not supported
