### ISSUE TITLE
.NET Convert JSON schema to a model

### ISSUE THREAD

**Issue by jrmcdona** [Microsoft/AdaptiveCards#411]
Hi,
Is there a simple method to build a schema in the visualizer then either use that JSON directly in C# or convert it to .NET based model?   Just trying to figure out the fastest way to build the Adaptive card in .NET after visualizer/JSON.

Thanks

**Comment by EricDahlvang** [comment]
One option is to save the .json in your bot project, and load the file directly:

```cs
public async Task<string> GetCardText(string cardName)
{
    var path = HostingEnvironment.MapPath($"/Cards/{cardName}.json");
    if (!File.Exists(path))
        return string.Empty;

    using (var f = File.OpenText(path))
    {
        return await f.ReadToEndAsync();
    }
}

```

Then, add that as an attachment to the return message like:

```cs
var returnMessage = dialogContext.MakeMessage();

returnMessage.Attachments.Add(new Attachment()
{
    Content = await GetCardText("[Card File Name Here]"),
    ContentType = AdaptiveCard.ContentType,
    Name = "Card"
});

```

**Comment by jrmcdona** [comment]
very cool, thanks

**Comment by Yashu1904** [comment]
@EricDahlvang I have tried the same steps as you mentioned above, but I got a problem like can't render card. Hope you help me to sort it out.
![screenshot 1](https://user-images.githubusercontent.com/31498666/32312228-ba7844b8-bfc2-11e7-8381-5077c3952102.png)


Thanks in Advance,
Yashwanth.

**Comment by PoojaSha** [comment]
Hi Yashu,

If you could please tell how did you resolve the issue, I am also facing the same.

**Comment by PoojaSha** [comment]
@Yashu1904

**Comment by CleberDSantos** [comment]
It's working fine for me.

Install-Package AdaptiveCards -IncludePrerelease

`  var json = await GetCardText("card1");

            AdaptiveCardParseResult jsonResult = AdaptiveCard.FromJson(json);

            replyMessage.Attachments.Add(new Attachment()
            {
                Content = jsonResult.Card,
                ContentType = AdaptiveCard.ContentType,
                Name = "Card"
            });
`

**Comment by PoojaSha** [comment]
AdaptiveCardParseResult class and FromJSON method is not being recognized. Did you create it? Can you please show the implementation of it? @CleberDSantos

**Comment by CleberDSantos** [comment]
Install-Package AdaptiveCards -IncludePrerelease

**Comment by PoojaSha** [comment]
I have already installed Adaptive Cards package. 

On entering above command, it gives following error

 At line:1 char:16
+ Install-Package <<<<  AdaptiveCards -IncludePrerelease
    + CategoryInfo          : ObjectNotFound: (Default:String) [Install-Package], ItemNotFoundException
    + FullyQualifiedErrorId : NuGetProjectNotFound,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by PoojaSha** [comment]
Please help @CleberDSantos

**Comment by CleberDSantos** [comment]
Try 

uninstall-Package AdaptiveCards
Install-Package AdaptiveCards -IncludePrerelease

**Comment by PoojaSha** [comment]
Hi @CleberDSantos ,

On entering "Find-Package AdaptiveCards" it displays following, which means cards do exist in my code
Id                                  Versions                                 Description                                                                                
--                                  --------                                 -----------                                                                                
Microsoft.AdaptiveCards             {0.5.1}                                  This library implements classes for building and serializing adaptive card objects         
Time Elapsed: 00:00:02.6086086



But on entering PM> uninstall-Package AdaptiveCards
it displays following:

Uninstall-Package : Project 'Default' is not found.
At line:1 char:18
+ uninstall-Package <<<<  AdaptiveCards
    + CategoryInfo          : ObjectNotFound: (Default:String) [Uninstall-Package], ItemNotFoundException
    + FullyQualifiedErrorId : NuGetProjectNotFound,NuGet.PackageManagement.PowerShellCmdlets.UninstallPackageCommand


Kindly help. I have tried uninstall-Package **Microsoft**.AdaptiveCards too

**Comment by CleberDSantos** [comment]
Please, check if you selected correct project on nuget package console:

![image](https://user-images.githubusercontent.com/1626423/33109014-5bc45fb0-cf26-11e7-9ca8-a25a38b826f5.png)

If yes, check the package.config:

![image](https://user-images.githubusercontent.com/1626423/33109072-9e38a7ac-cf26-11e7-8bea-1fd2ad13a39e.png)

**Comment by CleberDSantos** [comment]
I had to downgrade to **1.0.0-beta03**, because not working for me with the last beta version:

![image](https://user-images.githubusercontent.com/1626423/33153194-d04363bc-cfc7-11e7-96c5-dbcd842662ce.png)

![image](https://user-images.githubusercontent.com/1626423/33153237-17952660-cfc8-11e7-8cb9-c674a3c17db4.png)

![image](https://user-images.githubusercontent.com/1626423/33153458-0329cee6-cfc9-11e7-98fc-0b3b6cd455ab.png)

**Comment by matthidinger** [comment]
Hi @CleberDSantos, what is the issue you were seeing with beta08?

**Comment by CleberDSantos** [comment]
Hi @matthidinger. Whe I'm using the beta08 the adptive card not render for me.

![image](https://user-images.githubusercontent.com/1626423/33171797-d1829064-d034-11e7-9fe9-3b82fca62eaf.png)

![image](https://user-images.githubusercontent.com/1626423/33171812-de02a70c-d034-11e7-9e4b-fca17b68b261.png)

But, when I'm using beta03 it's working fine. I don't know what's going on.

**Comment by matthidinger** [comment]
Can you share the c# code you're using to generate the Json, and/or the Json payloads geneated by beta03 and beta08 so I can see the dinrrrences

**Comment by PoojaSha** [comment]
Hi @matthidinger,

I am trying to render my Adaptive card on Workplace using Bot Framework in C#. The same card is displaying fine on Facebook messenger. But if I publish it on Workplace chat, it is coming as blank. Could you please help me with the possible solution?

Thanks much

**Comment by CleberDSantos** [comment]
My code is very simple, I'm @EricDahlvang  approach. 


```
       [LuisIntent("")]
        public async Task None(IDialogContext context, LuisResult result)
        {

            var replyMessage = context.MakeMessage();
            var json = await GetCardText("card1");

            AdaptiveCardParseResult jsonResult = AdaptiveCard.FromJson(json);

            replyMessage.Attachments.Add(new Attachment()
            {
                Content = jsonResult.Card,
                ContentType = AdaptiveCard.ContentType,
                Name = "Card"
            });

            await context.PostAsync(replyMessage);
        }
```

**Comment by matthidinger** [comment]
The "type" property is being stripped from everything, that should definitely not be happening. Let me investigate and get a fix out as soon as possible

**Comment by CleberDSantos** [comment]
Great 

I guess the issue is in Microsoft.Bot.Builder.

![image](https://user-images.githubusercontent.com/1626423/33186887-7b1128d6-d074-11e7-8052-e63d6773944d.png)

![image](https://user-images.githubusercontent.com/1626423/33186909-b5503640-d074-11e7-978a-91154655b170.png)

But, it's just a suggestion ^^

**Comment by matthidinger** [comment]
I'm having a hard time reproducing. All of our tests are working too, and we deserialize from files in the many tests.

Are you able to reproduce where exactly the "type" properties are being stripped? Is it what your service is returning or is it once the payload gets to webchat/emulator?

**Comment by CleberDSantos** [comment]
I'm copying from details field.

Localhost bot emulator test, 

![image](https://user-images.githubusercontent.com/1626423/33187231-7d8b62ea-d077-11e7-8ba9-d9c09d60a597.png)

But i had the same issue in **webchat** iframe:

![image](https://user-images.githubusercontent.com/1626423/33187312-1fbe0ad6-d078-11e7-902b-01798c75f424.png)


And **Skype Channel**:

![image](https://user-images.githubusercontent.com/1626423/33187283-eab7494c-d077-11e7-8e9b-027699910418.png)

**Comment by matthidinger** [comment]
Ok thanks, I've got a repo. Going to investigate with the BF team, stay tuned!

**Comment by matthidinger** [comment]
This should be fixed with the **beta09** package that will be releasing shortly. Thanks for your patience!

**Comment by jeandasilvapapa** [comment]
hi @CleberDSantos I want to add an adaptive card in a LuisIntent
follow the pictures you can help me
![image](https://user-images.githubusercontent.com/31745657/37261423-21fbd88e-257b-11e8-816e-9f1f717878eb.png)
![image](https://user-images.githubusercontent.com/31745657/37261434-3a4be924-257b-11e8-8ae3-5271fc977488.png)

**Comment by artemious7** [comment]
The conversation above seems to me mostly irrelevant to the issue topic - ".NET Convert JSON schema to a model". @jrmcdona has asked 

> to build a schema in the visualizer then either use that JSON directly in C# or convert it to .NET based model

The solution provided here was to read JSON from a file and use it for adaptive card. **But how do I fill the schema with my values?** I thought Adaptive cards were not meant to be static, but show relevant content each time user requests a card. If I parse the JSON schema, I'll have to find each element and fill it with my values. But using C# adaptive cards library model would simplify it. 

**Is there any JSON-schema-to-C#-model converter?**

**Comment by arafattehsin** [comment]
@artemious7 I am looking for the similar solution. Please let me know if you were able to get it done somehow.

**Comment by Massi-G** [comment]
@artemious7 where you able to solve this, if yes please can you share solution to populating adaptive cards with values

**Comment by arafattehsin** [comment]
Hello @Massi-G, I think I was able to do that long back ago. I will try to look for the code snippet for you once I am free tomorrow.

**Comment by artemious7** [comment]
Hello @Massi-G, I asked this question [here](https://github.com/MicrosoftDocs/AdaptiveCards/issues/124#issuecomment-475501134)
and Microsoft replied:

> There is an early preview of [Data Binding in Adaptive Cards] (microsoft/AdaptiveCards#2448).

**Comment by artemious7** [comment]
However, I didn't use the new data binding feature. I used Adaptive Cards v1, so I had to clone adaptive card nodes and change the values according to my data.
[Here's some code from my project](https://gist.github.com/artemious7/e5a8f7d92e30b3b2607e9b8fad3b3d31)

**Comment by Massi-G** [comment]
Hi

Thank you for the code snippet, I have seen the adaptive card binding document. However, that presumed a lot and as I am new at the adaptive cards will try and work through it.

Kind Regards
[signature_170447147]


Massimo Gatta | Business Analyst

PUBLICIS COMMERCE
Cambridge Retail Park, 22 Witkoppen Road, Paulshof
PostNet Suite #249, Private Bag X87, Bryanston, 2024
Phone: +27 (0)87 255 1257

www.creativecounsel.co.za<http://www.creativecounsel.co.za/>
www.publicisgroupe.com<http://www.publicisgroupe.com/>
