### ISSUE TITLE
[Android][User Input Issues] [Can't enter an Input.Date]

### ISSUE THREAD

**Issue by jpjpjp** [microsoft/AdaptiveCards#4112]
# Platform
Android

What platform is your issue or question related to? (Delete other platforms).
* Android
# Author or host

Host on Webex Teams

# Version of SDK

We have our own fork of AdaptiveCards@v1.2.6

# Details

When entering a Date on a card with an Input.Date field on Android, the Android Calendar shows up but there does not appear to be any button that allows the user to "enter" the date.  

![Date Enter](https://user-images.githubusercontent.com/4774656/83782084-536c5780-a65d-11ea-82d4-3d909939a226.png)

Replicated with Webex Teams Android app with the following Android Device:

![Android Phone Details](https://user-images.githubusercontent.com/4774656/83781826-0daf8f00-a65d-11ea-9c53-66e929c7ee8b.jpg)

 Create a free Webex Teams account https://www.webex.com/team-collaboration.html to replicate

JSON is the original default sample from the Adaptive Cards Designer (attached)

{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "Container",
			"items": [
				{
					"type": "TextBlock",
					"text": "Publish Adaptive Card schema",
					"weight": "bolder",
					"size": "medium"
				},
				{
					"type": "ColumnSet",
					"columns": [
						{
							"type": "Column",
							"width": "auto",
							"items": [
								{
									"type": "Image",
									"url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg",
									"size": "small",
									"style": "person"
								}
							]
						},
						{
							"type": "Column",
							"width": "stretch",
							"items": [
								{
									"type": "TextBlock",
									"text": "Matt Hidinger",
									"weight": "bolder",
									"wrap": true
								},
								{
									"type": "TextBlock",
									"spacing": "none",
									"text": "Created {{DATE(2017-02-14T06:08:39Z,SHORT)}}",
									"isSubtle": true,
									"wrap": true
								}
							]
						}
					]
				}
			]
		},
		{
			"type": "Container",
			"items": [
				{
					"type": "TextBlock",
					"text": "Now that we have defined the main rules and features of the format, we need to produce a schema and publish it to GitHub. The schema will be the starting point of our reference documentation.",
					"wrap": true
				},
				{
					"type": "FactSet",
					"facts": [
						{
							"title": "Board:",
							"value": "Adaptive Card"
						},
						{
							"title": "List:",
							"value": "Backlog"
						},
						{
							"title": "Assigned to:",
							"value": "Matt Hidinger"
						},
						{
							"title": "Due date:",
							"value": "Not set"
						}
					]
				}
			]
		}
	],
	"actions": [
		{
			"type": "Action.ShowCard",
			"title": "Set due date",
			"card": {
				"type": "AdaptiveCard",
				"body": [
					{
						"type": "Input.Date",
						"id": "dueDate",
						"title": "Select due date"
					},
					{
						"type": "Input.Text",
						"id": "comment",
						"isMultiline": true,
						"placeholder": "Add a comment"
					}
				],
				"actions": [
				    {
				        "type": "Action.OpenUrl",
						"title": "OK",
						"url": "https://adaptivecards.io"
			        }
				]
			}
		},
		{
			"type": "Action.OpenUrl",
			"title": "View",
			"url": "https://adaptivecards.io"
		}
	]
}

**Comment by shalinijoshi19** [comment]
@jwoo-msft is this related to #3671 you think? @almedina-ms also for FYI.

**Comment by shalinijoshi19** [comment]
@jpjpjp closing this one out per the offline sync as something that you will be investigating at your end.  Do feel free to update this issue with any details that might help the integration scenario going forward. We weren't able to repro this with the public Android images or with our stock Android renderer + Visualizer test app (@golddove feel free to include specifics with what you tested here)
