### ISSUE TITLE
[Android][Render Problem] [Buttons Dissapear after clicking an Action.OpenUrl]

### ISSUE THREAD

**Issue by jpjpjp** [microsoft/AdaptiveCards#4115]
# Platform
* Android

# Author or host
Host on Webex Teams

# Version of SDK

We have our own fork of AdaptiveCards@v1.2.6

# Details

When we render a card with an Action.OpenUrl button on Android, if the user clicks on that, and follows the link to the URL, when they return to the Webex Teams client, the buttons are no longer seen.

Example of Card rendered on Mac:
![CardWithOpenUrlButton](https://user-images.githubusercontent.com/4774656/83785561-7b5cba80-a65f-11ea-943c-42d433150e1b.png)

Example of Card rendered on Android after the user has hit the OpenUrl Button

![AndroidRenderAfterClickingOpenUrl](https://user-images.githubusercontent.com/4774656/83785589-87487c80-a65f-11ea-817a-bcef4181c591.png)

Create a free Webex Teams account https://www.webex.com/team-collaboration.html to replicate using the Webex Teams Android client.   Create a space with cardSampler@webex.bot, choose the "Restaurant" sample, and click the "More Info" button.

Alternately use this JSON:

[BHP issue- buttons disappearing.docx](https://github.com/microsoft/AdaptiveCards/files/4731515/BHP.issue-.buttons.disappearing.docx)

**Comment by shalinijoshi19** [comment]
@almedina-ms , @jwoo-msft our Android and iOS SMEs respectively. @jpjpjp apologies if this was discussed in our syncs already but would be great to understand the reason for your forks (vs leveraging our framework packages directly) and also what exactly are the differences -- do we already have access to your source or debugging data?

**Comment by shalinijoshi19** [comment]
This does appear to be an AC issue with some inconsistencies that @golddove reported. @golddove please go ahead add in your additional debugging details please? Thanks

**Comment by golddove** [comment]
Following card also works fine on the JS renderer, but only shows one Action on Android. So, issue appears to be with multiple actionsets in a column.
```
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "ActionSet",
                            "actions": [
                                {
                                    "type": "Action.Submit",
                                    "title": "Action.Submit1"
                                }
                            ]
                        },
                        {
                            "type": "ActionSet",
                            "actions": [
                                {
                                    "type": "Action.Submit",
                                    "title": "Action.Submit2"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/4442788/84423000-d9534a00-abeb-11ea-94b3-3f1223541373.png)
