### ISSUE TITLE
[iOS][Accessibility] [Input.ChoiceSet hard to use on iOS]

### ISSUE THREAD

**Issue by jpjpjp** [microsoft/AdaptiveCards#4116]
# Platform

* iOS

# Author or host

Host on Webex Teams.  

Create a free Webex Teams account https://www.webex.com/team-collaboration.html to replicate using the Webex Teams iOS client. Create a space with cardSampler@webex.bot, and use the Input.ChoiceSet drop down that you get from its first message

# Version of SDK

We have our own fork of AdaptiveCards@v1.2.6

# Details

When using the Input.ChoiceSet on an iOS 13 device with dark mode, the background for the drop down is black even if the applications theme is not:

![BlackInputChoiceSet](https://user-images.githubusercontent.com/4774656/83793392-79e4bf80-a66a-11ea-8b73-376e52997d1e.png)

**Comment by shalinijoshi19** [comment]
@jwoo-msft thoughts on this?

**Comment by shalinijoshi19** [comment]
This looks to have been broken post iOS13. @jwoo-msft to look into this and report back here with options? Thanks!

**Comment by shalinijoshi19** [comment]
Looks like there's 2 aspects here in this bug - @jpjpjp  / @jwoo-msft please correct me if I am wrong here. 

1. Re. the theming issue related to the latest iOS13 update that kind of is messing with the existing App defaults. Something that we should do some background research on to come up with viable options. @jwoo-msft could you help here with that pre-prep a bit for next week's sync? 

2. The second aspect is the fact that the behavior you report is native/natural to iOS users/platform and so it may be a case of educating the app users on iOS for Cisco. But we should still keep this open for us to see if there's anything more we can do at the SDK level to aid here.. @jwoo-msft would love to hear your thoughts on this! 
Thanks

**Comment by jpjpjp** [comment]
@shalinijoshi19 agree that this is two issues.   I've updated the original description so that the team can focus on issue 1.

**Comment by shalinijoshi19** [comment]
@jwoo-msft what was the resolution here again wrt #1 & #2 ?

**Comment by jwoo-msft** [comment]
> @jwoo-msft what was the resolution here again wrt #1 & #2 ?

@shalinijoshi19  for #1, there is a global setting for app that disables systems to apply system's theme. for #2, the control mechanic is iOS standard.
