### ISSUE TITLE
[Mobile][Markdown support] [Markdown with the * does not work on mobile renderers]

### ISSUE THREAD

**Issue by jpjpjp** [microsoft/AdaptiveCards#4117]
# Platform

* Android
* iOS

# Author or host

Host on Webex Teams.

Create a free Webex Teams account https://www.webex.com/team-collaboration.html to replicate using the Webex Teams iOS client. Create a space with cardSchool@webex.bot, and use the "Pick Another Lesson" button to select "Lesson 9 Buttons and Actions" to see how a Text element with markdown renders

# Version of SDK

We have our own fork of AdaptiveCards@v1.2.6

# Details

On Android a card that uses the '*' to create a list using markdon, does not render with bullets, but keeps the star:

![AndroidMarkdown](https://user-images.githubusercontent.com/4774656/83794012-54a48100-a66b-11ea-9f7a-2dc074470b60.png)

On iOS it is even worse, as the newlines at the end of each list item seem to be ignored:

![iOSMarkdown](https://user-images.githubusercontent.com/4774656/83794061-68e87e00-a66b-11ea-9a36-690a0499dfdb.png)

The JSON for this card is here: https://developer.webex.com/buttons-and-cards-designer/lesson-9

**Comment by shalinijoshi19** [comment]
This is likely a dup of #1984. @jwoo-msft / @paulcam206 / @almedina-ms can you guys confirm ?

**Comment by shalinijoshi19** [comment]
The big ask is here is simply to support '*' for lists in our markdown story; While we are at it, we might want to support '+' also ([Reference](https://daringfireball.net/projects/markdown/syntax#list)).
We do say in our [docs here](https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/text-features) that we do support bulleted lists though don't go into whether it's via hyphens only or also via asterisks '*' or '+' for that matter so it could be misleading there. @jwoo-msft / @paulcam206 what does it take to just simply support the 2 additional syntax notations for unordered lists in AC ?

**Comment by jpjpjp** [comment]
@jwoo-msft thanks for what looks like good progress on this?   I wanted to bring one thing to your attention.  Early on in our discussion on this, one suggestion was to use the hyphen instead of the star for list markdown.   

We've found that that while the mobile renderers DO support the hyphen, the JS renderer does not, so adding the star to the mobile render will give a way to create platform agnostic cards.

**Comment by matthidinger** [comment]
Reopening this, @shalinijoshi19 asked about `+` support and indeed it seems like commonmark does support this as a format. It's not immediately obvious from their default page, https://commonmark.org/help/ but looking at the commonmark spec it does indeed show the `+` syntax:

https://spec.commonmark.org/0.29/#lists

If this is an easy enough addition to the open PR I'd agree let's just get it in?

**Comment by jwoo-msft** [comment]
> The big ask is here is simply to support asterisk(*) for lists in our markdown story; While we are at it, we might want to support '+' also ([Reference](https://daringfireball.net/projects/markdown/syntax#list)).
> We do say in our [docs here](https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/text-features) that we do support bulleted lists though don't go into whether it's via hyphens only or also via asterisks '*' or '+' for that matter so it could be misleading there. @jwoo-msft / @paulcam206 what does it take to just simply support the 2 additional syntax notations for unordered lists in AC ?

didn't see the note :-)

**Comment by jwoo-msft** [comment]
> Reopening this, @shalinijoshi19 asked about `+` support and indeed it seems like commonmark does support this as a format. It's not immediately obvious from their default page, https://commonmark.org/help/ but looking at the commonmark spec it does indeed show the `+` syntax:
> 
> https://spec.commonmark.org/0.29/#lists
> 
> If this is an easy enough addition to the open PR I'd agree let's just get it in?

done
