### ISSUE TITLE
[Mobile][Inconsistency] [Date payloads from mobile and web clients are in different formats]

### ISSUE THREAD

**Issue by anbah34** [microsoft/AdaptiveCards#4118]
# Date format inconsistent across different SDKs
- [ ] Android
- [ ] iOS
- [ ] JS
- [ ] UWP
- [ ] WPF

This was raised by WorkDay

Added the screenshots
![Inconsistent date format](https://user-images.githubusercontent.com/65276405/83797784-c529bd00-a6c0-11ea-9452-ab825d607e0d.jpg)

**Comment by anbah34** [comment]
@shalinijoshi19

**Comment by shalinijoshi19** [comment]
@jwoo-msft / @paulcam206 is this a dup of #3613? Where does the original issue's fix stand? thanks!

**Comment by jwoo-msft** [comment]
@anbah34   @adumrewal @Gunashree-R-V.
We've updated our renderer as part 2.0 update a.k.a 1.3 such that renderers's input format will respect the platform's input format. Please check if this issue is fixed after 1.3 update. Thanks

**Comment by shalinijoshi19** [comment]
> @anbah34 @adumrewal @Gunashree-R-V.
> We've updated our renderer as part 2.0 update a.k.a 1.3 such that renderers's input format will respect the platform's input format. Please check if this issue is fixed after 1.3 update. Thanks

hello @anbah34 please go ahead and reactivate this issue if it still persists with our latest v1.3 artifacts.. Thanks!
