### ISSUE TITLE
[Mobile clients]Links to come in a markdown format

### ISSUE THREAD

**Issue by anbah34** [microsoft/AdaptiveCards#4119]
Issue description: In attempts to display IPs with hyperlinks within Adaptive card, the mobile app does not convert Markdown format [text](link) and displays raw string. 

Please see attachment below, Network(s) column

While on the desktop version the IPs are formatted and displayed correctly.
![link markdown](https://user-images.githubusercontent.com/65276405/83801560-fc02d180-a6c6-11ea-9140-64e36b66bb07.jpg)

**Comment by anbah34** [comment]
@shalinijoshi19

**Comment by shalinijoshi19** [comment]
@paulcam206 / @jwoo-msft this again seems to be another instance of #1984. Specifically for iOS or Android do markdown style hyperlinks not work ? @anbah34 what renderer platform are you using in your app on the desktop again?

**Comment by jwoo-msft** [comment]
@anbah34 can you share your json payload here?

thanks

**Comment by jwoo-msft** [comment]
> @paulcam206 / @jwoo-msft this again seems to be another instance of #1984. Specifically for iOS or Android do markdown style hyperlinks not work ? @anbah34 what renderer platform are you using in your app on the desktop again?

It's hard to tell what's going on without the actual payload. It's probably due to some characters inside markdown link.

**Comment by shalinijoshi19** [comment]
@anbah34 / @VikrantSingh01 this is another one that we are requesting more data for - Do you happen to have the json payload for this at all?

**Comment by jwoo-msft** [comment]
> @anbah34 / @VikrantSingh01 this is another one that we are requesting more data for - Do you happen to have the json payload for this at all?

@shalinijoshi19 
I went ahead and manually type the string from the image to the sample app. I couldn't repo this issue.

**Comment by jwoo-msft** [comment]
@anbah34 Could you please follow up with the repro steps. Especially, a payload, please?

**Comment by jwoo-msft** [comment]
@anbah34 as we have discussed. This is no repro. Please re-open the issue if this issue re-occurs.
