### ISSUE TITLE
Add editable/noneditable to input controls

### ISSUE THREAD

**Issue by tomlm** [microsoft/AdaptiveCards#412]
Sometimes you need to show selection state (via radio buttons or checkboxes) but not allow it to be modified.

**Comment by dclaux** [comment]
Showing disabled controls doesn't strike me as the right way to represent unmodifiable state... If controls could go from enabled to disabled state and back, then yes, but given we do not support that, I don't know that we need this non-editable state.

**Comment by RebeccaAnne** [comment]
This is a good suggestion, but not something that's on our roadmap at this time. We may reconsider it in the future, or if you would like to make a contribution please see our contribution guidelines [here](https://github.com/microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md).
