### ISSUE TITLE
Doc site: broken links

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/AdaptiveCards#413]
On these pages, certain links lead to a 404:

* http://adaptivecards.io/documentation/#create-GettingStarted `Card Schema reference documentation` 
* http://adaptivecards.io/documentation/#display-gettingstarted `Implement a renderer`
* http://adaptivecards.io/documentation/#resources-tools `Render2Image sample project`
* http://adaptivecards.io/documentation/#display-libraries-android _And all other platform pages_ `Implement a renderer`

I would send a PR, but It's not apparent how to form these internal URLs correctly.

**Comment by matthidinger** [comment]
Thanks Dan, I'm working on porting all of our documentation to docs.microsoft.com, the transition should be done this week

**Comment by matthidinger** [comment]
This is fixed now
