### ISSUE TITLE
[Templating/Designer] OpenGraph properties break the designer 

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#4134]
OpenGraph uses `:` in their property names and it causes the templating to fail in the Designer. Not sure if this is an issue at the templating, rendering, or designer layer. 

To repro create a card with this Sample data and try to bind a TextBlock to the `og:title` property. 

```json
{
    "og:title": "The Rock (1996)",
    "og:type": "video.movie",
    "og:url": "http://www.imdb.com/title/tt0117500/",
    "og:image": "http://ia.media-imdb.com/images/rock.jpg" 
}
```

**Comment by dclaux** [comment]
As far as I can tell, this is an Adaptive Expressions issue. Here is what I see in the console:
![image](https://user-images.githubusercontent.com/1334689/83931019-53e51b00-a74f-11ea-9f21-4515fc6fe400.png)

That message ("syntax error...") is emitted by AE.

**Comment by dclaux** [comment]
Confirmed. Exception thrown in ExpressionAntlrParser.js:
![image](https://user-images.githubusercontent.com/1334689/83931321-e508c180-a750-11ea-8125-251bb8544599.png)

**Comment by boydc2014** [comment]
@dclaux @matthidinger can you try to see if getProperty or foo["a:b"] will works in this scenario, we are using https://github.com/microsoft/botbuilder-dotnet/issues/4029 as a native support special character in top-level

**Comment by paulcam206** [comment]
Fixing this isn't currently on the roadmap.
