### ISSUE TITLE
[Designer] [Input.Attachments]

### ISSUE THREAD

**Issue by TylerOdenthal** [microsoft/AdaptiveCards#4135]
I would love to be able to request attachments in my adaptive cards!

Any thoughts on getting that done?

**Comment by TylerOdenthal** [comment]
Appreciate you guys adding it to the requests. I would probably use this feature for accepting multiple files at once and sending those files to cognitive services via HTTP in my bots.

**Comment by RebeccaAnne** [comment]
Thanks for the request! We're tracking file upload support via #3707.

**Comment by kamarajPasupathi** [comment]
Hi Guys ,

I Want to attach my file to the adaptive card from the client side .
can you guide me on how to do that?

Regards,
Kamaraj.P
