### ISSUE TITLE
[iOS-Android-UWP][Parity Issue - Fact Set] [Card with empty factSet does not render on iOS but renders on other platforms]

### ISSUE THREAD

**Issue by adumrewal** [microsoft/AdaptiveCards#4136]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [x] Android
- [x] iOS
- [x] UWP
- [x] WPF

# Author or host

Host - Teams iOS

# Version of SDK

Latest master

# Details

Card with empty factSet does not render on iOS but renders on Android and Desktop.
` { "type": "FactSet", "facts": [ ] } `

[EmptyFactSetIssue.txt](https://github.com/microsoft/AdaptiveCards/files/4744964/EmptyFactSetIssue.txt)

**Comment by shalinijoshi19** [comment]
@jwoo-msft can you take a look at this one to drive what the behavior should be here ? @dclaux / @matthidinger thoughts?
