### ISSUE TITLE
[MSTeams][iOS] Invalid Url error Action.OpenUrl

### ISSUE THREAD

**Issue by ckruszynsky** [microsoft/AdaptiveCards#4139]
# Platform
What platform is your issue or question related to? (Delete other platforms).
* iOS

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? Author

If you're an author, who are you sending cards to?
Teams

# Version of SDK

# Details
We are using PowerAutomate to post an adaptive card message to a teams channel. The adaptive card contains a button with the action.OpenUrl that points to a folder in SharePoint Document library. If the folder name in SharePoint contains a space; when the user clicks the button in Teams on iOS they are receiving a "Invalid URL" message.  However, this same action works on the desktop, web and Android versions of Teams.

**Comment by shalinijoshi19** [comment]
@jwoo-msft do we not support spaces in URL for action.OpenURL actions? Also @VikrantSingh01 / @anbah34 have you guys seen this before?

**Comment by RebeccaAnne** [comment]
@ckruszynsky are you url % encoding the spaces in your URL? If not, you need to do so to make a valid URL. If you're already doing that please reactivate. Thanks!
