### ISSUE TITLE
Doc site: allow deep links

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/AdaptiveCards#414]
Each heading in a markdown file should have a deep link so that clicking will take you to that section of the page.

For example, if someone wanted to link to the `Customization` section of the http://adaptivecards.io/documentation/#display-gettingstarted page.

**Comment by matthidinger** [comment]
We'll get this when we move to docs in a few days

**Comment by matthidinger** [comment]
This is now working with the new docs site https://docs.microsoft.com/en-us/adaptive-cards/
