### ISSUE TITLE
[.NET WPF][Templating] [Extra comma added after calling expand on templated arrays]

### ISSUE THREAD

**Issue by jbp199** [microsoft/AdaptiveCards#4141]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF

# Author or host

host - hub

If you're an author, who are you sending cards to?

# Version of SDK

AdaptiveCards Templating v1.0.0 -rc

# Details

Using templating with arrays to create multiple repetitions of the same part of a card, results in invalid JSON using the RC .net templating api. The card that is generated contains ',}' or ',]' which will fail json validation.

I've been able to workaround it using a regular expression to replace these invalid parts of the document.  

To repro, bind a container to an array in the data json, then see the output from exand().  You'll see at least one extra comma.  Right in the middle of something, but I can supply a repro if required.

**Comment by jwoo-msft** [comment]
@jbp199 thanks for reporting the issue. please share the payload.

**Comment by jbp199** [comment]
[cardrepro.zip](https://github.com/microsoft/AdaptiveCards/files/4748973/cardrepro.zip)

The card template, data and the resultant card with extra commas.

**Comment by jwoo-msft** [comment]
@jbp199 

Thanks for the sharing the payload.

I can confirm that there are extra commas. This is not a bug. WPF renderer will actually render the card. But the issue was the card contained the framework id that is not valid. id starting with number, for example, is not valid. If the dangled comma is still an issue, you can avoid it by not adding the data context ($data) as the last json pair in the json object. Rest assured, changes for avoiding dangled comma is in code review.

**Comment by jbp199** [comment]
Actually I logged in a hurry - we are using the .net HTML renderer.  I was getting an error when converting the string to AdaptiveCard:

                        AdaptiveCardTemplate transformer = new AdaptiveCardTemplate(card);
                        cardString = transformer.Expand(acData);
                        
                        //cardString = workaroundIdIssue(cardString);

                        card = JsonConvert.DeserializeObject<AdaptiveCard>(cardString);

The ids work fine and in the html allow opening and closing of the sections, but deserializing results in an error.  The commented out line is what I use to workaround it with a regular expression to find ,} and ,] and remove the commas.
