### ISSUE TITLE
[.NET WPF][Templating] escaped characters in strings in the data are not preserved escaped after calling expand()

### ISSUE THREAD

**Issue by jbp199** [microsoft/AdaptiveCards#4142]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF

# Author or host

host - hub

# Version of SDK

1.0.0 -rc templating api

# Details

We have text in some of our strings in the data that have escaped characters, mainly \n\r for new lines.  These need to be double escaped within the json document as \\n\\r however, after calling expand(), the extra escaping is lost.

To repro use a datafile that has a string, that binds to a textblock in the adaptive card, with a new line in it.  you'll need to double escape it for it to be valid, but after the expand(), the json that is created is not valid.

**Comment by jwoo-msft** [comment]
duplicate with #4137
