### ISSUE TITLE
Need alot of improvements.

### ISSUE THREAD

**Issue by dhanush-ai1990** [microsoft/AdaptiveCards#4150]
Horrible interface, Doesn't show errors, Very primitive.

My card json doesnt even load on the designer. Works fine in a python code base.

**Comment by dclaux** [comment]
Hi @dhanush-ai1990, thank you for the feedback. What would be really helpful would be to get your card payload so we can assess what the problem is and improve the designer.

**Comment by shalinijoshi19** [comment]
Thanks @dhanush-ai1990 ! +1 to @dclaux 's request for slightly more information -- including your specific card json and suggestions to improve your workflow/experience here..
