### ISSUE TITLE
[Templating] Ability to customize the binding syntax

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#4152]
The current templating syntax is `${expression}` but this may cause errors/warnings in certain usages, such as the default linting rules in `create-react-app`

`Line 91:41: Unexpected template string expression no-template-curly-in-string`

The workaround is the disable the rule in code comments

```
/*eslint-disable no-template-curly-in-string */
... template definitions go in here...
/*eslint-enable no-template-curly-in-string */
```
This was originally filed here:
https://github.com/MicrosoftDocs/AdaptiveCards/issues/292

One proposed alternative would be to customize the binding syntax at the card level, which the Templating SDKs would use to prepare processing and ensure the cards remain compatible on all hosts that use the templating SDKs.

## Schema change

```json
{
   "type": "AdaptiveCard",
   "$bindingPrefix": "@",
   "body": [
       { 
          "type": "TextBlock",
          "text": "@{myText}"
       }
   ]
}
```

## SDK Changes

The templating SDKs would look for the `$bindingPrefix` token during processing and ensure the expressions get evaluated correctly.

**Comment by dclaux** [comment]
I think this would be very helpful to a lot of developers. I would push this proposed design a bit further though, so as to allow for backward compatibility with our previous syntax during the preview phase:
```
{
   "type": "AdaptiveCard",
   "$bindingStartMarker": "{",
   "$bindingEndMarker": "}",
   "body": [
       { 
          "type": "TextBlock",
          "text": "{myText}"
       }
   ]
}
```

**Comment by WieserSoftware** [comment]
@dclaux What would the defaults be if they weren't found?
Default to the old syntax.
The new syntax would be "$bindingStartMarker": "${"
The react syntax would be "$bindingStartMaker": "@{"

Have I understood correctly?

**Comment by dclaux** [comment]
Defaults would be `${` and `}` to match the current built-in syntax. I wouldn't necessarily ban any marker, but simply document that some markers would likely not work properly.

**Comment by paulcam206** [comment]
Not currently on the roadmap
