### ISSUE TITLE
Column is missing that `type` is a required field

### ISSUE THREAD

**Issue by scottlovegrove** [microsoft/AdaptiveCards#4156]
Currently the documentation makes no mention of the fact that `"type": "Column"` is _required_ when adding a column item to a ColumnSet. It shows it in the example, but it doesn't list it in the property list like it does for every thing else.

---
* URL: https://adaptivecards.io/explorer/Column.html

**Comment by shalinijoshi19** [comment]
@matthidinger as you are making updates to the documentation, possible to pick this up?

**Comment by RebeccaAnne** [comment]
Type is not a required field for columns

**Comment by RebeccaAnne** [comment]
Type should be added to the schema for column. It is not required, but if set must be set to "Column".

**Comment by jonmill** [comment]
This should be fixed now
