### ISSUE TITLE
[.NET Renderer][Performance] Calling Visit on AdaptiveVisitor and passing in an AdaptiveToggleVisibilityAction causes an infinite loop.

### ISSUE THREAD

**Issue by DDEfromOR** [microsoft/AdaptiveCards#4164]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET

# Author or host

We are a service that supports sending Adaptive Cards between various chat clients and Azure Bots.

# Version of SDK
NuGet: AdaptiveCards v1.2.4

# Details
An analysis of crash dumps from a series of high CPU usage issues revealed an infinite loop that seems to be initiated by by calling the Visit(AdaptiveAction) function on AdaptiveVisitor when passing in an AdaptiveToggleVisibilityAction. Specifically the call on [line 142](https://github.com/microsoft/AdaptiveCards/blob/fd0d15d929a0b896c487dad3c4822b9f001a9890/source/dotnet/Library/AdaptiveCards/Rendering/AdaptiveVisitor.cs#L142) attempts to find an overload of Visit that accepts an AdaptiveToggleVisibilityAction, fails as no such overload exists, and instead matches with itself, as AdaptiveToggleVisibilityAction derives from AdaptiveAction. It looks like the other paths in this logic have sub-type specific overloads of Visit and this one was simply missed.

**Comment by shalinijoshi19** [comment]
@jwoo-msft  please prioritize. tx

**Comment by jwoo-msft** [comment]
> @jwoo-msft please prioritize. tx

@shalinijoshi19 This is not a templating issue. It's .Net Rendering issue.

**Comment by jwoo-msft** [comment]
@DDEfromOR Can you share your payload that caused this issue?

Thanks
