### ISSUE TITLE
[MSTeams][iOS] isvisible: false not working 

### ISSUE THREAD

**Issue by summertony15** [microsoft/AdaptiveCards#4165]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.
Author
If you're an author, who are you sending cards to?
Teams Bot
# Version of SDK

v1.2

# Details

When using adaptive card as a chatbot response, I set visible:false in the body but it is not working, still showing as default. For the desktop version, it works, but not working on iOS mobile.
Here is the example of my code style

{
            "contentType": "application/vnd.microsoft.card.adaptive",
            "content": {
                "type": "AdaptiveCard",
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "version": "1.2",
                "body": [
                    {
                        "type": "Input.Text",
                        "id": "activity",
                        "value": "{\"attachments\":[],\"channelId\":\"msteams\",\"serviceUrl\":\"https://smba.trafficmanager.net/apac/\",\"conversation\":{\"conversationType\":\"personal\"}",
                        "isVisible": false
                    }
                ]
            }
        }

**Comment by jwoo-msft** [comment]
Labeled issue MSTeams-Developer-Support
Justification:
It's a basic use case & it's not reproducible on sample app.

**Comment by summertony15** [comment]
Do you have any updates?
