### ISSUE TITLE
[Mobile][Usability] [No Cheveron on Action.ShowCards]

### ISSUE THREAD

**Issue by jpjpjp** [microsoft/AdaptiveCards#4167]
# Platform

- [ ] Android
- [x] iOS

# Author or host

Host on Webex Teams

# Version of SDK

We have our own fork of AdaptiveCards@v1.2.6

# Details

Action.ShowCard buttons on JS Renderer include a chevron that points down when the card is expanded and points up when the card is closed.  This helps user differentiate these types of buttons from the other types.    The mobile renderers should do something similar.

JS Render:

![JS-Render](https://user-images.githubusercontent.com/4774656/84418386-2122a300-abe5-11ea-9529-6e5a872ef6ff.png)

Android Render:

![Android-Render](https://user-images.githubusercontent.com/4774656/84418433-38fa2700-abe5-11ea-8f25-5620235d30b6.png)

ios render:

![ios-render](https://user-images.githubusercontent.com/4774656/84418471-431c2580-abe5-11ea-9f2c-2c2bf60f3905.png)

**Comment by shalinijoshi19** [comment]
@jwoo-msft this one seems to be a higher priority for Cisco. @golddove for FYI for help on the Android side.

**Comment by shalinijoshi19** [comment]
Reactivating to track fixes on the other platforms

**Comment by shalinijoshi19** [comment]
@golddove how are we looking on Android/other platforms?

**Comment by shalinijoshi19** [comment]
@golddove as part of closing this out, can you help create a separate issue to track the story on the other remaining platforms (vis .NET (WPF/HTML), UWP)? Thanks!
