### ISSUE TITLE
[.NET][Templating] Expand function doesn't handle strings with escape characters

### ISSUE THREAD

**Issue by nimercer** [microsoft/AdaptiveCards#4176]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* .NET (Templating nuget)

# Author or host

Author / Host

If you're an author, who are you sending cards to?
1.2.9

What version are you using? Ex: NuGet 1.0.2, or latest main, etc...
Templating nuget release candidate

Explain your issue. If you just have a question, please post on StackOverflow instead:

- When expanding a templated json with a concrete type, any strings within that type that contain escape characters \ or " will break the json parser.

Example:

Given this template

```
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "text": "${title}"
        }
    ]
} 
```

And expanding with a concrete type with Property

```
[JsonProperty("title")]
Title => return "Hello \ world";
```

Will result in a parsing error when the card is expanded and result in no card being displayed.

We're currently working around this issue by manually escaping all strings we use, but it would be great if the templating system could handle strings that contain escape characters.

**Comment by jwoo-msft** [comment]
@nimercer 
Hello,

Could you share which version of nuget packages you used? For example, we have 1.0.0-rc.0 and 1.0.0-rc.1. Also, can you provide the template data payload also?

**Comment by jwoo-msft** [comment]
@nimercer 

Hi, 
1.0.0-rc.1 will leave alone valid escape sequences. However, "\ " is not valid json escape sequence, and will throw. Are there any reasons that you use invalid escape sequences?

**Comment by shalinijoshi19** [comment]
@jwoo-msft let's follow up here with @nimercer (Nicola) from Cortana to understand their use case. Meanwhile let's update the WPF renderer to match the behavior of other renderers.

**Comment by nimercer** [comment]
Hi @shalinijoshi19 / @jwoo-msft - apologies for missing your comment before. 
We're using an API to pull Meeting titles and populate them into Adaptive cards using the templating system. Any meeting which contained the string '\' in the title (for example _'Schedule for the [UWP\Triage] team'_) would cause the cards to break. We're currently working around this by manually adding extra \ in the title, but obviously we're having to apply this for **all** strings we pull from external sources, just in case any of those have \ in as well.

This seems like something that could be dealt with on the templating side? 

Let me know if that makes sense/doesn't make sense :)

**Comment by arvindkannan** [comment]
Hi,
Greetings.

I too had the same issue when it comes to transaction number with escape character ('\') which causes Templating Engine Expand method to break !!

Until the fix for the above said bugs released is there any go-around to handle without card rendering being broken !

Thanks...

**Comment by nimercer** [comment]
Hi @arvindkannan - the workaround I used was to write my own custom Adaptive Expression and replace the escape string characters

```
                AdaptiveExpressions.Expression.Functions.Add("stringFormat", (args) =>
                {
                    string returnVal = args[0] ?? string.Empty;
                    returnVal = returnVal.Replace(@"\", @"\\").Replace(@"""", @"\""");
                    return returnVal;
                });
```

then use that inside my template like this:

```
               "text": "${stringFormat(stringToReplace)}"
```

**Comment by RebeccaAnne** [comment]
Please reactivate if you're still seeing this issue in the latest templating package.
