### ISSUE TITLE
Add SelectAction support to Shared model and UWP renderer

### ISSUE THREAD

**Issue by riarenas** [Microsoft/AdaptiveCards#418]
Implement the SelectAction property for Container and Image elements.

**UWP implementation status**
- [x] Container (PR #747)
- [x] ColumnSet (PR #747)
- [ ] Column
- [ ] Image

**Comment by anbare** [comment]
@matthidinger this is a key feature for toasts, should we make this milestone 1.1?

I could probably help implement the UWP code for this since it's already in the shared model if everyone else is busy

**Comment by matthidinger** [comment]
Duplicate
