### ISSUE TITLE
String only Inlines are round-tripped as full TextRuns

### ISSUE THREAD

**Issue by v-kydela** [microsoft/AdaptiveCards#4183]
# Platform

* .NET

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? Author

If you're an author, who are you sending cards to?
A console app

# Version of SDK

NuGet 1.2.4

# Details

A [rich text block](https://adaptivecards.io/explorer/RichTextBlock.html) can have strings instead of text runs in its inlines property. However, the strings get deserialized into text runs because the .NET library treats the inlines property as a `List<IAdaptiveInline>` (which can't contain strings of course). The only type that implements `IAdaptiveInline` is `TextRun` so strings have to be deserialized as text runs, but then they can't be reserialized as strings.

```c#
var json = "{'type':'AdaptiveCard','version':'1.0','body':[{'type':'RichTextBlock','inlines':['Inline string']}]}";
var card = AdaptiveCard.FromJson(json).Card;

Console.WriteLine(card.ToJson());
// {
//   "type": "AdaptiveCard",
//   "version": "1.0",
//   "body": [
//     {
//       "type": "RichTextBlock",
//       "inlines": [
//         {
//           "type": "TextRun",
//           "text": "Inline string"
//         }
//       ]
//     }
//   ]
// }
```

I can see two ways to fix this:

1. Automatically serialize text runs as strings if the only populated property is `text`.
2. Create a new type that implements `IAdaptiveInline` to represent strings.

**Comment by shalinijoshi19** [comment]
@RebeccaAnne can you take a look at this one to investigate ?

**Comment by RebeccaAnne** [comment]
@v-kydela, can you tell me more about the scenario where the current behavior causes problems for you? The string version of the inline is meant as a convenience for card authors, but the meaning is the same as a TextRun with no additional properties, so the card information is maintained even if the form has changed.

Serializing text runs with only text as strings would be a reasonable behavior, just trying to understand the scenario better. Thanks!

**Comment by v-kydela** [comment]
@RebeccaAnne - Those are good points. It's been a while since I've thought about this, but I think I remember a customer just being confused about how to represent string inlines as C# objects.

**Comment by v-kydela** [comment]
Actually on further consideration, automatically serializing text runs as strings wouldn't fix the problem if the problem is making sure the JSON can be round-tripped consistently. Maybe a better solution is to put something in the documentation to keep people from getting confused.

**Comment by RebeccaAnne** [comment]
@v-kydela That seems reasonable, we can look at a documentation update on this topic to make sure it's clear that the string form is just a short-hand for a TextRun with no additional properties. I don't think it's necessarily a goal for the round tripped json to be identical to the json coming in, only that the card it represents is the same. For always outputting the string form I was thinking that might help if there was a verbosity concern, which is why I asked about the scenario, but it doesn't seem like that's the issue. I'll mark this for a doc update. Thanks!

**Comment by shalinijoshi19** [comment]
@RebeccaAnne is this still on track to getting in for 20.10?
