### ISSUE TITLE
Remove long/short support for TIME

### ISSUE THREAD

**Issue by dclaux** [Microsoft/AdaptiveCards#419]
# Implementation status
- [X] TypeScript
- [ ] UWP
- [ ] WPF
- [ ] iOS
- [ ] Android
- [ ] Documentation

# Problem
Long/short formats in the TIME function are unnecessary given they only control whether or not seconds are displayed.

# Solution
Remove support for long/short formats from the TIME function.

**Comment by matthidinger** [comment]
Any thoughts on this? I'm OK removing it unless we decide we need it

**Comment by matthidinger** [comment]
Tracking this issue with #908
