### ISSUE TITLE
 $root: not taking dynamic data

### ISSUE THREAD

**Issue by RashmiMithun** [microsoft/AdaptiveCards#4191]
i am unable to use the templating, i tried to have the data in var and loaded to the root it is not working

```javascript
    var obj = { name: "John" };
    var myJSON = JSON.stringify(obj);
    // Create a Template instance from the template payload
var template = new ACData.Template(jsonTemplate);
 
// Expand the template with your `$root` data object.
// This binds it to the data and produces the final Adaptive Card payload
var cardPayload = template.expand({
   $root: {
    myJSON
   }
});
```

**Comment by shalinijoshi19** [comment]
@RashmiMithun can you elaborate on what version and platform of the templating SDK you are using?

**Comment by RashmiMithun** [comment]
Hi Shalini
I have fixed this issue, but i have one question how to bind Input.Time with 12hrs format with AM/PM.
Could you please help me
