### ISSUE TITLE
[UWP] Unnecessary string copying

### ISSUE THREAD

**Issue by chriche-ms** [microsoft/AdaptiveCards#4198]
# Platform

* Android
* iOS
* UWP

# Author or host

Author and host. Cortana in Windows - app is both an author and host.

# Version of SDK

NuGet 1.2.8

# Details

Many C++ functions accept std::string parameters by value when they should really be by const-ref or r-value ref. Updating the parameter types would help improve performance by reducing the number of string copies made during parsing and rendering.

**Comment by shalinijoshi19** [comment]
@paulcam206 / @RebeccaAnne to help review this and shepherd it into main where it can bake for a bit until we push out the July refresh.
