### ISSUE TITLE
Designer - Shows that Teams doesn't support 1.2v

### ISSUE THREAD

**Issue by cconrado** [microsoft/AdaptiveCards#4199]
Teams does support 1.2v
![image](https://user-images.githubusercontent.com/9168464/85214984-ee408380-b337-11ea-91c0-6fe797ef5c91.png)

**Comment by dclaux** [comment]
@cconrado I can repro this on https://vnext.adaptivecards.io/designer but not on https://adaptivecards.io/designer
I think vNext is a bit out of date, and in any case the main site currently represents the latest. @matthidinger do you know what might be happening on vNext?

**Comment by cconrado** [comment]
@dclaux ah that's right I tried it on vnext.

**Comment by shalinijoshi19** [comment]
@matthidinger / @Paulcam206 / @dclaux  - longer term we should get together to try to figure out a story for what and where vnext gets deployed from and for what purpose..

**Comment by DeeJayTC** [comment]
Why don't you guys add a beta branch, 
deploy changes to there first and only merge beta -> main?

main -> www.adaptivecards.io
beta -> vnext.adaptivecards.io 

Thats what i usually do at least, based on that vnext would always be at least same as main most likely have more things however.

**Comment by dclaux** [comment]
@deejaytc that's what it's supposed to be basically. Not sure why vnext seems to be behind main though at the moment.

**Comment by DeeJayTC** [comment]
Deployment failed maybe?

**Comment by shalinijoshi19** [comment]
@DeeJayTC we'll be debugging and and get back to you on this one on what is going in here. Thanks a ton for your patience!
