### ISSUE TITLE
[JavaScript][rendering] [Input.Date not correctly rendered in Teams ]

### ISSUE THREAD

**Issue by MouadhDos** [microsoft/AdaptiveCards#4200]
the properties "min" and "max" , of Input.Date not correctly rendered in Teams channel .

**Comment by shalinijoshi19** [comment]
@MouadhDos can you share a little bit more context here? Is this a regression that you are observing in your scenario? What is the version of Teams you are working with where you are observing this behavior (do you have screenshots?) , what's your card payload look like etc? @siduppal / @VikrantSingh01 are you aware of a recent regression on any of the platforms around AdaptiveCards Input.Date at all?
