### ISSUE TITLE
Datetime control in outlook actionable messages adaptive cards to record back-dated datetime transactions 

### ISSUE THREAD

**Issue by Vishnuvk33** [microsoft/AdaptiveCards#4214]
Hi,
Need a  Date-time control in outlook actionable messages adaptive cards to record back-dated transactions with time.
So that user entered date-time value will be converted in to GMT with reference to client time zone.
 
Thanks,
Vishnukumar M

**Comment by dclaux** [comment]
@Vishnuvk33 you can use a Date input plus make your own time input using two ChoiceSet (for hours and minutes). Ideally the AC Time input would be supported in Outlook, but at the moment it is not.

[As I outlined here](https://github.com/microsoft/AdaptiveCards/issues/4186), the team is working on a fix that will give you the time zone offset for the date value.

All in all that should allow you to do what you want.

**Comment by shalinijoshi19** [comment]
@Vishnuvk33 please do take a look at @dclaux 's response above and reactivate or file a separate one in case this doesn't work. I am dup'ing this to #4186
