### ISSUE TITLE
[iOS][InputFiedl - Keyboard] [Japanese keyboard is not working properly with ACRTextField input field]

### ISSUE THREAD

**Issue by adumrewal** [microsoft/AdaptiveCards#4215]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Host - Team iOS

# Version of SDK

1.2.7

# Details

Default Japanese Keyboard font changes to English font inside ACRTextField input fields. Works fine with ACRTextView input fields.

Repro steps:
- Add Japanese keyboard as one of your keyboards
- Tap on multi line input field and try changing language to Japanese -> This works fine
- Tap on single line input field and try changing language to Japanese -> Notice a different Japanese keyboard pops up this time with default English script.
PFA the screenshots of the two different keyboards.

|Expected|Actual|
|:-:|:-:|
|<img src="https://user-images.githubusercontent.com/8917620/85509841-41565700-b614-11ea-96fa-f19056a8139a.png" alt="drawing" width="250"/> | <img src="https://user-images.githubusercontent.com/8917620/85509856-461b0b00-b614-11ea-9523-c7e55050738e.png" alt="drawing" width="250"/>|

**Comment by shalinijoshi19** [comment]
@jwoo-msft can you help me understand the nature of changes involved here? Thanks!
