### ISSUE TITLE
[iOS][Font color - Input Fields] [Font color in ACRTextView gets overwritten]

### ISSUE THREAD

**Issue by adumrewal** [microsoft/AdaptiveCards#4216]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Host - Teams iOS

# Version of SDK

1.2.7

# Details
Issues:
- ACRTextView overwrites the defined font color in the following function:
```
- (void)textViewDidBeginEditing:(UITextView *)textView
{
    if (_placeholderText && [textView.text isEqualToString:_placeholderText]) {
        textView.text = @"";
        textView.textColor = [UIColor blackColor];
    }
    [textView becomeFirstResponder];
}
```
- Input field background color changes based on the system theme instead of app theme
- Keyboard appearance changes based on system theme

These issues are critical when the user is on iOS 13 with System Dark Theme enabled.
PFA the screenshot:
<img src="https://user-images.githubusercontent.com/8917620/85512537-a2335e80-b617-11ea-8f3d-e952f357e347.png" alt="drawing" width="250"/>

**Comment by jwoo-msft** [comment]
@adumrewal thanks for reporting the issue.
