### ISSUE TITLE
[iOS & Android][rendering][IsVisible toggling not rendering now visible element correctly ]

### ISSUE THREAD

**Issue by icatchx22i** [microsoft/AdaptiveCards#4226]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android
* iOS

# Author
Sending to Teams iOS version 2.0.14 with and without developers preview. As well as Android, latest version.

# Version of SDK: 
JS - v1.6.0

# Details

We use a collapsed view of our cards to show our users only the most relevant information then allow them to ToggleVisibility on additional information. This worked perfectly fine until recently. Now it appears the elements that were initially set to isVisible:false do not get rendered correctly when toggled to true.

We tested this on new cards as well as cards that were previously sent by the system to the mobile device. This is happening in both v1.0 and verison 1.2 of the schema

Steps to reproduce: 

1. go to: https://amdesigner.azurewebsites.net/
2. select the Expense Approval sample
3. copy the JSON payload 
4. use the App Studio within Teams to send yourself this card
5. observe expanding sections load correctly on the Desktop - ok
6. view same card on mobile app (just checked again on ios13.5.1) and notice that when expanding hidden panels they over lay with other ones, overall height is not adjusted - KO

**Comment by shalinijoshi19** [comment]
@VikrantSingh01 / @anbah34 / @Aditya0603 have you guys seen reports of this issue wiht Teams mobile again?

**Comment by icatchx22i** [comment]
@shalinijoshi19 Any update on this issue? thank you

**Comment by jwoo-msft** [comment]
@icatchx22i 
This card won't load as it is for iOS and Android because parsing the payload will fail due to id collisions.
there are a few IDs that share the IDs.
c.c @jonmill

**Comment by jwoo-msft** [comment]
closing this issue as it is being tracked by #6015
