### ISSUE TITLE
[Desktop/Mobile][Render] Mobile render cutts off adaptive card text

### ISSUE THREAD

**Issue by dvehapetian** [microsoft/AdaptiveCards#4228]
# Platform

What platform is your issue or question related to? 
* Android
* iOS

# Details
Viewing a adaptive card on the Teams mobile client, specifically IOS devices, the content of the card is cut-off. This happens especially in cases where the adaptive card is a reply of another post but can also happen in some top level threads as well. There are some examples attached, in this image you can see that the top text "NOC - Declared an update..." gets cut off in the mobile version but not on the desktop client.

The same adaptive card on Desktop vs IOS:
![MicrosoftTeams-image - Desktop](https://user-images.githubusercontent.com/67475652/85877870-d0df3f80-b7a5-11ea-9c22-b153020c7ea8.jpg)

![MicrosoftTeams-image - IOS](https://user-images.githubusercontent.com/67475652/85877017-88735200-b7a4-11ea-8efd-82227bd6dea5.png)

**Comment by shalinijoshi19** [comment]
@anbah34 / @VikrantSingh01 / @aditya0603 have you guys seen reports of this at all?

**Comment by shalinijoshi19** [comment]
@dvehapetian can you share the sample card that you are working with please?tx

**Comment by RebeccaAnne** [comment]
Please re-activate with a sample card if this is still repro-ing for you.
