### ISSUE TITLE
[UWP][InputValidation] Focus not set on toggle input when validation fails

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#4229]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP
* (See also #4230 for JS)

# Details

Using the toggle test card below, if the required toggle is not checked, on submit, the keyboard focus is not set on the toggle input.

Expected behavior:
![image](https://user-images.githubusercontent.com/9091833/85886914-be600880-b79b-11ea-9a08-2b2e4e4d81c3.png)

Actual behavior:
![image](https://user-images.githubusercontent.com/9091833/85886958-cc158e00-b79b-11ea-99af-c671bc770581.png)

Json:
```json
{
	"type": "AdaptiveCard",
	"version": "1.3",
	"body": [
		{
			"type": "Input.Toggle",
			"label": "Not Required",
			"title": "Toggle!",
			"id": "notRequired"
		},
		{
			"type": "Input.Toggle",
			"label": "Required",
			"title": "Toggle!",
			"id": "required",
			"isRequired": true,
			"errorMessage": "This toggle is required!"
		}
	],
	"actions": [
		{
			"type": "Action.Submit",
			"title": "Send!"
		}
	]
}
```

**Comment by RebeccaAnne** [comment]
Actually, it turns out focus is actually on the toggle in some way, in that if i hit the space bar that toggle is toggled. There's just no visible indication that focus has been set there as there is when using keyboard navigation. The toggle is also not scrolled into view if it's currently off screen.

**Comment by paulcam206** [comment]
taking a look at this one :)

**Comment by paulcam206** [comment]
I think this is by design -- keyboard focus **is** indicated if you use the keyboard to invoke the submit action.
