### ISSUE TITLE
[Android] Action.Submit crashes when no inputs

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#4235]
# Platform

* Android

# Details

Using the card [Action.ShowCard.json] (https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Elements/Action.ShowCard.json) the android mobile app crashes when the "Neat" button is clicked

**Comment by RebeccaAnne** [comment]
The issue is caused by a submit action in a nested card.
