### ISSUE TITLE
Action buttons not responding in web page

### ISSUE THREAD

**Issue by gitmenonsandu** [Microsoft/AdaptiveCards#424]
<code>
  "actions": [

    {
      "type": "Action.OpenUrl",
      "method": "POST",
      "url": "http://google.com,",
      "title": "Create Meeting"
    },
    {
      "type": "Action.OpenUrl",
      "method": "POST",
      "url": "http://google.com",
      "title": "Dismiss"
    }]
</code>

I have my adaptiveCards running in my web application (not bot or any renderer). 
When I click the action button, there is no response.

**Comment by danmarshall** [comment]
You will need to add some global event handlers:
```
AdaptiveCards.AdaptiveCard.onExecuteAction = <your onExecuteAction event handler>;
AdaptiveCards.AdaptiveCard.onShowPopupCard = <your onShowPopupCard event handler>;
```

**Comment by danmarshall** [comment]
see http://adaptivecards.io/documentation/#display-libraries-htmlclient

**Comment by gitmenonsandu** [comment]
Thank you very much.

**Comment by Kikketer** [comment]
@danmarshall The `onShowPopupCard` callback isn't documented on that htmlclient page.  I had to step through the code to find it.  Should I open a new "documentation feature" request/issue to have it added?

**Comment by danmarshall** [comment]
@kikketer yes, please! :)
