### ISSUE TITLE
Add Actions bar to Container

### ISSUE THREAD

**Issue by riarenas** [Microsoft/AdaptiveCards#425]

**Comment by riarenas** [comment]
As of the current schema, Container does not have an action array.

**Comment by jorenl** [comment]
The Schema Explorer documentation page on Container lists an actions property.
http://adaptivecards.io/explorer/#Container

**Comment by dclaux** [comment]
This is an error in the documentation - there is no "actions" property on Container. To add actions to a container, use the ActionSet element.
