### ISSUE TITLE
data binding to $index fails 

### ISSUE THREAD

**Issue by IntranetFactory** [microsoft/AdaptiveCards#4260]
I use the following card definition in the online designer. $index in ` "$when": "${$index < 3}",` works as expected, the 4th item is not shown. But the $index in `"l${$index+1} = ${id}` doesn't work, $index is always 0.

How can I use the $index of the current element in my expression?

```json
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Container",
            "$data":  [{"id":"l1"},{"id":"l2"},{"id":"l3"},{"id":"l4"}],
            "$when": "${$index < 3}",
            "items": [
                {
                    "type": "ColumnSet",
                    "columns": [
                        {
                            "type": "Column",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "l${$index+1} = ${id}",
                                    "wrap": true,
                                    "size": "Medium"
                                }
                            ],
                            "width": "stretch",
                            "verticalContentAlignment": "Center"
                        }
                    ]
                }
            ],
            "separator": true,
            "id": "first-container",
            "style": "good"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2"
}
```

actual result:
![image](https://user-images.githubusercontent.com/7462342/86172491-6d7a4800-baec-11ea-963b-e83cccf3b3de.png)

expected result:
l1 = l1
l2 = l2
l3 = l3

**Comment by dclaux** [comment]
@IntranetFactory thanks for reporting. I can repro on adaptivecards.io/designer, but not locally from compiled code. I believe I fixed this bug some time ago and it's likely the web site hasn't been updated yet. @matthidinger?

**Comment by shalinijoshi19** [comment]
@dclaux do you know the issue# to help track the fix?

**Comment by IntranetFactory** [comment]
When I try the same card in cdn.html running on localhost preview does not work at all. I think that cdn.html uses the latest version so I couldn't verify if it's fixed in latest  `<script src="https://unpkg.com/adaptivecards-designer@latest/dist/adaptivecards-designer.min.js"></script>`     

![image](https://user-images.githubusercontent.com/7462342/86175766-e62fd300-baf1-11ea-8119-199422f59c69.png)

**Comment by dclaux** [comment]
@IntranetFactory as far as I can tell from the screenshot, you are not in preview mode, so it indeed won't work. But anyway, I am not sure a package with the fix has been published yet. The locally compiled code doesn't have the problem.

**Comment by dclaux** [comment]
@shalinijoshi19 sorry, I don't. I believe it was part of a bigger set of changes.

**Comment by shalinijoshi19** [comment]
@IntranetFactory we recently released the latest version of the designer which should have these fixes - can you please try the latest version at https://www.npmjs.com/package/adaptivecards-designer and let us know if you continue to see this issue? Thanks!

**Comment by IntranetFactory** [comment]
It works now. Thank you.
