### ISSUE TITLE
data binding to boolean expression fails

### ISSUE THREAD

**Issue by IntranetFactory** [microsoft/AdaptiveCards#4261]
I need to bind `isVisible` to an expression returning a boolean.

When I use the expression `"text": "n = ${count(records)}, visible ${count(records)>10}",`  and records[] contains 7 objects I get, as expected `false` for `${count(records)>10}` :
![image](https://user-images.githubusercontent.com/7462342/86174598-f3e45900-baef-11ea-92e5-25eff91d81e2.png)

But how can I now bind that to `isVisible`?

` "isVisible": ${count(records)>10}`   is not valid json
` "isVisible": "${count(records)>10}"`  seems to evaluate to true, at least the text is visible

![image](https://user-images.githubusercontent.com/7462342/86174254-4ffaad80-baef-11ea-973a-2e807f7ed8f9.png)

**Comment by shalinijoshi19** [comment]
@dclaux could you take a first pass? tx

**Comment by shalinijoshi19** [comment]
Hello @IntranetFactory we recently released an updated version of the designer package here https://www.npmjs.com/package/adaptivecards-designer; Could you please retry and let us know if this works now for you? Thanks

**Comment by IntranetFactory** [comment]
Problem still exists.  I was even unable to bind any bool (see https://github.com/microsoft/AdaptiveCards/issues/4350)   so I think problem is not only a boolean expression, but all bool data.
