### ISSUE TITLE
Designer preview fails in cdn.html sample

### ISSUE THREAD

**Issue by IntranetFactory** [microsoft/AdaptiveCards#4264]
When I try preview in cdn.html running on localhost preview does not work at all. I think that cdn.html uses the latest version   `<script src="https://unpkg.com/adaptivecards-designer@latest/dist/adaptivecards-designer.min.js"></script>`     

When Preview is clicked console shows the following entry twice:
`Template expansion error: Cannot read property 'dataType' of undefined card-designer-surface.ts:345 `

![image](https://user-images.githubusercontent.com/7462342/86175766-e62fd300-baf1-11ea-8119-199422f59c69.png)

**Comment by shalinijoshi19** [comment]
Hello @IntranetFactory we recently released an updated version of the designer package here https://www.npmjs.com/package/adaptivecards-designer; Could you please retry and let us know if this works now for you? Thanks
