### ISSUE TITLE
[Android][MarkDown] [strong emphasis at the end is not covered]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#4269]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android

# Version of SDK
feature/inputEvolution

# Details
```json
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "text": "**test1** **test2**"
        }
    ]
}
```

The card has text that have strong emphasis. test1 will become bold as it should, but test2 doesn't get bold. This is not reproducible on iOS.

**Comment by almedina-ms** [comment]
what do you mean by not reproducible? Do you mean to say that in iOS it works as expected?

**Comment by jwoo-msft** [comment]
> what do you mean by not reproducible? Do you mean to say that in iOS it works as expected?

yes

**Comment by almedina-ms** [comment]
progress update: something is failing on the MarkDownParser GenerateHtml method, UWP works as expected so it may be a compiler issue

**Comment by almedina-ms** [comment]
another progress update: expected behaviour happens in emulators, just not in devices

![image](https://user-images.githubusercontent.com/35784165/86637406-4909ea00-bf8a-11ea-818b-3822f3ed6cdb.png)

**Comment by jwoo-msft** [comment]
@almedina-ms that's interesting find

**Comment by shalinijoshi19** [comment]
@almedina-ms is this an Inputs issue?

**Comment by almedina-ms** [comment]
should we mark this one as to fix for 1.3, it seems like this bug has been hanging around for a while now

**Comment by shalinijoshi19** [comment]
Not a ship blocker for 20.07;

**Comment by golddove** [comment]
Possibly related to #4463

**Comment by jonmill** [comment]
Should be fixed in the latest versions
