### ISSUE TITLE
We should use the json-ld standard syntax for our "type" property

### ISSUE THREAD

**Issue by dclaux** [microsoft/AdaptiveCards#427]
json-ld calls for "@type" as the property name for a strongly typed json object. We shouldn't reinvent typing, we should use the one standard the industry uses.

**Comment by rektide** [comment]
I'd never heard of adaptive cards until [watching the BUILD 2017 video](https://docs.microsoft.com/en-us/adaptive-cards/?WT.mc_id=twitter). My ears pricked up around 19m in, hearing:

> what we're trying to do is skirt this line, between semantic information, & structural layout. we tried to go full semantic but...

I realize these are all abstract concepts, but this line specifically filled me with a lot of hope, that there would be some good semantic tech under the hood. Finding a lack of json-ld, and your own hand-rolled "type" property shortly thereafter was a major cool-down on my excitement, left me wishing a little more respect had been put in for dealing with the rest of the semantic world.

Using JSON-LD would be a huge indicator that this is tech we can & should take for real, to me. Not inventing your own "type" would be good. Having a JSON-LD contexts would be a very nice :+1: sign.

**Comment by BigBlueHat** [comment]
I noticed the `@type` and `@context` in the examples here: https://docs.microsoft.com/en-us/outlook/actionable-messages/actionable-messages-via-connectors

FWIW, `type` can be aliased to `@type`, so either one of those can be used.

Also, I'm co-chair of the [JSON-LD WG](https://www.w3.org/2018/json-ld-wg/) at the W3C, and would be happy to help explore what's needed/missing/wanted from JSON-LD wrt to implementing AdaptiveCards.

Cheers!
🎩

**Comment by matthidinger** [comment]
Hi @BigBlueHat - thanks for the feedback! I think it would be great if we could connect on this topic. Mind if I reach out via email?

**Comment by BigBlueHat** [comment]
@matthidinger please do! It's on my GitHub profile. Write anytime. 😄

**Comment by dclaux** [comment]
@matthidinger please include me in the thread.

**Comment by BigBlueHat** [comment]
@matthidinger @dclaux thought of this thread again recently and thought I'd stop by and say "hi" and see if y'all would still like to chat about JSON-LD. The JSON-LD 1.1 spec is headed into "Candidate Recommendation" soon https://w3c.github.io/json-ld-syntax/ Among other things it includes a normative text about embedding JSON-LD into HTML (and extracting it) which could be useful for discovery of "cards" within an HTML-constructed UX.

Happy to chat whenever works for y'all.

Cheers!
🎩

**Comment by matthidinger** [comment]
Hey @BigBlueHat, thanks for the ping. I actually emailed you on 10/31/18 but it potentially went to spam or I sent to the wrong address. I just replied to the mail in case it went to spam, maybe you'll see something now? If not, can you email my firstname.lastname at microsoft? Would love to sync up on this!
