### ISSUE TITLE
[UWP][Documentation] There's no documentation for parser extensibility

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#4272]
# Platform

* UWP

# Version of SDK

main

# Details

Documentation on how to create a custom element does not exist and there are no samples on the visualizer app. UWP is not self explanatory when creating a custom element so new users may not use this feature

**Comment by shalinijoshi19** [comment]
@almedina-ms this is not a blocker for Inputs v1 per-se right? @RebeccaAnne are we looking to addressing this for the July refresh milestone irrespective?

**Comment by RebeccaAnne** [comment]
> @almedina-ms this is not a blocker for Inputs v1 per-se right? @RebeccaAnne are we looking to addressing this for the July refresh milestone irrespective?

Correct, this is a general documentation issue not related to inputs. I don't think this needs to go into the July release.

**Comment by paulcam206** [comment]
#6316 👀
