### ISSUE TITLE
[WPF][Input Evolution] [Number Validation Doesn't Work]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#4276]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF

# Version of SDK
feature/inputEvolution

# Details
**Payload**
https://github.com/microsoft/AdaptiveCards/blob/feature/inputEvolution/samples/v1.3/Elements/Input.Number.ErrorMessage.json

if number is inputted greater than max, the number is divided by 10 until it's within the range by app. 

Similar things happen for min check, it will insert last valid number. If submit button is pressed, cards will get submitted and produce no error messages.

**Comment by almedina-ms** [comment]
Adding more context here, the input number doesn't get cut when submit is pressed, it happens when the input loses focus
