### ISSUE TITLE
[Schema] Input.ChoiceSet could be more succinct with optional title 

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#4278]
Some products and partners are really focused on minimizing payload size. In many cases the for an `Input.ChoiceSet` the `title` and `value` may be the same content. 

## Shema changes

- `title` would change to `required: false`
- If a title is omitted, the `value` will be used 

### Example

```json
{
    "choices": [
        {
            "value": "Red"
        },
        {
            "value": "Green"
        },
        {
            "value": "Blue"
        }
    ]
}
```

We could go even further and allow something like this:

```json
{
    "choices": [
        "Red",
        "Green",
        "Blue"
    ]
}
```

**Comment by dclaux** [comment]
Sounds good to me.

I don't understand this statement though:
> `title` would change to `required: false`

This would have to be possible too I believe:
```
"choices": [
    "Red",
    { "title": "Light green", "value": "LightGreen" },
    "Blue"
]
```

**Comment by RebeccaAnne** [comment]
This is not currently on our roadmap
