### ISSUE TITLE
[iOS/Android][backgroundImage] Lookup native element of backgroundImage by including `id` in JSON

### ISSUE THREAD

**Issue by adamrangs** [microsoft/AdaptiveCards#4286]
**What platform is your feature request related to? (Delete other platforms).**
* Android
* iOS

**Is your feature request related to a problem? Please describe.**
I would like to add a background image retrospectively (post-render) by querying the view hierarchy using an `id`.  Currently the JSON payload for a card does not support including an `id` for backgroundImage. 

**Describe the solution you'd like**
The JSON payload needs to have a new `id` property.  We should be able to query the view hierarchy, post-render, using iOS/Android native API `viewByTag()` which returns the view associated with that tag (i.e. the `id` here)

**Describe alternatives you've considered**
There are no alternatives since this functionality is already available for elements in the `body` but not elements in the `AdaptiveCard` level.

**Additional context**
None

**Comment by shalinijoshi19** [comment]
@jwoo-msft / @golddove have we been doing any work here that you are aware of for this issue ?

**Comment by golddove** [comment]
@shalinijoshi19 Cisco confirmed they were able to address their use case by using resource resolvers rather than directly accessing the views.
