### ISSUE TITLE
http://adaptivecards.io/samples/#StockUpdate > Error in example card layout

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/AdaptiveCards#429]
There is a layout error in the Stock Update sample card available at http://adaptivecards.io/samples/#StockUpdate

![adaptive cards example - stock update layout error](https://user-images.githubusercontent.com/3075047/27153525-a6fe23b0-5106-11e7-9286-bc7311874dc4.png)

**Comment by matthidinger** [comment]
Thanks! this has been fixed now
