### ISSUE TITLE
ActionSet Schema data, incorrect description

### ISSUE THREAD

**Issue by scottlovegrove** [microsoft/AdaptiveCards#4294]
The description for `actions` is incorrect. It currently says:

> The array of Image elements to show.

It should probably say:

> The array of Action elements to show.

---
* URL: https://adaptivecards.io/explorer/ActionSet.html

**Comment by matthidinger** [comment]
Thanks for reporting! This is fixed in `main` and will be published to prod this week.

* URL: http://adaptivecards-ci.azurewebsites.net/explorer/ActionSet.html
