### ISSUE TITLE
[MS Teams][Rendering] [Desctructive button type not rendered correctly]

### ISSUE THREAD

**Issue by scottlovegrove** [microsoft/AdaptiveCards#4296]
# Author or host

Author

If you're an author, who are you sending cards to?

Sending to Microsoft Teams

# Version of SDK

No SDK.

# Details

This particular issue is how an Action is rendered, when outside the "actions" area in Teams. 

If you use the following Adaptive Card json https://pastebin.com/MpdumUjh in the designer, this renders correctly
![image](https://user-images.githubusercontent.com/25244878/86482670-52a50f00-bd4a-11ea-9a97-75f222788b95.png)

But in teams, the signout button is rendered as a positive style, rather than the provided destructive style
![image](https://user-images.githubusercontent.com/25244878/86482701-63ee1b80-bd4a-11ea-9b26-dbbc57663ac5.png)

If you include the same Action json as part of the "actions" content, it renders correctly, for some reason, but not when it's in an ActionSet. When included in the "actions" section, it renders like this (which is the correct button style)
![image](https://user-images.githubusercontent.com/25244878/86482750-75cfbe80-bd4a-11ea-953e-951d3343ed8b.png)

**Comment by scottlovegrove** [comment]
In case the pastebin link disappears, the full json is as follows:

```json
{
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [{
            "type": "ColumnSet",
            "columns": [{
                    "type": "Column",
                    "items": [{
                            "type": "TextBlock",
                            "text": "Task content",
                            "isSubtle": true,
                            "size": "small"
                        }, {
                            "type": "Input.Text",
                            "id": "content",
                            "placeholder": "What do you want to get done?",
                            "value": "This is some task that I want you to do do, so go add it somewhere"
                        }
                    ]
                }
            ]
        }, {
            "type": "TextBlock",
            "text": "Project",
            "isSubtle": true,
            "size": "small"
        }, {
            "type": "Input.ChoiceSet",
            "id": "project",
            "value": "Inbox",
            "choices": [{
                    "title": "Inbox",
                    "value": "Inbox"
                }
            ]
        }, {
            "type": "TextBlock",
            "text": "Priority",
            "isSubtle": true,
            "size": "small"
        }, {
            "type": "Input.ChoiceSet",
            "id": "priority",
            "value": 4,
            "choices": [{
                    "title": "Priority 1 (Highest)",
                    "value": 1
                }, {
                    "title": "Priority 2",
                    "value": 2
                }, {
                    "title": "Priority 3",
                    "value": 3
                }, {
                    "title": "Priority 4 (Normal)",
                    "value": 4
                }
            ]
        }, {
            "type": "TextBlock",
            "text": "Due date (optional)",
            "isSubtle": true,
            "size": "small"
        }, {
            "type": "Input.ChoiceSet",
            "id": "datestring",
            "choices": [{
                    "title": "No due date",
                    "value": ""
                }, {
                    "title": "Today",
                    "value": "Today"
                }, {
                    "title": "Tomorrow",
                    "value": "Tomorrow"
                }, {
                    "title": "Next workday",
                    "value": "Next workday"
                }, {
                    "title": "Next week",
                    "value": "Next week"
                }
            ]
        }, {
            "spacing": "extraLarge",
            "type": "ColumnSet",
            "columns": [{
                    "type": "Column",
                    "width": "auto",
                    "items": [{
                            "type": "ActionSet",
                            "actions": [{
                                    "title": "Sign out",
                                    "style": "destructive",
                                    "type": "Action.Submit",
                                    "data": {
                                        "actionType": "signout"
                                    }
                                }
                            ]
                        }
                    ]
                }, {
                    "type": "Column",
                    "width": "stretch",
                    "items": [{
                            "type": "TextBlock",
                            "text": " "
                        }
                    ]
                }, {
                    "type": "Column",
                    "width": "auto",
                    "horizontalAlignment": "right",
                    "items": [{
                            "type": "ActionSet",
                            "actions": [{
                                    "title": "Add",
                                    "type": "Action.Submit",
                                    "data": {
                                        "actionType": "add_task",
                                        "timeStamp": "2020-07-03T13:09:57.842000+01:00",
                                        "timeOffset": "+01:00"
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```

**Comment by shalinijoshi19** [comment]
@siduppal could you help investigate this one from the Teams side please? thanks!

**Comment by Trinetra-MSFT** [comment]
@scottlovegrove , We can repro this at our end, We have filed a Bug for this. 
Adaptive Card Designer:
![image](https://user-images.githubusercontent.com/50989436/87126762-67cdf080-c2aa-11ea-9193-7c4fa3562341.png)

Adaptive Card in Teams
![image](https://user-images.githubusercontent.com/50989436/87126157-59cba000-c2a9-11ea-9e8d-93b897c78a89.png)

**Comment by Trinetra-MSFT** [comment]
There's no destructive design for buttons in Teams yet.

**Comment by markscottmckenna** [comment]
Might there be a timeline for supporting positive/destructive action styles in Teams? The styles are part of the 1.2 schema. 

Currently I see this if it helps anyone:

`{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "wrap": true,
            "text": "The positive/destructive action styles work correctly in Bot Emulator but not in MS Teams."
        },
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.Submit",
                    "style": "positive",
                    "title": "ActionSet Positive"
                },
                {
                    "type": "Action.Submit",
                    "style": "destructive",
                    "title": "ActionSet Destructive"
                },
                {
                    "type": "Action.Submit",
                    "title": "ActionSet None"
                }
            ]
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "style": "positive",
            "title": "Card Positive"
        },
        {
            "type": "Action.Submit",
            "style": "destructive",
            "title": "Card Destructive"
        },
        {
            "type": "Action.Submit",
            "title": "Card None"
        }
    ]
}
`

Emulator
![image](https://user-images.githubusercontent.com/66265462/97037905-f9026380-1537-11eb-8916-1425e599d327.png)

Teams/Windows
![image](https://user-images.githubusercontent.com/66265462/97037985-1a634f80-1538-11eb-926a-3be5734cd89b.png)

Teams/Android
![image](https://user-images.githubusercontent.com/66265462/97038080-41ba1c80-1538-11eb-87e3-4bb87751ce4a.png)

**Comment by Abhijit-MSFT** [comment]
There is no timeline that we can share for this.
