### ISSUE TITLE
Video in Adaptive Cards

### ISSUE THREAD

**Issue by cpacheco7** [Microsoft/AdaptiveCards#430]
Do you know if we will be able to insert video in an adaptive card?
It's imposible like an image, and it's necessary to my Project.

Some help, please :)

**Comment by danmarshall** [comment]
Please see #196 
It's not yet a part of the schema. Upon which platform is your project?

**Comment by cpacheco7** [comment]
I'm using .NET and the Skype and Direct channels

**Comment by ashoksamal6363** [comment]
Do you know what it ll be available?
