### ISSUE TITLE
[Spec][Inconsistency] [Invalid Size Specification For ImageSet Size Property]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#4300]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* Spec

# Details
Our spec does not specify that "Auto" or "Stretch" is invalid values for ImageSet size nor what happens when invalid values are encountered for the size.

**Resolution From Discussion**
1. "auto", "stretch" are invalid
2. default size is "medium" when invalid or empty size is present.

**Comment by shalinijoshi19** [comment]
This tracks the doc work to go with #4043
