### ISSUE TITLE
[Website] Schema explorer incorrectly lists "Column" as a "fallback" option

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#4312]
# Platform

* Website (url: http://adaptivecards-ci.azurewebsites.net/explorer/TextBlock.html)

With a change in #4273 `Column` is marked as an `Element` but that isn't quite correct. It's really a `NonRootElement` or `ChildElement` or some other moniker, which still has all the styling properties of `Element` but cannot be used outside of a `ColumnSet`. This will require some code changes to `ac-typed-schema` most likely.  

Also on the `Column` docs, fallback **MUST BE** a `Column` but currently suggests that other elements can be used

**Comment by RebeccaAnne** [comment]
#4273 was never merged
