### ISSUE TITLE
Action.Submit not returning a value 

### ISSUE THREAD

**Issue by fbessez** [Microsoft/AdaptiveCards#432]
Hey, 
I think I may have found a bug...
I am using Node.js and running this code in the  BotFramework Emulator.
Upon pressing the SUBMIT button, my response.value is {} instead of the desired input. 
This was presented here as well but in C#: https://stackoverflow.com/questions/44388731/how-can-i-read-the-value-from-complex-adaptive-card

How can I grab the message.value that should contain my input field responses!

```const logWorkAdaptiveCard = {
      attachments: [
      	{
            contentType: 'application/vnd.microsoft.card.adaptive',
            content: {
              	type: 'AdaptiveCard',
              	body: [
          		{
          			type: 'ColumnSet',
          			columns: [
          			{
          				type: 'Column',
          				size: 2,
          				items: [
          				{
          					type: 'TextBlock',
          					text: 'Log your work!',
          					weight: 'bolder',
          					size: 'large'
          				},
          				{
          						type: 'TextBlock',
          						text: 'Select from Recent Issues',
          						isSubtle: true
          				},
          				{
          					type: 'Input.ChoiceSet',
          					id: 'issue_selection',
          					style: "compact",
          					choices: [
				            {
				              title: "Select one",
				              value: "selected",
				              isSelected: true
				            },
				            {}
				            ]
          				},
          				{
          						type: 'TextBlock',
          						text: 'How much time did you spend on this? (ex. 1h 30m)?',
          						isSubtle: true,
          						wrap: true
          				},
          				{
          					type: 'Input.ChoiceSet',
          					id: 'time_spent',
          					style: 'compact',
          					choices: [
          					{
          						title: '0h',
          						value: '0h',

          					},
          					{
          						title: '1h',
          						value: '1h',
       
          					},
          					{
          						title: '2h',
          						value: '2h',
       
          					},
          					{
          						title: '3h',
          						value: '3h',
       
          					}]
          				},
          				{
          					type: 'TextBlock', 
          					text: 'Something Here',
          					wrap: true,
          					isSubtle: true
          				},
          				{
          					type: 'Input.Text',
          					id: 'work_description',
          				}]
          			}
          		actions: [
          		{
          			type: 'Action.Submit',
          			title: 'Log this work',
          			// data: JSON.stringify({selected: selected.value,
          			// 		work_description: work_description.value,
          			// 		time_spent: time_spent.value,  
          			// 		})
          		}]
            }
        }
      ]
}```

**Comment by danmarshall** [comment]
Hi @fbessez - this may be an issue with the preview version that was shipped for the Build event. We are working on updates, which should be released around the time when [this PR](https://github.com/Microsoft/BotFramework-WebChat/pull/471) gets merged.

**Comment by fbessez** [comment]
great, thank you @danmarshall.

**Comment by danmarshall** [comment]
@reyesrico @photodesignch can you create a WebChat unit test for AdaptiveCards such that an Action.Submit button sends data to DirectLine. (if not already done).

**Comment by danmarshall** [comment]
@fbessez - We will try to figure out at which layer this issue occurs. It may be in:
1. Adaptive Cards
2. WebChat
3. DirectLine
4. Your bot

Our unit tests are showing that we are receiving the data through 1, 2, and 3 so this is a question for BotBuilder. I am going to close this issue here since it is not an issue in the AdaptiveCards project.

Can you please open a new issue, either on [the BotBuilder GitHub](https://github.com/Microsoft/BotBuilder) or on StackOverflow. You may want to have a more specific question in the title such as "How can I get a complex object result from an AdaptiveCard Action.Submit
in my NodeJs bot?". Thanks

**Comment by photodesignch** [comment]
I am on it. ☺

**Comment by photodesignch** [comment]
@fbessez I tried to put your adaptive card json into a test, one thing I realized!  Your actions[] is wrapping inside of the body[].  It's not only it won't work, it won't even render the action button.

Instead of wrapping in the body[], it should be outside of it, but parallel to it.  Look at example in [here](http://adaptivecards.io/visualizer/?card=/explorer/cards/Action.Submit.json).  If  your actions[] are outside of body[], it will fire correctly and the button will render correctly as well.

**Comment by fbessez** [comment]
@photodesignch, thanks for trying to help! I really appreciate it. However, still having an issue. 

I shortened the json a little bit. When I run the code in the adaptive.io/visualizer, then it works and they show the data in the dropdown. However, when I actually run the bot (and console.log the response) I get the following: 

Am I wrong to expect a message.value.work_description???
```{
      attachments: [
        {
            contentType: 'application/vnd.microsoft.card.adaptive',
            content: {
                type: 'AdaptiveCard',
                version: '0.5',
                body: [
                  {
                    type: 'ColumnSet',
                    columns: [
                      {
                        type: 'Column',
                        size: 2,
                        items: [
                          {
                            type: 'TextBlock',
                            text: 'text!',
                            weight: 'bolder',
                            size: 'large'
                          },
                          {
                            type: 'TextBlock', 
                            text: 'Please add a short description of what you did',
                            wrap: true,
                            isSubtle: true
                          },
                          {
                            type: 'Input.Text',
                            id: 'work_description',
                          }
                        ]
                      },
                    ]
                  }
                ],
                actions: [
                  {
                    type: 'Action.Submit',
                    title: 'Log this work',
                  }
                ]
            } 
        }
      ]
    }

{ type: 'message',
  value: {},
  timestamp: '2017-06-23T09:44:25.118Z',
  localTimestamp: '2017-06-23T09:44:25+00:00',
  textLocale: 'en-US',
  text: '',
  attachments: [],
  entities: [],
  address: 
   { id: 'dn2j9a6n6hiecj013',
     channelId: 'emulator',
     user: { id: 'default-user', name: 'User' },
     conversation: { id: '7ggci796be4lhilkjc' },
     bot: { id: '9cdm9290g5d0hm834c', name: 'Bot' },
     serviceUrl: 'https://8a33d25a.ngrok.io' },
  source: 'emulator',
  user: 'emulator:default-user',
  channel: 'emulator:7ggci796be4lhilkjc',
  question: '' }```

**Comment by fbessez** [comment]
I consulted this https://stackoverflow.com/questions/44388731/how-can-i-read-the-value-from-complex-adaptive-card and one of the comments suggested that this is an issue with columns within adaptive cards. I changed my form to not include columns and it worked! Thanks for the help!
