### ISSUE TITLE
[.Net][AdaptiveCards.AdaptiveSerializationException] [AdaptiveCard.FromJson failed when i set isVisible attribute using a bool varaible from an object]

### ISSUE THREAD

**Issue by DreamBlack** [microsoft/AdaptiveCards#4322]
Here is a copy of my template:
{
        "type": "FactSet",
        "facts": [
          {
            "title": "Resolved By:",
            "value": "${ResolvedBy}"
          },
          {
            "title": "Resolved At:",
            "value": "{{DATE(${ResolvedAt}SHORT)}}"
          }
        ],
        "isVisible": "${ResolvedByVisible}",
        "spacing": "Small",
        "separator": true
      }
There is a bool variable in my class named ResolvedByVisible.

 string cardJson = template.Expand(incident);
var response = context.Activity.CreateReply();
AdaptiveCardParseResult result = AdaptiveCard.FromJson(cardJson);//failed

I got an exception:
![image](https://user-images.githubusercontent.com/16420800/86884005-8191fb00-c125-11ea-9816-b6ce6e1f5fac.png)

How can i control visibility of the factset by a variable

**Comment by shalinijoshi19** [comment]
@jwoo-msft could you take a look at this one?

**Comment by jwoo-msft** [comment]
@DreamBlack Thanks for reporting the issue and payload.
