### ISSUE TITLE
HTML on Adaptive Cards

### ISSUE THREAD

**Issue by cpacheco7** [Microsoft/AdaptiveCards#433]
Hi!
Is it posible to insert HTML text on an adaptive card? I don't want to convert a card to HTML, or the json to the HTML neither. I need HTML inside a TextBox of an Adaptive Card.

Thanks and sorry, my english is awful!

**Comment by dclaux** [comment]
Hi @cpacheco7, you can use Markdown to do some formatting in TextBlock elements (bold, italic, underline, links), but HTML is not supported and there are no plans to add support for it. We want Adaptive to remain a simple (but still powerful) format that is independent of any underlying layout language. This way, the bar to render Adaptive is much lower and each host can maintain a fair level of control over styling.

**Comment by cpacheco7** [comment]
It's simply perfect.
Thanks!

**Comment by Suneethae7** [comment]
Hi,

im trying Adaptive Cards,
in TextBlock :text   i want assign some text which contains link

EX: var card = new AdaptiveCard();
 card.Body.Add(new TextBlock()
            {
                Wrap = true,
                ***Text = "Details are available [here](https://microsfoft.com)",****
              
                Size = TextSize.Medium,
                Weight = TextWeight.Normal,
                HorizontalAlignment = HorizontalAlignment.Stretch,
                Color = TextColor.Default


            });

the text is coming  as is 
**need to show :** Details are available **Here**   
     
**note** (here is the link)

pls help on this as i need to submit task


Thanks

**Comment by Suneethae7** [comment]
text is coming as  : **details are available here (https://xxxx)**
need to show : Details are available Here
thanks,

**Comment by jimmyhawkins** [comment]
Hi,
What about the sigin Card, if it's for authentication stuff I beleave most be like entre UserId and password, I mean the traditional way, there is any card or method or property that I can use for that porpuse?

**Comment by matthidinger** [comment]
Hi @jimmyhawkins, the Bot Framework SignIn Card is specific to Bot Framework and not part of adaptive cards. Maybe try reaching out to them: https://github.com/Microsoft/BotBuilder

**Comment by Gitere** [comment]
When is the **"style": "password"** expected to be released?

**Comment by deepakvashisth** [comment]
Hi, can we add embedded code e.g like from twitter or youtube, in out adaptive card ?

**Comment by pkhtcindia** [comment]
hi can we able to add pie chart html into adaptive card , i have tried many methods didn't worked for me .
Please let me know

**Comment by SanketKulayeAvanade** [comment]
No it is not possible to add HTML in adaptive cards

**Comment by J-Cake** [comment]
what if you receive data from sharepoint in html form and microsoft refuses to add a block for automatic html to markdown conversion?
