### ISSUE TITLE
[Android][TextRun] [color not working for TextRun if it is specified a select action, works fine with iOS lib]

### ISSUE THREAD

**Issue by longlong-cs** [microsoft/AdaptiveCards#4334]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android

# Version of SDK

version 1.2.6, also reproduce with 1.2.10

# Details

We try to use TextRun to implement a clickable text, according to the official doc, we can customize its color and set a select action, but after i set an action for it, the color won't take effect. I checked the code and found that the real span used will change from ForegroundColorSpan to ClickableSpan, the later does not consume the color property. 

We also tried with iOS lib, works fine.

**Comment by shalinijoshi19** [comment]
@almedina-ms can you take a look at this to see what's going on here real quick? Thanks.

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
