### ISSUE TITLE
[WPF] Update Xceed license 

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#4339]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF

# Detail

1. Make sure that third-party-notice explains the non-commercial limitation 
2. Update the `AdaptiveCards.Rendering.Wpf.Xceed` `.csproj` License to match the `wpftoolkit` license. https://github.com/xceedsoftware/wpftoolkit/blob/master/license.md

**Comment by shalinijoshi19** [comment]
@matthidinger assigning to you for now. Thanks

**Comment by shalinijoshi19** [comment]
1. is already taken care of by @paulcam206 ;
2. is likely the reason we are continuing to be flagged.

**Comment by matthidinger** [comment]
I've reached out to the Xceed package owners for clarification on license terms and how we can align our license to be in compliance with them. Will report back when I hear from them

**Comment by RebeccaAnne** [comment]
@paulcam206 to fix up the third party notices and then assign to matt to follow up.
