### ISSUE TITLE
[.NET WPF][Rendering] [Unable to render only the template]

### ISSUE THREAD

**Issue by Hammad-H** [microsoft/AdaptiveCards#4344]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF

# Details
I have tested the .NET WPF visualizer tool and tried to render only the template part of card payload. For the Activity Update card, the behavior is what I would expect as shown below: 
![template](https://user-images.githubusercontent.com/33607998/87089837-06a01180-c205-11ea-9cdd-61ae11455dec.PNG)
_using only the template_
![ActivityJson](https://user-images.githubusercontent.com/33607998/87087545-48c75400-c201-11ea-8b7b-f41b5d4fe15f.PNG)

However, when I tried the same thing with the Restaurant template, the visualizer stops working and the following exception is generated in AdaptiveCardConverter.cs:
![ExceptionOnRestaurant](https://user-images.githubusercontent.com/33607998/87089572-9db89980-c204-11ea-9962-aa67e5aff103.PNG)

I have noticed a similar exception in flight update as well.

**Comment by jwoo-msft** [comment]
@Hammad-H 
Thanks for the bug report. I can repro this issue.
