### ISSUE TITLE
[iOS][Image Rendering] Cards are too long when added Image via ResourceResolver

### ISSUE THREAD

**Issue by akaashdev** [microsoft/AdaptiveCards#4349]
# Platform

* iOS

# Details

The `ACRContentHoldingUIView` takes the height of the image when inserted via **ResourceResolver**, which results in long cards.

## Steps to reproduce
- Setup a ResourceResolver by confirming to `ACOIResourceResolver` protocol
- Return an UIImageView *imgView* in the protocol method `func resolveImageViewResource(_ url: URL?) -> UIImageView?`
- Set an image of size say 960x540 in *imgView* later.

## Screenshots
<img width="320" alt="Simulator Screen Shot - iPhone 11 Pro - 2020-07-09 at 17 31 50" src="https://user-images.githubusercontent.com/17749787/87132702-e1b6a780-c2b3-11ea-9a5a-c15072c8bbd2.png">
<img width="320" alt="Simulator Screen Shot - iPhone 11 - 2020-07-10 at 12 50 24" src="https://user-images.githubusercontent.com/17749787/87132723-eaa77900-c2b3-11ea-8f1a-a213f3deb62f.png">

## Debugger Screenshots
<img width="1563" alt="Screenshot 2020-07-10 at 12 43 31 PM" src="https://user-images.githubusercontent.com/17749787/87133720-59390680-c2b5-11ea-9fb7-5fc28cc0c1ab.png">
<img width="1623" alt="Screenshot 2020-07-10 at 12 47 43 PM" src="https://user-images.githubusercontent.com/17749787/87133476-01020480-c2b5-11ea-9ade-a80e5ee41313.png">

**Comment by jwoo-msft** [comment]
@akaashdev 
Thanks for reporting the issue.
Can you share the payload? I'm interested in getting the URL to the image, so I can try from my end. Could I also know fillMode you used?

**Comment by akaashdev** [comment]
@jwoo-msft 
[payloads.zip](https://github.com/microsoft/AdaptiveCards/files/4906543/payloads.zip)
These are the payloads of the above attached cards. Regarding the URL of the image, We re-host the image in our servers internally and I don't think so it will be accessible. It is for this reason we use **ResourceResolvers**. We use custom URLs (similar to those in the attached payloads) passed in the payload, to get necessary ids and infos to download the image.

[card-images.zip](https://github.com/microsoft/AdaptiveCards/files/4906552/card-images.zip)
These are the downloaded images. Hope this helps.

Regarding the fillMode, I'm not really sure. I have noticed this issue in many cards with images.
Have noticed this sizing issue in sample cards like [WeatherLarge](https://adaptivecards.io/samples/WeatherLarge.html) as well, when image is inserted via **ResourceResolver** flow.

**Comment by jwoo-msft** [comment]
> @jwoo-msft
> [payloads.zip](https://github.com/microsoft/AdaptiveCards/files/4906543/payloads.zip)
> These are the payloads of the above attached cards. Regarding the URL of the image, We re-host the image in our servers internally and I don't think so it will be accessible. It is for this reason we use **ResourceResolvers**. We use custom URLs (similar to those in the attached payloads) passed in the payload, to get necessary ids and infos to download the image.
> 
> [card-images.zip](https://github.com/microsoft/AdaptiveCards/files/4906552/card-images.zip)
> These are the downloaded images. Hope this helps.
> 
> Regarding the fillMode, I'm not really sure. I have noticed this issue in many cards with images.
> Have noticed this sizing issue in sample cards like [WeatherLarge](https://adaptivecards.io/samples/WeatherLarge.html) as well, when image is inserted via **ResourceResolver** flow.

thanks. I have everything I need.
