### ISSUE TITLE
data binding to boolean fails

### ISSUE THREAD

**Issue by IntranetFactory** [microsoft/AdaptiveCards#4350]
I have the following simple payload 

```json
{
    "title": "boolean binding",
    "visible": false
}
```

and the following simple card definition

```json
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "${title}",
                    "isVisible": "${visible}"
                }
            ]
        }
    ]
}
```

I cannot bind `visible`

`"isVisible": "${visible}"`  still shows the TextBlock
`"isVisible": ${visible}`   isn't valid JSON so the card

**Comment by dclaux** [comment]
@IntranetFactory I assume this is a designer issue. In the future, please make sure you specify that.

I can repro in the designer. Note this issue will not repro if you use the templating SDK in your own code. It is a designer specific issue.

**Comment by dclaux** [comment]
To be more explicit - the designer currently has limited data binding support. Aside from the properties that can be explicitly bound, other things might not work as expected, and that includes Boolean properties.

I will look into fixing this specific use case (e.g. binding Boolean properties) but other limitations will still exist and you might still hit them. Comprehensive data binding support in the designer is on the roadmap but it is a significant work item.

**Comment by IntranetFactory** [comment]
>It is a designer specific issue.

What syntax should be used to bind a boolean property?

a. `"isVisible": "${visible}"`   I think that this won't work, as the result is a string
b. `"isVisible": ${visible}`    I assume this should work - but a file containing that expression isn't a valid json file

**Comment by dclaux** [comment]
`"isVisible": "${visible}"` is the correct syntax. The result isn't a string. It is the type of the binding expression, `${visible}`, which in your case is a Boolean. `"isVisible": ${visible}` isn't valid JSON to start with and would cause the entire payload to fail parsing.

**Comment by dclaux** [comment]
I have a PR that fixes this: https://github.com/microsoft/AdaptiveCards/pull/4351
