### ISSUE TITLE
[iOS] size "stretch" doesn't stretch image

### ISSUE THREAD

**Issue by golddove** [microsoft/AdaptiveCards#4353]
# Platform

* iOS

# Version of SDK

latest main

# Details

Expected the last image to stretch to the width of the card. Payload:
```
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.2",
	"body": [
		{
			"type": "Image",
			"url": "https://picsum.photos/25?image=882",
			"size": "small"
		},
		{
			"type": "Image",
			"url": "https://picsum.photos/25?image=882",
			"size": "medium"
		},
		{
			"type": "Image",
			"url": "https://picsum.photos/25?image=882",
			"size": "large"
		},
		{
			"type": "Image",
			"url": "https://picsum.photos/25?image=882",
			"size": "auto"
		},
		{
			"type": "Image",
			"url": "https://picsum.photos/25?image=882",
			"size": "stretch"
		}
	]
}

```

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-10 at 13 02 04](https://user-images.githubusercontent.com/4442788/87179954-3b8f8f80-c2fd-11ea-8765-7da4e5963f74.png)

**Comment by shalinijoshi19** [comment]
@jwoo-msft I've approved this for now but @golddove is this related to a potential 20.07 investigation? Priority wise I'd say the Inputs/Teams mobile/Cisco bugs should be higher priority for this sprint

**Comment by golddove** [comment]
Yes, JS respects `stretch`. Not a priority, just filing the bug.
