### ISSUE TITLE
[WPF][Accessibility] Inputs not reading label

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#4355]
# Platform

* .NET WPF

# Details

The following elements don't read label and/or error message
| Rendered element | Labels Success | ErrorMessage Success | Observations
| --- | --- | --- | --- | 
| Xceed Input.Number | ❌ | ❌ | By design |
| Xceed Input.Time | ❌ | ❌ | By design |
| Inline Input.Text | ❌ | ✔ | |
| Xceed Input.Date | ✔ | ❌ | By design |
| ChoiceSet.Expanded | ✔ | ❌ | |

**Comment by almedina-ms** [comment]
Leaving some more context here, it looks like Xceed not having UI Automation (Accessibility) properties is by design they only provide it in the paid version 

https://github.com/xceedsoftware/wpftoolkit/wiki/Xceed-Toolkit-Plus-for-WPF

**Comment by paulcam206** [comment]
wow -- that's really disappointing to find out about the xceed toolkit :(

**Comment by shalinijoshi19** [comment]
For now, the linked PR suffices; The other thing remaining for exceed support is the update to its license that @paulcam206 is driving orthogonal to Inputs. At this point we'll be pushing ahead with this level of support for Exceed

**Comment by shalinijoshi19** [comment]
@almedina-ms it would also be nice to have a version of the table *after* your fixes here. Thanks
