### ISSUE TITLE
[UWP][InputValidation] Required input with no label has no visual required indicator 

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#4356]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Details

The below card (a simplified version of our Inputs.json card where the name field has been marked required) uses placeholders for labels. As a result there is no label to append the * indicator to and there is no indication that the input is required until after submit. Is this the desired behavior?

|  |  |
| --- | --- |
|![image](https://user-images.githubusercontent.com/9091833/87202338-37d81a80-c2b5-11ea-9cce-abf32065c1cb.png)|![image](https://user-images.githubusercontent.com/9091833/87202369-432b4600-c2b5-11ea-9ec3-33cda2adcd57.png)|

```|son
{
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "size": "medium",
      "text": "Please enter the following information:"
    },
    {
      "type": "Input.Text",
      "placeholder": "Name",
      "isRequired": true,
      "id" : "name",
      "errorMessage":"Name is required"
    },
    {
      "type": "Input.Text",
      "placeholder": "Homepage",
      "id": "homepage"
    },
    {
      "type": "Input.Text",
      "placeholder": "Email",
      "id": "EmailVal"
    },
    {
      "type": "Input.Text",
      "placeholder": "Phone",
      "id": "TelVal"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Submit"
    }
  ]
}
```

**Comment by jwoo-msft** [comment]
we are not going to block the shipping but we should look back at it.

**Comment by RebeccaAnne** [comment]
We've decided that this is the expected behavior. Using placeholders as labels is not a good practice in general, and card authors should use a label when marking inputs required. We will return warnings when a card author marks an input as required without including a label.
