### ISSUE TITLE
[Android][InputLabels] Labels no longer render on latest version of the visualizer app

### ISSUE THREAD

**Issue by shalinijoshi19** [microsoft/AdaptiveCards#4358]
# Platform

* Android

# Version of SDK
Internal Visualizer app from appcenter off of feature/inputEvolution.

# Details

Tried this with ChoiceSet samples as well as Input.Date.. labels aren't rendering anymore; In addition there is an error about id collision for input1 at least for the ChoiceSet sample; Screenshot below from Inputs.ChoiceSet:
### Working Input.ChoiceSet JS screenshot 
![image](https://user-images.githubusercontent.com/20822397/87206803-5e9b4e80-c2bf-11ea-8a01-8c22d019fd2c.png)
### Input.Choiceset sample on Android
![image](https://user-images.githubusercontent.com/20822397/87205543-8dfc8c00-c2bc-11ea-8f72-d262452af53a.png)
### Working Input.Dates sample on JS
![image](https://user-images.githubusercontent.com/20822397/87206962-986c5500-c2bf-11ea-87f7-bce0c5394b8d.png)
### Input.Dates sample on Android
![image](https://user-images.githubusercontent.com/20822397/87206177-06b01800-c2be-11ea-84cd-3ca82ff89d5e.png)

**Comment by almedina-ms** [comment]
I just removed all versions of the visualizer and installed the lastest build and this is the result. Could you check that you are using the latest version (2020.07.10.1)? Maybe it's an issue we haven't caught before

![Screenshot_20200710-181622_AdaptiveCards Visualizer](https://user-images.githubusercontent.com/35784165/87207291-70312600-c2c0-11ea-8ed2-083505512acc.jpg)

**Comment by almedina-ms** [comment]
The latest version of the app should have an Import tab and the the card name should appear not in the input text box

**Comment by jwoo-msft** [comment]
send app line or update app installation instruction for the android app from the app center
