### ISSUE TITLE
Unable to run the website solution in VS2017

### ISSUE THREAD

**Issue by preshi** [Microsoft/AdaptiveCards#436]
Getting the below error with respect to dependency Markednet in VS 2017 when trying to run the .net core website in folder AdaptiveCards\source\website

Unable to resolve 'MarkedNet (>= 1.0.6)' for '.NETCoreApp,Version=v1.1'.				

Removed MarkedNet dll manually and restored MarkedNet 1.5 and ran the solution.This fixed the problem.What is the nugget version to be used. 

Thanks,

**Comment by matthidinger** [comment]
We had to use an internal build of MarkedNet for a bit, but that will be removed soon. Thanks for pointing it out!

**Comment by matthidinger** [comment]
This is fixed now
