### ISSUE TITLE
[Android][Input Evolution] [Time Validation Doesn't Work]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#4361]
# Platform

* Android

# Details
Time is not correctly validated. As seen in the below image, if time is set to 3:00 AM for min value test, and 9:00 PM for max value test. Submission proceeds against the expectation of error messages and blocked the submission.

![Screenshot (Jul 10, 2020 3_11_50 PM)](https://user-images.githubusercontent.com/4112696/87207577-09603c80-c2c1-11ea-940f-06b595858eda.png)

**Comment by golddove** [comment]
No repro. If I'm looking at this correctly, those labels are for the input's below them. So 8:11pm is being validated for minimum of 6:00am, so it passes.

**Comment by golddove** [comment]
@jwoo-msft 
No repro. If I'm looking at this correctly, those labels are for the input's below them. So 8:11pm is being validated for minimum of 6:00am, so it passes.

**Comment by jwoo-msft** [comment]
> @jwoo-msft
> No repro. If I'm looking at this correctly, those labels are for the input's below them. So 8:11pm is being validated for minimum of 6:00am, so it passes.

but it should fail at 8:00pm max time check

**Comment by jwoo-msft** [comment]
you can close it as long as input submission is blocked.

**Comment by shalinijoshi19** [comment]
@golddove please go ahead and confirm this is working as expected and close it out! thanks
