### ISSUE TITLE
[JavaScript] [Input Validation] isRequired doesn't trigger red styling for Input.Toggle

### ISSUE THREAD

**Issue by golddove** [microsoft/AdaptiveCards#4362]
# Platform

* JavaScript

# Version of SDK

https://adaptivecardsci.z5.web.core.windows.net/pr/4239/designer

# Details
There are no error indications for Toggle.Input, when there is no error text.

```
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "Input.Toggle",
            "title": "New Input.Toggle",
            "id": "id1",
            "isRequired": true
        },
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.Submit",
                    "title": "Action.Submit"
                }
            ]
        }
    ]
}
```

**Comment by jwoo-msft** [comment]
It doesn't provide a cue for errors and focus is not set to the toggle input.

**Comment by shalinijoshi19** [comment]
@golddove to follow up here with @dclaux ; @paulcam206 FYI

**Comment by shalinijoshi19** [comment]
@dclaux could you also help drive this along with @paulcam206?  Thanks a ton

**Comment by shalinijoshi19** [comment]
@dclaux what was the final decision on this specific issue?

**Comment by dclaux** [comment]
This is fixed with this commit: https://github.com/microsoft/AdaptiveCards/commit/a7e2d6bd1fd5c9d140924ad050ef8ee7f15f048a

I forgot to create a separate branch and pushed the commit directly into `feature/inputEvolution`
