### ISSUE TITLE
[Spec Issue][Input Validation] Spec clarification required for behavior of input validation in the case of popup show cards

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#4369]
# Details

Spun off the spec issue from the crash tracked by #4245. We need to spec the behavior of input validation in the case of popup show cards. What happens when an error in a parent card prevents a popup card from submitting?

**Comment by RebeccaAnne** [comment]
Popup show cards in general are not well supported today (#4392). Moving this out of 1.3 milestone for future consideration.

**Comment by Jeffders** [comment]
This is a test.

**Comment by Jeffders** [comment]
This is a test.

**Comment by Jeffders** [comment]
This is a test.

**Comment by RebeccaAnne** [comment]
We are revisiting show card popup support via #4392. Closing this for now.
