### ISSUE TITLE
Brokend Documentation links

### ISSUE THREAD

**Issue by preshi** [Microsoft/AdaptiveCards#437]
The below documentation link is broken

http://adaptivecards.io/documentation/ImplementingRenderer.md
https://github.com/Microsoft/AdaptiveCards/blob/master/source/source/dotnet/Samples/RenderImage/Render2Image.csproj
 
Any future plan  for 'plug n play' samples?

**Comment by matthidinger** [comment]
Hi preshi, thanks for pointing it out, we'll be publishing docs fixes soon.

What kind of sample are you looking for? Generating Cards for a bot? Using the renderer inside your app? Something else?

**Comment by preshi** [comment]
Hi Matt, The Samples page was not working because the node modules were not referenced. Am new to node js and was unable to install it in the respective source location place given the .npmrc file present in it. Good to have some Pre Build Steps like install commands and all.Its easy to start for some people.

Also With respect to examples. If you can provide couple of simple examples like referencing from a cdn (if plausible )and implementing the example in various frameworks like Angular 1.x ,Angular 2 as directive/component.

**Comment by matthidinger** [comment]
This should all be updated now with the latest adaptivecards.io site. Please do let us know if you have additional feedback!
