### ISSUE TITLE
[Android][Dev Experience] Investigate issue with actions not properly casting all time

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#4378]
# Platform

* Android

# Version of SDK

latest release / main

# Details

Sometimes, the baseActionElement.findImplObj() is not an instance of a custom action element. It is an instance of BaseActionElement only. In these cases it leads to a class cast exception. Investigation is needed to figure out why this happens

**Comment by jonmill** [comment]
No context / point of contact here...closing since we have no details here
