### ISSUE TITLE
[Feature Request] Add usage example to NPM module description page at https://www.npmjs.com/package/microsoft-adaptivecards

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/AdaptiveCards#438]
**Notes**
The [microsoft-adaptivecards module on NPM](https://www.npmjs.com/package/microsoft-adaptivecards) currently has no usage examples demonstrating how to use the module. 

**User Story**
As a developer/user of Bot Framework Node SDK, I would like to be able to learn how to use the `microsoft-adaptivecards` module by reading a usage example on the NPM module description page. 

**Acceptance Criteria:**
`microsoft-adaptivecards` description page on NPM contains at least one usage example.

**Comment by matthidinger** [comment]
This is updated now
