### ISSUE TITLE
[Shared Model][Input Evolution] [Input.Number can't have nullable value]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#4382]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android
* iOS
* UWP

# Details
Input.Number has Value field.
If Value field is left empty, the shared model should let the renderer knows that value is null.
Currently, at renderer, if GetValue is called, it will return 0. This will leads to "required" validation not to work and causes inconsistency issue. WPF and JS leaves field empty, and "required" validation will work.

**Comment by paulcam206** [comment]
doesn't look like this change needs to be made for any other inputs (they use the empty string to denote a property that hasn't been set)

**Comment by jwoo-msft** [comment]
I realized that we have the same issue with max length for TextInput.

**Comment by shalinijoshi19** [comment]
@jwoo-msft / @paulcam206 status on this one ?
