### ISSUE TITLE
[iOS][InputValidation] Warning should be returned when an input is marked as required but doesn't have a label

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#4387]
# Platform

* iOS

# Details

See issue #4356 for details. When an input is marked as required but does not include a label a warning should be returned to inform the card author that there will be no visual indication that their input is required.

**Comment by shalinijoshi19** [comment]
@jwoo-msft do you have bandwidth to cover this? Or @almedina-ms can you help?

**Comment by jwoo-msft** [comment]
> @jwoo-msft do you have bandwidth to cover this? Or @almedina-ms can you help?

yes, I can implement it.
