### ISSUE TITLE
Need example of dynamic data

### ISSUE THREAD

**Issue by iwaldman** [Microsoft/AdaptiveCards#439]
How would I get real weather data into the [Weather Example](http://adaptivecards.io/samples/#WeatherLarge)?  

For example, I would like to show today's date and current temp.  This will most likely be retrieved by a HTTP call before rendering the card.

```	
{
 "type": "TextBlock",
 "text": "**Monday April 1**",
 "size": "large"
},
{
 "type": "TextBlock",
 "text": "63 / 42",
 "size": "medium",
 "separation": "none"
}
```

**Comment by EricDahlvang** [comment]
Hi @iwaldman, 

There is a blog post here: https://blog.botframework.com/2017/06/07/Adaptive-Card-Dotnet/ describing how to use a 3rd party weather service to show the forecast in a bot using Adaptive Cards.

Here is the corresponding .net project: https://github.com/EricDahlvang/AdaptiveCards-WeatherBot

Here is a node project that does the same: https://github.com/nwhitmont/botframework-luis-adaptive-cards-weather-example

Here's another node sample with some dynamic cards: https://github.com/Microsoft/BotBuilder-Samples/blob/master/Node/cards-AdaptiveCards/app.js

I hope this helps.

**Comment by iwaldman** [comment]
Ok, that is what I was thinking.  I will pursue that route.  Thank you.
