### ISSUE TITLE
[Documentation][Input Validation] Input validation documentation issues

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#4391]
# Platform

What platform is your issue or question related to? (Delete other platforms).

Documentation

# Details

This issue tracks outward facing documentation for issues related to Input Validation. Specifically, we need to document:

- We have introduced a **breaking change** in which inputs are returned by a submit action in a cards with show cards. Previously all inputs would be returned for all cards, now only those belonging to the card with the submit action and any parent cards will be returned. 
- Input validation of inputs which can be hidden by an Action.ToggleVisibility is not recommended.
- Input validation may not be well supported when the host is using `popup` show cards rather than the default `inline` show cards.

**Comment by shalinijoshi19** [comment]
@RebeccaAnne assigning this to you for follow up please! thanks
