### ISSUE TITLE
[Inconsistency][Input Label] Required hint should keep attention color

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#4393]
# Platform

- [x] .NET WPF
- [x] Android
- [x] iOS
- [x] JavaScript
- [x] UWP

# Details

When a host config label color changes we should keep the required hint with attention color. WPF, Android and UWP don't follow the same behaviour

**Comment by shalinijoshi19** [comment]
@almedina-ms bringing this to your attention for fixing. Thanks

**Comment by shalinijoshi19** [comment]
@golddove can you help pick this up if @almedina-ms has his hands full iwth other bugs ? thanks

**Comment by shalinijoshi19** [comment]
@jwoo-msft , @dclaux , @golddove can you please help out with the rest of the platforms here? Tx!

**Comment by golddove** [comment]
Already works on Android. I'll mark it.

**Comment by jwoo-msft** [comment]
works on iOS. Marked it.

**Comment by paulcam206** [comment]
JS works -- Marked.
