### ISSUE TITLE
[iOS][Code Maintainence] Provision to provide custom Bundle path

### ISSUE THREAD

**Issue by akaashdev** [microsoft/AdaptiveCards#4402]
**Platform**
* iOS

**Is your feature request related to a problem? Please describe.**

It's related to [Issue 4167](https://github.com/microsoft/AdaptiveCards/issues/4167) - *No Cheveron on Action.ShowCards*

**Describe the solution you'd like**

The fix provided was good and it involved modifying the [ACRButtonExpandable.xib](https://github.com/microsoft/AdaptiveCards/blob/e23e08bb732f4d2712b8aacd519c6379b63dd0f4/source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRButtonExpandable.xib) which resides in the AdaptiveCards source code. 
It is good to have a custom bundle path that can be provided to the SDK where our own .xib resides, so that we can own the design.

**Comment by shalinijoshi19** [comment]
@jwoo-msft please prioritize this for 20.08 after we've shipped 20.07 including Inputs! thanks.

**Comment by shalinijoshi19** [comment]
@jwoo-msft please prioritize and ensure all your open issues per [this query](https://github.com/microsoft/AdaptiveCards/issues?q=is%3Aissue+milestone%3A20.10+label%3APriority-Now+label%3AMsft-TeamsMobile+is%3Aopen+assignee%3Ajwoo-msft) are closed out and checked into main ahead of this week before taking this one on pls! We are looking to fork and provide privates for testing to Teams by tues, 10/27 EOD

**Comment by shalinijoshi19** [comment]
@jwoo-msft is this still on track for this week for 20.10?

**Comment by RebeccaAnne** [comment]
This should be solved by using swift package manager, please reopen if this is still an issue for you.
