### ISSUE TITLE
[Android][Image Rendering] - Rendered image inside card are down scaled via ResourceResolver

### ISSUE THREAD

**Issue by ankbat** [microsoft/AdaptiveCards#4410]
# Platform

* Android

# Version of SDK

1.2.6 (Maven repository)

# Details

The images in some cards are not rendered in the expected size. The rendered images are down scaled from its original size in some of the cards. ```IResourceResolver``` is used and bitmap is getting returned on **resolveImageResource** function from the client.

**Payload data** : [Restaurant Card](https://developer.webex.com/buttons-and-cards-designer/restaurant)

# Screenshots

 **Android**

<img width="395" alt="Screenshot 2020-07-08 at 11 31 13 AM" src="https://user-images.githubusercontent.com/9837823/87747966-4fae2200-c812-11ea-9da4-99253473d849.png">

**Expected**

<img width="197" alt="Picture 1" src="https://user-images.githubusercontent.com/9837823/87748111-aa477e00-c812-11ea-8ed9-760b18e7e875.png">

**Comment by shalinijoshi19** [comment]
@golddove could you link this issue to the PRs wiht the resource resolver fix to close out..tx

**Comment by golddove** [comment]
@ankbat even after our scaling fix on Android, please note that when size is set to "auto," the image should not scale up.

Refer to our schema docs on `size`: https://adaptivecards.io/explorer/Image.html
