### ISSUE TITLE
[Android][Image Rendering] - Parallel calling of IResourceResolver 

### ISSUE THREAD

**Issue by ankbat** [microsoft/AdaptiveCards#4411]
# Platform
* Android

# Version of SDK

1.2.6 (Maven repository)

# Details

```IResourceResolver``` -> ```resolveImageResource``` :  is called in the sequential manner to get the bitmap from the client by the SDK.

**Example**

In case client needs some time to download the image at its end before returning the bitmap and the cards has multiple images in it and one of the first image is big in size in comparison to others and it's take time.

The other image callers will have to wait until the first image caller returns back to SDK. Because the calling mechanism of the ```IResourceResolver``` is sequential in nature.

## Current Flow:
<img width="1045" alt="Screenshot 2020-07-07 at 4 58 59 PM" src="https://user-images.githubusercontent.com/9837823/87749048-2f339700-c815-11ea-9b45-20eb28755f95.png">

**Comment by shalinijoshi19** [comment]
@golddove could you link the associated Android PRs we have that we believe fixes these to this issue to verify and close? Thanks
