### ISSUE TITLE
[JavaScript][Deregistering a property from the parser/render]

### ISSUE THREAD

**Issue by mokandre** [microsoft/AdaptiveCards#4414]
**What platform is your feature request related to?**

* JavaScript

**Is your feature request related to a problem? Please describe.**

We would like to disable the functionality of unsupported properties on parser/render

**Describe the solution you'd like**
It would be great to have a way to `Deregister a property from the parser/render`

**Deregister has to work for the following cases:**

* Deregister the property for a particular element( For Example: Deregister the `Height` property of `columnSet`)
* Deregister the property for all elements(For Example:  Deregister the `verticalContentAlignment` property  for all the elements where it supports)

### For Example

Unsupported Property  : `maxLines` for `TextBlock` element.

After deregistering a  property, though users try to add `maxLines` property to their JSON then that property shouldn't render/parse.

**Current behavior:**

<img width="1680" alt="Screenshot 2020-07-17 at 11 37 18 AM" src="https://user-images.githubusercontent.com/55378170/87754154-e9c99680-c821-11ea-93f0-d5e393a428e0.png">

**If possible, validator have to point out that the unsupported properties are not supported as warning message**

For Example:(Warning Message)

**Unknown/Unsupported property :`maxLines` of `TextBlock` Element**

**Comment by dclaux** [comment]
This is actually already supported, via the SrializableObject.onRegisterCustomProperties event. Example:

```typescript
Adaptive.SerializableObject.onRegisterCustomProperties = (sender: Adaptive.SerializableObject, schema: Adaptive.SerializableObjectSchema) => {
    if (sender instanceof Adaptive.TextBlock) {
        schema.remove(Adaptive.TextBlock.heightProperty);
    }
}

```

Can you please try this and close this issue if that solves your problem?

**Comment by mokandre** [comment]
> @mokandre This is actually already supported, via the SrializableObject.onRegisterCustomProperties event. Example:
> 
> ```ts
> Adaptive.SerializableObject.onRegisterCustomProperties = (sender: Adaptive.SerializableObject, schema: Adaptive.SerializableObjectSchema) => {
>     if (sender instanceof Adaptive.TextBlock) {
>         schema.remove(Adaptive.TextBlock.heightProperty);
>     }
> }
> ```
> 
> Can you please try this and close this issue if that solves your problem?

@dclaux  Able to deregister some of the properties but
 **Following are some issues facing while deregistering  (`fallback` and `requires`) properties**

* Deregistering `requires` property:
<img width="1530" alt="Screenshot 2020-07-20 at 2 28 37 PM" src="https://user-images.githubusercontent.com/55378170/87919831-ff46f680-ca95-11ea-8f14-c317641dd83f.png">

**Output:**
<img width="1680" alt="Screenshot 2020-07-20 at 2 47 49 PM" src="https://user-images.githubusercontent.com/55378170/87921353-0ff86c00-ca98-11ea-9996-65d54ef51178.png">



* I'm not able to access the `fallback` property in element (Example: Adaptive.TextBlock. ? ). Can you give me an example of how to deregister `fallback` property for all elements?

**Comment by dclaux** [comment]
@mokandre I will implement another model for property deregistration. I could just fix the bug you mentioned, but I fear there will be more such bugs as the renderer expects and needs some properties to be registered.

As for fallback, it is not handled as a property internally and therefore cannot be unregistered. Fallback is mainly a parse-time feature, and fallback elements are not parsed if they are not needed. I will add a global flag to disable fallback.
