### ISSUE TITLE
[Android]Inconsistent spacing for Action set

### ISSUE THREAD

**Issue by Gunashree-R-V** [microsoft/AdaptiveCards#4417]
# Platform

What platform is your issue or question related to? 

* Android

# Author or host

Teams Mobile

# Version of SDK

1.2.10

# Details

No spacing is applied above the action set component on Android. While there is spacing applied for bottom actions.

Here are the screenshots of how it looks on Android and Desktop

**_Desktop:_**
<img width="449" alt="Screenshot 2020-07-17 at 2 34 49 PM" src="https://user-images.githubusercontent.com/28745768/87769335-1e961780-c83b-11ea-955c-f398940c6227.png">

**_Android:_**
<img width="519" alt="Screenshot 2020-07-17 at 2 26 33 PM" src="https://user-images.githubusercontent.com/28745768/87769355-26ee5280-c83b-11ea-930e-c72b45c61942.png">

Attached the card JSON below:

[action-and-actionset-spacing.txt](https://github.com/microsoft/AdaptiveCards/files/4936785/action-and-actionset-spacing.txt)

cc: @VikrantSingh01, @anbah34, @shbhadra

**Comment by Gunashree-R-V** [comment]
@shalinijoshi19/ @paulcam206 Do we have any updates on this bug?

**Comment by shalinijoshi19** [comment]
@golddove can you please work with @jwoo-msft to outline what the behavior will be here as an issue update pls?

**Comment by paulcam206** [comment]
Fixing this is not currently on our roadmap.
