### ISSUE TITLE
[Android] ActionSetRenderer not honouring registered ActionLayoutRenderer

### ISSUE THREAD

**Issue by Gunashree-R-V** [microsoft/AdaptiveCards#4418]
# Platform

What platform is your issue or question related to? 

* Android

# Author or host

Microsoft Teams Mobile

# Version of SDK

1.2.10

# Details

Actions in action set are to be rendered using the registered ActionLayoutRenderer. Rather, default ActionLayoutRenderer is being used.

Below is the code snippet for reference(ActionSetRenderer.java):

```
try {
            ActionLayoutRenderer.getInstance().renderActions(renderedCard, context, fragmentManager, actionsLayout, baseActionElementList, cardActionHandler, hostConfig, renderArgs);
}
 catch (Exception e) {}

```

cc: @VikrantSingh01, @anbah34, @shbhadra

**Comment by shalinijoshi19** [comment]
@Gunashree-R-V is this an issue that is still repro'ing with the latest 2.x version of the Android renderer?

**Comment by Gunashree-R-V** [comment]
@shalinijoshi19, Yes. This issue is still applicable.

**Comment by paulcam206** [comment]
This is not currently on our roadmap - please reactivate if you don't have a workaround.
