### ISSUE TITLE
[iOS][InputEvo] Compact Input.ChoiceSet not getting focus

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#4428]
# Platform

* iOS

# Version of SDK

feature/inputEvolution

# Details

When input validation fails and the first element to fail validation is a Compact ChoiceSet it should get focus but it currently doesn't. This may not be possible but Input.Date actually performs the focus behavior correctly

| Input.Date | Input.ChoiceSet | 
| --- | --- |
| ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-17 at 14 29 51](https://user-images.githubusercontent.com/35784165/87832078-fbb73380-c839-11ea-80de-ddd18eb15e18.png) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-17 at 14 29 25](https://user-images.githubusercontent.com/35784165/87832052-ec37ea80-c839-11ea-8535-70bfbaf1d728.png) |

**Comment by jwoo-msft** [comment]
Android does bring up a user selection subview, but we decided to keep the current behavior for iOS.

**Comment by jwoo-msft** [comment]
re-opening the issue. I re-checked the issue, and there is some improvement I can make, and reopening it to track.
