### ISSUE TITLE
[WPF][Input Evolution] [Choice Set Compact's Input is not collected]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#4429]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF

# Details
![image](https://user-images.githubusercontent.com/4112696/87832612-3cfc1300-c83b-11ea-8438-5fa496181d81.png)

If no choices are made for ChoiceSet compact, its input is not gathered.

**Comment by shalinijoshi19** [comment]
@almedina-ms can you help take a look at this pls? thanks!
