### ISSUE TITLE
Column size auto clipping text

### ISSUE THREAD

**Issue by matthidinger** [Microsoft/AdaptiveCards#443]
Flight update for Depart is clipped

![image](https://user-images.githubusercontent.com/1432195/27563345-e5a73dc6-5a85-11e7-8cb5-fe9ae220e7fd.png)

**Comment by dclaux** [comment]
The center column isn't defined correctly. Its size should be "stretch" and elements inside should have their "horizontalAlignment" set to "center." Other columns should have "size": "auto"
