### ISSUE TITLE
[Android][Rendering] Conflict between image size and column weight

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#4439]
# Platform
* Android

# Details

With the introduction of image resizing to a bigger scale the ```v1.2/Elements/Column.Weighted.Image.json``` card became broken as there's a conflict between the image size and the column weight.

![image](https://user-images.githubusercontent.com/35784165/87984820-67dea500-ca8f-11ea-9b60-ca89e02effed.png)

**Comment by shalinijoshi19** [comment]
@almedina-ms / @golddove does this need to be backported to 1.2 ? If so please label it with AdaptiveCards v1.2.11

**Comment by shalinijoshi19** [comment]
ping @golddove / @almedina-ms ?

**Comment by golddove** [comment]
Reopening due to revert
