### ISSUE TITLE
HttpAction Does not include headers in the onExecuteAction callback

### ISSUE THREAD

**Issue by Kikketer** [Microsoft/AdaptiveCards#444]
I'm not getting the `headers` object when listening for an HttpAction:

The card looks like this:
```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "0.5",
  "actions": [
    {
      "type": "Action.Http",
      "title": "Something",
      "url": "http://localhost:3000/api/test",
      "method": "POST",
      "headers": {
        "Content-Type": "application/json"
      },
      "body": "{\"message\": \"Heres some json already stringified\"}"
    }
  ]
...
}
```

The listener is super basic:
``` 
  AdaptiveCards.AdaptiveCard.onExecuteAction = (action) => {
    if(action instanceof AdaptiveCards.HttpAction) {
      console.log(action.headers)
    }
  }
```

That log always turns up an empty array.  I tried to use a string that looks like a JSON object in the card definition but it came back with a ton of "http header" objects (assuming one for each character in the string).

**Comment by dclaux** [comment]
Hi @Kikketer, your headers property isn't defined properly, you need to define it as follows:

```
"headers": [
    { "name": "Content-Type", "value": "application/json" }
]
```
The headers property is a collection of strongly typed name/value pairs.

**Comment by matthidinger** [comment]
He raises an interesting design question though. Should we consider changing this array to be an object? Is the order of the headers important? Or is there a scenario where a header with the same key would exist?

**Comment by dclaux** [comment]
Order has no importance in HTTP headers. They are always available to an HTTP client all at once. The strongly-typed format we currently have is better for validation; allowing for headers to be specified as just an object (or "any") makes it possible to define things that wouldn't make sense.

**Comment by dclaux** [comment]
@Kikketer, I realize that the documentation and the implementation do not match. You did the right thing according to the doc, but my preference in terms of the schema is the way it's currently implemented. Any opinion/insight you'd like to share?

**Comment by Kikketer** [comment]
The headers array seems overkill to me.  I was attempting to use it with "fetch" and it was handy to be able to simply pass it along:

```
fetch(action.url, {
  method: action.method,
  headers: action.headers
})
```

Instead of having to loop through the array and create an object.  I haven't ever seen a headers object be an array before, not sure the advantage it would give (since order doesn't matter).

**Comment by dclaux** [comment]
This is the way the headers property is defined in a Request object that can be fed to fetch:
```
interface Headers {
    append(name: string, value: string): void;
    delete(name: string): void;
    forEach(callback: ForEachCallback): void;
    get(name: string): string | null;
    has(name: string): boolean;
    set(name: string, value: string): void;
}
```
And as far as I can tell, the usage pattern is this (https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch):
```
var myHeaders = new Headers();
myHeaders.append("Content-Type", "text/plain");
myHeaders.append("Content-Length", content.length.toString());
myHeaders.append("X-Custom-Header", "ProcessThisImmediately");

var myInit = { method: 'GET',
               headers: myHeaders,
               mode: 'cors',
               cache: 'default' };

var myRequest = new Request('flowers.jpg', myInit);

fetch(myRequest);
```
It doesn't seem that headers is just an object; per its definition, it's a lot more like a collection. Also, it doesn't seem to support implicit conversion from any object (although I might be missing something).

Maybe the right thing to do here is to define the Http action's headers property as a Headers instance.

**Comment by Kikketer** [comment]
That may work as well, but the creation of the `new Headers()` is truly a painful experience (especially since it just turns into a couple strings in the header).

I specifically use https://www.npmjs.com/package/whatwg-fetch which seems to handle that annoying part for me.

More standards compliant is good in my book, but shortcuts are also super handy.

**Comment by dclaux** [comment]
I don't think the Adaptive Card library should have a dependency on an external project such as whatwg-fetch and be modeled in such a way that it becomes harder to use it with the standard compliant version of fetch, wouldn't you agree? I think the current name/value pair is a good compromise.

**Comment by Kikketer** [comment]
Yep, you've convinced me.  Even the standard XHR headers is an array.
So I guess the result of this is an update to the documentation: https://docs.microsoft.com/en-us/adaptive-cards/create/cardschema#action-http

Thanks!

**Comment by dclaux** [comment]
Yes, we will update the doc. Thank you!

**Comment by matthidinger** [comment]
Docs have been updated here: https://docs.microsoft.com/en-us/adaptive-cards/create/cardschema#action-http
