### ISSUE TITLE
[.NET][Adaptive Card Templating Transform/Expand] [Error with decimal in Data]

### ISSUE THREAD

**Issue by iwekardum** [microsoft/AdaptiveCards#4441]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET

# Author or host

- Author
- Microsoft Teams

# Version of SDK

AdaptiveCards.Templating 1.0.0

# Details

Expand function reports error 
"Invalid JavaScript property identifier character: ,. Path 'body[3].columns[1].items[0].columns[1].selectAction.data._source.evaluation.score', line 1, position 1777."

**SourceCode**
var transformer = new AdaptiveCardTemplate(template);
return JToken.Parse(**transformer.Expand(this)**); <- throws exception

**Template**
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "text": "${_source.properties.username} hat am ${date} um ${time} auf deine Frage geantwortet",
      "id": "username",
      "color": "Accent",
      "wrap": true,
      "size": "Small"
    },
    {
      "type": "ColumnSet",
      "separator": true,
      "spacing": "Large",
      "columns": [
        {
          "type": "Column",
          "items": [
            {
              "type": "RichTextBlock",
              "inlines": [
                {
                  "type": "TextRun",
                  "text": "${_source.question}",
                  "wrap": true,
                  "height": "stretch",
                  "id": "question"
                }
              ]
            }
          ],
          "width": "stretch"
        }
      ]
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "items": [
            {
              "type": "TextBlock",
              "text": "${_source.answer}",
              "id": "answer",
              "wrap": true,
              "height": "stretch",
              "size": "Large"
            }
          ],
          "width": "stretch"
        }
      ]
    },
    {
      "type": "ColumnSet",
      "separator": true,
      "spacing": "Large",
      "columns": [
        {
          "type": "Column",
          "width": 30,
          "items": [
            {
              "type": "RichTextBlock",
              "inlines": [
                {
                  "type": "TextRun",
                  "text": "Wie passend war die Antwort  auf deine Frage?\n\rScore ${formattedscore} bei ${_source.evaluation.count} Bewertungen",
                  "size": "Small",
                  "color": "Accent"
                }
              ]
            }
          ]
        },
        {
          "type": "Column",
          "width": 10,
          "items": [
            {
              "type": "ColumnSet",
              "spacing": "Medium",
              "columns": [
                {
                  "type": "Column",
                  "selectAction": {
                    "title": "",
                    "type": "Action.Submit",
                    "data": {
                      "id": "${id}",
                      "_id": "${_id}",
                      "channelid": "${channelid}",
                      "objectname": "QnaDispatcher",
                      "methodname": "Evaluate",
                      "parametervalue": "1",
                      "_source": {
                        "properties": {},
                        "evaluation": {
                          **"score": "${_source.evaluation.score}",  <- throws error**
                          "count": "${_source.evaluation.count}"
                        }
                      }
                    }
                  },
                  "items": [
                    {
                      "type": "Image",
                      "horizontalAlignment": "Center",
                      "url": "http://media.insyca.com/icon/thumbs-o-up.png"
                    }
                  ],
                  "width": "stretch"
                },
                {
                  "type": "Column",
                  "selectAction": {
                    "title": "",
                    "type": "Action.Submit",
                    "data": {
                      "id": "${id}",
                      "_id": "${_id}",
                      "channelid": "${channelid}",
                      "objectname": "QnaDispatcher",
                      "methodname": "Evaluate",
                      "parametervalue": "6",
                      "_source": {
                        "properties": {},
                        "evaluation": {
                          **"score": "${_source.evaluation.score}", <- throws error**
                          "count": "${_source.evaluation.count}"
                        }
                      }
                    }
                  },
                  "items": [
                    {
                      "type": "Image",
                      "title": "",
                      "horizontalAlignment": "Center",
                      "url": "http://media.insyca.com/icon/thumbs-o-down.png"
                    }
                  ],
                  "width": "stretch"
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.2"
}

**Data (this)**
{
  "_index": "qna",
  "_type": "_doc",
  "_id": "DwTjbXMByFVv5EHpI-mk",
  "_score": 2.302585,
  "_source": {
    "properties": {
      "timestamp": "2020-07-20T22:21:08.7580921+02:00",
      "username": "User",
      "objectname": "AttachmentConnector",
      "methodname": "GetCardAttachment",
      "parametervalue": "PersonalResponse.json"
    },
    "evaluation": {
      **"score": 17651.25, <- throws error**
      "count": 4
    },
    "question": "Gerhard",
    "tags": "",
    "answer": "Mann von Wilma"
  },
  "id": "94ba701e-0fbe-42fd-9936-79e300d8fa1d",
  "channelid": "8842c23e-99fe-4391-8d33-46d83655cf31",
  "date": "20.07.2020",
  "time": "22:21",
  "formattedscore": "17651,25"
}

**Comment by jwoo-msft** [comment]
@iwekardum 
this issue is no repro on master. it probably got fixed via [PR4345](https://github.com/microsoft/AdaptiveCards/pull/4345) The fix will be available in this month's patch release.
rendered card via main
![image](https://user-images.githubusercontent.com/4112696/88003454-c4ef5080-cab9-11ea-9bc6-7c3f8265a701.png)
