### ISSUE TITLE
No IAdaptiveCardConfig

### ISSUE THREAD

**Issue by ncipollina** [Microsoft/AdaptiveCards#445]
The documentation for Typescript says the following:

> npm install microsoft-adaptivecards
There are interface definitions in schema.d.ts which describe the shape of the schema.

```
let card :IAdaptiveCard = {
    "type": "AdaptiveCard",
    "version": "0.5",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "Meow!"
                },
                {
                    "type": "Image",
                    "url": "http://adaptivecards.io/api/cat"
                }
            ]
        }
    ]
};
```

> There is also an object model for creating cards.

```
let card :IAdaptiveCard =  new AdaptiveCard();
card.body.add(new TextBlock() 
{
    text = "hello world"
});
```

I do not see an IAdaptiveCard anywhere in the Typescript files.  Is this something that has changed and the documentation needs to be updated?

**Comment by dclaux** [comment]
Hi @ncipollina, the interface definitions are not up to date. There is a work item for this, I just haven't had a chance to do it yet. Sorry about that.

**Comment by ncipollina** [comment]
@dclaux are you saying that the documentation is more current than the code?  This would make sense because the part of the documentation that uses the AdaptiveCard is incorrect.  The new card object has no body property and the syntax for property initialization on the new TexBlock is incorrect.  It should be:
`
card.body.add(new TextBlock()
{
     text: "hello world"
});
`
The syntax in the documentation looks like C# to me.

**Comment by dclaux** [comment]
No, actually the code is more current than the documentation. The reference is the AdaptiveCard object model. Interfaces now have to be defined according to the object model - the ones that currently exist are not up to date. And yes, the example in the doc is wrong (it's not proper JS/TS.)

**Comment by dclaux** [comment]
It would be this:
```
var textBlock = new TextBlock();
textBlock.text = "Hello world";

var card = new AdaptiveCard();
card.addItem(textBlock);

var renderedCard = card.render();
```

**Comment by ncipollina** [comment]
And what if I want to add this AdaptiveCard as an attachment in a bot?  Assuming I have the following code:

```
let msg = new builder.Message(session)
     .addAttachment(card.render());
session.send(msg);
```

`card.render()` returns and `HTMLElement` and `addAttachment()` is expecting an `IAttachment` to be passed in.

**Comment by dclaux** [comment]
In its current state, the TypeScript HTML library offers an object model that can render to an HTML element. It does not provide serialization to a string, which is what you seem to want. At some point in the past few months, interfaces matching the object model were introduced for serialization purposes, but these interfaces have not been maintained as the object model evolved. I will need to update them. In addition to that, a toString() method will likely be added to the AdaptiveCard object to do the same. I hope to get these done soon.

For now, I would say your best bet is to just write your card as an object without using the library, and do a JSON.stringify() on it.

Does that make sense?

**Comment by ncipollina** [comment]
Yes, it makes sense.

**Comment by dclaux** [comment]
I would actually like to completely remove the schema interfaces. They are not very useful and are redundant with the OM. We should discuss.

**Comment by dclaux** [comment]
The Typescript renderer now supports serialization via the OM using the toJSON method. Here is how to use it:
```
let myCard = new AdaptiveCard();
// populate the card one way or another (either parse() a payload or dynamically add elements in code)

let serializedCard = JSON.stringify(myCard.toJSON());
```

Closing this issue - please reopen if necessary.
