### ISSUE TITLE
[JavaScript][Input Validation] Return warning if validation properties exist without an errorMessage

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#4451]
# Platform

* JavaScript

# Details

If the card author has set input validation properties but not set an errorMessage, return a warning to encourage the card author to add an errorMessage to provide more information to the user explaining why the input is invalid.

**Comment by dclaux** [comment]
This is fixed with this commit: https://github.com/microsoft/AdaptiveCards/commit/a7e2d6bd1fd5c9d140924ad050ef8ee7f15f048a

I forgot to create a separate branch, and the fix was pushed directly to `feature/inputEvaolution`
