### ISSUE TITLE
[Node.js][Templating] [$when should be marked as reserved]

### ISSUE THREAD

**Issue by sqrrrl** [microsoft/AdaptiveCards#4459]
# Platform

* JavaScript

# Author or host

Neither -- Using the templating library as a standalone library for JSON templating.

# Version of SDK

 adaptivecards-templating@1.0.0

# Details

When expanding a template with a $when conditional, the final output still contains a property "$when": true. This breaks usage when restrictive schemas are in place that don't allow additional properties.

Suggest adding $when to the list of reserved keywords so the property is removed from the final output.

To reproduce:

```
const ACData = require('adaptivecards-templating');

const template = new ACData.Template({
    values: [
        {
            $when: "${condition}",
            text: 'Hello'
        }
    ]
});

console.log(template.expand({
    $root: {
        condition: true
    }
}));
```

Expected output is:

```
{ values: [ { text: 'Hello' } ] }
```

Actual output is:

```
{ values: [ { '$when': true, text: 'Hello' } ] }
```

**Comment by RebeccaAnne** [comment]
Please reopen if this is still an issue with the latest packages
