### ISSUE TITLE
Documentation: Please document onShowPopupCard

### ISSUE THREAD

**Issue by Kikketer** [microsoft/AdaptiveCards#447]
The http://adaptivecards.io/documentation/#display-libraries-htmlclient page does not document the `onShowPopupCard`.  Users (like me) are not aware that it's a separate event from the shown `onExecuteAction`.

Related to: https://github.com/Microsoft/AdaptiveCards/issues/424

**Comment by dclaux** [comment]
I think you're raising a good point here. Not sure there is a need for two separate events. Folding them both into onExecuteAction would work just fine - what do you think?

**Comment by andrewleader** [comment]
Closing as everything seems to go through onExecuteAction now
