### ISSUE TITLE
Text Blocks default to false for wrap

### ISSUE THREAD

**Issue by anbah34** [microsoft/AdaptiveCards#4483]
# Platform

All Platforms. The issue is more relevant to Mobile - iOS and Android.

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.

If you're an author, who are you sending cards to?

1.2.10

What version are you using? Ex: NuGet 1.0.2, or latest main, etc...

# Details

Explain your issue. If you just have a question, please post [on StackOverflow instead

Why is it that the default value for the word wrapping is kept as false. Most times the developers test the card only on desktop and due to the large real estate the text does not get truncated but on mobile it does. I don't understand why the default value is not set to true for word wrap

![MicrosoftTeams-image-31](https://user-images.githubusercontent.com/65276405/88364696-5b18c480-cda1-11ea-834d-5ccb0e8e88b7.png)
<img width="307" alt="Screen Shot 2020-07-21 at 12 34 29 PM" src="https://user-images.githubusercontent.com/65276405/88364701-5d7b1e80-cda1-11ea-919d-d9c64dfe34ff.png">

**Comment by anbah34** [comment]
@shalinijoshi19 Please see the an example of the issue that is caused with the current behavior wherin the text gets truncated unless the developer has specified word wrap to be true

cc- @VikrantSingh01

**Comment by anbah34** [comment]
FYI @matthidinger, @jwoo-msft

**Comment by shalinijoshi19** [comment]
We'll be keeping the behavior here, but will be updating the designer instead.

**Comment by jwoo-msft** [comment]
Change for updating the designer is merged. Closing it per discussion.
