### ISSUE TITLE
[Android] Placeholder values of input components are not applied

### ISSUE THREAD

**Issue by Gunashree-R-V** [microsoft/AdaptiveCards#4484]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android

# Author or host

Microsoft Teams

# Version of SDK

1.2.10

# Details

As per the schema, Input components do have `placeholder` property which are to be shown when no selection has been made.

Placeholder properties aren't utilised on Android for Input.Number, Input.Date, Input.Time. 

Here is the experience:

| Android Experience | Desktop OOB Experience | Desktop Teams Experience |  iOS Teams Experience
|-----------|:-----------:|-----------:|  -----------:|  
| <img width="369" alt="Screenshot 2020-07-24 at 4 05 43 PM" src="https://user-images.githubusercontent.com/28745768/88383514-4d2a6a00-cdc8-11ea-98e9-528a9dc88b2b.png"> | <img width="489" alt="Screenshot 2020-07-24 at 4 06 29 PM" src="https://user-images.githubusercontent.com/28745768/88383641-8531ad00-cdc8-11ea-8eeb-15ebd9018db0.png"> | <img width="450" alt="Screenshot 2020-07-24 at 4 06 52 PM" src="https://user-images.githubusercontent.com/28745768/88383655-8bc02480-cdc8-11ea-80bb-3e1d18417614.png"> | ![image](https://user-images.githubusercontent.com/28745768/88384152-80212d80-cdc9-11ea-97e4-dac4f23b43f1.png) |

Here is the card JSON:

```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "text": "Date Input"
        },
        {
            "type": "Input.Date",
            "id": "date",
            "placeholder": "Enter a date"
        },
        {
            "type": "Input.Number",
            "id": "number",
            "placeholder": "Enter a number within 1-10",
            "min": 1,
            "max": 10
        },
        {
      "type": "Input.Text",
      "id": "input1",
      "placeholder": "enter comment",
      "maxLength": 500
    },
    {
      "type": "Input.Time",
      "id": "time",
      "min": "09:00",
      "max": "17:00",
      "placeholder": "Enter time between 9-17"
    }
    ]
}
```

cc: @VikrantSingh01, @anbah34, @shbhadra

**Comment by almedina-ms** [comment]
This has been fixed in version 2.0+, during one of our meetings it was decided to not backport this fix into 1.2
