### ISSUE TITLE
[JavaScript]Getting following error "initializeIcons is not a function" when trying to use adaptivecards-fabric.js

### ISSUE THREAD

**Issue by sadviramana** [microsoft/AdaptiveCards#4485]
I was trying to directly include the output adaptivecards-fabric.js file to my HTML file and use it to style my adaptive cards. I also included the dependencies cdn urls to my html.

    <script src="https://unpkg.com/adaptivecards/dist/adaptivecards.js"></script>
    <script src="https://unpkg.com/markdown-it@8.4.0/dist/markdown-it.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/16.8.6/umd/react.development.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.8.6/umd/react-dom.development.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fluentui-react/7.123.7/fluentui-react.js"></script>
    <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/css/fabric.min.css" />
    <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/css/fabric.components.min.css" />
    <script src="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/js/fabric.min.js"></script>

Can you please tell me what iam doing wrong here? I guess initializeIcons is from fluentui-react, which I have included.

**Comment by RebeccaAnne** [comment]
If this is still an issue for you please reopen
