### ISSUE TITLE
[MsTeams][Rendering] [Data Uri for images not working on MsTeams application]

### ISSUE THREAD

**Issue by Imari91** [microsoft/AdaptiveCards#4487]
# Author or host

I am the author and the host app is Ms Teams (either desktop and web), I am sending the adaptive card using Power Automate as personal chat message.

# Version of SDK

# Details

The data uri encoding worked few months ago and I have today tested directly on the designer, however the image is not displayed anymore on Microsoft Teams:

![image](https://user-images.githubusercontent.com/11196217/88467716-3411de00-ceda-11ea-83cc-18f4289614d0.png)

JSON:

`{"type":"AdaptiveCard","$schema":"http://adaptivecards.io/schemas/adaptive-card.json","version":"1.2","body":[{"type":"TextBlock","size":"Medium","weight":"Bolder","text":"New approval: ai processes and solutions"},{"type":"ColumnSet","columns":[{"type":"Column","items":[{"type":"Image","style":"Person","url":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAXM[...]","size":"Small"}],"width":"auto"},{"type":"Column","items":[{"type":"TextBlock","weight":"Bolder","text":"User title","wrap":true},{"type":"TextBlock","spacing":"None","text":"Created 25-07-2020","isSubtle":true,"wrap":true}],"width":"stretch"}]},{"type":"TextBlock","text":"Nueva aprobación pendiente","wrap":true},{"type":"ActionSet","actions":[{"type":"Action.Submit","title":"Approve","style":"positive","data":{"ActionTaken":"Approved"}},{"type":"Action.Submit","title":"Reject","data":{"ActionTaken":"Rejected"}}]}]}`

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4095
