### ISSUE TITLE
Input.Time control is not visible in Mobile Outlook Apps(Both Android and IoS)

### ISSUE THREAD

**Issue by Vishnuvk33** [microsoft/AdaptiveCards#4488]
Hi,
       We are doing the responsive adaptive cards (Can use in mobile as well as Desktop outlook Apps) for our customers( Our customer are willing to use adaptive cards)

      While we are using Input.Time control in 0365, The time control is visible.

      But in Mobile outlook app, The time control is not visible(Both in Android and ioS)

**Comment by RebeccaAnne** [comment]
Please raise this issue against Outlook , Thanks!
