### ISSUE TITLE
[MSTeams][Desktop/mobile] [Images are not getting render]

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [microsoft/AdaptiveCards#4491]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML
* Android
* iOS
* JavaScript

# Author or host
MsTeams

# Details

Hi Team,

I'm Facing an issue related to Images in adaptive card,

### Currently i'm using images stored in Azure blob . For many users who have good or great internet connection also getting "**undefined images**"  instead of real image in adaptive card.

please check screenshots
<img width="660" alt="Bot Screen shot" src="https://user-images.githubusercontent.com/60354515/88709536-efcd4a80-d132-11ea-9753-eebfa5cb57de.png">

I'm using blow adaptive card json for adaptive card
[CardJson.txt](https://github.com/microsoft/AdaptiveCards/files/4990542/CardJson.txt)

To resolve this issue we **tried to use base 64 image** format but  with this format it is taking lot of time to load card in bot conversation pane 

### this issue also affecting for different image types like GIF in adaptive card

**please Guide me what i have to do in such case??**
we need solution on this ASAP as it making impact on bot please help us.

Thank you

**Comment by Sujit-Gaikwad** [comment]
HI i'm not able to see any update or any assignment on this issue can you please update the status here

**Comment by RebeccaAnne** [comment]
This should be working for images that do not require authentication. Please reopen if you are still seeing this issue.
