### ISSUE TITLE
AdaptiveCard doesn't render in Office 365 ProPlus outlook (1902) software

### ISSUE THREAD

**Issue by TechMinder** [microsoft/AdaptiveCards#4493]
# Platform

What platform is your issue or question related to? (Delete other platforms).

Office 365 ProPlus

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.

I am trying to render an adaptive card in Office 365 Proplus outlook. I am author and hosting the card.

If you're an author, who are you sending cards to?

I am sending it to myself. It works in Browser and in Outlook 2016, but doesn't render in Office 365 ProPlus outlook.

# Version of SDK
I tried all but it seems only 1.0 works.

# Issue

There are multiple issues I am facing;
1) A card doesn't render in Outlook 365 ProPlus. It shows the script in the email body.
2) I see the card rendering in Outlook 2016 but it attached the JSON as well.
3) I am unable to refresh the Card after performing the action. I tried sending back response header as well but it didn't work

You can find the card JSON that I have posted along with the question on StackOverflow, and I haven't got any responses on StackOverflow. Maybe it's posted recently.

https://stackoverflow.com/questions/63142619/adaptivecard-doesnt-render-in-office-365-proplus-outlook
ProPlus outlook Version: https://github.com/TechMinder/Shared/blob/master/office%20version.png

Thanks,
Hitesh

**Comment by Atili0** [comment]
Hi team ,
Same error here. Can you help us ?

Saludos

**Comment by RebeccaAnne** [comment]
Please open this support ticket against Outlook for this issue.
