### ISSUE TITLE
[Android] AdaptiveRichTextBlock preceding whitespace issues for inline elements

### ISSUE THREAD

**Issue by natwallbank** [microsoft/AdaptiveCards#4498]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android

# Author or host

Host rendering cards - app is in development.

# Version of SDK

1.2.4

# Details

I've been using AdaptiveRichTextBlock to highlight certain words in a text block, and this renders fine in Windows Teams app and via the web.

However, I've just started testing the messages in the Android Teams app and notice that there are whitespace issues - it appears to be trimming any whitespace at the beginning of an `AdaptiveTextRun`

Example:

![image](https://user-images.githubusercontent.com/1752093/88919233-a714af00-d262-11ea-95ca-1e0828ecde3e.png)

vs

![image](https://user-images.githubusercontent.com/1752093/88919262-b136ad80-d262-11ea-81bd-2eeef57a2e78.png)

**Comment by natwallbank** [comment]
Note: it appears possible to work around this by using some other white space character, as provided here: https://qwerty.dev/whitespace/

**Comment by RebeccaAnne** [comment]
We believe this should be fixed in our latest versions. Please reopen if this is still an issue for you.
