### ISSUE TITLE
Need a code to convert website application into desktop application icon 

### ISSUE THREAD

**Issue by sonu-create** [microsoft/AdaptiveCards#4499]
Internet Explorer 

I launch a website application using internet explorer , I want to convert it into a desktop application and being launched as a small pop up window at users desktop instead of launching it through browser.

**Comment by paulcam206** [comment]
This isn't an Adaptive Cards issue. That being said, you might want to look into [Persistent Web Apps](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-edgehtml/get-started).

Good luck! 👍
