### ISSUE TITLE
BUG:  Invalid column size: Stretch in Visualizer but C# ColumnSize.Stretch = 'Stretch'

### ISSUE THREAD

**Issue by qpongo** [Microsoft/AdaptiveCards#450]
```
    public class ColumnSize
    {
        public const string Stretch = "Stretch";
```
doesn't match [http://adaptivecards.io/visualizer/index.html](http://adaptivecards.io/visualizer/index.html) so **an error is reported from JSON generated by the C# classes when pasted into visualizer.**

**Repro:**
1. build a card using C# classes and specify ColumnSize.Stretch..
```
Column col = new Column()
{
    Size = ColumnSize.Stretch,
```
2. Get the JSON created by the card
strJsonRtn = JsonConvert.SerializeObject(card, Formatting.None);
3.  Paste the JSON into the visualizer -- http://adaptivecards.io/visualizer/index.html

**Expected:**  No Errors

**Actual:**  Error - "Invalid column size: Stretch"

Minor bug but one side creates mixed case value for 'Stretch' and the other expects it not to be.

**Comment by matthidinger** [comment]
This should be fixed in the latest AdaptiveCards package

Full details here:
https://docs.microsoft.com/en-us/adaptive-cards/create/libraries/net
