### ISSUE TITLE
[MSTeams][Action.OpenURL] Open URl button is not working with some URls in Teams

### ISSUE THREAD

**Issue by Chekrii** [microsoft/AdaptiveCards#4500]
# Platform
* .NET Core

# Host
* Ms Teams

Hello Team,

I have built a bot using MS Bot framework v4 and hosted in MS teams.

I have noticed that the Action.OpenURL button is not working some time in the Adaptive card when URl is containing text with some Local language characters.

I have tried the same in App studio and the button is not clickable.

Please find the sample Adaptive card with Action.OpenURL below:-

```
{"type":"AdaptiveCard","$schema":"http://adaptivecards.io/schemas/adaptive-card.json","version":"1.2","body":[{"type":"TextBlock","wrap":true,"text":"The first open url is not working in MS Teams"}],"actions":[{"type":"Action.OpenUrl","url":"https://DummyHomepage.Com/esc?id=Look&spa=1&t=kb&q=política de carro","title":"OpenUrl not working"},{"type":"Action.Submit","title":"Cancel"}]}
```

Please help us with this as soon as possible.
Thanks.

**Comment by Chekrii** [comment]
Hello Team,

In the above json, I noticed that removing of 'í' from "política de carro" in open URL makes button clickable.

**Comment by Chekrii** [comment]
Hello Team, Can you please provide us the update on this bug or any alternative to make that button clickable.

**Comment by Chekrii** [comment]
Hello Team,

It is working in Adaptive visualizer but not in App studio and in Teams Bot. Please reply on this as soon as possible. 

Thanks.

**Comment by shereenfathy** [comment]
hello,
Any updates regarding this issue? it happened with me also.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4094
