### ISSUE TITLE
[Android][Images are either missing or too small]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#4518]
# Platform

* Android

# Version of SDK

20.07

# Details

* [ActivityUpdate.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Scenarios/ActivityUpdate.json) doesn't have the profile picture.
* [FlightItinerary.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Scenarios/FlightItinerary.json) has a very small image.
* [WeatherCompact.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Scenarios/WeatherCompact.json) doesn't have the weather image.
* [ProductVideo.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Scenarios/ProductVideo.json) doesn't have the poster.
* [ExpenseReport.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.2/Scenarios/ExpenseReport.json) doesn't have chevrons that toggle subviews. It appears that an image view is missing since the view handles the touch event. 

![Screenshot_20200731-170555](https://user-images.githubusercontent.com/4112696/89089060-4d8aae00-d350-11ea-8cbd-a7ee21919b29.png)

![Screenshot_20200731-171520](https://user-images.githubusercontent.com/4112696/89089321-95f69b80-d351-11ea-9cb7-b2ab404d02e3.png)

**Comment by paulcam206** [comment]
@golddove - possibly related to your recent changes?

**Comment by shalinijoshi19** [comment]
@almedina-ms / @golddove whats the status of this one? Still going in for 1.2.11?
