### ISSUE TITLE
[Android][Regression] [The Sizes of Images in ImageSet in Food Order May Be Different]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#4519]
# Platform

* Android

# Version of SDK

20.07

# Details
The images used to be in the same row.

![Screenshot_20200731-165801](https://user-images.githubusercontent.com/4112696/89088949-be7d9600-d34f-11ea-897d-ae65aea2f77c.png)

**Comment by jwoo-msft** [comment]
@golddove if the image size of the ImageSet is configurable through host config, feel free to close it.

**Comment by shalinijoshi19** [comment]
@almedina-ms / @golddove we did say this wasn't a ship blocker right?

**Comment by golddove** [comment]
Likely related to #4687
