### ISSUE TITLE
[javascript][New Event]Could we have an event dispatched after user activity on buttons and editor.

### ISSUE THREAD

**Issue by vaisrame** [microsoft/AdaptiveCards#4521]
**What platform is your feature request related to? (Delete other platforms).**
* JavaScript

**Is your feature request related to a problem? Please describe.**
Currently there is no way for the users to know when user does any action like copies/pastes/parse data either through buttons or via Monaco editor. We would like to add analytics on these to observe developer behaviour and right now there is no straight forward way. 

**Describe the solution you'd like**
Is it possible to emit an event after the following scenarios.
1. User copies data from Monco editor either through context menu or through keyboard.
2. User pastes data to Monaco editor
3. User copies data via Copy JSON button.
4. User tries to parse the card content using Parse Adaptive card button (can we also get errors if any during parsing?). 

**Describe alternatives you've considered**
We are considering to add event listener on the elements by class

**Comment by RebeccaAnne** [comment]
This is a good suggestion, but not something that's on our roadmap at this time. We may reconsider it in the future, or if you would like to make a contribution please see our contribution guidelines [here](https://github.com/microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md).
