### ISSUE TITLE
The 'https://adaptivecards.io/designer/' can be used

### ISSUE THREAD

**Issue by Cherise-xu** [microsoft/AdaptiveCards#4528]
The 'https://adaptivecards.io/designer/' can be used , the wrong is 'Uncaught SyntaxError: Unexpected end of input
jquery.min.dc5e7f.js:2 Uncaught ReferenceError: ACDesigner is not defined
    at HTMLDocument.<anonymous> ((index):760)
    at e (jquery.min.dc5e7f.js:2)
    at t (jquery.min.dc5e7f.js:2)'
Please deal with it as soon as possible,thank you

**Comment by paulcam206** [comment]
The [designer](https://adaptivecards.io/designer/) appears to be working for me. Is it still broken for you?

![image](https://user-images.githubusercontent.com/16614499/89819233-e9aa7700-daff-11ea-91ca-35bc629e1025.png)
