### ISSUE TITLE
[MsTeams][Button Styling issue] [Poor contrast between selected and non selected button]

### ISSUE THREAD

**Issue by sanjeev9160** [microsoft/AdaptiveCards#4530]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* MsTeams

# Author or host

Author

If you're an author, who are you sending cards to?
MsTeams

# Version of SDK

NA

# Details

The contrast between the selected button and the non-selected button is very difficult to find out.
[MsTeams:]
![image](https://user-images.githubusercontent.com/64134945/89264074-f33f6500-d64f-11ea-839a-b3e6208a08c5.png)

whereas in the adaptive card explorer we have the correct behavior
[AdaptiveCard explorer]
![image](https://user-images.githubusercontent.com/64134945/89264305-50d3b180-d650-11ea-9d5e-efcf33ebd654.png)

**Comment by shalinijoshi19** [comment]
@dclaux isn't the contrast something that's defined by the host via hostconfig (CSS in this Teams' case)? 
@sanjeev9160 what is the AdaptiveCards explorer again and can you please share your card json as well?
Thanks

**Comment by sanjeev9160** [comment]
@shalinijoshi19: I am using the https://adaptivecards.io/designer with the following settings: 
- host app -  Microsoft Teams - Light
- Target version: 1.2

Card Json:
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "Test Text",
                    "wrap": true
                },
                {
                    "type": "ActionSet",
                    "actions": [
                        {
                            "type": "Action.ShowCard",
                            "title": "Comment1",
                            "card": {
                                "type": "AdaptiveCard",
                                "body": [
                                    {
                                        "type": "Input.Text",
                                        "isMultiline": true,
                                        "id": "commentText",
                                        "placeholder": "Enter your comment"                                        
                                    },
                                    {
                                        "type": "ActionSet",
                                        "actions": [
                                            {
                                                "type": "Action.Submit",
                                                "title": "Submit"
                                            }
                                        ]
                                    }
                                ]
                            }
                        },
                        {
                            "type": "Action.ShowCard",
                            "title": "Comment2",
                            "card": {
                                "type": "AdaptiveCard",
                                "body": [
                                    {
                                        "type": "Input.Text",
                                        "isMultiline": true,
                                        "id": "commentText",
                                        "placeholder": "Enter your comment"                                        
                                    },
                                    {
                                        "type": "ActionSet",
                                        "actions": [
                                            {
                                                "type": "Action.Submit",
                                                "title": "Submit"
                                            }
                                        ]
                                    }
                                ]
                            }
                        }
                    ]
                }
            ]
        }
    ]
}

Please let me know if you need any additional information. Thanks.

**Comment by sanjeev9160** [comment]
Gentle Reminder on it. I can see the contrast difference in developer preview of teams. When do we expect the changes in the other versions of teams client.

**Comment by shalinijoshi19** [comment]
@siduppal / @Wajeed-msft could you  help with expected timelines for this issue on teh Teams client side? tx

**Comment by VaraPrasad-MSFT** [comment]
This is a feature request , could you please raise [user voice](https://microsoftteams.uservoice.com/forums/555103-public-preview/category/182881-developer-platform) for this.
