### ISSUE TITLE
[iOS][RichTextBlock Rendering] [Parity issue in RichTextBlock TextRun with action]

### ISSUE THREAD

**Issue by adumrewal** [microsoft/AdaptiveCards#4531]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Host - Teamspace iOS

# Version of SDK

1.2.10

# Details

TextRun in a RichTextBlock with selectAction renders differently across clients with difference in text color and underline style.
Desktop:
<img width="435" alt="Screenshot 2020-08-04 at 4 55 09 PM" src="https://user-images.githubusercontent.com/8917620/89295530-c9e9fd80-d67e-11ea-9f72-b44bb20f8d9c.png">
iOS:
<img width="327" alt="Screenshot 2020-08-04 at 6 15 04 PM" src="https://user-images.githubusercontent.com/8917620/89295553-cf474800-d67e-11ea-85d2-fac8b5070502.png">

cardJSON:
```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.2",
  "body": [
    {
      "type": "RichTextBlock",
      "inlines": [
        {
          "type": "TextRun",
          "text": "This is the first inline.",
          "selectAction": {
            "type": "Action.OpenUrl",
            "title": "Action.OpenUrl",
            "url": "http://adaptivecards.io"
          }
        }
      ]
    }
  ]
}
```

**Comment by shalinijoshi19** [comment]
@matthidinger / @dclaux / @RebeccaAnne is this supposed to be by design depending on how each platform renders hyperlinks for this specific case where the selectAction is of type "OpenUrl"?

**Comment by jwoo-msft** [comment]
@jwoo-msft Can you check if Android has the same issue?

**Comment by anbah34** [comment]
@jwoo-msft Can you please add this to the next SDK uptake?

**Comment by jwoo-msft** [comment]
@RebeccaAnne and @paulcam206 
Should we discuss this in the design discussion meeting or can we just use the procedure we defined for handling missing and invalid values of required properties?

**Comment by anbah34** [comment]
@jwoo-msft any updates on this?

**Comment by jwoo-msft** [comment]
Gentle ping to @jonmill, @RebeccaAnne and @paulcam206
