### ISSUE TITLE
[JavaScript][Rendering] Library doesn't respect column width for card rendering

### ISSUE THREAD

**Issue by pappk** [microsoft/AdaptiveCards#4545]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Author or host

Host, I am rendering cards that were generated by Microsoft Teams applications, bots.

# Version of SDK

v1.2.6

# Details

I am rendering cards that were generated by Microsoft Teams applications. In the following example, this card was generated by the Team's Praise app. In the JSON of the card shows explicitly the column widths. However, the rendered card is displayed with different column width settings. The source code for reproduction can be found here: https://github.com/pappk/ms-adaptive-card-issue-report/blob/master/adptive-card-test.html

The card JSON:
```
var card = {
  "type": "AdaptiveCard",
  "body": [
	{
	  "columns": [
		{
		  "width": "2.6",
		  "items": [
			{
			  "altText": "Awesome",
			  "horizontalAlignment": "center",
			  "url": "https://statics.retailservices.teams.cdn.office.net/ui/static/praise/develop/all/assets/badges/en-GB/AwesomeBadge.ce6dd1dd36.png",
			  "height": "auto",
			  "type": "Image"
			}
		  ],
		  "type": "Column"
		},
		{
		  "width": "6",
		  "items": [
			{
			  "isSubtle": true,
			  "size": "small",
			  "text": "John Doe sent praise to",
			  "wrap": true,
			  "type": "TextBlock"
			},
			{
			  "size": "medium",
			  "text": "Jane Doe",
			  "weight": "bolder",
			  "wrap": true,
			  "spacing": "small",
			  "type": "TextBlock"
			},
			{
			  "text": "",
			  "wrap": true,
			  "spacing": "small",
			  "type": "TextBlock"
			}
		  ],
		  "spacing": "medium",
		  "type": "Column"
		}
	  ],
	  "spacing": "large",
	  "separator": true,
	  "type": "ColumnSet"
	}
  ],
  "$schema": "https://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0"
};
```

The rendered output is the following:
![image](https://user-images.githubusercontent.com/6438434/89516640-016cbd00-d7d9-11ea-9c9b-49e2d5356a0e.png)

Instead of:

![image](https://user-images.githubusercontent.com/6438434/89516811-31b45b80-d7d9-11ea-9537-2cb92300eeb2.png)

The problem is with the second `.ac-container` div element's inline style. Because it has the following style: `flex: 1 1 100%;` instead of a smaller amount. Also, the first container div has a bigger width setting (50%) but the main problem is with the second container in case of a "thumbnail card like"  layout

**Comment by shalinijoshi19** [comment]
@dclaux I am seeing slightly different behaviors here with this card on the [designer](https://adaptivecards.io/designer) depending on what hostconfig I use, in addition to seeing this warning with it.. Thoughts? Could that be the reason why the height property is being disregarded? 

`[Parse] Invalid value "auto" for property "height".`

**Comment by dclaux** [comment]
@pappk I see two problems with this payload:
- The Image's height is set to `"auto"`. That is not supported, contrary to what the documentation says (we'll have to fix the documentation.) An Image's size is controlled either via its `"size"` property (which can be set to **auto**, **stretch**, **small**, **medium** or **large**) or via its `"width"` and `"height"` properties to specify explicit pixels dimensions in the **"\<number of pixels\>px"** format (e.g. "25px")
- To set a Column's width as a weight that weight has to be expressed as a number, not a string.

The JS SDK otherwise functions as expected. Please update your card and you should be able to achieve what you want.

@shalinijoshi19 how would you like to proceed for the documentation issue? Do you want to repurpose this one or create another?

**Comment by pappk** [comment]
@dclaux So, you say the source JSON is incorrect, isn't it? My concern with this is the following, I am not the author of the content JSON. I've captured this content JSON from Microsoft Teams, and the content was generated by the following official Microsoft product: https://support.microsoft.com/en-us/office/send-praise-to-people-50f26b47-565f-40fe-8642-5ca2a5ed261e. Also, in the Teams client the card is rendered correctly.

**Comment by dclaux** [comment]
@pappk yes, the JSON is incorrect. My guess is that this might be an older card that hasn't been updated. The JS SDK used to accept column weights expressed as strings but the other SDKs didn't, so the JS SDK was made more strict to match, at the risk of breaking some existing cards. I think this is an example of that.

As for the image's "height": "auto" I need to clarify: It is "supported" (it's the default), but it doesn't control the size of the actual image, just the size of the image's host element. In the payload, the image size defaults to stretch (e.g. use whatever horizontal space is available) and the width of its containing column is derived from the width of the text in the right hand side column. So there is no documentation error, that is my mistake.

I'll try to find the owners of the scenario to see if they can update their card.

**Comment by pappk** [comment]
@dclaux thank you for the explanation. I've repeated the content recording with the Praise card and the result is the same.

I've tried to manipulate the recorded data manually and I've changed the string width values to numbers as you described. That modification solves the rendering issue. This means before I would use your SDK I have to check every card content JSON and convert every column's width string to number recursively before rendering. It is really inefficient solution for my case.

This string-number type acceptance change is interesting because in the following schema specification says the width property can be string and number too. https://adaptivecards.io/explorer/Column.html. Also, there is a card specification version number, this type-change could be bind to that version number. My example shows that official Microsoft products don't match with their own schema specification.

**Comment by dclaux** [comment]
@pappk yes, Column.width can be string or number, but when it is a string it has to be a pixel size (e.g. "25px")

I am sorry for the inconvenience of having to deal with this change, but technically the JS renderer was too lenient originally and didn't match the behavior of the other SDKs (or the documentation).

**Comment by shalinijoshi19** [comment]
@RebeccaAnne can you pls update this Thanks!

**Comment by RebeccaAnne** [comment]
@pappk Since this card is behaving according to current design, we're closing this issue for now. That said, I've opened #4564 to track the possibility of updating all renderers to support this case where the number value is passed as a string. Please feel free to track that issue for updates on this topic. Thanks for bringing this issue to our attention.
