### ISSUE TITLE
[Website] [Need an end to end example for Power Automate/Flow]

### ISSUE THREAD

**Issue by bandtank** [microsoft/AdaptiveCards#4547]
The samples page does not actually help a beginner get started. I have no idea where to paste the template code so it can be used nor do I understand how to create a flow that uses it. A complete example from the very beginning to the very end with screenshots seems like an obvious omission. I basically have no idea how to use any of this information because the other documentation assumes the user already knows what to do.

---
* URL: https://adaptivecards.io/samples/

**Comment by matthidinger** [comment]
Thank you for providing us your feedback. I agree we need to do better surfacing the Getting Started docs with our various partners. We've actually got some explorations in the backlog that should help with this, and I'm hoping to make progress and share more in the next few months.

**Comment by RebeccaAnne** [comment]
This link should include the documentation you need: https://docs.microsoft.com/en-us/power-automate/create-adaptive-cards
