### ISSUE TITLE
[Mobile][Usability] [Chevron no reset issue in Action.ShowCards ]

### ISSUE THREAD

**Issue by manujai** [microsoft/AdaptiveCards#4548]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* Android
* iOS

# Author or host
Host on Webex Teams

# Version of SDK
We have our own fork of AdaptiveCards@v1.2.11

# Details
The Chevron on Action.ShowCards() buttons does not reset back to their default state when a different button is pressed. 
For example, 
1) Lets say, we have two buttons which have chevrons pointing downwards as its default state. (Expected)
2) Button A is pressed and chevron A points upwards and a card is displayed at the bottom (Expected) 
3) Button B is pressed and chevron B points downwards and the card associated with Button B is displayed, but the chevron A does not resets back to its default state (which is pointing downwards) 

A fix is required where pressing a Action.ShowCards() button resets the state of all the other chevrons. 

Attached videos for reference. 

![ezgif-4-08afaf15ed7b](https://user-images.githubusercontent.com/69314716/89553902-c182f580-d82b-11ea-8f95-316ca54662be.gif)
![ezgif-4-be9e7aa0cea7](https://user-images.githubusercontent.com/69314716/89554011-e8412c00-d82b-11ea-8022-aa149a2e7921.gif)

**Comment by shalinijoshi19** [comment]
@almedina-ms can you take a look at this real quick please? Thanks

**Comment by shalinijoshi19** [comment]
@almedina-ms can you take a look at this one while @jwoo-msft is OOF? thanks
