### ISSUE TITLE
Ms Teams margin issue in header adaptive cards

### ISSUE THREAD

**Issue by ravikant15796** [microsoft/AdaptiveCards#4555]
# Platform

* JavaScript
* MS Teams

# Details
There is some extra margin coming in header while using  **separator : true**  in TextBlock as highlighted in attached screenshot.

![issue](https://user-images.githubusercontent.com/10558023/89635488-ac0dda00-d8c4-11ea-911e-087d8ef9dc59.png)

cards json schema:-

{
  "text": "",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "content": {
        "type": "AdaptiveCard",
        "version": "1.0",
        "body": [
          {
            "type": "TextBlock",
            "text": "Here are some things you can ask for :",
            "wrap": true,
            "size": "medium"
          },
          {
            "type": "ColumnSet",
            "bleed": false,
            "separator": true,
            "spacing": "medium",
            "columns": [
              {
                "type": "Column",
                "width": "auto",
                "spacing": "small",
                "items": [
                  {
                    "type": "Image",
                    "url": "ww.xyz.png",
                    "height": "20px",
                    "style": "person",
                    "size": "small"
                  }
                ]
              },
              {
                "type": "Column",
                "width": 4,
                "items": [
                  {
                    "type": "TextBlock",
                    "text": "Product Walkthrough Video",
                    "color": "accent",
                    "size": "medium"
                  }
                ]
              }
            ],
            "selectAction": {
              "type": "Action.Submit",
              "id": 0,
              "title": "Product Walkthrough Video",
              "data": {
                "msteams": {
                  "type": "imBack",
                  "value": "Product Walkthrough Video"
                }
              }
            }
          },
          {
            "type": "ColumnSet",
            "bleed": false,
            "separator": true,
            "spacing": "medium",
            "columns": [
              {
                "type": "Column",
                "width": "auto",
                "spacing": "small",
                "items": [
                  {
                    "type": "Image",
                    "url": "ww.xyz.png",
                    "height": "20px",
                    "style": "person",
                    "size": "small"
                  }
                ]
              },
              {
                "type": "Column",
                "width": 4,
                "items": [
                  {
                    "type": "TextBlock",
                    "text": "Do you Know",
                    "color": "accent",
                    "size": "medium"
                  }
                ]
              }
            ],
            "selectAction": {
              "type": "Action.Submit",
              "id": 1,
              "title": "Do you Know",
              "data": {
                "msteams": {
                  "type": "imBack",
                  "value": "Do you Know"
                }
              }
            }
          },
          {
            "type": "ColumnSet",
            "bleed": false,
            "separator": true,
            "spacing": "medium",
            "columns": [
              {
                "type": "Column",
                "width": "auto",
                "spacing": "small",
                "items": [
                  {
                    "type": "Image",
                    "url": "ww.xyz.png.png",
                    "height": "20px",
                    "style": "person",
                    "size": "small"
                  }
                ]
              },
              {
                "type": "Column",
                "width": 4,
                "items": [
                  {
                    "type": "TextBlock",
                    "text": "Health & Well Being",
                    "color": "accent",
                    "size": "medium"
                  }
                ]
              }
            ],
            "selectAction": {
              "type": "Action.Submit",
              "id": 2,
              "title": "Health & Well Being",
              "data": {
                "msteams": {
                  "type": "imBack",
                  "value": "Hey, Please help me with Health & Well Being options"
                }
              }
            }
          },
          {
            "type": "ColumnSet",
            "bleed": false,
            "separator": true,
            "spacing": "medium",
            "columns": [
              {
                "type": "Column",
                "width": "auto",
                "spacing": "small",
                "items": [
                  {
                    "type": "Image",
                    "url": "ww.xyz.png",
                    "height": "20px",
                    "style": "person",
                    "size": "small"
                  }
                ]
              },
              {
                "type": "Column",
                "width": 4,
                "items": [
                  {
                    "type": "TextBlock",
                    "text": "Plan my Day",
                    "color": "accent",
                    "size": "medium"
                  }
                ]
              }
            ],
            "selectAction": {
              "type": "Action.Submit",
              "id": 3,
              "title": "Plan my Day",
              "data": {
                "msteams": {
                  "type": "imBack",
                  "value": "Plan my Day"
                }
              }
            }
          },
          {
            "type": "ColumnSet",
            "bleed": false,
            "separator": true,
            "spacing": "medium",
            "columns": [
              {
                "type": "Column",
                "width": "auto",
                "spacing": "small",
                "items": [
                  {
                    "type": "Image",
                    "url": "ww.xyz.png",
                    "height": "20px",
                    "style": "person",
                    "size": "small"
                  }
                ]
              },
              {
                "type": "Column",
                "width": 4,
                "items": [
                  {
                    "type": "TextBlock",
                    "text": "Leave & Attendance",
                    "color": "accent",
                    "size": "medium"
                  }
                ]
              }
            ],
            "selectAction": {
              "type": "Action.Submit",
              "id": 4,
              "title": "Leave & Attendance",
              "data": {
                "msteams": {
                  "type": "imBack",
                  "value": "Hey, Please help me with leave related options?"
                }
              }
            }
          },
          {
            "type": "ColumnSet",
            "bleed": false,
            "separator": true,
            "spacing": "medium",
            "columns": [
              {
                "type": "Column",
                "width": "auto",
                "spacing": "small",
                "items": [
                  {
                    "type": "Image",
                    "url": "ww.xyz.png",
                    "height": "20px",
                    "style": "person",
                    "size": "small"
                  }
                ]
              },
              {
                "type": "Column",
                "width": 4,
                "items": [
                  {
                    "type": "TextBlock",
                    "text": "Recruit",
                    "color": "accent",
                    "size": "medium"
                  }
                ]
              }
            ],
            "selectAction": {
              "type": "Action.Submit",
              "id": 5,
              "title": "Recruit",
              "data": {
                "msteams": {
                  "type": "imBack",
                  "value": "Hey, Please help me with Recruit related options?"
                }
              }
            }
          },
          {
            "type": "ColumnSet",
            "bleed": false,
            "separator": true,
            "spacing": "medium",
            "columns": [
              {
                "type": "Column",
                "width": "auto",
                "spacing": "small",
                "items": [
                  {
                    "type": "Image",
                    "url": "ww.xyz.png",
                    "height": "20px",
                    "style": "person",
                    "size": "small"
                  }
                ]
              },
              {
                "type": "Column",
                "width": 4,
                "items": [
                  {
                    "type": "TextBlock",
                    "text": "Employee Information",
                    "color": "accent",
                    "size": "medium"
                  }
                ]
              }
            ],
            "selectAction": {
              "type": "Action.Submit",
              "id": 6,
              "title": "Employee Information",
              "data": {
                "msteams": {
                  "type": "imBack",
                  "value": "Hey, Please help me with Employee information related options?"
                }
              }
            }
          },
          {
            "type": "ColumnSet",
            "bleed": false,
            "separator": true,
            "spacing": "medium",
            "columns": [
              {
                "type": "Column",
                "width": "auto",
                "spacing": "small",
                "items": [
                  {
                    "type": "Image",
                    "url": "ww.xyz.png",
                    "height": "20px",
                    "style": "person",
                    "size": "small"
                  }
                ]
              },
              {
                "type": "Column",
                "width": 4,
                "items": [
                  {
                    "type": "TextBlock",
                    "text": "General Query",
                    "color": "accent",
                    "size": "medium"
                  }
                ]
              }
            ],
            "selectAction": {
              "type": "Action.Submit",
              "id": 7,
              "title": "General Query",
              "data": {
                "msteams": {
                  "type": "imBack",
                  "value": "Hey, Please help me with general query options?"
                }
              }
            }
          },
          {
            "type": "ColumnSet",
            "bleed": false,
            "separator": true,
            "spacing": "medium",
            "columns": [
              {
                "type": "Column",
                "width": "auto",
                "spacing": "small",
                "items": [
                  {
                    "type": "Image",
                    "url": "ww.xyz.png",
                    "height": "20px",
                    "style": "person",
                    "size": "small"
                  }
                ]
              },
              {
                "type": "Column",
                "width": 4,
                "items": [
                  {
                    "type": "TextBlock",
                    "text": "Start a Meeting",
                    "color": "accent",
                    "size": "medium"
                  }
                ]
              }
            ],
            "selectAction": {
              "type": "Action.Submit",
              "id": 8,
              "title": "Start a Meeting",
              "data": {
                "msteams": {
                  "type": "imBack",
                  "value": "Start a Meeting"
                }
              }
            }
          },
          {
            "type": "ColumnSet",
            "bleed": false,
            "separator": true,
            "spacing": "medium",
            "columns": [
              {
                "type": "Column",
                "width": "auto",
                "spacing": "small",
                "items": [
                  {
                    "type": "Image",
                    "url": "ww.xyz.png",
                    "height": "20px",
                    "style": "person",
                    "size": "small"
                  }
                ]
              },
              {
                "type": "Column",
                "width": 4,
                "items": [
                  {
                    "type": "TextBlock",
                    "text": "Performance & Learning",
                    "color": "accent",
                    "size": "medium"
                  }
                ]
              }
            ],
            "selectAction": {
              "type": "Action.Submit",
              "id": 9,
              "title": "Performance & Learning",
              "data": {
                "msteams": {
                  "type": "imBack",
                  "value": "Hey, Please help me with performance  options?"
                }
              }
            }
          },
          {
            "type": "ColumnSet",
            "bleed": false,
            "separator": true,
            "spacing": "medium",
            "columns": [
              {
                "type": "Column",
                "width": "auto",
                "spacing": "small",
                "items": [
                  {
                    "type": "Image",
                    "url": "ww.xyz.png",
                    "height": "20px",
                    "style": "person",
                    "size": "small"
                  }
                ]
              },
              {
                "type": "Column",
                "width": 4,
                "items": [
                  {
                    "type": "TextBlock",
                    "text": "Sales Enablement",
                    "color": "accent",
                    "size": "medium"
                  }
                ]
              }
            ],
            "selectAction": {
              "type": "Action.Submit",
              "id": 10,
              "title": "Sales Enablement",
              "data": {
                "msteams": {
                  "type": "imBack",
                  "value": "Hey, Please help me with Sales Enablement options?"
                }
              }
            }
          }
        ],
        "actions": []
      }
    }
  ]
}

**Comment by shalinijoshi19** [comment]
@ravikant15796 do you happen to have a simpler card json for your issue here? Also does it also repro on our [designer](https://adaptivecards.io/designer) or only when rendered in Teams?

**Comment by ravikant15796** [comment]
it works fine in designer https://adaptivecards.io/designer/  and mobile devices but problem comes in teams desktop.
please refer below screenshots and card json.

Designer Screenshot :-
![designer_screenshot](https://user-images.githubusercontent.com/10558023/89891612-02478980-dbf3-11ea-9606-ccbf33d23a92.png)


Desktop Screenshot :-
![desktop_screenshot](https://user-images.githubusercontent.com/10558023/89892991-32902780-dbf5-11ea-8301-3bb45f49b893.png)

Mobile Screenshot : -
![mobile_screenshot (2)](https://user-images.githubusercontent.com/10558023/89893198-8b5fc000-dbf5-11ea-8539-ff7949a1530e.png)




Designer Card Payload :-
{
    "type": "AdaptiveCard",
    "body": [
        {
        "type": "TextBlock",
        "text": "Here are some things you can ask for :",
        "wrap": true,
        "size": "medium"
     },
  
    {
        "type": "ColumnSet",
        "bleed": false,
        "separator": true,
        "spacing": "medium",
        "columns": [
            {
                "type": "Column",
                "width": "auto",
                "spacing": "small",
                "items": [
                    {
                        "type": "Image",
                        "url": "https://img.icons8.com/material-outlined/2x/cloud-network.png",
                        "height": "20px",
                        "style": "person",
                        "size": "small"
                    }
                ]
            },
            {
                "type": "Column",
                "width": 4,
                "items": [
                    {
                        "type": "TextBlock",
                        "text": "Plan my Day",
                        "color": "accent",
                        "size": "medium"
                    }
                ]
            }
        ],
        "selectAction": {
            "type": "Action.Submit",
            "id": 3,
            "title": "Plan my Day",
            "data": {
                "msteams": {
                    "type": "imBack",
                    "value": "Plan my Day"
                }
            }
        }
    }
    ],
    "actions": [
        {
            "type": "Action.ShowCard",
            "title": "Set due date",
            "card": {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "Input.Date",
                        "id": "dueDate"
                    },
                    {
                        "type": "Input.Text",
                        "id": "comment",
                        "placeholder": "Add a comment",
                        "isMultiline": true
                    }
                ],
                "actions": [
                    {
                        "type": "Action.Submit",
                        "title": "OK"
                    }
                ],
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
            }
        },
        {
            "type": "Action.OpenUrl",
            "title": "View",
            "url": "${viewUrl}"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3"
}

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
