### ISSUE TITLE
[All Platforms] Support string values for non-string type properties

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#4564]
Currently the behavior for properties that are defined as number or boolean is that if the value of the property is a string it fails to parse, even if that string represents a valid value (i.e. "2" or "false"). Originally the JavaScript renderer did support parsing across type in this manner, but was changed to match the behavior on other platforms for consistency. This issue tracks adding this support to all platforms.

As you close per-platform tasks please tick the corresponding tasks off the list below. To prevent closing this issue with each task inadvertently, use the References keyword instead of resolves/fixes etc.

- [ ] .NET
- [ ] Android
- [ ] iOS
- [ ] JavaScript
- [ ] UWP

**Comment by shalinijoshi19** [comment]
@RebeccaAnne FYI i've moved this out to 20.11. But if we arent actively working on this perhaps move this out to Backlog?

**Comment by JeanRoca** [comment]
Not on the roadmap at the moment. Will resurface if things change.
