### ISSUE TITLE
[Android] Action.ShowCard is shown with different margin

### ISSUE THREAD

**Issue by golddove** [microsoft/AdaptiveCards#4568]
# Platform

* Android

# Version of SDK

latest main

# Details

Action.ShowCard cards show up with different margins depending on whether it is in an ActionSet or whether it is in the bottom action bar. 

`samples/v1.2/Elements/ActionSet.json`:

![image](https://user-images.githubusercontent.com/4442788/89940177-1dac9780-dbe7-11ea-820d-16c7c62c8ef4.png)

**Comment by shalinijoshi19** [comment]
@golddove is this an inconsistency issue or just somethign on Android? @almedina-ms thoughts on this one ?

**Comment by golddove** [comment]
Looks like just an Android bug to me, unless there's some design decision I'm missing.

**Comment by RebeccaAnne** [comment]
Doesn't meet the bug bar.
