### ISSUE TITLE
[Inconsistency] Card "style" property respected, but not in schema docs

### ISSUE THREAD

**Issue by golddove** [microsoft/AdaptiveCards#4569]
# Platform

* Android
* JavaScript

# Version of SDK

latest main

# Details

On Android, the "style" property seems to be respected for a "card" element. But our [schema doesn't mention it](https://adaptivecards.io/explorer/AdaptiveCard.html). On JavaScript, the property is ignored.

So, is the sample card / Android's implementation wrong? Or is the schema doc / JavaScript implementation wrong?

If the `style` property was deprecated from `card`, what is our replacement guidance on how to apply a style to card?

`v1.0/Elements/Action.ShowCard.Style.json`:

![image](https://user-images.githubusercontent.com/4442788/89945268-17221e00-dbef-11ea-8708-600325949f26.png)
![image](https://user-images.githubusercontent.com/4442788/89945283-1db09580-dbef-11ea-9206-0d255d0b142b.png)

**Comment by shalinijoshi19** [comment]
@jwoo-msft can you drive this conversation as part of the Inconsistencies bucket?

**Comment by RebeccaAnne** [comment]
Doesn't meet the bug bar.
