### ISSUE TITLE
Adds interactive maps support

### ISSUE THREAD

**Issue by Tpt** [microsoft/AdaptiveCards#457]
It would be great to allow to embed interactive maps in AdaptativeCards.
It could maybe be implemented by a new card Element "Map" that would have an attribute "geojson" with the GeoJson shape to display.
The "properties" field of the "Feature" GeoJson object could be use to embed interactive elements.
The map provider would be left to the renderer to choose (Bing maps, Here, Google Maps...).

**Comment by szul** [comment]
I can see this working for cards on web sites/applications, but not sure how it would be handled in things like Skype or Facebook Messenger. You can send a location via Skype, but this is an image snapshot that links to the map application on the phone (or other device), so it's essentially an image card with an action that points to a URL.

So the question would be: does a more generic embed type need to be created that potentially has different functionality depending on the targeted platform, but encompasses things like maps, SVG, etc., or does Microsoft want to stick to the lowest common denominator across platforms, and require an image card for this.

**Comment by matthidinger** [comment]
Thanks for the suggestion and discussion folks, we were actually discussing something very similar to your proposal a little while back. 

Ideally we could do as suggested and allow a pluggable MapRenderer if a Host wants to allow interactive maps within their experience. And we were considering by default we would simply use the Bing/Google maps APIs to generate static images, since as of now we don't want Adaptive Cards to have any 3rd party dependencies

Regarding a generic "embed" type that @szul mentions, we are also considering how to handle this separately. Would love to hear any feedback or requests here -- ideally in a separate issue to keep this one focused on Maps.

**Comment by vxnsbir1ugsp** [comment]
Very interested in such feature right now. What's the progress?

**Comment by vxnsbir1ugsp** [comment]
Someone??

**Comment by dclaux** [comment]
Hi @vxnsbir1ugsp, we are currently focused on closing the v1 feature set, and a map element won't be part of that. It is on the radar for a future version, but can't give any prediction as to if/when it'll happen at this time.

**Comment by alexarg** [comment]
Any updates on this? (Last comment was added 9 months ago)

**Comment by Oscar-Navarrete-Estevez** [comment]
Any update on this? (Last comment was added several months ago)

**Comment by noocyte** [comment]
We're also considering using Adaptive Cards for our municipality, public facing information. Map support out of the box would make that a lot easier.

**Comment by RebeccaAnne** [comment]
This is a good suggestion, but not something that's on our roadmap at this time. We may reconsider it in the future, or if you would like to make a contribution please see our contribution guidelines [here](https://github.com/microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md).

**Comment by jwalakom** [comment]
Hello Is there any update about this feature request? We are trying to explore a similar scenario! @RebeccaAnne

**Comment by brianpmccullough** [comment]
Yes.  customer would like to roll own "Locations" experience due to limitations around Out of the box experience.  like to use custom connector and display a search reault with embedded map.
