### ISSUE TITLE
[Android] Column stretch expands too much

### ISSUE THREAD

**Issue by golddove** [microsoft/AdaptiveCards#4570]
# Platform

* Android

# Version of SDK

latest main

# Details

Column.width = stretch seems to expand a column more than it should (note the textblocks on both ends fail to show their contents)

`v1.0/Elements/Column.Width.json`:

![image](https://user-images.githubusercontent.com/4442788/89959519-9ec95600-dc0a-11ea-8265-100f2ef88ad3.png)

**Comment by shalinijoshi19** [comment]
Reassigning to myself for verification, to load balance. @golddove FYI

**Comment by shalinijoshi19** [comment]
Blocked on getting hte latest unsigned APK on my device. Following up.

**Comment by shalinijoshi19** [comment]
@almedina-ms assigning to you for load balancing and also since I am unable to get the unsigned APK of the Visualizer nightly on my mobile device

**Comment by shalinijoshi19** [comment]
@almedina-ms / @RebeccaAnne i am moving this out to 20.11. @golddove holler if this is going to be a ship blocker.

**Comment by almedina-ms** [comment]
assigning to @golddove

**Comment by golddove** [comment]
Verified as fixed.
