### ISSUE TITLE
[Android] Container with selectAction submit throws error

### ISSUE THREAD

**Issue by golddove** [microsoft/AdaptiveCards#4571]
# Platform

* Android

# Version of SDK

latest main

# Details

Click on the third container in sample card. Error is thrown. Expected submit to work.

`v1.0/Elements/Container.SelectAction.json`

![image](https://user-images.githubusercontent.com/4442788/89960373-e05b0080-dc0c-11ea-8b6c-a94b6eea0a4e.png)

**Comment by RebeccaAnne** [comment]
@almedina-ms Can you check if this still repros? Thanks!

**Comment by almedina-ms** [comment]
This issue doesn't repro in latest main but the card in the picture doesn't match the json for the card in the repo. There's an extra container that the repo card doesn't have
