### ISSUE TITLE
[Inconsistency] Contained container offset differs by platform

### ISSUE THREAD

**Issue by golddove** [microsoft/AdaptiveCards#4572]
# Platform

* Android
* JavaScript

# Version of SDK

latest main

# Details

Contained container is offset in certain cases, but not in others. JavaScript/Android don't agree on behavior. Unclear which one is correct. 

Note the presence vs. absence of offset in the "Contained container - emphasis"

`v1.0/Elements/Container.Style.json`:

JavaScript:

![image](https://user-images.githubusercontent.com/4442788/89961027-8e1adf00-dc0e-11ea-9b9d-3aa3909e3ab1.png)

Android:

![image](https://user-images.githubusercontent.com/4442788/89960950-63308b00-dc0e-11ea-8a2c-29d9ab8aacce.png)

**Comment by shalinijoshi19** [comment]
@jwoo-msft / @golddove can you guys work together to bring some of these inconsistency conversations as part of the Wed design discussions (@RebeccaAnne FYI) and start to make progress on getting these answered/resolved ?

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
