### ISSUE TITLE
[nodejs][Keyboard shortcut] Ctrl+Enter not working when inlineAction associated with a text.input

### ISSUE THREAD

**Issue by scottlovegrove** [microsoft/AdaptiveCards#4575]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Author or host

Host, using the SDK to render adaptive cards ourselves

SDK version 2.0.0  on npm

# Details

When having an `inlineAction` set against a `Text.Input`, pressing ctrl+enter with the keyboard when in the input field should trigger the inline action, right now, it is not.

This is seen in Chrome (v84.0.4147.125), haven't tried this in other browsers, but would imagine it's the same.

**Comment by scottlovegrove** [comment]
In my own project, I had to use `e.ctrlKey && e.charCode === 13 && this.inlineAction` as my condition. I have created a fix for this, but I'm unsure whether to submit because apparently `charCode` is deprecated and `code` should be used, but that doesn't appear in my types as an available option 🤷‍♂️

**Comment by shalinijoshi19** [comment]
Thanks for raising and proposing the fix. @dclaux thoughts?

**Comment by dclaux** [comment]
@scottlovegrove I am able to repro this in Firefox, thanks for reporting and for proposing a fix. `charCode` is non-standard and deprecated though, so we can't use it. But so is `keyCode` which the code currently uses. [The guidance](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) is to use `KeyboardEvent.code` instead. While it is not supported in IE, I believe it is an OK compromise.

Could you update your change to use `KeyboardEvent.code` and make sure it works across browsers?

**Comment by scottlovegrove** [comment]
> Could you update your change to use KeyboardEvent.code and make sure it works across browsers?

@dclaux The problem I have here is that although the guidance is to use `KeyboardEvent.code`, I can't actually find any typescript type definitions that include this, so couldn't this end up breaking a build somewhere?

**Comment by shalinijoshi19** [comment]
@dclaux bringing this up to your attention.

**Comment by dclaux** [comment]
@scottlovegrove not sure what version of TypeScript you're using, but `KeyboardEvent.code` does show up for me:
![image](https://user-images.githubusercontent.com/1334689/93815684-3c04aa80-fc0b-11ea-905b-84e159993cf0.png)
