### ISSUE TITLE
Docs: remove isSelected from Input.ChoiceSet/Choice

### ISSUE THREAD

**Issue by matthidinger** [Microsoft/AdaptiveCards#458]
The default value of any input is set by the “value” property. So for a ChoiceSet with isMultiSelect = true, the default value would be a comma-separated list of values that matches the “value" property of one of the input’s choices.

- [x] Update docs
- [x] Update json-schema
- [x] Update Input.ChoiceSet sample
- [x] Update Schema Explorer

**Comment by zhusongm** [comment]
Good to know. Was going to ask about it. I'll make the change for .net renderer.

**Comment by matthidinger** [comment]
This is done
