### ISSUE TITLE
[iOS][Image Rendering][ResourceResolvers] Image not being replaced by new image in Grids via ResourceResolver

### ISSUE THREAD

**Issue by akaashdev** [microsoft/AdaptiveCards#4585]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Version of SDK

v1.2.11

# Details

We are trying to populate images in cards using **ResourceResolvers**. We first set an empty placeholder image in the imageView that was sent to the SDK via the Resolver methods. After the original image is downloaded we try to replace the same imageView with the new image. This seems to fail in some cards with grid layout. The placeholder image doesn't get replaced with the new image.

![resource-resolver_setting-new-image](https://user-images.githubusercontent.com/17749787/90143456-44133400-dd9b-11ea-8d9b-398474abfbee.gif)

### Steps to reproduce
* Create an array of UIImageView, *imageViews* (count equal to no. of images in grid)
* Pass the *imageView* via **resolveImageViewResource(_ url: URL?) -> UIImageView?** protocol method
* Set a placeholder image to the *imageView* after card renders. 
* Set a new image later to the *imageView*. This step fails on imageViews inside a grid.

### Samples payloads (JSON)
[image-gallery.txt](https://github.com/microsoft/AdaptiveCards/files/5069480/image-gallery.txt)
[food-order.txt](https://github.com/microsoft/AdaptiveCards/files/5069486/food-order.txt)

**Comment by jwoo-msft** [comment]
Hi @akaashdev 
Thanks for the feedback.
As this issue is now tracked by #4682, do you mind if I close this issue? You can reopen this issue if resolution to #4682 does not resolve this issue.

**Comment by akaashdev** [comment]
Yea sure!
Thanks! 👍
