### ISSUE TITLE
Missing downward arrow on the Action.ShowCard as shown in documentation

### ISSUE THREAD

**Issue by naveenkumarreddym** [microsoft/AdaptiveCards#4588]
Missing downward arrow on the Action.ShowCard as shown in the adaptive cards document

Screenshots
![image](https://user-images.githubusercontent.com/51904323/90231855-65c2f880-de39-11ea-8e97-8f09df2cfe1f.png)
![image](https://user-images.githubusercontent.com/51904323/90231878-6f4c6080-de39-11ea-80c7-1f4fc3a2f89f.png)

Version
1.2 and above

Describe the bug
Document showing different card and same is not working

Steps to reproduce
In the Adaptive card designer add Action.ShowCard
Cannot see the downward arrow.

Expected behavior

**Comment by golddove** [comment]
Styling is controlled by the host app that is displaying your card. For example, you can change the host app at the top of our designer to see what it will look like on Outlook (which does show the arrow):

![image](https://user-images.githubusercontent.com/4442788/90274789-2ee7e500-de2f-11ea-9236-5949e0e5ce67.png)

@dclaux / @matthidinger perhaps we should add the host config we use (in Schema Explorer / Samples) as an option in the designer?

**Comment by dclaux** [comment]
@golddove technically it is already in the designer, it's the Outlook one. The problem is setting expectations: if we defaulted to Outlook (or introduced a "Default") developers would still find discrepancies between the designer and the host they target.

**Comment by golddove** [comment]
@naveenkumarreddym 

Please check out the Outlook option in "Select host app" dropdown in designer. Feel free to re-open this issue if you have further questions.
