### ISSUE TITLE
XamlSubmitAction - PlatformNotSupportedException

### ISSUE THREAD

**Issue by HernanCote** [microsoft/AdaptiveCards#459]
Hey guys,

I'm writing a Xamarin.Forms application using the AdaptiveCards library and I've implemented an action callback for the XamlRenderer just like the WPF Sample.

What is happening is that the code works with the Xamarin.Forms UWP and Android Projects, but when I run the code on my iOS device and click the action, I get a PlatformNotSupportedException Exception from the XamlSubmitAction.cs file in the AdaptiveCards.Xaml Shared Project as you can see in the image:

![image](https://user-images.githubusercontent.com/17727598/27892537-e1278f48-61c5-11e7-8049-73fb06b9a0fb.png)

Is there anything that I'm not taking into account when working on Xamarin.Forms projects? Is this a blocker for implementing UI Actions in Xamarin.Forms iOS projects? if not, is there anything I can do to make it work?

Thanks in advance!

**Comment by matthidinger** [comment]
Weird, it seems we used some "advanced" dynamic features that aren't possible on all Xamarin platforms. @Clancey do you happen to have any insight here?

**Comment by Clancey** [comment]
Not sure why we didnt see this sooner, was this method always dynamic? https://github.com/Microsoft/AdaptiveCards/blob/a91c425a89784130f8e9603762574737d145977c/source/dotnet/Library/AdaptiveCards.Xaml.Shared/Rendering/RenderContext.cs#L129

Is it required that it is dynamic?

**Comment by matthidinger** [comment]
I'm pretty sure it's always been dynamic. @tomlm is most familiar with that code, he might know off hand. I'd have to dive in to see if it could be refactored, but that might be a little while since I'm heading out of town tonight. 

If anyone else wants to take a stab at it by all means!
