### ISSUE TITLE
[UWP][Image Rendering] Revisit image async loading

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#4593]
# Platform

* UWP

# Version of SDK

main

# Details

Async tasks used for Image loading in UWP should be refactored. As XamlBuilder owns the control over all async calls, small changes can break the detection of the moment when images finish loading, for example, this issue blocks PRs as #3113 . By going back to refactor this issue we can tackle other topics such as opening the functionality to wait for image loads in the nuget package version and the best way to expose it (adding an images loaded event vs having this functionality as part of an async call).

**Comment by paulcam206** [comment]
guessing that this will be addressed by #6323
