### ISSUE TITLE
[MSTeams][Adaptive card updation is not happening real time and has some issues]

### ISSUE THREAD

**Issue by DivyankaM** [microsoft/AdaptiveCards#4599]
# Platform

MS Teams

# Details

![image](https://user-images.githubusercontent.com/15843532/90361908-f6d5e180-e07c-11ea-804d-d939c5161c70.png)

The adaptive card doesn't get updated dynamically in a channel. This issue is happening sometimes. Switching to other channel and then coming back to the previous channel is a workaround that works for us, but this is not a good customer experience.
Please look into this issue and help us get this resolved.

**Comment by Wajeed-msft** [comment]
@DivyankaM - Thanks for reporting this. We are able to repro this at our end and are tracking it here: https://github.com/MicrosoftDocs/msteams-docs/issues/2011
Please follow [this issue](https://github.com/MicrosoftDocs/msteams-docs/issues/2011) for updates/progress/questions.
