### ISSUE TITLE
[iOS][MSTeams][EventID] [Select action covers Submit action]

### ISSUE THREAD

**Issue by GrayLeee** [microsoft/AdaptiveCards#4600]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* iOS

# Author or host
Microsoft Teams iOS app

# Version of SDK
Pod 1.0.3

# Details
Hello, I'm a SDE from Cortana in Teams iOS team of Microsoft. We use adaptive cards for Cortana skills like join meeting

<img width="120" alt="Screen Shot 2020-08-17 at 5 04 05 PM" src="https://user-images.githubusercontent.com/22672403/90378738-4da6df80-e0ac-11ea-8e4c-c5224e2dda70.png">

Currently we added a deep link in the flight, this link will bring user to meeting details page if user tapped whole card(except join button).

<img width="120" alt="Screen Shot 2020-08-17 at 5 10 39 PM" src="https://user-images.githubusercontent.com/22672403/90379027-c148ec80-e0ac-11ea-8682-e7d313564435.png">

But we found after we added this deep link, it would covers the link that join button would respond, so tapping join button would user to meeting details page too, that's not we want, join button should bring user to pre-join page like

<img width="120" alt="Screen Shot 2020-08-17 at 5 11 09 PM" src="https://user-images.githubusercontent.com/22672403/90379349-34526300-e0ad-11ea-9a93-2763118e1aa0.png">

We have verify in Android and they do not have this issue, and after debug primarily, we found both card and join button respond meeting details event, so we believe that the event of join button has been covered.

Here is the payload:
https://microsoft-my.sharepoint.com/:u:/p/jili15/EbhWz8n4WHlIrCRph08yywgBCmn5S3udBfhLKAQTsGy5tg?e=l3XZUV

**Comment by shalinijoshi19** [comment]
@jwoo-msft thoughts on this one? Are we still planning on investigating for 20.09?

**Comment by GrayLeee** [comment]
@jwoo-msft does anybody Investigating this bug?

**Comment by jwoo-msft** [comment]
@GrayLeee 
Hi, yes, I can repro. Let me get back to you shortly.

**Comment by GrayLeee** [comment]
@jwoo-msft 
Thanks for your help! If you have any question, ping me in Teams by jili15@microsoft.com. I'm sorry for bothering you, but a feature of Cortana is blocked by this issue.

**Comment by shalinijoshi19** [comment]
@GrayLeee / @jwoo-msft  moving this out to 20.11 given our tight timeline here.. @VikrantSingh01 FYI
