### ISSUE TITLE
[Input Validation] Add support for focusLost validation

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#4602]
Tracking issue for support for validating inputs on focusLost.

- [ ] .NET
- [ ] Android
- [ ] iOS
- [ ] JavaScript
- [x] UWP

**Comment by shalinijoshi19** [comment]
@RebeccaAnne are we still planning on shipping this for v20.09? This is merged at this point but as i understand it we are not prioritizing shipping this update.. Should this be reverted from main?

**Comment by RebeccaAnne** [comment]
@shalinijoshi19 None of this work is in main. The UWP implementation is in the feature/focusLostValidation branch.
