### ISSUE TITLE
[UWP][Input Validation] Clicking on input label does not put focus in input.

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#4606]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Details

Clicking on the label should put focus in the input box (see JavaScript behavior below). This does not happen in UWP.
![ClickLabel](https://user-images.githubusercontent.com/9091833/90429610-e290e500-e07a-11ea-9315-7cb3dbe43bf0.gif)

**Comment by RebeccaAnne** [comment]
@shalinijoshi19 I think we probably want to take the longer view on this. What I recall from working on this last year is that you get this for free if you use the XAML Header property. When I did that, however, it lead to the borders I was drawing to show invalid inputs surrounding the label and input rather than just the input. There may be a way to work around this (either another way to draw the border or a way to handroll the click to select behavior), but I think the right fix here is probably going to be to take a dependency on WinUI 3.0 and take advantage of the validation rendering that provides. I suspect, but don't know for sure, that using WinUI 3.0 for the validation UI will get us the validation rectangle in the right place while using the Header properly for the click to select property, hopefully with minimal code on our part.

**Comment by JeanRoca** [comment]
Closing this for now as not sure we will be able to get to it any time soon.
