### ISSUE TITLE
[JS] "selectAction" is not sending selected Input.ChoiceSet value to server.

### ISSUE THREAD

**Issue by edukondalugorla** [microsoft/AdaptiveCards#4609]
# Platform

What platform is your issue or question related to? 
* JavaScript

# Details:  "selectAction" is not sending selected Input.ChoiceSet value to server.

Hi,
I want to perform validation on selected choice set. But In below adaptive card, "selectAction" is not sending selected input choice value to server. It would to great if you help to read selected choice value by selectAction.
``` json
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "verticalContentAlignment": "Center",
  "type": "AdaptiveCard",
  "body": [
    {
  "selectAction": {
    "type": "Action.Submit",
    "id": "safas",
    "title": "",
    "data": {
      "formData": ""
    }
  },
  "type": "Container",
  "items": [
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "items": [
            {
              "spacing": "Small",
              "id": "leave_type_data",
              "placeholder": "",
              "isMultiSelect": false,
              "type": "Input.ChoiceSet",
              "choices": [{"title":"CL","value":"1"},{"title":"PL","value":"2"},{"title":"Birthday Leave","value":"3"}]
            }
          ]
        }
      ]
    }
  ]
}
  ]
}
```

**Comment by edukondalugorla** [comment]
What are the additional information you need. Please let me know, I will provide.

**Comment by jonmill** [comment]
This scenario of having a ChoiceSet with a selectAction on the body is not the recommended approach for this; we have #[6811](https://github.com/microsoft/AdaptiveCards/issues/4714) tracking the correct approach to take here
