### ISSUE TITLE
[Samples][Accessibility] Inputs in samples don't use labels

### ISSUE THREAD

**Issue by golddove** [microsoft/AdaptiveCards#4612]
# Platform

* All platforms

# Version of SDK

latest main

# Details

Tracking this as a reminder to "activate" the new samples created as part of #4552 to show them on the schema explorer. This is blocked on a critical mass of hosts support schema 1.3.

**Comment by almedina-ms** [comment]
assigning to @jwoo-msft

**Comment by RebeccaAnne** [comment]
We need to at least get this in PR for 21.03 to be reviewed by the accessibility team.

**Comment by golddove** [comment]
@RebeccaAnne @jonmill should probably combine this with #4552 at this point.

**Comment by jonmill** [comment]
Dupe of #4552
