### ISSUE TITLE
Disabled button is not supported.

### ISSUE THREAD

**Issue by animia** [microsoft/AdaptiveCards#4614]
**What platform is your feature request related to? (Delete other platforms).**

* .NET HTML
* Android
* iOS (Swift/Objective C)
* JavaScript

**Is your feature request related to a problem? Please describe.**
 When user click any button, we want to change button into disabled status. 

**Describe the solution you'd like**
 When user click any button, we want to change button into disabled button in local.
 It means button is changed into dimmed status without server's interaction.

**Describe alternatives you've considered**
 I think the alternative is dimmed button image which cannot be clicked.

**Additional context**

![image](https://user-images.githubusercontent.com/16422846/90603921-039e3500-e237-11ea-8426-7e1e4d14be7c.png)

**Comment by RebeccaAnne** [comment]
This will be introduced with our 1.5 release. See #4670
