### ISSUE TITLE
Pagination of list items

### ISSUE THREAD

**Issue by animia** [microsoft/AdaptiveCards#4615]
**What platform is your feature request related to? (Delete other platforms).**

* .NET HTML
* Android
* iOS (Swift/Objective C)
* JavaScript

**Is your feature request related to a problem? Please describe.**
 When there are many list items, we want to show list with pagination.

**Describe the solution you'd like**
 I suggest text with link and icon image.
 
**Describe alternatives you've considered**
 Text link can be alternatives.

**Additional context**
![image](https://user-images.githubusercontent.com/16422846/90604587-0a797780-e238-11ea-827d-b414a49ff5ce.png)

**Comment by RebeccaAnne** [comment]
This is not on our roadmap, but we are considering a carousel feature that may help with your scenario. Please track #6438 for updates.
