### ISSUE TITLE
Templating not working as expected when setting $data context for an array

### ISSUE THREAD

**Issue by pankajpalOlk** [microsoft/AdaptiveCards#4642]
If i try the template sample(Activity Update) provided here : https://adaptivecards.io/samples/ by clicking on the `Try it Yourself` but it doesnt seem to work.

This is what is not working:

  `{
            "type": "FactSet",
            "facts": [
                {
                    "$data": "${properties}",
                    "title": "${key}:",
                    "value": "${value}"
                }
            ]
        }`

Here is the data to bind to:
`{
"properties": [
        { "key": "Board", "value": "Adaptive Cards" },
        { "key": "List", "value": "Backlog" },
        { "key": "Assigned to", "value": "Matt Hidinger" },
        { "key": "Due date", "value": "Not set" }
    ]
}`

The snapshot attached on the sample page suggests this is supposed to work, but may be broken now..

**Comment by jwoo-msft** [comment]
Hello,
Please try clicking "Preview Mode" to enable template binding.

<img width="748" alt="Screen Shot 2020-08-24 at 11 39 40 AM" src="https://user-images.githubusercontent.com/4112696/91083273-d9fe5880-e5fe-11ea-8244-2784f419cdc8.png">

**Comment by pankajpalOlk** [comment]
Ah, got it! Thanks for quick reply.
