### ISSUE TITLE
[iOS][Image Rendering][ResourceResolvers] Image not visible when ImageView is passed with an Image via ResourceResolver

### ISSUE THREAD

**Issue by akaashdev** [microsoft/AdaptiveCards#4650]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Version of SDK

v1.2.11

# Details

The *imageView* passed via **ResourceResolver** is not visible when it already has an image in it.

### Steps to reproduce
- Create an **UIImageView**, *imageView* 
- Add an image to it. `imageView.image = UIImage(named: "foo")`
- Pass the *imageView* via **resolveImageViewResource(_ url: URL?) -> UIImageView?** protocol method
- The image won't be visible on the card

This also happens when the *imageView* is created with an image. `UIImageView(image: UIImage(named: "foo"))`

[sample_payloads.zip](https://github.com/microsoft/AdaptiveCards/files/5123362/sample_payloads.zip)

### Initial Investigations
Not sure whether this is the root cause. But yea, it was found that the constraints of the *imageView* gets set using Key-Value Observer on **image** property. Since this property is pre-filled before the KVO registers, the *imageView* never gets the correct constraints and it's not getting visible on screen.

**Comment by jwoo-msft** [comment]
Hi @akaashdev,

As we have discussed today,  you have to create a task as block and enque the task to the main queue. This will ensure proper synchronization.

```
   dispatch_async(dispatch_get_main_queue(), ^{
                          imageView.image = image;
                      });
```

However, this won't address your scenario of having a placeholder image to avoid re-draw on the entire Adaptive Card when the real image is available. For that, we will address the supporting placeholder image as a feature request after the internal review.

Thank you.

**Comment by jwoo-msft** [comment]
Hi @akaashdev 
Thanks for the feedback.
As this issue is now tracked by #4682, do you mind if I close this issue? You can reopen this issue if resolution to #4682 does not resolve this issue.

**Comment by akaashdev** [comment]
Hi @jwoo-msft 
Thanks for the suggestion. I can potentially see what this piece of code can do and you're right that this doesn't fix the issue what we're facing now. In fact this is something we already have in place.

And yes, this issue can be closed. We're okay until we have a ticket to track the issue. :)
Again, thanks for the support! 👍
