### ISSUE TITLE
[UWP] Manually constructed cards do not renderer correctly

### ISSUE THREAD

**Issue by chriche-ms** [microsoft/AdaptiveCards#4655]
# Platform

* UWP

# Author or host

Author and host. Cortana in Windows - app is both an author and host.

# Version of SDK

NuGet 1.2.10

# Details

When adaptive cards are 'manually' constructed (i.e. create a new AdaptiveCard instance, add an AdaptiveTextBlock to its body etc.) they do not render correctly. If the same card instances are serialized to JSON and parsed via a call to AdaptiveCard.FromJsonString they render correctly.

![adaptive card rendering issue](https://user-images.githubusercontent.com/34072661/91181996-8284e900-e6e1-11ea-8659-f62cde57f07e.png)

Note: email address has been redacted in image

**Comment by shalinijoshi19** [comment]
Hey @chriche-ms what were the follow-up's to this one again? _sorry if i missed an offline update here! _ thanks

**Comment by chriche-ms** [comment]
@shalinijoshi19 We were going to see if this is still an issue in 2.0 and later releases. I've just tested Cortana against the 2.1 release and it still exhibits this bug.

**Comment by shalinijoshi19** [comment]
@RebeccaAnne / @chriche-ms am assuming there hasnt been any active work on this one for this sprint? Moving out to next sprint  - @chriche-ms is this an upgrade blocker for you?

**Comment by chriche-ms** [comment]
This isn't a blocker for us. We have a workaround - serializing the cards and then parsing them to re-create the card object

**Comment by RebeccaAnne** [comment]
@chriche-ms Could you send me a sample json/code that this repros with? Thanks!

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.
