### ISSUE TITLE
Adaptive Card Designer not rendering properly FactSet component in Preview Mode

### ISSUE THREAD

**Issue by jesuspsalas2** [microsoft/AdaptiveCards#4657]
# Platform

Adaptive Cards Designer (v.1.1.0) / Angular 8 

# Details

Demo Card Preview snapshot when using the Desinger embedded in our app

![image](https://user-images.githubusercontent.com/44103405/91210049-7d17a680-e6c1-11ea-8bb1-4ff0b658b914.png)

Same card Preview on adaptivecards.io designer (same card and sample data jsons)

![image](https://user-images.githubusercontent.com/44103405/91210213-b819da00-e6c1-11ea-9c40-427cac91ebcb.png)

There might be something interfering with you designer?

**Comment by matthidinger** [comment]
Hi @jesuspsalas2, we just released v1.3.0 of the designer on npm, can you let us know if it still repro's there?

**Comment by shalinijoshi19** [comment]
> Hi @jesuspsalas2, we just released v1.3.0 of the designer on npm, can you let us know if it still repro's there?

Closing this out for now. @jesuspsalas2 please go ahead reactivate if you continue to observe this issue.. thanks!
