### ISSUE TITLE
[Designer] Incorrect warnings when templating expressions are used

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#4658]
# Platform
* Designer

# Details

When card templates using binding expressions, e.g., the [Stock card](https://adaptivecards.io/samples/StockUpdate.html), it shows a Parse error for enum values.

![image](https://user-images.githubusercontent.com/1432195/91215420-53627d80-e6c9-11ea-9ce8-61b0c806de5f.png)

We should suppress this error/warning if a templating expression is used

# Linked issue

Re this bug filed from our docs: https://github.com/MicrosoftDocs/AdaptiveCards/issues/323

**Comment by shalinijoshi19** [comment]
@dclaux are you able to pick this one up for 20.09?

**Comment by dclaux** [comment]
@shalinijoshi19 absolutely not :) This is a huge feature with lots of work behind it, including a huge change in the parser logic.

**Comment by dclaux** [comment]
To be more precise, doing this work will fit in the "live data binding" feature that we've been talking about and have on our roadmap for 2021+.
