### ISSUE TITLE
[iOS][Image Rendering][ResourceResolvers] BackgroundImage is not filled properly when set second time

### ISSUE THREAD

**Issue by akaashdev** [microsoft/AdaptiveCards#4667]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Version of SDK

v1.2.11

# Details

BackgroundImage seems not fill properly when set the second time on an *imageView* passed via **ResourceResolver**. We generally set a placeholder image first until the original image gets downloaded. So, when the original image tries to replace the placeholder, it doesn't follow proper filling.

![IMG_3092](https://user-images.githubusercontent.com/17749787/91315377-3fa43d80-e7d5-11ea-8e22-bfac5608c80f.jpeg)

Also, the icon images doesn't fill properly too.

#### Mac version of same card

<img width="451" alt="Screenshot 2020-08-26 at 7 41 14 PM" src="https://user-images.githubusercontent.com/17749787/91315132-ec31ef80-e7d4-11ea-94c3-661ea645f91e.png">

[card-details.zip](https://github.com/microsoft/AdaptiveCards/files/5130400/card-details.zip)
Attached the card payload and images in this zip.

**Comment by jwoo-msft** [comment]
@akaashdev 
This is similar to #4650. 

When an UIImage is set to an UIImageView, it will notify the observer and the observer sets the constraints on the UIImageVew based on UIImage's size attributes.  After the notification happens, the observer is removed, and no further notification will be generated. So if you used the observer for placeholder image, there will be no notification for the real image, so the constraints won't be proper likewise. 

If the use of the placeholder image is a requirement, this issue and #4650 will be a feature request.  Do Android and Desktop use placeholder images?

**Comment by akaashdev** [comment]
@jwoo-msft 
Use of placeholder image is definitely a requirement for us. The logic is to have a placeholder image, matching the dimensions of the original image, set before the original image comes in. This is to avoid the change in the card's height. We run into performance issues and sometimes in crash scenarios when the heights of the card (inturn the height of the cell) changes frequently.

**Comment by jwoo-msft** [comment]
> @jwoo-msft
> Use of placeholder image is definitely a requirement for us. The logic is to have a placeholder image, matching the dimensions of the original image, set before the original image comes in. This is to avoid the change in the card's height. We run into performance issues and sometimes in crash scenarios when the heights of the card (inturn the height of the cell) changes frequently.
> And yea, if there is any other way to tackle the height changing issue, we're happy to give it a shot. But still, we would prefer using a placeholder image shown first, as it sort of gives a visual feedback of an image being downloaded.

Hi @akaashdev 
Thanks for the feedback.
As this issue is now tracked by #4682, do you mind if I close this issue? You can reopen this issue if resolution to #4682 does not resolve this issue.

**Comment by akaashdev** [comment]
Sure! This can be closed!
Thanks! 👍
