### ISSUE TITLE
[iOS][Accessibility] ACRTextView placeholder text color too light

### ISSUE THREAD

**Issue by JustinBlock** [microsoft/AdaptiveCards#4672]
# Platform

What platform is your issue or question related to?

* iOS

# Author or host

Host

# Version of SDK

Latest main (2020.07)

# Details

ACRTextView placeholder text color is not using UIColor.placeholderText. The ACRTextView placeholder text color is lighter than the placeholderText color causing accessibility issues. In the attached screenshots the “Tell me hey you’re calling (briefly)” text is the rendered adaptive card. I’ve attached a screenshot with accessibility -> increase contrast to better show the text color difference.

![Untitled](https://user-images.githubusercontent.com/1756997/91350582-be7c8480-e79b-11ea-8b41-13d748133113.jpeg)

**Comment by jwoo-msft** [comment]
@JustinBlock 
What's your target iOS version? placeholderTextColor is only available on iOS 13+ https://developer.apple.com/documentation/uikit/uicolor/3173134-placeholdertextcolor?language=objc
Thanks

**Comment by JustinBlock** [comment]
@jwoo-msft I am running on iOS 13.6. In my example the top text block is using UIColor.placeholderTextColor but the bottom rendered card isn’t.

**Comment by jwoo-msft** [comment]
> @jwoo-msft I am running on iOS 13.6. In my example the top text block is using UIColor.placeholderTextColor but the bottom rendered card isn’t.

Yes, I can update the UITextColor to placeholder text color for the devices with iOS 13+.
