### ISSUE TITLE
[MSTeams][Special Characters in Adaptive Cards][Backslash Characters in Adaptive Card showing strange behavior]

### ISSUE THREAD

**Issue by apurva1112** [microsoft/AdaptiveCards#4677]
# Platform
* MSTeams

# Author or host
Authon

If you're an author, who are you sending cards to?
MSTeams

# Version of SDK
What version are you using? Ex: NuGet 1.0.2, or latest main, etc...
NA

# Details

Explain your issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards).

We are seeing strange behavior when escaping backslash characters in adaptive card text body.
Card JSON
>{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "text": "Sample textblock - \\\\ \\\\\\\\ \\\\\\\\\\\\ \\\\\\\\\\\\\\\\ \\\\\\\\\\\\\\\\\\\\ \\\\\\\\\\\\\\\\\\\\\\\\ "
        }
    ]
}

Bot Preview - 
![image](https://user-images.githubusercontent.com/42499837/91412967-1b457100-e868-11ea-93a9-ea2908140dbb.png)

**Expected behavior** - for every two consecutive backslash characters, teams adaptive card should output one '\\' char.

| No of backslash chars in Adaptive Card JSON TextBlock | Expected no of chars to be displayed on teams adaptive card | Actual no of chars displayed on teams adaptive card |
|-----|-----|-----|
| 2 | 1 | 1
| 4 | 2 | 1
| 6 | 3 | 2
| 8 | 4 | 2
| 10 | 5 | 3
| 12 | 6 | 3

**Comment by shalinijoshi19** [comment]
@apurva1112 have you tried this combination on our stock AC tool - https://adaptivecards.io/designer? Do you continue to observe the unexpected behavior?

**Comment by Trinetra-MSFT** [comment]
@shalinijoshi19 @apurva1112 , We can repro this issue at our end. We tested this for Bot & Designer,special character are coming as it is

**Designer**:
![image](https://user-images.githubusercontent.com/50989436/93848357-fdccc100-fcc6-11ea-9141-4e7f1f6bf639.png)

**Bot**
![image](https://user-images.githubusercontent.com/50989436/93848388-10df9100-fcc7-11ea-90a5-5929eeb09e06.png)

I will file a Bug for this.

**Comment by apurva1112** [comment]
@Trinetra-MSFT Thanks for acknowledging, we are facing significant number of errors due to this.  Please keep us posed on updates regarding fixing of this bug.

**Comment by Trinetra-MSFT** [comment]
This is expected behavior with the "escape" rule in the CommonMark Spec - played around with the example (https://spec.commonmark.org/0.15/#backslash-escapes). Will have to investigate what the impacts are in disabling the "escape" rule - so far, it seems that by disabling the rule, there would be no way to escape Markdown rules (i.e. if there is something that is considered as Markdown, it would be interpreted as such)

**Comment by WinIT23** [comment]
Also in android device it's showing different behavior.

for this textblock after we have escaped the strings.
`"type": "AdaptiveCard",
  "version": "1.2",
  "body": 
  [{
    type: 'TextBlock',
    color: 'default',
    text: 'test \\/ | \\\\ | \\/\\/ | \\\\ | \\" | \\" | \\" | '
  }]`

desktop shows this card.
![image](https://user-images.githubusercontent.com/23058976/112267639-c94cb880-8c9b-11eb-8038-c0f1b08f2e2c.png)

While Android MS Teams app shows this for the same card.
![image](https://user-images.githubusercontent.com/23058976/112267803-01ec9200-8c9c-11eb-977e-43bc8342eec2.png)

**Comment by Nikitha-MSFT** [comment]
I could see teams desktop gives the same as adaptive card designer, please check below screen shots
![image](https://user-images.githubusercontent.com/61688740/112622055-81bb5d80-8e50-11eb-87d2-79e62850c0f1.png)
![image](https://user-images.githubusercontent.com/61688740/112622090-8a139880-8e50-11eb-8c2e-001378047a3d.png)

for mobile we have raised a bug we don't have ETA to share when it will be fixed.
