### ISSUE TITLE
[iOS][Resource Resolver] Add Placeholder Image Support For Resource Resolver

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#4682]
**What platform is your feature request related to?**

- [ ] iOS
- [ ] Dev Spec

We don't currently support placeholder images while resource resolver is resolving images. Once we get the image through the resource resolver, we can not update the placeholder image with the resolved images. This is by design. However, being able to configure a placeholder image is a real use case. 

If the placeholder image is in the cache, we can draw the card quickly, and when the image is ready for replacement. We don't have to redraw the entire card, instead, it becomes a possibility that Adaptive Card re-draws only the image portion. Please note that the performance benefit will be lost if we do not know the size of the real image, therefore knowing the size of the real image at the time of acquiring a placeholder image is a requirement for this feature.

This feature will be implemented for iOS first since iOS re-draws the entire card in such events, and there are no such requests from the customers of other platforms. Dev Spec task is for review purposes, and for the future consistency consideration. Once the spec is drawn and agreed, we can refer back to the spec, once there are requests from customers for the other platforms.

**Related Issues**
 #4667, #4650, #4585

**Comment by jwoo-msft** [comment]
Hi @akaashdev,
I added you for feedback and visibility.

**Comment by akaashdev** [comment]
Thanks for this @jwoo-msft 👍
