### ISSUE TITLE
Adding custom color and custom text in adaptive cards.

### ISSUE THREAD

**Issue by Shivang007-del** [microsoft/AdaptiveCards#4684]
Is there any ways to add custom color and custom text in adaptive cards.

**Comment by matthidinger** [comment]
Thanks for the feedback! Currently this is not possible but is under consideration providing we can enforce accessibility contrast requirements and it is broadly desirable by our primary partner platforms (MS Teams, Outlook, WebEx Teams, etc.)

The feature is on our public feature portal where can you vote on how important this is to you and include any additional comments there:

https://portal.productboard.com/adaptivecards/1-adaptive-cards-features/c/29-custom-colors-for-text
