### ISSUE TITLE
[Azure Bot - Adaptive Card][Accessibility - Focus not going to read only text in the adaptive card

### ISSUE THREAD

**Issue by ridwived-microsoft** [microsoft/AdaptiveCards#4685]
We are from Dynamics 365 Knowledge Management Team.
We are using adaptive cards to show smart knowledge suggestions.

The issue observed on the adaptive card is for a section in the card that is just read only.
The section can be toggled via an info icon, once the section is enabled the narrator doesn't read the content of the section
![image](https://user-images.githubusercontent.com/60729090/91532529-1518c880-e92c-11ea-9a0d-bb1bbc6e0e49.png)

Expected behavior is that narrator should be reading the read only section on the card as well

**Comment by ridwived-microsoft** [comment]
Any updates on this?

**Comment by shalinijoshi19** [comment]
@ridwived-microsoft same question here as well for you - could you help me understand what platform + SDK of AdaptiveCards you are working with again? And also if you could share the sample json for us to repro this on wtih our tooling like https://adaptivecards.io/designer etc. tx

**Comment by ridwived-microsoft** [comment]
Platform
What platform is your issue or question related to? (Delete other platforms).

JavaScript
Author or host
Host, D365, Customer Service Workspace app

If you're an author, who are you sending cards to?
NA

Version of SDK
1.3

Template for ref.
{
	"type": "AdaptiveCard",
	"version": "1.2",
	"body": [
		{
			"type": "Container",
			"items": [
				{
					"type": "ColumnSet",
					"columns": [
						{
							"type": "Column",
							"width": "stretch",
							"items": [
								{
									"type": "TextBlock",
									"text": "[${Title}](#)",
									"size": "Medium",
									"color": "Accent",
									"weight": "Bolder",
									"wrap": true,
									"maxLines": 2,
									"$when": "${$root.Title != \"\"}"
								}
							],
							"selectAction": {
								"type": "Action.Submit",
								"title": "Open knowledge article, ${Title}",
								"data": {
									"customActionName": "Microsoft.KnowledgeSuggestion.ExecuteOperation",
									"customActionParams": {
										"SuggestionRequestId":"${SuggestionRequestId}",
										"ActionName": "OpenArticle",
										"KnowledgeArticleId": "${SuggestedArticleId}",
										"SuggestionForEntityId": "${SuggestionForEntityId}",
										"SuggestionForEntityLogicalName":"${SuggestionForEntityLogicalName}",
										"Title": "${Title}"
									}
								}
							}
						},
						{
							"type": "Column",
							"id": "PopupActionColumn",
							"width": "auto",
							"verticalContentAlignment": "Top",
							"items": [
								{
									"type": "PopupAction",
									"image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAySURBVHgB7ZIhCgAACAPVn+z/j1QxmoSZxIOVhWNh6okQmJC8YEsAoNKZ9PQC/SNdEAR4xwppIVYGGAAAAABJRU5ErkJggg==",
									"width": "24px",
									"height": "8px",
									"items": [
										{
											"$when": "${EnableCopyLink}",
											"actionset": {
												"type": "ActionSet",
												"actions": [
													{
														"title": "Copy URL",
														"type": "Action.Submit",
														"data": {
															"customActionName": "Microsoft.KnowledgeSuggestion.ExecuteOperation",
															"customActionParams": {
																"SuggestionForEntityId":"${SuggestionForEntityId}",
																"SuggestionForEntityLogicalName":"${SuggestionForEntityLogicalName}",
																"SuggestionRequestId":"${SuggestionRequestId}",
																"ActionName": "CopyLink",
																"KnowledgeArticleId": "${SuggestedArticleId}",
																"ExternalKMPortalURL": "${ExternalKMPortalURL}",
																"ArticlePublicNumber": "${ArticlePublicNumber}"
															}
														}
													}
												]
											}
										},
										{
											"$when": "${EnableEmailArticle}",
											"actionset": {
												"type": "ActionSet",
												"actions": [
													{
														"title": "Email URL",
														"type": "Action.Submit",
														"data": {
															"customActionName": "Microsoft.KnowledgeSuggestion.ExecuteOperation",
															"customActionParams": {
																"SuggestionRequestId":"${SuggestionRequestId}",
																"ActionName": "EmailArticle",
																"SuggestionForEntityId": "${SuggestionForEntityId}",
																"SuggestionForEntityLogicalName":"${SuggestionForEntityLogicalName}",
																"KnowledgeArticleId": "${SuggestedArticleId}",
																"ExternalKMPortalURL": "${ExternalKMPortalURL}",
																"Title": "${Title}",
																"ArticlePublicNumber": "${ArticlePublicNumber}"
															}
														}
													}
												]
											}
										},
										{
											"$when": "${EnableEmailArticleContent}",
											"actionset": {
												"type": "ActionSet",
												"actions": [
													{
														"title": "Email",
														"type": "Action.Submit",
														"data": {
															"customActionName": "Microsoft.KnowledgeSuggestion.ExecuteOperation",
															"customActionParams": {
																"SuggestionForEntityId":"${SuggestionForEntityId}",
																"SuggestionForEntityLogicalName":"${SuggestionForEntityLogicalName}",
																"SuggestionRequestId":"${SuggestionRequestId}",
																"ActionName": "EmailArticleContent",
																"ContentToMail": "${ArticleContent}",
																"KnowledgeArticleId": "${SuggestedArticleId}",
																"Title": "${Title}"
															}
														}
													}
												]
											}
										}
									]
								}
							]
						}
					],
					"id": "Header"
				},
				{
					"type": "ColumnSet",
					"columns": [
						{
							"type": "Column",
							"width": "stretch",
							"items": [
								{
									"type": "TextBlock",
									"text": "${Description}",
									"size": "Medium",
									"wrap": true,
									"maxLines": 2,
									"color": "default",
									"$when": "${$root.Description != \"\"}"
								},
								{
									"type": "TextBlock",
									"text": "_No description found for this article._",
									"isSubtle": true,
									"$when": "${$root.Description == \"\"}"
								}
							]
						},
						{
							"type": "Column",
							"width": "auto",
							"items": [
								{
									"$when": "${EnableLinkArticle}",
									"type": "Image",
									"url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB8AAAAfCAYAAAAfrhY5AAAACXBIWXMAABCcAAAQnAEmzTo0AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAJTSURBVHgBxZdNbtpAFMffm3G7qFTJmy4qBWFCVl3lCHADblAqFVJVqsINGk5Q2EVppdATpCco9Ab0AvVIsGlXbEoTYeb1jbFLHQWYsXDyl0aejwe/+Xh+8wzwgEJw1GF78p4fTS4BFwWII42yq86fK3CUE7zamgwJoWbqxGBcTcBIaeHVXScgbA0P29NOAjagSnhRqvDce8lwgBRdgqOs4QR0ap7pClfbTx0emPEujJGgFrTCY3CQNTzZYmXAR6/DGtfPDFgD1pH0N2MjQe4fHrSm6Z/6QTP0Iy92tIEBq48HY0JRNoNLiQoc5O0yMGABNEyafTWozPhpyqt0HIEaYDz/OhqDgzwrMILPze6Pi9JZ0Al9OfcuCfR3RFkmoubKGtOJWQtdwTj3hvyj9dnyufMR8PhBDxyFecDGu3nFfdAMfrocqZ7bijfCrcBPonpe4Eb4fYIz8PsG/4M/BNhIBG/CAJGubMCmH/YoIRfyOA6dHLF2gbnf+fLYJm8pwDcxll8dP96FuXd111YnE9rvymGx/JLczQ2hvXDTGWcCy77gJiSSiOp8ZX7m+3rEfd0inOsuxbFdnVcUrFKjwvTi7a9Me/7s9+5bLY+q7bABJP/3D7xZXGeNfkJYCBzQO2W/qW0zkfRoUAw8Fek+e2rGdwgwQMCXpl4oXMvHvdsZrUnBOA/MBferJ9OdgUYTBTY5uTN8nblsFL+xdt8D1nCtoW5rKwR8AIugZA1Xn0ojW9vqyWRGFFfx6N00uwt/FugMzyOho6/65nbnGlkUnJJS3jb+F5d+U9uyEhvyAAAAAElFTkSuQmCC",
									"width": "20px",
									"height": "20px",
									"selectAction": {
										"type": "Action.Submit",
										"title": "Link to case",
										"data": {
											"customActionName": "Microsoft.KnowledgeSuggestion.ExecuteOperation",
											"customActionParams": {
												"SuggestionForEntityId":"${SuggestionForEntityId}",
												"SuggestionForEntityLogicalName":"${SuggestionForEntityLogicalName}",
												"SuggestionRequestId":"${SuggestionRequestId}",
												"ActionName": "LinkArticle",
												"KnowledgeArticleId": "${SuggestedArticleId}"
											}
										}
									},
									"horizontalAlignment": "Right"
								},
								{
									"$when": "${EnableUnlinkArticle}",
									"type": "Image",
									"url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB8AAAAfCAYAAAAfrhY5AAAACXBIWXMAABCcAAAQnAEmzTo0AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAMLSURBVHgBxVfNbtpAEJ5ZHHroofRSqRIpTpRTLyVvAE/Q5AlCpCZFlarAEyQ8AfRSRXAIfYKkTwB9gubUWwAFpEo9pZcoJPZOZ9aGArHBjvLzSWjXs7t8szPj3c8IMbBW7ObItfYJIAsIKURoA2HzrJ7+BncARp24+rG/BwQ180Bw4a9O+cMHnfpyBWJCRZlkF7v2iBgVbXcayy91wlkfO8HkdrGfg5iIRK602vB6VDs7fNMUZ1BbLdk5p+DUzHH1BsREJHKTY4ZW+N1zxjrmfNncrZByNs0cpd5BTEQi51hnPFKd9bzRP9hY5jwfWI5xQox/ISasRRNWdwZHQJTjbk+r5InYOo1MSVq71E25l1ZVqlaROoaYwIXESAWP2Mr3Dl/3TNUDZmWnRPBewi9579aX1yEmrFjEu/19LoADUwW+5+xAm557eY8LjEXMr5S8XhqobCYmltoyBncExifGfK+RPoV7AD4V8RT5YxOPyZ+CWGCt7p5XuWYLj00sUHwlFri9WEQs9rtcHvPJfSy5V6lw4kHJ2O8ZFiDyPUxVF62fxhIQagI3ixGvgThQnXq6pom2SVQJYvMhczwLc7z2Gm+a3DThgfH2059x/9fXV+Fnu9xYolN6zZULutYllUy0eofpthkr/rbDjlURGgk3kQsYwuHN1eTzEYYR4yUrFQZdO3lxYDy2M8jyKyIqphak2+yd84JCPIIF4LUYvHOhSpoTKAtJq2UXusaBCWIRjnOvY7ntEEV0zA6ovZHwDCQ3REwoxGMHit2ycunYX1gRFQNzIMSdeubWnJXd/hb/Zzh5kAO+YIRJYolEQsHe1EJNNkE0zJVRxoEP/TIqaI1M+tqpjcZZRlc5vLmpRZG/BBYISJNjBE+beRrdRq8GTNho6GxqDfnJH5sjfzxYc4n/F1dF3zg1nKwBvwh5rD297tzmajf9tc+DW3FwhzSfXHY2STzO8WQRPks02RT+ocBVrYe0NWv29b5BYNjNjhC+wExVeweOk2ffTwiXShAO4vUvuM0E/AhGCvQp8Q/7I70GozDeEQAAAABJRU5ErkJggg==",
									"width": "20px",
									"height": "20px",
									"selectAction": {
										"type": "Action.Submit",
										"title": "Unlink to case",
										"data": {
											"customActionName": "Microsoft.KnowledgeSuggestion.ExecuteOperation",
											"customActionParams": {
												"SuggestionForEntityId":"${SuggestionForEntityId}",
												"SuggestionForEntityLogicalName":"${SuggestionForEntityLogicalName}",
												"SuggestionRequestId":"${SuggestionRequestId}",
												"ActionName": "UnlinkArticle",
												"KnowledgeArticleId": "${SuggestedArticleId}"
											}
										},
										"horizontalAlignment": "Right"
									}
								}
							],
							"id": "ImageGroup"
						}
					],
					"id": "VisibleColumnSet",
					"spacing": "Small"
				},
				{
					"type": "ColumnSet",
					"columns": [
						{
							"type": "Column",
							"width": "stretch",
							"items": [
								{
									"type": "RichTextBlock",
									"$when": "${EnableUnlinkArticle}",
									"inlines": [
										{
											"type": "TextRun",
											"text": " Linked to case ",
											"size": "Small",
											"highlight": true,
											"color": "good"
										}
									],
									"verticalAlignment": "Center",
									"spacing": "None"
								}
							]
						}
					]
				}
			],
			"height": "stretch"
		},
		{
			"type": "Column",
			"width": "auto",
			"items": [
				{
					"$when": "${EnableUnlinkArticle}",
					"type": "Image",
					"url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB8AAAAfCAYAAAAfrhY5AAAACXBIWXMAABCcAAAQnAEmzTo0AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAMLSURBVHgBxVfNbtpAEJ5ZHHroofRSqRIpTpRTLyVvAE/Q5AlCpCZFlarAEyQ8AfRSRXAIfYKkTwB9gubUWwAFpEo9pZcoJPZOZ9aGArHBjvLzSWjXs7t8szPj3c8IMbBW7ObItfYJIAsIKURoA2HzrJ7+BncARp24+rG/BwQ180Bw4a9O+cMHnfpyBWJCRZlkF7v2iBgVbXcayy91wlkfO8HkdrGfg5iIRK602vB6VDs7fNMUZ1BbLdk5p+DUzHH1BsREJHKTY4ZW+N1zxjrmfNncrZByNs0cpd5BTEQi51hnPFKd9bzRP9hY5jwfWI5xQox/ISasRRNWdwZHQJTjbk+r5InYOo1MSVq71E25l1ZVqlaROoaYwIXESAWP2Mr3Dl/3TNUDZmWnRPBewi9579aX1yEmrFjEu/19LoADUwW+5+xAm557eY8LjEXMr5S8XhqobCYmltoyBncExifGfK+RPoV7AD4V8RT5YxOPyZ+CWGCt7p5XuWYLj00sUHwlFri9WEQs9rtcHvPJfSy5V6lw4kHJ2O8ZFiDyPUxVF62fxhIQagI3ixGvgThQnXq6pom2SVQJYvMhczwLc7z2Gm+a3DThgfH2059x/9fXV+Fnu9xYolN6zZULutYllUy0eofpthkr/rbDjlURGgk3kQsYwuHN1eTzEYYR4yUrFQZdO3lxYDy2M8jyKyIqphak2+yd84JCPIIF4LUYvHOhSpoTKAtJq2UXusaBCWIRjnOvY7ntEEV0zA6ovZHwDCQ3REwoxGMHit2ycunYX1gRFQNzIMSdeubWnJXd/hb/Zzh5kAO+YIRJYolEQsHe1EJNNkE0zJVRxoEP/TIqaI1M+tqpjcZZRlc5vLmpRZG/BBYISJNjBE+beRrdRq8GTNho6GxqDfnJH5sjfzxYc4n/F1dF3zg1nKwBvwh5rD297tzmajf9tc+DW3FwhzSfXHY2STzO8WQRPks02RT+ocBVrYe0NWv29b5BYNjNjhC+wExVeweOk2ffTwiXShAO4vUvuM0E/AhGCvQp8Q/7I70GozDeEQAAAABJRU5ErkJggg==",
					"width": "20px",
					"height": "20px",
					"selectAction": {
						"type": "Action.Submit",
						"title": "Unlink to case",
						"data": {
							"customActionName": "Microsoft.KnowledgeSuggestion.ExecuteOperation",
							"customActionParams": {
								"SuggestionForEntityId":"${SuggestionForEntityId}",
								"SuggestionForEntityLogicalName":"${SuggestionForEntityLogicalName}",
								"SuggestionRequestId":"${SuggestionRequestId}",
								"ActionName": "UnlinkArticle",
								"KnowledgeArticleId": "${SuggestedArticleId}"
							}
						}
					},
					"horizontalAlignment": "Right"
				},
				{
					"$when": "${!EnableUnlinkArticle}",
					"type": "Image",
					"url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB8AAAAfCAYAAAAfrhY5AAAACXBIWXMAABCcAAAQnAEmzTo0AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAJTSURBVHgBxZdNbtpAFMffm3G7qFTJmy4qBWFCVl3lCHADblAqFVJVqsINGk5Q2EVppdATpCco9Ab0AvVIsGlXbEoTYeb1jbFLHQWYsXDyl0aejwe/+Xh+8wzwgEJw1GF78p4fTS4BFwWII42yq86fK3CUE7zamgwJoWbqxGBcTcBIaeHVXScgbA0P29NOAjagSnhRqvDce8lwgBRdgqOs4QR0ap7pClfbTx0emPEujJGgFrTCY3CQNTzZYmXAR6/DGtfPDFgD1pH0N2MjQe4fHrSm6Z/6QTP0Iy92tIEBq48HY0JRNoNLiQoc5O0yMGABNEyafTWozPhpyqt0HIEaYDz/OhqDgzwrMILPze6Pi9JZ0Al9OfcuCfR3RFkmoubKGtOJWQtdwTj3hvyj9dnyufMR8PhBDxyFecDGu3nFfdAMfrocqZ7bijfCrcBPonpe4Eb4fYIz8PsG/4M/BNhIBG/CAJGubMCmH/YoIRfyOA6dHLF2gbnf+fLYJm8pwDcxll8dP96FuXd111YnE9rvymGx/JLczQ2hvXDTGWcCy77gJiSSiOp8ZX7m+3rEfd0inOsuxbFdnVcUrFKjwvTi7a9Me/7s9+5bLY+q7bABJP/3D7xZXGeNfkJYCBzQO2W/qW0zkfRoUAw8Fek+e2rGdwgwQMCXpl4oXMvHvdsZrUnBOA/MBferJ9OdgUYTBTY5uTN8nblsFL+xdt8D1nCtoW5rKwR8AIugZA1Xn0ojW9vqyWRGFFfx6N00uwt/FugMzyOho6/65nbnGlkUnJJS3jb+F5d+U9uyEhvyAAAAAElFTkSuQmCC",
					"width": "20px",
					"height": "20px",
					"selectAction": {
						"type": "Action.Submit",
						"title": "link to case",
						"data": {
							"customActionName": "Microsoft.KnowledgeSuggestion.ExecuteOperation",
							"customActionParams": {
								"SuggestionForEntityId":"${SuggestionForEntityId}",
								"SuggestionForEntityLogicalName":"${SuggestionForEntityLogicalName}",
								"SuggestionRequestId":"${SuggestionRequestId}",
								"ActionName": "LinkArticle",
								"KnowledgeArticleId": "${SuggestedArticleId}"
							}
						}
					},
					"horizontalAlignment": "Right"
				}
			],
			"id": "VisibleColumnSet",
			"spacing": "Small"
		},
		{
			"type": "ColumnSet",
			"columns": [
				{
					"type": "Column",
					"width": "auto",
					"verticalContentAlignment": "Bottom",
					"items": [
						{
							"type": "Image",
							"url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAOiSURBVHgBxVe/bxRHGH0zdySREIr5C1iitHHOaZIU0Z1TpcOKi0ThOJZUaYghXZr47CppYiOqVB6fz6SMXYbCOneIaoGGji0RIPmQjQT2eof3zYzNgX2+A2vFO+3t7Ozsvvlmvh9vFYZAHMcjQFZBlk9A6yq7Ih4j4XYXFglgU5TUqjHtlWHeqQYS5tkUm1d6iAaAE4Ay0OVFY0zab5TuS9qoT5H0AZtNR2rR4XkGOcaxnZ01rbaKPvlUQW+ddn1+crRcRe6ZfGftUuP8xX7vP9Ti+OKFOVh7xRtAQosZ0253MABcIe5INk5z/uZlxT9v58zS8m8DiUm6wMF8g+ydneFD83hLXL58HptdroBS03CrpRbM0tLPvWNKb5CKpb84Up2Pm9aNoRzlTdy+fQ8T30/e6j5+chNa/UDzvq6MfvZxcvfe/weI4ws/xVyAP/dJzY0Ex0Cn08HE5OTDV+SqRvKnJL+1T8y9iYB8gcRcFvv7u1p6GPk3tdGH28+xTeLveHxZGfvinyRJnnuvznaawRuTYfeUXm955IPGXb++TPNOzIeoYARkzmk9sUbVnXNcRTGw/M2G9q+SH1RcrzMb4T+Ita32GAoCyRR2szU6WpUGfkuL7YSfk11EsbAkXYeEsMY5zQ0/47vVW3nxsHv8GnJHLKiSOGSYcvlY4TMIURSRI0v3LsW5XPJnQu+iQDSbTf5/lIbLEY33BCF2lsbxjxEKhLf4VQ0X4tQ1s3KEApGmKZyYEFA4CLH3NI0aCsSpUzvArvXE2qaaLr4SZlF19bQgPHv2oWLoNoRJ2dKqDmHUZVjVWMRrKABiUJ5v1+DEgU0XWq1VHcLomhuhMC1FvAAwXeKP0GzJfygSZalIG2K1KIfggUdCNBePgeHoDBHBKCsK+wA6M9Lv6rHURxbpF6FmfiXFW4q41NPjQAx49GhzDFZqPbjJuGoW/13fJ3bkVAaVz0clzmqiGIRcirjImHclZQiN0do1+Pi9ZlrLf+3dPyj2GnWZXQwv9mZdEeca0RcwLJzYe6pEjzcDqeG2XOodc7i8bdTneJpy90U5lDCr9Qedkydf2M3NEy7hH+YHPhwZGbuY9nvqME/SAwKj75eEE39K0RPV2dAlYbdId7zDMpNwBTb8ct6PeB0xH1Q5yVoP4YasWD8pNeAThvk7L4k2rgZNduT4AB+eemvemJW+FW+YF/lJOIlkzzHvnAk1/HQPUcqYWUeuV1DeSo4i3MNLP4uBrC583CYAAAAASUVORK5CYII=",
							"horizontalAlignment": "Right",
							"selectAction": {
								"type": "Action.ToggleVisibility",
								"targetElements": [
									"KeyWordDefaultText"									
								],
								"title": "Read about why article ${Title} was suggested"
							},
							"size": "Small",
							"width": "11px",
							"height": "11px"
						}
					],
					"id": "InfoIcon",
					"backgroundImage": {
						"verticalAlignment": "Center"
					},
					"verticalContentAlignment": "Center"
				},
				{
					"type": "Column",
					"width": "auto",
					"items": [
						{
							"type": "TextBlock",
							"size": "Small",
							"color": "default",
							"text": "•",
							"spacing": "None",
							"horizontalAlignment": "Center"
						}
					],
					"horizontalAlignment": "Center",
					"verticalContentAlignment": "Center"
				},
				{
					"type": "Column",
					"width": "auto",
					"items": [
						{
							"type": "TextBlock",
							"size": "Small",
							"color": "default",
							"text": "${confidencescore}% confidence",
							"horizontalAlignment": "Center"
						}
					],
					"horizontalAlignment": "Center",
					"verticalContentAlignment": "Center"
				},
				{
					"type": "Column",
					"width": "auto",
					"items": [
						{
							"type": "TextBlock",
							"size": "Small",
							"color": "default",
							"text": "•",
							"spacing": "None",
							"horizontalAlignment": "Center"
						}
					],
					"horizontalAlignment": "Center",
					"verticalContentAlignment": "Center",
					"backgroundImage": {
						"horizontalAlignment": "Center"
					}
				},
				{
					"type": "Column",
					"width": "auto",
					"items": [
						{
							"type": "TextBlock",
							"size": "Small",
							"color": "default",
							"text": "Was this relevant?",
							"horizontalAlignment": "Center"
						}
					],
					"horizontalAlignment": "Center",
					"verticalContentAlignment": "Center"
				},
				{
					"width": "auto",
					"type": "Column",
					"items": [
						{
							"$when": "${$root.HelpfulVote == 1}",
							"type": "ActionSet",
							"actions": [
								{
									"title": "Yes",
									"speak": "Give positive feedback",
									"style": "positive",
									"type": "Action.Submit"
								}
							],
							"spacing": "None"
						},
						{
							"$when": "${$root.HelpfulVote != 1}",
							"type": "ActionSet",
							"actions": [
								{
									"title": "Yes",
									"speak": "Give positive feedback",
									"type": "Action.Submit",
									"data": {
										"customActionName": "Microsoft.KnowledgeSuggestion.ExecuteOperation",
										"customActionParams": {
											"SuggestionForEntityId":"${SuggestionForEntityId}",
											"SuggestionForEntityLogicalName":"${SuggestionForEntityLogicalName}",
											"SuggestionRequestId":"${SuggestionRequestId}",
											"ActionName": "SendFeedback",
											"KnowledgeArticleId": "${SuggestedArticleId}",
											"Feedback": "1"
										}
									}
								}
							],
							"spacing": "None"
						}
					],
					"id": "HelpfulFeedbackYes",
					"verticalContentAlignment": "Center",
					"horizontalAlignment": "Center",
					"bleed": true
				},
				{
					"width": "auto",
					"type": "Column",
					"items": [
						{
							"type": "ActionSet",
							"actions": [
								{
									"title": "No",
									"speak": "Give negative feedback",
									"type": "Action.Submit",
									"data": {
										"customActionName": "Microsoft.KnowledgeSuggestion.ExecuteOperation",
										"customActionParams": {
											"SuggestionForEntityId":"${SuggestionForEntityId}",
											"SuggestionForEntityLogicalName":"${SuggestionForEntityLogicalName}",
											"SuggestionRequestId":"${SuggestionRequestId}",
											"ActionName": "SendFeedback",
											"KnowledgeArticleId": "${SuggestedArticleId}",
											"Feedback": "2"
										}
									}
								}
							],
							"spacing": "None"
						}
					],
					"id": "HelpfulFeedbackNo",
					"verticalContentAlignment": "Bottom",
					"bleed": true
				}
			],
			"id": "ToolBar1",
			"separator": true
		},
		{
			"type": "ColumnSet",
			"columns": [
				{
					"type": "Column",
					"width": "stretch",
					"items": [
						{
							"type": "TextBlock",
							"text": "This knowledge article was surfaced with the help of these key phrases",
							"wrap": true,
							"isSubtle": true,
							"id": "KeyWordDescription",
							"size": "Small"
						},
						{
							"type": "TextBlock",
							"id": "KeyWords",
							"text": "${Tags}",
							"weight": "bolder",
							"color": "dark",
							"wrap": true,
							"size": "Small"
						},
						{
							"$when": "${$Tags == \"\"}",
							"type": "TextBlock",
							"id": "KeyWordsNull",
							"text": "No key phrases found.",
							"weight": "bolder",
							"isSubtle": true,
							"size": "Small"
						}
					]
				}
			],
			"id": "KeyWordDefaultText",
			"isVisible": false,
			"separator": false
		}
	],
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}

**Comment by RebeccaAnne** [comment]
Please reopen if this is still an issue for you.
