### ISSUE TITLE
[Android] Background image squished.

### ISSUE THREAD

**Issue by Gunashree-R-V** [microsoft/AdaptiveCards#4687]
# Platform

* Android

# Author or host

Microsoft Teams

# Version of SDK

1.2.10

# Details

Here is the JSON: 

When a background image has fillMode: `"repeat"`/`"repeatHorizontally"`/`"repeatVertically"`, the image is compressed.
And this happens irrespective of where the background image is placed.

Here is the Desktop, Android and iOS comparison:

| Desktop | Android | iOS |  
|-----------|:-----------:|-----------:|  
|![image](https://user-images.githubusercontent.com/28745768/91535127-4f846480-e930-11ea-9d33-97069ee4d9d9.png)| ![image](https://user-images.githubusercontent.com/28745768/91534981-15b35e00-e930-11ea-9f69-22225ba4a7f1.png) |![image](https://user-images.githubusercontent.com/28745768/91535167-5a3ef980-e930-11ea-81bb-8c449137fd01.png) |  

```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Container",
            "minHeight": "150px",
            "backgroundImage": "https://adaptivecards.io/content/AlkiBeach.jpg",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "What a beautiful background"
                }
            ]
        },
        {
            "type": "TextBlock",
            "text": "They can even repeat a bunch of different ways..."
        },
        {
            "type": "Container",
            "minHeight": "100px",
            "backgroundImage": {
                "url": "https://adaptivecards.io/content/uparrow.png",
                "fillMode": "Repeat"
            }
        },
        {
            "type": "Container",
            "backgroundImage": {
                "url": "https://adaptivecards.io/content/uparrow.png",
                "fillMode": "RepeatHorizontally",
                "verticalAlignment": "Center"
            }
        },
        {
            "type": "Container",
            "minHeight": "100px",
            "backgroundImage": {
                "url": "https://adaptivecards.io/content/uparrow.png",
                "fillMode": "RepeatVertically",
                "horizontalAlignment": "Center"
            }
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2"
}

```
cc: @VikrantSingh01, @anbah34, @shbhadra

**Comment by shalinijoshi19** [comment]
@golddove please update with your investigation comments here. Moving to 20.10 based on priorities around Accessibility for 9/30

**Comment by golddove** [comment]
Talked with @dclaux about this before - the same issue occurs with Image that has `size: auto`. Android shows a much smaller image than JS.

This needs a design discussion about how we want to treat images when there's no explicit width/stretch given.

Our spec just says that auto means no scaling (as long as it fits). This would mean every device would show a different sized image subject to the display's pizel density. But perhaps we want to instead scale them such that the same images take up the same physical size across devices..?

**Comment by shalinijoshi19** [comment]
@golddove currently working on this. Testing out/Validating fix.

**Comment by shalinijoshi19** [comment]
@golddove updates? Is this still on track to be checked in by EOW?

**Comment by golddove** [comment]
> @golddove updates? Is this still on track to be checked in by EOW?

Should be good. In PR.
