### ISSUE TITLE
Ability to Change Action.Submit URL

### ISSUE THREAD

**Issue by RaisinBread42** [microsoft/AdaptiveCards#4688]
**What platform is your feature request related to? (Delete other platforms).**

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

**Is your feature request related to a problem? Please describe.**
The default behavior is that the service/app that sends a card to a user and awaiting the user's response, must wait and handle the it.  

Working on this within Azure, with pay-as-you-go model, can incur unnecessary costs; The service/app could be waiting a long time until the user responds. Would be more efficient to avoid this and send the user's response elsewhere, like to an API, queueing service, etc.

**Describe the solution you'd like**
Ability to specify URL for Action.Submit. This will provide more flexibility to send the user's response with out leaving services waiting in idle.  **EDIT:** Also, but can wait for later, ability to specify headers, to account for sending authenticated requests using basic auth, subscription keys, etc.

**Describe alternatives you've considered**
Could not think of alternatives that will work.

**Comment by RaisinBread42** [comment]
@dclaux  @matthidinger  @shalinijoshi19

**Comment by RaisinBread42** [comment]
So found out what I want can be achieved by using outlook - https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-email.  Still, would like to use when sending cards to other apps like MS Teams for example.

**Comment by RebeccaAnne** [comment]
This type of Action.HTTP support is not on our roadmap.
