### ISSUE TITLE
Adaptive Cards Designer Cache issue

### ISSUE THREAD

**Issue by saikrishnasgit** [microsoft/AdaptiveCards#4689]
Hello Team, the https://adaptivecards.io/designer/ is very intuitive and I like the interface. But, I found there are cache issues with the designer. I worked on a template (Microsoft Teams - Light) and after three to four versions, the changes were not reflecting when copied the "Copy card JSON". It would be great, if it is fixed

**Comment by shalinijoshi19** [comment]
Thanks for the note here @saikrishnasgit ; For increased visibility and followup though may i request that you use our Bug templates to file bugs in the future? Do you happen to have precise repro steps at all for us? 
Also @dclaux for FYI & weighing. Thanks!
