### ISSUE TITLE
Automatic tooltip for selectAction title

### ISSUE THREAD

**Issue by productboard-ac** [microsoft/AdaptiveCards#4694]
For `selectAction` we currently drop the `title` and `iconUrl` properties. This work would make the `title` property serve as an automatic tooltip on platforms that support it.

![screenshot](https://user-images.githubusercontent.com/1334689/91479250-052eb500-e856-11ea-9ab1-79338faaa7af.png)

```json
{
   "type": "Container",
   "items": [
      { 
         "type": "TextBlock", 
         "text": "View user profile" 
      }
    ],
   "selectAction": {
      "type": "Action.OpenUrl",
      "url": "https://adaptivecards.io",
      "title": "Learn more about this user"
   }
}
```

Implementation issues for non-mobile platforms:

- [x] JavaScript #4699
- [x] UWP #4700
- [x] .NET #4701

**Comment by productboard-ac** [comment]
Link to feature: https://adaptivecards.productboard.com/feature-board/planning/features/5489521

**Comment by RebeccaAnne** [comment]
Implemented for all applicable platforms
