### ISSUE TITLE
Renderer allows containers to support custom types 

### ISSUE THREAD

**Issue by matthidinger** [Microsoft/AdaptiveCards#47]
Scenario: Toast Notifications have a progress bar in their payloads
```
 "body": [
                    {
                        "type": "TextBlock",
                        "text": "Serious Pie",
                        "textWeight": "bolder",
                        "textSize": "medium"
                    },
                    **{
                        "type": "ProgressBar",
                        "Value": "50"
                    }**
                ]
```

The Renderer should provide some kind of callback to the container to handle generating UI for any unknown types

**Comment by dclaux** [comment]
@matthidinger What is this about, and why is it needed?

**Comment by Assaya** [comment]
http://adaptivecards.io/

x

**Comment by dclaux** [comment]
@Assaya not sure what you mean to say here?

**Comment by matthidinger** [comment]
Agreed, this is redundant and covered in the implementation spec. This isn't a change from existing 1.0 behavior

**Comment by Assaya** [comment]
Fiverr
    
    
            
      {
          "@context": "http://schema.org",
          "@type": "EmailMessage",
          "action": {
            "@type": "ViewAction",
            "url": "https://www.fiverr.com/s2/044196ead2",
            "name": "Browse Services on Fiverr"
          },
          "description": "Browse Services on Fiverr"
      }
    

        
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    

                                        
    

    
        Globalcherry is tired of keeping Fiverr a secret.
    

    
        Fiverr is the world’s largest marketplace for services,where you can get everything you need at an unbeatable value.
    

    
        Sounds too good to be true? See for yourself!
    



                                        
                                            
                                                
                                                    
                                                        
                                                            Browse Services On Fiverr
                                                        
                                                    
                                                
                                                
                                                    
                                                        

		
			
			
			The Fiverr Team
		
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
                
                    
                        
                            
                                

                                    © Fiverr International Limited 2010-2016, Fiverr Inc. | 401 Broadway, Suite 1600 New York NY, 10013 USA.
                                    Your personal information will not be stored or used for any marketing purposes.
                                
                            
                         
                    
                
            
        
            

    

If you would like to unsubscribe and stop receiving these emails click here.

**Comment by Assaya** [comment]
Hi there,

Have a great day.


angela@thehelm

[cid:531f1391-907f-4431-93c9-f6444318d824]

**Comment by Assaya** [comment]
https://join.slack.com/t/pwc-ltd/shared_invite/enQtNzgwNTQ1MDE2MTUxLTBlNDNiMDA1YmRjNjA5MjhmMGE1ZmJkZDA0YWQxMjU0NzYzMmEwMjM0Y2Y1NWZlOWE2NzI1MzIwYzQ4ZDE1OGM


angela@thehelm

[cid:e17e6240-7bb3-46f3-af14-959488788c1a]
