### ISSUE TITLE
Make sure we're using {{Date}} features in all samples

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#4709]
We should do a pass on our samples to make sure we're using {{Date}} constructs wherever possible.

Shouldn't we have to update this textblocks to use {Date} formatting in the string? Seems like we're missing an opportunity here

_Originally posted by @almedina-ms in https://github.com/microsoft/AdaptiveCards/pull/4695#discussion_r480298954_

**Comment by almedina-ms** [comment]
assigning to @jwoo-msft  as he'll be working on accessibility fixes for iOS
