### ISSUE TITLE
[Sample Cards] Text in sample cards truncated

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#4712]
# Platform

* Android
* iOS

# Issue

Newly updated Sporting Event card and Flight Update card have slightly longer text. For example, instead of **"San Francisco"**, it is **"San Francisco Airport"** after the update. Mobile platforms with narrower width such as Android and iOS would truncate the updated text. This is not what we want, we want to show all the text, so the ask is to add "wrap": true to those cards. Another way to fix this issue is making the "wrap" : true the default value as  asked in #4483.

**Comment by shalinijoshi19** [comment]
@golddove can you take a stab at handling this? Thanks

**Comment by shalinijoshi19** [comment]
> @golddove can you take a stab at handling this? Thanks

Looks like @almedina-ms had been looking at it from his email so assigning to him instead
