### ISSUE TITLE
[.Net] Allow developer to specify serialization format when calling ToJson()

### ISSUE THREAD

**Issue by pschaeflein** [microsoft/AdaptiveCards#4716]
**What platform is your feature request related to? (Delete other platforms).**

* .NET 

**Is your feature request related to a problem? Please describe.**
The response to the ToJson() method of the AdaptiveCard class is an indented string. 
https://github.com/microsoft/AdaptiveCards/blob/4bb9b3ae301917fc0fb36886c13f6360e266c91f/source/dotnet/Library/AdaptiveCards/AdaptiveCard.cs#L258

**Describe the solution you'd like**
I would like to specify the formatting options when calling ToJson

**Comment by pschaeflein** [comment]
Hey @RebeccaAnne, will you please provide some context to all these tags (P4, Triage, Roadmap)?

Is this request rejected? Included in some version? Closing without comment is not very helpful.

Thank you.

**Comment by skincarejen19** [comment]
What is this? I'm sorry but I keep getting emails about this.

**Comment by RebeccaAnne** [comment]
@pschaeflein Apologies for not leaving a comment in the bug. This is a good suggestion, but not something that's on our roadmap at this time. We may reconsider it in the future, or if you would like to make a contribution please see our contribution guidelines [here](https://github.com/microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md).
