### ISSUE TITLE
Support for Container styles

### ISSUE THREAD

**Issue by dclaux** [microsoft/AdaptiveCards#472]
# Implementation status
- [x] TypeScript (https://github.com/Microsoft/AdaptiveCards/pull/475)
- [x] UWP
- [x] WPF (PR #718)
- [x] iOS
- [x] Android
- [x] Documentation

# The problem
Certain scenarios are better addressed if the card author is able to apply a background color in certain containers. At the same time, background colors require specific text colors to enforce appropriate contrast level/accessibility requirements.

This issue describes a model that allows for background colors and enforce appropriate text colors.

# The design
#### ContainerStyle enumeration
```TypeScript
type ContainerStyle = "default" | "emphasis";
```
#### New style property on all containers
"All containers" means:
- AdaptiveCard
- Container
- Column

| Property name | Type | Description |
|-----------------|---------|-------------|
| style | ContainerStyle | The style property governs the container's background color as well as the color of all TextBlock element within that container, unless a nested container is used and has its own style set. style is ignored on AdaptiveCard if the HostConfig option **allowCustomStyle** is set to **false** (see below). |

#### "padding" value in Spacing enumeration
``` TypeScript
type Spacing = "none" | "small" | "default" | "medium" | "large" | "extraLarge" | "padding";
```
The **padding** value defines the amount of padding applied wherever padding is nedded (card and containers)

### Removed
- The whole **container** element is removed, as it was only used to define what the "normal" and "emphasis" styles were.
- **fontColors** is removed, replaced with **containerStyles** (see below)
- **backgroundColor** is removed from the **actions.showCard** node (replaced by style, see below)
- **backgroundColor** is removed from the **adaptiveCard** node. The default background color for an AdaptiveCard is always that of the **default** container style.
- **padding** is removed from both adaptiveCard and actions.showCard. Anywhere padding is applied, its amount is determined by the **padding** value of the Spacing enumeration 

#### Introducing container styles
Container styles are a way to define a background color and the associated colors for each of the named font colors. Container styles make it possible for hosts to define background/foreground color combinations that always meet the accessibility/contrast requirements, without the card author needing to worry about it.

A container style is defined as follows:
```TypeScript
interface ContainerStyleDefinition {
    backgroundColor?: string,
    fontColors: {
        dark: { normal: string, subtle: string },
        light: { normal: string, subtle: string },
        accent: { normal: string, subtle: string },
        good: { normal: string, subtle: string },
        warning: { normal: string, subtle: string },
        attention: { normal: string, subtle: string }
    },
}
```

When backgroundColor is omitted, it is assumed to be "no color", e.g. "transparent."

New **containerStyles** property at the root level:
```TypeScript
interface HostConfig {
    ...
    containerStyles: {
        default: ColorPaletteDefinition,
        emphasis: ColorPaletteDefinition
    }
    ...
}
```

New **style** property on the actions.showCard node. This property is optional; if not specified, it defaults to **emphasis**:
```TypeScript
interface HostConfig {
    ...,
    actions: {
        ...,
        showCard: {
            ...,
            style: ContainerStyle,
            ...
        }
        ...
    }
    ...
}
```

#### New property on the **adaptiveCard** node:

| Property name | Type | Description |
|-----------------|---------|-------------|
| allowCustomStyle | boolean | When set to **true**, the **style** property on an AdaptiveCard object is honored at render time. When set to **false**, the **style** property is ignored and the hostConfig-defined default color palette is applied instead. The **style** property of containers inside a card is always honored regardless of the value of allowCustomStyle. |

## Sample HostConfig
```
{
    supportsInteractivity: true,
    spacing: {
        small: 3,
        default: 8,
        medium: 20,
        large: 30,
        extraLarge: 40,
        padding: 20
    },
    separator: {
        lineThickness: 1,
        lineColor: "#EEEEEE"
    },
    fontFamily: "Segoe UI",
    fontSizes: {
        small: 8,
        normal: 10,
        medium: 12,
        large: 14,
        extraLarge: 16
    },
    fontWeights: {
        lighter: 200,
        normal: 400,
        bolder: 600
    },
    containerStyles: {
        default: {
            fontColors: {
                default: { normal: "#0000FF", subtle: "#222222" },
                accent: { normal: "#0000FF", subtle: "#0000DD" },
                attention: { normal: "#FF6600", subtle: "#DD4400" },
                good: { normal: "#00FF00", subtle: "#00DD00" },
                warning: { normal: "#FF0000", subtle: "#DD0000" }
            }
        },
        emphasis: {
            backgroundColor: "#EEEEEE",
            fontColors: {
                default: { normal: "#0000FF", subtle: "#222222" },
                accent: { normal: "#0000FF", subtle: "#0000DD" },
                attention: { normal: "#FF6600", subtle: "#DD4400" },
                good: { normal: "#00FF00", subtle: "#00DD00" },
                warning: { normal: "#FF0000", subtle: "#DD0000" }
            }
        }
    },
    imageSizes: {
        small: 40,
        medium: 80,
        large: 160
    },
    actions: {
        maxActions: 5,
        spacing: "default",
        buttonSpacing: 20,
        showCard: {
            actionMode: "inline",
            inlineTopMargin: 16
        },
        actionsOrientation: "horizontal",
        actionAlignment: "left"
    },
    adaptiveCard: {
        allowCustomStyle: false
    },
    image: {
        size: "medium"
    },
    imageSet: {
        imageSize: "medium",
        maxImageHeight: 100
    },
    factSet: {
        title: {
            color: "default",
            size: "normal",
            isSubtle: false,
            weight: "bolder",
            wrap: true,
            maxWidth: 150
        },
        value: {
            color: "default",
            size: "normal",
            isSubtle: false,
            weight: "normal",
            wrap: true
        },
        spacing: 10
    }
}
```

## Sample card
```
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"body": [
	    {
	        "type": "TextBlock",
	        "text": "TextBlock in the card's body."
	    },
		{
			"type": "Container",
			"style": "emphasis",
			"items": [
			    {
			        "type": "TextBlock",
			        "text": "TextBlock within a Container that has its **style** property set to **emphasis**. Note that the container has padding.",
			        "wrap": true
			    }
			]
		}
	]
}
```

As rendered:
![image](https://user-images.githubusercontent.com/1334689/30457800-b610575c-995d-11e7-8521-5d8e8c25f498.png)

**Comment by mdtauk** [comment]
With Microsoft platforms, how does the user's chosen Accent Colour play into things?
Perhaps there needs to be "Accent" as a colour option on elements, which can be set for UWP platforms, or chosen by the Host rendering platform?

**Comment by dclaux** [comment]
Thanks @mdtauk and yes, there will likely be an "accent" color palette or something similar. There is already an accent color for text.

**Comment by mdtauk** [comment]
@dclaux  I see it there for Fonts, but for background colours and borders, as well as glyphs, badges, and other elements that can be presented.

I wonder if the Windows Platform teams will enable elements like Windows Timeline, Live Tiles, Notification Toasts will become flexible enough to support custom Background/Text Colours - or will those always override?

**Comment by matthidinger** [comment]
Closing as complete
