### ISSUE TITLE
Adaptive Card Designer - toolbar buttons missing html type attribute

### ISSUE THREAD

**Issue by bzbetty** [microsoft/AdaptiveCards#4721]
Similar to https://github.com/microsoft/BotFramework-WebChat/issues/594, the buttons in the adaptive card designer are missing the type="button" attribute which means if it's embedded in a html form tag it tries to submit the form anytime buttons like the "new card" button is pushed.

**Comment by shalinijoshi19** [comment]
@dclaux are you able to take a look at this please? Thanks

**Comment by shalinijoshi19** [comment]
@golddove is this for Cisco by anychance? If so can you take it with the Cisco label? thanks
