### ISSUE TITLE
[Javascript][Adaptive Card] ["altText" attribute for Image element is not working]

### ISSUE THREAD

**Issue by mokandre** [microsoft/AdaptiveCards#4724]
# Platform

* JavaScript

# Author or host
 Cisco Webex Teams

# Version of SDK
Adaptive Cards: 1.2

# Details

`altText` attribute for image element is not working.

**JSON**
`{
   "type":"AdaptiveCard",
   "body":[
      {
         "type":"ColumnSet",
         "columns":[
            {
               "type":"Column",
               "items":[
                  {
                     "type":"Image",
                     "url":"https://developer.webex.com/images/webex-teams-logo.png",
                     "size":"Medium",
                     "altText":"altText sample",
                     "height":"50px"
                  }
               ],
               "width":"auto"
            },
            {
               "type":"Column",
               "items":[
                  {
                     "type":"TextBlock",
                     "text":"Cisco Webex Teams",
                     "weight":"Lighter",
                     "color":"Accent"
                  }
               ],
               "width":"stretch"
            }
         ]
      }
   ],
   "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
   "version":"1.2"
}`

**Output:**

<img width="518" alt="ac1 2" src="https://user-images.githubusercontent.com/55378170/91996659-e00adc80-ed56-11ea-89ab-15c4a06ecf1a.png">

**Designer:**           

**Before Image renders**

<img width="1034" alt="altText" src="https://user-images.githubusercontent.com/55378170/91997843-23b21600-ed58-11ea-9058-fe05cbf28bc5.png">

**When Image fails to render**

<img width="1148" alt="incorrect-url" src="https://user-images.githubusercontent.com/55378170/91997477-c1f1ac00-ed57-11ea-9ee2-20b45cd8f3a9.png">

**Comment by shalinijoshi19** [comment]
@dclaux  are you aware of this one? Could you help take a stab? thanks

**Comment by shalinijoshi19** [comment]
@mokandre FWIW the card you have seems to be working fine in our designerup on https://adaptivecards.io/designer 
![image](https://user-images.githubusercontent.com/20822397/92040333-7cb78500-ed2b-11ea-8989-36937aa864a4.png)

**Comment by mokandre** [comment]
@shalinijoshi19 `altText` should be shown when there is a delay in image rendering and when image render fails.

Please take a look for below

**Comment by shalinijoshi19** [comment]
@dclaux could you update this issue with the offline discussion on this please? Thanks.

**Comment by dclaux** [comment]
The reason we currently drop images when they can't be loaded is that it is probably the "least bad" option in order to avoid messing up the card layout.

Showing the altText doesn't seem like a practical solution, because text notoriously takes a lot of horizontal space, and in order to not completely degrade the card's layout it would have to be truncated, making a lot less useful.

Showing placeholders is easy enough when the screen size of the image is known in advance, but that isn't the case when an image is auto sized.

Per discussion recently, I believe we haven't agreed on a solution for this.
