### ISSUE TITLE
[iOS][Action Inputs] Missing Input values for input fields inside ShowCard

### ISSUE THREAD

**Issue by akaashdev** [microsoft/AdaptiveCards#4730]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Version of SDK

v1.2.11

# Details

The values of input text fields inside ShowCard seems to be missed when retrieving all inputs.

The inputs retrieved from iOS SDK
```
"inputs": {
    "date": "range",
    "workdayleave": "Yes",
    "notification": "webex,email,sms",
    "ooo_start_time": "",
    "ooo_start_date": "2020-08-31",
    "ooo": "no",
    "leave_type": "sick leave",
    "reason": "something here",
    "ooo_end_date": "2021-08-31",
    "intent_name": "leave",
    "ooo_end_time": "",
    "confirmed": "true"
  }
```

Inputs retrieved from other platforms for same card payload.
```
"inputs": {
    "confirmed": "true",
    "intent_name": "leave",
    "date": "range",
    "ooo_start_time": "10:17 AM",
    "reason": "",
    "notification": "webex,email,sms",
    "leave_type": "sick leave",
    "workdayleave": "Yes",
    "ooo_end_time": "10:17 AM",
    "ooo_start_date": "2020-08-31",
    "ooo_end_date": "2020-08-31",
    "ooo": "no",
    "ooo_message": "from android"
  }
```

The key 'ooo_message' seems to be missing.

[card-payload.txt](https://github.com/microsoft/AdaptiveCards/files/5166582/card-payload.txt)

**Comment by shalinijoshi19** [comment]
@jwoo-msft thoughts here?

**Comment by jwoo-msft** [comment]
Hello, @akaashdev 

I tried 1.2.11 & 1.2.12, and I could not reproduce the issue. Please see the attached.
<img width="327" alt="Screen Shot 2020-09-08 at 4 40 44 PM" src="https://user-images.githubusercontent.com/4112696/92537903-28604980-f1f2-11ea-9bbf-82b667596a86.png">
This is full output from Xcode
```
ADCIOSVisualizer[74922:12921809] user response fetched: {
  "reason" : "",
  "workdayleave" : "Yes",
  "notification" : "webex,email,sms",
  "ooo_end_time" : "",
  "leave_type" : "sick leave",
  "ooo_start_time" : "",
  "ooo_end_date" : "",
  "date" : "range",
  "ooo_message" : "From iOS",
  "ooo" : "no",
  "ooo_start_date" : ""
} with {"confirmed":"true","intent_name":"leave"}
```

If you try this card with 2.0 renderer the one with the new Input feature or the main branch, you will notice that the input from the showcard is not captured. That's as designed. Showcard's AdaptiveCard has to have a submit button to collect its input and its parent card. when the parent's submit action is triggered, it won't collect its sub or child card inputs.  this is the case for this card.

**Comment by jwoo-msft** [comment]
Hello @akaashdev,

As we have discussed, this is a newly updated behavior with the addition of the input feature update on main branch. I realized that this change can be a big surprise, and to improve the user experiences, I created a new issue https://github.com/microsoft/AdaptiveCards/issues/4753.

**Comment by akaashdev** [comment]
Thanks for this @jwoo-msft !
