### ISSUE TITLE
[.NET HTML][AdaptiveImage] [Silent Error/Data loss: JsonSerializationException swallowed for invalid AdaptiveImage.Url]

### ISSUE THREAD

**Issue by p-nagpal** [microsoft/AdaptiveCards#4738]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* .NET 

# Author or host
DirectLine Channel in Bot Framework. Sending cards from Bot to WebChat Client

# Version of SDK
Failure reproduces with latest C# SDK

# Details

Originally reported on https://github.com/microsoft/BotFramework-Services/issues/214

The customer is sending an Adaptive Card with an image stored in the data URI. The original customer card is here: https://github.com/microsoft/BotFramework-Services/files/4663983/card.lg.zip

The image is directly embedded in the body-->item (type image) --> url.

    "body": [
        {
        "type": "Container",
        "items": [
            {
            "type": "Image",
            "url": "data:image/png;base64,iVBORw0KG...", <-- problematic element
            "size": "Stretch"
            }
        ]
        }

This seems to be allowed in the visualizer https://adaptivecards.io/visualizer/index.html?hostApp=Bot%20Framework%20WebChat but in C#, there is a failure reading this file as an Adaptive card, specifically converting the png string to a Uri. This failure is swallowed and the result is an invalid Adaptive Card without the image (data loss as perceived by the customer).

The failure occurs at AdaptiveTypedElementConverter --> 
ReadJson --> serializer.Populate(jObject.CreateReader(), result);
(AdaptiveCards\source\dotnet\Library\AdaptiveCards\AdaptiveTypedElementConverter.cs:line 100)

                var result = (AdaptiveTypedElement)Activator.CreateInstance(type);
                try
                {
                    serializer.Populate(jObject.CreateReader(), result);
                    result.InternalID = internalID;
                }
                **catch (JsonSerializationException) { }**

Swallowed Exception:
"Error converting value \"data:image/png;base64,iVBORw0KG..."

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at AdaptiveCards.AdaptiveTypedElementConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in AdaptiveCards\source\dotnet\Library\AdaptiveCards\AdaptiveTypedElementConverter.cs:line 100

Could you help fix this behavior or could you advise us if there is a different way to validate the card and prevent further processing? Thank you.

**Comment by aakashjain181** [comment]
` body": [
              {
                "type": "Container",
                "items": [
                  {
                    "type": "ColumnSet",
                    "columns": [
                      {
                        "type": "Column",
                        "width": "auto",
                        "items": [
                          {
                            "type": "Image",
                            **"url": "data:image/png;base64,iVBORw0K**


Even I am facing the same issue for image rendering in Xamarin.Android.
It gives me an exception stating "expected entity "url" is empty".

**Comment by RebeccaAnne** [comment]
We should confirm whether this repros for .NET generally (rather than just HTML)

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.
