### ISSUE TITLE
[NodeJS][Column] No way to set backgroundimage on a column

### ISSUE THREAD

**Issue by scottlovegrove** [microsoft/AdaptiveCards#4741]
# Platform

* JavaScript

# Author or host

Author, sending cards to our own custom renderer.

# Version of SDK

All versions, but seeing this with 1.2.6 and 2.3.0

# Details

The Schema and Designer at adaptivecards.io both say you can add a background image to a `Column`, however in the npm package, there is no way to actually achieve this. There is a `backgroundImage` property, but this is readonly and having looked in the source, there doesn't appear to be anywhere that's actually setting the backing field within Column or Container.

**Comment by scottlovegrove** [comment]
Quick code sample:

```typescript
            const column = new Column('stretch')
            column.minPixelHeight = 150
            const backgroundImage = new BackgroundImage()
            backgroundImage.url = quickSearch.image
            backgroundImage.verticalAlignment = VerticalAlignment.Center
            backgroundImage.horizontalAlignment = HorizontalAlignment.Center
            column.backgroundImage = backgroundImage
```
At the point I try and set `column.backgroundImage = backgroundImage`, Typescript then errors because `column.backgroundImage` is read-only.

**Comment by dclaux** [comment]
It is already possible to set a background image on a column. The code patterns is this:
```typescript
const column = new Column('stretch');
column.minPixelHeight = 150;
column.backgroundImage.url = quickSearch.image;
column.backgroundImage.verticalAlignment = VerticalAlignment.Center;
column.backgroundImage.horizontalAlignment = HorizontalAlignment.Center;
```

To remove the background image, set its `url` to `undefined`.

**Comment by scottlovegrove** [comment]
Thanks @dclaux, I can confirm this does indeed sort my issue out 👍🏻
