### ISSUE TITLE
[iOS][Rendering] Crash when "bleed" property used on outermost container

### ISSUE THREAD

**Issue by akaashdev** [microsoft/AdaptiveCards#4745]
# Platform

* iOS

# Version of SDK

v1.2.11

# Details

When "bleed" property is used on the outermost container, the SDK crashes on [this line](https://github.com/microsoft/AdaptiveCards/blob/f9d6436cd489015a310fad5c62058391d0cadc4b/source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentStackView.mm#L399).

[bleed-card-payload.txt](https://github.com/microsoft/AdaptiveCards/files/5188285/bleed-card-payload.txt)
[bleed-crash-stacktrace.txt](https://github.com/microsoft/AdaptiveCards/files/5188286/bleed-crash-stacktrace.txt)
These are the card-payload and stack-trace.

**Comment by jwoo-msft** [comment]
Hello @akaashdev,

Thanks for reporting this issue. I can reproduce this issue on my end. 

Thanks
