### ISSUE TITLE
[iOS][Action Inputs] Get content of multi input card in order of appearance

### ISSUE THREAD

**Issue by JustinBlock** [microsoft/AdaptiveCards#4752]
**What platform is your feature request related to? (Delete other platforms).**
* iOS

**Is your feature request related to a problem? Please describe.**
I’ve got a chat system using adaptive cards that contains multiple inputs in one card. When that card is submitted I don’t have a way to easily get the users input in the order in which it was entered. This would allow me to show the user the input they entered on the screen after they submit the card.

**Describe the solution you'd like**
It would be good if ACOAdaptiveCard contained a property that had an adaptive cards input fields - dates, number, plain text etc. - in an array in the order it was presented to the user. Ideally the array would contain some struct containing the field title and field value.

**Describe alternatives you've considered**
I haven’t found a way to get this data. The best I can do is look at the ACOAdaptiveCard.inputs() but this does not return the data in order of it’s appearance. I had a workaround where I could look at the input fields and cast them to a native UITextField and then get the value. This however was broken with 2020.07. 

**Additional context**
N/A

**Comment by jwoo-msft** [comment]
@JustinBlock 
Thanks for sharing your feedback. I will bring it to our team's attention to see if we can add this feature for the next input iteration.

Thanks.

**Comment by shalinijoshi19** [comment]
@jwoo-msft fyi. For now have added this to our backlog - Please work with @RebeccaAnne and @matthidinger to get this included in our productboard backlog for appropriate prioritization and planning. thanks
