### ISSUE TITLE
[Teams][UI] ActionSet wrapping/scrolling in Teams iOS/Android hides buttons

### ISSUE THREAD

**Issue by ballwood** [microsoft/AdaptiveCards#4758]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android
* iOS

# Author or host

**Author**

If you're an author, who are you sending cards to?

**MS Teams**

# Version of SDK

**1.2**

# Details

We have an adaptive card with a set of 2 ActionSets (due to the 6 button limit), on the MS Teams desktop client they render (ok-ish)
![image](https://user-images.githubusercontent.com/4639337/92619162-11d0f580-f2b9-11ea-8f17-f20138fa1ad9.png)

However on mobile with this specific set of buttons they render without a scroll bar so you can't see the last buttons.
![image](https://user-images.githubusercontent.com/4639337/92619462-6eccab80-f2b9-11ea-95bf-a4e1950b191a.png)

Firstly, is there any reason why teams has this arbitrary limit on buttons in an ActionSet when I can send two action sets with 6 buttons each and it works fine?
Secondly, could the wrapping/scrolling issue be fixed...As a suggestion would it be better if the buttons are stack vertically on the screen like you would do on a responsive website.

Thanks :)

**Comment by jwoo-msft** [comment]
@ballwood 
Thanks for reporting this issue.
AdaptiveCards and MS Teams are separate teams. 
AdaptiveCards provides host config options for button orientation and the max number of actions allowed in an action set. The options are configurable by a host app, in this case, MS Teams. As for the scrolling, the scroll bar will appear if you touch close to buttons or the gap in the buttons. Please note that scrolling action is hard to mimic in the simulator using a mouse. 

I'm closing this issue for now, and feel free to open it again.
Thanks

**Comment by ballwood** [comment]
@jwoo-msft who would I contact to report this issue?
