### ISSUE TITLE
[All]Default Wrap value for Actions' Vertical Orientation 

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#4759]
**What platform is your feature request related to? (Delete other platforms).**

- [ ] .NET HTML
- [ ] .NET WPF
- [ ] Android
- [x] iOS
- [ ] JavaScript
- [ ] UWP

**Is your feature request related to a problem? Please describe.**
#4739, #4107
Buttons Increase its width beyond their superview's width.

**Describe the solution you'd like**
Make texts in buttons to wrap by default in the vertical alignment.

**Comment by shalinijoshi19** [comment]
@jwoo-msft what is going on with this one ? Can you add a bit more context here pls? Did we have the design discussion on tihs? Could you add a pointer to the speclet/draft here pls? Thanks

**Comment by paulcam206** [comment]
@jwoo-msft - feel free to reactivate with more details here
