### ISSUE TITLE
Authenticated image downloads (Graph, SharePoint, etc)

### ISSUE THREAD

**Issue by productboard-ac** [microsoft/AdaptiveCards#4763]

**Comment by productboard-ac** [comment]
Link to feature: https://adaptivecards.productboard.com/feature-board/planning/features/5454678

**Comment by JeanRoca** [comment]
Issue was first brought up in 2018 and unfortunately, we won't be able to get to it soon. If this is a strong ask for you or your team, please feel free to bubble it up again :)
