### ISSUE TITLE
Can we have some updates please, community call would be good

### ISSUE THREAD

**Issue by MikeAinOz** [microsoft/AdaptiveCards#4770]
Hi There, I know you people are really busy, but can we have some blog updates, particularly the community call. It's on at 2am here in Brisbane and, although I love Adaptive Cards, I'm not going to stay up or get up for it. Regards Mike

---
* URL: https://adaptivecards.io/blog/

**Comment by golddove** [comment]
@matthidinger, looks like we might be missing blog posts for recent community calls.

@MikeAinOz, thanks for pointing it out! You can always find the recorded calls on our Microsoft 365 channel: https://www.youtube.com/c/Microsoft365Developer/search?query=adaptive+cards+community+call
