### ISSUE TITLE
Can we have a clear page that states what version of AdaptiveCard schema is currently supported for each platform (Outlook / Teams etc)?

### ISSUE THREAD

**Issue by chaim770** [microsoft/AdaptiveCards#4771]
**What platform is your feature request related to?**
All

**Is your feature request related to a problem?**
Currently, there is no way for me to know whether a certain Outlook (or Teams, for that matter) build/version is supporting the v1.3 (for example) schema.

**Describe the solution you'd like**
A simple table with build versions and supported schema version for each platform.

For example:
Outlook Desktop >= 2002 - v1.1
Outlook Desktop >= 1891 - v1.0
Outlook Web - v1.2
Teams - v1.2
etc

**Describe alternatives you've considered**
Trying to figure it out manually is not too productive and time consuming.

**Comment by shalinijoshi19** [comment]
@chaim770 does this page help - https://docs.microsoft.com/en-us/adaptive-cards/resources/partners ? 
@matthidinger FYI.

**Comment by chaim770** [comment]
> @chaim770 does this page help - https://docs.microsoft.com/en-us/adaptive-cards/resources/partners ?
> @matthidinger FYI.

Well, partly.

It does not specify exact versions of Outlook (for example), nor when can we expect future versions (say v1.3) to be available for that partner/host.

**Comment by shalinijoshi19** [comment]
@chaim770 when you say exact versions of outlook are you referring to mobile, desktop etc? @matthidinger / @dclaux  FYI.

**Comment by chaim770** [comment]
> @chaim770 when you say exact versions of outlook are you referring to mobile, desktop etc? @matthidinger / @dclaux FYI.

Yes.

But as far as I remember, some Outlook versions (in mobile & desktop) are not even capable of showing AdaptiveCards, while some versions are only capable of showing specific version (such as v1.0).

Ultimately, in my own case, I just need an answer to this question:
When (or at what version) can I expect to render AdaptiveCards **v1.3** in Outlook (web, mobile & desktop)?

**Comment by shalinijoshi19** [comment]
@RebeccaAnne an interesting one to see if we can try to tackle as we are trying to work on our external-facing documentation.. MOved out to consider fr next sprint or maybe even the "slower" Dec sprint.

**Comment by RebeccaAnne** [comment]
This is tracked here: https://docs.microsoft.com/en-us/adaptive-cards/resources/partners 

We should review this list to make sure it is accurate and up to date.

@JeanRoca

**Comment by paulcam206** [comment]
The partners page mentioned above should be up-to-date and should be used as a reference here.
