### ISSUE TITLE
[Ms Teams] [Ms Teams Conversation- Message Deletion Output is not consistent]

### ISSUE THREAD

**Issue by priyakewlani18** [microsoft/AdaptiveCards#4772]
# Platform

What platform is your issue or question related to? (Delete other platforms).

MsTeams

# Author or host
Author
If you're an author, who are you sending cards to?
MsTeams

# Version of SDK
NA
What version are you using? Ex: NuGet 1.0.2, or latest main, etc...

# Details

In Ms Teams- from ongoing conversation in the channel, if user delete any message then it either shows "This message has been deleted. Undo" and sometimes Ms Teams just delete it and don't show any message. 
It's not clear why there is inconsistency and what is the desired behaviour?

![image](https://user-images.githubusercontent.com/65468026/93021095-7e702b00-f5fe-11ea-8acb-c4787a081959.png)

**Comment by shalinijoshi19** [comment]
@Wajeed-msft / @siduppal could you help out with this? It doesnt seem related to AC on the outset?

**Comment by VaraPrasad-MSFT** [comment]
We are not able to repro this from our end. While deleting message it is showing the message "This message has been deleted. Undo" . How frequent does this happen? Please reach out to [Product Support Channel](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoftteams%2Fplatform%2Ffeedback%23product-support-channels&data=02%7C01%7Cv-gobegu%40microsoft.com%7C98bea019a05e4e6e38a308d85996610f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637357849703244801&sdata=G70QgZUCsp1Tqm1UVhSb0TXfKzX8aKvP1tuJ%2F4YZD7A%3D&reserved=0) if this happens again.

**Comment by shalinijoshi19** [comment]
@priyakewlani18 can you please take a look at the Teams dev response above and follow up using the recommended support channel with repro steps etc? Thanks again!
