### ISSUE TITLE
[https://adaptivecards.io/explorer/Container.html] Sample doesn't match the rendered card

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#4782]
For some reason the rendered card uses an accent color as background color while the sample states that it's the emphasis color, the json payload matches the contents of the Container.Style card but I couldn't find the other version in our samples

**Comment by shalinijoshi19** [comment]
@RebeccaAnne could you help take a look at this one while we are looking to flesh out our samples this milestone? Thanks!

**Comment by almedina-ms** [comment]
Sample matches the version 1.2 of the Container.Style.json card
