### ISSUE TITLE
[Adaptive card] Behaviour of card in mobile and O365

### ISSUE THREAD

**Issue by Vishnuvk33** [microsoft/AdaptiveCards#4785]
Hi, 

    We are using the same card json file  to view adaptive card in both mobile and O365.

    In O365, the adaptive card is wokring fine as expected.

    But in Android mobile outlook app(same card json), The bahaviour of the card is some what differ.
  
    Please refer the attached the card json for ref.

     Flow :  Click on Runnig Image in both desktop and mobileapp.
[cardissue.txt](https://github.com/microsoft/AdaptiveCards/files/5244158/cardissue.txt)

Thanks,
Vishnukumar M

**Comment by shalinijoshi19** [comment]
@golddove putting this on your plate for investigation for next milestone.

**Comment by Vishnuvk33** [comment]
Hi @golddove  
    
      Any update on this.

Thanks,
Vishnukumar M

**Comment by shalinijoshi19** [comment]
@Vishnuvk33 qq: could you elaborate on what you mean by O365 here -- are you comparing against the JS AC renderer or UWP for the baseline?

**Comment by RebeccaAnne** [comment]
@Vishnuvk33 Please let us know if you're still seeing an issue here and can give us a little more information about your setup and what differences you are seeing. Thanks!
