### ISSUE TITLE
[Android][Adaptive card rendering issue] [One of type of adaptive card is not rendering in Android.]

### ISSUE THREAD

**Issue by ranjanraviraj** [microsoft/AdaptiveCards#4789]
# Android

What platform is your issue or question related to?

* Android

# io.adaptivecards:adaptivecards-android:2.1.0

# In one of use-case an apdative card is supposed to render. Please find an attachment to the adaptive card response.
[organiser adaptive card.txt](https://github.com/microsoft/AdaptiveCards/files/5253591/organiser.adaptive.card.txt)

**This response is rendering** 
![image](https://user-images.githubusercontent.com/55788218/93735591-06f05c00-fbfb-11ea-958e-8b94d7cb7cfc.png) 

**instead of this in iOS and dextop client.** 
![image](https://user-images.githubusercontent.com/55788218/93735624-27201b00-fbfb-11ea-9efd-9ed7f8f4861c.png). 

A similar type of use-case with a slight difference in response is able to render cards properly in Android.  Please find the response and screenshot for the reference. 

[attendee adaptive card.txt](https://github.com/microsoft/AdaptiveCards/files/5253604/attendee.adaptive.card.txt)

![image](https://user-images.githubusercontent.com/55788218/93735779-c9400300-fbfb-11ea-87f7-78d6ff2d5eaa.png)

**Comment by shalinijoshi19** [comment]
@almedina-ms when you get a chance pls help take a look at this one! thanks.

**Comment by ranjanraviraj** [comment]
@shalinijoshi19  @almedina-ms  I was testing some of the features and it seems few more Adaptive cards are getting blank. If you want I can send adaptive card data. Just to let you know all these cards are working fine for version 1.2.9  last version I was using but not in 2.1.0 recently updated in our code base.

**Comment by almedina-ms** [comment]
Currently in main we are able to see the card being rendered properly, it's probable you have some type of extra information in your custom inputs. Or were you not even able to render the card you linked?

![image](https://user-images.githubusercontent.com/35784165/95779633-3dac1600-0c7f-11eb-8c80-58b47e830d7e.png)

**Comment by shalinijoshi19** [comment]
Closing this out as they've confirmed offline that this is resolved in the latest bits.
