### ISSUE TITLE
Support passing custom properties in JSON through to the parsed object model for host to use

### ISSUE THREAD

**Issue by anbare** [Microsoft/AdaptiveCards#479]
Sometimes hosts might need some additional properties on elements.

For example, Action Center allows you to provide images on their action buttons, which they then render using an AppBarButton style.

```json
  "actions": [

    {
      "type": "ToastAction.Background",
      "title": "Snooze",
      "imageUrl": "Snooze.png",
      "data": {
        "action": "snooze",
        "alarmId": "3"
      }
    },
```

![image](https://user-images.githubusercontent.com/13246069/28191858-b0fbce4c-67e7-11e7-9107-936d7e30a262.png)

Action Center would need to be able to retrieve that custom "imageUrl" property that was specified on the original JSON so that they can then choose to style their buttons differently (utilizing the custom button rendering hook which I have prototyped in my own branch)

**Comment by dclaux** [comment]
@anbare I think a better way to achieve this layout might be to use a ColumnSet with two columns. Each would have a weight of 1; each would contain an Image followed by a TextBlock; and each would have its selectAction set to whichever action you need.

**Comment by dclaux** [comment]
Here is a sample (minus correct spacing etc, just to illustrate the principle):
```
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"body": [
	    {
	        "type": "TextBlock",
	        "text": "Snooze for"
	    },
		{
			"type": "Input.ChoiceSet",
			"id": "snoozeTime",
			"choices": [
			    { "title": "10 minutes", "value": 10 }
			],
			"value": 10
		},
		{
			"type": "ColumnSet",
			"columns": [
				{
				    "size": 1,
				    "selectAction": {
				        "type": "Action.Submit",
				        "data": {
				            "action": "snooze",
				            "alarmId": "3"
				        }
				    },
				    "items": [
				        {
				            "type": "Image",
				            "url": "http://messagecardplayground.azurewebsites.net/assets/CircleGreen.png",
				            "horizontalAlignment": "center"
				        },
				        {
				            "type": "TextBlock",
				            "text": "Snooze",
				            "horizontalAlignment": "center"
				        }
				    ]
				},
				{
				    "size": 1,
				    "selectAction": {
				        "type": "Action.Submit",
				        "data": {
				            "action": "dismiss",
				            "alarmId": "3"
				        }
				    },
				    "items": [
				        {
				            "type": "Image",
				            "url": "http://messagecardplayground.azurewebsites.net/assets/CircleGreen.png",
				            "horizontalAlignment": "center"
				        },
				        {
				            "type": "TextBlock",
				            "text": "Dismiss",
				            "horizontalAlignment": "center"
				        }
				    ]
				}
			]
		}
	]
}
```

As rendered:
![image](https://user-images.githubusercontent.com/1334689/28192783-3ca89466-67ed-11e7-9395-268374892cd1.png)

**Comment by anbare** [comment]
But that wouldn't be a good way to ensure a consistent behavior for buttons. Plus, what if in the future the button style evolves and they want to display the buttons with images on the left instead of top? Or they want to display all the buttons right-aligned instead of center-spread? If we took this ColumnSet approach, they would be unable to do it since each app developer had to manually try to replicate the current behavior, which will then not match the new style in the future.

If we did take this ColumnSet approach, that would beg the question of **why do we even have an actions bar?** You could just use select actions for everything! You could lay out buttons horizontally, vertically, whatever you want!

I believe why we wanted an actions bar is so that the host can have some sort of consistency around how buttons are displayed :) We would want the same consistency here, simply with the ability to add an image.

**Comment by dclaux** [comment]
Technically you can already do what you want. In the payload you posted, your action type is "ToastAction.Background." For this to work with the Adaptive renderer, you have to register that action type, and you have to provide parsing logic for it. So you can already have that custom property you want . On top of that you have to customize the renderer so it renders the buttons as shown in you screenshot.

The questions really are, IMO:
- Should we officially support adding an icon to any action
- How should these actions be rendered, e.g. how much control does one host want to have over the layout of their buttons
- Should it be possible for one host to have buttons with icon on the left AND others with icon at the top in the same card

And then of course, because selectAction does exist, it will still always be possible for a card author to choose to do things the way I suggested earlier.

**Comment by anbare** [comment]
This issue was tracking the fact that custom properties aren't passed through on UWP (I believe UWP doesn't support custom types either yet so I've been pre-manipulating these to type of Action.Submit).

So if that's part of the plans we're all good - that's what this issue was tracking. I don't believe it should be part of the official schema since I don't believe everyone needs it.

**Comment by dclaux** [comment]
Each renderer should have a pluggable model to register custom element and action types. That should include providing both custom parsing and custom rendering logic for custom element types. For custom action types, it only includes providing custom parsing logic, as the rendering of action buttons is meant to be controlled by the host - which corresponds to what you want. So there does seem to be a need to discuss the points I mentioned above.

**Comment by anbare** [comment]
Dupe of #389
