### ISSUE TITLE
[Andoird][Unable to integrate sdk] [Not able to import Adaptive card]

### ISSUE THREAD

**Issue by gkode** [microsoft/AdaptiveCards#4796]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android

If you're an author, who are you sending cards to?

# Version of SDK
latest

# Details

I am unable to import adaptive card. 

I did npm install adaptivecards-reactnative . i can see dependency in my node modules, i can see all node modules of adaptivecards-reactnative but unable to " import AdaptiveCard from 'adaptivecards-reactnative'".

While running app, it throws unable to find  'adaptivecards-reactnative' module

**Comment by shalinijoshi19** [comment]
(@BalajiR, @pragadeeshk, @Vasanth-S are you able to help out on this one at all? Thanks

**Comment by gkode** [comment]
Adding more information "My project is using typescript."  React Native version is 0.61.5

**Comment by pragadeeshk** [comment]
@gkode Please post a code snippet of the import statements and AdaptiveCard component usage. The installation process is pretty much straight forward as mentioned in the [Readme](https://github.com/microsoft/AdaptiveCards/blob/main/source/community/reactnative/README.md). If you still face issue, I can assist you in setting it up.

**Comment by BalajiR** [comment]
@gkode , Tried to reproduce the issue you mentioned, but able to see the sample card rendered. Could be please share the error details (+ screenshots) like Is it happening during dependency addition / launching the JS bundler / while running in emulator ? 
I followed the below steps with same config you shared.

![4796](https://user-images.githubusercontent.com/462275/94530007-16555200-0258-11eb-8f74-3b96356491ba.png)

<img src="https://user-images.githubusercontent.com/462275/94530073-2f5e0300-0258-11eb-9f64-910660b3b0b4.png" width="320"/>

**Comment by shalinijoshi19** [comment]
@gkode closing this out since it's been stale for a bit - Could you take a look at @BalajiR 's response above and get back to us if you continue to see the issue? Thanks!

**Comment by Vasanth-S** [comment]
@shalinijoshi19 The issue has been discussed with the reporter and found that it's working as expected.
