### ISSUE TITLE
[Javascript][Theming] Allow custom styles for containers

### ISSUE THREAD

**Issue by scottlovegrove** [microsoft/AdaptiveCards#4797]
# Platform
* JavaScript

# Author or host

I'm both, but I think this might apply to the authoring side.

# Version of SDK

npm 2.3.0

# Details

I wasn't sure whether to put this as a bug or feature request, have gone for bug.

Container.style is defined as `string | undefined`, this to me suggests that we could put our own custom styles in and have that custom style represented in the hostconfig on my renderer. The problem is, if it isn't one of the official styles, the style property appears to be ignored and not included in the json.

On my rendering side, in my host-config file, I have a containerStyle set for my custom theme, and `adaptiveCards.allowCustomStyles` is set to true, but none of that will matter if the server doesn't send that custom style when it's serialized. 

So either:
- I'm doing something wrong to enable custom container styles
- It should work as I expected, but isn't
- The styles for containers should be fixed to a type to remove ambiguity for the dev.

**Comment by shalinijoshi19** [comment]
@dclaux could you take a first stab at helping out with this one ? thanks !

**Comment by dclaux** [comment]
The JS SDK does support non standard (custom) container styles. These must be defined in your **HostConfig** in the `containerStyles` section under the `customStyles` property.

This feature is **specific to the JS SDK**, is **not supported in other SDKs** and is **not supported by hosts such as Outlook or Teams**. Cards authored using custom styles will not rendered properly in those hosts.

```
{
    ...
    "containerStyles": {
        "default": {
            ... default style definition
        },
        ... other default styles
        "customStyles": [
            {
                "name": "myCustomStyleName",
                "style": {
                    ... definition of custom style
                }
            },
            ... more custom styles
        ]
    }
}
    
```

Then custom styles can be used in AC payloads just the same as any other built-in style:
```
{
    "type": "Container",
    "style": "myCustomStyleName"
}
```

**Comment by scottlovegrove** [comment]
Thanks for the info @dclaux. 

>  is not supported in other SDKs

Follow up question regarding this then. We are currently looking to use adaptive cards to extend our apps' UIs so that third parties can add their own integrations and UI to our products, if we were have our own style (eg, `overlay`), are you saying that this style can only be applied when using the javascript SDK? The android renderer won't allow for this? Similarly the iOS one?

**Comment by scottlovegrove** [comment]
> These must be defined in your HostConfig in the containerStyles section under the customStyles property.

Also, is this documented anywhere? I can't find any mention in the docs and possibly could have saved this issue being raised.

**Comment by dclaux** [comment]
@scottlovegrove that's correct

**Comment by dclaux** [comment]
And by the way, custom styles don't allow you to do everything you want - it's just a way to add more named styles, defined by its background color and associated font colors.

**Comment by scottlovegrove** [comment]
> And by the way, custom styles don't allow you to do everything you want

The scenario that has prompted this, it actually would have done. We were trying to get a semi-transparent background to overlay over a background image in order for some text to be more clearly read. I found that if I changed the style to `emphasis` and then set the emphasis' background to be a semi-transparent black color, this worked exactly as we needed. 

> @scottlovegrove that's correct

That's a shame, as it means we won't be able to adopt this approach then. Is this just something that's missing but will be added, or is not something that's planned at all for the other SDKs?

**Comment by scottlovegrove** [comment]
We've resorted to using a small semi-transparent png and setting it to a background image with a repeating fillMode in order to achieve this, but would have been simpler to use a custom style
![image](https://user-images.githubusercontent.com/25244878/94164369-dfaac080-fe80-11ea-9a49-39451a1e703b.png)

**Comment by dclaux** [comment]
Indeed it would have worked for you.

It's not "missing" in the other SDKs, and there is no plan to add it. The reason is that since custom styles are specific to hosts there would be no guarantee for a card author that a certain custom style would be available in the host they target. This custom styles feature was added solely to the JS SDK to support an internal project.

How many custom styles would you need? Just this `overlay` style? We could potentially introduce an additional out-of-the-box "overlay" style name that you could customize like all other built-in styles. We'd have to discuss internally though, and support would take time to come to all SDKs.

**Comment by scottlovegrove** [comment]
At the moment, yes, just the `overlay` style was needed. We could have just gone with the emphasis one, but we didn't feel comfortable overriding a standard style in this way, especially as our developers may want to use the emphasis one for what it's intended. 

Definitely a shame there's no way to configure the other SDKs to allow custom styles, especially for anyone who, like us, are both the authors and hosts.

**Comment by dclaux** [comment]
@matthidinger FYI
@scottlovegrove I hear you. We'll discuss internally, but I wouldn't hold my breath...

**Comment by shalinijoshi19** [comment]
@RebeccaAnne bringing this to your radar as potential discussion topic at some point.. @dclaux do we have a proposal draft that we could try to go over in one of the Wed discussions ? Thanks

**Comment by dclaux** [comment]
@shalinijoshi19 this capability is already supported in JS. The design is the one mentioned above in this very issue, which I'm pasting again here:

The JS SDK does support non standard (custom) container styles. These must be defined in your **HostConfig** in the `containerStyles` section under the `customStyles` property.

This feature is **specific to the JS SDK**, is **not supported in other SDKs** and is **not supported by hosts such as Outlook or Teams**. Cards authored using custom styles will not rendered properly in those hosts.

```
{
    ...
    "containerStyles": {
        "default": {
            ... default style definition
        },
        ... other default styles
        "customStyles": [
            {
                "name": "myCustomStyleName",
                "style": {
                    ... definition of custom style
                }
            },
            ... more custom styles
        ]
    }
}
    
```

Then custom styles can be used in AC payloads just the same as any other built-in style:
```
{
    "type": "Container",
    "style": "myCustomStyleName"
}
```

**Comment by dclaux** [comment]
It is not a good idea to support this feature officially. It will simply open the door to creating cards that do not look good everywhere, because it depends on the host defining the custom styles (and if they don't, the best we can do is fall back to something that will simply not look good.)

**Comment by paulcam206** [comment]
This is implemented in the Javascript renderer, but is not on our roadmap to implement on other platforms at the moment.
