### ISSUE TITLE
[Android][Rendering] [Rendering breaks when empty string is given in TextBlock]

### ISSUE THREAD

**Issue by dipja** [microsoft/AdaptiveCards#4801]
# Platform

What platform is your issue or question related to? (Delete other platforms).
- [x] Android
- [x] iOS
- [x] WPF
- [x] UWP

# Author or host

MS Teams - @microsoft/teams  

# Version of SDK

SDK version 2.1.0 (Adaptive card version 1.3)

# Details

The rendering of the container breaks when it has a TextBlock with an empty string in MS Teams. The same is observed in the android visualizer app.

The zip contains the sample json with empty string TextBlock and non empty string TextBlock and corresponding screenshots of the android visualizer.

This does NOT happen in adaptive card version 1.2

[TextBlock.zip](https://github.com/microsoft/AdaptiveCards/files/5267185/TextBlock.zip)

TextBlock with empty string

![image](https://user-images.githubusercontent.com/61967816/94006086-ee2fa400-fdbc-11ea-939f-f257893632fe.png)

Removing the TextBlock with empty string

![image](https://user-images.githubusercontent.com/61967816/94006048-de17c480-fdbc-11ea-81dc-46b902e3651e.png)

**Comment by sowrabh-msft** [comment]
@shalinijoshi19 @dclaux We are facing this issue as we are upgrading to the latest SDK in Teams. Can you please triage and let us know how we can work around this.
FYI: @VikrantSingh01

**Comment by jwoo-msft** [comment]
@sowrabh-msft this is fixed, and the fix will be in our next patch release which is scheduled for the end of this month.

**Comment by shalinijoshi19** [comment]
> @sowrabh-msft this is fixed, and the fix will be in our next patch release which is scheduled for the end of this month.

@jwoo-msft can you reference the corresponding PR/issue number here for reference and close this out as a dup of that issue pls? thanks. Also to be clear it won't be a patch release but a minor _(2.x series)_ release out of main for the 1.3 artifacts (_we are only doing patches at this point to the 1.2.x series_)

**Comment by shalinijoshi19** [comment]
@sowrabh-msft this issue was released as part of our 20.09 artifacts. Thanks.
