### ISSUE TITLE
JS builds are not publishing packages to internal feed

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#4805]
The nightly NodeJS builds are failing to publish the packages to the internal package feed. It seems to a problem in the version concatenation:

**Actual version** in the pipeline: `adaptivecards-designer-1.2.0-ci.20.0.tgz`
**Expected version** should automatically append a date and/or build number, e.g.,: `adaptivecards-designer-1.2.0-ci.20.09.23.01.tgz`

```
18 http fetch PUT 403 https://microsoft.pkgs.visualstudio.com/_packaging/ac9384a1-3d77-7fcf-aeac-aed5b8b4e35f/npm/registry/adaptivecards-designer 2434ms
19 verbose stack Error: 403 Forbidden - The feed 'AdaptiveCards' already contains file 'adaptivecards-designer-1.2.0-ci.20.0.tgz' in package 'adaptivecards-designer 1.2.0-ci.20.0'. (DevOps Activity ID: 10F405A8-FFB4-44AC-8C7E-2F8A8AC0BF7B) - PUT https://microsoft.pkgs.visualstudio.com/_packaging/ac9384a1-3d77-7fcf-aeac-aed5b8b4e35f/npm/registry/adaptivecards-designer - Forbidden
```

https://dev.azure.com/microsoft/AdaptiveCards/_build/results?buildId=27282399&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=3efd9125-3161-57ee-e30c-e647b481d948

**Comment by shalinijoshi19** [comment]
Will look into this one this week ahead of providing access to private packages to the Teams folks.

**Comment by shalinijoshi19** [comment]
@jwoo-msft  can you help take a look at this one ahead of release see if this is still an issue for builds coming out of main for JS?

**Comment by RebeccaAnne** [comment]
Per discussion, these seem to be being successfully generated:
https://dev.azure.com/microsoft/AdaptiveCards/_packaging?_a=package&feed=AdaptiveCards&package=adaptivecards-designer&protocolType=Npm&version=1.2.0-ci.202010.28001.0&view=versions
https://dev.azure.com/microsoft/AdaptiveCards/_packaging?_a=package&feed=AdaptiveCards&package=adaptivecards&protocolType=Npm&version=3.1.0-ci.202010.14001.0&view=versions

@matthidinger feel free to re-open if there's still an issue we're misunderstanding here.
