### ISSUE TITLE
[Designer] Switching to a host that supports a lower version of the AC schema shouldn't drop the unsupported constructs from the card payload unless the card is actually modified

### ISSUE THREAD

**Issue by dclaux** [microsoft/AdaptiveCards#4808]
# Platform

* JavaScript (designer)

# Description

If a card using say AC v1.3 features is loaded, and the host container is switched to a host that supports say v1.0, the card is re-rendered without using v1.3-specific features, and warnings are emitted. Switching back to a host that does support v1.3 should restore the correct rendering of the card, but currently it doesn't, as the v1.3 features are completely lost.

**Comment by shalinijoshi19** [comment]
@dclaux is this on your radar ? I've moved it out to 20.11 FYI. Thanks

**Comment by dclaux** [comment]
@shalinijoshi19 20.11 is more realistic. Thanks!

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.
