### ISSUE TITLE
.NET SDK isn't sending back choiceset style

### ISSUE THREAD

**Issue by ryanlengel** [Microsoft/AdaptiveCards#481]
I'm hitting an issue where I try to send an expanded choiceset and it doesn't get picked up in Bot Framework webchat. It seems that it's missing a style property when set to "expanded" but correctly passes through when set to "compact." You can find more details at

**Comment by ryanlengel** [comment]
Sorry I'm on mobile and can't find the edit button, previous discussions on this are found https://github.com/Microsoft/BotFramework-WebChat/issues/573

Thanks!

**Comment by matthidinger** [comment]
Thanks for reporting @ryanlengel! We'll triage this and try to get to it as soon as we can. I've added the Accepting PRs label if anyone feels like investigating

**Comment by amirtaub** [comment]
hi @matthidinger,
Do you know if we should expect any fix anytime soon, or maybe how can we work around it?

**Comment by Suneethae7** [comment]
Help on this.
Today when  I try choice set 

Emulator is working  but in web chat still show as drop down

Any work around for this 

WebChat
 
![image](https://user-images.githubusercontent.com/28727614/31250727-9afd28fe-a9d0-11e7-9029-3b5033c95fb8.png)

Emulator

**Comment by Suneethae7** [comment]
![image](https://user-images.githubusercontent.com/28727614/31250738-a748bfe2-a9d0-11e7-8721-24819e0aeac8.png)

**Comment by matthidinger** [comment]
Hi folks, this should be fixed in the latest NuGet beta package. Note we've made some breaking changes renamed the package to just `AdaptiveCards`. The .NET docs were updated with a few other changes as well.

https://docs.microsoft.com/en-us/adaptive-cards/create/libraries/net
https://www.nuget.org/packages/AdaptiveCards/
