### ISSUE TITLE
[Feature Request] Add parameter to Action.HTTP to allow to call local URI

### ISSUE THREAD

**Issue by matthenning** [microsoft/AdaptiveCards#4817]
I'm not sure whether this is the correct repository to request this feature, please correct me if I'm wrong here.

We're planning to use Teams Webhooks to send system alerts to our Ops team.
It would be great if we could acknowledge alerts right from Teams using Action.HTTP within an Adaptive Card, but like many Ops teams we don't have a publicly routed domain to reach our monitoring systems. It's only reachable via our LAN or VPN.

It would be great if there was a parameter in Action.HTTP that allows the client, in this case Teams, to send the HTTP request.

**Comment by RebeccaAnne** [comment]
This scenario should be covered by Action.Execute. Please reopen if that doesn't meet your needs.
