### ISSUE TITLE
[Javascript][Actions] [Execute ShowCardActions programmatically]

### ISSUE THREAD

**Issue by SubliemeSiem** [microsoft/AdaptiveCards#4818]
# Platform

* JavaScript

# Version of SDK

npm 2.3.0

# Details

The ```execute``` function does not work on a ```ShowCardAction```. It does work on a ```SubmitAction```. I have not checked the other action types.

# Example

```card.getActionAt(0).execute()```
When the action at index 0 is a ```SubmitAction```, the action is triggered. If it is a ```ShowCardAction``` it is not.

I need this to reset my card state after a rerender. Because of the way our application works, I may need to rerender the card on a internal store update, at which point I want to reset the state, including previously expanded subcards. I don't see another way to expand subcards programmatically.

**Comment by shalinijoshi19** [comment]
@dclaux could you take an initial first pass? thanks!
