### ISSUE TITLE
BUG: Setting Size = ImageSize.Auto does not render in JSON object

### ISSUE THREAD

**Issue by qpongo** [Microsoft/AdaptiveCards#482]
"size": "auto" is being dropped when looking at the JSON that the C# classes create and it breaks the rendering of my card when using ImageRenderer or VS Code Viewer (for example).

REPRO:  Construct the card in C# which has an image with Size = ImageSize.Large and look at the JSON that you get

ACTUAL: size is dropped from the JSON

EXPECTED:  "size": "auto" should be in my Json just like "size": "large" is there when I use large.

```
                                new Image()
                                    {
                                        Size = ImageSize.Large,
                                        Url = $"http://....",
                                    }
```

Viewing JSON with...

`string json = JsonConvert.SerializeObject(card, Formatting.None);`

Rendering with...
```

            ImageRenderer renderer = new ImageRenderer(new HostConfig(), String.Empty);
            Stream stream = await renderer.RenderAdaptiveCardAsync(card, 600);

```

I would have added the fix but didn't see where this is happening on my first dig.  I'm guessing you figured it wasn't necessary because maybe 'auto' is the default but someone else isn't making the same assumption.

**Comment by qpongo** [comment]
I can confirm that image render works correctly in the current master build but will let you close the bug in case it jogs your brain from something related.

I didn't see the change here that resolved it but I could be wrong.

https://github.com/Microsoft/AdaptiveCards/pull/469

**Comment by matthidinger** [comment]
This should be fixed in the latest .NET packages
