### ISSUE TITLE
[Android][Adaptive card actions] [User inputs unavailable on click of any (custom) action except submit action]

### ISSUE THREAD

**Issue by dipja** [microsoft/AdaptiveCards#4829]
# Platform

What platform is your issue or question related to? 

* Android

# Author or host

Microsoft Teams 

# Version of SDK

Adaptive card SDK 2.1.0 (Adaptive card v1.3)

# Details

When there is click on the custom action button, we try to get the input values from the rendered card. Even if the user puts some value on the inputs in the card, these inputs are not retrieved.

To get the inputs on the card we use the AC SDK method `renderedAdaptiveCard.getInputs()` which returns an inputs map with key-value pairs named `prevalidatedInputs`.

This `prevalidatedInputs `map is only populated when an `onClick()` event occurs for Submit Actions. In the `BaseActionElementRenderer` class from the AC SDK we can see the `renderedAdaptiveCard.areInputsValid()` being called only for Submit actions, this method is responsible for adding the inputs(id-value pair) to `prevalidatedInputs`. This flow is skipped in case of any action apart from submit action and thus an empty inputs map is returned when we try to get the inputs for a custom action.

Hence the **input validation** and **input retrieval** are tightly coupled with only submit actions.

**Comment by dipja** [comment]
@shalinijoshi19 @dclaux We are facing this issue as we are upgrading to the latest SDK in Teams. Can you please triage and let us know how we can work around this.
FYI: @sowrabh-msft @VikrantSingh01

**Comment by shalinijoshi19** [comment]
@almedina-ms any updates on this one?
