### ISSUE TITLE
[Android][Input validation error] [Input validation error UX]

### ISSUE THREAD

**Issue by dipja** [microsoft/AdaptiveCards#4830]
# Platform

What platform is your issue or question related to?

* Android

# Author or host

Microsoft Teams

# Version of SDK

Adaptive card SDK 2.1.0 (Adaptive card v1.3)

# Details

When there is an input validation error on the card, the SDK adds an error message to the card and changes the background color of the EditText.

The SDK gets the drawable of the EditText and applies a color filter to it assuming that the EditText would use the default drawable (`ValidatedEditText.class`). But in case the host uses a custom drawable with its EditText, the UX could be completely different. There is no place where the host can override this behavior of getting the drawable and applying the color filter to it.

Also, the color being used to highlight the EditText comes from ContainerStyle.Default -> ForegroundColor.Attention. There is no new host config to pick this color. (`TextInputRenderer.class`)

The difference between visualizer app which uses default EditText drawable and Teams android client which uses a custom drawable.

![image](https://user-images.githubusercontent.com/61967816/94392079-e84b1180-0174-11eb-932c-91e8692832a2.png)

![image](https://user-images.githubusercontent.com/61967816/94392246-5ee80f00-0175-11eb-9199-fdddf2aa5c9f.png)

**Comment by dipja** [comment]
@shalinijoshi19 @dclaux We are facing this issue as we are upgrading to the latest SDK in Teams. Can you please triage and let us know how we can work around this.
FYI: @sowrabh-msft @VikrantSingh01

**Comment by shalinijoshi19** [comment]
@almedina-ms any updates on this one? Thanks
