### ISSUE TITLE
[iOS][Image - repeatHorizontally] [Parity issue: iOS requires minimum height to render background image]

### ISSUE THREAD

**Issue by adumrewal** [microsoft/AdaptiveCards#4832]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Host - Teams iOS Client

# Version of SDK

1.2.10

# Details

On iOS if minHeight for Container is not defined, backgroundImage with fillMode "RepeatHorizontally" fails to render. However Android/Web render the card correctly.
PFA sample card json and screenshots:
iOS:
![Screenshot 2020-09-28 at 2 00 41 PM](https://user-images.githubusercontent.com/8917620/94409045-41c23900-0193-11eb-9206-6b53fbefaba5.png)
Desktop:
![Screenshot 2020-09-28 at 2 01 32 PM](https://user-images.githubusercontent.com/8917620/94409056-44bd2980-0193-11eb-82ab-9b29e6e0837d.png)

Card Json: 
[backgroundImage.txt](https://github.com/microsoft/AdaptiveCards/files/5290949/backgroundImage.txt)

**Comment by jwoo-msft** [comment]
@adumrewal 
![image](https://user-images.githubusercontent.com/4112696/94634295-824daf80-0284-11eb-9ebf-5c975bff2619.png)

Is your payload correct?
I tested it with main branch, and it doesn't look different.

Thanks
