### ISSUE TITLE
[iOS][Input validation] [Card UX issue : when error message is displayed on the card on button click]

### ISSUE THREAD

**Issue by jyoti-ms** [microsoft/AdaptiveCards#4835]
# Platform

What platform is your issue or question related to?

* iOS

# Author or host

Host - Teams iOS Client

# Version of SDK

SDK 2.1.0 (Adaptive card v1.3)

# Details

An error message is shown on the card when input validation check is not passed on submit button click.

SDK `send` method is not triggering any `onClick` event to the client whenever input validation failed and error messages are shown directly. 

In teams, we need to refresh the superview's layout (table view cell layout) that contains the adaptive card whenever error message is shown on the card as height of the adaptive card view has increased (changed by the SDK).

This is causing the UX to squeeze when user clicks on action.submit button. SDK is handling this right now and updating the layout for adaptive card only. 

PFA screenshot:
![image](https://user-images.githubusercontent.com/72016168/94468071-7fe64980-01e1-11eb-8dd6-cd37dc3c72db.png)

**Comment by jyoti-ms** [comment]
@shalinijoshi19 @dclaux @jwoo-msft  We are facing this issue as we are upgrading to the latest SDK in Teams. Can you please triage and let us know how we can work around this.
FYI: @sowrabh-msft @VikrantSingh01

**Comment by jwoo-msft** [comment]
@jyoti-ms As we have discussed, SDK will send layout change notification.

**Comment by jyoti-ms** [comment]
Thanks @jwoo-msft. yes, sending layout change notification on button click should work.

**Comment by shalinijoshi19** [comment]
@sowrabh-msft FYI this issue has been addressed with our last patch. thanks
