### ISSUE TITLE
[iOS][input validation error] [UX issue : Input view styling on validation error]

### ISSUE THREAD

**Issue by jyoti-ms** [microsoft/AdaptiveCards#4839]
# Platform

What platform is your issue or question related to?

* iOS

# Author or host

Host - Teams iOS Client

# Version of SDK

SDK 2.1.0 (Adaptive card v1.3)

# Details

When there is an input validation error message on the card, the SDK adds the border and changes the border colour of the inputView.

The SDK gets the inputView from the input stack and applies a colour filter to it assuming that the inputView would use the default renderer and this logic is present in `validate` method in ACRInputLabelView.mm and there is no new host config to pick this border colour.

```
    self.stack.arrangedSubviews[1].layer.borderWidth = 1;
    self.stack.arrangedSubviews[1].layer.cornerRadius = 6.0f;
    self.stack.arrangedSubviews[1].layer.borderColor = UIColor.systemRedColor.CGColor;
``` 

But in case the host uses a custom input renderer with its inputView, the UX we want should be based on the current theme/host config. There is no place where the host can override this behaviour of getting the input view and applying the border/colour filter to it. 

PFA screenshot of the default behaviour and expected host behaviour (teams client) :

Default behaviour :
![image](https://user-images.githubusercontent.com/72016168/94479113-eb381780-01f1-11eb-89f4-ae6229d38eeb.png)

Expected behaviour :
![image](https://user-images.githubusercontent.com/72016168/94485412-8681ba80-01fb-11eb-9390-da6382856371.png)

**Comment by jyoti-ms** [comment]
@shalinijoshi19 @dclaux @jwoo-msft  We are facing this issue as we are upgrading to the latest SDK in Teams. Can you please triage and let us know how we can work around this.
FYI: @sowrabh-msft @VikrantSingh01

**Comment by jwoo-msft** [comment]
Fixed via https://github.com/microsoft/AdaptiveCards/pull/4853
Please see https://github.com/microsoft/AdaptiveCards/pull/4852 for the usage.

**Comment by shalinijoshi19** [comment]
@sowrabh-msft please see @jwoo-msft's comments above. Thanks.
