### ISSUE TITLE
[iOS][Issue with isVisibility] [isVisibility for an item in Container gets imposed on other items]

### ISSUE THREAD

**Issue by adumrewal** [microsoft/AdaptiveCards#4843]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Host - Teams iOS Client

# Version of SDK

1.2.10

# Details

If isVisibility is set to false for one item in a container, all following items in container are not visible
PFA a sample JSON and screenshots to help understand the issue better.
iOS:
<img width="339" alt="Screenshot 2020-09-29 at 2 46 17 PM" src="https://user-images.githubusercontent.com/8917620/94539257-a00a1d00-0262-11eb-91b7-545162d59dae.png">

Desktop:
<img width="442" alt="Screenshot 2020-09-29 at 2 46 28 PM" src="https://user-images.githubusercontent.com/8917620/94539267-a39da400-0262-11eb-9fe1-a7bcfb0a5761.png">

Card JSON:
[containerVisibility.txt](https://github.com/microsoft/AdaptiveCards/files/5297798/containerVisibility.txt)

**Comment by jwoo-msft** [comment]
@adumrewal 

Thanks, I can repro it on my end.
