### ISSUE TITLE
[iOS][MS-Teams] If there is no select action on the image, then the select action from the superview should be passed onto the subview image.

### ISSUE THREAD

**Issue by SagarPant74** [microsoft/AdaptiveCards#4844]
# Platform

What platform is your issue or question related to? (Delete other platforms).
**iOS**
# Author or host

MS-Teams iOS client

If you're an author, who are you sending cards to?

# Version of SDK

1.2.10

# Details

Explain your issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards).

In case of an adaptive card having an image with no select action, there is no way to know whether the superview has a select action or not. So we can't decide whether to add a custom action handler for the image or not.

**In the video attached, two actions get triggered due to this on the card.**

[Link to video](https://microsoft-my.sharepoint.com/:v:/p/sagpan/EVySu_F99a9LmUdGAy_Oy9oBLupN81CG-ckAvfPuA_KbFw?e=CONUKg)

**Here is the card Json**
`{
  "body": [
    {
      "columns": [
        {
          "width": "35",
          "items": [
            {
              "size": "stretch",
              "url": "https://urlp.asm.skype.com/v1/url/content?url=https%3a%2f%2fmessagecardplayground.azurewebsites.net%2fassets%2fMostly%2520Cloudy-Square.png",
              "height": "auto",
              "type": "Image"
            }
          ],
          "type": "Column"
        },
        {
          "width": "65",
          "items": [
            {
              "size": "large",
              "text": "Monday April 1",
              "weight": "bolder",
              "type": "TextBlock",
              "color": "light"
            },
            {
              "size": "medium",
              "spacing": "none",
              "type": "TextBlock",
              "text": "63 / 42"
            },
            {
              "spacing": "none",
              "isSubtle": true,
              "type": "TextBlock",
              "text": "20% chance of rain"
            },
            {
              "spacing": "none",
              "isSubtle": true,
              "type": "TextBlock",
              "text": "Winds 5 mph NE"
            }
          ],
          "type": "Column"
        }
      ],
      "type": "ColumnSet"
    },
    {
      "columns": [
        {
          "items": [
            {
              "type": "TextBlock",
              "text": "Fri",
              "horizontalAlignment": "center"
            },
            {
              "url": "https://urlp.asm.skype.com/v1/url/content?url=https%3a%2f%2fmessagecardplayground.azurewebsites.net%2fassets%2fMostly%2520Cloudy-Square.png",
              "type": "Image",
              "height": "auto"
            },
            {
              "type": "TextBlock",
              "text": "62",
              "horizontalAlignment": "center"
            },
            {
              "text": "52",
              "spacing": "none",
              "isSubtle": true,
              "type": "TextBlock",
              "horizontalAlignment": "center"
            }
          ],
          "width": "20",
          "selectAction": {
            "url": "https://www.microsoft.com",
            "title": "View Friday",
            "type": "Action.OpenUrl"
          },
          "type": "Column"
        },
        {
          "items": [
            {
              "type": "TextBlock",
              "text": "Sat",
              "horizontalAlignment": "center"
            },
            {
              "url": "https://urlp.asm.skype.com/v1/url/content?url=https%3a%2f%2fmessagecardplayground.azurewebsites.net%2fassets%2fDrizzle-Square.png",
              "type": "Image",
              "height": "auto"
            },
            {
              "type": "TextBlock",
              "text": "60",
              "horizontalAlignment": "center"
            },
            {
              "text": "48",
              "spacing": "none",
              "isSubtle": true,
              "type": "TextBlock",
              "horizontalAlignment": "center"
            }
          ],
          "width": "20",
          "selectAction": {
            "url": "https://www.microsoft.com",
            "title": "View Saturday",
            "type": "Action.OpenUrl"
          },
          "type": "Column"
        },
        {
          "items": [
            {
              "type": "TextBlock",
              "text": "Sun",
              "horizontalAlignment": "center"
            },
            {
              "url": "https://urlp.asm.skype.com/v1/url/content?url=https%3a%2f%2fmessagecardplayground.azurewebsites.net%2fassets%2fMostly%2520Cloudy-Square.png",
              "type": "Image",
              "height": "auto"
            },
            {
              "type": "TextBlock",
              "text": "59",
              "horizontalAlignment": "center"
            },
            {
              "text": "49",
              "spacing": "none",
              "isSubtle": true,
              "type": "TextBlock",
              "horizontalAlignment": "center"
            }
          ],
          "width": "20",
          "selectAction": {
            "url": "https://www.microsoft.com",
            "title": "View Sunday",
            "type": "Action.OpenUrl"
          },
          "type": "Column"
        },
        {
          "items": [
            {
              "type": "TextBlock",
              "text": "Mon",
              "horizontalAlignment": "center"
            },
            {
              "url": "https://urlp.asm.skype.com/v1/url/content?url=https%3a%2f%2fmessagecardplayground.azurewebsites.net%2fassets%2fMostly%2520Cloudy-Square.png",
              "type": "Image",
              "height": "auto"
            },
            {
              "type": "TextBlock",
              "text": "64",
              "horizontalAlignment": "center"
            },
            {
              "text": "51",
              "spacing": "none",
              "isSubtle": true,
              "type": "TextBlock",
              "horizontalAlignment": "center"
            }
          ],
          "width": "20",
          "selectAction": {
            "url": "https://www.microsoft.com",
            "title": "View Monday",
            "type": "Action.OpenUrl"
          },
          "type": "Column"
        }
      ],
      "type": "ColumnSet"
    }
  ],
  "speak": "Weather forecast for Monday is high of 62 and low of 42 degrees with a 20% chance of rainWinds will be 5 mph from the northeast",
  "version": "1.0",
  "type": "AdaptiveCard",
  "backgroundImage": "https://urlp.asm.skype.com/v1/url/content?url=https%3a%2f%2fmessagecardplayground.azurewebsites.net%2fassets%2fMostly%2520Cloudy-Background-Dark.jpg",
  "$schema": "https://adaptivecards.io/schemas/adaptive-card.json"
}`

**Comment by jwoo-msft** [comment]
@SagarPant74 
thanks for the detailed description of the issue.
If this is urgent, could you please work with @anbah34 to include this issue for 20.10?

Thanks

**Comment by shalinijoshi19** [comment]
@jwoo-msft assigning to you for pickup.

**Comment by shalinijoshi19** [comment]
@jwoo-msft what is still pending for this issue to be closed at this point?

**Comment by jwoo-msft** [comment]
> @jwoo-msft what is still pending for this issue to be closed at this point?

@shalinijoshi19, I need to close on accessibility issues, I'm aiming for 20.12.
Thanks

**Comment by shalinijoshi19** [comment]
@SagarPant74 / @jwoo-msft is this a 1.3 upgrade blocker for Teams do we know? Can we find out to help prioritize? Tx

**Comment by shalinijoshi19** [comment]
@jwoo-msft removing the Upgrade Blocker tag from this issue; Please articulate/summarize the remaining work here including any broader resource resolver feature work to close this out for planning. Thanks!

**Comment by jwoo-msft** [comment]
@shalinijoshi19 

the typical use case for handling touch is that the touch is delivered to the further most view from the root view that can handle the touch.  this use case is different. the teams want the touch to be delivered to the further most view, but they don't want the view to be UIImageView if the image view's super view has the select action. what they want is an API to tell if the superview of a view has a selection action.

implemented code will have a tree traversal. many of our features have tree traversal components. Instead of replicating the code, we will implement a resource crawler that gathers any resources in json payload. the resources can be URLs, selectActions, padding, and anythings in JSON. once the resource crawler is done, we can implement this feature on top of it, and it should be straightforward to implement.

**Comment by jwoo-msft** [comment]
touch events won't occur twice with v2.4.6.

**Comment by VikrantSingh01** [comment]
@jwoo-msft : Is v2.4.6 already available for uptake now ?
