### ISSUE TITLE
[Javascript] After Using Adaptive Card Fabric Plugin - Radio buttons are displaying instead of dropdown

### ISSUE THREAD

**Issue by dharma-reddy** [microsoft/AdaptiveCards#4845]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Version of SDK

latest

# Details
Radio buttons are loading instead of dropdown.
**Before using Adaptive Card Fabric Plugin. Please see the screenshot of my dialog with dropdown**

![image](https://user-images.githubusercontent.com/16010724/94567613-49fca000-0289-11eb-9ea3-3747169a597f.png)

**After using Adaptive Card Fabric Plugin. Please see the screenshot of dialog with radio buttons**

![image](https://user-images.githubusercontent.com/16010724/94433301-ba39f180-01b5-11eb-9e5a-096566044c0c.png)

**Comment by shalinijoshi19** [comment]
@paulcam206 who is investigating this one? I dont see this assigned to anyone?

**Comment by dharma-reddy** [comment]
@paulcam206, Did you get a chance to try out the solution for the above error? Please let me know in case of any queries. It would be great if you help me with the current status.

**Comment by dharma-reddy** [comment]
Hi Team...Can you help us to fix this issue at the earliest.

**Comment by RebeccaAnne** [comment]
@matthidinger can you take a look at this one?

**Comment by dclaux** [comment]
The Fabric extension defaults to `expanded` mode when the style property isn't specified. To get a combo box, explicitly specify `"style": "compact"` on your `Input.ChoiceSet`

**Comment by dharma-reddy** [comment]
Hi David,

Thanks for your reply,

I have tried using the "style":"compact" to the "Input.ChoiceSet". But still, I am getting the expanded view only.

Please find the below screenshots

![image](https://user-images.githubusercontent.com/16010724/112793444-eeb63980-9082-11eb-9aef-46990862df10.png)
![image](https://user-images.githubusercontent.com/16010724/112793493-08f01780-9083-11eb-8164-f50c565db0e3.png).

Thanks,
Dharma

**Comment by dclaux** [comment]
That is weird, as far as I can tell the code correctly parses the style property and creates a combo box when style is set to "compact".

Looks like there is a bug indeed.

**Comment by dharma-reddy** [comment]
Hi David,

The "style":"compact" property displays combo box ,if I am not using "Adaptive Card Fabric Plugin". Problem exist only if I use "Adaptive Card Fabric Plugin". 

Please let me know, if you have any thoughts on this.

Thanks,
Dharma

**Comment by jonmill** [comment]
Adaptive Cards Fabric is deprecated and is not being maintained.
