### ISSUE TITLE
[JS] Markdown headings clipped

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#4847]
Using markdown to generate headings leads to clipped text.

Sample:
```json
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "# Markdown Heading"
        }
    ]
}
```

Here's what it looks like in the designer (note that this repros across hostconfigs regardless of whether in preview mode or not):

![image](https://user-images.githubusercontent.com/16614499/94601331-34b35180-0248-11eb-994b-7f6812ad2009.png)

**Comment by paulcam206** [comment]
It appears that this is due to the `line-height` property. I'm guessing this calculation doesn't account for the possibility of header tags?

https://github.com/microsoft/AdaptiveCards/blob/e736ed7dfca1949ac76a499e205b2d61997d7a65/source/nodejs/adaptivecards/src/card-elements.ts#L1077-L1104

**Comment by shalinijoshi19** [comment]
@dclaux do you mind taking a quick stab at this to understand what is going on here (pls also see @paulcam206 's comments above).. ?

**Comment by dclaux** [comment]
@shalinijoshi19 the solution to this is to use the non-standard `-webkit-line-clamp` CSS property which was not even an option back when the JS renderer was initially implemented. That is why the renderer uses the same trick basically every other Web developer uses, which is to explicitly set `line-height` and impose a `max-height`, which only works well when the text uses a single font size, which isn't true when using Markdown headers. Also, `-webkit-line-clamp` isn't supported in IE, so the trick currently used would have to remain as a fallback for IE.

I do not think this is a high priority issue though, or even worth fixing at all.

Do the other renderers handle this case properly?
