### ISSUE TITLE
[Javascript] Adaptive card doesn't works in IE

### ISSUE THREAD

**Issue by atishayv** [microsoft/AdaptiveCards#4855]
# Platform

* JavaScript

# Author or host

Microsoft Search

# Version of SDK

 adaptivecards: 2.0.0-rc.0
 adaptivecards-templating: 1.0.0-rc.0

# Details

The version of adaptive card doesn't works in IE. The script of adaptive card template contains many occurrences of =>, using the arrow function syntax, which indicates that there’s es2015 code in there that hasn’t been passed through babel to convert it to es5.

Passing these libraries through babel transpiler doesn't throw syntax error : 
["adaptivecards-templating", "adaptive-expressions", "antlr4ts", "lru-cache", "yallist","@microsoft/recognizers-text-data-types-timex-expression"]

but then getting these errors : 
![image](https://user-images.githubusercontent.com/13940020/94708390-29ecdf80-0362-11eb-9023-3bad9e25b519.png)

while calling template.expand.

Also, https://adaptivecards.io/designer/ doesnt works on IE.

**Comment by atishayv** [comment]
@dclaux Can you please look into the issue ?

**Comment by dclaux** [comment]
@atishayv the 1.0 release of the templating engine (including this RC, which is now outdated, please use v1.3) uses the [Adaptive Expression](https://www.npmjs.com/package/adaptive-expressions) library which compiles to ES6 and isn't compatible with IE and no plans to make it compatible. IE isn't supported anymore; how problematic is this to you?

**Comment by atishayv** [comment]
@dclaux We will not be able to support any of customisation features on IE which I think might be blocking for us. Let me loop in Jai and Jyoti as well here

**Comment by dclaux** [comment]
@matthidinger FYI

**Comment by shalinijoshi19** [comment]
@atishayv as @dclaux points out [IE 11 is deprecated in general](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666)  and will soon be stopped supporting across various Microsoft products as well; Adding support for new features to work on IE seems therefore a bit unexpected. Would be great if you or your team could share specific context ? Thanks
