### ISSUE TITLE
[Accessibility] Narrator is not reading the selection action title for the Rich Text Block

### ISSUE THREAD

**Issue by ridwived-microsoft** [microsoft/AdaptiveCards#4856]
# Platforms

- [x] JavaScript (#4857)
- [x] .NET (#5295)
- [x] UWP (Already behaves as expected)

See also #5310 and #5311

# Author or host
Host, D365, Customer Service Workspace app

# Version of SDK
1.3

# Repro
With the below RichTextBlock, Narrator should read "Click me" when the focus is on the RichTextBlock, but it reads "This is the text"
```
{
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.3",
  "body": [
    {
      "type": "RichTextBlock",
      "inlines": [
        {
          "type": "TextRun",
          "text": "This is the text",
          "selectAction": {
            "type": "Action.Submit",
            "title": "Click me"
          }
        }
      ]
    }
  ]
}
```

**Comment by ridwived-microsoft** [comment]
The narrator is expected to read the 'title' property on the selection action rather than the 'text' property of the text run in the rich text block

**Comment by shalinijoshi19** [comment]
@dclaux can you add a quick summary here of the changes you are making as part of addressing this? Thanks

**Comment by dclaux** [comment]
@shalinijoshi19 the change I am making is in the title of the PR: "Use TextRun.selectAction.title as aria-label"

**Comment by shalinijoshi19** [comment]
@RebeccaAnne FYI -- can we look into this one for next sprint? I've moved it out.

**Comment by RebeccaAnne** [comment]
This behaves as expected in UWP

**Comment by RebeccaAnne** [comment]
The bug repros on .NET WPF

**Comment by RebeccaAnne** [comment]
@jwoo-msft @golddove Could you guys check if this works as expected on iOS/Android? Thanks!

**Comment by RebeccaAnne** [comment]
Spun of iOS and Android to separate bugs to investigate and fix if necessary.
