### ISSUE TITLE
[UWP] Multi-line text input not wrapping

### ISSUE THREAD

**Issue by golddove** [microsoft/AdaptiveCards#4862]
# Platform

* UWP

# Version of SDK

latest main

# Details

JS renderer wraps long text when typing in a multiline text input. UWP renderer doesn't wrap.

Screenshot from `Inputs` scenario:

JS -

![image](https://user-images.githubusercontent.com/4442788/94960009-23747a00-04c0-11eb-8b32-ebc717c0a206.png)

UWP -

![image](https://user-images.githubusercontent.com/4442788/94743859-0e73db80-0346-11eb-913c-e3f299bf6f9c.png)

**Comment by shalinijoshi19** [comment]
@golddove can you be a bit more explicit/descriptive in your title as to what the issue here is ? And in teh description pls include a description or visual representation of what the actual and expected behavior is. Thanks

**Comment by golddove** [comment]
Added screenshot of expected behavior.
