### ISSUE TITLE
[UWP] False-positive errors and warnings in visualizer

### ISSUE THREAD

**Issue by golddove** [microsoft/AdaptiveCards#4863]
# Platform

* UWP

# Version of SDK

latest main

# Details

Three issues to fix, described below:

- [ ] FlightDetails
- [x] Agenda (#4886)
- [ ] Inputs

Visualizer surfaces an error for the `FlightDetails` scenario, but card does render.

![image](https://user-images.githubusercontent.com/4442788/94744059-63afed00-0346-11eb-8cf0-f0370790725b.png)

Likely related, `Agenda` scenario triggers a warning:

![image](https://user-images.githubusercontent.com/4442788/94744238-9fe34d80-0346-11eb-96fd-af3e7c0a7778.png)

And, in `Inputs` scenario:

![image](https://user-images.githubusercontent.com/4442788/94744425-f81a4f80-0346-11eb-9e34-48ea80130dcf.png)

**Comment by shalinijoshi19** [comment]
@RebeccaAnne moved this to our backlog - are tehse coming from the Visualizer or the UWP renderer itself?

**Comment by RebeccaAnne** [comment]
For the FlightDetails card:

The error is coming out of schema validation (performed by the Visualizer via Newtonsoft.Json.Schema.IsValid()). Simplest repro card below. Doesn't repro for some reason if the `wrap = true` is removed.

```json
 {
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.2",
	"body": [
		{
			"type": "RichTextBlock",
			"inlines": [
				{
					"type": "TextRun",
					"text": "Sat, Mar 4, 2017",
					"wrap": true
				}
			]
		}
	]
}
```

**Comment by RebeccaAnne** [comment]
For the Agenda card the message is also coming out of Schema validation. In that case there's a more obvious source. Horizontal Alignment is not in the schema for ColumnSet.  Simplest repro card:

```json
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "ColumnSet",
            "horizontalAlignment": "Center"
        }
    ]
}
```

**Comment by RebeccaAnne** [comment]
The Inputs.json issue is a legitimate warning. The number input has a min/max but no error message (#4447), and min/max now triggers input validation. We should update this when we update the scenario cards for input validation. (#4552/#4612).

 ```json
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "Input.Number",
			"min": -5,
			"max": 5,
			"id": "NumVal"
		}
	]
}

**Comment by shalinijoshi19** [comment]
@RebeccaAnne is this tracking for 20.10?

**Comment by RebeccaAnne** [comment]
@shalinijoshi19 No. A fix for one of the three issues will make the 20.10 payload, but one needs the sample updates that are tracking for after partners move onto 1.3, and the other hasn't been fully investigated yet.
