### ISSUE TITLE
[iOS][Package Manager] Add Swift Package Manager support

### ISSUE THREAD

**Issue by JustinBlock** [microsoft/AdaptiveCards#4875]
**What platform is your feature request related to? (Delete other platforms).**
* iOS

**Is your feature request related to a problem? Please describe.**
I use Carthage for downloading your package on iOS but development support is dwindling in favor of Swift Package Manager. Nearly all frameworks are moving to Swift Package Manager since it is fully supported by Apple.

**Describe the solution you'd like**
Add support for Swift Package Manager and ensure the use of semantic versioning.

**Describe alternatives you've considered**
The alternative is to continue to use Carthage or other package managers. However they are losing support due to Swift package manager. Additionally nearly all of my dependencies support Swift Package Manager.

**Additional context**
N/A

**Comment by jscalo** [comment]
I will 2nd this. In my case, I want to use AdaptiveCards _within_ a library that is itself distributed as a Swift Package and this appears to be totally impossible to do. It would be trivial if AdaptiveCards was available as a Swift Package.
