### ISSUE TITLE
[Site] Schema needs to be updated on the site

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#4879]
Although we've updated the current schema to the 1.3.0 version of the schema with #4884, this issue tracks whether we wish to revisit how we handle schema versioning. 

Looks like this will require a bit more planning -- specifically, the currently published schema is our 1.3.0 schema. Should newer schemas are published at versioned URLs (e.g. https://adaptivecards.io/schemas/1.4.0/adaptive-card.json). We need to square our structure with our card author guidance. Should the unversioned URL be considered "latest", or should it be the 1.3 schema encased in amber?

Some points:
* cards generated by the designer are all emitted with the unversioned schema url
* our samples all use the unversioned schema url
* due to this, loading any of our samples in the designer has some suboptimal behaviors (note that these aren't deficiencies in the designer):
  * properties introduced after the latest version aren't validated (e.g. `"isRequired": "steve"` weren't flagged for an invalid type when we we on the 1.1 schema) 
* our [docs](https://adaptivecards.io/explorer/AdaptiveCard.html) don't have any guidance around the value of `$schema`
* I'm not sure if we've ever publicly communicated the versioned schema URLs
* we should turn on schema validation for our samples if we're not already covering it

**Comment by paulcam206** [comment]
@matthidinger / @dclaux / @shalinijoshi19 FYI

**Comment by shalinijoshi19** [comment]
@RebeccaAnne ? I dont think we got traction on this from Paul's end before he left on leave. Can you pick it up to determine when/how this will need to be fixed - time for 20.10?

**Comment by RebeccaAnne** [comment]
@shalinijoshi19 This tracks the larger conversation around how we want to handle versioning our schema. #4884 is the immediate issue of updating our current schema to the latest version. I've moved that one back into 20.10, but this one represents a longer term conversation.
