### ISSUE TITLE
[User Experience] [Input validation errors] Lack of feedback after submission on Input Card with error

### ISSUE THREAD

**Issue by dipja** [microsoft/AdaptiveCards#4880]
# Platform

What platform is your issue or question related to?

All

# Author or host

Microsoft Teams

# Version of SDK

SDK version 2.1.0 (ACv1.3)

# Details
If action is taken on card for the subsequent time when errors are already showing on Adaptive Card, no change takes place on card. This could confuse the user that the card has frozen and nothing is happening. One way could be that error messages should vanish and reappear to show flicker so user knows that the card is not frozen.
Link to [video ](https://microsoft-my.sharepoint.com/:v:/p/dipja/EYXBk6ndT0FBrmsF6kG3Vz4BXbqoiYK6AhO8NacWqtyDtQ?e=OvB5wo)for the above experience

**Comment by shalinijoshi19** [comment]
@almedina-ms / @jwoo-msft this one is a P2 as far as the Teams 1.3 upgrade blockers is concerned but we should get this looked at and prioritized for design discussions; @RebeccaAnne FYI

**Comment by jwoo-msft** [comment]
> @almedina-ms / @jwoo-msft this one is a P2 as far as the Teams 1.3 upgrade blockers is concerned but we should get this looked at and prioritized for design discussions; @RebeccaAnne FYI

Sure, I will add those input related issues filed by Team to the design discussions.

**Comment by RebeccaAnne** [comment]
Because the errors are already showing, the user has an indication of what they need to do to progress. Additional indication here is not currently in scope.
