### ISSUE TITLE
[Android][Accessibility] [Input validation errors]

### ISSUE THREAD

**Issue by dipja** [microsoft/AdaptiveCards#4881]
# Platform

What platform is your issue or question related to?
* Android

# Author or host

Microsoft Teams

# Version of SDK

SDK version 2.1.0 (ACv1.3)

# Details

When the choiceset/toggle input is not the first input field with the error, no highlight (eg: red highlight in other input types) is applied to the input field. Only the associated error is displayed. Could we confirm if this is the expected behavior.

![image](https://user-images.githubusercontent.com/61967816/95111635-6acb6680-075d-11eb-8283-7e7d28e72ede.png)

**Comment by shalinijoshi19** [comment]
@almedina-ms assigning to you for tackling once we get clarity from the Teams side on expectation from the Accessibility SMEs here. @jwoo-msft  FYI.
