### ISSUE TITLE
[.NET] Input.Number inputs are displaying as "NaN" when no value is set using non-Xceed renderers

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#4882]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF

# Details

The below card renderers with "NaN" in .NET when Xceed Renderes are not in use:

![image](https://user-images.githubusercontent.com/9091833/95120585-a5ec7c00-0702-11eb-90e3-cfa20ae4995e.png)

```json
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "Input.Number",
            "id": "numberId"
        }
    ]
}
```

**Comment by shalinijoshi19** [comment]
@RebeccaAnne am assigning this to you to get addressed or backlogged appropriately. Tx
