### ISSUE TITLE
[Site] Update unversioned schema file on site

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#4884]
https://github.com/microsoft/AdaptiveCards/blob/7bfd4d1def2ca47cecaa6950e354574bbd6beff0/source/nodejs/adaptivecards-site/themes/adaptivecards/scripts/generator-adaptiveassets.js#L39-L44

We need further discussion about how to handle schema versioning all-up. We'll be tracking that discussion in #4879.

**Comment by shalinijoshi19** [comment]
@RebeccaAnne is this something on your radar at all? Another one that should be addressed for 20.11 if we dont have cycles for it for 20.10

**Comment by RebeccaAnne** [comment]
@shalinijoshi19 Easy enough to pull this one in for 20.10.
