### ISSUE TITLE
[Mobile][User Experience] [Input validation errors]Compact style Input ChoiceSet Focus Style on Error

### ISSUE THREAD

**Issue by jyoti-ms** [microsoft/AdaptiveCards#4889]
# Platform

What platform is your issue or question related to?
- [x] Android
- [x] iOS

# Author or host

Teams Mobile Client

# Version of SDK

SDK version 2.1.0 (ACv1.3)

# Details

**iOS**
If Input ChoiceSet (style: compact) is first item on Adaptive Card, and there is an error on card, the options pop up directly opens user view. It may cause user confusion as that is not the expected behaviour on action.
Link to [video](https://microsoft-my.sharepoint.com/:v:/p/jykukrej/EeFjS4t4p5ZJs9TDr-nkYX4BnbM9qV33xoX33fHSh5tx_A?e=Gu0lMS) for the above experience.

**Android**
If Input ChoiceSet (style: compact) is first item on Adaptive Card, and there is an error on card, the options pop up directly opens blocking user view. It may cause user confusion as that is not the expected behavior on action.
Link to [video ](https://microsoft-my.sharepoint.com/:v:/p/dipja/EScBrZ5gWPlBmyFc8tMoqvYBbOw-dVbcH2J7mV9QiUF9VQ?e=M67Uqe) for the above experience.

**Comment by shalinijoshi19** [comment]
@jwoo-msft assigning to you for initial investigation on these Teams-reported issues. Pls update with result +plan of action + milestone once we've done the initial review. thanks!
