### ISSUE TITLE
critical bug in TypeRegistry.unregisterType 

### ISSUE THREAD

**Issue by QingpingMeng** [Microsoft/AdaptiveCards#489]
TypeRegistry.unregisterType is trying to find matched type and remove it. However, splice function is doing removal in place and return the deleted elements.

`this._items = this._items.splice(i, 1);` will override the registered types with deleted one, which is completely wrong.

Fix should be just `this.items.splice(i,1)`

**Comment by QingpingMeng** [comment]
To make it clear, the file I was pointing was AdaptiveCards/source/html/renderer/src/card-elements.ts

**Comment by dclaux** [comment]
@QingpingMeng Thanks! This is now fixed in master and v0: https://github.com/Microsoft/AdaptiveCards/pull/490

**Comment by QingpingMeng** [comment]
@dclaux Thanks for the quick fix!
