### ISSUE TITLE
[iOS][Accessibility ] [Focus is not going to the first accessibility element]

### ISSUE THREAD

**Issue by jyoti-ms** [microsoft/AdaptiveCards#4890]
# Platform

What platform is your issue or question related to?

* iOS

# Author or host

Teams Mobile Client

# Version of SDK

SDK version 2.1.0 (ACv1.3)

# Details

When there are errors on the cards after pressing submit action, focus is not going to the first accessibility element (input field) on the card that has error message. Link to [video](https://msit.microsoftstream.com/video/af0ba1ff-0400-9fb2-1027-f1eb08a2a3cc?list=studio)

**Comment by shalinijoshi19** [comment]
@jwoo-msft assigning to you for initial investigation. Pls update once we do have an action plan for this. Thanks

**Comment by jwoo-msft** [comment]
Hello @jyoti-ms,

Can you be more specific about what's the issue here? If there is an error, the focus will be set on the first input item with an error. For example, if it's input.text, the focus will be set on the input.text and open up a keyboard.

**Comment by jyoti-ms** [comment]
@jwoo-msft When user clicks on submit button and if there is an error then, the view is getting scrolled and focus is not going to the first input that has errors. 
Focus is going out of the adaptive card's view when voice over is on (on input validation).

This is happening whenever layout of the superview is changed due to errors.
Can you please take a look at the video once? Link to [video](https://msit.microsoftstream.com/video/af0ba1ff-0400-9fb2-1027-f1eb08a2a3cc?list=studio) Do let me know if you need more info on this.

**Comment by jyoti-ms** [comment]
This issue can be fixed only when action type is known to me on layout change notification. 

Scenario -  Currently layout change notification is sent to the host on button click(Action.ShowCard, Action.Submit, Action.toggleVisibility). The host would need to have different layout change functions in teams client based on the type of the action. So if we have action.submit, then we can avoid performing reloadRows (because of this we are losing focus) we only need to update the height of the cell and changing the button state.
Can you please confirm on this is this is possible to provide action type and button ref on layout change notification?

cc:@sowrabh-msft @shalinijoshi19
