### ISSUE TITLE
[Android][UX] [Input ChoiceSet (compact) height and width squeezed]

### ISSUE THREAD

**Issue by dipja** [microsoft/AdaptiveCards#4891]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android

# Author or host

Microsoft Teams

# Version of SDK

SDK 2.1.0 (ACv1.3)

# Details

The height and width of the Input ChoiceSet (compact) is squeezed. The screenshot below shows the current user experience.

![image](https://user-images.githubusercontent.com/61967816/95294443-e7139600-0892-11eb-8d79-b798cbbec9d5.png)

**Comment by shalinijoshi19** [comment]
@almedina-ms / @jwoo-msft  can you please update the issue with results of the ongoing investigation? Thanks
