### ISSUE TITLE
[iOS][ActionSet renderer registration] [Setting setActionSetRenderer does not automatically set the same for ActionSets]

### ISSUE THREAD

**Issue by adumrewal** [microsoft/AdaptiveCards#4899]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Host - Teams iOS client

# Version of SDK

1.2.10

# Details

Setting Action set renderer using :
`[customRenderersRegististration setActionSetRenderer:[TSCActionSetRenderer getInstance]];`
sets it only for the "actions" element and not for the "ActionSet" element. For example in the attached json, the registered custom actionSet renderer will be called only for the "Actions" button and not the "ActionSet" button.

```{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "wrap": true,
      "text": "Below is an ActionSet"
    },
    {
      "type": "ActionSet",
      "actions": [
        {
          "type": "Action.OpenUrl",
          "title": "ActionSet",
          "url": "https://adaptivecards.io"
        }
      ]
    },
    {
      "type": "TextBlock",
      "wrap": true,
      "text": "Following is an actions element"
    }
  ],
  "actions": [
    {
      "type": "Action.OpenUrl",
      "title": "Actions",
      "url": "https://adaptivecards.io"
    }
  ]
}
```

**Comment by jwoo-msft** [comment]
@adumrewal 
ActionSet is considered as an element, and it is to be registered with element renderer registration.

**Comment by adumrewal** [comment]
Yup, that works. One small change is required in the ActionSetRenderer definition though:
```
@interface ActionSetRenderer : ACRBaseCardElementRenderer<ACRIBaseActionSetRenderer>
```

**Comment by shalinijoshi19** [comment]
Tracking for checkin to main by Monday EOD; @jwoo-msft
