### ISSUE TITLE
[Adaptive Expressions][Adaptive Expressions Date prebuilt function][Given a UTC DateTime, formatDateTime does not convert correctly in user timezone]

### ISSUE THREAD

**Issue by ccdev1205** [microsoft/AdaptiveCards#4903]
[MS Teams][Desktop/Mobile App]
[Adaptive Cards 1.2]

# Platform
*.Net

# Version of SDK
*AdaptiveCards 2.1.0
*AdaptiveCards.Templating 1.1.0
*AdaptiveExpressions 4.10.3
*Microsoft.Bot.Builder 4.10.3

# Details
Using formatDateTime does not display the correct date equivalent in user timezone.

Given this in template:
```
{
      "type": "Input.Date",
      "id": "date",
       "value": "${formatDateTime('2020-11-30T21:00:00Z', 'yyyy-MM-dd')}"
}
```

The datepicker value in GMT+8 renders **11/30/2020** instead of **12/01/2020** in either desktop/mobile MS Teams app
![image](https://user-images.githubusercontent.com/72416404/95599861-38cf4280-0a84-11eb-84ad-a054ee3e09e0.png)

It renders properly when tried on designer though
![image](https://user-images.githubusercontent.com/72416404/95602526-a29d1b80-0a87-11eb-9215-bb8202061aaf.png)

**Comment by jwoo-msft** [comment]
@ccdev1205 Can you please post your payload both template and the data that was used?
Thank,

**Comment by ccdev1205** [comment]
Hi @jwoo-msft , here's the sample template and data payload I used.

Template:
```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "FactSet",
            "facts": [
                {
                    "title": "Given Date 1",
                    "value": "${string(dueDate)}"
                },
                {
                    "title": "Formatted Date 1",
                    "value": "{{DATE(${string(dueDate)}, COMPACT)}}"
                },
                {
                    "title": "Given Date 2",
                    "value": "${dueDateTicks}"
                },
                {
                    "title": "Formatted Date 2",
                    "value": "${formatTicks(int(dueDateTicks), 'yyyy-MM-dd')}"
                }
            ]
        },
        {
            "type": "Input.Date",
            "id": "date",
            "value": "${formatDateTime(dueDate, 'yyyy-MM-dd')}"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2"
}
```

Data:
```
{
    "dueDate": "2020-11-30T21:00:00Z",
    "dueDateTicks": "637423668000000000"
}
```

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4776
