### ISSUE TITLE
Move from XamlBuilder to ElementRegistry model

### ISSUE THREAD

**Issue by riarenas** [microsoft/AdaptiveCards#491]
In order to support parsing and rendering of custom types and better selectAction support, the UWP renderer should move away from regisering the elements it can render using an internal Dictionary<ElementType, PointerToFunctionThatReturnsXaml> to expose an element and action registry like the one used in other platforms.

This will allow hosts to explicitly disallow the rendering of individual card elements and register custom elements to be rendered.

Issue #479 illustrates the need for this and the less-than-ideal workarounds that would need to happen while this is supported.

**Comment by matthidinger** [comment]
@riarenas yayyy this is almost done :D

**Comment by riarenas** [comment]
Yeah! The API changes are there, and I will do my best to get the implementation changes to the renderer side by tomorrow. I'm going to stage the deprecation of XamlBuilder in two phases:
1. Hook up the Registration model to the existing XamlBuilder methods.
2. Refactor the XamlBuilder methods into the respective renderer classes and remove the xamlBuilder class.

**Comment by andrewleader** [comment]
Closing as stale

**Comment by shalinijoshi19** [comment]
Being tracked by #3026
