### ISSUE TITLE
[All][Accessibility] [Multi lingual accessibility support for error messages]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#4913]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] .NET HTML
- [ ] .NET WPF
- [ ] Android
- [ ] iOS
- [ ] JavaScript
- [ ] UWP

# Version of SDK
v2.0+

# Details
reference #4912 
Need accessibility support on error messages for other languages.

**Comment by jwoo-msft** [comment]
@RebeccaAnne During the sync-up, it was suggested that the accessibility string is provided by App host or Card author. I didn't get a chance to clarify which one to use.

**Comment by RebeccaAnne** [comment]
The solution we landed on for #4912 did not end up introducing a string that need to be localized here.
