### ISSUE TITLE
[Android] \n Newline character added at the beginning/end of the text is not rendering.

### ISSUE THREAD

**Issue by Gunashree-R-V** [microsoft/AdaptiveCards#4914]
# Platform

* Android

# Author or host

Microsoft Teams

# Version of SDK

1.2.10

# Details

Text beginning/ ending with newline character(\n) aren't rendering on Android.

| Desktop | Android |
|-----------|:-----------:|
| ![image](https://user-images.githubusercontent.com/28745768/95845762-37de2f80-0d68-11eb-9cb0-1666d205a2be.png)| ![image](https://user-images.githubusercontent.com/28745768/95845790-3f9dd400-0d68-11eb-80fd-e8102cfe36dd.png)| 

Components tested out are:
1. RichTextBlock with TextRun.
2. TextBlock

Here is the sample JSON for above card:

```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "text": "This is a textblock"
        },
        {
            "type": "TextBlock",
            "text": "\n\nThis is a textblock"
        },
        {
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "\n This is a rich text block"
                },
                {
                    "type": "TextRun",
                    "text": "\n This is a rich text block \n"
                }
            ]
        }
    ]
}
```

cc: @anbah34, @vikrantsingh01, @shbhadra​

**Comment by shalinijoshi19** [comment]
@jwoo-msft this seems to be related to our markdown handling and differences in various line break and newline escape character handling - Can you link this to the existing issue /discussion around this we've been having and is it also mentinoed in our Inconsistencies spec?

**Comment by golddove** [comment]
Also noticed this in our `v1.2\Scenarios\FlightDetails.json` sample:

![image](https://user-images.githubusercontent.com/4442788/99296394-b1a88380-2814-11eb-9130-851b44db8743.png)

Is this an outcome of one of the inconsistency discussions? @jwoo-msft

**Comment by jwoo-msft** [comment]
@shalinijoshi19 
Sorry, somehow I missed your comment. This isn't a markdown issue.
Here is the parsed string we get once the deserialization is done for TextBlock with the text, "\n\nThis is a textblock".
	"<p>\n\nThis is a textblock</p>"	
notice that the newline chars are preserved."text": "\n\nThis is a textblock"

**Comment by RebeccaAnne** [comment]
Scheduling for 21.02 as this is a P0 Teams ask.

**Comment by jwoo-msft** [comment]
Task Update:
`Remove Android code that pulls newlines from the rich text blocks`
cc @paulcam206, @RebeccaAnne , @golddove

**Comment by VikrantSingh01** [comment]
@jwoo-msft : Can you share the build version where this bug is fixed.
