### ISSUE TITLE
[All Platforms] Allow hero card authors to specify fallback element for when an Image element fails to load

### ISSUE THREAD

**Issue by knt36** [microsoft/AdaptiveCards#4915]
**What platform is your feature request related to? (Delete other platforms).**

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

**Is your feature request related to a problem? Please describe.**
For the teams compose extension, The hero card format used in the preview section does not support a fallback option for images when a certain image fails to load. This is an issue because the server does not know if the image urls being sent are broken or not and checking if they are broken would slow the response time of the server.
Below is the wanted behavior where a fallback image is loaded when the first image fails.
![image](https://user-images.githubusercontent.com/16567053/95872072-422a0a80-0d23-11eb-9b37-111c6a836001.png)

**Describe the solution you'd like**
In the images object, I would like a fallbackUrl field to exist where when defined, would allow the fallbackUrl leading to an image to load if the first 'url' to the primary image fails.

Below is a sample:
```
{
   "contentType": "application/vnd.microsoft.card.hero",
   "content": {
     "title": "Seattle Center Monorail",
     "subtitle": "Seattle Center Monorail",
     "text": "The Seattle Center Monorail is an elevated train line between Seattle Center (near the Space Needle) and downtown Seattle. It was built for the 1962 World's Fair. Its original two trains, completed in 1961, are still in service.",
     "images": [
       {
         "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Seattle_monorail01_2008-02-25.jpg/1024px-Seattle_monorail01_2008-02-25.jpg",
         "fallbackUrl": "https://defaultimage.jpg"
       }
     ],
    "buttons": [
      {
         "type": "openUrl",
         "title": "Official website",
         "value": "https://www.seattlemonorail.com"
       },
      {
        "type": "openUrl",
        "title": "Wikipeda page",
        "value": "https://en.wikipedia.org/wiki/Seattle_Center_Monorail"
       }
     ]
   }
}
```

**Comment by knt36** [comment]
wrong repo

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4002
