### ISSUE TITLE
It should be possible to explicitly pick action alignment and orientation on a per ActionSet basis

### ISSUE THREAD

**Issue by dclaux** [microsoft/AdaptiveCards#492]
# Problem
Currently, action alignment is controlled solely via HostConfig. While that is great for hosts that only allow actions at the card level (and prohibit the use of ActionSet), it is not practical when using ActionSet.

# Design
Add the following properties to ActionSet:

| Property | type | Description |
|---|---|---
| orientation | Orientation (**horizontal** or **vertical**) | Specifies if actions should be represented stacked horizontally or vertically. |
| stretch | boolean | When set to **true**, actions stretch across the entire width of their container and each use the same amount of space, regardless of the specified horizontalAlignment. When set to **false** (the default), horizontalAlignment is applied. |

**Comment by matthidinger** [comment]
Are these properties on the ActionSet element the developer provides or in the HostConfig section of ActionSet? In either case it seems at first glance that the prefix of "actionsX" is redundant; why not just orientation and alignment?

**Comment by dclaux** [comment]
Actually, you are totally right. ActionSet, just like any element, already has a horizontalAlignment property. What is not supported is stretch. So I the two new properties should be orientation and stretch. I'll change the above "spec."

**Comment by RebeccaAnne** [comment]
See also request for this feature in #3770
