### ISSUE TITLE
[MSTeams]Unable to reach app. Please try again. 

### ISSUE THREAD

**Issue by rithinskaria** [microsoft/AdaptiveCards#4925]
I'm trying to create a Logic App which triggers everyday at 5:30 PM and uses the connector "Post a choice of options as the Flow bot to the user" and using the comments in the response from user, I have couple of conditions and connectors.

The problem is when Teams is taking the response from user, it is showing Unable to reach app. Please try again.

![image](https://user-images.githubusercontent.com/38252976/96116511-33e81400-0f06-11eb-9cc9-ac2762d6d925.png)

I could see the Logic App is waiting for the response from user, however, it never reached the Logic App. Please advise, thanks in advance.

**Comment by matthidinger** [comment]
@dblyth-msft can you help with this one?

@rithinskaria can you please include the JSON payload used and any other details, such as the Flow Run ID so we can diagnose

**Comment by rithinskaria** [comment]
@matthidinger Sure Matt

Workflow id: /subscriptions/xxxxxxxxxxxxx/resourcegroups/EA_team_RG/providers/Microsoft.Logic/workflows/case-posting
Azure portal session id: 1e4ae0a8278348798a3b9a83255a53f8
Logic App designer session id: c24cd96d-5920-42bd-a804-a0d1a96ebab8
Logic App designer instance id: bd6a246e-245b-4f18-a860-d0d49f65dc47
Workflow run id: 08585983588901608474713790524CU12
Timestamp: Wed, 21 Oct 2020 02:40:16 GMT

I just ran this today morning and nothing changed!

**Comment by dblyth-msft** [comment]
@rithinskaria Sorry for one more request -- we actually need a Fiddler (or Chrome/Edge HAR file) for you responding to the card. Is that something you could collect for us and share? (You can mail to dblyth AT microsoft DOT com to avoid posting it here)

**Comment by dblyth-msft** [comment]
@rithinskaria nevermind, I think figured it out. Right now the headline is *not* optional, though it should be. For now you'll need to specify a Headline value, but we're fixing it so that it is truly optional.

**Comment by rithinskaria** [comment]
@dblyth-msft Yes, that resolved the issue. I wish that field came in automatically when I choose the connector. Currently, it's in additional parameter and we often tend to miss that. Thanks for your help.
