### ISSUE TITLE
[Android][MSTeams] [Bug] Adaptive card doesn't render in a case

### ISSUE THREAD

**Issue by PBO-DEV** [microsoft/AdaptiveCards#4926]
# Platform

* Android

# Details

`                                {
                                    "type": "Image",
                                    "url": "{$root.mediaURL}"
                                }`

when URL is empty the card render on Mobile so:

![image](https://user-images.githubusercontent.com/72922549/96119280-08a4fb00-0eed-11eb-828a-55157a4ddd0d.png)

**Comment by DEV-PBO-DEV** [comment]
my schema for the adaptive card:

`{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "ColumnSet",
                    "columns": [
                        {
                            "width": "stretch",
                            "type": "Column",
                            "items": [
                                {
                                    "type": "Image",
                                    "url": "{$root.tweetImage}"
                                },
                                {
                                    "type": "Container"
                                },
                                {
                                    "type": "TextBlock",
                                    "wrap": true,
                                    "text": "{$root.tweetText}"
                                },
                                {
                                    "type": "Container"
                                },
                                {
                                    "type": "Image",
                                    "url": "{$root.mediaURL}"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}`

**Comment by kathirvGitHub** [comment]
Hi, is this is an generic issue with Teams mobile when using cards and container? I am using the code below which works well in Teams desktop client but not on mobile. Please advise.

{
                    type: "AdaptiveCard",
                    body: [
                        {
                            'type': 'Container',
                            'items': [
                                {
                                    'type': 'TextBlock',
                                    'weight': 'bolder',
                                    'text': 'Batch Disposition',
                                    'isSubtle': true
                                }
                            ]
                        }
                    ],
                    'actions': [
                        {
                            'type': 'Action.ShowCard',
                            'title': 'Batch Approve',
                            'card': {
                                'type': 'AdaptiveCard',
                                'body': [
                                    {
                                        'type': 'TextBlock',
                                        'text': 'Document List'
                                    },
                                    {
                                        'type': 'Input.ChoiceSet',
                                        'id': 'erpDocumentListApprove',
                                        "style": "expanded",
                                        "isMultiSelect": true,
                                        "choices": documentListForBatchDisposition,
                                        "wrap": true
                                    },
                                    {
                                        'type': 'TextBlock',
                                        'text': 'Approval Notes',
                                        'weight': 'bolder',
                                        'size': 'large'
                                    },
                                    {
                                        'type': 'TextBlock',
                                        'text': 'Approval Reason Code:'
                                    },
                                    {
                                        'type': 'Input.ChoiceSet',
                                        'id': 'approvalReasonCode',
                                        'isRequired': true,
                                        "errorMessage": "Required input",
                                        "style": "compact",
                                        "isMultiSelect": false,
                                        "value": "approved",
                                        "choices": [
                                            {
                                                "title": "Approved",
                                                "value": "approved"
                                            },
                                            {
                                                "title": "Approved with conditions",
                                                "value": "approvedWCondtions"
                                            }
                                        ]
                                    },
                                    {
                                        'type': 'TextBlock',
                                        'text': 'Approval Comments'
                                    },
                                    {
                                        'type': 'Input.Text',
                                        'id': 'approvalComments',
                                        'placeholder': 'Looks OK to me, approved!',
                                        'style': 'text'
                                    }
                                ],
                                'actions': [
                                    {
                                        'type': 'Action.Submit',
                                        'title': 'Batch Approve',
                                        'data': {
                                            'type': `batchApproveRecords|${erpSystem}`,
                                            'erpSystem': erpSystem
                                        }
                                    }
                                ]
                            }
                        },
                        {
                            'type': 'Action.ShowCard',
                            'title': 'Batch Reject',
                            'card': {
                                'type': 'AdaptiveCard',
                                'body': [
                                    {
                                        'type': 'TextBlock',
                                        'text': 'Document List'
                                    },
                                    {
                                        'type': 'Input.ChoiceSet',
                                        'id': 'erpDocumentListReject',
                                        "style": "expanded",
                                        "isMultiSelect": true,
                                        "choices": documentListForBatchDisposition,
                                        "wrap": true
                                    },
                                    {
                                        'type': 'TextBlock',
                                        'text': 'Rejection Notes',
                                        'weight': 'bolder',
                                        'size': 'large'
                                    },
                                    {
                                        'type': 'TextBlock',
                                        'text': 'Rejection Reason Code:'
                                    },
                                    {
                                        'type': 'Input.ChoiceSet',
                                        'id': 'rejectionReasonCode',
                                        'isRequired': true,
                                        "errorMessage": "Required input",
                                        "style": "compact",
                                        "isMultiSelect": false,
                                        "value": "rejected",
                                        "choices": [
                                            {
                                                "title": "Rejected",
                                                "value": "rejected"
                                            },
                                            {
                                                "title": "Duplicate Invoice",
                                                "value": "duplicateInvoice"
                                            },
                                            {
                                                "title": "Something fishy",
                                                "value": "somethingFishy"
                                            }
                                        ]
                                    },
                                    {
                                        'type': 'TextBlock',
                                        'text': 'Rejection Comments'
                                    },
                                    {
                                        'type': 'Input.Text',
                                        'id': 'rejectionComments',
                                        'placeholder': 'Looks NOT OK to me, rejected!',
                                        'style': 'text'
                                    }
                                ],
                                'actions': [
                                    {
                                        'type': 'Action.Submit',
                                        'title': 'Batch Reject',
                                        'data': {
                                            'type': `batchRejectRecords|${erpSystem}`,
                                            'erpSystem': erpSystem
                                        }
                                    }
                                ]
                            }
                        }
                    ]
                }

**Comment by RebeccaAnne** [comment]
Templating is not currently supported in mobile, so client side templating resolution on Android will not work.
