### ISSUE TITLE
Add Id property to all elements and actions

### ISSUE THREAD

**Issue by dclaux** [microsoft/AdaptiveCards#493]
# Implementation status
- [X] TypeScript (https://github.com/Microsoft/AdaptiveCards/pull/494)
- [x] UWP
- [x] WPF
- [x] iOS
- [x] Android
- [ ] Documentation

# Problem
- Some hosts, especially those that support Action.Http, might need an easy way to correlate an action from the client to its counterpart on the server. Such hosts will likely use an Id property on actions (added after the card is received) anyway, so we might as well make it official
- Still in the context of Action.Http, where the response to a POST call might contain instructions for the host replace all or a portion of a card with new content, having an Id property available on elements would make it easy to remove an element from a card's element tree and insert a new one.

# Solution
Add the following property on all element and action types

| Property | Type | Description |
|---|---|---|
| Id | string | Uniquely identifies the element or action within a card. If duplicate Ids are used in a given card, the first occurrence "wins." |

**Comment by matthidinger** [comment]
The concept sounds good to me. Do this would _not_ be a required property then?

**Comment by dclaux** [comment]
It will be at the discretion of hosts. Some hosts might want to make the Id property of an action required, some might not. I don't think the Id property of an element would be required at all.

**Comment by tomlm** [comment]
works for me too.

**Comment by matthidinger** [comment]
@riarenas did we already add this to UWP by chance?

**Comment by riarenas** [comment]
This is done in UWP for Actions and CardElements. Should this apply to elements that only exist inside specific containers such as choices, facts and columns?

**Comment by matthidinger** [comment]
That's how it is in C# as well, since Fact and Choice are not "typed" elements which is where we added the Id property.

**Comment by dclaux** [comment]
This seems to be done across the board, closing.

**Comment by andrewleader** [comment]
Looks like this never was documented, re-opening till that's complete

![image](https://user-images.githubusercontent.com/13246069/43041692-903b9218-8d1c-11e8-870d-1914f696e756.png)

**Comment by RebeccaAnne** [comment]
This is documented in main and will go out with the next website deployment.
