### ISSUE TITLE
Video play from a time.

### ISSUE THREAD

**Issue by Threepointone4** [microsoft/AdaptiveCards#4931]
Is there a way to play a video in an adaptive card from a timestamp rather than always play from the beginning?

**Comment by vishwasgpai** [comment]
I have created a dynamic adaptive card to play different videos based on users. But is it possible to pass a seek option in some way to play the video from that time? Eg: seek=sec

**Comment by jonmill** [comment]
That isn't currently supported at this time and is not currently on our roadmap for support. Sorry about that!
