### ISSUE TITLE
Is it possible to develop a asynchronous searchable Drop-down inside adaptive cards

### ISSUE THREAD

**Issue by konagallasushmitha** [microsoft/AdaptiveCards#4936]
`Hi, we are using backend (Azure) as nodejs and frontend as reactjs(webchat botframework). Actually we have a requirement for rendering an adaptive card in which it contains a asynchronous searchable Drop-down in which it gets data from API and show it in drop-down when user types something in the input area. I have searched a lot but couldn't found anything.`

**Comment by ashishtank** [comment]
@konagallasushmitha 
This feature is planned, check this link on product board [Product board](https://portal.productboard.com/adaptivecards/1-adaptive-cards-features/c/15-input-choiceset-auto-complete)

**Comment by konagallasushmitha** [comment]
Is there any workarounds for this inside adaptive cards??

**Comment by RebeccaAnne** [comment]
This is not currently supported.
