### ISSUE TITLE
[Android][MSTeams] Empty FactSet Causes Adaptive Card to Not Render

### ISSUE THREAD

**Issue by markscottmckenna** [microsoft/AdaptiveCards#4957]
# Platform

* Android

# Author or host

Author sending bot responses through bot framework to Teams channel.

# Version of SDK

Confirmed on Teams version 1416/1.0.0.2020100901 on Android 11 (Pixel 2) 

# Details

An empty FactSet anywhere in the payload, such as in the following contrived example, causes the entire adaptive card to not display anything.

`
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "wrap":  true,
            "text": "This text block does not render on Teams/Android when the FactSet is empty."
        },
        {
            "type": "FactSet",
            "facts": []
        }
    ]
}
` 

We use templating to generate categories of data that may or may not contain anything, so our workaround is to inject a "fake" fact that states the fact that the section is empty. Otherwise the entire card fails to render anything.

I am able to "avoid" it by adding a $when clause in the template to suppress the block entirely when the facts that make up the FactSet is empty but it took me some time to figure out what wasn't working so I raised the issue here. 

Screenshot from Teams for Windows (works):

![image](https://user-images.githubusercontent.com/66265462/96927440-0b6f9500-1485-11eb-90dc-a2a8e05b8bdd.png)

Screenshot from Teams for Android

![image](https://user-images.githubusercontent.com/66265462/96927499-217d5580-1485-11eb-99c6-ec173f81b4ea.png)

**Comment by jwoo-msft** [comment]
@markscottmckenna 
This issue is already fixed and Team is working on uptaking the fix for their next sprint, end of November.
Please feel free to reopen the issue if the next update doesn't fix the issue. 
Thanks
