### ISSUE TITLE
[Javascript/iOS/Android][MS Teams] [Card components not rendering all at once]

### ISSUE THREAD

**Issue by alexwaibel** [microsoft/AdaptiveCards#4959]
# Platform

* Android
* iOS
* JavaScript

This issue is experienced on all MS Teams clients (iOS, Android, Web, and Desktop).

# Author or host

> Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.

We are an author.

> If you're an author, who are you sending cards to?

Sending cards to MS Teams via bot conversations

# Version of SDK

Project uses NuGet AdaptiveCards.Templating package v1.0.

# Details

We have constructed a status pill for our cards by combining a rectangle and two semicircles to form a pill shape. However, the different parts of the pill are rendered at different times. Since we send the card payload all at once, we expect that all parts of the card will be rendered at the same time. As it is now, these pieces render at different times which causes the layout of the card to change rapidly when initially loading which is disruptive to users.

You can access Approvals from the Teams client and create a request to see this behavior yourself.

I will edit this PR and upload a sample card for repro when given the go-ahead by my team. In the meantime, feel free to ping me on Teams for those files.

**Comment by shalinijoshi19** [comment]
@alexwaibel thanks for reporting this issue; We are now tracking this with the #4974 feature request. Resolving this as a dup of that issue at this point.
Dup #4974
