### ISSUE TITLE
[Android] Image sizing regression in several configurations

### ISSUE THREAD

**Issue by golddove** [microsoft/AdaptiveCards#4964]
# Platform

* Android

# Version of SDK

20.09

# Details

Image sizing changed in 20.09. Appears to be a regression.

Size: small, medium, large are being stretched
Size: large, stretch in a column are being shrunk/stretched incorrectly

Using the latest payload at `v1.2/Test/ImageSizing.json`

Previous behavior in `20.08`:
![sizingregress2](https://user-images.githubusercontent.com/4442788/97043237-1dfad480-1540-11eb-87fd-c7d1d2c5401f.gif)
New behavior in `20.09`:
![sizingregress3](https://user-images.githubusercontent.com/4442788/97045182-4df7a700-1543-11eb-826f-8874e7d80ef8.gif)

**Comment by shalinijoshi19** [comment]
@golddove assigned to you for investigation - pls update as you go along esp around 20.10 impact

**Comment by shalinijoshi19** [comment]
@golddove any updates on this one? What is the impact of this bug and is this something that will impact Teams scenarios? @almedina-ms can you please chime in here?

**Comment by almedina-ms** [comment]
Chiming in, it looks bad, we should fix that before our release, not even specific sizes work

**Comment by shalinijoshi19** [comment]
@golddove / @almedina-ms do we understand the issue?

**Comment by golddove** [comment]
Regression due to bumping `constaint-layout` dependency bump to `2.0.1`
