### ISSUE TITLE
[Website Schema Explorer] ?'s in schema types

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#4969]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- Website

# Details

The json used to generate the schema and schema explorer appears to use ? operators. (See for example [Container.json](https://github.com/microsoft/AdaptiveCards/blob/main/schemas/src/elements/Container.json)) Those ?'s are showing up on the website in the schema explorer, which is probably not desired.

See result at https://adaptivecards.io/explorer/Container.html
![image](https://user-images.githubusercontent.com/9091833/97223399-f187c800-178c-11eb-918b-ed54e860f89d.png)

**Comment by paulcam206** [comment]
should be tracked in #6316
