### ISSUE TITLE
[Android][UnsatisfiedLinkError] [dlopen failed for libadaptivecards-native-lib.so file]

### ISSUE THREAD

**Issue by dipja** [microsoft/AdaptiveCards#4972]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android

# Author or host

Microsoft Teams

# Version of SDK

Adaptive card sdk version 2.2.0

# Details

Upgrading to the adaptive card sdk version from 2.1.0 to 2.2.0 is leading to this issue. When a call is made to the adaptive card native library there is an error which says failed to dlopen the libadaptivecards-native-lib.so file and the app crashes.
The error observed is as below:

`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_Unwind_Resume" referenced by "/data/app/com.microsoft.skype.teams.dev-GgORJFzm38OEBdFRaSYDzQ==/lib/arm64/libadaptivecards-native-lib.so"...`

This error is NOT observed while upgrading to 2.1.0 and something which has been introduced with 2.2.0. 

Additional Info: Teams uses the adaptive card sdk by downloading the maven package through [maven feeds and artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-maven?view=azure-devops) offered by azure devops.

**Comment by dipja** [comment]
@shalinijoshi19 Please help with this one.

**Comment by shalinijoshi19** [comment]
@almedina-ms I've gone ahead and assigned this over to you. Please take a look with high priority ! thanks

**Comment by golddove** [comment]
Unable to repro on our end using a sample project while consuming the `adaptivecards-android` library from maven. Tested both `2.1.0` and `2.2.0`, neither of which presented this error for us.
