### ISSUE TITLE
No support for Actions[] in containers in C#

### ISSUE THREAD

**Issue by vrnmthr** [Microsoft/AdaptiveCards#498]
Developing on v0.5, in C# there is only a way to add selectActions to a container, and no button related Actions, although on the schema it specifies that these exist.

**Comment by dclaux** [comment]
@250blahblah in Containers, you should use the ActionSet element instead.  The actions property isn't needed.

**Comment by matthidinger** [comment]
Are you looking to set the selectAction of a Container? If so, I believe you've found a bug in our .NET impl.

If you're looking to put multiple Actions inside a Container, then as @dclaux mentions an ActionSet is correct best approach.

**Comment by 250blahblah** [comment]
Thanks for such a prompt response -- the ActionSet works excellently. I just have one request (if either of you happen to be involved in the development of AdaptiveCards): can this be added to the documentation? As of today, https://docs.microsoft.com/en-us/adaptive-cards/create/cardschema#container does not mention ActionSets. 
Thanks!

**Comment by newtux** [comment]
I think this is a schema issue as well. The schema (at least at http://adaptivecards.io/schemas/adaptive-card.json) doesn't seem to indicate what an ActionSet actually is or that actions can be added to containers.

**Comment by matthidinger** [comment]
Currently ActionSet is not an official v1.0 feature but we're exploring ways to make it work in a future release. I've filed a separate tracking here: #877
