### ISSUE TITLE
[Android][Column Rendering] Long column content shrinks auto/fixed sized columns

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#4988]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Android

# Version of SDK

main

# Details

Refer to Teams' `surveyMonkey.txt` and `imageOverlap.txt` payloads. The column with survey icon shrinks due to the long text on the right column.

Screenshot of `imageOverlap.txt` on 2.1.0 vs 2.3.1:

![image](https://user-images.githubusercontent.com/4442788/98416899-fd597100-204d-11eb-8587-539a4a48015f.png)

In Agenda.json scenario card the column content is pushing the PowerPoint logo column so much that it's not appearing

![image](https://user-images.githubusercontent.com/35784165/97510014-086f1b80-1941-11eb-815f-3067ce34c1ac.png)

the card is rendered correctly in Javascript

![image](https://user-images.githubusercontent.com/35784165/97510124-4c622080-1941-11eb-81f6-1753a0a649cb.png)

Another example:

Android:
<img width="353" alt="Screenshot 2020-07-31 at 3 30 01 PM" src="https://user-images.githubusercontent.com/8917620/89024456-c08d2800-d342-11ea-8f76-9ad51bfe3f52.png">
Desktop:
<img width="434" alt="Screenshot 2020-07-31 at 3 29 48 PM" src="https://user-images.githubusercontent.com/8917620/89024466-c420af00-d342-11ea-88cf-a82fa834b71a.png">

[ACColumnSetImageWidth.txt](https://github.com/microsoft/AdaptiveCards/files/5006405/ACColumnSetImageWidth.txt)
```
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "items": [
            {
              "type": "TextBlock",
              "size": "ExtraLarge",
              "weight": "Lighter",
              "text": "BLR"
            }
          ],
          "width": "auto"
        },
        {
          "type": "Column",
          "verticalContentAlignment": "Center",
          "items": [
            {
              "type": "Image",
              "url": "https://messagecardplayground.azurewebsites.net/assets/graydot2x2.png",
              "width": "10000px",
              "height": "2px"
            }
          ],
          "width": "stretch"
        },
        {
          "type": "Column",
          "spacing": "Small",
          "verticalContentAlignment": "Center",
          "items": [
            {
              "type": "Image",
              "url": "https://messagecardplayground.azurewebsites.net/assets/smallairplane.png",
              "height": "16px",
              "altText": "Flight to"
            }
          ],
          "width": "auto"
        },
        {
          "type": "Column",
          "items": [
            {
              "type": "TextBlock",
              "horizontalAlignment": "Right",
              "size": "ExtraLarge",
              "weight": "Lighter",
              "text": "CDG"
            }
          ],
          "width": "auto"
        }
      ],
      "height": "stretch"
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0"
}
```

**Comment by shalinijoshi19** [comment]
@almedina-ms is this a ship blocker for 20.10? @RebeccaAnne FYI
