### ISSUE TITLE
[Android][Rendering] Elements with "height: stretch" cause other elements to vertically shrink

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#4989]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Android

# Version of SDK

main

# Details

With the revert of the constraint layout bump, an issue was unearthed in v1.2/Tests/ImageSizing.json. This bug makes some images in columns to use more height space than it should, making other elements in the column  too small (in height) to be visible

![image](https://user-images.githubusercontent.com/35784165/97511301-0064ab00-1944-11eb-8d6f-113951d60353.png)

Another example:

`v1.1\Tests\ColumnSet.VerticalStretch.json`:

![image](https://user-images.githubusercontent.com/4442788/98415468-5a9ff300-204b-11eb-8350-21278084cd09.png)

**Comment by shalinijoshi19** [comment]
@golddove / @dipja is this a Teams 1.3 upgrade blocker?

**Comment by dipja** [comment]
@shalinijoshi19 / @golddove This is regression from the earlier behavior. It would be good if we can fix this. (Currently I do not have any card from Teams where height is stretch inside columns.)

**Comment by golddove** [comment]
@dipja that card is not affected by this. This bug repros when an element uses height: stretch within a column. Do you have production cards affected by this? That would help with testing.

**Comment by dipja** [comment]
@golddove I did not find any such card from known apps in Teams Microsoft tenant. There could be number of external apps which might be using this property in their respective adaptive cards which could lead to regression.

**Comment by shalinijoshi19** [comment]
@dipja since we are operating on very limited (read 1 :( ) resource for Android if we don't have known cases of Teams customer cards/scenarios that are running into this then I am going to for now remove the 1.3 blocker upgrade tag and move this out to 20.12 to allow us to focus on the first batch of identified blockers at this point --  does that sound good? ?

**Comment by shalinijoshi19** [comment]
> @dipja since we are operating on very limited (read 1 :( ) resource for Android if we don't have known cases of Teams customer cards/scenarios that are running into this then I am going to for now remove the 1.3 blocker upgrade tag and move this out to 20.12 to allow us to focus on the first batch of identified blockers at this point -- does that sound good? ?

N/m; Looks like #5061 needs this.
