### ISSUE TITLE
[Android][ChoiceSet Input] [Choiceset input (required) rendering fails inside a container]

### ISSUE THREAD

**Issue by dipja** [microsoft/AdaptiveCards#4994]
# Platform

- [ ] Android

# Author or host

Microsoft Teams

# Version of SDK

2.2.0-nightly.20.10.29.1

# Details

Choiceset input (required input) is not rendered when inside a container. Could you also check for other required inputs inside a container.

![image](https://user-images.githubusercontent.com/61967816/97620461-9df4d300-1a47-11eb-9fcc-8d7b4a6f3504.png)

[Adaptive card json 
](https://microsoft-my.sharepoint.com/:u:/p/dipja/EeIqJRbexQxOowtNW2rPSwIBFkdeZx_raGALw3DuyhsgaA)

**Comment by dipja** [comment]
@shalinijoshi19

**Comment by shalinijoshi19** [comment]
@almedina-ms assigning this to you/approving for 20.10. @RebeccaAnne FYI
