### ISSUE TITLE
[.NET HTML][Input.Choiceset - Expanded ] Request for Horizontal Orientation/Flow

### ISSUE THREAD

**Issue by sam-sam-med** [microsoft/AdaptiveCards#4998]
**What platform is your feature request related to? (Delete other platforms).**

- [x] .NET HTML
- [ ] .NET WPF
- [ ] Android
- [ ] iOS
- [ ] JavaScript
- [ ] UWP

**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to a problem.  For the "Input.ChoiceSet" card element in "Expanded" style mode (this produces radio buttons), there isn't a horizontal orientation/flow.  It only has a vertical orientation.  Many Microsoft .NET controls like webform radio button control, WPF radio button control, etc., have a horizontal orientation option to choose from.  For consistency across the board, there should be a horizontal orientation for this as well.  In addition, many third party vendors' controls have horizontal orientation as well like Telerik. 

Because there isn't a horizontal orientation but only a vertical orientation, the use of the area's real estate is wasted because there is so much unused white space.  From a UI design perspective, it may not look good with so much white space.

**Describe the solution you'd like**
For the Input.Choiceset - Expanded style mode, there should be a horizontal orientation option for the developer to choose.  This could potentially be applied to the other platforms as well.

**Describe alternatives you've considered**
N/A. 

**Additional context**

Screenshot:

![image](https://user-images.githubusercontent.com/73308101/97632740-30698800-19f0-11eb-98e5-5e80bbcd8b8d.png)

**Comment by jonmill** [comment]
We don't have the resources to do this in the next 12-18 months; we'd welcome contributions if you'd like to take on this work. If so, please re-active and we'll help get you started
