### ISSUE TITLE
Input fields inside Columns not working with Action.Submit

### ISSUE THREAD

**Issue by vrnmthr** [Microsoft/AdaptiveCards#500]
I'm experiencing problems extremely similar to those expressed in [this issue](https://github.com/MicrosAoft/AdaptiveCards/issues/432) - if I place input elements inside a Column inside a ColumnSet, upon clicking an Action.Submit button these input fields are not recognized and represented in the ouput. However, if I place this same input element straight into the Body of the card, it does work. I'm using the botframework emulator.

[This StackOverflow post](https://stackoverflow.com/questions/44388731/how-can-i-read-the-value-from-complex-adaptive-card) also explains the same problem and apparently the bug has been fixed in the HTML renderer. Any updates on when a fix might be coming to the C# .nuget package?

Opening a new issue since the previous one was closed, although the bug doesn't seem to be fixed.

**Comment by matthidinger** [comment]
Hi @vrnmthr can you please let us know if you're still seeing this issue in the latest .NET packages? Note that they have new names, we've removed the Microsoft.* prefix 

https://docs.microsoft.com/en-us/adaptive-cards/display/libraries/net-wpf
