### ISSUE TITLE
[Bug] Generated HTML button tag is missing type attribute

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/AdaptiveCards#501]
Missing `type="button"` attribute on HTML `<button></button>` tags generated for Adaptive Cards buttons causes button to fall-back to default type of `submit`.

Adaptive Cards users report that clicking on button without `type="button"` attribute causes "submit" action to unintentionally execute, and in some cases, causes page reload, which is undesirable. 

From MDN > <button> > Attributes > type:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
>submit: The button submits the form data to the server. **This is the default if the attribute is not specified**, or if the attribute is dynamically changed to an empty or invalid value.

Relates to: 
https://github.com/Microsoft/BotBuilder/issues/3146

**Comment by dclaux** [comment]
Thanks for reporting! I'll check in a fix asap.

**Comment by dclaux** [comment]
This is now fixed in the v0 and master branches.

**Comment by nwhitmont** [comment]
@dclaux Thanks for the quick response!
