### ISSUE TITLE
[.NET][Bot framework] [Background images not generating on containers when creating images for other channels via bot framework]

### ISSUE THREAD

**Issue by kandelabr** [microsoft/AdaptiveCards#5011]
# Platform

- [ ] .NET HTML
- [ ] .NET WPF

# Author or host
We are creating images using adaptive cards and send them to Facebook using Bot framework to Facebook channel

# Details

We are trying to create adaptive cards and use them in our Chatbot solution. In those cards we want to have different background colors in different containers within one adaptive card. We were planning to do this by assigning each container with its own background image containing only one color.
This way every container and all the objects inside it would have this color as a background.
This all works fine, when creating cards for MS webchat, but when we have some channel like Facebook, for which images are generated from bot framework, background images are not created, and all of them share default color. The same behavior is observed when we use library: https://www.nuget.org/packages/AdaptiveCards.Rendering.Wpf and try to render image from JSON card. 
When we use https://adaptivecards.io/designer/ and select image render option, it works as expected. 
Also if we set background image on an adaptive card level, not container, then whole card uses it as background color.

In attachment you may find adaptive card as JSON as well as image created by using it from library and from Facebook.
[backgroundimagesjson.txt](https://github.com/microsoft/AdaptiveCards/files/5475493/backgroundimagesjson.txt)
![backgroundimages json](https://user-images.githubusercontent.com/2485533/97876644-6bcfc380-1d1c-11eb-9a8d-509528949ab3.jpg)
![facebook_default_color](https://user-images.githubusercontent.com/2485533/97876647-6c685a00-1d1c-11eb-8cd3-ec6421071302.png)

EDIT: also attaching activity sent to BF
[activity.txt](https://github.com/microsoft/AdaptiveCards/files/5475574/activity.txt)

Thanks

**Comment by shalinijoshi19** [comment]
@RebeccaAnne officially marking it "Triage-Investigate" and retaining assignment to you.

**Comment by jonmill** [comment]
The .NET rendering stack is currently deprecated and is not being maintained.
