### ISSUE TITLE
[MS Teams][IPhone] [Carousal][Weird behavior with Action.Submit  title text]

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [microsoft/AdaptiveCards#5016]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] iOS

# Details
Hi team,

We have seen weird behavior for adaptive card consist of only action button on iPhone teams.

we have seen that for same adaptive card complete text on Action button in adaptive card, But some time we are getting ... (Continuation dots) for same card. please check the screenshot attached below for reference. 

**Please find the sample Adaptive card json**
 [Sample JsonTxt.txt](https://github.com/microsoft/AdaptiveCards/files/5480577/Sample.JsonTxt.txt)

**Screen Shot 1**:
![123](https://user-images.githubusercontent.com/60354515/97964788-54a5da00-1ddf-11eb-8855-accefd5bd219.jpeg)

**ScreenShot 2**:

![1234](https://user-images.githubusercontent.com/60354515/97964793-57083400-1ddf-11eb-8f9b-76441eacc1a4.jpeg)

**Comment by shalinijoshi19** [comment]
@jwoo-msft is this on your radar for fixing for 20.11? @Sujit-Gaikwad / @dipja would this be an upgrade blocker?

**Comment by RebeccaAnne** [comment]
@jwoo-msft Can you investigate this and see if you can repro and whether there is a bug to fix on our end? Thanks!

**Comment by jwoo-msft** [comment]
@RebeccaAnne 
It doesn't repro on iOS visualizer from main.
As more letters are added in, text in the button is wrapped, and is never clipped with ellipsis.
![Screen Shot 2021-09-13 at 3 04 15 PM](https://user-images.githubusercontent.com/4112696/133162567-f4780bd4-a92d-492c-a074-352801a75633.png)

**Comment by Sujit-Gaikwad** [comment]
It should not wrap the text as on other teams platform we are able see **...** (continuation dots) 
Also the both images are from same carousel and but they have different appearance do you mean it will now work as expected? We can see same UI behavior for both cards?

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4940
