### ISSUE TITLE
[MS Teams][Adaptive card] [Getting Unicode value for single quote character in selected value for drop down text]

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [microsoft/AdaptiveCards#5017]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Windows
- [ ] MAC
- [ ] Android
- [ ] iOS

# Details

Hi team,

facing issue in adaptive card having single quotes in value of adaptive card drop down. the quotes are getting converted into Unicode character after selecting or for default value
please help us on this as this will look bad to show such text in response.

please find sample json attached with:
[Sample Json .txt](https://github.com/microsoft/AdaptiveCards/files/5480847/Sample.Json.txt)
![Issue Screenshot1](https://user-images.githubusercontent.com/60354515/97979002-73629b80-1df4-11eb-8c81-3bfc1fae5adb.PNG)
![Issue Screenshot2](https://user-images.githubusercontent.com/60354515/97979007-7493c880-1df4-11eb-8780-10914c1c7ccc.PNG)

**Comment by RebeccaAnne** [comment]
@Sujit-Gaikwad We're not able to repro using the attached txt file. Please reactivate if this is still an issue for you.

![image](https://user-images.githubusercontent.com/9091833/98866571-01a4d600-2422-11eb-8711-4d89bf3f341d.png)
