### ISSUE TITLE
[Android][Accessibility] [Successful submit action puts the focus on next card/element in chat]

### ISSUE THREAD

**Issue by dipja** [microsoft/AdaptiveCards#5018]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Android

# Author or host

Microsoft Teams

# Version of SDK

2.3.0

# Details

On successful submit action, the focus goes to the next available element/card in Teams chat. The sdk currently tries to clear the focus (Util.clearFocus() ) currently on submission of an action. This is leading to focus issue. 

[Video ](https://microsoft-my.sharepoint.com/:v:/p/dipja/EXj1ACbm10lNveRytjsSdmwBtuLp0-HaPmab-TDmWeGG0g?e=1C7VjA)recording for the experience.

**Comment by golddove** [comment]
On successful submit, because we cleared focus, Android automatically moves focus to another input if there is one. In Teams' case, that is the next Adaptive Card.

Fix: don't cleat focus on successful submit.
