### ISSUE TITLE
[iOS][ChoiceSet] [choice set not rendered properly for long text]

### ISSUE THREAD

**Issue by jyoti-ms** [microsoft/AdaptiveCards#5023]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ]  iOS

# Author or host

Teams 

# Version of SDK

2.3.0

# Details
Choice set text is getting clipped and choices are getting animated on selection. Tried removing the custom choice set renderer and found out issue is there with SDK itself.
Issue is reproing in sample app with this json  [inp.txt](https://github.com/microsoft/AdaptiveCards/files/5484789/inp.txt)

Sample screenshots
|<img src="https://user-images.githubusercontent.com/72016168/98053308-4ba81d80-1e5e-11eb-8535-4978c36b3511.png" width=250> | <img src="https://user-images.githubusercontent.com/72016168/98054137-3502c600-1e60-11eb-860f-2a8bb8a34f8d.png" width=250>

**Comment by shalinijoshi19** [comment]
@jwoo-msft
