### ISSUE TITLE
[iOS][Custom Action] [ Can not send additional properties to action delegates in case of custom action]

### ISSUE THREAD

**Issue by jyoti-ms** [microsoft/AdaptiveCards#5025]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] iOS

# Author or host
Teams

# Version of SDK
2.3.0

# Details
Currently we can not build target with action element. It would be good to have build target function for `BaseActionElement` so that we can send extra properties in case of custom action to the delegate function.

**Comment by shalinijoshi19** [comment]
@jwoo-msft this one lower/normal priority to be tackled later - Are you able to articulate the workaround here pls? Thanks!
