### ISSUE TITLE
[Android] Focus on previously focused input does not scroll into view

### ISSUE THREAD

**Issue by golddove** [microsoft/AdaptiveCards#5027]
# Platform

- [ ] Android

# Version of SDK

This bug will be present once #5026 is merged.

# Details

On submit, first invalid input should receive keyboard focus, screen reader focus, and should scroll into view. However, if the input already has keyboard focus, setting focus again does not cause it to scroll into view on Android.

`v1.3/Scenarios/InputsWithValidation.json`:
![5019](https://user-images.githubusercontent.com/4442788/98052135-6600dd80-1e03-11eb-9c66-d3f63ede5b47.gif)

**Comment by shalinijoshi19** [comment]
@dipja is this bug something that will be an issue for the teams integration scenarios?

**Comment by golddove** [comment]
Will investigate in 20.12 if fixing this is possible without re-introducing issue #5019. If not possible, this will likely be closed as by design. As spec'd, scrolling to the focused input will only be done to the extent the platform supports it (e.g. on ios, we do not scroll to focused inputs).

**Comment by golddove** [comment]
@jonmill @almedina-ms this should probably be closed as by design. It is simply the default Android behavior for scrolling on focus. When we try to force it to behave in a non-default way, we introduce other issues (like #5019).

**Comment by jonmill** [comment]
That sounds like a fair assessment. Closing issue; if anyone feels otherwise, feel free to comment and let me know
