### ISSUE TITLE
[JS][Templating functionality] [isMatch AEL is not giving expected result]

### ISSUE THREAD

**Issue by niravk-microsoft** [microsoft/AdaptiveCards#5033]
# Platform

- [ ] JavaScript

# Author or host

We are using JSRenderer to render adaptive cards to website as well as we are sending adaptive cards to Outlook.

# Version of SDK

Adaptive Cards Templating Version 1.1.0

# Details

We are using isMatch AEL function. We tried to provide below regex to that and realize that we are not reaching to expected results.

E.g.
1. [0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])
2. [0-9]{2}[-|\/]{1}[0-9]{2}[-|\/]{1}[0-9]{4}
3. /\\d{4}-\\d{2}-\\d{2}/
4. ^(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])-[0-9]{4}$

Also when we utilize isMatch AEL function within $when condition it works however we noticed that if we embed isMatch with if condition, then it is not giving expected result

E.g.
1. ${if(isMatch(numberPropertyValue, '[-+]?[0-9]*\\.?[0-9]+'), formatNumber(float(numberPropertyValue), 2), numberPropertyValue)}

**Comment by shalinijoshi19** [comment]
@dclaux / @RebeccaAnne can we look into this one as well for Templating (JS + .NET resp) as this is again coming from our MSApprovals partners. Thanks!

**Comment by dclaux** [comment]
@niravk-microsoft I am not able to reproduce this using the JS versions of the templating engine and AEL (tested in the designer).

Your above expression `${if(isMatch(numberPropertyValue, '[-+]?[0-9]*\.?[0-9]+'), formatNumber(float(numberPropertyValue), 2), numberPropertyValue)}` functions as expected.

Note that your regx `[-+]?[0-9]*\.?[0-9]+` is very permissive and **does** match say "1abc0", as pictured below. Thus your `if` will probably eval to true way more than you'd want, and the overall expression will thus often not produce the desired result. My suggestion is you fix your regular expression (I haven't tested the other regular expressions you mentioned above.)

![image](https://user-images.githubusercontent.com/1334689/99097751-e86c6880-258c-11eb-9fc1-3e263a9ec65b.png)

**Comment by jwoo-msft** [comment]
@niravk-microsoft 

This is not reproducible on dotnet template
`{
"numberPropertyValue":  "30.01234"
}`

`{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "Image",
      "url": "https://adaptivecards.io/content/cats/1.png",
      "test": "${if(isMatch(numberPropertyValue, '[-+]?[0-9]*\.?[0-9]+'), formatNumber(float(numberPropertyValue), 2), numberPropertyValue)}"     
    }
  ]
}`

Expanded into as below
`{"$schema":"http://adaptivecards.io/schemas/adaptive-card.json","type":"AdaptiveCard","version":"1.0","body":[{"type":"Image","url":"https://adaptivecards.io/content/cats/1.png","test":"30.01"}]}`

cc @dclaux , @shalinijoshi19, @RebeccaAnne

**Comment by RebeccaAnne** [comment]
Per @jwoo-msft's comment above removing .NET from the title/description

**Comment by RebeccaAnne** [comment]
Please see comments above from @jwoo-msft and @dclaux. We believe this is working as expected, let us know if you have any further concerns.
