### ISSUE TITLE
[.NET HTML][Functionality] [Toggle Visibility with Expand Collapse is not working]

### ISSUE THREAD

**Issue by niravk-microsoft** [microsoft/AdaptiveCards#5034]
# Platform

- [ ] .NET HTML

# Author or host

we are sending HTML to Outlook along with Adaptive cards

# Version of SDK

AdaptiveCards.Rendering.HTML version 2.3.0

# Details

We are generating HTML from Adaptive cards using AdaptiveCards.Rendering.HTML, however we have noticed that Toggle Visibility within Adaptive cards is getting generated as HTML however the Toggle Visibility functionality is not working as expected.

**Comment by shalinijoshi19** [comment]
@niravk-microsoft is there a reason you are using our .NET HTML renderer? So heads up that we've been investigating deprecating it and it's not always uptodate with the latest features etc. @dclaux do you have an alternative to them using our .NET HTML renderer at all? Thanks

**Comment by dclaux** [comment]
@niravk-microsoft this will never work in Outlook. There is no way to achieve any kind of dynamic behavior in the HTML body of an email. Action.ToggleVisibility requires client-side JavaScript execution, and there is never any custom JavaScript allowed in traditional HTML emails.

**Comment by niravk-microsoft** [comment]
Thanks for the information. For now I am marking this as closed because if as mentioned HTML body in email does not allow JavaScript to execute in traditional email then we may not need this for now.
