### ISSUE TITLE
Adaptive Card Action.OpenURL Tracking

### ISSUE THREAD

**Issue by SharmaHarsh7** [microsoft/AdaptiveCards#5035]
# Platform

* Bot Framework
* Adaptive Card
* WebChat

# Author or host

Host.

If you're an author, who are you sending cards to?

# Version of SDK

Adaptive Card 1.2 / 1.3

# Issue

This is related to the **Action.OpenURL** button which we have in Adaptive Cards. 
When you display an Adaptive Card to a user with some links on it (Action.OpenURL), it simply open that URL in a new tab.
Bot doesn't any idea whether the link was clicked or not, this makes the tracking of the event difficult to handle specially in case of when we wants to log which link was clicked for a particular utterance.

We want some help from the Microsoft team, if they can provide an event or information from the adaptive card when a particular Action (link) is clicked.

This will be very helpful in many business scenarios where customer wants to improve their services/bot experience by collecting the data being accessed.

**Comment by jonmill** [comment]
This is up to the host application to provide Telemetry hooks to track this data; the Adaptive Cards SDK has no control over this aspect. I'll transfer this bug over to Teams for more traction

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/3804
