### ISSUE TITLE
[Sample] [LongFactSet Rendering Changed]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#5043]
# Platform
- [ ] Samples

# Version of SDK
10.20

With the update to the markdown, +space is considered as the list item of Markdown.
Past
![image](https://user-images.githubusercontent.com/4112696/98168269-30113700-1e9f-11eb-8f24-28eebd05e3ea.png)

Need to update the sample app.
Present
![Simulator Screen Shot - iPhone 8 - 2020-11-04 at 13 11 25](https://user-images.githubusercontent.com/4112696/98168430-6949a700-1e9f-11eb-97f2-f462e72d6f0e.png)

**Comment by jonmill** [comment]
Tracked by #1984
