### ISSUE TITLE
[Android][Image rendering] Image sizes are not being respected when rendering inside a column

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#5054]
# Platform

- [ ] Android

# Version of SDK

main

# Details

When images are rendered inside a column, they may shrink to allow other columns have enough space to render, this provokes behaviours as documented in #4988 , a revision must be made to verify what is the actual behaviour we want as cards as `1.2/Scenarios/FlightUpdate` expect images to shrink

**Comment by golddove** [comment]
Closing as duplicate of #4988
