### ISSUE TITLE
[Azure Bot][AdaptiveCards in Other Channels] [Adaptive Card not displayed in Directline Channel]

### ISSUE THREAD

**Issue by HebatallaTarek** [microsoft/AdaptiveCards#5058]
Hello , i am using  "Adaptive Cards Designer" to create new adaptive card for different bot channels , when i use webchat channel payload the adaptive card rendered successfully , but when i tried to render the same card on Directline channel using "Bot Framework Other Channels (Image render)" payload  the card was not displayed at all . i tried to use .Net render image using wpf but i t did not work with me too .
I am using Bot Framework v4 and .net core 2.1 
May i know reasons or  how to solve this issue , please ?
Many Thanks

**Comment by shalinijoshi19** [comment]
@HebatallaTarek can you pls share your card payload here? @dandriscoll since i am still having issues transferring issues to the botframework repositories, could you pls help route this over to the right folks? Thanks again

**Comment by jonmill** [comment]
Closing due to age and lack of response
