### ISSUE TITLE
[Android][Container rendering] [The verticalContentAlignment is not working in containers]

### ISSUE THREAD

**Issue by dipja** [microsoft/AdaptiveCards#5062]
# Platform

What platform is your issue or question related to?

- [ ] Android

# Author or host

Microsoft Teams

If you're an author, who are you sending cards to?

# Version of SDK

2.3.0

# Details
Setting the verticalContentAlignment property in containers to center/bottom is not working.

Sample json:
`{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
    "version": "1.1",	
    "minHeight": "150px",
    "body": [
        {
            "type": "TextBlock",
            "text": "I'm a regular TextBlock..."
        },
        {
            "type": "Container",
            "height": "stretch",
            "verticalContentAlignment": "center",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "But I'm centered..."
                }
            ]
        },
        {
            "type": "Container",
            "verticalContentAlignment": "bottom",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "And I'm like a footer!"
                }
            ]
        }
    ]
}`

**Comment by shalinijoshi19** [comment]
@golddove moving this back into 20.11 since this appears to be a Teams 1.3 upgrade blocker. @dipja pls confirm? Thanks
