### ISSUE TITLE
[Android][Inline Action] [Inline Action with image are rendered too big]

### ISSUE THREAD

**Issue by dipja** [microsoft/AdaptiveCards#5063]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Android

# Author or host

Microsoft Teams

If you're an author, who are you sending cards to?

# Version of SDK

2.3.0

# Details

Inline Action with image are rendered too big. [Sample json](https://microsoft-my.sharepoint.com/:u:/p/dipja/Efm9x-iZzrtDjWcbgne2Q2sB2y2SpP2hy18PHb4d0-tBMQ)

![image](https://user-images.githubusercontent.com/61967816/98556512-20dc2000-22c9-11eb-8560-e42f6c0240a5.png)

**Comment by shalinijoshi19** [comment]
@golddove I've moved this back to 20.11 since this is coming from Teams and looks to be an upgrade blocker; @dipja could you pls confirm?

**Comment by shalinijoshi19** [comment]
@golddove pls update with your investigation notes and whether this can land for 20.11. Thanks!
