### ISSUE TITLE
[All][Background Images] Add 9-grid support

### ISSUE THREAD

**Issue by Stevenic** [microsoft/AdaptiveCards#5064]
**What platform is your feature request related to? (Delete other platforms).**

- [x] .NET HTML
- [x] .NET WPF
- [x] Android
- [x] iOS
- [x] JavaScript
- [x] UWP

**Is your feature request related to a problem? Please describe.**
I'd like to be able to use an image with rounded corners to create buttons and badges. The background image for a container lets you stretch and tile an image but that won't work for images with rounded corners as it would distort them.

**Describe the solution you'd like**
I'd like to see new "9-grid" `ImageFillMode` added that will cause the image sliced into 9 pieces when stretching. This way the corners of the image can be preserved.

**Comment by jonmill** [comment]
We don't have the resources to take on this work in the next 12-18 months, but if you'd like to contribute and work on this then please reactivate 🙂
