### ISSUE TITLE
Add ability to add shapes like ellipse or rectangle

### ISSUE THREAD

**Issue by niels9001** [microsoft/AdaptiveCards#507]
Would be cool if we could add shapes to our cards as well. In this way a little graph could be made for example (couple of rectangles horizontally stacked). Maybe render it to image on the host application?

**Comment by anbare** [comment]
Hey @niels9001, cool idea, could you possibly provide some mockups of the cards you would like to create using rectangles/ellipses, so that we can visualize the idea and have a more tangible example?

Thanks!

**Comment by niels9001** [comment]
First thing that comes to mind is stuff for charts like below:

![image](https://user-images.githubusercontent.com/9866362/28979424-21d9a42c-794a-11e7-9f00-66a493a2dcb1.png)

![image](https://user-images.githubusercontent.com/9866362/28979461-3a22598e-794a-11e7-83b1-2b4feb399533.png)


Ideally SVG would be supported: this would allow extreme flexibility in terms of shapes but also stuff like icons!

**Comment by andrewleader** [comment]
Thanks niels9001, we're tracking this on our portal and is currently a candidate for 1.3: https://portal.productboard.com/adaptivecards/1-adaptive-cards-portal/c/32-svg-support
