### ISSUE TITLE
[All][Accessibility] Support to add aria properties

### ISSUE THREAD

**Issue by niravk-microsoft** [microsoft/AdaptiveCards#5077]
**What platform is your feature request related to? (Delete other platforms).**

- [ ] .NET HTML
- [ ] .NET WPF
- [ ] Android
- [ ] iOS
- [ ] JavaScript
- [ ] UWP

**Is your feature request related to a problem? Please describe.**
There is no option for host of card to add aria properties for the controls.

**Describe the solution you'd like**
Provide provision to add aria-properties to controls which will be applied while rendering controls.

**Comment by jonmill** [comment]
Duplicate of https://github.com/microsoft/AdaptiveCards/issues/4815
