### ISSUE TITLE
[UX] Unable to have two SubmitAction Buttons *and* validation

### ISSUE THREAD

**Issue by scottlovegrove** [microsoft/AdaptiveCards#5078]
# Platform

- [x] .NET WPF (#5137)
- [x] Android (#5152)
- [x] iOS (#5148)
- [X] JavaScript (#5136)
- [x] UWP (#5141)
- [x] Shared Model (#5139)
- [x] Schema (#5140)
- [ ] Merge feature branch to main (#5078)

# Author or host

Author

If you're an author, who are you sending cards to?

Own host.

# Version of SDK

2.5.0

# Details

With 1.3, input validation and `required` was added to some of the input controls, which is great. However, I'm running into a problem whereby I need multiple SubmitAction buttons on the page for different purposes, but none of them will work unless all the validation has been met.

User scenario: I create a form card with several `Input.Text` fields, at the bottom, I have a SubmitAction button with a label and id of "Submit", but I also want to offer the user a way to cancel this screen and go back to the previous screen, so I would add another SubmitAction button with a label and id of "Cancel", but the user can't do anything with the cancel button because the form validation may not be meeting the required validation criteria. 

This would apply to any additional SubmitAction buttons in the card (maybe I have a logo image with an attached SubmitAction that takes the user back to the "home" card, for example), none of these will work unless the user actually fills in all the forms.

**Comment by scottlovegrove** [comment]
Thanks for updating the spec @dclaux, I was literally just coming back to comment that I'd just discovered the `ignoreInputValidation` setting in the nodejs SDK 😄

**Comment by dclaux** [comment]
@scottlovegrove note that it's a non official feature and it might be replaced with another model - so while it can unblock you for now, just know that it might stop working at some point.

**Comment by scottlovegrove** [comment]
@dclaux as long as it is replaced with _something_ I'm OK with that.

**Comment by shalinijoshi19** [comment]
@RebeccaAnne  can you update with the details on what work will be required here on the sharedmodel platforms?

**Comment by RebeccaAnne** [comment]
> @RebeccaAnne can you update with the details on what work will be required here on the sharedmodel platforms?

Assuming the agreed upon design spec'd here: [ignoreInputValidation.md](https://github.com/microsoft/AdaptiveCards/blob/main/specs/DesignDiscussions/ignoreInputValidation.md). In the shared model itself we need to introduce the `associatedInputs` property with the values `auto` and `none`. Then each platform would need to check that property on submit. If it is `none` the code needs to skip both validating and gathering the inputs. Should be pretty straightforward.

**Comment by golddove** [comment]
@golddove working on shared model changes

**Comment by sowrabh-msft** [comment]
The proposal shared above proposes an opt-out approach to input validation, would it be good to do the opposite - opt-in for input validation? Especially in Teams, usually one button in the card would be button requiring validation. 
cc @siduppal

**Comment by dclaux** [comment]
@sowrabh-msft It's already an opt-in model, given that the `isRequired` property has to be set to true for an input to be validated. Or are you asking for something different?

**Comment by paulcam206** [comment]
this work will be tracked in https://github.com/microsoft/AdaptiveCards/tree/feature/associatedInputs

**Comment by RebeccaAnne** [comment]
Per discussion this is needed for Teams to enable input validation. We think we can make it for this release so moving back into 20.11-12 for now.

**Comment by sowrabh-msft** [comment]
@dclaux As I understand, default value if `associatedInputs` is not specified, developer needs to add `associatedInputs: "none"` to all other buttons, other than the button for which they need validation. And in case of Teams, we have buttons that open task module also work through `Action.Submit` ([Reference](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots)). I was wondering if we should have the default value as `none` instead of `all`, when `associatedInputs` is not specified, so that input validation happens when developer intentionally specifies the `associatedInputs` along with that button.

**Comment by dclaux** [comment]
@sowrabh-msft for all this to be a problem, Bot developers would have to modify their Bots to take advantage of input validation, i.e. set the `isRequired` property of at least one input to `true`. Given they have to do work to opt into input validation in the first first, it seems reasonable that at the same time they would also have to tweak those Action.Submits that open a task module to set their `associatedInputs` property to "none"?

**Comment by paulcam206** [comment]
@golddove / @jwoo-msft - how's it looking for iOS and Android implementations here? just want a gut check :)
