### ISSUE TITLE
[iOS-Android-Desktop][Parity issue] [Shared model platforms fail to render card with invalid version number]

### ISSUE THREAD

**Issue by adumrewal** [microsoft/AdaptiveCards#5080]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Android
- [ ] iOS
- [ ] UWP

# Author or host

Host - Teams

# Version of SDK

Latest main

# Details

When the card json has an adaptive card version number greater than the renderer's version number, the card is not displayed on mobile whereas desktop ignores the check and renders the card successfully.
PFA the screenshots for the 3 platform and the card json:

**iOS:**
<img width="406" alt="Screenshot 2020-11-12 at 6 09 14 PM" src="https://user-images.githubusercontent.com/8917620/98941886-2e84e600-2513-11eb-8648-a1490aa30d3e.png">

**Android:**
<img width="527" alt="Screenshot 2020-11-12 at 6 15 45 PM" src="https://user-images.githubusercontent.com/8917620/98941904-36448a80-2513-11eb-9e96-ad495b6222ed.png">

**Desktop:**
<img width="446" alt="Screenshot 2020-11-12 at 6 08 30 PM" src="https://user-images.githubusercontent.com/8917620/98941926-3cd30200-2513-11eb-8f3b-fdb52246bcd8.png">

**Card JSON:** 
[invalidVersion.txt](https://github.com/microsoft/AdaptiveCards/files/5530657/invalidVersion.txt)

**Comment by shalinijoshi19** [comment]
@adumrewal to be clear by "invalid" you are referring to a schema version that's in the right semver syntax but it's higher than what the renderer SDK currently supports, so am limiting the discussion in my comment to that specific condition for now;  This isn't going to be backported to the release/1.2 codebase either. The ask is that we match our implementation across the JS & mobile renderers in particular. @jwoo-msft this should be touched up on [here] (https://github.com/microsoft/AdaptiveCards/blob/jwoo/inconstency/specs/DesignDiscussions/Inconsistencies.md#solution-1) as well as part of renderer parsing inconsistencies.. 

- [ ] JS: we seem to perform the validation, bubble up a warning but go ahead and do a best effort rendering of the card anyways

![image](https://user-images.githubusercontent.com/20822397/98979858-bbf31680-24d0-11eb-9639-932e04cf6349.png)

- [ ] UWP/iOS/Android: These spit out the warning below and drop the card with the default fallback text:
![image](https://user-images.githubusercontent.com/20822397/98987175-c1555e80-24da-11eb-9232-aa4fe23c08e0.png)
![image](https://user-images.githubusercontent.com/20822397/98987187-c6b2a900-24da-11eb-8f67-89d61845f3d1.png)

@jwoo-msft/ @RebeccaAnne can one of you drive the general conversation on this issue across the platforms and then help offload it if needed to make the change in our SharedModel code (likely) once we determine what JS is doing is the right behavior for when the version is greater than what a host currently supports..

**Comment by adumrewal** [comment]
@shalinijoshi19 yes, you are right. The expectation as you mentioned is that both the mobile SDK and the desktop SDK should have the same behaviour for the same card payload.

**Comment by shalinijoshi19** [comment]
@RebeccaAnne heads up -- this should be a relatively easy discussion and fix i think .. Can we chat a bit about this at one of the design discussions say this week?

**Comment by anbah34** [comment]
@jwoo-msft When is this being addressed? Can we pick this one up in the next SDK release? This has resulted in inconsistencies in the past where the card renderered in desktop but not on the mobile clients because the version number isn't valid (higher than what is supported)

**Comment by jwoo-msft** [comment]
@anbah34,

Thanks, anbah34 for bringing this to our attention.

**Comment by jwoo-msft** [comment]
@RebeccaAnne & @paulcam206 
I saw the `Design Discussion` tag. Should we have this design discussion meeting or can we resolve the issue using the procedure we defined for handling missing or invalid required properties?

**Comment by anbah34** [comment]
@jwoo-msft , @RebeccaAnne Any updates on this bug?

**Comment by jwoo-msft** [comment]
gentle ping to @jonmill, @RebeccaAnne, @paulcam206

**Comment by jonmill** [comment]
This is similar to https://github.com/microsoft/AdaptiveCards/issues/6015, closing as duplicate
