### ISSUE TITLE
Javascript - validation error message is coming in blue color instead of red

### ISSUE THREAD

**Issue by RashmiMithun** [microsoft/AdaptiveCards#5081]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Author or host
Host, using adaptive cards in web application

# Version of SDK

2.4

# Issue

I am using validation for choiceset, validation is working but error message is showing in blue color instead of red
![image](https://user-images.githubusercontent.com/66737678/98943221-2c238b80-2515-11eb-9c1d-9fd39c620d80.png)

**Comment by shalinijoshi19** [comment]
@RashmiMithun can you share your card json + host config/css configuration? 
@dclaux do the validation colors get defined in our host config or via CSS?

**Comment by dclaux** [comment]
@RashmiMithun The color used for validation error messages is the `Attention` color as defined in HostConfig. The host displaying the card above has picked blue for the `Attention` color. This issue can only be solved by the host application.

**Comment by RashmiMithun** [comment]
Hi Team,
here is the card and the code to render the card using JavaScript in react application

Card :
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.3",
    "body": [
        {
            "type": "TextBlock",
            "text": "Hello !!",
            "size": "Medium",
            "weight": "Bolder"
        },
        {
            "type": "Container",
            "style": "accent",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "What was the type?"
                },
                {
                    "type": "Input.ChoiceSet",
                    "id": "call_type",
                    "style": "compact",
                    "isRequired": true,
                    "errorMessage": " required input",
                    "placeholder": "Please choose",
                    "choices": [
                        {
                            "$data": "${Survey.questions[0].items}",
                            "title": "${choice}",
                            "value": "${value}"
                        }
                    ]
                }
            ]
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Submit"
        }
    ]
}
and the card rendering code
var jsonTemplate="some data",
var jsonDate="some data"
 var template = new ACData.Template(jsonTemplate);
        var cardPayload = template.expand({
            $root: jsonData
        });
 var adaptiveCard = new AdaptiveCards.AdaptiveCard();
 adaptiveCard.onExecuteAction = function (action) { alert("Ow!"); }
 adaptiveCard.parse(cardPayload);
 let renderedCard= adaptiveCard.render();
 document.body.appendChild(renderedCard);

Note :  I have not specified any specific  CSS nor hostconfig, i am just using the above code to render the card and the output is coming like below button style is not taking and also the validation error is in blue

![image](https://user-images.githubusercontent.com/66737678/99035747-4e191e80-25a6-11eb-8dc7-1e3db2cdf4a8.png)

**Comment by shalinijoshi19** [comment]
@RashmiMithun pls see @dclaux 's response above -- it appears the host has chosen an "Attention" color definition that is blue (not our default) - @dclaux i am assuming our default is some version of red?

**Comment by RashmiMithun** [comment]
Thanks for the response @shalinijoshi19 and @dclaux
Could you guys please tell me what I have to do to get the webchat styles into my react application? 
is there a way to specify the webchat container styles into react app while rendering the card?
need to explicitly set the hostconfig?

**Comment by dclaux** [comment]
You would have to simply use WebChat as is instead of overriding its out-of-the-box HostConfig.

**Comment by RashmiMithun** [comment]
Could you please tell me how to use?

**Comment by dclaux** [comment]
Documentation on how to customize the WebChat UI is available here: https://github.com/Microsoft/BotFramework-WebChat

As a starting point though - you must have written explicit code to override out-of-the-box settings and get that blue color you don't want. Maybe start by removing that custom code?

**Comment by RashmiMithun** [comment]
I have included hostConfig  and the CSS of webchat solved the issue
