### ISSUE TITLE
[Android][Column Rendering] [The elements inside the column do not get correct type of the parent view]

### ISSUE THREAD

**Issue by dipja** [microsoft/AdaptiveCards#5083]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Android

# Author or host

Microsoft Teams

# Version of SDK

2.3.1

# Details

A `mockLayout `(parent) in `CardRendererRegistration `is sent to the element renderers in sdk code. This `mockLayout `is set to FlexboxLayout in case of columns and LinearLayout in case of other elements. Actually this `mockLayout `should follow the same as the parent container. example: When an image is placed inside a column, it should get parentLayout (mockLayout) as FlexboxLayout (currently LinearLayout). The custom renderer is unable to identify the parent container correctly and unable to set properties like gravity/justifyContent.

**Comment by dipja** [comment]
@shalinijoshi19 I have discussed this with @golddove. It would be a small condition change in the code.

**Comment by shalinijoshi19** [comment]
Thanks. @golddove pls keep this issue posted with results of your investgation. thanks

**Comment by golddove** [comment]
This should no longer be a blocker for Teams, after #5085 is merged. Nonetheless, the logic here should be fixed for future-proofing.

**Comment by shalinijoshi19** [comment]
Thanks. Moving this to 21.01 and removing the blocker tag. @dipja FYI.

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
