### ISSUE TITLE
[iOS] Input.Date renders blank despite of having "value" property set, and behaviour of Date picker is not very intuitive 

### ISSUE THREAD

**Issue by gaurav0921** [microsoft/AdaptiveCards#5088]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] iOS

# Author or host

Host on Webex Teams

# Details

To start with Input box for Input.Date renders blank despite of "value" property being set.
Sample JSON:
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "TextBlock",
                            "weight": "Bolder",
                            "text": "Adaptive Cards Sample",
                            "horizontalAlignment": "Left",
                            "wrap": true,
                            "color": "Light",
                            "size": "Large",
                            "spacing": "Small"
                        }
                    ],
                    "width": "stretch"
                }
            ]
        },
        {
            "type": "TextBlock",
            "text": "DOB",
            "wrap": true
        },
        {
            "type": "Input.Date",
            "value": "21/09/1986",
            "id": "dob"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2"
}

Screenshot to show how card renders:
![Blank Input box for Date](https://user-images.githubusercontent.com/66796976/99445407-81abce00-2943-11eb-97cb-154c9a2ab742.jpg)

Moreover, tapping on input box opens a picker at the bottom of screen with only current date, on clicking of this current date, calendar appears.  The behaviour is not very intuitive. At the beginning it appears like there is no date available in the picker for selection.
Calendar shall render on tap of input box itself, as in the case of Android.

Screenshots for how it appears on tapping input box are as follows:
![Tapping on date input box-1](https://user-images.githubusercontent.com/66796976/99445883-2fb77800-2944-11eb-91e4-3c6cca0fa99b.jpg)
![Tapping on date input box-2](https://user-images.githubusercontent.com/66796976/99445891-32b26880-2944-11eb-95a9-dc87e2ae39da.jpg)

**Comment by jwoo-msft** [comment]
@gaurav0921 as we have discussed, the value has to be in the specific format, 'YYYY-MM-DD'.
iOS 14 has changed the look of date and time picker view to the current state. Updated in PR 5016 for address the issue.
