### ISSUE TITLE
[JavaScript][Extensibility] [Min/max limit not set on number input]

### ISSUE THREAD

**Issue by aroraketan** [microsoft/AdaptiveCards#5092]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] JavaScript

# Author or host

Host: Microsoft Teams (multi-window).

# Version of SDK

JS v2.5.0.

# Details

On a custom number type input, if the limit `min`/`max` is set to `0`, it is set as `undefined` and hence the range validation is not effective.

**Comment by shalinijoshi19** [comment]
@dclaux are you able to take a look at this real quick? @golddove who;d been investigating with the Teams dev.

**Comment by dclaux** [comment]
@aroraketan given that this cannot be reproduced with the default implementation of `NumberInput`, and assuming that your custom `NumberInput`:
- Extends the base `NumberInput`
- Replaces its rendering by overriding `internalRender`

My conclusion would be that your custom control code doesn't properly set the min and max values on your replacement control. Please check that and let me know.

**Comment by dclaux** [comment]
Scratch the above - there is indeed a bug in the base `NumberInput` implementation whereas if `min` or `max` are set to 0 they are not set on the input control.

I will fix today.
