### ISSUE TITLE
[iOS][Image Rendering] Few images breaks when framework is built with Optimizations

### ISSUE THREAD

**Issue by akaashdev** [microsoft/AdaptiveCards#5096]
# Platform

- [ ] iOS

# Version of SDK

 - 2020.10 (latest master as of Oct 27th)

# Details

Few card constraints seems to be breaking when the framework is built with Optimization **-0s (Fastest and smallest)**
These cards work fine in Debug builds, i.e when built with Optimization **-0none**

#### Built with Optimization
<img alt="IMG_0089" src="https://user-images.githubusercontent.com/17749787/99647070-48747a80-2a77-11eb-95ba-dd4b061aee20.jpeg" width=240>  

#### Built with No Optimization
<img alt="IMG_0091" src="https://user-images.githubusercontent.com/17749787/99647074-49a5a780-2a77-11eb-9a0e-76428406c68d.jpeg" width=240>

**Edit:**
These can be reproduced in `ADCIOSVisualizer` as well, when compiled in **Release** configuration and run on a physical device.

[location-card.txt](https://github.com/microsoft/AdaptiveCards/files/5566037/location-card.txt)
[flight.txt](https://github.com/microsoft/AdaptiveCards/files/5566042/flight.txt)

**Comment by shalinijoshi19** [comment]
@jwoo-msft thoughts on this one?
