### ISSUE TITLE
[Android] Input.Date renders with current Date instead of date declared in "value" property

### ISSUE THREAD

**Issue by gaurav0921** [microsoft/AdaptiveCards#5097]
# Platform

- [ ] Android

# Author or host

Host on Webex Teams

# Details

While using Input.Date, card renders with input box populated with current date instead of date declared in "value" property.
Sample JSON:
{
"type": "AdaptiveCard",
"body": [
{
"type": "ColumnSet",
"columns": [
{
"type": "Column",
"items": [
{
"type": "TextBlock",
"weight": "Bolder",
"text": "Adaptive Cards Sample",
"horizontalAlignment": "Left",
"wrap": true,
"color": "Light",
"size": "Large",
"spacing": "Small"
}
],
"width": "stretch"
}
]
},
{
"type": "TextBlock",
"text": "DOB",
"wrap": true
},
{
"type": "Input.Date",
"value": "21/09/1986",
"id": "dob"
}
],
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"version": "1.2"
}

Screenshot of rendered card:
![Today's date in card rendering on Android](https://user-images.githubusercontent.com/66796976/99682696-86889300-2aa5-11eb-8e5c-c0ee357b39f2.jpg)

**Comment by shalinijoshi19** [comment]
@golddove is this something that you've had a chance to look at at all (it;s one of hte Cisco reported bugs).

**Comment by jwoo-msft** [comment]
@gaurav0921 closing as disucssed. value has to be in the specific format.
cc. @shalinijoshi19 @golddove
