### ISSUE TITLE
[Website] ToggleVisibility sample action text is not readable

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#5098]
![image](https://user-images.githubusercontent.com/1432195/99692195-e26c0100-2a3e-11eb-8e26-046c0f289c42.png)

---
* URL: https://adaptivecards.io/explorer/Action.ToggleVisibility.html

**Comment by shalinijoshi19** [comment]
@matthidinger still on your radar for fixing? Approving and retaining assignment to you. Thanks

**Comment by jonmill** [comment]
This is a test card that looks like is documented...we should move this into our test area and make a new sample card for toggling visibility
