### ISSUE TITLE
[All][Inputs] Retrieve all inputs

### ISSUE THREAD

**Issue by golddove** [microsoft/AdaptiveCards#5099]
# Platform

- [ ] .NET WPF
- [ ] Android
- [ ] iOS
- [x] JavaScript - this has always been supported in JS via the `getAllInputs()` method. Since we've introduced input validation, JS also sports a `getReferencedInputs()` on the base `Action` class which allows the retrieval of only those inputs that are referenced by a given action.
- [x] UWP

# Author or Host

Host - Cisco WebEx

# Version

SDK versions 2.x

# Details

**Describe the solution you'd like**
In order to empower hosts to implement their own data-gathering logic (instead of our heuristic - https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/input-validation#fields-to-be-validated-and-submitted), renderer SDK's should expose a way to retrieve all current values for all inputs in a card, at any time. So, on submit, a host can simply ignore the data collected by the SDK, and use this new API to choose the inputs they want.

UWP already exposes this (i.e. `RenderedAdaptiveCard.UserInputs`), but we should bring it to all platforms.

**Describe alternatives you've considered**
Another option is to add options to the submit action to control the associated inputs heuristic. However, this poses several pitfalls that need more fleshing out (e.g. indicating/surfacing to users any invalid inputs hidden within a showcard on submit). We're not yet ready to address those.

**Additional context**
Cisco is not yet confident in introducing the 2.x breaking change for data-collection behavior. They currently have this behavior on iOS and JS, but not on Android and their custom desktop renderer. In order to approve this behavior change for Android, they would like to collect telemetry and investigate the scenarios with developers to understand if the breaking change is acceptable. The time-scale of this would be in the order of months, according to Cisco.

This method would allow them to implement the legacy data-collection for now, while getting all the latest bugfixes from the 2.x renderer. When they finish investigating the new behavior, they can then remove this custom data-gathering.

**Comment by dclaux** [comment]
This has been supported from the beginning in JS.

**Comment by RebeccaAnne** [comment]
We agree to implement this API to be used temporarily to give an adjustment period to card authors to prepare for the change in behavior.

**Comment by golddove** [comment]
@RebeccaAnne as per last week's meeting, this is no longer needed
