### ISSUE TITLE
[JS][Templating] Template engine broken after change in AEL

### ISSUE THREAD

**Issue by dclaux** [microsoft/AdaptiveCards#5100]
# Platform

- JavaScript

# Description

As of version 4.10, AEL has introduced a change in the way it generates a root `concat` expression. Namely, it now always prepend an empty string constant.

This unfortunately break our templating logic.

This is a high priority issue as Search depends on it.

Because of this issue, the AEL team is now committing to providing a built-in solution to something that we've so far had to build manually in our templating engine SDKs.

**Comment by jwoo-msft** [comment]
@dclaux, I checked .NET. the issue isn't reproducible.
![image](https://user-images.githubusercontent.com/4112696/99747098-0ce5aa80-2a8f-11eb-8965-bd848520dccf.png)

**Comment by dclaux** [comment]
Great

**Comment by RebeccaAnne** [comment]
This is currently repro-ing on the latest bits so reactivating.

**Comment by RebeccaAnne** [comment]
False alarm. This is in fact working as expected so re-closing.
