### ISSUE TITLE
[Android][Rendering fallback elements] [fallback element is not rendered if parent element's isVisible property is false]

### ISSUE THREAD

**Issue by dipja** [microsoft/AdaptiveCards#5109]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Android

# Author or host

Microsoft Teams

# Version of SDK

2.3.2

# Details

Fallback element is not rendered if parent element's isVisible property is false. Same is observed in adaptive card sample app. Is this expected. (Its not how its on js sdk)
[sample json](https://microsoft-my.sharepoint.com/:u:/p/dipja/EdflLXQUvBpLiQ9fJYNyWJIBxR83r-4wAA5k5TocwpalQw?e=qrIldb)

**Comment by shalinijoshi19** [comment]
@golddove is this something you are aware of and looking into as part of the 1.3 upgrade conversations with Teams?

**Comment by golddove** [comment]
This was not considered a 1.3 blocker. @dipja, can you please confirm?

**Comment by shalinijoshi19** [comment]
@paulcam206 pls update with expected behavior fallback here (is there a link to the fallback spec we can add/reference here?) ; there seems to be a difference in behavior between JS & the rest of the shared model platforms.
Waiting to hear from @dipja before removing the "1.3 upgrade blocker tag".

**Comment by dipja** [comment]
This is not a blocker for 1.3 upgrade. To me the android behavior seems to be correct, just that its not the same as JS.

**Comment by paulcam206** [comment]
This is not currently on our roadmap.
