### ISSUE TITLE
[msTeams]Some images do not get rendered in chat, while App Studio shows them perfectly [Adaptive Cards]

### ISSUE THREAD

**Issue by fabiank0** [microsoft/AdaptiveCards#5113]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Android
- [ ] iOS
- [ ] JavaScript

# Author or host

Microsoft Teams

# Version of SDK

1.6
# Details

Some images in Adaptive Cards do not get rendered, so for instance I built an example with App Studio:

Preview from App Studio Card Editor, image gets shown as intended:
![Screenshot 2020-11-27 at 23 06 42](https://user-images.githubusercontent.com/43517763/100486676-380e7080-3105-11eb-995e-0d8f55a9171a.png)

But when sending the card to an user, no image gets shown, but rather 'undefined'
![Screenshot 2020-11-27 at 23 05 53](https://user-images.githubusercontent.com/43517763/100486657-1b723880-3105-11eb-9144-8b1601ffb760.png)

The image in question is .jpg file.

**Comment by shalinijoshi19** [comment]
@fabiank0 it might be useful if you can share some of the card json here for the cards giving you trouble. Also tagging the Teams support team here for an initial pass at this to reconcile the Appstudio vs teams chat renderering inconsistency;

**Comment by Nikitha-MSFT** [comment]
We are looking into it.

**Comment by Nikitha-MSFT** [comment]
Is your image is public? App studio will render the images which are public, It does not load the images which are in the private. Could you please try by using the public image. Try if that helps.

**Comment by fabiank0** [comment]
@Nikitha-MSFT The image is hosted on Firebase Storage, but a token is provided in the image url link, as such it is public. This error only happens with some images, most work fine, which makes this issue a bit confusing to me. 

This is the adaptive card in question, from App Studio inside Teams.

```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.1",
  "body": [
    {
      "type": "Container",
      "items": [
        {
          "type": "ColumnSet",
          "columns": [
            {
              "type":"Column",
              "items":[
                {"type":"TextBlock",
                "text":"where is the image?"
                }
              ]
            },

            {
              "type": "Column",
              "width": "auto",
              "items": [
                {
                  "size": "small",
                  "style": "person",
                  "type": "Image",
                  "url": "https://firebasestorage.googleapis.com/v0/b/clexx-eaebf.appspot.com/o/expenses%2FZANUxZljHNWZuYiUUZ8JPARqjP93%2Fthumbnails%2Fpreview-422412-1.jpg?alt=media&token=3bc1d9c6-bd86-4de1-b3ef-9ba969350079"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}


```

**Comment by Mallipriya-MSFT** [comment]
We are checking this with engineering team, we will get back to you once we got any response.

**Comment by Mallipriya-MSFT** [comment]
@fabiank0, 
Images must be at most 1024×1024. Image in the post exceeds this limit. 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/73868678/101471735-a822bf00-396d-11eb-8044-1f3fabac8592.png).

For reference check  [Cards Reference Docs](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#inline-card-images).

Could please try with smaller size image?

**Comment by fabiank0** [comment]
> @fabiank0,
> Images must be at most 1024×1024. Image in the post exceeds this limit.
> ![MicrosoftTeams-image](https://user-images.githubusercontent.com/73868678/101471735-a822bf00-396d-11eb-8044-1f3fabac8592.png).
> 
> For reference check [Cards Reference Docs](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#inline-card-images).
> 
> Could please try with smaller size image?

Thanks, this was the issue.
