### ISSUE TITLE
[.NET HTML][Extended character set] [different results in different bot channels]

### ISSUE THREAD

**Issue by MichaelBuczek** [microsoft/AdaptiveCards#5114]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] .NET HTML

# Author or host

Sending adaptive cards from a bot in MS bot framework to various channels

# Version of SDK

latest main

# Details
These are the results of reading appsettings.json in the same adaptive card in the bot framework emulator and the bot framework test environment for the app service on Azure:

This is the emulator result:
![image](https://user-images.githubusercontent.com/27769195/100541865-06052780-3247-11eb-9888-3fb29219f777.png)

This is the Azure Portal result:
![image](https://user-images.githubusercontent.com/27769195/100541900-42d11e80-3247-11eb-8e8b-f1db27286fbf.png)

This is the result in the react app (production version):
![image](https://user-images.githubusercontent.com/27769195/100541926-77dd7100-3247-11eb-9f0a-0e984b1ea442.png)

Luckily there is a way to test that the results display correctly by using the Azure test environment, but it is an extra step that really should not be required.

The content of the appsettings.json is:
  "StartButton1Text": "Problem / service",
  "StartButton1Query": "Problem / Service",
  "StartButton2Text": "Bostad/bil/förråd",
  "StartButton2Query": "Bostad, bilplats, förråd",
  "StartButton3Text": "Betalningar",
  "StartButton3Query": "Allmänna betalningsfrågor",
  "StartButton4Text": "Om Riksbyggen",
  "StartButton4Query": "Allmänt om Riksbyggen"

using "&aring" instead of "å" would of course make it display correctly in the webchat emulator, but then it would come out wrong in the other environments.

**Comment by paulcam206** [comment]
This looks to be more of a Bot Framework issue -- please open an issue in their [GitHub repo](https://github.com/Microsoft/botframework-sdk). Thanks!
