### ISSUE TITLE
[Designer] Tooltips obscure content at the top of the card payload editor

### ISSUE THREAD

**Issue by v-kydela** [microsoft/AdaptiveCards#5118]
Ordinarily when you mouse over an element's JSON property in the card payload editor, the tooltip is correctly shown sufficiently far above the text so that the text can still be read.

![image](https://user-images.githubusercontent.com/41968495/100670802-44b4e380-3314-11eb-8dc5-df9592d52c82.png)

However, when the element is near the top of the panel, the tooltip is shown in front of the text, right where the mouse cursor is. This makes it difficult to select text near the top.

![image](https://user-images.githubusercontent.com/41968495/100670188-606bba00-3313-11eb-8545-d1310a2c46f6.png)

Here are a few possible solutions:

1. Make sure the tooltip's coordinates are always somewhere out of the way
2. Make the tooltip transparent and non-selectable and allow the text behind it to be selected

**Comment by shalinijoshi19** [comment]
@dclaux thoughts? Is this something we (can) control/configure directly in the designer ?

**Comment by jonmill** [comment]
This is handled by the underlying OS, Adaptive Cards does not handle displaying the actual tooltip

**Comment by dclaux** [comment]
@v-kydela this is actually controlled by the [Monaco editor](https://github.com/Microsoft/monaco-editor). It is most likely by design, but if you feel strongly about it you could file a bug in their repository.
