### ISSUE TITLE
how to reset the form in adaptive card

### ISSUE THREAD

**Issue by RashmiMithun** [microsoft/AdaptiveCards#5120]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* JavaScript

# Author or host
host

# Version of SDK

2.4

# Issue

I am new to the adaptive cards and till now I have not tried with resetting the form. I don't have any idea how to clear the selected values in adaptive cards. Could any one please help me

**Comment by shalinijoshi19** [comment]
Hi @RashmiMithun ! Thanks for trying out AdaptiveCards. Also thanks for posting the question on [StackOverflow](https://stackoverflow.com/questions/65085690/how-to-reset-the-form-in-adaptive-card) where our MVP @DeeJayTC has already jumped right in to help you out (Thanks Tim!).  Am going ahead and closing this issue out to continue over on stackoverflow
