### ISSUE TITLE
[ReactNative]TextInput max length issue

### ISSUE THREAD

**Issue by UncleZen** [microsoft/AdaptiveCards#5122]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] React Native
# Details

There is a bug in this line of code:

https://github.com/microsoft/AdaptiveCards/blob/077e265edd1b9beaabc03997075d3c629c27abc1/source/community/reactnative/src/components/inputs/input.js#L135

Please fix it as is causing the TextInput not to enforce the max length.

**Comment by RebeccaAnne** [comment]
Fixed by #5224
