### ISSUE TITLE
Better CSS support

### ISSUE THREAD

**Issue by spanwargithub** [microsoft/AdaptiveCards#513]
While the DOM elements generated by the renderer do have default CSS  classes on them, the fact that the class name is the same and the nested nature of the generated DOM makes it quite difficult to have a concise form of overriding rules.

**Comment by jkymarsh** [comment]
Seconding this.

To expand: not only do the duplicated/reused class names make styling difficult, there are also a number of generated elements that don't contain any sort of class name at all, making them borderline impossible to target.

It'd be nice if every generated element contained a class to make styling considerably more plausible.

**Comment by dclaux** [comment]
The general idea is that you don't have to/probably shouldn't work with the generated HTML aside from putting it wherever you want in your page. The renderer own the layout. If you want to have control over the generated HTML, you can reimplement some (or all) elements to your liking.
