### ISSUE TITLE
[iOS][Crash] [App will crash when render an image]

### ISSUE THREAD

**Issue by yanweida99** [microsoft/AdaptiveCards#5132]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] iOS

# Author or host

Use Adaptive Card in my project.

# Version of SDK

 2.3.1 from CocoaPods

# Details

If the Card include an image, the app will crash when render. But the 1.2.13 version is normal.

Last Exception BackTrace: NSInternalInconsistencyException: Mutating a priority from required to not on an installed constraint (or vice-versa) is not supported. You passed priority 750 and the existing priority was 1000.
	0-4	CoreFoundation - Foundation	0x00000001ef96bef8 - 0x00000001f03079b8	__exceptionPreprocess - -[NSLayoutConstraint setPriority:]
5	AdaptiveCards	0x0000000144651c54	-[ACRImageRenderer configUpdateForUIImageView:config:image:imageView:]
6	AdaptiveCards	0x000000014467f2ac	-[ACRView observeValueForKeyPath:ofObject:change:context:]

**Comment by jwoo-msft** [comment]
@yanweida99 
Thanks for reporting the issue.
Could you please share more about your project such as use cases for AdaptiveCards in your app, and perhaps the apps' name if you could?
Also please share your payload, so I can repro from my side.

Thanks

**Comment by yanweida99** [comment]
> @yanweida99
> Thanks for reporting the issue.
> Could you please share more about your project such as use cases for AdaptiveCards in your app, and perhaps the apps' name if you could?
> Also please share your payload, so I can repro from my side.
> 
> Thanks

I just embed AdaptiveCard in my project to make a simple demo.

Payload: { "type": "AdaptiveCard", "version": "1.0", "body": [ { "type": "Image", "url": "http://adaptivecards.io/content/adaptive-card-50.png", "horizontalAlignment":"center" }, { "type": "TextBlock", "horizontalAlignment":"center", "text": "Hello **Adaptive Cards!**" } ], "actions": [ { "type": "Action.OpenUrl", "title": "Learn more", "url": "http://adaptivecards.io" }, { "type": "Action.OpenUrl", "title": "GitHub", "url": "http://github.com/Microsoft/AdaptiveCards" } ] }

All Stack Trace: 
Last Exception BackTrace: NSInternalInconsistencyException: Mutating a priority from required to not on an installed constraint (or vice-versa) is not supported. You passed priority 750 and the existing priority was 1000.
0	CoreFoundation	0x00000001ef96bef8	__exceptionPreprocess
1	libobjc.A.dylib	0x00000001eeb39a3c	objc_exception_throw
2	CoreFoundation	0x00000001ef880068	+[NSException raise:format:arguments:]
3	Foundation	0x00000001f036c3dc	-[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4	Foundation	0x00000001f03079b8	-[NSLayoutConstraint setPriority:]
5	AdaptiveCards	0x0000000147f09c54	-[ACRImageRenderer configUpdateForUIImageView:config:image:imageView:]
6	AdaptiveCards	0x0000000147f372ac	-[ACRView observeValueForKeyPath:ofObject:change:context:]
7	Foundation	0x00000001f03ddd48	NSKeyValueNotifyObserver
8	Foundation	0x00000001f03e01dc	NSKeyValueDidChange
9	Foundation	0x00000001f03dfb0c	-[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:]
10	Foundation	0x00000001f032ea38	-[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:]
11	Foundation	0x00000001f03da44c	_NSSetObjectValueAndNotify
12	Test	0x00000001073803b4	__109-[UIView(WebCache) sd_setImage:imageData:basedOnClassOrViaCustomSetImageBlock:transition:cacheType:imageURL:]_block_invoke
13	Test	0x00000001073802ac	-[UIView(WebCache) sd_setImage:imageData:basedOnClassOrViaCustomSetImageBlock:transition:cacheType:imageURL:]
14	Test	0x000000010737f420	__134-[UIView(WebCache) sd_internalSetImageWithURL:placeholderImage:options:operationKey:internalSetImageBlock:progress:completed:context:]_block_invoke.50
15	Test	0x000000010737ef7c	__134-[UIView(WebCache) sd_internalSetImageWithURL:placeholderImage:options:operationKey:internalSetImageBlock:progress:completed:context:]_block_invoke.38
16	Test	0x0000000107377524	__104-[SDWebImageManager callCompletionBlockForOperation:completion:image:data:error:cacheType:finished:url:]_block_invoke
17	Test	0x0000000107377294	-[SDWebImageManager callCompletionBlockForOperation:completion:image:data:error:cacheType:finished:url:]
18	Test	0x00000001073757f0	__65-[SDWebImageManager loadImageWithURL:options:progress:completed:]_block_invoke
19	Test	0x0000000107363428	__55-[SDImageCache queryCacheOperationForKey:options:done:]_block_invoke_2
20	libdispatch.dylib	0x00000001ef3a36c4	_dispatch_call_block_and_release
21	libdispatch.dylib	0x00000001ef3a4480	_dispatch_client_callout
22	libdispatch.dylib	0x00000001ef3509e8	_dispatch_main_queue_callback_4CF$VARIANT$mp
23	CoreFoundation	0x00000001ef8fa1b8	__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
24	CoreFoundation	0x00000001ef8f5080	__CFRunLoopRun
25	CoreFoundation	0x00000001ef8f45b4	CFRunLoopRunSpecific
26	GraphicsServices	0x00000001f1b68580	GSEventRunModal
27	UIKitCore	0x000000021c8b8bc4	UIApplicationMain
28	Test	0x0000000106431a34	main
29	libdyld.dylib	0x00000001ef3b4b90	start

**Comment by jwoo-msft** [comment]
@yanweida99 
I can't repro your issue on my end. I noticed two things; SDWebImageManager, and "NSInternalInconsistencyException: Mutating a priority from required to not on an installed constraint (or vice-versa) is not supported".
It seems that a constraint with the required priority was set on your ImageView, possibly from SDWebImageManager. AdaptiveCards renderer is installing its own constraints. Please check those constraints with the maximum priorities.

**Comment by jwoo-msft** [comment]
@yanweida99 
Closing this issue as it requires the fix externally. Please let us know if changes in AdatpiveCards is required to resolve your issue.
Thanks,
c.c @shalinijoshi19 @paulcam206

**Comment by yanweida99** [comment]
> @yanweida99
> Closing this issue as it requires the fix externally. Please let us know if changes in AdatpiveCards is required to resolve your issue.
> Thanks,
> c.c @shalinijoshi19 @paulcam206

2020-12-21 15:52:06.674813+0800 ADCIOSVisualizer[4565:1656621] completed loading elements
2020-12-21 15:52:06.688209+0800 ADCIOSVisualizer[4565:1656621] completed loading elements
2020-12-21 15:52:09.293441+0800 ADCIOSVisualizer[4565:1656621] *** Assertion failure in -[NSLayoutConstraint setPriority:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1556/Foundation/Layout.subproj/NSLayoutConstraint.m:234
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Mutating a priority from required to not on an installed constraint (or vice-versa) is not supported.  You passed priority 750 and the existing priority was 1000.'
terminating with uncaught exception of type NSException
2020-12-21 15:52:09.294451+0800 ADCIOSVisualizer[4565:1656621] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Mutating a priority from required to not on an installed constraint (or vice-versa) is not supported.  You passed priority 750 and the existing priority was 1000.'
*** First throw call stack:
(0x1ef96bef8 0x1eeb39a40 0x1ef88006c 0x1f036c3e0 0x1f03079bc 0x100be9f20 0x100cbd1b4 0x1f03ddd4c 0x1f03e01e0 0x1f03dfb10 0x1f032ea3c 0x1f03da450 0x10060a668 0x1031e7840 0x1031e8de4 0x1031f6a94 0x1ef8fa1bc 0x1ef8f5084 0x1ef8f45b8 0x1f1b68584 0x21c8b8bc8 0x10062b22c 0x1ef3b4b94)
libc++abi.dylib: terminating with uncaught exception of type NSException


I still need your help. Because I run your demo, ADCIOSVisualizer. Then touch V1.2 -> Scenarios -> FlightDetails.json. It will crash. The crash is the same as my project. 
Project: ADCIOSVisualizer
Platform: iOS
Version of SDK：2.3.1 from CocoaPods
