### ISSUE TITLE
[iOS][custom actions] [selectAction/inlineAction does not support custom actions]

### ISSUE THREAD

**Issue by jyoti-ms** [microsoft/AdaptiveCards#5133]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] iOS

# Author or host

Microsoft Teams

# Version of SDK

2.3.1

# Details

Custom/unknown actions implemented by developers doesn't work with selectAction/inlineAction. 
Suppose we have added a custom action named action.execute and we are using this action inside inlineAction/selectAction, it is not supported by adaptive card SDK currently.
[test_selectaction.txt](https://github.com/microsoft/AdaptiveCards/files/5652463/test_selectaction.txt)
[inlineAction.txt](https://github.com/microsoft/AdaptiveCards/files/5652464/inlineAction.txt)

**Comment by jwoo-msft** [comment]
fixed via https://github.com/microsoft/AdaptiveCards/pull/5070

**Comment by sowrabh-msft** [comment]
Does this fix both inline action and select action @jwoo-msft? Also is it possible we have the same issue on other platforms as well?
cc: @shalinijoshi19
