### ISSUE TITLE
Close accessibility exceptions

### ISSUE THREAD

**Issue by productboard-ac** [microsoft/AdaptiveCards#5138]
# Accessibility exceptions

- [ ] Media closed captions
- [ ] Action's with icons need a accessible title
- [ ] Official table support

**Comment by productboard-ac** [comment]
Link to feature: https://adaptivecards.productboard.com/feature-board/planning/features/6371021

**Comment by matthidinger** [comment]
Closing as unnecessary. This was meant to be an aggregate of the exceptions but we already have the individual ones filed
