### ISSUE TITLE
[C#] Input.Date : Default to today's date?

### ISSUE THREAD

**Issue by dharmeshtailor** [microsoft/AdaptiveCards#5142]
Is it possible to assign today's date to Input.Date control? So that whenever user open the email, the control defaults to today's date?

**Comment by anna-dingler** [comment]
@dharmeshtailor We are considering adding `today` as an accepted input for the `value` property. `today` would assign the today's date to the Input.Date on initial render.

Would this resolve your issue?

**Comment by anna-dingler** [comment]
Hi @dharmeshtailor! Can you provide more context as to whether the above change to Input.Date would resolve your issue? Thank you!

**Comment by dharmeshtailor** [comment]
> Hi @dharmeshtailor! Can you provide more context as to whether the above change to Input.Date would resolve your issue? Thank you!

Hi @anna-dingler sorry for delayed response. I have moved on from the company to a new workplace. But I am sure, this would resolve the issue we had then.

**Comment by anna-dingler** [comment]
@paulcam206 @licanhua @jwoo-msft @dclaux How do we want to move forward with this?

**Comment by dclaux** [comment]
We can't default to an actual value, as that would break the existing behavior (input are "not set" unless a value is specified in the payload, Input.Toggle beng the only exception). We could however, for example, allow the card author to specify the value of the Input.Date as "today".

**Comment by licanhua** [comment]
@JeanRoca Is there any customer complains Input.Date because of timezone? If yes, can this help them to resolve their issue. 
@anna-dingler If there is no team to adopt the change, it's better to cut it.

**Comment by dclaux** [comment]
@licanhua this feature wouldn't help with time zones. To correctly support time zones, the value of a date input needs to be expressed as a full offsetted date/time, e.g. `2022-04-06T00:00-8:00` and not be converted to UTC on the client before being sent to the Bot.

**Comment by licanhua** [comment]
For example, we add a feature convertEmptyToTodayDateWhenSubmit. No matter what the server time zone it is, client use local timezone and sends today (04-06-2022) to the server. It may workaround some time zone issue.

**Comment by dclaux** [comment]
There's no need to introduce a new feature if we just allow the default value of the Input.Date to be expressed as "today":
```json
{
    "type": "Input.Date",
    "value": "today",
    ...
}
```

**Comment by anna-dingler** [comment]
We recommend resolving this issue using `utcNow()`. Below are some examples of setting the Input.Date and Input.Time `value` to the current date using this function.

```
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5",
    "body": [
        {
            "id": "test1",
            "type": "Input.Time",
            "value": "${convertFromUTC(utcNow(), 'Pacific Standard Time', 'HH:mm')}"
        },
        {
            "id": "test2",
            "type": "Input.Date",
            "value": "${convertFromUTC(utcNow(), 'Pacific Standard Time', 'yyyy-MM-dd')}"
        },
        {
            "id": "test3",
            "type": "Input.Date",
            "value": "${formatDateTime(utcNow(), 'yyyy-MM-dd')}"
        }
    ]
}
```
