### ISSUE TITLE
Outlook Actionable Message - Version Supported

### ISSUE THREAD

**Issue by stuel22** [microsoft/AdaptiveCards#5145]
Does anyone know when version 1.1+ will be supported for Outlook Actionable Messages?

**Comment by Greg-Hitchon** [comment]
Would love to get an update on this as well!

**Comment by paulcam206** [comment]
@dclaux / @matthidinger - care to jump in here?

**Comment by Greg-Hitchon** [comment]
From the community call today the guidance (from my understanding) is that the 1.4 version will be rolled out to Outlook sometime in the next month.

**Comment by rahulamlekar** [comment]
I've looped in someone on the Outlook team to provide more context. Sorry for the delay!

**Comment by rahulamlekar** [comment]
Here's the update from the Outlook PM - Outlook Mac, Web, iOS, and Android are on v1.4 already, you can create cards in v1.4 today and expect it to work on these platforms. Outlook desktop will follow in the next few months (they're working on it). 

Also Outlook went straight from v1.0 -> v1.4 so your card will need to target one of these two versions.

**Comment by stuel22** [comment]
Great, thanks for the info!

**Comment by Greg-Hitchon** [comment]
I also asked this on a Community Call, and my understanding was that all the other platforms essentially use the Javascript sdk and so can be supported "easily" whereas the desktop uses a different renderer which causes this issue. 

Also from my understanding they are working to at some point in the future make everything run off the same web based tooling, but there are no timelines on that so the desktop support might continue to be painful for a while.
