### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by spanwargithub** [microsoft/AdaptiveCards#515]
We would like to have an ability where we can specify different layout for different screen resolutions/viewport sizes in the Schema itself.

**Comment by andrewleader** [comment]
Thanks for this feedback, is responsive UI support still an active request on Adaptive Cards, something that you need?

Can you share any pictures or examples of what specifically you're trying to achieve? Additional requirements and examples help us make sure we build the right features for you :)

Please re-open if this is still an active request and share some more details!
