### ISSUE TITLE
Disable submit button/loading on the card on submit

### ISSUE THREAD

**Issue by RashmiMithun** [microsoft/AdaptiveCards#5168]
# Platform
React Web Application
What platform is your issue or question related to? (Delete other platforms).
- [ ] JavaScript

# Author or host

Host

What version are you using? Ex: NuGet 1.0.2, or latest main, etc...

# 2.4

I have a form while submitting the card I want submit button to be disable or need a kind of loading for the card so that can avoid continues  submission of form
Could any one please help me

**Comment by shalinijoshi19** [comment]
@RashmiMithun can you please share your sample json here ? Also in the future you are welcome to engage with us and the community on the [Discussions Page](https://github.com/microsoft/AdaptiveCards/discussions)

**Comment by RashmiMithun** [comment]
> @RashmiMithun can you please share your sample json here ? Also in the future you are welcome to engage with us and the community on the [Discussions Page](https://github.com/microsoft/AdaptiveCards/discussions)

**Comment by RashmiMithun** [comment]
@shalinijoshi19 here is the json 

{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "Custom"
        }
    ],
    "actions": [
        {
            "type": "Action.Alert",
            "title": "Click me",
            "text": "Hello world!"
        }
    ]
}
