### ISSUE TITLE
Fixed height cards should clip partial content

### ISSUE THREAD

**Issue by matthidinger** [Microsoft/AdaptiveCards#517]
# Implementation status
- [x] TypeScript
- [x] UWP
- [x] WPF
- [x] iOS
- [x] Android
- [ ] Documentation

# The problem
Currently fixed height cards like Timeline and Tiles will show partial text at the bottom of the card, which isn't desirable

![image](https://user-images.githubusercontent.com/1432195/28630360-f1cfdd90-71de-11e7-8738-3d0014a1fa3e.png)

**Comment by dclaux** [comment]
What is the desired behavior? Is the goal to preserve the bottom padding at all cost (even at the cost of cutting a line of text in the middle horizontally) or is it that the text block in the above example is trimmed to three lines (probably even 2 actually)?

**Comment by anbare** [comment]
I believe the desired behavior would be that the text block in the example becomes trimmed to 3 lines (or possibly 2 lines). That's how adaptive XML tiles function today.

So no text randomly cut off, and padding of at least the host config's padding amount is preserved (potentially even more padding would be visibly present depending on font size and where the line breaks end up)

**Comment by dclaux** [comment]
Very hard to do. No automatic/CSS-based way to do it. I would have to somehow compute the remaining space, determine that this particular text block is the element that overflows and calculate/set its maxlines property. Unless someone else wants to do it, this will be a limitation of the HTML renderer.

**Comment by matthidinger** [comment]
Ropening for tracking. It has to be done in uwp

**Comment by khouzam** [comment]
This has been implemented
