### ISSUE TITLE
[iOS][Package Management] XCFramework support

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#5171]
**What platform is your feature request related to? (Delete other platforms).**

- [ ] iOS

**Describe the solution you'd like**
Apple introduced a new binary framework, XCFramework. We should support this as the Teams mobile is going to mandate it, and XCFramework has great features and works well with our current initiative for support Swift Package Manager, Apple's artifact distributor.

**Comment by golddove** [comment]
From https://github.com/microsoft/fluentui-apple :

> As of this writing, the version of Swift Package Manager shipped with the latest Xcode does not support packages that require resource bundles. As Fluent UI Apple does require resource bundles, we do not currently support Swift Package Manager.

Does this apply to us?

**Comment by jwoo-msft** [comment]
> From https://github.com/microsoft/fluentui-apple :
> 
> > As of this writing, the version of Swift Package Manager shipped with the latest Xcode does not support packages that require resource bundles. As Fluent UI Apple does require resource bundles, we do not currently support Swift Package Manager.
> 
> Does this apply to us?

@golddove No, it doesn't.
XCFramework does not need SPM to work.
