### ISSUE TITLE
[Sample Card][Input Validation / Regex] [Change Regex pattern]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#5181]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Sample Cards

# Details
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.3/Scenarios/InputFormWithLabels.json
```json
"label": "Your name (Last, First)",
"isRequired": true,
"regex": "^[A-Z](a-z)+ [A-Z](a-z)+( ([A-Z][a-z]+))*$",
"errorMessage": "Please enter your name in the specified format"
```
regex here makes no sense. especially the group, `(a-z)+` since it matches literal 'a-z'.

**Comment by shalinijoshi19** [comment]
Dup of #5201
