### ISSUE TITLE
[SmokeTest][Sample][Accessibility] Hard to read text in the Solitaire.json sample for BotFramework host config

### ISSUE THREAD

**Issue by shalinijoshi19** [microsoft/AdaptiveCards#5182]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] .NET HTML
- [ ] .NET WPF
- [ ] Android
- [ ] iOS
- [ ] JavaScript
- [ ] UWP

# Details
At least on JS the BotFramework-WebChat host config has the text in the tetxblock element with hard to read contrast; Confirmed the other host configs seem to be fine. Interestingly running Accessibility Insights against that page causes a crash in Edge :S 
![image](https://user-images.githubusercontent.com/20822397/101969438-2e8f0900-3bd9-11eb-9553-14311ece15e0.png)

**Comment by RebeccaAnne** [comment]
This sample was removed in https://github.com/microsoft/AdaptiveCards/pull/5253.
