### ISSUE TITLE
[JavaScript] Network type URL's don't render properly in adaptive cards

### ISSUE THREAD

**Issue by atishayv** [microsoft/AdaptiveCards#5191]
# Platform

- [ ] JavaScript

# Author or host

Host Name : Microsoft Search

# Version of SDK

"adaptivecards": "2.0.0-rc.0"

# Details

The link for below adaptive card doesn't render properly : 

```
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "TextBlock",
            "text": "[abc.docx](\\\\MININT-O7QDU1Q.fareast.corp.microsoft.com.microsoft.com\\IgniteDemoShare\\abc.docx)",
            "wrap": true
        }
    ]
}
```

On inspecting. the href is not correct : 
```
href="%5CMININT-O7QDU1Q.fareast.corp.microsoft.com%5CIgniteDemoShare%5Cabc.docx"
```
![image](https://user-images.githubusercontent.com/13940020/102353720-76de6a80-3fcf-11eb-8d5f-00323d2888dd.png)

Ideally it should be : 
```
href="\\MININT-O7QDU1Q.fareast.corp.microsoft.com\IgniteDemoShare\abc.docx"
```

**Comment by atishayv** [comment]
@matthidinger , @dclaux Can you please look into it ?

**Comment by shalinijoshi19** [comment]
@atishayv can you please upgrade to the [latest JS 2.4.6 RTM SDK](https://www.npmjs.com/package/adaptivecards) and check if te issue still persists in the latest version ? Thanks.

**Comment by shalinijoshi19** [comment]
This is not repro'ing on our [designer](https://adaptivecards.io/designer):

![image](https://user-images.githubusercontent.com/20822397/104669716-7ea53380-568f-11eb-9413-a33e4e3cfeb6.png)

**Comment by atishayv** [comment]
@shalinijoshi19 Sorry for not following up on this before. 
The issue was that the href of rendered link is not correct. I am able to reproduce it on designer.
If you see the the below screenshot : 
![image](https://user-images.githubusercontent.com/13940020/105466081-bf1d3680-5cb9-11eb-9fe3-1a0a3f281ccd.png)

even though the html is rendering properly. The link for anchor element is not correct. 

On inspecting. the href is  :

```href="%5CMININT-O7QDU1Q.fareast.corp.microsoft.com%5CIgniteDemoShare%5Cabc.docx"```

 it should be :

```href="\\MININT-O7QDU1Q.fareast.corp.microsoft.com\IgniteDemoShare\abc.docx"```

**Comment by atishayv** [comment]
Can we please reopen this issue and find a resolution ?

**Comment by dclaux** [comment]
@atishayv can you confirm you guys use Markdown-it? Not sure it is the culprit, but it's quite possible.

**Comment by atishayv** [comment]
Yes we do use markdown it

**Comment by dclaux** [comment]
@atishayv as far as I can tell, Markdown-it (Markdown in general) doesn't support those network paths. Also - and I might be mistaken - isn't that network path syntax Windows specific?

In any case, there isn't much AC can do here.

**Comment by paulcam206** [comment]
Hey @atishayv -- have you tried this using `file://machine-name/share`?

**Comment by paulcam206** [comment]
> Hey @atishayv -- have you tried this using `file://machine-name/share`?

Actually, it looks like won't work either.

**Comment by RebeccaAnne** [comment]
This is not supported by Markdown-It so it is not something we support.
