### ISSUE TITLE
[Outlook Desktop][Input.Number] [Input.Number does not accept floating numbers in Outlook for O365]

### ISSUE THREAD

**Issue by obshrog** [microsoft/AdaptiveCards#5192]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Windows Outlook

# Author or host

Author

Organization

# Version of SDK

Actionable Emails using Adaptive Cards 1.0

# Details

Input.Number does not accept floating numbers in Outlook for O365. Outlook for Web does permit decimal numbers, while Outlook on the desktop only allows digits.

**Comment by shalinijoshi19** [comment]
@dclaux who on Outlook should take this bug - What's the process to route these over again? @obshrog FYI that Outlook uses a pretty old custom renderer based on 1.0 schema. We don't directly own that bit of logic but we'll try to get you the right folks over on that side for additional follow up. Thanks for your patience with this...

**Comment by RebeccaAnne** [comment]
Please contact onboardoam@microsoft.com for outlook support. Thanks!
