### ISSUE TITLE
[JavsScript ] Required Input validation not working properly on "Input Form with Labels" sample 

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#5201]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [X] JavaScript

# Details
http://adaptivecards-ci.azurewebsites.net/samples/InputFormWithLabels.html

Loaded this card on the website, and the Name and Email fields are marked required, but input validation did not fire. Possibly because they are created with data binding expressions?

![image](https://user-images.githubusercontent.com/1432195/102551845-08ec7e80-4075-11eb-9c3b-18ecf28325fc.png)

**Comment by shalinijoshi19** [comment]
@matthidinger the regex seems to be busted for that sample for starters; I was *just* on it as well! 

![image](https://user-images.githubusercontent.com/20822397/102553001-fd9a5280-4076-11eb-86a3-f873a215d243.png)

Here's the fixes to the regex for basic email + name formats:

![image](https://user-images.githubusercontent.com/20822397/102553055-160a6d00-4077-11eb-9ea9-6eab3b233274.png)
