### ISSUE TITLE
[Teams][Consistency] [Markdown for bold not working on Android]

### ISSUE THREAD

**Issue by lindach167** [microsoft/AdaptiveCards#5208]
![AndroidBold](https://user-images.githubusercontent.com/29580478/102678548-3103dc80-415e-11eb-9027-fed4935a17a5.png)
[markDownBoldFactSet.txt](https://github.com/microsoft/AdaptiveCards/files/5718793/markDownBoldFactSet.txt)

# Platform

- [ ] Android

# Author or host

Host - Teams Mobile

# Version of SDK

1.2

# Details

Using markdown for bold in Fact value does not work on Android. See screenshot where Android renders **120 hours** instead of bolding 120 hours. This does not repro on iOS or Web where the same card renders bold for 120 hours as expected.

**Comment by golddove** [comment]
This is using our 1.2.x renderer. Already fixed in 2.x:

![image](https://user-images.githubusercontent.com/4442788/105402747-d09d0a80-5bf5-11eb-88d9-b4576068cb5b.png)
