### ISSUE TITLE
Collision Problem with Id when iterating in Visual Studio with .NET C#

### ISSUE THREAD

**Issue by samoZacc** [microsoft/AdaptiveCards#5212]
When creating a loop with templating, I also create an Input.Text type for each of my iterations, (imagine looping answers, and then comment fields as input for each of those answers). The problem here is that Input.Text requires a unique ID, and that is a problem if you want to save the result to an object in the backend. If I do a $index, the object cannot be mapped and thus saved in my DB. 

There is a way to make it work the old way, by writing the card in C#. But this includes writing a new card for each step so there are no conflicts, and putting all the cards in a foreach loop. Finally you could put all the cards in a List of Attachments, but the final look is horrible. I don't see a way to use Templating with binding to make my solution work.

When writing the card in the online Designer I don't get a collision due to iterating, the submit button maps the fields properly for every generated button (unless I manually write (iterate) all the fields that need to be iterated, then I get the duplicate id error from the validator). When using Visual Studio I get: **Collision detected for id '{Id name goes here}'** 

**Packages**: "AdaptiveCards 2.4.0", "AdaptiveCards.Templating 1.1.0"

---
* URL: https://adaptivecards.io/explorer/Input.Text.html

**Comment by jwoo-msft** [comment]
@samoZacc 
Hi,

You can use AEL concat function.
Suppose you have "id": "${}",
You can have a unique id by appending $index, for example, "id": "${concat('aString', $index)}"
Can you try this, and let me know how it goes?
Thanks

**Comment by samoZacc** [comment]
That is not binding the data. It needs to be the same text as the property to bind. Nothing new is added to the DB if you do that. That solves only the bug, but doesn't solve the problem. "id" : "propertyName + index" doesn't work

**Comment by jwoo-msft** [comment]
> hey @jwoo-msft
> That is not binding the data. It needs to be the same text as the property to bind. Nothing new is added to the DB if you do that. That solves only the error, but doesn't solve the problem. "id" : "propertyName + index" doesn't work

@samoZacc 
I'm not sure. I'm following you. You mentioned that your issue is duplicated ID, and I mentioned a way to generate a unique id. Can you share your template & data?
