### ISSUE TITLE
[Web Channel] Update activity is not working for Adaptive card

### ISSUE THREAD

**Issue by MUKESHNITP** [microsoft/AdaptiveCards#5215]
# Web channel

We are working on web channel. We have some feature, where we need to update the adaptive card. We are trying to update the adaptive card using the updateActivity method by response activity id but it is giving the process activity error. We also tried from postman using put method, but it is giving the error that "This channel does not support this operation"[PFA]. This updateActivity logic work fine for teams channel.

We got to know from below link update activity don't work on web channel.
Link - https://stackoverflow.com/questions/57402058/how-to-update-an-existing-activity-in-webchat

Could you please let us know that can we update the adaptive card on web channel ?

Please find the below screen shot of error from postman - 
![image](https://user-images.githubusercontent.com/35325927/102973085-2c567400-4522-11eb-9f08-730570f57a49.png)

**Comment by MUKESHNITP** [comment]
Could you please update about this ?

**Comment by vijhhh2** [comment]
I am also facing the same issue in my project. Are there any alternatives or workarounds for this issue?

**Comment by MUKESHNITP** [comment]
could you please any one update about this ?

**Comment by dclaux** [comment]
This would be best reported to the [WebChat repo](https://github.com/microsoft/BotFramework-WebChat) It's not an Adaptive Card issue. Please create an issue there then close this one.
