### ISSUE TITLE
[Android][Rendering] [Column Width Issue]

### ISSUE THREAD

**Issue by manujai** [microsoft/AdaptiveCards#5216]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Android

# Author or host

Webex

# Version of SDK

2.4.0 for Android

# Details
Column width issue (collapsing) in a column set between columns with images. 
Please refer to the screenshots below. 

2.4.0 Version
![Screenshot 2020-12-23 at 7 03 05 PM](https://user-images.githubusercontent.com/69314716/103000674-802c8180-4551-11eb-9485-56a65a699c7c.png)

1.2.11 Version 
![Screenshot 2020-12-23 at 7 02 49 PM](https://user-images.githubusercontent.com/69314716/103000650-760a8300-4551-11eb-9ff0-0816fdedac90.png)

The expectation is to have the card similar to the one rendered in 1.2.11. 

JSON payload for the card: 
[column_width_json.docx](https://github.com/microsoft/AdaptiveCards/files/5735457/column_width_json.docx)

**Comment by golddove** [comment]
@manujai the Android renderer seems to match the web renderer:

![image](https://user-images.githubusercontent.com/4442788/103018756-b9460100-4513-11eb-93e7-25ed222fab3a.png)

Columns with width "stretch" take up remaining space, while width "auto" requires enough space for its content. When there is insufficient card width, the two images determine the size of the left/right columns in this example, so the middle column gets only the remaining width. The previous behavior did not match the web renderer. This behavior matches our spec.

**Comment by golddove** [comment]
Closing for now, but please feel free to reopen if there are any concerns.
