### ISSUE TITLE
[Adaptive Cards][Input.Number trims first and last digits]

### ISSUE THREAD

**Issue by Ms-fernandes** [microsoft/AdaptiveCards#5218]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Adaptive Cards
- [ ] Outlook

# Author or host

Author

Organization

# Version of SDK

Actionable Emails using Adaptive Cards 1.0

# Details

Strange but Input.Number trims first and the last digits.

{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Input.Number",
            "placeholder": "Placeholder text",
            "id": "test"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0",
    "actions": [
        {
            "type": "Action.Http",
            "title": "Action.Http",
            "body":"{{test.value}}"
        }
    ]
}

Input: 23434
Output: 343

**Comment by shalinijoshi19** [comment]
@dclaux another ActionableMessage bug -- who/how can we route these correctly again?

**Comment by jonmill** [comment]
Please send the bug to the Actionable Messages team:  onboardoam@microsoft.com
