### ISSUE TITLE
Input.Date Adaptive card in IE-Adaptive card option Input.Date not populating in IE browser of Bot Framework

### ISSUE THREAD

**Issue by LakshummaC** [microsoft/AdaptiveCards#5219]
Hi Team,

We encountered an issue while developing through bot framework i.e. When we use Input.Date adaptive card form display issue occurs when the webchat window open in IE browser.

Client is looking for solution and the resolution is needed on high demand. Looking for help on this issue.

Thanks,

**Comment by shalinijoshi19** [comment]
@LakshummaC FYI that Msft has [officially deprecated support for IE11](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666) as of Nov 2020 so very curious to understand their end-end scenario here ? @dandriscoll what is the "IE Browser of BotFramework" again?  @dclaux thoughts?
