### ISSUE TITLE
intergrate i frame 

### ISSUE THREAD

**Issue by Idayachelvan** [Microsoft/AdaptiveCards#522]
How we can include iframes in adaptive card ?? is there any possibilities

**Comment by matthidinger** [comment]
Hi @Idayachelvan, we are using Github issues to track bugs and feature discussions. For general questions please use stackoverflow.com and tag the question with "adaptive-cards" and we'll try and help there. Please do include some sample code and additional information to help us help though

**Comment by danmarshall** [comment]
@Idayachelvan you would have to fork the project and implement a new schema item.
