### ISSUE TITLE
How to invoke the bot when ShowCard action button is clicked?

### ISSUE THREAD

**Issue by gb2793** [microsoft/AdaptiveCards#5222]
On an adaptive card sent in Teams Conversation, I want to invoke a bot when ShowCard action button is clicked. The bot receives the information like message Id, user Id, etc. I will invoke my service to perform validations and return the data applicable for the user. I will wrap this data in an Adaptive card and respond to the bot. The Teams client will show the returned adaptive card.

Is this feasible? Can you please share document links or code pointers?
---
* URL: https://adaptivecards.io/explorer/Action.ShowCard.html

**Comment by RebeccaAnne** [comment]
This is not currently on our roadmap. Take a look at the 1.4 Refresh/Action.Exectue feature to see if they help address your scenario.
