### ISSUE TITLE
Is there an action when an adaptive card is being displayed to the users in Teams Conversation?

### ISSUE THREAD

**Issue by gb2793** [microsoft/AdaptiveCards#5223]
I am looking for support of an action, say CardAction.OnRender. I will invoke C# bot, evaluate the information that needs to be shown in the card based on user Id, message Id, etc. The bot will respond with the AdaptiveCard response object with appropriate fields and values.

This is super useful where we have privilege based access for users imposed in our external system. This would also save us from compliance sign-offs where our data will not be stored in Teams datastore and is always fetched from our system by OnRender action.

If this action is not supported, then what is the recommended approach to solve this problem?

---
* URL: https://adaptivecards.io/explorer/AdaptiveCard.html

**Comment by gb2793** [comment]
Is there an expiry date for adaptive or other cards sent in Teams?

**Comment by DeeJayTC** [comment]
@gb2793 Suddenly you can only send a card but you don't really know if a customer has seen it yet or if it was displayed on any of his devices. The only callback to the c# bot is happening when a user interacts with the card in forms of actions. (ie action.submit) you would need to add an action like "I have read this" to get a confirmation. 

There also technically is no expiry date for a card. If someone submits an action on a card that is like a year old or something it will still send a call to your bot. You have to handle that sort of yourself.

**Comment by jonmill** [comment]
Context-aware cards in Teams was released at Build 2021: https://mybuild.microsoft.com/sessions/512470be-15d3-4b50-b180-6532c8153931?source=sessions
