### ISSUE TITLE
Support for Antlr4 version 4.8.0

### ISSUE THREAD

**Issue by Morhpeuss** [microsoft/AdaptiveCards#5225]
Hello,

I am not able to use this library after upgrade the Microsoft.Bot.Builders.* libraries to version 4.11.1 because these libraries refer to Antlr4 version 4.8.0 and you are using Antlr4.runtime version 4.6.6.,

Could you please upgrade this reference?

Thanks.

**Comment by jwoo-msft** [comment]
@Morhpeuss,
Sure, the work is currently underway.

**Comment by Morhpeuss** [comment]
Hello, any progress?

**Comment by jwoo-msft** [comment]
> Hello, any progress?

It's tracked for 21.02 which means it will be part of this month's release that will occur at the end of each Month.

**Comment by Morhpeuss** [comment]
> > Hello, any progress?
> 
> It's tracked for 21.02 which means it will be part of this month's release that will occur at the end of each Month.

@jwoo-msft  Thank you

**Comment by Mikhail2k15** [comment]
When will this fix available on nuget.org?

**Comment by jwoo-msft** [comment]
@Mikhail2k15 
It was planned for the last Friday, but it was delayed 1 or 2 days.
