### ISSUE TITLE
[Microsoft Teams Desktop][Accessibility - Usability] [MS Teams Adaptive card Multi select UX different in pop out app to normal app]

### ISSUE THREAD

**Issue by prasanthrpadharthi** [microsoft/AdaptiveCards#5226]
# Platform

- MS Teams Desktop

# Author or host

Host - Adaptive card on MS Teams looks different from normal to pop out app

# Version 

Adaptive card 1.0 

# Details

MS Teams Adaptive card Multi-select UX different in pop out app to normal app. Same adaptive card designed using adapticard.io designer looks different from normal desktop MS Teams app to MS Teams desktop pop out app of the chat window.

Normal MS Teams window - Multiselect looks fine with checkboxes to multi select 

![image](https://user-images.githubusercontent.com/36985649/103547809-d8636c00-4edf-11eb-8b58-20475b2f6479.png)

Same chat window in pop out app mode, Multiselect control checbox is missing, rather it works in tag control mode which is a usability issue 
![image](https://user-images.githubusercontent.com/36985649/103547863-e913e200-4edf-11eb-8413-51352479e5c1.png)

**Comment by prasanthrpadharthi** [comment]
Hi Team,

Any idea if this is an issue or any workaround to solve this issue?

**Comment by shalinijoshi19** [comment]
@prasanthrpadharthi can you please share your sample json with us? Also are you sending your card into Teams via an offline workflow like Bots or something? Are you able to repro this on our [designer](https://adaptivecards.io/designer) that uses the same renderer as Teams desktop (albeit a newer version of it)..

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/3511

**Comment by jonmill** [comment]
Moving to the Teams repo as it is a bug in Teams
