### ISSUE TITLE
[MS teams] Adaptive card image partially rendered in MS Teams

### ISSUE THREAD

**Issue by hdmiimdh** [microsoft/AdaptiveCards#5228]
I'm generating dynamic images and include them as part of the adaptive card, the images are relatively small only 60kb, when I reply with the image for the first time, it's partially shown until I scroll up or leave the conversation I assume that triggers native update, as soon as image is cached it's loaded properly, the problem appears only with the first render

```
{
    "type": "AdaptiveCard",
    "version": "1.2",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "body": [
        {
            "type": "TextBlock",
            "text": "Any text",
            "wrap": true
        },
        {
            "type": "Image",
            "url": "https://806168b00b02.ngrok.io/myimage"
        }
    ]
}
```

<img width="525" alt="Screen Shot 2020-12-17 at 10 57 14 AM" src="https://user-images.githubusercontent.com/27004732/103633874-5c0c6f80-4f57-11eb-8d1f-77313b12f489.png">

This is critical for us since we rely on the images while interacting with the bot, very annoying and questionable

https://stackoverflow.com/questions/65336959/adaptive-card-image-partially-rendered-in-ms-teams

**Comment by shalinijoshi19** [comment]
@siduppal  how does the image loading work here again - Isnt it the host app that actually downloads the actual image and performs the action in the callback? I dont see this issue repro on our designer for eg.. ?

**Comment by Manish-MSFT** [comment]
@stressedoutt : We have already created a bug for this issue and shell inform you once the fix is arrived.

**Comment by paulcam206** [comment]
@Manish-MSFT - can you paste a bug link here so we can track? Thanks!

**Comment by Trinetra-MSFT** [comment]
@paulcam206 : Sure, here is the Bug Id : [1443280](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1443280/),
This is still under investigation , We will let you know once it got fixed

**Comment by orenbenmeir** [comment]
Any update or ETA?

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/3510

**Comment by Nikitha-MSFT** [comment]
Bug is Resolved now, we have tested this at our end. If you still face any issue please feel free to reopen the issue

**Comment by orenbenmeir** [comment]
Still seeing the same issue on Mac client
