### ISSUE TITLE
[Android][BotFramework] [Adaptive card does not render in Teams Bot app, works fine on Desktop app]

### ISSUE THREAD

**Issue by kiranbhadani** [microsoft/AdaptiveCards#5237]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Android

# Microsoft Teams

# Version of SDK

Nuget 2.4.0

# Details
Microsoft Teams Bot - Adaptive card not displaying in android mobile app, it works fine in desktop app, json as below, also other card for list of records works, is that something to with empty text columns? Checked with 'adaptivecards.io' not issues reported.

`{
                "type": "AdaptiveCard",
                "body": [
                    {
                        "items": [
                            {
                                "columns": [
                                    {
                                        "width": "stretch",
                                        "items": [
                                            {
                                                "color": "accent",
                                                "horizontalAlignment": "center",
                                                "size": "large",
                                                "text": "johnlastiri",
                                                "weight": "bolder",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            },
                                            {
                                                "horizontalAlignment": "center",
                                                "size": "small",
                                                "style": "person",
                                                "url": "https://urlp.asm.skype.com/v1/url/content?url=https%3a%2f%2fapp.skypointcloud.com%2fdist%2fimg%2fuser.png",
                                                "height": "auto",
                                                "type": "Image"
                                            }
                                        ],
                                        "type": "Column"
                                    }
                                ],
                                "type": "ColumnSet"
                            }
                        ],
                        "type": "Container"
                    },
                    {
                        "items": [
                            {
                                "columns": [
                                    {
                                        "width": "30",
                                        "items": [
                                            {
                                                "text": "CustomerId",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    },
                                    {
                                        "width": "65",
                                        "items": [
                                            {
                                                "color": "accent",
                                                "text": "1efdbc00-3787-460e-8561-1d705294f016",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    }
                                ],
                                "type": "ColumnSet"
                            },
                            {
                                "columns": [
                                    {
                                        "width": "30",
                                        "items": [
                                            {
                                                "text": "FirstName",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    },
                                    {
                                        "width": "65",
                                        "items": [
                                            {
                                                "color": "accent",
                                                "text": "john",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    }
                                ],
                                "type": "ColumnSet"
                            },
                            {
                                "columns": [
                                    {
                                        "width": "30",
                                        "items": [
                                            {
                                                "text": "LastName",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    },
                                    {
                                        "width": "65",
                                        "items": [
                                            {
                                                "color": "accent",
                                                "text": "lastiri",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    }
                                ],
                                "type": "ColumnSet"
                            },
                            {
                                "columns": [
                                    {
                                        "width": "30",
                                        "items": [
                                            {
                                                "text": "FullName",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    },
                                    {
                                        "width": "65",
                                        "items": [
                                            {
                                                "color": "accent",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    }
                                ],
                                "type": "ColumnSet"
                            },
                            {
                                "columns": [
                                    {
                                        "width": "30",
                                        "items": [
                                            {
                                                "text": "DateOfBirth",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    },
                                    {
                                        "width": "65",
                                        "items": [
                                            {
                                                "color": "accent",
                                                "text": "2008-01-0700:00:00",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    }
                                ],
                                "type": "ColumnSet"
                            },
                            {
                                "columns": [
                                    {
                                        "width": "30",
                                        "items": [
                                            {
                                                "text": "Gender",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    },
                                    {
                                        "width": "65",
                                        "items": [
                                            {
                                                "color": "accent",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    }
                                ],
                                "type": "ColumnSet"
                            },
                            {
                                "columns": [
                                    {
                                        "width": "30",
                                        "items": [
                                            {
                                                "text": "Email",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    },
                                    {
                                        "width": "65",
                                        "items": [
                                            {
                                                "color": "accent",
                                                "text": "john_lastiri@edwardsllc.com",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    }
                                ],
                                "type": "ColumnSet"
                            },
                            {
                                "columns": [
                                    {
                                        "width": "30",
                                        "items": [
                                            {
                                                "text": "Telephone",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    },
                                    {
                                        "width": "65",
                                        "items": [
                                            {
                                                "color": "accent",
                                                "text": "0866516312",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    }
                                ],
                                "type": "ColumnSet"
                            },
                            {
                                "columns": [
                                    {
                                        "width": "30",
                                        "items": [
                                            {
                                                "text": "PostCode",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    },
                                    {
                                        "width": "65",
                                        "items": [
                                            {
                                                "color": "accent",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    }
                                ],
                                "type": "ColumnSet"
                            },
                            {
                                "columns": [
                                    {
                                        "width": "30",
                                        "items": [
                                            {
                                                "text": "StreetAddress",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    },
                                    {
                                        "width": "65",
                                        "items": [
                                            {
                                                "color": "accent",
                                                "text": "746jeremyfields",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    }
                                ],
                                "type": "ColumnSet"
                            },
                            {
                                "columns": [
                                    {
                                        "width": "30",
                                        "items": [
                                            {
                                                "text": "City",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    },
                                    {
                                        "width": "65",
                                        "items": [
                                            {
                                                "color": "accent",
                                                "text": "sparks",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    }
                                ],
                                "type": "ColumnSet"
                            },
                            {
                                "columns": [
                                    {
                                        "width": "30",
                                        "items": [
                                            {
                                                "text": "State",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    },
                                    {
                                        "width": "65",
                                        "items": [
                                            {
                                                "color": "accent",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    }
                                ],
                                "type": "ColumnSet"
                            },
                            {
                                "columns": [
                                    {
                                        "width": "30",
                                        "items": [
                                            {
                                                "text": "Country",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    },
                                    {
                                        "width": "65",
                                        "items": [
                                            {
                                                "color": "accent",
                                                "text": "usa",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    }
                                ],
                                "type": "ColumnSet"
                            },
                            {
                                "columns": [
                                    {
                                        "width": "30",
                                        "items": [
                                            {
                                                "text": "Headshot",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    },
                                    {
                                        "width": "65",
                                        "items": [
                                            {
                                                "color": "accent",
                                                "wrap": true,
                                                "type": "TextBlock"
                                            }
                                        ],
                                        "type": "Column"
                                    }
                                ],
                                "type": "ColumnSet"
                            }
                        ],
                        "type": "Container"
                    }
                ],
                "version": "1.0"
            }`

https://stackoverflow.com/questions/65590775/microsoft-teams-bot-adaptive-card-not-rendering-in-mobile-app-android

**Comment by shalinijoshi19** [comment]
@golddove can you try the json listed above and also [here](https://jsfiddle.net/yaorm2en/) on our Visualizer app to see if it will repro? 
@VikrantSingh01 / @lindach167 is this a known issue on the Teams mobile app side would you know?

**Comment by linda167** [comment]
@shalinijoshi19 this is not a known issue I have seen reported. I think there may be some issues with the markup for how the card JSON is crafted, it does not send a card if I paste the JSON as a new adaptive card in App Studio.

**Comment by kiranbhadani** [comment]
I am able to solve it, problem is null values in data, it does not produce json "text" property, replacing null values with empty string works

**Comment by RebeccaAnne** [comment]
Closing per above comment.
