### ISSUE TITLE
[iOS][Extensibility] Non-existent custom properties are sent as "null"

### ISSUE THREAD

**Issue by jscalo** [microsoft/AdaptiveCards#5244]
# Platform

iOS

# Author or host

Host

# Version of SDK

2.4.6

# Details

In the `ACRBaseCardElementRenderer.render()` hook, when the `acoElem` doesn't have any additional properties, instead of being nil as expected, it's a string: "null". This is contrary to convention on Swift and Obj-C where the lack of something would normally be nil. Further, there's no mention of this in the documentation which implies that it will be a dictionary.

**Comment by jwoo-msft** [comment]
@jscalo , thanks for reporting the issue. I will take a look at it. thanks

**Comment by jwoo-msft** [comment]
@jscalo 
Hello,
You need to create a resolver and register it with the registration.
Examples for a resolver can be found in [ADCResolver.h](https://github.com/microsoft/AdaptiveCards/blob/main/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ADCResolver.h) and [ADCResolver.m](
https://github.com/microsoft/AdaptiveCards/blob/main/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ADCResolver.m).
Main protocol that needs to be implemented is 
`- (UIImageView *)resolveImageViewResource:(NSURL *)url`
The method should return a UIImageView asynchronously. By assigning the image to the image view once the image become available will notify the renderer and render the image in the AdaptiveCard view via KVO.

The registration example is [here](https://github.com/microsoft/AdaptiveCards/blob/deae52bb889e22f63aac137876bc4a5a89d96899/source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m#L172).
When registering, you register the resolver for each url's scheme as desired as shown in below.
`    [_resolvers setResourceResolver:resolver scheme:@"https”]; `

Thank you

**Comment by jscalo** [comment]
Thanks @jwoo-msft ! (But I think this meant to go into #5252 ? )
