### ISSUE TITLE
[iOS][Rendering] backgroundImage not showing on Container

### ISSUE THREAD

**Issue by jscalo** [microsoft/AdaptiveCards#5252]
# Platform

iOS

# Author or host

Host

# Version of SDK

2.4.6

# Details

No image appears when setting `backgroundImage` on a Container type.

e.g.:

```
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "Container",
            "backgroundImage": "https://messagecardplayground.azurewebsites.net/assets/Mostly%20Cloudy-Background.jpg",
            "items": [
                {
                    "type": "TextBlock",
                    "size": "ExtraLarge",
                    "text": "Some Text!",
                    "wrap": true
                }
            ]
        }
    ]
}
```

Result:

![image](https://user-images.githubusercontent.com/2917357/104213011-7a60e800-53fb-11eb-8621-9c415d0ce633.png)

**Comment by jwoo-msft** [comment]
@jscalo 
Hi,
I tried your payload in the sample app. It worked for me.

![Simulator Screen Shot - iPhone 12 Pro - 2021-01-11 at 15 58 40](https://user-images.githubusercontent.com/4112696/104252082-0425ab00-5426-11eb-8300-b56c6feb36c7.png)

Could it be possible that you may need to set a resource resolver in your app?
Thanks

**Comment by jscalo** [comment]
Sounds like it. This is the first I've heard of resource resolvers. Can you point me to where that is documented? I've looked and couldn't find it.
