### ISSUE TITLE
[JavaScript][Action.Submit associatedInputs property values are case sensitive]

### ISSUE THREAD

**Issue by bbullock-trustquay** [microsoft/AdaptiveCards#5260]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] JavaScript

# Author or host

I'm both an author and a host. I author the Adaptive Card template and data JSON in a C# .NET desktop application and render it in a web application.

# Version of SDK

C# .NET - NuGet 2.4.0
JavaScript - NPM 2.6.0

# Details

The Adaptive Cards Schema documentation states that the Action.Submit associatedInputs property accepts values "Auto" and "None" when in fact these values are case sensitive and should be lowercase.

https://adaptivecards.io/explorer/Action.Submit.html

![image](https://user-images.githubusercontent.com/69152251/104304934-f32b7700-54c3-11eb-8640-dd221370da19.png)

**Comment by shalinijoshi19** [comment]
@RebeccaAnne can you take a look please? Thanks

**Comment by RebeccaAnne** [comment]
This shouldn't be case sensitive, although it is true that using "None" rather than "none" doesn't work in the Javascript renderer today.
