### ISSUE TITLE
[Javascript][Accessibility - Focus outline is getting hidden]

### ISSUE THREAD

**Issue by ananddidwania** [microsoft/AdaptiveCards#5266]
# Platform

- [ ] JavaScript

# Author or host

Host Name : Microsoft Search

# Version of SDK

"adaptivecards": "2.0.0-rc.0"

# Details

Focus outline on anchor element is getting hidden when focusing that element.
![image](https://user-images.githubusercontent.com/44603844/104424639-a7e99500-55a5-11eb-9531-332b01bba581.png)

This is causing because .ac-TextBlock class adding property "overflow: hidden" and that hides the focus outline as well.
The possible fix would either to remove the overflow from .ac-TextBlock class or to add outlin-offset: -1px for the anchor element when focus.

**Comment by diduanand** [comment]
@matthidinger, @dclaux Can you please look into it ?
cc - @atishayv

**Comment by shalinijoshi19** [comment]
@diduanand can you please upgrade to the latest 2.4.x series of the renderer to see if this is still an issue for you? We've made a bunch of accessibility fixes since the rc was released.

**Comment by diduanand** [comment]
@shalinijoshi19 Can you please tell me which version of rendered the https://adaptivecards.io/designer/ is using. Would be great if you can tell how we can also check that.

**Comment by jonmill** [comment]
Closing due to lack of responses...if this is still a problem, please re-open and we'll engage. Thanks!
