### ISSUE TITLE
[Platform][Broader Feature Request Category if applicable] Title

### ISSUE THREAD

**Issue by sazarghani** [microsoft/AdaptiveCards#5268]
**What platform is your feature request related to? (Delete other platforms).**

- [ ] JavaScript

We use "botframework-directlinejs" (0.11.6) in our Angular 8 Web UI to render the direct line chat window. We use Adaptive Cards extensively, and it is important for us to somehow highlight the "clicked on" buttons on all adaptive cards permanently, so that the user can see what button he/she had clicked on during the whole conversion. Unfortunately, we could not find any possibility to do that.

One Idea is: If we could add an id to each Adaptive Card, or better each button, we could record each click action, correspond it to the correct card, and change the styling of the clicked button. This requires to override the default adaptive card renderer in the Angular app. We know one can override the "attachmentMiddleware" and manipulate the card json content before rendering. But how can we change the renderer or rendered element?  

An alternative idea is to access the html element after it is rendered and displayed, but because there is no id, we cannot make sure we get the correct card.

Any better/other idea is much appreciated.

**Comment by jonmill** [comment]
@dclaux - is there a way to get this scenario to work through native styling?

**Comment by jonmill** [comment]
Closing due to lack of responses. If this is still an issue, please re-open and we'll engage. Thanks!

**Comment by sazarghani** [comment]
I just saw "Closed because of lack of response", well I did not get any question from you, or did I missed something?  Or does that mean you implemented something for this and I can test? Yours,

**Comment by jonmill** [comment]
Apologies - each element in an adaptive card supports the `id` field, so you should be able to use the ID field to track which button was last clicked and apply CSS styles to that element. I hope this helps!

**Comment by sazarghani** [comment]
thank youfor yor response. That is right, problme is, the id is not in the rendered html element, the renderer simply igonres it. I do not know hot chnge this beaviour, or use my own rederer. Yours,

**Comment by dclaux** [comment]
@sazarghani you might be using an old version of the SDK. Newer versions stamp the element Id on the generated DOM element.

If you render the cards yourself (I can't tell from your original posting) then you can also simply handle the card's onExecuteAction event, which will give you the `action` object that is being executed, and from there you can get its associated DOM element via the `renderedElement` property.

**Comment by sazarghani** [comment]
thank you very much i will test it
