### ISSUE TITLE
[iOS][Rendering] Column width is ignored, generates auto layout errors

### ISSUE THREAD

**Issue by jscalo** [microsoft/AdaptiveCards#5269]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] iOS

# Author or host

Host

# Version of SDK

2.4.6

# Details

When setting a column's width, the width is not respected and a bunch of auto layout errors or logged to the console.

E.g.:

```
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "Container",
            "style": "emphasis",
            "backgroundImage": "https://messagecardplayground.azurewebsites.net/assets/Mostly%20Cloudy-Background.jpg",
            "minHeight": "400px",
            "items": [
                {
                    "type": "Container",
                    "minHeight": "380px"
                },
                {
                    "type": "ColumnSet",
                    "columns": [
                        {
                            "type": "Column",
                            "width": "180px",
                            "items": [
                                {
                                    "type": "Container",
                                    "style": "accent"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
```

In the designer the result looks like this (correct):

<img width="437" alt="image" src="https://user-images.githubusercontent.com/2917357/104484266-b5dfeb80-558e-11eb-94a1-301c339c3694.png">

But in iOS the result looks like this (the column is full width):

![image](https://user-images.githubusercontent.com/2917357/104484602-13743800-558f-11eb-8e5b-bb55fd5c5bd8.png)

Here are the auto layout errors:

```
2021-01-13 10:57:38.076820-0600 SFx[3588:1252348] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x281111450 ACRColumnView:0x102117500.width == 180   (active)>",
    "<NSLayoutConstraint:0x2811112c0 H:|-(0)-[UIStackView:0x1021171f0]   (active, names: '|':ACRColumnSetView:0x102116e20 )>",
    "<NSLayoutConstraint:0x281111310 H:[UIStackView:0x1021171f0]-(0)-|   (active, names: '|':ACRColumnSetView:0x102116e20 )>",
    "<NSLayoutConstraint:0x281110b90 H:|-(20)-[UIStackView:0x102115ee0]   (active, names: '|':ACRColumnView:0x102115cf0 )>",
    "<NSLayoutConstraint:0x281110be0 H:[UIStackView:0x102115ee0]-(20)-|   (active, names: '|':ACRColumnView:0x102115cf0 )>",
    "<NSLayoutConstraint:0x281114320 H:|-(20)-[UIStackView:0x10202fdf0]   (active, names: '|':ACRView:0x10202f240 )>",
    "<NSLayoutConstraint:0x281114370 H:[UIStackView:0x10202fdf0]-(20)-|   (active, names: '|':ACRView:0x10202f240 )>",
    "<NSLayoutConstraint:0x281114140 ACRView:0x10202f240.width == 375   (active)>",
    "<NSLayoutConstraint:0x2811134d0 'UISV-alignment' ACRColumnView:0x102115670.leading == ACRColumnSetView:0x102116e20.leading   (active)>",
    "<NSLayoutConstraint:0x281113430 'UISV-alignment' ACRColumnView:0x102115670.trailing == ACRColumnSetView:0x102116e20.trailing   (active)>",
    "<NSLayoutConstraint:0x281113020 'UISV-canvas-connection' UIStackView:0x1021171f0.leading == ACRColumnView:0x102117500.leading   (active)>",
    "<NSLayoutConstraint:0x281113070 'UISV-canvas-connection' H:[ACRColumnView:0x102117500]-(0)-|   (active, names: '|':UIStackView:0x1021171f0 )>",
    "<NSLayoutConstraint:0x281113390 'UISV-canvas-connection' UIStackView:0x102115ee0.leading == ACRColumnView:0x102115670.leading   (active)>",
    "<NSLayoutConstraint:0x2811133e0 'UISV-canvas-connection' H:[ACRColumnView:0x102115670]-(0)-|   (active, names: '|':UIStackView:0x102115ee0 )>",
    "<NSLayoutConstraint:0x281113700 'UISV-canvas-connection' UIStackView:0x10202fdf0.leading == ACRColumnView:0x102115cf0.leading   (active)>",
    "<NSLayoutConstraint:0x281113750 'UISV-canvas-connection' H:[ACRColumnView:0x102115cf0]-(0)-|   (active, names: '|':UIStackView:0x10202fdf0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x281111450 ACRColumnView:0x102117500.width == 180   (active)>
```

**Comment by jwoo-msft** [comment]
@jscalo,

thanks for reporting the issue. The reason is that the payload has one single column and its width is set to 180 while the parent's width is set to 400 intrinsically by the background image and the parent's view's height bing 400. AdaptiveCards uses a stack view, and since there is one single column inside the stack view that is not 400, so UIKit breaks the constraint that sets 180. 
A workaround is adding an empty column as below.
`
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "Container",
            "style": "emphasis",
            "backgroundImage": "https://messagecardplayground.azurewebsites.net/assets/Mostly%20Cloudy-Background.jpg",
            "minHeight": "400px",
            "items": [
                {
                    "type": "Container",
                    "minHeight": "380px"
                },
                {
                    "type": "ColumnSet",
                    "columns": [
                        {
                            "type": "Column",
                            "width": "180px",
                            "items": [
                                {
                                    "type": "Container",
                                    "style": "accent"
                                }
                            ]
                        },
                        {
                            "type": "Column"
                        }
                    ]
                }
            ]
        }
    ]
}
`

**Comment by jscalo** [comment]
Excellent, thanks for the workaround @jwoo-msft. For the sake of platform parity do you think it would be worth having the framework detect this scenario (there being only a single Column with a fixed width) and adding a spacer view to the UIStackView proactively?

**Comment by jwoo-msft** [comment]
@jscalo,  Thanks for bringing this up & I like your suggestion, and I will include it in the next available cycle.
