### ISSUE TITLE
[iOS][Framework] ACRRegistration.setActionRenderer() takes an opaque NSNumber instead of an enum

### ISSUE THREAD

**Issue by jscalo** [microsoft/AdaptiveCards#5271]
# Platform

iOS

# Author or host

Host

# Version of SDK

2.4.6

# Details

In ACRRegistartion.h there is:

```
- (void)setActionRenderer:(ACRBaseActionElementRenderer *_Nullable)renderer cardElementType:(NSNumber *_Nonnull)cardElementType;
```

It's not documented (even in the header) what cardElementType is supposed to be. It's just an opaque NSNumber. In the visualizer sample app there's a comment about this:

> // enum will be part of API in next iterations when custom renderer extended to non-action
> // type - tracked by issue #809

But issue #809 has already been closed.

**Comment by shalinijoshi19** [comment]
@jwoo-msft do you have context on this issue ?
