### ISSUE TITLE
[Teams][Input Validation] Input.Number floating point support

### ISSUE THREAD

**Issue by golddove** [microsoft/AdaptiveCards#5278]
# Platform

- [ ] Android
- [ ] SharedModel 
- [ ] iOS

See also #5308(.NET) and #5309(UWP)

# Author or host

Host - Teams

# Version of SDK

20.12 releases

# Details

There is platform inconsistency on acceptance of floating-point values for Input.Number.

* JS renderer accepts floating-point in the card payload (i.e. Input.Number.min, Input.Number.max, Input.Number.value) and accepts floating-point user input as valid.
* iOS renderer does not accept floating-point in card payload, but accepts floating-point user input
* Android renderer does not accept floating-point at all
* UWP renderer does not accept floating-point in card payload, but accepts floating-point user input. Additionally, min/max comparisons can be incorrect due to flooring.
* .NET Xceed renderer does not accept floating-point at all

This needs to be made consistent. The correct solution seems to be to match the JS renderer on all platforms.

**Comment by golddove** [comment]
Seems to be mitigated in Teams Android 1.3 upgrade by making the change in subclass of ac numberinputrenderer and numberinputhandler. Continuing to track this for fix in our library / other platforms.

**Comment by RebeccaAnne** [comment]
Android and shared model changes will make 21.01

**Comment by RebeccaAnne** [comment]
Spun off .NET and UWP into separate issues. This bug now tracks only the shared model and Android changes.

**Comment by golddove** [comment]
Need to fix iOS, too.
