### ISSUE TITLE
Review and streamline CI/Tooling backend settings

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#5281]
# Details
Review and streamline CI/Tooling backend settings

**Comment by shalinijoshi19** [comment]
Updating the SAS URL for the .NET tool library for 21.01.

**Comment by shalinijoshi19** [comment]
@paulcam206 assigning to you to track reviewing this all up & repurposing this bug to be more of an all up review issue. @jwoo-msft  FYI
