### ISSUE TITLE
[iOS][Accessibility] Font size should adapt system settings.

### ISSUE THREAD

**Issue by SpicyNoodless** [microsoft/AdaptiveCards#5283]
**What platform is your feature request related to? (Delete other platforms).**
- iOS

**Additional context**
If we changed font size in system settings, I think font size of adaptive card should be adjusted automatically like the green part in screenshots.

![image](https://user-images.githubusercontent.com/76025453/104681214-c62dcd00-572c-11eb-968a-7b013925826b.png)![image](https://user-images.githubusercontent.com/76025453/104681158-a1d1f080-572c-11eb-8fff-52574974574c.png)
![image](https://user-images.githubusercontent.com/76025453/104681105-849d2200-572c-11eb-849c-b0e4bdf59fce.png)![image](https://user-images.githubusercontent.com/76025453/104681199-bc0bce80-572c-11eb-8258-5d7a280aef5f.png)

**Comment by jonmill** [comment]
@jwoo-msft - do we have any work to do here or is this on the host to manage this situation?

**Comment by jwoo-msft** [comment]
@jonmill,
We need to make some changes to SDK for this to happen. It's a relatively new feature with iOS 11.

**Comment by RebeccaAnne** [comment]
We should discuss whether this is something we should handle in our SDKs (because the system supports a call for text scaling) or whether the host should listen to these changes and update host config. If we do decide that this is on hosts to handle, our visualizers should do this work.

**Comment by jwoo-msft** [comment]
iOS renderer will check with iOS's native ability in supporting this feature. If this can be supported easily without needing changes in shared code such as HostConfig, we will use the native feature.
