### ISSUE TITLE
[Platform][Broader Feature Request Category if applicable] Title

### ISSUE THREAD

**Issue by kcguptaji** [microsoft/AdaptiveCards#5286]
**What platform is your feature request related to? (Delete other platforms).**

- [ ] .NET HTML
- [ X] .NET WPF
- [ ] Android
- [ ] iOS
- [ ] JavaScript
- [ ] UWP

**Is your feature request related to a problem? Please describe.**
On WPF app we can use the custom fonts without installing the font on the client machine. but the same thing does not work for the adaptive card.

**Describe the solution you'd like**
The adaptive card on a wpf client bot support custom font (without the font being installed on the client machine).

**Describe alternatives you've considered**
Using the other installed font

**Additional context**

**Comment by shalinijoshi19** [comment]
Closing this - following on https://github.com/microsoft/AdaptiveCards/discussions/5284
