### ISSUE TITLE
[iOS][Consistency] [Extra Separator With ToggleVisibility]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#5288]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] iOS

# Details
![image](https://user-images.githubusercontent.com/4112696/104788329-e8344900-5746-11eb-9ee8-8608d92b0c8d.png)

A separator is visible when a hidden element becomes visible and the previous element becomes invisible.

**Comment by jonmill** [comment]
We won't get to this for quite some time...closing
