### ISSUE TITLE
Allow text wrapping on Action buttons when layout is vertical

### ISSUE THREAD

**Issue by danmarshall** [microsoft/AdaptiveCards#529]
Hello, we are receiving customer reports that they would like text to wrap on Action buttons in WebChat
https://github.com/Microsoft/BotFramework-WebChat/issues/616
Seems like this is a reasonable request if button layout is in vertical mode.

**Comment by dclaux** [comment]
Seems reasonable to me too.

**Comment by dclaux** [comment]
The question is, should it be a host config option? Will some host want to prevent wrapping?

**Comment by danmarshall** [comment]
It's possible...
At the very least we should provide a tooltip, in case text is truncated with ellipses.

**Comment by jfb74** [comment]
Any update on this?

**Comment by szul** [comment]
I would like to at least control the action button layout. The WebChat defaults to horizontal whereas Skype defaults to vertical. I would like to be able to specify vertical in the WebChat for the action button layout for times where a choice of buttons (like the Bot Framework choice prompt) is needed, but without forcing users to deal with a horizontal carousel scroll.

**Comment by kds-snyder** [comment]
I would also like the text on buttons to wrap. In some cases I am asking the user which question they meant, and some questions are longer and get truncated. As danmarshall said above, at least provide a tooltip if the text is truncated.

**Comment by RebeccaAnne** [comment]
This is a good suggestion, but not something that's on our roadmap at this time. We may reconsider it in the future, or if you would like to make a contribution please see our contribution guidelines [here](https://github.com/microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md).

**Comment by dclaux** [comment]
We have a new request for this same feature: https://github.com/microsoft/AdaptiveCards/issues/6198
