### ISSUE TITLE
Bearer token "sub" is returning action performer object id now instead of email address

### ISSUE THREAD

**Issue by Rajkumar4428** [microsoft/AdaptiveCards#5290]
In our actionable email implementation, when user take action on the actionable email, we are calling a Power automate flow which then takes the  current user bearer and does the validation. It was working fine till yesterday as the **bearer token "sub" was returning the user email address, but now the same property it is returning user object id** which is breaking the validation of our code. 

Which one is the trusted one user object id or email address? so that we can go ahead with that to change the code. In the MS document code sample also it was mentioned as email address. 
https://docs.microsoft.com/en-us/outlook/actionable-messages/security-requirements#verifying-that-requests-come-from-microsoft

![image](https://user-images.githubusercontent.com/77660572/105002634-9eee3d00-5a57-11eb-8535-2f7d51304059.png)

**Comment by jonmill** [comment]
Please email onboardoam@microsoft.com as this is an Outlook actionable message issue; they should be able to provide more guidance. Thank you!

**Comment by laksh5feb85** [comment]
Hi Raj kumar/Jon,

I also faced the same issue today, its working for some of the users (Sub is showing email address after encoding the bearer  token) but not working for some users( As after encoding bearer token the sub value is showing as OBJECTID)
Which is working fine earlier in all the environments

Could you please help me on it , if we find any fix on it earlier ?
Do we
