### ISSUE TITLE
Binding buttons(actions)

### ISSUE THREAD

**Issue by pedro-ramirez-suarez** [microsoft/AdaptiveCards#5292]
Is it possible to create an adaptive card with dynamic buttons? the number of buttons and the content of each button may vary. I found samples where you can bind the number and type of input controls but I can't reproduce it for buttons.

**Comment by jwoo-msft** [comment]
@pedro-ramirez-suarez 
Yes, you can. If you go to the [Designer](https://adaptivecards.io/designer/). Once you add an ActionSet, you can create a payload with actions by clicking "Add an Action".
![image](https://user-images.githubusercontent.com/4112696/107410157-c4ec8780-6ac1-11eb-9413-dd0b1b57e687.png)

Or if you'are asking if you can create a card that can display a different set of actions depending on the data you have. You can use [Templating SDK](https://docs.microsoft.com/en-us/adaptive-cards/templating/).
