### ISSUE TITLE
Background color doesn't respect RGBA values

### ISSUE THREAD

**Issue by prejedj** [microsoft/AdaptiveCards#5294]
Though the documentation doesn't suggest RGBA values work, the adaptivecards.io designer previews a functioning backgroundColor when using RGBA. In practice however when using the card in Teams the RGBA value doesn't working, you MUST use a hex value.

Please fix this issue with Adaptive Cards, or the issue in Teams as required

---
* URL: https://adaptivecards.io/explorer/Image.html

**Comment by paulcam206** [comment]
Sounds like we have two issues here:
* The designer (and presumably the entire JS platform) is allowing RGBA `backgroundColor` values -- I don't think this is intentional?
* Our documentation suggests that `backgroundColor` is of type `string`, when it should probably be the color enum

**Comment by dclaux** [comment]
RGBA colors have always been supported everywhere in AC where an explicit color can be used. That includes all color definitions in HostConfig as well as the `Image.backgroundColor` property.

The format for `backgroundColor`, again like everywhere else explicit colors are supported, is the same as in CSS for colors without an alpha channel, and AARRGGBB for colors with an alpha channel. The following are valid colors:
| Color code | Actual color |
| --- | --- |
| `000000` | Opaque black |
| `80FFFFFF` | Semi-transparent white |
| `00FF0000` | Completely transparent red |
| `CC6DFF` | Opaque purple |

**Comment by paulcam206** [comment]
huh... I totally forgot that we support that for `backgroundColor`. 😬

**Comment by dclaux** [comment]
Teams desktop uses the JS SDK so this should not be an issue. @prejedj is the behavior you're reporting in Teams mobile only? If it is, then it's either a bug in Teams or a bug in our iOS and/or Android SDKs.

**Comment by prejedj** [comment]
I haven’t checked the issue is on Mobile, I only know it’s on the Desktop client.

Regards,
-Devin

**Comment by dclaux** [comment]
If the issue exists on desktop, there would seem to be a problem with Teams, and not the AC SDK. @siduppal can someone on t=your side look into this?

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/3509
