### ISSUE TITLE
[MSTeams][Action.OpenURL] Open URl button is not working with some URls in Teams

### ISSUE THREAD

**Issue by shereenfathy** [microsoft/AdaptiveCards#5297]
# Platform

- .Net Core

# Details

I've developed bot using Microsoft bot framework, the bot response is adaptive card and i want to use the action.openurl button to open specific link and it worked with some urls but when i used url to document located in Microsoft online word the button become not clickable and this is the json object :
```json
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "size": "Medium",
      "weight": "Bolder",
      "text": "test",
      "wrap": true
    }
  ],
  "actions": [
    {
      "type": "Action.OpenUrl",
      "title": "View",
      "url": "https://shpc.itn.intraorange/sites/MUSCLES/_layouts/15/WopiFrame.aspx?sourcedoc={35729A64-4706-43F1-A530-6EF903831010}&file=DRIssuesTest.doc&action=default"
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.2"
}
```
**NOTE**: this button worked in teams mobile app but not work in teams on Microsoft edge browser and  chrome browser  and teams disktop app

**Comment by RebeccaAnne** [comment]
The card seems to work okay in the JS designer. @Wajeed-msft @siduppal could you take a look and see if there's anything going on on the Teams side here?

**Comment by Mallipriya-MSFT** [comment]
The card seems to be working fine on Teams side as well. Here are the repro screenshots:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/73868678/105287749-b48d6f00-5bdd-11eb-9d64-036f9c9dd270.png)

**card Json**

{
 "type": "AdaptiveCard",
 "body": [
 {
 "type": "TextBlock",
 "size": "Medium",
 "weight": "Bolder",
 "text": "test",
 "wrap": true
 }
 ],
 "actions": [
 {
 "type": "Action.OpenUrl",
 "title": "View",
 "url": "https://blrdev.sharepoint.com/:w:/s/LibraryAssist142/Eb_7Y3V2jvhCkVfTbBY-AvcBzX2W-BFia9zOMfjHVyaK1g?e=Y6f0ov"
 }
 ],
 "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
 "version": "1.2"
}

**Posted card**

![MicrosoftTeams-card](https://user-images.githubusercontent.com/73868678/105288906-00d8af00-5bde-11eb-9ac5-2eed91ad79dd.png)

**On Click of View Button, Document is opening**

![image](https://user-images.githubusercontent.com/73868678/105290020-485f3b00-5bde-11eb-989e-7a3f3f8f6c9d.png)

**Comment by Mallipriya-MSFT** [comment]
@shereenfathy, Could you please share the repro screenshots from your side?

**Comment by shereenfathy** [comment]
the problem appears when i took the url from the address bar:
![image](https://user-images.githubusercontent.com/31906452/105335747-18656700-5be1-11eb-859a-3793cc5e5b27.png)
**card json** 
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "size": "Medium",
      "weight": "Bolder",
      "text": "https://shpc.itn.intraorange/sites/MUSCLES/_layouts/15/WopiFrame.aspx?sourcedoc={6702F20D-3EB2-4C4F-8AFA-85AA7D1B7D14}&file=B2G%20Teams%20Direct%20Routing%20-%20Common%20Issues%20Test.doc&action=default",
      "wrap": true
    }
  ],
  "actions": [
    {
      "type": "Action.OpenUrl",
      "title": "View",
      "url": "https://shpc.itn.intraorange/sites/MUSCLES/_layouts/15/WopiFrame.aspx?sourcedoc={6702F20D-3EB2-4C4F-8AFA-85AA7D1B7D14}&file=B2G%20Teams%20Direct%20Routing%20-%20Common%20Issues%20Test.doc&action=default"
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.2"
}

**posted card** 
![image](https://user-images.githubusercontent.com/31906452/105336521-0801bc00-5be2-11eb-9949-c69b9bea8241.png)

**and on click on the view button nothing happen**

**Comment by shereenfathy** [comment]
> @shereenfathy, Could you please share the repro screenshots from your side?

**Comment by Mallipriya-MSFT** [comment]
@shereenfathy, It is working with the url copied from the address bar. 

![image](https://user-images.githubusercontent.com/73868678/105348714-bd4a6900-5c0e-11eb-8894-689696e94974.png)

**Card Json**

{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "size": "Medium",
      "weight": "Bolder",
      "text": "test",
      "wrap": true
    }
  ],
  "actions": [
    {
      "type": "Action.OpenUrl",
      "title": "View",
      "url": "https://blrdev.sharepoint.com/:w:/r/sites/LibraryAssist142-Nikitha/_layouts/15/Doc.aspx?sourcedoc=%7BEDC75D3C-F612-4013-8122-2520595D6A42%7D&file=aosolis_TaskmodulePayloads.docx&action=default&mobileredirect=true"
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.2"
}

Onclick of view Button, document opens up

![image](https://user-images.githubusercontent.com/73868678/105349243-6f823080-5c0f-11eb-9ca7-24c129703c73.png)

![image](https://user-images.githubusercontent.com/73868678/105348955-07334f00-5c0f-11eb-89d7-9f5fdf71b301.png)

**Comment by shereenfathy** [comment]
> @shereenfathy, It is working with the url copied from the address bar.
> 
> ![image](https://user-images.githubusercontent.com/73868678/105348714-bd4a6900-5c0e-11eb-8894-689696e94974.png)
> 
> **Card Json**
> 
> {
> "type": "AdaptiveCard",
> "body": [
> {
> "type": "TextBlock",
> "size": "Medium",
> "weight": "Bolder",
> "text": "test",
> "wrap": true
> }
> ],
> "actions": [
> {
> "type": "Action.OpenUrl",
> "title": "View",
> "url": "https://blrdev.sharepoint.com/:w:/r/sites/LibraryAssist142-Nikitha/_layouts/15/Doc.aspx?sourcedoc=%7BEDC75D3C-F612-4013-8122-2520595D6A42%7D&file=aosolis_TaskmodulePayloads.docx&action=default&mobileredirect=true"
> }
> ],
> "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
> "version": "1.2"
> }
> 
> Onclick of view Button, document opens up
> 
> ![image](https://user-images.githubusercontent.com/73868678/105349243-6f823080-5c0f-11eb-9ca7-24c129703c73.png)
> 
> ![image](https://user-images.githubusercontent.com/73868678/105348955-07334f00-5c0f-11eb-89d7-9f5fdf71b301.png)


it is not working on my side, the document is located in SharePoint Collaboration .. does this make any problem? or is my link wrong ?  also you can use my link to test.

**Comment by cadin** [comment]
I'm experiencing the same (or similar) issue. Neither of the URLs provided by @shereenfathy or @Mallipriya-MSFT work for me. When clicking the button I get a "Something went wrong" message:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/2348891/105386812-b64d3780-5bc9-11eb-964a-8a94f6ea93d4.png">

This is occurring for me in **Teams desktop for Mac (R1)**.
The buttons seem to work properly in Teams for iOS, web, and in desktop Teams R2 or higher.

Does that line up with your experience @shereenfathy?

**Comment by Wajeed-msft** [comment]
> I'm experiencing the same (or similar) issue. Neither of the URLs provided by @shereenfathy or @Mallipriya-MSFT work for me. When clicking the button I get a "Something went wrong" message:

This error message looks different.  Could you please share your adaptive card JSON?

**Comment by cadin** [comment]
@Wajeed-msft My example is using the JSON provided by @Mallipriya-MSFT above:
```
{
"type": "AdaptiveCard",
"body": [
{
"type": "TextBlock",
"size": "Medium",
"weight": "Bolder",
"text": "test",
"wrap": true
}
],
"actions": [
{
"type": "Action.OpenUrl",
"title": "View",
"url": "https://blrdev.sharepoint.com/:w:/r/sites/LibraryAssist142-Nikitha/_layouts/15/Doc.aspx?sourcedoc=%7BEDC75D3C-F612-4013-8122-2520595D6A42%7D&file=aosolis_TaskmodulePayloads.docx&action=default&mobileredirect=true"
}
],
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"version": "1.2"
}
```

I'm sending my cards as messages through the Graph API for Teams (not sure if that makes a difference).
Let me know if this should be opened as a separate issue. I thought it might be related.

**Comment by Mallipriya-MSFT** [comment]
@shereenfathy, I have tested with the url provided by you initially in Teams web app, It is working but when tested through Teams desktop app, it is not working. Can you check and confirm this behavior from your end ? Meanwhile, I will check internally.

**Comment by Mallipriya-MSFT** [comment]
Hi @cadin, I got it working when posted the adaptive card to channel, Just to confirm have you tested using the API [Send chatMessage to channel](https://docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&tabs=http#example-3-cards) with same request body format.

**Comment by cadin** [comment]
@Mallipriya-MSFT Yes, that's how I'm sending them. It works for you in Teams desktop R1?

**Comment by shereenfathy** [comment]
> @shereenfathy, I have tested with the url provided by you initially in Teams web app, It is working but when tested through Teams desktop app, it is not working. Can you check and confirm this behavior from your end ? Meanwhile, I will check internally.

@Mallipriya-MSFT  
in Teams web app the button is clickable but open the teams app in new tab instead of opening the right link, and yes it is not clickable in teams desktop app.

**Comment by Mallipriya-MSFT** [comment]
Hi @shereenfathy, Can we discuss this over a call? Could you please write to us at microsoftteamsdev@microsoft.com.

**Comment by Mallipriya-MSFT** [comment]
Hi @shereenfathy, are you still facing the issue?

**Comment by Mallipriya-MSFT** [comment]
@shereenfathy, For now we are closing the issue, please feel free to open again if the issue still persists.

**Comment by galando** [comment]
Hey,

@Mallipriya-MSFT we are experiencing the same problem. We use "Action.OpenUrl" with url which contain about 200 characters. The button doesn't work from the app, although from mobile it works.

Can we reopen this issue?

**Comment by dacopan** [comment]
same error for me and occurs when:

- the link is not https 
- not have domain only ip 
- link have spaces

**Comment by fabiobarboza7** [comment]
You guys are using OpenUrl (L) but should be OpenUri according to docs, no?

**Comment by fabiobarboza7** [comment]
![Captura de Tela 2021-08-18 às 11 41 31](https://user-images.githubusercontent.com/39923194/129918957-2f3edc13-4613-41b7-850b-753d6ba16b3d.png)

same error, through browser we get that error when clicking.

**Comment by fabiobarboza7** [comment]
@dacopan and others. I was getting same error. So now it's working for me even http. What a figured out is, if the URL has spaces, special caracters etccc it should be encode look what I did in my code:

`http://jsondiff.com/?left=${encodeURIComponent(initialValue)}&right=${encodeURIComponent(lastData)}`

So that's it, probably just need to encode before call the action.

**Comment by JhonBreTo** [comment]
I found this: The sharepoint/OneNote Url should be in encoded format. If URL has '{' and '}' it does not work. Please replace '{' with '%7B' and '}' with '%7D' respectively it will work. 

Sample URL:

https://{domainName}.sharepoint.com/:w:/r/teams/My_Test/_layouts/15/Doc.aspx?sourcedoc=%7BF2B5321E-7CA9-468D-B628-8ECB9308F982%7D&file=Document.docx&action=default&mobileredirect=true

credits: https://techcommunity.microsoft.com/t5/teams-developer/teams-adaptive-card-won-t-open-onenote-url-s/m-p/2257072/thread-id/2951

**Comment by rahulyadav97185966** [comment]
I want to open the software center from the button. but it didn't work for me. Previously it worked. 
I have used the below code.
`{
                        "type": "openUrl",
                        "title": "SCCM",
                        "value": "softwarecenter:"
 }`

Why it is not working now..

**Comment by Prasad-MSFT** [comment]
@rahulyadav97185966 - We are able to repro this issue. We have raised a bug for the same and engineering team is looking into it. We will inform you once we get any further update. 
Thanks!

![image](https://user-images.githubusercontent.com/62237649/197769860-71d3ff41-5336-44d3-8f97-e7af2d74c669.png)

**Comment by rahulyadav97185966** [comment]
Okay Thanks for informing. Please keep me posted.


Thanks and Regards,
@rahulyadav97185966 <https://github.com/rahulyadav97185966>

**Comment by rahulyadav97185966** [comment]
Okay, Please keep me posted.

**Comment by Prasad-MSFT** [comment]
@rahulyadav97185966 - We are checking with engineering team about this issue. We will inform you once we have any update.
Thanks!

**Comment by rahulyadav97185966** [comment]
Hi @Prasad-MSFT, Any Updates on the issue.

**Comment by rahulyadav97185966** [comment]
Hi @Prasad-MSFT @Mallipriya-MSFT, Any Updates on the issue ?

**Comment by Prasad-MSFT** [comment]
Hi @rahulyadav97185966 - 
Engineering team is investigating the issue. We will update you once we have an ETA to share.

**Comment by Prasad-MSFT** [comment]
@rahulyadav97185966 - We got update from engineering team that, "Currently  external deep link like `softwarecenter:` are not supported".

**Comment by rahulyadav97185966** [comment]
@Prasad-MSFT Is there any way that we can use external deep links like softwarecenter: Since we need to integrate this in the bot?

**Comment by Prasad-MSFT** [comment]
@rahulyadav97185966 - There is no such way to use external deep links.

**Comment by rahulyadav97185966** [comment]
When this bug will get fix. @Prasad-MSFT

**Comment by Prasad-MSFT** [comment]
@rahulyadav97185966 - We don't support external deep link like `softwarecenter:`. There is no plan for supporting them.
Thanks!

**Comment by Annie-Johnson** [comment]
@matthidinger is the ability to launch custom URI schemes from adaptive cards still unsupported?  This is a huge gap, especially for Adaptive Card Extensions in Viva Connections experiences, a solution designed to be a "digital front door".  If anyone has insight into how to get around this limitation, please share it.
