### ISSUE TITLE
[Designer] Designer doesn't seem to respect the $when property

### ISSUE THREAD

**Issue by jervill** [microsoft/AdaptiveCards#5298]
The Designer doesn't seem to be respecting the $when property. I'm new to adaptive cards so there's a good chance I'm doing this wrong, but I don't think so as even the template for "Flight Itinerary" which uses $when property doesn't seem to behave as expected.

This is the preview of the "Flight Itinerary" card, without any modifications.

<img width="538" alt="Designer___Adaptive_Cards" src="https://user-images.githubusercontent.com/4871828/105228817-a3cef180-5b28-11eb-9774-e74c7b29f726.png">

There are four Text Blocks displayed in the first column, but I would expect only two (the ones corresponding to the right city) given the $when defined in the card and the data where `Segments[0].OriginStation = 11235`:
```
{
    "type": "Column",
    "width": 1,
    "items": [
        {
            "type": "TextBlock",
            "$when": "${Segments[0].OriginStation == 11235}",
            "text": "${Places[0].Name}",
            "isSubtle": true,
            "wrap": true
        },
        {
            "type": "TextBlock",
            "$when": "${Segments[0].OriginStation == 13554}",
            "text": "${Places[1].Name}",
            "isSubtle": true,
            "wrap": true
        },
        {
            "type": "TextBlock",
            "size": "ExtraLarge",
            "color": "Accent",
            "$when": "${Segments[0].OriginStation == 11235}",
            "text": "${Places[0].Code}",
            "spacing": "None",
            "wrap": true
        },
        {
            "type": "TextBlock",
            "size": "ExtraLarge",
            "color": "Accent",
            "$when": "${Segments[0].OriginStation == 13554}",
            "text": "${Places[1].Code}",
            "spacing": "None",
            "wrap": true
        }
    ]
}
```

**Comment by jwoo-msft** [comment]
@jervill,

it's a common mistake. you have to click on `preview` to see the result of the template expansion as seen in the image.
![image](https://user-images.githubusercontent.com/4112696/106339998-2a807e80-624d-11eb-90f6-92ae7f43cec1.png)
