### ISSUE TITLE
[iOS][Rendering] Having a `height` property in a custom element causes errors

### ISSUE THREAD

**Issue by jscalo** [microsoft/AdaptiveCards#5301]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] iOS

# Author or host

Host

# Version of SDK

2.4.6

# Details

A custom element with a property named "height" results in a parsing error:

`Error Domain=ACRParseErrorDomain Code=3 "(null)"`

"width", "w", "h" are all OK. But not "height".

This actually took me a long time to figure out and I even filed a different bug (#5300) thinking it had a different cause.

**Comment by jwoo-msft** [comment]
@jscalo, do you mind sharing your json for the custom element?

**Comment by jscalo** [comment]
Yes of course

```
{
    "type" : "AdaptiveCard",
    "$schema" : "http://adaptivecards.io/schemas/adaptive-card.json",
    "version" : "1.3",
    "body" : [
        {
            "type" : "Container",
            "items" : [
                {
                    "type": "PSSpacer",
                    "height": 60
                }
            ]
        }
    ]
}
```

Produces:

> 2021-01-22 13:50:56.091206-0600 SFx[2852:983903] [ACCardLoader.swift:renderCard(jsonStr:viewBounds:):44] *** cardParseResult not valid. Errors: Optional([Error Domain=ACRParseErrorDomain Code=3 "(null)"])

If I change "height" to "h", no problem.

I think error 3 is `ErrorStatusCode.InvalidPropertyValue` (from `Enums.h`).

**Comment by jscalo** [comment]
Oh I bet it's expecting a string like "60px" or something. But I'd argue that since this is a custom type it should be allowed to structure its properties however it wants.

**Comment by jwoo-msft** [comment]
@jscalo
hey, so I debugged it with the payload. you should treat the height property as a reserved keyword. The reason is that we treat all elements including customs types as derived ones from BaseCardElement, and the BaseCardElement has the height property, and its type is an enum when deserialized, and our parser expects the value to be in the string. Valid json values are "stretch" and "auto".

**Comment by jscalo** [comment]
OK makes sense (and I already switched to 'w' and 'h'). Closing.
