### ISSUE TITLE
[Adaptive Card-UI][Text Block] Ellipses do not appear in Text Block when text length exceeds the limit set by "maxLines" and "wrap" = "true"

### ISSUE THREAD

**Issue by riagarwa-ms** [microsoft/AdaptiveCards#5302]
1. Ellipses in TextBlock of Adaptive Card do not show up if text is truncated when "maxLines" and "wrap" values are set. Example in the below screenshot "maxLines" is set to 2 and "wrap" is set to true.
![image](https://user-images.githubusercontent.com/64960865/105281942-34faa280-5bd3-11eb-8bd3-4bff91becfed.png)

2. However, if "maxlines" and "wrap" values are not set. The text gets truncated and ellipses show up.
Below is the screenshot
![image](https://user-images.githubusercontent.com/64960865/105282026-6c694f00-5bd3-11eb-9e19-5399d4c921d9.png)

How can we get the ellipses enabled when "maxLines" value is set and "wrap" is enabled?

**Comment by riagarwa-ms** [comment]
The screenshot is taken from Teams client. (An app added in Teams to handle link unfurling request). Here is the json for the Text block: {
                      "type": "TextBlock",
                      "text": "Now that we have defined the main rules and features of the format, we need to produce a schema and publish it to GitHub The schema will be the starting point of our reference documentation.",
                      "fontType": "Default",
                      "size": "Large",
                      "spacing": "small",
                      "maxLines": "2",
                      "wrap": true
                    }

Attaching the complete json payload.
[jsonPayload.txt](https://github.com/microsoft/AdaptiveCards/files/5850515/jsonPayload.txt)

**Comment by dclaux** [comment]
This is a known limitation and something we don't really have a plan to fix it for now. The fix is not straightforward.

**Comment by dclaux** [comment]
I found an acceptable solution to this that also happens to address another bug. Will fix.
