### ISSUE TITLE
[iOS][Rendering] There's no way to get additional properties from ACOAdaptiveCard

### ISSUE THREAD

**Issue by jscalo** [microsoft/AdaptiveCards#5303]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] iOS

# Author or host

Host

# Version of SDK

2.4.6

# Details

We have a need to override some properties at the card level that are normally at the host config level. For example our host config file might contain:

```
    "mycompany.contentLightColor": "FFFFFFFF",
    "mycompany.contentDarkColor": "00263EFF",
```

But for some cards, we want to override those with different colors. In the rendering hooks for the UI elements we can get a reference to the `ACOAdaptiveCard` via `ACRView.card` but the problem is that `ACOAdaptiveCard` doesn't expose any of the properties that we've included at the top level of the card.

**Comment by jscalo** [comment]
I had thought that `ACOAdaptiveCard.inputs` would give me this data, but it's always empty.

```
(lldb) po String(data:rootView!.card()!.inputs(), encoding: .utf8)
▿ Optional<String>
  - some : "{\n\n}"
```

**Comment by RebeccaAnne** [comment]
@jwoo-msft Can you answer what the expected behavior here is? Is this a bug or something that's missing from the API? Thanks!

**Comment by jwoo-msft** [comment]
@jscalo, thanks for reporting this issue.

**Comment by RebeccaAnne** [comment]
This is about additional properties on the card level which is available on some platforms but not all, and should be available everywhere.

**Comment by RebeccaAnne** [comment]
@jwoo-msft What is the status of this bug?

**Comment by jwoo-msft** [comment]
@RebeccaAnne, I re-assigned the issue to me.
