### ISSUE TITLE
[Android] Reduce package size

### ISSUE THREAD

**Issue by golddove** [microsoft/AdaptiveCards#5306]
**Is your feature request related to a problem? Please describe.**
Multiple clients (Teams, Todoist) are reporting several MB increase in apk size from the addition of adaptivecards. Need to analyze the source of the size (including from shared model and third party dependencies).

**Describe the solution you'd like**
Profile exactly how much space the package requires, and determine if any optimizations can be made.

**Comment by paulcam206** [comment]
@golddove - when you get a chance, can you see if the MinRel flag fix works well? I'd love to get this out with the next release if possible.

**Comment by golddove** [comment]
@paulcam206 from our last discussion, the MinSizeRel flag only seemed to reduce a couple kb.

Will need to do some profiling to get a baseline understanding of our footprint. Also need to see if switching to static will increase or decrease our impact (e.g. need to check if Teams is already using the shared STL).

**Comment by golddove** [comment]
Dug in with the apk analyzer a bit with our sample app.

Java bytecode (*.dex):

| Package  | Description | Bytecode Size |
| --- | --- | --- |
| io.adaptivecards.renderer.* | Java classes written for our Android renderer | 86.8 KB |
| io.adaptivecards.objectmodel.* | Java wrappers generated by SWIG | 265.6 KB |

Native code (*.so):
(for arm64 architecture, but others are similar)
| Library | Description | Library Size |
| --- | --- | --- |
| libadaptivecards-native-lib.so | Shared AdaptiveCards C++ object model | 566.5 KB |
| libc++_shared.so | Shared C++ STL | 265.9 KB |

Much lower than the raw sizes (~ 2 MB bytecode, and ~ 2 MB native lib) we saw when simply inspecting the library (*.aar) by itself, primarily because of proguard (R8) optimization. But, Teams was seeing a much bigger impact on their apk. Could be that our sample app has much lower coverage of our API than Teams, or Teams has proguard rules that are preventing some code stripping.

**Comment by nitinsethi86** [comment]
I am from Teams team.
What is the optimal proguard / R8 rule that is necessary for this library to work in release builds?
