### ISSUE TITLE
[Android][Accessibility] Narrator is not reading the selection action title for the Rich Text Block

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#5311]
Spun off from #4856

# Platform

- [ ] Android

# Details

With the below RichTextBlock, Narrator should read "Click me" when the focus is on the RichTextBlock. We need to confirm that this is the current behavior on Android and fix if necessary.

```json
{
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.3",
  "body": [
    {
      "type": "RichTextBlock",
      "inlines": [
        {
          "type": "TextRun",
          "text": "This is the text",
          "selectAction": {
            "type": "Action.Submit",
            "title": "Click me"
          }
        }
      ]
    }
  ]
}
```

**Comment by jonmill** [comment]
@golddove - is this fixed with the recent accessibility push?

**Comment by golddove** [comment]
@jonmill @RebeccaAnne no, this is not done for RichTextBlock in particular, along with several other features. Android SDK lets us control a `View`'s accessibility labels/traits, tooltips, etc. However, a subset of text (i.e. TextRun) within a TextView is not a standalone `View`, so none of these methods exist for it. We can only style the substring, and add a click handler.

It might be worth checking with some Accessibility experts for Android to see if there is a workaround.

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing for now. We may return to this in the future. Feel free to continue the conversation in this issue.
