### ISSUE TITLE
[Outlook Desktop on Windows] Input.Toggle is not rendered in Outlook desktop on Windows

### ISSUE THREAD

**Issue by surjyams** [microsoft/AdaptiveCards#5316]
# Platform

What platform is your issue or question related to? (Delete other platforms).

# Author

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.

If you're an author, who are you sending cards to?
Self

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest main, etc...
Adaptive Cards designer
# Details
Input.Toggle control is not rendered in Outlook desktop clients; it appears fine on Outlook web clients

![image](https://user-images.githubusercontent.com/23640808/105507124-d4fa1e00-5cf0-11eb-9fd9-449cd74c15c0.png)
![image](https://user-images.githubusercontent.com/23640808/105507499-48039480-5cf1-11eb-849e-8274c904fe2a.png)

**Comment by surjyams** [comment]
**JSON Payload:**
{
	"$schema": "https://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "ColumnSet",
			"spacing": "large",
			"separator": true,
			"columns": [
				{
					"width": "32px",
					"items": [
						{
							"type": "Image",
							"width": "32px",
							"style": "person",
							"horizontalAlignment": "center",
							"url": "https://messagecardplayground.azurewebsites.net/assets/person_m2.png",
							"altText": "Leo Adams Profile Picture"
						}
					]
				},
				{
					"width": "stretch",
					"items": [
						{
							"type": "TextBlock",
							"text": "**Leo Adams added a card**"
						},
						{
							"type": "TextBlock",
							"spacing": "none",
							"isSubtle": true,
							"text": "\"Visual design for Project A\" to \"Fabrikam\" list"
						},
						{
							"type": "TextBlock",
							"spacing": "small",
							"isSubtle": true,
							"text": "Due date: 12/12/2017"
						},
                        {
                            "type": "Input.Toggle",
                            "id": "taskId${$index}",
                            "spacing": "Small"
                        }
					]
				}
			]
		}
	]
}

**Comment by surjyams** [comment]
Is there any update on this please?

**Comment by RebeccaAnne** [comment]
Thanks for filing, we'll follow up with the outlook team to investigate this bug.

**Comment by dclaux** [comment]
I have a feeling it is because your card doesn't define a `title` property on the Input.Toggle. Please try adding one.

**Comment by surjyams** [comment]
Thank you @dclaux . It was indeed because of the missing title property.

**Comment by dclaux** [comment]
Great, thanks for confirming. I'll close this now.
