### ISSUE TITLE
[Designer] Designer preview for Microsoft Teams preview allows .svg images

### ISSUE THREAD

**Issue by jervill** [microsoft/AdaptiveCards#5322]
The https://adaptivecards.io/designer/ preview for Microsoft Teams makes it appear as if .svg are valid inputs for image elements in Microsoft Teams when in fact they are not (in Microsoft Teams itself, I see a 415 "Unsupported Media Type" error code when the image is fetched).

**Comment by jonmill** [comment]
Good callout, we'll fix this as part of #777
