### ISSUE TITLE
Add selectAction on TextBlock

### ISSUE THREAD

**Issue by dclaux** [Microsoft/AdaptiveCards#535]
There are many, many scenarios that call for a piece of text to be clickable, and where buttons wouldn't work visually. For these scenarios, we should add support for selectAction on TextBlock.

**Comment by matthidinger** [comment]
Can't markdown hyperlink syntax handle this scenario, while also making sure it gets a standard visual treatment?

**Comment by dclaux** [comment]
I was actually going to open an issue for exactly this. We would have to support something like this:

```
{
	"type": "TextBlock",
	"text": "Action support in markdown [Execute action with Id abc](action:abc)",
	"weight": "bolder",
	"size": "medium"
}
```

And we would have to have a way to declare actions outside the context of any element, likely at the card level, something like this:

```
{
    "type": "AdaptiveCard",
    ...
    "resources": [
        {
            "type": "Action.Http",
            "id": "abc",
            ...
        }
    ]
}
```

However, I still think supporting selectAction on TextBlock would be very helpful.

**Comment by dclaux** [comment]
I'm not clear above - I think the markdown approach is very useful and we should do it. I also think we should have selectAction on TextBlock.
