### ISSUE TITLE
Input.Date's first day of the week at Teams doesn't change

### ISSUE THREAD

**Issue by WhiteCyClop** [microsoft/AdaptiveCards#5361]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- .Net Core
- Adaptive cards in MS Teams inside Chat bot

# Details

I use an Input.Date in adaptive card. In Teams a week in the calendar starts on Sunday:
![image](https://user-images.githubusercontent.com/47722281/107034243-e0a91280-67cf-11eb-9435-f34e66eeb589.png)
I need it to be displayed from Monday, so I tried to change app's language to English (United Kingdom), but it didn't help.

**Comment by golddove** [comment]
@siduppal feature request for Teams to change calendar start day based on the card's localization

**Comment by Nikitha-MSFT** [comment]
Could you please Raise a [user voice](https://microsoftteams.uservoice.com/forums/555103-public-preview/category/182881-developer-platform)?

**Comment by WhiteCyClop** [comment]
I created an idea on the user voice - [link](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/42649435-change-calendar-start-day-based-on-the-adaptive-ca)

**Comment by WhiteCyClop** [comment]
Hello! Maybe do you have some additional opportunity to find out the predictions on this problem?

**Comment by Nikitha-MSFT** [comment]
Currently we don't have any other way. Thanks for Raising a user voice.

**Comment by Wajeed-msft** [comment]
User voice would be right place to track this. Closing this from issues page.
