### ISSUE TITLE
Suggestion!

### ISSUE THREAD

**Issue by arman-g** [microsoft/AdaptiveCards#5364]
Just a suggestion, remove issues section since most of the bug reports being ignored and stay unresolved.

**Comment by dclaux** [comment]
Hi @arman-g, we are sorry that issues are not being resolved as fast as you would like.

A quick search in our repo shows that you opened two identical issues (https://github.com/microsoft/AdaptiveCards/issues/3991 and https://github.com/microsoft/AdaptiveCards/issues/4091) against the .NET HTML SDK.

I will make sure the team is aware the issues have been pending for a long time and that we give an update.

I also want to remind you that the AC SDKs are all open source and you are more than welcome to contribute a bug fix.

**Comment by paulcam206** [comment]
We're going to continue tracking in #3991
