### ISSUE TITLE
Is there any UI tool to create adaptive cards?

### ISSUE THREAD

**Issue by kenyeung128** [Microsoft/AdaptiveCards#538]

**Comment by matthidinger** [comment]
Hi @kenyeung128, 

The Visualizer here is our primary tool right now
http://adaptivecards.io/visualizer/

We also have a VS Code extension that enables a live preview in the editor 
https://docs.microsoft.com/en-us/adaptive-cards/resources/tools#visual-studio-code-extension

Is there another kind of tool you were looking for?

**Comment by mdtauk** [comment]
A designer with drag and drop for valid elements, drop down to select "template" as in Live Tile/HTML/Notification/XAML implementations, and responsive sizing tests. - Export the XML/C#/JS code needed.

Maybe overkill, but could be a good Visual Studio feature, along with a future updated XAML designer, When AdaptiveCards become the defacto UWP method for data display.  Could work as a native XAML control, where you load in an XML source also.

**Comment by kenyeung128** [comment]
Hi, Matt,

Yes, like Martin said, a designer where drag and drop with elements, rather
writing json to design, as it takes quite some time to build different
cards. It would be very helpful with a designer tool.
ᐧ

*Ken Yeung*
*CEO & Co-founder of *Clare.AI <http://clare.ai/>
ken@clare.ai | Skype: denmarkken | Mobile: +852 5333 2683
Building Natural Asian Language AI Digital Assistants

**Comment by paulcam206** [comment]
I think we can consider this [done](https://adaptivecards.io/designer/), right @matthidinger?

**Comment by matthidinger** [comment]
Yessir! Check out the [all-new designer](https://adaptivecards.io/designer/)!
