### ISSUE TITLE
[Shared/Android/iOS/UWP/.NET][Markdown] Whitespace

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#5380]
**What platform is your feature request related to? (Delete other platforms).**

- [ ] .NET WPF
- [ ] Android
- [ ] iOS
- [ ] UWP
- [ ] Shared

**Is your feature request related to a problem? Please describe.**
1. Update the shared model markdown parser to handle whitespace characters. TBA for detailed spec.
2. Investigate if all listed platforms will honor parsed HTML by the markdown parser.

**Comment by jonmill** [comment]
Closing per triage
