### ISSUE TITLE
[All Platforms][Input.ChoiceSet] 'Choices' prop should be made 'NOT Required' with the introduction of 'choices.data' for autocomplete

### ISSUE THREAD

**Issue by karthikbaskar** [microsoft/AdaptiveCards#5389]
**What platform is your feature request related to? (Delete other platforms).**
All Platforms

**Is your feature request related to a problem? Please describe.**
Currently, in Android and iOS SDK, parsing of the card json fails completely if the choices prop is empty or not provided in Input.ChoiceSet. In the JS SDK, this is gracefully handled and this only affects the ChoiceSet control and the rest of the card renders.

**Describe the solution you'd like**
In Input.ChoiceSet, 'choices' is currently a required property. With the [introduction of 'choices.data' for dynamic bot querying](https://github.com/microsoft/AdaptiveCards/issues/3924) for choice data, the 'choices' property should no longer be a required property. 

**Describe alternatives you've considered**
No alternatives have been identified yet for the mobile sdks. Since the card parsing fails due to this issue and overriding parsers for base elements is not supported, this is a blocker.

**Additional context**
In Teams, we are building an Adaptive Card People Picker control based on the Autocomplete/BotQuerying feature in Input.ChoiceSet linked above. In this case, the dataset will be AAD  and 'choices' property is not required. When user enters a query, we will query AAD and populate the results as choices. The JS SDK allows providing an empty 'choices' prop whereas the mobile SDKs don't since the parsing fails.

**Comment by matthidinger** [comment]
This makes sense to me. I guess the question is, if we agree with the suggestion and update the schema, can the team coding up the features in iOS/Android make this change at the parsing layer? (@karthikbaskar not sure if that is you directly or not)

**Comment by karthikbaskar** [comment]
@matthidinger Overriding the parser of a base element like Input.ChoiceSet is not supported in Android and iOS. So I think an SDK fix will be required. I'm reaching out to Devs from the AC team that works on the mobile SDKs for confirmation on this. Will post an update here on this soon.

**Comment by karthikbaskar** [comment]
@matthidinger Discussed this issue with Joseph. Changes are required in the parsing layer in the shared models (cpp) to support this ask. Once that is done and an SDK update is available, we should be able to consume this in Teams.

**Comment by jwoo-msft** [comment]
@RebeccaAnne, Can we close this?

**Comment by jwoo-msft** [comment]
Confirmed with @RebeccaAnne.
Closing it.
