### ISSUE TITLE
Host Config should include option to add overlay for background images

### ISSUE THREAD

**Issue by j-halletthook** [microsoft/AdaptiveCards#539]
Text can be hard to read with a full bleed background image. 
There should be an option in the Host Config file to add an overlay to background images to increase text legibility.

**Comment by mdtauk** [comment]
For the background image, you should be able to add a tint opacity and possibly tint colour.

**Comment by j-halletthook** [comment]
I can't find references to tint opacity or tint color, do you have an example I could see?

**Comment by mdtauk** [comment]
@j-halletthook   I didn't mean those options currently exist, but that they should exist, to implement the feature you suggested in a flexible and powerful way.

**Comment by RebeccaAnne** [comment]
This is a good suggestion, but not something that's on our roadmap at this time. We may reconsider it in the future, or if you would like to make a contribution please see our contribution guidelines [here](https://github.com/microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md).
