### ISSUE TITLE
[JavaScript][Input.Number value] [Non-Required empty Input.Number returns "NaN" as value on Submit]

### ISSUE THREAD

**Issue by aroraketan** [microsoft/AdaptiveCards#5390]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [x] JavaScript

# Author or host

Host: Microsoft Teams (multi-window).

# Version of SDK

JS v2.6.0

# Details

A non required empty Input.Number returns value `"NaN"` when clicked on Submit.

## Reason
The `valeAsNumber` is `NaN` for empty DOM Elements and when converted to string before submitting, it becomes `"NaN"`.
Following is a snippet of `value` getter of `NumberInput`
![image](https://user-images.githubusercontent.com/16015962/108020698-ea8a0b80-7042-11eb-9b5f-b0acff7a898b.png)

**Comment by paulcam206** [comment]
@dclaux - can you take a look?

**Comment by golddove** [comment]
Possibly fixed by #5307. @aroraketan checking with 2.7 renderer

**Comment by aroraketan** [comment]
Tested with the v2.7.0 renderer. Works fine. Thanks.

**Comment by paulcam206** [comment]
thanks for confirming @aroraketan! closing as fixed.
