### ISSUE TITLE
Only show when - Property

### ISSUE THREAD

**Issue by Geradav** [microsoft/AdaptiveCards#5391]
Hello,

How can we use the 'Only show when' property in adaptive cards?

---
* URL: https://adaptivecards.io/explorer/TextBlock.html

**Comment by jwoo-msft** [comment]
https://docs.microsoft.com/en-us/adaptive-cards/templating/language#conditional-evaluation
https://docs.microsoft.com/en-us/adaptive-cards/templating/language#conditional-layout-with-when
