### ISSUE TITLE
[iOS][ColumnSet] ChoiceSet inside ColumnSet has improper layout

### ISSUE THREAD

**Issue by akaashdev** [microsoft/AdaptiveCards#5399]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] iOS

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.

If you're an author, who are you sending cards to?

# Version of SDK

2020.10 (latest master as of Oct 27th)

# Details

When 3 columns is used with ChoiceSet, the layout kindof breaks.

<img src="https://user-images.githubusercontent.com/17749787/108371835-2b8d4600-7224-11eb-9f22-ddc0f4c9d704.jpeg" alt="IMG_5469" width=340>

This can be reproduced using iOS Visualizer app

<img src="https://user-images.githubusercontent.com/17749787/108371924-452e8d80-7224-11eb-80fd-ac73ab848a33.PNG" alt="IMG_0166" width=340>

The same card however renders fine on Android

<img src="https://user-images.githubusercontent.com/17749787/108372670-0e0cac00-7225-11eb-9165-69437e54ab6e.png" alt="Screenshot_20210218-164054" width=340>

The card JSON for reference
[multi-column-choicesets.txt](https://github.com/microsoft/AdaptiveCards/files/6003474/multi-column-choicesets.txt)

**Comment by jwoo-msft** [comment]
@akaashdev 
Thanks for reporting this issue.
Look like linebreak mode needs to be changed to word break.

**Comment by jwoo-msft** [comment]
@akaashdev 
As we have discussed, this is due to the narrow width.  I recommend adjusting the leading & trailing paddings and font size in the way of custom rendering for ACRInputChoiceSetRenderer.
Thanks.
