### ISSUE TITLE
UWP Renderer renders inputs regardless of the supportsInteractivity field in HostConfig

### ISSUE THREAD

**Issue by riarenas** [Microsoft/AdaptiveCards#540]
Actions are properly ignored, but all inputs are rendered regardless of the configuration.

**Comment by mdtauk** [comment]
If the SupportInteractivity setting is false, should it not still render the UI declared, but set the input fields to Read Only, so they can not be interacted with, but are still visible?

**Comment by riarenas** [comment]
Rendering read only input fields would confuse users, and the blame would end up being directed to the host. The current desired design is that it should be up to card authors to know the guidelines for the specific host that will be rendering their cards as to know that they don't support use any of the action or input elements.
