### ISSUE TITLE
[Android][Column rendering] [TextBlock inside column inside another column not rendering]

### ISSUE THREAD

**Issue by dipja** [microsoft/AdaptiveCards#5415]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Android

# Author or host

Microsoft Teams 

# Version of SDK

SDK version 2.4.0

# Details

Text Block inside column inside another column does not render. 
Sample JSON - [Link](https://microsoft-my.sharepoint.com/:u:/p/dipja/ETV4S6bd21pDiS4jNwQ321ABP7OQsWii4JnPpi5TPEt1fA?e=mOZz1G) 

**Before**
<img width="279" alt="image" src="https://user-images.githubusercontent.com/61967816/108820158-c77ecf00-75e1-11eb-81e6-05ae667564ed.png">

**After**
<img width="279" alt="image" src="https://user-images.githubusercontent.com/61967816/108820218-e1201680-75e1-11eb-8bb0-f0fbac259bf1.png">

**Comment by dipja** [comment]
@shalinijoshi19 / @golddove Could you help triage this regression.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4838
