### ISSUE TITLE
Teams doesn't format adaptive cards like the designer does

### ISSUE THREAD

**Issue by pr1malc0de** [microsoft/AdaptiveCards#5416]
Teams has stopped showing adaptive cards the same as the designer does. In teams the card outline goes wide across the whole of the teams window but the designer shows them looking fine. Also colors are ignored. This was working fine previously and it appears a recent update to teams has changed this although i couldn't
![Screenshot 2021-02-23 183947](https://user-images.githubusercontent.com/662108/108891360-877e1300-7606-11eb-85f7-f4397626a19e.png)
 say when it changed. All previous adaptive cards posted now look the same

Edit - the designer formats the color warning as yellow, teams formats them as red

**Comment by paulcam206** [comment]
@siduppal - were there color updates to your hostconfig recently? we might need to ingest them...

**Comment by pr1malc0de** [comment]
Hey @siduppal I did submit a support ticket via Powerautomate support (as we post adaptive cards from there) and they informed us the wide layout of the cards and the color not selecting based on the option for "Attention" or "Warning" is... "By Design".  This doesn't match the documentation though and seems an odd choice, can you confirm if this is indeed "by design" or just a bug that will be resolved? Thanks

**Comment by Jagadeesh-MSFT** [comment]
Hi @pr1malc0de, Thanks for brining up this suggestion, I'm able to repro your issue from my end, I will rise buy and will share the details for the same.

**Comment by Jagadeesh-MSFT** [comment]
Hi @pr1malc0de, I have raised the [bug](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1651172) and concern team will work on this. 
Thanks..!

**Comment by pr1malc0de** [comment]
Hi @Jagadeesh-MSFT 

Thanks, This is a better response than the Microsoft support team have got from the teams engineers who closed my ticket saying the engineers told him and I quote "this is out of support"

**Comment by jonmill** [comment]
@Jagadeesh-MSFT, @pr1malc0de - we'll close the issue here since Teams is tracking it internally. Feel free to continue communicating here on the status of the bug since the internal bug is not visible
