### ISSUE TITLE
[JavaScript/NodeJS] Improve the rendered image quality for unsupported platforms

### ISSUE THREAD

**Issue by Kadae** [microsoft/AdaptiveCards#5421]
Adaptive Cards so pixelated when renders in Bot Framework in image for Telegram (Telegram doesn't support it) in NodeJs.
Is there a way to improve the image quality on NodeJS?

**Comment by paulcam206** [comment]
I can take a look here :)

**Comment by jonmill** [comment]
Dupe of #5430
