### ISSUE TITLE
[Platform][Choices] Conditional visibility based on selected choice without Action.Submit

### ISSUE THREAD

**Issue by VMey** [microsoft/AdaptiveCards#5422]
**What platform is your feature request related to? (Delete other platforms).**

- [ ] .NET HTML
- [ ] JavaScript

**Is your feature request related to a problem? Please describe.**
There doesn't seem to be a way to hide or show elements based on the choice a user inputs.  If a user wanted to book a one-way flight or a round-trip flight, they would not see a return date for the one-way flight but they would see a return date for the round-trip flight.  Today, as far as I know, I'd have to build the card to have Action.Submit send the card and load a new card with the appropriate fields.  I know of no way to dynamically respond to user's input other than Action.ToggleVisibility

**Describe the solution you'd like**
We'd like to be able to apply logic, such as $when or logic on isVisible, that is sensitive to a user's input BEFORE they've executed an Action.Submit interaction.  

So, in my example above, if the user chooses "one-way" for a flight, the returnDate field is hidden, but if they choose "round-trip" the returnDate field is shown.  

**Describe alternatives you've considered**

- We could build it in such a way that these are not real choices, using columns perhaps or other things and then having Action.ToggleVisibility set up.  But this won't allow us to use the drop down element, and won't scale very easily if we need more than just a couple options.
- I checked to see if selectAction is available on choices, like this, but it doesn't work.
```json
                {
                    "title": "Choice 1",
                    "value": "Choice 1",
                    "selectAction": {
                        "type": "Action.ToggleVisibility",
                        "targetElements": [
                            "button"
                        ]
                    }
                }
```
- We could take the user's dropdown choice and submit it and then load a new card conditionally, but this is overly complicated.

**Comment by paulcam206** [comment]
hey @matthidinger -- interesting feature request 👍

**Comment by VMey** [comment]
@paulcam206 and @matthidinger this could be genericized a bit more as simply allowing active state of an element to be evaluated.  I say this because it isn't just about show/hide.

Imagine you have a choice field for **Colors**, with values Blue, Green, and Red.

Now you have a choice field for **Shades**, where the options are would be dependent on the **Color** chosen. 
If Blue is chosen, the options could be "Light Blue" and "Dark Blue"

Then that could be potentially used with functions to automatically build the set of options into an array like this ("$card" being a hypothetical syntax for referencing the card's active state, "$card.colors" is the means of targeting a specific Id on the card, and "$card.colors.selection" represents the currently selected value):  ${foreach(createArray('Light','Dark'),x,concat(x,' ',$card.colors.Selection))}

**Comment by RebeccaAnne** [comment]
This is an interesting idea, but not on our immediate roadmap. Moving to backlog for future consideration.

**Comment by paulcam206** [comment]
Not currently on our roadmap - closing.
