### ISSUE TITLE
[Designer] Highlight JSON block when clicking an element element

### ISSUE THREAD

**Issue by Narizz28** [microsoft/AdaptiveCards#5423]
When clicking on an element in either the Card pane or Card Structure pane, highlight the entire JSON connected to it in the Card Payload Editor.
![image](https://user-images.githubusercontent.com/72027960/109020651-c43a2080-767f-11eb-8419-62a67efc5c30.png)

**Comment by paulcam206** [comment]
@dclaux - designer feature request :)

**Comment by dclaux** [comment]
One word: hard.

**Comment by paulcam206** [comment]
This is not currently on our roadmap.
