### ISSUE TITLE
Feature request: Some way to specify container margins

### ISSUE THREAD

**Issue by jscalo** [microsoft/AdaptiveCards#5427]
In our organization where we're heavily adopting AdaptiveCards, we often run into cases where we'd like to have content within a container start drawing at a certain margin (aka inset) from the sides. Currently we achieve this behavior by putting everything inside a ColumnSet where the 1st and 3rd columns are empty and control the margins, and the 2nd column contains the content, but this is really cumbersome to do.

I propose that all container types support a property `margins` that looks something like this:

```
{
    "top": 8,
    "bottom": 8,
    "left": 15,
    "right": 15
}
```

And then content within that container would be surrounded by the prescribed padding.

`HostConfig.SpacingsConfig` doesn't work for this because it affects _all_ elements are laid out.
`Container.spacing` doesn't work for this because it only affects the vertical spacing to the previous element.

**Comment by paulcam206** [comment]
@matthidinger - can you take a look at this request?

**Comment by jonmill** [comment]
@jscalo - this currently is not supported by-design. Please take a look at our documentation to read more about the reasoning behind this: https://docs.microsoft.com/en-us/adaptive-cards/#semantic-instead-of-pixel-perfect
