### ISSUE TITLE
[Designer] [Separator property is not updated correctly]

### ISSUE THREAD

**Issue by zsolt-illes** [microsoft/AdaptiveCards#5429]
Repro steps:
1. Go to https://adaptivecards.io/designer/
2. Choose the title text box "Publish Adaptive Card Schema"
3. In the Element Properties pane tick the Separator box.
4. Note that the "separator": true tag is added to the JSON output.
5. In the Element Properties pane untick the Separator box.

Expected behavior: The separator tag in the JSON output disappears, or changes to false.

Actual behavior: The separator tag in the JSON output does not change.

**Comment by paulcam206** [comment]
@dclaux - care to take a look?
