### ISSUE TITLE
Fix list of named color

### ISSUE THREAD

**Issue by dclaux** [microsoft/AdaptiveCards#543]
# Implementation status
- [X] TypeScript (https://github.com/Microsoft/AdaptiveCards/pull/582)
- [ ] UWP
- [ ] WPF
- [ ] iOS
- [ ] Android
- [ ] Documentation

# Problem
We currently have, among other, two (or three, depending on the renderer) named colors:
- Dark
- Light
- Default (this one doesn't exist in the HTML renderer)

Additionally, HostCong has a textBlock.color property to define what the default text color is among the available named colors.

This model doesn't work. The default color should always be the one that works well on a given background. Dark and Light color names are not useful given that each color can have a "subtle" version.

# Solution
- Remove the **"dark"** and **"light"** color names
- Keep (or add where missing) the **"default"** color name
- Remove HostConfig.textBlock.color
- Make all TextBlock elements default to the "default" color

The enumeration, as defined in TypeScript, becomes:
```
export type TextColor = "default" | "accent" | "good" | "warning" | "attention";
```

**Comment by matthidinger** [comment]
@dclaux what about scenarios where a developer provides a light background image that needs dark text overlayed, or a dark background and needs to force light text?

**Comment by dclaux** [comment]
Yep, good point. I think I'll need to revert this change. What we seem to need is the below.

In HostConfig:
* Each container style needs to define light and dark colors in host config.
* Each container style also needs to define which of the named colors is its default. That will depend on its background color; for instance, the "default" style for Teams will define the "dark" color as its default, while Timeline's "default" style (which has a dark background) will define "light" as the default color.

In the renderer:
* A new "defaultTextColor" property is introduced on Container to override the container style's default color. A card author would set that property as appropriate when they assign a background image to the container

How does that sound?

**Comment by matthidinger** [comment]
I'm not 100% sure I'm following. If I don't specify a background image then I should be able to rely on my TextBlocks in a given container having the correct default color. If I choose light or dark without a background image presumably it won't look very good, but that seems like the fault of the payload author? If I DO specify a background image that is a light contrast, and I explicitly want dark text over it, then I would use TextBlock color: "dark" and it would look correct regardless of which container style I choose, right?

**Comment by dclaux** [comment]
Container styles define the a container's background color. Say we have a "cave" style that is defined like this:
```
{
    "backgroundColor": "000000",
    "fontColors": {
        "dark": "000000",
        "light": "FFFFFF",
        ... other colors
    }
}
```

Obviously the "dark" color won't work on a container with the "cave" style because its background is also black. However you don't want to defined "dark" as a color that's actually light... So you add a **defaultColor** property to the style definition to indicate which of the colors is the default one that each text block uses unless their color is explicitly specified:

```
"cave": {
    "backgroundColor": "000000",
    "defaultColor": "light",
    "fontColors": {
        "dark": "000000",
        "light": "FFFFFF",
        ... other colors
    }
}
```

In your payload:
```
...
{
    "type": "Container",
    "style": "cave",
    "items": [
        {
            "type": "TextBlock",
            "text": "Hello world"
        }
    ]
}
...
```

The above will render properly, white text on black background.

Now say the card author applies a background image on top of that same container, and it so happens that it is overall very light. White text on that container wouldn't work, so the author needs to be able to override what the default color for the container is. For that we introduce a new **defaultTextColor** on Container:

```
...
{
    "type": "Container",
    "style": "cave",
    "backgroundImage": "http://www.fabrikan.com/very_light_background.png",
    "defaultTextColor": "dark",
    "items": [
        {
            "type": "TextBlock",
            "text": "Hello world"
        }
    ]
}
...
```

The above will render properly, dark text on the light background, regardless of the definition of the style applied to the container.

Make sense?

**Comment by matthidinger** [comment]
Thanks for the explanation, it does make sense. I just can't shake the feeling that this is adding complication in order to "protect" the dev from themselves. If a developer choose to combine a background image with a style, it seems reasonable (at least to me) to also make them include a color property on each TextBlock. 

So in your exmple they would add color: "dark" on the TextBlock.  

Your proposal is definitely less verbose. Thinking about this more, it seems like this is this something we could decide in v1.1, since 1.0 doesn't have container background images. Does that sound ok?

**Comment by dclaux** [comment]
That is fine, yes. And you are right that we could simply require that the author explicitly specifies a color on each TextBlock, but as you say I was looking for a less verbose solution. BTW I think it's an important aspect of Adaptive that we protect card authors from themselves as much as possible.

**Comment by dclaux** [comment]
Just to be clear, we do need the defaultColor property on a style definition.

**Comment by englishextra** [comment]
Hi there.
As I understand it right. there's no way to change the color of the `TextBlock` using JavaScript from cdn (I'm developing a PWA for web and Electron)?

Say, I cannot set color `#212121` for `TextBlock` like so:

`"type": "TextBlock","color":"#212121"`
