### ISSUE TITLE
JSON Templates for common card/data types.

### ISSUE THREAD

**Issue by mdtauk** [Microsoft/AdaptiveCards#544]
Will there be some guidance for developers in the best practices for managing the various types of AdaptiveCards - almost like templates, so they can match their cards to common patterns and system ui defaults.

This could prevent someone's Notification Centre from looking like a disjointed mess perhaps.  Of course there may not need any guidance/samples/templates for these things - and I am over thinking it.

It just occurred to me that once these Cards become fully integrated into Windows, and appear on Android, iOS - with their own UI standards and conventions - it could be important to provide a way to keep consistency.

**Comment by matthidinger** [comment]
@mdtauk Windows will be providing guidance on their respective experiences, e.g., Timeline will have a set of best practices, and Action Center will have a similar set of best practices. Ultimately this will be up to each experience owner to guide their developers in the most appropriate way for them.

Separately, we are also working on some prototypes for standardizing a set of well known data types. I hope to share more on this in the coming weeks.

**Comment by mdtauk** [comment]
Thank you @matthidinger

**Comment by matthidinger** [comment]
Closing issues as resolved, please do continue with the feedback @mdtauk!
