### ISSUE TITLE
[Android][iOS] Support for custom 'style' values in controls ('people' style in Input.ChoiceSet)

### ISSUE THREAD

**Issue by karthikbaskar** [microsoft/AdaptiveCards#5444]
**What platform is your feature request related to? (Delete other platforms).**
Android, iOS

**Is your feature request related to a problem? Please describe.**
Currently, in Android and iOS SDK, properties like 'style' have their values restricted to an enum and do not support any custom value. In case of an unrecognized value being passed, it falls back to a default value in the enum. 
To improve the experience for the upcoming [dynamic querying capabilities for Input.ChoiceSet](https://github.com/microsoft/AdaptiveCards/issues/3924), we would like to support custom styling for the people picker scenario in Teams and drive this by setting a value like 'people' as the 'style'.

**Describe the solution you'd like**
A way to know if an unsupported value is passed to a controlled prop. Non-standard props can currently be accessed through additionalProperty bag. Something along these lines would be great!

**Describe alternatives you've considered**
NA

**Additional context**
In Teams, we are building an Adaptive Card People Picker control based on the Autocomplete/BotQuerying feature in Input.ChoiceSet linked above. The dataset can be used to drive the UX for pre-defined datasets. But for custom datasets which are owned by the bot developer, for which a people picker like style would be appropriate, we currently do not have a provision. We got a customer ask from Workday for such custom user datasets.

**Comment by paulcam206** [comment]
@karthikbaskar - what would be the timeline for this?

**Comment by matthidinger** [comment]
Also tracked by #5525 which was just pushed from Productboard
