### ISSUE TITLE
Input Value Substitution Not Working in Action.Http Body

### ISSUE THREAD

**Issue by nyczducky** [microsoft/AdaptiveCards#5447]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] .NET HTML
- [ ] .NET WPF
- [ ] Android
- [ ] iOS
- [ ] JavaScript
- [ ] UWP

# Author or host

Author: Sending cards to myself as a test using Microsoft Flow.

# Version of SDK

V1.0

# Details

Input value substitution is not working properly. The below adaptive card renders correctly in Outlook and functions correctly. However when receiving the HTTP Reponse, I am getting {{newVendorNames.value}} instead of whatever I typed into newVendorNames. Same with {{newVendorDocs.value}} and {{existingVendorAction.value}}.

```json
{
  "type": "AdaptiveCard",
  "originator": "ORIGINATOR ID",
  "body": [
    {
      "type": "TextBlock",
      "size": "medium",
      "weight": "bolder",
      "text": "Title Block"
    },
    {
      "type": "TextBlock",
      "text": "BLAH BLAH.",
      "wrap": true
    }
  ],
  "actions": [
    {
      "type": "Action.ShowCard",
      "title": "New Vendor",
      "card": {
        "type": "AdaptiveCard",
        "body": [
          {
            "type": "TextBlock",
            "text": "FIRST RESPONSE",
            "wrap": true,
            "color": "attention",
            "size": "medium"
          },
          {
            "type": "Input.Text",
            "id": "newVendorNames",
            "placeholder": "newVendorNames",
            "isMultiline": true
          },
          {
            "type": "Input.Toggle",
            "title": "newVendorDocs",
            "id": "newVendorDocs",
            "valueOn": "Yes",
            "valueOff": "No"
          }
        ]
      }
    },
    {
      "type": "Action.ShowCard",
      "title": "Existing Vendors",
      "card": {
        "type": "AdaptiveCard",
        "body": [
          {
            "type": "TextBlock",
            "text": "SECOND QUESTION",
            "wrap": true,
            "color": "attention",
            "size": "medium"
          },
          {
            "type": "TextBlock",
            "text": "SECOND QUESTION",
            "wrap": true
          },
          {
            "type": "Input.ChoiceSet",
            "choices": [
              {
                "title": "Answer 1",
                "value": "Answer 1"
              },
              {
                "title": "Answer 2",
                "value": "Answer 2"
              },
              {
                "title": "Answer 3",
                "value": "Answer 3"
              },
              {
                "title": "Answer 4",
                "value": "Answer 4"
              }
            ],
            "id": "existingVendorAction",
            "style": "expanded"
          }
        ]
      }
    },
    {
      "type": "Action.Http",
      "title": "Submit Response",
      "method": "POST",
      "headers": [
        {
          "name": "Authorization",
          "value": ""
        },
        {
          "name": "Content-Type",
          "value": "application/json"
        }
      ],
      "url": "HTTP RECEIVE URL",
      "isPrimary": true,
      "body": "{\"newVendorNames\": \"{{newVendorNames.value}}\",\"newVendorDocs\": \"{{newVendorDocs.value}}\",\"existingVendorAction\": \"{{existingVendorAction.value}}\"}"
  }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0"
}
```

**Comment by pankajpalOlk** [comment]
I had a look at the issue.
 
We do capture input values for an action for following scenarios:
 
Action button in Show card:
Inputs defined in show card and parent card will be captured.
Action button in main card:
Inputs defined in parent card will only be captured.
 
Here, the action button is part of main card and we are expecting to capture inputs defined in the different show cards, which is not supported as per design. It seems a bit confusing to the users as well. `The suggestion from our side is to move the Submit action inside the show cards.`
 
Especially in mobile, we open show card in a new window, and if I follow the current card design, I will have to fill input value in the new pop-up window, close it and then click on the submit button. IMO, this is a bit counter intuitive. It would be more natural if user fills up the input and click on an action button which is inside the show card itself.

**Comment by nyczducky** [comment]
Thanks @pankajpalOlk. I'll see if I can redesign this. Wasn't aware of any scope limitations with the cards.

**Comment by nyczducky** [comment]
Confirming that was the issue! Thanks!

Suggesting that the Input Value Substitution documentation be updated to be a little clearer.
