### ISSUE TITLE
UWP: Body element cannot be empty, which means can't make card with only actions

### ISSUE THREAD

**Issue by anbare** [Microsoft/AdaptiveCards#545]
You can't even just use a blank array on body, you currently have to provide elements inside the body, otherwise the renderer fails to render.

HTML renderer allows no body/empty body.

Some scenarios there's no body, just actions.

**Comment by riarenas** [comment]
I will split this issue into two:
As of current documentation, Body is a mandatory property for an adaptive card. I will file an issue for the documentation and schema to determine if a change there is needed. It is a bug however that the UWP renderer does not allow rendering of an empty body.

**Comment by riarenas** [comment]
Opened #548

**Comment by anbare** [comment]
Fixed with #553
