### ISSUE TITLE
Support for Pseudo CSS Classes and Elements

### ISSUE THREAD

**Issue by spanwargithub** [microsoft/AdaptiveCards#546]
We use a variety of CSS pseudo classes and pseudo elements to achieve various UI effects. For example, to highlight the background of the content card on mouse hover we use :hover CSS class. To show that element is in focus (by outlining it) we use :focus CSS class. 
Adaptive library supports hover functionality; however, I have not found any support for focus yet. 
Along with the pseudo classes, we use pseudo element as well such as 
1.	::after (:after)
2.	::before (:before)
Pseudo element gives us the ability to decorate HTML elements using custom fonts.

**Comment by RebeccaAnne** [comment]
This is a good suggestion, but not something that's on our roadmap at this time. We may reconsider it in the future, or if you would like to make a contribution please see our contribution guidelines [here](https://github.com/microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md).
