### ISSUE TITLE
[.NET] Agenda card column with backgroundImage not showing

### ISSUE THREAD

**Issue by golddove** [microsoft/AdaptiveCards#5462]
# Platform

- [ ] .NET WPF

# Version of SDK

21.02 (rc)

# Details

Agenda card has columns with vertical line (using a background image). The image doesn't render on WPF (compare to JS below).

Not a 21.02 regression (i.e. same behavior observable in the `release/21.01` branch)

WPF:
![image](https://user-images.githubusercontent.com/4442788/109741975-2f15bb00-7b9c-11eb-9659-bd852c91c207.png)

JS:
![image](https://user-images.githubusercontent.com/4442788/109742047-540a2e00-7b9c-11eb-8ade-d6d84cd4f320.png)

**Comment by paulcam206** [comment]
this is likely not a regression, but we should consider taking a fix
