### ISSUE TITLE
In android  visibility false configuration textbox   , adaptive card not loading.

### ISSUE THREAD

**Issue by poonam0025** [microsoft/AdaptiveCards#5464]
# Platform
Android
[code.txt](https://github.com/microsoft/AdaptiveCards/files/6076088/code.txt)

What platform is your issue or question related to? (Delete other platforms).

- [ ] .NET 

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.

If you're an author, who are you sending cards to?

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest main, etc...

# Details

Explain your issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards).

**Comment by paulcam206** [comment]
@poonam0025 - would it be possible for us to see the card payload itself, after you've generated it?

We could also use some clarification here -- this is a bot written in C#, but you're seeing problems in Android Teams?

**Comment by poonam0025** [comment]
> @poonam0025 - would it be possible for us to see the card payload itself, after you've generated it?
> 
> We could also use some clarification here -- this is a bot written in C#, but you're seeing problems in Android Teams?

**Comment by poonam0025** [comment]
[json.txt](https://github.com/microsoft/AdaptiveCards/files/6078208/json.txt)


Reported issue in Note 5 pro, Note 7 pro,   Teamsversion : 1416/1.0.0.2021022202,calling version : 2021.02.01.29

**Comment by paulcam206** [comment]
Thanks @poonam0025 - I can repro the card not rendering in Android. @golddove, can you take a look? it literally renders blank:

![image](https://user-images.githubusercontent.com/16614499/109855646-68d2da00-7c0d-11eb-9124-e73726878b99.png)

**Comment by paulcam206** [comment]
I should probably note that the card renders and behaves correctly in the designer:

![image](https://user-images.githubusercontent.com/16614499/109856009-d5e66f80-7c0d-11eb-8ba4-75656d6fcd03.png)

**Comment by poonam0025** [comment]
yes ,in desktop teams  app  also  showing properly causing issue in android.

**Comment by jonmill** [comment]
@golddove - FYI that triage is approving this for 21.05
