### ISSUE TITLE
Data binding - Ability to untie view and data into separate json

### ISSUE THREAD

**Issue by spanwargithub** [microsoft/AdaptiveCards#547]
Untying the view and data gives the following benefits
1.	Potentially smaller size payload sent over the wire.
2.	We can cache the tokenized template JSON in CDN

e..g
  "type":"AdaptiveCard",
   "version":"0.5",
   "body":[
      {
         "type":"ColumnSet",
         "columns":[
            {
               "type":"Column",
               "items":[
                  {
                     "type":"Image",
                     "**url":"{headline-image}",**
                     "size":"auto"
                  }
               ]
            }
         ]
      },

**Comment by RebeccaAnne** [comment]
Databinding now exists! 
https://docs.microsoft.com/en-us/adaptive-cards/templating/
