### ISSUE TITLE
Is Body a mandatory or optional element in a card?

### ISSUE THREAD

**Issue by riarenas** [Microsoft/AdaptiveCards#548]
https://docs.microsoft.com/en-us/adaptive-cards/create/cardschema#adaptivecard 
indicates that Body is a mandatory property. The Html renderer and visualizer however allow cards without a body to be rendered. The renderers that use the shared model require the property to be present.

Which is the desired behavior?

**Comment by riarenas** [comment]
Body is now an optional property. Documentation needs to be updated.

**Comment by riarenas** [comment]
@matthidinger You were asking about this recently. I think at this point it's just a matter of updating the docs.

**Comment by matthidinger** [comment]
Docs don't show it as required now, should be good now
