### ISSUE TITLE
PopulateImageUrlAsync should account for errors during httpClient calls

### ISSUE THREAD

**Issue by riarenas** [Microsoft/AdaptiveCards#549]
XamlBuilder LN 466 httpClient->GetInputStreamAsync(imageUri, &getStreamOperation); should have an HR check for cases where there were problems with internet connection

**Comment by anbare** [comment]
Oh this is the same as #556, it's more than just checking for an hresult since it's async code, see that other issue thread which I put all the info in without realizing you had this one.

**Comment by riarenas** [comment]
Closing as duplicate of #556, which has a more thorough investigation.
