### ISSUE TITLE
[iOS][Rendering] Layout issues when padding is 0

### ISSUE THREAD

**Issue by jscalo** [microsoft/AdaptiveCards#5501]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] iOS

# Version of SDK

2.5.0

# Details

Since our UI designs often call for container elements to bleed all the way to the edge of the view, we'd like to be able to set the host config's `padding` to 0. However when we do this we encounter strange layout issues.

For example with this host config:

```
{
    "spacing" : {
        "padding" : 0
    }
}
```

And this card:

```
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "Container",
            "style": "accent",
            "items": [
                {
                    "type": "ColumnSet",
                    "height": "stretch",
                    "columns": [
                        {
                            "type": "Column",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "Some text!",
                                    "size": "extraLarge",
                                    "weight": "bolder",
                                    "horizontalAlignment": "center"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
```

We get the following: (The superview has a background color of green to help illustrate.)

![spacing = 0](https://user-images.githubusercontent.com/2917357/109868446-3afd8d80-7c2d-11eb-8066-9f7946a632e9.png)

As you can see, the card isn't filling its superview for some reason.

But if the spacing is set to 1 we get:

![spacing = 1](https://user-images.githubusercontent.com/2917357/109868472-42249b80-7c2d-11eb-843d-5fdf2b5208c8.png)

Now the card is filling its superview but of course the container has a 1 pt border around it.

**Comment by paulcam206** [comment]
@jwoo-msft - care to take a look?

**Comment by jwoo-msft** [comment]
@jscalo 
Thanks for report the issue. The issue is fixed. For more detail, check https://github.com/microsoft/AdaptiveCards/pull/5516.
cc. @paulcam206

**Comment by jscalo** [comment]
Thank you!
