### ISSUE TITLE
Will there be an AdaptiveCard control for XAML/UWP or is it only internal to Microsoft?

### ISSUE THREAD

**Issue by mdtauk** [Microsoft/AdaptiveCards#551]
Will UWP developers be able to add an AdaptiveCard control into their XAML, set it's Source property to some JSON, and create a HostConfig to fit their app?

Or is the UWP implementation only for those parts of the Windows Shell that Microsoft control (Live Tiles, Timeline Activities, Notifications)?

Unless I am missing something, it seems like you have to use Code to generate a card, which is then rendered as XAML at runtime?  No design-time experience?

I believe it should be available as a XAML control in the UWP Framework, so someone building an app can use it in a DataTemplate - Bind to it somehow, and use it to display rich content in lists, dashboards, etc

**Comment by matthidinger** [comment]
The current plan is to ship the XamlAdaptiveCardRenderer ([source code here](https://github.com/Microsoft/AdaptiveCards/tree/master/source/uwp)) as a beta nuget package in September, which will allow a developer to render Adaptive Cards inside their app. They will also be able to define their own Host Config that the renderer will use.

As for wrapping it inside a control and providing a design-time experience, we don't have any concrete plans yet, but it should be relatively straight forward to achieve, and I'd be happy to work with you or the community on a PR to enable it :)

**Comment by mdtauk** [comment]
Thank you for the response @matthidinger - I am just an enthusiast and design when it comes to Apps and C#/XAML but I am curious and interested, so I will have to reserve that to those with the talents, and ability to actually make it a reality.  And look forward to seeing how these Cards are rendered by the Shell points in a future Windows 10 update. 
 
Live Tiles may get much more flexible for drawing content, or the Windows Shell will heavily restrict the styling of these things.  Its going to be interesting to see it all come together.

Seeing Acrylic becoming part of the UWP implementation
![start-menu-neon 1](https://user-images.githubusercontent.com/7389110/29236302-b45cf428-7f00-11e7-94bc-d6b491939697.png)

with Vibrance as the iOS equivalent perhaps?
![vibrancy 1](https://user-images.githubusercontent.com/7389110/29236259-38a7aa26-7f00-11e7-9361-e4d68e1ba0c8.png)

**Comment by anbare** [comment]
Glad to see the enthusiast interest in the future of Start! Insider builds will be the place to keep looking for the latest! Closing this issue thread.
