### ISSUE TITLE
Data is getting wiped out once submit action taken on adaptive card

### ISSUE THREAD

**Issue by jayarau** [microsoft/AdaptiveCards#5515]
What version are you using? 
"adaptivecards": "^1.2.6",

We are using adaptivecards package with bot framework in spfx solution.
Reference link: https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-adaptivecards
# Details
Data is getting wiped out once submit action taken on adaptive card. We are using below adaptive card package:
"adaptivecards": "^1.2.6",

Issue
a. When a user provides inputs to cards all data are seen whatever user has provided as input.
b. As soon as a user submits an action button on that, a request is submitted to bot with all user input data.
c. An issue is all user input data are wiped out.

**Comment by RebeccaAnne** [comment]
@jayarau It sounds like you're submitting the card to the bot, and then receiving a new one, is that correct? If so, you would need to manually set the values on the inputs on the `value` property in the returned card.

**Comment by jayarau** [comment]
Hi @RebeccaAnne ,
Yes we are submitting input data provided to card to bot.

We have similar issue as mentioned in below bug
[https://github.com/microsoft/AdaptiveCards/issues/3870](url)

**Comment by jonmill** [comment]
@dclaux - could you take a look and see if this is the same issue as bug #3870? Thanks!

**Comment by dclaux** [comment]
I am not understanding the problem.

There is currently no way to refresh a card as a result of a Bot executing an Action.Submit. The Bot would have to send a new card back to the chat. Regardless, if that new card has to have the same inputs as the one that was interacted with and those inputs have to have the same values as those that were entered, the Bot is responsible for crafting the new card the right way by explicitly setting the "value" properties on the inputs, as @RebeccaAnne wrote above.

Aside from that, the JS SDK will not remove the values of the inputs after a user clicks an Action.Submit button.

Finally, the JS SDK is at version 2.10 now, so version 1.2.6 is quite outdated (and not maintained anymore)

**Comment by jonmill** [comment]
@jayarau - can you try updating your package version to the latest and see if this repros?

**Comment by jayarau** [comment]
@jonmill  We are trying with upgrade adaptive card package version. But As current fix, we are explicitly setting value on card rendered by bot-framework.

**Comment by RebeccaAnne** [comment]
Setting the values on the refreshed card is the right fix for this issue.
