### ISSUE TITLE
[.Net] [Unicode literals are escaped in if statements]

### ISSUE THREAD

**Issue by bradrivers-modality** [microsoft/AdaptiveCards#5518]
# Platform

- [ ] .NET

# Host

The host is a bot framework solution sending messages to Teams and emails to Outlook using the appropriate bot framework channels.

# Version of SDK

AdaptiveCards.Templating v1.1.0

# Details

I have the following Textblock in a template (it happens with AdaptiveCard version 1.0 - 1.2, haven't tried 1.3). Note the if statement, where the return values contain unicode literals..

```
{
      "type": "TextBlock",
      "text": "${if(IntTemplateProperty >= 0, IntTemplateProperty + ' % \u25b2', IntTemplateProperty + '%  \u25bc')}"
}
```

When I use the AdaptiveCards.Templating.AdaptiveCardTemplate.Expand method to populate the text property with the code below, it escapes the unicode literal string and sets text property *5% \\\\u25b2*. This means that when the card is sent (I've tried to Outlook and Teams) the value displays as *5% \\u25b2* rather than *5% ▲* as I would expect.

```
var model = new
  {
      IntTemplateProperty = 5
  };
var template = new AdaptiveCardTemplate(scenarioTemplate.Template);
var card = template.Expand(model);
```

But when you use the unicode literal as a static value, as in the example below, it displays correctly.

```
{
      "type": "TextBlock",
      "text": "5% \u25b2"
}
```

In the template I am using the literal ( *\u25b2* ) rather than the characters it self ( *▲* ) because the later doesn't render when sent to Outlook via bot framework email channel.

**Comment by paulcam206** [comment]
@jwoo-msft - care to take a look?

**Comment by jwoo-msft** [comment]
@paulcam206 
We deserialize the data and after expanding the template with the data, we serialize it back. The issue here is that what we deserialize is just the data portion, but when we serialize we serialize the data + template string in the text of TextBlock which is already in serialized form. There are few options, and I'm evaluating them.
