### ISSUE TITLE
[.Net] [v1.2 AdaptiveCardTemplating.Expand does not populate card payload]

### ISSUE THREAD

**Issue by bradrivers-modality** [microsoft/AdaptiveCards#5519]
# Platform

- [ ] .NET

# Author or host

The host is a bot framework solution sending messages to Teams and emails to Outlook using the appropriate bot framework channels.

# Version of SDK

AdaptiveCards.Templating v1.2.0

# Details

Since upgrading from version 1.1.0 to 1.2.0 the AdaptiveCards.Templating.AdaptiveCardTemplate.Expand method no longer populates the card payload with values from the data, the templating placeholders still exist.

Using AdaptiveCards.Templating v1.2.0 and following the [templating sdk docs](https://docs.microsoft.com/en-us/adaptive-cards/templating/sdk), example below:

```
var templateJson = @"
{
    ""type"": ""AdaptiveCard"",
    ""version"": ""1.2"",
    ""body"": [
        {
            ""type"": ""TextBlock"",
            ""text"": ""Hello ${name}!""
        }
    ]
}";

// Create a Template instance from the template payload
AdaptiveCardTemplate template = new AdaptiveCardTemplate(templateJson);

// You can use any serializable object as your data
var myData = new
{
    Name = "Matt Hidinger"
};

// "Expand" the template - this generates the final Adaptive Card payload
string cardJson = template.Expand(myData);
```

In version 1.2.0 this is the value of cardJson, I would expect *name* to be replaced with *Matt Hidinger*.

`{"type":"AdaptiveCard","version":"1.2","body":[{"type":"TextBlock","text":"Hello ${name}!"}]}`

In version 1.1.0 this is the value of cardJson.

{"type":"AdaptiveCard","version":"1.2","body":[{"type":"TextBlock","text":"Hello Matt Hidinger!"}]}

**Comment by jwoo-msft** [comment]
@bradrivers-modality Thanks for reporting this issue. It's now fixed pending review, and a new NuGet will get soon published, Thanks

**Comment by bradrivers-modality** [comment]
@jwoo-msft Great, thanks for fixing so quickly
