### ISSUE TITLE
RichTextBlock Schema Explorer - Include Color Options

### ISSUE THREAD

**Issue by alex-zwingli** [microsoft/AdaptiveCards#5521]
While the documentation clearly states and shows how colors are supported, it would be helpful if it listed which colors were supported. 
---
* URL: https://adaptivecards.io/explorer/RichTextBlock.html

**Comment by paulcam206** [comment]
I agree it's not clear how colors are supported -- in the interim, you can find the docs here: https://adaptivecards.io/explorer/TextRun.html

(the `inlines` property contains `TextRun`s)

**Comment by jonmill** [comment]
Tracked by #6316
