### ISSUE TITLE
Universal Action Model Schema Released and Documented

### ISSUE THREAD

**Issue by productboard-ac** [microsoft/AdaptiveCards#5523]
- [ ] Parsing and rendering (#3076)
- [x] Schema update (#5317)
- [X] Microsoft docs updates

**Comment by productboard-ac** [comment]
Link to feature: https://adaptivecards.productboard.com/feature-board/planning/features/5302870

**Comment by RebeccaAnne** [comment]
Closing this, with #3076 tracking the remaining work (javascript implementation)
