### ISSUE TITLE
[NET HTML] The search drop down menu with Cards behind the embed app content in Teams app\web

### ISSUE THREAD

**Issue by Koniksan** [microsoft/AdaptiveCards#5526]
# Platform
- [X] .NET HTML

# Details
The search drop down menu with Cards behind the embed app content in Teams app\web

**Expected behavior**
Drop-down is visible with correct z-index property 
![image](https://user-images.githubusercontent.com/15952613/109493668-e11a8d80-7a9d-11eb-9981-d190a499f695.png)

**Screenshots**
Drop-down is not visible
![image](https://user-images.githubusercontent.com/15952613/109493473-9a2c9800-7a9d-11eb-90c5-2cb6b5ae1475.png)

**Comment by Koniksan** [comment]
@paulcam206  Should I ask @siduppal  in other topic or just wait for response here ?

**Comment by paulcam206** [comment]
He should chime in -- if not I'll ping him offline :)

**Comment by Koniksan** [comment]
Is there any progress on it ?

**Comment by paulcam206** [comment]
I'll ping him again -- sorry for the delay 😬
