### ISSUE TITLE
[All][Validation] It would be useful if a field could be optionally Required, based on a specific Action button

### ISSUE THREAD

**Issue by HiltonGiesenow** [microsoft/AdaptiveCards#5537]
**What platform is your feature request related to? (Delete other platforms).**

All

**Is your feature request related to a problem? Please describe.**
Many Approval scenarios have Approve and Reject buttons, an a text box for comments. We often get requested by clients to make the Comments box 'optional' for an Approve, but 'required' for Reject (i.e. you can *choose* to add a comment for Approve, but if you need to Reject then you HAVE to give a comment).

**Describe the solution you'd like**
A possible solution would be to add a 'RequiredFields' value (or similar) to the Action.Execute (or Action.Submit) command

**Describe alternatives you've considered**
Two possible workarounds, but neither great:
1) use Action.ShowCard to show/hide a similar "Comments" box. It means an extra interaction for the user
2) send the response back to the bot, which would resend the card if Reject is clicked without a comment, with an added text message (like a red Error text)

**Comment by RebeccaAnne** [comment]
This functionality is tracked by #5392. The P2 proposal would cover this scenario.
