### ISSUE TITLE
[IOS/Android] Is there plan to support "Adaptive Card Templating SDKs" for IOS/Android

### ISSUE THREAD

**Issue by FelixZhang001** [microsoft/AdaptiveCards#5541]
I read the wiki for Adaptive Card Templating SDKs and find that it only show SDK for javascript and .Net. 
Just want to know if we have a plan to support the feature for IOS/Android?
https://docs.microsoft.com/en-us/adaptive-cards/templating/sdk

---
* URL: https://adaptivecards.io/explorer/

**Comment by paulcam206** [comment]
hello @FelixZhang001 - this work is currently being tracked here: https://portal.productboard.com/adaptivecards/1-adaptive-cards-features/c/61-templating-on-mobile-sdks

(you can use https://aka.ms/acroadmap/ to get to this page)
