### ISSUE TITLE
[Adaptive Cards] [Is there any way to make multilingual adaptive card?]

### ISSUE THREAD

**Issue by jychaaacha** [microsoft/AdaptiveCards#5550]
[Your detailed feedback here]

I am utilizing rendering SDK. (Android, Java script, iOS)
I want to use multilingual adaptive card, but rendering SDK doesn't support multilingual adaptive card.
I think it is because a data json doesn't work in rendering SDK.

Is there any other way to provide multilingual?
Or do you have a plan to support data json in rendering SDK?
---
* URL: https://adaptivecards.io/explorer/

**Comment by jonmill** [comment]
You can use templating to get almost all of the way there (depending on your scenario) if you control the end-to-end solution. If not, we don't currently support localization but definitely should.

**Comment by jychaaacha** [comment]
@jonmill If I use templating to support multilingual function, Is there any way to provide templating for android and ios? As I know, there is no templating SDK for android and ios. Is there any code to match and support templating in android and ios?

**Comment by jonmill** [comment]
Good question - we don't currently support templates for mobile...that is currently on our roadmap but we don't have a timeframe for it yet. If you need a multilingual card that supports mobile then we don't have direct support yet...I'd recommend adding support through your API layer (if possible) until we can build support for this case

**Comment by jychaaacha** [comment]
@jonmill Thanks for reply. Is there any sample code for support template in Android and iOS? Please provide if there is anything I can refer to for API development.

**Comment by jonmill** [comment]
Mobile templating support is on our roadmap but not currently supported. Sorry about that, we know it is painful and hopefully we'll be able to provide support there soon.
