### ISSUE TITLE
[Teams][Rendering] [Broken rendering of markup links on iOS / Android]

### ISSUE THREAD

**Issue by lindach167** [microsoft/AdaptiveCards#5553]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [x] Android
- [x] iOS

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.

Host - Teams Mobile

If you're an author, who are you sending cards to?

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest main, etc...

2.4.6

# Details

Explain your issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards).

With the given JSON payload with markup links, desktop renders it as expected, while on iOS / Android, there's an extra ".aspx)" being rendered.

[
[markupLinkBugJson.txt](https://github.com/microsoft/AdaptiveCards/files/6159660/markupLinkBugJson.txt)
](url)

Desktop render:

![image](https://user-images.githubusercontent.com/29580478/111537133-4e7a1f80-8728-11eb-860e-4f6b84af0890.png)

Mobile render:

![image](https://user-images.githubusercontent.com/29580478/111537167-56d25a80-8728-11eb-81c5-b52f2367aa10.png)

Note that this repros in the standalone visualizer app as shown above in addition to Teams Mobile clients.

**Comment by jwoo-msft** [comment]
it's our shared model markdown. the inner closing parenthesis matched with the outer parenthesis of mark down link.

**Comment by paulcam206** [comment]
This is by [design behavior](https://meta.stackexchange.com/questions/13501/links-to-urls-containing-parentheses) for Markdown. Have you tried escaping the `)` as `\)`?

**Comment by jwoo-msft** [comment]
@lindach167 in case, you missed @paulcam206's comments above.

**Comment by lindach167** [comment]
@paulcam206 @jwoo-msft escaping ) as \) does not have any effect. The more important thing is that this renders differently on mobile than it does on desktop (see the two screenshots in the bug). Developers who test against desktop gets an unexpected rendering behavior on mobile

**Comment by khanisak** [comment]
@lindach167 have you managed to find out the solution? 

I can confirm this issue too. Rendering of adaptive cards on android and ios broken when url have parenthesis. Escaping whole url include parenthesis doesn't work.
Adaptive cards renders well on desktop but not on teams mobile.

**Comment by lindach167** [comment]
@khanisak I have not found a workaround. This needs to be fixed in the SDK. @jwoo-msft @paulcam206 any updates for this issue?

**Comment by paulcam206** [comment]
I've got a line on a fix for this - should hopefully have something to show tomorrow
