### ISSUE TITLE
Add AdaptiveCards.Rendering.Wpf .NET NuGet package

### ISSUE THREAD

**Issue by stellarfoto** [microsoft/AdaptiveCards#5555]
- .NET WPF

In the DotNet Library, there is a package for .NET Core, but when you go to NuGet Packages, there is no AdaptiveCards.Rendering.Wpf.Core Package. I would like to add AdaptiveCards to a WPF .NET Core project.

Could someone add a reference to AdaptiveCards.Rendering.Wpf.Core into NuGet Library.

Thank you,

Greg Lelonek

**Comment by paulcam206** [comment]
We should look into what it would take for us to produce a .NET Core NuGet package.

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing for now. We may return to this in the future. Feel free to continue the conversation in this issue.

**Comment by p-hev** [comment]
Any thoughts on revisiting this? we really need it

**Comment by danielrouleau** [comment]
Agreed on the need for this still being here. With the community-focused effort on WPF in .NET moving forward, I wonder if a similar effort here would be beneficial. The wpf.core project seems to build and render well in limited testing and it would be preferable to not need to maintain a private fork to build this one nuget package.
