### ISSUE TITLE
[iOS][Sample App] [Focusing after input validation failure is not correct]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#5559]
# Platform

- [ ] iOS

# Details
Sample's app's content offset calculation logic needs to be re-visited after recent sample app changes.

**Comment by jonmill** [comment]
@jwoo-msft - is this a critical bug to take? What are the repercussions of this not being fixed?

**Comment by jwoo-msft** [comment]
> @jwoo-msft - is this a critical bug to take? What are the repercussions of this not being fixed?
this bug is due to the recent sample app changes (~ Feb). We need to fix this so we can demo the feature and help customers who may be debugging their issues by providing solid reference points.
