### ISSUE TITLE
UWP renderer crashes if HTTP image cannot be found

### ISSUE THREAD

**Issue by anbare** [Microsoft/AdaptiveCards#556]
If an image can't be found, like bad HTTP link or anything, the UWP renderer crashes uncatchably and crashes the parent app.

Repro payload

```json
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "0.5",
	"body": [
		{
			"type": "Image",
			"url": "http://adaptivecards.io/assets/Closed%20bug%2092x92.png",
			"size": "medium"
		}
	]
}
```

**Comment by anbare** [comment]
@riarenas this is likely that missing THROW_IF_FAILED, did you already fix that or want me to submit a pull request?

```c++
httpClient->GetInputStreamAsync(imageUri, &getStreamOperation);
```

**Comment by anbare** [comment]
Eh, seems it's not simply just that, adding a THROW_IF_FAILED it still crashes, investigating further

**Comment by anbare** [comment]
Figured out the source of the error, inside PopulateImageFromUrlAsync, one of the delegates will throw an error if the image download failed. But since no one is capturing that async result, it ends up as an unhandled exception.

![image](https://user-images.githubusercontent.com/13246069/29293258-53aee3a6-80ff-11e7-99cb-875eb0ed336e.png)

Maybe reporting the error via the imageLoadTracker will be the solution.

**Comment by anbare** [comment]
@matthidinger needs to decide on the final behavior of this.

Options are...

1) Have RenderAsync throw an exception when an HTTP image fails to load

2) Make RenderAsync return some sort of result that contains both the rendered card (without the image) and info like "2 images failed to load"

I've written the code for (1) in branch anbare/uwp-fix-image-errors, but (2) is likely the better solution so it would have to be slightly modified if we want that.

**Comment by anbare** [comment]
@matthidinger your vote on this?

We could always start with option 1 since the hosts like Action Center that we know about would choose that option to not display anything if image download fails, and later on we could add an advanced Render method which supports partial rendering and returning errors like image download failure.

Although another interesting question is whether buttons should still be displayed? Action Center currently will drop the adaptive XML portion if an image fails to download, but since buttons currently aren't part of adaptive toasts, the buttons still get displayed.

While I'm gone next week feel free to use my code in branch _anbare/uwp-fix-image-errors_ if we're going with option 1 since that's already coded up and I've tested that it works!

**Comment by matthidinger** [comment]
Also agree that throwing seems clumsy and bad, especially for non-exceptional failures like poor network connectivity. In our API review next week let's add this to the discussion. There are a couple ways we can go about this

**Comment by riarenas** [comment]
This issue is popping up more and more frequently. There are a few corner cases that are not captured with Andrew's fix, such as:
*Empty image URL.
*Invalid URL format,
*Lack of internet connectivity.
*No internet capability in calling app.

I'm working on top of Andrew's changes to address these issues. We have discussed a rework on how we handle image downloads, but that will require more comprehensive code changes. For now I'm patching our existing image downloader so that if one of this issues is present, the card won't be rendered at all. It's not ideal behavior, but I belive it's the best thing we can do for now to fix a lot of the issues our consumers have been reporting.

**Comment by anbare** [comment]
Nice! Agreed, we can always add a new method like RenderWithErrorInfo or something that will provide a half-rendered card with error info about failed images/etc. For now just failing completely is good enough for our existing scenarios.
