### ISSUE TITLE
[Android][Input Validation] [Error message is not cleared]

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#5563]
# Platform

What platform is your issue or question related to? (Delete other platforms).
- [ ] Android

# Details
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.3/Scenarios/InputFormWithLabels.json

1. click the submit button; error messages will appear for two places
2. fill the first field correctly. e.g. Hello, World
3. click the submit button; focus moves to the next input field correctly, however, the error message and the cue are not cleared.

**Comment by golddove** [comment]
@jwoo-msft what version is this on? I can't repro it from main:

![5563](https://user-images.githubusercontent.com/4442788/116619465-799e8400-a90e-11eb-8945-accd8c74ce0f.gif)

**Comment by jwoo-msft** [comment]
@golddove this must be part of the smoke test for our latest release, https://github.com/microsoft/AdaptiveCards/releases

**Comment by golddove** [comment]
@jwoo-msft tried the same payload using App Center apk, but wasn't able to repro. Please re-open if you're still seeing this.
