### ISSUE TITLE
[Android][iconSize is not honoured for iconUrl using resource resolver]

### ISSUE THREAD

**Issue by manujai** [microsoft/AdaptiveCards#5567]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Android

# Author or host

Host - Cisco WebEx

Cisco Webex

# Version of SDK

latest main

# Details

The `iconSize` host config field for `iconUrl` (inline) is not being honoured when resource resolver is used.

**Comment by paulcam206** [comment]
@golddove - care to take a look?

**Comment by golddove** [comment]
@paulcam206 yup, this is a known inconsistency between platforms (Android renderer only respects iconSize when iconPlacement is above). Will take up in 21.04

**Comment by paulcam206** [comment]
@golddove - do we have another bug tracking this already?
