### ISSUE TITLE
[Shared] Horizontal Alignment for ColumnSet not being returned from Shared Model

### ISSUE THREAD

**Issue by kishorepmr** [microsoft/AdaptiveCards#5568]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- Shared Model

# Author or host

Host - Cisco WebEx Teams

# Version of SDK

1.2

# Details

Horizontal Alignment property of ColumnSet not being able get the property from Shared library of adaptive cards

**Comment by paulcam206** [comment]
@kishorepmr - can you elaborate a little bit on what you mean by "Shared model"? Are you referring to the .NET `AdaptiveCards` library, or the C++ Shared Model (`source/shared/cpp/ObjectModel`)?

**Comment by kishorepmr** [comment]
The C++ Shared Model (source/shared/cpp/ObjectModel) @paulcam206

**Comment by paulcam206** [comment]
tracking work in #5822
