### ISSUE TITLE
[.Net] Newtonsoft.Json 13.0.1 (latest) version explicitly not supported

### ISSUE THREAD

**Issue by 951p** [microsoft/AdaptiveCards#5575]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [X] .NET HTML

# Author or host

Developer 

# Version of SDK

What version are you using? NuGet 1.2.1 -- (latest)

# Details

Latest nuget doesn't support (explicitly prevents) Newtonsoft.Json 13.0.1 (latest) version
![image](https://user-images.githubusercontent.com/5575984/112303390-9b06b300-8c72-11eb-99b6-9ce9e25828b4.png)

**Comment by paulcam206** [comment]
thanks @951p - we'll take a look :)

**Comment by andrekiba** [comment]
Which is plan for this? it is really a problem because it prevents to use the programmatically approach to write cards in lot of new projects. Why was the #5671 closed that is maybe more general than this? Thank you!

**Comment by andrekiba** [comment]
up

**Comment by ig-jb** [comment]
This is forcing package downgrades on other projects -- would be great if it could be addressed soon.

**Comment by AlexandreArpin** [comment]
I believe this bug should be reopened given that the fix was reverted.

**Comment by brittonQ** [comment]
> This is forcing package downgrades on other projects for me, I imagine many others will have similar problems -- would be great if it could be addressed soon.

It's definitely a problem, a growing problem.  Simply changing the Newtonsoft.Json version dependency to 13.0.1 on my local versions .nuspec fixed the issue and it seemed to work fine.  But perhaps there are unseen side effects.

**Comment by austinw-fineart** [comment]
Why does AdaptiveCards even have a dependency on Newtonsoft.Json? If you're going to implement serialization then it should be in its own package, like how [NodaTime](https://www.nuget.org/packages/NodaTime/) has [NodaTime.Serialization.JsonNet](https://www.nuget.org/packages/NodaTime.Serialization.JsonNet/). That way you can also switch to [System.Text.Json](https://www.nuget.org/packages/System.Text.Json/), which I'm surprised hasn't happened yet,

**Comment by AlexandreArpin** [comment]
**A PR to revert the issue was opened, but it was never merged.** 

I am sorry for the confusion my comment caused.

As far as I know, the next version of AdaptiveCards will have unpinned versions.

**Comment by brittonModuleQ** [comment]
Hi @paulcam206 , can you confirm this will be addressed in the next version?  Much appreciated.

**Comment by jonmill** [comment]
This issue should be fixed in the latest .NET release
