### ISSUE TITLE
[MS Teams][Input.Time] The time value of Input.Time does not appear normally.

### ISSUE THREAD

**Issue by cleans2002** [microsoft/AdaptiveCards#5580]
# Platform
- [ ] Python

# Author or host
- [ ] MS Teams

Hi. I'm using MS Teams' Bot service. I am using an adaptive card including Input.Time as input, but the time value of Input.Time is not normal.

I chose '오후 3:00'.('오후' is 'PM'.) I think it should come out at 15:00, but the result came out at 03:00.
![image](https://user-images.githubusercontent.com/41402699/112404270-63bc0300-8d53-11eb-80f1-d9553a4b143d.png)
![image](https://user-images.githubusercontent.com/41402699/112404116-150e6900-8d53-11eb-9941-b2e20acb6ed2.png)

And when I entered '3:00 오후' directly, the result came out as 15:00.
![image](https://user-images.githubusercontent.com/41402699/112404223-4f780600-8d53-11eb-9e31-1af2a2248786.png)
![image](https://user-images.githubusercontent.com/41402699/112404139-235c8500-8d53-11eb-8a72-e7273ed814ce.png)

Since my language is Korean, I am wondering if this error occurs or if there is a solution.

**Comment by paulcam206** [comment]
@cleans2002 - interesting... I took a look at [one of our samples](https://adaptivecards.io/samples/Inputs.html) while browsing in Korean, and it *appears* to have the correct submit behavior (specifically looking at the `TimeVal` portion of the submit payload). can you confirm?

if it does indeed behave correctly there, this might be an issue in Teams.

**Comment by cleans2002** [comment]
> @cleans2002 - interesting... I took a look at [one of our samples](https://adaptivecards.io/samples/Inputs.html) while browsing in Korean, and it _appears_ to have the correct submit behavior (specifically looking at the `TimeVal` portion of the submit payload). can you confirm?
> 
> if it does indeed behave correctly there, this might be an issue in Teams.

Thank you for answer.

As a result of checking the sample, if the value is forcibly registered, the value is displayed normally. 
![image](https://user-images.githubusercontent.com/41402699/112586464-33ea2980-8e3f-11eb-9690-d9213669385b.png)
![image](https://user-images.githubusercontent.com/41402699/112586480-3ba9ce00-8e3f-11eb-8c3c-64a4a579461b.png)
![image](https://user-images.githubusercontent.com/41402699/112586490-41071880-8e3f-11eb-95df-d0490341d76d.png)

However, if the time is changed, the same error occurs.
![image](https://user-images.githubusercontent.com/41402699/112586633-81669680-8e3f-11eb-9a3b-78bab564a859.png)
![image](https://user-images.githubusercontent.com/41402699/112586627-7ca1e280-8e3f-11eb-8074-130f16545ae3.png)

Is it possible to change the value type of Input.Time to 24-hour format?

**Comment by jonmill** [comment]
@siduppal - does Teams override the base rendering of the Time picker?

**Comment by Nikitha-MSFT** [comment]
We are not able to repro the issue at our end? Are you facing this for particular users or are you facing issue with all the user is using your bot? Could you please try out signin/signout?

**Comment by Nikitha-MSFT** [comment]
@jonmill - Could you please share an update

**Comment by jonmill** [comment]
@cleans2002 - not sure if you saw @Nikitha-MSFT's questions...could you please provide some additional information to help us diagnose this issue? Thanks!

**Comment by cleans2002** [comment]
Hello

The same error is happening over and over again now, and all users are experiencing it.
In short,
1. I am using Input.Time of the adaptive card.
2. I speak Korean, and '오후' in the image above means PM.
3. In Input.Time, it is entered as '오후 3:00', but the result is 03:00.
4. If you send the text'afternoon' after 3:00 (like '3:00 오후'), the result is 15:00.

I tried logging out/logging in, but it shows the same symptoms.

**Comment by jonmill** [comment]
Thanks for clarifying @cleans2002. @Nikitha-MSFT, do the repro steps provided above help repro the issue?

**Comment by Nikitha-MSFT** [comment]
Checking it will update soon

**Comment by Nikitha-MSFT** [comment]
Raised a Bug. We are tracking it internally. We don't have ETA to share when it will be fixed.

**Comment by Nikitha-MSFT** [comment]
Internally team is working on the bug- We are tracking the bug - will update once it is fixed. We don't have ETA to share when it will be Fixed.

**Comment by Nikitha-MSFT** [comment]
Bug is Resolved now, we have tested this at our end, could you please also check and confirm?

**Comment by jisuneom** [comment]
@Nikitha-MSFT , Hi! I'm also developing the Bot service of MS Teams by setting it in Korean. I also made an adaptive card using Input.Time, but even though I entered it as P.M, it still came out as A.M. Can you check it one more time?
![1](https://user-images.githubusercontent.com/54271526/128990694-fc3585a5-78a3-456b-9709-d69b4b135df8.PNG)
![2](https://user-images.githubusercontent.com/54271526/128990696-f86c1f8d-ca5a-4df8-bbd1-645e7329108b.PNG)
