### ISSUE TITLE
[javascript] Action.Execute doesn't expose fallback, can't be set for serialized object.

### ISSUE THREAD

**Issue by tomlm** [microsoft/AdaptiveCards#5582]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] JavaScript

# Author or host

Author

If you're an author, who are you sending cards to?
ACN

# Version of SDK
npm 2.9

# Details

I am trying to create a card using the SDK and then serialize it as a response to client. 

```javascript
 let action = new ExecuteAction();
        action.title = "Roll";
        (<any>action).fallback = SubmitAction.JsonTypeName;
        action.data = {
            type: ActionContentType,
            id: this.runtime.documentId,
            verb: "roll",
            // data: model
        };
        ac.addAction(action);
```
You can see from documentation https://adaptivecards.io/explorer/Action.Execute.html, I am supposed to be able to specify a fallback.
1,  fallback property is missing
2. if I set the property on the object by using < any > it doesn't get serialized.
There appears to be no way for me to use the object model to create the card and serialize it using fallback.

**Comment by paulcam206** [comment]
@dclaux - care to take a look?

**Comment by dclaux** [comment]
@tomlm that's by design. `fallback` isn't in the SDK's object model, it's just read and interpreted during parse time. The main reason for that was to not use memory to store something that is used only at parse time. But in turn, that means that indeed as of now if you want to generate a card payload that includes `fallback` you can't user the OM.

If you think this is sorely missing, I can add support for it later.

**Comment by dclaux** [comment]
@tomlm actually there should be a way for you to do what you want:
```typescript
GlobalSettings.enableFullJsonRoundtrip = true;

let executeAction = new ExecuteActin();
// Setup your ExecuteAction the way you want

// Declare your fallback action in pure JSON
let fallbackAction = {
  type: "Action.Submit",
  data: {
    ...
  }
}

executeAction.setCustomProperty("fallback", fallbackAction);
```

Give that a try and let me know if you're unblocked.

**Comment by jonmill** [comment]
This is a great find; we'll add it to our design discussion to make sure we spec out what we need to do here on all platforms

**Comment by jonmill** [comment]
Fallback is currently not heavily utilized, documented, and is not being actively maintained at this point; the current guidance is to avoid fallback for the time being
