### ISSUE TITLE
[UWP] CustomActionWrapper and CustomElementWrapper are not copying all relevant properties

### ISSUE THREAD

**Issue by chriche-ms** [microsoft/AdaptiveCards#5586]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] UWP

# Author or host

Author and host. Cortana in Windows - app is both an author and host.

# Version of SDK

NuGet 2.1.0

# Details

The CustomActionWrapper and CustomElementWrapper types are not wrapping/copying all relevant properties from the custom type. A quick check suggests the following properties are being ignored.

CustomElementWrapper:

- Height
- IsVisible
- Requires
- Fallback
- FallbackType

CustomActionWrapper:

- IconUrl
- Style
- Requires
- Fallback
- FallbackType

**Comment by paulcam206** [comment]
@RebeccaAnne - care to take a look?

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.
