### ISSUE TITLE
Input controls are not correctly rendered in .net html renderer

### ISSUE THREAD

**Issue by zhusongm** [Microsoft/AdaptiveCards#559]

**Comment by zhusongm** [comment]
I'm going to fix it; don't have the permission to assign it to myself.

**Comment by matthidinger** [comment]
Hi @zhusongm are you still seeing this? I've made some updates to the HTML renderer recently and if you provide more context I can look into this

**Comment by zhusongm** [comment]
That's the work item I created for myself when I was working on those
controls. Guess I forgot to close them:).

**Comment by matthidinger** [comment]
Cool, I'll close this then 👍
