### ISSUE TITLE
[Teams][Rendering] [Backslash escape special characters not working as expected on iOS / Android]

### ISSUE THREAD

**Issue by lindach167** [microsoft/AdaptiveCards#5590]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Android
- [ ] iOS

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.

Host - Teams Mobile

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest main, etc...

latest main

# Details

See attached card JSON, escaping special characters work as expected on web viewer, but not working on iOS / Android
[escapeSpecialCharsJson.txt](https://github.com/microsoft/AdaptiveCards/files/6215190/escapeSpecialCharsJson.txt)

Card render on desktop:
![image](https://user-images.githubusercontent.com/29580478/112711695-8e0edd00-8e87-11eb-9bac-7fe2f82bfa38.png)

Card render on mobile:
![image](https://user-images.githubusercontent.com/29580478/112711704-a121ad00-8e87-11eb-9c09-b5ee6fc5f4b3.png)
![image](https://user-images.githubusercontent.com/29580478/112711708-a8e15180-8e87-11eb-93f0-986a85783a92.png)

**Comment by paulcam206** [comment]
I'm guessing this is either more text-handling differences with web or something markdown related. @golddove - can you take a look?

**Comment by jonmill** [comment]
@paulcam206 - I think there is a larger discussion to be had here...let's circle up about this offline

**Comment by jonmill** [comment]
Tracked by #1984
