### ISSUE TITLE
[MS Teams][Input.Date] [Max and min attributes are not working with input.Date]

### ISSUE THREAD

**Issue by jisuneom** [microsoft/AdaptiveCards#5602]
# Platform
- Python

# Author or host
- MS Teams

# Details
I'm using a bot for Microsoft teams.
I set the "min" to today because I want to disable the previous dates as of today, but in MS Teams Bot service, the previous dates are not disabled, also they are clicked and "Action.Submit" is worked.

With the same json, in the adaptive cards designer it is works, but it is not working in the Bot for Microsoft teams.

- **JSON**
```
{ "type": "AdaptiveCard", "version": "1.2", "body": [ { "type": "Container", "style": "emphasis", "items": [ { "type": "ColumnSet", "columns": [ { "type": "Column", "items": [ { "type": "TextBlock", "weight": "Bolder", "text": "Alarm", "wrap": true, "horizontalAlignment": "Center" }, { "type": "ColumnSet", "columns": [ { "type": "Column", "width": "auto", "items": [ { "type": "TextBlock", "text": "Date", "wrap": true } ], "spacing": "Large", "verticalContentAlignment": "Center" }, { "type": "Column", "width": "stretch", "items": [ { "type": "Input.Date", "min": "2021-03-30", "id": "target_day" } ] }, { "type": "Column", "width": "auto", "items": [ { "type": "TextBlock", "text": "Tme", "wrap": true } ], "verticalContentAlignment": "Center" }, { "type": "Column", "width": "stretch", "items": [ { "type": "Input.Time", "id": "target_time" } ] } ] } ], "width": "stretch" } ] } ], "bleed": true }, { "type": "ActionSet", "actions": [ { "type": "Action.Submit", "title": "Save" } ] } ], "$schema": "http://adaptivecards.io/schemas/adaptive-card.json" }
```

- **in Designer** (https://adaptivecards.io/designer/)
![image](https://user-images.githubusercontent.com/54271526/112945266-05d25580-916f-11eb-8efa-f70dc8f43730.png)

- **in Bot for Microsoft teams**
![image](https://user-images.githubusercontent.com/54271526/112947223-809c7000-9171-11eb-9e2a-dde81a36611a.png)

**Comment by jwoo-msft** [comment]
@jisuneom, can you tell us which platforms android, iOS, desktop were used?

**Comment by jisuneom** [comment]
> @jisuneom, can you tell us which platforms android, iOS, desktop were used?

@jwoo-msft , I used desktop.

**Comment by jonmill** [comment]
@siduppal - is Teams overriding the default Date renderer here?

**Comment by Sridevi-MSFT** [comment]
@jisuneom , I am able to repro the issue taking this for internal discussion with team and will get back to you.

**Comment by Sridevi-MSFT** [comment]
@jisuneom, We have raised a bug for this issue, concerned engineering team is working on it.

**Comment by jisuneom** [comment]
@Sridevi-MSFT Thank you!! If the issue is resolved, Could you please share it??

**Comment by Sridevi-MSFT** [comment]
@jisuneom - We will update you immediately once we get any input from Engineering team.

**Comment by Sridevi-MSFT** [comment]
@jisuneom - This issue has been fixed and the fix is rolling in the internal rings. We have verified that internally and I will keep you updated once it will available publicly. Currently we don’t have any ETA to share.
