### ISSUE TITLE
[Android][MS-Teams] [Input.Text]When user taps on Input.Text, it only has the focus for a second, then it loses its focus. User can not type anything there.

### ISSUE THREAD

**Issue by MengliElmendorf137** [microsoft/AdaptiveCards#5617]
# Platform

What platform is your issue or question related to?
- [ ] Android

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.
Host - Teams Mobile

# Version of SDK
latest main

# Details
When user taps on Input.Text, it only has the focus for a second, then it loses its focus. Keyboard is not opening up as well. User can not type anything there.
Please see the attached video for more information

https://user-images.githubusercontent.com/81446141/113601729-b62cd780-960f-11eb-8e97-89184a4c77f7.mp4

**Comment by paulcam206** [comment]
@golddove - do you see any issues on our side? might be teams integration...

**Comment by Lorenzo-MWF** [comment]
I'm having the same issue on both Android and iOS

**Comment by leonkyr** [comment]
+1

**Comment by golddove** [comment]
@paulcam206 text inputs don't exhibit this in our sample app. Double-checked with the last few releases.

**Comment by golddove** [comment]
@siduppal can you repro this on your end

**Comment by Mamatha-MSFT** [comment]
@golddove I will repro at my end and will let you know.

**Comment by lindach167** [comment]
> @siduppal @lindach167 can your team repro this on your end

Yes, @MengliElmendorf137 from my team opened this issue from bug being reported in Teams mobile.

**Comment by golddove** [comment]
@Lorenzo-MWF you mention it works everywhere except group chats on the mobile app. Does that mean that it works correctly in other parts of the mobile app (e.g. in a channel)?

**Comment by Lorenzo-MWF** [comment]
> @Lorenzo-MWF you mention it works everywhere except group chats on the mobile app. Does that mean that it works correctly in other parts of the mobile app (e.g. in a channel)?

Works fine in channels and in one on one chats.
I've only seen this issue in group chats.

**Comment by karthikgopal36** [comment]
This issue has been fixed recently in Teams. Focus was enabled only for Media card type, so user unable type anything on the RIchText_Html card type. We have enabled the focus for this as well.
