### ISSUE TITLE
Bot Error in SDK 3.1 C# .NET Adaptive cards

### ISSUE THREAD

**Issue by ctharmon722** [microsoft/AdaptiveCards#5624]
When adding a card into our deployed bot, our bot no longer works. Sending us this error
Request URL: https://XXXXXXX.azurewebsites.net/api/messages Request name: GET /api/messages Response code: 405

We made this carding using the adaptive dialog card designer. Not sure where to even start with such a general error. Any suggestions on where to start would be useful.

If you're an author, who are you sending cards to?

I created a welcome card for my bot to display to the user. To create this card I used the adaptive dialog card designer found here 
https://adaptivecards.io/designer/

# Version of SDK

SDK 3.1 .NET

**Comment by jonmill** [comment]
hi @ctharmon722 - is this error coming from the bot or is your app that is rendering the card throwing this error? Can you provide a code sample of the card itself and how you're rendering it? Thanks!

**Comment by jonmill** [comment]
Closing due to not enough info to proceed
