### ISSUE TITLE
[.NET][Accessibility] Support heading navigation

### ISSUE THREAD

**Issue by golddove** [microsoft/AdaptiveCards#5629]
# Platform

- [ ] .NET WPF

# Version of SDK

`main`

# Details

Narrator supports navigation by headings. See [support article](https://support.microsoft.com/en-us/windows/chapter-5-navigation-68941680-3245-6ef5-5012-0674b8b6fc59) that describes how to cycle through navigation modes.

Text with `style: heading` receive the appropriate accessibility flags on other platforms to support this mode of navigation, including UWP XAML. However, the .NET WPF renderer doesn't seem to offer this support (see details in #5626).

Consult with accessibility team to determine if there is a workaround, or close this as external.

**Comment by jonmill** [comment]
@golddove - is this issue the same as #5479 or is it a different issue?

**Comment by golddove** [comment]
@jonmill yeah, didn't realize that existed when I created this. Shall I close this one and move the description there?

**Comment by jonmill** [comment]
@golddove - let's keep one issue open for this...if we need to add additional info to the previous bug, then please add it there :)
