### ISSUE TITLE
UWP renderer returns UIElement instead of FrameworkElement

### ISSUE THREAD

**Issue by anbare** [Microsoft/AdaptiveCards#563]
The renderer API's method signature returns a UIElement, but the actual item we're returning is a FrameworkElement...

Might as well change the method signature to return the more-specific FrameworkElement (which extends UIElement).

Natasha from Skype UWP had to actually cast the returned result to FrameworkElement since they need to set it as the content of a ContentPresenter, and ContentPresenter requires a FrameworkElement.

**Comment by riarenas** [comment]
Seems completely reasonable.
