### ISSUE TITLE
[Documentation] Some optional properties' default values are not documented

### ISSUE THREAD

**Issue by golddove** [microsoft/AdaptiveCards#5643]
# Platform

N/A

# Version of SDK

latest

# Details

[Column](https://adaptivecards.io/explorer/Column.html) width's default is not documented, for example. We should check if there are any other gaps.

**Comment by jonmill** [comment]
@golddove - what is the urgency of this issue? Are you currently working on this?

**Comment by golddove** [comment]
@jonmill Cisco didn't say it is urgent, but they're writing a renderer, so an accurate schema/doc would ensure they stay consistent with our renderers

**Comment by jonmill** [comment]
Gotcha - have you accounted for the work this milestone (21.04) or is this work not currently accounted for yet?

**Comment by golddove** [comment]
Not yet, was brought up during yesterday's call

**Comment by jonmill** [comment]
Tracked as part of #6316
