### ISSUE TITLE
How to Create a custom function in jQuery when click in buttons in Adaptive card  ?

### ISSUE THREAD

**Issue by mohd3wamleh** [microsoft/AdaptiveCards#5651]
i try to create a function when i click in buttons in adaptive card -----> hide the card but isn't working 

when i do it in any different buttons outside the card is working

why can't create a function of buttons inside the adaptive cards?

**Comment by jonmill** [comment]
hi @mohd3wamleh - can you please provide a code sample and additional information about the issue you're facing?

**Comment by mohd3wamleh** [comment]
`    public static Attachment CreateAdaptiveCard()
        {
            AdaptiveCard card = new AdaptiveCard();

            string imgName = @"logo.png";
            string currentDirectory = System.IO.Directory.GetCurrentDirectory();
            string[] fullFilePath = System.IO.Directory.GetFiles(currentDirectory, imgName, SearchOption.AllDirectories);

            //https://ash-chatbot-5npgsta.azurewebsites.net/wwwroot/ChatBotAssets/img/logo.png

            var uri = new System.Uri(currentDirectory + "\\" + imgName);
            var converted = uri.AbsoluteUri;

            // Body content  
            card.Body.Add(new AdaptiveImage()
            {
                //http://paisbot.eastasia.cloudapp.azure.com/UploadedImages/alsayer-logo.png
                //https://brandloungeme.com/wp-content/uploads/2017/07/logo-Al-Sayer.png
                //https://brandloungeme.com/wp-content/uploads/2017/07/logo-Al-Sayer.png
                Url = new System.Uri(/*fullFilePath.FirstOrDefault()*//*"https://www.jobawy.com/wp-content/uploads/2019/05/1880559_logo_1554268728_n.png"*/"https://chat.alsayergroup.com/alsayer-logo.png")
                ,
                Size = AdaptiveImageSize.Stretch,
            });

            card.Actions.AddRange(new List<AdaptiveSubmitAction>()
            {
                new AdaptiveSubmitAction()
                 {
                     Title = TextResource.LocationAndTiming,
                     Data = TextResource.LocationAndTiming
                 },
                new AdaptiveSubmitAction()
                 {
                     Title = TextResource.SalesPromotion,
                     Data = TextResource.SalesPromotion
                 },
                new AdaptiveSubmitAction()
                {
                     Title = TextResource.VehicleService,
                     Data = TextResource.VehicleService
                 },
            });
           
            card.Actions.AddRange(new List<AdaptiveSubmitAction>()
            {
                new AdaptiveSubmitAction()
                 {
                     Title = TextResource.VehicleDelivery,
                     Data = TextResource.VehicleDelivery
                 },
                new AdaptiveSubmitAction()
                 {
                     Title = TextResource.ContactUs,
                     Data = TextResource.ContactUs
                 }
            });

            // Create the attachment with adapative card.  
            Attachment attachment = new Attachment()
            {
                ContentType = AdaptiveCard.ContentType,
                Content = JsonConvert.DeserializeObject(JsonConvert.SerializeObject(card))
            };
            return attachment;
        }`
this code for the card from bot to frontend .
requirements : this card i want to hide when i click in any button in this card 
issue: when i write a function in jQuery the code doesn't have any response 
 $(".ac-pushButton").bind("click",function(){
            $( ".webchat__row.attachment" ).last().css( "display", "none" );
        }) 

when i create this function in any other button is working fine but dose not work when i create in buttons inside the adaptive card 

and thank you so much

**Comment by jonmill** [comment]
@dclaux - does the nodejs renderer support jQuery handlers or should @mohd3wamleh use the built-in mechanism to handle the action clicks?

**Comment by dclaux** [comment]
To handle an action button in an Adaptive Card, you need to implement an `onExecuteAction` handler. Please refer to the documentation: https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/javascript/actions

**Comment by jonmill** [comment]
Thanks David! The solution is to use the built-in handlers; we do not support using jQuery handlers out-of-box.
