### ISSUE TITLE
Provide a webpack bundle that excludes the markdown-it dependency

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#566]
The dist version of adaptive-cards.js currently weighs in around 300k. `markdown-it` is consuming about 253k of that without the the minified version, which is wasted space for folks who plan to replace the markdown processing with their own library.

Also we should make sure we're using the minified version of markdow-it.

**Comment by dclaux** [comment]
Unbundling is easy technically, but it opens the door of various hosts inconsistently rendering markdown.

The minified version of markdown-it is only 100k. I don't think we have a minified version of the adaptive library yet, but maybe it would make sense to look at its size. It seems it would be around 125k. What's our size target?

**Comment by danmarshall** [comment]
I have an opinion about "young" libraries - just my opinion and I'm ok if others do not agree :) which is not to minify until some level of maturity. Bugs are easier to trace in fully commented debuggable code which helps the community to self-support and contribute.
If someone is sensitive to download size, they are of course free to minify their own deployment.

Also, React has set a good example here by shipping both debug and production versions of their library.

**Comment by danmarshall** [comment]
Exposing the markdown-it library is another option. This is the strategy in WebChat, which [exposes the AdaptiveCards library as a global](https://github.com/Microsoft/BotFramework-WebChat/blob/master/AdaptiveCards.md#optional-embed-without-webpack).
