### ISSUE TITLE
[AuthenticationBot, TeamsAuth] sign in button not clickable on Microsoft teams

### ISSUE THREAD

**Issue by shereenfathy** [microsoft/AdaptiveCards#5663]
Hello,
I'M trying to test the AuthBot and i did all the steps and it works fine when i test it in the webchat but when i test it on Microsoft teams the sign in button on click doing nothing

**Comment by jonmill** [comment]
Can you please provide the additional information that is requested in the bug template?

**Comment by shereenfathy** [comment]
@jonmill  I fixed it by adding "token.botframework.com" to valid domains in the app manifest for teams.
