### ISSUE TITLE
[Javascript Renderer][Formatting]Markdown Formatting not Applied

### ISSUE THREAD

**Issue by HiltonGiesenow** [microsoft/AdaptiveCards#5664]
# Platform

- [ x] JavaScript

# Author or host

Both

# Version of SDK

2.9.0

# Details

I'm creating a web page to host some adaptive cards, and I'm rendering the cards fine, but I see that **Bold** and _Italics_ rendering don't do anything. To put it differently, I can render the Adaptive Card, but the Markdown is not doing anything in the Javascript renderer

**Comment by scottlovegrove** [comment]
@HiltonGiesenow Have you told the renderer what markdown parser to use? https://github.com/Microsoft/AdaptiveCards/tree/main/source/nodejs/adaptivecards#supporting-markdown

I added markdown-it to our web app and markdown renders just fine.

**Comment by HiltonGiesenow** [comment]
didn't spot but that will look into it, thanks @scottlovegrove
