### ISSUE TITLE
[.NET] AdaptiveCards nuget not support Newtonsoft.Json 13.0.1

### ISSUE THREAD

**Issue by vmadurga** [microsoft/AdaptiveCards#5671]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] .NET

# Author or host

Developer

# Version of SDK

What version are you using? AdaptiveCards v2.7.1

# Details

Latest nuget doesn't support Newtonsoft.Json 13.0.1 version
![imagen](https://user-images.githubusercontent.com/25466105/114832386-b75bc280-9dce-11eb-9ad7-ae7e42bc5d42.png)

**Comment by jonmill** [comment]
Dupe of #5575
