### ISSUE TITLE
[ActionSet] [HorizontalAlignment]

### ISSUE THREAD

**Issue by scottlovegrove** [microsoft/AdaptiveCards#5672]
There is no mention in the schema documentation about the HorizontalAlignment property of ActionSet.

We are looking at building a custom renderer and trying to work out what we need, and looking at some AdaptiveCard code we've written in nodejs, we use `ActionSet.horizontalAlignment` and it does actually make a difference in our rendered cards in our web app. 

Is this an omission on the documentation? Or is this something we shouldn't be using?

---
* URL: https://adaptivecards.io/explorer/ActionSet.html

**Comment by jonmill** [comment]
This looks to be an undocumented JS feature that is not available on the other platforms, so this is something that should not be included in custom renderers.
