### ISSUE TITLE
[Outlook][Actions] Calls to Microsoft Graph API not working

### ISSUE THREAD

**Issue by ms-jptoupin** [microsoft/AdaptiveCards#5674]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- Outlook Online and Outlook Desktop

# Author or host

Author

If you're an author, who are you sending cards to? **Myself**

# Version of SDK

Not using SDK. I'm using the [Actionable Message Designer](https://amdesigner.azurewebsites.net/).

# Details

### STEPS TO REPRODUCE

1. Copy this JSON Payload in the [Actionable Message Designer](https://amdesigner.azurewebsites.net/) (make sure to replace [INSERT-PERSONAL-EMAIL-HERE] and [INSERT-BEARER-HERE] tags):
```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "ActionSet",
            "id": "54c64d02-0b5a-6308-4e06-a8b5a0a04c63",
            "actions": [
                {
                    "type": "Action.Http",
                    "id": "d8b86e97-4921-94fe-5f0f-2f9994a0007a",
                    "title": "Send Email to Myself",
                    "url": "https://graph.microsoft.com/v1.0/me/sendMail",
                    "method": "POST",
                    "style": "positive",
                    "isPrimary": true,
                    "body": "{ \"message\": { \"subject\": \"Meet for lunch?\", \"body\": { \"contentType\": \"Text\", \"content\": \"The new cafeteria is open.\" }, \"toRecipients\": [{ \"emailAddress\": { \"address\": \"[INSERT-PERSONAL-EMAIL-HERE]\" } }] }, \"saveToSentItems\": \"false\" }",
                    "headers": [
                        {
                            "name": "Authorization",
                            "value": "Bearer [INSERT-BEARER-HERE]"
                        },
                        {
                            "name": "Content-Type",
                            "value": "application/json"
                        }
                    ]
                }
            ]
        }
    ],
    "padding": "None",
    "@type": "AdaptiveCard",
    "@context": "http://schema.org/extensions"
}
```

2. Click button "Send" (top right corner)
3. Navigate to your Outlook Online or Outlook Desktop and display the message (you should see an Adaptive Card with a "Send Email to Myself" button)
4. Click the button

### CURRENT BEHAVIOR
I get this error:
![image](https://user-images.githubusercontent.com/68490254/114901177-8b4a3c80-9de2-11eb-8247-0e185c672343.png)

### EXPECTED BEHAVIOR
An email with subject "Meet for lunch?" should be sent to my personal email

### IT'S NOT THE BEARER
Using the exact same Bearer <ACCESS-TOKEN> in Postman, I'm able to send the email.
![image](https://user-images.githubusercontent.com/68490254/114903025-60f97e80-9de4-11eb-8e05-cdc60f05c80e.png)

**Comment by jonmill** [comment]
@dclaux - do you have the right contact on the Outlook team for this bug?

**Comment by ms-jptoupin** [comment]
Thank you @jonmill

**Comment by ms-jptoupin** [comment]
@jonmill, @dclaux Any updates on this?

**Comment by dclaux** [comment]
Could you please send an email to the Outlook Actionable Message support address at onboardoam@microsoft.com? They do not monitor this repository.

**Comment by ms-jptoupin** [comment]
Here's the response from the onboardoam@microsoft.com :
```
Subject: Re: [EXTERNAL] [Outlook][Actions] Calls to Microsoft Graph API not working

Hi Jean,

When you execute action.http action, client will send a post request to our internal service which does the communication with the your service i.e url provided in the action.execute payload. 

The internal service expects a valid response which contains adaptive card payload. This response is relayed back to the client to render the refresh card.

Since your service, the graph api, is not a returning a valid response to the internal service, response to the client will be an error with 40* code.  Hence it displays error toast message.

If you have further questions, please reply back.
```

So Microsoft Graph API si not compatible with Microsoft OAM.
