### ISSUE TITLE
[MS Teams][Action.OpenUrl] Mailto with several recipients

### ISSUE THREAD

**Issue by WhiteCyClop** [microsoft/AdaptiveCards#5677]
**Platform**

MS Teams

**Description**

I create an Adaptive card with Action.OpenUrl and set url to create email via "mailto". But it works fine only if I set one recipient, when I try to set several recipients there is nothing to happen.

```
{
    "type": "Action.OpenUrl",
    "title": "Create email",
    "url": "mailto:one@email.com;two@email.com?Subject=Test"
}
```
It would be great to have opportunity to do this thing or maybe I just do something wrong?

**Comment by jonmill** [comment]
@siduppal - this looks like a Teams Host issue, can you take a look please?

**Comment by Mamatha-MSFT** [comment]
Hi @WhiteCyClop, Can you please tell us on which platform your facing this issue (like mobile, desktop).

**Comment by WhiteCyClop** [comment]
Hi, I face this issue on desktop Teams at Windows 10. I send adaptive card with this Action.OpenUrl via my chat bot. It displays fine, but when I press the button, nothing happened. On mobile app (Android) this card is doesn't displayed at all. Also I can't sent this card via App Studio, there is an error "cannot write a null value for property 'url'"

**Comment by Mamatha-MSFT** [comment]
Hi @WhiteCyClop I am able to repro the issue taking this for internal discussion with team and will get back to you.

**Comment by bengschf** [comment]
I have a similar issue. I have an Adaptive Card with a mailto-link (just one recipient) and there are different behaviours on mobile, desktop and webapp:
- WebApp: A new tab opens with url https://teams.microsoft.com/_ 
- Desktop Client (Windows, Version 1.4.00.8872 (64-Bit)): Nothing happens
- Mobile App (iOS, 3.6.77.2021063201): Works as aspected, Apple Mail opens

**Comment by Mamatha-MSFT** [comment]
@bengschf  - We have raised a bug for this issue and concerned team is working on it. Will update if it gets resolved.

**Comment by Mamatha-MSFT** [comment]
@WhiteCyClop @bengschf  - Currently openUrl  doesn't support mailto Urls.

**Comment by bengschf** [comment]
@Mamatha-MSFT if mailto-Links are not supported currently, why does it work on iOS?

**Comment by christopherollie** [comment]
and Android 👍 but not Windows.

**Comment by Wajeed-msft** [comment]
This has been added as feture request and engineering team is looking into it. Once this feature is completed, we will have parity across platforms.

**Comment by ajayvats18** [comment]
> @bengschf - We have raised a bug for this issue and concerned team is working on it. Will update if it gets resolved.

is it resolved ?

**Comment by Prasad-MSFT** [comment]
@ajayvats18 - This feature is currently not implemented. We are following up with engineering team. We will inform in this thread once we have any update. Thanks!

**Comment by Prasad-MSFT** [comment]
We got update from engineering team that "Only comma delimited IDs are supported. That's by design." 
Following this RFC: https://datatracker.ietf.org/doc/html/rfc6068"
