### ISSUE TITLE
[JS] [Accessibility] Duplicate Ids in aria-labelledby attribute for Input.ChoiceSet

### ISSUE THREAD

**Issue by muthurathinam** [microsoft/AdaptiveCards#5686]
# Platform

JavaScript

# Author or host

Outlook Host

# Version of SDK

Npm [v2.9.0](https://www.npmjs.com/package/adaptivecards/v/2.9.0)

# Details

When a ChoiceSetInput having a label is rendered, aria-labelledby attribute has the value as same id twice. Windows narrator is smart enough to identify the duplication and speaks the label only once. but in case of Mac's voice over the label is spoken twice. I think we need to make sure to add unique ids to the aria-labelledby attribute.

**Comment by jonmill** [comment]
Thanks for the feedback - we'll dig in and figure out where the underlying issue is

**Comment by jonmill** [comment]
@dclaux  - can you take a look to see if we're duplicating id's here?

**Comment by jonmill** [comment]
@dclaux - just a ping here :)

**Comment by dclaux** [comment]
@jonmill Is this supposed to be a 21.04 deliverable? It's not labeled as such.

**Comment by jonmill** [comment]
@dclaux - It was not initially included in 21.04 but it looks like you already have a PR for it, so we can definitely include it. Thanks for the quick turnaround!
