### ISSUE TITLE
[Teams][Rendering consistency] Line separator is missing after heading in iOS

### ISSUE THREAD

**Issue by lindach167** [microsoft/AdaptiveCards#5688]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [x] iOS

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.

Host - Teams

If you're an author, who are you sending cards to?

# Version of SDK

Latest

# Details

Line separator is missing after heading in iOS, renders fine on Android and Web

I've verified that this repros in the standalone visualizer, in addition to Teams iOS client, see screen shot and card JSON below:

[LineSeparatorJSON.txt](https://github.com/microsoft/AdaptiveCards/files/6332371/LineSeparatorJSON.txt)
![image](https://user-images.githubusercontent.com/29580478/115163581-b50f9780-a05e-11eb-8e26-e79c75da5cf4.png)

**Comment by jwoo-msft** [comment]
@lindach167 @jonmill 
I was just triaging the issue and found that the fix was very simple (~ 30 min), so I just fixed it out of the band.
https://github.com/microsoft/AdaptiveCards/pull/5692
