### ISSUE TITLE
Handling of non-Latin languages

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#57]
We ran into some issues in the Windows Tile Renderer when it came to Thai and other asian languages which had larger heights and were getting clipped with the line above them

**Comment by matthidinger** [comment]
@riarenas can we track this is an investigation bug for the UWP renderer? Since I'm vague on the scenario it would behoove us to double check the original XTR code and see what provisions they made doe ascenders/descenders in text

**Comment by andrewleader** [comment]
Closing as no customer requests for this
