### ISSUE TITLE
[Schema] Action.id docs

### ISSUE THREAD

**Issue by scottlovegrove** [microsoft/AdaptiveCards#5703]
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] .NET HTML
- [ ] .NET WPF
- [ ] Android
- [ ] iOS
- [x] JavaScript
- [ ] UWP

# Author or host

Both author and host

If you're an author, who are you sending cards to?

Our own platform (Twist)

# Version of SDK

2.9.0

# Details

Not sure if this is a bug, missing documentation, or another of these "special nodejs only features" that I keep finding. In our integrations, we are utilising the `id` field on an [`Action.Submit`](https://adaptivecards.io/explorer/Action.Submit.html) but looking at the spec, there is no `id` field. However, if you go to the designer and add a new Action.Submit element, you get the id field as something you can fill in. Same applies to `Action.Execute`.
![image](https://user-images.githubusercontent.com/25244878/115590791-471ad880-a2c9-11eb-8612-73a737c45b12.png)

So is this another nodejs only "unsupported" feature?

**Comment by jonmill** [comment]
This looks like a documentation bug...everything should have an ID field. We'll look into this. Thanks for bringing this to our attention!

**Comment by scottlovegrove** [comment]
@jonmill Awesome, that's good news, means I don't have to make a whole bunch of changes in my code 😄
