### ISSUE TITLE
Core Feature suggestion - Private Mode

### ISSUE THREAD

**Issue by mdtauk** [microsoft/AdaptiveCards#573]
I know this wont be likely for any v1 release, but as these Cards are intended to work with Notifications.  It could be useful to be able to mark a data field as "sensitive" or "personal" some kind of nomenclature that will enable the Card to hide or replace these with lines or placeholders.  That way if for whatever reason these Cards are used in an app model which handles private details, there is a platform way to ensure only those "logged in" or "known" can see it.

**Comment by andrewleader** [comment]
Thanks for this excellent idea! We're tracking your feedback in our internal productboard, closing this issue, we'll let you know if/when we do this.
