### ISSUE TITLE
Need More Definite Definition for Size Property of Column

### ISSUE THREAD

**Issue by nesalang** [microsoft/AdaptiveCards#574]
We currently have thee values: auto, stretch, and number.
Some renderers such as iOS renderer does not support some of the each values or some of combinations of the values. More firm definitions are needed to implement those values for platforms that do not support them natively. For example, if (auto | stretch) and number values are used, column width is unclear for columns with (auto | stretch).

**Comment by riarenas** [comment]
@nesalang Did you ever get any closure on this?

**Comment by andrewleader** [comment]
Closing as likely fixed now
