### ISSUE TITLE
[Feature Request] Animated GIF support

### ISSUE THREAD

**Issue by jonmill** [microsoft/AdaptiveCards#5748]
# What is the problem you are attempting to solve with this feature?

Add support for displaying animated GIFs

# A description of your proposed solution to the problem

A partner has expressed interest in adding renderer support to properly display animated GIFs.

# What alternatives or workarounds have you considered

N/A

**Comment by Sujit-Gaikwad** [comment]
hi do we have ETA for this?

**Comment by jonmill** [comment]
Hi @Sujit-Gaikwad - we don't currently have an ETA here. We know this is an important ask from the community and it is definitely on our roadmap. I'll update this issue when we have an ETA. Thanks for your patience!

**Comment by jonmill** [comment]
Closed as dupe of #3079

**Comment by Sujit-Gaikwad** [comment]
@jonmill thanks for your reply. please do let us know once you have ETA for this.

Also As per my research on the Adaptive card feature , adaptive card do have support to GIF image on  teams Desktop, Browser and Android teams channel.
Only teams iOS platform will render the GIF image like an normal image (without any animation).

**Comment by jonmill** [comment]
@Sujit-Gaikwad - absolutely. We'll update the work item above when we get started on it. This is an ask we've heard loud and clear so it should be sooner than later.
