### ISSUE TITLE
[Designer] Add High Contrast theme(s) to the Designer

### ISSUE THREAD

**Issue by Josverl** [microsoft/AdaptiveCards#5761]
In order to make sure that cards are clearly legible and accessible I would like so see a (Teams) High contrast theme in the editor,
This would allow cards be designed with accessibility in mind from the start , and would lessen the amount of re-work than needs to be done when accessibility issues may only be found in testing.

I think this is more important then preferences for either light or dark themes.
I think it should not be much effort to include one additional HostConfig based on an existing client such as Teams.

**Comment by dclaux** [comment]
Reassigning to Jonathan at this time. This feature should be handled by the Teams folks. I have pinged them about it. If they agree to do it, we should assign this issue to them.

**Comment by jonmill** [comment]
Hi @Josverl, thanks for reaching out - this will be tracked by Teams via https://github.com/MicrosoftDocs/msteams-docs/issues/3230
