### ISSUE TITLE
[Rendering] Adaptive card Input.Choice set placeholder not rendering on iOS

### ISSUE THREAD

**Issue by TheBluLion** [microsoft/AdaptiveCards#5762]
# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:
- iOS

# Target Application

MSTeams

# Problem Description

When adaptive card JSON below is posted by a bot, the card renders correctly on Teams desktop and web clients but provides an inconsistent experience on Android, and a blank card on iOS. 

If JSON payload is updated with different ordering and v1.0 card, card is displayed correctly in three locations with consistent experience. 

# Screenshot

Expected render (correctly displayed on desktop)
![image](https://user-images.githubusercontent.com/41968802/117023242-87f9f080-acbe-11eb-91b7-630815763e07.png)

Blank card on iOS
![image](https://user-images.githubusercontent.com/41968802/117020682-4a946380-acbc-11eb-971d-5cb1d42e32f0.png)

# Card JSON

```
{
	"type": "AdaptiveCard",
	"body": [
	{
	"type": "Input.Text",
	"placeholder": "Enter your name",
	"isVisible": false,
	"value": "Test",
	"id": "userName"
	},
	{
	"type": "TextBlock",
	"weight": "Bolder",
	"text": "Title Text:",
	"wrap": true
	},
	{
	"type": "Input.ChoiceSet",
	"choices": [
	{
	"title": "Choice 1",
	"value": "Choice 1"
	},
	{
	"title": "Choice 2",
	"value": "Choice 2"
	}
	],
	"placeholder": "Placeholder text",
	"isMultiSelect":true,
	"id": "PlaceholderID"
	},
	{
	"type": "ActionSet",
	"actions": [
	{
	"type": "Action.Submit",
	"title": "Submit"
	}
	]
	}
	],
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"version": "1.2"
	}


```
# Sample Code

Please provide any relevant code samples to help reproduce the issue

Corrected card json and expected render added here for context

```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "weight": "Bolder",
            "text": "This guideline helped me in the following decision support (Check all that apply):",
            "wrap": true
        },
        {
            "type": "Input.ChoiceSet",
            "placeholder": "Select at least one",
            "choices": [
                {
                    "title": "Choice 1",
                    "value": "Choice 1"
                },
                {
                    "title": "Choice 2",
                    "value": "Choice 2"
                }
            ],
            "id": "ChoiceID",
            "isMultiSelect": true
        }
    ],
    "actions": [
        {
            "id": "Submitbtn",
            "type": "Action.Submit",
            "title": "Submit"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

iOS render (expected)

![image](https://user-images.githubusercontent.com/41968802/117023543-d1e2d680-acbe-11eb-8eb5-f56a18c1952b.png)

# Version of SDK

Bot Composer Framework v 1.4.0

**Comment by jwoo-msft** [comment]
This issue is not reproducible in iOS SDK.
## Desktop
![Screen Shot 2021-05-04 at 12 41 58 PM](https://user-images.githubusercontent.com/4112696/117060835-47a66c80-acd6-11eb-9423-ca01559ccc1a.png)
## iOS
![Screen Shot 2021-05-04 at 12 43 31 PM](https://user-images.githubusercontent.com/4112696/117060891-5ab93c80-acd6-11eb-897b-69a061a4df6e.png)

@jonmill,
Can you help me to loop in the right person for this issue?

**Comment by TheBluLion** [comment]
This is reproducible in the iOS teams app with the sample card provided in bot composer framework v1.4.0 How do I provide/record a repro for follow up?

**Comment by jonmill** [comment]
Hi @TheBluLion - based on the investigation by @jwoo-msft, we'll move this over to the Teams repo for them to take a look at....it looks to be a specific problem with the Teams renderer.

**Comment by jonmill** [comment]
Tracked by Teams bug https://github.com/MicrosoftDocs/msteams-docs/issues/3232
