### ISSUE TITLE
[Feature Request] After JSON Validation Also Validate the Mandatory Input Required Fields

### ISSUE THREAD

**Issue by mdresch** [microsoft/AdaptiveCards#5780]
# What is the problem you are attempting to solve with this feature?

The automated match to the correct JSON validates which JSON to use and confirms which one has been requested.  A data set of fields which by using the JSON with all the mandatory required fields is missing. This feature would greatly benefit any json submitted to the W3C foundation.

# A description of your proposed solution to the problem

In order to ensure a message is sent using the correct JSON contains the minimum required data fields before it is sent out.

# What alternatives or workarounds have you considered

A confirmation to manually check when the correct JSON is validated to go through each field and establish whether it is mandatory or a field that only requires data when applicable.

**Comment by jonmill** [comment]
@mdresch - Can you please provide some more historical context about where this request is coming from and more information about a proposed solution? Thank you!

**Comment by jonmill** [comment]
Closed due to needing more information; if you have more information, please let us know and we can re-open and re-evaluate
