### ISSUE TITLE
[Designer] Fallback Elements Not Being Displayed

### ISSUE THREAD

**Issue by RootOfAllEval** [microsoft/AdaptiveCards#5797]
On designer screen, select _New Card_ > _Simple fallback_. Fallback elements are not rendered in preview.

![image](https://user-images.githubusercontent.com/5480993/117350598-be7c6a80-ae7a-11eb-87e2-7d0ba87527b1.png)

**Comment by jonmill** [comment]
@dclaux - is fallback with templates supported in the designer or is there a bug here?

**Comment by RootOfAllEval** [comment]
This also appears to be a regression in the BotFramework Emulator as versions 4.11.0 and prior displayed fallback elements correctly but newer versions do not.

**Comment by dclaux** [comment]
Fallback will be displayed in Preview mode.

Designing fallback elements isn't supported and we have no plan to add support at this time.

**Comment by jonmill** [comment]
Per David, closing as by-design
