### ISSUE TITLE
SDK Release Cadences

### ISSUE THREAD

**Issue by BnSmth** [Microsoft/AdaptiveCards#581]
Hi, I am currently working on a project that is using both the .NET and Javascript SDKs. Unfortunately, the .NET SDK is at v0.5 (released in May) whereas the Javascript SDK is at 0.6 (released in June). What is the release process regarding SDKs? Can I expect the SDK's to be updated together in the future and is there a roadmap in place for releases?

Thanks

**Comment by matthidinger** [comment]
Hi @BnSmth, you can expect the SDKs to be released together in the future, once we get the iOS, Android and UWP renderers in "beta" with the v1.0 schema, which should be around the end of September. We'll definitely be sharing the roadmap in the next few weeks. Thanks for your patience while we get our big rocks in order. 

Regarding .NET, are you using it just for the object model, or are you using the WPF/.NET HTML renderers?

**Comment by mdtauk** [comment]
On a similar note...

As there are plans to implement AdaptiveCards into parts of the Windows Shell - will additions to the Schema, Rendering (at least for UWP and XAML) be reliant on the Windows twice yearly update cycle?

If not, how will Windows support new additions between OS updates?  Is it a Windows Update thing, or something in the Windows Store?  Has there been any thought on keeping it decoupled with fallback for those not up to date with Windows updates?

**Comment by matthidinger** [comment]
Adaptive Cards will be supported in the Windows Shell but the renderer will be tied to a particular OS build for now. We will provide a mechanism for app developers to query which version is supported so they can craft the most appropriate card for the user

**Comment by mdtauk** [comment]
@matthidinger Good to know.  And checking the docs for what is supported where, will be important.

**Comment by matthidinger** [comment]
Hi folks, we've shipped a few updates to the .NET packages lately and plan to improve this consistency over the coming weeks, thanks for your patience!
