### ISSUE TITLE
Upgrade Adaptive cards to version 1.3

### ISSUE THREAD

**Issue by Andrewhoddie** [microsoft/AdaptiveCards#5815]
Hi

Hopefully this is in the correct area,  we have adaptive cards version 1.2 but we would like 1.3,  does anyone know how we can upgrade to this?

thanks
Andrew

**Comment by jonmill** [comment]
Hi @Andrewhoddie - what application or platform are you running? Are you trying to host cards or author cards?

**Comment by Andrewhoddie** [comment]
hi @jonmill I am trying to run this from Power Automate via https://unitedkingdom.flow.microsoft.com/ from here I create a new flow and create the adaptive card from there.
I dont think that we are hosting the card but not sure.

thanks

**Comment by jonmill** [comment]
Thanks for the info - it sounds like you are creating the card in Power Automate. Where are you sending the card to (Teams, Outlook, etc)?

**Comment by Andrewhoddie** [comment]
Hi @jonmill yes creating the card in Power Automate with the intention of using it in Teams.  thanks

**Comment by jonmill** [comment]
Thanks for clarifying - we'll move this to the Teams repo so they can help provide guidance here

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/3508
