### ISSUE TITLE
Image isn't displayed in Ms Teams in Web and Desktop  application but displayed in mobile application 

### ISSUE THREAD

**Issue by mykyta-Koptsov** [microsoft/AdaptiveCards#5817]
Please list the platform(s) that your application is targeting and remove platforms you are not targeting:
- NodeJS
- Desktop
- Web

# Target Application
-MS Teams

# Problem Description
Image isn't displayed in Ms Teams in Web and Desktop  application but displayed in mobile application.
In web console Image have 

# Screenshot
Example from web application
![Screenshot 2021-05-13 at 22 07 06](https://user-images.githubusercontent.com/57220090/118175697-1f86de00-b439-11eb-843d-64b7d24f36b0.png)
on Mobile application
![2021-05-13 22 18 49](https://user-images.githubusercontent.com/57220090/118175811-43e2ba80-b439-11eb-921e-568bd7e5cfe7.jpg)

Please provide a screenshot of the problem (if possible)

# 

Please provide the JSON of the Card that is being rendered

# Sample Code
```json
{
                "type": "Action.ShowCard",
                "title": "Set labels",
                "card": {
                    "type": "AdaptiveCard",
                    "actions": [{
                        "type": "Action.Submit",
                        "title": "Save",
                        "data": {
                            "action": "set-labels-submit",
                            "cardId": "${cardId}"
                        }
                    }],
                    "body": [{
                        "type": "Image",
                        "altText":"why",
                        "id":"0",
                        "url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg"
                    }]
                }
            }
```

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest main, etc...

**Comment by jonmill** [comment]
@siduppal - could this be related to Teams resource resolver?

**Comment by Sridevi-MSFT** [comment]
@mykyta-Koptsov - We are able to repro the issue will check this issue with internal team and get back to you.

**Comment by jonmill** [comment]
@mykyta-Koptsov and @Sridevi-MSFT - we're closing this issue as it is a Teams issue, but please continue to communicate here to track. Thank you!

**Comment by kostyaVyrodov** [comment]
@jonmill ,
could you share with us the link to the Teams's issue if you have that one, so we can get posted on updates?

**Comment by jonmill** [comment]
@siduppal - do you have the public bug number?

**Comment by jBuchholz590** [comment]
Hi, we are having the same problem in our deployed bot. It used to work as expected but stopped working in both desktop apps and web some days ago without us changing anything.

**Comment by Sridevi-MSFT** [comment]
@jonmill - We have raised a bug for this issue, concerned engineering team is working on it and it is being tracked internally.

**Comment by holygrolli** [comment]
any update on this? this is a really annoying bug.

**Comment by Sridevi-MSFT** [comment]
@holygrolli - I didn't get any update from Bug Team. Will inform you immediately if I get any information.

**Comment by holygrolli** [comment]
Guys this is inacceptable! This kind of bug is around for a very long time. We are internally testing an App/Bot which should be published to the marketplace and to paying customers. We cannot display images in our adaptive card.
Who can provide support for this issue? Can we somehow get a work around? 
@jonmill mentioned a Teams resource resolver. Can we change whatever inside our Cards for not having the resolver mess with our images?
Any help appreciated!

**Comment by Sridevi-MSFT** [comment]
@mykyta-Koptsov - This issue has been fixed and the fix is rolling in the internal rings. We have verified this internally. Currently we don’t have any ETA to share.
