### ISSUE TITLE
Adaptive cards not rendered properly on webchat channel. works on directline though..

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/AdaptiveCards#583]
![image](https://user-images.githubusercontent.com/2233628/29815945-02c2febe-8cd0-11e7-82d3-632e21806a92.png)

The above is an example of scuba bot number input.
The same behavior is observed across all adaptive cards of scuba card...

Used the webchat iframe.
   <div class="col-md-6">
                    <iframe src="https://webchat.botframework.com/embed/<BOT>?s=<secretKey>"
          style="height: 500px; max-height: 502px; width:500px;  float:right;"></iframe>

          </div> 

Tested on Chrome and IE. same behavior.
Using nodejs code.

Also read about the npm microsoft-adaptivecards module. How is that to be used? any documentation anywhere?

**Comment by dclaux** [comment]
@ubreddy can you elaborate on what's not working? I'm not sure I get it based on the screenshot. Also, what is the payload for the card that doesn't render properly?

**Comment by ubreddy** [comment]
This is the payload I am sending through bot 
session.send(payload)
{
  "type": "message",
  "inputHint": "expectingInput",
  "speak": "How many people will be joining you?  There is a minimum of 3 and a maximum of 6.",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "content": {
        "type": "AdaptiveCard",
        "version": "1.0",
        "body": [
          {
            "type": "TextBlock",
            "text": "{{destination}}, nice choice!"
          },
          {
            "type": "ColumnSet",
            "columns": [
              {
                "type": "Column",
                "items": [
                  {
                    "type": "TextBlock",
                    "text": "How many people will be joining you?"
                  }
                ]
              }
            ]
          },
          {
            "type": "Input.Number",
            "id": "numberOfPeople",
            "placeholder": "Enter a number",
            "min": 1,
            "max": 10,
            "value": 3
          }
        ],
        "actions": [
          {
            "type": "Action.Submit",
            "title": "Next",
            "data": {
              "people": ""
            }
          }
        ]
      }
    }
  ]
}
The above is just an example. All cards from scuba bot are behaving the same way. Being rendered as images and options below the image.
And for this I am getting the image as shown in the webchat channel (instantiated from iframe) . But it works properly if instantiated from Botchat.js...
Is webchat iframe not supportive of adaptive cards.

**Comment by ubreddy** [comment]
Even the same is not working from Skype channel too...

Error: Request to 'https://smba.trafficmanager.net/apis/v3/conversations/29%3A13
TA28m5CkdUwY3QPXUEkfr2qXLipnH09EJ9ZI3xYzpE/activities' failed: [400] Bad Request

    at Request._callback (C:\scuba\node_modu
les\botbuilder\lib\bots\ChatConnector.js:523:46)

**Comment by danmarshall** [comment]
@ubreddy can you tell me your bot ID?

**Comment by ubreddy** [comment]
AS_Skype

**Comment by danmarshall** [comment]
Hi @ubreddy - you need to check the "Enable Preview" checkbox in your Web Chat configuration page for that embed code.

**Comment by ubreddy** [comment]
did that. 
Still doest seem the serve the adaptive cards as cards... they are being shown as images with the actions showing up as options ( non clickable)

**Comment by ubreddy** [comment]
Well, when I created a new site it worked. Existing default after enabling preview didnt though. Strange!
