### ISSUE TITLE
Actionable email developer dashboard not working

### ISSUE THREAD

**Issue by st0014** [microsoft/AdaptiveCards#5832]
# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:
- NodeJS

# Target Application

Outlook

# Problem Description

Actionable email developer dashboard not working, it gives an error on loading

# Screenshot

<img width="894" alt="Untitled 3" src="https://user-images.githubusercontent.com/80271015/118228506-37cf1b00-b482-11eb-9e66-72cc6fc19fef.png">

# How to replicate
Navigate to:
https://aka.ms/publishoam

After authenticating, the error above appears.

# Other options tried

Tried to email onboardoam@microsoft.com - no response.
Tried to log issue on StackOverflow - no response

**Comment by jonmill** [comment]
@dclaux - this looks to be an Outlook issue...do you know the right person that we can route this to?

**Comment by dclaux** [comment]
Please send a mail to onboardoam@microsoft.com which is the correct support channel for Outlook Actionable Messages.

**Comment by st0014** [comment]
Thanks this has now been resolved.

**Comment by fidcast89** [comment]
could someone advise how this was resolved? am facing the same problem
@st0014 @dclaux
