### ISSUE TITLE
Issue with Adaptive cards when using in Xamarin.iOS

### ISSUE THREAD

**Issue by aakashjain181** [microsoft/AdaptiveCards#5836]
# Target Application

Mobile App using Xamarin.iOS

# Problem Description

Given that we do not have any adaptive cards sdk for Xamarin.iOS, we tried building our own Xamarin.iOS.Binding project.
We used the CocoaPods library and were able to create the project successfully.
However, the output was not as expected as it was not displaying the respective adaptive cards.

# Expected Outcome

Adaptive cards to be rendered successfully on iOS as intended

# Actual Outcome

Adaptive cards are not rendering and the space remains blank.
There are no errors.

# Repro Steps

Create a Xamarin.iOS binding project for Adaptive cards and test with any Adaptive card demo.
In case needed I can share the Binding project which I created.

# Schema Version

1.0

**Comment by jonmill** [comment]
Adaptive Cards does not currently support Xamarin.iOS as a project type; there may be a way to get it to work, but there is no official support for this project type.
