### ISSUE TITLE
[JS] Replace `keyCode` with `code` everywhere

### ISSUE THREAD

**Issue by dclaux** [microsoft/AdaptiveCards#5837]
# Target Platform

JS

# Problem Description

`KeyboardEvent.keyCode` is deprecated. Applications should use `KeyboardEvent.code` instead. The JS SDK still uses `keyCode` in some places; these should be updated.

**Comment by ChristoperHowell** [comment]
Hello, would you mind if I grabbed this as a first issue?

**Comment by dclaux** [comment]
@ChristoperHowell please do! Thank you!
