### ISSUE TITLE
Action.OpenUrl not working anymore

### ISSUE THREAD

**Issue by ysnoek2** [microsoft/AdaptiveCards#5839]
# Target Application

Teams

# Problem Description

When clicking on the action button in Teams it should open a browser but since a few days it is not working anymore. When clicking on "open app in new tab" in Teams and then clicking the button, it somehow does work. I have tried the url in postman and it works fine. 

# Screenshot
The url in postman:

![image](https://user-images.githubusercontent.com/76207835/118620381-bfd85c00-b7c5-11eb-9d9f-b4b7ce86d8d5.png)

![image](https://user-images.githubusercontent.com/76207835/118620464-cf57a500-b7c5-11eb-9d38-2c082a7a4503.png)

The card in Teams:

![image](https://user-images.githubusercontent.com/76207835/118620782-1e053f00-b7c6-11eb-894c-ca6e362aa175.png)

# Card JSON

{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "Image",
            "url": "https://isabot.ista.nl/api/Afrekening/GetImgDocuware",
            "size": "Large"
        },
        {
            "type": "TextBlock",
            "text": "Afrekening van object: **${user.Bewoner.content.ObjectNr}** ",
            "wrap": true,
            "size": "Large"
        },
        {
            "type": "TextBlock",
            "text": "${Straat} ${Huisnrvan} t/m ${Huisnrtm} ${Plaats}",
            "wrap": true,
            "size": "Small"
        },
        {
            "type": "TextBlock",
            "text": "${user.Bewoner.Jaar}",
            "wrap": true,
            "height": "stretch",
            "size": "Small",
            "color": "Accent"
        }
    ],
    "actions": [
        {
            "type": "Action.OpenUrl",
            "title": "Open afrekening",
            "url": "${dialog.Response.content}",
            "style": "positive"
        }
    ],
    "selectAction": {
        "type": "Action.OpenUrl"
    }
}

# Version of SDK

1.3

**Comment by jonmill** [comment]
This is a Teams-specific issue...moving to the Teams repo

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/3347
