### ISSUE TITLE
Typescript/UWP renderer are case sensitive for string property values. 

### ISSUE THREAD

**Issue by riarenas** [Microsoft/AdaptiveCards#584]
As an example, column Size property is case sensitive:

"size": "auto" :heavy_check_mark:
"size": "Auto" :x:

Should we be this strict with the casing in the value for the size? The documentation says this:

"auto", "stretch", or a number representing relative width of the column in the column Set (Default:Auto)

Although the docs are clear in that we expect those literal strings, the remark about the default might be interpreted as taking Auto as a valid value.

I tend to think we should be case insensitive when evaluating this value. Thoughts?

**Comment by matthidinger** [comment]
I agree case insensitive seems the best way to go. @dclaux any issue?

**Comment by dclaux** [comment]
I don't have a problem with it.

**Comment by riarenas** [comment]
Trying to get some closure on this one. @dclaux Did this make it to the typescript renderer? The published visualizer is still case sensitive for column width.

**Comment by dclaux** [comment]
This has been changed a long time ago.
