### ISSUE TITLE
Unable to render array of objects in adaptivecard as lineitems with adaptivecards-templating

### ISSUE THREAD

**Issue by kiranbudati** [microsoft/AdaptiveCards#5841]
I have invoice data as JSON with line items as an array of objects, i'm trying to render invoice data with adaptivecards-templating engine, able to render json object but unable to render array of objects as rows.

I'm passing data conext as ${lineAttributes} but mbf I'm getting datacontext as like this "$data":"[object Object],[object Object]" and passing

**Comment by jonmill** [comment]
@kiranbudati - Please re-file using our issue template and provide answers to the template questions; without those answers, we do not have enough information to help.
