### ISSUE TITLE
Adaptive Card Schema is missing Speak property

### ISSUE THREAD

**Issue by riarenas** [Microsoft/AdaptiveCards#585]
https://docs.microsoft.com/en-us/adaptive-cards/create/cardschema#adaptivecard

has no mention of a speak property, but https://docs.microsoft.com/en-us/adaptive-cards/create/speech mentions there should be a speak property on the card for "On Delivery" reading of the property.
Once it is added, should be implemented in all renderers.

**Comment by matthidinger** [comment]
This has been added  now
