### ISSUE TITLE
Add Action.ToggleVisiblity to Input.Choice

### ISSUE THREAD

**Issue by npongo** [microsoft/AdaptiveCards#5852]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML
* .NET WPF
* Android
* iOS
* JavaScript
* UWP

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.

If you're an author, who are you sending cards to?

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest main, etc...

# Issue

Explain your issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards).

**Comment by npongo** [comment]
Adding toggle visibility to input. choice would allow for implementing skip patterns by toggling the visibility of questions that are only required based on the choice made.

**Comment by jonmill** [comment]
@npongo - Please use our issue templates to add the relevant information that is needed for us to triage and understand the issue.
