### ISSUE TITLE
[Feature Request] Options to remove asterisk sign from Input field label

### ISSUE THREAD

**Issue by dev-sandeep** [microsoft/AdaptiveCards#5868]
# What is the problem you are attempting to solve with this feature?
For Input fields like choice sets and Input box labels, there should be options for removing the asterisk symbol from the label

Binding the user in a particular way for form validation may not be a great idea, eg: some applications wish to disable the submit buttons till all the mandatory fields are filled, while other just want to show the asterisk sign in the label and gives an error message if there are some error. It would be great if more flexibility is provided

# A description of your proposed solution to the problem
I propose there should be options to remove the asterisk signs in label(signifying the mandatory fields) either from hostapp config json or via some unique css selectors which one could target, to override and hide the asterisk sign

**Comment by atishayv** [comment]
CC: @dclaux , @matthidinger

**Comment by dclaux** [comment]
With the JS SDK you should already be able to do that by setting `HostConfig.inputs.label.requiredInputs.suffix = undefined`

Please give this a try.

**Comment by dev-sandeep** [comment]
Thanks a lot @dclaux, It worked
