### ISSUE TITLE
[Rendering] ios teams mobile app, entire adaptive card not showing when text (Input Text) is used after last teams update

### ISSUE THREAD

**Issue by vindevries** [microsoft/AdaptiveCards#5870]
# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:

- iOS

# Target Application

Microsoft Teams

# Problem Description

When you use Input.Text in an Adaptive card on IOS the entire card will not render when called from a task module.

# Screenshot

Nothing is rendered so a screenshot would be blank.

# JSON

{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "Input.Text",
            "placeholder": "Placeholder text"
        }
    ]
}

**Comment by jwoo-msft** [comment]
@vindevries 
Please add "id" to "Input.Text". It's the required property.
e.g, "id" : "hello"
```json
{
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.3",
  "body": [
    {
      "type": "Input.Text",
      "id": "hello",
      "placeholder": "Placeholder text"
    }
  ]
}
```

**Comment by vindevries** [comment]
@jwoo-msft 
Thanks for your reply, but this doesn't solve the issue. A toggle button for example does render:

`{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "Input.Toggle",
            "title": "New Input.Toggle",
            "id": "myId"
        }
    ]
}`

But the same Input.Text doesn't:

`{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "Input.Text",
            "placeholder": "Placeholder text",
            "id": "MyId"
        }
    ]
}`

**Comment by jwoo-msft** [comment]
@jonmill,
Can you help me redirect this issue to Teams?

This issue doesn't repro on iOS sample app.

payload used;
```json
{
"type": "AdaptiveCard",
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"version": "1.3",
"body": [
{
"type": "Input.Text",
"placeholder": "Placeholder text",
"id": "MyId"
}
]
}
```

<img width="297" alt="Screen Shot 2021-05-26 at 12 26 55 PM" src="https://user-images.githubusercontent.com/4112696/119719483-aa92ab80-be1d-11eb-8fad-555ce202144c.png">

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/3497

**Comment by jonmill** [comment]
Sure thing, redirecting!
