### ISSUE TITLE
[JS] Investigate Platform Implementation

### ISSUE THREAD

**Issue by jonmill** [microsoft/AdaptiveCards#5934]

**Comment by dclaux** [comment]
@jonmill what is this about?

**Comment by jonmill** [comment]
This is the time-bucket for investigating / prototyping the Input.ChoiceSet for JS. We're going to circle up on Wednesday June 9th to finalize the design for Input.ChoiceSet based on everyone's prototype and what questions / open issues they've found

**Comment by dclaux** [comment]
Got it. Maybe the title should reflect that a little more precisely? Because seen in GitHub alone it's difficult to make sense of it.
