### ISSUE TITLE
Adaptive Cards Roadmap + Feedback

### ISSUE THREAD

**Issue by JeanRoca** [microsoft/AdaptiveCards#5939]
Hey everyone!

Adaptive Cards is constantly changing and the team is working hard to deliver a great experience to all our users. We have the [Adaptive Cards Roadmap](https://portal.productboard.com/adaptivecards/1-adaptive-cards-features/tabs/5-launched) which can be found on our website and now here on GitHub as well!

## What we're planning
Please head over to our [Planning Board](https://portal.productboard.com/adaptivecards/1-adaptive-cards-features/tabs/6-planned) to check out all the features the team is planning to release in the future. These features do not have a set date for their release, but you could really help the team prioritize by clicking on the feature and describing your need under the "**How important is this to you?**" section.

## Share your feedback
Don't see an important feature listed on our planning board? Head over to our [Under Consideration](https://portal.productboard.com/adaptivecards/1-adaptive-cards-features/tabs/4-under-consideration) board and take a look there. If your feature is still not there, you can easily submit an idea by clicking the button found on the top right of the site. If you have any questions or feedback on the product please feel free to either leave a comment on this issue or open up a new one and someone on the team will get back to you 😊

**Comment by RebeccaAnne** [comment]
Per discussion closing this issue.
