### ISSUE TITLE
Action.OpenUrl not working in Teams meeting chat for guest users

### ISSUE THREAD

**Issue by figgsoftware** [microsoft/AdaptiveCards#5940]
If a person is logged into the Teams tenant with a guest user (Microsoft account or out of tenant Office 365 account ) and click a button in an Adaptive Card with an Action.OpenURL in a meeting chat, they get a strange error message: "This card action is not supported by . " It seems Action.OpenUrl is not working properly for tenant guests/anonymous users.
![image](https://user-images.githubusercontent.com/17601161/120084562-8d860300-c0d1-11eb-897e-3203628642c3.png)

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/3553
