### ISSUE TITLE
[Feature Request] MAUI Support

### ISSUE THREAD

**Issue by pooran** [microsoft/AdaptiveCards#5941]
# What is the problem you are attempting to solve with this feature?

We were waiting for Xamarin support for quite some time. But with MAUI around the corner, it would have been a double effort. Can we expect complete support for MAUI directly - iOS, Android, UWP, and MacOS?

# A description of your proposed solution to the problem

It is fine to have native support for iOS, Android, React. But having cross-platform support using MAUI will make adoption much faster. Generating UI is one of the crucial parts of any app design and if AdaptiveCards becomes a defacto rendering engine for most of the display and input, more community contribution will increase adoption.

# What alternatives or workarounds have you considered

We tried building binding projects for native implementations, If something works, something doesn't. MacOS is still elusive. 

Please start with MAUI asap

**Comment by RebeccaAnne** [comment]
Xamarin/MAUI support is being tracked on product board here: https://adaptivecards.productboard.com/portal/1-adaptive-cards-features/tabs/c88173a2-a3a1-4bc5-ad15-11051b3c7942/features/1961753/portal/expanded

Please upvote the feature there!
