### ISSUE TITLE
[iOS][Accessibility]Adaptive Card focus on the first element which is image

### ISSUE THREAD

**Issue by kaichun-wu** [microsoft/AdaptiveCards#5942]
# Target Platform
- iOS

# Target Application

Teams

# Problem Description

Accessibility default focus on the first card will finally focus on the first image. Would like to focus on the whole card instead.

# Expected

Focus on the whole card.

# Screenshot
![IMG_0072_1](https://user-images.githubusercontent.com/85100080/120160796-3abf5f00-c229-11eb-8a99-e03a5a538405.png)

# Sample Code

UIAccessibility.post(notification: .layoutChanged, argument: firstcard)

# Version of SDK

2.4.6

**Comment by RebeccaAnne** [comment]
We should follow up with our accessibility team to confirm the desired behavior.

**Comment by kaichun-wu** [comment]
@RebeccaAnne Do you have any updates on this? Thanks.

**Comment by muhamadizzuddin** [comment]
no
________________________________

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4663
