### ISSUE TITLE
[Website] Action.Execute doesn't enable to use in designer of Adaptive Cards

### ISSUE THREAD

**Issue by Coderast** [microsoft/AdaptiveCards#5943]
In doc described [not deprecated action "Action.Execute"](https://adaptivecards.io/explorer/Action.Execute.html), but when I try to use it in [Adaptive Cards Designer](https://adaptivecards.io/designer/) but it doesn't render whichever host app I choose. Does it a bug or "Action.Execute" now is deprecated action?

---
* URL: https://adaptivecards.io/explorer/Action.Execute.html

**Comment by RebeccaAnne** [comment]
The designer defaults to version 1.3 which does not support Action.Execture. If you change the target version (upper right corner) to 1.4 this should work for you. Please reactivate if you run into any issues.
