### ISSUE TITLE
UWP: API to grab all input values user currently inputted

### ISSUE THREAD

**Issue by anbare** [Microsoft/AdaptiveCards#596]
When user clicks on a toast (including outside the Adaptive Card region), we need to be able to collect all of the input values that the user currently has written, so that when the app gets activated, it gets all of the inputs.

This would likely simply involve making the GatherAllInputs or whatever method public, and actually return a different object rather than just a FrameworkElement, or somehow make the original Card model update with the values the user inputs in the XAML

```csharp
RenderResult result = renderer.RenderCardAsXaml(card);

// Later on, when entire toast is clicked
string inputValues = result.GetInputValues();
```

**Comment by matthidinger** [comment]
@riarenas is this done in the beta or polish?

**Comment by riarenas** [comment]
It's done! it's already part of the RenderedAdaptiveCard.

```csharp
RenderedAdaptiveCard renderResult = _renderer.RenderAdaptiveCardFromJson(jsonObject);
JsonObject userInputs = renderResult.UserInputs.AsJson(InputValueMode.RawString)
```

**Comment by anbare** [comment]
Confirmed it works :) closing!
