### ISSUE TITLE
[Authoring] [Web] [Accessibility] Accessibility issues with link markdown in a text block inside a column

### ISSUE THREAD

**Issue by abhinav12** [microsoft/AdaptiveCards#5972]
# Target Application

Web Browsers. Reproed in Chrome and Edge

# Problem Description

Double keyboard navigation and narrator issues when using link markdown inside a column containing TextBlock component and a select action

# Expected Outcome

The Text Block should be navigatable only once and the title should be read by the narrator

# Actual Outcome

The Text Block and the anchor tab are separately keyboard navigatable. The anchor tag text and the selectaction title is read separately by screen reader.

# Repro Steps
1) Use the following Json on [Adaptive Card Designer](https://adaptivecards.io/designer) : 

```json
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.3",
    "body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "TextBlock",
                            "text": "[Column 1](https://www.youtube.com/watch?v=dQw4w9WgXcQ)"
                        }
                    ],
                    "selectAction": {
                        "type": "Action.OpenUrl",
                        "title": "cool link",
                        "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
                    },
                    "width": "stretch"
                },
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "TextBlock",
                            "text": "Column 2"
                        }
                    ],
                    "width": "stretch"
                }
            ]
        }
    ]
}
```

2) In Preview mode, Navigate to 'Column 1'. The text is navigated twice.
3) Turn on Narrator ( if on Windows ). Both 'Cool Link' and 'Column 1' texts are read.

# Schema Version

What JSON Schema Version are you targeting?
1.3

**Comment by jonmill** [comment]
Hi @abhinav12 - this is working by-design due to having two controls expressed (via the JSON) in the UI tree. If your goal is to have an action that looks like a link, I recommend using a `RichTextBlock` with a `SelectAction` on the `TextRun`.
