### ISSUE TITLE
Adaptive Card Action.ShowCard Button Focus Out Issue

### ISSUE THREAD

**Issue by sauravmahuri2007** [microsoft/AdaptiveCards#5974]
# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:
- NodeJS
```
"botbuilder": "^3.14.0",
"botbuilder-teams": "^0.2.1",
```
Though I believe it should be same for bot written in Python

# Target Application

Please provide the name of the application that is rendering the card
- Webchat (https://cdn.botframework.com/botframework-webchat/latest/webchat.js)

# Problem Description
It is hard to explain the issue in words so attaching a video for better explanation.

- All five buttons as shown in the video (00:00 seconds) are choice buttons and each of them displays some of the data. Similary **DQ sheet** button also shows adaptive cards in carousel. The last adaptive card  (titled Deal Qualification Sheet - 3) in carousel used **Action.ShowCard** (expandable button) to show more data in the video (00:10 seconds). i,e **Opportunity Assessment** is actually an **Action.ShowCard**
- We noticed that when the carousel (left-right arrow) or **Action.ShowCard** is clicked it is making other choice buttons available in the space non-reachable at first click. As it is shown in the video (00:17 seconds) when **Sales strategy** choice button is clicked, it directly jumped back to the Carousel where adaptive cards were shown.

**Note:** We noticed that the adaptive cards having **Action.ShowCard** is causing this issue more frequently. Which means that showing just a single adaptive card (not necessarily in carousel layout) with **Action.ShowCard** buttons is enough to reproduce this issue. Though I'm also attaching few sample adaptive cards.

# Screenshot

https://user-images.githubusercontent.com/3635655/121223765-7c917a80-c8a5-11eb-8dda-a029b211a4bc.mp4

# Card JSON

Attaching the equivalent json response (which was received by emulator) as the JSON was quite large.
**Note:** The issue is only appearing for channel = `webchat`. Couldn't replicate it using emulator.

# Sample Code

[emulator_response_json.txt](https://github.com/microsoft/AdaptiveCards/files/6618435/emulator_response_json.txt)

# Version of SDK

**Comment by Saransh-spec** [comment]
Hey Saurav,
I am new to Adaptive Cards. Currently i am using BotFramework and Using Adaptive Designer to create cards for ChatBot . I am stucked at a place and dont know what to do, It will be good if you can sort me out.   --->
 I Need to display Specific Data With Each Choice Option in ChoiceSet. Eg- If User Select "PhoneCall" from ChoiceSet--> It 
 should display other details for user to enter country code & Phone Number and Finally Submit the Information.
 But If User Select "TeamsChat" -->It just Submit the Contact Method.
![image](https://user-images.githubusercontent.com/84326593/121516817-44587c00-ca0c-11eb-9c72-ef42a46df445.png)


Is there any way to do this. Please Guide its Imp.

**Comment by Saransh-spec** [comment]
Or If It is not possible , then Can i display Separate Cards for PhoneCall Choice/TeamsChat Choice/EmailChoice  Inside Main Adaptive Card.
![image](https://user-images.githubusercontent.com/84326593/121518401-0f4d2900-ca0e-11eb-9caa-d15b79eba4c7.png)

**Comment by sauravmahuri2007** [comment]
> Hey Saurav,
> I am new to Adaptive Cards. Currently i am using BotFramework and Using Adaptive Designer to create cards for ChatBot . I am stucked at a place and dont know what to do, It will be good if you can sort me out. --->
> I Need to display Specific Data With Each Choice Option in ChoiceSet. Eg- If User Select "PhoneCall" from ChoiceSet--> It
> should display other details for user to enter country code & Phone Number and Finally Submit the Information.
> But If User Select "TeamsChat" -->It just Submit the Contact Method.
> ![image](https://user-images.githubusercontent.com/84326593/121516817-44587c00-ca0c-11eb-9c72-ef42a46df445.png)
> 
> Is there any way to do this. Please Guide its Imp.

I doubt this is possible in Adaptive card. Dynamically changing the contents of adaptive card based on the events is not supported yet. I suggest you to create other fields as hidden and use JavaScript in your webchat html file to make other fields visible based on the choice selection. There might be a better way to do this so I recommend you to ask this as a separate question in Stackoverflow/Github.

**Comment by compulim** [comment]
Hi @sauravmahuri2007,

As the width of the UI is so tight with 3 cards showing side-by-side, could you change the layout from side-by-side (a.k.a. "carousel") to vertical stack?

If you unset the [`activity.attachmentLayout`](https://docs.microsoft.com/en-us/javascript/api/botframework-schema/activity?view=botbuilder-ts-latest#attachmentLayout), it should show 3 cards vertically, and there will be enough space and the Step 1-4 buttons can be clicked with ease.

**Comment by jonmill** [comment]
Closing as external since this is in WebChat, but please continue the conversation here as necessary :)
