### ISSUE TITLE
[Rendering] Content Security Policy violations in adaptive-expressions npm library

### ISSUE THREAD

**Issue by BenBullock1992** [microsoft/AdaptiveCards#5978]
# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:
- NodeJS

# Target Application

Angular single-page web application

# Problem Description

When serving our Angular application through our Node.js/Express.js web server, we are seeing Content Security Policy violations coming from the adaptive-expressions npm library when we try to render an Adaptive Card.

The violation is being raised as this library calls functions like "eval()" and "new Function()" which are considered dangerous since they are susceptible to XSS attacks.

Please could you advise on possible workarounds which will not compromise our security?

# Version of SDK

"adaptive-expressions": "^4.12.0",
"adaptivecards": "^2.9.0",
"adaptivecards-templating": "^2.1.0"

**Comment by paulcam206** [comment]
Issue moved to [microsoft/botbuilder-js #3889](https://github.com/microsoft/botbuilder-js/issues/3889) via [**ZenHub**](https://www.zenhub.com/)

**Comment by paulcam206** [comment]
The `adaptive-expressions` library is a separate project, and so this issue should be over in their repo...
