### ISSUE TITLE
[Authoring] Text input field fails to validate if not mandatory

### ISSUE THREAD

**Issue by UncleZen** [microsoft/AdaptiveCards#5983]
# Target Application

iOS & Android React Native application

# Problem Description

The user's input in a text input is validated only if it is marked as mandatory. Otherwise the said field does not get validated. E.g. Consider the adaptive card JSON definition below:

```json
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "Input.Text",
            "placeholder": "K2C 3L5",
            "id": "postal_code",
            "label": "Postal Code",
            "regex": "^[a-zA-Z]\\d[a-zA-Z] ?\\d[a-zA-Z]\\d$",
            "errorMessage": "Please enter a valid Canadian Postal Code"
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Submit"
        }
    ]
}
```

The user would be able to submit this form regardless the value they enter in the text input field. 

I believe, this line of code:

https://github.com/microsoft/AdaptiveCards/blob/58abbf574ef8b9a319b7a02bc092a457b679f114/source/community/reactnative/src/components/inputs/text-input.js#L124

causes the text input to be validated only if the field is mandatory. 

I suggest that the handleBlur method is changed to:

`
handleBlur = () => {
const valInputTextStyles = [Enums.InputTextStyle.Email, Enums.InputTextStyle.Url, Enums.InputTextStyle.Tel];
if (this.isRequired || this.regex || valInputTextStyles.some(style => style === this.styleValue))			
this.validate();	
}
`

Consequently, the validate() method must be updated accordingly.

# Expected Outcome

A text input that has regex property specified or its style property set to either Tel, Url or Email must be validated regardless whether it is mandatory or not. 

# Actual Outcome

A text input is not validated if it is not mandatory.

# Schema Version

v1.3

# Version of SDK

React: v. 16.13.1
React Native: v. 0.63.3
adaptivecards-reactnative: v. 2.2.8

**Comment by jonmill** [comment]
@Vasanth-S - is this something your team could help with?

**Comment by Vasanth-S** [comment]
Yes, @jonmill. @vivekvijayakrishnan  @IbrahimSulai  Please look into this issue.

**Comment by jonmill** [comment]
The RN renderer is now at https://github.com/bigthinkcode/adaptivecards, please re-open the issue there if this is still a problem. Thanks!
