### ISSUE TITLE
[Accessibility]Tooltip is not available for keyboard only users for Action.Submit button configured to image.

### ISSUE THREAD

**Issue by GayatriDeviP** [microsoft/AdaptiveCards#5998]
# Platform

Accessibility

* .NET HTML
* JavaScript

# Author or host
D365 sales insights

# Version of SDK
Latest

# Issue
1. open any of sample adaptive card and place the below Json in card payload editor
2. Navigate using keyboard and verify whether tooltip is visible or not.
3. On mouse hover, tooltip is visible.

**Json:**
{
    "type": "AdaptiveCard",
    "$schema": http://adaptivecards.io/schemas/adaptive-card.json,
    "version": "1.3",
    "body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "Image",
                            "altText": "Gayatri",
                            "width": "32px",
                            "height": "32px",
                            "url": https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg,
                            "selectAction": {
                                "type": "Action.Submit",
                                "title": "Gayatri"
                            }
                        }
                    ],
                    "width": "32px",
                    "selectAction": {
                        "type": "Action.Submit"
                    },
                    "verticalContentAlignment": "Center"
                }
            ]
        }
    ]
}

**Comment by jonmill** [comment]
Hey @GayatriDeviP - great find! Unfortunately, Adaptive Cards cannot control when a tooltip is displayed. The AC SDK only tells what the tooltip text should be, but the underlying system (OS platform) is responsible for when a tooltip is displayed. There isn't anything we can do here
