### ISSUE TITLE
Image does not display on Desktop

### ISSUE THREAD

**Issue by Andrew-Murdock** [microsoft/AdaptiveCards#6010]
# Desktop and iOS mobile

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:
- iOS
- WPF
- UWP

# Target Application

Teams 

# Problem Description

Adaptive Card rendered from a Flow to a Teams channel displays Image on the card correctly on Browser (Edge: latest update). Does not display image on Desktop App or iOS phone or iPad.

# Screenshot

Attached below
![Screenshot 2021-06-15 180721](https://user-images.githubusercontent.com/85969402/122144357-30e05300-ce08-11eb-89ff-c3d88476b158.jpg)
![Screenshot 2021-06-15 180640](https://user-images.githubusercontent.com/85969402/122144362-3342ad00-ce08-11eb-8496-8b46be2aff14.jpg)
![20210616_012646000_iOS](https://user-images.githubusercontent.com/85969402/122144427-54a39900-ce08-11eb-8380-551192a0f9e3.jpg)

# Card JSON
```json
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Large",
            "weight": "Bolder",
            "text": "2021-06-15",
            "color": "Accent"
        },
        {
            "type": "TextBlock",
            "text": "Notice submitted by external user via a form",
            "wrap": true,
            "horizontalAlignment": "Center",
            "weight": "Bolder"
        },
        {
            "type": "TextBlock",
            "spacing": "None",
            "wrap": true,
            "size": "Small"
        },
        {
            "type": "FactSet",
            "facts": [
                {
                    "title": "Activity",
                    "value": "WellDunn Drone"
                },
                {
                    "title": "Location",
                    "value": "Confluence of Meager Creek and Lillooet Creek"
                },
                {
                    "title": "Other Info",
                    "value": "will be doing pre-planned grid patterns over landslide area, below 120m AGL, will be monitoring 126.7 and will callout before taking off, should be flying around 1pm to 4pm"
                }
            ]
        },{
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.OpenUrl",
                    "url": "https://blackcombhelicopters.sharepoint.com/sites/ElectronicFlightBags/Shared%20Documents/NOTAMs%20and%20Drone%20Activity/Resource%20Material/2021%20June-July%20Meager%20UAV%20Flyover.jpg",
                    "iconUrl": "https://blackcombhelicopters.sharepoint.com/sites/ElectronicFlightBags/Shared%20Documents/NOTAMs%20and%20Drone%20Activity/Resource%20Material/2021%20June-July%20Meager%20UAV%20Flyover.jpg",
                    "title": "Open Map"
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2"
}
```
# Sample Code

Please provide any relevant code samples to help reproduce the issue

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest main, etc...

**Comment by jonmill** [comment]
Adaptive Cards & Teams does not currently support displaying images requiring authentication. The ask to support this is being tracked by issue https://github.com/microsoft/AdaptiveCards/issues/3612

**Comment by Andrew-Murdock** [comment]
Please excuse my lack of knowledge, what jpg URL would not require authentication?
