### ISSUE TITLE
[iOS] Adaptive cards not rendering in Teams iOS app but show up on the desktop client.

### ISSUE THREAD

**Issue by ved-dave** [microsoft/AdaptiveCards#6013]
# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:
- iOS

# Target Application

Microsoft Teams for iOS

# Problem Description

Microsoft Teams app on iOS is not rendering adaptive cards when sent via an inbound webhook.

# Screenshot
Desktop:
![image](https://user-images.githubusercontent.com/51809650/122465058-7158e180-cf6c-11eb-9256-ec3a5328e04d.png)
Phone:
![bug](https://user-images.githubusercontent.com/51809650/122465593-2390a900-cf6d-11eb-8303-66e845235f21.jpg)

# Card JSON

Tried it with some of the templates as well available online and none of them rendered at all.

# Sample Code

N/A

# Version of SDK

N/A

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/3672
