### ISSUE TITLE
[Rendering] `getConstraintsForImageAlignment:withSuperView:toView` returns centerY constraint

### ISSUE THREAD

**Issue by janusbal** [microsoft/AdaptiveCards#6014]
# Target Platform

- iOS

# Target Application

Teams

# Problem Description

When applying constraint/s based on `imgElem->GetHorizontalAlignment()` this [method](https://github.com/microsoft/AdaptiveCards/blob/60ae7122af53776bc2cc1f55d415b035238658d5/source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOHostConfig.mm#L220) always attach `centerY` constraint which makes the image center vertically. This constraint conflicts with .top constraint we apply we need to anchor the image on top of the card. 

# Screenshot

|Expectation | Actual|
|:--:|:--:|
|![Screen Shot 2021-06-17 at 1 02 24 PM](https://user-images.githubusercontent.com/86079148/122464973-525a4f80-cf6c-11eb-86c7-52c6eb2beb95.png) | ![Screen Shot 2021-06-17 at 1 09 43 PM](https://user-images.githubusercontent.com/86079148/122465759-5470de00-cf6d-11eb-89a3-c361edf6cd70.png)  | 

# Card JSON

[ImageIssueAndTextTruncate.json.zip](https://github.com/microsoft/AdaptiveCards/files/6672976/ImageIssueAndTextTruncate.json.zip)

# Sample Code
```
NSArray *alignmentConstraints = [ACOHostConfig getConstraintsForImageAlignment:imgElem->GetHorizontalAlignment()
                                                                     withSuperview:wrappingview
                                                                            toView:view];

//     This commented block allows the card render properly
//    for (NSLayoutConstraint *constraint in alignmentConstraints) {
//        if (constraint.firstAttribute == NSLayoutAttributeCenterY || constraint.secondAttribute == NSLayoutAttributeCenterY) {
//            constraint.priority = UILayoutPriorityDefaultHigh;  //lower than required priority
//        }
//    }

    [wrappingview addConstraints:alignmentConstraints];

```

# Version of SDK
    pod 'AdaptiveCards', '2.4.6'

**Comment by jonmill** [comment]
@jwoo-msft - can you chime in to speak about the origin (0, 0) of an image in iOS?

@janusbal - can you speak a little to what you are attempting to achieve here? There are alignment properties that can help with aligning images in a card...is the issue that when the `Horizontal Alignment` is set that iOS is *also* setting the `Vertical Alignment` without you telling it to?

**Comment by janusbal** [comment]
> @jwoo-msft - can you chime in to speak about the origin (0, 0) of an image in iOS?
> 
> @janusbal - can you speak a little to what you are attempting to achieve here? There are alignment properties that can help with aligning images in a card...is the issue that when the `Horizontal Alignment` is set that iOS is _also_ setting the `Vertical Alignment` without you telling it to?

@jonmill  Yes. calling `getConstraintsForImageAlignment:imgElem->GetHorizontalAlignment()` returns two constraints. One `.leading` which I expect, and one `.centerY` which I do not expect.

![Screen Shot 2021-06-17 at 1 36 35 PM](https://user-images.githubusercontent.com/86079148/122469000-48871b00-cf71-11eb-8835-e8e0b75f5ca4.png)

**Comment by jwoo-msft** [comment]
Hi @janusbal,
The below is the image taken from the sample app. As you can see, the issue is not reproducible on the sample app.
![Screen Shot 2021-06-18 at 10 44 36 AM](https://user-images.githubusercontent.com/4112696/122598849-403ae880-d022-11eb-918a-955b00edcec2.png)

The api you mentioned is not used in the iOS SDK. I believe that there is a divergence in the SDK's image renderer and the Teams' custom image renderer that is causing this issue.
c.c. @jonmill

**Comment by janusbal** [comment]
Resolved in client
