### ISSUE TITLE
[Rendering] AAF: Returning `SuccessResponse` without `rawContent`

### ISSUE THREAD

**Issue by compulim** [microsoft/AdaptiveCards#6024]
# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:

- NodeJS

# Target Application

Web Chat

# Problem Description

In the `ChannelAdapter.sendRequestAsync`, when we return the async function with:

```js
return new SuccessResponse(request);
```

Adaptive Cards will throw an error:

![image](https://user-images.githubusercontent.com/1622400/122826748-5ce05600-d298-11eb-8d64-c9269310e896.png)

But, when we return `SuccessResponse` with an empty string, it succeeded without any errors:

```js
return new SuccessResponse(request, '');
```

![image](https://user-images.githubusercontent.com/1622400/122826883-86997d00-d298-11eb-8e37-b2d4bcc4ee50.png)

Looking into the type definition of `SuccessResponse`:

```ts
export declare class SuccessResponse extends ActivityResponse {
    readonly request: IActivityRequest;
    readonly rawContent?: string | undefined;
    constructor(request: IActivityRequest, rawContent?: string | undefined);
}
```

The `rawContent` is optional and support `undefined`. Unfortunately, when we skip it or passing `undefined`, it throw an exception.

# Screenshot

![image](https://user-images.githubusercontent.com/1622400/122826748-5ce05600-d298-11eb-8d64-c9269310e896.png)

# Card JSON

<details>
<summary>Expand to see the card JSON</summary>

```js
{
  type: 'AdaptiveCard',
  body: [
    {
      type: 'TextBlock',
      text: 'Card state: Root'
    }
  ],
  actions: [
    {
      type: 'Action.Execute',
      verb: 'dump',
      title: 'Dump value',
      data: {
        hello: 'World!'
      }
    },
    {
      type: 'Action.Execute',
      verb: 'string',
      title: 'Show a string',
      data: 'Hello, World!'
    }
  ],
  $schema: 'http://adaptivecards.io/schemas/adaptive-card.json',
  version: '1.4'
}
```
</details>

# Sample Code

```ts
async sendRequestAsync(request): Promise<ActivityResponse> {
  return new SuccessResponse(request);
}
```

# Version of SDK

2.9.0

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing for now. We may return to this in the future. Feel free to continue the conversation in this issue. Please reactivate if this is a high priority for your team.
