### ISSUE TITLE
[Website] Schema explorer does not specify what the color format is for backgroundColor

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#6027]
We support a `backgroundColor` property on `Image`, and `Container` types, but it doesn't specify what the string format is. 

We should update the description of any `backgroundColor` properties that it is required to be in hex format, either #RRGGBB or #AARRGGBB 

---
* URL: https://adaptivecards.io/explorer/Image.html

**Comment by licanhua** [comment]
@matthidinger For description of backgroundColor, can I change it from `Applies a background to a transparent image. This property will respect the image style.` to:
`Applies a background to a transparent image. This property will respect the image style. Required to be in hex format, either  #RRGGBB or #AARRGGBB. For example, #C7DEF9`
Also I only see Image has backgroundColor, and Container doesn't have any color property

**Comment by paulcam206** [comment]
This can be addressed as part of #6316 -- tracking there.
