### ISSUE TITLE
[Website] [Your feedback title here]

### ISSUE THREAD

**Issue by pbunyan22** [microsoft/AdaptiveCards#6032]
Can it allow the adjustment of how much the adaptive card fills the outlook reading pane?

---
* URL: https://adaptivecards.io/blog/2019/Announcing-1.2/

**Comment by jonmill** [comment]
The amount of fill in the Outlook reading pane is outside the control of Adaptive Cards...please open a feature request on Outlook to support this scenario since Adaptive Cards does not have any capabilities to change this in Outlook.
