### ISSUE TITLE
[Feature Request] PowerShell Access to Local Templating

### ISSUE THREAD

**Issue by PsychoData** [microsoft/AdaptiveCards#6035]
# What is the problem you are attempting to solve with this feature?

Using Templates make a huge amount of sense, but if it doesn't make sense to have a public Template equivalent (I'm working on making templates to use for posting Alerts, Tickets, and Assets from our RMM provider into Teams) then it is a significant hassle to "apply" a local template to Data JSONs so that you can post it to a service like Teams or similar. 

# A description of your proposed solution to the problem

Publish a PowerShell Module to the PSGallery that uses the .NET / NuGet class , so that you can do something similar to 
```powershell
Import-Module AdaptiveCards #hypothetical, not currently available 
$AdaptiveCardTemplJSON = @"
{
    ""type"": ""AdaptiveCard"",
    ""version"": ""1.2"",
    ""body"": [
        {
            ""type"": ""TextBlock"",
            ""text"": ""Hello ${name}!""
        }
    ]
}
"@
$DataCardJSON = @"
{
    Name = "Matt Hidinger"
}
"@

$AdaptiveCardTempl = New-AdaptiveCardTemplate -JSON $AdaptiveCardTemplJSON
$CardJSON = New-AdaptiveCard -Data $DataCardJSON -Template $AdaptiveCardTempl
```

or even just (though it wouldn't be proper form) import the Class in the module but don't expose specific PowerShell cmdlets  that the user could still use like 
```powershell
Import-Module AdaptiveCards #hypothetical, not currently available 
#....Variable Entries from above
$template = [AdaptiveCardTemplate]::new($templateJson)
$cardJSON = $template.Expand($DataCardJSON) 
``` 

# What alternatives or workarounds have you considered

The [.NET SDK](https://docs.microsoft.com/en-us/adaptive-cards/templating/sdk#net) Looks like it might be able to make a good, local solution for expanding, but installing the NuGet package is throwing warnings, even after that I would have to pull some uncommonly known tricks to use the NuGet's classes from PowerShell (example [1](https://endjin.com/blog/2020/12/how-to-consume-a-nuget-package-in-powershell) and [2](https://www.itinsights.org/Load-PowerShell-assemblies-from-nuget-packages/)) - though there seems to be [issues with the dependencies currently](https://i.imgur.com/fg28duu.png) 

Or host my own version of the  [Templating Service from here ](https://github.com/microsoft/adaptivecards-templates) - and upload my personal templates to there - which would be additional cost and management hassle.

**Comment by jonmill** [comment]
Hi @PsychoData - this is not currently a scenario that we're looking to support. This seems like a great tool for the community to build, but is not currently on our roadmap or a scenario that we're looking to enable moving forward

**Comment by PsychoData** [comment]
It's pretty simple, but I did a thing 
 
 https://www.powershellgallery.com/packages/Posh-AdaptiveCards

Now in PowerShell you can do something like this, to use an adapted example from the [Templating SDKs page](https://docs.microsoft.com/en-us/adaptive-cards/templating/sdk)
(Note I had to use @'  '@ here strings not @"   "@ here-strings so that the `${name}` wouldn't try to expand before it was time)

```powershell
Install-Module -Name Posh-AdaptiveCards    

$TemplateJSON= @'
{
    "type": "AdaptiveCard",
    "version": "1.3",
    "body": [
        {
            "type": "TextBlock",
            "text": "Hello ${Name}!"
        }
    ]
}
'@ 
$DataJSON = @'
{
            "Name": "Matt Hidinger"
}
'@
New-AdaptiveCardInstance -Data $DataCardJSON -Template $TemplateJSON
```
which yields 
```json
{"type":"AdaptiveCard","version":"1.3","body":[{"type":"TextBlock","text":"Hello Matt Hidinger!"}]}
```
