### ISSUE TITLE
Adaptive Card Rich Text Block Issue

### ISSUE THREAD

**Issue by gleason7** [microsoft/AdaptiveCards#6037]
Hi Team,

I'm using AdaptiveRichTextBlock in my application but don't know how to add value in Inlines as shown below.
Getting error please have a look on the screenshot. Please help me asap how to add value in Inlines.

 card.Body.Add(new AdaptiveRichTextBlock()
                {
                    Inlines = "[{ 'type':'TextRun','text':'gleason','strikethrough':true,'weight':'bolder'}]",
                });

![image](https://user-images.githubusercontent.com/69605707/123614102-a6ddb480-d821-11eb-879d-b72db9605a8f.png)

Thanks & Regards,
Gleason Philip

**Comment by jonmill** [comment]
Hi Gleason - the object model requires adding objects to the `Inlines`, not JSON. You can parse JSON into a card *or* you can work using the object model, but you can't combined the two by working with JSON and the object model to generate a card like this. Try using the `TextRun` class to add what you're looking for
