### ISSUE TITLE
[Schema Explorer] Input.Text pattern property not documented.

### ISSUE THREAD

**Issue by Stevenic** [microsoft/AdaptiveCards#6071]
# Problem Description

The designer has a `pattern` property for \`Input.Text\` but it's not documented in the Schema Explorer.

**Comment by jonmill** [comment]
The property name looks to be incorrect as this property actually maps to the `Regex` property. We need to update the designer to fix this

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.
