### ISSUE TITLE
[Rendering] Adaptive Cards is not wrapping Text Block when I set wrap=true

### ISSUE THREAD

**Issue by shaobo9856** [microsoft/AdaptiveCards#6073]
# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:
- UWP

# Target Application

 Windows - Bot Framework Emulator (V4)

# Problem Description
I am developing a chatbot using Microsoft Bot framework. I want the robot to return a TextBlock, because the text in the TextBlock is very long, so I set Wrap = true, the text indeed does automatically wrap, but the last few words in the first line do not seem to be displayed, I tried many times, it doesn't work. can you help me? Below is my code and screenshot.

# Screenshot

![image](https://user-images.githubusercontent.com/26827545/125092433-a373e400-e0d1-11eb-992e-0bcad5c8a823.png)
![image](https://user-images.githubusercontent.com/26827545/125092465-a969c500-e0d1-11eb-8b85-06dbaac915f1.png)
![image](https://user-images.githubusercontent.com/26827545/125092618-cd2d0b00-e0d1-11eb-94a7-3538e64fd4d9.png)

# Sample Code

            AdaptiveCard card = this.CreateAdaptiveCard();
            AdaptiveTextBlock textBlock = new AdaptiveTextBlock()
            {
                Text = "- Only 2 out of 3  are shown.  If you cannot find the required product,  please type in a more specific part number.",
                Size = AdaptiveTextSize.Small,
                Wrap = true,
            };

            card.Body.Add(textBlock);

# Version of SDK

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Net Framework Setup\NDP\CDF\v4.0
    HttpNamespaceReservationInstalled    REG_DWORD    0x1
    NetTcpPortSharingInstalled    REG_DWORD    0x1
    NonHttpActivationInstalled    REG_DWORD    0x1
    SMSvcHostPath    REG_SZ    C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
    WMIInstalled    REG_DWORD    0x1

**Comment by shaobo9856** [comment]
Who can help me?

**Comment by paulcam206** [comment]
The clipping here is due to the host application ([Bot Framework Emulator](https://github.com/Microsoft/BotFramework-Emulator) in this case) -- please [file a bug](https://github.com/microsoft/BotFramework-Emulator/issues/new/choose) on them to investigate.
