### ISSUE TITLE
[Rendering] [Teams] Image not rendered on Microsoft Teams chat desktop & browser application

### ISSUE THREAD

**Issue by khanisak** [microsoft/AdaptiveCards#6076]
# Target Application

Please provide the name of the application that is rendering the card (ex: Outlook, Teams, etc)
- Microsoft Teams (Browser, Desktop for Mac & Desktop for Windows)

# Problem Description

Image on adative card  rendered well on Mobile Application, but not in Browser & Desktop (mac & windows) Teams application.

# Screenshot

this is mobile application screenshot which is well rendered
![rendering goods](https://user-images.githubusercontent.com/15967833/125248034-cbf01e00-e31d-11eb-9a96-88b512a3b941.jpeg)

and this one is screenshot from teams desktop on windows. teams desktop for mac & teams browser application is same.
![image](https://user-images.githubusercontent.com/15967833/125248171-f80b9f00-e31d-11eb-998a-e6b892123215.png)

# Card JSON

```
{
                    $schema: "http://adaptivecards.io/schemas/adaptive-card.json",
                    type: "AdaptiveCard",
                    version: "1.2",
                    body: [{
                        type: "TextBlock",
                        text: `${contentType} :`,
                        weight: "Bolder",
                        size: "Medium",
                        color: "Accent"
                    },
                    {
                        type: "TextBlock",
                        text: `[${title}](${newsUrl})`,
                        isSubtle: true,
                        wrap: true
                    },
                    {
                        type: "Image",
                        url: image, // "base64 image"
                        horizontalAlignment: "Center"
                    }]
                }
```

**Comment by muhamadizzuddin** [comment]
how can you do this
________________________________
From: Khanis Anthony K ***@***.***>
Sent: 12 July 2021 15:36
To: microsoft/AdaptiveCards ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/AdaptiveCards] [Rendering] [Teams] Image not rendered on Microsoft Teams chat desktop & browser application (#6076)


Target Application

Please provide the name of the application that is rendering the card (ex: Outlook, Teams, etc)

  *   Microsoft Teams (Browser, Desktop for Mac & Desktop for Windows)

Problem Description

Image on adative card rendered well on Mobile Application, but not in Browser & Desktop (mac & windows) Teams application.

Screenshot

this is mobile application screenshot which is well rendered
[rendering goods]<https://user-images.githubusercontent.com/15967833/125248034-cbf01e00-e31d-11eb-9a96-88b512a3b941.jpeg>

and this one is screenshot from teams desktop on windows. teams desktop for mac & teams browser application is same.
[image]<https://user-images.githubusercontent.com/15967833/125248171-f80b9f00-e31d-11eb-998a-e6b892123215.png>

Card JSON

{
                    $schema: "http://adaptivecards.io/schemas/adaptive-card.json",
                    type: "AdaptiveCard",
                    version: "1.2",
                    body: [{
                        type: "TextBlock",
                        text: `${contentType} :`,
                        weight: "Bolder",
                        size: "Medium",
                        color: "Accent"
                    },
                    {
                        type: "TextBlock",
                        text: `[${title}](${newsUrl})`,
                        isSubtle: true,
                        wrap: true
                    },
                    {
                        type: "Image",
                        url: image, // "base64 image"
                        horizontalAlignment: "Center"
                    }]
                }

**Comment by khanisak** [comment]
@muhamadizzuddin sorry, i didn't understand. can you explain your question in more detail?

**Comment by khanisak** [comment]
I found out this problem only occur when I build adaptive card and specify image with base64image. 
Teams desktop rendered well if I specify image with public url instead. 

I believe this is bug in microsoft teams for desktop & web application since teams for mobile apps did not experience this issue.

**Comment by khanisak** [comment]
After a few days of successfully sending adaptive cards, yesterday i found out that all my image of adapative cards in my chat history suddenly not showing. 

its weird since the image show up well when I send the message and after a few days it only show broken image like below.
![image](https://user-images.githubusercontent.com/15967833/128475269-73021351-89b4-4acb-94e6-0e5f8fb803d2.png)

Once again, its only happen in Teams desktop and teams web. The image still show up well in my android and ios devices until today. 

One more thing I can tell for this issue is,
Url of the broken image in one of my message now is points to https://urlp.asm.skype.com/v1/url/content?url=url-to-image. 
And i got http error 502 when I hit this url.

But I remember exactly that few days ago, that image url is points to https://urlp.sfbassets.com/urlpcdn/ea1/contentdel30/uid-of-content. And until today, this link can be opened and display my image correctly.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4941
