### ISSUE TITLE
Fact.Title wraps when Value is long

### ISSUE THREAD

**Issue by ankitbko** [microsoft/AdaptiveCards#608]
I am facing an issue where if the`value` of any fact in FactSet is large enough, all the `fact.title` in the set wraps too. See below images for reference. Doesn't look very nice, any way to avoid this behavior?

When value is small -  

![image](https://user-images.githubusercontent.com/3169316/30100476-a558bd76-9306-11e7-9149-6ebfa7e03241.png)

When value is large enough -  

![image](https://user-images.githubusercontent.com/3169316/30100442-8a847dbe-9306-11e7-8b3c-1e1351aa1192.png)

**Comment by dclaux** [comment]
@ankitbko FactSet is rendered as a 2-column Table. Title is allowed to wrap so as to not take too much space if it's long. But the drawback is what you're seeing. We can force title to not wrap, but then this can happen:

![image](https://user-images.githubusercontent.com/1334689/30137917-71c36f06-931a-11e7-99a7-5c7d6f8a61ef.png)

Not sure that's better?

Alternatively, we could prevent wrapping if the title has fewer than a certain number of characters (maybe 50?), and wrap above that.

Thoughts?

**Comment by danmarshall** [comment]
I just tried an HTML entity and it worked! The non-breaking space character `&nbsp;`
`Assigned&nbsp;to:`
Not sure if this is a bug or a feature :)

**Comment by dclaux** [comment]
Well, it's a feature of HTML :) But is it the right way to handle this?

**Comment by ubreddy** [comment]
well even if the it is a single word it wraps... which looks quite ugly... 
![needs-formatting](https://user-images.githubusercontent.com/2233628/35714558-747d3d8c-07f3-11e8-92ef-f740b8d2836d.png)
Any solution suggested?

**Comment by chaim770** [comment]
Why not let us control the behavior (just like in HTML/CSS with `white-space`/`nowrap` directives)?

Something like:

`{
    "title": "Some long title",
    "value": "Nevermind",
    "wrap": false
}`

**Comment by dclaux** [comment]
It seems to me that the problem isn't really whether or not the title is wrapped, but more "if it does wrap, when does it wrap". FactSet is a table under the covers; the width of the left column (holding the title) can essentially be defined in 3 different ways:
1. As wide as needed to fit all titles on a single line
2. As a fixed value
3. Or as a percentage of the total available space

Option 1 just doesn't work in many cases:
- If a the set contains a long and a short title for instance
- If titles are long and values are long too

With option 2 and 3, titles can either wrap or be truncated. I don't believe truncating titles is the right thing to do.

If we allowed you to say "my titles don't wrap", you'd potentially end up with titles that are truncated. Worse - in a card template that binds to data and the data isn't known in advance, the sample data used to design the template might not lead to title truncation but the real data might.

Currently, with the JS SDK at least, the sizing of the title column is left to the layout engine, whose logic is this:
- Determine the proportion of the total width title and value would need if each was displayed on a single line
- Give the title and value columns that proportion of the actually available width

In turn, that leads to little space for title and lots of space for value if title is significantly shorter than value, which is the case in the examples provided in this issue.

To me the most appropriate solution would be to allow the card author to specify the width of the title column in pixels, and always wrap titles as is currently the case.

**Comment by ig-jb** [comment]
> To me the most appropriate solution would be to allow the card author to specify the width of the title column in pixels, and always wrap titles as is currently the case.

This would solve the problem I've got. Would it be worth accepting other values e.g. rem/em so that the card author can allow for hosts rendering fonts in differing sizes?

**Comment by RebeccaAnne** [comment]
The current behavior is by our current design and not something we're considering revisiting at this time.
