### ISSUE TITLE
[Feature Request] Accessibility Issue

### ISSUE THREAD

**Issue by srinutamada** [microsoft/AdaptiveCards#6085]
I am using adaptive cards in my Team's chatbot. When I tried to use "Immersive Read" option that Team's messages having, it didn't read what content that card is having.

Where as its working fine without any adaptive card. So, can you implement accessibility capability for adaptive cards so that it can be used in Teams or Web chat.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/3925
