### ISSUE TITLE
Extra indentation in the navigation bar causing text to wrap

### ISSUE THREAD

**Issue by rahulamlekar** [microsoft/AdaptiveCards#6089]
# Platform

Website

# Issue

The indentation in the navigation bar on the left should be close to 0. This is in main but isn't deployed yet (go to the adaptive cards ci url to repro).

![image](https://user-images.githubusercontent.com/9759782/125665888-c0ecacc5-beb8-40f8-8df5-347c580209e7.png)

**Comment by RebeccaAnne** [comment]
If this doesn't repro on the main site this may be a recent-ish regression.

**Comment by paulcam206** [comment]
@JeanRoca - can you take a look at this?

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
