### ISSUE TITLE
Support custom glyphs for text and actions

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#609]
Need to spec this out.

**Comment by mdtauk** [comment]
Other than an image payload within the card, wouldn't this require the ability to use custom font files?  How do you practically allow that, other than using a web-hosted and cached file.

By default, HTML Card renderers can handle this with @fontface - but for Android, iOS, UWP?

**Comment by matthidinger** [comment]
It will have to be part of the API we give developers using the SDKs, and the custom glyphs will only work in an app that registers support for it. For example Skype could register a custom glyph font in all of the platforms, and they would tell their bot developers what glyphs are available to use.

**Comment by mdtauk** [comment]
@matthidinger  So there will be an ability for the host app to "provide" a custom font with glyphs in, and call on them within the payload.  Not restricted to the MDL2 font icons, or platform glyph fonts.

**Comment by anbare** [comment]
Toasts would find this useful. "Quick Pair" settings team uses Seoge MDL2 font icons for 95% of their images, so if they want to use a toast, they have to first create images out of them which is impractical and wastes storage space.

**Comment by matthidinger** [comment]
Dupe of #3053 

@VMey we are working on a story to make this possible, hopefully able to share more early next year!
