### ISSUE TITLE
"isSubtle" is invalid in Teams Chat, but normal in Designer.

### ISSUE THREAD

**Issue by hulin17** [microsoft/AdaptiveCards#6095]
designer: ![image](https://user-images.githubusercontent.com/31561654/125882601-39d8aa00-a2c7-4c9b-96ba-debc26d040c2.png)
Teams Desktop App: ![image](https://user-images.githubusercontent.com/31561654/125882618-9bab3433-f074-44ed-93e4-b157ee588ec3.png)
Microsoft.Bot.Builder:Version=4.11.1.0
FYI.

Can someBody help me? Thanks!

**Comment by hulin17** [comment]
@jonmill Pls help me. Thanks a lot.

**Comment by hulin17** [comment]
![image](https://user-images.githubusercontent.com/31561654/125884432-d86d17e1-ab45-4b55-be7d-752cbe14680f.png)
![image](https://user-images.githubusercontent.com/31561654/125884442-580dbf5f-e251-41c3-8f3c-d53933184049.png)
Clearer.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/3864
