### ISSUE TITLE
[Feature Request] MAUI update?

### ISSUE THREAD

**Issue by pooran** [microsoft/AdaptiveCards#6098]
# What is the problem you are attempting to solve with this feature?

We were waiting for Xamarin.Forms version to come along. But I think if we have a version for MAUI, it will be great. Is it already in the roadmap/works?

# A description of your proposed solution to the problem

With MAUI set to launch in few months, it will be great if we have Adapative Cards finally available for MAUI

**Comment by RebeccaAnne** [comment]
Supporting MAUI is not currently on our roadmap.
