### ISSUE TITLE
Video won't play in an adaptive card

### ISSUE THREAD

**Issue by peterjkrebs** [microsoft/AdaptiveCards#6099]
I'm testing adaptive card functionality for a to determine if it can be used across Microsoft Help and training. Right now, the blocking issue is I can't get video to play in the card. 

{
            	"type": "Media",
            	"poster": "https://adaptivecards.io/content/poster-video.png",
            	"sources": [
                {
                    "mimeType": "video/mp4",
                    "url": "https://youtu.be/qKG8r1NERl4"
                }

Ideally I would like the following video syntax supported:
For Office and Doc videos, we used this syntax: https://www.microsoft.com/videoplayer/embed/RE42hMy
I've also tried adding a YouTube vide with this syntax, but it doesn't work either: https://youtu.be/qKG8r1NERl4
---
* URL: https://adaptivecards.io/blog/

**Comment by jonmill** [comment]
@peterjkrebs - we don't currently support YouTube links for card media and it is not currently in our scope to enable
