### ISSUE TITLE
Input.ChoiceSet not working inside ColumnSet

### ISSUE THREAD

**Issue by Maglar42** [Microsoft/AdaptiveCards#610]
I am attempting to build out a formatted set of labels and drop downs next to each other.  To do this i was creating a container then adding a column set with a text block and a choice set.  I am using adaptive-cards.js built from renderer on npm.  When attempting to call this in my project i just get a grayed out box for a drop down.  After trying a number of different combinations in the visualizer i figured out it is an issue with the drop down logic inside a column set.  Here is the simplest example where i am seeing this issue:

{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "0.5",
	"speak":
		"<s>Nothing to say here</s>",
	"body": [
		
		{
			"type": "ColumnSet",
			"separation": "strong",
			"columns": [
				{
					"type": "Column",
					"size": "auto",
					"items": [
						{
							"type": "TextBlock",
							"text": "Drop Down 1",
							"isSubtle": false,
							"horizontalAlignment": "left"
						}
					]
				},
				{
					"type": "Input.ChoiceSet",
					"id": "myColor",
					"style": "compact",
					"isMultiSelect": false,
					"value": "1",
					"choices": [
					  {
						  "title": "Option 1",
						  "value": "1",
						  "isSelected": true
					  },
					  {
						  "title": "Option 2",
						  "value": "2"
					  },
					  {
						  "title": "Option 3",
						  "value": "3"
					  }
					]
				}
			]
			
		}
	]
}

This issue is similar to this: https://github.com/Microsoft/AdaptiveCards/issues/500

**Comment by matthidinger** [comment]
Good catch! @dclaux any ideas?

**Comment by dclaux** [comment]
@Maglar42: A ColumnSet can only contain Column elements. The payload above has a ColumnSet that contains a Column and then a ChoiceSet. The ChoiceSet won't render because it's not a Column. You need to put it in a Column, see below payload.

A couple additional notes:
* "type": "Column" isn't required for a Column, it can be omitted
* isSelected isn't valid. To set the initial value of a ChoiceSet, specifying its "value" property is enough, exactly as you did.

```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "0.5",
    "speak": "Nothing to say here",
    "body": [
        {
            "type": "ColumnSet",
            "separation": "strong",
            "columns": [
                {
                    "type": "Column",
                    "size": "auto",
                    "items": [
                        {
                            "type": "TextBlock",
                            "text": "Drop Down 1",
                            "isSubtle": false,
                            "horizontalAlignment": "left"
                        }
                    ]
                },
                {
                    "items": [
                        {
                            "type": "Input.ChoiceSet",
                            "id": "myColor",
                            "style": "compact",
                            "isMultiSelect": false,
                            "value": "1",
                            "choices": [
                                {
                                    "title": "Option 1",
                                    "value": "1"
                                },
                                {
                                    "title": "Option 2",
                                    "value": "2"
                                },
                                {
                                    "title": "Option 3",
                                    "value": "3"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by Maglar42** [comment]
Sorry about that and thank you that is working great now.
