### ISSUE TITLE
Link is "null" in Button Action

### ISSUE THREAD

**Issue by freakontour** [microsoft/AdaptiveCards#6101]
# Target Application

Target Application is Microsoft Teams, I am using an incoming Webhook to send the JSON as Message

# Problem Description

I've created the Message in the expected JSON-Format. There is a message to show the user some short information about the problem. Attached is a Button to get an direct link to our internal System. 
When I am using the link to our Webserver, the Button gets has as link property null. If I using http://google.de, the card is working fine.

I didnt find the failure, maybe there is an blackfilter of Websites. But I didn't find any settings about it.

`{
"@type":"MessageCard",
"@context":"http://schema.org/extensions",
"themeColor":"ff0000",
"summary":"Line 227",
"sections":[
    {
        "text":"**Linie 227** benötigt einen Vorarbeiter\nStation: Linie"
    }
    ],
    "potentialAction": [
        {
            "@type":"OpenUri",
            "name":"Show Message",
            "targets":[
                {
                    "os":"default",
                    "uri":"http://gps01/FAS/QRQC/Maintain/Message/ConfirmMessage.aspx?messageID=20135"
                }
                ]
        }
        ]
}`

**Comment by jonmill** [comment]
@freakontour - thanks for opening the issue! Can you please clarify how you're determining that the button has a null link property? Is this something you're seeing on the server side or client side? The more details here the better 🙂

**Comment by freakontour** [comment]
@jonmill thank you for answering.
I using this card to send from an external program a message card to a teams channel. When I am using "http:google.com" in the Button I will forwarding to google. But when I am using my own Address which is hosted internal (http.gps01/FAS/) there is no forwarding. In the past the message card was working. After a few days the button was forwarding to "teams.microsoft.com/null". Now is the button not working when I using our internal link. Not working means that the button is clickable in the Client but no action triggered.

I am tried it with Mac Client for Teams, Webclient for Teams and Microsoft Client for Teams.
What I am wondering, its working on iOS Client for Teams on my iPhone.

**Comment by jonmill** [comment]
Ah, thank you that helps clarify. This sounds like Teams has a bug in their URL opening...I'll transfer the issue over to them to take a look

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/3924
