### ISSUE TITLE
Why blockquote is not working?

### ISSUE THREAD

**Issue by srinutamada** [microsoft/AdaptiveCards#6102]
I am currently using <blockquote> for differentiating few chatbot response from others. Its working perfectly. Now I got requirements to implement similar thing for adaptive cards.

I tried all possible ways and nothing worked. Is there any way to highlight or differentiate few adaptive card response from others?
If so, please provide help on it. If not, please implement the functionality or capability to it.

Channel I am using is 'MS Teams'

**Comment by jonmill** [comment]
@srinutamada - please re-file using our issue templates and fill in the required data so we can fully understand the issue you're facing. Thank you!

**Comment by srinutamada** [comment]
I am using blockquote for showing some content in chatbot. It is working fine with simple messages. But if I am using same in Adaptive card for text messages, its not working.
