### ISSUE TITLE
[iOS][Rendering] Using "didLoadElements" doesn't always get called after the ACRRenderer has returned a result

### ISSUE THREAD

**Issue by shabripabba** [microsoft/AdaptiveCards#6107]
# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:
- iOS

# Target Application

Please provide the name of the application that is rendering the card (ex: Outlook, Teams, etc)
Teams

# Problem Description
After using "didLoadElements" delegate function, it was noticed that there are scenarios where the "didLoadElements" gets called even before "ACRRenderer" returns a ACRView, so even though we were sending a reloadRowsAtIndexPaths on "dispatch_async(dispatch_get_main_queue()..." this causes an infinite loop, as the tableviewcell tries to reload before the "ACRRenderer" returned a view.

Please enter a description of the issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards)

# Screenshot

Please provide a screenshot of the problem (if possible)

# Card JSON

Please provide the JSON of the Card that is being rendered

# Sample Code

Please provide any relevant code samples to help reproduce the issue

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest main, etc...
2.8.0-beata1, branch - release/21.04

**Comment by jwoo-msft** [comment]
@shabripabba,

Are you using resource resolver for images? If not, the delegate would not work properly. The resource resolver tracks the images to load, and call the delegate when all images are loaded. If resolver is not implemented, the delgate may get called while your app is loading the images.

**Comment by jwoo-msft** [comment]
c.c @jonmill 
Teams mobile is working on the fix using the default image renderer with a custom resource resolver.
@shabripabba
feel free to re-open this issue.
