### ISSUE TITLE
JS Learning

### ISSUE THREAD

**Issue by jonmill** [microsoft/AdaptiveCards#6108]
Time set aside to go through the Plurasight Javascript & ReactNative training

1) Get access to Plurasight: https://microsoft.sharepoint.com/sites/infopedia/engineering/Pages/Cards/Get-Plurasight.aspx
2) Take the 4 hour course: https://www.pluralsight.com/courses/react-js-getting-started

**Comment by almedina-ms** [comment]
This is the basics course for language syntax

https://app.pluralsight.com/library/courses/getting-started-typescript/table-of-contents
