### ISSUE TITLE
HTML Renderer should show warnings/fail to render for JSON-schema violations

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#611]
The HTML renderer currently accepts string values where a bool is expected, but the other renderers are strict about requiring a bool.  The payload below works in HTML but not in UWP or Android. 

Our JSON-schema states that wrap is a boolean so we should probably run the payload through a JSON-schema validator and either output the warnings in the Visualizer or maybe fail to render.

Thoughts?

```json
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "0.5",
  "body": [
    {
     "type": "TextBlock",
     "text": "Hello",
     "wrap": "true"
    }
    ]
}
```

**Comment by dclaux** [comment]
Yes, we should run through a schema validator. This however requires that we have an up to date JSON schema, which I don't think is the case right now.
