### ISSUE TITLE
[Feature Request][PR attached] Enable the use of custom functions within adaptivecards-templating 

### ISSUE THREAD

**Issue by jsonsCode** [microsoft/AdaptiveCards#6133]
# Platform

**JavaScript**

# Version of SDK

**adaptivecards-templating**:  
Latest (Present in both NPM latest 2.1.0 and the main branch 2.2.0-beta.1)

# What is the problem you are attempting to solve with this feature?
Currently users are unable to add custom functions to adaptive-expressions and have them parsed in adaptivecards-templating due to the JS library of only searching in the standardFunctions map.

I have created a PR #6132 to enable the use of adaptive-expression custom functions with the JS adaptive-templating package.

# A description of your proposed solution to the problem

The current version of adaptive expressions (and the targeted version in peerDependencies) supports custom functions for templating, with information for the C# version of the library documented [here](https://docs.microsoft.com/en-gb/adaptive-cards/templating/sdk#custom-functions).

This can be supported in the JS version of adaptive-templates by switching out the lookup in the *parseInterpolatedString* method to use the *FunctionTable* of adaptive-expressions, rather than the *standardFunctions* Map, which currently limits developers to only using the standard library.

**Comment by RebeccaAnne** [comment]
Thanks for this issue and PR! Based on our contribution guidelines we'll need to go through a spec review before taking this feature. Please reference our contribution guidelines and answer the questions presented in there. 

[CONTRIBUTING.md](https://github.com/Microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md)

**Comment by paulcam206** [comment]
We may revisit this in the future, but at this point taking this change is not on our roadmap.

**Comment by cheeseypi** [comment]
Absolutely absurd that this change (That just brings parity with the .NET version of adaptive-templating) was not merged.
