### ISSUE TITLE
[Designer] Incorrect rendering of markdown for Microsoft Teams host application

### ISSUE THREAD

**Issue by Corey-M** [microsoft/AdaptiveCards#6148]
I have been using the Adaptive Cards Designer to test the appearance of cards generated from my code. After getting the output how I wanted it, I sent the card to Teams and found that the MarkDown support in the live product does not support some of the features that the Designer does.

Specifically, the following TextBlock renders 'correctly' in the Designer, although in Teams the 'indented code block' MarkDown feature is not supported:

	{
		"type": "TextBlock",
		"text": "\t   at Example.UpdateDevice.DoUpdate() in C:\\Dev\\Example\\UpdateDevice.cs:line 35\n\t   at Example.UpdateDevice.Update(DataSource source) in C:\\Dev\\Example\\UpdateDevice.cs:line 31\n\t   at Example.Updater`1.Run(DataSource source) in C:\\Dev\\Example\\Updater.cs:line 46"
	}

While more extensive MarkDown support in Teams would be the preferred outcome, it would be nice if the Designer gave a more accurate rendering as per the limitations of the specific applications.

**Comment by RebeccaAnne** [comment]
Per current spec code blocks are not supported. We will revisit whether we want to add this support as part of our larger discussion surrounding markdown. [Text Features](https://aka.ms/actextfeatures)

**Comment by Corey-M** [comment]
@RebeccaAnne Microsoft Teams current version (v1.4.00.19572) on Windows desktop. While I'd love to see broader markdown support in Teams, until we do it'd be nice if the Designer was in sync with the supported features for the product previewers.

**Comment by jonmill** [comment]
Closing as this is currently by-design
