### ISSUE TITLE
[Adaptive Cards Templating] $when Works as expected if ${PlaceHolder} is empty string. However, it does not work as expected if ${PlaceHolder} is null.

### ISSUE THREAD

**Issue by pankajvaher** [microsoft/AdaptiveCards#6152]
# Target Platform
- .NET HTML

# Target Application
Teams

# Problem Description
\"$when\":\"${ResultSnippet != ''}\" Works as expected if ResultSnippet is empty string. However, it does not work as expected if ResultSnippet  is null.

## Template string
"{\"type\":\"AdaptiveCard\",\"version\":\"1.2\",\"body\":[{\"type\":\"ColumnSet\",\"columns\":[{\"type\":\"Column\",\"width\":\"auto\",\"items\":[{\"type\":\"Image\",\"url\":\"https://searchuxcdn.azureedge.net/designerapp/images/servicenow-icon.png\",\"size\":\"Small\",\"horizontalAlignment\":\"Center\",\"altText\":\"ServiceNow logo\"}],\"height\":\"stretch\"},{\"type\":\"Column\",\"width\":8,\"items\":[{\"type\":\"TextBlock\",\"text\":\"[${number} ${shortdescription}](${AccessUrl})\",\"color\":\"Accent\",\"size\":\"Medium\",\"weight\":\"Bolder\",\"$when\":\"${shortdescription != ''}\"},{\"type\":\"RichTextBlock\",\"inlines\":[{\"type\":\"TextRun\",\"$when\":\"${sysupdatedby != ''}\",\"text\":\"${sysupdatedby} \",\"weight\":\"Bolder\"},{\"type\":\"TextRun\",\"$when\":\"${sysupdatedby != ''}\",\"text\":\" modified \"},{\"type\":\"TextRun\",\"$when\":\"${sysupdatedon != ''}\",\"text\":\"{{DATE(${sysupdatedon})}}\"}],\"spacing\":\"None\"},{\"type\":\"TextBlock\",\"text\":\"${ResultSnippet}\",\"wrap\":true,\"maxLines\":3,\"spacing\":\"Medium\",\"$when\":\"${ResultSnippet != ''}\",\"color\":\"Dark\"}],\"horizontalAlignment\":\"Center\",\"spacing\":\"Medium\"}]}],\"$schema\":\"http://adaptivecards.io/schemas/adaptive-card.json\"}"

## Sample Data:
{
   "number": "KB0046925",
   "shortdescription": "User Account: How to Send B2B Invites Using the Azure Portal?",
   "AccessUrl": https://microsoft.service-now.com/kb_view.do?sys_kb_id=2dfd5689db52cf800c1f546adc9619ed,
   "sysupdatedby": "v-preetm",
   "sysupdatedon": "2021-07-20T18:52:16Z",
   "HitHighlightedProperties": ""
}

## Expanded Adaptive card:
{
  "type": "AdaptiveCard",
  "version": "1.2",
  "body": [
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "Image",
              "url": "https://searchuxcdn.azureedge.net/designerapp/images/servicenow-icon.png",
              "size": "Small",
              "horizontalAlignment": "Center",
              "altText": "ServiceNow logo"
            }
          ],
          "height": "stretch"
        },
        {
          "type": "Column",
          "width": 8,
          "items": [
            {
              "type": "TextBlock",
              "text": "[KB0046925 User Account: How to Send B2B Invites Using the Azure Portal?](https://microsoft.service-now.com/kb_view.do?sys_kb_id=2dfd5689db52cf800c1f546adc9619ed)",
              "color": "Accent",
              "size": "Medium",
              "weight": "Bolder"
            },
            {
              "type": "RichTextBlock",
              "inlines": [
                {
                  "type": "TextRun",
                  "text": "v-preetm ",
                  "weight": "Bolder"
                },
                {
                  "type": "TextRun",
                  "text": " modified "
                },
                {
                  "type": "TextRun",
                  "text": "{{DATE(2021-07-20T18:52:16Z)}}"
                }
              ],
              "spacing": "None"
            },
            {
              "type": "TextBlock",
              "text": "${ResultSnippet}",
              "wrap": true,
              "maxLines": 3,
              "spacing": "Medium",
              "color": "Dark"
            }
          ],
          "horizontalAlignment": "Center",
          "spacing": "Medium"
        }
      ]
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}

# Sample Code

AdaptiveCardTemplate template = new AdaptiveCardTemplate(templateJsonString);
string cardJson = template.Expand(Source);
AdaptiveCardParseResult cardParseResult = AdaptiveCard.FromJson(cardJson);

# Version of SDK

AdaptiveCards.Templating Version="1.2.1"

**Comment by jwoo-msft** [comment]
@pankajvaher 
Your use case seems to be invalid.
nil is not the same as an empty string.
Can you add null check or it with emptying string check?
The comparison you make is powered by [AEL](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-adaptive-expressions?view=azure-bot-service-4.0&tabs=comparison)
Please do check the [AEL](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-adaptive-expressions?view=azure-bot-service-4.0&tabs=comparison) site for more information.
