### ISSUE TITLE
[Rendering] Bug Title Here

### ISSUE THREAD

**Issue by Roger-Tribe** [microsoft/AdaptiveCards#6155]
# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:
- NodeJS

# Target Application

Single Page web Application in Angular

# Problem Description

The accessibility structure of the Action.Submit container does not contain any menu-items when the container is a menubar.
This is not in accordance to the recommended definition of a menubar for accessibility.
https://www.w3.org/TR/wai-aria-practices-1.1/#menu

# Screenshot

Please provide a screenshot of the problem (if possible)
<img width="1147" alt="screen-shot" src="https://user-images.githubusercontent.com/69205389/127836660-913cf56a-f821-4e56-81f7-27c39f515036.PNG">

# Card JSON

Please provide the JSON of the Card that is being rendered:
``` json
"{\"$schema\": \"http://adaptivecards.io/schemas/adaptive-card.json\",\"type\": \"AdaptiveCard\",\"version\": \"1.3\",\"body\": [{\"type\": \"Input.Text\",\"isRequired\": \"true\",\"errorMessage\": \"Required\",\"label\": \"Passport/ID number\",\"placeholder\": \"Passport/ID number\",\"isMultiline\": \"false\",\"regex\": \"\",\"maxLength\": 50,\"style\": \"text\",\"id\": \"PPT003862000010000\",\"value\": \"${PPT003862000010000}\"},{\"type\": \"Input.Date\",\"isRequired\": \"true\",\"label\": \"Passport/ID issue date\",\"errorMessage\": \"Required\",\"id\": \"PPT003862000020000\",\"value\": \"${PPT003862000020000}\"},{\"type\": \"Input.Date\",\"isRequired\": \"true\",\"label\": \"Passport/ID expiry date\",\"errorMessage\": \"Required\",\"id\": \"PPT003862000030000\",\"value\": \"${PPT003862000030000}\"},{\"type\": \"Input.Text\",\"isRequired\": \"true\",\"errorMessage\": \"Required\",\"label\": \"Passport/ID country of issue\",\"placeholder\": \"Passport/ID country of issue\",\"isMultiline\": \"false\",\"regex\": \"\",\"maxLength\": 50,\"style\": \"text\",\"id\": \"PPT003862000040000\",\"value\": \"${PPT003862000040000}\"}],\"actions\": [{\"type\": \"Action.Submit\",\"title\": \"Back\",\"style\": \"positive\",\"associatedInputs\" : \"none\"},{\"type\": \"Action.Submit\",\"title\": \"Next\",\"style\": \"positive\"}]}"
```

# Sample Code

Please provide any relevant code samples to help reproduce the issue
See scree-shot image attached for code.

# Version of SDK

"adaptive-expressions": "^4.12.0",
"adaptivecards": "^2.9.0",
"adaptivecards-templating": "^2.1.0"

**Comment by RebeccaAnne** [comment]
Dup of #6156
