### ISSUE TITLE
[Website] [selectAction of TaskRun doesn't work]

### ISSUE THREAD

**Issue by hw123** [microsoft/AdaptiveCards#6162]
[Your detailed feedback here]
My program is displaying adaptive card using .NET HTML SDK.
When following json data is rendered, selectAction of each TextRun seems not to be rendered.
So it is displayed as normal text.
I reviewed schema and searched many web site,
inlines in RichTextBlock and selectAction in TextRun is defined in schema.
I tried with SDK(2.3.0) and latest version(2.7.1).
Please let me know what I did wrong.
```json
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.3",
    "body": [
        {
            "type": "TextBlock",
            "text": "Text1",
            "wrap": "true"
        },
        {
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "1. Menu1",
                    "selectAction": {
                        "type": "Action.Submit",
                        "data": {
                            "id": "1"
                        }
                    }
                }
            ]
        },
        {
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "2. Menu2",
                    "selectAction": {
                        "type": "Action.Submit",
                        "data": {
                            "x": "2"
                        }
                    }
                }
            ]
        }
    ]
}
```

Thank you!
---
* URL: https://adaptivecards.io/blog/

**Comment by RebeccaAnne** [comment]
.NET HTML is not being actively developed and doesn't currently support all features (including this one). Would the JavaScript renderer work for you?

https://github.com/microsoft/AdaptiveCards/blob/main/SUPPORT.md#1x-maintenance-1
