### ISSUE TITLE
[Rendering] Different colors rendered in Teams.

### ISSUE THREAD

**Issue by flora-luo** [microsoft/AdaptiveCards#6170]
# Target Platform
- NodeJS

# Target Application
- Teams

# Problem Description
The text colors rendered by Teams are not same as on the Adaptive Cards Schema Explorer.

# Screenshot
![image](https://user-images.githubusercontent.com/22345679/128467037-72228fdc-0185-441f-bd2a-cc5ac2a95474.png)

# Version of SDK

NuGet 5.10.0

**Comment by RebeccaAnne** [comment]
This is by design. The host controls the colors used via a host configuration file and will not be consistent across different hosts.
