### ISSUE TITLE
[Authoring] Most of the container styles are not display in Microsoft Teams Windows Latest Version 1.4.00.19572 (64-bit)

### ISSUE THREAD

**Issue by derry668** [microsoft/AdaptiveCards#6178]
# Target Application

Microsoft Teams

# Problem Description

After updating the Teams version to Windows latest version of 1.4.00.19572, the container styles of good, warning, attention and accent are not displaying the corresponding color.

# Expected Outcome

Display the corresponding color as below:

![image](https://user-images.githubusercontent.com/3744444/128798278-a07a8511-429c-4754-a9b7-bebc2db22d72.png)

# Actual Outcome

The colors of good, warning, attention and accent are all displaying the default style:

![image](https://user-images.githubusercontent.com/3744444/128798425-d92a7d1f-dc7f-410b-813f-7acc0a581057.png)

# Repro Steps

Using the card payload in https://adaptivecards.io/designer/index.html?card=/payloads/Container.Style.json, and rendering it in Teams

# Schema Version

1.2

**Comment by RebeccaAnne** [comment]
This displays correctly in the designer, moving over to Teams to take a look.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/3968
