### ISSUE TITLE
Remove Action.Http from v1, to revisit later

### ISSUE THREAD

**Issue by matthidinger** [Microsoft/AdaptiveCards#618]
`Action.Http` is used to execute an HTTP action against an arbitrary 3rd party service. There are some inherent security issues with this, and thur far all consumers have decided to remove support for it. 

We will gather the feedback and revisit adding it back in a future release.

**Comment by dclaux** [comment]
If we remove Action.Http, then Action.Submit needs to be removed as well. Both are host specific at this point. What should remain in the schema are actions that are universally supported (e.g. Action.OpenUrl and Action.ShowCard.) All others should be done via extensibility.

**Comment by matthidinger** [comment]
Does Outlook use Action.Http or register custom actions? If they use Action.Http then that's my misunderstanding. I was under the impression every single host said they wouldn't support it
