### ISSUE TITLE
Move backgroundImage property into background object

### ISSUE THREAD

**Issue by matthidinger** [Microsoft/AdaptiveCards#619]
Currently background images are specified using a URL string as a top-level property on AdaptiveCard. This presents a problem if we add background color support, as well as makes it difficult to enhance the background image with render hints like what kind of overlay and adjusting the opacity.

## Current 

```json
{
    "type": "AdaptiveCard",
    "backgroundImage": "http://xyz.com"
}
```

## Proposal for v1
This optional more naturally enables background color, and also aligns closer to the concept of backgrounds for `Columns`/`Containers`.

```json
{
    "type": "AdaptiveCard",
    "background": {
        "image": {
            "url": ""
        }
    }
}
```

## Future possibilities (to paint the picture)

```json
{
    "type": "AdaptiveCard",
    "background": {
        "color": "",
        "image": {
            "url": "",
            "overlay": "light|dark",
            "opacity": 0.7
        }
    }
}
```

**Comment by dclaux** [comment]
Background colors should solely be controlled via the style property of a container, which ensures that text is rendered with appropriate contrast according to color definitions from HostConfig.
For background images, there should be a backgroundImage property defined as proposed (and approved for v1.1) in this issue: https://github.com/Microsoft/AdaptiveCards/issues/477

We can certainly introduce opacity in the future if necessary. As for the overlay, please check my proposal in this other issue as I believe it makes more sense: https://github.com/Microsoft/AdaptiveCards/issues/543#issuecomment-328621936

**Comment by matthidinger** [comment]
Closing this after discussion, we're going to keep it as-is for 1.0 and explore the v1.1 improvement per #477
