### ISSUE TITLE
[Authoring] Select action works inline in json but isn't documented and doesn't show up on the element properties pane

### ISSUE THREAD

**Issue by rahulamlekar** [microsoft/AdaptiveCards#6195]
# Problem Description

I can create an action on text by adding the "selectAction" property to the json of a RichTextBlock but this is not documented in the schema, neither is it shown as an option in the "element properties" section.

![image](https://user-images.githubusercontent.com/9759782/129116649-b37dff3e-7acb-4813-8527-19f30a85fc7d.png)

![image](https://user-images.githubusercontent.com/9759782/129116322-99449a6e-2a58-499d-b0dd-b9fb1f9b6683.png)

![image](https://user-images.githubusercontent.com/9759782/129116630-807c0565-44e7-4906-a017-8b4bbd509244.png)

# Expected Outcome

Schema and element properties pane should be consistent with the available functionality. Are there other controls such as TextBlock, Media etc. where this works as well? Are there places where we don't want this to work but it still does?

# Repro Steps

Use this in the designer
```json
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.4",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "RichTextBlock",
                    "inlines": [
                        {
                            "type": "TextRun",
                            "text": "Open URL link",
                            "selectAction": {
                                "type": "Action.OpenUrl",
                                "url": "https://myurl.com"
                            }
                        }
                    ]
                }
            ]
        }
    ]
}
```
# Schema Version

1.4

**Comment by RebeccaAnne** [comment]
Spun this bug off into the three above bugs to track the different aspects of this issue. Closing this bug.
