### ISSUE TITLE
[Rendering] Action contract for Action.Execute need to be documented

### ISSUE THREAD

**Issue by rahulamlekar** [microsoft/AdaptiveCards#6196]
As a new host / target application trying to render adaptive cards, I want to know how to access the data from action.execute and understand how I can process it. Is it the same format across all target platforms (UWP, JS, Android, etc.) and adaptive cards schema versions? What are the best practices to handle data from Action.Execute?

Here's a stackoverflow question on the same topic - https://stackoverflow.com/questions/53378090/adaptive-cards-submit-actions

# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:
- NodeJS
- iOS
- Android
- WPF
- UWP

# Target Application

New target application

**Comment by jonmill** [comment]
Tracked with #6316
