### ISSUE TITLE
[Rendering] Parity issue - Date format is not visible on date/time input when placeholder is missing

### ISSUE THREAD

**Issue by jyoti-ms** [microsoft/AdaptiveCards#6200]
# Target Platform

- iOS

# Target Application

Microsoft Teams

# Problem Description

Date format is not visible on date/time input when placeholder is not present. Same is visible on desktop/android

This issue is reproing on SDK sample app (Visualiser) also on latest main branch.

# Screenshot

iOS 

<img width="297" alt="Screenshot 2021-08-12 at 2 21 52 PM" src="https://user-images.githubusercontent.com/72016168/129168128-197374a9-53d4-40ed-a7ee-cd4362304002.png">

Desktop/Mobile (date format is visible)
<img width="297" alt="Screenshot 2021-07-14 at 11 51 20 AM" src="https://user-images.githubusercontent.com/72016168/129167855-94060b7f-c6a0-4aaf-9be9-87d783f392c6.jpeg">

# Card JSON
```json
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "text": "Date Input"
    },
    {
      "type": "Input.Date",
      "id": "date"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "OK"
    }
  ]
}

```
# Sample Code

# Version of SDK
v1.2

**Comment by RebeccaAnne** [comment]
In JavaScript we're getting this for free from the control/browser. For iOS we would need to implement this ourselves.

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
