### ISSUE TITLE
[Designer] No support for building RichTextBlocks

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6203]
# Problem Description

Split off from #6195 We do not currently support building RichTextBlocks in the designer. We only present a message saying "Use the **Card Payload Editor** to edit the text of this RichTextBlockElement". This bug tracks adding that support to the designer.

# Screenshot

![image](https://user-images.githubusercontent.com/9091833/129271064-cbb38951-0cc5-4644-af29-a1e8ae3028ae.png)

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
