### ISSUE TITLE
[MarkedNet] text "\#\#" can't be parsed as text

### ISSUE THREAD

**Issue by KayMKM** [microsoft/AdaptiveCards#6206]
# Target Platform

Please list the platform(s) that your application is targeting and remove platforms you are not targeting:
- NodeJS
- iOS
- Android
- WPF
- UWP

# Target Application

Please provide the name of the application that is rendering the card (ex: Outlook, Teams, etc)

# Problem Description

Please enter a description of the issue. If you just have a question, please post [on StackOverflow instead](https://stackoverflow.com/questions/tagged/adaptive-cards)

I am using MarkedNet to parse markdown message, and I overrided the renderer to convert markdown to another format.
In my renderer, I overrided the Text() function. When I try to parse a string of "\\#\\#", I expect the parser will call the Text() of renderer but it doesn't call the function.

# Screenshot

Please provide a screenshot of the problem (if possible)

# Card JSON

Please provide the JSON of the Card that is being rendered

# Sample Code

Please provide any relevant code samples to help reproduce the issue

```
public class MyRenderer : TextMarkdownRenderer
{
    public MyRenderer (Options options) : base(options)
    {
    }
    public override string Text(string text)
    {
        return doingSomething(text);
    }
}

var marked = new Marked();
marked.Options.Sanitize = false;
marked.Options.Mangle = false;
marked.Options.EscapeHtml = false;
marked.Options.Renderer = new MyRenderer(marked.Options);

marked.Parse("\\#\\#");
```

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest main, etc...

NuGet 2.7

**Comment by RebeccaAnne** [comment]
You should log this issue against the [markednet](https://github.com/alex-titarenko/markednet) repo.

If you're using Microsoft.MarkedNet you may want to switch over to the primary MarkedNet package.
