### ISSUE TITLE
[JS][Authoring] Custom fields based on `Image` not being serialised

### ISSUE THREAD

**Issue by scottlovegrove** [microsoft/AdaptiveCards#6217]
# Target Application

Twist.com (our own renderer)

# Problem Description

I have created a custom component that extends the `Image` class, the class itself is fairly simple, it's literally just:
```ts
export class Imageist extends Image {
    static readonly JsonTypeName = 'Image'
    static readonly aspectRatioProperty = new NumProperty(Versions.v1_0, 'aspectRatio')

    @property(Imageist.aspectRatioProperty)
    aspectRatio?: number

    getJsonTypeName(): string {
        return Imageist.JsonTypeName
    }
}
```

When I try and use this new field in my application, it doesn't get serialised. Calling `getSchema()` on it doesn't show the new field at all and I'm unsure why.

I have created a few custom components with additional fields in exactly the same way and all of them have worked without an issue. An example is one based on `TextInput`

```ts
export class TextInputist extends TextInput {
    static readonly JsonTypeName = 'Input.Text'
    static readonly rowsProperty = new NumProperty(Versions.v1_0, 'rows')
    static readonly inputStyleProperty = new StringProperty(Versions.v1_0, 'inputStyle')

    @property(TextInputist.rowsProperty)
    rows?: number

    @property(TextInputist.inputStyleProperty)
    inputStyle?: InputStyle

    getJsonTypeName(): string {
        return TextInputist.JsonTypeName
    }
}
```
The new fields here (`rows` and `inputStyle`) get serialised just fine without having to do anything except use them.  I've actually created custom versions of `AdaptiveCard`, `TextInput`, and `ChoiceSetInput` all with additional fields, and none of them have had an issue when it comes to being serialised.

I wonder whether it has anything to do with the fact none of the others I've done had a base class that overrode the `populateSchema` function? I actually did try this, and added my own override that explictly adds the `aspectRatioProperty` to the schema, but it still gets ignored.

# Expected Outcome

I was expecting the new fields to be serialised in the same way as other new components I've written.

# Actual Outcome

The new fields don't appear in the schema and so aren't serialised.

**Comment by scottlovegrove** [comment]
I forgot to mention, this is using 2.9.0 of the node package.

**Comment by scottlovegrove** [comment]
The plot thickens a little. It turns out that one of the properties that was working before is now no longer working in the TextInputist component (shown above). That property is the `rows` one. The `inputStyle` one still works just fine.

So what do these two failing properties have in common? They are both using the `NumProperty` to create the property static backing field. I have checked at runtime and the `isSerializationEnabled` property on the static property is set to true.

So because this property is now no longer working, I've gone back through our commits to where it did work, gone back to that specific commit, and it does again work. I've managed to trace it forward from there to a commit I made where the integration's version of adaptivecards package did change (context: we have all our integrations in a monorepo using npm workspaces), so effectively, this integration has gone from using 2.7.0 of the AC package, to 2.9.0 of the package. 

So were there any changes between these versions that could have had an adverse affect on the `NumProperty` class?

**Comment by RebeccaAnne** [comment]
@dclaux Do you have any insight into this one?

**Comment by dclaux** [comment]
@scottlovegrove I'm surprised any of your properties would serialize.

Try overriding `getSchemaKey` and have it return a value specific to your class. For instance, in `Imageist`:

```typescript
protected getSchemaKey(): string {
    return "Imageist";
}
```

Without the override, if for whatever reason your code ends up instantiating the out-of-box `Image` class, its constructor will build its schema and cache it under its "schema key". Subsequently, when your `Imageist` class is instantiated, given it inherits `Image`'s schema key, it will use `Image`'s already built schema, which does not include your custom properties. With the override, your class will have its own schema.

As I initially coded this, I wanted to dynamically create a unique schema key for each class extending `SerializableObject`, but eventually decided to leave it to every class to specify their own schema key. Why? I have no recollection. Room for improvement.

Please let me know if this solves your problem.

**Comment by scottlovegrove** [comment]
THanks @dclaux that fixed it 👍🏻 Is that something I missed somewhere in the docs? Looking at [this](https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/javascript/extensibility) I can't see any mention of that function. This is basically where I started with our new components.

**Comment by dclaux** [comment]
@scottlovegrove technically, you shouldn't have to override `getSchemaKey`, that's why I didn't document it explicitly. By default, `getSchemaKey` returns the same value as `getJsonTypeName`. But the assumption is that most of the time, any given JSON type name will be used by a single class. Your (perfectly valid) implementation of `Imageist` uses the same JSON type name as the built-in `Image`, and so it has the same schema key, which is why in that "special" case you need to override `getSchemaKey`.
