### ISSUE TITLE
Change image sizing model

### ISSUE THREAD

**Issue by dclaux** [Microsoft/AdaptiveCards#622]
# Implementation
- [x] JavaScript (https://github.com/Microsoft/AdaptiveCards/pull/475)
- [x] UWP (#1334)
- [x] WPF (#1337)
- [x] iOS (#1336)
- [x] Android (#1335)
- [x] Documentation

# Problem
For single Image elements, the small, medium and large image sizes are basically useless because they are no predictable. At the same time, a card author might actually want to precisely control an image's size, which they can accomplish by pointing to a specially-sized image and using the auto sizing mode. Often though, and to properly deal with high DPI screens, a card author might want to have a single, larger image on their server and render it at a reduced size in the card, which is currently not possible.

For ImageSet, small, medium and large actually make sense, as the goal isn't to display an image at a predicatble size but instead show a collection of images more or less preeminently. auto and stretch are not useful, as auto would make the collection look particularly bad as images would all potentially have a different size, and stretch would be the equivalent of displaying one image per row which can be accomplished with several individual Image elements.

# Solution
## For single Image elements
We should only support the following size modes:

Sizing mode | Property to set | Description
--------------|-------------|--------------
Automatic sizing | size = auto | The image is rendered at its native resolution.
Stretch to container width | size = stretch | The image is stretched horizontally so it uses the entire available width of its parent container.
Explicit size | pixelWidth = x and/or pixelHeight = y | The image is sized using to the spcified dimensions. If only one of the two is specified, the other is computed so as to respect the image's aspect ratio. pixelWidth/pixelHeight always "win", e.g. if size is also specified it is ignored. If both pixelWidth and pixelHeight are omitted, size is used instead. |

## For ImageSet elements
Only **small**, **medium** and **large** should be allowed via the imageSize property; stretch and auto should not be supported.

**Comment by matthidinger** [comment]
We also need to try and find some way to handle image heights based on related elements. E.g., set the height based on the lineHeight of TextBlock with a size of large, or medium, etc.

**Comment by paulcam206** [comment]
Documentation is done and in the mahiding/site1.1 branch.
