### ISSUE TITLE
[Feature Request] Allow custom URL for Action.OpenURL

### ISSUE THREAD

**Issue by alondattner** [microsoft/AdaptiveCards#6221]
# What is the problem you are attempting to solve with this feature?

I'm trying to build an adaptive card with a button (Action.OpenURL) to open a local software while passing some data. Using a browser one can open the software using this custom URL: _mytool://?data=123456_

I tried using this URL on an adaptive card (Action.OpenURL) but when you click the button, nothing happens.

I guess the URL somehow gets validated and if it's not a "valid" URL starting with https:// it gets replaced?

# A description of your proposed solution to the problem

Allow custom URLs for Action.OpenURL

# What alternatives or workarounds have you considered

I couldn't find any workaround since the URL always gets deleted and using HTML is not possible on adaptive cards.

**Comment by alondattner** [comment]
This may be a Teams related (rendering) problem. Also this may go together with #4947.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4001
