### ISSUE TITLE
Change the input.date format to mm/dd/yyyy

### ISSUE THREAD

**Issue by sreejithrkknd** [microsoft/AdaptiveCards#6237]
### Target Platforms

Other

### SDK Version

Bot Framework V4

### Application Name

Direct Line channel

### Problem Description

I am using bot framework v4 and adaptive card version 1.3. currently, the date picker is showing the format as dd/mm/yyyy but I want to change it to mm/dd/yyyy I tried so many ways but it is not working. Anyone can help me with this?

### Screenshots

![image](https://user-images.githubusercontent.com/87656788/130476721-79c58cd9-6305-4add-ab01-b478c0445c45.png)

### Card JSON

```JSON
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "text": "Please select a date"
    },
    {
      "type": "Input.Date",
      "id": "date",
      "placeholder": "Select a date",
      "value": "${dueDate}",
      "max": "${maxDate}"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Select"
    }
  ]
}
```

**Comment by RebeccaAnne** [comment]
We don't control the date format of the date picker, it is controlled by the control and the platform locale. It is by design that the date picker format will be consistent with the system.
