### ISSUE TITLE
Static Location support

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/AdaptiveCards#624]
# The problem

People share locations with each other all the time, be it an address of a family member, the location of a restaurant or the place where they took a picture. This issue proposes a StaticLocation type that would display the content of the card inside a pin on a map like the following example:

![map](https://user-images.githubusercontent.com/1564575/30406074-4e0b7894-98a4-11e7-8bff-387188d54cf1.jpg)

# The design

We would introduce a new type "StaticLocation" with a Coordinate and Content property. The Coordinate would determine where the pin would be shown and the Content property would become the content of the pin. Existing properties like spacing could apply to how much space would be shown around the pin etc. as follows:

``` json
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"body": {
                "type": "StaticLocation",
                "spacing": "extraLarge",
                "coordinate": {
                        "lat": 47.6430113,
                        "lon": -122.1381009,
                 },
		 "content": [
                        {
                               "type": "TextBlock",
        		        "text": "Microsoft Studio C"
                        }
                 ]
        }
}
```

**Comment by GokulManickam** [comment]
Hi

**Comment by GokulManickam** [comment]
I have a issue regarding the static location type...In adaptive cards it shows an error like "Unknown Element Type: StaticLocation".....

Can u specify this type and version for it.

**Comment by dclaux** [comment]
@GokulManickam StaticLocation isn't supported in Adaptive Cards. This issue is only a proposal for a future feature at this point.

**Comment by dclaux** [comment]
@GokulManickam StaticLocation isn't supported in Adaptive Cards. This issue is only a proposal for a future feature at this point.

**Comment by noocyte** [comment]
Suggestion: The Coordinate property should use Geojson and their feature/geometry. And perhaps support multiple features. Example: https://gist.github.com/wavded/1200773?short_path=99c1af9

**Comment by RebeccaAnne** [comment]
Related issue: https://github.com/microsoft/AdaptiveCards/issues/457

**Comment by RebeccaAnne** [comment]
This is a good suggestion, but not something that's on our roadmap at this time. We may reconsider it in the future, or if you would like to make a contribution please see our contribution guidelines [here](https://github.com/microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md).
