### ISSUE TITLE
[Rendering] InlineAction darkmode is unreadable in designer HTML 

### ISSUE THREAD

**Issue by tomlm** [microsoft/AdaptiveCards#6249]
### Target Platforms

NodeJS

### SDK Version

latest

### Application Name

Adaptive CArd Designer

### Problem Description

See screenshots

### Screenshots

Light mode
![image](https://user-images.githubusercontent.com/17789481/130873090-fd7e991a-50f7-48ee-954c-6c0ca749419f.png)

Dark mode
![image](https://user-images.githubusercontent.com/17789481/130873057-af2184c8-68e5-479b-a68d-8939e7ae4f90.png)

### Card JSON

```JSON
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
        {
            "type": "Input.Text",
            "id": "textInlineActionId",
            "inlineAction": {
                "type": "Action.OpenUrl",
                "title": "Reply",
                "url": "https://adaptivecards.io"
            }
        }
    ]
}
```

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
