### ISSUE TITLE
[Accessibility] Activity Update: Keyboard and talkback focus does not appear in synchronized navigation with Tab key under DatePicker on Activity Update pane.

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6261]
### Target Platforms

Javascript

### SDK Version

Unknown

### Application Name

Visualizer

### Problem Description
[33897610](https://microsoft.visualstudio.com/OS/_workitems/edit/33897610)

Keyboard and talkback focus does not appear in synchronized navigation with Tab key under DatePicker on Activity Update pane.

### Card JSON

[ActivityUpdate.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Scenarios/ActivityUpdate.json)

**Comment by jonmill** [comment]
Closing as bug is on an external team, not AC
