### ISSUE TITLE
[Accessibility] Voiceover is not providing role information with column which has select action on “Column.SelectAction” page.

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6269]
### Target Platforms

iOS

### SDK Version

App Version: 1.0 (1.3.0.20200820.7)

### Application Name

Visualizer

### Problem Description

[29141394](https://microsoft.visualstudio.com/OS/_workitems/edit/29141394)

Voiceover is not providing role information with column which has select action on “Column.SelectAction” page.

### Card JSON

[Column.SelectAction.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Elements/Column.SelectAction.json)

**Comment by jwoo-msft** [comment]
duplicate [37824988](https://microsoft.visualstudio.com/OS/_workitems/edit/37824988)

**Comment by vagpt** [comment]
Closing this issue due to duplicate of #7016
