### ISSUE TITLE
[Accessibility] Voiceover is reading the role of “Telephone Number” link two times on “TestBlock.Markdown.Telephony” page.

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6279]
### Target Platforms

iOS

### SDK Version

App Version: 1.0 (1.3.0.20200820.7)

### Application Name

Visualizer

### Problem Description

[29469129](https://microsoft.visualstudio.com/OS/_workitems/edit/29469129)

Voiceover is reading the role of “Telephone Number” link two times on “TestBlock.Markdown.Telephony” page. It is reading as " Link-Link".

### Card JSON

```JSON
TestBlock.Markdown.Telephony
```

**Comment by vagpt** [comment]
Not repro on the latest build hence closing this issue.
