### ISSUE TITLE
[Accessibility] Luminosity ratio is less than 3:1 for green icons present on the “Agenda” page.

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6282]
### Target Platforms

iOS

### SDK Version

App Version: 1.0 (1.3.0.20200820.7)

### Application Name

Visualizer

### Problem Description

[29575823](https://microsoft.visualstudio.com/OS/_workitems/edit/29575823)

Luminosity ratio is less than 3:1 for green icons present on the “Agenda” page.

### Card JSON

[Agenda.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.2/Scenarios/Agenda.json)

**Comment by jwoo-msft** [comment]
not reproducible in the newer build

**Comment by MohitTyagi13** [comment]
Same issue is still repro in latest build.

Test Environment:
Device: iPhone X
iOS Version: 15.5
Application: Adaptive Cards
Application Version: 1.0 (2.4.0-beta.20220620.1)
![image](https://user-images.githubusercontent.com/95915837/174782838-d8c18097-6df1-4284-a06e-be262b5f4cb8.png)

**Comment by paulcam206** [comment]
@jwoo-msft - care to take a look?

**Comment by vagpt** [comment]
This issue is not repro on Release 179, hence closing this issue.
