### ISSUE TITLE
[Accessibility] Voiceover focus is moving to all the links in one go present on “RitchTextBlock.TextRun.SelectAction” page.

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6283]
### Target Platforms

iOS

### SDK Version

App Version: 1.0 (1.3.0.20200820.7)

### Application Name

Visualizer

### Problem Description

[29576696](https://microsoft.visualstudio.com/OS/_workitems/edit/29576696)

Voiceover focus is moving to all the links in one go present on “RitchTextBlock.TextRun.SelectAction” page.

### Card JSON

[RichTextBlock.TextRun.SelectActions.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.2/Tests/RichTextBlock.TextRun.SelectActions.json)

**Comment by vagpt** [comment]
Card is not available on latest build.
