### ISSUE TITLE
[Accessibility] CalendarReminder: Focus order is not logical as focus is going on 'Snooze' button instead of 'Dropdown' menu items by using swipe.

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6285]
### Target Platforms

iOS

### SDK Version

App Version: Version 1.0 (2.3.1-beta.20210603.1)

### Application Name

Visualizer

### Problem Description

[33752716](https://microsoft.visualstudio.com/OS/_workitems/edit/33752716)

Focus order is not logical in swipe navigation on "CalendarReminder.JSON” page. As after performing right swipe from the 'Snooze for' label it is going on the 'Snooze' button.

### Card JSON

[CalendarReminder.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Scenarios/CalendarReminder.json)

**Comment by jwoo-msft** [comment]
verified that it's fixed.

**Comment by vagpt** [comment]
Closing this issue as not repro on the latest build.
