### ISSUE TITLE
[Accessibility] Voice over does not convey the name of the 'DatePicker' button under 'ActivityUpdate.JSON' screen.

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6287]
### Target Platforms

iOS

### SDK Version

App Version: Version 1.0 (2.3.1-beta.20210603.1)

### Application Name

Visualizer

### Problem Description

[33753620](https://microsoft.visualstudio.com/OS/_workitems/edit/33753620)

Voice Over does not convey the name of the 'Date Picker' button, Currently VO does announce as 'Button' only.

### Card JSON

[ActivityUpdate.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Scenarios/ActivityUpdate.json)

**Comment by vagpt** [comment]
Working fine on the latest build.
