### ISSUE TITLE
[Accessibility] Inputs: Input screen is not getting scrolled when voice over is activated.

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6292]
### Target Platforms

iOS

### SDK Version

App Version: Version 1.0 (2.3.1-beta.20210603.1)

### Application Name

Visualizer

### Problem Description

[33764750](https://microsoft.visualstudio.com/OS/_workitems/edit/33764750)

After the due date option, Input screen is not getting scrolled when voice over is activated and on tapping any option no action is getting performed.

### Card JSON

[Inputs.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Scenarios/Inputs.json)

**Comment by jwoo-msft** [comment]
This event has to be handled by the hosting app. Hosting app in this case is a sample app. Since bug is filed on the sample that is not public, the issue is closed.

**Comment by vagpt** [comment]
AS per the above comment closing this issue.
