### ISSUE TITLE
[Accessibility] Agenda: Voice over does not convey the name of the image under Agenda screen.

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6294]
### Target Platforms

iOS

### SDK Version

App Version: Version 1.0 (2.3.1-beta.20210603.1)

### Application Name

Visualizer

### Problem Description

[33767249](https://microsoft.visualstudio.com/OS/_workitems/edit/33767249)

Voice over does not convey the name of the image. It is announcing only as 'Image'. Voice over should convey the name of the image or make it non interactive so that focus should not land on it.

### Card JSON

[Agenda.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.2/Scenarios/Agenda.json)

**Comment by jwoo-msft** [comment]
doesn't repro anymore

**Comment by MohitTyagi13** [comment]
issue is still repro'ing in latest build. activating this issue

**Test Environment:**
Device: iPhone X
iOS:15.5
App Version: Version 1.0 (2.4.0-beta.20220620.1)
Screen Reader: Voice Over

https://user-images.githubusercontent.com/95915837/174777494-74979329-abe3-45dd-99de-2e7ba3c8f10d.mov

**Comment by paulcam206** [comment]
@jwoo-msft - care to take a look?

might be this one lonely altTextless image: 

https://github.com/microsoft/AdaptiveCards/blob/648d7392bcf54c8d82d5d6cf6b3c8d87042529ad/samples/v1.2/Scenarios/Agenda.json#L306-L311

**Comment by vagpt** [comment]
Working fine on the latest build hence closing this issue.
