### ISSUE TITLE
[Accessibility] Expenses: Voice Over does not convey the role for the 'Show History' button.

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6295]
### Target Platforms

iOS

### SDK Version

App Version: Version 1.0 (2.3.1-beta.20210603.1)

### Application Name

Visualizer

### Problem Description

[33768386](https://microsoft.visualstudio.com/OS/_workitems/edit/33768386)

Voice over does not convey the role for the 'Show History' button. It is announcing as 'Show History' only.

### Card JSON

[ExpenseReport.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.2/Scenarios/ExpenseReport.json)

**Comment by vagpt** [comment]
Closing this issue as this issue is not repro on the below build 1.0(2.4.0-beta.20220718.1).
