### ISSUE TITLE
[Accessibility] Input with Validation: Elements under 'Inputwithvalidation' screen does not adopt the larger text settings.

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6296]
### Target Platforms

iOS

### SDK Version

App Version: Version 1.0 (2.3.1-beta.20210603.1)

### Application Name

Visualizer

### Problem Description

[33768879](https://microsoft.visualstudio.com/OS/_workitems/edit/33768879)

Elements under 'Input with validation' screen does not adopt the larger text.

### Card JSON

[InputsWithValidation.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.3/Scenarios/InputsWithValidation.json)

**Comment by jwoo-msft** [comment]
It's fixed already in the current build.

**Comment by vagpt** [comment]
Not repro on the updated build.
