### ISSUE TITLE
[Accessibility] Activity Update: Voice Over does convey the incorrect information for the text fields.

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6297]
https://microsoft.visualstudio.com/OS/_workitems/edit/33771772

**Comment by jwoo-msft** [comment]
verified that it's fixed in the current build.
FYI, card used is  v1.3/Scenario/ActivityUpdateWithLabel.json

**Comment by vagpt** [comment]
Not repro on the updated build.
