### ISSUE TITLE
Cards with multiple action show card does not render on iOS

### ISSUE THREAD

**Issue by astuj** [microsoft/AdaptiveCards#6308]
### Target Platforms

iOS

### SDK Version

1.2

### Application Name

Microsoft Teams

### Problem Description

I created a card for Microsoft teams which consists of 2 action.showcard actions, the card is rendering fine on windows but on iOS it shows up nothing. 

Any leads would be a great help, thanks.

### Screenshots

<img width="955" alt="Screenshot 2021-09-02 at 11 52 30 AM" src="https://user-images.githubusercontent.com/20801184/131792772-591287d1-dd75-43d8-9cf7-d9cd204a7321.png">

![7CF8FAB3-9AAC-4B6A-ADCB-809F5EA25C45_1_201_a](https://user-images.githubusercontent.com/20801184/131792850-39bd5e40-4b50-44f9-b52b-051ddcfc2c62.jpeg)

### Card JSON

```JSON
{
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.3",
  "actions": [
    {
      "type": "Action.ShowCard",
      "title": "Action.ShowCard",
      "card": {
        "type": "AdaptiveCard",
        "body": [
          {
            "type": "Input.Text",
            "placeholder": "Placeholder text"
          },
          {
            "type": "Input.Text",
            "placeholder": "Placeholder text"
          }
        ]
      }
    },
    {
      "type": "Action.ShowCard",
      "title": "Action.ShowCard",
      "card": {
        "type": "AdaptiveCard",
        "body": [
          {
            "type": "Input.Time"
          },
          {
            "type": "Input.Date"
          }
        ]
      }
    }
  ],
  "body": [
    {
      "type": "TextBlock",
      "text": "New TextBlock",
      "wrap": true
    }
  ]
}
```

**Comment by RebeccaAnne** [comment]
@jwoo-msft Could you verify real quick if this repros in the visualizer? Thanks!

**Comment by astuj** [comment]
@RebeccaAnne @jwoo-msft any updates on the issue??

**Comment by jwoo-msft** [comment]
@astuj 
Your cards are missing the required properties. For Inputs, IDs are required. For the exhaustive list of required properties, you can refer to them [here](https://adaptivecards.io/explorer/Input.Text.html).
We have a plan to update ios/android SDKs to render cards even if the required properties are missing, meanwhile, please do add the required properties to your card.
