### ISSUE TITLE
[Designer] Needs to be usable at higher zoom levels

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#6313]
### Problem Description

Original bug: #6263

WCAG 2.1 requirements [state](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html) that content needs to be able to be read/interacted with using only vertical scrolling at 1280x768 400% zoom. 

The original bug tracks getting the designer to the point where everything is at least accessible, if not convenient. This bug tracks giving the designer a more thoughtful redesign to be useful and usable at high zoom levels.

### Card JSON

```JSON
{}
```

### Screenshot

width 1280 @ 400% zoom:
![image](https://user-images.githubusercontent.com/16614499/132572823-592880ff-6afb-46de-b5db-eedbead335c7.png)

**Comment by JeanRoca** [comment]
PR addressing issue has been merged
