### ISSUE TITLE
Image element JS schema interface does not allow pixel height

### ISSUE THREAD

**Issue by ms-nichoi** [microsoft/AdaptiveCards#6333]
### Target Platforms

NodeJS

### SDK Version

2.9.0

### Application Name

SharePoint

### Problem Description

We found an issue with the Image element JS schema interface:

```
export interface IImage extends ICardElement {

    type: "Image";

    altText?: string;

    selectAction?: IAction;

    size?: Size;

    style?: ImageStyle;

    url: string;

}
```

IImage extends ICardElement, which only allows a height property of "auto" or "stretch," even though the schema.json allows any string to accommodate pixel heights (e.g., height: "100px" ).

A solution would be to not extend ICardElement (just as in the schema.json), or do something like this:

```
export interface IImage extends Omit<ICardElement, 'height'> {

    type: "Image";

    altText?: string;

    selectAction?: IAction;

    size?: Size;
    height?: 'auto' | 'stretch' | string;

    style?: ImageStyle;

    url: string;

}
```

https://github.com/microsoft/AdaptiveCards/blob/4aa4651ebb45ac8768877491631904625086cd4c/source/nodejs/adaptivecards/src/schema.ts#L92

### Card JSON

```JSON
n/a
```

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
