### ISSUE TITLE
[Rendering] Input.Text missing spell-check options

### ISSUE THREAD

**Issue by kitzeller** [microsoft/AdaptiveCards#6364]
### Target Platforms

NodeJS

### SDK Version

1.2

### Application Name

Microsoft Teams

### Problem Description

I'm unsure if this is an adaptive card issue or a Teams issue, but when using an Input.Text element, misspelled text is underlined, though on right-clicking, no spell-check options appear.

### Screenshots

![image](https://user-images.githubusercontent.com/13111149/133686380-8ca7d581-0270-4f18-b967-1eed582e96b0.png)

### Card JSON

```JSON
{
    "type": "Input.Text",
    "style": "text",
    "isMultiline": true,
    "id": "commentVal",
    "value": "{comment}"
}
```

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4189
