### ISSUE TITLE
[JS] IAction schema interface is missing style property

### ISSUE THREAD

**Issue by ms-nichoi** [microsoft/AdaptiveCards#6369]
### Target Platforms

NodeJS

### SDK Version

2.9.0

### Application Name

SharePoint

### Problem Description

https://github.com/microsoft/AdaptiveCards/blob/4aa4651ebb45ac8768877491631904625086cd4c/source/nodejs/adaptivecards/src/schema.ts#L13

`IAction` is missing `style`

```
export interface IAction {
    id: string;
    title?: string;
}
```

### Card JSON

```JSON
n/a
```

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
