### ISSUE TITLE
[JS] IAdaptiveCard interface has an incomplete list of allowed types for body

### ISSUE THREAD

**Issue by ms-nichoi** [microsoft/AdaptiveCards#6371]
### Target Platforms

NodeJS

### SDK Version

2.9.0

### Application Name

SharePoint

### Problem Description

https://github.com/microsoft/AdaptiveCards/blob/main/source/nodejs/adaptivecards/src/schema.ts#L169

`IAdaptiveCard.body` has type `(ITextBlock | IImage | IImageSet | IFactSet | IColumnSet | IContainer)[]`

This is missing a IRichTextBlock element, which doesn't exist yet (issue [here](https://github.com/microsoft/AdaptiveCards/issues/6370)), and all the `IInput` elements. 

### Card JSON

```JSON
n/a
```

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
