### ISSUE TITLE
[Designer] Outdated warning for Teams on AC Designer

### ISSUE THREAD

**Issue by rahulamlekar** [microsoft/AdaptiveCards#6383]
### Problem Description

Teams supports v1.4 for "Bot sent Cards". We should update our warning to reflect this and also update it in our docs.

New message - Teams only supports v1.4 for Bot Sent Cards. For User Sent Cards, please use v1.3.

### Card JSON

```JSON
NA
```

**Comment by RebeccaAnne** [comment]
Dup of #6314
