### ISSUE TITLE
[Rendering] Android Outlook seems to not process 1.0 card (Action.Http)

### ISSUE THREAD

**Issue by Greg-Hitchon** [microsoft/AdaptiveCards#6396]
### Target Platforms

Android

### SDK Version

1.0

### Application Name

Outlook

### Problem Description

Hello,

I have some cards with Action.Http used for `autoInvokeAction` and some `actions`. These work in Outlook Desktop and Outlook Web, but recently it seems like they no longer working in Android Outlook. 

For a concrete example:

```
"autoInvokeAction": {
        "method": "POST",
        "url": "https://myendpoint",
        "headers": [
            {
                "name": "Content-Type",
                "value": "application/json"
            }
        ],
        "body": "{my data}",
        "type": "Action.Http"
    }
```

1. This works in Outlook Desktop (hits endpoint, refreshes card)
2. This works in Outlook Web (hits endpoint, refreshes card)
3. This does not work in Outlook Android (does not hit endpoint, does not refresh card) Android App version is 4.2135.3 (42135810)

Is this still supported/any idea as to why it would not be working on Android?

### Card JSON

```JSON
"autoInvokeAction": {
        "method": "POST",
        "url": "https://myendpoint",
        "headers": [
            {
                "name": "Content-Type",
                "value": "application/json"
            }
        ],
        "body": "{my data}",
        "type": "Action.Http"
    }
```

**Comment by RebeccaAnne** [comment]
This is an issue in Outlook. Please raise this with them at https://docs.microsoft.com/en-us/answers/topics/office-addins-dev.html
