### ISSUE TITLE
Finalize behavior for empty textblocks

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#641]
Different things happen in each renderer with an empty string (""), a space (" "), and a non-breaking space ("&nsbp;") 

```json
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": ""
        },
        {
            "type": "TextBlock",
            "text": "New TextBlock"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```

**UWP**: Adds the blank TextBlock

![image](https://user-images.githubusercontent.com/13246069/60831314-23c37f80-a16e-11e9-8d1a-c71423bd2d39.png)

**JS**: Drops the blank TextBlock

![image](https://user-images.githubusercontent.com/13246069/60831365-3ccc3080-a16e-11e9-8b98-ca5a9e3bff02.png)

**Comment by shalinijoshi19** [comment]
Dup of #3702
