### ISSUE TITLE
[Rendering] Teams adaptative cards 1.4 can't display

### ISSUE THREAD

**Issue by CDSFounder** [microsoft/AdaptiveCards#6413]
### Target Platforms

Other

### SDK Version

Latest

### Application Name

Microsoft Teams

### Problem Description

Microsoft updated documentation to state that Adaptive Card version 1.4 is now supported by Teams when sent via a bot.

When I attempt to send a sample JSON adaptive card via Power Automate to "Send an adaptative card via flow bot" the end user gets a message from flow bot, but the card simple says "We're sorry, this card couldn't be displayed".

Are adaptive cards 1.4 not supported by Flow Bot? 
Would be nice to be able to update a card after submission, which is why I am looking at version 1.4 

Any help understanding what is going on is greatly appreciated. :)

### Card JSON

```JSON
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.4",
  "body": [
    {
      "type": "TextBlock",
      "text": "Select from food options"
    },
    { 
      "type": "ActionSet",
      "actions": [
        {
          "type": "Action.Execute",
          "title": "Chicken",
          "verb": "food",
          "data": {
              "item": "chicken"
          }
        },
        {
          "type": "Action.Execute",
          "title": "Beef",
          "verb": "food",
          "data": {
              "item": "beef"
          }
        },
        {
          "type": "Action.Execute",
          "title": "Vegan",
          "verb": "food",
          "data": {
              "item": "vegan"
          }
        }
      ]
    }
  ]
}
```

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4250
