### ISSUE TITLE
[Website] Activity Update: Ensures elements with an ARIA role that require parent roles are contained by them (aria-required-parent - 

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6426]
### Target Platforms

NodeJS

### SDK Version

https://adaptivecards.io/  9/9/2021

### Application Name

Website

### Problem Description

[ADO 35919222](https://microsoft.visualstudio.com/OS/_workitems/edit/35919222)

**Repro Steps:**
1. Open above URL with valid credential.
2. Navigate to 'Samples' link and press tab key to activate it.
3. Select the 'Activity Update' option and navigate to 'Date Picker' under 'Publish Adaptive Card Schema'.
4. Run Accessibility insight for Web and observe the issue.

**Actual Result:**
Ensures elements with an ARIA role that require parent roles are contained by them.

**Expected Result:**
Ensures elements with an ARIA role that require parent roles are contained by them.

### Card JSON

```JSON
ActivityUpdate.json
```

**Comment by paulcam206** [comment]
This has been fixed.
