### ISSUE TITLE
[Website] Left Navigation Bar-Activity Update: Aria attributes are not allowed for an element's role.

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6428]
### Target Platforms

NodeJS

### SDK Version

https://adaptivecards.io/samples/ImageGallery.html 9/14/2021

### Application Name

Website

### Problem Description

[ADO 36107187](https://microsoft.visualstudio.com/OS/_workitems/edit/36107187)

**Repro Steps:**
1. Launch the above URL.
2. Run Accessibility Insight Tool of Web.
3. Observe the issue.

**Actual Result:**
Aria attributes are not allowed for an element's role.

**Expected Result:**
Ensure Aria attributes are allowed for an element's role.

### Card JSON

```JSON
No card
```

**Comment by paulcam206** [comment]
This has been fixed.
