### ISSUE TITLE
[Website] Connect with us: Ensures links have discernible text.

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6432]
### Target Platforms

NodeJS

### SDK Version

https://adaptivecards.io/connect/ 9/14/2021

### Application Name

Website

### Problem Description

[ADO 36108394](https://microsoft.visualstudio.com/OS/_workitems/edit/36108394)

**Repro Steps:**
1. Launch the above URL.
2. Run AI4W tool.
3. Observe the issue.

**Actual Result:**
Links do not have discernible text.

**Expected Result:**
Links must have accessible names.

### Card JSON

```JSON
No Card
```

**Comment by PankajBhojwani** [comment]
Closing this as the `adaptivecards.io/connect` page has now been removed
