### ISSUE TITLE
[Authoring] Input.Date Card does not work for Global Applications

### ISSUE THREAD

**Issue by blummichellec** [microsoft/AdaptiveCards#6441]
### Target Application

Microsoft Teams

### Application Operating System

Windows

### Schema Version

1.3

### Problem Description

We have a Teams application using the Input.Date Adaptive card. This application is used by Global Users all in different Local Timezones... When the raw input from the card is sent to our application, it sets the date by sending Local TZ -> GMT 00:00:00. For example,

Ireland Standard Time (GMT+1):
Inputs 09/30/2021 @ 5pm
Output 09/29/2021 @ 5pm

Pacific Standard Time (GMT-7):
Inputs 09/30/2021 @ 5pm
Output 09/30/2021 @ 5pm

### Expected Outcome

The backend should be using the date/time to determine the output GMT date.

### Actual Outcome

Since the adaptive card backend seems to be only using input the date to determine the output GMT date, this causes issues for a Global use case..

### Card JSON

```JSON
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "text": "Date Input"
    },
    {
      "type": "Input.Date",
      "id": "date",
      "placeholder": "Enter a date",
      "value": "2017-10-12"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "OK"
    }
  ]
}
```

### Repro Steps

1. Create an adaptive card receiving date/time input field
2. Have a user in IST test this versus a user in PST or EST
3. Observe that for users in TZ where it is GMT+# the previous date will be returned, but for users in TZ where it is GMT-# the correct date will be returned.

**Comment by WhiteCyClop** [comment]
Hello! I have the same problem with my teams bot and adaptive cards. This bug appeared recently, we only encountered it a couple of days ago. Before that there were no such problems, no changes were made to the bot for a long time

**Comment by stojanovic** [comment]
We have the same issue in production, and it's a bit frustrating because it affects many of our customers (not all of them, even on the same version of the Microsoft Teams application). The problem has been happening since Friday, September 24th.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4251
