### ISSUE TITLE
[Rendering] Compact Input.ChoiceSet is not correctly rendered in High Contrast

### ISSUE THREAD

**Issue by ManuNswamy** [microsoft/AdaptiveCards#6447]
### Target Platforms

Other

### SDK Version

1.2

### Application Name

Microsoft Teams

### Problem Description

The issue below is witnessed in the High Contrast Theme of Microsoft Teams Desktop Client.

The options available in the drop down menu (Input.ChoiceSet - "style": "compact") is not properly rendered/displayed. The Option 1 is displayed totally dark and the remaining options also turns dark when we select them. When these options turns dark, it is impossible to distinguish the option and the background.

Also, when I change the style of Input.ChoiceSet to "expanded", then the card is properly rendered and working as expected.

### Card JSON

```JSON
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "text": "Select Options from Dropdown",
      "color": "accent",
      "size": "medium",
      "weight": "bolder"
    },
    {
      "type": "Input.ChoiceSet",
      "id": "teams",
      "placeholder": "Select multiple options",
      "isMultiSelect": true,
      "value": "${options}",
      "choices": [
        {
          "$data": "${CustomOptions}",
          "title": "${OptionName}",
          "value": "${OptionValue}"
        }
      ]
    },
    {
      "type": "ActionSet",
      "actions": [
        {
          "type": "Action.Submit",
          "title": "Proceed"
        },
        {
          "type": "Action.Submit",
          "title": "Cancel",
          "data": {
            "msteams": {
              "type": "messageBack",
              "displayText": "cancel",
              "text": "cancel"
            }
          }
        }
      ]
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.2"
}
```

**Comment by ManuNswamy** [comment]
![Sample Screenshot](https://user-images.githubusercontent.com/29920276/135245516-a8e8c60e-f260-45dd-8dc1-d0d7c69405a0.PNG)

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4252
