### ISSUE TITLE
[JavaScript] A button with a title but no tooltip is duplicating the title in the tooltip

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6449]
### Target Platforms

NodeJS

### SDK Version

https://adaptivecardsci.z5.web.core.windows.net/designer 9/29/2021

### Application Name

Designer

### Problem Description

When an action has a title which is displayed on the button itself we should not repeat that title in the tooltip

### Screenshots

![image](https://user-images.githubusercontent.com/9091833/135312016-a2bd106a-e840-48e5-887d-7281b151f80a.png)

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5",
    "body": [
        {
            "type": "TextBlock",
            "text": "Button with a title",
            "weight": "Bolder",
            "wrap": true
        },
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.Submit",
                    "title": "Title",
                    "iconUrl": "https://adaptivecards.io/content/cats/1.png"
                }
            ]
        }
    ]
}
```

**Comment by licanhua** [comment]
I prefer to make it as `won't fix`. Please re-triage it.

The perfect solution is to show tooltip only when parts of content is not visible. but it's hard to do it with css and JS.
ToolTip is still required when content is overflow, in scrollview and truncated in parent. So removing the tooltip for the button is not a very good solution.

![image](https://user-images.githubusercontent.com/6290692/139779269-0e731002-7c86-4895-87f2-f3f18f99b53a.png)

![image](https://user-images.githubusercontent.com/6290692/139779526-3c16ff91-161d-4785-b7b0-53d7aeb86992.png)

**Comment by licanhua** [comment]
we need to provide tooltips for overflow and accessibility and that this behavior is expected and managed by the browser, not AC
