### ISSUE TITLE
[Designer] [Adaptive Card 'Only Show When' ]

### ISSUE THREAD

**Issue by Andrew-Murdock** [microsoft/AdaptiveCards#6454]
I am trying to use "Only Show When" in an Adaptive Card posted to Teams.
"${@{outputs('Post_adaptive_card_and_wait_for_a_response')?['body/data/choiceFRATRating']} = 1}"
The "choiceFRATRating" is either 1,2, or 3.
The card shows the Textblock regardless of value.
Thoughts?

**Comment by RebeccaAnne** [comment]
Please reopen using our Designer issue template. Thanks!

**Comment by Andrew-Murdock** [comment]
Can you please be more specific?

**Comment by RebeccaAnne** [comment]
When you open a new issue in our repo, you should see a list of options that looks like the below. Please select the Designer bug template and fille in the required information. That helps us understand and triage the issue. Thanks!

![image](https://user-images.githubusercontent.com/9091833/135884339-737043ea-1cbf-4901-b1e3-ec7b206e3d5a.png)
