### ISSUE TITLE
[Rendering][Teams][iOS] The markdown is not handled in the adaptive card when the card includes mention

### ISSUE THREAD

**Issue by mpelekh** [microsoft/AdaptiveCards#6458]
### Target Platforms

iOS

### SDK Version

1.0

### Application Name

Microsoft Teams

### Problem Description

The markdown is not handled in the adaptive card when the card includes mention.

But when the mention part is not in card JSON, markdown is processed appropriately.

### Screenshots

Adaptive card with mention within:
![Screenshot 2021-09-30 at 17 01 36](https://user-images.githubusercontent.com/9514958/135471657-2df16167-8920-410c-81a6-dfc56c84761c.png)

Adaptive card without mention within:
![Screenshot 2021-09-30 at 17 02 08](https://user-images.githubusercontent.com/9514958/135471666-29fc8871-ee80-4577-947d-7edd5d6b5490.png)

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "Hello <at>Username</at>",
                    "wrap": true
                },
                {
                    "type": "TextBlock",
                    "text": "This is some text that includes markdown. **This part should be bold.** [This is a link](https://www.example.com)",
                    "wrap": true
                }
            ]
        }
    ],
    "msteams": {
        "entities": [
            {
                "type": "mention",
                "text": "<at>Username</at>",
                "mentioned": {
                    "id": "<userId>",
                    "name": "Username"
                }
            }
        ]
    },
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4253
