### ISSUE TITLE
[Designer] Adaptive Card 'Only Show When'

### ISSUE THREAD

**Issue by Andrew-Murdock** [microsoft/AdaptiveCards#6464]
### Problem Description

I am trying to use "Only Show When" in an Adaptive Card posted to Teams.
`${@{outputs('Post_adaptive_card_and_wait_for_a_response')?['body/data/choiceFRATRating']} = 1}`
The "choiceFRATRating" is either 1,2, or 3.
The card shows the Textblock regardless of value.
Thoughts?

### Card JSON

```JSON
"type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "text": "@{outputs('Post_adaptive_card_and_wait_for_a_response')?['body/data/dateFRAT']}",
            "wrap": true,
            "spacing": "Large",
            "height": "stretch",
            "size": "Large",
            "weight": "Bolder",
            "color": "Accent",
            "horizontalAlignment": "Center"
        },
        {
            "type": "TextBlock",
            "text": "Pre EMT FRAT has defined the day as:",
            "wrap": true,
            "horizontalAlignment": "Center",
            "separator": true
        },
        {
            "type": "TextBlock",
            "text": "Green",
            "wrap": true,
            "separator": true,
            "$when": "${@{outputs('Post_adaptive_card_and_wait_for_a_response')?['body/data/choiceFRATRating']} = 1}",
            "height": "stretch",
            "horizontalAlignment": "Center",
            "size": "Medium",
            "weight": "Bolder",
            "color": "Good"
        },
        {
            "type": "TextBlock",
            "text": "Yellow",
            "wrap": true,
            "separator": true,
            "$when": "${@{outputs('Post_adaptive_card_and_wait_for_a_response')?['body/data/choiceFRATRating']} = 2}",
            "height": "stretch",
            "horizontalAlignment": "Center",
            "size": "Medium",
            "weight": "Bolder",
            "color": "Warning",
            "isSubtle": true
        },
        {
            "type": "TextBlock",
            "text": "Green",
            "wrap": true,
            "separator": true,
            "$when": "${@{outputs('Post_adaptive_card_and_wait_for_a_response')?['body/data/choiceFRATRating']} = 3}",
            "height": "stretch",
            "horizontalAlignment": "Center",
            "size": "Medium",
            "weight": "Bolder",
            "color": "Attention"
        }
    ]
}
```

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4280

**Comment by RebeccaAnne** [comment]
@Andrew-Murdock Could you please share with us a sample data payload? Thanks! Also, just to confirm, are you viewing the card in preview mode? You can use preview mode by clicking here:
![image](https://user-images.githubusercontent.com/9091833/135919083-d1128b6f-e9b4-4f87-b042-90f4eacd2d68.png)

**Comment by Andrew-Murdock** [comment]
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "text": "@{outputs('Post_adaptive_card_and_wait_for_a_response')?['body/data/dateFRAT']}",
            "wrap": true,
            "spacing": "Large",
            "height": "stretch",
            "size": "Large",
            "weight": "Bolder",
            "color": "Accent",
            "horizontalAlignment": "Center"
        },
        {
            "type": "TextBlock",
            "text": "Pre EMT FRAT has defined the day as:",
            "wrap": true,
            "horizontalAlignment": "Center",
            "separator": true
        }
    ]
}

**Comment by Andrew-Murdock** [comment]
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "text": "@{outputs('Post_adaptive_card_and_wait_for_a_response')?['body/data/dateFRAT']}",
            "wrap": true,
            "spacing": "Large",
            "height": "stretch",
            "size": "Large",
            "weight": "Bolder",
            "color": "Accent",
            "horizontalAlignment": "Center"
        },
        {
            "type": "TextBlock",
            "text": "Pre EMT FRAT has defined the day as:",
            "wrap": true,
            "horizontalAlignment": "Center",
            "separator": true
        },
        {
            "type": "TextBlock",
            "text": "Green",
            "wrap": true,
            "separator": true,
            "$when": "${1 = 1}",
            "height": "stretch",
            "horizontalAlignment": "Center",
            "size": "Medium",
            "weight": "Bolder",
            "color": "Good"
        },
        {
            "type": "TextBlock",
            "text": "Yellow",
            "wrap": true,
            "separator": true,
            "$when": "${1 = 2}",
            "height": "stretch",
            "horizontalAlignment": "Center",
            "size": "Medium",
            "weight": "Bolder",
            "color": "Warning",
            "isSubtle": true
        },
        {
            "type": "TextBlock",
            "text": "Green",
            "wrap": true,
            "separator": true,
            "$when": "${1 = 3}",
            "height": "stretch",
            "horizontalAlignment": "Center",
            "size": "Medium",
            "weight": "Bolder",
            "color": "Attention"
        }
    ]
}

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing for now. We may return to this in the future. Feel free to continue the conversation in this issue.

**Comment by drevil75** [comment]
you are trying to assig a value, not to compare.
wrong: "$when": "${@{outputs('Post_adaptive_card_and_wait_for_a_response')?['body/data/choiceFRATRating']} = 2}"
right: "$when": "${@{outputs('Post_adaptive_card_and_wait_for_a_response')?['body/data/choiceFRATRating']} == 2}"
