### ISSUE TITLE
Creating an Image

### ISSUE THREAD

**Issue by ryuzaki4337** [microsoft/AdaptiveCards#6475]
![ChatBot4](https://user-images.githubusercontent.com/56956409/135721392-18d8a1ee-42d6-40f4-beab-5d26123d459f.jpg)
Can we design images as it is shown in the above image using an adaptive card? If so, can someone help me out. Like +2/+3 on a given image

**Comment by RebeccaAnne** [comment]
We don't currently support the scenario of adding +2/+3 on top of an image. You can achieve that visual by including that in the image you send.
