### ISSUE TITLE
[Bug] [Android] Static Filtered Choice Set

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#6480]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android

# Version of SDK
v1.5

# Issue
- [ ] #6484
- [ ] #6483
 - [ ] #6485
![Screenshot_20211004-124248](https://user-images.githubusercontent.com/4112696/135914621-e8f7a3a1-bef4-4cbd-b963-4e219d2f44af.png)

**Comment by RebeccaAnne** [comment]
These issue have been split out into separate bugs. Closing this master bug.
