### ISSUE TITLE
[Smoke Test] [Android] Tables

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#6482]
- [ ] #6486

![Screenshot_20211004-125218](https://user-images.githubusercontent.com/4112696/135915997-ff101c21-5c1c-4322-be05-0c0ad47351a2.png)
- [ ] #6487
![Screenshot_20211004-130147](https://user-images.githubusercontent.com/4112696/135916856-a58af5f6-39b0-4e04-9ecf-d77c913859ca.png)

**Comment by RebeccaAnne** [comment]
The sub issues have been spun off into separate issues. Closing this master bug.
