### ISSUE TITLE
[Android] Tables: inner gridline is darker; gridlines may overwrap each other.

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6486]
From #6482

![image](https://user-images.githubusercontent.com/9091833/135922066-8b329a86-e533-4c66-a307-09da10f0bada.png)

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
