### ISSUE TITLE
[BugBash][Android] Text Clipping

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#6489]
Text in cells is clipped.
![Screenshot_20211004-142049](https://user-images.githubusercontent.com/4112696/135926716-a05bb7fc-09e1-4cfe-923c-1a4bdb032754.png)

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing for now. We may return to this in the future. Feel free to continue the conversation in this issue.
