### ISSUE TITLE
[BugBash][Android] Icon is not centered when button doens't have title.

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#6490]
![Screenshot_20211004-142938](https://user-images.githubusercontent.com/4112696/135927816-8232549a-942a-4cf2-8337-66364e4824a3.png)

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.
