### ISSUE TITLE
[Inconsistency] Inconsistent Behavior of Handling Missing Title for Inline Action

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#6491]
### Target Platforms

Other

### SDK Version

Main 1.5

### Application Name

N/A

### Problem Description

If no title is given for inline action, JS or Designer set `inline action` as a default string whereas iOS/Android set empty string. This is inconsistent behavior, and setting `inline action` seems to be the right behavior.

### Card JSON
 
```JSON
      {
            "type": "Input.Text",
            "label": "Input w/ Inline Action",
            "id": "0",
            "inlineAction": {
                "type": "Action.Submit"
            }
        }
```

**Comment by paulcam206** [comment]
closing as this is not a very high priority, and card authors should be specifying a title
