### ISSUE TITLE
[BugBash][Android] Image Size doesn't seem to work properly

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#6497]
Some Images' size seems off when tested With [RtlTestCard.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.5/Test/RtlTestCard.json).
### JS
![Screen Shot 2021-10-04 at 2 59 14 PM](https://user-images.githubusercontent.com/4112696/135930546-58d4f804-92ae-49b1-8ca9-c1a7ec55bd35.png)
### Android
![Screenshot_20211004-145525](https://user-images.githubusercontent.com/4112696/135930689-b1304782-dfdb-4439-be51-b80ab8fa53e5.png)
![Screenshot_20211004-145533](https://user-images.githubusercontent.com/4112696/135930675-a9aca614-2185-48da-85cd-2ac043bfa465.png)
![Screenshot_20211004-145539](https://user-images.githubusercontent.com/4112696/135930680-ea16cd25-b28e-4228-af16-4f927b1da42b.png)

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
