### ISSUE TITLE
[iOS] Empty space in StockUpdate card

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/AdaptiveCards#6498]
# Platform

* iOS

# Version of SDK

main

# Issue

StockUpdate card is showing a big empty space above the 2.69 USD text block

![Simulator Screen Shot - iPhone 13 Pro - 2021-10-04 at 14 59 42](https://user-images.githubusercontent.com/35784165/135930678-33ebe216-0946-4848-ab02-1f34c9ebb6ab.png)

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
