### ISSUE TITLE
[Designer] Designer doesn't have RTL support

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6508]
### Problem Description

The designer does not provide a way to mark a card/container/column as RTL in the UI. It does handle the property correctly if manually typed into the json editor.

### Card JSON

```JSON
none
```

### Screenshot

![image](https://user-images.githubusercontent.com/9091833/136111564-5ab47eb4-27e8-4653-b5f3-09cc2511b252.png)

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing for now. We may return to this in the future. Feel free to continue the conversation in this issue.
