### ISSUE TITLE
[Android] [BugBash] Container.SelectAction.json

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#6519]
[Container.SelectAction.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Elements/Container.SelectAction.json)
Tooltip works only for the container with `Emphasis link`. The card has three tooltips one for each container.

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
