### ISSUE TITLE
[JavaScript] Select Actions in RichTextBlocks are not disabled when isEnabled is set to false

### ISSUE THREAD

**Issue by RebeccaAnne** [microsoft/AdaptiveCards#6523]
### Target Platforms

NodeJS

### SDK Version

https://adaptivecardsci.z5.web.core.windows.net/designer 10/6/2021

### Application Name

Designer

### Problem Description

The isEnabled property is not respected on SelectActions on TextRuns.

### Screenshots

![image](https://user-images.githubusercontent.com/9091833/136292521-0b3dcff3-5447-4dd3-9827-2f3dcf86442f.png)

### Card JSON

```JSON
{
	"type": "AdaptiveCard",
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"version": "1.5",
	"body": [
		{
			"type": "RichTextBlock",
			"inlines": [
				{
					"type": "TextRun",
					"text": "Do not click "
				},
				{
					"type": "TextRun",
					"text": "here",
					"selectAction": {
						"type": "Action.Submit",
						"isEnabled": false
					}
				},
				{
					"type": "TextRun",
					"text": ", as it is disabled."
				}
			]
		}
	]
}
```

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing for now. We may return to this in the future. Feel free to continue the conversation in this issue.
