### ISSUE TITLE
Date Input selecting a date prior to the selected date on Adaptive Card Version 1.2

### ISSUE THREAD

**Issue by snandaku** [microsoft/AdaptiveCards#6529]
### Target Platforms

NodeJS

### SDK Version

1.2

### Application Name

MS Teams

### Problem Description

We found that recently, without any changes in our existing code, we see that now the date which is selected on the calender is one day ealier than the selected date.

Is there any issue already open on this. Attaching the details for reference.

On Button submission, the value received from the context ( context.activity.value.) comes a day earlier to the selected date.

Regards
Smitha

### Screenshots

<img width="351" alt="date issue" src="https://user-images.githubusercontent.com/64223805/136342677-a78210ef-97d9-49f1-b18a-37c4caa19fd0.PNG">
But value received is "2021-10-15"

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "type": "Input.Date",
            "id": "date1"
        },
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.Submit",
                    "title": "Submit",
                    "data": {
                        "Action": "selectDate"
                    }
                }
            ]
        }
    ]
}
```

### Sample Code Language

Nodejs

### Sample Code

console.log(context.activity.value.date1);

**Comment by stojanovic** [comment]
Hey, we have the same problem with our customers in production, and it drives me crazy. I have been trying to report it for two weeks, and everyone is just redirecting us to another support or another Github repository.

Here's a detailed video of the issue:

https://user-images.githubusercontent.com/613478/136363013-f43f5af9-0a01-4437-a279-c7c40de090f0.mp4

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4355
