### ISSUE TITLE
[Rendering] Warnings on UWP AdaptiveCardVisualizer when loading flightdetails.json

### ISSUE THREAD

**Issue by licanhua** [microsoft/AdaptiveCards#6535]
### Target Platforms

UWP

### SDK Version

0

### Application Name

n/a

### Problem Description

There is warnings

### Screenshots

![image](https://user-images.githubusercontent.com/6290692/136440814-5338ede8-53fa-42f3-a832-82a4b1e9c370.png)

### Card JSON

```JSON
flightdetails.json
```

**Comment by paulcam206** [comment]
@beervoley - this is another good first issue... it looks like UWP is generating an error in `RichTextBlock` elements when the `inlines` property is specified as an object rather than a string ([both](https://github.com/microsoft/AdaptiveCards/issues/1933#issuecomment-483459493) are supported)
