### ISSUE TITLE
BadRequest when using AdaptiveRefresh in AdaptiveCard

### ISSUE THREAD

**Issue by gsamuelb** [microsoft/AdaptiveCards#6596]
### Target Application

Microsoft Teams

### Application Operating System

Windows

### Schema Version

1.4

### Problem Description

I am using the .NET Platform, version 2.7.2. I have a problem when I send an AdaptiveCard including an AdaptiveRefresh through ConnectorClient.Conversations.SendToConversationAsync. It always returns a BadRequest error. I have no problem sending an AdaptiveCard without specifying an AdaptiveRefresh.

After testing, I found out an issue with the mapping between the C# class and the JSON payload for the AdaptiveRefresh class. 

The refresh part of the JSON sent looks like this :

`"refresh": {
   "Action": {
	  "type": "",
	  "verb": "",
	  "title": ""
   },
   "UserIds": []
}`

while it should look like this :

`"refresh": {
   "action": {
	  "type": "",
	  "verb": "",
	  "title": ""
   },
   "userIds": []
}`

I know this is the problem because I changed the properties capitalization at runtime while debugging and it worked.

### Expected Outcome

I want my AdaptiveCard to refresh properly when I add a AdaptiveRefresh to it.

### Actual Outcome

I receive a BadRequest error and the card does not appear in Microsoft Teams.

### Card JSON

```JSON
-
```

**Comment by baton17** [comment]
This issue looks like duplicate of https://github.com/microsoft/AdaptiveCards/issues/6862, which is fixed in this change https://github.com/microsoft/AdaptiveCards/pull/7107
