### ISSUE TITLE
[Rendering] JANK (UI Shift) when clicking on Audio media without poster

### ISSUE THREAD

**Issue by anindara** [microsoft/AdaptiveCards#6607]
### Target Platforms

NodeJS

### SDK Version

1.3

### Application Name

Viva Connections

### Problem Description

When no poster is set for an audio media, clicking on the item causes a significant UI reflow/JANK. Can we prevent the reflow or is the recommendation here to use posters with fixed height. 

### Screenshots

![image](https://user-images.githubusercontent.com/22333452/137965134-1cba6721-4f5f-476f-8fa9-92b9d5d2d546.png)

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "Media",
            "id": "vid3",
            "altText": "Adaptive Card Audio (No Poster)",
            "sources": [
                {
                    "mimeType": "audio/mp3",
                    "url": "https://adaptivecardsblob.blob.core.windows.net/assets/AdaptiveCardsOverviewVideo.mp3"
                }
            ]
        }
    ]
}
```

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
