### ISSUE TITLE
[Rendering] Original aspect ratio not respected, causing image distortion

### ISSUE THREAD

**Issue by anindara** [microsoft/AdaptiveCards#6608]
### Target Platforms

NodeJS

### SDK Version

1.3

### Application Name

Viva Connections

### Problem Description

Image aspect ratio is not respected resulting in a distorted image. The source image below is 2048x1365px and embedding it on a person style clearly shows the distortion as seen in the screenshot

### Screenshots

![image](https://user-images.githubusercontent.com/22333452/137965879-1a7c84df-3aec-4ea3-9760-e5e5dc6c5e6c.png)

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "TextBlock",
            "text": "Image 2048x1365 - Persona 200x200px with background #333333",
            "wrap": true
        },
        {
            "type": "Image",
            "url": "https://news.microsoft.com/wp-content/uploads/prod/2020/02/SAKristiOdom4.jpg",
            "height": "200px",
            "selectAction": {
                "type": "Action.OpenUrl"
            },
            "width": "200px",
            "backgroundColor": "#333333",
            "style": "Person"
        }
    ]
}
```

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
