### ISSUE TITLE
[Website] Samples page left nav is incorrectly blue

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#6622]
Seen here: http://adaptivecards-release-ci.azurewebsites.net/samples/

![image](https://user-images.githubusercontent.com/1432195/138179625-6bd3fa41-1ce7-4d7e-ac21-8cde9bfd1689.png)

**Comment by paulcam206** [comment]
this was an intentional change to satisfy accessibility requirements (see #5534) - we should consider having a conversation with them if we want to change this back :)
