### ISSUE TITLE
[Rendering] Adaptive Cards Push Button not rendering border on iOS 15

### ISSUE THREAD

**Issue by SamuelBishop** [microsoft/AdaptiveCards#6623]
### Target Platforms

iOS

### SDK Version

1.1.0

### Application Name

Microsoft Omnichannel Live Chat Widget

### Problem Description

Multiple choice questions (in ActionSet type) are rendered without border in iOS 15.

Steps for fast and easy repro: 
1. Navigate to this link on an iOS 15 device https://oclocalsamuelbinameusrs.blob.core.windows.net/localwidgets/normal.html

2. Wait for the bot to respond

3. In the chat enter the text, "mr cooper card" and press submit

4. Witness the adaptive card push buttons without borders

*Note: I have tired the most recent version of the adaptive cards package and this error still repros.

### Screenshots

![image](https://user-images.githubusercontent.com/43118573/138181128-74851dbf-7c4e-4552-add6-9992b54425d5.png)

### Card JSON

```JSON
{
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.2",
  "body": [
    {
      "type": "Container",
      "items": [
        {
          "type": "TextBlock",
          "text": "Paperless protects your personal information and gives you anytime access to your important documents.\u000b",
          "wrap": true,
          "color": "Light"
        },
        {
          "type": "TextBlock",
          "text": "I have read the [paperless disclosure](https://www.mrcooper.com/paperless/disclosure) and agree to receive all my account communications electronically.",
          "wrap": true,
          "size": "Small",
          "color": "Light"
        },
        {
          "type": "ActionSet",
          "actions": [
            {
              "type": "Action.Submit",
              "title": "Go Paperless"
            },
            {
              "type": "Action.Submit",
              "title": "Maybe Later"
            }
          ]
        }
      ],
      "bleed": true,
      "backgroundImage": {
        "url": "https://test/test.gif"
      }
    }
  ]
}
```

### Sample Code Language

.json

**Comment by jonmill** [comment]
@SamuelBishop - closing as we don't have enough info here. If you could reply back to Joseph's question above, we can re-open and investigate. Thanks!
