### ISSUE TITLE
[Rendering] Discrepancy (in js and C# libraries) while rendering an AC template containing an invalid "$when" condition 

### ISSUE THREAD

**Issue by SowmyaVelugoti** [microsoft/AdaptiveCards#6630]
### Target Platforms

NodeJS

### SDK Version

latest

### Application Name

Microsoft Search

### Problem Description

We observe that, when the Adaptive card contains an invalid $when condition (an example of which is given below)

Example:
"$when": "https://searchuxcdn.azureedge.net/designerapp/images/servicenow-icon.png!=\"\""

The C# Templating library throws an exception, when we try to bind the template with data -> adaptiveTemplate.Expand(source),  with the following exception message:  "String was not recognized as a valid Boolean." 

However, the JS library  treats it as a valid string and displays the result evaluating the condition to true.
Can this discrepancy be fixed ?

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "${title}",
            "$when": "https://searchuxcdn.azureedge.net/designerapp/images/servicenow-icon.png!=\"\""
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5"
}
```

### Sample Code Language

C#

**Comment by SowmyaVelugoti** [comment]
Team, 

Do we have any ETA on this ?

Thanks,
Sowmya

**Comment by paulcam206** [comment]
Fixing this issue is not currently on our roadmap. Feel free to continue the conversation on this issue. If you feel strongly about this issue, please let us know and we can reevaluate.

**Comment by anna-dingler** [comment]
## Issue

NodeJS and .NET templating libraries resolve invalid `$when` conditions differently

### On NodeJS platform

We evaluate the `$when` condition if the given value is `instanceof AEL.Expression`. Invalid expressions skip over this logic and essentially ignore `$when` espression.

However, if evaluating given expression results in an error or non-boolean value, we default to `false`.

Code can be viewed [here](https://github.com/microsoft/AdaptiveCards/blob/main/source/nodejs/adaptivecards-templating/src/template-engine.ts#L408-L418)


### On .NET platform

Throws an error when the given string isn't an expression.

## Proposed Solution

Realign platforms by having them return `false` if the given condition is invalid and sending a warning that the condition was invalid.

**Comment by jwoo-msft** [comment]
@anna-dingler 

Can you elaborate on what constitutes invalid? 
for example, does invalid include syntax error in template language and run time error at AEL?

When you say returning false, do you implying dropping adaptive element that has `when`?

**Comment by anna-dingler** [comment]
> @anna-dingler
> 
> Can you elaborate on what constitutes invalid? for example, does invalid include syntax error in template language and run time error at AEL?
> 
> When you say returning false, do you implying dropping adaptive element that has `when`?
@jwoo-msft 

In this case, invalid means it is not an expression. For instance `"0 ==0"` is not an expression because it needs to be surrounded by `"${}"`. `"${0 ==0}"` would be valid.

We are not considering errors that AEL has when it tries to parse a valid expression.

Yes, returning false means that the adaptive element would be dropped.

**Comment by jwoo-msft** [comment]
> > @anna-dingler
> > Can you elaborate on what constitutes invalid? for example, does invalid include syntax error in template language and run time error at AEL?
> > When you say returning false, do you implying dropping adaptive element that has `when`?
> 
> @jwoo-msft
> 
> In this case, invalid means it is not an expression. For instance `"0 == 0"` is not an expression because it needs to be surrounded by `"${}"`. `"${0 == 0}"` would be valid.
> 
> We are not considering errors that AEL has when it tries to parse a valid expression.
> 
> Yes, returning false means that the adaptive element would be dropped.

yes, so syntax error is invalid.

**Comment by anna-dingler** [comment]
> 

Yes.

I just checked and we also have a discrepancy between the platforms if there is a run time error at AEL. NodeJS drops the element and .NET displays it.

**Comment by jwoo-msft** [comment]
@anna-dingler,
please take a look at [this spec](
https://github.com/microsoft/AdaptiveCards/blob/main/specs/DesignDiscussions/Inconsistencies.md#differences-in-handling-invalid-values-in-rendering)
at parser level, when we encounter an invalid value, we create a warning and hand it to renderer.
render will decide whether to render it or not with warning.
if chose to render, then our renderer will do the best effort to render.

js renderer behaver behaves closer to the spec.

however, i think we should think more carefully about what to substitute for invalid syntax. essentially, we are deciding what is the best default value for $when. since it's boolean, we have only two choices. 

with warnings, renderers still has opportunity to decide whether to render or not.

**Comment by jwoo-msft** [comment]
> @jwoo-msft
> 
> I just checked and we also have a discrepancy between the platforms if there is a run time error at AEL. NodeJS drops the element and .NET displays it.

if it was other way around, it would have been easier to decide. i'm wondering if js has setting of not rendering with warning.

**Comment by anna-dingler** [comment]
> > @jwoo-msft
> > I just checked and we also have a discrepancy between the platforms if there is a run time error at AEL. NodeJS drops the element and .NET displays it.
> 
> if it was other way around, it would have been easier to decide. i'm wondering if js has setting of not rendering with warning.

Are you suggesting that we look into resolving this on the renderer side instead?

**Comment by jwoo-msft** [comment]
> > > @jwoo-msft
> > > I just checked and we also have a discrepancy between the platforms if there is a run time error at AEL. NodeJS drops the element and .NET displays it.
> > 
> > 
> > if it was other way around, it would have been easier to decide. i'm wondering if js has setting of not rendering with warning.
> 
> Are you suggesting that we look into resolving this on the renderer side instead?

No, I'm saying that js seems to have inconsistency in rendering between template with invalid ael syntax in $when and AEL runtime error. i'm not advocating one over the other.

**Comment by almedina-ms** [comment]
> > > > @jwoo-msft
> > > > I just checked and we also have a discrepancy between the platforms if there is a run time error at AEL. NodeJS drops the element and .NET displays it.
> > > 
> > > 
> > > if it was other way around, it would have been easier to decide. i'm wondering if js has setting of not rendering with warning.
> > 
> > 
> > Are you suggesting that we look into resolving this on the renderer side instead?
> 
> No, I'm saying that js seems to have inconsistency in rendering between template with invalid ael syntax in $when and AEL runtime error. i'm not advocating one over the other.

I had issues understanding what's the behaviour on each platform, are you saying for JS, if the $when condition is not a proper condition, it also raises a warning and can also render the card as if the $when condition evaluated to true?

**Comment by anna-dingler** [comment]
@almedina-ms 

We have two scenarios

1. $when condition is not an expression (ex: `"$when": "notAnExpression"`)
**JS Behavior**: $when evaluates to true - no warning
**.NET Behavior**: throws an error and card is not rendered


2. $when condition is an invalid expression (ex: `"$when": "${invalidExpression}"`
**JS Behavior**: $when evaluates to false - no warning
**.NET Behavior**: $when evaluates to true - no warning


I'm thinking that both of these scenarios should have the same behavior and throw a warning so developers know where the default value came from.

**Comment by dclaux** [comment]
I agree with the proposed resolution: if `$when` is specified, it cannot be ignored (as opposed to what JS currently does). If it's not an expression, if it's an expression that doesn't return a Boolean, or if it's an invalid expression, it should always return `false`. Throwing (as .NET currently does in one case) isn't desirable IMO.
