### ISSUE TITLE
[Feature Request] support template bool for rtl and other boolean properties.

### ISSUE THREAD

**Issue by licanhua** [microsoft/AdaptiveCards#6631]
### Problem Statement

$ is not a valid usage in JSON, so it has problem to convert the template data to bool directly.
```
"rtl": ${bool($rtl)}
```

### Proposed solution
Data binding works as expected as requested in this feature request. To see the correct usage, see [4350](https://github.com/microsoft/AdaptiveCards/issues/4350). Designer needs to be updated so that a serialization doesn't happen before template expansion because templates are stripped off if the expected type are not string.

**Comment by aarongustafson** [comment]
Ditto for `int()` to be used with `value`, `min`, and `max` for number fields.

**Comment by JeanRoca** [comment]
Is this a regression? I'm not sure if this is a new feature request or a bug since this PR seems to address it:
https://github.com/microsoft/AdaptiveCards/pull/4351

**Comment by JeanRoca** [comment]
See https://github.com/microsoft/AdaptiveCards/issues/4350 as well

**Comment by aarongustafson** [comment]
@JeanRoca Given the dates, I’m guessing it’s a regression. Not sure if it is extended to `int()`, but if it isn’t it should be.

**Comment by jwoo-msft** [comment]
I think this might be just Designer issue. let me try using in code. There will a lot more issues filed if this doesn't work.

**Comment by jwoo-msft** [comment]
Hey, I verify that it does work in code.

**Comment by jwoo-msft** [comment]
I've updated the feature request with a proposed solution.

**Comment by JeanRoca** [comment]
This also happens when trying to set image height and width using the data payload.

Card JSON
```
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5",
    "body": [
        {
            "type": "TextBlock",
            "text": "Image test:",
            "wrap": true
        },
        {
            "type": "Image",
            "url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg",
            "width": "${imageSize}",
            "height": "${imageSize}"
        }
    ]
}
```

Data JSON
```
{
    "imageSize": "100px"
}
```
