### ISSUE TITLE
[.NET] `AdaptiveCards.Rendering.Wpf` package license miscategorized

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#6642]
On the ClearlyDefined site, the [`AdaptiveCards.Rendering.Wpf`](https://clearlydefined.io/?sort=releaseDate&sortDesc=true&name=AdaptiveCards.Rendering.Wpf) package's licensing is described as "Other". We should review our packages on the site and remediate any license packaging and declaration issues we may have to make sure they are accurate. The shift away from `MIT` was likely caused by #5169.

**Comment by jonmill** [comment]
Internal task that was taken care of
