### ISSUE TITLE
[Rendering] HTML Renderer posts Input.Number value as a string with Action.Execute

### ISSUE THREAD

**Issue by tomlm** [microsoft/AdaptiveCards#6669]
### Target Platforms

Other

### SDK Version

2.7

### Application Name

HTML

### Problem Description

Input.number posts the value as a string instead of a number.

Repo:
1. create empty card with Text.Input with Id X in designer
2. Set value to 3
3. Click Action.Execute
Payload will be 
```
"data":  {
      "X":"3"
}
```
Expected:
```
"data":  {
      "X": 3
}
```
with no quotes, as that is the valid json for numbers.

### Screenshots

![image](https://user-images.githubusercontent.com/17789481/139724646-bd09da58-560d-4399-9e26-086b554ff265.png)

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5",
    "body": [
        {
            "type": "Input.Number",
            "placeholder": "Placeholder text",
            "label": "X",
            "value": 3,
            "id": "X"
        }
    ],
    "actions": [
        {
            "type": "Action.Execute",
            "title": "Action.Execute"
        }
    ]
}
```

**Comment by jonmill** [comment]
Per David's comment https://github.com/microsoft/AdaptiveCards/issues/6670#issuecomment-958216601, this is by-design. Same comment applies that if you'd like us to change this then please re-open and I'll convert to a feature request. Thanks!
