### ISSUE TITLE
[Rendering] [import] some "..." appear in text, text  loss 

### ISSUE THREAD

**Issue by kevin-leak** [microsoft/AdaptiveCards#6674]
### Target Platforms

Android

### SDK Version

2.8.0

### Application Name

Microsoft Adaptive Card demo.

### Problem Description

Why are there some "...". This is not correct.
Please help find the root cause and solution.

if we delete the code of `textView.setMovementMethod(LinkMovementMethod.getInstance());
` in TextBlockRender
it look like good.

### Screenshots

![image](https://user-images.githubusercontent.com/30002212/139827821-985a69ab-b368-46f5-a2c4-3e9d94f3c385.png)

### Card JSON

```JSON
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
   {
     "type": "ColumnSet",
     "height": "stretch",
     "columns": [
      {
        "type": "Column",
        "items": [
         {
           "type": "TextBlock",
           "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris",
           "wrap": true
         }
        ]
      },
      {
        "type": "Column",
        "separator": true,
        "items": [
         {
           "type": "TextBlock",
           "text": "FactSet",
           "wrap": true
         }
        ]
      }
     ]
   }
  ]
}
```

### Sample Code Language

english

### Sample Code

None

**Comment by jonmill** [comment]
@almedina-ms - can you take a look and see what is going on here please?

**Comment by kevin-leak** [comment]
@almedina-ms 
Hello, I know you are very busy, but the bugs that these text disappear greatly affect the user experience, now there is a solution？

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration. We are, however, happy to take a PR to fix it!
