### ISSUE TITLE
[Designer] Automatic scroll down event fired on dragging card elements 

### ISSUE THREAD

**Issue by santiagoclv** [microsoft/AdaptiveCards#6685]
### Problem Description

An automatic scroll down event to the bottom of the page is being fired when a card element is dragged from the card elements toolbox to the card. You can notice it in the official page https://adaptivecards.io/designer/ but it is more noticeable when the page where the Adaptive Card Designer is being embedded has a footer or something below the ACD.

There is some cases where this automatic event is not being fired, for example when the Tree View is collapsed.

### Card JSON

```JSON
{}
```

**Comment by jonmill** [comment]
Great find, thank you! This is a great first issue for folks to contribute back 🙂

**Comment by paulcam206** [comment]
Addressing this issue is not currently on our roadmap, so closing. Please feel free to continue the conversation in this issue for future consideration.
