### ISSUE TITLE
[Designer] Feedback title here

### ISSUE THREAD

**Issue by ending1221** [microsoft/AdaptiveCards#6687]
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "width": "auto",
                    "backgroundImage": {
                        "verticalAlignment": "Center",
                        "horizontalAlignment": "Center"
                    },
                    "items": [
                        {
                            "type": "Image",
                            "url": "https://event.smarter.com.tw/_nuxt/img/logo_bk.9b7a6e9.svg",
                            "size": "Medium",
                            "horizontalAlignment": "Center",
                            "width": "120px"
                        }
                    ]
                },
                {
                    "type": "Column",
                    "items": [
                        {
                            "type": "TextBlock",
                            "weight": "Bolder",
                            "text": "OOO 門市線上預約報表",
                            "wrap": true,
                            "size": "Medium"
                        },
                        {
                            "type": "TextBlock",
                            "spacing": "None",
                            "text": "Created {{DATE(${createdUtc},SHORT)}}",
                            "isSubtle": true,
                            "wrap": true
                        }
                    ],
                    "width": "stretch"
                }
            ]
        },
        {
            "type": "Table",
            "columns": [
                {
                    "width": 1
                },
                {
                    "width": 1
                },
                {
                    "width": 1
                },
                {
                    "width": 1
                }
            ],
            "rows": [
                {
                    "type": "TableRow",
                    "cells": [
                        {
                            "type": "TableCell",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "客戶名稱",
                                    "wrap": true,
                                    "horizontalAlignment": "Center"
                                }
                            ],
                            "horizontalAlignment": "Center",
                            "height": "stretch"
                        },
                        {
                            "type": "TableCell",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "預約項目",
                                    "wrap": true,
                                    "horizontalAlignment": "Center",
                                    "height": "stretch"
                                }
                            ]
                        },
                        {
                            "type": "TableCell",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "預約時段",
                                    "wrap": true,
                                    "horizontalAlignment": "Center",
                                    "height": "stretch"
                                }
                            ],
                            "backgroundImage": {
                                "verticalAlignment": "Center",
                                "horizontalAlignment": "Center"
                            }
                        },
                        {
                            "type": "TableCell",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "客戶電話",
                                    "wrap": true,
                                    "horizontalAlignment": "Center",
                                    "height": "stretch"
                                }
                            ],
                            "backgroundImage": {
                                "verticalAlignment": "Center"
                            }
                        }
                    ]
                },
                {
                    "type": "TableRow",
                    "cells": [
                        {
                            "type": "TableCell",
                            "items": [
                                {
                                    "type": "ActionSet",
                                    "actions": [
                                        {
                                            "type": "Action.OpenUrl",
                                            "title": "陳品潔",
                                            "url": "https://event.smarter.com.tw/2020/head_spa/"
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "type": "TableCell",
                            "items": [
                                {
                                    "type": "ActionSet",
                                    "actions": [
                                        {
                                            "type": "Action.OpenUrl",
                                            "title": "身體療程",
                                            "url": "#",
                                            "isEnabled": false
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "type": "TableCell",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "2021-11-06 18:00",
                                    "wrap": true,
                                    "horizontalAlignment": "Center"
                                }
                            ]
                        },
                        {
                            "type": "TableCell",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "0989166358",
                                    "wrap": true,
                                    "horizontalAlignment": "Center"
                                }
                            ]
                        }
                    ]
                },
                {
                    "type": "TableRow",
                    "cells": [
                        {
                            "type": "TableCell",
                            "items": [
                                {
                                    "type": "ActionSet",
                                    "actions": [
                                        {
                                            "type": "Action.OpenUrl",
                                            "title": "陳品潔",
                                            "url": "https://event.smarter.com.tw/2020/head_spa/"
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "type": "TableCell",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "身體療程",
                                    "wrap": true,
                                    "horizontalAlignment": "Center",
                                    "height": "stretch",
                                    "maxLines": 1
                                }
                            ]
                        },
                        {
                            "type": "TableCell",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "2021-11-06 18:00",
                                    "wrap": true,
                                    "horizontalAlignment": "Center"
                                }
                            ]
                        },
                        {
                            "type": "TableCell",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "0989166358",
                                    "wrap": true,
                                    "horizontalAlignment": "Center"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5"
}

**Comment by jonmill** [comment]
@ending1221 - can you please use our Issue Forms to re-file and provide the relevant information? Thanks!
