### ISSUE TITLE
[Feature Request] Trusted Types support in JavaScript SDK

### ISSUE THREAD

**Issue by tosmolka** [microsoft/AdaptiveCards#6692]
### Problem Statement

JavaScript SDK should fully support [Trusted Types API](https://w3c.github.io/webappsec-trusted-types/dist/spec/) so that it can be seamlessly integrated in applications that enforce Trusted Types for all [DOM XSS Injection Sinks](https://w3c.github.io/webappsec-trusted-types/dist/spec/#dom-xss-injection-sinks) (such as innerHTML setters) via CSP directive [require-trusted-types-for](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for). 

On a practical side this means hopefully minor re-factoring of methods where string content is interpreted as HTML and possibly appended to DOM. At first glance there are only few locations in code where this is happening (e.g. assignments to innerHTML) so chances are this can be achieved with relatively low effort. 

### Proposed solution

Review source code of the library and identify locations that will require rewrite, groom it and do it. We could start from this list:

- Empty string assignments into .innerHTML
  - Here we should leverage [TrustedTypePolicyFactory.emptyHTML](https://w3c.github.io/webappsec-trusted-types/dist/spec/#dom-trustedtypepolicyfactory-emptyhtml)
    - https://github.com/microsoft/AdaptiveCards/blob/45bd264a7b64e7bc452961a83143a557b174a65f/source/nodejs/adaptivecards-react/src/adaptive-card.tsx#L127
    - https://github.com/microsoft/AdaptiveCards/blob/495987d1d4a3eef2e41a271111006a33b147a37b/source/nodejs/adaptivecards-controls/src/calendar.ts#L165
    - https://github.com/microsoft/AdaptiveCards/blob/495987d1d4a3eef2e41a271111006a33b147a37b/source/nodejs/adaptivecards-controls/src/calendar.ts#L285
    - https://github.com/microsoft/AdaptiveCards/blob/0ceb34c39647f0fe811e51554466a7d417855a27/source/nodejs/adaptivecards-controls/src/radiobutton.ts#L78
    - https://github.com/microsoft/AdaptiveCards/blob/0ceb34c39647f0fe811e51554466a7d417855a27/source/nodejs/adaptivecards-controls/src/textbox.ts#L150

- Arbitrary HTML assignments into .innerHTML
  - Here we probably need to create unique [TrustedTypesPolicy](https://w3c.github.io/webappsec-trusted-types/dist/spec/#create-trusted-type-policy-algorithm) for AdaptiveCards SDK and wrap content using `createHTML` method prior assignment. 
    - https://github.com/microsoft/AdaptiveCards/blob/cf1e0a81753b1240cb0325983e67398e31987497/source/nodejs/adaptivecards/src/card-elements.ts#L926
    - https://github.com/microsoft/AdaptiveCards/blob/cf1e0a81753b1240cb0325983e67398e31987497/source/nodejs/adaptivecards/src/card-elements.ts#L1063
    - https://github.com/microsoft/AdaptiveCards/blob/437e57abde755ffaac542fb52408e4eaf4994870/source/nodejs/adaptivecards/src/utils.ts#L121
    - https://github.com/microsoft/AdaptiveCards/blob/66af50085692bf26a58f10e903b3053ac8a2aef3/source/nodejs/adaptivecards-controls/src/inputwithpopup.ts#L192

### Alternatives or Workarounds

Typical alternative is to rewrite the library to avoid using DOM XSS Injection Sinks completely. This is possible in some cases (e.g. when HTML is static and can be constructed by standard DOM manipulation methods) but not always. 

We also need to be careful to keep supporting browsers without Trusted Types support. This is usually done by testing whether window.trustedTypes is defined and fall-back to current behavior if it's not. 

Similar implementations in other libraries for reference:
 - [Visual Studio Code](https://github.com/microsoft/vscode/blob/469d4f6a1c1e36cf232358a8a7eb9d49a76ef56a/src/vs/editor/standalone/browser/colorizer.ts#L45)
 - [Webpack](https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/runtime/CreateScriptUrlRuntimeModule.js#L55)
 - [Angular](https://github.com/angular/components/blob/e7a3f683c80601c6e023f25626cffb0aeafa9032/src/material/icon/trusted-types.ts#L71)

**Comment by tosmolka** [comment]
@paulcam206 , @licanhua , do you plan to address my comments in the PR? Thank you.

**Comment by licanhua** [comment]
@tosmolka what comment? If you are going to add new comment, yes, please go ahead.

**Comment by tosmolka** [comment]
@licanhua , apologies, I did not submit the review so you were unable to see them. Comments should now be visible in the PR.
