### ISSUE TITLE
Input.Date Adaptive card Bug - Choosing year from calendar.

### ISSUE THREAD

**Issue by MROOPESH** [microsoft/AdaptiveCards#6719]
### Problem Statement

In Input.Date Adaptive card, How to change the year easily?? Should I need to choose different year date by click back button?
<img width="431" alt="Input date Adaptive card Bug" src="https://user-images.githubusercontent.com/24470490/141239088-ba581eb0-479f-4ea6-aca7-6b04ea16ea9e.PNG">

Previously, the Input.Date adpative card used to look like the following:

![IMG_20211110_174043](https://user-images.githubusercontent.com/24470490/141239170-4d88dee5-a253-4ac6-92ae-c6085172ab29.jpg)
![IMG_20211110_174059](https://user-images.githubusercontent.com/24470490/141239147-b66c6138-3ec8-4c5e-829a-b84edcd972ad.jpg)

Is this feature deprecated by https://adaptivecards.io/explorer ??
If so, why they make it complex to choose a date??

Awaiting your reply,
Regards.

### Proposed solution

I am not able to choose the year that is very earlier.

There is no drop down enabled to choose year.

![IMG_20211110_174043](https://user-images.githubusercontent.com/24470490/141239449-46bee3ef-c6f3-4926-937d-5f099e57aa78.jpg)

![IMG_20211110_174059](https://user-images.githubusercontent.com/24470490/141239491-be12bfe9-9aa4-4c1b-895f-13246e140304.jpg)

Awaiting your reply,
Regards.

**Comment by jonmill** [comment]
It looks like the card is being rendered in Teams, which overrides default AC behavior. Moving the issue over to them.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4553

**Comment by tacoblacho** [comment]
Hi,
I'm still having this same as of today. In Teams it doesn't let you scroll through the years, only back and forth arrow per month. From the answers above and the other repo https://github.com/MicrosoftDocs/msteams-docs/issues/4553 I couldn't find any solution. 

Thanks,
