### ISSUE TITLE
Failing to bundle after upgrading version to adaptivecards latest versions

### ISSUE THREAD

**Issue by arunakshi** [microsoft/AdaptiveCards#6721]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* SharePoint Framework 
* JavaScript
* 
# Version of SDK

node@10.14.0
npm@6.14.11
@microsoft/generator-sharepoint@1.12.1
gulp@4.0.2
adaptive-expressions@^4.14.1
adaptivecards@^2.10.0
adaptivecards-fluentui@^0.5.3
adaptivecards-templating@^2.2.0

# Issue

I built an SPFX solution to display adaptivecards dynamically based on provided card JSON. I was using old version of adaptivecards. I upgraded the adaptivecards version from 1.x to latest version (tried with 2.9.0 and 2.10.0) and also upgraded all adaptivecards relavant dependencies (adaptivecards-officeuifabric to adaptivecards-fluentui, adaptivecards-templating version and added alsoadaptive-expressions ) are upgraded. 

However I am getting the following error while bundling my SPFX solution: 

> Error - [tsc] node_modules/adaptivecards/lib/card-elements.d.ts(907,61): error TS1005: ',' expected.
> Error - [tsc] node_modules/adaptivecards/lib/card-elements.d.ts(907,67): error TS1005: ',' expected.
> Error - [tsc] node_modules/adaptivecards/lib/card-elements.d.ts(908,57): error TS1005: ',' expected.
> Error - [tsc] node_modules/adaptivecards/lib/card-elements.d.ts(908,63): error TS1005: ',' expected.
> Error - [tsc] node_modules/adaptivecards/lib/card-elements.d.ts(932,54): error TS1005: ',' expected.
> Error - [tsc] node_modules/adaptivecards/lib/card-elements.d.ts(932,60): error TS1005: ',' expected.
> Error - [tsc] node_modules/adaptivecards/lib/card-elements.d.ts(933,50): error TS1005: ',' expected.
> Error - [tsc] node_modules/adaptivecards/lib/card-elements.d.ts(933,56): error TS1005: ',' expected.
> Error - 'tsc' sub task errored after 9.14 s 
>  exited with code 2

Can anyone help me here please.

**Comment by jonmill** [comment]
It looks like your Typescript version needs to be upgraded; please upgrade your Typescript version in your packages.json file and see if that helps

**Comment by jonmill** [comment]
@arunakshi - does my suggestion above help solve your problem?

**Comment by arunakshi** [comment]
@jonmill, I haven't checked it yet. I had to use the older version. I would this over the weekend and will keep you updated

**Comment by jonmill** [comment]
Closing as we haven't received a confirmation and the proposed solution should fix the issue. If you feel that this question has not been resolved, please respond back with additional information and we'll re-engage. Thank you!
