### ISSUE TITLE
Dlls not signed for at least versions 2.7.1 and 2.7.2 in nuget

### ISSUE THREAD

**Issue by jofri-msft** [microsoft/AdaptiveCards#6735]
### Problem Description

I tried referencing both 2.7.1 and 2.7.2 in a Power Automate corext.config and both caused the builds to break because the dlls aren't signed. I had been able to upgrade the sdk to version 2.5.1 without any issue. This is blocking Power Automate from supporting adaptive cards with version 1.4 in the Teams connector

 Here's the failing master build:

```
8>X:\bt\1012451\repo\out\retail-amd64\RDPackage\ExpressV2Sandbox\Worker\Roles\Worker\AdaptiveCards.dll : error U1234: Unsigned file detected [X:\bt\1012451\repo\ExpressV2\ExpressV2.proj]
2021/11/12 12:36:30 PM         8>X:\bt\1012451\repo\out\retail-amd64\RDPackage\ExpressV2Sandbox\Synthetics\bin\AdaptiveCards.dll : error U1234: Unsigned file detected [X:\bt\1012451\repo\ExpressV2\ExpressV2.proj]
2021/11/12 12:36:30 PM         8>X:\bt\1012451\repo\out\retail-amd64\RDPackage\ExpressV2Sandbox\Frontend\Roles\Web\Bin\AdaptiveCards.dll : error U1234: Unsigned file detected [X:\bt\1012451\repo\ExpressV2\ExpressV2.proj
```

**Comment by paulcam206** [comment]
this has been fixed in the `2.7.3` release (which might take a bit to show up in NuGet)
