### ISSUE TITLE
Parse and Render failures/warnings

### ISSUE THREAD

**Issue by matthidinger** [Microsoft/AdaptiveCards#674]
## Problem

We need a way for Host Apps to determine whether a card has any parse errors/warnings and render error/warnings.

- [ ] Should we have standardized error codes across the SDKs? Does this add much/any benefit?
- [ ] Document the errors/warnings in the [Renderer spec](https://docs.microsoft.com/en-us/adaptive-cards/display/implementingrenderer)

## Parse Errors (throw)
* AdaptiveSerializationExpception
   * InvalidJson - The payload was not in a valid JSON format
   * SchemaViolations - The payload did not validate against the JSON-Schema
      * MissingRequiredProperty
      * InvalidPropertyValue (only primitives like bool, version, and non-extensible enums like Column width)

## Render Errors (throw)
* UnsupportedSchemaVersion
* Host Config - exceed max payload size

## Render Warnings 
* NoRendererForType (including actions)
* UnknownEnumValue (e.g., TextBlock size="massive")
* HostConfigWarnings
   * InteractivityNotSupported
   * TooManyActions

* Image/asset failing to load

## API 

Validate card against Host Config errors

```csharp
ValidationResult result = card.Validate(myHostConfig);
if (!result.IsValid) {
    IList<ValidationError> errors = result.Errors;
}
```

### Validate against Host Config

```csharp
ValidationResult result = card.Validate(myHostConfig);
```

**Comment by andrewleader** [comment]
Closing since all renderers return errors and warnings. A new issue can be opened for standardizing the errors/warnings across all the renderers if desired.
