### ISSUE TITLE
[.NET] Delete deprecated `AdaptiveCards.Rendering.Html` source

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#6747]

**Comment by jonmill** [comment]
Fixed in #6800

**Comment by mwasplund-msft** [comment]
Can we mark the nuget package as deprecated? https://www.nuget.org/packages/AdaptiveCards.Rendering.Html 

I spent time trying to figure out why this package was using such an old version of AdaptiveCards and the code was just gone with no indication besides this empty issue that this was on purpose.

**Comment by mwasplund-msft** [comment]
Also, our own docs tell folks to use this package for rendering HTML: https://learn.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/net-html/render-a-card
