### ISSUE TITLE
[Designer] AdaptiveCards 1.5 usage in Microsoft Teams

### ISSUE THREAD

**Issue by baconsplit** [microsoft/AdaptiveCards#6753]
I urgently want to use the "style" flag "Password" introduced by AdaptiveCards 1.5 Update in Microsoft Teams.
Building my App with an AdaptiveCard Version 1.5 into the Bot Framework Emulator just displays an empty card sadly, and usage in Teams wouldn't work either so far.

Any help or information on this topic?

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4654
