### ISSUE TITLE
[Designer] Default card does not render array data properly

### ISSUE THREAD

**Issue by teamstap100** [microsoft/AdaptiveCards#6755]
The default card in the Adaptive Card Designer specifies a FactSet that pulls from an array of data:

Card:
`        {
            "type": "FactSet",
            "facts": [
                {
                    "$data": "${properties}",
                    "title": "${key}:",
                    "value": "${value}"
                }
            ]
        }`

Data:
`    "properties": [
        {
            "key": "Board",
            "value": "Adaptive Cards"
        },
        {
            "key": "List",
            "value": "Backlog"
        },
        {
            "key": "Assigned to",
            "value": "Matt Hidinger"
        },
        {
            "key": "Due date",
            "value": "Not set"
        }
    ]`

But the displayed card just shows ${key}: ${value} in the FactSet. This happens in all selected host apps.
![adaptive-card-designer](https://user-images.githubusercontent.com/47112439/142466783-94c69195-246a-4c6a-bfb5-6256e8ebd3c3.png)

In other places, this sample card displays each of these properties separately as intended, such as on the [Samples page](https://adaptivecards.io/samples/).

**Comment by jonmill** [comment]
@teamstap100 - looks like you aren't in Preview Mode but are instead in Design Mode. To get the data to show up, please click the `Preview` button next to the `Host App Docs` button and everything should work :)
