### ISSUE TITLE
Trigger phone calls from adaptive cards

### ISSUE THREAD

**Issue by wujasmine** [microsoft/AdaptiveCards#6761]
Hi! How can we trigger phone calls from adaptive cards?

<img width="546" alt="Screen Shot 2021-11-19 at 3 34 58 PM" src="https://user-images.githubusercontent.com/12118798/142704259-9187dc8a-552b-413e-9317-b631ae607a73.png">

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4662
