### ISSUE TITLE
Standardize API functionality

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#677]
# Implementation status
- [ ] TypeScript
- [ ] UWP
- [ ] iOS
- [ ] Android
- [ ] .NET
- [X] [Spec / Documentation](https://github.com/Microsoft/AdaptiveCards/blob/master/samples/APISpec.md)

## Major callouts

* Click the spec link for full details. Please ensure your APIs match this general pattern
* No more action events or any other behavior on the `Renderer` class, It's only job is rendering cards.
* The `myRenderer.RenderCard()` methods returns a `RenderedAdaptiveCard` object
   * This object contains all the behavior associated with a rendered card: wiring up action events, including gathering input data, accessing the UI tree, etc
* Input-gathering is provided as a stand-alone API and standardized response format. See #652 for the input response spec.
* `Action.Submit` changes to match the schema
   * The `data` property was moved onto the `SubmitAction` versus the action. It also must be declared as a "JObject" on each respective platform. The schema allows either a string or object in the `data` property, so hosts need to be able to read it appropriately.
   * Inputs and `data` and now separate API calls. The host **can** merge them together if they see fit. E..g, Bot Framework clients will merge them.

**Comment by andrewleader** [comment]
Closing as stale and likely not going to make API changes at this stage
