### ISSUE TITLE
[Rendering] Adaptive Card Image Not opening for the First time

### ISSUE THREAD

**Issue by shivajipotnuru** [microsoft/AdaptiveCards#6770]
### Target Platforms

Other

### SDK Version

1.2

### Application Name

Microsoft Teams

### Problem Description

I'm Sending an Adaptive Image over the Adaptive Card
- Our Images are stored in Azure Blob Storage(Hot access)
- Image Size is Less than 1 Mb
- Before initializing the Adaptive Card we sent Images using Attachment

The issue is once the user clicks on the enlarge option on the adaptive card bot is not responding, the user has to go to another chat/app again come back and click on the adaptive card.

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "type": "Image",
            "msTeams": {
                "allowExpand": true
            },
            "horizontalAlignment": "Center",
            "spacing": "Padding",
            "url": ""
        }
    ]
}
```

### Sample Code Language

C#

### Sample Code

 public  static Attachment ImageCard(string pathURL)
        {
            var imageCard = new AdaptiveCard("1.5");

            var msteamsProp = new MsTeamsObject()
            {
                AllowExpand = true
            };
            SerializableDictionary<string, object> msteams = new SerializableDictionary<string, object>();
            msteams.Add("msteams", msteamsProp);

            imageCard.Body.Add(new AdaptiveImage()
            {
                Url = new Uri(pathURL),

                AdditionalProperties = msteams
            });
            return  new Attachment()
            {
                ContentType = AdaptiveCard.ContentType,
                Content = imageCard
            };
        }

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4736
