### ISSUE TITLE
Enable accessibility in Teams bot: Reading the Task Module and Guidance to close the module

### ISSUE THREAD

**Issue by prajwalmanju** [microsoft/AdaptiveCards#6775]
### Target Application

Microsoft Teams

### Application Operating System

Windows

### Schema Version

NA

### Problem Description

When a keyboard and screen reader user clicks "Read More" to view an article, the screen reader does not automatically read the contents of the pop-up where the article and its content can be viewed. There is also no option for a keyboard user to hover over the pop up nor its contents and he can only navigate the Teams interface in the background. Hence, there is no way for the article content to be read by a screen reader, nor is it easy for someone to get rid of the pop up as a keyboard user after reading.

### Expected Outcome

Pop up Cards like the Knowledge Management article details should Understood by Screen reader.

### Actual Outcome

Pop up Cards like the Knowledge Management article details Not Understood by Screen reader.

### Card JSON

```JSON
NA
```

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4734
