### ISSUE TITLE
List card does not have speech support.

### ISSUE THREAD

**Issue by prajwalmanju** [microsoft/AdaptiveCards#6776]
### Target Application

Microsoft Teams

### Application Operating System

Windows

### Schema Version

v1.2

### Problem Description

List card as a new message will be read as “message from Una, undefined.” But if one hovers over the list view, the screen reader will be able to read it.  

### Expected Outcome

Screen reader should read new message card as "message from una bot you received a card message use shift + tab key to read more"

### Actual Outcome

List card as a new message will be read as “message from Una, undefined.”

### Card JSON

```JSON
NA
```

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4733
