### ISSUE TITLE
After clicking on the button, pressing  Tab key few times other cards are selected but not latest one

### ISSUE THREAD

**Issue by prajwalmanju** [microsoft/AdaptiveCards#6778]
### Target Application

Microsoft Teams

### Application Operating System

Windows

### Schema Version

v1.0

### Problem Description

When any feature related button is clicked from any card e.g. Log a case button from view bsc detail card then log a case utterance is triggered followed by its response card is shown. But unable to know where is the control. After pressing  Tab key few times some of the card is selected but not latest one. Only some times it is on recent card or else some of the card it is selected which is on chat screen. It is difficult to know which card it is selected. And for remaining buttons user need to trigger the feature again. Eg. Log a case.
Alt solution: Shift Tab is going the control in reverse order and most of the times the control is selecting the last message(latest message)

### Expected Outcome

when control is coming back from browser screen card focus should be on latest card.

### Actual Outcome

when control is coming back from browser screen, card focus is not on the latest card.

### Card JSON

```JSON
<Adaptive>{
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0",
  "speak": "Of course! I can help you raise a new case or view your existing cases.",
  "body": [
    {
      "type": "TextBlock",
      "text": "Of course! I can help you raise a new case or view your existing cases.",
      "wrap": true
    }
  ],
  "actions": [
    {
      "type": "Action.OpenUrl",
      "title": "Raise a case",
      "url": "sample url"
    },
    {
      "type": "Action.Submit",
      "title": "View cases",
      "data": {
        "msteams": {
          "type": "imBack",
          "value": "View cases"
        }
      }
    },
    
    {
      "type": "Action.Submit",
      "title": "Cancel",
      "data": {
        "msteams": {
          "type": "imBack",
          "value": "Cancel"
        }
      }
    }
  ]
}</Adaptive>
```

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4730
