### ISSUE TITLE
There is no mechanism or voice to the user, when multiple messages are loaded

### ISSUE THREAD

**Issue by prajwalmanju** [microsoft/AdaptiveCards#6782]
### Target Application

Microsoft Teams

### Application Operating System

Windows

### Schema Version

v1.2

### Problem Description

When any response card is having multiple cards, after triggering that feature screen reader is reading first response content/text followed by 'message from Una bot undefined'. But not the case when only one card is shown as response
There is no mechanism or voice to the user there are multiple cards and user need to use arrow or some other keys to select one of the multiple cards

### Expected Outcome

screen reader should inform user regarding the multiple cards and user need to use arrow or some other keys to select one of the multiple cards

### Actual Outcome

screen reader is not informing user regarding the multiple cards.

### Card JSON

```JSON
<msg><Adaptive>{
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.2",
  "body": [
    {
      "type": "TextBlock",
      "text": "Here are the top results I found in Knowledge.",
      "wrap": true
    }
  ]
}</Adaptive></msg>{
  VendorRegistrationCarousel
}<msg><Adaptive>{
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.2",
  "body": [
    {
      "type": "TextBlock",
      "text": "You can also perform an advanced search with filters.",
      "wrap": true
    }
  ],
  "actions": [
    {
      "type": "Action.OpenUrl",
      "title": "Perform advanced search",
      "url": "{AdavanceSearchUrl}"
    }
  ]
}</Adaptive></msg>
```

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4726
