### ISSUE TITLE
Instead of reading new card, screen reader is reading existing card along with new card, when card is updated

### ISSUE THREAD

**Issue by prajwalmanju** [microsoft/AdaptiveCards#6785]
### Target Application

Microsoft Teams

### Application Operating System

Windows

### Schema Version

v1.2

### Problem Description

When any action by user like button click bot is replacing with existing card with a new card. And upon trying to focus new card first the screen reader is reading Existing card and then New card details are pronounced. Eg. Unilever dictionary, Adaptive card cancel response

### Expected Outcome

when any card replacing with existing card with a new card. upon focusing on the updated card screen reader should read only updated card instead of previous card along with updated card.

### Actual Outcome

when any card replacing with existing card with a new card. upon focusing on the updated card screen reader is start reading previous card along with updated card.

### Card JSON

```JSON
NA
```

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4723
