### ISSUE TITLE
Adaptive Card -media player is not supporting,unable to hear voice in IPhone Safari/chrome browser

### ISSUE THREAD

**Issue by amoyalan20** [microsoft/AdaptiveCards#6788]
### Target Platforms

iOS

### SDK Version

latest version

### Application Name

webchat

### Problem Description

Hi could you please help me out if there any known issues in IOS Safari browser while playing a audio using adaptive card media url inside a chatbot(bot framework v4). I am not able to hear the voice while playing audio in IOS safari.

### Card JSON

```JSON
{
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "Media",
      "sources": [
        {
          "mimeType": "audio/mpeg",
          "url": "https:..."
        }
      ]
    }
  ]
}
```

### Sample Code

```javascript
var pronunciationPlayBack = new AdaptiveMedia()
{
Type = "Media",
Sources = new List()
{
new AdaptiveMediaSource()
{
Url = pronunciationUrl,
MimeType = "audio/mpeg"
}
                            }
                        };
```

**Comment by paulcam206** [comment]
I'm not aware of any specific issues with the `Media` element on iOS in Safari or Chrome. Do you get playback controls when the card is rendered?

**Comment by amoyalan20** [comment]
Hi Paul, we have the play and pause control, but don't have the control for volume.
Also there is no voice even if play the audio. Its perfectly working in android and windows. 
![image](https://user-images.githubusercontent.com/73281779/143992188-9c554a1f-1e42-4134-ace8-ad5be674d3fb.png)

**Comment by amoyalan20** [comment]
Any updates on this issue?

**Comment by Nivedipa-MSFT** [comment]
@amoyalan20 - We have tried audio using adaptive card media in Teams desktop client.We get the result that Media playback is currently not supported in Adaptive Cards in Teams and also its documented: https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#support-for-adaptive-cards 
![Screenshot 2021-12-10 140224](https://user-images.githubusercontent.com/92150070/145543054-10d23528-702c-4630-ade7-bb2ea4a36b99.png)

**Comment by amoyalan20** [comment]
we are looking on playing a audio using adaptive card media url inside a chatbot(bot framework v4) not in teams client and media player is working as expected in Ipad, MAC but not able to listen voice in iphone. is there any known limitations?

**Comment by Nivedipa-MSFT** [comment]
@amoyalan20 - Media elements are not supported in Adaptive Card. You can use the Task Module for playing audio. Render the html code for audio playing in Task Module.

**Comment by amoyalan20** [comment]
Thanks confirming the adaptive card media element will not work in teams platform, but we are looking inside the chatbot in webapp.
adaptive card media element not working in iPhone safari/chrome browsers but the same which is working in MAC and in iPad. is there any known limitations for adaptive media element in iPhone?

**Comment by Nivedipa-MSFT** [comment]
Could you please share that how you are using adaptive card media element in MAC and in iPad?

**Comment by Nivedipa-MSFT** [comment]
@amoyalan20 - Could you please share the repro steps?

**Comment by v-chetsh** [comment]
@amoyalan20  -  Could you please share the repro steps that how you are testing Adaptive Card Media in MAC and in iPad?

**Comment by amoyalan20** [comment]
@Nivedipa-MSFT @v-chetsh we have integrated this media adaptive card inside a chatbot(bot framework).
1. Accessed the chatbot, type an user query
2. bot would render media adaptive card
3. the card is not working in iPhone but its working in MAC and iPad.
•	Issue Description: Unable to hear the audio file playback inside Adaptive card of chatbot. Audio control bar shows up, user clicks on play button, the audio plays but no sound is heard. Issue occurs only in IOS Devices. Android mobiles, Desktop, Laptop browsers working fine. 
•	Device with Issue : IOS Mobile devices (Iphone X, Iphone 11plus tested)
•	Browser : Safari/Chrome browsers 
•	Chatbot Details: Bot framework V4 Used
•	Channel with issue : Web

**Comment by Nivedipa-MSFT** [comment]
@amoyalan20 - Could you please share your sample code to check at our end.

**Comment by Nivedipa-MSFT** [comment]
@amoyalan20 - Could you please share your sample code to check at our end.

**Comment by v-chetsh** [comment]
@amoyalan20 - Could you please share the code snippet so that we can check it from our end?

**Comment by amoyalan20** [comment]
@v-chetsh  Below were the sample code:

var pronunciationPlayBack = new AdaptiveMedia()
{
Type = "Media",
Sources = new List()
{
new AdaptiveMediaSource()
{
Url = pronunciationUrl,
MimeType = "audio/mpeg"
}
                            }
                        };

**Comment by v-chetsh** [comment]
@amoyalan20  - We will try it from our end and let you know the updates.

**Comment by amoyalan20** [comment]
@v-chetsh - We are wanting to understand a potential resolution as soon as possible. Thank you.

**Comment by v-chetsh** [comment]
@amoyalan20 - Sure, could you please share the docs which you are following for AdaptiveMedia() ?

**Comment by amoyalan20** [comment]
@v-chetsh - https://adaptivecards.io/explorer/Media.html referred from this link, only the audio part i have implemented.
Thanks for the quick response!!

**Comment by Nivedipa-MSFT** [comment]
@amoyalan20 - Could you please share the test environment to test at our end?

**Comment by amoyalan20** [comment]
@Nivedipa-MSFT  - At this point we are not able to share the test environment since it is integrated with Azure AD Authentication. Kindly let us know, if our test environment is mandatory for you to proceed.

**Comment by Wajeed-msft** [comment]
@jonmill , @paulcam206  - could you please help here for query related to rendering of Adaptive card inside WebChat?

**Comment by amoyalan20** [comment]
@Wajeed-msft  is there any updates?

**Comment by paulcam206** [comment]
> @jonmill Jonathan Miller FTE , @paulcam206 Paul Campbell (DXP) FTE - could you please help here for query related to rendering of Adaptive card inside WebChat?

See [this comment](https://github.com/microsoft/AdaptiveCards/issues/6788#issuecomment-997939225)

**Comment by paulcam206** [comment]
@compulim @benbrown - This looks like this is the same issue as microsoft/BotFramework-WebChat#4088 - can you take a look here?

**Comment by amoyalan20** [comment]
@paulcam206 @compulim  We are wanting to understand a potential resolution as soon as possible. is there any updates on this? Thank you.

**Comment by compulim** [comment]
@paulcam206 could you share any updates on this? Quite a few customers using Web Chat is being blocked by this issue.

We used CodeSandbox to render the card using Adaptive Cards and it repro on Safari. The WAV file is from one of our customers. [The source code](https://codesandbox.io/s/quirky-kalam-35klg) is fairly simple and does not contain anything from Web Chat. We are testing it on iOS 15.

You can visit the sandbox on your iOS device at https://35klg.csb.app/. After clicking on the play button, which appears as trapezium, you will notice the audio is muted by default.

<details>
<summary>Expand to see the code</summary>

> Copied from https://codesandbox.io/s/quirky-kalam-35klg.

```js
import { AdaptiveCard } from "adaptivecards";

const card = new AdaptiveCard();

card.parse({
  $schema: "http://adaptivecards.io/schemas/adaptive-card.json",
  type: "AdaptiveCard",
  version: "1.3",
  body: [
    {
      type: "Media",
      sources: [
        {
          mimeType: "audio/mpeg",
          url: "https://www2.cs.uic.edu/~i101/SoundFiles/BabyElephantWalk60.wav"
        }
      ]
    }
  ]
});

card.render(document.getElementById("app"));
```
<details>

**Comment by jwoo-msft** [comment]
@amoyalan20, 
![image](https://user-images.githubusercontent.com/73281779/144008285-334d428d-27c0-40d6-a2b8-1c748236d032.png)
as @compulim has mentioned, the music is muted. If you click on the compulim's link, you can see that there is a volume control icon and it's muted. The narrower width as shown in the image above caused the volume control to collapsed into '...'. As for why desktop version of safari behaves differently, iOS has been always stricker in media playback. For example, iOS Safari wouldn't support autoplay of media out of box while it will work in the desktop and chrome. You can add a TextBlock to your card to prompt users to unmute. @compulim, perhaps you can add media play icon image that indicate users to unmute via HostConfig.

**Comment by amoyalan20** [comment]
@jwoo-msft We have the same issue in iOS chrome browser also not just in safari.
Also we have checked the '...' in the webchat media player as you mentioned, but it doesn't contain an option to control the volume(mute/unmute).
So adding a text card to prompt users to unmute wont work here in our scenario.
Can you please double check your recommendation and let us know the earliest.
@compulim @jwoo-msft  Thanks for the detailed description!!

**Comment by jwoo-msft** [comment]
@amoyalan20,
There isn't much we can do here. iOS mobile browsers are preventing us from achieving what we want. 
![Screen Shot 2022-01-27 at 11 09 55 AM](https://user-images.githubusercontent.com/4112696/151428646-c672d41b-3b2b-4a0a-8f26-a318c0c47e66.png)
Essentially, the problem is volume control is inaccessible when the width is too narrow. 
![Screen Shot 2022-01-27 at 3 18 49 PM](https://user-images.githubusercontent.com/4112696/151459385-06af233f-c852-48ea-9823-9a1995428229.png)
You have to make sure that width is sufficiently long to display the volume control.
