### ISSUE TITLE
[Rendering] [Android/iOS] Text hyperlink not rendering properly if a url has round brackets.

### ISSUE THREAD

**Issue by karthikgopal36** [microsoft/AdaptiveCards#6797]
### Target Platforms

iOS, Android

### SDK Version

2.8.0

### Application Name

Teams

### Problem Description

If a Url has round brackets the hyperlink text is not properly rendering in Teams Mobile client (Android/iOS). This is working fine in Teams Desktop/Web.

Attached sample payload.

### Screenshots

![139327281-cb6fe3fa-8893-4f45-874e-053f3884cfa4](https://user-images.githubusercontent.com/80986038/144106706-ce03dbc2-6c03-487e-87a4-8f0113f7fd6f.png
![139327387-25188a78-a661-406c-8753-49f38378465a](https://user-images.githubusercontent.com/80986038/144106726-cef9928f-5e46-4816-914b-cf2825f1f970.png)
)

### Card JSON

```JSON
{
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"type": "AdaptiveCard",
"version": "1.2",
"msteams": {
"width": "full"
},
"body": [
{
"type": "TextBlock",
"text": "[Stay tuned to Know more](https://tcscomprod.sharepoint.com/sites(Test).doc?somegarbageValue)",
"wrap": true
}
]
}
```

**Comment by paulcam206** [comment]
fixing this is covered in #1984
