### ISSUE TITLE
IE11 rendering issue

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/AdaptiveCards#680]
Date field is not working well in IE11 but working in Chrome...
![image](https://user-images.githubusercontent.com/2233628/30790434-7d31e990-a1c9-11e7-8aa5-3c06d8878b78.png)

Chrome renders as below
![image](https://user-images.githubusercontent.com/2233628/30791268-f8188cea-a1ce-11e7-9a58-85d720b86bf1.png)

**Comment by matthidinger** [comment]
Duplicate of #519
