### ISSUE TITLE
Adaptive card Action.openURL is not working in custom app(iOS) 

### ISSUE THREAD

**Issue by saranyasivasankaran** [microsoft/AdaptiveCards#6807]
### Target Platforms

iOS

### SDK Version

SDK V4

### Application Name

Custom Application

### Problem Description

I created an adaptive card , in which i have used "Action.openURL" for redirecting URL. This particular adaptive card is working fine in teams and webchat both in iOS and android as well as in the custom app installed in android . I am facing issues particular in the custom application installed in iOS platform. whenever the button clicks the action is not triggered i.e Redirection is not happening.

### Card JSON

```JSON
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "text": "Amadeus Login",
      "weight": "Bolder",
      "color": "Accent"
    }
  ],
  "actions": [
    {
      "type": "Action.OpenUrl",
      "title": "Download",
      "url": " "
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0"
}
```

### Sample Code Language

c#

### Sample Code

private Attachment CreateAdaptiveCardAttachment()
        {
            var adaptiveCard = " ";
            var cardResourcePath = "SASBot.Cards.Amedius.json";            
            using (var stream = GetType().Assembly.GetManifestResourceStream(cardResourcePath))
            {
                using (var reader = new StreamReader(stream))
                {
                    adaptiveCard = reader.ReadToEnd();
                }
            } 
            var card = AdaptiveCard.FromJson(adaptiveCard).Card;
            var action = (card.Actions[0] as AdaptiveOpenUrlAction);
            ServiceNowIntegration si = new ServiceNowIntegration(_config);
            var value = si.kbarticle();
            Uri link = new Uri("https://flysas.service-now.com/sp?id=kb_article&sys_id=" + value);
            action.Url = link;
            var DropdownCard = card.ToJson();

            return new Attachment()
            {
                ContentType = "application/vnd.microsoft.card.adaptive",
                Content = JsonConvert.DeserializeObject(DropdownCard),
            };
        }
    }
}

**Comment by paulcam206** [comment]
What custom application are you using on iOS? If it's your own custom application, have you [registered an action delegate](https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/ios/actions)?

**Comment by paulcam206** [comment]
Closing due to lack of engagement.
