### ISSUE TITLE
MsTeams : Issue in Input.Date Component for Adaptive Cards

### ISSUE THREAD

**Issue by devtfq** [microsoft/AdaptiveCards#6816]
# Platform

*  Web (MsTeams Web http://teams.microsoft.com )
* Ms Teams Desktop Client  1.4.00.29478 (Mac OS Big Sur)

# Issue

I have a simple Adaptive card, with a date picker and an action button. When I select a date in date picker and then click on the button, I should be getting the postback date which was selected.

However, when I select a date, and click the action button, i am geting the postback date as (selected date - 1), that is ; **just a day before the actual selected date.**

**Payload used:** 

[payload.txt](https://github.com/microsoft/AdaptiveCards/files/7666723/payload.txt)

My time zone: Indian Standard Time (IST)

I tried in desktop client in my MacOS , version of the app being  1.4.00.29478, issue exists there.

<img width="534" alt="Screenshot 2021-12-07 at 2 01 35 PM" src="https://user-images.githubusercontent.com/69789507/144994193-49097152-f3c5-4c19-b50b-12a571793932.png">

Even though date selected was 29th November 2021, I got the postback as:
{"date":"2021-11-28","action":"clicked"}

I tried in chrome browser , navigating to teams web (teams.microsoft.com ), and again I am able to see the same issue in Date.

Very strangely, issue in teams web client is **not being seen when tested in Firefox  browser** (78.13.0esr) , **although the date  is coming in a different format and appearance of date picker is also different here.**

<img width="567" alt="Screenshot 2021-12-07 at 2 03 15 PM" src="https://user-images.githubusercontent.com/69789507/144994451-8b0f760b-6a79-438b-a0da-f6bec82a8235.png">

Also, the problem is not being seen whe tested in Ms teams Android app (1416/1.0.0.2021183702/1117).

Please help me to know how I can fix this date picker issue, or if this is an ms teams issue .

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4807

**Comment by devtfq** [comment]
@Wajeed-msft  thank you
