### ISSUE TITLE
Action.OpenUrl results in encoding of # to %23 in the URL

### ISSUE THREAD

**Issue by shoryacr7** [microsoft/AdaptiveCards#6839]
# Platform

What platform is your issue or question related to?

* iOS

# Author 

A bot installed into Microsoft teams, shares an adaptive card into Microsoft Teams channel.

# Version of SDK

1.2

# Issue

The following payload is sent in adaptive card for actions:-  

"actions" : [
&nbsp; {   
&nbsp;&nbsp;"type" : "Action.OpenUrl",  
&nbsp;&nbsp;"title" : "Launch in browser",  
&nbsp;&nbsp;"url" : "https://xyz.com/path?a=b#123"
&nbsp; }  
]

While clicking on "Launch in Browser" button on the adaptive card in the iOS mobile and tab devices , the "#" in URL gets encoded to "%23", as a result of which the website stops working.  The url open as "https://xyz.com/path?a=b%23123". This happens only in iOS and is working correctly in Android, Windows desktop and web version.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4853
