### ISSUE TITLE
How to set themeColor with .NET AdaptiveCards SDK

### ISSUE THREAD

**Issue by soulflyman** [microsoft/AdaptiveCards#6841]
### Discussed in https://github.com/microsoft/AdaptiveCards/discussions/6382

<div type='discussions-op-text'>

<sup>Originally posted by **soulflyman** September 21, 2021</sup>
When sending the following json to a MS Teams Webhook I can change the color bar above the message with the `themeColor` Option:
```json
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "MessageCard",    
    "themeColor": "ff0000",
    "version": "1.2",
    "title": "Alarm!",
    "text": "Test Message" 
}
```

![2021-09-21 17_14_24-Microsoft Teams](https://user-images.githubusercontent.com/379492/134198261-2780dd0a-0a8f-486a-b2bf-67870ae184bb.png)

How is this possible with the .NET AdaptiveCards SDK that ist available via nuget?</div>

**Comment by jonmill** [comment]
Hi @soulflyman - this is a feature specific to Teams and is not an AC feature. Moving over to their repo so they can help provide better guidance

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4854
