### ISSUE TITLE
[Rendering] Crash on teams iOS platform, due to conflicting constraints

### ISSUE THREAD

**Issue by shabripabba** [microsoft/AdaptiveCards#6846]
### Target Platforms

iOS

### SDK Version

2.8.1-beata1

### Application Name

Microsoft Teams

### Problem Description

Microsoft Teams iOS app, now uses a subclass of `ACRImageRenderer` to render element of Type `ACRImage, a constraint conflict causes a crash on Teams app, when a user taps on "Approve" or "Reject" which are of type "Show Card"

showing crash: **[E-AH][AXPApplication sendEvent:] exception occurred : Invalid parameter not satisfying: isfinite(coefficient)**

We essentially did a lot of trial and error to come to the conclusion that `ACRImageRenderer` constraints are the reason why we get the crash, please look at 1st Attachment for the code that is causing the crash, and look at second attachment for the code change that doesn't crash anymore.

The crash log we get: 
[E-AH][AXPApplication sendEvent:] exception occurred : Invalid parameter not satisfying: isfinite(coefficient) 0   CoreFoundation                      0x00007fff203fbbb4 __exceptionPreprocess + 242
1   libobjc.A.dylib                     0x00007fff2019ebe7 objc_exception_throw + 48
2   Foundation                          0x00007fff20750da9 -[NSMutableDictionary(NSMutableDictionary) classForCoder] + 0
3   CoreAutoLayout                      0x00007fff5f7f2943 NSISLinExpReplaceVarWithVar + 616
4   CoreAutoLayout                      0x00007fff5f7e1993 _pivotToMakeColNewHeadOfRow + 649
5   CoreAutoLayout                      0x00007fff5f7e8100 -[NSISEngine removeConstraintWithMarker:] + 661
6   CoreAutoLayout                      0x00007fff5f7fd77a -[NSLayoutConstraint _removeFromEngine:] + 209
7   UIKitCore                           0x00007fff254b73c3 __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 217
8   CoreAutoLayout                      0x00007fff5f7e56b4 -[NSISEngine withBehaviors:performModifications:] + 84
9   UIKitCore                           0x00007fff254b72b9 -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 192
10  UIKitCore                           0x00007fff254b760c __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 203
11  CoreAutoLayout                      0x00007fff5f7e56b4 -[NSISEngine withBehaviors:performModifications:] + 84
12  UIKitCore                           0x00007fff254b751a __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 560
13  CoreAutoLayout                      0x00007fff5f7e56b4 -[NSISEngine withBehaviors:performModifications:] + 84
14  UIKitCore                           0x00007fff254b72b9 -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 192
15  UIKitCore                           0x00007fff254b760c __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 203
16  CoreAutoLayout                      0x00007fff5f7e56b4 -[NSISEngine withBehaviors:performModifications:] + 84
17  UIKitCore                           0x00007fff254b751a __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 560
18  CoreAutoLayout                      0x00007fff5f7e56b4 -[NSISEngine withBehaviors:performModifications:] + 84
19  UIKitCore                           0x00007fff254b72b9 -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 192
20  UIKitCore                           0x00007fff254b760c __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 203
21  CoreAutoLayout                      0x00007fff5f7e56b4 -[NSISEngine withBehaviors:performModifications:] + 84
22  UIKitCore                           0x00007fff254b751a __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 560
23  CoreAutoLayout                      0x00007fff5f7e56b4 -[NSISEngine withBehaviors:performModifications:] + 84
24  UIKitCore                           0x00007fff254b72b9 -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 192
25  UIKitCore                           0x00007fff254b760c __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 203
26  CoreAutoLayout                      0x00007fff5f7e56b4 -[NSISEngine withBehaviors:performModifications:] + 84
27  UIKitCore                           0x00007fff254b751a __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 560
28  CoreAutoLayout                      0x00007fff5f7e56b4 -[NSISEngine withBehaviors:performModifications:] + 84
29  UIKitCore                           0x00007fff254b72b9 -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 192
30  UIKitCore                           0x00007fff254b760c __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 203
31  CoreAutoLayout                      0x00007fff5f7e56b4 -[NSISEngine withBehaviors:performModifications:] + 84
32  UIKitCore                           0x00007fff254b751a __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 560
33  CoreAutoLayout                      0x00007fff5f7e56b4 -[NSISEngine withBehaviors:performModifications:] + 84
34  UIKitCore                           0x00007fff254b72b9 -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 192
35  UIKitCore                           0x00007fff254b760c __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 203
36  CoreAutoLayout                      0x00007fff5f7e56b4 -[NSISEngine withBehaviors:performModifications:] + 84
37  UIKitCore                           0x00007fff254b751a __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 560
38  CoreAutoLayout                      0x00007fff5f7e56b4 -[NSISEngine withBehaviors:performModifications:] + 84
39  UIKitCore                           0x00007fff254b72b9 -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 192
40  UIKitCore                           0x00007fff254b760c __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 203
41  CoreAutoLayout                      0x00007fff5f7e56b4 -[NSISEngine withBehaviors:performModifications:] + 84
42  UIKitCore                           0x00007fff254b751a __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 560
43  CoreAutoLayout                      0x00007fff5f7e56b4 -[NSISEngine withBehaviors:performModifications:] + 84
44  UIKitCore                           0x00007fff254b72b9 -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 192
45  UIKitCore                           0x00007fff254b760c __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 203
46  CoreAutoLayout                      0x00007fff5f7e56b4 -[NSISEngine withBehaviors:performModifications:] + 84
47  UIKitCore                           0x00007fff254b751a __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 560
48  CoreAutoLayout                      0x00007fff5f7e56b4 -[NSISEngine withBehaviors:performModifications:] + 84
49  UIKitCore                           0x00007fff254b72b9 -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 192
50  UIKitCore                           0x00007fff255a6c86 __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 95
51  UIKitCore                           0x00007fff255a6bae -[UIView(Hierarchy) _postMovedFromSuperview:] + 800
52  UIKitCore                           0x00007fff255b687d -[UIView(Internal) _addSubview:positioned:relativeTo:] + 2478
53  UIKitCore                           0x00007fff25491abd -[_UILayoutArrangement insertItem:atIndex:] + 525
54  UIKitCore                           0x00007fff254959ae __50-[_UIOrderedLayoutArrangement insertItem:atIndex:]_block_invoke + 50
55  UIKitCore                           0x00007fff2549567e -[_UIOrderedLayoutArrangement _trackChangesAffectingExternalBaselineConstraints:] + 115
56  UIKitCore                           0x00007fff25495954 -[_UIOrderedLayoutArrangement insertItem:atIndex:] + 479
57  UIKitCore                           0x00007fff25491890 -[_UILayoutArrangement addItem:] + 116
58  UIKitCore                           0x00007fff2549df08 -[UIStackView addArrangedSubview:] + 66
59  TeamSpaceApp                        0x000000010776576d -[TSChatViewController(Cards) configureCardViews:isLeftCell:withMessageInfo:shouldShowSenderName:] + 2253
60  TeamSpaceApp                        0x0000000107be546d -[TSChatViewController configureCell:atIndexPath:withMessageInfo:] + 13181
61  TeamSpaceApp                        0x0000000107bd0965 -[TSChatViewController tableView:cellForRowAtIndexPath:] + 7317
62  UIKitCore                           0x00007fff2526568a -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 1580
63  UIKitCore                           0x00007fff25265c97 -[UITableView _createPreparedCellForRowAtIndexPath:willDisplay:] + 80
64  UIKitCore                           0x00007fff252720a2 -[UITableView _heightForRowAtIndexPath:] + 147
65  UIKitCore                           0x00007fff252863c8 -[UISectionRowData heightForRow:inSection:canGuess:] + 205
66  UIKitCore                           0x00007fff2528b383 -[UITableViewRowData heightForRow:inSection:canGuess:adjustForReorderedRow:] + 214
67  UIKitCore                           0x00007fff2528d106 -[UITableViewRowData rectForRow:inSection:heightCanBeGuessed:] + 383
68  UIKitCore                           0x00007fff2528d283 -[UITableViewRowData rectForGlobalRow:heightCanBeGuessed:] + 117
69  UIKitCore                           0x00007fff2528de17 -[UITableViewRowData globalRowsInRect:canGuess:] + 581
70  UIKitCore                           0x00007fff252903cd -[_UITableViewUpdateSupport _faultInRealHeightsOfNeededElements] + 120
71  UIKitCore                           0x00007fff2529e439 -[_UITableViewUpdateSupport _setupAnimations] + 31
72  UIKitCore                           0x00007fff25230fa6 -[UITableView _updateWithItems:updateSupport:] + 3011
73  UIKitCore                           0x00007fff252283e2 -[UITableView _endCellAnimationsWithContext:] + 16963
74  UIKitCore                           0x00007fff252424d4 -[UITableView endUpdatesWithContext:] + 116
75  UIKitCore                           0x00007fff252426be -[UITableView _performBatchUpdates:withContext:completion:] + 277
76  UIKitCore                           0x00007fff252427b1 -[UITableView performBatchUpdates:completion:] + 109
77  TeamSpaceApp                        0x00000001085a85de -[UITableView(AXP) performUpdates:withCompletion:] + 286
78  TeamSpaceApp                        0x00000001087d7094 __72-[TSBaseMessagingViewController refreshLayoutForCellAtIndex:properties:]_block_invoke_3 + 324
79  UIKitCore                           0x00007fff255af1fe +[UIView(Animation) performWithoutAnimation:] + 84
80  TeamSpaceApp                        0x00000001087d6a52 __72-[TSBaseMessagingViewController refreshLayoutForCellAtIndex:properties:]_block_invoke_2 + 658
81  TeamSpaceApp                        0x0000000107ab9456 -[TSArrayTableViewController pinIndexPath:forTableUpdate:] + 902
82  TeamSpaceApp                        0x00000001087d671f __72-[TSBaseMessagingViewController refreshLayoutForCellAtIndex:properties:]_block_invoke + 367
83  TeamSpaceApp                        0x0000000107ab8877 __42-[TSArrayTableViewController updateTable:]_block_invoke + 119
84  TeamSpaceApp                        0x000000010cee80ec +[TSDispatchUtilities dispatchOnMainThread:] + 108
85  TeamSpaceApp                        0x0000000107ab879a -[TSArrayTableViewController updateTable:] + 186
86  TeamSpaceApp                        0x00000001087d651d -[TSBaseMessagingViewController refreshLayoutForCellAtIndex:properties:] + 333
87  TeamSpaceApp                        0x00000001074e456d -[TSCAdaptiveCardsActionHandler refreshACRCellLayout:] + 285
88  TeamSpaceApp                        0x00000001074e7fb6 -[TSCAdaptiveCardsActionHandler didFetchUserResponses:action:] + 726
89  AdaptiveCards                       0x00000001203d72d7 -[ACRShowCardTarget toggleVisibilityOfShowCard] + 1710
90  UIKitCore                           0x00007fff25002189 -[UIApplication sendAction:to:from:forEvent:] + 83
91  UIKitCore                           0x00007fff2489b573 -[UIControl sendAction:to:forEvent:] + 110
92  UIKitCore                           0x00007fff2489b955 -[UIControl _sendActionsForEvents:withEvent:] + 332
93  UIKitCore                           0x00007fff24897e8c -[UIButton _sendActionsForEvents:withEvent:] + 148
94  UIKitCore                           0x00007fff2489a206 -[UIControl touchesEnded:withEvent:] + 488
95  UIKitCore                           0x00007fff24acab5a _UIGestureEnvironmentUpdate + 9184
96  UIKitCore                           0x00007fff24ac82f2 -[UIGestureEnvironment _updateForEvent:window:] + 902
97  UIKitCore                           0x00007fff250449c9 -[UIWindow sendEvent:] + 5273
98  UIKitCore                           0x00007fff2501b4e8 -[UIApplication sendEvent:] + 825
99  TeamSpaceApp                        0x0000000107935fd6 -[AXPApplication sendEvent:] + 86
100 UIKitCore                           0x00007fff250b128a __dispatchPreprocessedEventFromEventQueue + 8695
101 UIKitCore                           0x00007fff250b3a10 __processEventQueue + 8579
102 UIKitCore                           0x00007fff250aa1b6 __eventFetcherSourceCallback + 240
103 CoreFoundation                      0x00007fff20369e25 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
104 CoreFoundation                      0x00007fff20369d1d __CFRunLoopDoSource0 + 180
105 CoreFoundation                      0x00007fff203691f2 __CFRunLoopDoSources0 + 242
106 CoreFoundation                      0x00007fff20363951 __CFRunLoopRun + 875
107 CoreFoundation                      0x00007fff20363103 CFRunLoopRunSpecific + 567
108 GraphicsServices                    0x00007fff2c851cd3 GSEventRunModal + 139
109 UIKitCore                           0x00007fff24ffbe63 -[UIApplication _run] + 928
110 UIKitCore                           0x00007fff25000a53 UIApplicationMain + 101
111 TeamSpaceApp                        0x000000010fcdad7f Intune_UIApplicationMain + 194
112 TeamSpaceApp                        0x000000010793059f AXPApplicationMain + 63
113 TeamSpaceApp                        0x000000010861414b main + 459
114 dyld                                0x000000011fbd8e1e start_sim + 10
115 ???                                 0x0000000000000001 0x0 + 1 AXPApplication:873

Reason of crash -: "Invalid parameter not satisfying: isfinite(coefficient)" exception

### Screenshots

<img width="1896" alt="Crash" src="https://user-images.githubusercontent.com/87400370/145863820-39049f52-5a4e-4be4-95be-94884ffe8041.png">
<img width="1896" alt="NoCrash" src="https://user-images.githubusercontent.com/87400370/145864050-1d080c04-fc8b-423e-adff-809b7b0a6b63.png">

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
      {
        "height": "auto",
        "type": "Image",
        "url": "https://urlp.asm.skype.com/v1/url/content?url=https%3a%2f%2faka.ms%2fapprovals-logo",
        "altText": "Power Automate approvals logo"
      },
      {
        "size": "large",
        "weight": "bolder",
        "type": "TextBlock",
        "text": "Review new SharePoint file 'AppInstallViewData.json'"
      },
      {
        "type": "TextBlock",
        "text": "Requested by Sagar Pant <Pant.Sagar@microsoft.com>",
        "wrap": true
      },
      {
        "facts": [
          {
            "title": "Date Created",
            "value": "{{DATE(2021-11-26T11:50:05Z, LONG)}} {{TIME(2021-11-26T11:50:05Z)}}"
          },
          {
            "title": "Link",
            "value": "[AppInstallViewData.json](https://microsoftapc.sharepoint.com/teams/Testteam2182/Shared%20Documents/AppInstallViewData.json)"
          }
        ],
        "type": "FactSet"
      },
      {
        "wrap": true,
        "id": "ApprovalDetailsSection",
        "type": "TextBlock",
        "text": "- **Added to:** Shared Documents/\n- **Created by:**  Sagar Pant <Pant.Sagar@microsoft.com>\n- **Created time (UTC):**  2021-11-26T11:49:29Z"
      },
      {
        "actions": [
          {
            "title": "Approve",
            "card": {
              "body": [
                {
                  "type": "TextBlock",
                  "text": "Comments",
                  "wrap": true
                },
                {
                  "id": "comments1",
                  "placeholder": "Enter comments",
                  "type": "Input.Text",
                  "isMultiline": true,
                  "maxLength": 2048
                }
              ],
              "type": "AdaptiveCard",
              "actions": [
                {
                  "title": "Submit",
                  "data": {
                    "OnBehalfOfNotice": "Requested by Sagar Pant <Pant.Sagar@microsoft.com>",
                    "ApprovalName": "53243a00-68e8-42c0-87bd-5964e9d322c9",
                    "SelectedOption": "Approve",
                    "Options": [
                      "Approve",
                      "Reject"
                    ],
                    "MessageTitle": "Review new SharePoint file 'AppInstallViewData.json'",
                    "ApprovalTitle": "Review new SharePoint file 'AppInstallViewData.json'",
                    "ApprovalLink": "https://flow.microsoft.com/manage/environments/839eace6-59ab-4243-97ec-a5b8fcc104e4/approvals/received/53243a00-68e8-42c0-87bd-5964e9d322c9?loginTenant=72f988bf-86f1-41af-91ab-2d7cd011db47",
                    "ItemLinkDescription": "AppInstallViewData.json",
                    "Details": "- **Added to:** Shared Documents/\n- **Created by:**  Sagar Pant <Pant.Sagar@microsoft.com>\n- **Created time (UTC):**  2021-11-26T11:49:29Z",
                    "Environment": "839eace6-59ab-4243-97ec-a5b8fcc104e4",
                    "CreatorName": "Sagar Pant",
                    "CreationTime": "\"Friday, 26 November 2021 11:50 GMT\"",
                    "ActionType": 1,
                    "CreatorEmail": "Pant.Sagar@microsoft.com",
                    "ItemLink": "https://microsoftapc.sharepoint.com/teams/Testteam2182/Shared%20Documents/AppInstallViewData.json"
                  },
                  "type": "Action.Submit"
                }
              ],
              "version": "1.0"
            },
            "type": "Action.ShowCard"
          },
          {
            "title": "Reject",
            "card": {
              "body": [
                {
                  "type": "TextBlock",
                  "text": "Comments",
                  "wrap": true
                },
                {
                  "id": "comments2",
                  "placeholder": "Enter comments",
                  "type": "Input.Text",
                  "isMultiline": true,
                  "maxLength": 2048
                }
              ],
              "type": "AdaptiveCard",
              "actions": [
                {
                  "title": "Submit",
                  "data": {
                    "OnBehalfOfNotice": "Requested by Sagar Pant <Pant.Sagar@microsoft.com>",
                    "ApprovalName": "53243a00-68e8-42c0-87bd-5964e9d322c9",
                    "SelectedOption": "Reject",
                    "Options": [
                      "Approve",
                      "Reject"
                    ],
                    "MessageTitle": "Review new SharePoint file 'AppInstallViewData.json'",
                    "ApprovalTitle": "Review new SharePoint file 'AppInstallViewData.json'",
                    "ApprovalLink": "https://flow.microsoft.com/manage/environments/839eace6-59ab-4243-97ec-a5b8fcc104e4/approvals/received/53243a00-68e8-42c0-87bd-5964e9d322c9?loginTenant=72f988bf-86f1-41af-91ab-2d7cd011db47",
                    "ItemLinkDescription": "AppInstallViewData.json",
                    "Details": "- **Added to:** Shared Documents/\n- **Created by:**  Sagar Pant <Pant.Sagar@microsoft.com>\n- **Created time (UTC):**  2021-11-26T11:49:29Z",
                    "Environment": "839eace6-59ab-4243-97ec-a5b8fcc104e4",
                    "CreatorName": "Sagar Pant",
                    "CreationTime": "\"Friday, 26 November 2021 11:50 GMT\"",
                    "ActionType": 1,
                    "CreatorEmail": "Pant.Sagar@microsoft.com",
                    "ItemLink": "https://microsoftapc.sharepoint.com/teams/Testteam2182/Shared%20Documents/AppInstallViewData.json"
                  },
                  "type": "Action.Submit"
                }
              ],
              "version": "1.0"
            },
            "type": "Action.ShowCard"
          }
        ],
        "type": "ActionSet"
      }
    ]
  }
```

**Comment by jonmill** [comment]
@shabripabba - interesting bug report! It looks like you've identified the line causing the crash...would you be able to open a PR with the fix?

**Comment by jonmill** [comment]
@jwoo-msft - FYI
