### ISSUE TITLE
[Templating] Adaptive card templating is not working for Boolean fields like wrap, isVisible, Same happening with .net core SDK

### ISSUE THREAD

**Issue by SubbaReddi** [microsoft/AdaptiveCards#6854]
Adaptive card templating for boolean fields like wrap, IsVisible is not working.

**Comment by SubbaReddi** [comment]
In Dotnet core, boolean value(false) is replacing with **F**alse and JSON parsing is failing because of that.

**Comment by jonmill** [comment]
Great find - thank you! We'll look into this

**Comment by jwoo-msft** [comment]
@SubbaReddi 
Can you post your template and data?
So I can repro?

**Comment by SowmyaVelugoti** [comment]
Facing the same issue. Any update on the fix here please? 

Sample template:
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "text": "Title is ${title != ''}"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5"
}

Sample Data:
"title": ""

Output is coming as "Title is **F**alse" instead of "Title is **f**alse"

**Comment by theentropic** [comment]
This has been broken for a while now, downgrading to 1.2.1 of AdaptiveCards.Templating seems to fix the problem.  Is there any idea of when this will be fixed so we can stay up to date with the newest features?
