### ISSUE TITLE
[Rendering] Time taken to render same adaptive card JSON first time is more than subsequent times to render same json

### ISSUE THREAD

**Issue by atishayv** [microsoft/AdaptiveCards#6856]
### Target Platforms

NodeJS

### SDK Version

2.9.0

### Application Name

Microsoft Enterprise Search

### Problem Description

In search application, we render almost 15 results when searching for a keyword. All these 15 results are adaptive card. Mostly all of these 15 results are same AC json with different data binding. 
The issue is that the time taken to render the first adaptive card result is a lot more than rendering the same ac json again.

I have tried to reproduce the same issue here : 
https://codepen.io/atishayv/pen/mdBBpMw
In the above code pen example, I am rendering the same ac json twice and measuring the time taken to render it
![image](https://user-images.githubusercontent.com/13940020/147212329-f47a98b8-d106-4e50-ab8f-f77fc8728956.png)

In the screenshot shown, it took 12.8ms to render the ac json first time and around 3.47ms the second time onwards.

I have 2 issue to report here:
1) Why does it takes almost 4 times(400% increase in time) the time to render the ac json first time than second time and onwards. Is there any optimisation we can do to make the first time render faster ?
2) Also when comparing the time taken to render the similar card though react component is much faster than the ac json. Can we optimise the rendering time of ac json ?

### Card JSON

```JSON
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "text": "Your registration is almost complete",
      "size": "medium",
      "weight": "bolder",
      "wrap": true
    },
    {
      "type": "TextBlock",
      "text": "What type of food do you prefer?",
      "wrap": true
    },
    {
      "type": "ImageSet",
      "imageSize": "medium",
      "images": [
        {
          "type": "Image",
          "url": "https://contososcubademo.azurewebsites.net/assets/steak.jpg",
          "altText": "Steak cut with fries"
        },
        {
          "type": "Image",
          "url": "https://contososcubademo.azurewebsites.net/assets/chicken.jpg",
          "altText": "Fried chicken with lettuce"
        },
        {
          "type": "Image",
          "url": "https://contososcubademo.azurewebsites.net/assets/tofu.jpg",
          "altText": "Tofu topped with red sauce"
        }
      ]
    }
  ],
  "actions": [
    {
      "type": "Action.ShowCard",
      "title": "Steak",
      "card": {
        "type": "AdaptiveCard",
        "body": [
          {
            "type": "TextBlock",
            "text": "How would you like your steak prepared?",
            "size": "medium",
            "wrap": true
          },
          {
            "type": "Input.ChoiceSet",
            "id": "SteakTemp",
            "style": "expanded",
            "choices": [
              {
                "title": "Rare",
                "value": "rare"
              },
              {
                "title": "Medium-Rare",
                "value": "medium-rare"
              },
              {
                "title": "Well-done",
                "value": "well-done"
              }
            ]
          },
          {
            "type": "Input.Text",
            "id": "SteakOther",
            "isMultiline": true,
            "placeholder": "Any other preparation requests?"
          }
        ],
        "actions": [
          {
            "type": "Action.Submit",
            "title": "OK",
            "data": {
              "FoodChoice": "Steak"
            }
          }
        ]
      }
    },
    {
      "type": "Action.ShowCard",
      "title": "Chicken",
      "card": {
        "type": "AdaptiveCard",
        "body": [
          {
            "type": "TextBlock",
            "text": "Do you have any allergies?",
            "size": "medium",
            "wrap": true
          },
          {
            "type": "Input.ChoiceSet",
            "id": "ChickenAllergy",
            "style": "expanded",
            "isMultiSelect": true,
            "choices": [
              {
                "title": "I'm allergic to peanuts",
                "value": "peanut"
              }
            ]
          },
          {
            "type": "Input.Text",
            "id": "ChickenOther",
            "isMultiline": true,
            "placeholder": "Any other preparation requests?"
          }
        ],
        "actions": [
          {
            "type": "Action.Submit",
            "title": "OK",
            "data": {
              "FoodChoice": "Chicken"
            }
          }
        ]
      }
    },
    {
      "type": "Action.ShowCard",
      "title": "Tofu",
      "card": {
        "type": "AdaptiveCard",
        "body": [
          {
            "type": "TextBlock",
            "text": "Would you like it prepared vegan?",
            "size": "medium",
            "wrap": true
          },
          {
            "type": "Input.Toggle",
            "id": "Vegetarian",
            "title": "Please prepare it vegan",
            "valueOn": "vegan",
            "valueOff": "notVegan"
          },
          {
            "type": "Input.Text",
            "id": "VegOther",
            "isMultiline": true,
            "placeholder": "Any other preparation requests?"
          }
        ],
        "actions": [
          {
            "type": "Action.Submit",
            "title": "OK",
            "data": {
              "FoodChoice": "Vegetarian"
            }
          }
        ]
      }
    }
  ]
}
```

### Sample Code Language

JS

### Sample Code

Code can be found here
https://codepen.io/atishayv/pen/mdBBpMw

**Comment by atishayv** [comment]
CC : @dclaux , @matthidinger , @jonmill

**Comment by dclaux** [comment]
@atishayv

Re 1: There is nothing the SDK does differently the first time vs subsequent times. What you're seeing is in all likelihood an HTML/JS optimization happening in the underlying framework, which we have no control over. It would be interesting to push this test a bit further: after rendering this card twice, render another, significantly different card twice. IMO you'll observe either of the following two things:
- The first rendering of the second card is also going to be significantly slower than the second rendering
  - If that's what you see, the optimization likely happens as the JSON is parsed
- Or the first and second rendering will take just as much time
- If that's what you're seeing (and I have a feeling that's what you'll see) the optimization is likely that the AC SDK code is compiled just-in-time the first time it's used

Re 2: What React component are you referring to, and what are the numbers you are seeing.

**Comment by atishayv** [comment]
@dclaux 
Re 1: I have updated the pen to log both parse and render time and also added code to render a different card 2nd time
https://codepen.io/atishayv/pen/mdBBpMw

As you can see in the screenshot below
![image](https://user-images.githubusercontent.com/13940020/147533685-63b11558-ef9b-413f-b99e-10bba0683ec1.png)

--> The time taken to render the first card is greater than the parsing time.
--> Also, the first rendering of the second card is significantly slower than the second rendering.

I am not sure whats happening in the underlying framework and why the second card rendering is slower.

Re 2: Sorry for the confusion here. What I was trying to convey here is that if I try to render the same amount of content(similar looking html) with React components without using adaptive card, the time taken is lesser. I am not sure if thats a valid comparison to do but there might be some optimisation needed to make ac framework also render fast?

**Comment by dclaux** [comment]
It is normal that the first parse of the first card is slower than the second. When the SDK parses a specific element type for the first time, it dynamically builds it schema and caches it. That schema building step will take additional time. I would say it's also not surprising that the first parse of the second card is slower than the second parse, because the second card uses Action.ShowCard which the first card doesn't, and thus the schema for Action.ShowCard is not yet cached.

I however do not understand why rendering is slower the first time.  I would understand it if you were re-rendering the same AdaptiveCard instance, but you're actually creating a new instance every time.

**Comment by jonmill** [comment]
Thanks for the investigation here - based on the data, the slowest render is 12ms which is well inside the acceptable range for UI interaction. Is there a particular issue with the 12ms time? This doesn't seem like an issue that we would prioritize at this point given the rendering is still within the normal range for UI framework rendering

**Comment by jonmill** [comment]
Closing due to above comment - but let's please continue the discussion here if necessary
