### ISSUE TITLE
How to reply to thread by using the return of send_stream_request() ?

### ISSUE THREAD

**Issue by Karl-luyi** [microsoft/AdaptiveCards#6860]
Here is the send_stream_request()

-----------------------------------------
class BotPlugin(BotPluginBase):
    def send_stream_request(
        self,
        user: Identifier,
        fsource: IOBase,
        name: str = None,
        size: int = None,
        stream_type: str = None,
    ):
        """
        Sends asynchronously a stream/file to a user.

        :param user: is the identifier of the person you want to send it to.
        :param fsource: is a file object you want to send.
        :param name: is an optional filename for it.
        :param size: is optional and is the espected size for it.
        :param stream_type: is optional for the mime_type of the content.

        It will return a Stream object on which you can monitor the progress of it.
        """
        return self._bot.send_stream_request(user, fsource, name, size, stream_type)

**Comment by Karl-luyi** [comment]
I want to reply to thread with the file which got via send_stream_request().

**Comment by jonmill** [comment]
This looks to be an issue for the Bot Framework, not Adaptive Cards. Please re-open this on the [Bot Framework SDK repo](https://github.com/Microsoft/botframework-sdk)
