### ISSUE TITLE
[Feature Request] Can we get native MAUI support?

### ISSUE THREAD

**Issue by pooranoayaw** [microsoft/AdaptiveCards#6861]
### Problem Statement

We have skipped Xamarin.Forms completely, though we have native iOS and Android libraries and React components for Adaptive Cards. Enterprise Xamarin.Forms applications could not use it at all

### Proposed solution

As MAUI is planned for 2022 Q2. Please plan for full native MAUI support?

**Comment by jonmill** [comment]
Dupe of #3255
