### ISSUE TITLE
Custom Adoptive card is not loading in the other users email except the flow creator's email

### ISSUE THREAD

**Issue by mmusthaque** [microsoft/AdaptiveCards#6876]
### Target Platforms

Other

### SDK Version

1.2

### Application Name

Microsoft Outlook

### Problem Description

I have created a custom adoptive card for Microsoft Flow approval. Its working in the flow creator's email. But not working in the others email. Relevant attachments are attached in the form. Please see that. Creator's email comes as "SRM_TEST@___" like this.
I have tried using different versions as well. Still same.

### Screenshots

![responder email](https://user-images.githubusercontent.com/97453037/148779416-224785a6-e2c1-4910-91f6-7fa02af63afb.png)
![creator email](https://user-images.githubusercontent.com/97453037/148779422-dad7710d-3535-4a1b-83d8-ad7fe6ba8e02.png)

### Card JSON

```JSON
"type": "AdaptiveCard",
  "version": "1.2",
  "body": [
    {
      "altText": "Power Automate approvals logo",
      "url": "https://aka.ms/approvals-logo",
      "type": "Image"
    },
    {
      "size": "Large",
      "text": "Action is already performed by another user.",
      "weight": "Bolder",
      "type": "TextBlock"
    },
    {
      "facts": [
        {
          "title": "User ID:",
          "value": "Sooae Cho"
        },
        {
          "title": "User Email:",
          "value": "sooae.cho@imi-ksa.com"
        },
        {
          "title": "Remark:",
          "value": "Approve by Sooae"
        },
        {
          "title": "Date Submitted:",
          "value": "11/24/2021 12:00 PM"
        }
      ],
      "type": "FactSet"
    },
    {
      "items": [
        {
          "size": "Small",
          "text": "Get the Power Automate app to receive push notifications and grant approvals from anywhere. [Learn more](https://flow.microsoft.com). This message was created by a flow in Power Automate. Do not reply. Microsoft Corporation 2020.",
          "weight": "Lighter",
          "wrap": true,
          "type": "TextBlock"
        }
      ],
      "separator": true,
      "type": "Container"
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "fallbackText": "This card requires Adaptive Cards v1.2 support to be rendered properly."
}
```

**Comment by paulcam206** [comment]
This looks to be an issue with Outlook Actionable Messages. Please [follow up](https://docs.microsoft.com/outlook/actionable-messages/#submit-feedback) with them to get your issue resolved.
