### ISSUE TITLE
[MS Teams] [Adaptive Cards] Adaptive Card meaning full text sentence are breaking into unreadable format. 

### ISSUE THREAD

**Issue by rajeeshmenoth** [microsoft/AdaptiveCards#6881]
## Platform
* Web ( MsTeams Web http://teams.microsoft.com )
* Microsoft Teams Version 1.4.00.32771 (64-bit). It was last updated on 12/15/2021.

### Programing Language
* C#
### Channel
* MS Teams
### Adaptive Card Version
1.2
## Issue

The following screenshot breakdown the proper sentence into unreadable format like "Personal" it showing as "Per" in the first line and then remaining words are showing in the next line. Is there any solution for this issue ?

![image](https://user-images.githubusercontent.com/8437883/148897307-e96b1c0b-5e07-4324-8384-fd66d3a3f73b.png)

### C# Code
`
public static Attachment DisplayFAQResponse(string buttonTitleForImage,string FaqMessage, string FaqAnswer, string RequestId = null, List<ImageUrl>ImageUrl= null )
        {
            var faqResponseCard = new AdaptiveCard("1.2");

            var msteamsProp = new MsTeamsObject()
            {
                Width = "Full",
                Wrap = true,
            };
            SerializableDictionary<string, object> msteams = new SerializableDictionary<string, object>();

            msteams.Add("msteams", msteamsProp);

            faqResponseCard.AdditionalProperties = msteams;

            faqResponseCard.Body.Add(new AdaptiveTextBlock()
            {
                AdditionalProperties = msteams,
                Text = FaqMessage,
                Separator = true,
                Spacing = AdaptiveSpacing.ExtraLarge,
                Wrap = true
            });

            faqResponseCard.Body.Add(new AdaptiveTextBlock()
            {
                AdditionalProperties = msteams,
                Text = FaqAnswer,
                Spacing = AdaptiveSpacing.Default,
                Wrap = true,
                Separator = true
            });
            
            

            return new Attachment()
            {
                ContentType = AdaptiveCard.ContentType,
                Content = faqResponseCard
            };
        }`

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/5003
