### ISSUE TITLE
[Rendering] Markdown Parser not behaving correctly with list items inside links

### ISSUE THREAD

**Issue by snbehar** [microsoft/AdaptiveCards#6883]
# Platform

Cisco WebEx

# Description/Screenshots

The markdown parser for list items inside hyperlinks seems to not behave according to the expectation. This is a special case, since links work fine when there's a space between the "[" and "3."

Eg: 
<img width="400" alt="Screenshot 2022-01-12 at 7 24 30 AM" src="https://user-images.githubusercontent.com/79969931/149050024-3ef1d070-f964-409b-bc7e-ab444325c429.png">

Yields

<img width="523" alt="Screenshot 2022-01-12 at 7 25 04 AM" src="https://user-images.githubusercontent.com/79969931/149050075-70a82f44-4e77-484b-9eb4-be1d78436bd1.png">

# Sample JSON

```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
    {
        "type": "TextBlock",
        "text": "[3. Hello World](https://www.google.com)",
        "wrap": true
    }
    ]
} 
```

**Comment by paulcam206** [comment]
Please reach out to Cisco WebEx [support](https://developer.webex.com/support) for this issue.

**Comment by snbehar** [comment]
@paulcam206 The root cause of this is in the markdown parser where when we call the function ```generateHTMLString()```, a string with an extra <p> tag is generated.
