### ISSUE TITLE
Issue with adaptive card in teams use by Bot

### ISSUE THREAD

**Issue by rohan081296** [microsoft/AdaptiveCards#6884]
### Problem Description

I have created chatbot with bot composer and published it on azure and enabled teams channel too. 

I have used adaptive card in chatbot. When I click on button in adaptive card in teams, it is showing message "Your response was sent to the app".

When I check same with web chat, It is not showing any message like this.

Ideally, I don't want this type of message when click on button in adaptive cards.

### Card JSON

```JSON
{
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"type": "AdaptiveCard",
"version": "1.3",
"body": [
{
"type": "TextBlock",
},
{
"type": "Input.ChoiceSet",
"id": "myChoiceData",
"style": "expanded",
"value": "Product Data",
"placeholder": "Product Data",
"choices": [
{
"title": "Product Data",
"value": "Product Data"
},
{
"title": "Customer Data",
"value": "Customer Data"
},
{
"title": "All/Others",
"value": "All/Others"
}
]
}
],
"actions": [
{
"type": "Action.Submit",
"title": "OK"
}
]
}
```

### Screenshot

![image](https://user-images.githubusercontent.com/96237252/149079106-2196d650-c5ab-4934-82fc-5ce99ed48d84.png)

**Comment by paulcam206** [comment]
This is a BotFramework/WebChat issue, please reopen in their repo: https://github.com/Microsoft/BotFramework-WebChat

**Comment by nameissainani** [comment]
Any solution how we can restrict your response is sent to the app after clicking submit button in the adaptive card in teams.
