### ISSUE TITLE
Aria label for checkbox is not escaped, causing issues with screen readers

### ISSUE THREAD

**Issue by elopezanaya** [microsoft/AdaptiveCards#6888]
https://github.com/microsoft/AdaptiveCards/blob/c05dca84b97bc5d9f388b26aaa3bcbb1a8b30055/source/nodejs/adaptivecards/src/card-elements.ts#L3282-L3284

For checkbox components, at the moment of rendering is assigning the title value into the aria-label tag, this is a problem when the title contains ascii code , because visually the code is being rendered and presented properly, but the screen reader is including the ascii code as part of the description of the element

as example- >

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/981914/149248893-45026c64-37d0-49c2-88ab-5c47f9c65a45.png">

**Comment by paulcam206** [comment]
This is by design -- there's no way for us to know what the card author's intent with `title` is, so we use it as supplied. The recommendation would be to only use readable content in the title.
