### ISSUE TITLE
[Android] Failed to resolve 'io.adaptivecards:adaptivecards-android-arm:0.5.0' 

### ISSUE THREAD

**Issue by girish3** [Microsoft/AdaptiveCards#689]
While adding following line

compile 'io.adaptivecards:adaptivecards-android-arm:0.5.0' 

I am getting failed to resolve the dependency.

And also Readme Doc doesn't mention any maven url to add.

**Comment by nesalang** [comment]
Thanks for the feed back.
Please try this --> compile 'io.adaptivecards:adaptivecards-android-arm:1.0.0'
For more info,
https://search.maven.org/#artifactdetails%7Cio.adaptivecards%7Cadaptivecards-android-arm%7C1.0.0%7Caar

if you click on android package badge in AdaptiveCards' GitHub main page, it will take you to the latest package. 
I will update the read me, sorry for the inconvenience.
