### ISSUE TITLE
[AdaptiveCardTemplate] Issue with accessing array elements

### ISSUE THREAD

**Issue by SowmyaVelugoti** [microsoft/AdaptiveCards#6907]
## Sample AC and data: 
Sample AC:
```JSON
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "${title['1']}"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5"
}
```
Sample data
```JSON
{
 "title" : [
        "Title1",
        "Title2",
        "Title3"
    ]
}
```

## Issue
- Using the https://www.adaptivecards.io/designer/ we are able to retrieve the array element using ${title[**'**1**'**]}
- Whereas the AdaptiveCard dot net templating library is unable to parse this string.  The templating library is able to parse ${title[1]} but not ${title['1']} which is currently supported by the js library.

**Comment by jwoo-msft** [comment]
@SowmyaVelugoti,
This is by design. Please use integer to index into an array.
