### ISSUE TITLE
[Designer] Feedback title here

### ISSUE THREAD

**Issue by mig82** [microsoft/AdaptiveCards#6909]
The designer is brilliant, but I find myself wishing I could somehow bake it into our development cycle. Mainly because I see this is a tool for the designer and the product manager to design the UX, so then the question is how do we save this work, version it and hand it over to the engineers.

At the moment, I'm copying the JSON and taking screenshots to put that into our requirement docs, but I wish I could somehow embed these designs into a larger design of the whole conversation flow.

**Comment by paulcam206** [comment]
Thanks for this suggestion! It's a great idea, and we're looking into something like this. Please feel free to give us more information on what you would want to see here.
