### ISSUE TITLE
[Rendering] Issues with rendering arrays using adaptive card templating

### ISSUE THREAD

**Issue by tvvignesh** [microsoft/AdaptiveCards#6912]
### Target Platforms

Other

### SDK Version

2.10.0

### Application Name

Web chat

### Problem Description

Hi. I am trying to render the choices in a Choiceset by passing an array as a data payload in `v1.3` . I tried different approaches with `$data`, `$index`, etc. and I got an issue where the first element of the array repeats again and again when passing array as data. 

But this does not happen when the data is directly passed in the template.

To illustrate, this is the issue:

**Repeats the first element again and again when passed via data**

![image](https://user-images.githubusercontent.com/1165845/152195865-6a2798fd-a15d-4a46-838a-aca9ffc7593e.png)

**Works when passed directly in the template**

![image](https://user-images.githubusercontent.com/1165845/152195996-34609ea9-696f-4119-978a-da394cb6ec5f.png)

The only difference between the 2 screenshots is that one passes the choiceset data within the template and another via data.

If I am not wrong, both should be leading to the same output for me but that is not the case. I guess this is a bug.

Kindly help. Thanks.

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "version": "1.3",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "${question}",
                    "wrap": true,
                    "fontType": "Default",
                    "size": "Medium",
                    "color": "Dark"
                },
                {
                    "type": "Container",
                    "items": [
                        {
                            "type": "Container",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "$data": "${$root['names']}",
                                    "text": "${$index}.name"
                                }
                            ]
                        },
                        {
                            "type": "Input.ChoiceSet",
                            "$data": [
                                    {"title":"Option 1", "value":"Value 1"},
                                    {"title":"Option 2", "value":"Value 2"},
                                    {"title":"Option 3", "value":"Value 3"}
                            ],
                            "choices": [
                                {
                                    "title": "${title}",
                                    "value": "${value}"
                                }
                            ],
                            "placeholder": "Placeholder text",
                            "style": "expanded",
                            "wrap": true,
                            "id": "mcq-response"
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by tvvignesh** [comment]
**CC:** @paulcam206 @jonmill Tagging you to bring this to your attention since this is blocking us from using one template but multiple data payload elements in our application. Can you please guide me here? Thanks 🙏🏼

**Comment by paulcam206** [comment]
This appears to be working to me:

![image](https://user-images.githubusercontent.com/16614499/152430737-b0f0259d-2fb6-4db7-aac9-f181e2f764dc.png)

Please reactivate with more information if perhaps we're misunderstanding the problem.

Thanks!
