### ISSUE TITLE
[Rendering] Image is not displayed with AWS S3 authorized urls

### ISSUE THREAD

**Issue by xsymg** [microsoft/AdaptiveCards#6919]
### Target Platforms

Other

### SDK Version

@microsoft/teams-js ^1.9.0

### Application Name

Microsoft Teams

### Problem Description

URI of format
`https://big-corporation.s3.amazonaws.com/org/aaa/image123.jpeg?AWSAccessKeyId=123&Signature=123&x-amz-security-token=123 `
is converted to 
`https://big-corporation.s3.amazonaws.com/org/aaa/image123.jpeg?AWSAccessKeyId=123&amp;Signature=123&amp;x-amz-security-token=123` in `href` which is treated by AWS S3 as an invalid link, thus the image is not displayed in adaptive card

### Card JSON

```JSON
{
    type: 'AdaptiveCard',
    '$schema': 'http://adaptivecards.io/schemas/adaptive-card.json',
    version: '1.2',
    body: [
      {
        type: 'Container',
        items: [
          {
            type: 'Image',
            url: 'https://big-corporation.s3.amazonaws.com/org/aaa/image123.jpeg?AWSAccessKeyId=123&Signature=123&x-amz-security-token=123'
          }
        ]
      }
    ]
  }
```

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/5251
