### ISSUE TITLE
[Screen Reader - Adaptive Cards iOS - Home] Voice over is not reading the heading label information for “Available Sample JSONs” heading on “Adaptive Cards” home page. 

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#6999]
https://microsoft.visualstudio.com/OS/_workitems/edit/29040468

**Comment by carlos-zamora** [comment]
This bug was filed on the iOS visualizer, not an adaptive card. That is an internal dev tool. Hence, closing.
