### ISSUE TITLE
[Visual Requirements - Adaptive Cards iOS - V1.0] Luminosity ratio is less than 4.5:1 for “Back” button text on “V1.0” screen of “Adaptive Cards”.

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#7000]
https://microsoft.visualstudio.com/OS/_workitems/edit/29040907

**Comment by carlos-zamora** [comment]
This bug was filed on the iOS visualizer, not an adaptive card. That is an internal dev tool. Hence, closing.
