### ISSUE TITLE
[Screen Reader - Adaptive Cards iOS - V1.0] Voiceover is not reading the position of list items on “Elements” page on “Adaptive Cards” home page. 

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#7001]
https://microsoft.visualstudio.com/OS/_workitems/edit/29041206

**Comment by carlos-zamora** [comment]
This bug was filed on the iOS visualizer, not an adaptive card. That is an internal dev tool. Hence, closing.
