### ISSUE TITLE
[Keyboard Navigation - Adaptive Cards - Save File]: Keyboard focus is getting lost after pressing Esc key to close dialogue which appears after activating the Save File button.

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#7006]
https://microsoft.visualstudio.com/OS/_workitems/edit/31568418

**Comment by jwoo-msft** [comment]
as stated in ADO, it can be closed since the renderer doesn't ship to customer.

**Comment by carlos-zamora** [comment]
As stated above, this issue is filed on the visualizer, which does not ship to the customer.
