### ISSUE TITLE
[Keyboard navigation - Adaptive Cards - Host Config]: Keyboard focus jumps to the Background after activating the Host Config button.

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#7007]
https://microsoft.visualstudio.com/OS/_workitems/edit/31569004

**Comment by jwoo-msft** [comment]
As stated in ADO, can be closed since the renderer is shipping to customer

**Comment by carlos-zamora** [comment]
This issue is filed on the UWP visualizer, which does not ship to the customer. Specifically, the "host config" button is a part of the visualizer and not the rendered adaptive card.
