### ISSUE TITLE
[Keyboard Navigation - Adaptive Cards - Activity Update.Json]: Keyboard focus does not move to the Close button while backward navigation using Shift + Tab key.

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#7008]
https://microsoft.visualstudio.com/OS/_workitems/edit/31569675

**Comment by jwoo-msft** [comment]
could be closed due to xaml render not shipping.

**Comment by carlos-zamora** [comment]
This issue is filed on the UWP visualizer, which does not ship to the customer.
