### ISSUE TITLE
[V1.2-> Scenarios - Expense Report.json]: VoiceOver is announcing unncesseray informartion as 'Misspelt Words Text Field' on 'ER-13052' link under 'ExpenseReport.json' card.

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#7009]
https://microsoft.visualstudio.com/OS/_workitems/edit/35691127

**Comment by paulcam206** [comment]
@jwoo-msft - it looks like this issue is blocking Teams... can you take a look? at first glance, this feels like it might be a bug in VoiceOver, but I don't have your expertise :)

**Comment by vagpt** [comment]
Closing this issue as currently issue is fixed.
