### ISSUE TITLE
[Adaptive Card: Link]: Screen reader is announcing link and button both while keyboard focus lands on actionable item 'Publish adaptive card schema'.

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#7010]
https://microsoft.visualstudio.com/OS/_workitems/edit/36485740

**Comment by jwoo-msft** [comment]
possible invalid test case since it's using unexpanded template for testing

**Comment by PankajBhojwani** [comment]
This is an authoring issue. The text in the TextBlock is a link - "text": "[${Title}](#)" while at the same time there is a "selectAction" put on the same column - "selectAction": {"type": "Action.Submit",...}. 

The link on the text causes a link to be created and the selectAction on the column causes the button to be created. Pick the one to keep, remove the other and the issue will be fixed.
