### ISSUE TITLE
[Schema Explorer- TextBlock]: On resizing the page to 200% link "https://aka.ms/ACTextFeatures" is getting cropped.

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#7014]
https://microsoft.visualstudio.com/OS/_workitems/edit/37791949

**Comment by carlos-zamora** [comment]
We didn't hear back from the accessibility team regarding our concerns.

**Comment by carlos-zamora** [comment]
Of course! After we closed the issue, they reactivated it and responded haha. Here's their response:
> On resizing the page to 200% the two-dimensional horizontal scroll bar is not present and even when user navigate with the tab key between the cells then also the link text is getting cropped this needs to be fixed as user who rely on resize will not be able to see the text, hence reactivating the bug.

**Comment by PankajBhojwani** [comment]
This appears to be a browser issue. The bug repros on Edge version 99.0.1150.39, but no longer repros on Edge version 101.0.1193.0. Resolved the bug on ADO as 'No repro', with the substatus "Not observed in newer build"
