### ISSUE TITLE
UWP doesn't support hostConfig fontWeights

### ISSUE THREAD

**Issue by anbare** [Microsoft/AdaptiveCards#702]
In UWP, the fontWeights specified in hostConfig are completely ignored

```json
  "fontWeights": {
    "lighter": 200,
    "default": 400,
    "bolder": 100
  },
```

The code simply assigns "lighter" = Light and "bolder" = Bold.

Instead the code should take the font weight values from the host config and utilize them

```csharp
FontWeight = new Windows.UI.Text.FontWeight() { Weight = 400 }
```

**Comment by riarenas** [comment]
This was fixed with #681
