### ISSUE TITLE
[Adaptive Card iOS - ChoiceSet.UnclippedText]: Voice over does convey the incorrect role as 'Button' for the radio buttons.

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#7020]
https://microsoft.visualstudio.com/OS/_workitems/edit/37842970

**Comment by vagpt** [comment]
Test scenario is not available in latest build. hence, closing this bug.

Adaptive Card iOS build: Version 1.0 (2.4.0-beta.20220628.3)
