### ISSUE TITLE
[Adaptive Card iOS - RichTextBlock.TextRun.SelectAction]: Voice over focus does not lands separately on each elements under 'RichTextBlock.TextRun.SelectAction'.

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#7023]
https://microsoft.visualstudio.com/OS/_workitems/edit/37845248

**Comment by vagpt** [comment]
Closing this bug as in v1.2, Test Scenario RitchTextBlock.TextRun.SelectAction is not available on latest build.
