### ISSUE TITLE
[v1.5-Tests-ActionModeTestCard.json]: Voice over is conveying incorrect role and name for '...' control.

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#7027]
https://microsoft.visualstudio.com/OS/_workitems/edit/37857281

**Comment by vagpt** [comment]
@jwoo-msft , currently on the below environment VO is announcing the correct role but it is not announcing the name of the (...) as 'More Option' hence reactivating this issue.

https://user-images.githubusercontent.com/95913748/180009976-07c498d3-ae0a-48d3-8402-31111124fa40.mp4

**Comment by jwoo-msft** [comment]
@vagpt 

I'm closing this issue. The payload should not have been available to Sample app since the payloads in test folders. I'm closing this issue since the original issue is fixed and the new issue on the sample card specifically that is removed from the sample app via https://github.com/microsoft/AdaptiveCards/pull/7583

**Comment by vagpt** [comment]
Adding A11yTTValidated tag as per the above comment.
