### ISSUE TITLE
[SampleCard-ExpenseReport; Config-Default]: Screen reader focus order is incorrect when navigate using swipe gestures for Total Expense Amount and its associated value.

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#7029]
https://microsoft.visualstudio.com/OS/_workitems/edit/37986532

**Comment by vagpt** [comment]
This issue is still repro on the below environment, hence activating this issue.

**Test Environment:**
Device: iPhone 11
iOS Version: 15.5
A

Uploading issue is still repro on expences report.MP4…

pp Version: Version 1.0 (2.4.0-beta.20220628.3)

**Comment by vagpt** [comment]
Uploading issue is still repro on expenses  report.

https://user-images.githubusercontent.com/95913748/176647845-bbbeaf01-0df7-4a64-8606-07beb76c0019.MP4

**Comment by vagpt** [comment]
Working fine on the Release 179, hence closing this issue.
