### ISSUE TITLE
[Authoring] $if conditional does not work on text color

### ISSUE THREAD

**Issue by JeanRoca** [microsoft/AdaptiveCards#7040]
### Problem Description

I am unable to switch the text color with an $if conditional. The error I get is 

[Parse] Invalid value "${if(priceChange >= 0, 'good', 'attention')}" for property "color".

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "THIS IS A TEST ${priceChange}",
                    "wrap": true,
                    "color": "${if(priceChange >= 0, 'good', 'attention')}"
                }
            ]
        }
    ]
}




Data.json
{
    "priceChange": 4
}
```

### Screenshot

![image](https://user-images.githubusercontent.com/33772802/153105896-bd19ccab-fcb8-4319-a96a-bb07d56f639c.png)

**Comment by paulcam206** [comment]
of note (per @licanhua) - this appears to work correctly when assigned to the `text` property

**Comment by ankur198** [comment]
Any solution?

**Comment by JeanRoca** [comment]
> Any solution?

Hey @ankur198 ! There is no solution to this problem yet. The only workaround we have ATM is to use the $when conditional to show the card with the appropriate text color.

**Comment by jwoo-msft** [comment]
@ankur198 & @JeanRoca 
Don't be alarmed. This scenarios does work. Designer is needed to be updated for demonstration.
I'm closing this issue as the designer update is tracked [here](https://github.com/microsoft/AdaptiveCards/issues/6631).

**Comment by anna-dingler** [comment]
Hi @g138!

Templating expressions only work in Preview mode on the designer (see images below).

<img width="596" alt="image" src="https://user-images.githubusercontent.com/98650930/198078763-025d8444-3dd2-44ad-9d98-8e2fde4fe354.png">

<img width="610" alt="image" src="https://user-images.githubusercontent.com/98650930/198079018-c785dca9-8687-4f8c-a893-24789b840cc2.png">

We also have an issue open in the backlog to remove the parse error in this scenario (https://github.com/microsoft/AdaptiveCards/issues/7775) - thank you for bringing it to our attention again!

Let me know if you have any other questions!

**Comment by g138** [comment]
Thanks for the quick response @anna-dingler 

When I am trying to use a similar logic with card JSON to post an adaptive card in the team channel via PowerAutomate Flow. It doesn’t work, can you guide me on what I am doing wrong

Below is the JSON I am using to post an adaptive card.
```
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.4",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "${title}",
            "color": "${if(1 >= 0, 'good', 'attention')}"
        }
    ]
}
```

**Comment by anna-dingler** [comment]
Hey @g138,  

The templating expressions are evaluated using our `adaptivecards-templating` package (https://www.npmjs.com/package/adaptivecards-templating). Templates are **expanded** using the templating package, and then the **resulting** card is parsed by the Adaptive Cards library.

Since the template you provided works in the designer, there is a chance that PowerAutomate doesn't use the templating library. I would [reach out to them here](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity) to see if they have any information on this.

**Comment by g138** [comment]
Thanks, @anna-dingler for the response, using the library solved my issue on the node side, separate from this preview mode helped to see the change on the adaptivecard.io

```
var ACData = require('adaptivecards-templating');

let cardJson = {
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
          {
                "type": "TextBlock",
                "size": "Medium",
                "weight": "Bolder",
                "text": "${number}",
                "color": "${if(number > 0, 'good', 'attention')}"
          }
    ]
}

let finalCardJson = cardJson.expand({
        $root: {
            number: 10
        },
})

```

![image](https://user-images.githubusercontent.com/36992519/198274770-9acd7e86-e2d4-44d0-a695-daf80bf7a7ac.png)

**Comment by anna-dingler** [comment]
Hi @DanjunEscoto9,

This issue has been fixed already. If you aren't seeing changes in the Designer, try switching to Preview mode.

Let me know if you still have any problems - thanks!

**Comment by DanjunEscoto9** [comment]
Hi @anna-dingler. I'm having this issue 
![image](https://user-images.githubusercontent.com/83352593/213796356-181fb02c-cce0-492e-ae05-b9b2538aabd4.png)

**Comment by DanjunEscoto9** [comment]
> Hi @anna-dingler. I'm having this issue ![image](https://user-images.githubusercontent.com/83352593/213796356-181fb02c-cce0-492e-ae05-b9b2538aabd4.png)

It shows the said errors and when I use it in power automate it show this 
![image](https://user-images.githubusercontent.com/83352593/213796582-fcccee8a-d002-4253-879e-3bf7bd11d02e.png)

**Comment by JeanRoca** [comment]
> > Hi @anna-dingler. I'm having this issue ![image](https://user-images.githubusercontent.com/83352593/213796356-181fb02c-cce0-492e-ae05-b9b2538aabd4.png)
> 
> It shows the said errors and when I use it in power automate it show this ![image](https://user-images.githubusercontent.com/83352593/213796582-fcccee8a-d002-4253-879e-3bf7bd11d02e.png)

Hi @DanjunEscoto9 please refer to this comment:
https://github.com/microsoft/AdaptiveCards/issues/7040#issuecomment-1292366320

The issue you are facing should be reported to the Power Automate team if you are experiencing it on their product. To know if this issue has been fixed on our side, please try your JSON in [our Designer](https://adaptivecards.io/designer/)
