### ISSUE TITLE
Set backgroundImage's fillMode to 'repeat' doesn't make it cover the whole area.

### ISSUE THREAD

**Issue by lcmsft** [microsoft/AdaptiveCards#7056]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Author or host

Host

# Version of SDK

AdaptiveCards.Redering.Uwp  3.0.2

# Issue

I  want to use an image to fill the whole background of my adaptive card. By setting 'fillMode' to 'repeat',  I assume no matter the how small the image is, it will cover the whole area of the adaptive card. But seems this is not true. The image only cover part of the area. 

Here is the template and data. 

```c#
        const string templateJson = @"
{
    ""type"": ""AdaptiveCard"",
    ""version"": ""1.5"",
    ""backgroundImage"": {
            ""url"": ""${BackgroundImageUrl}"", 
            ""fillMode"": ""repeat""
            },          
    ""body"": [
        {
            ""type"": ""Container"",                      
            ""verticalContentAlignment"": ""bottom"",  
            ""items"": [
                {
                    ""type"": ""Container"",
                    ""backgroundImage"": {
                        ""url"": ""${BackgroundImageUrl2}"", 
                        ""fillMode"": ""repeat""
                        },                    
                    ""items"":[
                        {
                        ""type"": ""TextBlock"",
                        ""text"": ""${Name}"",  
                        ""size"": ""medium"", 
                        ""wrap"": true, 
                        ""maxLines"": 2,
                        ""horizontalAlignment"": ""center""
                        }
                    ],
                    ""bleed"": true
                }
            ],
            ""height"":""stretch"",
            ""spacing"": ""none""
        }
    ],
    ""selectAction"": {
                ""type"": ""Action.OpenUrl"",
                ""url"": ""${Url}""
            },
    ""$schema"": ""http://adaptivecards.io/schemas/adaptive-card.json"",
    ""minHeight"": ""200px"",
    ""verticalContentAlignment"": ""top""
}";

var myData = new
            {
                Name = "hello world",
                Url = "https://office.com",

                // This iamge has larger dimension 
                //BackgroundImageUrl = "https://neonstorage1.blob.core.windows.net/adaptivecardresources/orange.png",

                // This image has smaller dimension
                BackgroundImageUrl = "https://neonstorage1.blob.core.windows.net/adaptivecardresources/green.png"
            };
```

Here is the rendering result:
![image](https://user-images.githubusercontent.com/91639102/154779381-e75ec9f1-05a4-4a9a-9322-507dc5db04ea.png)

**Comment by paulcam206** [comment]
Thanks for the report! This looks like a recent regression. We'll investigate as soon as we can.

**Comment by beervoley** [comment]
@lcmsft the problem is that the image you supply is very large by default **(750 x 1350)** :) I assume you wanted your image to be just the **green rectangle**, but instead if you open the link, you will see that your picture is white background with a little green rectangle in the top left corner. You will need to adjust your image to get desired behavor.

**Comment by lcmsft** [comment]
@beervoley You are right. Sorry I didn't notice it before.

**Comment by lcmsft** [comment]
@beervoley I just created a new small image 
https://neonstorage1.blob.core.windows.net/adaptivecardresources/green2.png

I then use this image to render a 800x800 adaptive card.
![image](https://user-images.githubusercontent.com/91639102/155623577-ec7cbfef-5da9-4c95-991d-b1bb36f558e6.png)

This is what I get. The light green is image covered area.
![image](https://user-images.githubusercontent.com/91639102/155623475-47555c7f-59ee-4a36-9959-720f80fa02a3.png)

**Comment by beervoley** [comment]
@lcmsft can I ask what behavior are you trying to achieve?

I'm using a sample weather card and these are the possible outcomes (**with the picture you provided**) for the backgroundImage:
`fillMode : repeat`
![image](https://user-images.githubusercontent.com/21356912/155624397-2e492ead-3fc9-4a5b-b84b-7f065483942a.png)

`fillMode: repeatHorizontally`
![image](https://user-images.githubusercontent.com/21356912/155624476-b41c1847-3a7d-4076-afdb-ca4f65f0e244.png)

`fillMode: repeatVertically`
![image](https://user-images.githubusercontent.com/21356912/155624499-a25b9d02-bdfb-46ca-908e-b72e8b846217.png)

**Comment by lcmsft** [comment]
@beervoley My understanding is no matter how large the adaptivecard is, backgroundImage should cover the whole area when fillMode is repeat.  But I didn't see it on my UWP sample.

**Comment by beervoley** [comment]
@lcmsft can you check the size of your **Rendered Adaptive Card**?
It seems that though **Grid** is **600x600** the adaptive card is much smaller :)

**Comment by lcmsft** [comment]
@beervoley After I change minHeight from 200px to 600px, backgroundImage covers the whole area. So minHeight actually determines the real height, is my understanding right?

**Comment by lcmsft** [comment]
@beervoley Yes, you are right. I think it is because the card's height is smaller.
