### ISSUE TITLE
Datepicker and time picker not loading

### ISSUE THREAD

**Issue by chamile** [microsoft/AdaptiveCards#7058]
### Target Platforms

Other

### SDK Version

2.2.21

### Application Name

react native mobile app

### Problem Description

When clicking on a DateTime picker text box, it's not loading picker(date or time) instead of, getting a warning in debug mode in the to react native app and release mode does nothing.

### Screenshots

![image](https://user-images.githubusercontent.com/12965257/154932313-9c7f6619-762c-4085-ae74-eaf7b8288560.png)

![image](https://user-images.githubusercontent.com/12965257/154930809-71297b20-c3e4-4eca-9f29-85d5c4ff2720.png)

![image](https://user-images.githubusercontent.com/12965257/154930741-169227a2-4579-4fa0-8cc1-02094a60841d.png)

### Card JSON

```JSON
{
   {
      "type":"AdaptiveCard",
      "version":"1.0",
      "body":[
         {
            "type":"Container",
            "items":[
               {
                  "type":"TextBlock",
                  "size":"extraLarge",
                  "weight":"bolder",
                  "text":"Hjärtsvikt",
                  "wrap":true
               },
               {
                  "type":"TextBlock",
                  "weight":"bolder",
                  "text":"Nu  till!",
                  "wrap":true
               }
            ],
            "separator":true
         },
         {
            "type":"Container",
            "items":[
               {
                  "type":"TextBlock",
                  "size":"medium",
                  "text":"The answer applies to",
                  "wrap":true
               },
               {
                  "type":"Container",
                  "items":[
                     {
                        "type":"Container",
                        "items":[
                           {
                              "type":"TextBlock",
                              "text":"Date"
                           },
                           {
                              "type":"Input.Date",
                              "id":"00000000-0000-0000-0000-000000000000-date",
                              "value":"2022-02-21"
                           }
                        ]
                     },
                     {
                        "type":"Container",
                        "items":[
                           {
                              "type":"TextBlock",
                              "text":"Time"
                           },
                           {
                              "type":"Input.Time",
                              "id":"00000000-0000-0000-0000-000000000000-time",
                              "value":"14:27"
                           }
                        ]
                     }
                  ]
               }
            ],
            "separator":true
         }
      ],
      "actions":[
         {
            "type":"Action.Submit",
            "title":"Next",
            "style":"positive"
         }
      }
```

### Sample Code Language

Javascript -React native

### Sample Code

card = above data set
              
<AdaptiveCard
                payload={card}
                hostConfig={hostConfig}
                themeConfig={themeConfig}
                onExecuteAction={action => executeCardAction(action)}
              />

**Comment by paulcam206** [comment]
@vivekvijayakrishnan - This looks like a ReactNative issue. It looks like your fork doesn't have Issues enabled. Can you enable Issues in your fork and port this bug over? Thanks!

**Comment by vivekvijayakrishnan** [comment]
Hi @chamile, Can you please create the issue in the [BigThinkCode](https://github.com/BigThinkcode/AdaptiveCards) fork repository? The RN SDK related changes are maintained here. We can check the issue and if it needs any fix we can plan in the upcoming release.

CC: @Vasanth-S, @pragadeeshk @IbrahimSulai

**Comment by vivekvijayakrishnan** [comment]
> @vivekvijayakrishnan - This looks like a ReactNative issue. It looks like your fork doesn't have Issues enabled. Can you enable Issues in your fork and port this bug over? Thanks!

Sure @paulcam206. I have enabled the `Issues` section in the Fork. Thank You
