### ISSUE TITLE
[Rendering] DataUri is not supported on AdaptiveCards.Rendering.UWP 3.0.2

### ISSUE THREAD

**Issue by lcmsft** [microsoft/AdaptiveCards#7062]
### Target Platforms

UWP

### SDK Version

3.0.2

### Application Name

My own UWP app

### Problem Description

I want to use DataUri to render backgroundImage. I find AdaptiveCards.Rendering.UWP 3.0.0 can correctly display it while 3.0.2 can't.

Here is a sample DataUri

"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAu4AAAVGAQMAAAD7O6yEAAAABlBMVEX///8cdqN2RKVIAAABLklEQVR42uzMoQ0AMAzAsP1/86SN5oGCSg4L8XmTXTwej8fj8T08Ho/H4/F4PB7fw+PxeDwej8fj8T08Ho/H4/F4PB7fw+PxeDwej8fj8T08Ho/H4/F4PB7fw+PxeDwej8fj8T08Ho/H4/F4PB7fw+PxeDwej8fj8T08Ho/H4/F4PB7fw+PxeDwej8fj8T08Ho/H4/F4PB7fw+PxeDwej8fj8T08Ho/H4/F4PB7fw+PxG3hJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiTpswcHAgAAAABA/q+NoKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqoq7cEhAQAAAICg/699YQIAAAAAAIBdwQ+h1GPqlFQAAAAASUVORK5CYII="

### Card JSON

```JSON
const string templateJson = @"
{
    ""type"": ""AdaptiveCard"",
    ""version"": ""1.5"",
    ""backgroundImage"": {
            ""url"": ""${BackgroundImageUrl}"", 
            ""fillMode"": ""repeat""
            },      
    ""body"": [
        {
            ""type"": ""Container"",                      
            ""verticalContentAlignment"": ""bottom"",     
            ""items"": [
                {
                    ""type"": ""Container"",
                    ""backgroundImage"": {
                        ""url"": ""${SecondaryBackgroundImageUrl}"",  
                        ""fillMode"": ""repeat""
                        },                    
                    ""items"":[
                        {
                        ""type"": ""TextBlock"",
                        ""text"": ""${Name}"",  
                        ""color"": ""light"",
                        ""size"": ""large"", 
                        ""wrap"": true, 
                        ""maxLines"": 2,
                        ""horizontalAlignment"": ""left""
                        }
                    ],
                    ""bleed"":true
                }
            ],
            ""height"":""stretch"",
            ""spacing"": ""none""
        }
    ],
    ""selectAction"": {
                ""type"": ""Action.OpenUrl"",
                ""url"": ""${Url}""
            },
    ""$schema"": ""http://adaptivecards.io/schemas/adaptive-card.json"",
    ""minHeight"": ""200px"",
    ""verticalContentAlignment"": ""top""
}";
```

**Comment by paulcam206** [comment]
Looks like a recent regression...

**Comment by beervoley** [comment]
@paulcam206 since we changed the way **backgroundImage** was rendered, we need to extract logic for rendering images from **data uris** from **AdaptiveImageRendering** and use it to render background image.
