### ISSUE TITLE
[Rendering] Images with Action.Submit on Teams

### ISSUE THREAD

**Issue by ToriParla** [microsoft/AdaptiveCards#7070]
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Teams

### Problem Description

Images with Action.Submit are not working when clicking on it

            {
              "type": "Image",
              "url": "${telephonyurl}",
              "selectAction": {
                "type": "Action.Submit",
                "title": "Telephony Rates",
                "data": {
                  "action": "Telephony Rates"
                }
              }
            }

### Card JSON

```JSON
{
              "type": "Image",
              "url": "${telephonyurl}",
              "selectAction": {
                "type": "Action.Submit",
                "title": "Telephony Rates",
                "data": {
                  "action": "Telephony Rates"
                }
              }
            }
```

**Comment by Nekkilodeon** [comment]
Stopped working after updating Teams.

**Comment by ToriParla** [comment]
Yes! It was working for me last week after updating Teams this week stopped :(

**Comment by ToriParla** [comment]
Any news?

**Comment by joschi27** [comment]
-> I opened my own issue as i have stumbled upon a bigger problem with this. I might also have a fix for you guys, provided you have an element behind your image. Here's the [issue](https://github.com/microsoft/AdaptiveCards/issues/7085)

**Comment by jonmill** [comment]
Thanks for reaching out and I understand the frustration here. These are Teams specific issues, not on Adaptive Cards. To help get some progress here, we'll reach out internally and reference the Team's issues and see how we can get some traction for you internally. Sorry for your pain you've had here, hopefully we can help resolve this!

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/5379
