### ISSUE TITLE
Hi  Team,

### ISSUE THREAD

**Issue by laksh5feb85** [microsoft/AdaptiveCards#7071]
Hi Team,

In our actionable email implementation, when user take action on the actionable email, we are calling a Power automate flow which then takes the current user bearer and does the validation, after encoding the bearer token for some users we are getting sub value as email address(The identity of the user who took the action), but  its not working for some users( As after encoding bearer token the sub value is showing as OBJECTID)
Which is working fine earlier in all the environments

Could you please help me on it and tell me the fix ?

**Comment by jonmill** [comment]
Hi @laksh5feb85 - we don't have enough information to help here. Please re-open your issue using our issue templates so we can have the right amount of information to provide guidance. Thank you!
