### ISSUE TITLE
[Authoring] IAction doesn't have the style property

### ISSUE THREAD

**Issue by JCMartell** [microsoft/AdaptiveCards#7078]
### Target Application

Microsoft Teams, SharePoint

### Application Operating System

Other

### Schema Version

1.2

### Problem Description

The IAction interface in the nodejs SDK (source/nodejs/adaptivecards/src/schema.ts) doesn't have the style property. When typing our cards properly, the TypeScript compiler (tsc) throws an error for this when we set the style of an action.

### Expected Outcome

Should be able to set the style (ActionStyle.Positive, ActionStyle.Destructive, etc.) to an IAction.

### Actual Outcome

Setting the style to an IAction throws an error.

### Card JSON

```TypeScript
import { IAdaptiveCard } from "adaptivecards"

const card: IAdaptiveCard = {
    schema: "http=//adaptivecards.io/schemas/adaptive-card.json",
    type: "AdaptiveCard",
    version: "1.2",
    body: [],
    actions: [
        {
            type: "Action.Submit",
            title: "Some text",
            style: "Positive", // This will give an error
            id "someId",
            data {
                id: "someId",
            }
        }
    ],
}

```

**Comment by jonmill** [comment]
Great find, thank you for pointing this out! Added to our backlog
