### ISSUE TITLE
[Rendering] MS Teams Images with selectAction have inconsistent behaviour across platforms

### ISSUE THREAD

**Issue by joschi27** [microsoft/AdaptiveCards#7085]
### Target Platforms

Other

### SDK Version

1.4 / 1.5

### Application Name

Microsoft Teams

### Problem Description

Inconsistent behaviour of selectAction on images in Teams. And image display on adaptive cards in general.

I raised an [issue](https://github.com/MicrosoftDocs/msteams-docs/issues/4998) with the teams crew a few weeks ago about this inconsistent behaviour.
As with most of my bug reports they kinda ignored it and said it was by design.

The reason I opened that ticket was because I had a selectAction on a column that triggered Action.OpenUrl. The column contained an image. It worked on desktop / web. But on mobile (android, not tested with iOS), clicking on the image just opened the image (in my case a link icon) in a separate window instead of opening the url. 

I fixed that by putting the selectAction on the image instead of the column, which opened the url on both platforms, and I forgot about it.
Now, it seems like with the last update teams implemented a catch-22.

Current Behaviours:

|                       | Desktop | Mobile |
| ------------- | ------------- | ------------- |
| selectAction on column | opens url (correct)  | displays image |
| selectAction on image | does nothing | opens url (correct)  |

Which means, that I can now either choose to break the app on mobile or desktop.

This **is a bug** and cannot be by design.

I understand that normal images sent in a teams chat have to be clickable on mobile, but images on adaptive cards shouldn't be clickable by default. My reasoning behind this is that adaptive cards has it's own way of dealing with images. Additionally, the "msTeams":{ "allowExpand":true } property exists to explicitly say when displaying the image should be possible. This works great on desktop! It just doesn't make sense. You can click every single icon, be it something like a checkmark for design. It then opens stretched and on a black background.

There was already an [issue](https://github.com/microsoft/AdaptiveCards/issues/7070) open about this, but I think this one might help understand the bigger problem.

For anyone needing a quick solution, you can just put the same selectAction on an element "behind" the image (in my case a column) AND on the image itself. Seems to work for now.

### Card JSON

```JSON
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.5",
  "body": [
    {
      "type": "TextBlock",
      "text": "This should display the image on both platforms - msTeams allowExpand is set to true.",
      "weight": "bolder",
      "size": "large"
    },
    {
      "type": "Image",
      "url": "https://adaptivecards.io/content/cats/1.png",
      "size": "medium",
      "msTeams": {
        "allowExpand": true
      }
    },
    {
      "type": "TextBlock",
      "text": "This should NOT display the image on both platforms. It's just an image",
      "weight": "bolder",
      "size": "large"
    },
    {
      "type": "Image",
      "url": "https://adaptivecards.io/content/cats/1.png",
      "size": "medium"
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "100px",
          "selectAction": {
            "type": "Action.OpenUrl",
            "url": "https://google.com"
          },
          "items": [
            {
              "type": "Image",
              "height": "50px",
              "url": "https://upload.wikimedia.org/wikipedia/commons/e/ee/Chain_link_icon.png",
              "horizontalAlignment": "Center"
            }
          ]
        },
        {
          "type": "Column",
          "width": "stretch",
          "VerticalContentAlignment": "center",
          "items": [
            {
              "type": "TextBlock",
              "text": "This works on Desktop only",
              "wrap": true
            },
            {
              "type": "TextBlock",
              "text": "The selectAction is on the column",
              "wrap": true
            },
            {
              "type": "TextBlock",
              "text": "<- Click the icon to go to google.com",
              "wrap": true
            }
          ]
        }
      ]
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "100px",
          "items": [
            {
              "type": "Image",
              "height": "50px",
              "url": "https://upload.wikimedia.org/wikipedia/commons/e/ee/Chain_link_icon.png",
              "horizontalAlignment": "Center",
              "selectAction": {
                "type": "Action.OpenUrl",
                "url": "https://google.com"
              }
            }
          ]
        },
        {
          "type": "Column",
          "width": "stretch",
          "VerticalContentAlignment": "center",
          "items": [
            {
              "type": "TextBlock",
              "text": "This works on Mobile only",
              "wrap": true
            },
            {
              "type": "TextBlock",
              "text": "The selectAction is on the image"
            },
            {
              "type": "TextBlock",
              "text": "<- Click the icon to go to google.com",
              "wrap": true
            }
          ]
        }
      ]
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "100px",
          "items": [
            {
              "type": "Image",
              "height": "50px",
              "url": "https://upload.wikimedia.org/wikipedia/commons/e/ee/Chain_link_icon.png",
              "horizontalAlignment": "Center",
              "selectAction": {
                "type": "Action.OpenUrl",
                "url": "https://google.com"
              }
            }
          ],
          "selectAction": {
            "type": "Action.OpenUrl",
            "url": "https://google.com"
          }
        },
        {
          "type": "Column",
          "width": "stretch",
          "VerticalContentAlignment": "center",
          "items": [
            {
              "type": "TextBlock",
              "text": "This works on both but is a hack.",
              "wrap": true
            },
            {
              "type": "TextBlock",
              "text": "The selectAction is on both elements"
            },
            {
              "type": "TextBlock",
              "text": "<- Click the icon to go to google.com",
              "wrap": true
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/5378

**Comment by jonmill** [comment]
Thanks for reaching out and I understand the frustration here. These are Teams specific issues, not on Adaptive Cards. To help get some progress here, we'll reach out internally and reference the Team's issues and see how we can get some traction for you internally. Sorry for your pain you've had here, hopefully we can help resolve this!
