### ISSUE TITLE
[Designer] How can I change the default card payload?

### ISSUE THREAD

**Issue by ericrrichards** [microsoft/AdaptiveCards#7087]
I'm trying to use the Card Designer JS SDK in a product I'm working on, and I would like to change the default card payload that the designer is initialized with so that it is a blank card, instead of the "Publish Adaptive Card Schema" card.

I can't set my own stored card payload with designer.setCard() until the Monaco Editor component gets initialized - `require(['vs/editor/editor.main'], function () { designer.monacoModuleLoaded(); designer.setCard(card)}):` - , so for half a second after the designer is attached it will show the default card from [constants.ts](https://github.com/microsoft/AdaptiveCards/blob/356eed2256a04bbe2b1545950db3bd5e9471e7de/source/nodejs/adaptivecards-designer/src/constants.ts).

This might be a little unusual because I am using OrchardCore, and so I'm pulling in their packaged version of Monaco, but going through the OrchardCore source it should be the same version.

I suppose I can wrap everything in a div and hide it until everything is initialized, but I would rather not do that.

**Comment by jonmill** [comment]
We have an example [here](https://github.com/microsoft/AdaptiveCards/blob/49b15d69903be0ef7c88a47a6eaf23a16781d74a/source/nodejs/adaptivecards-designer/index.html#L66-L80) that shows how to set the default card. You look to be calling `monacoModuleLoaded();` **before** the `setCard` call; please try switching the order of these calls like in the example.

**Comment by ericrrichards** [comment]
I don't see how that could possibly work with the way that setCardPayload() is implemented - if I'm reading things right that won't do anything at all until after monacoModuleLoaded() is called so that this._isMonacoEditorLoaded == true, and that matches what I'm seeing.

https://github.com/microsoft/AdaptiveCards/blob/main/source/nodejs/adaptivecards-designer/src/card-designer.ts#:~:text=%7D-,private%20setCardPayload(payload%3A%20object%2C%20addToUndoStack%3A%20boolean)%20%7B,%7D,-private%20setSampleDataPayload(payload

**Comment by fabiofranzini** [comment]
Hey @ericrrichards I confirm this problem... Thanks this thread I found a possible way to "fix" like this:

1. load the monaco editor instance
2. when loaded, instantiates the CardDesigner object
3. set the monaco instance to the CardDesigner instance using the monacoModuleLoaded method
4. on CardDesigner instance invoke the setCard method to load the card you want
5. on CardDesigner instance invoke the clearUndoStack method to reset the Undo / Redo buttons
6. To be sure, invoke designerSurface.updateLayout (true) on the CardDesigner instance to "reset" the card designer layout.

For me, this works!
I'm integrating the designer into a react component, to avoid the flickering you inevitably have with this method, you can use a spinner to indicate that you are loading the editor.

**Comment by fabiofranzini** [comment]
> Hey @ericrrichards I confirm this problem... Thanks this thread I found a possible way to "fix" like this:
> 
> 1. load the monaco editor instance
> 2. when loaded, instantiates the CardDesigner object
> 3. set the monaco instance to the CardDesigner instance using the monacoModuleLoaded method
> 4. on CardDesigner instance invoke the setCard method to load the card you want
> 5. on CardDesigner instance invoke the clearUndoStack method to reset the Undo / Redo buttons
> 6. To be sure, invoke designerSurface.updateLayout (true) on the CardDesigner instance to "reset" the card designer layout.
> 
> For me, this works! I'm integrating the designer into a react component, to avoid the flickering you inevitably have with this method, you can use a spinner to indicate that you are loading the editor.

@dclaux I resolved in this way 🙂

**Comment by fabiofranzini** [comment]
Simple gif of my own react control that hosts the Adaptive Card Designer:
![AdaptiveCardDesigner](https://user-images.githubusercontent.com/4202747/160158011-3aa27e2d-c9ec-4eea-9096-1670024ef9cd.gif)

**Comment by beervoley** [comment]
@licanhua FYI

**Comment by licanhua** [comment]
@ericrrichards we don't have API for you to change the default payload from code. I moved `designer.attachTo(document.getElementById("designerRootHost"));` into the require function, likely it avoids the problem in my testing.


```
			require(['vs/editor/editor.main'], function () {
				designer.attachTo(document.getElementById("designerRootHost"));
				designer.monacoModuleLoaded();
				designer.setCard(
				{
					type: "AdaptiveCard",
					version: "1.0",
					body: [
						{
							type: "TextBlock",
							text: "Hello world"
						}
					]
				}
			);
			});

```

Otherwise please try @fabiofranzini, and it should work too.

**Comment by paulcam206** [comment]
Sounds like this has been resolved. Please let us know if this doesn't work for you. Thanks!
