### ISSUE TITLE
[Feature Request] Input.Toggle value should be a boolean

### ISSUE THREAD

**Issue by JCMartell** [microsoft/AdaptiveCards#7092]
### Problem Statement

Currently, the Input.Toggle value is set to be a string. However, it doesn't really makes sense to have "true" and "false" as strings.

### Proposed solution

The value, valueOn and valueOff properties should be booleans.

**Comment by jonmill** [comment]
The card author is able to set the values "true" and "false" to other things (ex: "checked" and "unchecked") via the schema...the "True" and "False" strings are default values. Please see the [schema docs](https://adaptivecards.io/explorer/Input.Toggle.html) for more information about how to do this. Thanks!

**Comment by JCMartell** [comment]
Okay, I can see the purpose behind this implementation. There's other things that could go wrong with the "value" property then. Let's say I define valueOn: "checked", valueOff: "unchecked" and value: "chekced" (intended the typo here), I'm expecting the toggle to be checked when initialized. However, giving freedom on what the value property can be can result in human errors/mistakes. One thing that could avoid that is having a property telling which value between valueOn and valueOff should be used on initialization, like defaultValueOn: true for example. In this example, having it set to true would set the toggle initial value to the valueOn value and having it set to false would set the initial value to the valueOff value. Does that make sense? Is this something that can be worth considering?
