### ISSUE TITLE
Roadmap linked to on main adaptivecards.io page is broken

### ISSUE THREAD

**Issue by Greg-Hitchon** [microsoft/AdaptiveCards#7099]
# Issue

It looks like the roadmap project board is broken: https://portal.productboard.com/adaptivecards/1-adaptive-cards-features/tabs/5-roadmap

The link works but the page doesn't load, looks like a parsing error:

![image](https://user-images.githubusercontent.com/3837138/157270621-462ff94a-17f1-424e-b145-2b0630aa794f.png)

**Comment by paulcam206** [comment]
@JeanRoca - Can you take a look at this in light of ProductBoard work we have going on?

**Comment by paulcam206** [comment]
We should double check to make sure out blog post links are up to date as well.

**Comment by JeanRoca** [comment]
This will be fixed here: https://github.com/microsoft/AdaptiveCards/pull/7163

Our team is no longer using productboard.
