### ISSUE TITLE
Adaptive Cards not rendering in the Framework Emulator

### ISSUE THREAD

**Issue by JSchenk8** [microsoft/AdaptiveCards#7141]
### Target Platforms

NodeJS

### SDK Version

v4

### Application Name

Microsoft Framework Emulator

### Problem Description

I have downloaded the botbuilder samples from https://github.com/microsoft/BotBuilder-Samples and added an adaptive card to 16. proactive-messages as per the sample built using the azure tools in VSCode. 

The code to send the card looks like this: 

```javascript
const card = cardTools.AdaptiveCards.declare(notificationCard).render(data);
    for (const conversationReference of Object.values(conversationReferences)) {
        if (conversationReference.user.name === recipientName) {
            await adapter.continueConversationAsync(process.env.MicrosoftAppId, conversationReference, async context => {
                await context.sendActivity({ attachments: [CardFactory.adaptiveCard(card)] });
            });
            res.writeHead(200);
        } else {
            res.writeHead(404);
        }
    }
```

But in the framework emulator despite receiving the card correctly, nothing is rendered. Here is a screenshot of the framework emulator:
<img width="662" alt="Screenshot 2022-03-16 at 17 58 05" src="https://user-images.githubusercontent.com/76001984/158646498-ae554c53-9e02-459e-863f-5b47fb4ce278.png">

And a screenshot to show the adaptive card is in the post request sent to trigger this card:
<img width="551" alt="Screenshot 2022-03-16 at 17 58 26" src="https://user-images.githubusercontent.com/76001984/158646570-0b9e3649-2176-41ad-9ec9-1fd010578b06.png">

Either there is a bug with this adaptive card methodology or the docs need updating. Please let me know as to whether or not this is an issue or if the docs have misled me as to how to proactively send an adaptive card. 

### Screenshots

<img width="551" alt="Screenshot 2022-03-16 at 17 58 26" src="https://user-images.githubusercontent.com/76001984/158646676-f57b8ef4-12ca-4fcb-89eb-1232048fa9da.png">
<img width="662" alt="Screenshot 2022-03-16 at 17 58 05" src="https://user-images.githubusercontent.com/76001984/158646685-fb5af5b5-9b07-434f-b5c6-2f67d905e53f.png">

### Card JSON

```JSON
{
  "type": "AdaptiveCard",
  "body": [
      {
          "type": "ColumnSet",
          "columns": [
              {
                  "type": "Column",
                  "items": [
                      {
                          "type": "Image",
                          "style": "Icon",
                          "url": "somesampleURL",
                          "size": "Small"
                      }
                  ],
                  "width": "auto"
              },
              {
                  "type": "Column",
                  "items": [
                      {
                          "type": "TextBlock",
                          "weight": "Bolder",
                          "text": "Notification",
                          "wrap": true
                      },
                      {
                          "type": "TextBlock",
                          "spacing": "None",
                          "text": "Sent ${data.date}",
                          "isSubtle": true,
                          "wrap": true
                      }
                  ],
                  "width": "stretch"
              }
          ]
      },
      {
          "type": "TextBlock",
          "text": "${data.notification}",
          "wrap": true
      }
  ],
  "actions": [
      {
          "type": "Action.OpenUrl",
          "title": "Go to Document",
          "url": "${data.documentLink}"
      },
      {
        "type": "Action.OpenUrl",
        "title": "Unsubscribe",
        "url": "${data.toUnsubscribe}"
      }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.4"
}
```

### Sample Code Language

Javascript

### Sample Code

```javascript
const card = cardTools.AdaptiveCards.declare(notificationCard).render(data);
    for (const conversationReference of Object.values(conversationReferences)) {
        if (conversationReference.user.name === recipientName) {
            await adapter.continueConversationAsync(process.env.MicrosoftAppId, conversationReference, async context => {
                await context.sendActivity({ attachments: [CardFactory.adaptiveCard(card)] });
            });
            res.writeHead(200);
        } else {
            res.writeHead(404);
        }
    }
```

**Comment by paulcam206** [comment]
@JeanRoca - can you take a look and redirect?

**Comment by JeanRoca** [comment]
We have contacted the Bot Framework team and hoping to hear back

**Comment by clearab** [comment]
The Bot Framework Emulator (and the underlying WebChat control) do not support Adaptive Card versions > 1.3 . I believe this is the root of this issue.

**Comment by beervoley** [comment]
Closing per the comment above :)
