### ISSUE TITLE
[.NET] Any plan to release the new version? Which support schema 1.5

### ISSUE THREAD

**Issue by Danieladu** [microsoft/AdaptiveCards#7169]
### Problem Statement

Currently, the .NET version of 2.7.3 just support schema 1.4, but the code in main branch has already support 1.5 now. Do you have any plan to release the new version? Thanks!

### Proposed solution

Release a new version, or just cherry pick the Upgrade commit into "2.7.3".

**Comment by beervoley** [comment]
@Danieladu we don't have any public announcements regarding the dot net package at this time :)
