### ISSUE TITLE
Link to sample HostConfig.json is 404

### ISSUE THREAD

**Issue by jsw** [Microsoft/AdaptiveCards#717]
https://docs.microsoft.com/en-us/adaptive-cards/display/hostconfig

links to non-existent

https://github.com/Microsoft/AdaptiveCards/blob/master/samples/Themes/sample.json

**Comment by EricDahlvang** [comment]
Hi @jsw
Thanks for reporting the bad link.  We will get the docs updated soon.  In the mean time: that file can now be found here: 

https://github.com/Microsoft/AdaptiveCards/blob/master/samples/v1.0/HostConfig/sample.json

**Comment by matthidinger** [comment]
This has been fixed now
