### ISSUE TITLE
Can't run two different forms on the same bot

### ISSUE THREAD

**Issue by fernandofas** [microsoft/AdaptiveCards#7198]
I have a bot on PVA and I'm using adaptive cards with Bot Framework Composer. So, when I activate the first form on PVA, the process run fine, but if I run a second form, the bot immediately gives me the result as the form is already sent.

The result of the first form is sent to my email ok, but the second not even comes up on the chatbot.

Here is a video I recorded:
https://www.kapwing.com/videos/624ec3eee62d030067e2aa06

---
* URL: https://adaptivecards.io/blog/

**Comment by paulcam206** [comment]
This appears to be an issue with BotFramework rather than Adaptive Cards. Please file this issue on their [GitHub repo](https://github.com/microsoft/botframework-sdk/issues/new/choose).
