### ISSUE TITLE
Action.Execute field "associatedInputs" issue with case sensitivity

### ISSUE THREAD

**Issue by limar63** [microsoft/AdaptiveCards#7213]
### Target Application

Microsoft Teams

### Application Operating System

Other

### Schema Version

1.5

### Problem Description

associatedInputs in the docs https://adaptivecards.io/explorer/Action.Execute.html has such description listed:
`Allowed values:
"Auto": Inputs on the current card and any parent cards will be validated and submitted for this Action.
"None": None of the inputs will be validated or submitted for this Action.`

And in [designer playground](https://adaptivecards.io/designer) `"associatedInputs": "None"` works fine. But when I was implementing it via Json (I am using Scala, not C#), sending Json card structure to the Microsoft Teams app, the property wasn't working until I made the field `"associatedInputs": "none"` without capital letter. This feels like either an issue when it comes to the way Json is processed or issues with documentation/designer tools, that behaviour isn't consistent.

### Expected Outcome

associatedInputs field works with "None" string value assigned or documents/designer appropriately doesn't work with "None" and don't say this is the needed value.

### Actual Outcome

associatedInputs field doesn't work with "None" string value assigned, while documents/designer work fine with "None" value assigned

### Card JSON

```JSON
{
   "type":"application/vnd.microsoft.card.adaptive",
   "value":{
      "type":"AdaptiveCard",
      "body":[
         {
            "text":"Choose search object type",
            "type":"TextBlock"
         },
         {
            "id":"objectType",
            "choices":[
               {
                  "title":"Opportunity",
                  "value":"Opportunity"
               },
               {
                  "title":"Account",
                  "value":"Account"
               },
               {
                  "title":"Case",
                  "value":"Case"
               }
            ],
            "style":"filtered",
            "isRequired":true,
            "type":"Input.ChoiceSet"
         }
      ],
      "version":"1.5",
      "refresh":{
         "action":{
            "isEnabled":true,
            "associatedInputs":"auto",
            "type":"Action.Execute"
         },
         "userIds":[
            
         ]
      },
      "actions":[
         {
            "data":{
               "entityId":"someId",
               "userId":"someId",
               "tenant":"someId"
            },
            "title":"Confirm",
            "verb":"typeChosen",
            "isEnabled":true,
            "associatedInputs":"auto",
            "type":"Action.Execute"
         },
         {
            "data":{
               "entityId":"someId",
               "userId":"someId",
               "tenant":"someId"
            },
            "title":"Back",
            "verb":"backToYes",
            "isEnabled":true,
            "associatedInputs":"None",
            "type":"Action.Execute"
         }
      ]
   }
}
```

**Comment by paulcam206** [comment]
@limar63 - where are you running Teams? Teams on Desktop? iOS or Android?

**Comment by paulcam206** [comment]
Hmm... Given that this works in the Designer, I think this is probably an issue specific to Teams. I'm going to move this bug over for them to look at.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/6175
