### ISSUE TITLE
Unable to resolve module AccessbilityInfo ReactNative with Expo

### ISSUE THREAD

**Issue by bozali** [microsoft/AdaptiveCards#7218]
# Platform

* Android
* Expo

# Target Application

Android React Native with Expo

# Version of SDK

react: 17.0.1
react-native: 0.64.3
expo: 44.0.0

# Issue

I tried to create an example app like the following example https://github.com/BigThinkcode/AdaptiveCards/tree/master/source/community/reactnative#databinding. After building and starting the app using Expo and the Expo Sandbox I got the error message that a module cannot be resolved. I even followed the steps that were mentioned in the error.

```
Unable to resolve module AccessibilityInfo from D:\dev\someproject\node_modules\adaptivecards-reactnative\node_modules\react-native\Libraries\react-native\react-native-implementation.js: AccessibilityInfo could not be found within the project or in these directories:
  node_modules\adaptivecards-reactnative\node_modules
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  19 | const ReactNative = {
  20 |   // Components
> 21 |   get AccessibilityInfo() {
     |       ^
  22 |     return require('AccessibilityInfo');
  23 |   },
  24 |   get ActivityIndicator() {
```

**Comment by paulcam206** [comment]
Please file this issue over in the [BigThinkcode/AdaptiveCards](https://github.com/BigThinkcode/AdaptiveCards/) repo. Thanks!
