### ISSUE TITLE
[Visual Requirements - Upload Card Structure]: Luminosity ratio of "Cancel" button border with respect to background color is 1.605:1 which is less than 3:1.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7230]
https://microsoft.visualstudio.com/OS/_workitems/edit/30642435

**Comment by vagpt** [comment]
This issue is not repro at our end, hence closing this issue.


**Snippet:**

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/c4acd737-cf2c-46f1-a423-31c33c7709b8)
