### ISSUE TITLE
[Visual Requirements - Upload Card Structure]: Luminosity ratio of "Scrollbar" is 1.8:1 which is less than 3:1.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7231]
https://microsoft.visualstudio.com/OS/_workitems/edit/30642873

**Comment by vagpt** [comment]
This issue is not repro, hence closing this issue.

**Snippet:**

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/98c6a897-8f1d-4a01-a657-f509ac78d5fd)
