### ISSUE TITLE
[Visual requirements: Designer_Select Host App menu]: Luminosity ratio is 1.6:1 for the focus indicator on 'Select Host App' menu items which is less than 3:1.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7232]
https://microsoft.visualstudio.com/OS/_workitems/edit/30868120

**Comment by vagpt** [comment]
Issue is not repro hence closing this issue.

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/49efb2b4-a554-441d-9899-27467071658c)
