### ISSUE TITLE
[Visual Requirement: Designer_Element Properties Pane]: Luminosity ratio of "Add a New Fact" menu item boundary is 1.5:1, without keyboard focusing.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7234]
https://microsoft.visualstudio.com/OS/_workitems/edit/30926378

**Comment by vagpt** [comment]
This issue is not repro, hence closing this issue.

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/e3819051-5b2d-4fce-acd0-286c7c96619f)
