### ISSUE TITLE
[Visual Requirement: Samples_Inputs With Validation]: Luminosity ratio of "Name" edit boundary is 1.3:1 which is less than 3:1.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7236]
https://microsoft.visualstudio.com/OS/_workitems/edit/30943601

**Comment by vagpt** [comment]
Issue is not repro, hence closing this issue.

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/0abcbc05-b981-4a06-af9f-328a5ee12273)
