### ISSUE TITLE
[Screen Reader: Designer> Element Properties]: Place holder for “Data Context” edit field is incorrect to convey the exact purpose of the field.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7238]
https://microsoft.visualstudio.com/OS/_workitems/edit/30961076

**Comment by vagpt** [comment]
This issue is not repro on the environment below, hence closing this issue.


**Test Environment:**
URL: https://adaptivecards.io/designer/
OS Version: 23H2 (OS Build 25997.1000)
Browser Version: 121.0.2277.4
