### ISSUE TITLE
[Samples-> Inputs with Validation]: Incorrect name is defined for 'Close' button appearing for suggestion list for Name edit field.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7248]
https://microsoft.visualstudio.com/OS/_workitems/edit/33898123

**Comment by vagpt** [comment]
This issue is not repro on the environment below, hence closing this issue.

**Test Environment:**
URL: https://adaptivecards.io/samples/InputsWithValidation.html
OS Version: 23H2 (OS Build 25997.1000)
Browser Version: 121.0.2277.4
