### ISSUE TITLE
[Designer-> Element Properties]: Incorrect name is defined for 'Remove' button under 'Element Properties' pane.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7249]
https://microsoft.visualstudio.com/OS/_workitems/edit/33898617

**Comment by vagpt** [comment]
This issue is not repro, hence closing this issue.

Snippet:

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/58f6ba22-6282-4fdb-b5d9-04b5a278e364)
