### ISSUE TITLE
[Adaptive Cards- Import- Expense Report]: Luminosity ratio of 'Reject' text is '2.0:1' which is less than 4.5:1 on Reject button under Expense Report Pane.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7252]
https://microsoft.visualstudio.com/OS/_workitems/edit/34056133

**Comment by Raisul123** [comment]
As per new guideline we are enhancing the severity. so we are closing this issue and logged new bug: [[Adaptive Cards- Import- Expense Report]: Luminosity ratio of 'Reject' text is '2.0:1' which is less than 4.5:1 on Reject button under Expense Report Pane. · Issue #8475 · microsoft/AdaptiveCards (github.com)](https://github.com/microsoft/AdaptiveCards/issues/8475)
