### ISSUE TITLE
[Adaptive Cards- Import- Activity Update]: Luminosity ratio of selected date on Calendar Picker under 'Activity Update' pane is 1.2:1 which is less than 3:1.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7255]
https://microsoft.visualstudio.com/OS/_workitems/edit/34057871

**Comment by Raisul123** [comment]
As per New guideline we are closing this issue and logged new bug with ID [[Adaptive Cards- Import- Activity Update]: Luminosity ratio of selected date on Calendar Picker under 'Activity Update' pane is 1.2:1 which is less than 3:1. · Issue #8464 · microsoft/AdaptiveCards (github.com)](https://github.com/microsoft/AdaptiveCards/issues/8464)
