### ISSUE TITLE
[Schema Explorer>Header]: Screen reader is announcing incorrect role as "Group" for "Feedback" link. 

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7272]
https://microsoft.visualstudio.com/OS/_workitems/edit/35878695

**Comment by vagpt** [comment]
This issue is not repro as of now SR is announcing as Link hence closing this issue.

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/15ccc5ca-949a-47ef-a743-1563b3258f99)
