### ISSUE TITLE
[AdaptiveCards- Designer - Target Version]: At 200%, Target version button is getting cropped.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7283]
https://microsoft.visualstudio.com/OS/_workitems/edit/35927350

**Comment by vagpt** [comment]
This issue is not repro, hence closing this issue.

**Snippet:**

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/260c3747-750d-4fb9-b071-df728dc16a19)
