### ISSUE TITLE
[AdaptiveCards- Designer - Host App Docs]: After performing the 'Undo or Redo' action, screen reader does not provide any information. 

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7286]
https://microsoft.visualstudio.com/OS/_workitems/edit/35992390

**Comment by vagpt** [comment]
Closing this issue here as of now this issue is being tracked using below URL.

https://github.com/microsoft/AdaptiveCards/issues/8168
