### ISSUE TITLE
[AdaptiveCards- Designer - Card Element]: Screen Reader does not convey the descriptive information to the user to use 'Drag & Drop' elements. 

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7287]
https://microsoft.visualstudio.com/OS/_workitems/edit/35994426

**Comment by vagpt** [comment]
Closing this bug here as this issue is now tracking with below URL.

https://github.com/microsoft/AdaptiveCards/issues/8169
