### ISSUE TITLE
[AdaptiveCards- Designer - Card Structure]: Ensures elements with an ARIA role that require parent roles are contained by them (.acd-tree-item[role="treeitem"])

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7288]
https://microsoft.visualstudio.com/OS/_workitems/edit/35996009

**Comment by vagpt** [comment]
This issue is still repro.

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/f9957b15-8c78-4bb6-afbb-98660ee83318)

@anna-dingler, could you please let us know, by when this issue will be fix?

**Comment by anna-dingler** [comment]
Hi @vagpt,

This issue is fixed on our internal site. I expect us to make another website release this month, so I will go ahead and mark this as completed.

Please let me know if you have any questions!
