### ISSUE TITLE
[Adaptive Cards - Sample Cards]: The Luminosity Ratio of the focusable list items present in the dropdown under 'Sample Cards' is 1.3:1 which is less than the required 3:1.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7293]
https://microsoft.visualstudio.com/OS/_workitems/edit/36143745

**Comment by Raisul123** [comment]
As per New guideline we are closing this issue and logged new bug with ID [[Adaptive Cards - Sample Cards]: The Luminosity Ratio of the focusable list items present in the dropdown under 'Sample Cards' is 1.3:1 which is less than the required 3:1. · Issue #8463 · microsoft/AdaptiveCards (github.com)](https://github.com/microsoft/AdaptiveCards/issues/8463)
