### ISSUE TITLE
{Linked:Bug2509202}[Adaptive Card-Schema Explorer- Input.Date]: Tooltips are not provided for the 'Go to Next month' and 'Go to previous month' buttons in calendar pop-up.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7299]
https://microsoft.visualstudio.com/OS/_workitems/edit/37641373

**Comment by vagpt** [comment]
This issue is not repro, hence closing this issue.

**Snippet:**

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/8c78225d-3a3f-485b-b322-bdbca18ce643)
