### ISSUE TITLE
[Adaptive Card-Schema Explorer- Input.Date]: 'Clear' and 'Today' buttons in calendar pop-up is appearing as links in HC mode.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7300]
https://microsoft.visualstudio.com/OS/_workitems/edit/37642918

**Comment by vagpt** [comment]
Hi @anna-dingler 

Could you please let us know is there any future plan to fix this issue? As issue is still repro.

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/60179ecb-0108-40e8-9f03-99c28175d389)

**Comment by anna-dingler** [comment]
Closing this issue since it is a duplicate of https://github.com/microsoft/AdaptiveCards/issues/7714

**Comment by vagpt** [comment]
As per the comment above adding A11yTTValidated.
