### ISSUE TITLE
[Designer- Card Elements- Containers]: ARIA attribute are not allowed for an elements( Containers) role.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7305]
https://microsoft.visualstudio.com/OS/_workitems/edit/37767442

**Comment by vagpt** [comment]
This issue is not repro, hence closing this issue.

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/bc51e6ef-ddf9-4729-a4a1-16281b6d4f64)
