### ISSUE TITLE
Updated schema doc is missing enums

### ISSUE THREAD

**Issue by jsw** [Microsoft/AdaptiveCards#736]
Intentional?

ImageSize, etc...

https://docs.microsoft.com/en-us/adaptive-cards/create/cardschema

**Comment by matthidinger** [comment]
Known issue and will be resolved soon. In the mean time you can view all those properties using the [Schema explorer](adaptivecards.io/explorer/)

**Comment by matthidinger** [comment]
Duplicate of #883
