### ISSUE TITLE
Add support for expanding/collapsing a card by clicking "See all"/" See lees" 

### ISSUE THREAD

**Issue by BernardoAMunoz** [microsoft/AdaptiveCards#737]
The card should be able to

1.	Render markup (html), 
a.	Data coming from Toronto are in HTML format with the mix of text, url links (and probably images)
b.	The adaptive card treats text and url as separate control.
2.	Support url link callback and other user action callback (for telemetry)
3.	Support hide/show some parts of the content for See More/Less.

The schema for AdaptiveCard would something like

{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "HtmlBlock",
      "html": "html with <div>, <p>, <url>, <image>, <ul>, <ui> etc"
    },
    {
      "type": "HtmlBlock-second",                /* this is the block for See more/less, it may be defined in Action.ShowHide as a separate card. */
      "html": "html with <div>, <p>, <url>, <image>, <ul>, <ui>, etc"
    },
  ],
  "actions": [
    {
      "type": "Action.ShowHide",
      "title-show": "See More", /* Click to show the "HtmlBlock-second" defined above
                  "title-hide": "See Less",
    }
  ]
}

**Comment by BernardoAMunoz** [comment]
Adding sample images

![image](https://user-images.githubusercontent.com/19616737/31189469-2fc777bc-a8ed-11e7-9dda-6b6eda4cda92.png)
![image](https://user-images.githubusercontent.com/19616737/31189477-36181ffe-a8ed-11e7-8e3c-297dd27ba650.png)

**Comment by Nasby** [comment]
Have you heard of any progress on this?

**Comment by levotragiang** [comment]
Vote for this! 👍 
Hope to see soon 😄

**Comment by dclaux** [comment]
Hi there, we have another feature proposal similar to this but more generic: [Support dynamically showing/hiding a portion of a card after user interaction](https://github.com/Microsoft/AdaptiveCards/issues/1729)

**Comment by RebeccaAnne** [comment]
This scenario is now supported by ToggleVisibility as linked above.
