### ISSUE TITLE
[SampleCard-FlightDetails.json; Config-Default]: Screen reader announcement is not descriptive enough for "SFO" and "JFK" and does not describe the topic or purpose of the element.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7371]
https://microsoft.visualstudio.com/OS/_workitems/edit/37982790

**Comment by Raisul123** [comment]
As per new guideline we are enhancing the severity. so we are closing this issue and logged new bug: https://github.com/microsoft/AdaptiveCards/issues/8477
