### ISSUE TITLE
[SampleCard-FlightDetails.json; Config-testVariantHostConfig.json]: The luminosity ratio of the label in name 'CHECK IN' and 'VIEW' buttons is not sufficient.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7374]
https://microsoft.visualstudio.com/OS/_workitems/edit/37985835

**Comment by Raisul123** [comment]
As per new guideline we are enhancing the severity. so we are closing this issue and logged new bug: https://github.com/microsoft/AdaptiveCards/issues/8479
