### ISSUE TITLE
[SampleCard-Agenda; Config-windows-timeline.json]: The color contrast ratio for graphical component 'LocationC image', 'CalendarConflict image', 'TravelByCar image' is not sufficient.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7381]
https://microsoft.visualstudio.com/OS/_workitems/edit/37988703

**Comment by Raisul123** [comment]
As per new guideline we are enhancing the severity. so we are closing this issue and logged new bug: [[SampleCard-Agenda; Config-windows-timeline.json]: The color contrast ratio for graphical component 'LocationC image', 'CalendarConflict image', 'TravelByCar image' is not sufficient. · Issue #8473 · microsoft/AdaptiveCards (github.com)](https://github.com/microsoft/AdaptiveCards/issues/8473)
