### ISSUE TITLE
[SampleCard-Agenda; Config-windows-timeline.json]: The color contrast ratio for text "1hr" and "about 45 minutes" in calendar conflicts is not sufficient.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7382]
https://microsoft.visualstudio.com/OS/_workitems/edit/37988784

**Comment by Raisul123** [comment]
As per new guideline we are enhancing the severity. so we are closing this issue and logged new bug: [[SampleCard-Agenda; Config-windows-timeline.json]: The color contrast ratio for text "1hr" and "about 45 minutes" in calendar conflicts is not sufficient. · Issue #8474 · microsoft/AdaptiveCards (github.com)](https://github.com/microsoft/AdaptiveCards/issues/8474)
