### ISSUE TITLE
[SampleCard-WeatherCompact; Config-Windows-timeline: The color contrast ratio for the text "Redmond, WA" is 2.82:1 which is not sufficient.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7384]
https://microsoft.visualstudio.com/OS/_workitems/edit/37989399

**Comment by Raisul123** [comment]
As per new guideline we are enhancing the severity. so we are closing this issue and logged new bug: [[SampleCard-WeatherCompact; Config-Windows-timeline: The color contrast ratio for the text "Redmond, WA" is 2.82:1 which is not sufficient. · Issue #8471 · microsoft/AdaptiveCards (github.com)](https://github.com/microsoft/AdaptiveCards/issues/8471)
