### ISSUE TITLE
[SampleCard-StockUpdate; Config-microsoft-teams-light.json]: The color contrast ratio for the text related to 'Rise in Stock' in green is having 2.07:1 is not sufficient.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7385]
https://microsoft.visualstudio.com/OS/_workitems/edit/37992132

**Comment by Raisul123** [comment]
As per new guideline we are enhancing the severity. so we are closing this issue and logged new bug: [[SampleCard-StockUpdate; Config-microsoft-teams-light.json]: The color contrast ratio for the text related to 'Rise in Stock' in green is having 2.07:1 is not sufficient. · Issue #8470 · microsoft/AdaptiveCards (github.com)](https://github.com/microsoft/AdaptiveCards/issues/8470)
