### ISSUE TITLE
[Inputs.json]: There is no announcement made by talkback or a visual information provided about the range of values the user can enter in the Quantity edit box.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7392]
https://microsoft.visualstudio.com/OS/_workitems/edit/38003560

**Comment by Raisul123** [comment]
As per new guideline we are enhancing the severity. so we are closing this issue and logged new bug: [[Inputs.json]: There is no announcement made by talkback or a visual information provided about the range of values the user can enter in the Quantity edit box. · Issue #8469 · microsoft/AdaptiveCards (github.com)](https://github.com/microsoft/AdaptiveCards/issues/8469)
