### ISSUE TITLE
[Inputs.json]: Keyboard focus moves to non interactive element in DatePicker under Due Date.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7393]
https://microsoft.visualstudio.com/OS/_workitems/edit/38004603

**Comment by Raisul123** [comment]
As per new guideline we are enhancing the severity. so we are closing this issue and logged new bug: [[Inputs.json]: Keyboard focus moves to non interactive element in DatePicker under Due Date. · Issue #8468 · microsoft/AdaptiveCards (github.com)](https://github.com/microsoft/AdaptiveCards/issues/8468)
