### ISSUE TITLE
[Usable: Designer>CARD STRUCTURE]: "Hide CARD STRUCTURE" button doesn't look like a hide or close button.

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/AdaptiveCards#7409]
https://microsoft.visualstudio.com/OS/_workitems/edit/30909992

**Comment by vagpt** [comment]
Now this issue is not repro , hence closing this issue.

![image](https://github.com/user-attachments/assets/9ad91b2d-8188-4484-b1fb-57fccdf62878)
