### ISSUE TITLE
Enable adding actions (buttons) in the middle of the card body (ActionSet, etc)

### ISSUE THREAD

**Issue by andrewleader** [microsoft/AdaptiveCards#743]
Quick Pair team would like to have buttons inside the body of their adaptive card

![image](https://user-images.githubusercontent.com/13246069/31154685-a45f52ec-a85d-11e7-92b5-c4af6f5da1df.png)

**Comment by andrewleader** [comment]
This was implemented with action set in 1.2, closing!

**Comment by Edwardfelix08** [comment]
Was this feature released?

**Comment by andrewleader** [comment]
Yes, it was released with Adaptive 1.2, which hosts are still working on updating to (Bot Framework WebChat has updated to 1.2 already!)

Here's the ActionSet docs: https://adaptivecards.io/explorer/ActionSet.html
