### ISSUE TITLE
[Rendering] iOS App crashing when rendering Adaptive Card

### ISSUE THREAD

**Issue by basti95** [microsoft/AdaptiveCards#7438]
### Target Platforms

iOS

### SDK Version

v1.0

### Application Name

Microsoft Teams

### Problem Description

Created Card as a response from custom Chatbot. The card renders just fine within MS Teams on MacOS.
However, every time the Chat with the regarding Bot is opened, the App crashes. 
I already reset the App-Data on iOS, still crashing every time. I am using the current version (4.7.1) on iOS.

### Card JSON

```JSON
{
	"lang": "en",
	"$schema": "https://adaptivecards.io/schemas/adaptive-card.json",
	"version": "1.0",
	"type": "AdaptiveCard",
	"body": [{
		"type": "TextBlock",
		"text": "Hello World!",
		"wrap": true
		},{
		"type": "Image",
		"url": "https://cataas.com/cat",
		"size": "auto",
		"spacing": "none"}

]}
```

Edit: Corrected Boolean from True to true, Json was created from python-dict with botbuilder for python

**Comment by jwoo-msft** [comment]
issue is not reproducible on ios sample app.

this appears to be Teams app specific issue.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/6114
