### ISSUE TITLE
[JS] Carousel doesn't work inside of a Web Component

### ISSUE THREAD

**Issue by paulcam206** [microsoft/AdaptiveCards#7440]
See [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/39087836) for repro. Short version is that the Carousel control doesn't quite work in the context of [Web Components](https://developer.mozilla.org/en-US/docs/Web/Web_Components) (next/previous doesn't work via mouse or keyboard). From what I understand, common issues here are:
* The script manipulating the DOM inside the component referencing elements outside of the component via `querySelector`, `getElementById`, etc.
* The inverse of the above (outside script attempting to get at elements inside the component)

I debugged a little bit and noticed that at least in the keyboard case, that swiper's underlying eventing module (called "dom7") checks to see if the control is in view before allowing the keystroke to go through. It does this by looking at viewport scroll position and location of the swiper control, but all of the sizes come back all zeroes. (Note: the in-viewport-only behavior is something we opt in to:

https://github.com/microsoft/AdaptiveCards/blob/d5020b143cc0f8185e08e33538c9a5b9a1047f5e/source/nodejs/adaptivecards/src/carousel.ts#L372-L375

Difficult to say for sure, but it looks like the mouse handlers aren't attached correctly in the component case. I tried updating to `swiper@8.1.4`, but it didn't appear to make a difference.

**Comment by jwoo-msft** [comment]
it's resolved as seen in the vso link.
