### ISSUE TITLE
[Rendering] Is it possible to open video in teams through adaptive card instead of redirecting to other tab

### ISSUE THREAD

**Issue by nameissainani** [microsoft/AdaptiveCards#7457]
### Target Platforms

Other

### SDK Version

1.3

### Application Name

teams

### Problem Description

Is it possible to open video in teams through adaptive card, instead of redirecting to other tab, i need the video to be played in teams, any solution appreciated.

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "Media",
            "sources": [
                {}
            ]
        }
    ]
}
```

### Sample Code Language

c#

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/6111
