### ISSUE TITLE
[Rendering] ReactNative cannot register custom column

### ISSUE THREAD

**Issue by feiyin0719** [microsoft/AdaptiveCards#7479]
### Target Platforms

Other

### SDK Version

2.2.24

### Application Name

Test app

### Problem Description

in ColumnSet, it use Column directly , so when we register my custom column, it will not work

### Card JSON

```JSON
N/A
```

**Comment by paulcam206** [comment]
We don't support registering custom `Column`s. If you want to override the behavior of `Column`, you need to register a custom `ColumnSet`.
