### ISSUE TITLE
[Rendering] Cards overlap on IPad

### ISSUE THREAD

**Issue by sueess** [microsoft/AdaptiveCards#7483]
### Target Platforms

iOS

### SDK Version

Adpative Card 1.4

### Application Name

Microsoft Teams

### Problem Description

Sometimes cards are not displayed right on iPad. On the screenshot you see how on card cuts the other and hides some of the content.

**IPad**
Version: 15.4.1
Model: IPad Air (4. Generation)

### Screenshots

![unnamed](https://user-images.githubusercontent.com/6587992/170236444-821b3b5e-c362-4846-8d37-a40dda6577bc.png)

### Card JSON

```JSON
Not related to the card.json
```

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/6110
