### ISSUE TITLE
[Designer] Feedback title here

### ISSUE THREAD

**Issue by sunzhenghe** [microsoft/AdaptiveCards#7491]
[Adaptive Cards] Target version:1.3,
powerAutomate work flow can not sendemail is successful.Why?

**Comment by paulcam206** [comment]
@rahulamlekar - care to take a look?

**Comment by paulcam206** [comment]
Please open an issue in the [Power Automate Community](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity), as this isn't an issue with Adaptive Cards itself.

**Comment by rahulamlekar** [comment]
Thanks for reaching out @sunzhenghe - The Power Apps team doesn't officially support sending Adaptive Cards via email. You can open an issue on the [Power Automate](https://github.com/MicrosoftDocs/power-automate-docs/) page for this request.
