### ISSUE TITLE
[Designer] Bug Adpative card values disappears when switch between tabs in MS Teams

### ISSUE THREAD

**Issue by midhunkumar22** [microsoft/AdaptiveCards#7492]
### Problem Description

when user types somthing and before clicking submit button if he changes the chat Adpative card values disappears in MS Teams when he comes back to the chat

### Card JSON

```JSON
{
"$schema": "http://adaptivecards.io/schemas/adpative-card.json",
"type": "AdpativeCard",
"version":"1.3",
"body":[
{
"type": "Input.text",
"lable": "Comments"
}
],
"actions":[
"type": "Action.Submit",
"tittle": "Submit",
"data" :{
   "id":"Test"
}
]
}
```

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/6174
