### ISSUE TITLE
[Feature Request] Add ability to add Card Type ID for User posts in teams

### ISSUE THREAD

**Issue by riley-momo** [microsoft/AdaptiveCards#7500]
### Problem Statement

Currently, the "Post adaptive card in a chat or channel" action in power automate does not allow the Post as: User option to see the advanced options where they can enter the Card Type ID to be handled by other flows. This is problematic in the case of service accounts and where enterprises restrict access to the Power Automate app within teams, meaning posts cannot go out through the flow bot.

### Proposed solution

Add the ability to specify Card Type ID as user with the existing action, or add this functionality in a more general way so many different adaptive cards, posted even outside of teams, can have this Card Type ID attribute added to them.

**Comment by paulcam206** [comment]
Please open an issue in the [Power Automate Community](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity), as this request isn't applicable to Adaptive Cards directly.
