### ISSUE TITLE
[Power Automate] Error 403 when using new Adaptive Card action "Update an adaptive card in chat or channel"

### ISSUE THREAD

**Issue by CDSFounder** [microsoft/AdaptiveCards#7501]
### Target Platforms

Other

### SDK Version

Latest

### Application Name

Microsoft Teams

### Problem Description

We would like to report an intermittent problem with this new action in Azure Logic Apps. We are seeing the following error when attempting to update an existing message posted to a channel via the "Post an adaptive card and wait for response" action:
{
  "error": {
    "code": 403,
    "message": "The ID of the user attempting to edit the message, ID:1f7c0b62-2c04-46ba-bdc0-a11bcee36ff1 does not match the actual user ID of the original sender, ID:",
    "source": "logic-apis-westus2.azure-apim.net",
    "path": "choose[6][\\when[1](file://when[1/)]",
    "policyId": "",
    "clientRequestId": "ca899974-1723-40c5-936e-5298044ec1bb"
  }
}
Note: The original message is sent by the PWA bot, and we are trying to update it as the PWA bot.

We have observed that if you run the same exact flow with the same exact data ~3 times, it will start steadily working without any error. After some time of not running the flow, it appears to give this error again for the first ~2 or ~3 runs. Originally, we added these actions to existing flows, but we were able to replicate this problem in a brand new flow with just two actions. To replicate this, we did the following:
1)	Create a new flow in Azure Logic Apps with a manual or HTTP trigger.
2)	Create action “Post an Adaptive Card and wait for response”. Use any sample or simple card with an action submit.
3)	Create an action “Update an adaptive card in chat or channel” and provide the Message ID from 2nd step by using @{body('PostAnAdaptiveCardName')?['messageId']}
4)	Run the flow and press the action.submit button in the corresponding Team channel. Observe that the flow will fail with the error 403 provided above.
a.	Run the flow without any changes a few more times and observe that the flow will start to work without error.

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.4",
    "body": [
        {
            "type": "Container",
            "style": "good",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "CARD WAS UPDATED",
                    "wrap": true
                }
            ]
        }
    ]
}
```

**Comment by paulcam206** [comment]
@CDSFounder - please open an issue in the [Power Automate Community](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity), as this isn't an issue with Adaptive Cards itself.

**Comment by truespinmice** [comment]
just for the record -> issue opened in the PA Community: https://github.com/microsoft/PowerPlatformConnectors/issues/1887
