### ISSUE TITLE
[Website] Voice Access is showing numbers on all non-interactive labels like Software, etc. under 'All Microsoft' combo box.

### ISSUE THREAD

**Issue by Shireen2000** [microsoft/AdaptiveCards#7504]
### Target Platforms

Other

### SDK Version

103

### Application Name

Adaptive Card

### Problem Description

https://microsoft.visualstudio.com/OS/_queries/edit/39920026/?triage=true

Test Environment:
OS: 22H2 (OS Build 25120.1000)
Browser: Edge Dev
Browser Version: Version 103.0.1255.0 (Official build) dev (64-bit)
URL: [Adaptive Cards](https://adaptivecards.io/)
Tool: Voice Access

Repro Steps:
Launch the above URL.
Navigate to 'All Microsoft' and activate it to expand.
Command: "Voice access wake up"
Command: "Show Numbers"
Observe the issue for the labels.
Actual Result:
Voice Access is showing numbers on all non-interactive labels like Software, etc. under 'All Microsoft' combo box.

Expected Result:
Voice Access should not show numbers for all non-interactive labels like Software, etc. under 'All Microsoft' combo box.

Observation: 'IsKeyboardFocusable' property is set as 'True' for 'Software' label.

User Experience:

People with limited mobility (cerebral palsy, quadriplegia) who use Voice Access to use OneNote may not be able edit or type they will find difficulty in accessing 'Canvas area' and 'Canvas Title' edit field. Voice access users will get impact and will not able to interact with controls with pre-defined Voice access commands.
 
MAS Reference:
[No Disruption of Accessibility Features - Liquid (microsoft.com)](https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/04.03.01)
 
Have feedback to share on Bugs? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-chisha%40microsoft.com%7c1334b110f98744a7f5df08d968eb842b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656183104980596%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=r4ndSHk/LrBDwzi7FO%2BjKN0DCnqUSUcELBvGRkgc5CU%3D&reserved=0)"

To learn more about Voice Access and how an application can support its different modes, Refer: [VoiceAccess Testing - OSGWiki](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fwww.osgwiki.com%2fwiki%2fVoiceAccess_Testing&data=05%7c01%7cv-shiwasi%40microsoft.com%7c00297be07a15467b634408da325a247c%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637877659989570305%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=sQj%2Bb4UzcB2jUBsX3r%2f4%2BjkjzUrXncXKGhGCIuu8vc4%3D&reserved=0)

### Card JSON

```JSON
NA
```

**Comment by Shireen2000** [comment]
https://user-images.githubusercontent.com/96283152/173513921-155ac7a8-a3b1-447d-ac3d-9617676a1464.mp4
![MAS4 3 1 - Showng mubers for non interactive labels under All microsoft Code](https://user-images.githubusercontent.com/96283152/173513981-1f23cc76-3534-4935-a45c-ceaa43465432.png)
![MAS4 3 1 - Showng mubers for non interactive labels under All microsoft](https://user-images.githubusercontent.com/96283152/173513993-c52e7611-b72a-41b8-8153-d044879c6778.png)

**Comment by anna-dingler** [comment]
@paulcam206 It looks like we need to update `header.ejs` and `footer.ejs`. 

For this issue, the non-interactive button has been switched to span on the (microsoft website)[https://www.microsoft.com/en-us/], so we are likely behind.

**Comment by vagpt** [comment]
Adding A11yTTValidated tag as issue is not repro.
