### ISSUE TITLE
[Navigate to and select "Input.Time" list item in "Inputs" section.]: Voice Access is not showing numbers for 'Option 1' present under 'Please make selection' combo box

### ISSUE THREAD

**Issue by Shireen2000** [microsoft/AdaptiveCards#7505]
### Target Platforms

Other

### SDK Version

103

### Application Name

Adaptive Card

### Problem Description

https://microsoft.visualstudio.com/OS/_queries/edit/39920272/?triage=true

Test Environment:
OS: 22H2 (OS Build 25120.1000)
Browser: Edge Dev
Browser Version: Version 103.0.1255.0 (Official build) dev (64-bit)
URL: [Adaptive Cards](https://adaptivecards.io/)
Tool: Voice Access

Repro Steps:
Launch the above URL.
Command: "Voice access wake up"
Command: "Click Schema Explorer" for the top header.
Command: 'Click Input.time' from under 'Inputs' label.
Navigate till the second card present under this page.
Command: 'Show Numbers'.
Expand 'Please make selection' combo box.
Command: 'Show Numbers'.
Observe the issue for 'Option 1'.
Actual Result:
Voice Access is not showing numbers for 'Option 1' present under 'Please make selection' combo box.

Expected Result:
Voice Access should show numbers for 'Option 1' present under 'Please make selection' combo box.

Note: This issue is repro throughout this page.

Observation: 'IsKeyboardFocusable' property is set as 'True' for 'Option 1'.

User Experience:

People with limited mobility (cerebral palsy, quadriplegia) who use Voice Access to use OneNote may not be able edit or type they will find difficulty in accessing 'Canvas area' and 'Canvas Title' edit field. Voice access users will get impact and will not able to interact with controls with pre-defined Voice access commands.
 
MAS Reference:
[No Disruption of Accessibility Features - Liquid (microsoft.com)](https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/04.03.01)
 
Have feedback to share on Bugs? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-chisha%40microsoft.com%7c1334b110f98744a7f5df08d968eb842b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656183104980596%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=r4ndSHk/LrBDwzi7FO%2BjKN0DCnqUSUcELBvGRkgc5CU%3D&reserved=0)"

To learn more about Voice Access and how an application can support its different modes, Refer: [VoiceAccess Testing - OSGWiki](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fwww.osgwiki.com%2fwiki%2fVoiceAccess_Testing&data=05%7c01%7cv-shiwasi%40microsoft.com%7c00297be07a15467b634408da325a247c%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637877659989570305%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=sQj%2Bb4UzcB2jUBsX3r%2f4%2BjkjzUrXncXKGhGCIuu8vc4%3D&reserved=0)

### Card JSON

```JSON
NA
```

**Comment by Shireen2000** [comment]
https://user-images.githubusercontent.com/96283152/173514358-11f2ebee-401c-4444-a17b-f2a4247aa851.mp4
![MAS4 3 1 - Not showing number for 
![MAS4 3 1 - Not showing number for Option 1](https://user-images.githubusercontent.com/96283152/173514419-320c3ab1-9287-4cee-a8b5-ec1f16491cde.png)
Option 1 Code](https://user-images.githubusercontent.com/96283152/173514408-6b9c0f29-bdd4-42e0-b93a-32277688c78c.png)

**Comment by anna-dingler** [comment]
We utilize the HTML select element for this control, so we have less control over its behavior.

This is error also occurs within [documentation examples](https://developer.mozilla.org/en-US/docs/web/html/element/select) for the control.

@carlos-zamora Do you have ideas for how to fix this? Since the elements are already focusable, I'm not sure if there's a workaround.

**Comment by anna-dingler** [comment]
Closing the issue since we determined offline that this is an issue with Voice Access.
