### ISSUE TITLE
Many discrepancies between json-schema and html doc

### ISSUE THREAD

**Issue by jsw** [Microsoft/AdaptiveCards#751]
The html page is not super useful as it's missing tons of types and has many discrepancies with the json-schema. From the github activity, it looks like the schema has been finalized for the next version. Is the json-schema the authority?

https://github.com/Microsoft/AdaptiveCards/blob/master/schemas/adaptive-card.json
https://docs.microsoft.com/en-us/adaptive-cards/create/cardschema

**Comment by matthidinger** [comment]
Hi @jsw, sorry about the confusion. The docs and JSON-schema should be aligned (specifically since the docs are actually generated from the JSON-schema). Can you tell me some discrepancies you are seeing? I know most of the "enum" values are missing but are there other gaps you've seen?

**Comment by jsw** [comment]
@matthidinger My bad! I am new to interpreting json-schema. I now realize that some of the `AdaptiveCard` properties are defined at the root level:

https://github.com/Microsoft/AdaptiveCards/blob/master/schemas/adaptive-card.json#L12-L29

and some are defined in the `AdaptiveCard` definition itself:

https://github.com/Microsoft/AdaptiveCards/blob/master/schemas/adaptive-card.json#L134-L150

This issue can be closed, but I couple follow-up questions on the json-schema structure: 

1. What is the intention and resulting semantics of that separation?
1. Why is there a `CardElements` type instead of `AdaptiveCard.body` being an array of `CardElement`?

Thanks for the insights.

**Comment by matthidinger** [comment]
The separation is due to the fact that CardElements can be re-used inside Containers/Columns, and for AdaptiveCard some properties can be used inside a `ShowCard.card` and the `version` property for example doesn't apply in there. Please re-open if you have further questions!
