### ISSUE TITLE
[.NET][Templating] I can't use adaptive card 1.5

### ISSUE THREAD

**Issue by mgood2** [microsoft/AdaptiveCards#7511]
### Target Platforms

Other

### SDK Version

AdaptiveCards 2.7.3, AdaptiveCards 1.3.1

### Application Name

Chatbot

### Problem Description

We have been creating AdaptiveCard object.
`var card = new AdaptiveCard(new AdaptiveSchemaVersion(1, 0)){};`
We need to use the new feature from v1.5 template. I updated latest version from nuget.
And changed to 
`var card = new AdaptiveCard(new AdaptiveSchemaVersion(1, 5)){};`
When I try in Bot Framework Emulator and chatbot react app, it fails.

### Card JSON

```JSON
I am not using json.
lots of logic are involved in the C# side.
```

### Sample Code Language

C#

### Sample Code

```
var card = new AdaptiveCard(new AdaptiveSchemaVersion(1, 0))
                {

                    Speak = _"Hello"
                    Body =
                    {
                        new AdaptiveTextBlock
                        {
                            Text = "Hello"
                        }
                    },
                    Actions = _welcomeActions
                };
```
To
```
var card = new AdaptiveCard(new AdaptiveSchemaVersion(1, 5))
                {

                    Speak = _"Hello"
                    Body =
                    {
                        new AdaptiveTextBlock
                        {
                            Text = "Hello"
                        }
                    },
                    Actions = _welcomeActions
                };
```

**Comment by paulcam206** [comment]
@mgood2 - what kind of failure are you seeing? exception? error message?

**Comment by paulcam206** [comment]
Closing due to lack of response. Please reactivate with more information if this issue is still relevant.
