### ISSUE TITLE
[AC New Feature] Telemetry tracking for Carousel component (page switch and time spent on page)

### ISSUE THREAD

**Issue by KesemZ** [microsoft/AdaptiveCards#7512]

**Comment by KesemZ** [comment]
Check with Dashboard - they would be able to expose this telemetry if we provide them with appropriate hooks

**Comment by JeanRoca** [comment]
| Capability      | Priority |
| ----------- | ----------- |
| Event for when user clicks the next arrow on the carousel | Must |
| Event for when a user clicks the previous arrow on the carousel | Must |
| Event for when a user navigates the carousel with the bottom dots | Must |
| Which carousel pages did the user see vs not see | Must |
| How much time a user spent on a carousel and which page | Must |
| How long did the user hover over the page | Could |
| Event for when user clicks on something in the carousel that might not be an action (i.e. highlighting text) | Could |
