### ISSUE TITLE
UWP Bug: Cannot set "spacing": "padding"

### ISSUE THREAD

**Issue by anbare** [Microsoft/AdaptiveCards#753]
In the v1.0 schema, "padding" is supposed to be one of the options card authors can use on their card elements for the spacing property: `"spacing": "padding"`.

However on UWP the card fails to render if the payload uses that.

```json
{
    "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "This is some text"
        },
        {
            "type": "TextBlock",
            "text": "Using \"padding\" spacing",
            "weight": "bolder",
            "spacing": "padding"
        }
    ]
}
```

Similarly, in the HostConfig, if the HostConfig specifies *actions->spacing "padding"*, that also causes HostConfig to fail

```json
{
  "actions": {
    "maxActions": 5,
    "spacing": "default",
    "buttonSpacing": 10,
    "showCard": {
      "actionMode": "inline",
      "inlineTopMargin": 16
    },
    "actionsOrientation": "horizontal",
    "actionAlignment": "stretch"
  }
}
```

**Comment by matthidinger** [comment]
@dclaux wasn't this named "cardPadding" originally? It seems a little clearer with what padding it's referring to

**Comment by anbare** [comment]
Ping @dclaux @matthidinger this schema needs to be locked if devs are going to implement this

**Comment by dclaux** [comment]
@matthidinger it was always named "padding" since introduced. I am fine renaming to "cardPadding" if really necessary. The term "padding" was chosen because that's the padding that's applied everywhere padding is needed, not just at the card level.
