### ISSUE TITLE
[Rendering] iOS integration through SPM don't work

### ISSUE THREAD

**Issue by NicolasLourenco** [microsoft/AdaptiveCards#7550]
### Target Platforms

iOS

### SDK Version

latest

### Application Name

Test app

### Problem Description

When I add the dependency in SPM, the framework don't compile.

### Screenshots

<img width="594" alt="Capture d’écran 2022-06-20 à 17 13 53" src="https://user-images.githubusercontent.com/6010156/174632906-a0e3bce7-4e6b-464b-8e45-0d2e0e0ef1d6.png">

**Comment by jwoo-msft** [comment]
Thanks, @NicolasLourenco for reporting this issue, I will get back to you soon.

**Comment by fabianwilliams** [comment]
hello @NicolasLourenco Ive communicated with the engineer tasked with this work and this work has been approved to be worked on, I do not have a date of estimated completion yet but will be keeping tabs on this.

**Comment by RiddhiTharewal23** [comment]
@jwoo-msft I added 2.8.1 version but I am getting below error

<img width="666" alt="Image" src="https://github.com/user-attachments/assets/304cb7cf-b136-434d-8c4b-671eb1eb1504" />

I see localization is added in 2.9.0 version of IOS but I still get same error
