### ISSUE TITLE
[iOS][Rendering] ImageSet is occupying the full width

### ISSUE THREAD

**Issue by aksagarw** [microsoft/AdaptiveCards#7557]
### Target Platforms

iOS

### SDK Version

Commit- https://github.com/microsoft/AdaptiveCards/commit/9c514851cb4a780dcb654b8c89b9f9d24c77c680

### Application Name

Webex

### Problem Description

ImageSet Component is always occupying the full width of card, because of that the adjacent elements are going out of the screen.

Even if the ImageSet's parent (Column in this case) is setting the width to "auto", imageset is behaving like "Stretch". Same Json is able to render the card correctly in Web.

### Screenshots

![IMG_8096](https://user-images.githubusercontent.com/84726200/174954414-fb473b67-8ca0-46b0-9535-5a4796319d46.jpeg)

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "width": "auto",
                    "items": [
                        {
                            "type": "ImageSet",
                            "images": [
                                {
                                    "type": "Image",
                                    "url": "https://www.webex.com/content/dam/wbx/us/images/rebrand/webex-logo.png",
                                    "width": "50px",
                                    "size": "Medium"
                                }
                            ]
                        }
                    ]
                },
                {
                    "type": "Column",
                    "width": "stretch",
                    "items": [
                        {
                            "type": "TextBlock",
                            "text": "Test Card"
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by jwoo-msft** [comment]
I can't repro this issue on iOS.
![Screenshot 2023-01-03 at 1 01 44 PM](https://user-images.githubusercontent.com/4112696/210441166-58f87f8c-f12f-4230-a2ba-9df1c89d69bb.png)
