### ISSUE TITLE
[Adaptive Cards> ExpencesReport.json]: Voice Over does not convey the convey the role for the 'Show History'.

### ISSUE THREAD

**Issue by vagpt** [microsoft/AdaptiveCards#7590]
### Target Platforms

iOS

### SDK Version

Version 1.0 (2.3.1-beta.20220620.1)

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
Device: iPhone 11
iOS: 15.5
Application: Adaptive Cards
App Version: 1.0 (2.4.0-beta.20220612.1)
Screen Reader: Voice Over

**Repro Steps:**
1. Launch Adaptive Cards iOS application.
2. Home screen will appear.
3. Activate Voice over
4. Navigate to "V1.2" control and select it.
5. Navigate to 'Scenarios' control and activate it.
6. Navigate to 'ExpencesReport.json' and activate it.
7. Navigate to the 'Show History'
 and observe the issue.

**Actual Result:**
Voice over is not conveying the role for the 'Show History'. It is announcing only as **'Show History'**.

**Expected Result:**
Voice over should convey the role of the 'Show History' as 'Button'.

**User Experience:**
It will impact the screen reader user if the screen reader does not convey the role of any controls on the screen as user won't be able to understand the basic functionality of the control. 

**MAS Reference:**
https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/04.01.02

"Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “

### Screenshots

Uploading MAS4.1.2-Voice Over does not convey the convey the role for the 'Show History'..MP4…

### Card JSON

```JSON
NA
```

**Comment by jwoo-msft** [comment]
closing it since it's a duplicated issue.
https://github.com/microsoft/AdaptiveCards/issues/6295

**Comment by vagpt** [comment]
Verified this issue as this issue is duplicate of #6295

**Comment by vagpt** [comment]
Adding A11yTTValidated tag as its duplicate bug is in closed state.
