### ISSUE TITLE
{Freeway-Bug} [Adaptive Card > RestaurantOrder.Json]: After typing any character on the edit field, on screen keyboard is getting disappeared. 

### ISSUE THREAD

**Issue by vagpt** [microsoft/AdaptiveCards#7601]
### Target Platforms

iOS

### SDK Version

Version 1.0 (2.4.0-beta.20220628.3)

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
Device: iPhone 11
iOS Version: 15.5
Screen Reader: Voice Over

**Repro Steps:**
1. Launch Adaptive Cards iOS application.
2. Home screen will appear.
3. Navigate to "V1.5" control and select it.
4. Navigate on "V1.5" screen and select "Scenarios" button.
5. 'Scenario' screen will appear.
6. Navigate to "RestaurantOrder.json" control and double tap to activate it.
7. Navigate to the 'Please Choose' edit field under 'Which entry would you like?'.
8. Double tap to edit and type some character and observe the issue.

**Actual Result:**
While navigating to edit field under 'Which entry would you like?' on typing some character on screen keyboard is getting disappeared.

**Expected Result:**
On screen keyboard should not be disappeared while typing any character under edit field under 'Which entry would you like?'

**Note:**
1. After selecting any option from the list focus is going on hidden element as well.
2. This issue is repro without swipe gesture as well. As on typing any character manually it is also getting disappeared.
 
**User Experience:**
It will impact the screen reader user if the on screen keyboard will disappear every time while typing any character in edit search field.
 
**MAS Reference:**
https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/04.03.01

"Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “

### Screenshots

https://user-images.githubusercontent.com/95913748/176640988-b7399f83-1b21-4330-853d-4ec7060ddf4d.MP4

### Card JSON

```JSON
NA
```

**Comment by jwoo-msft** [comment]
@vagpt 
Thanks for reporting this issue.

**Comment by vagpt** [comment]
This issue is working fine on the environment, hence closing this issue.

**Test Environment:**
Device: iPhone 11
iOS Version: 16.4
App Version: 1.0(2.4.0-beta.23.4.23.1)
