### ISSUE TITLE
[Authoring] findDOMNodeOwner function cannot find Action on the CardElement itself

### ISSUE THREAD

**Issue by compulim** [microsoft/AdaptiveCards#7606]
### Target Application

Web browser

### Application Operating System

Windows

### Schema Version

1.5

### Problem Description

When calling `card.findDOMNodeOwner` with a HTML element representing an `Action` *directly* on the card (not `ActionSet`), it return `CardElement`. However, when calling with an `Action` inside `ActionSet`, it return the `Action` object.

In the code snippet below, we have 2 buttons:

1. An `Action` inside an `ActionSet` on the body of the card, it say "Aloha!"
2. An `Action` attached below the card, it say "Hello, World!"

When calling `findDOMNodeOwner`, the result is respectively:

1. The `Action` object, this is correct
2. The `CardElement` object (i.e. the root card), this is incorrect

Also, note this issue also applies to `Action` inside the `Action.ShowUrl`, where the `findDOMNodeOwner` is also `AdaptiveCard`, not the actual `Action`.

### Expected Outcome

I believe the 2nd result should be the `Action` object from the `CardElement`, i.e. same as `card.getActionAt(0)`.

### Actual Outcome

The root `CardElement`.

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.OpenUrl",
                    "title": "Aloha!",
                    "url": "https://bing.com/"
                }
            ]
        }
    ],
    "actions": [
        {
            "type": "Action.OpenUrl",
            "title": "Hello, World!",
            "url": "https://bing.com/"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5"
}
```

### Repro Steps

```js
const card = new AdaptiveCard();

card.parse({
  type: 'AdaptiveCard',
  body: [
    {
      type: 'ActionSet',
      actions: [
        {
          type: 'Action.OpenUrl',
          title: 'Aloha!',
          url: 'https://bing.com/'
        }
      ]
    }
  ],
  actions: [
    {
      type: 'Action.OpenUrl',
      title: 'Hello, World!',
      url: 'https://bing.com/'
    }
  ],
  $schema: 'http://adaptivecards.io/schemas/adaptive-card.json',
  version: '1.5'
});

const [firstButton, secondButton] = card.render().querySelectorAll('.ac-pushButton');

expect(firstButton.innerText).toBe('Aloha!');
expect(secondButton.innerText).toBe('Hello, World!');

const firstCardObject = card.findDOMNodeOwner(firstButton);
const secondCardObject = card.findDOMNodeOwner(secondButton);

expect(firstCardObject.toJSON()).toHaveProperty('type', 'Action.OpenUrl');
expect(secondCardObject.toJSON()).toHaveProperty('type', 'Action.OpenUrl'); // This line failed, the "type" expected to be "Action.OpenUrl", however, actual is "AdaptiveCard".
```

**Comment by beervoley** [comment]
thanks @compulim for submitting the issue :)
we'll have a look soon :)
