### ISSUE TITLE
[Designer] [Bug 40020188](https://microsoft.visualstudio.com/OS/_workitems/edit/40020188): [ProductVideo.json-Video Slider.]: Screen reader is not announcing instant feedback when change values with the help of slider.

### ISSUE THREAD

**Issue by aaagrawal** [microsoft/AdaptiveCards#7611]
### Problem Description

[Bug 40020188](https://microsoft.visualstudio.com/OS/_workitems/edit/40020188): [ProductVideo.json-Video Slider.]: Screen reader is not announcing instant feedback when change values with the help of slider.

### Card JSON

```JSON
[Bug 40020188](https://microsoft.visualstudio.com/OS/_workitems/edit/40020188): [ProductVideo.json-Video Slider.]: Screen reader is not announcing instant feedback when change values with the help of slider.
```

**Comment by vagpt** [comment]
Closing this issue as of now this issue is repro'ing intermittent at our end.
