### ISSUE TITLE
[Designer] Bug 35353022: [Adaptive Cards - ExpenseReport.Json]: 'Reject' button in 'Expense Approval' card is not performing any action when activated using keyboard.

### ISSUE THREAD

**Issue by aaagrawal** [microsoft/AdaptiveCards#7621]
### Problem Description

[Bug 35353022](https://microsoft.visualstudio.com/OS/_workitems/edit/35353022): [Adaptive Cards - ExpenseReport.Json]: 'Reject' button in 'Expense Approval' card is not performing any action when activated using keyboard.

Test Environment:
Application: Adaptive Cards
OS Version: 21H2 (OS Build 22000.132)
Application Version: 2.7.2108.2001

Repro steps:
Launch the Adaptive Card application.
Adaptive Card UWP Visualizer screen starts appearing. 
Navigate to ExpenseReport.Json button by using Tab key and activate it using Enter key.
Expense approval adaptive card will be appeared on right sight of the pane.
Navigate to Expense approval card by using Tab key.
Navigate to 'Reject' button using Tab key and activate it using Enter key
Observe the issue.
Actual Result:
'Reject' button in 'Expense Approval' card is not performing any action when activated using keyboard.
Even on clicking using mouse no action is taking place.

Expected Result:
'Reject' button in 'Expense Approval' card should perform action when activated using keyboard.
Also it should perform action when clicked through mouse.

User Experience:
User who rely on AT will face difficulty if 'Reject' button in 'Expense Approval' card is not performing any action when activated using keyboard or mouse.

Note:
This issue is also repro for 'Show Cards' button under Inputs.Json.

### Card JSON

```JSON
Designer Bug. Repro on latest UWP Adaptive Card visualizer
```

**Comment by paulcam206** [comment]
The `Reject` button isn't an action like `Accept` -- it displays additional UI for the user (you may need to tab or scroll down).

This behavior is working as intended.

**Comment by vaishali1397** [comment]
Closing this bug as per above comment that The Reject button isn't an action like Accept -- it displays additional UI for the user (you may need to tab or scroll down).

This behavior is working as intended.

![image](https://user-images.githubusercontent.com/104483005/235417717-f274ba22-6fb2-4e1f-bfed-79e8819677b4.png)
