### ISSUE TITLE
[Designer] Bug 33489084: [Adaptive Cards - FlightUpdate.Json]: Screen reader focus jumps to the decorative image under the FlightUpdate.Json card in scan mode by using up and down arrow key.

### ISSUE THREAD

**Issue by aaagrawal** [microsoft/AdaptiveCards#7627]
### Problem Description

[Bug 33489084](https://microsoft.visualstudio.com/OS/_workitems/edit/33489084): [Adaptive Cards - FlightUpdate.Json]: Screen reader focus jumps to the decorative image under the FlightUpdate.Json card in scan mode by using up and down arrow key.

Test Environment:

Application: Adaptive Cards
OS version: Dev (OS Build 21387.1)

Application Version: 2.7.2105.11001

Screen Reader: Narrator

Repro steps:

1. Launch the Adaptive Card application and narrator.

2. Adaptive Card UWP Visualizer screen starts appearing. 

3. Navigate to FlightUpdate.Json button by using Tab key and activate it.

4. FlightUpdate adaptive card will be appeared on right sight of the pane.

5. Navigate to FlightUpdate card by using Tab key.

6. Navigate in scan mode and observe the issue.

Actual Result:
Screen reader focus jumps to the decorative image under the  FlightUpdate.Json card in scan mode by using up and down arrow key. Narrator announces only Image when focus jump to the decorative image.

Expected Result:
Screen reader focus should not jumps to the decorative image by using up and down arrow key.

User Experience:
Screen reader users will be impacted if screen reader focus will jump to the decorative image in scan mode.

Observation:
NVDA(2022.4) and JAWS(2021) scan mode is not working on Adaptive Cards.

### Card JSON

```JSON
Designer Bug. Repro on UWP Adaptive Card visualizer
```

**Comment by vagpt** [comment]
This issue is not repro, hence closing this issue.

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/ce1c994e-f755-45e7-99fc-7d672ff2443c)
