### ISSUE TITLE
[Designer] Bug 33488858: [Adaptive Cards - ExpenseReport.Json]: The name property of focusable element must not be NULL.

### ISSUE THREAD

**Issue by aaagrawal** [microsoft/AdaptiveCards#7628]
### Problem Description

[Bug 33488858](https://microsoft.visualstudio.com/OS/_workitems/edit/33488858): [Adaptive Cards - ExpenseReport.Json]: The name property of focusable element must not be NULL.

Test Environment:

Application: Adaptive Cards
OS version: Dev (OS Build 21387.1)

Application Version: 2.7.2105.11001

Tool Used: Accessibility Insights 

Repro steps:

1. Launch the Adaptive Card application.

2. Adaptive Card UWP Visualizer screen starts appearing. 

3. Navigate to ExpenseReport.Json button by using Tab key and activate it.

4. Expense approval adaptive card will be appeared on right sight of the pane.

5. Navigate to Expense approval card by using Tab key.

6. Navigate to 'Show History' button with Tab key.

7. Run K4D on Show History button and verify the issue.

Actual Result:
Name property is defined NULL of 'Show History' button.

Expected Result:
Name property must be defined for the 'Show History' button.

User Experience:
It will not impact the screen reader users if Name property of any control will be defined NULL.

### Card JSON

```JSON
Designer Bug. Repro on UWP Adaptive Card visualizer
```

**Comment by vagpt** [comment]
Hi @anna-dingler 

This issue is still repro at our end so is there any plan whether Dev will work on it or not?

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/d5c2e73a-7508-4bec-965b-7a4de440d81b)

**Comment by anna-dingler** [comment]
Hi @vagpt,

I will speak with my team about budgeting for this bug.

Thanks,
Anna

**Comment by vagpt** [comment]
This issue is now tracking with #9076 hence closing this issue here.
