### ISSUE TITLE
[Designer]Bug 31601166: [Usable - Adaptive Cards - FlightItinerary.JSON]: Narrator focus jumps to the hidden control while navigating in scan mode by using up and down arrow key.

### ISSUE THREAD

**Issue by aaagrawal** [microsoft/AdaptiveCards#7631]
### Problem Description

[Bug 31601166](https://microsoft.visualstudio.com/OS/_workitems/edit/31601166): [Usable - Adaptive Cards - FlightItinerary.JSON]: Narrator focus jumps to the hidden control while navigating in scan mode by using up and down arrow key.

User Experience:

It will not impact the screen reader users if Narrator focus jumps to the hidden control while navigating in scan mode by using up and down arrow key.

Test Environment:

Application: Adaptive Cards
OS version: 2004 (OS Build 21301.1000)

Application Version: 2101.28.1.0

Tool Used: Accessibility Insights 

Pre-Requisite: Launch the Adaptive Card application.

Repro steps:

1. Launch the Adaptive Card application and Enable Narrator.

2. Adaptive Card UWP Visualizer screen starts appearing. 

3. Navigate to FlightItinerary.JSON button and activate it.

4. Adaptive card will be appeared on right pane.

4. Press down arrow key just after AMS text and verify the issue.

Actual Result:

Narrator focus jumps to the hidden control while navigating in scan mode by using up and down arrow key. While forward navigation narrator announces 'No next text' and backward navigation narrator announces 'No previous text'.

Expected result:

Narrator focus should not jumps to the hidden control while navigating in scan mode by using up and down arrow key.

### Card JSON

```JSON
Designer Bug. Repro on UWP Adaptive Card visualizer
```

**Comment by vagpt** [comment]
Now, this issue is tracking with below bug hence closing this issue.

#8979
