### ISSUE TITLE
[Designer] Bug 31586004: [Usable - Adaptive Cards - Agenda.Json]: Screen reader focus jumps to the decorative image under the Agenda card in scan mode by using up and down arrow key.

### ISSUE THREAD

**Issue by aaagrawal** [microsoft/AdaptiveCards#7635]
### Problem Description

[Bug 31586004](https://microsoft.visualstudio.com/OS/_workitems/edit/31586004): [Usable - Adaptive Cards - Agenda.Json]: Screen reader focus jumps to the decorative image under the Agenda card in scan mode by using up and down arrow key.

User Experience:

Screen reader users will be impacted if screen reader focus will jump to the decorative image in scan mode.

Test Environment:

Application: Adaptive Cards
OS version: 2004 (OS Build 21301.1000)

Application Version: 2101.28.1.0

Pre-Requisite: Launch the Adaptive Card application.

Repro steps:

1. Launch the Adaptive Card application and Enable Narrator.

2. Adaptive Card UWP Visualizer screen starts appearing. 

3. Navigate to Agenda.Json button and activate it.

4. Agenda Card will be appeared on right sight of the pane.

5. Switch narrator into scan mode.

6. Navigate Agenda adaptive card by using up and down arrow key and verify the issue.

Actual Result:

Screen reader focus jumps to the decorative image under the Agenda card by using up and down arrow key in scan mode. Narrator announces only Image when focus jump to the decorative image.

Note:
Same issue is repro'ing under the FlightDetails.Json adaptive card. Refer the attachment.

Expected result:

Screen reader focus should not jumps to the decorative image by using up and down arrow key.

Observation:
NVDA scan mode is not working on Adaptive Cards

### Card JSON

```JSON
Designer Bug. Repro on UWP Adaptive Card visualizer
```

**Comment by vagpt** [comment]
This issue is not repro on 1.0.2.0 build hence closing this issue.
