### ISSUE TITLE
[Adaptive Cards-Header control]: On resizing the page to 400% horizontal scroll bar is appearing on the page.

### ISSUE THREAD

**Issue by Susmitha474** [microsoft/AdaptiveCards#7641]
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive Cards

### Problem Description

Test Environment:
URL: https://adaptivecards.io/
OS: Version 21H2 (OS Build 22000.318)
Edge Dev: version 105.0.1300.0 (Official build) dev (64-bit)

Pre-Requisites:
1. Change Display Resolution to 1024* 768.
2. Zoom the page to 400%

Repro steps:
1. Launch the above URL in edge dev browser and login with v- credentials.
2. Navigate to Documentation, Schema Explorer, Samples, Blog and Designer links under 'Adaptive Cards' through tab key under the header controls.
3. Verify that on resizing the page to 400% horizontal scroll bar is appearing on the page or not.

Actual Result:
On resizing the page to 400% horizontal scroll bar is appearing on the page.

Expected Result:
On resizing the page to 400% horizontal scroll bar should not appear on the page.

User Experience:
User with visual disability will have difficulty in clearly identifying and in seeing the content as to view the content properly user needs to scroll horizontal scroll bar which create difficulty for the user if on resizing the page to 400% horizontal scroll bar is appearing on the page.

MAS Reference Link:
[Reflow - Liquid (microsoft.com)](https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/01.04.10)

"Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “,

### Screenshots

![Horizontal and Verticle scrollbars are present in 400% Zoom settings](https://user-images.githubusercontent.com/104482612/177274242-dcc231bf-5941-4d24-8239-9adeb7fa369c.png)

### Card JSON

```JSON
NA
```

### Sample Code Language

NA

### Sample Code

NA

**Comment by vagpt** [comment]
This issue is not repro, hence closing this issue.
