### ISSUE TITLE
[AdaptiveCards- Schema Explorer]: Focus is moving on to the 'Inherited Properties' text which is non-Interactive element.

### ISSUE THREAD

**Issue by Susmitha474** [microsoft/AdaptiveCards#7643]
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive Cards

### Problem Description

Test Environment:

OS: Version 21H2 (OS Build 22000.318)

URL: [https://adaptivecards.io/](https://nam06.safelinks.protection.outlook.com/?url=https://adaptivecards.io/&data=04%7c01%7cv-ibalam%40microsoft.com%7cbd35d875ec3f4539762308d88f709775%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637417061036711036%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=dUolQbKGi1J8gsoxC2JG5TGoNi41msPfIIjKSIyPGHM%3D&reserved=0)

Edge Dev: version 105.0.1300.0 (Official build) dev (64-bit)

Screen Reader: Narrator

Repro Steps:

1. Open above URL with valid credential.

2. Turn on the Narrator using ctrl+win+enter key.

3. Navigate to 'Schema Explorer' link and press tab key to activate it.

4. Activate 'RichText Block' card element from the left pane with 'Enter' key.

5. Now Navigate to 'Inherited Properties' with 'Tab' key and observe the issue.

 

Actual Result:
Key board focus is moving on to the 'Inherited Properties' heading and Screen Reader conveys incorrect role for the 'Inherited Properties' as 'Inherited Properties Link'.

Expected Result:
'Inherited Properties' is an non-interactive element and it should not get keyboard focus when navigating using tab key.

User Experience:
Keyboard and screen reader user will affect if keyboard focus is going to non-interactive heading "Inherited Properties" text and announce as Link.

MAS Reference:
https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/02.04.03

"Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “.

### Screenshots

https://user-images.githubusercontent.com/104482612/177701111-74b31c92-6c51-472d-97f8-d7908cda6937.mp4

### Card JSON

```JSON
NA
```

### Sample Code Language

NA

### Sample Code

NA

**Comment by anna-dingler** [comment]
Upon investigation, `Inherited properties` is a non-interactive element, but https://adaptivecards.io/explorer/RichTextBlock.html#Inherited-properties is a valid url. 

I propose adding an interactive element, such as a link icon, beside the text so that it is clear that `Inherited properties` is linked to a specific url in our site.

An example of this behavior can be found on [our documentation site](https://docs.microsoft.com/en-us/adaptive-cards/#how-they-work).

**Comment by vagpt** [comment]
Issue is not repro, hence adding A11yTTValidated tag.
