### ISSUE TITLE
[AdaptiveCards- Designer - Target Version]: Screen Reader is not conveying the state of 'Target Version' combo box when it got expanded and Collapsed. 

### ISSUE THREAD

**Issue by Susmitha474** [microsoft/AdaptiveCards#7645]
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive Cards

### Problem Description

Test Environment:

OS: Version 21H2 (OS Build 22000.318)

URL: [https://adaptivecards.io/](https://nam06.safelinks.protection.outlook.com/?url=https://adaptivecards.io/&data=04%7c01%7cv-ibalam%40microsoft.com%7cbd35d875ec3f4539762308d88f709775%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637417061036711036%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=dUolQbKGi1J8gsoxC2JG5TGoNi41msPfIIjKSIyPGHM%3D&reserved=0)

Edge Dev: version 105.0.1300.0 (Official build) dev (64-bit)

Screen Reader: Narrator

Repro Steps:

1. Open above URL with valid credential.

2. Navigate to 'Designer' link and press enter key to activate it.

3. Navigate to 'Redo' button and press tab key.

4. Navigate to 'Target Version' button and observe the issue.

Actual Result:

Screen reader is not conveying state as 'Collapsed' and 'Expanded' for the 'Target Version' button.

Expected Result:

Screen reader should convey the state of the target version combo box when it is expanded and collapsed.

Note:
1. This issue is working fine on 'Chrome+NVDA'.
2. Same issue is repro throughout the application for the expandable button controls.

User Experience:

It will impact the screen reader user if the screen reader does not convey the state for any combo box on the screen.

MAS Reference:
[Change Notification - Liquid (microsoft.com)](https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/04.02.12)

"Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “.

### Screenshots

https://user-images.githubusercontent.com/104482612/177286536-19e4e108-0313-4d9b-9c86-829a0e4c4887.mp4

### Card JSON

```JSON
NA
```

### Sample Code Language

NA

### Sample Code

NA

**Comment by Raisul123** [comment]
Closing it - As per SME, Screen reader is announcing state as 'Hashpoup' which is sufficient to the screen reader user.
