### ISSUE TITLE
Screen reader is announcing extra information as "current" after each dropdown item.

### ISSUE THREAD

**Issue by palitsourish** [microsoft/AdaptiveCards#7679]
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
Platform: Web
Test URL: [Adaptive Cards](https://adaptivecards.io/)
OS: Windows 11 
Version: 22H2 (OS Build 22622.290) 
Browser version: 105.0.1300.0 (Official build) dev (64-bit) 
Screen Reader: Narrator 

**Repro Steps:**
1.Open above URL with valid credential.
2.Turn on the Narrator using ctrl+win+enter key.
3.Navigate to 'Designer' tab and activate it.
4.Navigate to 'Bot framework webchat' and activate it.
5.Navigate to the dropdown items and observe the issue

**Actual Result:**
Narrator is announcing extra information as 'current' when user navigates to the list of menu items.

**Expected Result:**
Screen Reader should not convey the irrelevant information as "current" when user navigates to the list of menu items.

**Observations:**
Issue is not repro with NVDA.

**User Experience:**
It will impact to the screen reader users if the screen reader convey the irrelevant information for the list of menu items.

### Screenshots

https://user-images.githubusercontent.com/95914144/179224583-0a83b04c-6a5d-48ea-9e73-6591478b55b6.mp4

### Card JSON

```JSON
NA
```

**Comment by vagpt** [comment]
This issue is not repro, hence closing this issue.
