### ISSUE TITLE
Proposal: Host Config fontFamily as array

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#768]
# Problem

Host Config is a shared cross-platform configuration, but doesn't currently address the reality that different platforms have different fonts. 

Our current [Host Config](https://github.com/Microsoft/AdaptiveCards/blob/master/samples/v1.0/HostConfig/sample.json) lists fontfamily as a string.
```json
"fontFamily": "Segoe UI",
```

# Spec

`fontFamily` should support multiple strings (similar to CSS), and the renderer should apply the first one that exists. Multiple strings are specified via commas (comma separated).

```json
"fontFamily": "Segoe UI, Roboto, serif",
```

**Comment by dclaux** [comment]
This was already discussed before, and we had agreed that fontFamily could remain a comma-separated list of font names as that is how both HTML and XAML do it. Any particular reason why we now believe that isn't good enough?

**Comment by matthidinger** [comment]
Sorry for the delay here. This seems like a pretty strange design that we would have to carefully document in each renderer. Since it's really an array of strings it seems like we should model that properly in JSON. It's a lot less error prone to `string.Join(arr, ", ")`  over `string.split(', ')` given we would need to carefully check for ',' or ', ' etc. Feels like this is our best chance to clean this up before release and not break folks.

**Comment by dclaux** [comment]
No strong opinion, but again this was discussed and agreed upon before. IMO XAML and HTML both using just a string is indication enough that the simple string model is good enough.

**Comment by matthidinger** [comment]
Indeed CSS and XAML allow comma separated string in FontFamily, unfortunately Android and iOS do not [as far as I can tell](https://stackoverflow.com/questions/12128331/how-to-change-fontfamily-of-textview-in-android). So having to crack open the string based on a comma seems a bit error prone, especially when considering new renderers come online they may also have to split the string.

**Comment by dclaux** [comment]
Just looking at Android:
- The names of the supported font families are not formatted the same as in HTML
- Only one font family can be specified

So in the end, a HostConfig has to be specially crafted for Android, and a single string is enough. I haven't looked, but I'm going to assume the situation is similar on iOS. Why would we need an array?

**Comment by matthidinger** [comment]
We are trying to specifically avoid having to have separate host configs. The plan for Android would be loop through the fontFamily array and find the first font that exists on the system. Same as what CSS and XAML do, but we have to do it manually, since the native UI platform doesn't have it for us

**Comment by dclaux** [comment]
I don't know how you do that given that Android font family names are not the same are those used in HTML (and likely iOS.) To solve that problem, Adaptive would have to define its own font family names and each renderer would have to map them to their target platform. IMO that makes very little sense given that one HostConfig file is supposed to be specific that that one host anyway.

**Comment by matthidinger** [comment]
Hmm, I don't think I'm following.

The proposal is that the Renderer would enumerate all the font names in the array and apply the first one that exists. In CSS and XAML this works automatically since their UI platforms already work this way  (as long as we join the arrray into a single string with `string.join(arr, ", "):`)

## Example

This array would work for iOS, since SF Pro Display would match. It would work for Windows because of Segoe UI, and Android would work since it would find Roboto, lastly as a catch-all any other renderer that didn't match anything would match serif.

`"fontFamily": [ "SF Pro Display", "Segoe UI", "Roboto", "serif" ]`

**Comment by dclaux** [comment]
But what is the scenario where a single HostConfig is used across multiple hosts?
