### ISSUE TITLE
Send adaptive card through AWS email service (SES)

### ISSUE THREAD

**Issue by saurabh-dwivedi** [microsoft/AdaptiveCards#7681]
### Discussed in https://github.com/microsoft/AdaptiveCards/discussions/7666

<div type='discussions-op-text'>

<sup>Originally posted by **saurabh-dwivedi** July 12, 2022</sup>
Hello,

I am trying to figure out if we can send adaptive cards in email using a third party layer like Amazon [SES](https://aws.amazon.com/ses/). 

I am receiving  the emails but the card is not visible in the email, but when I go to View source of the email I do the adaptive card content in the raw email data.
Email data -
<html><head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dutf-8"><script =
type=3D"application/adaptivecard+json">
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "originator": "",
    "body": [
        {
            "size": "large",
            "text": "Hello Actionable message",
            "wrap": true,
            "type": "TextBlock"
        }
    ],
    "actions": [
        {
            "type": "Action.InvokeAddInCommand",
            "title": "Open Actionable Messages Debugger",
            "addInId": "3d1408f6-afb3-4baf-aacd-55cd867bb0fa",
            "desktopCommandId": "amDebuggerOpenPaneButton"
        }
    ]
}
</script></head><body>If the card doesn't appear, <a target=3D"_blank" href=3D"=
https://store.office.com/app.aspx?assetid=3DWA104381686&amp;productgroup=3DOutlo=
ok&amp;mktvid=3DPN102957641&amp;mktcmpid=3Dsendmailsample">install Actionable Me=
ssages Debugger Outlook add-in</a> to debug the issue. </body></html>

I also tried sending adaptive card using https://amdesigner.azurewebsites.net/ which works as expected. Not sure if using a third party layer we need to add any setting to email content.</div>

**Comment by saurabh-dwivedi** [comment]
Please note I am using a node application to initiate the emails using third party services. Also I tried Sendgrid within Azure to send the cards, no success.

**Comment by paulcam206** [comment]
For support on Outlook Actionable Messages, please post a question on the [Office Addins Dev](https://docs.microsoft.com/en-us/answers/topics/office-addins-dev.html) site. If you need further help more specifically about Adaptive Cards, please let us know.

Thanks!
