### ISSUE TITLE
[Designer] [Tools- Adaptive card editor]: Role is not defined for "Set due date" and "Comment" controls on the "Adaptive card" under the "Pick a sample as a starting point".

### ISSUE THREAD

**Issue by JeanRoca** [microsoft/AdaptiveCards#7691]
https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1916693

**Comment by anna-dingler** [comment]
@JeanRoca I was not able to repro this bug within the [designer](https://adaptivecards.io/designer/)
