### ISSUE TITLE
[Designer] [Tools- Card Editor -Element Properties]: 'More Options '...''button is not getting activated by pressing Enter Key.

### ISSUE THREAD

**Issue by JeanRoca** [microsoft/AdaptiveCards#7695]
https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1898767

**Comment by anna-dingler** [comment]
@JeanRoca I was not able to repro this bug.

The most recent comment in the ADO thread also states that "Bug is not repro on adaptive card side hence removing partner tags and moving to dev portal team."
