### ISSUE TITLE
[Designer] [Tools- Card Editor -Element Properties]: Screen Reader is announcing incorrect name and role for 'More Options '...''button. 

### ISSUE THREAD

**Issue by JeanRoca** [microsoft/AdaptiveCards#7696]
https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1898753

**Comment by anna-dingler** [comment]
@JeanRoca I was not able to repro this bug.

The most recent comment in the ADO thread also states that "Bug is not repro on adaptive card side hence removing partner tags and moving to dev portal team."
