### ISSUE TITLE
[Tools- Adaptive card editor]: Cards list items present under the "Pick a sample as a starting point" dialog box are not accessible with arrow keys.[Rendering] Bug Title Here

### ISSUE THREAD

**Issue by Shireen2000** [microsoft/AdaptiveCards#7699]
### Target Platforms

Other

### SDK Version

105.0.1300.0 

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
OS Version: Dev (OS build 21390.1)
Browser Version: 93.0.916.1 (Official build) dev(64-bit)
URL: https://adaptivecards.io/designer/

**Repro Steps:**
1. Launch the URL: [Adaptive Cards (adaptivecards-ci.azurewebsites.net)](http://adaptivecards-ci.azurewebsites.net/)
2. Navigate to header control ‘Designer’ using tab key and activate it through enter key.
3. Navigate to 'New Card' button using the TAB key & activate it.
4. Observe the issue on the list items.

Actual Result:
Cards list items present under the "Pick a sample as a starting point" dialog box are not accessible with arrow keys. Cards list items are navigable with tab keys not but arrow keys.

**Expected Result:**
Cards list items present under the "Pick a sample as a starting point" dialog box should be accessible with arrow keys not with tab keys.

**User Experience:**
PWD users would be confused and try to access the cards list items with arrow keys and not able to access the cards if the cards list items are not accessible with arrow keys.

**MAS Reference:**
https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/02.01.01

### Screenshots

![MAS2 1 1_Cards list items are not accessible with arrow keys](https://user-images.githubusercontent.com/96283152/179940516-c6f71315-ee0a-45b3-8728-a97663f87b4d.JPG)

https://user-images.githubusercontent.com/96283152/179941163-9e7a9451-d377-495a-a99c-0ef9bf058355.mp4

### Card JSON

```JSON
NA
```

**Comment by anna-dingler** [comment]
@Shireen2000 As seen in the picture below, the **New Card** dialog contains two lists: **Create** and **Explore**.

Should you be able to navigate from the _last item_ (From JSON Schema) in the first list to the _first item_ (Activity Update) in the second list using the down arrow? Or is it acceptable for the two lists to function separately, and only the tab key lets you switch between them?

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/98650930/180891734-cad1cd32-727b-4be4-bed1-a383c0b61287.png">

**Comment by Shireen2000** [comment]
Hi @anna-dingler, I guess to switch between the list items, using the Tab key that would be fine. The main concern would be that the list items present within the list should be accessible using arrow keys.
