### ISSUE TITLE
"Unable to reach app" error during submit action in adaptive cards from MS Teams App

### ISSUE THREAD

**Issue by JiaudheenAM-RTContractor** [microsoft/AdaptiveCards#7712]
### Target Platforms

Other

### SDK Version

Microsoft Azure BOT Framework v4

### Application Name

Microsoft Teams

### Problem Description

While making a submit action in the adaptive card from MS Teams App, the card is throwing with an error "**Unable to reach app. Please try again**". 
I understand this might be due to delay in BOT response. This is creating bad user experience, as it misleads the bot users, because our bot would respond after 15 secs.

Is there way to fix this error or an option to suppress this message ?  

Appreciate if you could help is resolving this.

**Note**: I am not getting this issue with the Web Channel. I am only getting from the Teams Channel.

Application details:
1. Azure Web App Bot built on Azure BOT Framework v4.
2. MS Teams App as Messenger Channel.
3. Adaptive Cards 

Thanks.
<img width="425" alt="adaptivecard-submitaction-issue" src="https://user-images.githubusercontent.com/110030775/180997485-ea0e8fa9-e7c3-4d36-9ddb-286ac2c23045.png">
[InvoiceStatusFormEn.txt](https://github.com/microsoft/AdaptiveCards/files/9189458/InvoiceStatusFormEn.txt)

### Screenshots

<img width="425" alt="adaptivecard-submitaction-issue" src="https://user-images.githubusercontent.com/110030775/180998205-96753ce1-58d7-4739-8f4b-9129870a93c3.png">

### Card JSON

```JSON
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "text": "Any status will exclude Track Invoices",
      "wrap": true,
      "weight": "bolder"
    },
    {
      "type": "TextBlock",
      "text": "Please provide below detail for Vendor Invoice Status Request :",
      "wrap": true
    },
    {
      "type": "TextBlock",
      "text": "Purchase Order Number"
    },
    {
      "type": "Input.Text",
      "id": "PurchaseOrderNumber1",
      "placeholder": "Purchase Order Number"
    },
    {
      "type": "TextBlock",
      "text": "OR",
      "horizontalAlignment": "Center"
    },
    {
      "type": "TextBlock",
      "text": "Purchase Order Number + Vendor Invoice Reference Number",
      "wrap": true
    },
    {
      "type": "Input.Text",
      "id": "PurchaseOrderNumber2",
      "placeholder": "Purchase Order Number"

    },
    {
      "type": "Input.Text",
      "id": "ReferenceNumber1",
      "placeholder": "Vendor Invoice Reference Number"
    },
    {
      "type": "TextBlock",
      "text": "OR",
      "horizontalAlignment": "Center"
    },
    {
      "type": "TextBlock",
      "text": "Vendor Number + Vendor Invoice Reference Number",
      "wrap": true
    },
    {
      "type": "Input.Text",
      "id": "VendorNumber",
      "placeholder": "Vendor Number"
    },
    {
      "type": "Input.Text",
      "id": "ReferenceNumber2",
      "placeholder": "Vendor Invoice Reference Number"
    }

  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Submit",
      "data": {
        "actionType": "InvoiceStatusEn"
      }
    },
    {
      "type": "Action.Submit",
      "title": "Cancel",
      "associatedInputs": "none",
      "data": {
        "actionType": "Cancel"
      }
    }
  ]
}
```

### Sample Code Language

C# 6.0

**Comment by JiaudheenAM-RTContractor** [comment]
May I know the ETA / when it can be assigned ?

**Comment by samthrusha123** [comment]
I'm also facing the same issue during submit action in adaptive cards. Is there any way to hide it?

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/6581

**Comment by Veena9876** [comment]
I'm facing the same issue while submitting the response in post Adaptive card in a chat or channel:  "Unable to reach app. Please try again.", please pour your inputs on this to get resolved.
![image](https://github.com/microsoft/AdaptiveCards/assets/37996631/09ae974b-4701-411c-98a4-1e6d3e548884)
