### ISSUE TITLE
{Linked:Bug2509198}[Adaptive Card-Schema Explorer- Input.Date]: Screen reader is not providing any information after activating the show next/previous month buttons.

### ISSUE THREAD

**Issue by vaishali1397** [microsoft/AdaptiveCards#7719]
### Target Platforms

Other

### SDK Version

1.3

### Application Name

Adaptive cards

### Problem Description

**Test Environment:**
OS Build: Windows 11 Version Dev(OS Build 22523.1000)
Browser: Edge Dev Version 98.0.1108.13 (Official build) dev (64-bit)
URL: [Schema Explorer | Adaptive Cards](https://adaptivecards.io/explorer/Input.Date.html)
Screen Reader: Narrator

**Repro Steps:**
1. Open the above URL.
2. Activate Narrator using 'Ctrl+Win+Enter' key.
3. Schema Explore Input.Date Page will be appear.
4. Navigate to Date Input field in Adaptive Card and activate it.
5. Calendar Pop-up will be appear.
6. Navigate to 'Go to Next month' and 'Go to previous month' buttons.
7. Pressing enter key on both button
8. Observe the screen reader issue.

**Actual result:**
Screen reader is not providing any information after activating the show next/previous month buttons.
Screen reader just staying silent after activating those buttons.

**Expected result:**
Screen reader should provide the information after activating the show next/previous month buttons.
For example, Screen reader should narrate the current month information like 'January 2022'  after activating the next month button in 'December 2021'.

**Observations:**
Same issue is also repro'ing with NVDA and JAWs.

**User Impact:**
Screen Reader user navigating using keyboard won't be able to know about the status changed for the months because of no output given by the screen reader.

**MAS Reference:**
[MAS 1.3.1 – Info and Relationships](https://microsoft.sharepoint.com/:w:/r/sites/accessibility/CELA/Official_Microsoft_Accessibility_Standards/MAS%201.3.1%20%E2%80%93%20Info%20and%20Relationships%20.docx?d=w97358e8843674121bf9df0c6597d03b7&csf=1&web=1&e=yKDvRP)

**“Have feedback to share on Bugs ?** Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fforms.office.com%2fpages%2fresponsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-lalapati%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656401002888328%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=9rKyqggThK5iHRPhG9iMiNp6zSq%2BYr%2fr4gmiXwwFsnM%3D&reserved=0) “

### Screenshots

https://user-images.githubusercontent.com/104483005/181225179-fc43a81c-63ae-457b-acc0-ebb025f1b823.mp4

### Card JSON

```JSON
NA
```

**Comment by vagpt** [comment]
This issue is not repro, hence closing this issue.
