### ISSUE TITLE
Bind Adaptive Card drop down with some data source

### ISSUE THREAD

**Issue by akashSharma2505** [microsoft/AdaptiveCards#772]
I want to bind a data source with adaptive card choice type drop down. Is there any way to do this ? if not, is this a future prospect ?
Also if auto fill options are available with Text Input?

**Comment by anbare** [comment]
Hey @akashSharma2505, can you provide some more info? For example, what platform are you generating the Adaptive Card from? What type of object would your "data source" be? And what do you mean by auto fill?

**Comment by akashSharma2505** [comment]
I am using Node SDK.  I want to populate airport list in a drop down, in adaptive card, which coming from an internal api. This will allow user to select the airport directly instead of typing the country name while booking a flight.
Also, in case of auto fill actually I wanted to bind text input event to a text box in adaptive card if it is possible. And then produce some suggestions for user when he/she is typing in a text box. it's like sharepoint search suggestions if you have idea of sharepoint.

**Comment by andrewleader** [comment]
Thanks for this feedback! We're tracking a dynamic searchable dropdown here, it's a candidate for 1.3: https://portal.productboard.com/adaptivecards/1-adaptive-cards-portal/c/15-dynamic-searchable-select-menu-like-select2

And we've captured your request for an autosuggest text input. Thanks!
