### ISSUE TITLE
Deleted card message from bot in MS Teams channel, are still visible for the new user when they join the same team.

### ISSUE THREAD

**Issue by prashantsoniaa** [microsoft/AdaptiveCards#7730]
### Target Platforms

iOS, Android, Other

### SDK Version

Bot Builder 4.16.1

### Application Name

FlightAttendant

### Problem Description

We are posting an adaptive card with a few buttons to a team channel using a bot. When a user clicks on one of the buttons, we acknowledge what the user has selected, delete the existing card and repost the same card. 
 
Why do we repost the same card?
To make sure the card is easily accessible and does not get lost in the conversations. 

Why do we delete the existing card?
We do not want to keep duplicated messages/cards in the Teams chat. 

While the card is deleted for the existing users, any new users joining the team after the card was deleted for the existing users, new team members still see the deleted card. 

We are able to repro the behavior consistently in the production tenant, However, we are not able to reproduce this in our test tenant. This could be related to policies or the environment; we are not sure at this time. 

Repro
1.Open the team with the bot posted the card with the buttons. 
2.Click on one of the buttons from the adaptive card posted by the bot. 
3.Add a new team member. 
Expected 
1.Since the card is deleted and reposted, any new members joining the team should see only one card and should not see deleted card messages. 

Actual
1.New members can see the deleted cards. Existing members cannot see the deleted cards. 

 

### Screenshots

![image](https://user-images.githubusercontent.com/108713482/181766542-139a1413-bc87-49a3-a15a-8b64b2c31f4d.png)

### Card JSON

```JSON
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.4",
  "body": [
    {
      "columns": [
        {
          "type": "Column",
          "width": 2,
          "items": [
            {
              "type": "TextBlock",
              "text": "Welcome Flight Attendants, press a button below to send a quick message, or for free text use message area at the bottom",
              "size": "small",
              "wrap": true,
              "maxLines": 3
            }
          ]
        }
      ],
      "type": "ColumnSet"
    }
  ],
  "actions": [
    {
      "type": "Action.Execute",
      "title": "Bin space available",
      //"tooltip": "Bin space available",
      "data": {
        "teamId": "${teamId}",
        "response": "Bin space available, continue to allow carry on bags",
        "flightOriginDate": "${flightOriginDate}",
        "airlineCode": "${airlineCode}",
        "flightNumber": "${flightNumber}",
        "departureStation": "${departureStation}",
        "scheduleDepartureDateTime": "${scheduleDepartureDateTime}"
      }
    },
    {
      "type": "Action.Execute",
      "title": "Bins almost full",
      //"tooltip": "Bins almost full",
      "data": {
        "teamId": "${teamId}",
        "response": "Bins almost full, check all remaining bags",
        "flightOriginDate": "${flightOriginDate}",
        "airlineCode": "${airlineCode}",
        "flightNumber": "${flightNumber}",
        "departureStation": "${departureStation}",
        "scheduleDepartureDateTime": "${scheduleDepartureDateTime}"
      }
    },
    {
      "type": "Action.Execute",
      "title": "Bag check rqd",
      //"tooltip": "Bag check rqd",
      "data": {
        "teamId": "${teamId}",
        "response": "Bag check required. Bag is coming off the airplane and needs to be checked.",
        "flightOriginDate": "${flightOriginDate}",
        "airlineCode": "${airlineCode}",
        "flightNumber": "${flightNumber}",
        "departureStation": "${departureStation}",
        "scheduleDepartureDateTime": "${scheduleDepartureDateTime}"
      }
    },
    {
      "type": "Action.Execute",
      "title": "Seat Dupe",
      "data": {
        "teamId": "${teamId}",
        "response": "Seat Dupe, agent assistance needed",
        "flightOriginDate": "${flightOriginDate}",
        "airlineCode": "${airlineCode}",
        "flightNumber": "${flightNumber}",
        "departureStation": "${departureStation}",
        "scheduleDepartureDateTime": "${scheduleDepartureDateTime}"
      }
    }
  ]
}
```

### Sample Code Language

C#

### Sample Code

protected override async Task<InvokeResponse> OnInvokeActivityAsync(
            ITurnContext<IInvokeActivity> turnContext, 
            CancellationToken cancellationToken)
        {
            try
            {
                var activity = turnContext.Activity;

                ActionData actionData = 
                                JsonConvert.DeserializeObject<ActionData>
                                                (turnContext.Activity.Value.ToString());
                var userResponse = 
                    new UserResponse(_appId, 
                    turnContext.Activity.ChannelData?.channel?.id?.ToString(), 
                    turnContext.Activity.From.AadObjectId, actionData.Action.Data);

                //Send use response.
                await _notificationBusinessLogic.BuildAndSendResponse(actionData.Action.Data);

                //Delete existing card.
                await turnContext.DeleteActivityAsync(activity.ReplyToId, cancellationToken);

                //Build adaptive card and send. 
                await _notificationBusinessLogic.BuildAndSendCard(actionData.Action.Data);

                // Track use response.
                await _idsBusinessLogic.InsertUserResponseTransaction(userResponse);
                return new InvokeResponse { Status = 200 };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                await SendMessageAsync(turnContext, MessageFactory.Text("Something went wrong!"));
                return new InvokeResponse { Status = 500 };
            }
        }

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/6580
