### ISSUE TITLE
Action.Http not working with schema 1.4

### ISSUE THREAD

**Issue by rickputnam** [microsoft/AdaptiveCards#7736]
### Target Application

Outlook

### Application Operating System

Windows

### Schema Version

1.4

### Problem Description

I need to use schema version 1.4 in order to be able to use regex validation of inputs.  I also need to use the dynamic response feature which requires that I use Action.Http.  All works as expected if I use Action.Execute except that I get a "Something went wrong, please try again later" response when clicking the Execute button.

I cannot get the Action.Http button to show in the outlook email and I have been unable to find an example on the web using version 1.4 for outlook email with the Action.Http action.

Note that the attached json has the action.Execute in order to show the buttons.  If I use action.Http, the buttons do not show.

Can someone help me with this?

### Expected Outcome

I expected that the Action.Http action would work with schema 1.4 version of the Adaptive Card.

### Actual Outcome

The Action.Http button is not visible in the email when using version 1.4.

### Card JSON

```JSON
{
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.4",
  "body": [
    {
      "type": "Container",
      "items": [
        {
          "type": "TextBlock",
          "text": "Select one of the options below:",
          "wrap": true
        }
      ]
    }
  ],
  "actions": [
    {
      "type": "Action.ShowCard",
      "title": "Promote RFP to Opportunity",
      "card": {
        "type": "AdaptiveCard",
        "body": [
          {
            "type": "TextBlock",
            "text": "Enter owner email address",
            "wrap": true
          },
          {
            "type": "Input.Text",
            "placeholder": "Enter email address here.",
            "id": "email",
            "style": "email",
            "errorMessage": "Please provide valid email-id",
            "isRequired": true,
            "regex": "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+[.][A-Za-z0-9-]{2,4}$"
          }
        ],
        "actions": [
          {
            "type": "Action.Execute",
            "url": "",
            "title": "Promote to Opportunity",
            "method": "POST",
            "body": "{\n\"email\":\"{{email.value}}\",\n\"rfpId\":\"00000000-0000-0000-0000-000000000001\"\n}",
            "headers": [
              {
                "name": "Authorization",
                "value": ""
              },
              {
                "name": "Content-Type",
                "value": "application/json"
              }
            ]
          }
        ]
      }
    },
    {
      "type": "Action.ShowCard",
      "title": "Already Pursuing this Opportunity",
      "card": {
        "type": "AdaptiveCard",
        "body": [
          {
            "type": "TextBlock",
            "text": "Enter Opportunity CRM Number",
            "wrap": true
          },
          {
            "type": "Input.Text",
            "placeholder": "Enter CRM number here.",
            "id": "crmNumber"
          }
        ],
        "actions": [
          {
            "type": "Action.Http",
            "url": "",
            "title": "Submit",
            "method": "POST",
            "body": "{\n\"crmNumber\":\"{{crmNumber.value}}\"}",
            "headers": [
              {
                "name": "Authorization",
                "value": ""
              },
              {
                "name": "Content-Type",
                "value": "application/json"
              }
            ]
          }
        ]
      }
    }
  ]
}
```

### Repro Steps

Create a manually triggered email Power Automate flow with the included Adaptive Card json script in a compose block. In the resulting received email, click either the Promote RFP to Opportunity or Already Pursuing Opportunity buttons and then fill in a value in the input text and click either the Promote to Opportunity or the Submit button.  The error message will popup "Something went wrong please try again later"

**Comment by paulcam206** [comment]
For support on Outlook Actionable Messages, please post a question on the [Office Addins Dev](https://docs.microsoft.com/en-us/answers/topics/office-addins-dev.html) site. If you need further help more specifically about Adaptive Cards, please let us know.

Thanks!

**Comment by InfyTusharGalfade** [comment]
Can we pass url
in action.execute

**Comment by mitquinn** [comment]
I messed around with this a lot. I dont think its possible. MS says to use Action.Execute but I can't find any example for an http request using Action.Execute
