### ISSUE TITLE
[Feature Request] Rich Text Editor for Input.Text

### ISSUE THREAD

**Issue by meghnasavit** [microsoft/AdaptiveCards#7739]
### Problem Statement

We are working on the Github app for MS Teams and would like to implement a rich text editor in the task module for Input.Text.

This is our current experience. 
<img width="932" alt="image" src="https://user-images.githubusercontent.com/46958410/182646990-29d18732-5983-40a4-8d6f-ac1538a86d4b.png">

For our Description field, we would like to have a rich text editor like what is present in the JIRA app for MS Teams.
<img width="279" alt="image" src="https://user-images.githubusercontent.com/46958410/182647278-eb4aea3d-f4ab-4242-9201-f083c7e911cc.png">

### Proposed solution

Please let us know how this can be made possible or and workaround that we can use to achieve this experience.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/6624
