### ISSUE TITLE
MS Teams iOS mobile client – The button does not respond to tap if the keyboard was invoked just before tap on button.

### ISSUE THREAD

**Issue by prashantsoniaa** [microsoft/AdaptiveCards#7749]
### Target Platforms

iOS

### SDK Version

Microsoft Bot Builder SDK 4.16.1

### Application Name

Microsoft Teams

### Problem Description

We have a verb that we are using as a command for asking the bot to post the adaptive card with a few buttons. 

Example @FABot verbose card

The issue is seen when the user clicks on the button from the adaptive card, but no response is captured since the bot did not fire the on invoke activity. 

Repro
1.	User opens iOS MS Teams Mobile client. 
2.	Open the team where the bot is installed. 
3.	User post a new message mentioning the bot. i.e. @FABot verbose card.
4.	Bot triggers OnMessageActivityAsync activity fires. Bot check for command “verbose card” and renders the adaptive card with four buttons. (Note: the button has Action.Execute actions)
5.	User does not close the keyboard, instead on adaptive card render, clicks on the button on the Teams screen. 

Note: Please find the video outside the document “Issue Buttons not responding.mp4”
Expected 
1.	On Invoke activity event should fire in the bot.
Actual
1.	On Invoke activity event does not fire. 

Workaround
The user closes the keyboard after the card rendering and, holds and drags the screen up a couple of times. Then click on the button on the adaptive card. This fires on the activity event in the bot and the bot prints the acknowledgment message. 

### Screenshots

![image](https://user-images.githubusercontent.com/108713482/183655471-70a1eb99-3f3e-4c7a-b98c-be0afeb6a984.png)

### Card JSON

```JSON
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.4",
  "body": [
    {
      "columns": [
        {
          "type": "Column",
          "width": 2,
          "items": [
            {
              "type": "TextBlock",
              "text": "Welcome Flight Attendants, press a button below to send a quick message, or for free text use message area at the bottom",
              "size": "small",
              "wrap": true,
              "maxLines": 3
            }
          ]
        }
      ],
      "type": "ColumnSet"
    }
  ],
  "actions": [
    {
      "type": "Action.Execute",
      "title": "Bin space available",
      "tooltip": "Bin space available",
      "data": {
        "teamId": "${teamId}",
        "response": "Bin space available, continue to allow carry on bags",
        "flightOriginDate": "${flightOriginDate}",
        "airlineCode": "${airlineCode}",
        "flightNumber": "${flightNumber}",
        "departureStation": "${departureStation}",
        "scheduleDepartureDateTime": "${scheduleDepartureDateTime}"
      }
    },
    {
      "type": "Action.Execute",
      "title": "Bins almost full",
      "tooltip": "Bins almost full",
      "data": {
        "teamId": "${teamId}",
        "response": "Bins almost full, check all remaining bags",
        "flightOriginDate": "${flightOriginDate}",
        "airlineCode": "${airlineCode}",
        "flightNumber": "${flightNumber}",
        "departureStation": "${departureStation}",
        "scheduleDepartureDateTime": "${scheduleDepartureDateTime}"
      }
    },
    {
      "type": "Action.Execute",
      "title": "Bag check rqd",
      "tooltip": "Bag check rqd",
      "data": {
        "teamId": "${teamId}",
        "response": "Bag check required. Bag is coming off the airplane and needs to be checked.",
        "flightOriginDate": "${flightOriginDate}",
        "airlineCode": "${airlineCode}",
        "flightNumber": "${flightNumber}",
        "departureStation": "${departureStation}",
        "scheduleDepartureDateTime": "${scheduleDepartureDateTime}"
      }
    },
    {
      "type": "Action.Execute",
      "title": "Seat Dupe",
      "data": {
        "teamId": "${teamId}",
        "response": "Seat Dupe, agent assistance needed",
        "flightOriginDate": "${flightOriginDate}",
        "airlineCode": "${airlineCode}",
        "flightNumber": "${flightNumber}",
        "departureStation": "${departureStation}",
        "scheduleDepartureDateTime": "${scheduleDepartureDateTime}"
      }
    }
  ]
}
```

### Sample Code

https://user-images.githubusercontent.com/108713482/183943634-f2260730-4cab-43cc-9e2c-9ef7e5c2ef88.mp4

![keyboard-invoke-causing-button-click-canceled](https://user-images.githubusercontent.com/108713482/183943558-629533ca-596b-406b-8acd-97021e77c2a9.png)
 Language

C#

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/6688
