### ISSUE TITLE
MS Teams iOS mobile client – All buttons are disabled on adaptive card when user comes back from message view to chat view inside a team channel.[Rendering] Bug Title Here

### ISSUE THREAD

**Issue by prashantsoniaa** [microsoft/AdaptiveCards#7750]
![All-buttons-disabled](https://user-images.githubusercontent.com/108713482/183943967-5dbf3cb6-dd01-457d-9272-ab9046e3a53d.png)

https://user-images.githubusercontent.com/108713482/183943979-7bd9df7c-032f-49dd-a1f1-af1e5d3bc60e.mp4

### Target Platforms

iOS

### SDK Version

Microsoft Bot Builder 1.46.1

### Application Name

Microsoft Teams

### Problem Description

We have an adaptive card that has four buttons with Action.Execute actions. The bot renders the card in the iOS mobile client with these four buttons. When a user clicks on the button, the bot responds with an acknowledgment.

Issue 
When the user taps on the card or selects the reply option with the card message, the mobile client navigates to the next screen (i.e. message view). The user then clicks on the back button in the top-left corner to come back to the channel message view. When the user taps on any of the buttons from the adaptive card in this view, the button gets disabled.

Repro
1.	Render an adaptive card from the bot with a few buttons. 
2.	Click on the reply option or tap on the empty area of the card or title. 
3.	MS Teams will take the user to the next screen (i.e. individual message view).
4.	Click on the back button in the top left corner. 
5.	You will see the same card in the channel message view. Click on the button on the card. 
Note: Refer to the video outside for repro steps.
Expected 
1.	On activity event should fire one bot that prints the ack. message.

Actual
1.	On activity event is not fire. The button is disabled. You click on other buttons on the same card one by one, and those will get disabled too. 

Workaround
NA

### Screenshots

![image](https://user-images.githubusercontent.com/108713482/183656844-2e834613-5384-478f-a673-15a03a2d5ded.png)

### Card JSON

```JSON
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.4",
  "body": [
    {
      "columns": [
        {
          "type": "Column",
          "width": 2,
          "items": [
            {
              "type": "TextBlock",
              "text": "Welcome Flight Attendants, press a button below to send a quick message, or for free text use message area at the bottom",
              "size": "small",
              "wrap": true,
              "maxLines": 3
            }
          ]
        }
      ],
      "type": "ColumnSet"
    }
  ],
  "actions": [
    {
      "type": "Action.Execute",
      "title": "Bin space available",
      "tooltip": "Bin space available",
      "data": {
        "teamId": "${teamId}",
        "response": "Bin space available, continue to allow carry on bags",
        "flightOriginDate": "${flightOriginDate}",
        "airlineCode": "${airlineCode}",
        "flightNumber": "${flightNumber}",
        "departureStation": "${departureStation}",
        "scheduleDepartureDateTime": "${scheduleDepartureDateTime}"
      }
    },
    {
      "type": "Action.Execute",
      "title": "Bins almost full",
      "tooltip": "Bins almost full",
      "data": {
        "teamId": "${teamId}",
        "response": "Bins almost full, check all remaining bags",
        "flightOriginDate": "${flightOriginDate}",
        "airlineCode": "${airlineCode}",
        "flightNumber": "${flightNumber}",
        "departureStation": "${departureStation}",
        "scheduleDepartureDateTime": "${scheduleDepartureDateTime}"
      }
    },
    {
      "type": "Action.Execute",
      "title": "Bag check rqd",
      "tooltip": "Bag check rqd",
      "data": {
        "teamId": "${teamId}",
        "response": "Bag check required. Bag is coming off the airplane and needs to be checked.",
        "flightOriginDate": "${flightOriginDate}",
        "airlineCode": "${airlineCode}",
        "flightNumber": "${flightNumber}",
        "departureStation": "${departureStation}",
        "scheduleDepartureDateTime": "${scheduleDepartureDateTime}"
      }
    },
    {
      "type": "Action.Execute",
      "title": "Seat Dupe",
      "data": {
        "teamId": "${teamId}",
        "response": "Seat Dupe, agent assistance needed",
        "flightOriginDate": "${flightOriginDate}",
        "airlineCode": "${airlineCode}",
        "flightNumber": "${flightNumber}",
        "departureStation": "${departureStation}",
        "scheduleDepartureDateTime": "${scheduleDepartureDateTime}"
      }
    }
  ]
}
```

### Sample Code Language

C#

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/6687
