### ISSUE TITLE
[Rendering] Action.Submit buttons are not working on Android

### ISSUE THREAD

**Issue by maindi** [microsoft/AdaptiveCards#7758]
### Target Platforms

iOS, Android, UWP

### SDK Version

Latest

### Application Name

Microsoft Teams

### Problem Description

An adaptive card with Action.Submit buttons and with the type of `task/submit` are not working properly on the Android Teams client. Clicking a `task/submit` button is not even triggering an HTTP post event to the app. (ngrok local environment).  Clicking a `task/fetch` button works correctly.

**All card buttons work correctly on iOS & Web browser & Teams Desktop client.**

### Screenshots

![screenshot_20220811-120529](https://user-images.githubusercontent.com/7067646/184101076-ca02ae34-5bc4-4f96-b5b8-235bb1fdcdf5.jpg)

### Card JSON

```JSON
{
    type: "AdaptiveCard",
    $schema: "http://adaptivecards.io/schemas/adaptive-card.json",
    version: "1.4",
    body: [
      {
        type: "TextBlock",
        size: "Large",
        weight: "Bolder",
        text: "Here's what you can do with APP",
        separator: true,
      },
      {
        type: "ActionSet",
        actions: [
          {
            type: "Action.Submit",
            title: "Give Recognition",
            data: {
              msteams: {
                type: "task/fetch",
              },
              id: "give_recognition_apphome",
            },
          },
          {
            type: "Action.Submit",
            title: "Plant Trees",
            data: {
              msteams: {
                type: "task/submit",
              },
              id: "plant_trees",
            },
          },
          {
            type: "Action.Submit",
            title: "Statistics",
            data: {
              msteams: {
                type: "task/submit",
              },
              id: "view_statistics",
            },
          },
          {
            type: "Action.OpenUrl",
            title: "Help",
            url: "https://anurl.com,
          },
          {
            type: "Action.OpenUrl",
            title: "Dashboard ",
            url: process.env.WEBAPP_URL
          },
        ],
      },
      {
        type: "TextBlock",
        wrap: true,
        text:
          "🌱 You have " +
          seedsLeft +
          " seeds left to give 🌳 You have " +
          unplantedSeeds +
          " unplanted seeds",
        size: "Small",
        weight: "Default",
        isSubtle: true,
      },
    ],
  }
```

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/6686

**Comment by Keshav-MSFT** [comment]
@maindi  We are able to repro this issue. We have raised a bug for the same and engineering team is looking into it. We will inform you once we get any further update. Thanks!

**Comment by kevit-yuvraj-kanakiya** [comment]
any updates on the above issue? This is still not working in the mobile app with the latest version. It was working on the previous version of my Teams app (version: I don't know), but after I updated the Teams app( version: 1416/1.0.0.2023213504) the issue occurred again, this is very inconsistency why it is resolved and happened again and again as I also read some articles.
