### ISSUE TITLE
Control Adaptive Card Height when rendering in Outlook

### ISSUE THREAD

**Issue by Sphillips24** [microsoft/AdaptiveCards#7759]
# Platform

What platform is your issue or question related to? (Delete other platforms).

NET HTML

# Author or host

Outlook

# Version of SDK

Latest

# Issue

Outlook is cutting off the bottom of adaptive card. Is there a way to stop this from happening and remove the verticle scroll bar?

![image](https://user-images.githubusercontent.com/43961472/184358850-e220ce26-f4e2-44d2-b3fd-72eeb57f3a6b.png)

I've tried "minheight" and styling the containing HTML but it does not affect the behavior.

**Comment by paulcam206** [comment]
For support on Outlook Actionable Messages, please post a question on the [Office Addins Dev](https://docs.microsoft.com/en-us/answers/topics/office-addins-dev.html) site. If you need further help more specifically about Adaptive Cards, please let us know.

Thanks!
