### ISSUE TITLE
[Designer] Copying card payload does not include templating expressions

### ISSUE THREAD

**Issue by anna-dingler** [microsoft/AdaptiveCards#7764]
### Problem Description

When copying the card payload, the copied payload does not include any templating expressions. Instead, the expressions are replaced with the appropriate data.

## Proposed solution

Template expansion should not be applied when copying the payload.

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "${title}"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5"
}
```

### Card data

```JSON
{
    "title": "Publish Adaptive Card Schema"
}
```

### Copied payload

```JSON
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "Publish Adaptive Card Schema"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5"
}
```

**Comment by paulcam206** [comment]
by design - as discussed in triage, this is an intentional convenience feature (see the button's tooltip). we should consider adding some functionality around making copying the unbound template/data easier for the user, but I don't think it's on our radar at the moment (feel free to file) :)
