### ISSUE TITLE
{TrackingID:2208050050001317}[Outlook][Actionable email developer dashboard] [Can't access the Developer dashboard]

### ISSUE THREAD

**Issue by numsantos** [microsoft/AdaptiveCards#7767]
Hi,

I'm following the email Ticket Email Thread "TrackingID#2208050050001317".

We are maintaining the adaptive cards of a customer, to be sent through Outlook messages.
we needed to create a new Provider, since the email sender address needs to change.
The problem is, we cannot access the [Developer Dashboard](https://aka.ms/publishoam) to register the new provider as described in the [documentation](https://docs.microsoft.com/en-us/outlook/actionable-messages/email-dev-dashboard). We tried with different users and browsers. but with no avail.

the error shown is the following:
![image](https://user-images.githubusercontent.com/40486762/185678576-65e3ec0f-f4e6-41bc-9a97-ebc0db112589.png)

can you help me?

**Comment by honzakostejn** [comment]
My M365 support case: [Case #:32491137]

**Comment by paulcam206** [comment]
For support on Outlook Actionable Messages, please post a question on the [Office Addins Dev](https://docs.microsoft.com/en-us/answers/topics/office-addins-dev.html) site. If you need further help more specifically about Adaptive Cards, please let us know.

Thanks!

**Comment by numsantos** [comment]
forwarded here: https://docs.microsoft.com/en-us/answers/questions/979743/case-32491137actionable-email-developer-dashboard.html
