### ISSUE TITLE
[Rendering] Cannot display hyperlink inside choice title with markdown syntax

### ISSUE THREAD

**Issue by thanhnt210793** [microsoft/AdaptiveCards#7769]
### Target Platforms

Other

### SDK Version

Bot Framework 4.12.2

### Application Name

Testing Application

### Problem Description

I used markdown syntax to display hyperlink inside choice title.
For the textbox MS teams can display but for the Input.ChoiceSet.Choices **CANNOT**.
Can display on https://adaptivecards.io/designer/ and Bot Framework Emulator but MS Teams cannot.
Please take a look in the Card JSON

### Screenshots

![image](https://user-images.githubusercontent.com/37342171/185896948-0b5bfb88-0157-4254-a734-25a57e00556c.png)

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Input.ChoiceSet",
            "placeholder": "Placeholder text",
            "choices": [
                {
                    "title": "ABC. [URL Title](https://www.google.com/).",
                    "value": "AAA"
                },
                {
                    "title": "XYZ. [Here's what will happen](https://www.microsoft.com/).",
                    "value": "BBB"
                }
            ],
            "id": "choiceset",
            "style": "expanded",
            "isRequired": true,
            "wrap": true,
            "errorMessage": "please choose one option at least!",
            "label": "Label text here"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3"
}
```

### Sample Code Language

C#

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/6732
