### ISSUE TITLE
Multi-line TextBlocks should show ellipses when truncated

### ISSUE THREAD

**Issue by tongyliu** [Microsoft/AdaptiveCards#779]
Multi-line TextBlocks should match the behavior of single line ones when it comes to truncation -- currently with the TypeScript renderer, no ellipsis is shown if multi-line text overflows. This will be needed for Bing API news cards to display properly.

**Current:**
![image](https://user-images.githubusercontent.com/3249032/31569542-668398ea-b030-11e7-92c8-e48751e3a3a4.png)

**Desired:**
![capture](https://user-images.githubusercontent.com/3249032/31569903-b5edacf6-b033-11e7-82af-730c6bcdae58.PNG)

This is difficult/impossible to do with pure CSS (`text-overflow: ellipsis` only works for single lines, and `-webkit-line-clamp` isn't cross browser), so we might need to pre-truncate the text in JS. Will code up a prototype early next week.

**Comment by anbare** [comment]
@tongyliu are you making ellipses the default behavior in the nodejs renderer?

If so, we need to create an issue to track applying that ellipses behavior to ALL the renderers, as all renderers (iOS, Windows, Android) should behave the same

**Comment by tongyliu** [comment]
@anbare yep, this will make ellipses the default behavior for truncation there.

The renderer guidelines [here](https://docs.microsoft.com/en-us/adaptive-cards/display/implementingrenderer) say that TextBlocks "**SHOULD** trim any excess text with an ellipsis," so I'd assumed that the other renderers already supported this behavior and I was just dealing with a limitation of the nodejs renderer. If that's not the case though, I agree we should have an issue to track this behavior across all official renderers.

**Comment by anbare** [comment]
Awesome thx I created an uber issue to track all the renderers, I don't believe UWP does this today and we would have to confirm the other renderers do too

**Comment by tongyliu** [comment]
Closing as fixed.

**Comment by khouzam** [comment]
Reopenning as iOS is not respecting maxLines.

**Comment by dclaux** [comment]
@khouzam why did you reopen this?

**Comment by dclaux** [comment]
Sorry, I posted my question exactly at the same time as I got your response.

**Comment by khouzam** [comment]
After investigations, maxLines are respected but the ellipsis don't show on iOS. Will need to fix.
