### ISSUE TITLE
Animating text display

### ISSUE THREAD

**Issue by YoungjaeKim** [microsoft/AdaptiveCards#780]
Hi.

I'd like to _animate_ words while playing `speak` sound  as similar as Karaoke textflows.
If we targeted only Android, how can we achieve this feature with AdaptiveCards? Any idea?

Note that a sound can provide caption-style `mm:ss` or `duration` information for animating text on each word.

**Comment by andrewleader** [comment]
Hey, thanks for this feature request! That's a neat idea, but probably not something on our roadmap anytime soon. If you're rendering Adaptive Cards yourselves, you could extend the Android renderer and possibly implement this yourselves. Let us know if you have more questions! Thanks!
