### ISSUE TITLE
AdaptiveCards Id only in Input type

### ISSUE THREAD

**Issue by mrbrennonwilliams** [Microsoft/AdaptiveCards#781]
I notice that CardElement, TypedElement is missing the Id property shown throughout the schema and indeed only the Input type contains it. Is there any reason why it is not removed from Input and added to TypedElement?

Every object in the stack needs a property for a unique ID.

Cheers

**Comment by anbare** [comment]
Hey Brennon, why do you believe every element needs an ID property?

Thanks!
Andrew

**Comment by mrbrennonwilliams** [comment]
Hi Andrew,

It depends on the view of the platform architects to be honest and what their intentions are for extensibility.

Without an ID for each element, the ability to modify the element properties at runtime becomes quite difficult and error prone.


In my example, I want the user to be able to modify JSON in the text editor, and from there update the underlying object model to reflect the user changes. 

Without the ID being present in the element, I would overwrite any previous elements from the card object collection and lose important connections between them (as they are referenced by unique ID).

I completely understand (and agree with) the view of keeping the element property surface as clean as possible, 

In my experience, not being able to uniquely identify objects causes issues. Eventually the developer will have a need to traverse the adaptivecard object at runtime. This could be for testing, analytics or dynamic changes to the object for exmple.

Just some thoughts.

Cheers

**Comment by matthidinger** [comment]
Thanks for the discussion guys, the Id property was added to AdaptiveTypedElement
