### ISSUE TITLE
Properties with Required values should not render without a value

### ISSUE THREAD

**Issue by mrbrennonwilliams** [microsoft/AdaptiveCards#784]
Several types show required properties in the schema, yet the element will still render without a value assigned.

Either a property is required or it is not and the renderer should honour such requirements

**Examples**

- **AdaptiveImage.url** property is required, yet on TS the card will still render without it, while Android/iOS fails to render (#2665)

**Comment by shalinijoshi19** [comment]
@paulcam206 is this something that will be fixed with the isRequired element support that we're lighting up for 1.2?

**Comment by andrewleader** [comment]
Closing as TS no longer renders if the url isn't present for image
