### ISSUE TITLE
Inconsistent image size rendering in ImageSet web Visualiser

### ISSUE THREAD

**Issue by mrbrennonwilliams** [Microsoft/AdaptiveCards#785]
With the following JSON either the ImageSet imagesSize property should override the individual image size property or each image size should be honoured. The inconsistency is evident in the WPF visualiser as opposed to the web visualiser:

`{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "ImageSet",
            "images": [
                {
                    "type": "Image",
                    "size": "medium",
                    "url": "http://adaptivecards.io/content/cats/1.png",
                    "altText": ""
                },
                {
                    "type": "Image",
                    "url": "http://adaptivecards.io/content/cats/1.png",
                    "altText": ""
                }
            ],
            "imageSize": "large"
        }
    ],
    "version": {
        "Major": 1,
        "Minor": 0
    }
}`

**Comment by matthidinger** [comment]
That's a really interesting find, I don't think we ever considered that scenario. @dclaux do you recall if we ever discussed this, or should we figure it out now?

**Comment by dclaux** [comment]
I know there is no trace of it, but our decision was that ImageSet.imageSize applies to all images and the size property of the image objects is ignored.
