### ISSUE TITLE
HTML Client Source link is broken

### ISSUE THREAD

**Issue by IntranetFactory** [Microsoft/AdaptiveCards#786]
It just leads to a 404 page https://github.com/Microsoft/AdaptiveCards/tree/master/source/html

Where do I find the source for the html client?

![image](https://user-images.githubusercontent.com/7462342/31612797-015ca170-b24f-11e7-8857-60b036d944a0.png)

**Comment by anbare** [comment]
Hey IntranetFactory, sorry about that, the HTML nodejs client code is located here: https://github.com/Microsoft/AdaptiveCards/tree/master/source/nodejs

We'll get that front page updated!
