### ISSUE TITLE
[Adaptive Card-Schema Explorer]: Ensures elements with ARIA roles have all required ARIA attributes (.ac-textBlock[role="heading"]:nth-child(1))

### ISSUE THREAD

**Issue by Susmitha474** [microsoft/AdaptiveCards#7870]
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive Cards

### Problem Description

Test Environment:
OS: Version 22H2 (OS Build 25197.1000)
Edge Dev: version 107.0.1379.1 (Official build) dev (64-bit)
Application URL: [[[https://adaptivecards.io/](https://nam06.safelinks.protection.outlook.com/?url=https://adaptivecards.io/&data=04%7c01%7cv-ibalam%40microsoft.com%7cbd35d875ec3f4539762308d88f709775%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637417061036711036%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=dUolQbKGi1J8gsoxC2JG5TGoNi41msPfIIjKSIyPGHM%3D&reserved=0)]([https://adaptivecards.io/explorer/)](https://adaptivecards.io/%5D(https://adaptivecards.io/explorer/)%5D(https://adaptivecards.io/))

Pre-Requisites:
Run the Accessibility Tool on the Web page.

Repro Steps:
1.Open above URL with V- credential.
2.Navigate to 'Schema Explorer' link using tab key and press enter key to activate it.
3.Run the AI tool on the web page.
4.Navigate to "TextBlock" link present under CardElements from the left navigation using the tab key and activate it using Enter key.
5. Navigate to the final adaptive card using the Tab key.
6. Navigate to the 
                  Style set to heading
                  Style set to heading, color set to good
7. Observe the issue here.

Actual Issue: Required ARIA attribute not present: aria-level

Expected: Ensures elements with ARIA roles have all required ARIA attributes (aria-required-attr - https://accessibilityinsights.io/info-examples/web/aria-required-attr)

Snippet:[<div class="ac-textBlock" role="heading" style="overflow: hidden; font-family: &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 21px; color: rgb(0, 0, 0); font-weight: 600; text-align: start; line-height: 27.93px; overflow-wrap: break-word; box-sizing: border-box; flex: 0 0 auto;">] 

Note: This accessibility issue was found using Accessibility Insights for Web 2.34.1 (axe-core 4.4.1), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.

MAS Reference:
https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/04.01.02

"Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “.

### Screenshots

<img width="960" alt="AI issue on TextBlock" src="https://user-images.githubusercontent.com/104482612/190405109-5a9a6ead-2f5d-46f3-a177-b750110cd574.png">
<img width="965" alt="AI issue on TextBlock2" src="https://user-images.githubusercontent.com/104482612/190405125-c46ca3f6-cabd-467c-bfcf-0179c82aced6.png">

### Card JSON

```JSON
NA
```

### Sample Code Language

NA

### Sample Code

NA

**Comment by vagpt** [comment]
This issue is not repro at our end, hence adding A11yTTValidated tag.
