### ISSUE TITLE
[InputwithValidation.Json]: Voice Over focus is going on the hidden element while navigating in forward navigation from 'Input.text.'elements'. 

### ISSUE THREAD

**Issue by vagpt** [microsoft/AdaptiveCards#7876]
### Target Platforms

iOS

### SDK Version

Version 1.0(2.4.0-beta.22.9.4.1)

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
Device: iPhone 11
iOS: 15.6.1
Application: Adaptive Cards
App Version: Version 1.0(2.4.0-beta.22.9.4.1)
Screen Reader: Voice Over

**Repro Steps:**
1. Launch Adaptive Cards iOS application.
2. Home screen will appear.
3. Activate voice over
4. Navigate to "V1.3" control and select it.
5. Navigate to 'Scenarios' control and activate it.
6. Navigate to 'InputsWithValidation.Json' under 'Scenario' list item and activate it.
7. Card will be appear.
8. Navigate in forward navigation using right swipe and observe the issue.

**Actual Result:**
Voice Over focus is going on the hidden elements while navigating in forward navigation. While focus is on 'Input.Text.elements' on performing right swipe it is going on the hidden element.

**Expected Result:**
Voice over focus should not go on the hidden element and on performing right swipe it should go on the Name edit field.

**Note:**
This issue is working fine in backward navigation.
 
**User Experience:**
If after enlarging the text size of application, some content or controls are not properly appearing, then it would impact the low vision users.

Mas Reference:
(https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/02.04.03)

"Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “

### Screenshots

https://user-images.githubusercontent.com/95913748/190470014-8d87a7b6-3196-424c-9ec9-a83383ef8852.MP4

### Card JSON

```JSON
NA
```

**Comment by jwoo-msft** [comment]
this is fixed.

**Comment by vagpt** [comment]
This issue is working fine on the environment below.

Test Environment:
Device: iPhone 11
iOS Version: 16.2
App Version: 168
