### ISSUE TITLE
[Adaptive Cards-Schema Explorer]: Page is getting scrolled out automatically, when using narrator in scan mode after reading the context from the Adaptive card.

### ISSUE THREAD

**Issue by Susmitha474** [microsoft/AdaptiveCards#7887]
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive Cards

### Problem Description

Test Environment:
OS: Version 22H2 (OS Build 25197.1000)
Edge Dev: version 107.0.1379.1 (Official build) dev (64-bit)
Application URL: [[[https://adaptivecards.io/](https://nam06.safelinks.protection.outlook.com/?url=https://adaptivecards.io/&data=04%7c01%7cv-ibalam%40microsoft.com%7cbd35d875ec3f4539762308d88f709775%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637417061036711036%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=dUolQbKGi1J8gsoxC2JG5TGoNi41msPfIIjKSIyPGHM%3D&reserved=0)]([https://adaptivecards.io/explorer/)](https://adaptivecards.io/%5D(https://adaptivecards.io/explorer/)%5D(https://adaptivecards.io/))

Pre-Requisites:
Run the Narrator in the scan mode using "Control +Windows +Enter" short key.

Repro Steps:
1.Open above URL with V- credential.
2.Navigate to 'Schema Explorer' link using tab key and press enter key to activate it.
3.Run the narrator in the scan mode.
4.Navigate to "TextBlock" link present under CardElements from the left navigation using the tab key and activate it using Enter key.
5. Navigate to this content "wrap: false Lorem ipsum dolor sit amet, consectetur...." present under the adaptive card.
6. Observe the issue in scan mode.

Actual Result:
Page is getting scrolled out after narrator reading "Consectetur..." text in the scan mode.

Expected Result:
Page should not get scrolled out after "Consectetur..." text and narrator should read the content present under the adaptive cards sequentially and it should not skip the content present under it.

User Impact:
Screen reader users who are all with low vision will be impacted if page is getting scrolled out and they will be frustrated to get the focus on to the correct position and to understand what's happening on the screen.

MAS Reference:
https://liquid.microsoft.com/Web/Object/Read/ms.accessibility/Requirements/01.03.02

"Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “.
 

### Screenshots

https://user-images.githubusercontent.com/104482612/190579514-db692a93-79c2-4f1c-88c5-4461a27f7076.mp4

### Card JSON

```JSON
NA
```

### Sample Code Language

NA

### Sample Code

NA

**Comment by vagpt** [comment]
This issue is not repro, hence closing this issue.
