### ISSUE TITLE
[Adapter Cards-Schema Explorer]: Play/Pause button present under the video gets truncated when applied Reflow settings on Adaptive Cards.

### ISSUE THREAD

**Issue by Susmitha474** [microsoft/AdaptiveCards#7892]
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive Cards

### Problem Description

Test Environment:
OS: Version 22H2 (OS Build 25197.1000)
Edge Dev: version 107.0.1379.1 (Official build) dev (64-bit)
Application URL: [[[https://adaptivecards.io/](https://nam06.safelinks.protection.outlook.com/?url=https://adaptivecards.io/&data=04%7c01%7cv-ibalam%40microsoft.com%7cbd35d875ec3f4539762308d88f709775%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637417061036711036%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=dUolQbKGi1J8gsoxC2JG5TGoNi41msPfIIjKSIyPGHM%3D&reserved=0)]([https://adaptivecards.io/explorer/)](https://adaptivecards.io/%5D(https://adaptivecards.io/explorer/)%5D(https://adaptivecards.io/))

Pre-Requisites:
Change Display Resolution to 1024* 768.
Zoom the page to 400%

Repro Steps:
1.Open above URL with V- credential.
2.Navigate to 'Schema Explorer' link using tab key and press enter key to activate it.
3.Navigate to "MEdia" link present under "CardElements" from the left navigation using the tab key and activate it using Enter key.
4. Navigate to this video content present under the adaptive card using Tab key.
5. Observe the issue.

Actual Result:
Play button got truncated in the 400% settings.

Expected Result:
Play button should not get truncated in the 400% settings.

User Impact:
The Persons with low vision will be impacted and will get confused to activate the play button if the play button is truncated when playing video under the adaptive cards.

MAS Reference Link:
https://liquid.microsoft.com/Web/Object/Read/ms.accessibility/Requirements/01.04.10

"Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “,

### Screenshots
<img width="672" alt="play button is truncated in 400% mode" src="https://user-images.githubusercontent.com/104482612/190617461-ddb6e6d6-c552-4314-929d-45fdfb5f20af.png">

### Card JSON

```JSON
NA
```

### Sample Code Language

NA

### Sample Code

NA

**Comment by vagpt** [comment]
This issue is not repro on the environment below, hence closing this issue.

**Test Environment:**
URL: https://adaptivecards.io/explorer/Media.html
Browser Version: 117.0.2045.1 Edge Dev

**Snippet:**
![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/b5a1a1dc-1ee7-4cf3-a2d4-b141c392aaaa)
