### ISSUE TITLE
Adaptive Card by using Nodemailer SMPT, but unable to open that card in email, need help..

### ISSUE THREAD

**Issue by shafqatjan** [microsoft/AdaptiveCards#7893]
# Platform
I m doing a project in which we need to send adaptive card email with dynamic content and dynamic recipient but only all the member received but only open for who are in organization, is it required domain configuration with office.com account? what kind of provider we need, test user/organization/global or any other? 

What platform is your issue or question related to? (Delete other platforms).

* NodeJS

**Comment by paulcam206** [comment]
For support on Outlook Actionable Messages, please post a question on the [Office Addins Dev](https://docs.microsoft.com/en-us/answers/topics/office-addins-dev.html) site. If you need further help more specifically about Adaptive Cards, please let us know.

Thanks!
