### ISSUE TITLE
Image formatting

### ISSUE THREAD

**Issue by jasonpaulchris** [microsoft/AdaptiveCards#7895]
I have an image element in my adaptive card. I would like to be style the image (box shadow) but I'm not seeing a way to do that. Is it possible?

---
* URL: https://adaptivecards.io/blog/

**Comment by paulcam206** [comment]
There's no way to change styling for the display of images from within the card itself. If you are also _hosting_ the card, you should be able to style the display of images using your platform's native styling mechanisms (e.g. CSS for JS, ResourceDictionary for UWP XAML).
