### ISSUE TITLE
[Adaptive Card-Schema Explorer]: Ensures attributes that begin with aria- are valid ARIA attributes (.ac-selectable)

### ISSUE THREAD

**Issue by Susmitha474** [microsoft/AdaptiveCards#7908]
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive Cards

### Problem Description

Test Environment:
OS: Version 22H2 (OS Build 25197.1000)
Edge Dev: version 107.0.1379.1 (Official build) dev (64-bit)
Application URL: [[[https://adaptivecards.io/](https://nam06.safelinks.protection.outlook.com/?url=https://adaptivecards.io/&data=04%7c01%7cv-ibalam%40microsoft.com%7cbd35d875ec3f4539762308d88f709775%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637417061036711036%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=dUolQbKGi1J8gsoxC2JG5TGoNi41msPfIIjKSIyPGHM%3D&reserved=0)]([https://adaptivecards.io/explorer/)](https://adaptivecards.io/%5D(https://adaptivecards.io/explorer/)%5D(https://adaptivecards.io/))

Pre-Requisites:
Run the Accessibility Tool on the Web page.

Repro Steps:
1.Open above URL with V- credential.
2.Navigate to 'Schema Explorer' link using tab key and press enter key to activate it.
3.Run the AI tool on the web page.
4.Navigate to "Image" link present under "Cardelements" from the left navigation using the tab key and activate it using Enter key.
5. Navigate to the "Click the Cat" content and observe the issue on Cat graphic.

Actual Issue:   Invalid ARIA attribute name: aria-description

Expected: Ensures attributes that begin with aria- are valid ARIA attributes (aria-valid-attr - https://accessibilityinsights.io/info-examples/web/aria-valid-attr)

Snippet:<img class="ac-image ac-selectable" tabindex="0" role="link" aria-description="cool link" title="cool link" src="https://adaptivecards.io/content/cats/1.png" alt="Cat" style="min-width: 0px; max-width: 100%; max-height: 100%;">

Note: This accessibility issue was found using Accessibility Insights for Web 2.34.1 (axe-core 4.4.1), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.

MAS Reference:
https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/04.01.02

"Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “.

### Screenshots

<img width="960" alt="AI tool issue for Image Link" src="https://user-images.githubusercontent.com/104482612/190993365-aad094b4-ecaf-437d-9695-bc4dc8ce723e.png">
<img width="960" alt="AI tool issue for Image1 Link" src="https://user-images.githubusercontent.com/104482612/190993376-28134613-69b1-44de-815c-657f3c0e249e.png">

### Card JSON

```JSON
NA
```

### Sample Code Language

NA

### Sample Code

NA

**Comment by vagpt** [comment]
This issue is not repro on the environment below, hence adding A11yTTValidated.

**Test Environment:**
URL: https://adaptivecards.io/explorer/Image.html
OS Version: 22H2(OS Build 25330.1000)
Browser Version: 114.0.1807.1
