### ISSUE TITLE
[Adaptive Cards> Designer> Sample Data Editor]: Screen reader is not providing any information on activating the 'sample data editor' button.

### ISSUE THREAD

**Issue by vaishali1397** [microsoft/AdaptiveCards#7919]
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
OS Version: 22H2 (Build 25197.1000)
Browser: Edge Dev (107.0.1379.1)
URL: https://adaptivecards.io/designer/
Screen reader: Narrator

**Repro steps:**

1. Open the above URL in edge dev browser and login with v-.
2. Turn on the narrator through 'Ctrl+ Windows+ Enter key.
3. Navigate to the 'Designer' tab through tab key and activate it.
4. Navigate to the 'Sample data Editor' button through tab key and activate it.
5. Observe the issue.

**Actual Result:**
On activating 'Sample data editor', Screen reader is not providing any information. Screen reader remains silent. 

**Expected Result:**
On activating 'Sample data editor', Screen reader should properly announce the information of 'Hide payload editor' button as keyboard focus remains on hide payload editor button.

**Notes:**
Same issue repro with 'Card Payload Editor', 'Card structures' and 'Element Properties'.

**User Impact:**
Screen reader user will get impacted as user will not be able to interact with the content properly**MAS Reference link:**
https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/01.03.01

**"Have feedback to share on Bugs?** Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “.

### Screenshots

https://user-images.githubusercontent.com/104483005/215496841-c4ab33b3-1966-440b-83de-4a7aaeac6de1.mp4

Uploading MAS1.3.1 Screen redaer is not announcing any information on activating sample data editor button.mp4…

### Card JSON

```JSON
NA
```

**Comment by anna-dingler** [comment]
Hi @vaishali1397!

Can you provide additional context here?

I'm seeing that Narrator (not in scan mode) does not correctly maintain focus when the 'sample data editor' button is selected. In the gif below, you can see that focus remains on the button; however, the blue outline for narrator focus does not move. Is this the behavior you are seeing as well?

![narrator](https://user-images.githubusercontent.com/98650930/199078985-c0670e86-79d6-41c3-9673-cad30b4dbc73.gif)

Thanks!

**Comment by vagpt** [comment]
Hi @anna-dingler,

Thanks for letting us know, currently we are getting same behavior as mentioned in your above comment and still screen reader is not announcing the any information to the user. So as per the expected result on activating the Sample data editor button or any other button screen reader should convey the information to the user.

**Comment by vagpt** [comment]
Closing this issue as of now this issue is being tracked using below URL;

https://github.com/microsoft/AdaptiveCards/issues/8672
