### ISSUE TITLE
[Rendering] Discrepancy (in js and C# libraries) while rendering a template containing a list type property

### ISSUE THREAD

**Issue by apurva-msft** [microsoft/AdaptiveCards#7944]
### Target Platforms

NodeJS

### SDK Version

1.3.1

### Application Name

Microsoft Search

### Problem Description

When an adaptive card template uses a list type property, there is a discrepancy in the data binding in the C# and JS libraries.

For ex. If the following expression contains a list type property 'author', on binding the data using adaptiveTemplate.Expand(source), the C# library binds the unescaped list value with the square brackets. 

Expression: "${title} - ${author}"
C# library: **"Publish Adaptive Card Schema - ["John","Jane"]"**
JS library: **"Publish Adaptive Card Schema - John,Jane"**

This is leading to JSONParseException when converting the binded template to JSON Object.

### Screenshots

![image](https://user-images.githubusercontent.com/114716277/193184267-29237e55-2ccd-4378-8913-d736adc5a109.png)
<img width="391" alt="image" src="https://user-images.githubusercontent.com/114716277/193184642-56e98697-88b1-431b-ac2b-71707ca0164e.png">

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "${title} - ${author}"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3"
}
```

### Sample Code Language

C#

### Sample Code

var source = @"{
  ""Title"":""Publish Adaptive Card Schema"",
  ""Author"":[""John"", ""Jane""]
}";
var jsonData = JObject.Parse(source);
AdaptiveCardTemplate transformer = new AdaptiveCardTemplate(jsonTemplateObj);
string cardJson = transformer.Expand(jsonData);

**Comment by jwoo-msft** [comment]
@apurva-msft , the usage is clearly wrong. If string substitute was to occur, the source has to be string. the value of 'author' is an array. you can use JPATH or index to access the elements in an array. 
e.g $author[1] or $author[2]

**Comment by apurva-msft** [comment]
@jwoo-msft,  Just to confirm: The array type property would work with the JS library, but it is considered incorrect usage for the .Net library as it is using string substitution. Is that correct? 
In that case, how is the JS library processing this differently?

**Comment by jwoo-msft** [comment]
@apurva-msft, 

It's not the string substitution at fault. I mentioned the string substitution because your intent was substituting a string in place of ${author}. However, `author`'s corresponding value in your date type is an array, ["John", "Jane"].  so the array was substituted in place of ${author}.
