### ISSUE TITLE
[UWP] put_SelectAction on Container and ColumnSet are E_NOTIMPL

### ISSUE THREAD

**Issue by anbare** [Microsoft/AdaptiveCards#795]
The put_SelectAction method hasn't been implemented on `Container` and `ColumnSet` and throws E_NOTIMPL.

Just filing this issue so that this work gets tracked, it's a known issue but I never created the issue for it.

Tricky thing is that we need to be able to update the shared model when this is put, and we currently don't have a good way to do that. Someone needs to solve that problem.

**Comment by RebeccaAnne** [comment]
Fixed by #888
