### ISSUE TITLE
[Designer] Background image not occupying entire container

### ISSUE THREAD

**Issue by JeanRoca** [microsoft/AdaptiveCards#7958]
### Problem Description

When you add a background image to a widgets board container you can see a slight white border across the widgets board container. The background image is either not occupying the entire container, or the container size is larger than it should be. It is much more noticeable on the right side of the card. The corners also show this, and I believe there might also be a tiny bit on the left side, but can't tell completely due to the dotted lines around the card.

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.6",
    "backgroundImage": {
        "url": "https://coolbackgrounds.io/images/backgrounds/black/black-contour-f41038db.svg"
    }
}
```

### Screenshot

<img width="455" alt="image" src="https://user-images.githubusercontent.com/33772802/194687402-1fb542e2-a7e9-478e-a26f-8ec6a95ab2fa.png">

**Comment by JeanRoca** [comment]
@anna-dingler would you be able to take a look at this when you get a chance?

**Comment by ibrahimirfan17** [comment]
Hi , My issue is when we are adding the background image in the post adaptive card using the url from google the  image was not visible in the background of teams notification using the html code in send an notification(v3)  in the flow of  power automate These are the data i am runnin gin the flow

body {
margin: 0;
 padding: 16px;
 background-image: url('https://img.freepik.com/premium-vector/abstract-modern-blue-white-gradient-background_181182-131.jpg');

**Comment by anna-dingler** [comment]
Hi @ibrahimirfan17,

I am closing this issue because the original bug has been fixed.

Can you please file a new issue on our repo and include a sample card payload that shows the bug?

Thank you!
Anna
