### ISSUE TITLE
[Rendering][iOS][Android][MacOS][Windows] Shared cpp MarkDownParser goes into infinite loop and makes the client unresponsive

### ISSUE THREAD

**Issue by rj100189** [microsoft/AdaptiveCards#7960]
### Target Platforms

iOS, Android, Other

### SDK Version

master

### Application Name

Webex team in iOS, Android, macOS & Windows

### Problem Description

We are experiencing the client unresponsive for rendering cards in ios, android, macOS & windows.

The issue seems to be in Adaptive card shared MarkDownParser (`AdaptiveSharedNamespace::MarkDownParser`) attempting to transform text to html (Sample JSON attached below).

When the markdown parser tries to match the left and right emphasis in the text, it goes into infinite loop comparing.

If the text is `test***URGENT***`, the parser goes into **infinite loop**.
Whereas if the text is `test ***URGENT***`, the parser **works fine**.
**_(Notice the space between `test` and `***`)_**

Path to the class is: `https://github.com/microsoft/AdaptiveCards/tree/main/source/shared/cpp/ObjectModel)/MarkDownParsedResult.cpp`
function: `MatchLeftAndRightEmphasises()`

### Screenshots

![tempsnip](https://user-images.githubusercontent.com/78340612/195038690-3639a182-643a-40f8-85c4-a4c3971256da.png)

### Card JSON

```JSON
JSON that goes in infinite loop
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "text": "test***URGENT***",
            "wrap": true
        }
    ]
}

JSON that works fine
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "text": "test ***URGENT***",
            "wrap": true
        }
    ]
}
```

### Sample Code Language

C++

### Sample Code

on the client side text is passed as `test***URGENT***`

Client initializes the MarkDownParser
`auto markdownParser = std::make_shared<AdaptiveSharedNamespace::MarkDownParser>(text);`
`text = markdownParser->TransformToHtml();`

**Comment by jwoo-msft** [comment]
thanks @rj100189 for reporting the issue;

it's fixed.

thanks.
