### ISSUE TITLE
[Adaptive Card] Action.OpenUrl is not working for opening the internal SCCM software

### ISSUE THREAD

**Issue by rahulyadav97185966** [microsoft/AdaptiveCards#7978]
### Target Platforms

NodeJS

### SDK Version

v4

### Application Name

Microsoft teams

### Problem Description

We have used an adaptive card with a button to open the SCCM software. Before one month it perfectly working fine. But now it's not doing any action. Please find the code below. and suggest answers

`
{
"type": "openUrl",
"title": "Open SCCM",
"value": "softwarecenter:SoftwareID"
},
`

### Card JSON

```JSON
{
"type": "openUrl",
"title": "Open SCCM",
"value": "softwarecenter:SoftwareID"
},
```

### Sample Code Language

Node.js

### Sample Code

{
"type": "openUrl",
"title": "Open SCCM",
"value": "softwarecenter:SoftwareID"
},

**Comment by paulcam206** [comment]
It looks like your JSON is incorrect. Try this:

```diff
{
- "type": "openUrl",
+ "type": "Action.OpenUrl",
"title": "Open SCCM",
- "value": "softwarecenter:SoftwareID"
+ "url": "softwarecenter:SoftwareID"
}
```

**Comment by rahulyadav97185966** [comment]
We are using Hero Card, So Not able to use the JSON as you suggested. Tried this JSON it didn't worked as well.
