### ISSUE TITLE
[Designer] Fallback card has an invalid language set

### ISSUE THREAD

**Issue by jofri-msft** [microsoft/AdaptiveCards#7987]
### Problem Description

At [this point](https://github.com/microsoft/AdaptiveCards/blob/0ceb34c39647f0fe811e51554466a7d417855a27/source/dotnet/Library/AdaptiveCards/AdaptiveCardConverter.cs#:~:text=language%20%3D%20CultureInfo.CurrentCulture.TwoLetterISOLanguageName%3B) during the creation on the fall back card, the language is being set to "en". 
<img width="405" alt="image" src="https://user-images.githubusercontent.com/14795675/197645459-a49f7bdc-b7a8-4ed8-918f-5a117711e3ef.png">
 The mobile client in Teams doesn't know how to process this language and causes the application to crash because the cpp handler [fails](https://github.com/microsoft/AdaptiveCards/blob/77048071baaf20899fe8931245a659ec49d8d6fe/source/shared/cpp/ObjectModel/SharedAdaptiveCard.cpp#L151-L153) the length is only 2. Instead, it should be able to handle lang of length 2 as the adaptive card explorer explicitly mentions the lang of length 2 at https://adaptivecards.io/explorer/

### Card JSON

```JSON
{
  "type": "AdaptiveCard",
  "body": [
    {
      "text": "We're sorry, this card couldn't be displayed",
      "type": "TextBlock"
    }
  ],
  "speak": "We're sorry, this card couldn't be displayed",
  "version": "1.0",
  "lang": "en"
}
```

### Screenshot

<img width="405" alt="image" src="https://user-images.githubusercontent.com/14795675/197645406-5744b937-026b-4743-85b5-ef199a8cc35b.png">

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/7621
