### ISSUE TITLE
Support of PhoneNumber inputscope in Adaptive Card for toast 

### ISSUE THREAD

**Issue by leixu2046** [Microsoft/AdaptiveCards#801]
## Request
Toasts need to be able to have a text box with a `TelephoneNumber` input scope

## Needed for
Toasts v2

**Comment by mrbrennonwilliams** [comment]
As far as I can see the AdaptiveTextInputStyle of value Tel has no effect in terms of formatting (looking at WPF) - is this still a "todo" or am I missing something?
I ask because I am interested in how the format will be dictated with so many different formats? Will that require a culture variable to validate?

**Comment by anbare** [comment]
I believe AdaptiveTextInputStyle is one of those things that hasn't been implemented fully yet.

I don't believe we have plans on changing how the text box is displayed (such as automatically inserting parenthesis and dashes into their number). I believe the style would simply be used to assign the input scope (which only makes a difference on touchscreen devices with virtual keyboards).

But this is still something that we're working on, so we'd love your feedback on how you think the style property would be best utilized @mrbrennonwilliams!

**Comment by mrbrennonwilliams** [comment]
@anbare - I agree the format of the box should remain clean of artefacts (my humble opinion). That will be a dog to get consistent across all surfaces and will add even more work when considering localisation scenarios.

The use of the term "style" does refer to a visual application though, and my thoughts are that as a property type, this should be available for the developer to perform validation as they either want (or not) in assessment of the given input value. I actually liked @leixu2046 use of the word "scope"

**Comment by anbare** [comment]
Closing this as it looks like it's already implemented in UWP renderer

```json
{
  "type": "Input.Text",
  "id": "phoneNumber",
  "style": "tel"
}
```json

That'll result in TelephoneNumber input scope being applied to the TextBox.
