### ISSUE TITLE
[Rendering] Bug Title Here

### ISSUE THREAD

**Issue by Gooyou69** [microsoft/AdaptiveCards#8014]
### Target Platforms

NodeJS

### SDK Version

2.10.0

### Application Name

JS rendering on web page via React

### Problem Description

Hello,

I'm using adaptive card via React framework. I have an array of complex objects (customer.attributes). I want to filter the array's items and display the items that respect a condition ("isVisible": "${attributeCode == ##CC3##}"). This works fine, the adaptive card display only the items I want.

However, all the items that don't respect the condition create a empty div. These divs create blank spaces. How can I get rid of them ? I noticed that the content divs are not displayed. The separator divs have a 20px height.

For information, I also tried to use the $when attribute with the same result

I tried to hard code "isVisible": false in the template. The empty divs are still here but have a "display: none" properties in their css. Therefore, they're not visible, and that's perfect. Why isn't it working with the condition ?

### Screenshots

![image](https://user-images.githubusercontent.com/92318523/200027764-defaaca5-a5a0-4ad6-987a-5d38548f8ce7.png)

### Card JSON

```JSON
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "text": "${customer.firstName} ${customer.lastName}",
      "size": "Large"
    },
    {
      "type": "Container",
      "$data": "${customer.attributes}",
      "spacing": "medium",
      "items": [
        {
          "type": "TextBlock",
          "isSubtle": "true",
          "text": "${attributeLabel}",
          "isVisible": "${attributeCode == ##CC3##}"
        },
        {
          "type": "TextBlock",
          "isVisible": "${attributeCode == ##CC3##}",
          "text": "${attributeValue.textValue}",
          "weight": "Bolder"
        }
      ]
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0"
}
```

### Sample Code Language

JSON

### Sample Code

{
  "customer": {
    "customerId": "id",
    "firstName": "David",
    "attributes": [
      {
        "attributeCode": "CC1",
        "attributeType": "TEXT",
        "attributeLabel": "Texte libre 1",
        "attributeValue": "test1"
      },
      {
        "attributeCode": "CC3",
        "attributeType": "TEXT",
        "attributeLabel": "Texte libre 3",
        "attributeValue": "test3"
      }
    ],
    "loyaltyEligible": true,
    "loyaltyAccounts": []
  }
}

**Comment by jwoo-msft** [comment]
@Gooyou69, can you raise this in our Q&A section? so others can use this question you raised?

when you bind your data, you're binding an array in the container. when you bind an array to an adaptive element, you're repeating it as many times as there are elements in the array. 
so your payload will have multiple containers, and the space you're seeing is separator between the containers.
you don't have to bind the data in the container. one way is:

 "isVisible": "${customer.attributes.[0].attributeCode == ##CC3##}"

you can also try $when, it's similar, but is different in important ways, isVisble put element in rendered card; they are just not visible. if you use $when and and the element evaluates to false, that element is removed in parsed card, so the element won't be even rendered.

**Comment by Gooyou69** [comment]
Thank you for your reply and your time.

I'm not sure to follow you: "_you don't have to bind the data in the container. one way is: "isVisible": "${customer.attributes.[0].attributeCode == ##CC3##}"_"
Do I have to put this "isVisible" in the container bloc ? Or the item bloc ? Either way, I don't have any display. 
I'm surprise to see the [0]. What if the CC3 element is in the 3rd cell of the array ? 

I think I'm missing something.

Thank you very much

I tried : 
{
      "type": "Container",
      "items": [
        {
          "type": "TextBlock",
          "isSubtle": "true",
          "text": "${fieldName}",
          "isVisible": "${attributes.[0].attributeCode == ##CC3##}"
        },
        {
          "type": "TextBlock",
          "text": "${fieldValue}",
          "weight": "Bolder",
          "isVisible": "${attributes.[0].attributeCode == ##CC3##}"
        }
      ]
    }

I also tried
{
      "type": "Container",
      "isVisible": "${attributes.[0].attributeCode == ##CC3##}",
      "items": [
        {
          "type": "TextBlock",
          "isSubtle": "true",
          "text": "${fieldName}"
        },
        {
          "type": "TextBlock",
          "text": "${fieldValue}",
          "weight": "Bolder"
        }
      ]
    }

**Comment by jwoo-msft** [comment]
@Gooyou69 
I just modified your json a little
``` json
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "text": "${customer.firstName} ${customer.lastName}",
      "size": "Large"
    },
    {
      "type": "Container",
      "$data": "${customer.attributes}",
      "spacing": "medium",
      "items": [
        {
          "type": "TextBlock",
          "isSubtle": "true",
          "text": "${attributeLabel}",
          "isVisible": "${attributeCode == \"CC3\"}"
        },
        {
          "type": "TextBlock",
          "isVisible": "${attributeCode == \"CC3\"}",
          "text": "${attributeLabel}",
          "weight": "Bolder"
        }
      ]
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0"
}
```
this results in following AdaptiveCard JSON
``` json
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "text": "David ${customer.lastName}",
            "size": "Large"
        },
        {
            "type": "Container",
            "spacing": "Medium",
            "items": [
                {
                    "type": "TextBlock",
                    "isSubtle": true,
                    "text": "Texte libre 1",
                    "isVisible": false
                },
                {
                    "type": "TextBlock",
                    "isVisible": false,
                    "text": "Texte libre 1",
                    "weight": "Bolder"
                }
            ]
        },
        {
            "type": "Container",
            "spacing": "Medium",
            "items": [
                {
                    "type": "TextBlock",
                    "isSubtle": true,
                    "text": "Texte libre 3",
                    "isVisible": true
                },
                {
                    "type": "TextBlock",
                    "isVisible": true,
                    "text": "Texte libre 3",
                    "weight": "Bolder"
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5"
}
```

As you can see, the Container element is repeated. The separator is added by the Container. 
Try either of the following options:
1. make the separator value to have "none" conditionally, 
2. add IsVisible to Container
There are more options; I'm pointing out to you that separator is added by Container; and there are multiple Containers because the data, which is bound to Container is an array. If array is bound to an Adaptive element, templating engine repeats it.
