### ISSUE TITLE
Adaptive cards are not getting rendered for Mac users in their outlook

### ISSUE THREAD

**Issue by rameshtummalapalli** [microsoft/AdaptiveCards#8016]
### Target Platforms

iOS

### SDK Version

1.0

### Application Name

MS Outlook

### Problem Description

Adaptive cards are not getting rendered for Mac users in their outlook

### Card JSON

```JSON
Adaptive cards are not getting rendered for Mac users in their outlook
```

**Comment by rameshtummalapalli** [comment]
<img width="1102" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/117489611/200364828-16a94737-da40-4c3b-ae1a-6dfda52b6e46.png">

**Comment by jwoo-msft** [comment]
it's an issue with outlook; could you please file this bug to outlook?
