### ISSUE TITLE
[Rendering] Bug Title Here

### ISSUE THREAD

**Issue by rameshtummalapalli** [microsoft/AdaptiveCards#8017]
### Target Platforms

iOS

### SDK Version

1.0

### Application Name

MS Outlook

### Problem Description

Adaptive cards are not rendering for all our employees. We have enabled adaptive cards for all our company employees. However, some colleagues are still not able to see them in the email they are receiving. We have asked them to restart their machines to push/check for the necessary update, which has worked for most, but the issue still remains for some. 

### Card JSON

```JSON
Adaptive cards are not rendering for all our employees. We have enabled adaptive cards for all our company employees. However, some colleagues are still not able to see them in the email they are receiving. We have asked them to restart their machines to push/check for the necessary update, which has worked for most, but the issue still remains for some.
```

**Comment by paulcam206** [comment]
For support on Outlook Actionable Messages, please post a question on the [Office Addins Dev](https://docs.microsoft.com/en-us/answers/topics/office-addins-dev.html) site. If you need further help more specifically about Adaptive Cards, please let us know.

Thanks!
