### ISSUE TITLE
Renderers should trim text with ... ellipses

### ISSUE THREAD

**Issue by andrewleader** [Microsoft/AdaptiveCards#802]
This is an uber task tracking work across all the renderers to trim text with ellipses. No specific time needed by, but this is something that should be done to comply with the schema

- [x] UWP
- [x] Android
- [x] iOS
- [ ] HTML Server
- [x] NodeJS

**Comment by riarenas** [comment]
UWP now does this.

**Comment by tongyliu** [comment]
This is fixed in TypeScript now as well.

**Comment by almedina-ms** [comment]
Marking iOS and Android as complete
