### ISSUE TITLE
Accessibility Issue Adaptive Card - Buttons with identical accessible names

### ISSUE THREAD

**Issue by Bradrajkumar** [microsoft/AdaptiveCards#8020]
**Issue Description : -**

Interactive elements need a programmatically determined name, role, and value. These properties must also be accurate and appropriate.
There are buttons that have identical accessible names. This may particularly disadvantage users that interface with the accessibility properties of elements, such as screen reader and voice recognition users. That the accessible name is identical may confuse or mislead users.
This has been raised as an Additional Issue as the accessible names are not wrong. However, the accessible names could be made more explicit, such that they are easier to understand and differentiate.

**Success Criteria : -**

Make sure that interactive elements have unique and descriptive names. In this case, make sure that both buttons include a reference to the specific product.
This can be achieved by using the id of the container for the product name and an aria-describedby attribute on the buttons that references this. Ensure that the id and aria-describedby values match. For example:

some text

Select this product
![6_1](https://user-images.githubusercontent.com/34365788/200263388-7b1e1d66-b531-4ee8-aa9d-2bcc1a34be4a.png)
![6_2](https://user-images.githubusercontent.com/34365788/200263395-09ac6045-2503-4014-a856-8058763c52f3.png)

**Steps to reproduce :-**

Observe the interactive elements.
Inspect the elements and review the DOM.
Review the computed accessibility properties.
Observe that the names are programmatically determined.
Observe that the names are identical.
Webchat Version :- 4.13.0

**Link to raised Issue :-**

There is an issue thread raised to Microsoft Bot framework - webchat Team and as per their Comments it is an adaptive card Issue.
Please check this link for detailed information :- https://github.com/microsoft/BotFramework-WebChat/issues/4470.

**Comment by JeanRoca** [comment]
Hi @Bradrajkumar thanks for filing this. 

Buttons in Adaptive Cards are treated as Actions and have access to the Tooltip property. We have a section in our [schema explorer](https://adaptivecards.io/explorer/Action.OpenUrl.html) talking about this property.


If this does not solve your problem, I am not understanding correctly and I am interested in learning why not :)

**Comment by Bradrajkumar** [comment]
Hi @paulcam206 , @JeanRoca,

please reopen this issue as i tried the workaround on this and found out that whenever i am changing my version of adaptive card from 1.5 to 1.3 for webchat, it is showing warning on adaptive card designer. it seems webchat latest version doesn't supports adaptive card version 1.5 for now.

**Comment by JeanRoca** [comment]
> Author

Hi @Bradrajkumar- in that case the issue is not with Adaptive Cards and instead is with the webchat team not supporting our latest version. I will be leaving this issue as closed for now as our team has provided a fix for this already

**Comment by compulim** [comment]
FYI, [Web Chat 4.15.1 released on 2022-03-04](https://github.com/microsoft/BotFramework-WebChat/blob/main/CHANGELOG.md#4151---2022-03-04) is using [Adaptive Cards library 2.10, which support Adaptive Cards schema 1.5](https://www.npmjs.com/package/adaptivecards).

@Bradrajkumar could you check what version of Web Chat you are using?
