### ISSUE TITLE
[Adaptive Cards>ActivityUpdatewithLabel.json]: Unselected text look like a selected text in HC mode

### ISSUE THREAD

**Issue by PERUAMLLABALAKRISHNA** [microsoft/AdaptiveCards#8040]
### Target Platforms

UWP

### SDK Version

3.0.2210.26001

### Application Name

Adaptive cards

### Problem Description

**Test Environment:**
OS version: 22H2 (Build 25182.1010)
Application: AdaptiveCardVisualizer
Application Version: 3.0.2210.26001
Screen Reader: Narrator

**Repro Steps:**

1.Open the Adaptive Card Visualizer application.
2.Turn on the HC mode.
3.Navigate to the 'ActivityUpdate.Json' control through tab key and activate it.
4.Now, navigate through ActivityUpdatewithLabel.json card and observe the issue.

**Actual Result:**
When the low vision user applied HC mode, unselected text look like a selected text.

**Expected Result:**
For better low vision user experience, unselected text should not look like a selected text.

**Observation:**
Same issue repro throughout the application.

**User Impact:**
Low vision users will get confusion, if the text is looks like a selected text, even if the text is not selected.

**MAS Reference:**
https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/04.03.01

### Screenshots

<img width="1720" alt="In HC mode normal text is visible as selected text" src="https://user-images.githubusercontent.com/117892125/201089566-dc31db1a-3cef-4d56-a73e-5260c90a79df.png">

### Card JSON

```JSON
NA
```

**Comment by vaishali1397** [comment]
Issue has been fixed in below test environment, hence adding A11yTTValidated tag.
**Test Environment:**
OS Version: 22H2 (Build 25330.1000)
Application: AdaptiveCardVisualizer

![image](https://user-images.githubusercontent.com/104483005/235416208-a4ee604a-21b1-4dd0-a95a-811cedf0e3d5.png)
