### ISSUE TITLE
[designer] xmark.svg is not found

### ISSUE THREAD

**Issue by becory** [microsoft/AdaptiveCards#8048]
### Discussed in https://github.com/microsoft/AdaptiveCards/discussions/8012

<div type='discussions-op-text'>

<sup>Originally posted by **becory** November  4, 2022</sup>
I want to add some features for my custom adaptive card designer.
It always shows errors when I try to build or watch adaptive card designer apps.

What can I do?
It doesn't have any documents to help me debug :(

using description file: /Users/***/Downloads/AdaptiveCards-main/source/nodejs/adaptivecards-designer-app/node_modules/adaptivecards-designer/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/***/Downloads/AdaptiveCards-main/source/nodejs/adaptivecards-designer-app/node_modules/adaptivecards-designer/package.json (relative path: ./assets/xmark.svg)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/***/Downloads/AdaptiveCards-main/source/nodejs/adaptivecards-designer-app/node_modules/adaptivecards-designer/assets/xmark.svg doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/***/Downloads/AdaptiveCards-main/source/nodejs/adaptivecards-designer-app/node_modules/adaptivecards-designer/assets/xmark.svg.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        /Users/***/Downloads/AdaptiveCards-main/source/nodejs/adaptivecards-designer-app/node_modules/adaptivecards-designer/assets/xmark.svg.tsx doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/***/Downloads/AdaptiveCards-main/source/nodejs/adaptivecards-designer-app/node_modules/adaptivecards-designer/assets/xmark.svg.js doesn't exist
      as directory
        /Users/***/Downloads/AdaptiveCards-main/source/nodejs/adaptivecards-designer-app/node_modules/adaptivecards-designer/assets/xmark.svg doesn't exist
 @ ./node_modules/adaptivecards-designer/lib/adaptivecards-designer-standalone.js 24:13-40
 @ ./node_modules/adaptivecards-designer/lib/adaptivecards-designer.js 17:13-59
 @ ./src/app.ts 7:17-50</div>

**Comment by omoore-senso** [comment]
Did you manage to fix this? I'm getting the same error

**Comment by nbelyh** [comment]
@anna-dingler  The PR does not seem to fix it ☹️ 
The "assets" folder **does not seem to be a part of the NPM package** (adaptivecards-designer) at all?

I would suggest to get rid of the `svg-url-loader` maybe, what's the point? It's a whole library brought into the project for showing a loading **a single svg image** (cross from font awesome) using webpack. Nah, seriously? First, it is not really required; webpack can load svg image urls just just fine. Second, having a separate svg image in a separate folder looks like a pain. Then the "assets" folder is not even part of the npm package, unless I'm mistaking (i.e. adaptivecards-designer)!

Also, why not to use inline image??

**Comment by anna-dingler** [comment]
Hi @becory,

I just made an update to our main branch that should resolve this issue. Can you let me know if the issue is resolved on your end?

I will discuss an official release with my team so that we can get a new package out.

Thanks!

**Comment by olliejm** [comment]
I'm also having this issue. Whenever I update `adaptivecards-designer` beyond version `2.3.0`, the Gatsby project which uses the designer fails to compile with the `Can't resolve '../assets/xmark.svg'` error. This has been happening for quite some time and preventing us from updating the designer. It has sometimes been a different SVG file path that gets printed in the error.
