### ISSUE TITLE
.NET Base Library does not support Adaptive Cards Schema 1.5

### ISSUE THREAD

**Issue by justin-mellor** [microsoft/AdaptiveCards#8063]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET HTML

# Author

If you're an author, who are you sending cards to? WebChat and Teams

# Version of SDK

DotNet 2.7.3

# Issue

Can't load an Adaptive Card with schema 1.5 to support tables
https://github.com/microsoft/AdaptiveCards/blob/dotnet-v2.7.3/source/dotnet/Library/AdaptiveCards/AdaptiveCard.cs#L41
only supports 1.4.
Even main that hasn't been released does not seem to have any Table support in the code.

**Comment by paulcam206** [comment]
@jwoo-msft can comment here :)

**Comment by jwoo-msft** [comment]
AdaptiveCards nuget package is going to release this Thursday.
