### ISSUE TITLE
[Rendering] Microsoft Teams does not post back the Data property of Action.Submit if it is a string

### ISSUE THREAD

**Issue by gildas** [microsoft/AdaptiveCards#8064]
### Target Platforms

Other

### SDK Version

REST API 1.3

### Application Name

Microsoft Teams

### Problem Description

If I send a Card to Teams with an Action.Submit's Data set to a string, Teams does not send it back in the `value` property of the message event.

If the Data is an object, then Teams sends it back.

According to the documentation, both strings and objects can be used (https://adaptivecards.io/explorer/Action.Submit.html)

This will produce an empty `value` field in the message event:
```json
{ ...
  "content": {
    "type": "AdaptiveCard",
    ...
    "body": [ ... ]
    "actions": [
      {
        "type": "Action.Submit",
        "title": "Title",
        "data": "something"
      }
    ]
  }
}
```

This will produce `"value": { "response": "something" }` in the message event:
```json
{ ...
  "content": {
    "type": "AdaptiveCard",
    ...
    "body": [ ... ]
    "actions": [
      {
        "type": "Action.Submit",
        "title": "Title",
        "data": {
          "response": "something"
        }
      }
    ]
  }
}
```

### Card JSON

```JSON
{
  "type": "AdaptiveCard",
  "$schema": "https://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.3",
  "body": [
    {
      "type": "TextBlock",
      "text": "Question",
      "size": "Medium",
      "wrap": true
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Title",
      "data": "something"
    }
  ]
}
```

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/7581
