### ISSUE TITLE
[Designer] Adaptive Card works on emulator but not Teams

### ISSUE THREAD

**Issue by duonghaichau** [microsoft/AdaptiveCards#8065]
Hi there,
I tested Adaptive card by curl to my MS Teams webhook:
curl -H 'Content-Type: application/json' -d @size1.json  $mywh
In the json file, I specified external URL image https://image-charts.com/chart?cht=pd&chd=t%3A24.119127516778523%2C74.66442953020135%2C1.2164429530201342&chs=700x400&chdl=Failed%7CPassed%7CSkipped&chl=24.1%25%7C74.7%25%7C1.2%25&chco=ed421f%7C37b84c%7CA9A9A9&chli=2384&chlps=color%2CFFFFFF%7Cfont.size%2C10%7CtextStrokeWidth%2C0.4&chdlp=b

From my team channels, image is not rendered:
<img width="898" alt="image" src="https://user-images.githubusercontent.com/59863242/202833580-8ae3dde0-0410-4f89-ab87-c6688e39bab7.png">

However, it's working on Adaptive Cards https://adaptivecards.io/designer as below image:
<img width="737" alt="image" src="https://user-images.githubusercontent.com/59863242/202833660-6fe5d7a2-48b9-4fc1-bc3c-2ddefb33835c.png">
My json file is here:
[size1.json.zip](https://github.com/microsoft/AdaptiveCards/files/10046028/size1.json.zip)

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/7580
