### ISSUE TITLE
TypeScript Renderer allows newlines with wrap false

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#807]
The TypeScript renderer allows a TextBlock to wrap lines with \n\n even with `wrap: false` - is this expected? If so we need to doc in the spec and verify other renderers.

![image](https://user-images.githubusercontent.com/1432195/31856760-29237f98-b67e-11e7-941d-8d3e73be616b.png)

```json
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
	    {
			"type": "TextBlock",
			"text": "Publish Adaptive\n\n Card schema",
			"weight": "bolder",
			"size": "medium",
			"wrap": false
		}
    ]	
}
```

**Comment by andrewleader** [comment]
Closing as this is expected/correct and how UWP/WPF also behave. Wrapping just limits whether the text should wrap, but it doesn't impose max lines.
