### ISSUE TITLE
[Authoring] Action.ToggleVisibility is not working within Action.ShowCard

### ISSUE THREAD

**Issue by thijoubert** [microsoft/AdaptiveCards#8086]
### Target Application

Microsoft Teams, Outlook

### Application Operating System

Windows

### Schema Version

1.4

### Problem Description

Following an event, I contact my end-users to get answers. 
- Yes 
- No

If Yes, I want that they precise Option 1 or Option 2. 

To do this, I am using: 
- Two Action.ShowCard to display "Yes" and "No"
- Within the "Yes" Card, an Action.ToggleVisibility to select "Option 1" and "Option 2". 
- If I select "Option 1" or "Option 2" some text and a "Confirm" button shall be displayed. These elements are not visibile by default

However, when I put the Action.ToggleVisibility within a an Action.ShowCard there is no effect when I activate the Toggle. 

### Expected Outcome

When I activate an Action.ToggleVisibility action within the ShowCard, I should see the targeted elements. 

### Actual Outcome

I cannot manage to change the visibility of items within ShowCard. 

For example, in the code below I cannot change the visibility of "MyText 1"

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.4",
    "body": [
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.ShowCard",
                    "title": "Action.ShowCard",
                    "card": {
                        "type": "AdaptiveCard",
                        "body": [
                                {
            "type": "Container",
            "isVisibility": false,
            "id": "id11",
            "items": [
                {
                    "type": "ActionSet",
                    "actions": [
                        {
                            "type": "Action.ToggleVisibility",
                            "title": "Action.ToggleVisibility",
                            "targetElements": [
                                "id1"
                            ]
                        }
                    ]
                },
                {
                    "type": "RichTextBlock",
                    "isVisibility": false,
                    "id": "id1",
                    "inlines": [
                        {
                            "type": "TextRun",
                            "text": "My Text 1"
                        }
                    ],
                    "isVisible": true

                }
            ]
        }
                            ]
                    }
                }
            ]
        }
    ]
}
```

**Comment by paulcam206** [comment]
noted in #8066:

> Action.Toggle Visibility stopped working when in a showcard sometime around last Friday(18th Nov 2022).

**Comment by jwoo-msft** [comment]
this probably be considered blocker for next release involving main; taking note here.
