### ISSUE TITLE
[Adaptive cards]: Ensures role attribute has an appropriate value for the element.

### ISSUE THREAD

**Issue by vaishali1397** [microsoft/AdaptiveCards#8135]
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
OS version: 22H2 (Build 25252.1010)110.0.1543.0 
Browser: Edge Dev (110.0.1543.0)
URL: https://adaptivecards.io/
Tool: Accessibility Insights for Web

**Repro Steps:**

1. Open the above URL in edge dev browser.
2. Turn on the fast pass of accessibility insights for web.
3. Observe the issue.

**Actual Result:**
Ensures role attribute has an appropriate value for the element.

**Expected Result:**
Ensures role attribute has an appropriate value for the element.

**User Impact:**
Screen reader user will get impacted if incorrect role is defined due to which user will not be able to understand the purpose of the content easily.

**MAS Reference link:**
https://microsoft.sharepoint.com/:w:/s/accessibility/EXdDUZzldv5MgwDaMHnTzcMBcT8opKGncYjU-gCJ4uqQdg?e=9nuVmt

“Have feedback to share on Bugs? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-vaibgu%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400980259288%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=TrcBaCyAPKg0WAQfdSZJP2i9pghMEDg59i2NeUUs5EQ%3D&reserved=0) “

### Screenshots

<img width="957" alt="MAS1 3 1 Ensure role attribute has an appropriate value" src="https://user-images.githubusercontent.com/104483005/207063878-63de0274-7ced-4fb1-b7aa-131df9e5cd4a.png">
<img width="580" alt="Code snippet" src="https://user-images.githubusercontent.com/104483005/208441108-e5fa5a03-4625-4707-af5e-6c47132ca4cd.png">
![image](https://user-images.githubusercontent.com/104483005/208441073-8ebf18e2-c6c7-42c4-875d-c81f3d1beb8a.png)

### Card JSON

```JSON
NA
```

**Comment by vagpt** [comment]
This issue is not repro, hence closing this issue.

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/1a8282ae-419b-48a5-a67f-3c136cf877c9)
