### ISSUE TITLE
Input.ChoiceSet - empty select option rendered when placholder text is missing.

### ISSUE THREAD

**Issue by kmaughan** [microsoft/AdaptiveCards#8144]
# Platform

* .NET WPF
* WebView User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; WebView/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19042

# Version of SDK

0.6.1

# Issue

https://github.com/microsoft/AdaptiveCards/blob/3790b9d1562dd210b01b30ae468f6fb2ef0e3b53/source/nodejs/adaptivecards/src/card-elements.ts#L4274

# Expected

When a placeholder value is not provided for _select_ elements, the placeholder _option_ element should not be rendered
  
# Actual

Currently, the element is rendered with 'disabled' and 'hidden' attributes which works for _most_ client applications.  However, Microsoft WebView clients ignore the 'hidden' attribute and the option is rendered adding an extra space to the option dropdown list.

![image](https://user-images.githubusercontent.com/20192595/207466104-e4f42352-a056-4a4c-907c-cd6a565294d5.png)
![image](https://user-images.githubusercontent.com/20192595/207466308-b6559993-f44f-45ba-9d8f-7fc4b23634a3.png)

**Comment by JeanRoca** [comment]
@paulcam206 / @jwoo-msft pinging this issue so we can make sure it is triaged in our next triage session :)

**Comment by jwoo-msft** [comment]
> # Platform
> * .NET WPF
> * WebView User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; WebView/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19042
> 
> # Version of SDK
> 0.6.1
> 
> # Issue
> https://github.com/microsoft/AdaptiveCards/blob/3790b9d1562dd210b01b30ae468f6fb2ef0e3b53/source/nodejs/adaptivecards/src/card-elements.ts#L4274
> 
> # Expected
> When a placeholder value is not provided for _select_ elements, the placeholder _option_ element should not be rendered
> 
> # Actual
> Currently, the element is rendered with 'disabled' and 'hidden' attributes which works for _most_ client applications. However, Microsoft WebView clients ignore the 'hidden' attribute and the option is rendered adding an extra space to the option dropdown list.
> 
> ![image](https://user-images.githubusercontent.com/20192595/207466104-e4f42352-a056-4a4c-907c-cd6a565294d5.png) ![image](https://user-images.githubusercontent.com/20192595/207466308-b6559993-f44f-45ba-9d8f-7fc4b23634a3.png)

@kmaughan,

You are using JS renderer from npmjs, right?

**Comment by kmaughan** [comment]
@jwoo-msft  we use markdown-it  13.0.1

**Comment by jwoo-msft** [comment]
@kmaughan,
Can you share the link to ADO workitem for this issue?
Do you also have JSON for this issue?

If there is no placeholder, AC shows an empty dropdown menu like this.
![image](https://user-images.githubusercontent.com/4112696/216670820-01546790-f7b6-4473-ab6a-3035508ea734.png)
Is this the desired behavior for your customer?
Directing the customers to provide placeholder text in their JSON is the quickest and easiest way to fix the issue.
or they can also provide 'value' field. 
```json
        { 
            "type": "Input.ChoiceSet", 
            "id": "snooze",
            "value": "1",
            "choices": [ 
                {
                    "title": "5 minutes",
                    "value": "1"
                },
```
![image](https://user-images.githubusercontent.com/4112696/216671754-990b6dbe-f968-479b-a3c4-dd9d2bbc9aba.png)
Have you talked to the customers to provide either value or placeholder?
Finally, not including placeholder options when it's not provided in JSON will result in behavior change. It will default to show the first item in the list. Which is different from current behavior.

**Comment by kmaughan** [comment]
@jwoo-msft we are already using a 'value' field.  The 'value' field value is correctly displayed as the default selection. 
![image](https://user-images.githubusercontent.com/20192595/216713985-8bf47d78-c383-488b-b20d-56712a46d2af.png)

` {
	"type": "Input.ChoiceSet",
	"choices": [
		{
			"title": "Provide...",
			"value": "option 1"
		},
		{
			"title": "Virtual...",
			"value": "option 2"
		},
		{
			"title": Virtual...",
			"value": "option 3"
		},
		{
			"title": "Provide...",
			"value": "option 4"
		},
		{
			"title": "Unable...",
			"value": "option 5"
		},
		{
			"title": "Not Specified",
			"value": "Not Specified"
		}
	],
	"value": "Not Specified",
	"id": "someId"
 }`
