### ISSUE TITLE
.NET: Unknown children type in Container and Column get returned as null

### ISSUE THREAD

**Issue by anbare** [Microsoft/AdaptiveCards#819]
In the .NET library, when parsing a JSON payload that has unknown element types (like `MattsFancyTextBlock`), if those children are within a `Container` or `Column`, they get inserted into the children list as null, rather than completely being dropped, and these null items within the list will cause null reference exceptions for renderers and consumers.

We fixed this in `AdaptiveCard` for 1st level children by having a custom JSON converter that removes null items from the Body/Actions lists, but that only works for 1st level children. We would either need to do the same converter for `Container` and `Column`, or implement something else.

This issue tracks this bug which we have to fix at some point.

**Comment by mrbrennonwilliams** [comment]
Shouldn't it be the element renderer that is responsible? I know we all like to *assume* the object coming to us in a method is valid - but history shows this approach will almost always fail. The renderer should have a graceful fail mechanism at any rate, so why not perform the validation there as well?

AdaptiveContainerRenderer.cs
`
        public static void AddContainerElements(Grid uiContainer, List<AdaptiveElement> elements, AdaptiveRenderContext context)
        {
            **foreach (var cardElement in elements.FindAll(x=> x!=null))**
            {
                // each element has a row`
  

Perhaps I am looking at this too simplistically? Perhaps I am just an old dog?

The converter route eventually adds _some_ performance overhead as I assume you have something like:
` [Browsable(false)]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    sealed internal class GenericBaseItemConverter <B,C, R> : JsonConverter
    {
        public override bool CanWrite => false;
        public override bool CanConvert(Type objectType)
        {
            return typeof(R).IsAssignableFrom(objectType);
        }
//..... the rest of it
`
In my experience, any object that has this type of converter applied to it, then has every property (of the type being converted) compared for conversion, with the CanConvert method - string, bool etc everything gets checked.

This may not be noticeable with small payloads and resulting object graphs.

Don't get me wrong, I like the Converter concept, for me it can get out of hand when you start needing to convert collections beyond a list - i.e. a converter for Dictionary<string,myType> is different then a Dictionary<guid, myType> which runs into Dictionary<guid, List<myType>> and on and on.

Other folks with a broader view of all platforms may have a valid argument against me though. I guess as long as the approach is consistent, that in the long run should trump any other arguments for and against.

**Comment by anbare** [comment]
If the host (like Skype or Timeline) wants to support a custom type, then they add a custom type parser to the Adaptive Card parser, and then their parsed card will contain their custom type.

Otherwise, all unknown types are dropped (and in the future we'll provide warning callbacks that tell you about the dropped element types).

The reason we want this logic in the parser vs the renderer is that the parser is shared by many renderers, so that logic only needs to be implemented once.

**Comment by mrbrennonwilliams** [comment]
I think I may be confused as to what area you were referring - I read
> In the .NET library, when parsing a JSON payload
I thought you were  talking about AdaptiveCard.cs FromJSON() as opposed to a shared parser (which I still don't understand where that is?)

I like the sound of custom type support and I look forward to seeing how that is implemented.

**Comment by matthidinger** [comment]
This is actually fixed in the latest drop. The Renderer will skip unknown elements (and return a warning that it did so)
