### ISSUE TITLE
Accessibility Full Conformance test pass on Adaptive Cards UWP  in Dec'22

### ISSUE THREAD

**Issue by vaishali1397** [microsoft/AdaptiveCards#8193]
### Target Platforms

UWP

### SDK Version

3.0.2210.26001

### Application Name

Adaptive Cards

### Problem Description

https://github.com/microsoft/AdaptiveCards/issues/7826
https://github.com/microsoft/AdaptiveCards/issues/7788
https://github.com/microsoft/AdaptiveCards/issues/7791
https://github.com/microsoft/AdaptiveCards/issues/7786
https://github.com/microsoft/AdaptiveCards/issues/7607
https://github.com/microsoft/AdaptiveCards/issues/7619
https://github.com/microsoft/AdaptiveCards/issues/7516
https://github.com/microsoft/AdaptiveCards/issues/7625
https://github.com/microsoft/AdaptiveCards/issues/7519
https://github.com/microsoft/AdaptiveCards/issues/7518
https://github.com/microsoft/AdaptiveCards/issues/7828
https://github.com/microsoft/AdaptiveCards/issues/7829
https://github.com/microsoft/AdaptiveCards/issues/7618
https://github.com/microsoft/AdaptiveCards/issues/7839
https://github.com/microsoft/AdaptiveCards/issues/7830
https://github.com/microsoft/AdaptiveCards/issues/8189
https://github.com/microsoft/AdaptiveCards/issues/8191
https://github.com/microsoft/AdaptiveCards/issues/7521
https://github.com/microsoft/AdaptiveCards/issues/7520
https://github.com/microsoft/AdaptiveCards/issues/8188
https://github.com/microsoft/AdaptiveCards/issues/8187
https://github.com/microsoft/AdaptiveCards/issues/7682
https://github.com/microsoft/AdaptiveCards/issues/7608
https://github.com/microsoft/AdaptiveCards/issues/7611
https://github.com/microsoft/AdaptiveCards/issues/7610
https://github.com/microsoft/AdaptiveCards/issues/7609

### Card JSON

```JSON
NA
```

**Comment by Raisul123** [comment]
Test Pass Completed
