### ISSUE TITLE
[Designer] The designer does not resolve facts

### ISSUE THREAD

**Issue by Mrxx99** [microsoft/AdaptiveCards#8198]
If you just go to https://adaptivecards.io/designer/ you will directly see this (wihtout any changes to default card):
![grafik](https://user-images.githubusercontent.com/33566379/210185944-77eacdf7-15cd-44f2-874b-429c598899ab.png)

The facts are not rendered even though the data is provided corretly (at least it looks correct to me)

**Comment by anna-dingler** [comment]
Hi @Mrxx99,

Since the FactSet is bound to the data, you need to be in **Preview** mode for it to render properly.

<img width="644" alt="image" src="https://user-images.githubusercontent.com/98650930/210379473-35e24b6d-c19b-4f32-9ef2-9b86475062cd.png">

Let me know if you have any other questions!

**Comment by Mrxx99** [comment]
> Since the FactSet is bound to the data, you need to be in **Preview** mode for it to render properly.

But why are then the other bound properties displayed when not in Preview mode, that seems to be inconsistent. How is the FactSet (${properties}) different to e.g. the description (${description})?

**Comment by anna-dingler** [comment]
@Mrxx99 We provided special handling for TextBlocks in Design mode. This is the only portion of the templating library that will work without switching to Preview mode.
