### ISSUE TITLE
HTML Renderer - Allow users to override TextFormatter

### ISSUE THREAD

**Issue by harshithkashyap** [microsoft/AdaptiveCards#820]
The current [formatText function](https://github.com/Microsoft/AdaptiveCards/blob/master/source/nodejs/adaptivecards/src/text-formatters.ts#L45-L58) uses `toLocaleTime/DateString` to parse datetime from text. We wanted to use [momentjs calendar time](http://momentjs.com/docs/#/displaying/calendar-time/) function to format the time based on end user's local timezone.

The only way I can think of to achieve this now is to store user's timezone in the db and use the momentjs function before sending adaptive card attachment.

Would you consider this a feature request to allow users to provide a custom implementation of `formatText` function?

```
new AdaptiveCards.AdaptiveCard({
    formatText: () => {/* user implemented logic */}
});
```

**Comment by matthidinger** [comment]
Seems like a good suggestion. @dclaux  thoughts here?

**Comment by RebeccaAnne** [comment]
This is a good suggestion, but not something that's on our roadmap at this time. We may reconsider it in the future, or if you would like to make a contribution please see our contribution guidelines [here](https://github.com/microsoft/AdaptiveCards/blob/main/.github/CONTRIBUTING.md).
