### ISSUE TITLE
[Designer] AdaptiveCard's backgroundImage's fillMode=Cover is not wired

### ISSUE THREAD

**Issue by elyasaf755** [microsoft/AdaptiveCards#8238]
**Repro steps:**
1. Select the `host app` to be `Widgets Board`
2. In the `CARD STRUCTURE` panel on the right, click on the `AdaptiveCard` element
3. Under the `Background image` properties, change the `fillMode` property to `Cover`
4. Go to the `CARD PAYLOAD EDITOR` panel, inspect the generated JSON, and look for the `fillMode` property

**Current behavior:**
The `fillMode` property did not set to `Cover`

**Expected behavior:**
The `fillMode` property should set to `Cover`

**Note:**
The `fillMode` property value changes accordingly to any other value.

**Comment by anna-dingler** [comment]
Hi @elyasaf755,

Are you seeing a change in the card?

Since `Cover` is the default for `fillMode`, we do not add it to the generated payload.

Thanks,
Anna

**Comment by elyasaf755** [comment]
Hi @anna-dingler,

It doesn't matter what's the default value for `fillMode`, right? let's say I select `Repeat` as `fillMode`, then I want to change back to `Cover` by selecting it from the dropdown. In that case, `fillMode` will remain as `Repeat` because selecting `Cover` does absolutely nothing, so I'll have to change the `fillMode` in the JSON by hand.
