### ISSUE TITLE
[Rendering] SVG Image with explicit dimensions doesn't support Size and explicit size

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/AdaptiveCards#8243]
### Target Platforms

UWP

### SDK Version

3.1.0

### Application Name

N/A

### Problem Description

SVG image that has dimension doesn't support size: small, medium, large, and explicit size.

### Screenshots

![image](https://user-images.githubusercontent.com/4112696/213370178-1e2a6d6e-f876-40d2-b898-e24ffd299467.png)
![image](https://user-images.githubusercontent.com/4112696/213370256-61dd950e-2176-4b1f-a9f3-55dd9e6c49b9.png)

### Card JSON

```JSON
{
  "type": "AdaptiveCard",
  "version": "0.5",
  "body": [
    {
      "type": "Image",
      "url": "https://adaptivecards.io/content/adaptive-card.svg",
      "size": "small"

    }
  ]
}
```

**Comment by anna-dingler** [comment]
Note: this is only an issue for SVGs that set an explicit height.

**Comment by anna-dingler** [comment]
Fixed with the above PR.
