### ISSUE TITLE
[Website] [Broken Link]

### ISSUE THREAD

**Issue by appliedcognetics** [microsoft/AdaptiveCards#8244]
The link https://adaptivecards.io/community-calls/ seems to be broken it does not take me to a registration for a community call
---
* URL: https://adaptivecards.io/community-calls/

**Comment by paulcam206** [comment]
@JeanRoca - can you take a look?

**Comment by JeanRoca** [comment]
Hi @appliedcognetics There will no longer be standalone community calls for Adaptive Cards. Instead, we have joined the M365 Platform calls [https://aka.ms/m365-dev-call](https://t.co/l1sNNbd3Ng)

These calls happen on a more frequent cadence and our team will join on occasion when we have topics to announce.
