### ISSUE TITLE
[Rendering] Multiple TextBlock spacing issue when first block contains mention

### ISSUE THREAD

**Issue by wooly** [microsoft/AdaptiveCards#8278]
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Microsoft Teams

### Problem Description

The 'none' spacing option appears to not be taking effect when used on a TextBlock element immediately proceeding another TextBlock element containing a mention in MS Teams for Mac. This is from an adaptive card sent by a teams bot to a channel only. Adaptive cards sent by the bot in chat are unaffected.

### Screenshots

Example 1: Teams channel adaptive card

<img width="621" alt="Screen Shot 2023-02-03 at 10 13 52 am" src="https://user-images.githubusercontent.com/351076/216473935-6b12d822-a50c-4ece-b03b-bff69469b6e9.png">

Example 2: Teams chat adaptive card

<img width="631" alt="Screen Shot 2023-02-03 at 10 14 29 am" src="https://user-images.githubusercontent.com/351076/216473991-8acb0dce-fad0-4ce5-bd7f-b4b9281841c1.png">

Example 3: Teams channel adaptive card no mention

<img width="618" alt="Screen Shot 2023-02-03 at 10 15 42 am" src="https://user-images.githubusercontent.com/351076/216474020-1e6d18c2-7d8e-46b6-a732-7bbe0b482209.png">

### Card JSON

```JSON
JSON for examples 1 and 2:

{
  "contentType": "application/vnd.microsoft.card.adaptive",
  "content": {
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.5",
    "msteams": {
      "entities": [
        {
          "type": "mention",
          "text": "<at>Steve Bell</at>",
          "mentioned": {
            "id": "<snipped>",
            "name": "Steve Bell"
          }
        }
      ],
      "width": "full"
    },
    "body": [
      {
        "type": "TextBlock",
        "text": "<at>Steve Bell</at>",
        "weight": "Bolder",
        "wrap": true
      },
      {
        "type": "TextBlock",
        "isSubtle": true,
        "spacing": "none",
        "text": "Business Owner",
        "wrap": true
      }
    ],
    "actions": []
  }
}

JSON for example 3:

{
  "contentType": "application/vnd.microsoft.card.adaptive",
  "content": {
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.5",
    "msteams": {
      "entities": [

      ],
      "width": "full"
    },
    "body": [
      {
        "type": "TextBlock",
        "text": "Steve Bell",
        "weight": "Bolder",
        "wrap": true
      },
      {
        "type": "TextBlock",
        "isSubtle": true,
        "spacing": "none",
        "text": "Business Owner",
        "wrap": true
      }
    ],
    "actions": []
  }
}
```

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/8084
