### ISSUE TITLE
what other video sites are supported by Adaptivecards 

### ISSUE THREAD

**Issue by denniszhang49** [microsoft/AdaptiveCards#8282]
Hi, whether the Adaptive Cards can support any other video website except Youtube, I have tried to use Youtube video URI as the source of Media and it works, but my users cannot see these videos because it's on Youtube and they do not have VPN to see it in China. I also try to find the videos URI in some other websites but cannot use them as source. I want to know whether there have some sites and the videos in the sites can be used in Adaptivecards so I can upload video to the site
[Your detailed feedback here]

---
* URL: https://adaptivecards.io/explorer/MediaSource.html

**Comment by jwoo-msft** [comment]
@denniszhang49,
AdaptiveCards doesn't do anything special. the mimetype is just a hint for video player. 
as long a the video can be serviced by uri and amongst the supported video types, it will work.
