### ISSUE TITLE
[Designer] Adaptive Card Auto Scroll in Teams

### ISSUE THREAD

**Issue by kraken8585** [microsoft/AdaptiveCards#8332]
Hi guys,

When a user clicks on an action.showcard , it outputs more options below in the Teams chat. However, upon click, a user would need to scroll down to see the other options. Can we set this to auto scroll? 

Similar issue seen in a different host app here
https://github.com/microsoft/BotFramework-WebChat/issues/470

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/8247
