### ISSUE TITLE
{Freeway-Bug}[Schema Explorer- TextBlock]: Ensures elements with ARIA roles have all required ARIA attributes.

### ISSUE THREAD

**Issue by vagpt** [microsoft/AdaptiveCards#8348]
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
URL: https://adaptivecards.io/
OS Version: 22H2 (OS Build 25390.1000)
Browser: Edge Dev (111.0.1661.27)
Tool: Accessibility Insight for Web

**Repro steps:**
1. Open the above URL in the edge dev browser.
2. Navigate to the 'Text Block' under 'Cards Elements' and press enter key to activate it.
3. Now, Navigate to the options present under 'style' and run the tool and observe the issue.

**Actual Result:**
Elements with ARIA roles do not have all the required ARIA attributes.

**Expected Result:**
Ensures elements with ARIA roles have all required ARIA attributes.

**Element path:** 
.ac-textBlock[role="heading"]:nth-child(1)

**How to fix:** 
Fix any of the following:
  Required ARIA attribute not present: aria-level

**Note:**
Same issue is repro with 'Publish Adaptive Card Schema' under 'Activity Update' screen.

**User Impact:**
It will impact the screen reader user if the elements do not have ARIA roles have ARIA attributes.

**WCAG Reference:**
https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html

"Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “,

### Screenshots

![MAS4 1 2-Ensures elements with ARIA roles have all required ARIA attributes](https://user-images.githubusercontent.com/95913748/223358264-8c4f0217-76a2-406c-9efc-1542e69035d4.png)

![image](https://user-images.githubusercontent.com/95913748/223392903-d06493c7-5c28-444a-9956-e9316954998b.png)

### Card JSON

```JSON
NA
```

**Comment by anna-dingler** [comment]
Hi @vagpt,

Closing this issue because it doesn't repro on the latest release of our website. Please let me know if you have any questions!

**Comment by vagpt** [comment]
This issue is not repro on the below environment, hence closing this issue.

**Test Environment:**
URL: https://adaptivecards.io/explorer/TextBlock.html
OS Version: 22H2(OS Build 25330.1000)
Browser Version: 114.0.1807.1
