### ISSUE TITLE
[Adaptive Cards]: Ensures elements with an ARIA role that require child roles contain them.

### ISSUE THREAD

**Issue by vaishali1397** [microsoft/AdaptiveCards#8363]
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive cards

### Problem Description

**Test Environment:**
OS version: 22H2 (Build 25314.1000)
Browser: Edge Dev (Version 111.0.1661.36 (Official build) dev (64-bit))
URL: https://adaptivecards.io/explorer/Table.html
Tool: Accessibility Insights for Web

**Repro Steps:**
1. Open the above URL in edge dev browser.
2. Turn on the fast pass of accessibility insights for web.
3. Observe the issue.

**Actual Result:**
Elements with an ARIA role that require child roles does not contain them.

**Expected Result:**
Ensures elements with an ARIA role that require child roles contain them.

**Snippet**: <div role="table" style="display: flex; flex-direction: column; box-sizing: border-box; flex: 0 0 auto; padding: 0px; margin: 0px;">

**How to fix:** 
Fix any of the following:
  Element has children which are not allowed (see related nodes)
  Element has no aria-busy="true" attribute

**User Impact**:
Screen reader user will get impacted as user will have difficulty in making track or in navigating the content properly.

**MAS Reference link:**
https://microsoft.sharepoint.com/:w:/s/accessibility/EXdDUZzldv5MgwDaMHnTzcMBcT8opKGncYjU-gCJ4uqQdg?e=9nuVmt

“Have feedback to share on Bugs? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-vaibgu%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400980259288%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=TrcBaCyAPKg0WAQfdSZJP2i9pghMEDg59i2NeUUs5EQ%3D&reserved=0) “

### Screenshots

<img width="960" alt="MAS1 3 1 Ensures elements with an aria role" src="https://user-images.githubusercontent.com/104483005/224680427-408a9300-c6d9-4a0b-8969-3d9e5281f98d.png">

### Card JSON

```JSON
NA
```

**Comment by vagpt** [comment]
This issue is not repro, hence closing this issue.

Snippet:

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/7718dae2-09de-4268-ab41-3c4911ab05b9)
