### ISSUE TITLE
[Adaptive Cards]: Ensures ARIA attributes are allowed for an element's role.

### ISSUE THREAD

**Issue by vaishali1397** [microsoft/AdaptiveCards#8364]
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
OS version: 22H2 (Build 25314.1000)
Browser: Edge Dev (Version 111.0.1661.36 (Official build) dev (64-bit))
URL: https://adaptivecards.io/explorer/Input.ChoiceSet.html
Tool: Accessibility Insights for Web

**Repro Steps:**
Open the above URL in edge dev browser.
Turn on the fast pass of accessibility insights for web.
Observe the issue.

**Actual Result:**
ARIA attribute is not allowed: aria-required="true".

**Expected Result:**
Ensures ARIA attributes are allowed for an element's role.

Element path: #__ac-fed4d876-560e-44c3-8669-5636f1d97e0d

Snippet: <div class="ac-input ac-choiceSetInput-expanded ac-input-required" tabindex="0" id="__ac-fed4d876-560e-44c3-8669-5636f1d97e0d" aria-required="true" style="width: 100%; min-width: 0px;">

How to fix: 
Fix any of the following:
  ARIA attribute is not allowed: aria-required="true"

**Notes:**
This issue is also repro under Input.Text' screen.

**User Impact:**
Screen reader user will get impacted as user will have difficulty in making track or in navigating the content properly.

**MAS Reference link:**
https://microsoft.sharepoint.com/:w:/s/accessibility/EZBde1C58eFKkdEvHy1sfB0BbfrE-sgqsVO5g2zVY6wbDA?e=jEWXd4

“Have feedback to share on Bugs? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-vaibgu%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400980259288%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=TrcBaCyAPKg0WAQfdSZJP2i9pghMEDg59i2NeUUs5EQ%3D&reserved=0) “

### Screenshots

<img width="960" alt="MAS4 1 2 Ensures aria attribute" src="https://user-images.githubusercontent.com/104483005/224689599-9b6d1c83-5d2d-4410-b517-13c92f20072e.png">

### Card JSON

```JSON
NA
```

**Comment by vagpt** [comment]
Hi @anna-dingler,

As this issue is still repro, so could you please let us know is there any future plan to fix this issue?

**Snippet:**

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/89beb419-8462-46d5-b12e-c47b5c007d40)

**Comment by anna-dingler** [comment]
Hi @vagpt,

This issue is fixed on our internal site. I expect us to make another website release this month, so I will go ahead and mark this as completed.

Please let me know if you have any questions!
