### ISSUE TITLE
Inconsistent rendering warnings for missing error messages

### ISSUE THREAD

**Issue by anna-dingler** [microsoft/AdaptiveCards#8381]
# Platform

* JavaScript
* UWP

# Samples
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.3/Tests/MissingErrorMessages.json

# Issue

All 16 inputs in this card have a type of validation and are missing error messages. The JS renderer only displays 8 error messages, and the UWP renderer only displays 13.

**Comment by paulcam206** [comment]
The UWP renderer applies schema validation against the payload, and so can show lots of not-quite-correct warnings. The JS renderer doesn't apply the same validation...
