### ISSUE TITLE
[Ms teams] Tooltip isn't visible if select action is added to Image element

### ISSUE THREAD

**Issue by rkalvitis** [microsoft/AdaptiveCards#8428]
### Target Application

Microsoft Teams

### Application Operating System

Windows

### Schema Version

1.5

### Problem Description

if openUrl action is added to image, tooltip does not show when hovering over image

### Expected Outcome

![image](https://user-images.githubusercontent.com/129366490/228756524-cf2a1c15-03d6-4e70-bdcb-2d2560c059aa.png)

when hovering over image it should show tooltip for the url

### Actual Outcome

![image](https://user-images.githubusercontent.com/129366490/228756873-d8c07781-0434-4ef5-b9e0-371988e41ec2.png)

on teams app tooltip can not be seen

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Image",
            "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/640px-Image_created_with_a_mobile_phone.png",
            "selectAction": {
                "type": "Action.OpenUrl",
                "url": "https://www.youtube.com/",
                "tooltip": "This is link to youtube"
            }
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5"
}
```

### Repro Steps

look at provided adaptive card json and send it in Microsoft Teams (private chat).

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/8884
