### ISSUE TITLE
[Adaptive Card iOS - Notification Card.Json]: While navigating the card, voice over focus is landing on the hidden elements.

### ISSUE THREAD

**Issue by vagpt** [microsoft/AdaptiveCards#8432]
### Target Platforms

iOS

### SDK Version

1.0 (2.4.0-beta.23.1.8.1)

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
Device: iPhone 11
iOS: 16.3.1
Application: Adaptive Cards
App Version: 1.0 (2.4.0-beta.23.1.8.1)
Screen Reader: Voice Over

**Repro Steps:**
1. Launch Adaptive Cards iOS application.
2. Home screen will appear.
3. Activate Voice over
4. Navigate to "V1.0" control and select it.
5. Navigate to 'Test' control and activate it.
6. Navigate to 'Notification Card.Jsons' and activate it.
7. Perform the right swipe and observe the issue.

**Actual Result:**
While navigating to the notification card screen, voice over focus is going on the hidden elements and announcing as 'Calendar Image'.

**Expected Result:**
Voice over focus should not land on the hidden element while navigating using the swipe gesture.

**Note:**
Same issue is repro under 'NumberedListTest.Json' screen.
Same issue is repro under 'Bleed.Comprehensive' screen.
Same issue is repro under 'LongFactSet' screen.
Same issue is repro under 'FlightItinerary_en' screen.
Same issue is repro under 'IconsInSomeAction' screen.
Same issue is repro under 'ToggleVisibility.AllElements' screen.
Same issue is repro under 'Choice_default_value' screen.
Same issue is repro under 'InputValidationTestCard' screen.
Same issue is repro under 'Activity Update' screen.

**User Impact:**
It will impact the screen reader user if the focus lands on the hidden elements as it will create confusion for the screen reader user.

**WCAG Reference:**
https://www.w3.org/WAI/WCAG21/Understanding/meaningful-sequence.html

"Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “

### Screenshots

https://user-images.githubusercontent.com/95913748/228826926-94437a3d-c467-4fe8-bb35-1237d8e82713.MP4

https://user-images.githubusercontent.com/95913748/228831704-bf139f53-82aa-4e8a-bb5a-8e575780ce9c.MP4

https://user-images.githubusercontent.com/95913748/229031885-807b7c50-1d70-49d8-9cbe-3bb2be8061b5.mov

### Card JSON

```JSON
NA
```

**Comment by jwoo-msft** [comment]
@vagpt 
Please note that any cards under the 'Test & Elements' section are intended solely for internal feature development. Once features have been verified, new cards are created and placed in the 'Scenario' section. It's important to focus testing efforts only on cards within the 'Scenario' section.

To address this, I'm currently working on fixing the issue so that cards from other folders will not appear in the sample app. Thank you for your understanding.

**Comment by vagpt** [comment]
Adding A11yTTValidated tag as per the above comment.
