### ISSUE TITLE
{Linked:Bug9781456} [Adaptive Cards> Designer]: Screen reader is not announcing any information after expanding or collapsing the 'Oct 22' buttons. 

### ISSUE THREAD

**Issue by vagpt** [microsoft/AdaptiveCards#8448]
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
OS Version: 22H2 (Build 25324.1011)
Browser: Edge Dev (113.0.1774.3)
Screen Reader: NVDA

**Repro Steps:**
1. Open the above URL in edge dev browser.
2. Navigate to the 'Designer' tab through tab key and activate it.
3. Navigate to the 'Sample data Editor' and ' Card payload editor' and attach the provided JSON file.
4. Navigate to 'Preview mode' and activate it.
5. Navigate to the 'Oct 22' button and press enter key and observe the issue.

**Actual Result:**
While navigating to the 'Oct 22' button, screen reader is not conveying the state as 'Collapsed or expanded'. Also, after activating it on renavigating on the same control screen reader is not conveying the state.

**Expected Result:**
Screen Reader should convey the state as 'Collapsed or Expanded' for 'Oct 22' button.

**User Impact:**
Screen reader users may affect if it does not give accurate announcement to the action on the screen.

**WCAG Reference:**
https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html

"Have feedback to share on Bugs? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “.

### Screenshots

https://user-images.githubusercontent.com/95913748/230363346-05cb11c1-3e6e-49d1-a031-da32dc56548d.mp4
[stock-awards-vesting-screen json.zip](https://github.com/microsoft/AdaptiveCards/files/11170136/stock-awards-vesting-screen.json.zip)

**Comment by anna-dingler** [comment]
Hi @vagpt,

This issue can be resolved by switching from `ToggleVisibility` to `ShowCard`. The `ShowCard` action has the accessibility behavior you are looking for and seems to be good for this use case.

Here is a link to the documentation: https://adaptivecards.io/explorer/Action.ShowCard.html

Also in the future, `ToggleVisibility` is a deprecated feature, and we no longer support it.

Let me know if you have any questions or would like an updated payload. Thanks!
