### ISSUE TITLE
[Rendering] iOS App crashing when rendering Adaptive Card with "lang" : "en" field

### ISSUE THREAD

**Issue by GabrielMedAlv** [microsoft/AdaptiveCards#8455]
### Target Platforms

iOS

### SDK Version

2.8.10

### Application Name

Microsoft Teams

### Problem Description

The app is crashing due a parsing issue for "lang" field value "en". It appears at the moment of initialize an app from a JSON string (see sample code). Looks like the class causing the issue is **ACOAdaptiveCard**, on the method _fromJson_. Last log on console is: 

_libc++abi: terminating with uncaught exception of type std::runtime_error: collate_byname<char>::collate_byname failed to construct for en
terminating with uncaught exception of type std::runtime_error: collate_byname<char>::collate_byname failed to construct for en_

Sending the card on desktop from developer portal is noticed that the "lang" field issue is marked (check image) but is only crashing on iOS, other platforms like Android and desktop show the card without a problem.

### Screenshots

![Screenshot 2023-03-29 at 17 58 02](https://user-images.githubusercontent.com/130393016/230978914-bb3a8f64-1378-44fb-be3c-faab7304da72.png)

### Card JSON

```JSON
{"body":[{"type":"TextBlock","text":"Hello World!","wrap":true},{"height":"auto","type":"Image","url":"https:\/\/us-prod.asyncgw.teams.microsoft.com\/urlp\/v1\/url\/content?url=https%3a%2f%2fcataas.com%2fcat","spacing":"none"}],"lang":"en","type":"AdaptiveCard","version":"1.2"}
```

### Sample Code Language

Objective-C

### Sample Code

ACOAdaptiveCardParseResult *cardParseResult = [ACOAdaptiveCard fromJson:cardJsonString];

**Comment by jwoo-msft** [comment]
this is fixed.
