### ISSUE TITLE
{Freeway-Bug}[Adaptive Cards> FlightUpdate.json]: Focus order is not appearing in logical sequence on passengers and seats name.

### ISSUE THREAD

**Issue by vaishali1397** [microsoft/AdaptiveCards#8456]
### Target Platforms

Other

### SDK Version

3.2.2303.22003

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
OS version: 22H2 (Build 25324.1011)
Application: AdaptiveCardVisualizer
Application Version: 3.2.2303.22003
Screen reader: Narrator

**Repro Steps:**

1. Open the Adaptive Card Visualizer application.
2. Turn on the Narrator through Ctrl+ Windows+ Enter key and press caps lock +space bar key to turn on the scan mode.
3. Navigate to the 'FlightUpdate.json' through tab key and activate it.
4. Now, navigate to 'Passengers' name through up/down arrow key.
5. Observe the issue.

**Actual Result:**
Focus order is not appearing in logical sequence on passengers and seats name text when user navigates in the scan mode of narrator through up/down arrow key.

**Expected Result:**
Focus order is not appearing in logical sequence on passengers and seats name text when user navigates in the scan mode of narrator through up/down arrow key.

**Notes:**
In scan mode of narrator focus is landing on the hidden content after AMS text. **PFA for Reference:** Notes~ Focus is landing on the hidden content after AMS text.png

**User Impact:**
Screen reader user will get impacted as user will have difficulty in navigating or in making proper track of the content.

**Reference link:**
https://microsoft.sharepoint.com/:w:/s/accessibility/EW6zey9ci4pKoOrN3OZ10pgBc71Xwgao7lLbzb9hRIvwRw?e=CeFN10
“Have feedback to share on Bugs? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-vaibgu%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400980259288%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=TrcBaCyAPKg0WAQfdSZJP2i9pghMEDg59i2NeUUs5EQ%3D&reserved=0) “
<img width="960" alt="Code snippet~ Focus order is not in sequence" src="https://user-images.githubusercontent.com/104483005/231066784-5847a6a3-0519-4221-ba9f-56db5a3b3499.png">

### Screenshots

https://user-images.githubusercontent.com/104483005/231066084-6f497987-a33e-4da1-919c-d8355023e7e2.mp4

<img width="960" alt="Notes~ Focus is landing on the hidden content after AMS text" src="https://user-images.githubusercontent.com/104483005/231066774-4a0593f2-3a9a-466d-b343-4baa974039cc.png">

### Card JSON

```JSON
NA
```

**Comment by vaishali1397** [comment]
Issue is repro'ing in the latest test environment will reactivate on 1 sep.
**Test environment:**
OS version: 23H2 (Build 25931.1000)
Application: AdaptiveCard Visualizer
Application Version: 1.2.2306.30005


![image](https://github.com/microsoft/AdaptiveCards/assets/104483005/b63ec63d-7204-4c20-af40-346fb21b664f)

**Comment by vagpt** [comment]
Adding A11yTTVAlidated tag as of now this issue is tracking with below URL.

[Adaptive Cards> FlightUpdate.json]: Focus order is not appearing in logical sequence on passengers and seats name. #8978
