### ISSUE TITLE
[Designer] after upgrading the designer version, TypeError: this.hostContainer.getCurrentStyleSheet is not a function

### ISSUE THREAD

**Issue by Neeraj-swarnkar** [microsoft/AdaptiveCards#8467]
### Problem Description
Urgent Issue - 
[Designer] I have upgraded the designer version and it's dependencies, screenshot added below for package.json changes.
node version - v17.1.0
npm version - 8.4.1

Following this doc -> https://www.npmjs.com/package/adaptivecards-designer
Earlier my project was working fine, but after upgrade it's giving below-mentioned error.

`npm install adaptivecards-designer adaptivecards adaptive-expressions adaptivecards-templating monaco-editor`

`npm install copy-webpack-plugin monaco-editor-webpack-plugin css-loader style-loader`

```
TypeError: this.hostContainer.getCurrentStyleSheet is not a function

    at CardDesigner.recreateDesignerSurface (card-designer.js:271:1)

    at CardDesigner.attachTo (card-designer.js:1280:1)

    at AdaptiveCardsDesigner.loadEditor (VM59339 AdaptiveCardsDesigner.js:233:16)

    at AdaptiveCardsDesigner.loadEditor (react-hot-loader.development.js:717:1)

    at eval (VM59339 AdaptiveCardsDesigner.js:168:15)

```
 
Added breakpoints in the code to see the object. Inside file node_modules/adaptivecards-designer/src/card-designer.ts

`if (Utils.isAbsoluteUrl(this.hostContainer.getCurrentStyleSheet()))`

Any help or pointers. Thanks.

### Card JSON

```JSON
nope
```

**Comment by anna-dingler** [comment]
Hi @Neeraj-swarnkar,

Which version are you upgrading to?

Also, did you trace which line is throwing the error?

My initial thought is that you should uncomment this line:
`// ACDesigner.GlobalSettings.supportedTargetVersions = [Adaptive.Versions.v1_0, Adaptive.Versions.v1_1, Adaptive.Versions.v1_2];`

**Comment by Neeraj-swarnkar** [comment]
> Hi @Neeraj-swarnkar,
> 
> Which version are you upgrading to?
> 
> Also, did you trace which line is throwing the error?
> 
> My initial thought is that you should uncomment this line: `// ACDesigner.GlobalSettings.supportedTargetVersions = [Adaptive.Versions.v1_0, Adaptive.Versions.v1_1, Adaptive.Versions.v1_2];`

Thanks for the response @anna-dingler,
I tried to update all the version and it's dependencies,
I am seeing different error - 

```

TypeError: this.hostContainer.getCurrentStyleSheet is not a function

    at CardDesigner.recreateDesignerSurface (card-designer.js:271:1)

    at CardDesigner.attachTo (card-designer.js:1280:1)

    at AdaptiveCardsDesigner.loadEditor (VM59339 AdaptiveCardsDesigner.js:233:16)

    at AdaptiveCardsDesigner.loadEditor (react-hot-loader.development.js:717:1)

    at eval (VM59339 AdaptiveCardsDesigner.js:168:15)

 
```

Added breakpoints in the code to see the object. Inside file node_modules/adaptivecards-designer/src/card-designer.ts

`if (Utils.isAbsoluteUrl(this.hostContainer.getCurrentStyleSheet()))`

It looks like the this.hostContainer object in our portal doesn't have the (getCurrentStyleSheet()) _stylesheet property set.

 
Css is not getting loaded or styles can be the issue, or some issue while using the style or css during webpack common code.

Can you help me now. I have updated description and added my package which is being updated for reference.

**Comment by anna-dingler** [comment]
Thanks for the additional information @Neeraj-swarnkar!

In 2.4.2, we introduced theming for our host containers. `getCurrentStyleSheet()` is a new abstract method on the `HostContainer` class.

You should update `WebexTeamsContainer` to either implement this method, or you can extend the new class `SingleThemeHostContainer` (https://github.com/microsoft/AdaptiveCards/blob/main/source/nodejs/adaptivecards-designer/src/containers/single-theme-host-container.ts).

Here is an example of one of our containers: https://github.com/microsoft/AdaptiveCards/blob/main/source/nodejs/adaptivecards-designer/src/containers/bf-image/bf-image-container.ts

**Comment by Neeraj-swarnkar** [comment]
> Thanks for the additional information @Neeraj-swarnkar!
> 
> In 2.4.2, we introduced theming for our host containers. `getCurrentStyleSheet()` is a new abstract method on the `HostContainer` class.
> 
> You should update `WebexTeamsContainer` to either implement this method, or you can extend the new class `SingleThemeHostContainer` (https://github.com/microsoft/AdaptiveCards/blob/main/source/nodejs/adaptivecards-designer/src/containers/single-theme-host-container.ts).
> 
> Here is an example of one of our containers: https://github.com/microsoft/AdaptiveCards/blob/main/source/nodejs/adaptivecards-designer/src/containers/bf-image/bf-image-container.ts

Hi @anna-dingler, thanks for the help, We are able to resolve the above-mentioned error.
Unfortunately we are seeing new error which is 

`Error: Super expression must either be null or a function`

We are debugging the same, let me know if this is know to you. Thanks.
