### ISSUE TITLE
{Freeway-Bug}[Inputs.json]: Keyboard focus moves to non interactive element in DatePicker under Due Date.

### ISSUE THREAD

**Issue by Bhaskar301101** [microsoft/AdaptiveCards#8468]
### Target Platforms

Android

### SDK Version

2023.03.31.1

### Application Name

Adaptive Card

### Problem Description

Test Environment
Device: S21+ 5G
Screen Reader: Talkback
AdaptiveCard Android App version: 2023.03.31.1
Tool: Logitech Bluetooth Keyboard

Repro Steps:

1. Open Adaptive Cards Visualizer Application.
2. Navigate to sample cards using tab key and activate it using Enter key.
3. A dropdown would appear. Activate it using Enter key.
4. Navigate to Inputs using tab key and activate it using Enter key.
5. Navigate to the Visual tab item present at the top. A sample card would appear.
6. Navigate to the Due Date edit box inside the sample card using tab key and activate it using Enter key.
7. Navigate through the date picker using Tab keys.
8. Observe the issue.

Actual Result:
Keyboard focus moves to non interactive element in DatePicker under Due Date. It goes to the current date which is a non interactive element.

Expected Result:
Keyboard focus shoyuld not move to non interactive element in DatePicker under Due Date. 

User Experience:
Keyboard users would get affected if Keyboard focus moves to non interactive element in DatePicker under Due Date.

WCAG Reference:
(https://www.w3.org/WAI/WCAG21/Understanding/focus-order)

"Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “,

### Screenshots

https://user-images.githubusercontent.com/89897257/232709237-27d9667f-f21a-4ac4-ac3d-c9838bf27e7c.mp4

### Card JSON

```JSON
NA
```

**Comment by jwoo-msft** [comment]
this is Android native ui picker issue. there is nothing we can do about it.
