### ISSUE TITLE
[Designer] Microsoft teams selects v1.4 of Adaptive Cards instead of v1.5

### ISSUE THREAD

**Issue by Roganik** [microsoft/AdaptiveCards#8487]
#### Current behavior 

When selecting Microsoft Teams in the [designer dropdown](https://adaptivecards.io/designer/) it automatically selects v1.4 of Adaptive Cards.

Microsoft Teams supports Adaptive Cards v1.5 per https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#support-for-adaptive-cards

#### Expected behavior 

Update designer to automatically select Adaptive Cards v1.5 for Microsoft Teams

---

Related: https://github.com/MicrosoftDocs/AdaptiveCards/pull/505

### Card JSON

N/A

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/8619

**Comment by jwoo-msft** [comment]
re-opened it since the bug is filed on the designer.
