### ISSUE TITLE
[Adaptive Cards - Card Structure]: Ensures ARIA attributes are allowed for an element's role for the 'Please choose' edit fields under 'Malt and Vine Order Form'.

### ISSUE THREAD

**Issue by vagpt** [microsoft/AdaptiveCards#8539]
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
OS: Version 23H2 (OS Build 25381.1)
URL: https://adaptivecards.io/designer/
Browser: Edge Dev Version 115.0.1880.3 (Official build) dev (64-bit)
Tools: Accessibility Insight For Web

**Repro Steps:**
1. Open the above URL in the edge dev browser.
2. Navigate to 'Designer' tab item and press enter key to activate it.
3. Navigate to 'New Card' button and press enter key to activate it.
4. Run accessibility insight for web tool and observe the issue.

**Actual Result:**
 ARIA attributes are not allowed for an element's role as for the 'Please Choose' edit field. Also, combo box is automatic getting expanded when focus comes on it,

**Expected Result:**
Ensures ARIA attributes should allowed for an element's role i.e. for 'Please Choose' edit field and combo box should not be expanded automatically when focus comes on it.

**Element path:** 
#__ac-14a10d9e-6f66-472b-9bc4-c8987d22e18c

**How to fix:** 
Fix any of the following:
  ARIA attribute is not allowed: aria-required="False"

**User Impact:**
It will impact the screen reader if the aria attributes are allowed for the element as it will not convey the required information to the user.

**WCAG Reference:**
https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html

“Have feedback to share on Bugs? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-vaibgu%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400980259288%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=TrcBaCyAPKg0WAQfdSZJP2i9pghMEDg59i2NeUUs5EQ%3D&reserved=0) “

### Screenshots

![WCAG4 1 2-Ensures ARIA attributes are allowed for an element's role for the 'Please choose' edit fields under 'Malt and Vine Order Form'](https://github.com/microsoft/AdaptiveCards/assets/95913748/560fb447-4cee-4a6e-b862-1b38544513b3)

![WCAG4 1 2-Ensures ARIA attributes are allowed for an element's role](https://github.com/microsoft/AdaptiveCards/assets/95913748/913e1d15-9e0a-4e2d-87de-13e12bc50653)

### Card JSON

```JSON
NA
```

**Comment by vagpt** [comment]
Hi @anna-dingler,

As this issue is still repro, so could you please let us know is there any future plan to fix this issue?


Snippet:

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/cfbb484a-c7c0-4752-9d4a-cce41d4d6f49)

**Comment by anna-dingler** [comment]
Hi @vagpt,

This issue is fixed on our internal site. I expect us to make another website release this month, so I will go ahead and mark this as completed.

Please let me know if you have any questions!

**Comment by vagpt** [comment]
Hi @anna-dingler,

Thanks for the update.

It would be great if you please create a new label as 'NotReadyToTest' for this type of condition.

**Comment by anna-dingler** [comment]
Hi @vagpt, 

Apologies for the late response. I just released a new version of the website so this fix can be seen in production.

I created a **NotReadyToTest** label that I will use in the future.

Thanks!

**Comment by vagpt** [comment]
Thanks @anna-dingler 

Adding A11yTTValidated tag as issue is not repro on latest version.

![image](https://github.com/microsoft/AdaptiveCards/assets/95913748/ae873360-91a5-4330-bf07-fec1241cadc2)
