### ISSUE TITLE
Using two actions in Single container

### ISSUE THREAD

**Issue by YogeshNat** [microsoft/AdaptiveCards#8567]
### Target Application

Bot Framework SDK

### Application Operating System

Windows

### Schema Version

1.3

### Problem Description

Hello,

I would like to use two actions, Action.Submit and Action.OpenUrl in a same container.

Scenario:
When user clicks a button, It should open a new webpage and also it should trigger a flow.

Thanks
Yogesh

### Expected Outcome

When user clicks a button, It should open a new webpage and also it should trigger a flow.

### Actual Outcome

 I used Select state. Only Action.OpenURl is working.

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "ActionSet",
                    "actions": [
                        {
                            "type": "Action.OpenUrl",
                            "title": "Action.OpenUrl",
                            "url": "https://adaptivecards.io/designer/"
                        }
                    ]
                }
            ]
        }
    ],
    "selectAction": {
        "type": "Action.Submit"
    }
}
```

**Comment by paulcam206** [comment]
This is not a supported scenario for Adaptive Cards. Please consider having a separate action for a user to open a URI.
