### ISSUE TITLE
Android package/namespace should be io.adaptivecards

### ISSUE THREAD

**Issue by matthidinger** [Microsoft/AdaptiveCards#857]
Not com.microsoft.

Let's fully discuss this one before implementing 

Also is it common to have such granular imports in Java? 

using Com.Microsoft.Adaptivecards.Objectmodel;
using Com.Microsoft.Adaptivecards.Renderer.Actionhandler;
using Com.Microsoft.Adaptivecards.Renderer;
using Com.Microsoft.Adaptivecards.Renderer.Readonly;
using Com.Microsoft.Adaptivecards.Renderer.Input;

**Comment by eschavez** [comment]
The rename is in v1.0
