### ISSUE TITLE
[AdaptiveCards] [Speak attribute details are not clear in documentation]

### ISSUE THREAD

**Issue by SubbaReddi** [microsoft/AdaptiveCards#8582]
We see following note in documentation for speak attribute: https://adaptivecards.io/explorer/
_Specifies what should be spoken for this entire card. This is simple text or SSML fragment_.

If we utilize the same feature in MS Teams bots, it proves beneficial for the immersive reader to read the Speak property value. However, its usefulness remains limited to this specific context and may require explicit mention in the documentation.
---
* URL: https://adaptivecards.io/explorer/

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/8957
