### ISSUE TITLE
[Rendering] FactSet now renders as a table with visible borders in Teams Desktop

### ISSUE THREAD

**Issue by SergeyGrayman** [microsoft/AdaptiveCards#8587]
### Target Platforms

WPF

### SDK Version

1.4

### Application Name

Microsoft Teams

### Problem Description

FactSet now renders as a table with visible borders and white background in Teams Desktop.
Mobile is ok.

### Screenshots

<img width="543" alt="Screenshot 2023-06-28 at 18 21 55" src="https://github.com/microsoft/AdaptiveCards/assets/9824156/52102be7-74c7-46d4-b38d-a65b9e36e52a">

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.4",
    "body": [
        {
            "type": "FactSet",
            "facts": [
                {
                    "title": "Fact 1",
                    "value": "Value 1"
                },
                {
                    "title": "Fact 2",
                    "value": "Value 2"
                },
                {
                    "title": "Fact 1",
                    "value": "Value 1"
                },
                {
                    "title": "Fact 1",
                    "value": "Value 1"
                },
                {
                    "title": "Fact 1",
                    "value": "Value 1"
                }
            ]
        }
    ],
    "backgroundImage": {
        "url": "https://htmlcolorcodes.com/assets/images/html-color-codes-color-tutorials-hero.jpg"
    }
}
```

**Comment by audioe** [comment]
Same here:

![image](https://github.com/microsoft/AdaptiveCards/assets/32540020/278f4108-a5cd-4647-b66d-8122aabeb02b)

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/8955
