### ISSUE TITLE
[Templating] AdaptiveCards.Templating does not work with Applications using Bot Framework DotNet SDK 4.20.0

### ISSUE THREAD

**Issue by justin-mellor** [microsoft/AdaptiveCards#8590]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET

# Author or host

Host running on ASP.NET Core 6.0 running Bot Framework

# Version of SDK

AdaptiveCards.Templating 1.4.0

# Issue

The June 2023 version of the Bot Framework (https://github.com/microsoft/botbuilder-dotnet/releases/tag/4.20.0) has changed to use ANTLR 4.11.1
See https://github.com/microsoft/botbuilder-dotnet/issues/6558 and https://github.com/microsoft/botbuilder-dotnet/pull/6586

AdaptiveCards.Templating is using ANTLR 4.8

Unfortunately ANTLR 4.10 (https://github.com/antlr/antlr4/releases/tag/4.10) seems to have broken the generated parsers and lexers in AdaptiveCards.Templating.

When creating a new AdaptiveCardTemplate class
new AdaptiveCardTemplate(templateJson).Expand(rootData)

we get a Type Initialization error
Method not found: 'Antlr4.Runtime.Atn.ATN Antlr4.Runtime.Atn.ATNDeserializer.Deserialize(Char[])'.

**Comment by jwoo-msft** [comment]
Thanks for reporting this issue. We will look into this issue.

**Comment by MattJam87** [comment]
+1 here

This incompatibility is very annoying! Is there any ETA on this?

Matt

**Comment by justin-mellor** [comment]
This issue has been raised by somebody else as https://github.com/microsoft/AdaptiveCards/issues/8615
The other issue seems to be getting a bit more commenting on.

**Comment by jwoo-msft** [comment]
Please follow issue #8614 for further updates, including the ETA
