### ISSUE TITLE
"Primary" and destructive action buttons

### ISSUE THREAD

**Issue by dclaux** [Microsoft/AdaptiveCards#861]
<table>
<tr>
<th>Release</th>
<th>Renderer status</th>
<th>Tasks status</th>
</tr>
<tr>
<td>1.2
<td>✔️ .NET (#1972)<br/>✔️ Android (#1970)<br/>✔️ iOS (#1971)<br/>🔄 TS (#2435)<br/>✔️ UWP (#2227)</td>
<td>✔️ Shared (#1968)</td>
</tr>
</table>

# Solves requests

* "Primary" and destructive action buttons (#2025)

# Solution
Add a style property of type Sentiment to all actions. The Sentiment enumeration will initially support only three values, but we could add more styles in the future.

## Schema

**New** property on `Action` 

Property|Type|Required|Description
---|---|---|---
sentiment | Sentiment | false | Controls the sentiment of an Action, which influences how the action is displayed, spoken, etc

Other property name ideas...

* category
* appearance - No, because this could have non-appearance related behaviors. Like when spoken, destructive could use a different tone.
* significance
* emotion
* sentiment

Why not `style`?

* We might want to use style for something else, like a "raised" button vs a "flat" button

![image](https://user-images.githubusercontent.com/13246069/45471455-fa6ccb00-b6e5-11e8-9b68-fce908419179.png)

**Sentiment** enum

Value | Description
--- | ---
default | Action is displayed as normal
positive | Action is displayed with a positive sentiment (typically the button becomes accent color)
destructive | Action is displayed with a destructive sentiment (typically the button becomes red)

Research on enum value names...

* Android does "positive" and "negative" on their dialogs, and "neutral" for normal
  * Why not "negative"?
    * Because sometimes authors want to display a "delete" button, which isn't exactly negative... it's destructive
* UWP docs mention "destructive", but they don't have anything baked into the API
* Bootstrap has "default", "primary", and "danger"
  * Why not "primary"?
    * Because primary implies that it also gains focus. Sometimes authors might want to have the cancel button as the primary focused button, but the Overwrite button should get the preferred visual treatment
* iOS uses "destructive" on their ActionSheet API
* No one seems to use "emphasized"

This is **different** from choosing the default action, since sometimes you want the destructive action (like deleting) to be the default action.

## Host Config
None. There's already no host config for specifying background colors of actions today. This should all be done using native styling.

## Down-level impact
**For authors**: Low. Actions will still appear, just not with the sentiment behavior.

**For hosts**: Breaking change. If host is currently natively styling buttons, and now a new primary button comes in, the new button has a new styling name key. Therefore, the host's current styling won't be applied. Hosts need to update their native styling so that when they receive a sentiment, the button at least looks like a default button.

## Renderer Requirements

1. A renderer **should** have a default appropriate rendering for these styles. For example, using accent color for emphasized, and red for destructive.
1. A renderer **must** output the appropriate styling name on the action, so that hosts can natively style the buttons. For example, a default button might get a style name of `Action`, but an emphasized button might get a style name of `Action.Positive` (or however the native platform styling naming convention works)

# Auto-generated task status

- [x] Shared
- [x] .NET
- [x] Android
- [x] iOS
- [ ] TS
- [x] UWP

**Comment by matthidinger** [comment]
We should also consider keyboarding experience as well. a Primary action could be wired up to Enter, and desstructive could be Esc

**Comment by dclaux** [comment]
Here is another suggestion for naming the property:
"emphasis": "none" | "positive" | "destructive" with "none" being the default.

Other than that spec looks fine. One thing that isn't mentioned is whether several actions can have a "positive" or "destructive" emphasis. My opinion is we should simply allow it.

**Comment by almedina-ms** [comment]
where should the accent color and the destructive button color be taken from? I've seen color configurations for containers but there's no default color configurations for a general case

**Comment by khouzam** [comment]
After some discussion, I think that the default behaviors should be:
1. Positive action changes the *background* to the `Accent` color
2. Destructive action changes the *foreground* to the `Attention` color from the host config.

Changing the background on both could lead to both types of actions having the same or similar background color and causing confusion. I'm using Red as my accent color on Windows.

**Comment by khouzam** [comment]
We've been discussing this feature and I wanted to propose an extensibility point that hosts could support. If the card author specifies another sentiment value than the ones specified here, the renderers would still try to apply the sentiment as a style to the action. This would allow for a host to easily support more sentiments through an efficient extensibility model.

For example, in the UWP renderer, the host can pass a resource dictionary with styles. Having `Adaptive.Action.Positive` override the default style for positive actions. If the host passes other such styles to the renderer, these styles could be applied for *sentiments*. This gives the host the option of supporting more sentiments that the card author can leverage if it knows about them.

The same thing can be applied to the JavaScript renderer with CSS classes.

Thoughts?

**Comment by andrewleader** [comment]
**DECISION**: For the action “sentiment” property, consensus was we should rename the property to “style”. Enum values remain the same (but the enum itself should be renamed to ActionStyle), and the values in it are different from ContainerStyle

```json
{
  “type”: “Action.Submit”,
  “style”: “default” | “positive” | “destructive”
```
