### ISSUE TITLE
Incompatibility with bot framework 4.2.0+

### ISSUE THREAD

**Issue by jamesemann** [microsoft/AdaptiveCards#8615]
### Target Platforms

Other

### SDK Version

1.4.0

### Application Name

all

### Problem Description

Since BF was updated to use ANTLR 4.11.1 (in 4.2.0) it is no longer possible to use `new AdaptiveCardTemplate(json)` in the same project

It fails with this error:

```
      System.TypeInitializationException: The type initializer for 'AdaptiveCardsTemplateLexer' threw an exception.
       ---> System.MissingMethodException: Method not found: 'Antlr4.Runtime.Atn.ATN Antlr4.Runtime.Atn.ATNDeserializer.Deserialize(Char[])'.
         at AdaptiveCardsTemplateLexer..cctor()
         --- End of inner exception stack trace ---
         at AdaptiveCardsTemplateLexer..ctor(ICharStream input)
         at AdaptiveCards.Templating.AdaptiveCardTemplate..ctor(Object jsonTemplate)
```

### Card JSON

Example, but all fail:

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5",
    "body": [
        {
            "type": "TextBlock",
            "text": "this doesnt work",
            "wrap": true
        }
    ]
}
```

### Sample Code Language

C# (dotnet core)

### Sample Code

I have created a repro below:

https://github.com/jamesemann/adaptive-cards-incompatibility

If you dotnet run, you will see:

```
❯ dotnet run
Unhandled exception. System.TypeInitializationException: The type initializer for 'AdaptiveCardsTemplateLexer' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Antlr4.Runtime.Atn.ATN Antlr4.Runtime.Atn.ATNDeserializer.Deserialize(Char[])'.
   at AdaptiveCardsTemplateLexer..cctor()
   --- End of inner exception stack trace ---
   at AdaptiveCardsTemplateLexer..ctor(ICharStream input)
   at AdaptiveCards.Templating.AdaptiveCardTemplate..ctor(Object jsonTemplate)
   at Repro.DoesItWork.Main() in C:\repos\templatingrepro\Repro\Repro\Program.cs:line 9
   at Repro.DoesItWork.<Main>()
```

**Comment by jamesemann** [comment]
Hello team, any update on this?

**Comment by jamesemann** [comment]
@vagpt would it be possible to get someone in the team to take a look at this? thank you!

**Comment by namanimsft** [comment]
Any update on this bug please? we are running into the same issue

**Comment by jamesemann** [comment]
Hi team, I have taken the time to build a repro for you and it has been one month now. Would you be able to take a look at this?

**Comment by jamesemann** [comment]
any update team?

**Comment by jamesemann** [comment]
@anna-dingler would it be possible to triage this issue please?

**Comment by jwoo-msft** [comment]
@jamesemann,

I will update SDK to use ANTLR 4.11.1

**Comment by jwoo-msft** [comment]
@jamesemann,

Unfortunately, ANTLR cannot be updated to version 4.11.1. The reason is that the template library depends on the AdaptiveExpression library, which in turn relies on ANTLR runtime 4.8.0.

Simply updating ANTLR in the template library alone won't make it compatible with version 4.11.1, as the AdaptiveExpression library will face the same issue you are currently encountering.

I recommend reaching out to the AdaptiveExpression team to inquire about updating their library to the version you desire. Once the AdaptiveExpression library is updated, we can proceed with updating the template library.

[AdaptiveExpressions 4.11.3 on NuGet](https://www.nuget.org/packages/AdaptiveExpressions/4.11.3?_src=template)

Thanks,

**Comment by jamesemann** [comment]
Thank you @justin-mellor. @jwoo-msft could you take another look please? as advised AdaptiveExpressions has already been updated to 4.11.1

![image](https://github.com/microsoft/AdaptiveCards/assets/6830648/d30e8125-4a66-44c3-942e-8f4a9cccd72b)

**Comment by jwoo-msft** [comment]
@Justin-Mellor & @JamesEmann

Thanks for the update. That's strange; for some reason, I didn't see the latest version.

I will check on thatl

**Comment by jwoo-msft** [comment]
@justin-mellor & @jamesemann 

issue has been fixed.

**Comment by justin-mellor** [comment]
@jwoo-msft Great news. Thanks. Obviously you know what the next question is always going to be. What is the timeline for a release with this in!

**Comment by jwoo-msft** [comment]
@justin-mellor 
9/15

**Comment by jwoo-msft** [comment]
it's released.

**Comment by namanimsft** [comment]
Thanks a lot @jwoo-msft (y)
