### ISSUE TITLE
Action.InvokeAddInCommand does not open add-ins from browsers

### ISSUE THREAD

**Issue by edwardKatsCourse** [microsoft/AdaptiveCards#8620]
### Target Application

Edge, Chrome

### Application Operating System

Windows

### Schema Version

1.4

### Problem Description

This is a code part, which should open the add-in by its ID.

                {
                  "type": "Action.InvokeAddInCommand",
                  "title": "${replyWithOutlookAddInButton.label}",
                  "addInId": "${replyWithOutlookAddInButton.addInId}",
                  "desktopCommandId": "msgReadOpenPaneButton",
                  "isEnabled": true,
                  "isPrimary": false,
                  "tooltip": "${replyWithOutlookAddInButton.tooltip}"
                }
Add-In gets opened via Outlook Desktop only, but nothing happens on button click via Outlook Web (tested in Chrome and Edge).

The example is made by this article.
https://learn.microsoft.com/en-us/outlook/actionable-messages/invoke-add-in

### Expected Outcome

Expectation: should open the relevant Add-In from browsers and Outlook Desktop.

### Actual Outcome

On button click in browser - nothing happens

### Card JSON

```JSON
{
  "$schema": "https://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "ColumnSet",
      "columns": [
        {
          "width": "stretch",
          "items": [
            {
              "type": "ActionSet",
              "isVisible": "${replyWithOutlookAddInButton.addInVisible}",
              "actions": [
                {
                  "type": "Action.OpenUrl",
                  "title": "${openButton.label}",
                  "url": "${openButton.url}"
                },
                {
                  "type": "Action.InvokeAddInCommand",
                  "title": "${replyWithOutlookAddInButton.label}",
                  "addInId": "${replyWithOutlookAddInButton.addInId}",
                  "desktopCommandId": "msgReadOpenPaneButton",
                  "isPrimary": false
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

### Repro Steps

1. Create an Adaptive Card button, using Action.InvokeAddInCommand or using the script below
                {
                  "type": "Action.InvokeAddInCommand",
                  "title": "${replyWithOutlookAddInButton.label}",
                  "addInId": "${replyWithOutlookAddInButton.addInId}",
                  "desktopCommandId": "msgReadOpenPaneButton",
                  "isEnabled": true,
                  "isPrimary": false,
                  "tooltip": "${replyWithOutlookAddInButton.tooltip}"
                }
2. The button should open Add-In

Works as expected in Outlook Desktop (old and new)
Nothing happens in Chrome and Edge browsers

**Comment by jwoo-msft** [comment]
this looks like Outlook issue; have you followed up with Outlook?
