### ISSUE TITLE
Why we have so many version of AdaptiveCards

### ISSUE THREAD

**Issue by nnahmed** [Microsoft/AdaptiveCards#864]
Hi 

If you search AdaptiveCards on NuGet you find bulk of libraries, why we have more then one version of libraries?
https://www.nuget.org/packages?q=AdaptiveCards+

What is difference between 
Install-Package AdaptiveCards -Version 1.0.0-beta01 VS  Install-Package Microsoft.AdaptiveCards -Version 0.5.1 VS Install-Package Microsoft.AdaptiveCards.Html -Version 0.5.3

Regards

**Comment by matthidinger** [comment]
It's definitely an unfortunately situation that we're hoping to resolve within a week or so. You should use the **AdaptiveCards.*** packages for now. 

There are some breaking changes between the older packages, see here:
https://docs.microsoft.com/en-us/adaptive-cards/create/libraries/net

**Comment by nnahmed** [comment]
Thank you @matthidinger 

Surely wait for the next update.

**Comment by matthidinger** [comment]
Sounds good, let us know if you run into any issues!
