### ISSUE TITLE
[Authoring] We cannot add any style to a button and the align-center property doesn't work

### ISSUE THREAD

**Issue by qjkobe** [microsoft/AdaptiveCards#8645]
### Target Application

Microsoft Teams

### Application Operating System

iOS

### Schema Version

1.5

### Problem Description

1. We cannot add any style to adaptive card. The adaptive card has a property called style. It has 2 optional values. One is positive, the other is destructive. If I change the style and render it by Bot Framework Web Chat, it will be like:
![image](https://github.com/microsoft/AdaptiveCards/assets/16449598/98048767-683c-421a-807a-7e2c3d04a52e)
But if I change the render engine to Teams, it will be like: 
![image](https://github.com/microsoft/AdaptiveCards/assets/16449598/d4752522-4a4f-4b6b-b52d-eb3243cb45a8)
2. If we set horizontalAlignment of ActionSet to true, the button inside it will be like:
![image](https://github.com/microsoft/AdaptiveCards/assets/16449598/ae9b56dc-f5ec-4054-8a0b-7260b3242f49)
But it doesn't work in Teams app. The button will be align-right automatically:
![image](https://github.com/microsoft/AdaptiveCards/assets/16449598/5e19afbd-a2f9-49e6-bf01-657a522635bc)

### Expected Outcome

1. We can change style of buttons.
2. We can align buttons to left, right or center.

### Actual Outcome

1. The style of buttons don't change.
2. The button alignment cannot be controlled by us. It will be align-right automatically.

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5",
    "body": [
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.Submit",
                    "title": "positive",
                    "style": "positive"
                },
                {
                    "type": "Action.Submit",
                    "title": "destructive",
                    "style": "destructive"
                }
            ],
            "spacing": "None",
            "horizontalAlignment": "Center"
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "default"
        }
    ]
}
```

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/9299

**Comment by jwoo-msft** [comment]
Hi @qjkobe,

Could you please raise this issue directly with the Teams mobile team? The host app needs to support the style for it to function properly.
