### ISSUE TITLE
Add preview text when using 'Post card to Teams chat or Channel' in Power Automate/Logic Apps needs added.

### ISSUE THREAD

**Issue by JimmyFromIT** [microsoft/AdaptiveCards#8647]
When one uses the 'Post adaptive card to chat or channel' action in Power Automate or Logic apps the notification preview of the card just says '**Card**.'

As an example, if one sends an email to a channel, the Subject of the email is the preview text for that notification.

Having preview text is very important to my IT team so they can understand what is being posted at a glance instead of having to break their attention, click teams, click Activity feed, then view the notification that the flow posted.  < This is not an efficient/ideal break of our attention.

We should be able to define the adaptive card's "Title," "Preview Text," or "Subject" (whatever you want to call it) as part of the AdaptiveCard schema.

---
* URL: https://adaptivecards.io/explorer/
![Screenshot 2023-08-07 104830](https://github.com/microsoft/AdaptiveCards/assets/141657665/abea1ad1-0085-4ce3-9cdb-141fcd8cec76)

**Comment by z3019494** [comment]
Agreed. At the moment it's totally non-descriptive.

**Comment by jwoo-msft** [comment]
@JimmyFromIT,
This question should be directed to Power Automate and Logic Apps. While AdaptiveCards provides tools to construct such cards, it's Power Automate that provides the visual you're looking for.
