### ISSUE TITLE
MS Teams Adaptive Cards TextBlock does not support line breaks if using a string variable

### ISSUE THREAD

**Issue by abrbon** [microsoft/AdaptiveCards#8656]
Hi, 

I am using a variable of type string to insert some text in my adaptive card in a TextBlock to post message in MS Teams.
Problem is if i use the '\n\n' to add a linebreak in my variable it is automatically transformed to '\\\\n\\\\n' 
so the linebreaks do not work :( 

Example:
`{
                    "type": "TextBlock",
                    "text": "\n\nTEST\n\n@{join(variables('AccountNames_Array'), '\n\n')}\n\nTEST-2\n\n",
                    "wrap": true,
                    "weight": "Default"
 }`

The output looks something like this:

`{
                    "text": "\n\nTEST\n\nJohn.doe@example.com\\n\\nJohn-2.doe@example2.com\\n\\n\n\nTEST-2\n\n",
                    "type": "TextBlock",
                    "weight": "Default",
                    "wrap": true
}`

How can i fix this so it will not change the '\n' in '\\\\n' when using it in a variable?
Like the example shows, if i use the \n\n directory as text (like with the TEST and TEST-2 text) it looks fine.

I have tried to fix this for the last 1,5 hour and it is driving me crazy!

Some extra info:
I am using this in a Logic App in MS Azure.

_Originally posted by @abrbon in https://github.com/microsoft/AdaptiveCards/issues/5538#issuecomment-1684231498_

**Comment by jwoo-msft** [comment]
Hi @abrbon,

your usage seems different from AdaptiveCards.

the correct form would be:
```
{ "type": "TextBlock", "text": "\n\nTEST\n\n${join(variables['AccountNames_Array'], '\n\n')}\n\nTEST-2\n\n", "wrap": true, "weight": "Default" }
```
and with sample data:
```
{
    "variables": { "AccountNames_Array" :  ["a", "b"]}
}

**Comment by abrbon** [comment]
Hi @jwoo-msft,

Happy to report I found the issue.
I was using a ‘compose’ block in Azure Logic App to create the content for the adaptive card and uses the output in the teams component to post a message.
Somehow the compose changed the data format I guess and my ‘/n/n’ didn’t work.

By copying the whole adaptive card code directly in the teams component it works as expected.
