### ISSUE TITLE
Input.Date is not rendering the way it does in Designer

### ISSUE THREAD

**Issue by AmitBa-Kore** [microsoft/AdaptiveCards#8657]
### Problem Description

I am using Input.Date to get date range from the user in a Bot. Adaptive Card function is fine, however, the UI is not matching the one which comes in designer

### Card JSON

```JSON
{
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "type": "AdaptiveCard",
            "version": "1.5",
            "body": [
                 {   "id":"date",
                 "type": "Input.Date"
                }
            ],
            "actions": [
                {
                    "type": "Action.Submit",
                    "title": "Submit",
                    "data": {
                        "id": "updateUserInformation"
                    }
                }
            ]
        }
```

### Screenshot

![Designer_format](https://github.com/microsoft/AdaptiveCards/assets/87968298/f1392ecc-1254-43d2-a7fe-8396e351c863)
![myBot](https://github.com/microsoft/AdaptiveCards/assets/87968298/327d78ac-e7cd-47d3-b33d-5a12101eea6c)

**Comment by jwoo-msft** [comment]
Hello @AmitBa-Kore,

Could you please provide more context regarding your issue?

Thank you.

**Comment by AmitBa-Kore** [comment]
Hi Joseph,

The rendered date template looks different when I use it, however, in
Designer it looks different and correct. I have attached the screenshot. We
need those features to select the years from the dropdown.

Thanks,
Amit

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/9439

**Comment by jwoo-msft** [comment]
Looks like you're using the Teams app as your host app. In that case, I recommend reaching out to the Teams for the resolution.
