### ISSUE TITLE
[Rendering] Adaptive Cards Templating not working in Power Automate + Outlook

### ISSUE THREAD

**Issue by andremusiol** [microsoft/AdaptiveCards#8659]
### Target Platforms

Other

### SDK Version

which ever version power automate uses

### Application Name

Microsoft Outlook

### Problem Description

Dear Developers,

I like your Adaptive Cards a lot. 
I am trying to use them in Power Automate with the send email action.
Everything working fine so far, apart from the templating functionality

Im using the inline method providing the data right in the card JSON as described here:
https://learn.microsoft.com/en-us/adaptive-cards/templating/language#option-a-inline-data

But even with the code example from the docs the data values arent being injected properly.
Can you help me out? Is this a bug or am I doing sth wrong?

KR Andre

### Screenshots

Power Automate Action to send Adaptive Card works just fine
![image](https://github.com/microsoft/AdaptiveCards/assets/21216028/5ae81ad2-fbcc-49f4-9c18-a0bed8c6b597)

Card will be rendered correctly in Outlook:
![image](https://github.com/microsoft/AdaptiveCards/assets/21216028/799270cf-ddef-43dc-9d81-2d742f4bc038)

But the $data attribute and its contents will be ignored as you can see in the unresolved placeholder values in the screenshot above. Am i doing something wrong?

### Card JSON

```JSON
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.4",
    "padding": "None",
    "originator": "5b6d3bbf-f0a0-4c47-8b7b-5c0721bca994",
    "hideOriginalBody": "true",
    "$data": {
        "employee": {
            "name": "Matt",
            "manager": { "name": "Thomas" },
            "peers": [{
                "name": "Andrew" 
            }, { 
                "name": "Lei"
            }, { 
                "name": "Mary Anne"
            }, { 
                "name": "Adam"
            }]
        }
    },
    "body": [
        {
            "type": "TextBlock",
            "text": "Hi ${employee.name}! Here's a bit about your org..."
        },
        {
            "type": "TextBlock",
            "text": "Your manager is: ${employee.manager.name}"
        },
        {
            "type": "TextBlock",
            "text": "3 of your peers are: ${employee.peers[0].name}, ${employee.peers[1].name}, ${employee.peers[2].name}"
        }
    ]
}
```

### Power Automate Action

Send an Email V2

### Body
```
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <script type="application/adaptivecard+json">
@{variables('TeamsCard')}
</script>
</head>
<body>
    Fallback: Visit the <a href="https://learn.microsoft.com/outlook/actionable-messages">Outlook Dev Portal</a> to
    learn more about Actionable Messages.

    <div        style="display:none;font-size:1px;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;mso-hide:all">
        From Tax Automation with ❤️</div>

</body>
</html>
```

@{variables('TeamsCard')} refers to the Card JSON from above

**Comment by jwoo-msft** [comment]
Hi @andremusiol,

Unfortunately, there isn't much we can assist with in this context. Outlook utilizes our libraries to create their public API surface. Would it be possible for you to consult with the Outlook team to understand how to use their API correctly?

Thanks.
