### ISSUE TITLE
[Rendering] Not honoring "text" property in the Authentication object.

### ISSUE THREAD

**Issue by muthurathinam** [microsoft/AdaptiveCards#8667]
### Target Platforms

NodeJS

### SDK Version

All

### Application Name

Microsoft Outlook

### Problem Description

Specifying `text` property in the Authentication object, I expect it to appear in the MagicCode card, but I always get the default text which is **Please login in the popup. You will obtain a magic code. Paste that code below and select "Submit"**

Should this property used for this purpose or is it for something else?

### Card JSON

```JSON
Happens for any LoginRequestResponse, which flow through magic code card experience.
```

**Comment by jwoo-msft** [comment]
@muthurathinam 

please contact Microsoft Outlook team on this issue.

thank you

**Comment by muthurathinam** [comment]
@jwoo-msft I am from Outlook Actionable Messages team, My ask, is there a way to customize this card https://github.com/microsoft/AdaptiveCards/blob/62f6a132bdc4c96bab48fafd811697fc52790bfd/source/nodejs/adaptivecards/src/adaptive-applet.ts#L195C5-L241C6 for the hardcoded strings.


![image](https://github.com/microsoft/AdaptiveCards/assets/6259786/ef3da18f-3649-49fc-9eed-cf9cbbe83bb9)

**Comment by saketmodi** [comment]
@jwoo-msft - Would you provide further update on the ask? For actionable messages, we are in need of having the user sign in with credentials different from the one that he would have signed into outlook with. We want to be able to guide them appropriately about what credentials they should use.

**Comment by paulcam206** [comment]
@saketmodi - you can customize this card/behavior by registering a handler for `onShowAuthCodeInputDialog`:

https://github.com/microsoft/AdaptiveCards/blob/62f6a132bdc4c96bab48fafd811697fc52790bfd/source/nodejs/adaptivecards/src/adaptive-applet.ts#L486-L492

**Comment by saketmodi** [comment]
@muthurathinam - Is @paulcam206 suggestion to be looked into by your team?
