### ISSUE TITLE
[Rendering] dependencies issue of "adaptivecards-templating" package

### ISSUE THREAD

**Issue by yukun-dong** [microsoft/AdaptiveCards#8676]
### Target Platforms

NodeJS

### SDK Version

adaptivecards-templating: 2.3.1

### Application Name

Microsoft Teams

### Problem Description

I'm using adaptivecards-templating ts to render adaptive card and I installed `adaptive-expressions` `adaptivecards-templating` according to your instructions. 

When I run npm run build shows error:
"cannot find module adaptivecards/src/schema"

I wonder what's your suggestion to fix this problem, like adding "adaptivecards" package to dependencies or dev-dependencies?

### Screenshots

![image](https://github.com/microsoft/AdaptiveCards/assets/25220706/c27de437-451a-435a-b2c3-6d557e0ca2d9)

### Card JSON

```JSON
none
```

**Comment by jwoo-msft** [comment]
have you followed [this instruction](https://learn.microsoft.com/en-us/adaptive-cards/templating/sdk#npm)?

**Comment by yukun-dong** [comment]
> have you followed [this instruction](https://learn.microsoft.com/en-us/adaptive-cards/templating/sdk#npm)?

This insutrction is not clear on this line:
![image](https://github.com/microsoft/AdaptiveCards/assets/25220706/293894e6-f03f-4e6b-8b06-f9c87806c718)
Does this mean the "adaptivecards" also need to be installed?

**Comment by jwoo-msft** [comment]
> > have you followed [this instruction](https://learn.microsoft.com/en-us/adaptive-cards/templating/sdk#npm)?
> 
> This insutrction is not clear on this line: ![image](https://user-images.githubusercontent.com/25220706/267187860-293894e6-f03f-4e6b-8b06-f9c87806c718.png) Does this mean the "adaptivecards" also need to be installed?

the example uses adaptivecards to render AdaptiveCards after JSON payload has been expanded. You should be able to follow the example code up to the line where it says // OPTIONAL: Render the card (requires that the adaptivecards library be loaded).
