### ISSUE TITLE
Adaptive Card render not showing using React app with Typescript.

### ISSUE THREAD

**Issue by lakshmikanth27** [microsoft/AdaptiveCards#8678]
### Discussed in https://github.com/microsoft/AdaptiveCards/discussions/8677

<div type='discussions-op-text'>

<sup>Originally posted by **lakshmikanth27** September  8, 2023</sup>
I changed the botframework version to 4.15.1 to render the tables(adaptive card schema 1.5), it is not showing the table but just a empty card.

tried these:

1. Added ```version``` property to adaptiveCardHostConfig no use, 
2. According to docs under the styleOptions wanted me to add adaptiveCardsParserMaxVersion to mention the version, it did not work either.

Need some inputs to get this solved

I am using Typescript. Please guide me.
</div>

**Comment by jwoo-msft** [comment]
JS ac renderers render tables as you can check with [the designer](https://adaptivecards.io/designer/). This is not the issue of AC parser/renderer.

**Comment by lakshmikanth27** [comment]
My ask is different and the answer I am getting is different. I have an app that uses botframework version 4.15.11 with react rendering. In the bot, I am trying to render the adaptive card with a table. As per documents, adaptive cards with schema 1.5 are only supported with botframework v1.3 (attached image). In our app adaptive schema with 1.3 is only supported. 

My question is what should I do in order to support adaptivecards schema 1.5 in my application? 

Not in the designer on anywhere else. It's all about my application to support adaptive card schema 1.5.

**Comment by jwoo-msft** [comment]
If you have an application that hosts the AdaptiveCards renderer, all you need to do is get the latest AdaptiveCards package from npmjs. The latest package supports versions up to v1.6, including v1.5.
