### ISSUE TITLE
[Rendering] Action with Style destructive renders with poor constrast in "Standard" Design and not visible in High Contrast mode

### ISSUE THREAD

**Issue by tstaehli** [microsoft/AdaptiveCards#8686]
### Target Platforms

WPF

### SDK Version

Bot Framework v4

### Application Name

Microsoft Teams

### Problem Description

Hi,
I am not sure if this is the right place, if not, could you please point me to the correct place to report this?

We have developed a bot application that uses adaptive cards to interact with its users. We recently noticed, that some of our action buttons get very poor contrast in the Windows Teams client (not Preview Version)

An adaptive card generated by our bot application renders very bad in Windows Teams Client: Version 1.6.00.24078 (64-Bit).

Standard design has bad contrast and high contrast design has the text rendered white on a white background.

Also High Contrast Design does not render Placeholder Text very well... 

See screenshots below.

Kind Regards,
Tobias Stähli

### Screenshots

![image](https://github.com/microsoft/AdaptiveCards/assets/3128725/59a7473d-7fbe-4890-9589-2acb0f557063)
![image](https://github.com/microsoft/AdaptiveCards/assets/3128725/91499785-bda6-49c6-8837-2b969b861196)

### Card JSON

```JSON
{
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.4",
  "body": [
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "stretch",
          "items": [
            {
              "type": "TextBlock",
              "size": "large",
              "text": "Microsoft Teams Testalarm (TS)",
              "wrap": true
            },
            {
              "type": "TextBlock",
              "spacing": "small",
              "isSubtle": true,
              "text": "Sie sind dabei, diesen Alarm auszulösen"
            }
          ]
        },
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "Image",
              "url": "https://na-teams-bot-develop.novalink.ch/static/images/alert_icon_46_neg.png",
              "width": "50px",
              "height": "50px",
              "backgroundColor": "#FF00FF"
            }
          ]
        }
      ]
    },
    {
      "type": "Container",
      "items": [
        {
          "type": "TextBlock",
          "text": "Individueller Alarmtext:"
        },
        {
          "type": "Input.Text",
          "placeholder": "Individuellen Alarmtext eingeben...",
          "id": "CustomAlertText",
          "value": ""
        },
        {
          "type": "TextBlock",
          "text": "PIN"
        },
        {
          "type": "Input.Text",
          "placeholder": "PIN-Code zum Auslösen",
          "id": "pinCode",
          "isMasked": true,
          "style": "password"
        }
      ],
      "separator": true
    }
  ],
  "actions": [
    {
      "type": "Action.Execute",
      "title": "Alarm auslösen",
      "data": {
        "value": "triggerable_alert_triggered",
        "NAAlertCookie": "some value"
      },
      "style": "positive"
    },
    {
      "type": "Action.Execute",
      "title": "Abbrechen",
      "data": {
        "value": "abort_triggerable_alert",
        "NAAlertCookie": "some value"
      },
      "style": "destructive"
    }
  ]
}
```

**Comment by jwoo-msft** [comment]
@tstaehli 
If you examine your card, you will notice that there are no places to configure the parameters you desire. It is intentional such parameters are supposed to be configured by host apps, in your case, it is Microsoft Teams. You should relay this concern to the Microsoft Teams team.

**Comment by tstaehli** [comment]
@jwoo-msft Thank you for your quick reply. 
I'm not sure I fully understand your answer. Is it, that I have reported the issue to the wrong project (If so, which one is the correct one) or that I have used properties in the adaptive card, that I should not have used? So basically is it a bug in microsoft or did I use stuff I should not have used?
Thank you

**Comment by jwoo-msft** [comment]
@tstaehli, you've reported to the wrong project.
You can test your card using [our designer](https://adaptivecards.io/designer/), which offers a close approximation of how cards would render in the respective hosting app.
![image](https://github.com/microsoft/AdaptiveCards/assets/4112696/c0ced6d4-e80b-40d6-8d70-e94a9938af23)
You can choose the host app and select between light/dark mode.
Your card renders correctly. Attributes such as background and button colors are configured by the hosting app. You should reach out to the team that owns the app rendering the AC and report this issue. Teams also have their own designer.
![image](https://github.com/microsoft/AdaptiveCards/assets/4112696/653507c7-ec3f-4392-9b44-fd2d20f34b6a)
![image](https://github.com/microsoft/AdaptiveCards/assets/4112696/7c7730bf-a23d-4112-8eca-d1868961d24d)
