### ISSUE TITLE
User profile picture not rendered in adaptive card on Teams client app

### ISSUE THREAD

**Issue by Ismael-Cruz** [microsoft/AdaptiveCards#8687]
### Target Platforms

Other

### SDK Version

Adaptive Cards 1.3

### Application Name

Microsoft Teams

### Problem Description

When adding the user profile picture with url "/_layouts/15/userphoto.aspx" to an adaptive card, it renders in Teams via browser but not in the client app, which returns a 401 Unauthorised.

URL for the image: https://TENANT.sharepoint.com/_layouts/15/userphoto.aspx?size=S&accountname=USER_EMAIL@TENANT.onmicrosoft.com

### Screenshots

Teams in browser:
![Screenshot 2023-09-22 154948](https://github.com/microsoft/AdaptiveCards/assets/7807026/a07490a5-052e-44a1-bf8c-257eb066a6cd)
Teams app:
![Screenshot 2023-09-22 154959](https://github.com/microsoft/AdaptiveCards/assets/7807026/ef0e436c-ff28-46d4-b3f1-1880e5692af0)

### Card JSON

```JSON
{
      "type": "AdaptiveCard",
      "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
      "version": "1.3",
      "body": [
        {
          "type": "Container",
          "items": [
            {
              "type": "ColumnSet",
              "spacing": "extraLarge",
              "columns": [
                {
                  "type": "Column",
                  "width": "36px",
                  "items": [
                    {
                      "type": "Image",
                      "url": "https://TENANT.sharepoint.com/_layouts/15/userphoto.aspx?size=S&accountname=USER_EMAIL@TENANT.onmicrosoft.com",
                      "width": "36px",
                      "style": "person"
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
```

**Comment by jwoo-msft** [comment]
Closing this issue since it's hosting app issue.
