### ISSUE TITLE
Create adapative card based on Json Schema is not working

### ISSUE THREAD

**Issue by vn0ytch** [microsoft/AdaptiveCards#8710]
### Problem Description

1. Go to https://adaptivecards.io/designer/
2. Click left top corner "New card"
3. Select from Json Schema 
4. Take to "Create from JSON Schema" page where I copied json schema contents and click create button
5. Doesn't generate full Adaptive card contents based on json schema.
6. Card Payload Editor gives adaptive card with null items
Output

Json Schema Input example is below
`
[
  {
    "id": "5f4fde50-aa9f-11ea-b5db-sdsdd",
    "name": "project-test",
    "owner": {
      "id": "100",
      "username": "John"
    },
    "project-source": "java"
  },
  {
    "id": "ed02aefe-ecdc-11ec-97dd-dfdfdf",
    "name": "Test-Demo",
    "owner": {
      "id": "200",
      "username": "Mike"
    },
    "project-source": "python"
  }
]
`
Please help me to generate adaptive card based on JSON.

### Card JSON

```JSON
`
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Container",
            "items": [
                null,
                null
            ]
        }
    ]
}
`
```

### Screenshot

![Screenshot 2023-10-16 at 10 52 43 AM](https://github.com/microsoft/AdaptiveCards/assets/44210472/e2183050-d625-4bdb-8128-db0f176f6e9d)
![Screenshot 2023-10-16 at 10 53 01 AM](https://github.com/microsoft/AdaptiveCards/assets/44210472/62fc092e-a814-451b-9537-77ed15ec212f)

**Comment by jwoo-msft** [comment]
@vn0ytch,

I suggest starting with a blank card and using our designers to design the cards. You can drag and drop elements from the card element pane on the left. Doing so will help you better understand the AdaptiveCards schema. After familiarizing yourself with this, the information found at [this link](https://learn.microsoft.com/en-us/adaptive-cards/templating/) will be invaluable. It delves into the AdaptiveCards' Templating feature. While the JSON Schema you provided can be utilized in templating, it's essential to create an AdaptiveCards template that can process that data. I am closing this issue for now. Please respond to this thread if needed, and refrain from creating a new issue.
