### ISSUE TITLE
Action.ToggleVisibility does not trigger an onAction event

### ISSUE THREAD

**Issue by aboultonhumana** [microsoft/AdaptiveCards#8711]
### Target Application

Viva Connections Dashboard

### Application Operating System

Windows

### Schema Version

1.5

### Problem Description

Setting an action of `Action.ToggleVisibility` in the Quick View JSON does not trigger the `onAction` event in SPFx code.

### Expected Outcome

Expecting the `Action.ToggleVisibility` action to trigger an `onAction` even in the same way that `Action.Submit` and `Action.Execute` trigger the event.

### Actual Outcome

`onAction` event is not triggered. 

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5",
    "body": [
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.ToggleVisibility",
                    "title": "Toggle visibility",
                    "id": "ToggleButton",
                    "targetElements": [
                        "hidden"
                    ]
                }
            ]
        },
        {
            "type": "TextBlock",
            "text": "Initially hidden content",
            "wrap": true,
            "id": "hidden",
            "isVisible": false
        }
    ]
}
```

### Repro Steps

- Implement the Quick View template above
- In code, listen for the `onAction` event.

**Comment by jwoo-msft** [comment]
@aboultonhumana,

Have you tried using your JSON in [the designer](https://adaptivecards.io/designer/)? I didn't find any issues there.
I'm closing this issue. Please respond to this thread if you have any further questions.

**Comment by aboultonhumana** [comment]
> @aboultonhumana,
> 
> Have you tried using your JSON in [the designer](https://adaptivecards.io/designer/)? I didn't find any issues there. I'm closing this issue. Please respond to this thread if you have any further questions.

Correct, Action.ToggleVisibility triggers the action event (i.e. pops up the alert with the data) in the Designer tool but not in SharePoint Framework (v 1.18 and tested with earlier versions). The other universal actions do trigger the event in code.

**Comment by jwoo-msft** [comment]
@aboultonhumana, Have you spoken with the developers who maintain SharePoint Framework? As demonstrated, Adaptive Cards are functioning correctly, as the designer is running on the latest version of Adaptive Cards.

**Comment by aboultonhumana** [comment]
Thanks @jwoo-msft -- agreed it's an issue with the SPFx implementation. For anyone stumbling upon this, a workaround is to _not_ use the **ToggleVisibility** action, but instead to use **Action.Execute** in combination with the **$when** attribute in the JSON template to show/hide the element based on a value stored in the card's state (e.g. a value of `${showTheThing}` that is initially `false`). So, instead of setting a **ToggleVisibility** action on an element, use **Action.Execute** in combination with a **verb** used to identify that specific interaction. Then, for the **Execute** action, the **onAction** event handler in the SPFx ACE code _is_ triggered. When that specific Action + verb occurs we then update the card's state corresponding to the **$when** condition, e.g. setting the `showTheThing` to `true` to conditionally show the element(s).
