### ISSUE TITLE
[WPF] Container Style of Default returns null

### ISSUE THREAD

**Issue by mrbrennonwilliams** [Microsoft/AdaptiveCards#873]
A container style of "Default" returns

` "style": null`

Web Visualiser fails - WPF continues to render

**Comment by matthidinger** [comment]
Hi Brennon, could you elaborate a bit? There was a bug in the .NET serializer that was adding "style": null to the JSON, but this has been fixed, and should be in the latest NuGet pacakge. Is that what you're referring to? These fixes and others are currently in the dotnet2 branch which has an open PR

https://www.nuget.org/packages/AdaptiveCards/1.0.0-beta02

**Comment by mrbrennonwilliams** [comment]
@matthidinger   My bad - using an old build in a test rig.

I continue to use direct from source rather than NuGet at the moment. Is the dotnet2 branch not public but pushed into NuGet?

I keep checking the source looking for the ID property ;-)

Cheers
