### ISSUE TITLE
{Linked:Bug11059109} [Adaptive Cards > Designer] - Screen Reader is conveying irrelevant information while activating the submit button. 

### ISSUE THREAD

**Issue by vagpt** [microsoft/AdaptiveCards#8733]
### Target Platforms

Other

### SDK Version

1.6

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
URL: https://adaptivecards.io/designer/
OS Version: 23H2 (OS Build 25977.1000)
Browser Version: Version 120.0.2186.2 (Official build) dev (64-bit)
Screen Reader: Screen Reader

**Pre-Requisite:**
Run the below attached JSON file under 'Copy Card Payload editor.'

**Repro Steps:**
1. Open the above URL on the EDGE Dev browser.
2. Run the Json file.
3. Navigate to the Preview mode and press enter key to activate it.
4. Leave all mandatory field blank and press tab key to navigate on Submit button.
5. Press enter key and observe the issue.

**Actual Result:**
Screen Reader is conveying irrelevant information when without entering value in any field user is activating submit button.
Instead of only error messages being read, extra information is being read which is not required and can be confusing to user.

**Expected Result:**
After activating the Submit button, screen reader should convey the error message only.

**User Impact:**
It will impact the Screen reader as they will be confused if extra information is being read which is not required.

**WCAG Reference:**
https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships

Have feedback to share on Bugs? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0)

### Screenshots

https://github.com/microsoft/AdaptiveCards/assets/95913748/79d5c599-212f-4cb5-8a2c-d18e0b2f7940

### Card JSON

```JSON
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.6",
    "body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "width": 2,
                    "items": [
                        {
                            "type": "TextBlock",
                            "text": "Please enter the below details to create SAP user account request",
                            "weight": "Bolder",
                            "wrap": true
                        },
                        {
                            "type": "Input.ChoiceSet",
                            "id": "Roles",
                            "style": "expanded",
                            "isMultiSelect": true,
                            "isRequired": true,
                            "errorMessage": "Please select the role",
                            "label": "Role",
                            "wrap": true,
                            "choices": [
                                {
                                    "title": "Project Manager",
                                    "value": "Project Manager"
                                },
                                {
                                    "title": "Business Manager",
                                    "value": "Business Manager"
                                },
                                {
                                    "title": "Customer Account Manager",
                                    "value": "Customer Account Manager"
                                },
                                {
                                    "title": "Software Engineer",
                                    "value": "Software Engineer"
                                }
                            ],
                            "value": ""
                        },
                        {
                            "type": "Input.Text",
                            "id": "Justification",
                            "isMultiline": true,
                            "isRequired": true,
                            "errorMessage": "Please provide the business justification",
                            "label": "Business Justification",
                            "value": "",
                            "wrap": true
                        }
                    ]
                }
            ]
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Submit",
            "data": {
                "id": "SAPUserRequest_Submit"
            }
        }
    ]
}
```

**Comment by vagpt** [comment]
Originally tracked with below URL.

https://dev.azure.com/MicrosoftIT/OneITVSO/_workitems/edit/11059109

**Comment by vagpt** [comment]
Hi @anna-dingler,

Any update on this bug?

**Comment by anna-dingler** [comment]
> Hi @anna-dingler,
> 
> Any update on this bug?

Can you send the video of the current behavior again? I do not have access to the original bug.

**Comment by vagpt** [comment]
Hi @jwoo-msft,

Sorry for late response.

Please find the below video from the dependent bug.

[11059109A11y_Intelligent Support_Iris bot_SAPaccessrequest_ScreenReader.webm](https://github.com/microsoft/AdaptiveCards/assets/95913748/67752c73-ddb6-49a2-a409-3031551e50b4)

**Comment by vagpt** [comment]
Hi @anna-dingler 

Any update on this bug?

**Comment by vagpt** [comment]
Hi @jwoo-msft 

Gentle Reminder!!!

**Comment by anna-dingler** [comment]
Hi @vagpt,

I don't have any updates on this bug at the moment. It is included in our March sprint.

Thanks!

**Comment by anna-dingler** [comment]
This fix is in production as of 3/18/24
