### ISSUE TITLE
trying to send a adaptive card in message body to MS Teams using MS Graph API - Send Messages - Getting Error

### ISSUE THREAD

**Issue by aoneahsan** [microsoft/AdaptiveCards#8744]
### Target Platforms

NodeJS

### SDK Version

1.4

### Application Name

Microsoft Teams - Microsoft Graph API

### Problem Description

I tried to send adaptive card as message body to MS Teams channel using MS Graph API
https://graph.microsoft.com/v1.0/teams/{team-id}/channels/{channel-id}/messages

I changed the respective values with teamid, and channelid and provided a valid access token as well.

but i'm getting error and an un able to send adaptive card as message to MS Teams us MS Graph API.

Please assist.

### Screenshots

<img width="1324" alt="Screenshot 2023-11-07 at 7 16 17 PM" src="https://github.com/microsoft/AdaptiveCards/asset
<img width="932" alt="Screenshot 2023-11-07 at 7 16 30 PM" src="https://github.com/microsoft/AdaptiveCards/assets/37369204/07c496c0-a224-4a13-9a79-39676fed18c3">
s/37369204/2de6d5f7-7bfe-447a-91e9-ee3db6eff760">

### Card JSON

```JSON
{
	type: 'AdaptiveCard',
	version: '1.0',
	body: [
		{
			type: 'TextBlock',
			text: 'Hello, this is an Adaptive Card!',
		},
	],
	actions: [
		{
			type: 'OpenUrl',
			title: 'Visit Zaions.com',
			url: 'https://zaions.com',
		},
	],
}
```

### Sample Code Language

JavaScript

### Sample Code

export const testSendNotificationToChannelInMSTeamsHandler = async () => {
	try {
		const teamId = 'teamId'
		const channelId = 'channelId'

		if (teamId && channelId) {
			const isValid = true
			const accessToken = 'token here'

			if (isValid && accessToken) {
				const card = {
					type: 'AdaptiveCard',
					version: '1.0',
					body: [
						{
							type: 'TextBlock',
							text: 'Hello, this is an Adaptive Card!',
						},
					],
					actions: [
						{
							type: 'OpenUrl',
							title: 'Visit Zaions.com',
							url: 'https://zaions.com',
						},
					],
				}
				const result = await axios.post(
					MS_TEAMS.GRAPH_API_ENDPOINTS.SEND_MESSAGE_IN_CHANNEL(
						teamId,
						channelId
					),
					{
						subject: 'Adaptive Card Test',
						body: {
							contentType: 'html',
							content: card,
						},
					},
					{
						headers: {
							Accept: 'application/json',
							'Content-Type': 'application/json',
							Authorization: `Bearer ${accessToken}`,
						},
					}
				)

				console.dir({ success: true, result, card })

				if (getObjectKey(getObjectKey(result, 'data'), 'id')) {
				  return {
				    message: messages.GENERAL.SUCCESS,
				    accessTokenIsValid: true,
				    success: true
				  }
				} else {
				  return {
				    message: messages.MS_TEAMS.MESSAGE_SENDING_FAILED,
				    accessTokenIsValid: true,
				    success: true
				  }
				}
			} else {
				return {
					message: messages.MS_TEAMS.ACCESS_TOKEN_EXPIRED,
					accessTokenIsValid: false,
					success: false,
				}
			}
		} else {
			return {
				message: messages.MS_TEAMS.TEAM_CHANNEL_ID_IS_REQUIRED,
				accessTokenIsValid: false,
				success: false,
			}
		}
	} catch (error) {
		const data = error.response.data
		console.dir(data)
		return {
			message: getObjectKey(error, 'message', messages.GENERAL.ERROR_OCCURRED),
			accessTokenIsValid: false,
			success: false,
		}
	}
}

**Comment by aoneahsan** [comment]
Hi there,

how ever look into this issue, i'm available to provide extra info as well, if the provided info is not enough to recreate the issue.

waiting for reply.

**Comment by jwoo-msft** [comment]
@aoneahsan , please file the issue to the Teams directly.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/9850
