### ISSUE TITLE
[Authoring] Int value does not dispaly in TextBlock

### ISSUE THREAD

**Issue by steam3d** [microsoft/AdaptiveCards#8749]
### Target Application

https://adaptivecards.io/designer/

### Application Operating System

Windows

### Schema Version

1.6

### Problem Description

When you set the number to TextBlock, it does not display 
```
{
    "number": 1    
}
```

### Expected Outcome

The number must display.

### Actual Outcome

The number does not display.

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.6",
    "body": [
        {
            "type": "TextBlock",
            "text": "${$root.number}",
            "wrap": true
        }
    ]
}
```

**Comment by anna-dingler** [comment]
Hi @steam3d,

You can resolve this by using [adaptive expressions prebuild functions](https://learn.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0)

For instance, `string()` would work here:

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.6",
    "body": [
        {
            "type": "TextBlock",
            "text": "${string($root.number)}",
            "wrap": true
        }
    ]
}
```
