### ISSUE TITLE
TypeScript date formatting function bugs

### ISSUE THREAD

**Issue by matthidinger** [Microsoft/AdaptiveCards#876]
- [ ] The DATE Short format is incorrect. Should be MM/DD/YYYY (or whatever is locale appropriate)
- [ ] The Regex isn't allowing a space between the format modifier

```json
{{DATE(2017-02-14T06:08:39Z, Short)}}
```

## Expected

![image](https://user-images.githubusercontent.com/1432195/32343600-4c55b8c2-bfc1-11e7-97e1-86d49e7f6dcc.png)

## Actual

![image](https://user-images.githubusercontent.com/1432195/32343622-6049a0b4-bfc1-11e7-8dd8-5cb2825869f2.png)

## Payload

```json
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
        {
            "type": "TextBlock",
            "text": "Created {{DATE(2017-02-14T06:08:39Z,Short)}} {{TIME(2017-02-14T06:08:39Z)}}",
            "wrap": true
        },
        {
            "type": "TextBlock",
            "text": "Created {{DATE(2017-02-14T06:08:39Z,Long)}} {{TIME(2017-02-14T06:08:39Z)}}",
            "wrap": true
        }
    ]
}
```

**Comment by dclaux** [comment]
The Date formatter actually supports 3 formats:
* Long, e.g. "Monday, February 13th, 2017"
* Short, e.g. "Mon, Feb 13th, 2017"
* Compact, e.g. "2/13/2017" which you get if no format is specified

Happy to change that, but the above was the original design, so why would the other renderers not match that behavior?

Why should a space be allowed before the format specifier?

**Comment by matthidinger** [comment]
Closing in lieu of #908 which will require some changes to all renderers
