### ISSUE TITLE
[Feature Request] Support backgroundcolor or font color on containers and textblocks and such

### ISSUE THREAD

**Issue by bzuidgeest** [microsoft/AdaptiveCards#8766]
### Problem Statement

It doesn't seem possible to set a background color or text color in the card. 
I can somewhat understand why this is so, as cards have to render in different environments. So just render hints are provided. 
However there is value in color. Red for warnings, green for safe. 

### Proposed solution

If actual color rgb information isn't possible. could the selection of hints like bold, bolder, normal be expanded to include things like "error", "warning" ,"ok" etc. ?

### Alternatives or Workarounds

using a background image with an rgb color

**Comment by jwoo-msft** [comment]
The actual color coding is determined by the host application, such as Teams and Outlook. In other words, if you are rendering the card, you can specify its color using hostConfig.

**Comment by bzuidgeest** [comment]
I know the host application determines color, but it does so based on the hints it gets from the card. There are no hints for warning, error, ok and all such kinds of information. Therefor the second solution I suggested was adding more rendering hints. Not just bold and normal, that is a rather limited set.





________________________________
