### ISSUE TITLE
Adaptive card design

### ISSUE THREAD

**Issue by Uthiraa1** [microsoft/AdaptiveCards#8771]
Within the adaptive card of Power Virtual Agent, there are three buttons. When one button is selected, the remaining two should be grayed out. Is it possible to implement this in PVA? We would greatly appreciate your assistance in this matter.

**Comment by jwoo-msft** [comment]
AC provides Action.Execute. Action.Execute provides a mean to refresh, and when card is refreshed, Actions can have different state.  However, hosting app of AC  must support this feature for cards authors to use it.

**Comment by Uthiraa1** [comment]
The command " Action.Execute" is not working. The version used is 1.4. There is no error shown in code while using it but it does not add the outputs of adaptive card, and this gives error while saving the topic. " Missing Action.Submit" is seen. Are there any alternatives?
