### ISSUE TITLE
Adaptive Card Tables - Bot Composer

### ISSUE THREAD

**Issue by LarryLeonidas** [microsoft/AdaptiveCards#8781]
It would seem **Composer 2.1.2** is unable to render **Tables**. Screenshot below. 

Please confirm

![image](https://github.com/microsoft/AdaptiveCards/assets/3912134/c975108c-e4d8-4319-bdf6-9cc53a0842dc)

---
* URL: https://adaptivecards.io/explorer/Table.html

**Comment by jwoo-msft** [comment]
Hi @LarryLeonidas 
Could you please check with the Composer team which version of AC is supported? The table feature is available starting from version 1.5.

**Comment by LarryLeonidas** [comment]
Ok thanks.
