### ISSUE TITLE
[Android][Rendering] Memory leak issue while rendering Textblock render

### ISSUE THREAD

**Issue by trickcharan** [microsoft/AdaptiveCards#8783]
### Target Platforms

Android

### SDK Version

3.1.1

### Application Name

Webex

### Problem Description

The issue at hand involves the rendering of an adaptive card within a fragment or activity in Android. As expected, once we navigate away from the fragment or activity, all memory associated with the adaptive card should be released. However, this isn't happening as it should. Instead, the text block renderer in the adaptive card is retaining the reference to the fragment or activity(code reference: https://github.com/microsoft/AdaptiveCards/blob/76cec36cf063009260f3dc5642d29a7624255ea5/source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/TextBlockRenderer.java#L239C6-L256C6), preventing the full release of memory. This memory leak could potentially lead to performance issues in the application.

In addition to this, we've identified another potential memory leak in the following places 

1. [DateInputHandler.java](https://github.com/microsoft/AdaptiveCards/blob/76cec36cf063009260f3dc5642d29a7624255ea5/source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/DateInputHandler.java#L24)
2. [TimeInputHandler.java](https://github.com/microsoft/AdaptiveCards/blob/76cec36cf063009260f3dc5642d29a7624255ea5/source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/TimeInputHandler.java#L26)

The problem arises from the storage of the fragment manager from the application which can potentially cause memory leaks.

### Screenshots

<img width="486" alt="Screenshot 2023-12-22 at 10 35 00 AM" src="https://github.com/microsoft/AdaptiveCards/assets/29520819/adf7ae79-6b6a-4733-ac20-ee725c324a28">

### Card JSON

```JSON
{
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"type": "AdaptiveCard",
"version": "1.0",
"body": [
{
"type": "TextBlock",
"text": "This is some text",
"size": "large"
},
{
"type": "TextBlock",
"text": "It doesn't wrap by default",
"weight": "bolder"
},
{
"type": "TextBlock",
"text": "So set wrap to true if you plan on showing a paragraph of text",
"wrap": true
},
{
"type": "TextBlock",
"text": "You can also use maxLines to prevent it from getting out of hand",
"wrap": true,
"maxLines": 2
},
{
"type": "TextBlock",
"text": "You can even draw attention to certain text with color",
"wrap": true,
"color": "attention"
}
]
}
```

### Sample Code Language

kotlin

### Sample Code

Once you run this project try to install the app and go to the second activity. Then do, dump memory. It will show two leaks.

[ButtonAndCards 2.zip](https://github.com/microsoft/AdaptiveCards/files/13914974/ButtonAndCards.2.zip)

**Comment by anna-dingler** [comment]
Closing as this was moved to AC Mobile: https://github.com/microsoft/AdaptiveCards-Mobile/issues/80
