### ISSUE TITLE
[adaptivecards-react]  action button rendering issue. (Not Wrapped for multi buttons)

### ISSUE THREAD

**Issue by fiatlux316** [microsoft/AdaptiveCards#8792]
# Platform
react 17.0.2

What platform is your issue or question related to? (Delete other platforms).
* JavaScript / TypeScript
  : Wrapper of Adaptivecards JS for React Web App

# Author or host
- host : react web

# Version of SDK
- "adaptivecards-react": "1.1.1",
- "adaptivecards-templating": "2.3.1"
-  "adaptivecards": "2.10.0"

# Issue
- I am testing adaptivecards for hierarchial quesion&answer flows via Action.Execute on React Web App.
- Multiple action buttons must be displayed on UI,  but some button is clipping !!  (Not wrapped)
  ( On Teams,  multiple action buttons is displayed on wrap default)

[react web]
<img width="330" alt="image" src="https://github.com/microsoft/AdaptiveCards/assets/43848399/4c5face9-fc0b-462e-804b-27ae277f0be0">

[teams app]
<img width="371" alt="image" src="https://github.com/microsoft/AdaptiveCards/assets/43848399/0d370996-5b8c-447e-9318-abf6ae92ff46">

**Comment by fiatlux316** [comment]
How to wrap buttons ??  (All conditions is same both react web and teams app)

**Comment by jwoo-msft** [comment]
that's a feature not supported by the library. The host of react web has to provide such feature via Native Styling or Extensibility feature of AdaptiveCards. 
https://learn.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/javascript/native-styling
https://learn.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/javascript/extensibility
also we no longer support adaptivecards-react
