### ISSUE TITLE
[Website] Image links are broken in some adaptive card samples

### ISSUE THREAD

**Issue by a1exwang** [microsoft/AdaptiveCards#8844]
![image](https://github.com/microsoft/AdaptiveCards/assets/9698542/d0b9b6b1-1e22-46be-9380-73ee78494e9d)

![image](https://github.com/microsoft/AdaptiveCards/assets/9698542/17839a0a-971d-4867-8a1a-ced4d0120a28)

---
* URL: https://adaptivecards.io/samples/Agenda.html

**Comment by anna-dingler** [comment]
Thank you for reporting! This issue has been fixed.
