### ISSUE TITLE
[Web] Render failure error notification incorrect

### ISSUE THREAD

**Issue by mrbrennonwilliams** [microsoft/AdaptiveCards#889]
The following fails in the Web renderer - because the textblock element has a requirement for text and no value is present, yet I get a response: **Cannot read property 'style' of null**

```json
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "minVersion": "1.0",
    "fallbackText": "this is the  fallback text",
    "speak": "",
    "backgroundImage": "http://adaptivecards.io/content/cats/1.png",
    "body": [
        {
            "type": "TextBlock",
            "id": "5c4586e3-35fa-4947-8db1-2e77d78e5b2a",
            "text": "",
            "maxLines": 1
        }
    ],
    "actions": [
        
    ]
}
```

**Comment by matthidinger** [comment]
Thanks Brennon this is good feedback. @dclaux not sure if we have an issue tracking more friendly errors, so labeling this to track it

**Comment by dclaux** [comment]
The above card yields "The card is empty" in the visualizer built from master, because an empty text block (empty text property) is ignored. Can you elaborate in what context you are getting "Cannot read property 'style' of null"? Are you using the npm package for the renderer? Maybe the npm package is outdated?

**Comment by mrbrennonwilliams** [comment]
I was getting that at the time from the web visualiser on the .io site,

As I hadn't rebooted for a month or two, I think Chrome was caching a long ago version.

It should be noted that i get no such error in the WPF visualiser on main branch. Not sure if you want to close this out an open a new issue specific to WPF?

**Comment by dclaux** [comment]
I think it should be fixed now. At least the visualizer built individually doesn't have that problem.

**Comment by mrbrennonwilliams** [comment]
I'll write this as a new issue WPF specific. Cheers

**Comment by mrbrennonwilliams** [comment]
Actually this is not correct. Inconsistent behaviour between WEB and WPF renderer.

I believe WPF is correct, because the property is set as "text" : "",  which is entirely valid. The WEB render should honour that and not return an error message of "The card is empty".

**Comment by dclaux** [comment]
The documentation says the text property is required, e.g. if text isn't specified the TextBlock isn't valid and shouldn't be rendererd, I think it boils down to defining what "required" and "specified" mean. If we say that an empty string is still a "specified" string then it doesn't make much sense IMO to define the text property as required. So either we change the documentation/spec to say text isn't required (and defaults to an empty string) or we consider that an empty string doesn't qualify as "specified" and makes the TextBlock invalid. To me the HTML renderer is per spec, the WPF one isn't, but I don't have a problem with either behavior, we just need to be crisp on which one all renderers need to implement.

@matthidinger what do you think?

**Comment by mrbrennonwilliams** [comment]
> I think it boils down to defining what "required" and "specified" mean

Absolutely agree.

The challenge is that Json considers a required property must simply not be null. This is why "" is valid.

I've never seen an object requirement for "specified" outside of a validation context, certainly not in a serialisation one.

Given that we are working within the context of Json, for my mind it makes sense to continue with the common implementation of it.

**Comment by andrewleader** [comment]
Closing as this now seems to render everywhere (JS/UWP/WPF tested)
