### ISSUE TITLE
Can AdaptiveChoice and AdaptiveFact become AdaptiveTypedElement?

### ISSUE THREAD

**Issue by mrbrennonwilliams** [microsoft/AdaptiveCards#890]
These two elements appear to be the only ones which do not inherit back to AdaptiveTypedElement, so they do not contain an ID property.

Can I ask if there is a specific reason why they are not AdaptiveTypedElements and if not, would it be possible to please make them?

Many thanks

**Comment by matthidinger** [comment]
Is adding an Id property good enough? I'm on the fence if inheriting is the correct design here, since the "type" is implicit for these elements and I'm not sure we even want to allow people to specify a type for them

**Comment by mrbrennonwilliams** [comment]
I ran into the problem when I was implementing the update from JSON. When traversing the card object I have a recursive method that seeks the original object and that method expects an AdaptiveTypedElement.

That be my problem, not yours ;-)

An Id property will let me achieve the desired result.

**Comment by andrewleader** [comment]
Closing as there's no use in the Adaptive schema itself to have an `Id` property on these elements, but through extensibility hosts can choose to read an id property from them.
