### ISSUE TITLE
[dotnet] Issues with Id

### ISSUE THREAD

**Issue by mrbrennonwilliams** [Microsoft/AdaptiveCards#892]
As the old saying goes... be careful what you wish for ;-)

Can AdaptiveInput return the base.Id rather than a separate static Id property?

If not, it may be appropriate to rename the AdaptiveTypedElement Id property to ElementId or some variation so there is a clear difference. 

![image](https://user-images.githubusercontent.com/32671341/32400067-b027f54e-c0f3-11e7-9b27-8c9d1a7770eb.png)

**Comment by matthidinger** [comment]
If you `git fetch` and `git checkout dotneterrors` this should be fixed now. I changed it such that AdaptiveInput no longer hides the inherited Id property but still enforces that all Inputs have an Id set

**Comment by mrbrennonwilliams** [comment]
Thanks for Matt.
