### ISSUE TITLE
.NET should offer a facade API to parse and render at once

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#895]

**Comment by mrbrennonwilliams** [comment]
Just clarifying my understanding:

Do you mean instead of deserialising a parse result and then getting a RenderedAdaptiveCard, just parse the JSON and return RenderedAdaptiveCard?

I assume at that point you would go ahead and render the fallback if the card fails inside the render?

**Comment by matthidinger** [comment]
Yea that's the idea. If the rendering/parsing fails it will still throw an `AdaptiveException`, either `AdaptiveSerializationException` or `AdaptiveRenderException`, and the host app could choose to display the fallback text if it was properly parsed
