### ISSUE TITLE
[Designer] all designer icons are broken

### ISSUE THREAD

**Issue by IntranetFactory** [microsoft/AdaptiveCards#9009]
### Problem Description

We just noticed that loading the icons woff files fail suddenly with CORS error. That even happens on https://adaptivecards.io/designer/

<img width="1917" alt="{8293742F-A6CF-40DB-8B88-2D15C580D58F}" src="https://github.com/user-attachments/assets/6aa4213d-7f8a-473f-943c-3e1a08161699">

### Card JSON

```JSON
not card specific
```

**Comment by mihaiManea89** [comment]
It also affects the adaptivecards-designer npm package.

**Comment by anna-dingler** [comment]
@IntranetFactory Can you provide repro details? We do not see this on our end. Thanks!

**Comment by IntranetFactory** [comment]
Today https://static2.sharepointonline.com/files/fabric/assets/icons/fabricmdl2icons-3.54.woff does not cause CORS errors any longer.
