### ISSUE TITLE
Can a .html file be rendered into Adaptive card

### ISSUE THREAD

**Issue by Yashu1904** [microsoft/AdaptiveCards#906]
I have tried rendering a html file to adaptive card, will this work out or Can I do it using any other cards like hero,thumbnail etc.,

**Comment by matthidinger** [comment]
Hi there, I don't really follow the question, can you provide more details? All adaptive cards are in JSON format, but can be rendered to HTML

**Comment by dclaux** [comment]
Hi @Yashu1904, assuming you mean "a way to render random HTML within an Adaptive Card" the answer is no, it isn't possible and won't, as that would defeat two of the main reasons for Adaptive Cards to exist in the first place:
1. Being a lightweight "universal" format
2. Shielding the host from "visual abuse" by somewhat constraining what can be accomplished in terms of styling, colors, etc.
