### ISSUE TITLE
Markdown bullet and numbered lists not being rendered in web visualizer

### ISSUE THREAD

**Issue by riarenas** [Microsoft/AdaptiveCards#909]
The Textblock.Markdown sample:

```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "This is some **bold** text"
        },
        {
            "type": "TextBlock",
            "text": "This is some _italic_ text"
        },
        {
            "type": "TextBlock",
            "text": "- Bullet \r- List \r"
        },
        {
            "type": "TextBlock",
            "text": "1. Numbered\r2. List\r"
        },
        {
            "type": "TextBlock",
            "text": "Check out [Adaptive Cards](http://adaptivecards.io)"
        }
    ]
}
```

Renders like this in the visualizer: 

![image](https://user-images.githubusercontent.com/23242101/32573437-d568e100-c482-11e7-87eb-972843b8d891.png)

**Comment by dclaux** [comment]
It works in the visualizer as built from master:
![image](https://user-images.githubusercontent.com/1334689/32638897-58714e06-c5e7-11e7-8658-bc6266990264.png)

I really don't know why/how there could be a difference in the official visualizer, unless the styles for bullets and numbered lists are somehow altered in a CSS.

**Comment by matthidinger** [comment]
I just deployed the latest master to adaptivecards.io and still seeing this. Looked into it, and it's a rule from the css we use from docs.microsoft.com. I'll have to find some way to ignore this rule, but not really sure how

![image](https://user-images.githubusercontent.com/1432195/32640294-df1695e4-c57c-11e7-8ee9-0fe1a9318262.png)

**Comment by shalinijoshi19** [comment]
@matthidinger i think this is resolved yes? I didnt try the visualizer but did try the Designer in prod, and i can see the markdown elements in the textbox just fine?
![image](https://user-images.githubusercontent.com/20822397/56151564-5b9f9a00-5f66-11e9-8a4c-ff7363113ce9.png)
