### ISSUE TITLE
Build Failing on Test

### ISSUE THREAD

**Issue by mrbrennonwilliams** [Microsoft/AdaptiveCards#916]
Just downloaded the entire repo and tried to build.

Got a failure in AdaptiveCards.Test

![image](https://user-images.githubusercontent.com/32671341/32625982-df6af1c6-c585-11e7-8826-8f443cde4142.png)

**Comment by matthidinger** [comment]
In master? I'm not seeing that. It should be AdaptiveTextBlock tho

**Comment by mrbrennonwilliams** [comment]
So the oddest thing - I downloaded the master branch direct from github site (not in VS) and it looks like the wrong repo downloaded. I suspect it was an old branch as the class name is different.

Shall close this - its building fine.
