### ISSUE TITLE
Can we get a TextBlock Background color property

### ISSUE THREAD

**Issue by mrbrennonwilliams** [microsoft/AdaptiveCards#919]
A nice to have I guess. I can see where folks wont want the awesome cat being blocked out by the textblock background ;-)

![image](https://user-images.githubusercontent.com/32671341/32629510-640b839a-c591-11e7-8395-fbc8c04965fa.png)

**Comment by matthidinger** [comment]
Is that screenshot from an actual renderer? or is that what you're asking for? If that's seen in an existing renderer it's a bug and I'd like to fix it :)

**Comment by mrbrennonwilliams** [comment]
That's from WPF Visualiser in main branch. Has always been like this for the Sample HostConfig at least

**Comment by mrbrennonwilliams** [comment]
Latest main branch fixes some host configs but not others

![image](https://user-images.githubusercontent.com/32671341/33444789-153c160e-d5f3-11e7-9f77-d7a578a50322.png)

**Comment by matthidinger** [comment]
Can you include the JSON that creates those renders?

**Comment by mrbrennonwilliams** [comment]
Sure thing

`{
    "type": "AdaptiveCard",
    "version": "1.0",
    "id": "48a2077f-f1a3-4324-9c1a-9dc84a93c5b6",
    "minVersion": "1.0",
    "fallbackText": "",
    "speak": "",
    "backgroundImage": "http://www.jamies.london/wp-content/uploads/2016/12/our-wine-bars-wide-2300x994.jpg",
    "body": [
        {
            "type": "Container",
            "id": "936346ce-a227-4c25-a6ff-6eb03915a343",
            "items": [
                {
                    "type": "TextBlock",
                    "id": "8c16a1d1-b35f-477b-ac25-a7fd2fc5ba5e",
                    "size": "large",
                    "weight": "bolder",
                    "color": "light",
                    "text": "Come and experience the best wine bar that London has to offer",
                    "horizontalAlignment": "right",
                    "wrap": true,
                    "maxLines": 3
                }
            ]
        }
    ]
}`

**Comment by mrbrennonwilliams** [comment]
This should be merged with #1017 

It looks like elements inside a container have a default background set to white

**Comment by andrewleader** [comment]
This is fixed now as far as I'm aware
