### ISSUE TITLE
Using old attachment schema. Upgrade to new card schema

### ISSUE THREAD

**Issue by lmb0795** [Microsoft/AdaptiveCards#926]
I tried to use http://adaptivecards.io/samples/CalendarReminder.html in my app.js. But the cards were not properly rendered and got the above error in console. Please let me know what can be done about this

**Comment by matthidinger** [comment]
Hi there, I don't see the error information you mentioned. Can you please provide as much info like the detailed error, a screenshot of what you're seeing, and the version of the script/npm package you're using?

**Comment by lmb0795** [comment]
Hi Matt,

Thanks for replying. I used a sample code from adaptivecards.io and made a
mistake while using it. I rectified it and it's working fine.

Regards,
Manas

**Comment by matthidinger** [comment]
Ok great, thanks for letting us know
