### ISSUE TITLE
[UWP] UWP input gathering is including all ShowCards

### ISSUE THREAD

**Issue by riarenas** [Microsoft/AdaptiveCards#935]
Same issue as #927 is present in UWP renderer.

**Comment by almedina-ms** [comment]
@matthidinger @khouzam @RebeccaAnne @eschavez @nesalang Is this an actual bug or what is the expected functioning? Android does the same as UWP and iOS has a different functioning (if there is a show card action with an Action.Submit and there's another submit action in the outermost card, both buttons work but only the innermost text input value is retrieved, while in the case where the outermost submit action is before the showcard action, then only the inner most button works)

**Comment by shalinijoshi19** [comment]
@almedina-ms is this issue fixed for iOS? PLease reactivate if not. Assuming fixed based on PR that went in.
