### ISSUE TITLE
TypeScript renderer not inspecting/requiring version attribute

### ISSUE THREAD

**Issue by matthidinger** [Microsoft/AdaptiveCards#943]
1. The `version` attribute is not validated as "version" type.
   * `"version": "tss"`  should error with "'tss' is not a valid 'version' identifier"

2. The following is expected to fail with "Required property 'version' not found on AdaptiveCard"

```json
{
    "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "text": "This is some text",
            "size": "large"
        }
    ]
}
```

**Comment by dclaux** [comment]
Fixed
