### ISSUE TITLE
"placeholder" property on Input.Date and Input.Numer

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#944]
Is this property useful on these types given that we don't render it anywhere, at least in the HTML renderer.

If we do indeed show it on certain renderers then I can update the schema docs to say "this property is not always displayed"

http://adaptivecards.io/explorer/Input.Number.html
http://adaptivecards.io/explorer/Input.Date.html

**Comment by mrbrennonwilliams** [comment]
@matthidinger it looks like the placeholder values are rendered in WPF, dependent on the host config. Windows timeline for instance renders the placeholder value for both

**Comment by dclaux** [comment]
@matthidinger the HTML renderer should render placeholder, but the standard HTML5 controls don't support it. "Some day" the HTML renderer should use its own controls instead of the HTML5 versions (which do not work in IE11) and at that point placeholder will be rendered.
