### ISSUE TITLE
Should AdaptiveOpenUrlAction Url property be a Uri?

### ISSUE THREAD

**Issue by mrbrennonwilliams** [Microsoft/AdaptiveCards#954]
I only just noticed that it is still a string. Should this not be changed to reflect all other Url property types?

**Comment by matthidinger** [comment]
Indeed it should, I'll get to this soon

**Comment by mrbrennonwilliams** [comment]
I just submitted a PR for this but I assume all the other platforms will also need to change?

**Comment by matthidinger** [comment]
This change is in master now, and live in beta08 package, thanks!
