### ISSUE TITLE
[.NET] Date Time formatting final spec

### ISSUE THREAD

**Issue by matthidinger** [Microsoft/AdaptiveCards#959]
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

.NET implementation of #908

**Comment by shalinijoshi19** [comment]
@RebeccaAnne where are we tracking this on the readiness table again? Is this related to the bugs you were referring to at standup? @almedina-ms FYI

**Comment by RebeccaAnne** [comment]
This is a 1.0 feature that has already shipped.
