### ISSUE TITLE
UWP docs update

### ISSUE THREAD

**Issue by matthidinger** [microsoft/AdaptiveCards#978]
With #974 the docs are a little out of date. 

The "template" I used for [WPF](https://review.docs.microsoft.com/en-us/adaptive-cards/display/libraries/net-wpf?branch=master) may work well to steal. 

FTEs can access pre-release docs here:
https://review.docs.microsoft.com/en-us/adaptive-cards/display/libraries/uwp?branch=master

@riarenas you mentioned you might be able to handle this so let me know how your bandwidth is looking

**Comment by andrewleader** [comment]
Closing as stale/probably irrelevant now
