### ISSUE TITLE
Platform specific action support

### ISSUE THREAD

**Issue by synk** [Microsoft/AdaptiveCards#980]
We are investigating feasibility of providing AdaptiveCards API by our LINE messenger platform.

We will support standard actions. But our customers and SDK developers would like to re-use LINE specific action and its JSON structure (`uri`, `message`, `postback`, `datetimepicker`, `location`).

Do you have any plans of such platform specific actions?

**Comment by matthidinger** [comment]
Hi @synk, that makes total sense and is a supported scenario. The schema is designed to be extensible, so you are totally free to define new action types. Any unknown actions or elements that are encountered on other platforms will be dropped. 

Are you planning on using the SDKs we provide for your investigation or building your own?

**Comment by synk** [comment]
Thank you for the comment. so we will support both standard actions and our custom actions.

> Are you planning on using the SDKs we provide for your investigation or building your own?

We are currently implementing AdaptiveCards renderers from scratch.

**Comment by matthidinger** [comment]
That sounds good to me. Please continue to reach out if you have any feedback

**Comment by dclaux** [comment]
Hi @synk, if you don't mind me asking, what platform/language is LINE developed with? Is there any particular reason why you felt the renderers we provide do not meet your needs? (I'm assuming it's simply because we do not have an implementation for your particular platform, but maybe it's more than that?)

**Comment by synk** [comment]
I can't answer details in public place, but one of the reason is that we have to handle cards in our java-based server side platform.

**Comment by mdtauk** [comment]
Wouldn't that only require your Java server-side code to export a JSON file, that is sent to the clients/front-ends, which would render the cards?

**Comment by synk** [comment]
We are implementing AdaptiveCards renderer based on our existing `template message` architecture.  Since it is tightly coupled with our app code base, we cannot use your SDKs as it is.

BTW, close this issue since my question was solved.  Thanks!
