### ISSUE TITLE
'Fact' is ambiguous between AdaptiveCards.Fact and Microsoft.Bot.Connector.Fact

### ISSUE THREAD

**Issue by ederbond** [Microsoft/AdaptiveCards#982]
Is it correct to have to classes to do basically the same thing ?
Look at the description of each of theses 2 classes:

**AdaptiveCards.Fact**
Describes a Fact in a FactSet as a **key/value pair**

now 

**Microsoft.Bot.Connector**
Set of **key-value pairs**. Advantage of this section is that key and value properties will be rendered with default style information with some delimiter between them. So there is no need for developer to specify style information.

**Comment by ederbond** [comment]
I'm trying to post an AdpativeCard from a Dialog from my Bot, in this Dialog I have reference to bolth **Microsoft.Bot.Connector** and **AdaptiveCards** so when I'm being forced to use the fullyqualified name of the AdaptiveCards.Fact class witch is a kind of wird.

**Comment by mrbrennonwilliams** [comment]
Hi @ederbond 
The AdaptiveCards Fact element is called AdaptiveFact, and not just Fact.

I think it was renamed from just Fact.

Are you using the latest?

Cheers

**Comment by matthidinger** [comment]
Indeed you should update to the `AdaptiveCards` package, which addresses this and other naming issues. Note there are some minor breaking change. 

Docs here: https://docs.microsoft.com/en-us/adaptive-cards/create/libraries/net

Please re-open if this doesn't address your issue

**Comment by ederbond** [comment]
You're right, I was using the old "Microsoft.AdaptiveCards"  package. After migrating to 
<package id="AdaptiveCards" version="1.0.0-beta09" targetFramework="net47" />
I've noticed these classes was renamed.
Thks
