### ISSUE TITLE
Request Feature: Input.Date - Preselection / Highlight

### ISSUE THREAD

**Issue by telkomops** [microsoft/AdaptiveCards#994]
Hi using adaptive cards on my chatbot ui, i have a Adaptive card of "type": "Input.Date".When the user opens up the date panel, i need to high light few dates based on custom logic. I have a specific scenario where input.date selection should be used to pre-filter input.time as part of the same card. Request if this is something that we can add as a feature.

**Comment by andrewleader** [comment]
Hey @telkomops, thanks for this feature request, we've captured this feedback in our feedback system and will let you know if/when we ship a feature enabling this.
