### ISSUE TITLE
[Beta10] Context.PostAsync not rendering AdditionalProperties of AdaptiveCard

### ISSUE THREAD

**Issue by ederbond** [Microsoft/AdaptiveCards#995]
After updating the nuget package "AdaptiveCards" to version="1.0.0-**beta09**" the code below has no efect on the json returned by my bot:

```csharp
var card = new AdaptiveCard();
card.AdditionalProperties.Add(new KeyValuePair<string, object>("customType", "MyCard1"));
```

It seem that after calling the AdditionalProperties.Add() method has no efect.

**Comment by ederbond** [comment]
@matthidinger is this property intended to be used to customize AdaptiveCard elements ?

**Comment by matthidinger** [comment]
Hi @ederbond, I'm unable to repro this. Can you confirm the output from card.ToJson()? It should have the additional properties you specified. If you're running in the emulator, can you also paste in what the JSON sent to the bot is?

**Comment by ederbond** [comment]
You are right, the AdaptiveCard seems to have no issue, the problem seems to be with the PostCardAsync method of Microsoft.Bot.Builder.Dialogs.Internals.DialogContext class. 
I've inspected the code below an noticed that even when my adaptive card instance has some "AdditionalProperties" in it (and correctly serializing it if I call ToJson() as you suggested), these "AdditionalProperties" get lost on the response of the BotFramework whan I call 

```csharp
await context.PostCardAsync(card);
```

The response of this method hides the "AdditionalProperties"

**Comment by ederbond** [comment]
Here is the Json result for the card.ToJson();

```
{
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "text": "Abrir e manter"
    },
    {
      "type": "TextBlock",
      "text": "Sem anuidades e sem taxas escondidas.\r\n\r\n"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "data": "Como terminar meu cadastro?",
      "title": "Como terminar meu cadastro?"
    },
    {
      "type": "Action.Submit",
      "data": "É seguro?",
      "title": "É seguro?"
    },
    {
      "type": "Action.Submit",
      "data": "Voltar",
      "title": "Voltar"
    }
  ],
  "customType": "MyCard1"
}
```
Notice here in the end that it correctly has the "customType": "MyCard1"

however after passing this instance to the context.PostAsync() method it doen't return my "customType":"MyCard1"

**Comment by matthidinger** [comment]
I'm actually not able to repro this with the following packages, using the same code. Can you confirm you're on the same package versions of Bot builder and bot connector?

```xml
  <package id="AdaptiveCards" version="1.0.0-beta10" targetFramework="net46" />
  <package id="Microsoft.Bot.Builder" version="3.11.0" targetFramework="net46" />
  <package id="Microsoft.Bot.Connector" version="3.11.1" targetFramework="net46" />
```
![image](https://user-images.githubusercontent.com/1432195/33453604-1bcb956c-d5cb-11e7-91fd-ba8687781872.png)

**Comment by ederbond** [comment]
@matthidinger follows the packages I'm using:

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AdaptiveCards" version="1.0.0-beta10" targetFramework="net47" />
  <package id="Autofac" version="4.6.2" targetFramework="net46" />
  <package id="BUS.Core" version="2.14.1" targetFramework="net47" />
  <package id="BUS.User" version="3.4.5" targetFramework="net47" />
  <package id="Chronic.Signed" version="0.3.2" targetFramework="net46" />
  <package id="Dapper" version="1.50.4" targetFramework="net47" />
  <package id="elmah" version="1.2.2" targetFramework="net47" />
  <package id="Elmah.Contrib.WebApi" version="1.0.10.25" targetFramework="net47" />
  <package id="elmah.corelibrary" version="1.2.2" targetFramework="net47" />
  <package id="LazyCache" version="0.7.1.44" targetFramework="net47" />
  <package id="Microsoft.AspNet.Cors" version="5.2.3" targetFramework="net47" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net46" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net46" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net46" />
  <package id="Microsoft.AspNet.WebApi.Cors" version="5.2.3" targetFramework="net47" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net46" />
  <package id="Microsoft.Bot.Builder" version="3.12.2.4" targetFramework="net47" />
  <package id="Microsoft.Bot.Builder.CognitiveServices" version="1.1.2" targetFramework="net47" />
  <package id="Microsoft.Bot.Connector" version="3.12.2.4" targetFramework="net47" />
  <package id="Microsoft.CSharp" version="4.4.0" targetFramework="net47" />
  <package id="Microsoft.IdentityModel.Logging" version="1.1.5" targetFramework="net47" />
  <package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.4.403061554" targetFramework="net46" />
  <package id="Microsoft.IdentityModel.Protocols" version="2.1.5" targetFramework="net47" />
  <package id="Microsoft.IdentityModel.Protocols.OpenIdConnect" version="2.1.5" targetFramework="net47" />
  <package id="Microsoft.IdentityModel.Tokens" version="5.1.5" targetFramework="net47" />
  <package id="Microsoft.Owin" version="3.1.0" targetFramework="net47" />
  <package id="Microsoft.Owin.Security" version="3.1.0" targetFramework="net47" />
  <package id="Microsoft.Rest.ClientRuntime" version="2.3.10" targetFramework="net46" />
  <package id="Microsoft.VisualStudio.SlowCheetah" version="3.0.61" targetFramework="net47" />
  <package id="Microsoft.WindowsAzure.ConfigurationManager" version="3.2.3" targetFramework="net46" />
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="net46" />
  <package id="Owin" version="1.0" targetFramework="net47" />
  <package id="Serilog" version="2.5.0" targetFramework="net47" />
  <package id="Serilog.Sinks.Debug" version="1.0.0" targetFramework="net47" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="net47" />
  <package id="System.IdentityModel.Tokens.Jwt" version="5.1.5" targetFramework="net47" />
</packages>
```

this is the result of my "card.ToJson()" note that it is correctly including my "customType": "MyCard1"

```json
{
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "text": "Sem anuidades e sem taxas escondidas.\r\n\r\n"
    },
    {
      "type": "TextBlock",
      "text": "Que tal abrir a sua conta agora?\r\n\r\n"
    }
  ],
  "actions": [
    {
      "type": "Action.OpenUrl",
      "url": "https://www.teste.com.br/abrirminhaconta",
      "title": "Abrir minha conta"
    },
    {
      "type": "Action.Submit",
      "data": "Voltar",
      "title": "Voltar"
    }
  ],
  "customType": "MyCard1"
}
```

And bellow is the result of the context.PostAsync of the same instance that generated the json above:

```json
{
  "type": "message",
  "id": "3ekexV7XT3V3U0kwRHReZs|0000008",
  "timestamp": "2017-12-01T13:58:32.0581455Z",
  "localTimestamp": "2017-12-01T13:58:30.6059052+00:00",
  "channelId": "directline",
  "from": {
    "id": "Toro",
    "name": "Toro Assistant"
  },
  "conversation": {
    "id": "3ekexV7XT3V3U0kwRHReZs"
  },
  "membersAdded": [],
  "membersRemoved": [],
  "text": "",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "content": {
        "type": "AdaptiveCard",
        "body": [
          {
            "type": "TextBlock",
            "text": "Sem anuidades e sem taxas escondidas.\r\n\r\n"
          },
          {
            "type": "TextBlock",
            "text": "Que tal abrir a sua conta agora?\r\n\r\n"
          }
        ],
        "actions": [
          {
            "type": "Action.OpenUrl",
            "url": "https://www.teste.com.br/abrirminhaconta",
            "title": "Abrir minha conta"
          },
          {
            "type": "Action.Submit",
            "data": "Voltar",
            "title": "Voltar"
          }
        ],
        "version": "1.0"
      }
    }
  ],
  "entities": [],
  "replyToId": "3ekexV7XT3V3U0kwRHReZs|0000007"
}
```

**Comment by ederbond** [comment]
After a few hours debuging I've noticed that my custom properties are being sent to the client correctly. 
As I can see on the Emulator:
![image](https://user-images.githubusercontent.com/12549812/33500389-c71caa06-d6bf-11e7-9257-bcff27a14526.png)


However the [directline-js ](https://github.com/Microsoft/BotFramework-DirectLineJS)lib  It seems to be a problem with the directline-js library...

Take a look at the result of the same dialog redered using the bot emulador vs my custon html chat using [directline js](https://github.com/Microsoft/BotFramework-DirectLineJS)

![image](https://user-images.githubusercontent.com/12549812/33501021-2a2fd904-d6c2-11e7-9854-3d0415a1dab8.png)

**Comment by matthidinger** [comment]
@EricDahlvang any idea here? If it's not a problem in the AdaptiveCards library I'm out of my element I'm afraid.

**Comment by EricDahlvang** [comment]
Hi @ederbond 

This is very odd, since the Emulator uses the WebChat control, and the WebChat control uses the DirectLineJs library.

What is the `context.PostCardAsync(card); ` method you refer to?  This method does not exist in the BotBuilder .net sdk: https://github.com/Microsoft/BotBuilder/search?utf8=✓&q=PostCardAsync

**Comment by ederbond** [comment]
Hello @EricDahlvang,
it's just an extension method I've create as follows:

```csharp
        public static async Task PostCardAsync(this IDialogContext context,  Attachment card)
        {
            var replyMessage = context.MakeMessage();
            replyMessage.Attachments.Add(card);
            var start = DateTime.Now;
            await context.PostAsync(replyMessage);
            var elapsed = DateTime.Now - start;
            if (elapsed.TotalSeconds > 2)
            {
                Log.Logger.Debug($"context.PostCardAsync() took {elapsed}");
            }
        }
```

**Comment by ederbond** [comment]
I'm using this version of DirectlineJs library:
`<script src="http://unpkg.com/botframework-directlinejs/directLine.js"></script>`

**Comment by ederbond** [comment]
![image](https://user-images.githubusercontent.com/12549812/33567566-c0f84412-d90a-11e7-8ba2-8484f3919233.png)

**Comment by EricDahlvang** [comment]
Thanks for bringing this to our attention! 

I spoke with some of the engineers, and it seems the bot connector serialization settings are skipping properties with no public setter.  AdditionalProperties has only a public getter: https://github.com/Microsoft/AdaptiveCards/blob/9a23297a7483b776303dfdc4304c83f968dc63d7/source/dotnet/Library/AdaptiveCards/AdaptiveTypedElement.cs#L32   

I don't have a timeline for you @ederbond, but this should be fixed soon.

**Comment by EricDahlvang** [comment]
@ederbond  Would you please try the new package: https://www.nuget.org/packages/AdaptiveCards/1.0.0-beta10

**Comment by matthidinger** [comment]
Actually the latest is beta11 😀

**Comment by ederbond** [comment]
I've got the same results with beta11, no AdditionalProperties  was returned.
Anyway, it's good to know you guys are aware of this issue and hope you could fix it as soon as possible.
Thanks for the help and congrats for get it evolving so fast.

**Comment by ederbond** [comment]
Hi @matthidinger,
any news on this front ?

**Comment by ederbond** [comment]
Hi @matthidinger, and @EricDahlvang
any news on this front ?

**Comment by EricDahlvang** [comment]
@ederbond Please try now.  

**AdditionalProperties** are coming through:

![image](https://user-images.githubusercontent.com/11055362/35543910-8343bf14-051c-11e8-829f-cbcfff97308e.png)

**Comment by ederbond** [comment]
Now it is working. 
Thank you guys.
