### ISSUE TITLE
Right-to-Left languages support

### ISSUE THREAD

**Issue by synk** [microsoft/AdaptiveCards#999]
The default value of `horizontalAlignment`should be `start` so that it is determined by the language's nature. 

https://github.com/Microsoft/AdaptiveCards/blob/04a96748495e9be564ade97617f84143b81d387b/source/nodejs/adaptivecards/src/card-elements.ts#L405-L415

**Comment by dclaux** [comment]
Not sure that's the right model. There is a right and a left in all languages, including RtL ones, and designers might want to align something right regardless of the fact that a card language might be in an RtL language. I think the right thing to do is add another property dedicated to RtL support.
